
/*
 * Copyright 2012, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Additional Licenses for Third Party components can be found here:
 * http://wiki.freebase.com/wiki/Freebase_Site_License
 *
 */
/*
 
 jQuery Tools @VERSION / Expose - Dim the lights

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/toolbox/expose.html

 Since: Mar 2010
 Date: @DATE 
 
 jQuery Tools @VERSION Overlay - Overlay base. Extend it.

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/overlay/

 Since: March 2008
 Date: @DATE 
*/
(function(b){function g(){if(b.browser.msie){var a=b(document).height(),d=b(window).height();return[window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth,20>a-d?d:a]}return[b(document).width(),b(document).height()]}function f(a){if(a)return a.call(b.mask)}b.tools=b.tools||{version:"@VERSION"};var e;e=b.tools.expose={conf:{maskId:"exposeMask",loadSpeed:"slow",closeSpeed:"fast",closeOnClick:!0,closeOnEsc:!0,zIndex:9998,opacity:0.8,startOpacity:0,color:"#fff",onLoad:null,
onClose:null}};var c,a,d,h,o;b.mask={load:function(i,j){if(d)return this;"string"==typeof i&&(i={color:i});i=i||h;h=i=b.extend(b.extend({},e.conf),i);c=b("#"+i.maskId);c.length||(c=b("<div/>").attr("id",i.maskId),b("body").append(c));var k=g();c.css({position:"absolute",top:0,left:0,width:k[0],height:k[1],display:"none",opacity:i.startOpacity,zIndex:i.zIndex});i.color&&c.css("backgroundColor",i.color);if(!1===f(i.onBeforeLoad))return this;i.closeOnEsc&&b(document).bind("keydown.mask",function(a){a.keyCode==
27&&b.mask.close(a)});i.closeOnClick&&c.bind("click.mask",function(a){b.mask.close(a)});b(window).bind("resize.mask",function(){b.mask.fit()});j&&j.length&&(o=j.eq(0).css("zIndex"),b.each(j,function(){var a=b(this);/relative|absolute|fixed/i.test(a.css("position"))||a.css("position","relative")}),a=j.css({zIndex:Math.max(i.zIndex+1,"auto"==o?0:o)}));c.css({display:"block"}).fadeTo(i.loadSpeed,i.opacity,function(){b.mask.fit();f(i.onLoad)});d=!0;return this},close:function(){if(d){if(!1===f(h.onBeforeClose))return this;
c.fadeOut(h.closeSpeed,function(){f(h.onClose);a&&a.css({zIndex:o})});b(document).unbind("keydown.mask");c.unbind("click.mask");b(window).unbind("resize.mask");d=!1}return this},fit:function(){if(d){var a=g();c.css({width:a[0],height:a[1]})}},getMask:function(){return c},isLoaded:function(){return d},getConf:function(){return h},getExposed:function(){return a}};b.fn.mask=function(a){b.mask.load(a);return this};b.fn.expose=function(a){b.mask.load(a,this);return this}})(jQuery);
(function(b){function g(c,a){var d=this,h=c.add(d),g=b(window),i,j,k,m=b.tools.expose&&(a.mask||a.expose),n=Math.random().toString().slice(10);m&&("string"==typeof m&&(m={color:m}),m.closeOnClick=m.closeOnEsc=!1);var l=a.target||c.attr("rel");j=l?b(l):c;if(!j.length)throw"Could not find Overlay: "+l;c&&-1==c.index(j)&&c.click(function(a){d.load(a);return a.preventDefault()});b.extend(d,{load:function(c){if(d.isOpened())return d;var i=e[a.effect];if(!i)throw'Overlay: cannot find effect : "'+a.effect+
'"';a.oneInstance&&b.each(f,function(){this.close(c)});c=c||b.Event();c.type="onBeforeLoad";h.trigger(c);if(c.isDefaultPrevented())return d;k=true;m&&b(j).expose(m);var l=a.top,p=a.left,s=j.outerWidth({margin:true}),q=j.outerHeight({margin:true});typeof l=="string"&&(l=l=="center"?Math.max((g.height()-q)/2,0):parseInt(l,10)/100*g.height());p=="center"&&(p=Math.max((g.width()-s)/2,0));i[0].call(d,{top:l,left:p},function(){if(k){c.type="onLoad";h.trigger(c)}});if(m&&a.closeOnClick)b.mask.getMask().one("click",
d.close);a.closeOnClick&&b(document).bind("click."+n,function(a){b(a.target).parents(j).length||d.close(a)});a.closeOnEsc&&b(document).bind("keydown."+n,function(a){a.keyCode==27&&d.close(a)});return d},close:function(c){if(!d.isOpened())return d;c=c||b.Event();c.type="onBeforeClose";h.trigger(c);if(!c.isDefaultPrevented()){k=false;e[a.effect][1].call(d,function(){c.type="onClose";h.trigger(c)});b(document).unbind("click."+n).unbind("keydown."+n);m&&b.mask.close();return d}},getOverlay:function(){return j},
getTrigger:function(){return c},getClosers:function(){return i},isOpened:function(){return k},getConf:function(){return a}});b.each(["onBeforeLoad","onStart","onLoad","onBeforeClose","onClose"],function(c,h){b.isFunction(a[h])&&b(d).bind(h,a[h]);d[h]=function(a){b(d).bind(h,a);return d}});i=j.find(a.close||".close");!i.length&&!a.close&&(i=b('<a class="close"></a>'),j.prepend(i));i.click(function(a){d.close(a)});a.load&&d.load()}b.tools=b.tools||{version:"@VERSION"};b.tools.overlay={addEffect:function(b,
a,d){e[b]=[a,d]},conf:{close:null,closeOnClick:!0,closeOnEsc:!0,closeSpeed:"fast",effect:"default",fixed:!b.browser.msie||6<b.browser.version,left:"center",load:!1,mask:null,oneInstance:!0,speed:"normal",target:null,top:"10%"}};var f=[],e={};b.tools.overlay.addEffect("default",function(c,a){var d=this.getConf(),h=b(window);d.fixed||(c.top+=h.scrollTop(),c.left+=h.scrollLeft());c.position=d.fixed?"fixed":"absolute";this.getOverlay().css(c).fadeIn(d.speed,a)},function(b){this.getOverlay().fadeOut(this.getConf().closeSpeed,
b)});b.fn.overlay=function(c){var a=this.data("overlay");if(a)return a;b.isFunction(c)&&(c={onBeforeLoad:c});c=b.extend(!0,{},b.tools.overlay.conf,c);this.each(function(){a=new g(b(this),c);f.push(a);b(this).data("overlay",a)});return c.api?a:this}})(jQuery);
(function(b){var g="undefined"!=typeof window.innerWidth?function(){return{w:window.innerWidth,h:window.innerHeight}}:"undefined"!=typeof document.documentElement&&"undefined"!=typeof document.documentElement.clientWidth&&0!=document.documentElement.clientWidth?function(){return{w:document.documentElement.clientWidth,h:document.documentElement.clientHeight}}:function(){return{w:document.getElementsByTagName("body")[0].clientWidth,h:document.getElementsByTagName("body")[0].clientHeight}};window.kbs=
function(f){b(".kbs.current",f).removeClass("current");var e=b(".domain-section:first",f),c=b(".domain-section:last",f),a=this.scroll_to=function(a){var d=b(document).scrollTop();b(document).height();var h=g().h,h=d+h,c=a.offset().top,a=c+a.height();c<d?b(document).scrollTop(c):a>h&&b(document).scrollTop(d+(a-h))},d=this.get_current=function(){return b(".kbs.current:first",f)},h=this.set_next=function(t,b,h){t=t||d();b.length&&(t.removeClass("current"),b.addClass("current"),h||a(b))},o=this.next_domain=
function(a){var b=d(),c=i(b);c&&(c=c.find(".kbs:first"),h(b,c,a))},i=this._next_domain=function(a){if(!a||!a.length)return b(".domain-section:first",f);a=a.closest(".domain-section");return!a.length||a[0]===c[0]?e:a.next(".domain-section")},j=this.prev_domain=function(){var a=d(),b=k(a);b&&(b=b.find(".kbs:first"),h(a,b))},k=this._prev_domain=function(a){if(!a||!a.length)return b(".domain-section:last",f);var d=a.closest(".domain-section");return a.closest(".property-section").length||a.closest(".type-section").length?
d:!d.length||d[0]===e[0]?c:d.prev(".domain-section")},m=this.next_type=function(){var a=d(),b=n(a);b&&(b=b.find(".kbs:first"),h(a,b))},n=this._next_type=function(a){if(!a||!a.length)return b(".type-section:first",f);var d=a.closest(".domain-section"),a=a.closest(".type-section"),a=a.length?a.next(".type-section"):d.find(".type-section:first");if(!a||!a.length){var c=i(d);if(c)for(;c.get(0)!==d.get(0);){a=c.find(".type-section:first");if(a.length)break;c=i(c)}}return a},l=this.prev_type=function(){var a=
d(),b=r(a);b&&(b=b.find(".kbs:first"),h(a,b))},r=this._prev_type=function(a){if(!a||!a.length)return b(".type-section:last",f);var d=a.closest(".domain-section"),c=a.closest(".type-section");if(a.closest(".property-section").length)return c;var h;c.length&&(h=c.prev(".type-section"));if(!h||!h.length)if(a=k(d))for(;a.get(0)!==d.get(0);){h=a.find(".type-section:last");if(h.length)break;a=k(a)}return h},u=this.next_prop=function(){var a=d(),b=v(a);b&&(b=b.find(".kbs:first"),h(a,b))},v=this._next_prop=
function(a){if(!a||!a.length)return b(".property-section:first",f);var d=a.closest(".domain-section"),c=a.closest(".type-section"),h=a.closest(".property-section"),d=h.length?h.next(".property-section"):c.length?c.find(".property-section:first"):d.find(".property-section:first");if(!d||!d.length)if(a=n(a))for(;a.get(0)!==c.get(0);){d=a.find(".property-section:first");if(d.length)break;null==c.get(0)&&(c=a);a=n(a)}return d},p=this.prev_prop=function(){var a=d(),b=s(a);b&&(b=b.find(".kbs:first"),h(a,
b))},s=this._prev_prop=function(a){if(!a||!a.length)return b(".property-section:last",f);var d=a.closest(".domain-section"),c=a.closest(".type-section"),h=a.closest(".property-section");if(a.closest(".data-section").length)return h;var e;h.length&&(e=h.prev(".property-section"));if(!e||!e.length)if(l=c.length?r(c):r(d))for(;l.get(0)!==c.get(0);){e=l.find(".property-section:last");if(e.length)break;null==c.get(0)&&(c=l);l=r(l)}return e};this.next=function(){var a=d();if(a&&a.length){var c=this._next(a);
if(c){h(a,c);return}}a=b(".kbs:visible:first",f);h(a,a)};this._next=function(a){if(!a||!a.length)return b(".domain-section:first .kbs:first",f);var d=a.closest(".domain-section"),h=a.closest(".type-section"),g=a.closest(".property-section");if(a.closest(".data-section").length){a=a.next(".kbs");if(a.length)return a;a=g.next(".property-section").find(".kbs:first");if(a.length)return a;a=h.next(".type-section").find(".kbs:first")}else if(g.length){a=g.find(".data-section:first .kbs:first");if(a.length)return a;
a=g.next(".property-section").find(".kbs:first");if(a.length)return a;a=h.next(".type-section").find(".kbs:first")}else if(h.length){a=h.find(".property-section:first .kbs:first");if(a.length)return a;a=h.next(".type-section").find(".kbs:first")}else a=d.find(".type-section:first .kbs:first");return a.length?a:d.get(0)===c.get(0)?e.find(".kbs:first"):d.next(".domain-section").find(".kbs:first")};this.prev=function(){var a=d(),b=this._prev(a);b&&h(a,b)};this._prev=function(a){if(!a||!a.length)return a=
b(".data-section:last .kbs:last",f),a.length||(a=b(".property-section:last .kbs:first",f)),a.length||(a=b(".type-section:last .kbs:first",f)),a.length||(a=b(".domain-section:last .kbs:first",f)),a;var d=a.closest(".domain-section"),h=a.closest(".type-section"),g=a.closest(".property-section");return a.closest(".data-section").length?(a=a.prev(".kbs"),a.length?a:g.find(".kbs:first")):g.length?(a=g.prev(".property-section").find(".kbs:last"),a.length?a:h.find(".kbs:first")):h.length?(a=h.prev(".type-section").find(".kbs:last"),
a.length?a:d.find(".kbs:first")):d.get(0)===e.get(0)?c.find(".kbs:last"):d.prev(".domain-section").find(".kbs:last")};this.edit=function(){this.get_current().trigger("edit")};var q=this;b(document).unbind(".kbs").bind("keydown.kbs",function(a){var d=a.target;if(d==document.body||d==document||d==window||d==b("html")[0])d=a.keyCode,68===d?a.shiftKey?j():o():84===d?a.shiftKey?l():m():80===d?a.shiftKey?p():u():74===d?q.next():75===d?q.prev():69===d&&q.edit()})}})(jQuery);
(function(b,g){var f=window.propbox={init:function(e,c){c=b.extend({lang:"/lang/en"},c);if(!c.base_ajax_url)throw Error("base_ajax_url required in propbox options");if(!c.base_static_url)throw Error("base_static_url required in propbox options");if(!c.id)throw Error("topic id required in propbox options");if(!c.lang)throw Error("lang required in propbox options");f.options=c;f.kbs=new g(e);b(".kbs",e).live("click",function(){var a=f.kbs.get_current();f.kbs.set_next(a,b(this),!0)}).live("edit",function(){var a=
b(this).find(".headmenu:first").data("submenu");a&&b("li:first a:first",a).click()});f.init_menus(e)},init_menus:function(e,c){e=b(e||document);c&&b(".nicemenu",e).nicemenu();var a;a=e&&e.is(".hover-row")?e:b(".hover-row",e);a.hover(f.row_menu_hoverover,f.row_menu_hoverout);a.dblclick(function(){var a=b(".nicemenu .default-action",this);a.length||(a=b(".nicemenu:first .submenu:first a:first",this));var c=a.attr("href");("#"==c||0==c.indexOf("javascript:void(0)"))&&b(a).click()});b(".nicemenu .headmenu",
e).add(b(".nicemenu .default-action",e)).click("click",function(){if(f.kbs){var a=f.kbs.get_current();a&&f.kbs.set_next(a,b(this).parents(".kbs:first"),!0)}return!1})},row_menu_hoverover:function(){b(this).addClass("row-hover")},row_menu_hoverout:function(){b(this).removeClass("row-hover")},get_script:function(e,c){var a=f.get_script.cache;a||(a=f.get_script.cache={});var d=a[e];d?1===d.state?d.callbacks.push(c):4===d.state&&c():(d=a[e]={state:0,callbacks:[c]},b.ajax({url:f.options.base_static_url+
e,dataType:"script",beforeSend:function(){d.state=1},success:function(){d.state=4;b.each(d.callbacks,function(a,d){d()})},error:function(){d.state=-1}}))},prop_edit:function(e,c){var a=b(e).parents(".property-section");a.length||(a=b(e).parents(".submenu").data("headmenu").parents(".property-section"));a=a.find(".data-section .data-row:first:visible .nicemenu:first .headmenu:first a");a.length?a.click():f.prop_add(e,c);return!1},prop_add:function(e,c){var a=b(e).parents(".property-section");a.length||
(a=b(e).parents(".submenu").data("headmenu").parents(".property-section"));f.get_script("/propbox-edit.mf.js",function(){f.edit.prop_add_begin(a,c)});return!1},value_edit:function(e){var c=b(e).parents(".submenu").data("headmenu").parents(".data-row:first"),a=c.parents(".property-section");f.get_script("/propbox-edit.mf.js",function(){f.edit.value_edit_begin(a,c)});return!1},value_delete:function(e){var c=b(e).parents(".submenu").data("headmenu").parents(".data-row:first"),a=c.parents(".property-section");
f.get_script("/propbox-edit.mf.js",function(){f.edit.value_delete_begin(a,c)});return!1},remove_type:function(e){var e=b(e),c=e.parents(".type-section");f.get_script("/propbox-edit.mf.js",function(){f.edit.remove_type_begin(e,c)});return!1},add_type:function(e,c,a){var e=b(e),d=e.parents(".type-section"),h=f.options.incompatible_types;h?h.search(f.options.id,c,a,{compatible:function(){f.add_type_submit(e,d)},incompatible:h.overlay_incompatible_callback({onConfirm:function(){f.add_type_submit(e,d)}})}):
f.add_type_submit(e,d);return!1},add_type_submit:function(b,c){f.get_script("/propbox-edit.mf.js",function(){f.edit.add_type_submit(b,c)})},add_has_no_value:function(e){var c=b(e).parents(".submenu").data("headmenu").parents(".property-section");f.get_script("/propbox-edit.mf.js",function(){f.edit.add_has_no_value(c)});return!1},add_has_value:function(e){var c=b(e).parents(".submenu").data("headmenu").parents(".property-section");f.get_script("/propbox-edit.mf.js",function(){f.edit.add_has_value(c)});
return!1},remove_has_no_value:function(e){var c=b(e).parents(".property-section");f.get_script("/propbox-edit.mf.js",function(){f.edit.remove_has_no_value(c)});return!1},remove_has_value:function(e){var c=b(e).parents(".property-section");f.get_script("/propbox-edit.mf.js",function(){f.edit.remove_has_value(c)});return!1},more:function(e,c,a){var d=b(e).parents(".property-section");f.get_script("/propbox-edit.mf.js",function(){f.edit.more(d,c,a)})}}})(jQuery,window.kbs);
(function(b,g,f){g.infinitescroll=function(a,d,b){this.element=g(b);this._create(a,d)};g.infinitescroll.defaults={loading:{finished:f,finishedMsg:"<em>Congratulations, you've reached the end of the internet.</em>",img:"http://www.infinite-scroll.com/loading.gif",msg:null,msgText:"<em>Loading the next set of posts...</em>",selector:null,speed:"fast",start:f},state:{isDuringAjax:!1,isInvalidPage:!1,isDestroyed:!1,isDone:!1,isPaused:!1,currPage:1},callback:f,debug:!1,behavior:f,binder:g(b),nextSelector:"div.navigation a:first",
navSelector:"div.navigation",contentSelector:null,extraScrollPx:150,itemSelector:"div.post",animate:!1,pathParse:f,dataType:"html",appendCallback:!0,bufferPx:40,errorCallback:function(){},infid:0,pixelsFromNavToBottom:f,path:f};g.infinitescroll.prototype={_binding:function(a){var d=this,b=d.options;if(b.behavior&&this["_binding_"+b.behavior]!==f)this["_binding_"+b.behavior].call(this);else{if("bind"!==a&&"unbind"!==a)return this._debug("Binding value  "+a+" not valid"),!1;if("unbind"==a)this.options.binder.unbind("smartscroll.infscr."+
d.options.infid);else this.options.binder[a]("smartscroll.infscr."+d.options.infid,function(){d.scroll()});this._debug("Binding",a)}},_create:function(a,d){if(!this._validate(a))return!1;var b=this.options=g.extend(!0,{},g.infinitescroll.defaults,a),c=g(b.nextSelector).attr("href");b.contentSelector=b.contentSelector||this.element;b.loading.selector=b.loading.selector||b.contentSelector;c?(b.path=this._determinepath(c),b.loading.msg=g('<div id="infscr-loading"><img alt="Loading..." src="'+b.loading.img+
'" /><div>'+b.loading.msgText+"</div></div>"),(new Image).src=b.loading.img,b.pixelsFromNavToBottom=g(document).height()-g(b.navSelector).offset().top,b.loading.start=b.loading.start||function(){g(b.navSelector).hide();b.loading.msg.appendTo(b.loading.selector).show(b.loading.speed,function(){beginAjax(b)})},b.loading.finished=b.loading.finished||function(){b.loading.msg.fadeOut("normal")},b.callback=function(a,c){b.behavior&&a["_callback_"+b.behavior]!==f&&a["_callback_"+b.behavior].call(g(b.contentSelector)[0],
c);d&&d.call(g(b.contentSelector)[0],c)},this._setup()):this._debug("Navigation selector not found")},_debug:function(){if(this.options.debug)return b.console&&console.log.call(console,arguments)},_determinepath:function(a){var b=this.options;if(b.behavior&&this["_determinepath_"+b.behavior]!==f)this["_determinepath_"+b.behavior].call(this,a);else{if(b.pathParse)return this._debug("pathParse manual"),"function"===typeof b.pathParse?b.pathParse():b.pathParse;if(a.match(/^(.*?)\b2\b(.*?$)/))a=a.match(/^(.*?)\b2\b(.*?$)/).slice(1);
else if(a.match(/^(.*?)2(.*?$)/)){if(a.match(/^(.*?page=)2(\/.*|$)/))return a=a.match(/^(.*?page=)2(\/.*|$)/).slice(1);a=a.match(/^(.*?)2(.*?$)/).slice(1)}else{if(a.match(/^(.*?page=)1(\/.*|$)/))return a=a.match(/^(.*?page=)1(\/.*|$)/).slice(1);this._debug("Sorry, we couldn't parse your Next (Previous Posts) URL. Verify your the css selector points to the correct A tag. If you still get this error: yell, scream, and kindly ask for help at infinite-scroll.com.");b.state.isInvalidPage=!0}this._debug("determinePath",
a);return a}},_error:function(a){var b=this.options;b.behavior&&this["_error_"+b.behavior]!==f?this["_error_"+b.behavior].call(this,a):("destroy"!==a&&"end"!==a&&(a="unknown"),this._debug("Error",a),"end"==a&&this._showdonemsg(),b.state.isDone=!0,b.state.currPage=1,b.state.isPaused=!1,this._binding("unbind"))},_loadcallback:function(a,d){var c=this.options,e=this.options.callback,i=c.state.isDone?"done":!c.appendCallback?"no-append":"append";if(c.behavior&&this["_loadcallback_"+c.behavior]!==f)this["_loadcallback_"+
c.behavior].call(this,a,d);else{switch(i){case "done":return this._showdonemsg(),!1;case "no-append":"html"==c.dataType&&(d=g("<div>"+d+"</div>").find(c.itemSelector));break;case "append":var j=a.children();if(0==j.length)return this._error("end");for(i=document.createDocumentFragment();a[0].firstChild;)i.appendChild(a[0].firstChild);this._debug("contentSelector",g(c.contentSelector)[0]);g(c.contentSelector)[0].appendChild(i);d=j.get()}c.loading.finished.call(g(c.contentSelector)[0],c);c.animate&&
(i=g(b).scrollTop()+g("#infscr-loading").height()+c.extraScrollPx+"px",g("html,body").animate({scrollTop:i},800,function(){c.state.isDuringAjax=!1}));c.animate||(c.state.isDuringAjax=!1);e(this,d)}},_nearbottom:function(){var a=this.options,d=0+g(document).height()-a.binder.scrollTop()-g(b).height();if(a.behavior&&this["_nearbottom_"+a.behavior]!==f)this["_nearbottom_"+a.behavior].call(this);else return this._debug("math:",d,a.pixelsFromNavToBottom),d-a.bufferPx<a.pixelsFromNavToBottom},_pausing:function(a){var b=
this.options;if(b.behavior&&this["_pausing_"+b.behavior]!==f)this["_pausing_"+b.behavior].call(this,a);else{"pause"!==a&&("resume"!==a&&null!==a)&&this._debug("Invalid argument. Toggling pause value instead");switch(a&&("pause"==a||"resume"==a)?a:"toggle"){case "pause":b.state.isPaused=!0;break;case "resume":b.state.isPaused=!1;break;case "toggle":b.state.isPaused=!b.state.isPaused}this._debug("Paused",b.state.isPaused);return!1}},_setup:function(){var a=this.options;if(a.behavior&&this["_setup_"+
a.behavior]!==f)this["_setup_"+a.behavior].call(this);else return this._binding("bind"),!1},_showdonemsg:function(){var a=this.options;a.behavior&&this["_showdonemsg_"+a.behavior]!==f?this["_showdonemsg_"+a.behavior].call(this):(a.loading.msg.find("img").hide().parent().find("div").html(a.loading.finishedMsg).animate({opacity:1},2E3,function(){g(this).parent().fadeOut("normal")}),a.errorCallback.call(g(a.contentSelector)[0],"done"))},_validate:function(a){for(var b in a)return b.indexOf&&-1<b.indexOf("Selector")&&
0===g(a[b]).length?(this._debug("Your "+b+" found no elements."),!1):!0},bind:function(){this._binding("bind")},destroy:function(){this.options.state.isDestroyed=!0;return this._error("destroy")},pause:function(){this._pausing("pause")},resume:function(){this._pausing("resume")},retrieve:function(a){var b=this,c=b.options,e=this._determinepath(e),i,j,k,m,a=a||null;beginAjax=function(a){a.state.currPage++;b._debug("heading into ajax",e);i=g(a.contentSelector).is("table")?g("<tbody/>"):g("<div/>");
j=e.join(a.state.currPage);k="html"==a.dataType||"json"==a.dataType?a.dataType:"html+callback";a.appendCallback&&"html"==a.dataType&&(k+="+callback");switch(k){case "html+callback":b._debug("Using HTML via .load() method");i.load(j+" "+a.itemSelector,null,function(a){b._loadcallback(i,a)});break;case "html":case "json":b._debug("Using "+k.toUpperCase()+" via $.ajax() method"),g.ajax({url:j,dataType:a.dataType,complete:function(a,c){(m="undefined"!==typeof a.isResolved?a.isResolved():"success"===c||
"notmodified"===c)?b._loadcallback(i,a.responseText):b._error("end")}})}};if(c.behavior&&this["retrieve_"+c.behavior]!==f)this["retrieve_"+c.behavior].call(this,a);else{if(c.state.isDestroyed)return this._debug("Instance is destroyed"),!1;c.state.isDuringAjax=!0;c.loading.start.call(g(c.contentSelector)[0],c)}},scroll:function(){var a=this.options,b=a.state;a.behavior&&this["scroll_"+a.behavior]!==f?this["scroll_"+a.behavior].call(this):!b.isDuringAjax&&!b.isInvalidPage&&!b.isDone&&!b.isDestroyed&&
!b.isPaused&&this._nearbottom()&&this.retrieve()},toggle:function(){this._pausing()},unbind:function(){this._binding("unbind")},update:function(a){g.isPlainObject(a)&&(this.options=g.extend(!0,this.options,a))}};g.fn.infinitescroll=function(a,b){switch(typeof a){case "string":var c=Array.prototype.slice.call(arguments,1);this.each(function(){var b=g.data(this,"infinitescroll");if(!b||!g.isFunction(b[a])||"_"===a.charAt(0))return!1;b[a].apply(b,c)});break;case "object":this.each(function(){var c=g.data(this,
"infinitescroll");c?c.update(a):g.data(this,"infinitescroll",new g.infinitescroll(a,b,this))})}return this};var e=g.event,c;e.special.smartscroll={setup:function(){g(this).bind("scroll",e.special.smartscroll.handler)},teardown:function(){g(this).unbind("scroll",e.special.smartscroll.handler)},handler:function(a,b){var e=this,f=arguments;a.type="smartscroll";c&&clearTimeout(c);c=setTimeout(function(){g.event.handle.apply(e,f)},"execAsap"===b?0:100)}};g.fn.smartscroll=function(a){return a?this.bind("smartscroll",
a):this.trigger("smartscroll",["execAsap"])}})(window,jQuery);
(function(b,g){var f=g.collection={init_infinitescroll:function(){var e=b("#infinitescroll"),c=e.attr("data-next");if(c&&"false"!==c){var a=b("#infinitescroll-next");e.infinitescroll({loading:{msgText:"Fetching more topics",img:g.h.static_url("lib/template/img/horizontal-loader.gif")},nextSelector:"#infinitescroll-next",navSelector:"#infinitescroll-next",dataType:"json",pathParse:function(){return[a[0].href+"&"+b.param({cursor:e.attr("data-next")})+"&page=",""]},appendCallback:!1},function(a){var a=
JSON.parse(a),c=a.result.cursor,a=b(a.result.html);f.init_menus(a);f.load_blurbs(a);e.append(a);c?e.attr("data-next",c):b(window).unbind(".infscr")});setTimeout(function(){b(window).trigger("scroll")})}},init_menus:function(e,c){e=b(e||document);c&&b(".nicemenu",e).nicemenu();(e&&e.is(".data-row")?e:b(".data-row",e)).hover(f.row_menu_hoverover,f.row_menu_hoverout);b(".nicemenu .headmenu",e).add(b(".nicemenu .default-action",e))},load_blurbs:function(e){b(".load-blurb",e).each(function(c,a){var d=
[g.acre.freebase.googleapis_url,"/text",b(a).attr("data-id"),"?key=",g.acre.freebase.api_key].join("");b.getJSON(d,function(c){c=c.result.split(/\s+/);b(a).text(c.slice(0,30).join(" "))})})},row_menu_hoverover:function(){var e=b(this);f.row_menu_hoverover.timeout=setTimeout(function(){e.addClass("row-hover")},300)},row_menu_hoverout:function(){clearTimeout(f.row_menu_hoverover.timeout);b(this).removeClass("row-hover")},row_edit:function(e){var c=b(e).parents(".submenu").data("headmenu").parents(".data-row:first");
g.get_script(g.h.ajax_url("lib/collection/collection-edit.mf.js"),function(){f.edit.row_edit_begin(c)});return!1},init:function(){f.init_infinitescroll();f.init_menus();f.load_blurbs();return f}};f.init()})(jQuery,window.freebase);
