
/*
 * Copyright 2012, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Additional Licenses for Third Party components can be found here:
 * http://wiki.freebase.com/wiki/Freebase_Site_License
 *
 */
/*
 
 jQuery Tools @VERSION Tooltip - UI essentials

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/tooltip/

 Since: November 2008
 Date: @DATE 
*/
(function(c){c.extend({tablesorter:new function(){function b(a,c){g(a+","+((new Date).getTime()-c.getTime())+"ms")}function g(a){"undefined"!=typeof console&&"undefined"!=typeof console.debug?console.log(a):alert(a)}function h(b,e){var h="";if(0!=b.tBodies.length){var d=b.tBodies[0].rows;if(d[0])for(var i=[],s=d[0].cells.length,t=0;t<s;t++){var q=!1;c.metadata&&c(e[t]).metadata()&&c(e[t]).metadata().sorter?q=a(c(e[t]).metadata().sorter):b.config.headers[t]&&b.config.headers[t].sorter&&(q=a(b.config.headers[t].sorter));
if(!q)a:{for(var q=b,k=d,l=-1,r=t,p=n.length,j=!1,o=!1,u=!0;""==o&&u;)l++,k[l]?(j=k[l].cells[r],o=c.trim(f(q.config,j)),q.config.debug&&g("Checking if value was empty on row:"+l)):u=!1;for(k=1;k<p;k++)if(n[k].is(o,q,j)){q=n[k];break a}q=n[0]}b.config.debug&&(h+="column:"+t+" parser:"+q.id+"\n");i.push(q)}b.config.debug&&g(h);return i}}function a(a){for(var c=n.length,b=0;b<c;b++)if(n[b].id.toLowerCase()==a.toLowerCase())return n[b];return!1}function e(a){var e;a.config.debug&&(e=new Date);for(var h=
a.tBodies[0]&&a.tBodies[0].rows.length||0,g=a.tBodies[0].rows[0]&&a.tBodies[0].rows[0].cells.length||0,i=a.config.parsers,s={row:[],normalized:[]},d=0;d<h;++d){var q=c(a.tBodies[0].rows[d]),k=[];if(q.hasClass(a.config.cssChildRow))s.row[s.row.length-1]=s.row[s.row.length-1].add(q);else{s.row.push(q);for(var l=0;l<g;++l)k.push(i[l].format(f(a.config,q[0].cells[l]),a,q[0].cells[l]));k.push(s.normalized.length);s.normalized.push(k)}}a.config.debug&&b("Building cache for "+h+" rows:",e);return s}function f(a,
b){var e="";if(!b)return"";a.supportsTextContent||(a.supportsTextContent=b.textContent||!1);return e="simple"==a.textExtraction?a.supportsTextContent?b.textContent:b.childNodes[0]&&b.childNodes[0].hasChildNodes()?b.childNodes[0].innerHTML:b.innerHTML:"function"==typeof a.textExtraction?a.textExtraction(b):c(b).text()}function d(a,e){var h;a.config.debug&&(h=new Date);for(var f=e.row,i=e.normalized,s=i.length,g=i[0].length-1,k=c(a.tBodies[0]),l=[],r=0;r<s;r++){var j=i[r][g];l.push(f[j]);if(!a.config.appender)for(var o=
f[j].length,n=0;n<o;n++)k[0].appendChild(f[j][n])}a.config.appender&&a.config.appender(a,l);l=null;a.config.debug&&b("Rebuilt table:",h);p(a);setTimeout(function(){c(a).trigger("sortEnd")},0)}function l(a,b){return a.config.headers[b]&&a.config.headers[b].lockedOrder?a.config.headers[b].lockedOrder:!1}function p(a){for(var b=a.config.widgets,c=b.length,e=0;e<c;e++)o(b[e]).format(a)}function o(a){for(var b=u.length,c=0;c<b;c++)if(u[c].id.toLowerCase()==a.toLowerCase())return u[c]}function x(a,b,e,
h){b.removeClass(h[0]).removeClass(h[1]);var i=[];b.each(function(){this.sortDisabled||(i[this.column]=c(this))});a=e.length;for(b=0;b<a;b++)i[e[b][0]].addClass(h[e[b][1]])}function r(a,c,e){var h,i;a.config.debug&&(h=new Date);var f="var sortWrapper = function(a,b) {",g=c.length;for(i=0;i<g;i++)var d=c[i][0],k=c[i][1],d="text"==a.config.parsers[d].type?0==k?j("text","asc",d):j("text","desc",d):0==k?j("numeric","asc",d):j("numeric","desc",d),l="e"+i,f=f+("var "+l+" = "+d),f=f+("if("+l+") { return "+
l+"; } "),f=f+"else { ";i=e.normalized[0].length-1;f+="return a["+i+"]-b["+i+"];";for(i=0;i<g;i++)f+="}; ";f+="return 0; }; ";a.config.debug&&b("Evaling expression:"+f,new Date);eval(f);e.normalized.sort(sortWrapper);a.config.debug&&b("Sorting on "+c.toString()+" and dir "+k+" time:",h);return e}function j(a,b,c){var e="a["+c+"]",c="b["+c+"]";if("text"==a&&"asc"==b)return"("+e+" == "+c+" ? 0 : ("+e+" === null ? Number.POSITIVE_INFINITY : ("+c+" === null ? Number.NEGATIVE_INFINITY : ("+e+" < "+c+") ? -1 : 1 )));";
if("text"==a&&"desc"==b)return"("+e+" == "+c+" ? 0 : ("+e+" === null ? Number.POSITIVE_INFINITY : ("+c+" === null ? Number.NEGATIVE_INFINITY : ("+c+" < "+e+") ? -1 : 1 )));";if("numeric"==a&&"asc"==b)return"("+e+" === null && "+c+" === null) ? 0 :("+e+" === null ? Number.POSITIVE_INFINITY : ("+c+" === null ? Number.NEGATIVE_INFINITY : "+e+" - "+c+"));";if("numeric"==a&&"desc"==b)return"("+e+" === null && "+c+" === null) ? 0 :("+e+" === null ? Number.POSITIVE_INFINITY : ("+c+" === null ? Number.NEGATIVE_INFINITY : "+
c+" - "+e+"));"}var n=[],u=[];this.defaults={cssHeader:"header",cssAsc:"headerSortUp",cssDesc:"headerSortDown",cssChildRow:"expand-child",sortInitialOrder:"asc",sortMultiSortKey:"shiftKey",sortForce:null,sortAppend:null,sortLocaleCompare:!0,textExtraction:"simple",parsers:{},widgets:[],widgetZebra:{css:["even","odd"]},headers:{},widthFixed:!1,cancelSelection:!0,sortList:[],headerList:[],dateFormat:"us",decimal:"/.|,/g",onRenderHeader:null,selectorHeaders:"thead th",debug:!1};this.benchmark=b;this.construct=
function(a){return this.each(function(){if(this.tHead&&this.tBodies){var v,j,m;this.config={};m=c.extend(this.config,c.tablesorter.defaults,a);v=c(this);c.data(this,"tablesorter",m);var i=this,s;i.config.debug&&(s=new Date);for(var t=[],q={},n=i.getElementsByTagName("THEAD")[0].getElementsByTagName("TR"),u=0;u<n.length;u++)for(var G=n[u].cells,D=0;D<G.length;D++){var A=G[D],z=A.parentNode.rowIndex,E=z+"-"+A.cellIndex,K=A.rowSpan||1,A=A.colSpan||1,C;"undefined"==typeof t[z]&&(t[z]=[]);var w;for(w=
0;w<t[z].length+1;w++)if("undefined"==typeof t[z][w]){C=w;break}q[E]=C;for(w=z;w<z+K;w++){"undefined"==typeof t[w]&&(t[w]=[]);for(var E=t[w],F=C;F<C+A;F++)E[F]="x"}}var B=c(i.config.selectorHeaders,i).each(function(a){this.column=q[this.parentNode.rowIndex+"-"+this.cellIndex];this.count=this.order="Number"!=typeof i.config.sortInitialOrder?"desc"==i.config.sortInitialOrder.toLowerCase()?1:0:1==i.config.sortInitialOrder?1:0;if(c.metadata&&!1===c(this).metadata().sorter||i.config.headers[a]&&!1===i.config.headers[a].sorter)this.sortDisabled=
!0;l(i,a)&&(this.order=this.lockedOrder=l(i,a));if(!this.sortDisabled){var b=c(this).addClass(i.config.cssHeader);i.config.onRenderHeader&&i.config.onRenderHeader.apply(b)}i.config.headerList[a]=this});i.config.debug&&(b("Built headers:",s),g(B));this.config.parsers=h(this,B);j=e(this);var H=[m.cssDesc,m.cssAsc];if(this.config.widthFixed){var I=c("<colgroup>");c("tr:first td",this.tBodies[0]).each(function(){I.append(c("<col>").css("width",c(this).width()))});c(this).prepend(I)}B.click(function(a){var b=
v[0].tBodies[0]&&v[0].tBodies[0].rows.length||0;if(!this.sortDisabled&&b>0){v.trigger("sortStart");c(this);b=this.column;this.order=this.count++%2;if(this.lockedOrder)this.order=this.lockedOrder;if(a[m.sortMultiSortKey]){a:{for(var a=m.sortList,e=a.length,i=0;i<e;i++)if(a[i][0]==b){a=true;break a}a=false}if(a)for(a=0;a<m.sortList.length;a++){e=m.sortList[a];i=m.headerList[e[0]];if(e[0]==b){i.count=e[1];i.count++;e[1]=i.count%2}}else m.sortList.push([b,this.order])}else{m.sortList=[];if(m.sortForce!=
null){e=m.sortForce;for(a=0;a<e.length;a++)e[a][0]!=b&&m.sortList.push(e[a])}m.sortList.push([b,this.order])}setTimeout(function(){x(v[0],B,m.sortList,H);d(v[0],r(v[0],m.sortList,j))},1);return false}}).mousedown(function(){if(m.cancelSelection){this.onselectstart=function(){return false};return false}});v.bind("update",function(){var a=this;setTimeout(function(){a.config.parsers=h(a,B);j=e(a)},1)}).bind("updateCell",function(a,b){var c=this.config,e=[b.parentNode.rowIndex-1,b.cellIndex];j.normalized[e[0]][e[1]]=
c.parsers[e[1]].format(f(c,b),b)}).bind("sorton",function(a,b){c(this).trigger("sortStart");m.sortList=b;for(var e=m.sortList,i=this.config,h=e.length,f=0;f<h;f++){var g=e[f],s=i.headerList[g[0]];s.count=g[1];s.count++}x(this,B,e,H);d(this,r(this,e,j))}).bind("appendCache",function(){d(this,j)}).bind("applyWidgetId",function(a,b){o(b).format(this)}).bind("applyWidgets",function(){p(this)});c.metadata&&(c(this).metadata()&&c(this).metadata().sortlist)&&(m.sortList=c(this).metadata().sortlist);0<m.sortList.length&&
v.trigger("sorton",[m.sortList]);p(this)}})};this.addParser=function(a){for(var b=n.length,c=!0,e=0;e<b;e++)n[e].id.toLowerCase()==a.id.toLowerCase()&&(c=!1);c&&n.push(a)};this.addWidget=function(a){u.push(a)};this.formatFloat=function(a){a=parseFloat(a);return isNaN(a)?0:a};this.formatInt=function(a){a=parseInt(a);return isNaN(a)?0:a};this.isDigit=function(a){return/^[-+]?\d*$/.test(c.trim(a.replace(/[,.']/g,"")))};this.clearTableBody=function(a){c.browser.msie?function(){for(;this.firstChild;)this.removeChild(this.firstChild)}.apply(a.tBodies[0]):
a.tBodies[0].innerHTML=""}}});c.fn.extend({tablesorter:c.tablesorter.construct});var d=c.tablesorter;d.addParser({id:"text",is:function(){return!0},format:function(b){return c.trim(b.toLocaleLowerCase())},type:"text"});d.addParser({id:"digit",is:function(b,g){return c.tablesorter.isDigit(b,g.config)},format:function(b){return c.tablesorter.formatFloat(b)},type:"numeric"});d.addParser({id:"currency",is:function(b){return/^[\u00a3$\u20ac?.]/.test(b)},format:function(b){return c.tablesorter.formatFloat(b.replace(RegExp(/[\u00a3$\u20ac]/g),
""))},type:"numeric"});d.addParser({id:"ipAddress",is:function(b){return/^\d{2,3}[\.]\d{2,3}[\.]\d{2,3}[\.]\d{2,3}$/.test(b)},format:function(b){for(var b=b.split("."),g="",h=b.length,a=0;a<h;a++)var e=b[a],g=2==e.length?g+("0"+e):g+e;return c.tablesorter.formatFloat(g)},type:"numeric"});d.addParser({id:"url",is:function(b){return/^(https?|ftp|file):\/\/$/.test(b)},format:function(b){return jQuery.trim(b.replace(RegExp(/(https?|ftp|file):\/\//),""))},type:"text"});d.addParser({id:"isoDate",is:function(b){return/^\d{4}[\/-]\d{1,2}[\/-]\d{1,2}$/.test(b)},
format:function(b){return c.tablesorter.formatFloat(""!=b?(new Date(b.replace(RegExp(/-/g),"/"))).getTime():"0")},type:"numeric"});d.addParser({id:"percent",is:function(b){return/\%$/.test(c.trim(b))},format:function(b){return c.tablesorter.formatFloat(b.replace(RegExp(/%/g),""))},type:"numeric"});d.addParser({id:"usLongDate",is:function(b){return b.match(RegExp(/^[A-Za-z]{3,10}\.? [0-9]{1,2}, ([0-9]{4}|'?[0-9]{2}) (([0-2]?[0-9]:[0-5][0-9])|([0-1]?[0-9]:[0-5][0-9]\s(AM|PM)))$/))},format:function(b){return c.tablesorter.formatFloat((new Date(b)).getTime())},
type:"numeric"});d.addParser({id:"shortDate",is:function(b){return/\d{1,2}[\/\-]\d{1,2}[\/\-]\d{2,4}/.test(b)},format:function(b,g){var h=g.config,b=b.replace(/\-/g,"/");if("us"==h.dateFormat)b=b.replace(/(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{4})/,"$3/$1/$2");else if("uk"==h.dateFormat)b=b.replace(/(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{4})/,"$3/$2/$1");else if("dd/mm/yy"==h.dateFormat||"dd-mm-yy"==h.dateFormat)b=b.replace(/(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{2})/,"$1/$2/$3");return c.tablesorter.formatFloat((new Date(b)).getTime())},
type:"numeric"});d.addParser({id:"time",is:function(b){return/^(([0-2]?[0-9]:[0-5][0-9])|([0-1]?[0-9]:[0-5][0-9]\s(am|pm)))$/.test(b)},format:function(b){return c.tablesorter.formatFloat((new Date("2000/01/01 "+b)).getTime())},type:"numeric"});d.addParser({id:"metadata",is:function(){return!1},format:function(b,g,h){b=g.config;b=!b.parserMetadataName?"sortValue":b.parserMetadataName;return c(h).metadata()[b]},type:"numeric"});d.addWidget({id:"zebra",format:function(b){var g;b.config.debug&&(g=new Date);
var h,a=-1,e;c("tr:visible",b.tBodies[0]).each(function(){h=c(this);h.hasClass(b.config.cssChildRow)||a++;e=0==a%2;h.removeClass(b.config.widgetZebra.css[e?0:1]).addClass(b.config.widgetZebra.css[e?1:0])});b.config.debug&&c.tablesorter.benchmark("Applying Zebra widget",g)}})})(jQuery);
(function(c){c(function(){c.tablesorter&&(c("<div>"),c.tablesorter.defaults.cssAsc="column-header-asc",c.tablesorter.defaults.cssDesc="column-header-desc",c.tablesorter.defaults.cssHeader="column-header",c.tablesorter.addParser({id:"datetime",is:function(){return!1},format:function(d,b,g){return c("[datetime]:first",g).attr("datetime")},type:"text"}),c.tablesorter.addParser({id:"ignoreCase",is:function(){return!1},format:function(c){return c.toLowerCase()},type:"text"}),c.tablesorter.addParser({id:"string",
is:function(){return!1},format:function(c){return c},type:"text"}),c.tablesorter.addParser({id:"number",is:function(){return!1},format:function(d,b,g){d=c(".number:first",g).attr("data-value");null==d&&(d=Number.MIN_VALUE);return d},type:"numeric"}),c(".table-sortable").each(function(){c(this).tablesorter()}))})})(jQuery);
(function(c){c.factory("collapse_module",{init:function(){var b=this;this.$column=c(this.options.column);this.modules=c(this.options.modules,this.element);this.first_module=this.modules.get(0);this.trigger=c(".trigger:first",this.first_module);this.first_section=c(".module-section",this.first_module);this.other_modules=this.modules.slice(1);this.column_offset=this.$column.css("margin-left");this.set_collapsed(this.options.collapsed);this.trigger.click(function(c){return b.toggle(c)})},set_collapsed:function(b){(this.toggle_state=
b)?(this.trigger.addClass("collapsed"),this.$column.css("margin-left",0),this.first_section.hide(),this.other_modules.hide()):(this.trigger.removeClass("collapsed"),this.$column.css("margin-left",this.column_offset),this.first_section.show(),this.other_modules.show())},toggle:function(){var b=this;this.toggle_state?(c.localstore("filters_collapsed",0,!1),this.trigger.removeClass("collapsed"),this.$column.animate({marginLeft:this.column_offset},function(){b.first_section.slideDown(function(){b.modules.removeClass("collapsed")});
b.other_modules.fadeIn()})):(c.localstore("filters_collapsed",1,!1),this.trigger.addClass("collapsed"),this.other_modules.fadeOut(),this.first_section.slideUp(function(){b.$column.animate({marginLeft:0});b.modules.addClass("collapsed")}));this.toggle_state=!this.toggle_state;this.options.toggle_callback&&this.options.toggle_callback.call(this.trigger,this.toggle_state);return!1}});var d=c("body").is(".embed")||c.localstore("filters_collapsed");c.extend(!0,c.collapse_module,{defaults:{collapsed:null===
d?!1:!!d,modules:".module",column:"#main-column"}})})(jQuery);
(function(c){function d(b,a,c){var f=c.relative?b.position().top:b.offset().top,g=c.relative?b.position().left:b.offset().left,d=c.position[0],f=f-(a.outerHeight()-c.offset[0]),g=g+(b.outerWidth()+c.offset[1]),p=a.outerHeight()+b.outerHeight();"center"==d&&(f+=p/2);"bottom"==d&&(f+=p);d=c.position[1];b=a.outerWidth()+b.outerWidth();"center"==d&&(g-=b/2);"left"==d&&(g-=b);return{top:f,left:g}}function b(b,a){var e=this,f=b.add(e),k,l=0,p=0,o=b.attr("title"),x=g[a.effect],r,j=b.is(":input"),n=j&&b.is(":checkbox, :radio, select, :button, :submit"),
u=b.attr("type"),y=a.events[u]||a.events[j?n?"widget":"input":"def"];if(!x)throw'Nonexistent effect "'+a.effect+'"';y=y.split(/,\s*/);if(2!=y.length)throw"Tooltip: bad events configuration for "+u;b.bind(y[0],function(b){clearTimeout(l);a.predelay?p=setTimeout(function(){e.show(b)},a.predelay):e.show(b)}).bind(y[1],function(b){clearTimeout(p);a.delay?l=setTimeout(function(){e.hide(b)},a.delay):e.hide(b)});o&&a.cancelDefault&&(b.removeAttr("title"),b.data("title",o));c.extend(e,{show:function(g){if(!k){if(o)k=
c(a.layout).addClass(a.tipClass).appendTo(document.body).hide().append(o);else if(a.tip)k=c(a.tip).eq(0);else{k=b.next();k.length||(k=b.parent().next())}if(!k.length)throw"Cannot find tooltip for "+b;}if(e.isShown())return e;k.stop(true,true);var j=d(b,k,a),g=g||c.Event();g.type="onBeforeShow";f.trigger(g,[j]);if(g.isDefaultPrevented())return e;j=d(b,k,a);k.css({position:"absolute",top:j.top,left:j.left});r=true;x[0].call(e,function(){g.type="onShow";r="full";f.trigger(g)});j=a.events.tooltip.split(/,\s*/);
k.bind(j[0],function(){clearTimeout(l);clearTimeout(p)});j[1]&&!b.is("input:not(:checkbox, :radio), textarea")&&k.bind(j[1],function(a){a.relatedTarget!=b[0]&&b.trigger(y[1].split(" ")[0])});return e},hide:function(b){if(!k||!e.isShown())return e;b=b||c.Event();b.type="onBeforeHide";f.trigger(b);if(!b.isDefaultPrevented()){r=false;g[a.effect][1].call(e,function(){b.type="onHide";r=false;f.trigger(b)});return e}},isShown:function(a){return a?r=="full":r},getConf:function(){return a},getTip:function(){return k},
getTrigger:function(){return b}});c.each(["onHide","onBeforeShow","onShow","onBeforeHide"],function(b,f){c.isFunction(a[f])&&c(e).bind(f,a[f]);e[f]=function(a){c(e).bind(f,a);return e}})}c.tools=c.tools||{version:"@VERSION"};c.tools.tooltip={conf:{effect:"toggle",fadeOutSpeed:"fast",predelay:0,delay:30,opacity:1,tip:0,position:["top","center"],offset:[0,0],relative:!1,cancelDefault:!0,events:{def:"mouseenter,mouseleave",input:"focus,blur",widget:"focus mouseenter,blur mouseleave",tooltip:"mouseenter,mouseleave"},
layout:"<div/>",tipClass:"tooltip"},addEffect:function(b,a,c){g[b]=[a,c]}};var g={toggle:[function(b){var a=this.getConf(),c=this.getTip(),a=a.opacity;1>a&&c.css({opacity:a});c.show();b.call()},function(b){this.getTip().hide();b.call()}],fade:[function(b){var a=this.getConf();this.getTip().fadeTo(a.fadeInSpeed,a.opacity,b)},function(b){this.getTip().fadeOut(this.getConf().fadeOutSpeed,b)}]};c.fn.tooltip=function(g){var a=this.data("tooltip");if(a)return a;g=c.extend(!0,{},c.tools.tooltip.conf,g);
"string"==typeof g.position&&(g.position=g.position.split(/,?\s/));this.each(function(){a=new b(c(this),g);c(this).data("tooltip",a)});return g.api?a:this}})(jQuery);
(function(c,d){d.filters={init_domain_type_property_filter:function(b){c(":text[name=domain], :text[name=type], :text[name=property]",b).suggest(c.extend({scoring:"schema",format:null,mql_output:JSON.stringify([{id:null,name:null,type:{id:null,"id|=":["/type/domain","/type/type","/type/property"],limit:1}}])},d.suggest_options.any("type:/type/domain","type:/type/type","type:/type/property"))).bind("fb-select",function(b,d){var a=c(this);a.val(d.id);var e=d.type.id;"/type/domain"===e?a.attr("name",
"domain"):"/type/type"===e?a.attr("name","type"):"/type/property"===e&&a.attr("name","property");this.form.submit()}).parents(".filter-form").submit(function(){return!1})}};c(function(){c(".filter-form :input").keypress(function(b){13===b.keyCode&&this.form.submit();return!0});c(".filter-help-trigger").tooltip({events:{def:"click,mouseout"},position:"top center",effect:"fade",delay:300,offset:[-8,0]});c(".filter-form-trigger").click(function(){var b=c(this).siblings(".filter-form");b.is(":hidden")?
b.slideDown(function(){c(":text:first",b).focus()}):b.slideUp()})})})(jQuery,window.freebase);
(function(c){var d="undefined"!=typeof window.innerWidth?function(){return{w:window.innerWidth,h:window.innerHeight}}:"undefined"!=typeof document.documentElement&&"undefined"!=typeof document.documentElement.clientWidth&&0!=document.documentElement.clientWidth?function(){return{w:document.documentElement.clientWidth,h:document.documentElement.clientHeight}}:function(){return{w:document.getElementsByTagName("body")[0].clientWidth,h:document.getElementsByTagName("body")[0].clientHeight}};window.kbs=
function(b){c(".kbs.current",b).removeClass("current");var g=c(".domain-section:first",b),h=c(".domain-section:last",b),a=this.scroll_to=function(a){var b=c(document).scrollTop();c(document).height();var e=d().h,e=b+e,f=a.offset().top,a=f+a.height();f<b?c(document).scrollTop(f):a>e&&c(document).scrollTop(b+(a-e))},e=this.get_current=function(){return c(".kbs.current:first",b)},f=this.set_next=function(b,c,f){b=b||e();c.length&&(b.removeClass("current"),c.addClass("current"),f||a(c))},k=this.next_domain=
function(a){var b=e(),c=l(b);c&&(c=c.find(".kbs:first"),f(b,c,a))},l=this._next_domain=function(a){if(!a||!a.length)return c(".domain-section:first",b);a=a.closest(".domain-section");return!a.length||a[0]===h[0]?g:a.next(".domain-section")},p=this.prev_domain=function(){var a=e(),b=o(a);b&&(b=b.find(".kbs:first"),f(a,b))},o=this._prev_domain=function(a){if(!a||!a.length)return c(".domain-section:last",b);var e=a.closest(".domain-section");return a.closest(".property-section").length||a.closest(".type-section").length?
e:!e.length||e[0]===g[0]?h:e.prev(".domain-section")},x=this.next_type=function(){var a=e(),b=r(a);b&&(b=b.find(".kbs:first"),f(a,b))},r=this._next_type=function(a){if(!a||!a.length)return c(".type-section:first",b);var e=a.closest(".domain-section"),a=a.closest(".type-section"),a=a.length?a.next(".type-section"):e.find(".type-section:first");if(!a||!a.length){var f=l(e);if(f)for(;f.get(0)!==e.get(0);){a=f.find(".type-section:first");if(a.length)break;f=l(f)}}return a},j=this.prev_type=function(){var a=
e(),b=n(a);b&&(b=b.find(".kbs:first"),f(a,b))},n=this._prev_type=function(a){if(!a||!a.length)return c(".type-section:last",b);var e=a.closest(".domain-section"),f=a.closest(".type-section");if(a.closest(".property-section").length)return f;var g;f.length&&(g=f.prev(".type-section"));if(!g||!g.length)if(a=o(e))for(;a.get(0)!==e.get(0);){g=a.find(".type-section:last");if(g.length)break;a=o(a)}return g},u=this.next_prop=function(){var a=e(),b=y(a);b&&(b=b.find(".kbs:first"),f(a,b))},y=this._next_prop=
function(a){if(!a||!a.length)return c(".property-section:first",b);var e=a.closest(".domain-section"),f=a.closest(".type-section"),g=a.closest(".property-section"),e=g.length?g.next(".property-section"):f.length?f.find(".property-section:first"):e.find(".property-section:first");if(!e||!e.length)if(a=r(a))for(;a.get(0)!==f.get(0);){e=a.find(".property-section:first");if(e.length)break;null==f.get(0)&&(f=a);a=r(a)}return e},v=this.prev_prop=function(){var a=e(),b=J(a);b&&(b=b.find(".kbs:first"),f(a,
b))},J=this._prev_prop=function(a){if(!a||!a.length)return c(".property-section:last",b);var e=a.closest(".domain-section"),f=a.closest(".type-section"),g=a.closest(".property-section");if(a.closest(".data-section").length)return g;var d;g.length&&(d=g.prev(".property-section"));if(!d||!d.length)if(j=f.length?n(f):n(e))for(;j.get(0)!==f.get(0);){d=j.find(".property-section:last");if(d.length)break;null==f.get(0)&&(f=j);j=n(j)}return d};this.next=function(){var a=e();if(a&&a.length){var g=this._next(a);
if(g){f(a,g);return}}a=c(".kbs:visible:first",b);f(a,a)};this._next=function(a){if(!a||!a.length)return c(".domain-section:first .kbs:first",b);var e=a.closest(".domain-section"),f=a.closest(".type-section"),d=a.closest(".property-section");if(a.closest(".data-section").length){a=a.next(".kbs");if(a.length)return a;a=d.next(".property-section").find(".kbs:first");if(a.length)return a;a=f.next(".type-section").find(".kbs:first")}else if(d.length){a=d.find(".data-section:first .kbs:first");if(a.length)return a;
a=d.next(".property-section").find(".kbs:first");if(a.length)return a;a=f.next(".type-section").find(".kbs:first")}else if(f.length){a=f.find(".property-section:first .kbs:first");if(a.length)return a;a=f.next(".type-section").find(".kbs:first")}else a=e.find(".type-section:first .kbs:first");return a.length?a:e.get(0)===h.get(0)?g.find(".kbs:first"):e.next(".domain-section").find(".kbs:first")};this.prev=function(){var a=e(),b=this._prev(a);b&&f(a,b)};this._prev=function(a){if(!a||!a.length)return a=
c(".data-section:last .kbs:last",b),a.length||(a=c(".property-section:last .kbs:first",b)),a.length||(a=c(".type-section:last .kbs:first",b)),a.length||(a=c(".domain-section:last .kbs:first",b)),a;var e=a.closest(".domain-section"),f=a.closest(".type-section"),d=a.closest(".property-section");return a.closest(".data-section").length?(a=a.prev(".kbs"),a.length?a:d.find(".kbs:first")):d.length?(a=d.prev(".property-section").find(".kbs:last"),a.length?a:f.find(".kbs:first")):f.length?(a=f.prev(".type-section").find(".kbs:last"),
a.length?a:e.find(".kbs:first")):e.get(0)===g.get(0)?h.find(".kbs:last"):e.prev(".domain-section").find(".kbs:last")};this.edit=function(){this.get_current().trigger("edit")};var m=this;c(document).unbind(".kbs").bind("keydown.kbs",function(a){var b=a.target;if(b==document.body||b==document||b==window||b==c("html")[0])b=a.keyCode,68===b?a.shiftKey?p():k():84===b?a.shiftKey?j():x():80===b?a.shiftKey?v():u():74===b?m.next():75===b?m.prev():69===b&&m.edit()})}})(jQuery);
(function(c,d){var b=window.propbox={init:function(g,h){h=c.extend({lang:"/lang/en"},h);if(!h.base_ajax_url)throw Error("base_ajax_url required in propbox options");if(!h.base_static_url)throw Error("base_static_url required in propbox options");if(!h.id)throw Error("topic id required in propbox options");if(!h.lang)throw Error("lang required in propbox options");b.options=h;b.kbs=new d(g);c(".kbs",g).live("click",function(){var a=b.kbs.get_current();b.kbs.set_next(a,c(this),!0)}).live("edit",function(){var a=
c(this).find(".headmenu:first").data("submenu");a&&c("li:first a:first",a).click()});b.init_menus(g)},init_menus:function(g,d){g=c(g||document);d&&c(".nicemenu",g).nicemenu();var a;a=g&&g.is(".hover-row")?g:c(".hover-row",g);a.hover(b.row_menu_hoverover,b.row_menu_hoverout);a.dblclick(function(){var a=c(".nicemenu .default-action",this);a.length||(a=c(".nicemenu:first .submenu:first a:first",this));var b=a.attr("href");("#"==b||0==b.indexOf("javascript:void(0)"))&&c(a).click()});c(".nicemenu .headmenu",
g).add(c(".nicemenu .default-action",g)).click("click",function(){if(b.kbs){var a=b.kbs.get_current();a&&b.kbs.set_next(a,c(this).parents(".kbs:first"),!0)}return!1})},row_menu_hoverover:function(){c(this).addClass("row-hover")},row_menu_hoverout:function(){c(this).removeClass("row-hover")},get_script:function(g,d){var a=b.get_script.cache;a||(a=b.get_script.cache={});var e=a[g];e?1===e.state?e.callbacks.push(d):4===e.state&&d():(e=a[g]={state:0,callbacks:[d]},c.ajax({url:b.options.base_static_url+
g,dataType:"script",beforeSend:function(){e.state=1},success:function(){e.state=4;c.each(e.callbacks,function(a,b){b()})},error:function(){e.state=-1}}))},prop_edit:function(g,d){var a=c(g).parents(".property-section");a.length||(a=c(g).parents(".submenu").data("headmenu").parents(".property-section"));a=a.find(".data-section .data-row:first:visible .nicemenu:first .headmenu:first a");a.length?a.click():b.prop_add(g,d);return!1},prop_add:function(g,d){var a=c(g).parents(".property-section");a.length||
(a=c(g).parents(".submenu").data("headmenu").parents(".property-section"));b.get_script("/propbox-edit.mf.js",function(){b.edit.prop_add_begin(a,d)});return!1},value_edit:function(g){var d=c(g).parents(".submenu").data("headmenu").parents(".data-row:first"),a=d.parents(".property-section");b.get_script("/propbox-edit.mf.js",function(){b.edit.value_edit_begin(a,d)});return!1},value_delete:function(g){var d=c(g).parents(".submenu").data("headmenu").parents(".data-row:first"),a=d.parents(".property-section");
b.get_script("/propbox-edit.mf.js",function(){b.edit.value_delete_begin(a,d)});return!1},remove_type:function(g){var g=c(g),d=g.parents(".type-section");b.get_script("/propbox-edit.mf.js",function(){b.edit.remove_type_begin(g,d)});return!1},add_type:function(d,h,a){var d=c(d),e=d.parents(".type-section"),f=b.options.incompatible_types;f?f.search(b.options.id,h,a,{compatible:function(){b.add_type_submit(d,e)},incompatible:f.overlay_incompatible_callback({onConfirm:function(){b.add_type_submit(d,e)}})}):
b.add_type_submit(d,e);return!1},add_type_submit:function(c,d){b.get_script("/propbox-edit.mf.js",function(){b.edit.add_type_submit(c,d)})},add_has_no_value:function(d){var h=c(d).parents(".submenu").data("headmenu").parents(".property-section");b.get_script("/propbox-edit.mf.js",function(){b.edit.add_has_no_value(h)});return!1},add_has_value:function(d){var h=c(d).parents(".submenu").data("headmenu").parents(".property-section");b.get_script("/propbox-edit.mf.js",function(){b.edit.add_has_value(h)});
return!1},remove_has_no_value:function(d){var h=c(d).parents(".property-section");b.get_script("/propbox-edit.mf.js",function(){b.edit.remove_has_no_value(h)});return!1},remove_has_value:function(d){var h=c(d).parents(".property-section");b.get_script("/propbox-edit.mf.js",function(){b.edit.remove_has_value(h)});return!1},more:function(d,h,a){var e=c(d).parents(".property-section");b.get_script("/propbox-edit.mf.js",function(){b.edit.more(e,h,a)})}}})(jQuery,window.kbs);
(function(c,d,b){d.infinitescroll=function(a,b,c){this.element=d(c);this._create(a,b)};d.infinitescroll.defaults={loading:{finished:b,finishedMsg:"<em>Congratulations, you've reached the end of the internet.</em>",img:"http://www.infinite-scroll.com/loading.gif",msg:null,msgText:"<em>Loading the next set of posts...</em>",selector:null,speed:"fast",start:b},state:{isDuringAjax:!1,isInvalidPage:!1,isDestroyed:!1,isDone:!1,isPaused:!1,currPage:1},callback:b,debug:!1,behavior:b,binder:d(c),nextSelector:"div.navigation a:first",
navSelector:"div.navigation",contentSelector:null,extraScrollPx:150,itemSelector:"div.post",animate:!1,pathParse:b,dataType:"html",appendCallback:!0,bufferPx:40,errorCallback:function(){},infid:0,pixelsFromNavToBottom:b,path:b};d.infinitescroll.prototype={_binding:function(a){var c=this,f=c.options;if(f.behavior&&this["_binding_"+f.behavior]!==b)this["_binding_"+f.behavior].call(this);else{if("bind"!==a&&"unbind"!==a)return this._debug("Binding value  "+a+" not valid"),!1;if("unbind"==a)this.options.binder.unbind("smartscroll.infscr."+
c.options.infid);else this.options.binder[a]("smartscroll.infscr."+c.options.infid,function(){c.scroll()});this._debug("Binding",a)}},_create:function(a,c){if(!this._validate(a))return!1;var f=this.options=d.extend(!0,{},d.infinitescroll.defaults,a),g=d(f.nextSelector).attr("href");f.contentSelector=f.contentSelector||this.element;f.loading.selector=f.loading.selector||f.contentSelector;g?(f.path=this._determinepath(g),f.loading.msg=d('<div id="infscr-loading"><img alt="Loading..." src="'+f.loading.img+
'" /><div>'+f.loading.msgText+"</div></div>"),(new Image).src=f.loading.img,f.pixelsFromNavToBottom=d(document).height()-d(f.navSelector).offset().top,f.loading.start=f.loading.start||function(){d(f.navSelector).hide();f.loading.msg.appendTo(f.loading.selector).show(f.loading.speed,function(){beginAjax(f)})},f.loading.finished=f.loading.finished||function(){f.loading.msg.fadeOut("normal")},f.callback=function(a,g){f.behavior&&a["_callback_"+f.behavior]!==b&&a["_callback_"+f.behavior].call(d(f.contentSelector)[0],
g);c&&c.call(d(f.contentSelector)[0],g)},this._setup()):this._debug("Navigation selector not found")},_debug:function(){if(this.options.debug)return c.console&&console.log.call(console,arguments)},_determinepath:function(a){var c=this.options;if(c.behavior&&this["_determinepath_"+c.behavior]!==b)this["_determinepath_"+c.behavior].call(this,a);else{if(c.pathParse)return this._debug("pathParse manual"),"function"===typeof c.pathParse?c.pathParse():c.pathParse;if(a.match(/^(.*?)\b2\b(.*?$)/))a=a.match(/^(.*?)\b2\b(.*?$)/).slice(1);
else if(a.match(/^(.*?)2(.*?$)/)){if(a.match(/^(.*?page=)2(\/.*|$)/))return a=a.match(/^(.*?page=)2(\/.*|$)/).slice(1);a=a.match(/^(.*?)2(.*?$)/).slice(1)}else{if(a.match(/^(.*?page=)1(\/.*|$)/))return a=a.match(/^(.*?page=)1(\/.*|$)/).slice(1);this._debug("Sorry, we couldn't parse your Next (Previous Posts) URL. Verify your the css selector points to the correct A tag. If you still get this error: yell, scream, and kindly ask for help at infinite-scroll.com.");c.state.isInvalidPage=!0}this._debug("determinePath",
a);return a}},_error:function(a){var c=this.options;c.behavior&&this["_error_"+c.behavior]!==b?this["_error_"+c.behavior].call(this,a):("destroy"!==a&&"end"!==a&&(a="unknown"),this._debug("Error",a),"end"==a&&this._showdonemsg(),c.state.isDone=!0,c.state.currPage=1,c.state.isPaused=!1,this._binding("unbind"))},_loadcallback:function(a,e){var f=this.options,g=this.options.callback,h=f.state.isDone?"done":!f.appendCallback?"no-append":"append";if(f.behavior&&this["_loadcallback_"+f.behavior]!==b)this["_loadcallback_"+
f.behavior].call(this,a,e);else{switch(h){case "done":return this._showdonemsg(),!1;case "no-append":"html"==f.dataType&&(e=d("<div>"+e+"</div>").find(f.itemSelector));break;case "append":var p=a.children();if(0==p.length)return this._error("end");for(h=document.createDocumentFragment();a[0].firstChild;)h.appendChild(a[0].firstChild);this._debug("contentSelector",d(f.contentSelector)[0]);d(f.contentSelector)[0].appendChild(h);e=p.get()}f.loading.finished.call(d(f.contentSelector)[0],f);f.animate&&
(h=d(c).scrollTop()+d("#infscr-loading").height()+f.extraScrollPx+"px",d("html,body").animate({scrollTop:h},800,function(){f.state.isDuringAjax=!1}));f.animate||(f.state.isDuringAjax=!1);g(this,e)}},_nearbottom:function(){var a=this.options,e=0+d(document).height()-a.binder.scrollTop()-d(c).height();if(a.behavior&&this["_nearbottom_"+a.behavior]!==b)this["_nearbottom_"+a.behavior].call(this);else return this._debug("math:",e,a.pixelsFromNavToBottom),e-a.bufferPx<a.pixelsFromNavToBottom},_pausing:function(a){var c=
this.options;if(c.behavior&&this["_pausing_"+c.behavior]!==b)this["_pausing_"+c.behavior].call(this,a);else{"pause"!==a&&("resume"!==a&&null!==a)&&this._debug("Invalid argument. Toggling pause value instead");switch(a&&("pause"==a||"resume"==a)?a:"toggle"){case "pause":c.state.isPaused=!0;break;case "resume":c.state.isPaused=!1;break;case "toggle":c.state.isPaused=!c.state.isPaused}this._debug("Paused",c.state.isPaused);return!1}},_setup:function(){var a=this.options;if(a.behavior&&this["_setup_"+
a.behavior]!==b)this["_setup_"+a.behavior].call(this);else return this._binding("bind"),!1},_showdonemsg:function(){var a=this.options;a.behavior&&this["_showdonemsg_"+a.behavior]!==b?this["_showdonemsg_"+a.behavior].call(this):(a.loading.msg.find("img").hide().parent().find("div").html(a.loading.finishedMsg).animate({opacity:1},2E3,function(){d(this).parent().fadeOut("normal")}),a.errorCallback.call(d(a.contentSelector)[0],"done"))},_validate:function(a){for(var b in a)return b.indexOf&&-1<b.indexOf("Selector")&&
0===d(a[b]).length?(this._debug("Your "+b+" found no elements."),!1):!0},bind:function(){this._binding("bind")},destroy:function(){this.options.state.isDestroyed=!0;return this._error("destroy")},pause:function(){this._pausing("pause")},resume:function(){this._pausing("resume")},retrieve:function(a){var c=this,f=c.options,g=this._determinepath(g),h,p,o,x,a=a||null;beginAjax=function(a){a.state.currPage++;c._debug("heading into ajax",g);h=d(a.contentSelector).is("table")?d("<tbody/>"):d("<div/>");
p=g.join(a.state.currPage);o="html"==a.dataType||"json"==a.dataType?a.dataType:"html+callback";a.appendCallback&&"html"==a.dataType&&(o+="+callback");switch(o){case "html+callback":c._debug("Using HTML via .load() method");h.load(p+" "+a.itemSelector,null,function(a){c._loadcallback(h,a)});break;case "html":case "json":c._debug("Using "+o.toUpperCase()+" via $.ajax() method"),d.ajax({url:p,dataType:a.dataType,complete:function(a,b){(x="undefined"!==typeof a.isResolved?a.isResolved():"success"===b||
"notmodified"===b)?c._loadcallback(h,a.responseText):c._error("end")}})}};if(f.behavior&&this["retrieve_"+f.behavior]!==b)this["retrieve_"+f.behavior].call(this,a);else{if(f.state.isDestroyed)return this._debug("Instance is destroyed"),!1;f.state.isDuringAjax=!0;f.loading.start.call(d(f.contentSelector)[0],f)}},scroll:function(){var a=this.options,c=a.state;a.behavior&&this["scroll_"+a.behavior]!==b?this["scroll_"+a.behavior].call(this):!c.isDuringAjax&&!c.isInvalidPage&&!c.isDone&&!c.isDestroyed&&
!c.isPaused&&this._nearbottom()&&this.retrieve()},toggle:function(){this._pausing()},unbind:function(){this._binding("unbind")},update:function(a){d.isPlainObject(a)&&(this.options=d.extend(!0,this.options,a))}};d.fn.infinitescroll=function(a,b){switch(typeof a){case "string":var c=Array.prototype.slice.call(arguments,1);this.each(function(){var b=d.data(this,"infinitescroll");if(!b||!d.isFunction(b[a])||"_"===a.charAt(0))return!1;b[a].apply(b,c)});break;case "object":this.each(function(){var c=d.data(this,
"infinitescroll");c?c.update(a):d.data(this,"infinitescroll",new d.infinitescroll(a,b,this))})}return this};var g=d.event,h;g.special.smartscroll={setup:function(){d(this).bind("scroll",g.special.smartscroll.handler)},teardown:function(){d(this).unbind("scroll",g.special.smartscroll.handler)},handler:function(a,b){var c=this,g=arguments;a.type="smartscroll";h&&clearTimeout(h);h=setTimeout(function(){d.event.handle.apply(c,g)},"execAsap"===b?0:100)}};d.fn.smartscroll=function(a){return a?this.bind("smartscroll",
a):this.trigger("smartscroll",["execAsap"])}})(window,jQuery);(function(c){c.fn.fixedcolumn=function(d){var b=c.extend(!0,{},d);return this.each(function(){var d=c(this).find("tr:first").children();1<d.length&&(b.all||(d=c(d.get(0))),d.each(function(){var b=c(this),a=b[0].nodeName.toUpperCase();if("TD"===a||"TH"===a)a=b.width(),0<a&&c(":first-child",b).width(a).css("display","inline-block")}))})}})(jQuery);
(function(c,d,b){var g=d.sameas={init:function(){c(".column.nav").collapse_module({modules:".module",column:".section"});c(":text[name=creator]").suggest(d.suggest_options.any("type:/type/user")).bind("fb-select",function(b,a){c(this).val(a.id).parents("form:first").submit()});b.init_menus();c(".infinitescroll > tbody").each(function(){g.init_infinitescroll(c(this))});c(".infinitescroll").fixedcolumn()},infid:0,init_infinitescroll:function(h){if(h.attr("data-next")){var a=h.next("tfoot").find(".infinitescroll-next");
h.infinitescroll({loading:{msgText:"Fetching more links",img:d.h.static_url("lib/template/img/horizontal-loader.gif")},nextSelector:a,navSelector:a,dataType:"json",pathParse:function(){return[a[0].href+"&"+c.param({next:h.attr("data-next")})+"&page=",""]},appendCallback:!1,infid:g.infid++},function(a){var a=JSON.parse(a),d=c(a.result.html);if(a=d.attr("data-next")){d=c(">tr",d);h.append(d);d.each(function(){b.init_menus(this,!0)});h.attr("data-next",a);var a=c(">tr",h).length,d=h.parent("table"),
g=d.prev(".table-title").find("[name=infinitescroll-count]");c(".number",g).attr("data-value",a).text(a);d.trigger("update")}else(a=h.data("infinitescroll"))&&a.unbind()});c(window).trigger("scroll")}else h.next("tfoot").remove()},add_key:function(b,a){var e=c(this);d.get_script(d.h.static_url("sameas-edit.mf.js"),function(){g.edit.add_key_begin(e,a)});return!1},edit_key:function(b,a){var e=c(b).parents(".submenu").data("headmenu").parents(".data-row:first");d.get_script(d.h.static_url("sameas-edit.mf.js"),
function(){g.edit.edit_key_begin(e,a)});return!1},delete_key:function(b,a){var e=c(b).parents(".submenu").data("headmenu").parents(".data-row:first");d.get_script(d.h.static_url("sameas-edit.mf.js"),function(){g.edit.delete_key_begin(e,a)});return!1}};c(g.init)})(jQuery,window.freebase,window.propbox);
