
/*
 * Copyright 2012, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Additional Licenses for Third Party components can be found here:
 * http://wiki.freebase.com/wiki/Freebase_Site_License
 *
 */
(function(){var a=window.mjt,c=window.mjt={};c.noConflict=function(){window.mjt=a;return c};c.NAME="mjt";c.VERSION="0.9.3";c.LICENSE="========================================================================\nCopyright (c) 2007-2009, Metaweb Technologies, Inc.\nAll rights reserved.\n\nRedistribution and use in source and binary forms, with or without\nmodification, are permitted provided that the following conditions\nare met:\n    * Redistributions of source code must retain the above copyright\n      notice, this list of conditions and the following disclaimer.\n    * Redistributions in binary form must reproduce the above\n      copyright notice, this list of conditions and the following\n      disclaimer in the documentation and/or other materials provided\n      with the distribution.\n\nTHIS SOFTWARE IS PROVIDED BY METAWEB TECHNOLOGIES ``AS IS'' AND ANY\nEXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE\nIMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR\nPURPOSE ARE DISCLAIMED. IN NO EVENT SHALL METAWEB TECHNOLOGIES BE\nLIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR\nCONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF\nSUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR\nBUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,\nWHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE\nOR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN\nIF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n========================================================================\n"})();
(function(a){"undefined"==typeof a.services&&(a.services={});a.debug=0;var c={};a.uniqueid=function(a){var b=c[a];typeof b!=="number"&&(b=1);c[a]=b+1;return a+"_"+b};var b=function(c,b){var d=document.createElement("div"),e,h;e=document.createElement("h3");e.style.backgroundColor="#fff0f0";e.appendChild(document.createTextNode(c));d.appendChild(e);for(var k=0;k<b.length;k++){var j=b[k];if(j instanceof Array){e=document.createElement("div");e.innerHTML=a.flatten_markup(j)}else{e=document.createElement("pre");
if(typeof j=="string")h=j;else try{h=JSON.stringify(j)}catch(l){h=""+j}h=h.replace(/\r?\n/g,"\r\n");e.appendChild(document.createTextNode(h))}d.appendChild(e)}(e=document.getElementById("mjt_debug_output"))||(e=document.getElementsByTagName("body")[0]);e&&e.appendChild(d)},d=function(a){return Array.prototype.slice.apply(a).join(" ")};if("object"!=typeof console||"undefined"==typeof console.log)if("undefined"!=typeof document)a.error=function(){b("error",arguments);return""},a.warn=function(){b("warning",
arguments);return""},a.log=function(){return""},a.note=function(){return""},a.openlog=function(){return""},a.closelog=function(){return""},a.assert=function(){return""};else{if("undefined"!=typeof Packages){var e=java.lang.System.err;a.error=function(){e.println("error: "+d(arguments));return""};a.warn=function(){e.println("error: "+d(arguments));return""};a.log=function(){e.println("log: "+d(arguments));return""};a.note=function(){e.println("note: "+d(arguments));return""};a.openlog=function(){return""};
a.closelog=function(){return""};a.assert=function(){return""}}}else"function"==typeof console.debug?(a.error=function(){console.error.apply(console,arguments);return""},a.warn=function(){console.warn.apply(console,arguments);return""},a.log=function(){console.log.apply(console,arguments);return""},a.note=function(){a.debug&&console.info.apply(console,arguments);return""},a.openlog="undefined"!=typeof console.group?function(){a.debug&&console.group.apply(console,arguments)}:a.log,a.closelog="undefined"!=
typeof console.groupEnd?function(){a.debug&&console.groupEnd.apply(console,arguments);return""}:function(){return""},a.assert=function(a){if(!a){console.error.apply(console,arguments);throw Error("assertion failed");}return""}):(a.error=function(){console.log("error: "+d(arguments));return""},a.warn=function(){console.log("warning: "+d(arguments));return""},a.log=function(){return""},a.note=function(){return""},a.openlog=function(){return""},a.closelog=function(){return""},a.assert=function(){return""});
a.formquote=function(a){return/^[-A-Za-z0-9~!*()_.',:@$\/]*$/.test(a)?a:encodeURIComponent(a).replace("%2C",",","g").replace("%3A",":","g").replace("%40","@","g").replace("%24","$","g").replace("%2F","/","g")};a.formencode=function(c){var b=[],d="",e,h,k,j=[];for(e in c)j.push(e);j.sort();for(k in j){e=j[k];h=c[e];if(typeof h!="undefined"){h instanceof Array||(h=[h]);for(var l=0;l<h.length;l++){var m=h[l];b.push(d);d="&";b.push(a.formquote(e));b.push("=");b.push(a.formquote(m))}}}return b.join("")};
a.formdecode=function(c){if(typeof c=="undefined"||c===null)return{};c=c.replace(/^\s*/m,"").replace(/\s+$/m,"");if(c=="")return{};for(var b={},c=c.split("&"),d=0;d<c.length;d++){var e=c[d].indexOf("=");if(e<1)a.log('bad uri query argument, missing "=": ',c[d]);else{var h=[c[d].substring(0,e),c[d].substring(e+1)],e=decodeURIComponent(h[0].replace(/\+/g," ")),h=decodeURIComponent(h[1].replace(/\+/g," "));e in b?b[e]instanceof Array?b[e].push(h):b[e]=[b[e],h]:b[e]=h}}return b};a.form_url=function(c,
b){return!b||!a.formencode(b)?c:c+"?"+a.formencode(b)};a.htmlencode=function(a){typeof a!="string"&&(a=""+a);return a.replace(/\&/g,"&amp;").replace(/\</g,"&lt;").replace(/\>/g,"&gt;").replace(/\"/g,"&quot;")};a.label_package=function(c){var b=window;if(c){for(var d=c.split(".");d.length;)b=b[d.shift()];if(typeof b=="function")b=b.prototype;(typeof b=="object"||typeof b=="function")&&b!==null?b._package_name=c:a.log("missing package",c)}for(var e in b){d=b[e];if(a&&a.Task&&d&&typeof d!="string"&&
!d.nodeName&&d.constructor!=Array&&/function/i.test(d+"")&&typeof d.prototype=="object"&&d.prototype instanceof a.Task)d.prototype._task_class=c+"."+e}}})(mjt);
(function(a){a.bless=function(c){return new a.Markup(c)};a.MarkupList=function(){for(var a=0;a<arguments.length;a++)this[a]=arguments[a]};a.Markup=function(a){this.html=a};a.Markup.prototype.toMarkup=function(){return this.html};var c=function(a,c,b){b.push('<span style="outline-style:solid;color:red;">');c?(b.push(c),b.push("</span>")):(b.push("bad markup element, type ["),b.push(typeof a),b.push("]</span>"))},b=function(d,e){switch(typeof d){case "object":if(null===d)c(d,"[null]",e);else if(d instanceof
a.MarkupList)for(var f=0;f in d;f++)b(d[f],e);else"function"===typeof d.toMarkupList?b(d.toMarkupList(),e):"function"===typeof d.toMarkup?e.push(d.toMarkup()):"function"===typeof d.toString?e.push(a.htmlencode(d.toString())):c(d,"[object]",e);break;case "undefined":c(d,"[undefined]",e);break;case "string":e.push(a.htmlencode(d));break;case "boolean":e.push(String(d));break;case "number":e.push(String(d));break;case "function":c(d,"[function]",e)}return e};a.flatten_markup=function(a){return b(a,[]).join("")};
a.make_attr_safe=function(c){return a.bless(a.flatten_markup(c).replace(/\</g,"&lt;").replace(/\>/g,"&gt;").replace(/\"/g,"&quot;"))}})(mjt);
(function(a){a.error_html=function(c,b,d){var e=[];if(b&&c.lineNumber){var f=c.lineNumber,b=b.split("\n");0>f&&(f=0);f>=b.length&&(f=b.length-1);var g=f-10;0>g&&(g=0);var i=[];for(e.push(a.bless(["\n<pre>"]));g<f;g++)i.push(b[g]);e.push(i.join("\n"));e.push(a.bless(['</pre>\n<pre style="color:red">']));e.push(b[f]+"\n");e.push(a.bless(["</pre>\n<pre>"]));i=[];for(g=f+1;g<b.length;g++)i.push(b[g]);e.push(i.join("\n"));e.push(a.bless(["</pre>\n"]))}c=[a.bless(['<div class="mjt_error"']),d?[a.bless([' id="']),
d,a.bless(['"'])]:[],a.bless([">"]),c.name,": ",c.message,e,a.bless(["</div>\n"])];return c=c.concat(e)};a.Codeblock=function(a,b){this.name=a;this.codestr=b;this.baseline=this.basefile=null};a.Codeblock.prototype.handle_exception=function(a,b){if("undefined"==typeof b.mjt_error){var d=!1;"undefined"!=typeof b.sourceURL&&(b.fileName=b.sourceURL);"undefined"!=typeof b.line&&(d=!0,b.lineNumber=b.line);b.mjt_error=b instanceof Error?{fileName:b.fileName,lineNumber:b.lineNumber,name:b.name,message:b.message,
stack:b.stack,rhinoException:b.rhinoException}:{name:"Unknown exception",fileName:"",message:""+b};if(this.basefile||d)if("string"==typeof b.stack){if(d=this.basefile.replace(/(\W)/g,"\\$1")+":(\\d+)\n",d=RegExp(d),d=d.exec(b.stack))d=parseInt(d[1])-this.baseline,0<d&&this.log_error_context(a,b,d)}else if(b.fileName==this.basefile||d)d=d?b.lineNumber-1:b.lineNumber-this.baseline,0<d&&(b.mjt_error.lineNumber=d,b.mjt_error.fileName="<generated code>",this.log_error_context(a,b,d))}};a.Codeblock.prototype.log_error_context=
function(c,b,d){for(var e=this.extract_context(this.codestr,d,5),d="---"+d+"--\>  ",f=[],g=0;g<d.length;g++)f.push(" ");f=f.join("");e=[f,e.prev_lines.join("\n"+f),"\n",d,e.the_line,"\n",f,e.next_lines.join("\n"+f)].join("");a.error("error",c,"\n    "+b.name+": "+b.message+"\n",e)};a.Codeblock.prototype.extract_context=function(a,b,d){a=a.split("\n");0>b&&(b=0);b>=a.length&&(b=a.length-1);var e=b-d;0>e&&(e=0);var f=[];for(line=e;line<b;line++)f.push(a[line]);var e=a[b],g=[];for(line=b+1;line<a.length&&
line<b+d;line++)g.push(a[line]);return{prev_lines:f,the_line:e,next_lines:g}};a.Codeblock.prototype.evaluate=function(){var c=(new Date).getTime(),b=[this.codestr],b=["var __mjt_eval = (function(){",this.codestr,"})(); __mjt_eval;\n"],b=b.join("");a.debug&&a.log("evaluating code "+this.name,{click_me:"view code",codestr:b});var d;if("undefined"==typeof window||"undefined"==typeof window.navigator.appName)d=eval(b);else{try{null()}catch(e){this.baseline=e.lineNumber+2,this.basefile=e.fileName}try{d=
eval(b)}catch(f){throw this.handle_exception("evaluating codeblock "+this.name,f),f;}}c=(new Date).getTime()-c;a.note("evaluated code in ",c,"msec, ",b.length,"chars, got ",typeof d);return d}})(mjt);
(function(a){a._eventcb={};a.kws=function(){for(var a={},b=0;b<arguments.length;b+=2)a[arguments[b]]=arguments[b+1];return a};a.foreach=function(a,b,d){var e,f;if("string"==typeof b||b instanceof Array||"object"==typeof jQuery&&b instanceof jQuery){f=b.length;for(e=0;e<f;e++)d.apply(a,[e,b[e]])}else if("object"===typeof b)if("undefined"!=typeof document&&"undefined"!=typeof b.item&&b.item===document.childNodes.item){f=b.length;for(e=0;e<f;e++)d.apply(a,[e,b.item(e)])}else for(e in b)b.hasOwnProperty(e)&&
d.apply(a,[e,b[e]])};a.ondomready=function(c,b){var d=a._ondomready_queue;null===a._ondomready_timer&&(a._ondomready_timer=setTimeout(a._ondomready_run,20));d.push(c);d.push(b)};a._ondomready_queue=[];a._ondomready_timer=null;a._ondomready_run=function(){a._ondomready_timer=null;var c=a._ondomready_queue;for(a._ondomready_queue=[];c.length;){var b=c.shift(),d=c.shift();b.apply(d)}};a.cleanup_noquote=function(c,b){var d=a.flatten_markup(c),d=d.replace(/&quot;/g,'"').replace(/&lt;/g,"<").replace(/&gt;/g,
">").replace(/&amp;/g,"&");"undefined"!=typeof b&&(d=d.replace(RegExp("</("+b+"\\s*)>","ig"),"<\\/$1>"));return a.bless(d)};a.ref=function(c){c=['<a href="view?name=',a.formquote(c),'">',a.htmlencode(c),"</a>"].join("");return new a.Markup(c)};a.TemplateCall=function(a){this.raw_tfunc=a;delete this._markup};a.TemplateCall.prototype.toMarkupList=function(){return this._markup};a.TemplateCall.prototype.toMarkup=function(){return a.flatten_markup(this._markup)};a.TemplateCall.prototype.redisplay=function(){var a=
new this.this_tfunc;a.prev_tcall=this;a.subst_id=this.subst_id;a.render(this.targs).display();return a};a.TemplateCall.prototype.display=function(c){if("undefined"!=typeof acre)return this;"undefined"!=typeof c&&(this.subst_id=c);c=this.subst_id;if("string"==typeof c){var b=document.getElementById(c);if(b)c=b;else return a.note("no element with id "+c),null}"IFRAME"==c.nodeName&&(c=c.contentWindow||c.contentDocument,c.document&&(c=c.document),c=c.getElementsByTagName("body")[0]);if(!c)return this;
"undefined"!=typeof this._markup&&a.replace_html(c,this);return this};a.TemplateCall.prototype.render=function(c){"undefined"!=typeof c&&(this.targs=c);c=this.raw_tfunc;if("undefined"==typeof window||"undefined"==typeof window.navigator.appName)return this._markup=c.apply(this,this.targs),this;try{this._markup=c.apply(this,this.targs)}catch(b){b.tcall=this;c=this.tpackage._codeblock;if(null===c)throw b;c.handle_exception("applying tfunc "+this.signature,b);var c=[],d;for(d in this.tasks){var e=this.tasks[d];
"object"===typeof e&&null!==e?c.push(d+":"+e.state):c.push(d+":"+typeof e)}this._markup=new a.MarkupList(a.bless("<h3>error applying "),this.signature," to id=",this.subst_id,a.bless("</h3>"),"states:[",c.join(" "),"]");throw b;}return this};a.TemplateCall.prototype.mktask=function(a,b){this.tasks[a]=b;var d=this;"init"==b.state&&b.enqueue();return b.ondone(function(){d.render().display()})};a.tfunc_factory=function(c,b,d,e){var f=function(){var b=arguments.callee;if(this instanceof b)this.tasks=
{},this.defs=this.exports={},"function"==typeof a.deprecate&&a.deprecate(this,"defs",".exports");else{for(var c=new b,d=[],e=0;e<arguments.length;e++)d[e]=arguments[e];e=c.signature.replace(/\(.*\)$/,"");c.subst_id=b.prototype.has_tasks?a.uniqueid("tcall__"+e):null;c.render(d);return c}};f.prototype=new a.TemplateCall(b);f.prototype.signature=c;f.prototype.tpackage=d;f.prototype.has_tasks=e;f.prototype.source_microdata=b.source_microdata;return f.prototype.this_tfunc=f}})(mjt);
(function(a){a.TemplatePackage=function(){this.namespace=this._template_fragments=this.output_mode=this.debug_locs=this._codeblock=this._compiled=this._template_strings=this.source=null};a.TemplatePackage.prototype.runtime={_break_token:a._break_token,_continue_token:a._continue_token,bless:a.bless,cleanup_noquote:a.cleanup_noquote,foreach:a.foreach,htmlencode:a.htmlencode,make_attr_safe:a.make_attr_safe,new_markuplist:function(){return new a.MarkupList},ondomready:a.ondomready,ref:a.ref,tfunc_factory:a.tfunc_factory,
uniqueid:a.uniqueid};a.TemplatePackage.prototype.init_from_json=function(c){"undefined"!=typeof c.file&&(this.source=c.file);"undefined"!=typeof c.stringtable&&(this._template_strings=c.stringtable);this._codeblock=null;"string"==typeof c.code?this._codeblock=new a.Codeblock(this.source,c.code):"function"==typeof c.code&&(this._compiled=c.code);"undefined"!=typeof c.debug_locs&&(this.debug_locs=c.debug_locs);"undefined"!=typeof c.output_mode&&(this.output_mode=c.output_mode);return this};a.TemplatePackage.prototype.init_from_js=
function(a){var b=a.def;this.init_from_json(a.info);this._compiled=b;return this};a.TemplatePackage.prototype.get_metadata=function(){return{file:this.source,stringtable:this._template_strings,debug_locs:this.debug_locs,output_mode:this.output_mode}};a.TemplatePackage.prototype.toJSON=function(){var c=this.get_metadata();null===this._codeblock?(a.warn("TemplatePackage.toJSON: complete source code unavailable",this.source),c.code=this._compiled):c.code=this._codeblock.codestr;return JSON.stringify(c)};
a.TemplatePackage.prototype.toJS=function(){var c=null;null===this._codeblock?(a.warn("TemplatePackage.toJS: complete source code unavailable",this.source),c=this._compiled):c="(function () {"+this._codeblock.codestr+"})()";return["{def: ",c,",\ninfo:",JSON.stringify(this.get_metadata()),"}\n"].join("")};a.TemplatePackage.prototype.lookup_line=function(a){return!(debug_locs instanceof Array)||a>=this.debug_locs.length?null:this.debug_locs[a-1]};a.TemplatePackage.prototype.compile_document=function(c,
b){(new Date).getTime();"undefined"==typeof b&&(b=new a.TemplateCompiler);b.compile_top(c,"rawmain()");(new Date).getTime();return this.init_from_json({source:this.source,stringtable:b.strings,code:b.codestr+"; return rawmain;",debug_locs:b.debug_locs,output_mode:b.output_mode})};a.TemplatePackage.prototype.load_document=function(a,b){this.source+="#"+a.id;this.compile_document(a);return this.load(b)};a.TemplatePackage.prototype.toplevel=function(a){null===this.namespace&&this.load(a);return this.namespace};
a.TemplatePackage.prototype.toString=function(){null===this.namespace&&this.load(targs);return a.flatten_markup(this.namespace._main.prototype.tpackage.tcall)};a.TemplatePackage.prototype.load=function(c){this._template_fragments=[];for(var b=0;b<this._template_strings.length;b++)this._template_fragments[b]=a.bless(this._template_strings[b]);null===this._compiled&&(null===this._codeblock?a.error("TemplatePackage has no code",this.source):this._compiled=this._codeblock.evaluate());"undefined"==typeof c&&
(c=[]);this._args=c;c=a.tfunc_factory("_main()",this._compiled,this,!1,!0);b=new c;b.render(this._args);this.tcall=b;b.pkg=this;"undefined"!=typeof this._compiled.doc_content_type&&(b.doc_content_type=this._compiled.doc_content_type);if("undefined"!=typeof b.exports._main)throw Error("_main() is illegal as a template function name");this.namespace=b.exports;this.namespace._main=c;if("undefined"!=typeof b.exports.main)throw Error("main() is illegal as a template function name");this.namespace.main=
c;"function"==typeof a.deprecate&&a.deprecate(this.namespace,"main","._main");return this}})(mjt);
"undefined"!=typeof jQuery&&function(a){function c(a,c,f){var g="";if("string"===typeof a){var i=b[a];"object"===typeof i?(i=i[c],"function"===typeof i?g=mjt.flatten_markup(i.apply(this,f)):console.warn("acre template '"+c+"' does not exist in package '"+a+"'")):console.warn("acre template package '"+a+"' has not been registered")}else g=mjt.flatten_markup(a);return g}if("undefined"!=typeof a){var b={};a(window).bind("acre.template.register",function(a,c){var f=c.pkgid,g=c.source;"string"===typeof f&&
"object"===typeof g&&(g.def&&(g=(new mjt.TemplatePackage).init_from_js(g).toplevel()),b[f]=g)});a.fn.mjt=function(a){var b=mjt.flatten_markup(a);return this.each(function(){this.innerHTML=b})};a.fn.acre=function(b,e,f){return this.each(function(){a(this).html(c(b,e,f))})};a.acre=function(a,b,f){return c(a,b,f)}}}(jQuery);
