
/*
 * Copyright 2010, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Additional Licenses for Third Party components can be found here:
 * http://wiki.freebase.com/wiki/Freebase_Site_License
 *
 */
/*
 
 jQuery Tools @VERSION / Expose - Dim the lights

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/toolbox/expose.html

 Since: Mar 2010
 Date: @DATE 
 
 jQuery Tools @VERSION Overlay - Overlay base. Extend it.

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/overlay/

 Since: March 2008
 Date: @DATE 
*/
(function(c,f){var b=window.propbox={init:function(a,d){d=c.extend({lang:"/lang/en"},d);if(!d.base_ajax_url)throw new Error("base_ajax_url required in propbox options");if(!d.base_static_url)throw new Error("base_static_url required in propbox options");if(!d.id)throw new Error("topic id required in propbox options");if(!d.lang)throw new Error("lang required in propbox options");b.options=d;b.kbs=new f(a);b.kbs.set_next(b.kbs.get_current(),c(".kbs:visible:first",a,true));c(".kbs",a).live("click",
function(){var e=b.kbs.get_current();b.kbs.set_next(e,c(this),true)}).live("edit",function(){var e=c(this).find(".headmenu:first").data("submenu");e&&c("li:first a:first",e).click()});b.init_menus(a)},init_menus:function(a,d){a=c(a||document);d&&c(".nicemenu",a).nicemenu();(a&&a.is(".data-row")?a:c(".data-row",a)).hover(b.row_menu_hoverover,b.row_menu_hoverout);c(".nicemenu .headmenu",a).add(c(".nicemenu .default-action",a)).click("click",function(){if(b.kbs){var e=b.kbs.get_current();e&&b.kbs.set_next(e,
c(this).parents(".kbs:first"),true)}return false})},row_menu_hoverover:function(){var a=c(this);b.row_menu_hoverover.timeout=setTimeout(function(){a.addClass("row-hover")},300)},row_menu_hoverout:function(){clearTimeout(b.row_menu_hoverover.timeout);c(this).removeClass("row-hover")},get_script:function(a,d){var e=b.get_script.cache;if(!e)e=b.get_script.cache={};var g=e[a];if(g)if(g.state===1)g.callbacks.push(d);else g.state===4&&d();else{g=e[a]={state:0,callbacks:[d]};c.ajax({url:b.options.base_static_url+
a,dataType:"script",beforeSend:function(){g.state=1},success:function(){g.state=4;c.each(g.callbacks,function(h,j){j()})},error:function(){g.state=-1}})}},prop_edit:function(a,d){var e=c(a).parents(".submenu").data("headmenu").parents(".property-section").find(".data-section .data-row:first:visible .nicemenu:first .headmenu:first a");e.length?e.click():b.prop_add(a,d);return false},prop_add:function(a,d){var e=c(a).parents(".submenu").data("headmenu").parents(".property-section");if(e.is(".editing"))return false;
e.addClass("editing");b.get_script("/propbox-edit.mf.js",function(){b.edit.prop_add_begin(e,d)});return false},value_edit:function(a){var d=c(a).parents(".submenu").data("headmenu").parents(".data-row:first"),e=d.parents(".property-section");if(e.is(".editing"))return false;e.addClass("editing");b.get_script("/propbox-edit.mf.js",function(){b.edit.value_edit_begin(e,d)});return false},value_delete:function(a){var d=c(a).parents(".submenu").data("headmenu").parents(".data-row:first"),e=d.parents(".property-section");
if(e.is(".editing"))return false;e.addClass("editing");b.get_script("/propbox-edit.mf.js",function(){b.edit.value_delete_begin(e,d)});return false},close_message:function(a){c(a).parents(".row-msg:first").remove();return false}}})(jQuery,window.kbs);
(function(c){function f(){if(c.browser.msie){var i=c(document).height(),k=c(window).height();return[window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth,i-k<20?k:i]}return[c(document).width(),c(document).height()]}function b(i){if(i)return i.call(c.mask)}c.tools=c.tools||{version:"@VERSION"};var a;a=c.tools.expose={conf:{maskId:"exposeMask",loadSpeed:"slow",closeSpeed:"fast",closeOnClick:true,closeOnEsc:true,zIndex:9998,opacity:0.8,startOpacity:0,color:"#fff",onLoad:null,
onClose:null}};var d,e,g,h,j;c.mask={load:function(i,k){if(g)return this;if(typeof i=="string")i={color:i};i=i||h;h=i=c.extend(c.extend({},a.conf),i);d=c("#"+i.maskId);if(!d.length){d=c("<div/>").attr("id",i.maskId);c("body").append(d)}var l=f();d.css({position:"absolute",top:0,left:0,width:l[0],height:l[1],display:"none",opacity:i.startOpacity,zIndex:i.zIndex});i.color&&d.css("backgroundColor",i.color);if(b(i.onBeforeLoad)===false)return this;i.closeOnEsc&&c(document).bind("keydown.mask",function(m){m.keyCode==
27&&c.mask.close(m)});i.closeOnClick&&d.bind("click.mask",function(m){c.mask.close(m)});c(window).bind("resize.mask",function(){c.mask.fit()});if(k&&k.length){j=k.eq(0).css("zIndex");c.each(k,function(){var m=c(this);/relative|absolute|fixed/i.test(m.css("position"))||m.css("position","relative")});e=k.css({zIndex:Math.max(i.zIndex+1,j=="auto"?0:j)})}d.css({display:"block"}).fadeTo(i.loadSpeed,i.opacity,function(){c.mask.fit();b(i.onLoad)});g=true;return this},close:function(){if(g){if(b(h.onBeforeClose)===
false)return this;d.fadeOut(h.closeSpeed,function(){b(h.onClose);e&&e.css({zIndex:j})});c(document).unbind("keydown.mask");d.unbind("click.mask");c(window).unbind("resize.mask");g=false}return this},fit:function(){if(g){var i=f();d.css({width:i[0],height:i[1]})}},getMask:function(){return d},isLoaded:function(){return g},getConf:function(){return h},getExposed:function(){return e}};c.fn.mask=function(i){c.mask.load(i);return this};c.fn.expose=function(i){c.mask.load(i,this);return this}})(jQuery);
(function(c){function f(d,e){var g=this,h=d.add(g),j=c(window),i,k,l,m=c.tools.expose&&(e.mask||e.expose),n=Math.random().toString().slice(10);if(m){if(typeof m=="string")m={color:m};m.closeOnClick=m.closeOnEsc=false}var p=e.target||d.attr("rel");k=p?c(p):d;if(!k.length)throw"Could not find Overlay: "+p;d&&d.index(k)==-1&&d.click(function(o){g.load(o);return o.preventDefault()});c.extend(g,{load:function(o){if(g.isOpened())return g;var r=a[e.effect];if(!r)throw'Overlay: cannot find effect : "'+e.effect+
'"';e.oneInstance&&c.each(b,function(){this.close(o)});o=o||c.Event();o.type="onBeforeLoad";h.trigger(o);if(o.isDefaultPrevented())return g;l=true;m&&c(k).expose(m);var q=e.top,t=e.left,u=k.outerWidth({margin:true}),v=k.outerHeight({margin:true});if(typeof q=="string")q=q=="center"?Math.max((j.height()-v)/2,0):parseInt(q,10)/100*j.height();if(t=="center")t=Math.max((j.width()-u)/2,0);r[0].call(g,{top:q,left:t},function(){if(l){o.type="onLoad";h.trigger(o)}});m&&e.closeOnClick&&c.mask.getMask().one("click",
g.close);e.closeOnClick&&c(document).bind("click."+n,function(s){c(s.target).parents(k).length||g.close(s)});e.closeOnEsc&&c(document).bind("keydown."+n,function(s){s.keyCode==27&&g.close(s)});return g},close:function(o){if(!g.isOpened())return g;o=o||c.Event();o.type="onBeforeClose";h.trigger(o);if(!o.isDefaultPrevented()){l=false;a[e.effect][1].call(g,function(){o.type="onClose";h.trigger(o)});c(document).unbind("click."+n).unbind("keydown."+n);m&&c.mask.close();return g}},getOverlay:function(){return k},
getTrigger:function(){return d},getClosers:function(){return i},isOpened:function(){return l},getConf:function(){return e}});c.each("onBeforeLoad,onStart,onLoad,onBeforeClose,onClose".split(","),function(o,r){c.isFunction(e[r])&&c(g).bind(r,e[r]);g[r]=function(q){c(g).bind(r,q);return g}});i=k.find(e.close||".close");if(!i.length&&!e.close){i=c('<a class="close"></a>');k.prepend(i)}i.click(function(o){g.close(o)});e.load&&g.load()}c.tools=c.tools||{version:"@VERSION"};c.tools.overlay={addEffect:function(d,
e,g){a[d]=[e,g]},conf:{close:null,closeOnClick:true,closeOnEsc:true,closeSpeed:"fast",effect:"default",fixed:!c.browser.msie||c.browser.version>6,left:"center",load:false,mask:null,oneInstance:true,speed:"normal",target:null,top:"10%"}};var b=[],a={};c.tools.overlay.addEffect("default",function(d,e){var g=this.getConf(),h=c(window);if(!g.fixed){d.top+=h.scrollTop();d.left+=h.scrollLeft()}d.position=g.fixed?"fixed":"absolute";this.getOverlay().css(d).fadeIn(g.speed,e)},function(d){this.getOverlay().fadeOut(this.getConf().closeSpeed,
d)});c.fn.overlay=function(d){var e=this.data("overlay");if(e)return e;if(c.isFunction(d))d={onBeforeLoad:d};d=c.extend(true,{},c.tools.overlay.conf,d);this.each(function(){e=new f(c(this),d);b.push(e);c(this).data("overlay",e)});return d.api?e:this}})(jQuery);
(function(c){c.fn.mqlkey=function(b){return this.each(function(){var a=c(this);if(a.is(":text")){var d=a.data("mqlkey");d&&d._destroy();d=new f(this,b);a.data("mqlkey",d)}})};var f=c.mqlkey=function(b,a){this.options=c.extend(true,{},f.defaults,a);this.input=c(b);this.original=this.input.val();this.init()};f.prototype={init:function(){var b=this;this.input.bind("keyup.mqlkey",function(a){b.textchange(a)}).bind(c.browser.msie?"paste.mqlkey":"input.mqlkey",function(a){b.textchange(a)});if(this.options.source){this.source=
c(this.options.source);this.source_generate=true;this.input.bind("change.mqlkey",function(){b.source_generate=false});this.source.bind("change.mqlkey",function(){if(b.source_generate){var a=f.from(b.source.val());b.input.val(a).trigger("keyup")}})}},_destroy:function(){this.input.unbind(".mqlkey");this.source&&this.source.unbind("change.mqlkey")},textchange:function(b){clearTimeout(this.textchange_timeout);var a=this;this.textchange_timeout=setTimeout(function(){a.textchange_delay(b)},200)},textchange_delay:function(){this.input.trigger("textchange");
var b=c.trim(this.input.val());return b===this.original&&b!==""?this.valid(b):f.reserved_word(b)?this.invalid(b,b+" is a reserved word."):f.test(b,this.options.schema)?b.length<this.options.minlen?this.invalid(b):this.options.check_key?this.check_key(b):this.valid(b):this.invalid(b)},check_key:function(b){var a=this;if(this.xhr){this.xhr.abort();this.xhr=null}var d={id:null,key:{namespace:this.options.namespace,value:b}};clearTimeout(this.check_key.timeout);this.check_key.timeout=setTimeout(function(){a.xhr=
a.options.mqlread(d,function(e){return e?a.invalid(b,"Key already exists"):a.valid(b)},function(e){return e?a.invalid(e.responseText()):a.invalid("mqlread error!")})},200)},valid:function(b){this.input.trigger("valid",b)},invalid:function(b,a){if(!a){a=this.options.minlen>1?"Key must be "+this.options.minlen+" or more alphanumeric characters":"Key must be alphanumeric";a+=", lowercase, begin with a letter and not end with a non-alphanumeric character. Underscores are allowed but not consecutively."}this.input.trigger("invalid",
a)}};c.extend(f,{defaults:{minlen:1,check_key:true,namespace:"/",mqlread:function(b,a,d){return f.mqlread(null,b,a,d)},source:null,schema:false},mqlread:function(b,a,d,e){b={url:b||"http://api.freebase.com/api/service/mqlread",data:{query:JSON.stringify({query:a})},dataType:"jsonp",success:function(g){return d(g.result)},error:e};return c.ajax(b)},from:function(b){b=b.toLowerCase();b=b.replace(/[^a-z0-9]/g,"_");b=b.replace(/\_\_+/g,"_");b=b.replace(/[^a-z0-9]+$/,"");b=b.replace(/^[^a-z]+/,"");if(f.reserved_word(b))b=
"x_"+b;return b},reservedwords:"meta typeguid left right datatype scope attribute relationship property link class future update insert delete replace create destroy default sort limit offset optional pagesize cursor index !index for while as in is if else return count function read write select var connect this self super xml sql mql any all macro estimate-count",typeonlywords:"guid id object domain name key type keys value timestamp creator permission namespace unique schema reverse",_reserved_word:null,
reserved_word:function(b){if(!f._reserved_word){f._reserved_word={};c.each([f.reservedwords,f.typeonlywords],function(a,d){c.each(d.split(" "),function(e,g){f._reserved_word[g]=1})})}return f._reserved_word[b]===1},fast:/^[A-Za-z0-9](?:[_-]?[A-Za-z0-9])*$/,slow:/^(?:[A-Za-z0-9]|\$[A-F0-9]{4})(?:[_-]?[A-Za-z0-9]|[_-]?\$[A-F0-9]{4})*$/,schema:/^[a-z](?:_?[a-z0-9])*$/,test:function(b,a){if(a)return f.schema.test(b);return f.fast.test(b)||f.slow.test(b)}})})(jQuery);
(function(c,f){f.require("dojo.date.stamp");f.require("dojo.date.locale");f.require("dojo.number");c.fn.validate_input=function(a){return this.each(function(){var d=c(this);if(d.is(":text")){var e=d.data("$.validate_input");e&&e._destroy();e=new b(this,a);d.data("$.validate_input",e)}})};var b=c.validate_input=function(a,d){var e=this.options=c.extend(true,{},b.defaults,d);if(typeof e.validator!=="function")throw"A validator is required";if(!e.lang)e.lang="/lang/en";e.lang=e.lang==="/lang/en"?["lang/en"]:
[e.lang,"/lang/en"];e.locales=[];c.each(e.lang,function(h,j){e.locales[h]=f.i18n.normalizeLocale(j.split("/").pop())});this.input=c(a);this.init();var g=this;this.input.bind("remove",function(){g._destroy()});return this};b.prototype={init:function(){var a=this;this.input.bind("keyup.validate_input",function(d){a.textchange(d)}).bind(c.browser.msie?"paste.validate_input":"input.validate_input",function(d){a.textchange(d)}).bind("keypress.validate_input",function(d){d.keyCode===13&&a.validate(true)}).bind("blur.validate_input",
function(){a.validate(true)})},_destroy:function(){this.input.unbind(".validate_input")},valid:function(a){this.input.trigger("valid",a)},invalid:function(a,d){this.input.trigger("invalid",d)},empty:function(){this.input.trigger("empty")},textchange:function(){clearTimeout(this.textchange_timeout);var a=this;this.textchange_timeout=setTimeout(function(){a.validate()},200)},validate:function(a){a&&clearTimeout(this.textchange_timeout);a=this.options;var d=c.trim(this.input.val());if(d==="")return this.empty();
try{return this.valid(a.validator(d,a))}catch(e){return this.invalid(d,""+e)}}};c.extend(b,{defaults:{validator:function(a){return{text:a,value:a}}},log:function(){},invalid:function(a,d,e,g){throw new Error("Invalid "+e+(g?": "+g:""));},text:function(a,d){if(a.lengh>4096)return this.invalid(a,d,type,"Text too long");return{text:a,value:a}},topic:function(){return b.defaults.validator},enumerated:function(){return b.defaults.validator},"boolean":function(){return b.defaults.validator},uri:function(a,
d){var e=b.uri.regex;if(!e)e=b.uri.regex=/^(https?|ftp):\/\/(((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:)*@)?(((\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5]))|((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?)(:\d*)?)(\/((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)+(\/(([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)*)*)?)?(\?((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|[\uE000-\uF8FF]|\/|\?)*)?(\#((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|\/|\?)*)?$/i;
if(e.test(a))return{text:a,value:a};return b.invalid(a,d,"uri")},"int":function(a,d){return b.number.parse(a,d,false)},"float":function(a,d){return b.number.parse(a,d,true)},number:function(a,d,e){return b.number.parse(a,d,e)},datetime:function(a,d){return b.datetime.parse(a,d)},mqlkey:function(a,d){var e=b.mqlkey.regex;if(!e)e=b.mqlkey.regex=/^[A-Za-z0-9][A-Za-z0-9_-]*$/;if(e.test(a))return{text:a,value:a};return b.invalid(a,d,"mqlkey")}});c.extend(b.number,{parse:function(a,d,e){var g=d&&d.locales||
["en"],h,j;h=0;for(j=g.length;h<j;h++){var i=g[h];d=f.number.parse(a,{locale:i});if(!isNaN(d)){a={};if(e){a.value=d;a.text=f.number.format(d,{locale:i})}else{a.value=f.number.round(d,0);a.text=f.number.format(a.value,{locale:i})}return a}}throw b.invalid("number",a);}});c.extend(b.datetime,{formats:["yyyy",["dateFormatItem-y"],"yyyy-MM",["dateFormatItem-yM","dateFormatItem-yMMM"],"yyyy-MM-dd",["dateFormat-short","dateFormat-medium","dateFormat-long"]],parse:function(a,d){if(!f.date.stamp._isoRegExp)f.date.stamp._isoRegExp=
/^(?:(-?\d{4})(?:-(\d{2})(?:-(\d{2}))?)?)?(?:T(\d{2}):(\d{2})(?::(\d{2})(.\d+)?)?((?:[+-](\d{2}):(\d{2}))|Z)?)?$/;var e=f.date.stamp.fromISOString(a);if(e)return{text:a,value:a,date:e};var g=d&&d.locales||["en"],h,j,i,k,l,m;h=0;for(j=g.length;h<j;h++){var n=g[h],p=f.date.locale._getGregorianBundle(n);i=0;for(k=b.datetime.formats.length;i<k;i+=2){var o=b.datetime.formats[i],r=b.datetime.formats[i+1];l=0;for(m=r.length;l<m;l++){var q=p[r[l]];if(q){q=i18n.normalize_pattern(q);try{e=f.date.locale.parse(a,
{datePattern:q,selector:"date",locale:n});return{text:a,value:f.date.locale.format(e,{datePattern:o,selector:"date"}),date:e}}catch(t){}}}}}throw b.invalid("datetime",a);}})})(jQuery,dojo);
(function(c){c.fn.data_input=function(f){return this.each(function(){var b=c(this),a=b.data("$.data_input");a&&a._destroy();a=new c.data_input(this,f);b.data("$.data_input",a)})};c.data_input=function(f,b){this.options=c.extend(true,{},c.data_input.defaults,b);this.container=c(f);this.metadata=this.container.metadata();this.input=c(":input",this.container);this.init();var a=this;this.input.bind("remove",function(){a._destroy()})};c.data_input.prototype={init:function(){var f=this,b=this.container,
a=this.input,d=this.options;a.bind("focusin.data_input",function(){f.container.addClass("focus")}).bind("focusout.data_input",function(){f.container.removeClass("focus")}).bind("valid.data_input",function(e,g){var h={name:f.input.attr("name")};if(g.id)h.id=g.id;else{h.value=g.value;if(f.metadata.type==="/type/text")h.lang=f.metadata.lang||d.lang}f.container.data("data",h);f.container.removeClass("error").addClass("valid");f.container.trigger("valid")}).bind("invalid.data_input",function(){f.container.removeData("data");
f.container.removeClass("valid").addClass("error");f.container.trigger("invalid")}).bind("empty.data_input",function(){var e={name:f.input.attr("name")};if(f.metadata&&f.metadata.lang)e.lang=f.metadata.lang;f.container.data("data",e);f.container.removeClass("valid").removeClass("error");f.container.trigger("empty")}).bind("keypress.data_input",function(e){e.keyCode===13&&!e.isDefaultPrevented()&&f.container.trigger("submit")}).bind("keyup.data_input",function(e){e.keyCode===27&&f.container.trigger("cancel")});
if(b.is(".topic")){b=c.extend(true,{},d.suggest,c.data_input.suggest_options(f.metadata.type));a.validate_topic(b).bind("valid.data_input",function(e,g){f.fb_select(g)}).bind("invalid.data_input",function(){f.fb_textchange()});if(this.metadata&&this.metadata.id){a.data("data.suggest",this.metadata);this.validate()}}else if(b.is(".text"))a.validate_input({validator:c.validate_input.text});else if(b.is(".datetime"))a.validate_input({validator:c.validate_input.datetime,lang:d.lang});else if(b.is(".enumerated")){a.validate_enumerated().bind("valid.data_input",
function(e,g){f.fb_select(g)}).bind("invalid.data_input",function(){f.fb_textchange()});this.metadata&&this.metadata.id&&this.validate()}else if(b.is(".int"))a.validate_input({validator:c.validate_input["int"],lang:d.lang});else if(b.is(".float"))a.validate_input({validator:c.validate_input["float"],lang:d.lang});else if(b.is(".uri"))a.validate_input({validator:c.validate_input.uri});else if(b.is(".boolean"))a.validate_boolean();else if(b.is(".enumeration"))a.validate_input({validator:c.validate_input.mqlkey});
else if(b.is(".rawstring"))a.validate_input({validator:c.validate_input.text});else throw new Error("Invalid data-input: "+b.attr("class"));},_destroy:function(){this.input.unbind(".data_input")},validate:function(){var f=this.input;c.each(["$.validate_topic","$.validate_input","$.validate_enumerated","$.validate_boolean"],function(b,a){var d=f.data(a);if(d){d.validate(true);return false}})},reset:function(){this.container.removeData("data");if(this.input.is(":text"))this.input.val("");else if(this.input.is("select"))this.input[0].selectedIndex=
0;else this.input.is(":radio")&&this.input.each(function(){this.checked=false})},fb_textchange:function(){},fb_select:function(){},ajax_beforeSend:function(f){if(!this.xhr_queue)this.xhr_queue=[];this.xhr_queue.push(f);this.container.trigger("loading")},ajax_complete:function(f){if(!this.xhr_queue)this.xhr_queue=[];for(var b=0,a=this.xhr_queue.length;b<a;b++)if(f===this.xhr_queue[b]){this.xhr_queue.splice(b,1);break}this.xhr_queue.length===0&&this.container.trigger("loading_complete")}};c.extend(c.data_input,
{defaults:{suggest:{service_url:"http://www.freebase.com",service_path:"/private/suggest",flyout_service_url:"http://www.freebase.com",flyout_service_path:"/private/flyout",category:"object",type:"/common/topic"}},is_metaweb_system_type:function(f){return f.indexOf("/type/")===0||f.indexOf("/common/")===0&&f!=="/common/topic"||f.indexOf("/freebase/")===0&&f.indexOf("_profile")===f.length-8},suggest_options:function(f){var b={category:"instance",type:f,type_strict:c.data_input.is_metaweb_system_type(f)?
"any":"should"},a=["any","type:"+f,"without:fus","without:inst"];c.each(["user","domain","type"],function(d,e){if(f==="/freebase/"+e+"_profile"){a.push("type:/type/"+e);return false}});f==="/book/book_subject"&&a.push("type:/base/skosbase/skos_concept");b.filter="("+a.join(" ")+")";return b}});c.fn.validate_topic=function(f){return this.each(function(){var b=c(this);if(b.is(":text")){var a=b.data("$.validate_topic");a&&a._destroy();a=new c.validate_topic(this,f);b.data("$.validate_topic",a)}})};c.validate_topic=
function(f,b){this.options=c.extend(true,{},b);this.input=c(f);this.init()};c.validate_topic.prototype={init:function(){var f=this;this.input.suggest(this.options).bind("fb-textchange.validate_topic",function(){f.input.val()===""?f.empty():f.invalid()}).bind("fb-select.validate_topic",function(b,a){f.input.val(a.name!=null?a.name:a.id);f.valid(a)})},invalid:function(){this.input.trigger("invalid")},valid:function(f){this.input.trigger("valid",f)},empty:function(){this.input.trigger("empty")},_destroy:function(){this.input.unbind(".validate_topic")},
validate:function(){if(this.input.val()==="")this.empty();else{var f=this.input.data("data.suggest");f?this.valid(f):this.invalid()}}};c.fn.validate_enumerated=function(f){return this.each(function(){var b=c(this);if(b.is("select")){var a=b.data("$.validate_enumerated");a&&a._destroy();a=new c.validate_enumerated(this,f);b.data("$.validate_enumerated",a)}})};c.validate_enumerated=function(f,b){this.options=c.extend(true,{},b);this.input=c(f);this.init()};c.validate_enumerated.prototype={init:function(){var f=
this;this.input.bind("change.validate_enumerated, keypress.validate_enumerated",function(){this.selectedIndex===0?f.empty():f.valid({text:c(":selected",this).text(),id:this.value})})},invalid:function(){this.input.trigger("invalid")},valid:function(f){this.input.trigger("valid",f);this.input.trigger("fb-select",f)},empty:function(){this.input.trigger("empty")},_destroy:function(){this.input.unbind(".validate_enumerated")},validate:function(){var f=this.input[0];f.selectedIndex>0?this.valid({text:c(":selected",
this.input).text(),id:f.value}):this.empty()}};c.fn.validate_boolean=function(f){var b,a;this.each(function(){var e=c(this);if(e.is(":radio"))if(e.val().toLowerCase()==="true")b=e;else if(e.val().toLowerCase()==="false")a=e});if(b&&a){var d=b.data("$.validate_boolean");d&&d._destroy();d=new c.validate_boolean(b,a,f);b.data("$.validate_boolean",d)}return this};c.validate_boolean=function(f,b,a){this.options=c.extend(true,{},a);this.tradio=f;this.fradio=b;this.input=this.tradio;this.init()};c.validate_boolean.prototype=
{init:function(){var f=this;this.tradio.bind("change.validate_boolean",function(){f.validate()})},_destroy:function(){this.input.unbind(".validate_boolean")},valid:function(f){this.input.trigger("valid",f)},empty:function(){this.input.trigger("empty")},validate:function(){if(this.tradio.is(":checked"))this.valid({text:this.tradio.text(),value:true});else this.fradio.is(":checked")?this.valid({text:this.fradio.text(),value:false}):this.empty()}}})(jQuery);
(function(c,f){var b=window.formlib={init_inline_add_form:function(a){var d=a.event_prefix||"form.inline_add_form.";a.edit_row.bind(d+"submit",function(){b.submit_inline_add_form(a)}).bind(d+"cancel",function(){b.cancel_inline_add_form(a)}).bind(d+"error",function(e,g){b.error(a,g);a.edit_row.removeClass("loading")}).bind(d+"success",function(){a.edit_row.removeClass("loading")}).bind(d+"valid",function(){b.enable_submit(a)}).bind(d+"invalid",function(){b.disable_submit(a)});b.init_submit_cancel(a);
a.trigger&&a.trigger.parents(".trigger-row:first").hide();a.body.append(a.head_row).append(a.edit_row).append(a.submit_row);a.init(a)},submit_inline_add_form:function(a){if(!a.edit_row.is(".loading"))if(b.is_submit_enabled(a)){document.activeElement&&c(document.activeElement).blur();b.clear_message(a);if(a.validate(a)){a.edit_row.addClass("loading");a.submit(a,b.default_submit_ajax_options(a))}}},success_inline_add_form:function(a,d){a.head_row.before(d);f.ize(d);a.reset(a);a.edit_row.trigger(a.event_prefix+
"success")},cancel_inline_add_form:function(a){a.head_row.remove();a.edit_row.remove();a.submit_row.remove();a.trigger&&a.trigger.parents(".trigger-row:first").show()},init_inline_edit_form:function(a){var d=a.event_prefix||"form.inline_edit_form.";a.edit_row.bind(d+"submit",function(){b.submit_inline_edit_form(a)}).bind(d+"cancel",function(){b.cancel_inline_edit_form(a)}).bind(d+"error",function(e,g){b.error(a,g);a.edit_row.removeClass("loading")}).bind(d+"success",function(){a.edit_row.removeClass("loading")}).bind(d+
"valid",function(){b.enable_submit(a)}).bind(d+"invalid",function(){b.disable_submit(a)});b.init_submit_cancel(a);a.row.hide();a.row.before(a.head_row).before(a.edit_row).before(a.submit_row);a.init(a)},submit_inline_edit_form:function(a){if(!a.edit_row.is(".loading"))if(b.is_submit_enabled(a)){document.activeElement&&c(document.activeElement).blur();b.clear_message(a);if(a.validate(a)){a.edit_row.addClass("loading");a.submit(a,b.default_submit_ajax_options(a))}}},success_inline_edit_form:function(a,
d){a.row.replaceWith(d);a.row=d;f.ize(d);a.edit_row.trigger(a.event_prefix+"cancel")},cancel_inline_edit_form:function(a){a.head_row.remove();a.edit_row.remove();a.submit_row.remove();a.row.show()},success_inline_delete:function(a,d,e){a.hide().addClass("old-row");a.after(d);d.append(a);if(e){a=c('<a href="#">Undo</a>');c(".msg-default",d).next().append(a);a.click(function(){e();return false})}},success_inline_delete_undo:function(a){var d=c(".old-row",a);a.before(d);d.show().removeClass("old-row");
a.remove()},init_modal_form:function(a){c(document.body).append(a.form.hide());var d=a.event_prefix||"form.modal_form.";a.form.bind(d+"submit",function(){b.submit_modal_form(a)}).bind(d+"cancel",function(){b.cancel_modal_form(a)}).bind(d+"error",function(e,g){b.error(a,g);a.form.removeClass("loading")}).bind(d+"success",function(){a.form.removeClass("loading")}).bind(d+"valid",function(){b.enable_submit(a)}).bind(d+"invalid",function(){b.disable_submit(a)});b.init_submit_cancel(a);a.form.overlay({close:".modal-buttons .cancel",
closeOnClick:false,load:true,fixed:false,mask:{color:"#000",loadSpeed:200,opacity:0.5},onLoad:function(){a.overlay=this;a.init(a)}})},submit_modal_form:function(a){if(!a.form.is(".loading"))if(b.is_submit_enabled(a)){document.activeElement&&c(document.activeElement).blur();b.clear_message(a);if(a.validate(a)){a.form.addClass("loading");a.submit(a,b.default_submit_ajax_options(a))}}},cancel_modal_form:function(a){a.form.data("overlay").close()},init_submit_cancel:function(a){var d=a.form||a.edit_row,
e=a.form||a.submit_row,g=a.event_prefix;a=c(".save",e).click(function(){d.trigger(g+"submit")});b.disable(a);c(".cancel",e).click(function(){d.trigger(g+"cancel")});c(":input",d).keypress(function(h){h.keyCode===13&&!h.isDefaultPrevented()&&d.trigger(g+"submit")}).keyup(function(h){h.keyCode===27&&d.trigger(g+"cancel")})},disable:function(a){c(a).attr("disabled","disabled").addClass("disabled")},enable:function(a){c(a).removeAttr("disabled").removeClass("disabled")},disable_submit:function(a){b.disable(c(".save",
a.form||a.submit_row))},enable_submit:function(a){b.enable(c(".save",a.form||a.submit_row))},is_submit_enabled:function(a){return!c(".save",a.form||a.submit_row).is(":disabled")},init_mqlkey:function(a,d){return a.next(".key-status").removeClass("valid invalid loading").text("").removeAttr("title").end().mqlkey(d).bind("valid",function(){c(this).next(".key-status").removeClass("invalid loading").addClass("valid").text("valid").attr("title","Key is available")}).bind("invalid",function(e,g){c(this).next(".key-status").removeClass("valid loading").addClass("invalid").text("invalid").attr("title",
g)}).bind("textchange",function(){c(this).next(".key-status").removeClass("valid invalid").text("loading").addClass("loading")})},validate_mqlkey:function(a,d){var e=d.next(".key-status"),g=d.val();if(g===""){d.trigger(a.event_prefix+"error","Key is required");return false}if(g===d.data("mqlkey").original)return true;if(e.is(".invalid")){d.trigger(a.event_prefix+"error",e.attr("title"));return false}else if(e.is(".loading"))return false;return true},error:function(a,d){b.disable_submit(a);return b.message(a,
d,"error")},message:function(a,d,e){a=a.head_row;a.find(".close-msg").css("visibility","visible").next().find(".msg-default").hide().next().text(d);a.addClass("row-msg");e&&a.addClass("row-msg-"+e)},clear_message:function(){},default_begin_ajax_options:function(){return b._default_ajax_options("GET")},default_submit_ajax_options:function(a){var d=b._default_ajax_options("POST");if(a){c.extend(d,a.ajax);c("input[type=hidden]",a.submit_row||a.form).each(function(){d.data[this.name]=this.value})}return d},
_default_ajax_options:function(a){return{data:{},dataType:"json",type:a||"GET",success:function(d,e,g){if(!b.check_ajax_success.apply(this,arguments))return this._error.apply(this,[g]);this.onsuccess&&this.onsuccess.apply(this,arguments)},error:function(){b.check_ajax_error.apply(this,arguments);return this._error.apply(this,arguments)},_error:function(d){if(d.status===401)c(window).trigger("fb.user.unauthorized");else if(this.onerror)this.onerror.apply(this,[d.responseText].concat(Array.prototype.slice.call(arguments)));
else{var e={},g=this;c.each(["url","data","dataType","type"],function(h,j){e[j]=g[j]});c.each(["status","statusText","responseText"],function(h,j){e[j]=d[j]});e.responseHeaders=d.getAllResponseHeaders();c(window).trigger("fb.user.feedback",e)}}}},check_ajax_success:function(){return b.check_api_response.apply(this,arguments)},check_ajax_error:function(a){var d=a.responseText;try{d=JSON.stringify(d)}catch(e){}return b.check_api_response.apply(this,[d,a.statusText,a])},check_api_response:function(a,
d,e){if(typeof a==="object"){if(a.code!=="/api/status/ok")return false}else if(e.status!==200)return false;return true}}})(jQuery,window.i18n);
(function(c){var f=window.editparams={Empty:function(b,a,d){this.structure=b;this.data=a;this.msg=d;this.toString=function(){return"Empty: "+this.msg}},Invalid:function(b,a,d){this.structure=b;this.data=a;this.msg=d;this.toString=function(){return"Invalid: "+this.msg}},parse:function(b,a){function d(i,k,l,m,n){try{f.validate(k,l);n.push(l)}catch(p){if(p instanceof f.Empty)n.push(l);else throw p;}}var e=(b.values||[]).slice(),g=b.properties||[],h=b.expected_type.mediator;if(h){if(!g.length)throw new f.Invalid(b,
null,"mediator musth have 1 or more properties");if(e.length&&e.length!==1)throw new f.Invalid(b,null,"Can't edit more than one value (row) for a mediator");}var j=[];c(".data-input",a).each(function(){var i=c(this),k=i.data("$.data_input");if(!k)throw new f.Invalid(b,null,"$.data-input not initialized for",this);k.validate(true);if(i.is(".error"))throw new f.Invalid(b,null,"$.data-input is invalid",this);k=i.data("data");if(!k)throw new f.Invalid(b,null,"$.data-input has no data",this);if(h){if(!j.length){j.push({});
c.each(g,function(n,p){j[0][p.id]=c.extend({},p,{values:[]})})}var l=j[0][k.name];if(l){var m=[];if(e.length)m=(m=e[0][l.id])&&m.values||[];d(i,l,k,m,l.values)}else console.warn("editparams","unknown mediator property data",k)}else d(i,b,k,e,j)});return h?f.parse_mediator(b,e,j):f.parse_simple(b,e,j)},parse_mediator:function(b,a,d){if(d.length!==1)throw new f.Invalid(b,d,"Must specify one (new or updated) value for a mediator");d=d[0];var e;if(a.length)e=a[0];a={};if(e)a.id=e.id;else{a.id=null;a.create=
"unconditional";a.connect=b.unique?"replace":"insert";var g=[];b.expected_type.id!=="/type/object"&&g.push({id:b.expected_type.id,connect:"insert"});var h=b.expected_type.included_types;h&&h.forEach(function(m){m!=="/type/object"&&g.push({id:m,connect:"insert"})});if(g.length)a.type=g}h=false;b=b.properties;for(var j=0,i=b.length;j<i;j++){var k=b[j],l=f.parse_simple(k,e&&e[k.id]&&e[k.id].values||[],d[k.id]&&d[k.id].values||[]);if(l.length){a[k.id]=l;h=true}}return h?[a]:[]},parse_simple:function(b,
a,d){return f.diff(b,a,d)},diff:function(b,a,d){var e=b.expected_type,g=b.expected_type.id,h=b.unique,j=g==="/type/text";if(h)if(!j)if(a.length&&a.length!==1)throw new f.Invalid(b,a,"Can't edit more than one value (row) for a unique property.");else if(d.length&&d.length!==1)throw new f.Invalid(b,d,"Can't edit more than one value (row) for a unique property.");var i=[];if(f.LITERAL_TYPE_IDS[g]){i.push("value");j&&i.push("lang")}else i.push("id");g=[];var k=[],l,m;l=0;for(m=a.length;l<m;l++){var n=
a[l];f.validate(b,n);f.inArray.apply(null,[n,d].concat(i))===-1&&g.push(f.clause(n,"delete"))}l=0;for(m=d.length;l<m;l++){n=d[l];try{f.validate(b,n)}catch(p){continue}if(f.inArray.apply(null,[n,a].concat(i))===-1){if(h)if(j){var o=f.inArray(n,g,"lang");o!==-1&&g.splice(o,1)}else return[f.clause(n,"replace",e)];k.push(f.clause(n,h?"replace":"insert",e))}}return g.concat(k)},validate:function(b,a){var d=b.expected_type.id;if(f.LITERAL_TYPE_IDS[d])if(f.isEmpty(a.value))throw new f.Empty(b,a);else{if(d===
"/type/text"&&f.isEmpty(a.lang))throw new f.Invalid(b,a,"Expected data.lang for /type/text");if(d==="/type/int"||d==="/type/float"){if(c.type(a.value)!=="number")throw new f.Invalid(b,a,"Expected number data.value for "+d);}else if(d==="/type/boolean"){if(c.type(a.value)!=="boolean")throw new f.Invalid(b,a,"Expected boolean data.value for /type/boolean");}else if(c.type(a.value)!=="string")throw new f.Invalid(b,a,"Expected string data.value for "+d);}else if(f.isEmpty(a.id))throw new f.Empty(b,a);
return a},clause:function(b,a,d){var e={connect:a};if(b.id){e.id=b.id;if(a!=="delete"&&d&&!d.enumeration){var g=[];d.id!=="/type/object"&&g.push({id:d.id,connect:"insert"});(b=d.included_types)&&b.forEach(function(h){h!=="/type/object"&&g.push({id:h,connect:"insert"})});if(g.length)e.type=g}}else{e.value=b.value;if(b.lang)e.lang=b.lang}return e},inArray:function(b,a){var d=Array.prototype.slice.call(arguments,2);if(!d.length)return c.inArray(b,a);for(var e=0,g=a.length;e<g;e++){for(var h=a[e],j=true,
i=0,k=d.length;i<k;i++){var l=d[i];if(h[l]!=b[l]){j=false;break}}if(j)return e}return-1},isEmpty:function(b){return b==null||b===""},LITERAL_TYPE_IDS:{"/type/int":1,"/type/float":1,"/type/boolean":1,"/type/rawstring":1,"/type/uri":1,"/type/text":1,"/type/datetime":1,"/type/id":1,"/type/key":1,"/type/value":1,"/type/enumeration":1}}})(jQuery);
(function(c,f,b,a,d){var e=f.edit={prop_add_begin:function(g,h){var j={s:f.options.id,p:g.attr("data-id"),lang:f.options.lang},i=c(">.data-section",g),k=c("> .data-table > tbody, > .data-list",i);c.ajax(c.extend(b.default_begin_ajax_options(),{url:f.options.base_ajax_url+"/prop_add_begin.ajax",data:j,onsuccess:function(l){l=c(l.result.html);var m=c(".edit-row-head",l),n=c(".edit-row",l),p=c(".edit-row-submit",l);l={event_prefix:"propbox.edit.prop_add.",init:e.init_prop_add_form,validate:e.validate_prop_add_form,
submit:e.submit_prop_add_form,reset:e.reset_prop_add_form,ajax:{url:f.options.base_ajax_url+"/prop_edit_submit.ajax",data:j},body:k,head_row:m,edit_row:n,submit_row:p,structure:l.metadata()};n.bind("propbox.edit.prop_add.cancel",function(){g.removeClass("editing")}).bind("propbox.edit.prop_add.success",function(){h&&n.trigger(form.event_prefix+"cancel")});b.init_inline_add_form(l)}}))},init_prop_add_form:function(g){e.init_data_inputs(g);c(":input:visible:first",g.edit_row).focus()},validate_prop_add_form:function(){return true},
reset_prop_add_form:function(g){e.reset_data_inputs(g);b.disable_submit(g);c(".cancel",g.submit_row).text("Done");c(":input:visible:first",g.edit_row).focus()},submit_prop_add_form:function(g,h){try{var j=a.parse(g.structure,g.edit_row);h.data.o=JSON.stringify(j)}catch(i){j=c(".data-input.error",g.edit_row);if(j.length){g.edit_row.trigger(g.event_prefix+"error","Please specify a valid value");j.eq(0).find(":input").focus().select()}else g.edit_row.trigger(g.event_prefix+"error",i.toString());return}c.ajax(c.extend(h,
{onsuccess:function(k){k=c(k.result.html);b.success_inline_add_form(g,k);f.init_menus(k,true);c(".nicemenu-item.edit").show();f.kbs.set_next(null,k,true)},onerror:function(k){g.edit_row.trigger(g.event_prefix+"error",k)}}))},value_edit_begin:function(g,h){var j;if(h.is("tr"))j=h.attr("data-id");else{j=c(".property-value:first",h);j=j.attr("data-id")||j.attr("data-value")||j.attr("datetime")}var i={s:f.options.id,p:g.attr("data-id"),replace:j,lang:f.options.lang};c.ajax(c.extend(b.default_begin_ajax_options(),
{url:f.options.base_ajax_url+"/value_edit_begin.ajax",data:i,onsuccess:function(k){k=c(k.result.html);var l=c(".edit-row-head",k),m=c(".edit-row",k),n=c(".edit-row-submit",k);k={event_prefix:"propbox.edit.value_edit.",init:e.init_value_edit_form,validate:e.validate_value_edit_form,submit:e.submit_value_edit_form,ajax:{url:f.options.base_ajax_url+"/prop_edit_submit.ajax",data:i},row:h,head_row:l,edit_row:m,submit_row:n,structure:k.metadata()};m.bind("propbox.edit.value_edit.success",function(){g.removeClass("editing")}).bind("propbox.edit.value_edit.cancel",
function(){g.removeClass("editing")}).bind("propbox.edit.value_edit.delete",function(){m.trigger("propbox.edit.value_edit.cancel");f.edit.value_delete_begin(g,h)});b.init_inline_edit_form(k)}}))},init_value_edit_form:function(g){e.init_data_inputs(g);c(".delete",g.submit_row).click(function(){g.edit_row.trigger(g.event_prefix+"delete")});c(":input:visible:first",g.edit_row).focus()},validate_value_edit_form:function(){return true},submit_value_edit_form:function(g,h){try{var j=a.parse(g.structure,
g.edit_row);h.data.o=JSON.stringify(j)}catch(i){j=c(".data-input.error",g.edit_row);if(j.length){g.edit_row.trigger(g.event_prefix+"error","Please specify a valid value");j.eq(0).find(":input").focus().select()}else g.edit_row.trigger(g.event_prefix+"error",i.toString());return}c.ajax(c.extend(h,{onsuccess:function(k){k=c(k.result.html);b.success_inline_edit_form(g,k);f.init_menus(k,true);c(".nicemenu-item.edit").show();f.kbs.set_next(null,k,true)},onerror:function(k){g.edit_row.trigger(g.event_prefix+
"error",k)}}))},value_delete_begin:function(g,h){var j;if(h.is("tr"))j=h.attr("data-id");else{j=c(".property-value:first",h);j=j.attr("data-id")||j.attr("data-value")||j.attr("datetime")}var i={s:f.options.id,p:g.attr("data-id"),o:j,lang:f.options.lang};c.ajax(c.extend(b.default_submit_ajax_options(),{url:f.options.base_ajax_url+"/value_delete_submit.ajax",data:i,onsuccess:function(k){var l=c(k.result.html);b.success_inline_delete(h,l,function(){c.ajax(c.extend(b.default_submit_ajax_options(),{url:f.options.base_ajax_url+
"/value_delete_undo.ajax",data:i,onsuccess:function(){b.success_inline_delete_undo(l)}}))});g.removeClass("editing")}}))},init_data_inputs:function(g){c(".data-input",g.edit_row).each(function(){e.init_data_input(c(this),g)})},init_data_input:function(g,h){g.data_input({lang:f.options.lang,suggest:f.options.suggest}).bind("valid",function(){h.edit_row.trigger(h.event_prefix+"valid");var j=g.parent(".form-field"),i=j.next(".magicbox-template");if(i.length){i=c("<div>").html(i.html());i=c(".form-field",
i);j.after(i);e.init_data_input(c(".data-input",i),h)}}).bind("empty",function(){h.edit_row.trigger(h.event_prefix+"valid")}).bind("invalid",function(){h.edit_row.trigger(h.event_prefix+"invalid")}).bind("submit",function(){h.edit_row.trigger(h.event_prefix+"submit")}).bind("cancel",function(){h.edit_row.trigger(h.event_prefix+"cancel")}).bind("loading",function(){c(this).addClass("loading")}).bind("loading_complete",function(){c(this).removeClass("loading")});if(g.is(".datetime"))d.ize_datetime_input(c(":text",
g));else if(g.is(".int")||g.is(".float"))d.ize_number_input(c(":text",g))},reset_data_inputs:function(g){c(".data-input",g.edit_row).each(function(){c(this).data("$.data_input").reset()})}}})(jQuery,window.propbox,window.formlib,window.editparams,window.i18n);
(function(c,f,b,a,d,e){var g=f.collection.edit={row_edit_begin:function(h){g._row_edit_begin(h)},row_edit_init:function(h){e.ize(h.form);b.init(h.form,{id:h.row.attr("data-id"),base_ajax_url:f.h.ajax_url("lib/propbox"),base_static_url:f.h.static_url("lib/propbox"),lang:f.lang||"/lang/en",suggest:c.extend({status:["","Searching...","Select an item from the list:"]},f.suggest_options.service_defaults)});c(".edit",h.form).show();c(".nicemenu",h.form).nicemenu({overlay:h.overlay.getOverlay()});var j=
c(".property-value:first",h.row).text();c(".modal-nav-title").text(j).css("visibility","visible");j=c(".modal-nav-prev",h.form).unbind();var i=c(".modal-nav-next",h.form).unbind(),k=h.row.prev(".data-row"),l=h.row.next(".data-row");k.length?j.click(function(){g.row_edit_prev(k,h);return false}).css("visibility","visible"):j.css("visibility","hidden");l.length?i.click(function(){g.row_edit_next(l,h);return false}).css("visibility","visible"):i.css("visibility","hidden")},row_edit_prev:function(h,j){g._row_edit_begin(h,
j)},row_edit_next:function(h,j){g._row_edit_begin(h,j)},_row_edit_begin:function(h,j){var i=j!=null,k=h.attr("data-id"),l=h.parent("table").metadata().prop_structures;l=l.map(function(m){return m.id});k={s:k,p:l,lang:f.lang||"/lang/en",nav:i};c.ajax(c.extend(a.default_begin_ajax_options(),{url:f.h.ajax_url("lib/collection/row_edit_begin.ajax"),data:k,traditional:true,onsuccess:function(m){m=c(m.result.html);if(i){c(".modal-inner",j.form).replaceWith(m);j.row=h;g.row_edit_init(j)}else{j={event_prefix:"collection.edit.row_edit.",
init:g.row_edit_init,validate:function(){return true},submit:function(){},ajax:{},form:m,row:h};c("button[type=submit]",m).hide();m.bind("collection.edit.row_edit.cancel",function(){window.location.reload(true)});a.init_modal_form(j)}}}))}}})(jQuery,window.freebase,window.propbox,window.formlib,window.editparams,window.i18n);
