
/*
 * Copyright 2012, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Additional Licenses for Third Party components can be found here:
 * http://wiki.freebase.com/wiki/Freebase_Site_License
 *
 */
/*
 
 jQuery Tools @VERSION Tabs- The basics of UI design.

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/tabs/

 Since: November 2008
 Date: @DATE 
*/
(function(a){function g(b,c,d){var f=this,e=b.add(this),j=b.find(d.tabs),i=c.jquery?c:b.children(c),g;j.length||(j=b.children());i.length||(i=b.parent().find(c));i.length||(i=a(c));a.extend(this,{click:function(c,b){var i=j.eq(c);"string"==typeof c&&c.replace("#","")&&(c=c.replace(/([\"\#\$\%\&\'\(\)\*\+\,\.\/\:\;\<\=\>\?\@\[\\\]\^\`\{\|\}\~])/g,"\\$1"),i=j.filter("[href*="+c.replace("#","")+"]"),c=Math.max(j.index(i),0));if(d.rotate){var o=j.length-1;if(0>c)return f.click(o,b);if(c>o)return f.click(0,
b)}if(!i.length){if(0<=g)return f;c=d.initialIndex;i=j.eq(c)}if(c===g)return f;b=b||a.Event();b.type="onBeforeClick";e.trigger(b,[c]);if(!b.isDefaultPrevented())return h[d.effect].call(f,c,function(){b.type="onClick";e.trigger(b,[c])}),g=c,j.removeClass(d.current),i.addClass(d.current),f},getConf:function(){return d},getTabs:function(){return j},getPanes:function(){return i},getCurrentPane:function(){return i.eq(g)},getCurrentTab:function(){return j.eq(g)},getIndex:function(){return g},next:function(){return f.click(g+
1)},prev:function(){return f.click(g-1)},destroy:function(){j.unbind(d.event).removeClass(d.current);i.find("a[href^=#]").unbind("click.T");return f}});a.each(["onBeforeClick","onClick"],function(c,b){a.isFunction(d[b])&&a(f).bind(b,d[b]);f[b]=function(c){a(f).bind(b,c);return f}});d.history&&a.fn.history&&(a.tools.history.init(j),d.event="history");j.each(function(c){a(this).bind(d.event,function(a){f.click(c,a);return a.preventDefault()})});i.find("a[href^=#]").bind("click.T",function(c){f.click(a(this).attr("href"),
c)});location.hash?f.click(location.hash):(0===d.initialIndex||0<d.initialIndex)&&f.click(d.initialIndex)}a.tools=a.tools||{version:"@VERSION"};a.tools.tabs={conf:{tabs:"a",current:"current",onBeforeClick:null,onClick:null,effect:"default",initialIndex:0,event:"click",rotate:!1,history:!1},addEffect:function(a,c){h[a]=c}};var h={"default":function(a,c){this.getPanes().hide().eq(a).show();c.call()},fade:function(a,c){var d=this.getConf(),f=d.fadeOutSpeed,e=this.getPanes();f?e.fadeOut(f):e.hide();e.eq(a).fadeIn(d.fadeInSpeed,
c)},slide:function(a,c){this.getPanes().slideUp(200);this.getPanes().eq(a).slideDown(400,c)},ajax:function(a,c){this.getPanes().eq(0).load(this.getTabs().eq(a).attr("href"),c)}},e;a.tools.tabs.addEffect("horizontal",function(b,c){e||(e=this.getPanes().eq(0).width());this.getCurrentPane().animate({width:0},function(){a(this).hide()});this.getPanes().eq(b).animate({width:e},function(){a(this).show();c.call()})});a.fn.tabs=function(b,c){var d=this.data("tabs");d&&(d.destroy(),this.removeData("tabs"));
a.isFunction(c)&&(c={onBeforeClick:c});c=a.extend({},a.tools.tabs.conf,c);this.each(function(){d=new g(a(this),b,c);a(this).data("tabs",d)});return c.api?d:this}})(jQuery);
(function(a,g){function h(e){return!a(e).parents().andSelf().filter(function(){return"hidden"===a.curCSS(this,"visibility")||a.expr.filters.hidden(this)}).length}a.ui=a.ui||{};a.ui.version||(a.extend(a.ui,{version:"1.8.10",keyCode:{ALT:18,BACKSPACE:8,CAPS_LOCK:20,COMMA:188,COMMAND:91,COMMAND_LEFT:91,COMMAND_RIGHT:93,CONTROL:17,DELETE:46,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,INSERT:45,LEFT:37,MENU:93,NUMPAD_ADD:107,NUMPAD_DECIMAL:110,NUMPAD_DIVIDE:111,NUMPAD_ENTER:108,NUMPAD_MULTIPLY:106,NUMPAD_SUBTRACT:109,
PAGE_DOWN:34,PAGE_UP:33,PERIOD:190,RIGHT:39,SHIFT:16,SPACE:32,TAB:9,UP:38,WINDOWS:91}}),a.fn.extend({_focus:a.fn.focus,focus:function(e,b){return"number"===typeof e?this.each(function(){var c=this;setTimeout(function(){a(c).focus();b&&b.call(c)},e)}):this._focus.apply(this,arguments)},scrollParent:function(){var e;e=a.browser.msie&&/(static|relative)/.test(this.css("position"))||/absolute/.test(this.css("position"))?this.parents().filter(function(){return/(relative|absolute|fixed)/.test(a.curCSS(this,
"position",1))&&/(auto|scroll)/.test(a.curCSS(this,"overflow",1)+a.curCSS(this,"overflow-y",1)+a.curCSS(this,"overflow-x",1))}).eq(0):this.parents().filter(function(){return/(auto|scroll)/.test(a.curCSS(this,"overflow",1)+a.curCSS(this,"overflow-y",1)+a.curCSS(this,"overflow-x",1))}).eq(0);return/fixed/.test(this.css("position"))||!e.length?a(document):e},zIndex:function(e){if(e!==g)return this.css("zIndex",e);if(this.length)for(var e=a(this[0]),b;e.length&&e[0]!==document;){b=e.css("position");if("absolute"===
b||"relative"===b||"fixed"===b)if(b=parseInt(e.css("zIndex"),10),!isNaN(b)&&0!==b)return b;e=e.parent()}return 0},disableSelection:function(){return this.bind((a.support.selectstart?"selectstart":"mousedown")+".ui-disableSelection",function(a){a.preventDefault()})},enableSelection:function(){return this.unbind(".ui-disableSelection")}}),a.each(["Width","Height"],function(e,b){function c(c,b,f,e){a.each(d,function(){b-=parseFloat(a.curCSS(c,"padding"+this,!0))||0;f&&(b-=parseFloat(a.curCSS(c,"border"+
this+"Width",!0))||0);e&&(b-=parseFloat(a.curCSS(c,"margin"+this,!0))||0)});return b}var d="Width"===b?["Left","Right"]:["Top","Bottom"],f=b.toLowerCase(),m={innerWidth:a.fn.innerWidth,innerHeight:a.fn.innerHeight,outerWidth:a.fn.outerWidth,outerHeight:a.fn.outerHeight};a.fn["inner"+b]=function(d){return d===g?m["inner"+b].call(this):this.each(function(){a(this).css(f,c(this,d)+"px")})};a.fn["outer"+b]=function(d,e){return"number"!==typeof d?m["outer"+b].call(this,d):this.each(function(){a(this).css(f,
c(this,d,!0,e)+"px")})}}),a.extend(a.expr[":"],{data:function(e,b,c){return!!a.data(e,c[3])},focusable:function(e){var b=e.nodeName.toLowerCase(),c=a.attr(e,"tabindex");if("area"===b){b=e.parentNode;c=b.name;if(!e.href||!c||"map"!==b.nodeName.toLowerCase())return!1;e=a("img[usemap=#"+c+"]")[0];return!!e&&h(e)}return(/input|select|textarea|button|object/.test(b)?!e.disabled:"a"==b?e.href||!isNaN(c):!isNaN(c))&&h(e)},tabbable:function(e){var b=a.attr(e,"tabindex");return(isNaN(b)||0<=b)&&a(e).is(":focusable")}}),
a(function(){var e=document.body,b=e.appendChild(b=document.createElement("div"));a.extend(b.style,{minHeight:"100px",height:"auto",padding:0,borderWidth:0});a.support.minHeight=100===b.offsetHeight;a.support.selectstart="onselectstart"in b;e.removeChild(b).style.display="none"}),a.extend(a.ui,{plugin:{add:function(e,b,c){var e=a.ui[e].prototype,d;for(d in c)e.plugins[d]=e.plugins[d]||[],e.plugins[d].push([b,c[d]])},call:function(a,b,c){if((b=a.plugins[b])&&a.element[0].parentNode)for(var d=0;d<b.length;d++)a.options[b[d][0]]&&
b[d][1].apply(a.element,c)}},contains:function(a,b){return document.compareDocumentPosition?a.compareDocumentPosition(b)&16:a!==b&&a.contains(b)},hasScroll:function(e,b){if("hidden"===a(e).css("overflow"))return!1;var c=b&&"left"===b?"scrollLeft":"scrollTop",d=!1;if(0<e[c])return!0;e[c]=1;d=0<e[c];e[c]=0;return d},isOverAxis:function(a,b,c){return a>b&&a<b+c},isOver:function(e,b,c,d,f,g){return a.ui.isOverAxis(e,c,f)&&a.ui.isOverAxis(b,d,g)}}))})(jQuery);
(function(a,g){if(a.cleanData){var h=a.cleanData;a.cleanData=function(b){for(var c=0,d;null!=(d=b[c]);c++)a(d).triggerHandler("remove");h(b)}}else{var e=a.fn.remove;a.fn.remove=function(b,c){return this.each(function(){c||(!b||a.filter(b,[this]).length)&&a("*",this).add([this]).each(function(){a(this).triggerHandler("remove")});return e.call(a(this),b,c)})}}a.widget=function(b,c,d){var f=b.split(".")[0],e,b=b.split(".")[1];e=f+"-"+b;d||(d=c,c=a.Widget);a.expr[":"][e]=function(c){return!!a.data(c,
b)};a[f]=a[f]||{};a[f][b]=function(a,c){arguments.length&&this._createWidget(a,c)};c=new c;c.options=a.extend(!0,{},c.options);a[f][b].prototype=a.extend(!0,c,{namespace:f,widgetName:b,widgetEventPrefix:a[f][b].prototype.widgetEventPrefix||b,widgetBaseClass:e},d);a.widget.bridge(b,a[f][b])};a.widget.bridge=function(b,c){a.fn[b]=function(d){var f="string"===typeof d,e=Array.prototype.slice.call(arguments,1),j=this,d=!f&&e.length?a.extend.apply(null,[!0,d].concat(e)):d;if(f&&"_"===d.charAt(0))return j;
f?this.each(function(){var c=a.data(this,b),f=c&&a.isFunction(c[d])?c[d].apply(c,e):c;if(f!==c&&f!==g)return j=f,!1}):this.each(function(){var f=a.data(this,b);f?f.option(d||{})._init():a.data(this,b,new c(d,this))});return j}};a.Widget=function(a,c){arguments.length&&this._createWidget(a,c)};a.Widget.prototype={widgetName:"widget",widgetEventPrefix:"",options:{disabled:!1},_createWidget:function(b,c){a.data(c,this.widgetName,this);this.element=a(c);this.options=a.extend(!0,{},this.options,this._getCreateOptions(),
b);var d=this;this.element.bind("remove."+this.widgetName,function(){d.destroy()});this._create();this._trigger("create");this._init()},_getCreateOptions:function(){return a.metadata&&a.metadata.get(this.element[0])[this.widgetName]},_create:function(){},_init:function(){},destroy:function(){this.element.unbind("."+this.widgetName).removeData(this.widgetName);this.widget().unbind("."+this.widgetName).removeAttr("aria-disabled").removeClass(this.widgetBaseClass+"-disabled ui-state-disabled")},widget:function(){return this.element},
option:function(b,c){var d=b;if(0===arguments.length)return a.extend({},this.options);if("string"===typeof b){if(c===g)return this.options[b];d={};d[b]=c}this._setOptions(d);return this},_setOptions:function(b){var c=this;a.each(b,function(a,b){c._setOption(a,b)});return this},_setOption:function(a,c){this.options[a]=c;"disabled"===a&&this.widget()[c?"addClass":"removeClass"](this.widgetBaseClass+"-disabled ui-state-disabled").attr("aria-disabled",c);return this},enable:function(){return this._setOption("disabled",
!1)},disable:function(){return this._setOption("disabled",!0)},_trigger:function(b,c,d){var f=this.options[b],c=a.Event(c);c.type=(b===this.widgetEventPrefix?b:this.widgetEventPrefix+b).toLowerCase();d=d||{};if(c.originalEvent)for(var b=a.event.props.length,e;b;)e=a.event.props[--b],c[e]=c.originalEvent[e];this.element.trigger(c,d);return!(a.isFunction(f)&&!1===f.call(this.element[0],c,d)||c.isDefaultPrevented())}}})(jQuery);
(function(a){a.widget("ui.mouse",{options:{cancel:":input,option",distance:1,delay:0},_mouseInit:function(){var g=this;this.element.bind("mousedown."+this.widgetName,function(a){return g._mouseDown(a)}).bind("click."+this.widgetName,function(h){if(!0===a.data(h.target,g.widgetName+".preventClickEvent"))return a.removeData(h.target,g.widgetName+".preventClickEvent"),h.stopImmediatePropagation(),!1});this.started=!1},_mouseDestroy:function(){this.element.unbind("."+this.widgetName)},_mouseDown:function(g){g.originalEvent=
g.originalEvent||{};if(!g.originalEvent.mouseHandled){this._mouseStarted&&this._mouseUp(g);this._mouseDownEvent=g;var h=this,e=1==g.which,b="string"==typeof this.options.cancel?a(g.target).parents().add(g.target).filter(this.options.cancel).length:!1;if(!e||b||!this._mouseCapture(g))return!0;this.mouseDelayMet=!this.options.delay;this.mouseDelayMet||(this._mouseDelayTimer=setTimeout(function(){h.mouseDelayMet=!0},this.options.delay));if(this._mouseDistanceMet(g)&&this._mouseDelayMet(g)&&(this._mouseStarted=
!1!==this._mouseStart(g),!this._mouseStarted))return g.preventDefault(),!0;this._mouseMoveDelegate=function(a){return h._mouseMove(a)};this._mouseUpDelegate=function(a){return h._mouseUp(a)};a(document).bind("mousemove."+this.widgetName,this._mouseMoveDelegate).bind("mouseup."+this.widgetName,this._mouseUpDelegate);g.preventDefault();return g.originalEvent.mouseHandled=!0}},_mouseMove:function(g){if(a.browser.msie&&!(9<=document.documentMode)&&!g.button)return this._mouseUp(g);if(this._mouseStarted)return this._mouseDrag(g),
g.preventDefault();this._mouseDistanceMet(g)&&this._mouseDelayMet(g)&&((this._mouseStarted=!1!==this._mouseStart(this._mouseDownEvent,g))?this._mouseDrag(g):this._mouseUp(g));return!this._mouseStarted},_mouseUp:function(g){a(document).unbind("mousemove."+this.widgetName,this._mouseMoveDelegate).unbind("mouseup."+this.widgetName,this._mouseUpDelegate);this._mouseStarted&&(this._mouseStarted=!1,g.target==this._mouseDownEvent.target&&a.data(g.target,this.widgetName+".preventClickEvent",!0),this._mouseStop(g));
return!1},_mouseDistanceMet:function(a){return Math.max(Math.abs(this._mouseDownEvent.pageX-a.pageX),Math.abs(this._mouseDownEvent.pageY-a.pageY))>=this.options.distance},_mouseDelayMet:function(){return this.mouseDelayMet},_mouseStart:function(){},_mouseDrag:function(){},_mouseStop:function(){},_mouseCapture:function(){return!0}})})(jQuery);
(function(a){a.ui=a.ui||{};var g=/left|center|right/,h=/top|center|bottom/,e=a.fn.position,b=a.fn.offset;a.fn.position=function(c){if(!c||!c.of)return e.apply(this,arguments);var c=a.extend({},c),b=a(c.of),f=b[0],m=(c.collision||"flip").split(" "),j=c.offset?c.offset.split(" "):[0,0],i,n,k;9===f.nodeType?(i=b.width(),n=b.height(),k={top:0,left:0}):f.setTimeout?(i=b.width(),n=b.height(),k={top:b.scrollTop(),left:b.scrollLeft()}):f.preventDefault?(c.at="left top",i=n=0,k={top:c.of.pageY,left:c.of.pageX}):
(i=b.outerWidth(),n=b.outerHeight(),k=b.offset());a.each(["my","at"],function(){var a=(c[this]||"").split(" ");a.length===1&&(a=g.test(a[0])?a.concat(["center"]):h.test(a[0])?["center"].concat(a):["center","center"]);a[0]=g.test(a[0])?a[0]:"center";a[1]=h.test(a[1])?a[1]:"center";c[this]=a});1===m.length&&(m[1]=m[0]);j[0]=parseInt(j[0],10)||0;1===j.length&&(j[1]=j[0]);j[1]=parseInt(j[1],10)||0;"right"===c.at[0]?k.left+=i:"center"===c.at[0]&&(k.left+=i/2);"bottom"===c.at[1]?k.top+=n:"center"===c.at[1]&&
(k.top+=n/2);k.left+=j[0];k.top+=j[1];return this.each(function(){var b=a(this),d=b.outerWidth(),f=b.outerHeight(),e=parseInt(a.curCSS(this,"marginLeft",true))||0,g=parseInt(a.curCSS(this,"marginTop",true))||0,h=d+e+(parseInt(a.curCSS(this,"marginRight",true))||0),q=f+g+(parseInt(a.curCSS(this,"marginBottom",true))||0),l=a.extend({},k),p;if(c.my[0]==="right")l.left=l.left-d;else if(c.my[0]==="center")l.left=l.left-d/2;if(c.my[1]==="bottom")l.top=l.top-f;else if(c.my[1]==="center")l.top=l.top-f/2;
l.left=Math.round(l.left);l.top=Math.round(l.top);p={left:l.left-e,top:l.top-g};a.each(["left","top"],function(b,e){if(a.ui.position[m[b]])a.ui.position[m[b]][e](l,{targetWidth:i,targetHeight:n,elemWidth:d,elemHeight:f,collisionPosition:p,collisionWidth:h,collisionHeight:q,offset:j,my:c.my,at:c.at})});a.fn.bgiframe&&b.bgiframe();b.offset(a.extend(l,{using:c.using}))})};a.ui.position={fit:{left:function(c,b){var f=a(window),f=b.collisionPosition.left+b.collisionWidth-f.width()-f.scrollLeft();c.left=
0<f?c.left-f:Math.max(c.left-b.collisionPosition.left,c.left)},top:function(c,b){var f=a(window),f=b.collisionPosition.top+b.collisionHeight-f.height()-f.scrollTop();c.top=0<f?c.top-f:Math.max(c.top-b.collisionPosition.top,c.top)}},flip:{left:function(c,b){if("center"!==b.at[0]){var f=a(window),f=b.collisionPosition.left+b.collisionWidth-f.width()-f.scrollLeft(),e="left"===b.my[0]?-b.elemWidth:"right"===b.my[0]?b.elemWidth:0,g="left"===b.at[0]?b.targetWidth:-b.targetWidth,i=-2*b.offset[0];c.left+=
0>b.collisionPosition.left?e+g+i:0<f?e+g+i:0}},top:function(b,d){if("center"!==d.at[1]){var f=a(window),f=d.collisionPosition.top+d.collisionHeight-f.height()-f.scrollTop(),e="top"===d.my[1]?-d.elemHeight:"bottom"===d.my[1]?d.elemHeight:0,g="top"===d.at[1]?d.targetHeight:-d.targetHeight,i=-2*d.offset[1];b.top+=0>d.collisionPosition.top?e+g+i:0<f?e+g+i:0}}}};a.offset.setOffset||(a.offset.setOffset=function(b,d){/static/.test(a.curCSS(b,"position"))&&(b.style.position="relative");var f=a(b),e=f.offset(),
g=parseInt(a.curCSS(b,"top",!0),10)||0,i=parseInt(a.curCSS(b,"left",!0),10)||0,e={top:d.top-e.top+g,left:d.left-e.left+i};"using"in d?d.using.call(b,e):f.css(e)},a.fn.offset=function(c){var d=this[0];return!d||!d.ownerDocument?null:c?this.each(function(){a.offset.setOffset(this,c)}):b.call(this)})})(jQuery);
(function(a,g){var h={buttons:!0,height:!0,maxHeight:!0,maxWidth:!0,minHeight:!0,minWidth:!0,width:!0},e={maxHeight:!0,maxWidth:!0,minHeight:!0,minWidth:!0};a.widget("ui.dialog",{options:{autoOpen:!0,buttons:{},closeOnEscape:!0,closeText:"close",dialogClass:"",draggable:!0,hide:null,height:"auto",maxHeight:!1,maxWidth:!1,minHeight:150,minWidth:150,modal:!1,position:{my:"center",at:"center",collision:"fit",using:function(b){var c=a(this).css(b).offset().top;0>c&&a(this).css("top",b.top-c)}},resizable:!0,
show:null,stack:!0,title:"",width:300,zIndex:1E3},_create:function(){this.originalTitle=this.element.attr("title");"string"!==typeof this.originalTitle&&(this.originalTitle="");this.options.title=this.options.title||this.originalTitle;var b=this,c=b.options,d=c.title||"&#160;",f=a.ui.dialog.getTitleId(b.element),e=(b.uiDialog=a("<div></div>")).appendTo(document.body).hide().addClass("ui-dialog ui-widget ui-widget-content ui-corner-all "+c.dialogClass).css({zIndex:c.zIndex}).attr("tabIndex",-1).css("outline",
0).keydown(function(d){if(c.closeOnEscape&&d.keyCode&&d.keyCode===a.ui.keyCode.ESCAPE){b.close(d);d.preventDefault()}}).attr({role:"dialog","aria-labelledby":f}).mousedown(function(a){b.moveToTop(false,a)});b.element.show().removeAttr("title").addClass("ui-dialog-content ui-widget-content").appendTo(e);var g=(b.uiDialogTitlebar=a("<div></div>")).addClass("ui-dialog-titlebar ui-widget-header ui-corner-all ui-helper-clearfix").prependTo(e),i=a('<a href="#"></a>').addClass("ui-dialog-titlebar-close ui-corner-all").attr("role",
"button").hover(function(){i.addClass("ui-state-hover")},function(){i.removeClass("ui-state-hover")}).focus(function(){i.addClass("ui-state-focus")}).blur(function(){i.removeClass("ui-state-focus")}).click(function(a){b.close(a);return false}).appendTo(g);(b.uiDialogTitlebarCloseText=a("<span></span>")).addClass("ui-icon ui-icon-closethick").text(c.closeText).appendTo(i);a("<span></span>").addClass("ui-dialog-title").attr("id",f).html(d).prependTo(g);a.isFunction(c.beforeclose)&&!a.isFunction(c.beforeClose)&&
(c.beforeClose=c.beforeclose);g.find("*").add(g).disableSelection();c.draggable&&a.fn.draggable&&b._makeDraggable();c.resizable&&a.fn.resizable&&b._makeResizable();b._createButtons(c.buttons);b._isOpen=!1;a.fn.bgiframe&&e.bgiframe()},_init:function(){this.options.autoOpen&&this.open()},destroy:function(){this.overlay&&this.overlay.destroy();this.uiDialog.hide();this.element.unbind(".dialog").removeData("dialog").removeClass("ui-dialog-content ui-widget-content").hide().appendTo("body");this.uiDialog.remove();
this.originalTitle&&this.element.attr("title",this.originalTitle);return this},widget:function(){return this.uiDialog},close:function(b){var c=this,d,f;if(!1!==c._trigger("beforeClose",b))return c.overlay&&c.overlay.destroy(),c.uiDialog.unbind("keypress.ui-dialog"),c._isOpen=!1,c.options.hide?c.uiDialog.hide(c.options.hide,function(){c._trigger("close",b)}):(c.uiDialog.hide(),c._trigger("close",b)),a.ui.dialog.overlay.resize(),c.options.modal&&(d=0,a(".ui-dialog").each(function(){if(this!==c.uiDialog[0]){f=
a(this).css("z-index");isNaN(f)||(d=Math.max(d,f))}}),a.ui.dialog.maxZ=d),c},isOpen:function(){return this._isOpen},moveToTop:function(b,c){var d=this.options;if(d.modal&&!b||!d.stack&&!d.modal)return this._trigger("focus",c);d.zIndex>a.ui.dialog.maxZ&&(a.ui.dialog.maxZ=d.zIndex);this.overlay&&(a.ui.dialog.maxZ+=1,this.overlay.$el.css("z-index",a.ui.dialog.overlay.maxZ=a.ui.dialog.maxZ));d={scrollTop:this.element.attr("scrollTop"),scrollLeft:this.element.attr("scrollLeft")};a.ui.dialog.maxZ+=1;this.uiDialog.css("z-index",
a.ui.dialog.maxZ);this.element.attr(d);this._trigger("focus",c);return this},open:function(){if(!this._isOpen){var b=this.options,c=this.uiDialog;this.overlay=b.modal?new a.ui.dialog.overlay(this):null;this._size();this._position(b.position);c.show(b.show);this.moveToTop(!0);b.modal&&c.bind("keypress.ui-dialog",function(b){if(b.keyCode===a.ui.keyCode.TAB){var c=a(":tabbable",this),e=c.filter(":first"),c=c.filter(":last");if(b.target===c[0]&&!b.shiftKey)return e.focus(1),!1;if(b.target===e[0]&&b.shiftKey)return c.focus(1),
!1}});a(this.element.find(":tabbable").get().concat(c.find(".ui-dialog-buttonpane :tabbable").get().concat(c.get()))).eq(0).focus();this._isOpen=!0;this._trigger("open");return this}},_createButtons:function(b){var c=this,d=!1,e=a("<div></div>").addClass("ui-dialog-buttonpane ui-widget-content ui-helper-clearfix"),g=a("<div></div>").addClass("ui-dialog-buttonset").appendTo(e);c.uiDialog.find(".ui-dialog-buttonpane").remove();"object"===typeof b&&null!==b&&a.each(b,function(){return!(d=!0)});d&&(a.each(b,
function(b,d){var d=a.isFunction(d)?{click:d,text:b}:d,e=a('<button type="button"></button>').attr(d,!0).unbind("click").click(function(){d.click.apply(c.element[0],arguments)}).appendTo(g);a.fn.button&&e.button()}),e.appendTo(c.uiDialog))},_makeDraggable:function(){function b(a){return{position:a.position,offset:a.offset}}var c=this,d=c.options,e=a(document),g;c.uiDialog.draggable({cancel:".ui-dialog-content, .ui-dialog-titlebar-close",handle:".ui-dialog-titlebar",containment:"document",start:function(e,
f){g="auto"===d.height?"auto":a(this).height();a(this).height(a(this).height()).addClass("ui-dialog-dragging");c._trigger("dragStart",e,b(f))},drag:function(a,d){c._trigger("drag",a,b(d))},stop:function(j,i){d.position=[i.position.left-e.scrollLeft(),i.position.top-e.scrollTop()];a(this).removeClass("ui-dialog-dragging").height(g);c._trigger("dragStop",j,b(i));a.ui.dialog.overlay.resize()}})},_makeResizable:function(b){function c(a){return{originalPosition:a.originalPosition,originalSize:a.originalSize,
position:a.position,size:a.size}}var b=b===g?this.options.resizable:b,d=this,e=d.options,h=d.uiDialog.css("position"),b="string"===typeof b?b:"n,e,s,w,se,sw,ne,nw";d.uiDialog.resizable({cancel:".ui-dialog-content",containment:"document",alsoResize:d.element,maxWidth:e.maxWidth,maxHeight:e.maxHeight,minWidth:e.minWidth,minHeight:d._minHeight(),handles:b,start:function(b,e){a(this).addClass("ui-dialog-resizing");d._trigger("resizeStart",b,c(e))},resize:function(a,b){d._trigger("resize",a,c(b))},stop:function(b,
g){a(this).removeClass("ui-dialog-resizing");e.height=a(this).height();e.width=a(this).width();d._trigger("resizeStop",b,c(g));a.ui.dialog.overlay.resize()}}).css("position",h).find(".ui-resizable-se").addClass("ui-icon ui-icon-grip-diagonal-se")},_minHeight:function(){var a=this.options;return"auto"===a.height?a.minHeight:Math.min(a.minHeight,a.height)},_position:function(b){var c=[],d=[0,0],e;if(b){if("string"===typeof b||"object"===typeof b&&"0"in b)c=b.split?b.split(" "):[b[0],b[1]],1===c.length&&
(c[1]=c[0]),a.each(["left","top"],function(a,b){+c[a]===c[a]&&(d[a]=c[a],c[a]=b)}),b={my:c.join(" "),at:c.join(" "),offset:d.join(" ")};b=a.extend({},a.ui.dialog.prototype.options.position,b)}else b=a.ui.dialog.prototype.options.position;(e=this.uiDialog.is(":visible"))||this.uiDialog.show();this.uiDialog.css({top:0,left:0}).position(a.extend({of:window},b));e||this.uiDialog.hide()},_setOptions:function(b){var c=this,d={},f=!1;a.each(b,function(a,b){c._setOption(a,b);a in h&&(f=!0);a in e&&(d[a]=
b)});f&&this._size();this.uiDialog.is(":data(resizable)")&&this.uiDialog.resizable("option",d)},_setOption:function(b,c){var d=this.uiDialog;switch(b){case "beforeclose":b="beforeClose";break;case "buttons":this._createButtons(c);break;case "closeText":this.uiDialogTitlebarCloseText.text(""+c);break;case "dialogClass":d.removeClass(this.options.dialogClass).addClass("ui-dialog ui-widget ui-widget-content ui-corner-all "+c);break;case "disabled":c?d.addClass("ui-dialog-disabled"):d.removeClass("ui-dialog-disabled");
break;case "draggable":var e=d.is(":data(draggable)");e&&!c&&d.draggable("destroy");!e&&c&&this._makeDraggable();break;case "position":this._position(c);break;case "resizable":(e=d.is(":data(resizable)"))&&!c&&d.resizable("destroy");e&&"string"===typeof c&&d.resizable("option","handles",c);!e&&!1!==c&&this._makeResizable(c);break;case "title":a(".ui-dialog-title",this.uiDialogTitlebar).html(""+(c||"&#160;"))}a.Widget.prototype._setOption.apply(this,arguments)},_size:function(){var b=this.options,
c,d,e=this.uiDialog.is(":visible");this.element.show().css({width:"auto",minHeight:0,height:0});b.minWidth>b.width&&(b.width=b.minWidth);c=this.uiDialog.css({height:"auto",width:b.width}).height();d=Math.max(0,b.minHeight-c);"auto"===b.height?a.support.minHeight?this.element.css({minHeight:d,height:"auto"}):(this.uiDialog.show(),b=this.element.css("height","auto").height(),e||this.uiDialog.hide(),this.element.height(Math.max(b,d))):this.element.height(Math.max(b.height-c,0));this.uiDialog.is(":data(resizable)")&&
this.uiDialog.resizable("option","minHeight",this._minHeight())}});a.extend(a.ui.dialog,{version:"1.8.10",uuid:0,maxZ:0,getTitleId:function(a){a=a.attr("id");a||(a=this.uuid+=1);return"ui-dialog-title-"+a},overlay:function(b){this.$el=a.ui.dialog.overlay.create(b)}});a.extend(a.ui.dialog.overlay,{instances:[],oldInstances:[],maxZ:0,events:a.map("focus mousedown mouseup keydown keypress click".split(" "),function(a){return a+".dialog-overlay"}).join(" "),create:function(b){0===this.instances.length&&
(setTimeout(function(){a.ui.dialog.overlay.instances.length&&a(document).bind(a.ui.dialog.overlay.events,function(b){if(a(b.target).zIndex()<a.ui.dialog.overlay.maxZ)return!1})},1),a(document).bind("keydown.dialog-overlay",function(c){b.options.closeOnEscape&&(c.keyCode&&c.keyCode===a.ui.keyCode.ESCAPE)&&(b.close(c),c.preventDefault())}),a(window).bind("resize.dialog-overlay",a.ui.dialog.overlay.resize));var c=(this.oldInstances.pop()||a("<div></div>").addClass("ui-widget-overlay")).appendTo(document.body).css({width:this.width(),
height:this.height()});a.fn.bgiframe&&c.bgiframe();this.instances.push(c);return c},destroy:function(b){var c=a.inArray(b,this.instances);-1!=c&&this.oldInstances.push(this.instances.splice(c,1)[0]);0===this.instances.length&&a([document,window]).unbind(".dialog-overlay");b.remove();var d=0;a.each(this.instances,function(){d=Math.max(d,this.css("z-index"))});this.maxZ=d},height:function(){var b,c;return a.browser.msie&&7>a.browser.version?(b=Math.max(document.documentElement.scrollHeight,document.body.scrollHeight),
c=Math.max(document.documentElement.offsetHeight,document.body.offsetHeight),b<c?a(window).height()+"px":b+"px"):a(document).height()+"px"},width:function(){var b,c;return a.browser.msie&&7>a.browser.version?(b=Math.max(document.documentElement.scrollWidth,document.body.scrollWidth),c=Math.max(document.documentElement.offsetWidth,document.body.offsetWidth),b<c?a(window).width()+"px":b+"px"):a(document).width()+"px"},resize:function(){var b=a([]);a.each(a.ui.dialog.overlay.instances,function(){b=b.add(this)});
b.css({width:0,height:0}).css({width:a.ui.dialog.overlay.width(),height:a.ui.dialog.overlay.height()})}});a.extend(a.ui.dialog.overlay.prototype,{destroy:function(){a.ui.dialog.overlay.destroy(this.$el)}})})(jQuery);
(function(a,g){var h=g.queryeditor={init:function(){CueCard.helper=g.h.ajax_url("lib/cuecard/");CueCard.freebaseServiceUrl=g.acre.freebase.service_url+"/";CueCard.urlPrefix=CueCard.apiProxy.base=g.h.ajax_url("lib/cuecard/");var e={initial_tab:"json"},b={focusOnReady:!0,codeMirror:{parserfile:[a("#codemirror-js").attr("href")],stylesheet:[a("#codemirror-css").attr("href")]}};g.permission.has_permission||(b.readOnly=!0,b.hideControls=!0);g.c&&g.c.query&&(b.content=JSON.stringify(g.c.query),autorun=
b.cleanUp=!0,e.queryLoaded=!0);b.onChange=function(){h.is_dirty=true;a("#save-query").addClass("disabled")};b.onRun=function(b){b.result&&h.is_dirty&&a("#save-query").removeClass("disabled")};b.onReady=function(){h.resize();a(window).resize(h.resize);h.is_dirty=false;autorun&&h.cuecard.queryEditor.run(false);setTimeout(function(){a("#qe-module, #the-output-pane").css("visibility","visible")},1)};h.cuecard=CueCard.createComposition({queryEditorElement:a("#the-query-editor")[0],queryEditorOptions:b,
outputPaneElement:a("#the-output-pane")[0],outputPaneOptions:e});h.page_chrome_height=a("#header").outerHeight()+a("#page-header").outerHeight()+(a("#page-content").outerHeight(!0)-a("#page-content").height())+a("#page-title").outerHeight(!0);a(window).bind("beforeunload",function(){})},resize:function(){var e=a("body").outerHeight()-h.page_chrome_height;e&&(a("#qe-module").height(e),h.cuecard.outputPane&&h.cuecard.outputPane.layout(e),h.cuecard.queryEditor&&h.cuecard.queryEditor.layout(e))},save:function(){a(this);
g.get_script(g.h.static_url("query-edit.mf.js"),function(){h.edit.save_submit(this)});return!1},clone:function(){window.location=g.h.fb_url("/query",{q:g.queryeditor.cuecard.queryEditor._editor.getCode(),autorun:1})}};"has_permission"in g.permission?h.init():a(window).bind("fb.permission.has_permission",function(){h.init()})})(jQuery,window.freebase);
