
/*
 * Copyright 2010, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Additional Licenses for Third Party components can be found here:
 * http://wiki.freebase.com/wiki/Freebase_Site_License
 *
 */
/*
 
 jQuery Tools @VERSION / Expose - Dim the lights

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/toolbox/expose.html

 Since: Mar 2010
 Date: @DATE 
 
 jQuery Tools @VERSION Overlay - Overlay base. Extend it.

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/overlay/

 Since: March 2008
 Date: @DATE 
*/
(function(b){function d(){if(b.browser.msie){var h=b(document).height(),j=b(window).height();return[window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth,h-j<20?j:h]}return[b(document).width(),b(document).height()]}function e(h){if(h)return h.call(b.mask)}b.tools=b.tools||{version:"@VERSION"};var a;a=b.tools.expose={conf:{maskId:"exposeMask",loadSpeed:"slow",closeSpeed:"fast",closeOnClick:true,closeOnEsc:true,zIndex:9998,opacity:0.8,startOpacity:0,color:"#fff",onLoad:null,
onClose:null}};var c,f,g,i,k;b.mask={load:function(h,j){if(g)return this;if(typeof h=="string")h={color:h};h=h||i;i=h=b.extend(b.extend({},a.conf),h);c=b("#"+h.maskId);if(!c.length){c=b("<div/>").attr("id",h.maskId);b("body").append(c)}var l=d();c.css({position:"absolute",top:0,left:0,width:l[0],height:l[1],display:"none",opacity:h.startOpacity,zIndex:h.zIndex});h.color&&c.css("backgroundColor",h.color);if(e(h.onBeforeLoad)===false)return this;h.closeOnEsc&&b(document).bind("keydown.mask",function(m){m.keyCode==
27&&b.mask.close(m)});h.closeOnClick&&c.bind("click.mask",function(m){b.mask.close(m)});b(window).bind("resize.mask",function(){b.mask.fit()});if(j&&j.length){k=j.eq(0).css("zIndex");b.each(j,function(){var m=b(this);/relative|absolute|fixed/i.test(m.css("position"))||m.css("position","relative")});f=j.css({zIndex:Math.max(h.zIndex+1,k=="auto"?0:k)})}c.css({display:"block"}).fadeTo(h.loadSpeed,h.opacity,function(){b.mask.fit();e(h.onLoad)});g=true;return this},close:function(){if(g){if(e(i.onBeforeClose)===
false)return this;c.fadeOut(i.closeSpeed,function(){e(i.onClose);f&&f.css({zIndex:k})});b(document).unbind("keydown.mask");c.unbind("click.mask");b(window).unbind("resize.mask");g=false}return this},fit:function(){if(g){var h=d();c.css({width:h[0],height:h[1]})}},getMask:function(){return c},isLoaded:function(){return g},getConf:function(){return i},getExposed:function(){return f}};b.fn.mask=function(h){b.mask.load(h);return this};b.fn.expose=function(h){b.mask.load(h,this);return this}})(jQuery);
(function(b){function d(c,f){var g=this,i=c.add(g),k=b(window),h,j,l,m=b.tools.expose&&(f.mask||f.expose),o=Math.random().toString().slice(10);if(m){if(typeof m=="string")m={color:m};m.closeOnClick=m.closeOnEsc=false}var p=f.target||c.attr("rel");j=p?b(p):c;if(!j.length)throw"Could not find Overlay: "+p;c&&c.index(j)==-1&&c.click(function(n){g.load(n);return n.preventDefault()});b.extend(g,{load:function(n){if(g.isOpened())return g;var r=a[f.effect];if(!r)throw'Overlay: cannot find effect : "'+f.effect+
'"';f.oneInstance&&b.each(e,function(){this.close(n)});n=n||b.Event();n.type="onBeforeLoad";i.trigger(n);if(n.isDefaultPrevented())return g;l=true;m&&b(j).expose(m);var q=f.top,t=f.left,u=j.outerWidth({margin:true}),v=j.outerHeight({margin:true});if(typeof q=="string")q=q=="center"?Math.max((k.height()-v)/2,0):parseInt(q,10)/100*k.height();if(t=="center")t=Math.max((k.width()-u)/2,0);r[0].call(g,{top:q,left:t},function(){if(l){n.type="onLoad";i.trigger(n)}});m&&f.closeOnClick&&b.mask.getMask().one("click",
g.close);f.closeOnClick&&b(document).bind("click."+o,function(s){b(s.target).parents(j).length||g.close(s)});f.closeOnEsc&&b(document).bind("keydown."+o,function(s){s.keyCode==27&&g.close(s)});return g},close:function(n){if(!g.isOpened())return g;n=n||b.Event();n.type="onBeforeClose";i.trigger(n);if(!n.isDefaultPrevented()){l=false;a[f.effect][1].call(g,function(){n.type="onClose";i.trigger(n)});b(document).unbind("click."+o).unbind("keydown."+o);m&&b.mask.close();return g}},getOverlay:function(){return j},
getTrigger:function(){return c},getClosers:function(){return h},isOpened:function(){return l},getConf:function(){return f}});b.each("onBeforeLoad,onStart,onLoad,onBeforeClose,onClose".split(","),function(n,r){b.isFunction(f[r])&&b(g).bind(r,f[r]);g[r]=function(q){b(g).bind(r,q);return g}});h=j.find(f.close||".close");if(!h.length&&!f.close){h=b('<a class="close"></a>');j.prepend(h)}h.click(function(n){g.close(n)});f.load&&g.load()}b.tools=b.tools||{version:"@VERSION"};b.tools.overlay={addEffect:function(c,
f,g){a[c]=[f,g]},conf:{close:null,closeOnClick:true,closeOnEsc:true,closeSpeed:"fast",effect:"default",fixed:!b.browser.msie||b.browser.version>6,left:"center",load:false,mask:null,oneInstance:true,speed:"normal",target:null,top:"10%"}};var e=[],a={};b.tools.overlay.addEffect("default",function(c,f){var g=this.getConf(),i=b(window);if(!g.fixed){c.top+=i.scrollTop();c.left+=i.scrollLeft()}c.position=g.fixed?"fixed":"absolute";this.getOverlay().css(c).fadeIn(g.speed,f)},function(c){this.getOverlay().fadeOut(this.getConf().closeSpeed,
c)});b.fn.overlay=function(c){var f=this.data("overlay");if(f)return f;if(b.isFunction(c))c={onBeforeLoad:c};c=b.extend(true,{},b.tools.overlay.conf,c);this.each(function(){f=new d(b(this),c);e.push(f);b(this).data("overlay",f)});return c.api?f:this}})(jQuery);
(function(b,d){d.require("dojo.date.stamp");d.require("dojo.date.locale");d.require("dojo.number");b.fn.validate_input=function(a){return this.each(function(){var c=b(this);if(c.is(":text")){var f=c.data("$.validate_input");f&&f._destroy();f=new e(this,a);c.data("$.validate_input",f)}})};var e=b.validate_input=function(a,c){var f=this.options=b.extend(true,{},e.defaults,c);if(typeof f.validator!=="function")throw"A validator is required";if(!f.lang)f.lang="/lang/en";f.lang=f.lang==="/lang/en"?["lang/en"]:
[f.lang,"/lang/en"];f.locales=[];b.each(f.lang,function(i,k){f.locales[i]=d.i18n.normalizeLocale(k.split("/").pop())});this.input=b(a);this.init();var g=this;this.input.bind("remove",function(){g._destroy()});return this};e.prototype={init:function(){var a=this;this.input.bind("keyup.validate_input",function(c){a.textchange(c)}).bind(b.browser.msie?"paste.validate_input":"input.validate_input",function(c){a.textchange(c)}).bind("keypress.validate_input",function(c){c.keyCode===13&&a.validate(true)}).bind("blur.validate_input",
function(){a.validate(true)})},_destroy:function(){this.input.unbind(".validate_input")},valid:function(a){this.input.trigger("valid",a)},invalid:function(a,c){this.input.trigger("invalid",c)},empty:function(){this.input.trigger("empty")},textchange:function(){clearTimeout(this.textchange_timeout);var a=this;this.textchange_timeout=setTimeout(function(){a.validate()},200)},validate:function(a){a&&clearTimeout(this.textchange_timeout);a=this.options;var c=b.trim(this.input.val());if(c==="")return this.empty();
try{return this.valid(a.validator(c,a))}catch(f){return this.invalid(c,""+f)}}};b.extend(e,{defaults:{validator:function(a){return{text:a,value:a}}},log:function(){},invalid:function(a,c,f,g){throw new Error("Invalid "+f+(g?": "+g:""));},text:function(a,c){if(a.lengh>4096)return this.invalid(a,c,type,"Text too long");return{text:a,value:a}},topic:function(){return e.defaults.validator},enumerated:function(){return e.defaults.validator},"boolean":function(){return e.defaults.validator},uri:function(a,
c){var f=e.uri.regex;if(!f)f=e.uri.regex=/^(https?|ftp):\/\/(((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:)*@)?(((\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5]))|((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?)(:\d*)?)(\/((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)+(\/(([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)*)*)?)?(\?((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|[\uE000-\uF8FF]|\/|\?)*)?(\#((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|\/|\?)*)?$/i;
if(f.test(a))return{text:a,value:a};return e.invalid(a,c,"uri")},"int":function(a,c){return e.number.parse(a,c,false)},"float":function(a,c){return e.number.parse(a,c,true)},number:function(a,c,f){return e.number.parse(a,c,f)},datetime:function(a,c){return e.datetime.parse(a,c)},mqlkey:function(a,c){var f=e.mqlkey.regex;if(!f)f=e.mqlkey.regex=/^[A-Za-z0-9][A-Za-z0-9_-]*$/;if(f.test(a))return{text:a,value:a};return e.invalid(a,c,"mqlkey")}});b.extend(e.number,{parse:function(a,c,f){var g=c&&c.locales||
["en"],i,k;i=0;for(k=g.length;i<k;i++){var h=g[i];c=d.number.parse(a,{locale:h});if(!isNaN(c)){a={};if(f){a.value=c;a.text=d.number.format(c,{locale:h})}else{a.value=d.number.round(c,0);a.text=d.number.format(a.value,{locale:h})}return a}}throw e.invalid("number",a);}});b.extend(e.datetime,{formats:["yyyy",["dateFormatItem-y"],"yyyy-MM",["dateFormatItem-yM","dateFormatItem-yMMM"],"yyyy-MM-dd",["dateFormat-short","dateFormat-medium","dateFormat-long"]],parse:function(a,c){if(!d.date.stamp._isoRegExp)d.date.stamp._isoRegExp=
/^(?:(-?\d{4})(?:-(\d{2})(?:-(\d{2}))?)?)?(?:T(\d{2}):(\d{2})(?::(\d{2})(.\d+)?)?((?:[+-](\d{2}):(\d{2}))|Z)?)?$/;var f=d.date.stamp.fromISOString(a);if(f)return{text:a,value:a,date:f};var g=c&&c.locales||["en"],i,k,h,j,l,m;i=0;for(k=g.length;i<k;i++){var o=g[i],p=d.date.locale._getGregorianBundle(o);h=0;for(j=e.datetime.formats.length;h<j;h+=2){var n=e.datetime.formats[h],r=e.datetime.formats[h+1];l=0;for(m=r.length;l<m;l++){var q=p[r[l]];if(q){q=i18n.normalize_pattern(q);try{f=d.date.locale.parse(a,
{datePattern:q,selector:"date",locale:o});return{text:a,value:d.date.locale.format(f,{datePattern:n,selector:"date"}),date:f}}catch(t){}}}}}throw e.invalid("datetime",a);}})})(jQuery,dojo);
(function(b){b.fn.data_input=function(d){return this.each(function(){var e=b(this),a=e.data("$.data_input");a&&a._destroy();a=new b.data_input(this,d);e.data("$.data_input",a)})};b.data_input=function(d,e){this.options=b.extend(true,{},b.data_input.defaults,e);this.container=b(d);this.metadata=this.container.metadata();this.input=b(":input",this.container);this.init();var a=this;this.input.bind("remove",function(){a._destroy()})};b.data_input.prototype={init:function(){var d=this,e=this.container,
a=this.input,c=this.options;a.bind("focusin.data_input",function(){d.container.addClass("focus")}).bind("focusout.data_input",function(){d.container.removeClass("focus")}).bind("valid.data_input",function(f,g){var i={name:d.input.attr("name")};if(g.id)i.id=g.id;else{i.value=g.value;if(d.metadata.type==="/type/text")i.lang=d.metadata.lang||c.lang}d.container.data("data",i);d.container.removeClass("error").addClass("valid");d.container.trigger("valid")}).bind("invalid.data_input",function(){d.container.removeData("data");
d.container.removeClass("valid").addClass("error");d.container.trigger("invalid")}).bind("empty.data_input",function(){var f={name:d.input.attr("name")};if(d.metadata&&d.metadata.lang)f.lang=d.metadata.lang;d.container.data("data",f);d.container.removeClass("valid").removeClass("error");d.container.trigger("empty")}).bind("keypress.data_input",function(f){f.keyCode===13&&!f.isDefaultPrevented()&&d.container.trigger("submit")}).bind("keyup.data_input",function(f){f.keyCode===27&&d.container.trigger("cancel")});
if(e.is(".topic")){e=b.extend(true,{},c.suggest,b.data_input.suggest_options(d.metadata.type));a.validate_topic(e).bind("valid.data_input",function(f,g){d.fb_select(g)}).bind("invalid.data_input",function(){d.fb_textchange()});if(this.metadata&&this.metadata.id){a.data("data.suggest",this.metadata);this.validate()}}else if(e.is(".text"))a.validate_input({validator:b.validate_input.text});else if(e.is(".datetime"))a.validate_input({validator:b.validate_input.datetime,lang:c.lang});else if(e.is(".enumerated")){a.validate_enumerated().bind("valid.data_input",
function(f,g){d.fb_select(g)}).bind("invalid.data_input",function(){d.fb_textchange()});this.metadata&&this.metadata.id&&this.validate()}else if(e.is(".int"))a.validate_input({validator:b.validate_input["int"],lang:c.lang});else if(e.is(".float"))a.validate_input({validator:b.validate_input["float"],lang:c.lang});else if(e.is(".uri"))a.validate_input({validator:b.validate_input.uri});else if(e.is(".boolean"))a.validate_boolean();else if(e.is(".enumeration"))a.validate_input({validator:b.validate_input.mqlkey});
else if(e.is(".rawstring"))a.validate_input({validator:b.validate_input.text});else throw new Error("Invalid data-input: "+e.attr("class"));},_destroy:function(){this.input.unbind(".data_input")},validate:function(){var d=this.input;b.each(["$.validate_topic","$.validate_input","$.validate_enumerated","$.validate_boolean"],function(e,a){var c=d.data(a);if(c){c.validate(true);return false}})},reset:function(){this.container.removeData("data");if(this.input.is(":text"))this.input.val("");else if(this.input.is("select"))this.input[0].selectedIndex=
0;else this.input.is(":radio")&&this.input.each(function(){this.checked=false})},fb_textchange:function(){},fb_select:function(){},ajax_beforeSend:function(d){if(!this.xhr_queue)this.xhr_queue=[];this.xhr_queue.push(d);this.container.trigger("loading")},ajax_complete:function(d){if(!this.xhr_queue)this.xhr_queue=[];for(var e=0,a=this.xhr_queue.length;e<a;e++)if(d===this.xhr_queue[e]){this.xhr_queue.splice(e,1);break}this.xhr_queue.length===0&&this.container.trigger("loading_complete")}};b.extend(b.data_input,
{defaults:{suggest:{service_url:"http://www.freebase.com",service_path:"/private/suggest",flyout_service_url:"http://www.freebase.com",flyout_service_path:"/private/flyout",mqlread_url:"http://api.freebase.com/api/service/mqlread",category:"object",type:"/common/topic"}},is_metaweb_system_type:function(d){return d.indexOf("/type/")===0||d.indexOf("/common/")===0&&d!=="/common/topic"||d.indexOf("/freebase/")===0&&d.indexOf("_profile")===d.length-8},suggest_options:function(d){var e={category:"instance",
type:d,type_strict:b.data_input.is_metaweb_system_type(d)?"any":"should"},a=["any","type:"+d,"without:fus","without:inst"];b.each(["user","domain","type"],function(c,f){if(d==="/freebase/"+f+"_profile"){a.push("type:/type/"+f);return false}});d==="/book/book_subject"&&a.push("type:/base/skosbase/skos_concept");e.filter="("+a.join(" ")+")";return e}});b.fn.validate_topic=function(d){return this.each(function(){var e=b(this);if(e.is(":text")){var a=e.data("$.validate_topic");a&&a._destroy();a=new b.validate_topic(this,
d);e.data("$.validate_topic",a)}})};b.validate_topic=function(d,e){this.options=b.extend(true,{},e);this.input=b(d);this.init()};b.validate_topic.prototype={init:function(){var d=this;this.input.suggest(this.options).bind("fb-textchange.validate_topic",function(){d.input.val()===""?d.empty():d.invalid()}).bind("fb-select.validate_topic",function(e,a){d.input.val(a.name!=null?a.name:a.id);d.valid(a)})},invalid:function(){this.input.trigger("invalid")},valid:function(d){this.input.trigger("valid",d)},
empty:function(){this.input.trigger("empty")},_destroy:function(){this.input.unbind(".validate_topic")},validate:function(){if(this.input.val()==="")this.empty();else{var d=this.input.data("data.suggest");d?this.valid(d):this.invalid()}}};b.fn.validate_enumerated=function(d){return this.each(function(){var e=b(this);if(e.is("select")){var a=e.data("$.validate_enumerated");a&&a._destroy();a=new b.validate_enumerated(this,d);e.data("$.validate_enumerated",a)}})};b.validate_enumerated=function(d,e){this.options=
b.extend(true,{},e);this.input=b(d);this.init()};b.validate_enumerated.prototype={init:function(){var d=this;this.input.bind("change.validate_enumerated, keypress.validate_enumerated",function(){this.selectedIndex===0?d.empty():d.valid({text:b(":selected",this).text(),id:this.value})})},invalid:function(){this.input.trigger("invalid")},valid:function(d){this.input.trigger("valid",d);this.input.trigger("fb-select",d)},empty:function(){this.input.trigger("empty")},_destroy:function(){this.input.unbind(".validate_enumerated")},
validate:function(){var d=this.input[0];d.selectedIndex>0?this.valid({text:b(":selected",this.input).text(),id:d.value}):this.empty()}};b.fn.validate_boolean=function(d){var e,a;this.each(function(){var f=b(this);if(f.is(":radio"))if(f.val().toLowerCase()==="true")e=f;else if(f.val().toLowerCase()==="false")a=f});if(e&&a){var c=e.data("$.validate_boolean");c&&c._destroy();c=new b.validate_boolean(e,a,d);e.data("$.validate_boolean",c)}return this};b.validate_boolean=function(d,e,a){this.options=b.extend(true,
{},a);this.tradio=d;this.fradio=e;this.input=this.tradio;this.init()};b.validate_boolean.prototype={init:function(){var d=this;this.tradio.bind("change.validate_boolean",function(){d.validate()})},_destroy:function(){this.input.unbind(".validate_boolean")},valid:function(d){this.input.trigger("valid",d)},empty:function(){this.input.trigger("empty")},validate:function(){if(this.tradio.is(":checked"))this.valid({text:this.tradio.text(),value:true});else this.fradio.is(":checked")?this.valid({text:this.fradio.text(),
value:false}):this.empty()}}})(jQuery);
(function(b){var d=window.editparams={Empty:function(e,a,c){this.structure=e;this.data=a;this.msg=c;this.toString=function(){return"Empty: "+this.msg}},Invalid:function(e,a,c){this.structure=e;this.data=a;this.msg=c;this.toString=function(){return"Invalid: "+this.msg}},parse:function(e,a){function c(h,j,l,m,o){try{d.validate(j,l);o.push(l)}catch(p){if(p instanceof d.Empty)o.push(l);else throw p;}}var f=(e.values||[]).slice(),g=e.properties||[],i=e.expected_type.mediator;if(i){if(!g.length)throw new d.Invalid(e,
null,"mediator musth have 1 or more properties");if(f.length&&f.length!==1)throw new d.Invalid(e,null,"Can't edit more than one value (row) for a mediator");}var k=[];b(".data-input",a).each(function(){var h=b(this),j=h.data("$.data_input");if(!j)throw new d.Invalid(e,null,"$.data-input not initialized for",this);j.validate(true);if(h.is(".error"))throw new d.Invalid(e,null,"$.data-input is invalid",this);j=h.data("data");if(!j)throw new d.Invalid(e,null,"$.data-input has no data",this);if(i){if(!k.length){k.push({});
b.each(g,function(o,p){k[0][p.id]=b.extend({},p,{values:[]})})}var l=k[0][j.name];if(l){var m=[];if(f.length)m=(m=f[0][l.id])&&m.values||[];c(h,l,j,m,l.values)}else console.warn("editparams","unknown mediator property data",j)}else c(h,e,j,f,k)});return i?d.parse_mediator(e,f,k):d.parse_simple(e,f,k)},parse_mediator:function(e,a,c){if(c.length!==1)throw new d.Invalid(e,c,"Must specify one (new or updated) value for a mediator");c=c[0];var f;if(a.length)f=a[0];a={};if(f)a.id=f.id;else{a.id=null;a.create=
"unconditional";a.connect=e.unique?"replace":"insert";var g=[];e.expected_type.id!=="/type/object"&&g.push({id:e.expected_type.id,connect:"insert"});var i=e.expected_type.included_types;i&&i.forEach(function(m){m!=="/type/object"&&g.push({id:m,connect:"insert"})});if(g.length)a.type=g}i=false;e=e.properties;for(var k=0,h=e.length;k<h;k++){var j=e[k],l=d.parse_simple(j,f&&f[j.id]&&f[j.id].values||[],c[j.id]&&c[j.id].values||[]);if(l.length){a[j.id]=l;i=true}}return i?[a]:[]},parse_simple:function(e,
a,c){return d.diff(e,a,c)},diff:function(e,a,c){var f=e.expected_type,g=e.expected_type.id,i=e.unique,k=g==="/type/text";if(i)if(!k)if(a.length&&a.length!==1)throw new d.Invalid(e,a,"Can't edit more than one value (row) for a unique property.");else if(c.length&&c.length!==1)throw new d.Invalid(e,c,"Can't edit more than one value (row) for a unique property.");var h=[];if(d.LITERAL_TYPE_IDS[g]){h.push("value");k&&h.push("lang")}else h.push("id");g=[];var j=[],l,m;l=0;for(m=a.length;l<m;l++){var o=
a[l];d.validate(e,o);d.inArray.apply(null,[o,c].concat(h))===-1&&g.push(d.clause(o,"delete"))}l=0;for(m=c.length;l<m;l++){o=c[l];try{d.validate(e,o)}catch(p){continue}if(d.inArray.apply(null,[o,a].concat(h))===-1){if(i)if(k){var n=d.inArray(o,g,"lang");n!==-1&&g.splice(n,1)}else return[d.clause(o,"replace",f)];j.push(d.clause(o,i?"replace":"insert",f))}}return g.concat(j)},validate:function(e,a){var c=e.expected_type.id;if(d.LITERAL_TYPE_IDS[c])if(d.isEmpty(a.value))throw new d.Empty(e,a);else{if(c===
"/type/text"&&d.isEmpty(a.lang))throw new d.Invalid(e,a,"Expected data.lang for /type/text");if(c==="/type/int"||c==="/type/float"){if(b.type(a.value)!=="number")throw new d.Invalid(e,a,"Expected number data.value for "+c);}else if(c==="/type/boolean"){if(b.type(a.value)!=="boolean")throw new d.Invalid(e,a,"Expected boolean data.value for /type/boolean");}else if(b.type(a.value)!=="string")throw new d.Invalid(e,a,"Expected string data.value for "+c);}else if(d.isEmpty(a.id))throw new d.Empty(e,a);
return a},clause:function(e,a,c){var f={connect:a};if(e.id){f.id=e.id;if(a!=="delete"&&c&&!c.enumeration){var g=[];c.id!=="/type/object"&&g.push({id:c.id,connect:"insert"});(e=c.included_types)&&e.forEach(function(i){i!=="/type/object"&&g.push({id:i,connect:"insert"})});if(g.length)f.type=g}}else{f.value=e.value;if(e.lang)f.lang=e.lang}return f},inArray:function(e,a){var c=Array.prototype.slice.call(arguments,2);if(!c.length)return b.inArray(e,a);for(var f=0,g=a.length;f<g;f++){for(var i=a[f],k=true,
h=0,j=c.length;h<j;h++){var l=c[h];if(i[l]!=e[l]){k=false;break}}if(k)return f}return-1},isEmpty:function(e){return e==null||e===""},LITERAL_TYPE_IDS:{"/type/int":1,"/type/float":1,"/type/boolean":1,"/type/rawstring":1,"/type/uri":1,"/type/text":1,"/type/datetime":1,"/type/id":1,"/type/key":1,"/type/value":1,"/type/enumeration":1}}})(jQuery);
(function(b,d,e){d.edit={text_edit_begin:function(a,c,f,g){var i={s:c,p:f,lang:g};b.ajax({url:a+"/text_edit_begin.ajax",data:i,dataType:"json",success:function(k){k=b(k.result.html);k={form:k,ajax:{base_url:a,data:b.extend({},i),url:a+"/text_edit_submit.ajax"},add_input:b(".data-input:first",k).data_input(),add_lang:b(".lang-select",k),structure:k.metadata()};d.edit.text_edit_init(k)},error:function(k){console.error("text_edit_begin",k)}})},text_edit_init:function(a){function c(h){b(".icon-link.delete",
h).click(function(){a.form.trigger(i+"delete",h)});b(".data-input",h).data_input().bind("submit",function(){a.form.trigger(i+"submit")}).bind("valid",function(){k.removeAttr("disabled").removeClass("disabled")}).bind("empty",function(){k.removeAttr("disabled").removeClass("disabled")}).metadata().lang===a.ajax.data.lang&&h.addClass("preferred")}b(document.body).append(a.form.hide());var f=b(".lang-select"),g=b(".lang-select-container");f.focus(function(){g.addClass("focused")}).blur(function(){g.removeClass("focused")});
a.form.overlay({close:".modal-buttons .button-cancel",closeOnClick:false,load:true,mask:{color:"#000",loadSpeed:200,opacity:0.5},onLoad:function(){b(":text:first",a.form).focus()}});var i="i18n.edit.text_edit.",k=b(".button-submit",a.form).click(function(){a.form.trigger(i+"submit")});b(".values > tr",a.form).each(function(){c(b(this))});f=b(".icon-link.add",a.form).bind("mouseover, focus",function(){b(this).parent().addClass("focused")}).bind("mouseout, blur",function(){b(this).parent().removeClass("focused")});
f.click(function(){a.form.trigger(i+"add")});f.focusin(function(){b(this).addClass("focused")}).focusout(function(){});a.add_lang.keypress(function(h){h.keyCode===13&&a.form.trigger(i+"add")});a.add_input.bind("submit",function(){a.form.trigger(i+"add")});a.form.bind(i+"add",function(){var h=a.add_input.data("data"),j=a.add_lang.val();if(h&&j){h=b.trim(h.value);if(h!==""){var l=b("option[value="+j.replace(/\//g,"\\/")+"]",a.add_lang),m=l.text();h=d.edit.new_text_edit_row(h,j,m).hide();b("tbody.values").prepend(h);
c(h);h.fadeIn(function(){a.add_input.data("$.data_input").reset();a.add_lang[0].selectedIndex=0;a.structure.unique&&l.attr("disabled","disabled");b(":text",a.add_input).focus()});k.removeAttr("disabled").removeClass("disabled");j!==a.ajax.data.lang&&b(".lang-warning").css("visibility","visible").hide().fadeIn("slow")}}else console.error("Text value and language required")}).bind(i+"submit",function(){d.edit.text_edit_submit(a)}).bind(i+"delete",function(h,j){j=b(j);var l=b(".data-input:first",j).metadata().lang;
j.fadeOut(function(){a.structure.unique&&b("option[value="+l.replace(/\//g,"\\/")+"]",a.add_lang).removeAttr("disabled");b(this).remove();k.removeAttr("disabled").removeClass("disabled")})})},text_edit_submit:function(a){if(!a.form.is(".loading")){var c=b(".button-submit",a.form);if(!c.is(":disabled")){document.activeElement&&b(document.activeElement).blur();var f=e.parse(a.structure,b(".values",a.form));if(f.length){a.form.addClass("loading");b.ajax({url:a.ajax.url,type:"POST",dataType:"json",data:b.extend(a.ajax.data,
{o:JSON.stringify(f)}),success:function(g,i,k){if(g.code!=="/api/status/ok")return console.error("text_edit_submt",k);window.location.reload(true)},error:function(g){console.error("text_edit_submt",g)}})}else c.attr("disabled","disabled").addClass("disabled")}}},new_text_edit_row:function(a,c,f){var g=b('<tr class="new">  <th class="row-header" scope="row">    <span class="data-input text">      <input class="fb-input" type="text">    </span>  </th>  <td class="lang">    <span></span>  </td>  <td class="delete-row">    <a class="icon-link delete" href="javascript:void(0);"><span class="delete-icon">delete</span></a>  </td></tr>'),
i=b(".data-input",g);i.addClass(JSON.stringify({value:a,lang:c,type:"/type/text"}));b(".fb-input",i).val(a);b(".lang > span",g).text(f);return g}}})(jQuery,window.i18n,window.editparams);
