
/*
 * Copyright 2012, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Additional Licenses for Third Party components can be found here:
 * http://wiki.freebase.com/wiki/Freebase_Site_License
 *
 */
(function(c){c.extend({tablesorter:new function(){function b(b,c){a(b+","+((new Date).getTime()-c.getTime())+"ms")}function a(b){"undefined"!=typeof console&&"undefined"!=typeof console.debug?console.log(b):alert(b)}function e(b,e){var p="";if(0!=b.tBodies.length){var h=b.tBodies[0].rows;if(h[0])for(var d=[],j=h[0].cells.length,k=0;k<j;k++){var m=!1;c.metadata&&c(e[k]).metadata()&&c(e[k]).metadata().sorter?m=f(c(e[k]).metadata().sorter):b.config.headers[k]&&b.config.headers[k].sorter&&(m=f(b.config.headers[k].sorter));
if(!m)a:{for(var m=b,g=h,v=-1,l=k,w=n.length,s=!1,q=!1,t=!0;""==q&&t;)v++,g[v]?(s=g[v].cells[l],q=c.trim(i(m.config,s)),m.config.debug&&a("Checking if value was empty on row:"+v)):t=!1;for(g=1;g<w;g++)if(n[g].is(q,m,s)){m=n[g];break a}m=n[0]}b.config.debug&&(p+="column:"+k+" parser:"+m.id+"\n");d.push(m)}b.config.debug&&a(p);return d}}function f(b){for(var c=n.length,a=0;a<c;a++)if(n[a].id.toLowerCase()==b.toLowerCase())return n[a];return!1}function g(a){var e;a.config.debug&&(e=new Date);for(var p=
a.tBodies[0]&&a.tBodies[0].rows.length||0,h=a.tBodies[0].rows[0]&&a.tBodies[0].rows[0].cells.length||0,d=a.config.parsers,j={row:[],normalized:[]},k=0;k<p;++k){var m=c(a.tBodies[0].rows[k]),g=[];if(m.hasClass(a.config.cssChildRow))j.row[j.row.length-1]=j.row[j.row.length-1].add(m);else{j.row.push(m);for(var f=0;f<h;++f)g.push(d[f].format(i(a.config,m[0].cells[f]),a,m[0].cells[f]));g.push(j.normalized.length);j.normalized.push(g)}}a.config.debug&&b("Building cache for "+p+" rows:",e);return j}function i(b,
a){var e="";if(!a)return"";b.supportsTextContent||(b.supportsTextContent=a.textContent||!1);return e="simple"==b.textExtraction?b.supportsTextContent?a.textContent:a.childNodes[0]&&a.childNodes[0].hasChildNodes()?a.childNodes[0].innerHTML:a.innerHTML:"function"==typeof b.textExtraction?b.textExtraction(a):c(a).text()}function w(a,e){var f;a.config.debug&&(f=new Date);for(var h=e.row,d=e.normalized,j=d.length,k=d[0].length-1,m=c(a.tBodies[0]),g=[],i=0;i<j;i++){var o=d[i][k];g.push(h[o]);if(!a.config.appender)for(var n=
h[o].length,l=0;l<n;l++)m[0].appendChild(h[o][l])}a.config.appender&&a.config.appender(a,g);g=null;a.config.debug&&b("Rebuilt table:",f);A(a);setTimeout(function(){c(a).trigger("sortEnd")},0)}function t(b,c){return b.config.headers[c]&&b.config.headers[c].lockedOrder?b.config.headers[c].lockedOrder:!1}function A(b){for(var c=b.config.widgets,a=c.length,e=0;e<a;e++)x(c[e]).format(b)}function x(b){for(var c=u.length,a=0;a<c;a++)if(u[a].id.toLowerCase()==b.toLowerCase())return u[a]}function B(b,a,e,
h){a.removeClass(h[0]).removeClass(h[1]);var d=[];a.each(function(){this.sortDisabled||(d[this.column]=c(this))});b=e.length;for(a=0;a<b;a++)d[e[a][0]].addClass(h[e[a][1]])}function y(a,c,e){var h,d;a.config.debug&&(h=new Date);var j="var sortWrapper = function(a,b) {",k=c.length;for(d=0;d<k;d++)var f=c[d][0],g=c[d][1],f="text"==a.config.parsers[f].type?0==g?l("text","asc",f):l("text","desc",f):0==g?l("numeric","asc",f):l("numeric","desc",f),i="e"+d,j=j+("var "+i+" = "+f),j=j+("if("+i+") { return "+
i+"; } "),j=j+"else { ";d=e.normalized[0].length-1;j+="return a["+d+"]-b["+d+"];";for(d=0;d<k;d++)j+="}; ";j+="return 0; }; ";a.config.debug&&b("Evaling expression:"+j,new Date);eval(j);e.normalized.sort(sortWrapper);a.config.debug&&b("Sorting on "+c.toString()+" and dir "+g+" time:",h);return e}function l(b,a,c){var e="a["+c+"]",c="b["+c+"]";if("text"==b&&"asc"==a)return"("+e+" == "+c+" ? 0 : ("+e+" === null ? Number.POSITIVE_INFINITY : ("+c+" === null ? Number.NEGATIVE_INFINITY : ("+e+" < "+c+") ? -1 : 1 )));";
if("text"==b&&"desc"==a)return"("+e+" == "+c+" ? 0 : ("+e+" === null ? Number.POSITIVE_INFINITY : ("+c+" === null ? Number.NEGATIVE_INFINITY : ("+c+" < "+e+") ? -1 : 1 )));";if("numeric"==b&&"asc"==a)return"("+e+" === null && "+c+" === null) ? 0 :("+e+" === null ? Number.POSITIVE_INFINITY : ("+c+" === null ? Number.NEGATIVE_INFINITY : "+e+" - "+c+"));";if("numeric"==b&&"desc"==a)return"("+e+" === null && "+c+" === null) ? 0 :("+e+" === null ? Number.POSITIVE_INFINITY : ("+c+" === null ? Number.NEGATIVE_INFINITY : "+
c+" - "+e+"));"}var n=[],u=[];this.defaults={cssHeader:"header",cssAsc:"headerSortUp",cssDesc:"headerSortDown",cssChildRow:"expand-child",sortInitialOrder:"asc",sortMultiSortKey:"shiftKey",sortForce:null,sortAppend:null,sortLocaleCompare:!0,textExtraction:"simple",parsers:{},widgets:[],widgetZebra:{css:["even","odd"]},headers:{},widthFixed:!1,cancelSelection:!0,sortList:[],headerList:[],dateFormat:"us",decimal:"/.|,/g",onRenderHeader:null,selectorHeaders:"thead th",debug:!1};this.benchmark=b;this.construct=
function(f){return this.each(function(){if(this.tHead&&this.tBodies){var l,p,h;this.config={};h=c.extend(this.config,c.tablesorter.defaults,f);l=c(this);c.data(this,"tablesorter",h);var d=this,j;d.config.debug&&(j=new Date);for(var k=[],m={},n=d.getElementsByTagName("THEAD")[0].getElementsByTagName("TR"),v=0;v<n.length;v++)for(var u=n[v].cells,D=0;D<u.length;D++){var s=u[D],q=s.parentNode.rowIndex,E=q+"-"+s.cellIndex,K=s.rowSpan||1,s=s.colSpan||1,C;"undefined"==typeof k[q]&&(k[q]=[]);var r;for(r=
0;r<k[q].length+1;r++)if("undefined"==typeof k[q][r]){C=r;break}m[E]=C;for(r=q;r<q+K;r++){"undefined"==typeof k[r]&&(k[r]=[]);for(var E=k[r],F=C;F<C+s;F++)E[F]="x"}}var z=c(d.config.selectorHeaders,d).each(function(b){this.column=m[this.parentNode.rowIndex+"-"+this.cellIndex];this.count=this.order="Number"!=typeof d.config.sortInitialOrder?"desc"==d.config.sortInitialOrder.toLowerCase()?1:0:1==d.config.sortInitialOrder?1:0;if(c.metadata&&!1===c(this).metadata().sorter||d.config.headers[b]&&!1===d.config.headers[b].sorter)this.sortDisabled=
!0;t(d,b)&&(this.order=this.lockedOrder=t(d,b));if(!this.sortDisabled){var a=c(this).addClass(d.config.cssHeader);d.config.onRenderHeader&&d.config.onRenderHeader.apply(a)}d.config.headerList[b]=this});d.config.debug&&(b("Built headers:",j),a(z));this.config.parsers=e(this,z);p=g(this);var G=[h.cssDesc,h.cssAsc];if(this.config.widthFixed){var H=c("<colgroup>");c("tr:first td",this.tBodies[0]).each(function(){H.append(c("<col>").css("width",c(this).width()))});c(this).prepend(H)}z.click(function(d){var b=
l[0].tBodies[0]&&l[0].tBodies[0].rows.length||0;if(!this.sortDisabled&&b>0){l.trigger("sortStart");c(this);b=this.column;this.order=this.count++%2;if(this.lockedOrder)this.order=this.lockedOrder;if(d[h.sortMultiSortKey]){a:{for(var d=h.sortList,a=d.length,j=0;j<a;j++)if(d[j][0]==b){d=true;break a}d=false}if(d)for(d=0;d<h.sortList.length;d++){a=h.sortList[d];j=h.headerList[a[0]];if(a[0]==b){j.count=a[1];j.count++;a[1]=j.count%2}}else h.sortList.push([b,this.order])}else{h.sortList=[];if(h.sortForce!=
null){a=h.sortForce;for(d=0;d<a.length;d++)a[d][0]!=b&&h.sortList.push(a[d])}h.sortList.push([b,this.order])}setTimeout(function(){B(l[0],z,h.sortList,G);w(l[0],y(l[0],h.sortList,p))},1);return false}}).mousedown(function(){if(h.cancelSelection){this.onselectstart=function(){return false};return false}});l.bind("update",function(){var d=this;setTimeout(function(){d.config.parsers=e(d,z);p=g(d)},1)}).bind("updateCell",function(d,b){var a=this.config,c=[b.parentNode.rowIndex-1,b.cellIndex];p.normalized[c[0]][c[1]]=
a.parsers[c[1]].format(i(a,b),b)}).bind("sorton",function(d,b){c(this).trigger("sortStart");h.sortList=b;for(var a=h.sortList,j=this.config,e=a.length,k=0;k<e;k++){var f=a[k],g=j.headerList[f[0]];g.count=f[1];g.count++}B(this,z,a,G);w(this,y(this,a,p))}).bind("appendCache",function(){w(this,p)}).bind("applyWidgetId",function(d,b){x(b).format(this)}).bind("applyWidgets",function(){A(this)});c.metadata&&(c(this).metadata()&&c(this).metadata().sortlist)&&(h.sortList=c(this).metadata().sortlist);0<h.sortList.length&&
l.trigger("sorton",[h.sortList]);A(this)}})};this.addParser=function(b){for(var a=n.length,c=!0,e=0;e<a;e++)n[e].id.toLowerCase()==b.id.toLowerCase()&&(c=!1);c&&n.push(b)};this.addWidget=function(b){u.push(b)};this.formatFloat=function(b){b=parseFloat(b);return isNaN(b)?0:b};this.formatInt=function(b){b=parseInt(b);return isNaN(b)?0:b};this.isDigit=function(b){return/^[-+]?\d*$/.test(c.trim(b.replace(/[,.']/g,"")))};this.clearTableBody=function(b){c.browser.msie?function(){for(;this.firstChild;)this.removeChild(this.firstChild)}.apply(b.tBodies[0]):
b.tBodies[0].innerHTML=""}}});c.fn.extend({tablesorter:c.tablesorter.construct});var i=c.tablesorter;i.addParser({id:"text",is:function(){return!0},format:function(b){return c.trim(b.toLocaleLowerCase())},type:"text"});i.addParser({id:"digit",is:function(b,a){return c.tablesorter.isDigit(b,a.config)},format:function(b){return c.tablesorter.formatFloat(b)},type:"numeric"});i.addParser({id:"currency",is:function(b){return/^[\u00a3$\u20ac?.]/.test(b)},format:function(b){return c.tablesorter.formatFloat(b.replace(RegExp(/[\u00a3$\u20ac]/g),
""))},type:"numeric"});i.addParser({id:"ipAddress",is:function(b){return/^\d{2,3}[\.]\d{2,3}[\.]\d{2,3}[\.]\d{2,3}$/.test(b)},format:function(b){for(var b=b.split("."),a="",e=b.length,f=0;f<e;f++)var g=b[f],a=2==g.length?a+("0"+g):a+g;return c.tablesorter.formatFloat(a)},type:"numeric"});i.addParser({id:"url",is:function(b){return/^(https?|ftp|file):\/\/$/.test(b)},format:function(b){return jQuery.trim(b.replace(RegExp(/(https?|ftp|file):\/\//),""))},type:"text"});i.addParser({id:"isoDate",is:function(b){return/^\d{4}[\/-]\d{1,2}[\/-]\d{1,2}$/.test(b)},
format:function(b){return c.tablesorter.formatFloat(""!=b?(new Date(b.replace(RegExp(/-/g),"/"))).getTime():"0")},type:"numeric"});i.addParser({id:"percent",is:function(b){return/\%$/.test(c.trim(b))},format:function(b){return c.tablesorter.formatFloat(b.replace(RegExp(/%/g),""))},type:"numeric"});i.addParser({id:"usLongDate",is:function(b){return b.match(RegExp(/^[A-Za-z]{3,10}\.? [0-9]{1,2}, ([0-9]{4}|'?[0-9]{2}) (([0-2]?[0-9]:[0-5][0-9])|([0-1]?[0-9]:[0-5][0-9]\s(AM|PM)))$/))},format:function(b){return c.tablesorter.formatFloat((new Date(b)).getTime())},
type:"numeric"});i.addParser({id:"shortDate",is:function(b){return/\d{1,2}[\/\-]\d{1,2}[\/\-]\d{2,4}/.test(b)},format:function(b,a){var e=a.config,b=b.replace(/\-/g,"/");if("us"==e.dateFormat)b=b.replace(/(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{4})/,"$3/$1/$2");else if("uk"==e.dateFormat)b=b.replace(/(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{4})/,"$3/$2/$1");else if("dd/mm/yy"==e.dateFormat||"dd-mm-yy"==e.dateFormat)b=b.replace(/(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{2})/,"$1/$2/$3");return c.tablesorter.formatFloat((new Date(b)).getTime())},
type:"numeric"});i.addParser({id:"time",is:function(b){return/^(([0-2]?[0-9]:[0-5][0-9])|([0-1]?[0-9]:[0-5][0-9]\s(am|pm)))$/.test(b)},format:function(b){return c.tablesorter.formatFloat((new Date("2000/01/01 "+b)).getTime())},type:"numeric"});i.addParser({id:"metadata",is:function(){return!1},format:function(b,a,e){b=a.config;b=!b.parserMetadataName?"sortValue":b.parserMetadataName;return c(e).metadata()[b]},type:"numeric"});i.addWidget({id:"zebra",format:function(b){var a;b.config.debug&&(a=new Date);
var e,f=-1,g;c("tr:visible",b.tBodies[0]).each(function(){e=c(this);e.hasClass(b.config.cssChildRow)||f++;g=0==f%2;e.removeClass(b.config.widgetZebra.css[g?0:1]).addClass(b.config.widgetZebra.css[g?1:0])});b.config.debug&&c.tablesorter.benchmark("Applying Zebra widget",a)}})})(jQuery);
(function(c){c(function(){c.tablesorter&&(c("<div>"),c.tablesorter.defaults.cssAsc="column-header-asc",c.tablesorter.defaults.cssDesc="column-header-desc",c.tablesorter.defaults.cssHeader="column-header",c.tablesorter.addParser({id:"datetime",is:function(){return!1},format:function(i,b,a){return c("[datetime]:first",a).attr("datetime")},type:"text"}),c.tablesorter.addParser({id:"ignoreCase",is:function(){return!1},format:function(c){return c.toLowerCase()},type:"text"}),c.tablesorter.addParser({id:"string",
is:function(){return!1},format:function(c){return c},type:"text"}),c.tablesorter.addParser({id:"number",is:function(){return!1},format:function(i,b,a){i=c(".number:first",a).attr("data-value");null==i&&(i=Number.MIN_VALUE);return i},type:"numeric"}),c(".table-sortable").each(function(){c(this).tablesorter()}))})})(jQuery);
(function(c){c.fn.fixedcolumn=function(i){var b=c.extend(!0,{},i);return this.each(function(){var a=c(this).find("tr:first").children();1<a.length&&(b.all||(a=c(a.get(0))),a.each(function(){var b=c(this),a=b[0].nodeName.toUpperCase();if("TD"===a||"TH"===a)a=b.width(),0<a&&c(":first-child",b).width(a).css("display","inline-block")}))})}})(jQuery);
(function(c){var i="undefined"!=typeof window.innerWidth?function(){return{w:window.innerWidth,h:window.innerHeight}}:"undefined"!=typeof document.documentElement&&"undefined"!=typeof document.documentElement.clientWidth&&0!=document.documentElement.clientWidth?function(){return{w:document.documentElement.clientWidth,h:document.documentElement.clientHeight}}:function(){return{w:document.getElementsByTagName("body")[0].clientWidth,h:document.getElementsByTagName("body")[0].clientHeight}};window.kbs=
function(b){c(".kbs.current",b).removeClass("current");var a=c(".domain-section:first",b),e=c(".domain-section:last",b),f=this.scroll_to=function(b){var a=c(document).scrollTop();c(document).height();var e=i().h,e=a+e,f=b.offset().top,b=f+b.height();f<a?c(document).scrollTop(f):b>e&&c(document).scrollTop(a+(b-e))},g=this.get_current=function(){return c(".kbs.current:first",b)},o=this.set_next=function(b,a,c){b=b||g();a.length&&(b.removeClass("current"),a.addClass("current"),c||f(a))},w=this.next_domain=
function(b){var a=g(),c=t(a);c&&(c=c.find(".kbs:first"),o(a,c,b))},t=this._next_domain=function(d){if(!d||!d.length)return c(".domain-section:first",b);d=d.closest(".domain-section");return!d.length||d[0]===e[0]?a:d.next(".domain-section")},A=this.prev_domain=function(){var b=g(),a=x(b);a&&(a=a.find(".kbs:first"),o(b,a))},x=this._prev_domain=function(d){if(!d||!d.length)return c(".domain-section:last",b);var j=d.closest(".domain-section");return d.closest(".property-section").length||d.closest(".type-section").length?
j:!j.length||j[0]===a[0]?e:j.prev(".domain-section")},B=this.next_type=function(){var b=g(),a=y(b);a&&(a=a.find(".kbs:first"),o(b,a))},y=this._next_type=function(a){if(!a||!a.length)return c(".type-section:first",b);var e=a.closest(".domain-section"),a=a.closest(".type-section"),a=a.length?a.next(".type-section"):e.find(".type-section:first");if(!a||!a.length){var f=t(e);if(f)for(;f.get(0)!==e.get(0);){a=f.find(".type-section:first");if(a.length)break;f=t(f)}}return a},l=this.prev_type=function(){var b=
g(),a=n(b);a&&(a=a.find(".kbs:first"),o(b,a))},n=this._prev_type=function(a){if(!a||!a.length)return c(".type-section:last",b);var e=a.closest(".domain-section"),f=a.closest(".type-section");if(a.closest(".property-section").length)return f;var g;f.length&&(g=f.prev(".type-section"));if(!g||!g.length)if(a=x(e))for(;a.get(0)!==e.get(0);){g=a.find(".type-section:last");if(g.length)break;a=x(a)}return g},u=this.next_prop=function(){var b=g(),a=I(b);a&&(a=a.find(".kbs:first"),o(b,a))},I=this._next_prop=
function(a){if(!a||!a.length)return c(".property-section:first",b);var e=a.closest(".domain-section"),f=a.closest(".type-section"),g=a.closest(".property-section"),e=g.length?g.next(".property-section"):f.length?f.find(".property-section:first"):e.find(".property-section:first");if(!e||!e.length)if(a=y(a))for(;a.get(0)!==f.get(0);){e=a.find(".property-section:first");if(e.length)break;null==f.get(0)&&(f=a);a=y(a)}return e},J=this.prev_prop=function(){var a=g(),b=p(a);b&&(b=b.find(".kbs:first"),o(a,
b))},p=this._prev_prop=function(a){if(!a||!a.length)return c(".property-section:last",b);var e=a.closest(".domain-section"),f=a.closest(".type-section"),g=a.closest(".property-section");if(a.closest(".data-section").length)return g;var h;g.length&&(h=g.prev(".property-section"));if(!h||!h.length)if(l=f.length?n(f):n(e))for(;l.get(0)!==f.get(0);){h=l.find(".property-section:last");if(h.length)break;null==f.get(0)&&(f=l);l=n(l)}return h};this.next=function(){var a=g(),b=this._next(a);b&&o(a,b)};this._next=
function(d){if(!d||!d.length)return c(".domain-section:first .kbs:first",b);var f=d.closest(".domain-section"),g=d.closest(".type-section"),h=d.closest(".property-section");if(d.closest(".data-section").length){d=d.next(".kbs");if(d.length)return d;d=h.next(".property-section").find(".kbs:first");if(d.length)return d;d=g.next(".type-section").find(".kbs:first")}else if(h.length){d=h.find(".data-section:first .kbs:first");if(d.length)return d;d=h.next(".property-section").find(".kbs:first");if(d.length)return d;
d=g.next(".type-section").find(".kbs:first")}else if(g.length){d=g.find(".property-section:first .kbs:first");if(d.length)return d;d=g.next(".type-section").find(".kbs:first")}else d=f.find(".type-section:first .kbs:first");return d.length?d:f.get(0)===e.get(0)?a.find(".kbs:first"):f.next(".domain-section").find(".kbs:first")};this.prev=function(){var a=g(),b=this._prev(a);b&&o(a,b)};this._prev=function(d){if(!d||!d.length)return d=c(".data-section:last .kbs:last",b),d.length||(d=c(".property-section:last .kbs:first",
b)),d.length||(d=c(".type-section:last .kbs:first",b)),d.length||(d=c(".domain-section:last .kbs:first",b)),d;var f=d.closest(".domain-section"),g=d.closest(".type-section"),h=d.closest(".property-section");return d.closest(".data-section").length?(d=d.prev(".kbs"),d.length?d:h.find(".kbs:first")):h.length?(d=h.prev(".property-section").find(".kbs:last"),d.length?d:g.find(".kbs:first")):g.length?(d=g.prev(".type-section").find(".kbs:last"),d.length?d:f.find(".kbs:first")):f.get(0)===a.get(0)?e.find(".kbs:last"):
f.prev(".domain-section").find(".kbs:last")};this.edit=function(){this.get_current().trigger("edit")};var h=this;c(document).unbind(".kbs").bind("keydown.kbs",function(a){var b=a.target;if(b==document.body||b==document||b==window||b==c("html")[0])b=a.keyCode,68===b?a.shiftKey?A():w():84===b?a.shiftKey?l():B():80===b?a.shiftKey?J():u():74===b?h.next():75===b?h.prev():69===b&&h.edit()})}})(jQuery);
(function(c,i){var b=window.propbox={init:function(a,e){e=c.extend({lang:"/lang/en"},e);if(!e.base_ajax_url)throw Error("base_ajax_url required in propbox options");if(!e.base_static_url)throw Error("base_static_url required in propbox options");if(!e.id)throw Error("topic id required in propbox options");if(!e.lang)throw Error("lang required in propbox options");b.options=e;b.kbs=new i(a);b.kbs.set_next(b.kbs.get_current(),c(".kbs:visible:first",a,!0));c(".kbs",a).live("click",function(){var a=b.kbs.get_current();
b.kbs.set_next(a,c(this),!0)}).live("edit",function(){var a=c(this).find(".headmenu:first").data("submenu");a&&c("li:first a:first",a).click()});b.init_menus(a)},init_menus:function(a,e){a=c(a||document);e&&c(".nicemenu",a).nicemenu();(a&&a.is(".data-row")?a:c(".data-row",a)).hover(b.row_menu_hoverover,b.row_menu_hoverout);c(".nicemenu .headmenu",a).add(c(".nicemenu .default-action",a)).click("click",function(){if(b.kbs){var a=b.kbs.get_current();a&&b.kbs.set_next(a,c(this).parents(".kbs:first"),
!0)}return!1})},row_menu_hoverover:function(){var a=c(this);b.row_menu_hoverover.timeout=setTimeout(function(){a.addClass("row-hover")},300)},row_menu_hoverout:function(){clearTimeout(b.row_menu_hoverover.timeout);c(this).removeClass("row-hover")},get_script:function(a,e){var f=b.get_script.cache;f||(f=b.get_script.cache={});var g=f[a];g?1===g.state?g.callbacks.push(e):4===g.state&&e():(g=f[a]={state:0,callbacks:[e]},c.ajax({url:b.options.base_static_url+a,dataType:"script",beforeSend:function(){g.state=
1},success:function(){g.state=4;c.each(g.callbacks,function(a,b){b()})},error:function(){g.state=-1}}))},prop_edit:function(a,e){var f=c(a).parents(".submenu").data("headmenu").parents(".property-section").find(".data-section .data-row:first:visible .nicemenu:first .headmenu:first a");f.length?f.click():b.prop_add(a,e);return!1},prop_add:function(a,e){var f=c(a).parents(".submenu").data("headmenu").parents(".property-section");b.get_script("/propbox-edit.mf.js",function(){b.edit.prop_add_begin(f,
e)});return!1},value_edit:function(a){var e=c(a).parents(".submenu").data("headmenu").parents(".data-row:first"),f=e.parents(".property-section");b.get_script("/propbox-edit.mf.js",function(){b.edit.value_edit_begin(f,e)});return!1},value_delete:function(a){var e=c(a).parents(".submenu").data("headmenu").parents(".data-row:first"),f=e.parents(".property-section");b.get_script("/propbox-edit.mf.js",function(){b.edit.value_delete_begin(f,e)});return!1},remove_type:function(a){var a=c(a),e=a.parents(".type-section");
b.get_script("/propbox-edit.mf.js",function(){b.edit.remove_type_submit(a,e)});return!1},add_type:function(a,e,f){var a=c(a),g=a.parents(".type-section"),i=b.options.incompatible_types;i?i.search(b.options.id,e,f,{compatible:function(){b.add_type_submit(a,g)},incompatible:i.overlay_incompatible_callback({onConfirm:function(){b.add_type_submit(a,g)}})}):b.add_type_submit(a,g);return!1},add_type_submit:function(a,c){b.get_script("/propbox-edit.mf.js",function(){b.edit.add_type_submit(a,c)})},add_has_no_value:function(a){var e=
c(a).parents(".submenu").data("headmenu").parents(".property-section");b.get_script("/propbox-edit.mf.js",function(){b.edit.add_has_no_value(e)});return!1},add_has_value:function(a){var e=c(a).parents(".submenu").data("headmenu").parents(".property-section");b.get_script("/propbox-edit.mf.js",function(){b.edit.add_has_value(e)});return!1},remove_has_no_value:function(a){var e=c(a).parents(".property-section");b.get_script("/propbox-edit.mf.js",function(){b.edit.remove_has_no_value(e)});return!1},
remove_has_value:function(a){var e=c(a).parents(".property-section");b.get_script("/propbox-edit.mf.js",function(){b.edit.remove_has_value(e)});return!1},more:function(a,e,f){var g=c(a).parents(".property-section");b.get_script("/propbox-edit.mf.js",function(){b.edit.more(g,e,f)})}}})(jQuery,window.kbs);
(function(c,i,b){var a=i.i18n_tab={init:function(){c("#i18n-table").fixedcolumn();b.init_menus()},add_name:function(b,f){var g=c(b).parents(".data-row:first");i.get_script(i.h.static_url("i18n-edit.mf.js"),function(){a.edit.add_name_begin(g,f)});return!1},edit_name:function(b,f,g){var o=c(b).parents(".submenu").data("headmenu").parents(".data-row:first");i.get_script(i.h.static_url("i18n-edit.mf.js"),function(){a.edit.edit_name_begin(o,f,g)});return!1},delete_name:function(b,f,g){var o=c(b).parents(".submenu").data("headmenu").parents(".data-row:first");
i.get_script(i.h.static_url("i18n-edit.mf.js"),function(){a.edit.delete_name_begin(o,f,g)});return!1}};c(a.init)})(jQuery,window.freebase,window.propbox);
