
/*
 * Copyright 2012, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Additional Licenses for Third Party components can be found here:
 * http://wiki.freebase.com/wiki/Freebase_Site_License
 *
 */
/*
 
 jQuery Tools @VERSION / Expose - Dim the lights

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/toolbox/expose.html

 Since: Mar 2010
 Date: @DATE 
 
 jQuery Tools @VERSION Overlay - Overlay base. Extend it.

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/overlay/

 Since: March 2008
 Date: @DATE 
*/
(function(d){var c="undefined"!=typeof window.innerWidth?function(){return{w:window.innerWidth,h:window.innerHeight}}:"undefined"!=typeof document.documentElement&&"undefined"!=typeof document.documentElement.clientWidth&&0!=document.documentElement.clientWidth?function(){return{w:document.documentElement.clientWidth,h:document.documentElement.clientHeight}}:function(){return{w:document.getElementsByTagName("body")[0].clientWidth,h:document.getElementsByTagName("body")[0].clientHeight}};window.kbs=
function(b){d(".kbs.current",b).removeClass("current");var a=d(".domain-section:first",b),f=d(".domain-section:last",b),e=this.scroll_to=function(a){var b=d(document).scrollTop();d(document).height();var f=c().h,f=b+f,g=a.offset().top,a=g+a.height();g<b?d(document).scrollTop(g):a>f&&d(document).scrollTop(b+(a-f))},g=this.get_current=function(){return d(".kbs.current:first",b)},j=this.set_next=function(a,b,d){a=a||g();b.length&&(a.removeClass("current"),b.addClass("current"),d||e(b))},k=this.next_domain=
function(a){var b=g(),d=h(b);d&&(d=d.find(".kbs:first"),j(b,d,a))},h=this._next_domain=function(c){if(!c||!c.length)return d(".domain-section:first",b);c=c.closest(".domain-section");return!c.length||c[0]===f[0]?a:c.next(".domain-section")},i=this.prev_domain=function(){var a=g(),b=l(a);b&&(b=b.find(".kbs:first"),j(a,b))},l=this._prev_domain=function(c){if(!c||!c.length)return d(".domain-section:last",b);var g=c.closest(".domain-section");return c.closest(".property-section").length||c.closest(".type-section").length?
g:!g.length||g[0]===a[0]?f:g.prev(".domain-section")},m=this.next_type=function(){var a=g(),b=o(a);b&&(b=b.find(".kbs:first"),j(a,b))},o=this._next_type=function(a){if(!a||!a.length)return d(".type-section:first",b);var f=a.closest(".domain-section"),a=a.closest(".type-section"),a=a.length?a.next(".type-section"):f.find(".type-section:first");if(!a||!a.length){var c=h(f);if(c)for(;c.get(0)!==f.get(0);){a=c.find(".type-section:first");if(a.length)break;c=h(c)}}return a},n=this.prev_type=function(){var a=
g(),b=p(a);b&&(b=b.find(".kbs:first"),j(a,b))},p=this._prev_type=function(a){if(!a||!a.length)return d(".type-section:last",b);var f=a.closest(".domain-section"),c=a.closest(".type-section");if(a.closest(".property-section").length)return c;var g;c.length&&(g=c.prev(".type-section"));if(!g||!g.length)if(a=l(f))for(;a.get(0)!==f.get(0);){g=a.find(".type-section:last");if(g.length)break;a=l(a)}return g},r=this.next_prop=function(){var a=g(),b=t(a);b&&(b=b.find(".kbs:first"),j(a,b))},t=this._next_prop=
function(a){if(!a||!a.length)return d(".property-section:first",b);var f=a.closest(".domain-section"),c=a.closest(".type-section"),g=a.closest(".property-section"),f=g.length?g.next(".property-section"):c.length?c.find(".property-section:first"):f.find(".property-section:first");if(!f||!f.length)if(a=o(a))for(;a.get(0)!==c.get(0);){f=a.find(".property-section:first");if(f.length)break;null==c.get(0)&&(c=a);a=o(a)}return f},u=this.prev_prop=function(){var a=g(),b=s(a);b&&(b=b.find(".kbs:first"),j(a,
b))},s=this._prev_prop=function(a){if(!a||!a.length)return d(".property-section:last",b);var f=a.closest(".domain-section"),c=a.closest(".type-section"),g=a.closest(".property-section");if(a.closest(".data-section").length)return g;var e;g.length&&(e=g.prev(".property-section"));if(!e||!e.length)if(n=c.length?p(c):p(f))for(;n.get(0)!==c.get(0);){e=n.find(".property-section:last");if(e.length)break;null==c.get(0)&&(c=n);n=p(n)}return e};this.next=function(){var a=g(),b=this._next(a);b&&j(a,b)};this._next=
function(c){if(!c||!c.length)return d(".domain-section:first .kbs:first",b);var g=c.closest(".domain-section"),e=c.closest(".type-section"),j=c.closest(".property-section");if(c.closest(".data-section").length){c=c.next(".kbs");if(c.length)return c;c=j.next(".property-section").find(".kbs:first");if(c.length)return c;c=e.next(".type-section").find(".kbs:first")}else if(j.length){c=j.find(".data-section:first .kbs:first");if(c.length)return c;c=j.next(".property-section").find(".kbs:first");if(c.length)return c;
c=e.next(".type-section").find(".kbs:first")}else if(e.length){c=e.find(".property-section:first .kbs:first");if(c.length)return c;c=e.next(".type-section").find(".kbs:first")}else c=g.find(".type-section:first .kbs:first");return c.length?c:g.get(0)===f.get(0)?a.find(".kbs:first"):g.next(".domain-section").find(".kbs:first")};this.prev=function(){var a=g(),b=this._prev(a);b&&j(a,b)};this._prev=function(c){if(!c||!c.length)return c=d(".data-section:last .kbs:last",b),c.length||(c=d(".property-section:last .kbs:first",
b)),c.length||(c=d(".type-section:last .kbs:first",b)),c.length||(c=d(".domain-section:last .kbs:first",b)),c;var g=c.closest(".domain-section"),e=c.closest(".type-section"),j=c.closest(".property-section");return c.closest(".data-section").length?(c=c.prev(".kbs"),c.length?c:j.find(".kbs:first")):j.length?(c=j.prev(".property-section").find(".kbs:last"),c.length?c:e.find(".kbs:first")):e.length?(c=e.prev(".type-section").find(".kbs:last"),c.length?c:g.find(".kbs:first")):g.get(0)===a.get(0)?f.find(".kbs:last"):
g.prev(".domain-section").find(".kbs:last")};this.edit=function(){this.get_current().trigger("edit")};var q=this;d(document).unbind(".kbs").bind("keydown.kbs",function(a){var b=a.target;if(b==document.body||b==document||b==window||b==d("html")[0])b=a.keyCode,68===b?a.shiftKey?i():k():84===b?a.shiftKey?n():m():80===b?a.shiftKey?u():r():74===b?q.next():75===b?q.prev():69===b&&q.edit()})}})(jQuery);
(function(d,c){var b=window.propbox={init:function(a,f){f=d.extend({lang:"/lang/en"},f);if(!f.base_ajax_url)throw Error("base_ajax_url required in propbox options");if(!f.base_static_url)throw Error("base_static_url required in propbox options");if(!f.id)throw Error("topic id required in propbox options");if(!f.lang)throw Error("lang required in propbox options");b.options=f;b.kbs=new c(a);b.kbs.set_next(b.kbs.get_current(),d(".kbs:visible:first",a,!0));d(".kbs",a).live("click",function(){var a=b.kbs.get_current();
b.kbs.set_next(a,d(this),!0)}).live("edit",function(){var a=d(this).find(".headmenu:first").data("submenu");a&&d("li:first a:first",a).click()});b.init_menus(a)},init_menus:function(a,c){a=d(a||document);c&&d(".nicemenu",a).nicemenu();(a&&a.is(".data-row")?a:d(".data-row",a)).hover(b.row_menu_hoverover,b.row_menu_hoverout);d(".nicemenu .headmenu",a).add(d(".nicemenu .default-action",a)).click("click",function(){if(b.kbs){var a=b.kbs.get_current();a&&b.kbs.set_next(a,d(this).parents(".kbs:first"),
!0)}return!1})},row_menu_hoverover:function(){var a=d(this);b.row_menu_hoverover.timeout=setTimeout(function(){a.addClass("row-hover")},300)},row_menu_hoverout:function(){clearTimeout(b.row_menu_hoverover.timeout);d(this).removeClass("row-hover")},get_script:function(a,c){var e=b.get_script.cache;e||(e=b.get_script.cache={});var g=e[a];g?1===g.state?g.callbacks.push(c):4===g.state&&c():(g=e[a]={state:0,callbacks:[c]},d.ajax({url:b.options.base_static_url+a,dataType:"script",beforeSend:function(){g.state=
1},success:function(){g.state=4;d.each(g.callbacks,function(a,b){b()})},error:function(){g.state=-1}}))},prop_edit:function(a,c){var e=d(a).parents(".submenu").data("headmenu").parents(".property-section").find(".data-section .data-row:first:visible .nicemenu:first .headmenu:first a");e.length?e.click():b.prop_add(a,c);return!1},prop_add:function(a,c){var e=d(a).parents(".submenu").data("headmenu").parents(".property-section");b.get_script("/propbox-edit.mf.js",function(){b.edit.prop_add_begin(e,
c)});return!1},value_edit:function(a){var c=d(a).parents(".submenu").data("headmenu").parents(".data-row:first"),e=c.parents(".property-section");b.get_script("/propbox-edit.mf.js",function(){b.edit.value_edit_begin(e,c)});return!1},value_delete:function(a){var c=d(a).parents(".submenu").data("headmenu").parents(".data-row:first"),e=c.parents(".property-section");b.get_script("/propbox-edit.mf.js",function(){b.edit.value_delete_begin(e,c)});return!1},close_message:function(a){d(a).parents(".row-msg:first").remove();
return!1}}})(jQuery,window.kbs);
(function(d){function c(){if(d.browser.msie){var a=d(document).height(),b=d(window).height();return[window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth,20>a-b?b:a]}return[d(document).width(),d(document).height()]}function b(a){if(a)return a.call(d.mask)}d.tools=d.tools||{version:"@VERSION"};var a;a=d.tools.expose={conf:{maskId:"exposeMask",loadSpeed:"slow",closeSpeed:"fast",closeOnClick:!0,closeOnEsc:!0,zIndex:9998,opacity:0.8,startOpacity:0,color:"#fff",onLoad:null,
onClose:null}};var f,e,g,j,k;d.mask={load:function(h,i){if(g)return this;"string"==typeof h&&(h={color:h});h=h||j;j=h=d.extend(d.extend({},a.conf),h);f=d("#"+h.maskId);f.length||(f=d("<div/>").attr("id",h.maskId),d("body").append(f));var l=c();f.css({position:"absolute",top:0,left:0,width:l[0],height:l[1],display:"none",opacity:h.startOpacity,zIndex:h.zIndex});h.color&&f.css("backgroundColor",h.color);if(!1===b(h.onBeforeLoad))return this;h.closeOnEsc&&d(document).bind("keydown.mask",function(a){a.keyCode==
27&&d.mask.close(a)});h.closeOnClick&&f.bind("click.mask",function(a){d.mask.close(a)});d(window).bind("resize.mask",function(){d.mask.fit()});i&&i.length&&(k=i.eq(0).css("zIndex"),d.each(i,function(){var a=d(this);/relative|absolute|fixed/i.test(a.css("position"))||a.css("position","relative")}),e=i.css({zIndex:Math.max(h.zIndex+1,"auto"==k?0:k)}));f.css({display:"block"}).fadeTo(h.loadSpeed,h.opacity,function(){d.mask.fit();b(h.onLoad)});g=!0;return this},close:function(){if(g){if(!1===b(j.onBeforeClose))return this;
f.fadeOut(j.closeSpeed,function(){b(j.onClose);e&&e.css({zIndex:k})});d(document).unbind("keydown.mask");f.unbind("click.mask");d(window).unbind("resize.mask");g=!1}return this},fit:function(){if(g){var a=c();f.css({width:a[0],height:a[1]})}},getMask:function(){return f},isLoaded:function(){return g},getConf:function(){return j},getExposed:function(){return e}};d.fn.mask=function(a){d.mask.load(a);return this};d.fn.expose=function(a){d.mask.load(a,this);return this}})(jQuery);
(function(d){function c(c,e){var g=this,j=c.add(g),k=d(window),h,i,l,m=d.tools.expose&&(e.mask||e.expose),o=Math.random().toString().slice(10);m&&("string"==typeof m&&(m={color:m}),m.closeOnClick=m.closeOnEsc=!1);var n=e.target||c.attr("rel");i=n?d(n):c;if(!i.length)throw"Could not find Overlay: "+n;c&&-1==c.index(i)&&c.click(function(a){g.load(a);return a.preventDefault()});d.extend(g,{load:function(c){if(g.isOpened())return g;var f=a[e.effect];if(!f)throw'Overlay: cannot find effect : "'+e.effect+
'"';e.oneInstance&&d.each(b,function(){this.close(c)});c=c||d.Event();c.type="onBeforeLoad";j.trigger(c);if(c.isDefaultPrevented())return g;l=true;m&&d(i).expose(m);var h=e.top,n=e.left,s=i.outerWidth({margin:true}),q=i.outerHeight({margin:true});typeof h=="string"&&(h=h=="center"?Math.max((k.height()-q)/2,0):parseInt(h,10)/100*k.height());n=="center"&&(n=Math.max((k.width()-s)/2,0));f[0].call(g,{top:h,left:n},function(){if(l){c.type="onLoad";j.trigger(c)}});if(m&&e.closeOnClick)d.mask.getMask().one("click",
g.close);e.closeOnClick&&d(document).bind("click."+o,function(a){d(a.target).parents(i).length||g.close(a)});e.closeOnEsc&&d(document).bind("keydown."+o,function(a){a.keyCode==27&&g.close(a)});return g},close:function(b){if(!g.isOpened())return g;b=b||d.Event();b.type="onBeforeClose";j.trigger(b);if(!b.isDefaultPrevented()){l=false;a[e.effect][1].call(g,function(){b.type="onClose";j.trigger(b)});d(document).unbind("click."+o).unbind("keydown."+o);m&&d.mask.close();return g}},getOverlay:function(){return i},
getTrigger:function(){return c},getClosers:function(){return h},isOpened:function(){return l},getConf:function(){return e}});d.each(["onBeforeLoad","onStart","onLoad","onBeforeClose","onClose"],function(a,b){d.isFunction(e[b])&&d(g).bind(b,e[b]);g[b]=function(a){d(g).bind(b,a);return g}});h=i.find(e.close||".close");!h.length&&!e.close&&(h=d('<a class="close"></a>'),i.prepend(h));h.click(function(a){g.close(a)});e.load&&g.load()}d.tools=d.tools||{version:"@VERSION"};d.tools.overlay={addEffect:function(b,
c,d){a[b]=[c,d]},conf:{close:null,closeOnClick:!0,closeOnEsc:!0,closeSpeed:"fast",effect:"default",fixed:!d.browser.msie||6<d.browser.version,left:"center",load:!1,mask:null,oneInstance:!0,speed:"normal",target:null,top:"10%"}};var b=[],a={};d.tools.overlay.addEffect("default",function(a,b){var c=this.getConf(),j=d(window);c.fixed||(a.top+=j.scrollTop(),a.left+=j.scrollLeft());a.position=c.fixed?"fixed":"absolute";this.getOverlay().css(a).fadeIn(c.speed,b)},function(a){this.getOverlay().fadeOut(this.getConf().closeSpeed,
a)});d.fn.overlay=function(a){var e=this.data("overlay");if(e)return e;d.isFunction(a)&&(a={onBeforeLoad:a});a=d.extend(!0,{},d.tools.overlay.conf,a);this.each(function(){e=new c(d(this),a);b.push(e);d(this).data("overlay",e)});return a.api?e:this}})(jQuery);
(function(d){d.fn.mqlkey=function(b){return this.each(function(){var a=d(this);if(a.is(":text")){var f=a.data("mqlkey");f&&f._destroy();f=new c(this,b);a.data("mqlkey",f)}})};var c=d.mqlkey=function(b,a){this.options=d.extend(!0,{},c.defaults,a);this.input=d(b);this.original=this.input.val();this.init()};c.prototype={init:function(){var b=this;this.input.bind("keyup.mqlkey",function(a){b.textchange(a)}).bind(d.browser.msie?"paste.mqlkey":"input.mqlkey",function(a){b.textchange(a)});this.options.source&&
(this.source=d(this.options.source),this.source_generate=""===this.source.val()?!0:!1,this.input.bind("change.mqlkey",function(){b.source_generate=!1}),this.source.bind("change.mqlkey",function(){if(b.source_generate){var a=c.from(b.source.val());b.input.val(a).trigger("keyup")}}))},_destroy:function(){this.input.unbind(".mqlkey");this.source&&this.source.unbind("change.mqlkey")},textchange:function(b){clearTimeout(this.textchange_timeout);var a=this;this.textchange_timeout=setTimeout(function(){a.textchange_delay(b)},
200)},textchange_delay:function(){this.input.trigger("textchange");var b=d.trim(this.input.val());return b===this.original&&""!==b?this.valid(b):c.reserved_word(b)?this.invalid(b,b+" is a reserved word."):c.test(b,this.options.schema)?b.length<this.options.minlen?this.invalid(b):this.options.check_key?this.check_key(b):this.valid(b):this.invalid(b)},check_key:function(b){var a=this;this.xhr&&(this.xhr=null);var c={id:null,key:{namespace:this.options.namespace,value:b}};clearTimeout(this.check_key.timeout);
this.check_key.timeout=setTimeout(function(){a.xhr=a.options.mqlread(c,function(c){return c?a.invalid(b,"Key already exists"):a.valid(b)},function(b){return b?a.invalid(b.responseText()):a.invalid("mqlread error!")})},200)},valid:function(b){this.input.trigger("valid",b)},invalid:function(b,a){a||(a=1<this.options.minlen?"Key must be "+this.options.minlen+" or more alphanumeric characters":"Key must be alphanumeric",a+=", lowercase, begin with a letter and not end with a non-alphanumeric character. Underscores are allowed but not consecutively.");
this.input.trigger("invalid",a)}};d.extend(c,{defaults:{minlen:1,check_key:!0,namespace:"/",mqlread:function(b,a,d){return c.mqlread(null,b,a,d)},source:null,schema:!1},mqlread:function(b,a,c,e){b={url:b||"http://api.freebase.com/api/service/mqlread",data:{query:JSON.stringify({query:a})},dataType:"jsonp",success:function(a){return c(a.result)},error:e};return d.ajax(b)},from:function(b){b=b.toLowerCase();b=b.replace(/[^a-z0-9]/g,"_");b=b.replace(/\_\_+/g,"_");b=b.replace(/[^a-z0-9]+$/,"");b=b.replace(/^[^a-z]+/,
"");c.reserved_word(b)&&(b="x_"+b);return b},reservedwords:"meta typeguid left right datatype scope attribute relationship property link class future update insert delete replace create destroy default sort limit offset optional pagesize cursor index !index for while as in is if else return count function read write select var connect this self super xml sql mql any all macro estimate-count",typeonlywords:"guid id object domain name key type keys value timestamp creator permission namespace unique schema reverse",
_reserved_word:null,reserved_word:function(b){c._reserved_word||(c._reserved_word={},d.each([c.reservedwords,c.typeonlywords],function(a,b){d.each(b.split(" "),function(a,b){c._reserved_word[b]=1})}));return 1===c._reserved_word[b]},fast:/^[A-Za-z0-9](?:[_-]?[A-Za-z0-9])*$/,slow:/^(?:[A-Za-z0-9]|\$[A-F0-9]{4})(?:[_-]?[A-Za-z0-9]|[_-]?\$[A-F0-9]{4})*$/,schema:/^[a-z](?:_?[a-z0-9])*$/,test:function(b,a){return a?c.schema.test(b):c.fast.test(b)||c.slow.test(b)}})})(jQuery);
(function(d){d.fn.validate_input=function(b){return this.each(function(){var a=d(this);if(a.is(":text")){var f=a.data("$.validate_input");f&&f._destroy();f=new c(this,b);a.data("$.validate_input",f)}})};var c=d.validate_input=function(b,a){if("function"!==typeof(this.options=d.extend(!0,{},c.defaults,a)).validator)throw"A validator is required";this.input=d(b);this.init();var f=this;this.input.bind("remove",function(){f._destroy()});return this};c.prototype={init:function(){var b=this;this.input.bind("keyup.validate_input",
function(a){b.textchange(a)}).bind(d.browser.msie?"paste.validate_input":"input.validate_input",function(a){b.textchange(a)}).bind("keypress.validate_input",function(a){13===a.keyCode&&b.validate(!0)}).bind("blur.validate_input",function(){b.validate(!0)})},_destroy:function(){this.input.unbind(".validate_input")},valid:function(b){this.input.trigger("valid",b)},invalid:function(b,a){this.input.trigger("invalid",a)},empty:function(){this.input.trigger("empty")},textchange:function(){clearTimeout(this.textchange_timeout);
var b=this;this.textchange_timeout=setTimeout(function(){b.validate()},200)},validate:function(b){b&&clearTimeout(this.textchange_timeout);var b=this.options,a=d.trim(this.input.val());if(""===a)return this.empty();try{var c=b.validator(a,b);return this.valid(c)}catch(e){return this.invalid(a,""+e)}}};d.extend(c,{defaults:{validator:function(b){return{text:b,value:b}}},log:function(){},invalid:function(b,a,c,d){throw Error("Invalid "+c+(d?": "+d:""));},text:function(b,a){return 4096<b.lengh?this.invalid(b,
a,type,"Text too long"):{text:b,value:b}},topic:function(){return c.defaults.validator},enumerated:function(){return c.defaults.validator},"boolean":function(){return c.defaults.validator},uri:function(b,a){var d=c.uri.regex;d||(d=c.uri.regex=/^(https?|ftp):\/\/(((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:)*@)?(((\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5]))|((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?)(:\d*)?)(\/((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)+(\/(([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)*)*)?)?(\?((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|[\uE000-\uF8FF]|\/|\?)*)?(\#((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|\/|\?)*)?$/i);
return d.test(b)?{text:b,value:b}:c.invalid(b,a,"uri")},"int":function(b,a){return c.number.parse(b,a,!1)},"float":function(b,a){return c.number.parse(b,a,!0)},number:function(b,a,d){return c.number.parse(b,a,d)},datetime:function(b,a){return c.datetime.parse(b,a)},mqlkey:function(b,a){var d=c.mqlkey.regex;d||(d=c.mqlkey.regex=/^[A-Za-z0-9][A-Za-z0-9_-]*$/);return d.test(b)?{text:b,value:b}:c.invalid(b,a,"mqlkey")}});d.extend(c.number,{parse:function(b,a,d){a=null;a=d?Globalize.parseFloat(b):Globalize.parseInt(b,
10);if(isNaN(a))throw c.invalid("number",b);if(d){var b="n",d=""+a,e=d.indexOf(".");-1!==e&&(b="n"+d.substr(e+1).length);return{value:a,text:Globalize.format(a,b)}}return{value:a,text:Globalize.format(a,"n0")}}});d.extend(c.datetime,{regexp:{iso:/^(?:(-?\d{4})(?:-(\d{2})(?:-(\d{2}))?)?)?(?:T(\d{2}):(\d{2})(?::(\d{2})(.\d+)?)?((?:[+-](\d{2}):(\d{2}))|Z)?)?$/,time:/^T?([01][0-9]|2[0-3])(:[0-5][0-9]){0,2}$/,bce:[/^(\d+)\s*[Bb]\.*[Cc]\.*[Ee]*/,/^[Bb]\.*[Cc]\.*[Ee]*\s*(\d+)/]},formats:"d yyyy-MM-dd Y yyyy-MM t HH:mm T HH:mm:ss".split(" "),
padyear:function(b){return 10>b?"000"+b:100>b?"00"+b:1E3>b?"0"+b:""+b},parse:function(b){var a,d,e;if(c.datetime.regexp.iso.test(b)||c.datetime.regexp.time.test(b))return d=b,0===d.indexOf("T")&&(d=d.substring(1)),{text:b,value:d};d=0;for(e=c.datetime.regexp.bce.length;d<e;d++)if(a=c.datetime.regexp.bce[d].exec(b))return d=parseInt(a[1],10),d-=1,d=c.datetime.padyear(d),{text:b,value:"-"+d};d=0;for(e=c.datetime.formats.length;d<e;d+=2)if(a=Globalize.parseDate(b,c.datetime.formats[d]))return{text:b,
value:Globalize.format(a,c.datetime.formats[d+1])};if(a=Globalize.parseDate(b))return{text:b,value:Globalize.format(a,"S")};throw c.invalid("datetime",b);}})})(jQuery,window.Globalize);
(function(d){d.fn.data_input=function(c){return this.each(function(){var b=d(this),a=b.data("$.data_input");a&&a._destroy();a=new d.data_input(this,c);b.data("$.data_input",a)})};d.data_input=function(c,b){this.options=d.extend(!0,{},b);this.container=d(c);this.metadata=this.container.metadata();this.input=d(":input",this.container);this.init();var a=this;this.input.bind("remove",function(){a._destroy()})};d.data_input.prototype={init:function(){var c=this,b=this.container,a=this.input,f=this.options;
a.bind("focusin.data_input",function(){c.container.addClass("focus")}).bind("focusout.data_input",function(){c.container.removeClass("focus")}).bind("valid.data_input",function(a,b){a.stopPropagation();var d={name:c.input.attr("name")};b.id?d.id=b.id:b.create_new?(d.create_new=b.create_new,d.lang=c.metadata.lang||f.lang):(d.value=b.value,"/type/text"===c.metadata.type?d.lang=c.metadata.lang||f.lang:"/type/key"===c.metadata.type&&(d.namespace=b.namespace));b.incompatible_types&&(d.incompatible_types=
b.incompatible_types);c.container.data("data",d);c.container.removeClass("error").addClass("valid");c.container.trigger("valid")}).bind("invalid.data_input",function(a){a.stopPropagation();c.container.removeData("data");c.container.removeClass("valid").addClass("error");c.container.trigger("invalid")}).bind("empty.data_input",function(a){a.stopPropagation();a={name:c.input.attr("name")};c.metadata&&c.metadata.lang&&(a.lang=c.metadata.lang);c.container.data("data",a);c.container.removeClass("valid").removeClass("error");
c.container.trigger("empty")}).bind("keypress.data_input",function(a){13===a.keyCode&&!a.isDefaultPrevented()&&c.container.trigger("submit")}).bind("keyup.data_input",function(a){27===a.keyCode&&c.container.trigger("cancel")});if(b.is(".topic")){var b=c.metadata.type,e=null;f.suggest_impl&&(e=f.suggest_impl.instance(b,!0,c.metadata&&c.metadata.lang||f.lang));a.validate_topic(d.extend({incompatible_types:c.options.incompatible_types,expected_type:b},e)).bind("valid.data_input",function(a,b){c.fb_select(b)}).bind("invalid.data_input",
function(){c.fb_textchange()});this.metadata&&this.metadata.id&&(a.data("data.suggest",this.metadata),this.validate())}else if(b.is(".text"))a.validate_input({validator:d.validate_input.text});else if(b.is(".datetime"))a.validate_input({validator:d.validate_input.datetime,lang:f.lang});else if(b.is(".enumerated"))a.validate_enumerated().bind("valid.data_input",function(a,b){c.fb_select(b)}).bind("invalid.data_input",function(){c.fb_textchange()}),this.metadata&&this.metadata.id&&this.validate();else if(b.is(".int"))a.validate_input({validator:d.validate_input["int"],
lang:f.lang});else if(b.is(".float"))a.validate_input({validator:d.validate_input["float"],lang:f.lang});else if(b.is(".uri"))a.validate_input({validator:d.validate_input.uri});else if(b.is(".boolean"))a.validate_boolean();else if(b.is(".enumeration"))a.validate_input({validator:d.validate_input.mqlkey});else if(b.is(".key"))a.validate_key(f,this.metadata);else if(b.is(".rawstring"))a.validate_input({validator:d.validate_input.text});else throw Error("Invalid data-input: "+b.attr("class"));},_destroy:function(){this.input.unbind(".data_input")},
validate:function(){var c=this.input;d.each(["$.validate_topic","$.validate_input","$.validate_enumerated","$.validate_boolean","$.validate_key"],function(b,a){var d=c.data(a);if(d)return d.validate(!0),!1})},reset:function(){this.container.removeData("data");this.input.is(":text")?this.input.val(""):this.input.is("select")?this.input[0].selectedIndex=0:this.input.is(":radio")&&this.input.each(function(){this.checked=!1})},fb_textchange:function(){},fb_select:function(){},ajax_beforeSend:function(c){this.xhr_queue||
(this.xhr_queue=[]);this.xhr_queue.push(c);this.container.trigger("loading")},ajax_complete:function(c){this.xhr_queue||(this.xhr_queue=[]);for(var b=0,a=this.xhr_queue.length;b<a;b++)if(c===this.xhr_queue[b]){this.xhr_queue.splice(b,1);break}0===this.xhr_queue.length&&this.container.trigger("loading_complete")}};d.fn.validate_topic=function(c){return this.each(function(){var b=d(this);if(b.is(":text")){var a=b.data("$.validate_topic");a&&a._destroy();a=new d.validate_topic(this,c);b.data("$.validate_topic",
a)}})};d.validate_topic=function(c,b){this.options=d.extend(!0,{},b);this.input=d(c);this.init()};d.validate_topic.prototype={init:function(){var c=this;this.incompatible_types={};this.input.suggest(this.options).bind("fb-textchange.validate_topic",function(){""===c.input.val()?c.empty():c.invalid()}).bind("fb-select.validate_topic",function(b,a){c.input.val(null!=a.name?a.name:a.id);c.incompatible_types_check(a)}).bind("fb-select-new.validate_topic",function(b,a){c.valid(a)})},incompatible_types_check:function(c){var b=
this;b.options.incompatible_types&&b.options.expected_type?b.options.incompatible_types.check(c.id,b.options.expected_type,{compatible:function(){b.valid(c)},incompatible:b.options.incompatible_types.inline_suggest_incompatible_callback(b.input,{onConfirm:function(a,d,e){b.incompatible_types[a]=e;b.valid(c)}})}):this.valid(c)},invalid:function(){this.input.trigger("invalid")},valid:function(c){"string"===typeof c&&(c={create_new:c});c.id&&this.incompatible_types[c.id]&&(c.incompatible_types=this.incompatible_types[c.id]);
this.input.trigger("valid",c)},empty:function(){this.input.trigger("empty")},_destroy:function(){this.input.unbind(".validate_topic")},validate:function(){if(""===this.input.val())this.empty();else{var c=this.input.data("data.suggest");c?this.valid(c):this.invalid()}}};d.fn.validate_enumerated=function(c){return this.each(function(){var b=d(this);if(b.is("select")){var a=b.data("$.validate_enumerated");a&&a._destroy();a=new d.validate_enumerated(this,c);b.data("$.validate_enumerated",a)}})};d.validate_enumerated=
function(c,b){this.options=d.extend(!0,{},b);this.input=d(c);this.init()};d.validate_enumerated.prototype={init:function(){var c=this;this.input.bind("change.validate_enumerated, keypress.validate_enumerated",function(){0===this.selectedIndex?c.empty():c.valid({text:d(":selected",this).text(),id:this.value})})},invalid:function(){this.input.trigger("invalid")},valid:function(c){this.input.trigger("valid",c);this.input.trigger("fb-select",c)},empty:function(){this.input.trigger("empty")},_destroy:function(){this.input.unbind(".validate_enumerated")},
validate:function(){var c=this.input[0];0<c.selectedIndex?this.valid({text:d(":selected",this.input).text(),id:c.value}):this.empty()}};d.fn.validate_boolean=function(c){var b,a;this.each(function(){var c=d(this);c.is(":radio")&&("true"===c.val().toLowerCase()?b=c:"false"===c.val().toLowerCase()&&(a=c))});if(b&&a){var f=b.data("$.validate_boolean");f&&f._destroy();f=new d.validate_boolean(b,a,c);b.data("$.validate_boolean",f)}else throw"$.fn.validate_boolean requires two radios: true and false";return this};
d.validate_boolean=function(c,b,a){this.options=d.extend(!0,{},a);this.tradio=c;this.fradio=b;this.input=this.tradio;this.init()};d.validate_boolean.prototype={init:function(){var c=this;this.tradio.bind("change.validate_boolean",function(){c.validate()})},_destroy:function(){this.input.unbind(".validate_boolean")},valid:function(c){this.input.trigger("valid",c)},empty:function(){this.input.trigger("empty")},validate:function(){this.tradio.is(":checked")?this.valid({text:this.tradio.text(),value:!0}):
this.fradio.is(":checked")?this.valid({text:this.fradio.text(),value:!1}):this.empty()}};d.fn.validate_key=function(c,b){var a,f;this.each(function(){var b=d(this);b.is(":text")&&(b.is(".key-namespace")?a=b:b.is(".key-value")&&(f=b))});if(a&&f){var e=f.data("$.validate_key");e&&e._destroy();e=new d.validate_key(a,f,c);a.data("$.validate_key",e);b&&(b.namespace&&b.value)&&(a.data("data.suggest",{id:b.namespace}),f.val(b.value))}else throw"$.fn.validate_key requires two inputs: namespace and value";
return this};d.validate_key=function(c,b,a){this.options=d.extend(!0,{},a);this.key_namespace_input=c;this.key_value_input=b;this.input=this.key_namespace_input;this.init()};d.validate_key.prototype={init:function(){var c=this,b=null;this.options.suggest_impl&&(b="/type/namespace/keys"!=this.key_value_input.attr("name")?this.options.suggest_impl.instance("/type/namespace"):d.extend({},this.options.suggest_impl.service_defaults));this.key_namespace_input.suggest(b).bind("fb-textchange.validate_key",
function(){c.validate()}).bind("fb-select.validate_key",function(a,b){c.key_namespace_input.val(b.name||b.id);c.validate()});this.key_value_input.validate_input({validator:d.validate_input.mqlkey}).bind("valid",function(a){a.stopPropagation();c.validate()}).bind("invalid",function(a){a.stopPropagation();c.validate()}).bind("empty",function(a){a.stopPropagation();c.validate()})},_destroy:function(){this.key_namespace_input.unbind(".validate_key");this.key_value_input.unbind()},invalid:function(){this.input.trigger("invalid")},
valid:function(c){this.input.trigger("valid",c)},empty:function(){this.input.trigger("empty")},validate:function(){this.is_valid_key_namespace()&&this.is_valid_key_value()?this.valid({namespace:this.key_namespace_input.data("data.suggest").id,value:this.key_value_input.val(),text:this.key_value_input.val()}):""===this.key_namespace_input.val()&&""===this.key_value_input.val()?this.empty():this.invalid()},is_valid_key_namespace:function(){return null!=this.key_namespace_input.data("data.suggest")},
is_valid_key_value:function(){try{return d.validate_input.mqlkey(this.key_value_input.val()),!0}catch(c){return!1}}}})(jQuery);
(function(d,c){var b=window.formlib={status:c,init:function(a){var d=a.event_prefix||"form.";a.form.bind(d+"submit",function(){b.submit(a)}).bind(d+"cancel",function(){b.cancel(a)}).bind(d+"error",function(d,g){a.form.removeClass("loading");b.disable_submit(a);c.error(g,!0)}).bind(d+"success",function(){a.form.removeClass("loading")}).bind(d+"valid",function(){b.enable_submit(a)}).bind(d+"invalid",function(){b.disable_submit(a)});b.init_submit_cancel(a);a.init(a)},submit:function(a){!a.form.is(".loading")&&
b.is_submit_enabled(a)&&(document.activeElement&&d(document.activeElement).blur(),a.validate(a)&&(a.form.addClass("loading"),a.submit(a,b.default_submit_ajax_options(a))))},cancel:function(){},init_inline_add_form:function(a){var d=a.event_prefix||"form.inline_add_form.";a.edit_row.bind(d+"submit",function(){b.submit_inline_add_form(a)}).bind(d+"cancel",function(){b.cancel_inline_add_form(a)}).bind(d+"error",function(d,g){a.edit_row.removeClass("loading");b.disable_submit(a);c.error(g,!0)}).bind(d+
"success",function(){a.edit_row.removeClass("loading")}).bind(d+"valid",function(){b.enable_submit(a)}).bind(d+"invalid",function(){b.disable_submit(a)});b.init_submit_cancel(a);a.trigger&&a.trigger.parents(".trigger-row:first").hide();a.body.append(a.edit_row).append(a.submit_row);a.init(a)},submit_inline_add_form:function(a){!a.edit_row.is(".loading")&&b.is_submit_enabled(a)&&(document.activeElement&&d(document.activeElement).blur(),a.validate(a)&&(a.edit_row.addClass("loading"),a.submit(a,b.default_submit_ajax_options(a))))},
success_inline_add_form:function(a,b){a.edit_row.before(b);a.reset(a);a.edit_row.trigger(a.event_prefix+"success")},cancel_inline_add_form:function(a){a.edit_row.remove();a.submit_row.remove();a.trigger&&a.trigger.parents(".trigger-row:first").show()},init_inline_edit_form:function(a){var d=a.event_prefix||"form.inline_edit_form.";a.edit_row.bind(d+"submit",function(){b.submit_inline_edit_form(a)}).bind(d+"cancel",function(){b.cancel_inline_edit_form(a)}).bind(d+"error",function(d,g){a.edit_row.removeClass("loading");
b.disable_submit(a);c.error(g,!0)}).bind(d+"success",function(){a.edit_row.removeClass("loading")}).bind(d+"valid",function(){b.enable_submit(a)}).bind(d+"invalid",function(){b.disable_submit(a)});b.init_submit_cancel(a);a.row.hide();a.row.before(a.edit_row).before(a.submit_row);a.init(a)},submit_inline_edit_form:function(a){!a.edit_row.is(".loading")&&b.is_submit_enabled(a)&&(document.activeElement&&d(document.activeElement).blur(),a.validate(a)&&(a.edit_row.addClass("loading"),a.submit(a,b.default_submit_ajax_options(a))))},
success_inline_edit_form:function(a,b){a.row.replaceWith(b);a.row=b;a.edit_row.trigger(a.event_prefix+"cancel")},cancel_inline_edit_form:function(a){a.edit_row.remove();a.submit_row.remove();a.row.show()},success_inline_delete:function(a,b,c){a.hide().addClass("old-row");a.after(b);b.append(a);c&&(a=d('<a href="#">Undo</a>'),d(".msg-default",b).next().append(a),a.click(function(){c();return!1}))},success_inline_delete_undo:function(a){var b=d(".old-row",a);a.before(b);b.show().removeClass("old-row");
a.remove()},init_modal_form:function(a){d(document.body).append(a.form.hide());var f=a.event_prefix||"form.modal_form.";a.form.bind(f+"submit",function(){b.submit_modal_form(a)}).bind(f+"cancel",function(){b.cancel_modal_form(a)}).bind(f+"error",function(d,g){a.form.removeClass("loading");b.disable_submit(a);c.error(g,!0)}).bind(f+"success",function(){a.form.removeClass("loading")}).bind(f+"valid",function(){b.enable_submit(a)}).bind(f+"invalid",function(){b.disable_submit(a)});b.init_submit_cancel(a);
a.form.data("overlay")&&a.form.removeData("overlay");a.form.overlay({close:".modal-buttons .cancel",closeOnClick:!1,load:!0,fixed:!1,mask:{color:"#000",loadSpeed:200,opacity:0.5},onLoad:function(){a.overlay=this;a.init(a)}})},submit_modal_form:function(a){!a.form.is(".loading")&&b.is_submit_enabled(a)&&(document.activeElement&&d(document.activeElement).blur(),a.validate(a)&&(a.form.addClass("loading"),a.submit(a,b.default_submit_ajax_options(a))))},cancel_modal_form:function(a){a.form.data("overlay").close();
a.form.next("#exposeMask").hide()},init_submit_cancel:function(a){var c=a.form||a.edit_row,e=a.form||a.submit_row,g=a.event_prefix,a=d(".save",e).click(function(){c.trigger(g+"submit")});b.disable(a);d(".cancel",e).click(function(){c.trigger(g+"cancel")});d(":input",c).keyup(function(a){27===a.keyCode&&c.trigger(g+"cancel")})},disable:function(a){d(a).attr("disabled","disabled").addClass("disabled")},enable:function(a){d(a).removeAttr("disabled").removeClass("disabled")},disable_submit:function(a){b.disable(d(".save",
a.form||a.submit_row))},enable_submit:function(a){b.enable(d(".save",a.form||a.submit_row))},is_submit_enabled:function(a){return!d(".save",a.form||a.submit_row).is(":disabled")},init_mqlkey:function(a,b){return a.next(".key-status").removeClass("valid invalid loading").text("").removeAttr("title").end().mqlkey(b).bind("valid",function(){d(this).next(".key-status").removeClass("invalid loading").addClass("valid").text("valid").attr("title","Key is available")}).bind("invalid",function(a,b){d(this).next(".key-status").removeClass("valid loading").addClass("invalid").text("invalid").attr("title",
b)}).bind("textchange",function(){d(this).next(".key-status").removeClass("valid invalid").text("loading").addClass("loading")})},validate_mqlkey:function(a,b){var c=b.next(".key-status"),d=b.val();return""===d?(b.trigger(a.event_prefix+"error","Key is required"),!1):d===b.data("mqlkey").original?!0:c.is(".invalid")?(b.trigger(a.event_prefix+"error",c.attr("title")),!1):c.is(".loading")?!1:!0},default_begin_ajax_options:function(){return d.extend(b._default_ajax_options("GET"),{beforeSend:function(){c.doing("Loading...")},
complete:function(){this.formlib_error||c.clear()}})},default_submit_ajax_options:function(a){var a=a||{},f=d.extend(b._default_ajax_options("POST"),a.ajax,{beforeSend:function(){this.formlib_options=a;c.doing("Saving...");d.isFunction(a.beforeSend)&&a.beforeSend.apply(this,arguments)},complete:function(){this.formlib_error||c.clear();d.isFunction(a.complete)&&a.complete.apply(this,arguments)}}),e=a.submit_row||a.form;e&&d("input[type=hidden]",e).each(function(){f.data[this.name]=this.value});return f},
_default_ajax_options:function(a){return{data:{},dataType:"json",type:a||"GET",success:function(a,c,g){if(!b.check_ajax_success(a,c,g))return this._error(g);if(d.isFunction(this.onsuccess))this.onsuccess(a,c,g)},error:function(a){return this._error(a)},_error:function(a){if(401===a.status)c.info("Authorizing..."),d(window).trigger("fb.user.unauthorized");else{console.error(a.responseText);this.formlib_error=!0;var e=b.get_error_message(a.responseText);if(d.isFunction(this.onerror))this.onerror(e,
a);else a=null,this.formlib_options&&(this.formlib_options.form?(this.formlib_options.form.trigger(this.formlib_options.event_prefix+"cancel"),a=this.formlib_options.form):a=this.formlib_options.edit_row),a?a.trigger(this.formlib_options.event_prefix+"error",e):c.error(e,!0)}}}},check_ajax_success:function(a,c,d){return b.check_api_response(a,c,d)},check_api_response:function(a,b,e){if(d.isPlainObject(a)){if(a.error&&401===a.error.code)return c.info("Authorizing..."),d(window).trigger("fb.user.unauthorized"),
!1;if("/api/status/ok"!==a.code)return!1}else if(200!==e.status)return!1;return!0},get_error_message:function(a){var b=null;try{var c=JSON.parse(a);c&&(c.error&&c.error.message?b=c.error.message:d.isArray(c.messages)&&c.messages.length&&(b=c.messages[0].message))}catch(g){}b||(b=a);return b}}})(jQuery,window.freebase.status);
(function(d){var c=window.editparams={Empty:function(b,a,c){this.structure=b;this.data=a;this.msg=c;this.toString=function(){return"Empty: "+this.msg}},Invalid:function(b,a,c){this.structure=b;this.data=a;this.msg=c;this.toString=function(){return"Invalid: "+this.msg}},parse:function(b,a){function f(a,b,d,g,e){try{c.validate(b,d),e.push(d)}catch(f){if(f instanceof c.Empty)e.push(d);else throw f;}}var e=(b.values||[]).slice(),g=b.properties||[],j=b.expected_type.mediator;if(j){if(!g.length)throw new c.Invalid(b,
null,"mediator musth have 1 or more properties");if(e.length&&1!==e.length)throw new c.Invalid(b,null,"Can't edit more than one value (row) for a mediator");}var k=[];d(".data-input",a).each(function(){var a=d(this),i=a.data("$.data_input");if(!i)throw new c.Invalid(b,null,"$.data-input not initialized for",this);i.validate(!0);if(a.is(".error"))throw new c.Invalid(b,null,"$.data-input is invalid",this);i=a.data("data");if(!i)throw new c.Invalid(b,null,"$.data-input has no data",this);if(j){k.length||
(k.push({property:{}}),d.each(g,function(a,b){k[0].property[b.id]=d.extend({},b,{values:[]})}));var l=k[0].property[i.name];if(l){var m=[];e.length&&(m=(m=e[0].property[l.id])&&m.values||[]);f(a,l,i,m,l.values)}else console.warn("editparams","unknown mediator property data",i)}else f(a,b,i,e,k)});return j?c.parse_mediator(b,e,k):c.parse_simple(b,e,k)},parse_mediator:function(b,a,f){if(1!==f.length)throw new c.Invalid(b,f,"Must specify one (new or updated) value for a mediator");var f=f[0],e;a.length&&
(e=a[0]);a={};if(e)a.id=e.id;else{a.id=null;a.create="unconditional";a.connect=b.unique?"replace":"insert";var g=[];"/type/object"!==b.expected_type.id&&g.push({id:b.expected_type.id,connect:"insert"});var j=b.expected_type.included_types;j&&d.each(j,function(a,b){"/type/object"!==b&&g.push({id:b,connect:"insert"})});g.length&&(a.type=g)}for(var j=!1,b=b.properties,k=0,h=b.length;k<h;k++){var i=b[k],l=e&&e.property&&e.property[i.id],m=f.property&&f.property[i.id],l=c.parse_simple(i,l&&l.values||[],
m&&m.values||[]);l.length&&(a[i.id]=l,j=!0)}return j?[a]:[]},parse_simple:function(b,a,d){return c.diff(b,a,d)},diff:function(b,a,d){var e=b.expected_type,g=b.expected_type.id,j=b.unique,k="/type/text"===g,h="/type/key"===g;if(j&&!k){if(a.length&&1!==a.length)throw new c.Invalid(b,a,"Can't edit more than one value (row) for a unique property.");if(d.length&&1!==d.length)throw new c.Invalid(b,d,"Can't edit more than one value (row) for a unique property.");}var i=[];c.LITERAL_TYPE_IDS[g]?(i.push("value"),
k?i.push("lang"):h&&i.push("namespace")):i.push("id");var g=[],l=[],m,o;m=0;for(o=a.length;m<o;m++){var n=a[m];c.validate(b,n);-1===c.inArray.apply(null,[n,d].concat(i))&&g.push(c.clause(n,"delete"))}m=0;for(o=d.length;m<o;m++){n=d[m];try{c.validate(b,n)}catch(p){continue}if(-1===c.inArray.apply(null,[n,a].concat(i))){if(j)if(k){var r=c.inArray(n,g,"lang");-1!==r&&g.splice(r,1)}else if(!h)return[c.clause(n,"replace",e)];l.push(c.clause(n,j?"replace":"insert",e))}}return g.concat(l)},validate:function(b,
a){var f=b.expected_type.id;if(c.LITERAL_TYPE_IDS[f]){if(c.isEmpty(a.value))throw new c.Empty(b,a);if("/type/text"===f&&c.isEmpty(a.lang))throw new c.Invalid(b,a,"Expected data.lang for /type/text");if("/type/key"===f&&c.isEmpty(a.namespace))throw new c.Invalid(b,a,"Expected data.namespace for /type/key");if("/type/int"===f||"/type/float"===f){if("number"!==d.type(a.value))throw new c.Invalid(b,a,"Expected number data.value for "+f);}else if("/type/boolean"===f){if("boolean"!==d.type(a.value))throw new c.Invalid(b,
a,"Expected boolean data.value for /type/boolean");}else if("string"!==d.type(a.value))throw new c.Invalid(b,a,"Expected string data.value for "+f);}else if(c.isEmpty(a.create_new)){if(c.isEmpty(a.id))throw new c.Empty(b,a);}else if(c.isEmpty(a.lang))throw new c.Invalid(b,a,"Expected lang for creating a new topic");return a},type_clause:function(b,a){var a=a||{},c=[];if(b){if(b.enumeration||b.never_assert)return c;"/type/object"!==b.id&&c.push({id:b.id,connect:"insert"});var e=b.included_types;e&&
d.each(e,function(b,d){"/type/object"===d||a[d]||c.push({id:d,connect:"insert"})})}return c},clause:function(b,a,d){var e={connect:a};b.id?(e.id=b.id,"delete"!==a&&(d&&!d.enumeration)&&(b=c.type_clause(d,b.incompatible_types),b.length&&(e.type=b))):b.create_new&&b.lang?(e.name={value:b.create_new,lang:b.lang},e.id=null,e.create="unconditional",b=c.type_clause(d),b.length&&(e.type=b)):(e.value=b.value,b.lang?e.lang=b.lang:b.namespace&&(e.namespace=b.namespace));return e},inArray:function(b,a){var c=
Array.prototype.slice.call(arguments,2);if(!c.length)return d.inArray(b,a);for(var e=0,g=a.length;e<g;e++){for(var j=a[e],k=!0,h=0,i=c.length;h<i;h++){var l=c[h];if(j[l]!=b[l]){k=!1;break}}if(k)return e}return-1},isEmpty:function(b){return null==b||""===b},LITERAL_TYPE_IDS:{"/type/int":1,"/type/float":1,"/type/boolean":1,"/type/rawstring":1,"/type/uri":1,"/type/text":1,"/type/datetime":1,"/type/id":1,"/type/key":1,"/type/value":1,"/type/enumeration":1}}})(jQuery);
(function(d,c,b,a,f){var e=c.edit={prop_add_begin:function(a){d.ajax(d.extend(b.default_begin_ajax_options(),{url:c.options.base_ajax_url+"/prop_add_begin.ajax",data:{s:c.options.id,p:a.attr("data-id"),lang:c.options.lang},onsuccess:function(b){var b=d(b.result.html),c=b.metadata(),f=c.expected_type.id;return"/common/document"===f?e.prop_add_document(a,b,c):"/common/image"===f?e.prop_add_image(a,b,c):e.prop_add(a,b,c)}}))},prop_add:function(a,f,k){var a=d(">.data-section",a),a=d("> .data-table > tbody, > .data-list",
a),h=d(".edit-row",f),f=d(".edit-row-submit",f),i={event_prefix:"propbox.edit.prop_add.",init:e.init_prop_add_form,validate:e.validate_prop_add_form,submit:e.submit_prop_add_form,reset:e.reset_prop_add_form,ajax:{url:c.options.base_ajax_url+"/prop_edit_submit.ajax"},body:a,edit_row:h,submit_row:f,structure:k};h.bind("propbox.edit.prop_add.success",function(){k.unique&&h.trigger(i.event_prefix+"cancel")});b.init_inline_add_form(i)},init_prop_add_form:function(a){e.init_data_inputs(a);d(":input:visible:first",
a.edit_row).focus()},validate_prop_add_form:function(){return!0},reset_prop_add_form:function(a){e.reset_data_inputs(a);b.disable_submit(a);d(".cancel",a.submit_row).text("Done");d(":input:visible:first",a.edit_row).focus()},submit_prop_add_form:function(g,e){try{var f=a.parse(g.structure,g.edit_row);e.data.o=JSON.stringify(f)}catch(h){f=d(".data-input.error",g.edit_row);f.length?(g.edit_row.trigger(g.event_prefix+"error","Please specify a valid value"),f.eq(0).find(":input").focus().select()):g.edit_row.trigger(g.event_prefix+
"error",h.toString());return}f.length?d.ajax(d.extend(e,{onsuccess:function(a){a=d(a.result.html);b.success_inline_add_form(g,a);c.init_menus(a,!0);d(".nicemenu-item.edit").show();c.kbs.set_next(null,a,!0)}})):g.edit_row.trigger(g.event_prefix+"error","Please specify a valid value")},value_edit_begin:function(a,j){var k=null,h=null;j.is("tr")?k=j.attr("data-id"):(h=d(".property-value:first",j),k=h.attr("data-value")||h.attr("data-id")||h.attr("datetime"),h=h.attr("data-namespace"));d.ajax(d.extend(b.default_begin_ajax_options(),
{url:c.options.base_ajax_url+"/value_edit_begin.ajax",data:{s:c.options.id,p:a.attr("data-id"),replace:k,namespace:h,lang:c.options.lang},onsuccess:function(b){if(b.result.invalid){f.clear();setTimeout(function(){f.sprintf("warning","The value you are trying edit is no longer valid. Please %s to continue editing.","reload",function(){window.location.reload(true);return false})})}else{var b=d(b.result.html),c=b.metadata(),k=c.expected_type.id;return k==="/common/document"?e.value_edit_document(a,j,
b,c):k==="/common/image"?e.value_edit_image(a,j,b,c):e.value_edit(a,j,b,c)}}}))},value_edit:function(a,f,k,h){var i=d(".edit-row",k),k=d(".edit-row-submit",k),h={event_prefix:"propbox.edit.value_edit.",init:e.init_value_edit_form,validate:e.validate_value_edit_form,submit:e.submit_value_edit_form,ajax:{url:c.options.base_ajax_url+"/prop_edit_submit.ajax"},row:f,edit_row:i,submit_row:k,structure:h};i.bind("propbox.edit.value_edit.delete",function(){i.trigger("propbox.edit.value_edit.cancel");c.edit.value_delete_begin(a,
f)});b.init_inline_edit_form(h)},init_value_edit_form:function(a){e.init_data_inputs(a);d(".delete",a.submit_row).click(function(){a.edit_row.trigger(a.event_prefix+"delete")});d(":input:visible:first",a.edit_row).focus()},validate_value_edit_form:function(){return!0},submit_value_edit_form:function(g,e){try{var f=a.parse(g.structure,g.edit_row);e.data.o=JSON.stringify(f)}catch(h){f=d(".data-input.error",g.edit_row);f.length?(g.edit_row.trigger(g.event_prefix+"error","Please specify a valid value"),
f.eq(0).find(":input").focus().select()):g.edit_row.trigger(g.event_prefix+"error",h.toString());return}d.ajax(d.extend(e,{onsuccess:function(a){a=d(a.result.html);b.success_inline_edit_form(g,a);c.init_menus(a,!0);d(".nicemenu-item.edit").show();c.kbs.set_next(null,a,!0)}}))},value_delete_begin:function(a,e){var f=null,h=null;e.is("tr")?f=e.attr("data-id"):(h=d(".property-value:first",e),f=h.attr("data-value")||h.attr("data-id")||h.attr("datetime"),h=h.attr("data-namespace"));var i={s:c.options.id,
p:a.attr("data-id"),o:f,lang:c.options.lang,namespace:h};d.ajax(d.extend(b.default_submit_ajax_options(),{url:c.options.base_ajax_url+"/value_delete_submit.ajax",data:i,onsuccess:function(a){var g=d(a.result.html);b.success_inline_delete(e,g,function(){d.ajax(d.extend(b.default_submit_ajax_options(),{url:c.options.base_ajax_url+"/value_delete_undo.ajax",data:i,onsuccess:function(){b.success_inline_delete_undo(g)}}))})}}))},prop_add_document:function(a,d,f){b.init_modal_form({event_prefix:"propbox.edit.prop_add_document.",
init:e.init_prop_add_document_form,validate:e.validate_prop_add_document_form,submit:e.submit_prop_add_document_form,ajax:{url:c.options.base_ajax_url+"/prop_add_document_submit.ajax"},prop_section:a,form:d,structure:f})},init_prop_add_document_form:function(a){var b=d("select[name=lang]",a.form);b.change(function(){var e=d(".lang-notice",a.form);this.value===c.options.lang?e.hide():(d("strong",e).text(d("option:selected",b).text()),e.show())});d("textarea",a.form).bind("keypress",function(){a.form.trigger(a.event_prefix+
"valid")}).bind("paste",function(){a.form.trigger(a.event_prefix+"valid")}).focus()},validate_prop_add_document_form:function(a){var b=d("textarea",a.form);return""===d.trim(b.val())?(a.form.trigger(a.event_prefix+"invalid"),b.focus(),!1):!0},submit_prop_add_document_form:function(a,b){var e=d("textarea",a.form);b.data[e.attr("name")]=d.trim(e.val());b.data.lang=d("select[name=lang]",a.form).val();d.ajax(d.extend(b,{onsuccess:function(b){b=d(b.result.html);if(a.prop_row)a.prop_row.replaceWith(b);
else{var e=d(">.data-section",a.prop_section);d("> .data-table > tbody, > .data-list",e).append(b)}c.init_menus(b,!0);d(".nicemenu-item.edit").show();c.kbs.set_next(null,b,!0);a.form.trigger(a.event_prefix+"cancel")}}))},value_edit_document:function(a,d,f,h){d={event_prefix:"propbox.edit.value_edit_document.",init:e.init_value_edit_document_form,validate:e.validate_value_edit_document_form,submit:e.submit_value_edit_document_form,ajax:{url:c.options.base_ajax_url+"/prop_add_document_submit.ajax"},
prop_section:a,prop_row:d,form:f,structure:h,cant_edit:f.is(".cant-edit-document-form")};d.cant_edit&&f.bind("propbox.edit.value_edit_document.submit",function(){f.trigger("propbox.edit.value_edit_document.cancel");e.prop_add_begin(a)});b.init_modal_form(d)},init_value_edit_document_form:function(a){a.cant_edit?b.enable_submit(a):e.init_prop_add_document_form(a)},validate_value_edit_document_form:function(a){return a.cant_edit?!0:e.validate_prop_add_document_form(a)},submit_value_edit_document_form:function(a,
b){a.cant_edit||e.submit_prop_add_document_form(a,b)},prop_add_image:function(){alert("Add image not yet implemented")},value_edit_image:function(){alert("Edit image not yet implemented")},init_data_inputs:function(a){d(".data-input",a.edit_row||a.form).each(function(){e.init_data_input(d(this),a)})},init_data_input:function(a,b){var f=b.edit_row||b.form;a.data_input({lang:c.options.lang,suggest_impl:c.options.suggest_impl,incompatible_types:c.options.incompatible_types}).bind("valid",function(){f.trigger(b.event_prefix+
"valid");var c=a.parent(".form-field"),i=c.next(".magicbox-template");i.length&&(i=d("<div>").html(i.html()),i=d(".form-field",i),c.after(i),e.init_data_input(d(".data-input",i),b))}).bind("empty",function(){f.trigger(b.event_prefix+"valid")}).bind("invalid",function(){f.trigger(b.event_prefix+"invalid")}).bind("submit",function(){f.trigger(b.event_prefix+"submit")}).bind("cancel",function(){f.trigger(b.event_prefix+"cancel")}).bind("loading",function(){d(this).addClass("loading")}).bind("loading_complete",
function(){d(this).removeClass("loading")})},reset_data_inputs:function(a){d(".data-input",a.edit_row).each(function(){d(this).data("$.data_input").reset()})}}})(jQuery,window.propbox,window.formlib,window.editparams,window.freebase.status);
(function(d,c,b,a,f){function e(b){a.edit.init_data_inputs(b);if(!b.structure.expected_type.mediator){var c=d(".fb-input:first",b.form);"/type/object/name"===c.attr("name")?b.name_input=c.parent(".data-input"):console.error("Expected /type/object/name as the first input")}d(":input:visible:first",b.form).focus()}function g(a){return a.name_input&&!a.name_input.data("data").value?(a.form.trigger(a.event_prefix+"error","Name is required"),!1):!0}function j(a,b){try{a.structure.expected_type.mediator=
!0;var e=f.parse(a.structure,a.form);b.data.o=JSON.stringify(e)}catch(g){e=d(".data-input.error",a.form);e.length?(a.form.trigger(a.event_prefix+"error","Please specify a valid value"),e.eq(0).find(":input").focus().select()):a.form.trigger(a.event_prefix+"error",g.toString());return}d.ajax(d.extend(b,{onsuccess:function(a){a=d(a.result.html);a=d(".property-value:first",a).attr("data-id");window.location.href=c.h.fb_url(a)}}))}d(function(){var f=d(".edit-form"),h=f.metadata(),i=d(".edit-row-submit",
f),l=d("input[name=s]",i).val(),i=c.h.lang_id(d("input[name=lang]",i).val());a.init(f,{id:l,base_ajax_url:c.h.ajax_url("lib/propbox"),base_static_url:c.h.static_url("lib/propbox"),lang:i,suggest_impl:c.suggest_options,incompatible_types:c.incompatible_types});f={event_prefix:"create.type.instance.",init:e,validate:g,submit:j,ajax:{url:c.h.ajax_url("lib/propbox/prop_edit_submit.ajax")},form:f,structure:h};b.init(f)})})(jQuery,window.freebase,window.formlib,window.propbox,window.editparams);
