
/*
 * Copyright 2012, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Additional Licenses for Third Party components can be found here:
 * http://wiki.freebase.com/wiki/Freebase_Site_License
 *
 */
(function(f){var l="undefined"!=typeof window.innerWidth?function(){return{w:window.innerWidth,h:window.innerHeight}}:"undefined"!=typeof document.documentElement&&"undefined"!=typeof document.documentElement.clientWidth&&0!=document.documentElement.clientWidth?function(){return{w:document.documentElement.clientWidth,h:document.documentElement.clientHeight}}:function(){return{w:document.getElementsByTagName("body")[0].clientWidth,h:document.getElementsByTagName("body")[0].clientHeight}};window.kbs=
function(c){f(".kbs.current",c).removeClass("current");var b=f(".domain-section:first",c),d=f(".domain-section:last",c),h=this.scroll_to=function(a){var e=f(document).scrollTop();f(document).height();var b=l().h,b=e+b,c=a.offset().top,a=c+a.height();c<e?f(document).scrollTop(c):a>b&&f(document).scrollTop(e+(a-b))},g=this.get_current=function(){return f(".kbs.current:first",c)},i=this.set_next=function(a,e,b){a=a||g();e.length&&(a.removeClass("current"),e.addClass("current"),b||h(e))},q=this.next_domain=
function(a){var e=g(),b=m(e);b&&(b=b.find(".kbs:first"),i(e,b,a))},m=this._next_domain=function(a){if(!a||!a.length)return f(".domain-section:first",c);a=a.closest(".domain-section");return!a.length||a[0]===d[0]?b:a.next(".domain-section")},r=this.prev_domain=function(){var a=g(),e=n(a);e&&(e=e.find(".kbs:first"),i(a,e))},n=this._prev_domain=function(a){if(!a||!a.length)return f(".domain-section:last",c);var e=a.closest(".domain-section");return a.closest(".property-section").length||a.closest(".type-section").length?
e:!e.length||e[0]===b[0]?d:e.prev(".domain-section")},s=this.next_type=function(){var a=g(),e=o(a);e&&(e=e.find(".kbs:first"),i(a,e))},o=this._next_type=function(a){if(!a||!a.length)return f(".type-section:first",c);var e=a.closest(".domain-section"),a=a.closest(".type-section"),a=a.length?a.next(".type-section"):e.find(".type-section:first");if(!a||!a.length){var b=m(e);if(b)for(;b.get(0)!==e.get(0);){a=b.find(".type-section:first");if(a.length)break;b=m(b)}}return a},j=this.prev_type=function(){var a=
g(),e=k(a);e&&(e=e.find(".kbs:first"),i(a,e))},k=this._prev_type=function(a){if(!a||!a.length)return f(".type-section:last",c);var e=a.closest(".domain-section"),b=a.closest(".type-section");if(a.closest(".property-section").length)return b;var d;b.length&&(d=b.prev(".type-section"));if(!d||!d.length)if(a=n(e))for(;a.get(0)!==e.get(0);){d=a.find(".type-section:last");if(d.length)break;a=n(a)}return d},u=this.next_prop=function(){var a=g(),e=t(a);e&&(e=e.find(".kbs:first"),i(a,e))},t=this._next_prop=
function(a){if(!a||!a.length)return f(".property-section:first",c);var e=a.closest(".domain-section"),b=a.closest(".type-section"),d=a.closest(".property-section"),e=d.length?d.next(".property-section"):b.length?b.find(".property-section:first"):e.find(".property-section:first");if(!e||!e.length)if(a=o(a))for(;a.get(0)!==b.get(0);){e=a.find(".property-section:first");if(e.length)break;null==b.get(0)&&(b=a);a=o(a)}return e},w=this.prev_prop=function(){var a=g(),b=v(a);b&&(b=b.find(".kbs:first"),i(a,
b))},v=this._prev_prop=function(a){if(!a||!a.length)return f(".property-section:last",c);var b=a.closest(".domain-section"),d=a.closest(".type-section"),h=a.closest(".property-section");if(a.closest(".data-section").length)return h;var g;h.length&&(g=h.prev(".property-section"));if(!g||!g.length)if(j=d.length?k(d):k(b))for(;j.get(0)!==d.get(0);){g=j.find(".property-section:last");if(g.length)break;null==d.get(0)&&(d=j);j=k(j)}return g};this.next=function(){var a=g();if(a&&a.length){var b=this._next(a);
if(b){i(a,b);return}}a=f(".kbs:visible:first",c);i(a,a)};this._next=function(a){if(!a||!a.length)return f(".domain-section:first .kbs:first",c);var e=a.closest(".domain-section"),g=a.closest(".type-section"),h=a.closest(".property-section");if(a.closest(".data-section").length){a=a.next(".kbs");if(a.length)return a;a=h.next(".property-section").find(".kbs:first");if(a.length)return a;a=g.next(".type-section").find(".kbs:first")}else if(h.length){a=h.find(".data-section:first .kbs:first");if(a.length)return a;
a=h.next(".property-section").find(".kbs:first");if(a.length)return a;a=g.next(".type-section").find(".kbs:first")}else if(g.length){a=g.find(".property-section:first .kbs:first");if(a.length)return a;a=g.next(".type-section").find(".kbs:first")}else a=e.find(".type-section:first .kbs:first");return a.length?a:e.get(0)===d.get(0)?b.find(".kbs:first"):e.next(".domain-section").find(".kbs:first")};this.prev=function(){var a=g(),b=this._prev(a);b&&i(a,b)};this._prev=function(a){if(!a||!a.length)return a=
f(".data-section:last .kbs:last",c),a.length||(a=f(".property-section:last .kbs:first",c)),a.length||(a=f(".type-section:last .kbs:first",c)),a.length||(a=f(".domain-section:last .kbs:first",c)),a;var e=a.closest(".domain-section"),g=a.closest(".type-section"),h=a.closest(".property-section");return a.closest(".data-section").length?(a=a.prev(".kbs"),a.length?a:h.find(".kbs:first")):h.length?(a=h.prev(".property-section").find(".kbs:last"),a.length?a:g.find(".kbs:first")):g.length?(a=g.prev(".type-section").find(".kbs:last"),
a.length?a:e.find(".kbs:first")):e.get(0)===b.get(0)?d.find(".kbs:last"):e.prev(".domain-section").find(".kbs:last")};this.edit=function(){this.get_current().trigger("edit")};var p=this;f(document).unbind(".kbs").bind("keydown.kbs",function(a){var b=a.target;if(b==document.body||b==document||b==window||b==f("html")[0])b=a.keyCode,68===b?a.shiftKey?r():q():84===b?a.shiftKey?j():s():80===b?a.shiftKey?w():u():74===b?p.next():75===b?p.prev():69===b&&p.edit()})}})(jQuery);
(function(f,l){var c=window.propbox={init:function(b,d){d=f.extend({lang:"/lang/en"},d);if(!d.base_ajax_url)throw Error("base_ajax_url required in propbox options");if(!d.base_static_url)throw Error("base_static_url required in propbox options");if(!d.id)throw Error("topic id required in propbox options");if(!d.lang)throw Error("lang required in propbox options");c.options=d;c.kbs=new l(b);f(".kbs",b).live("click",function(){var b=c.kbs.get_current();c.kbs.set_next(b,f(this),!0)}).live("edit",function(){var b=
f(this).find(".headmenu:first").data("submenu");b&&f("li:first a:first",b).click()});c.init_menus(b);f.tablesorter&&f(".data-table").addClass("table-sortable").tablesorter()},init_menus:function(b,d){b=f(b||document);d&&f(".nicemenu",b).nicemenu();var h;h=b&&b.is(".hover-row")?b:f(".hover-row",b);h.hover(c.row_menu_hoverover,c.row_menu_hoverout);h.dblclick(function(){var b=f(".nicemenu .default-action",this);b.length||(b=f(".nicemenu:first .submenu:first a:first",this));var c=b.attr("href");c&&("#"==
c||0==c.indexOf("javascript:void(0)"))&&f(b).click()});f(".nicemenu .headmenu",b).add(f(".nicemenu .default-action",b)).click("click",function(){if(c.kbs){var b=c.kbs.get_current();b&&c.kbs.set_next(b,f(this).parents(".kbs:first"),!0)}return!1})},row_menu_hoverover:function(){f(this).addClass("row-hover")},row_menu_hoverout:function(){f(this).removeClass("row-hover")},get_script:function(b,d){var h=c.get_script.cache;h||(h=c.get_script.cache={});var g=h[b];g?1===g.state?g.callbacks.push(d):4===g.state&&
d():(g=h[b]={state:0,callbacks:[d]},f.ajax({url:c.options.base_static_url+b,dataType:"script",cache:!0,beforeSend:function(){g.state=1},success:function(){g.state=4;f.each(g.callbacks,function(b,c){c()})},error:function(){g.state=-1}}))},prop_edit:function(b,d){var h=f(b).parents(".property-section");h.length||(h=f(b).parents(".submenu").data("headmenu").parents(".property-section"));h=h.find(".data-section .data-row:first:visible .nicemenu:first .headmenu");h.length?h.data("submenu").find("a:first").click():
c.prop_add(b,d);return!1},prop_add:function(b,d){var h=f(b).parents(".property-section");h.length||(h=f(b).parents(".submenu").data("headmenu").parents(".property-section"));c.get_script("/propbox-edit.mf.js",function(){c.edit.prop_add_begin(h,d)});return!1},value_edit:function(b){var d=f(b).parents(".submenu").data("headmenu").parents(".data-row:first"),h=d.parents(".property-section");c.get_script("/propbox-edit.mf.js",function(){c.edit.value_edit_begin(h,d)});return!1},value_delete:function(b){var d=
f(b).parents(".submenu").data("headmenu").parents(".data-row:first"),h=d.parents(".property-section");c.get_script("/propbox-edit.mf.js",function(){c.edit.value_delete_begin(h,d)});return!1},remove_type:function(b){var b=f(b),d=b.parents(".type-section");c.get_script("/propbox-edit.mf.js",function(){c.edit.remove_type_begin(b,d)});return!1},add_type:function(b,d,h){var b=f(b),g=b.parents(".type-section"),i=c.options.incompatible_types;i?i.search(c.options.id,d,h,{compatible:function(){c.add_type_submit(b,
g)},incompatible:i.overlay_incompatible_callback({onConfirm:function(){c.add_type_submit(b,g)}})}):c.add_type_submit(b,g);return!1},add_type_submit:function(b,d){c.get_script("/propbox-edit.mf.js",function(){c.edit.add_type_submit(b,d)})},add_has_no_value:function(b){var d=f(b).parents(".submenu").data("headmenu").parents(".property-section");c.get_script("/propbox-edit.mf.js",function(){c.edit.add_has_no_value(d)});return!1},add_has_value:function(b){var d=f(b).parents(".submenu").data("headmenu").parents(".property-section");
c.get_script("/propbox-edit.mf.js",function(){c.edit.add_has_value(d)});return!1},remove_has_no_value:function(b){var d=f(b).parents(".property-section");c.get_script("/propbox-edit.mf.js",function(){c.edit.remove_has_no_value(d)});return!1},remove_has_value:function(b){var d=f(b).parents(".property-section");c.get_script("/propbox-edit.mf.js",function(){c.edit.remove_has_value(d)});return!1},more:function(b,d,h){var g=f(b).parents(".property-section");c.get_script("/propbox-edit.mf.js",function(){c.edit.more(g,
d,h,function(){f.tablesorter&&g.find("table").addClass("table-sortable").tablesorter()})})}}})(jQuery,window.kbs);
