
/*
 * Copyright 2012, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Additional Licenses for Third Party components can be found here:
 * http://wiki.freebase.com/wiki/Freebase_Site_License
 *
 */
(function(d){d.extend({tablesorter:new function(){function a(a,d){b(a+","+((new Date).getTime()-d.getTime())+"ms")}function b(a){"undefined"!=typeof console&&"undefined"!=typeof console.debug?console.log(a):alert(a)}function e(a,A){var v="";if(0!=a.tBodies.length){var h=a.tBodies[0].rows;if(h[0])for(var c=[],i=h[0].cells.length,k=0;k<i;k++){var j=!1;d.metadata&&d(A[k]).metadata()&&d(A[k]).metadata().sorter?j=f(d(A[k]).metadata().sorter):a.config.headers[k]&&a.config.headers[k].sorter&&(j=f(a.config.headers[k].sorter));
if(!j)a:{for(var j=a,e=h,g=-1,o=k,w=l.length,s=!1,q=!1,u=!0;""==q&&u;)g++,e[g]?(s=e[g].cells[o],q=d.trim(n(j.config,s)),j.config.debug&&b("Checking if value was empty on row:"+g)):u=!1;for(e=1;e<w;e++)if(l[e].is(q,j,s)){j=l[e];break a}j=l[0]}a.config.debug&&(v+="column:"+k+" parser:"+j.id+"\n");c.push(j)}a.config.debug&&b(v);return c}}function f(a){for(var d=l.length,b=0;b<d;b++)if(l[b].id.toLowerCase()==a.toLowerCase())return l[b];return!1}function g(p){var b;p.config.debug&&(b=new Date);for(var e=
p.tBodies[0]&&p.tBodies[0].rows.length||0,h=p.tBodies[0].rows[0]&&p.tBodies[0].rows[0].cells.length||0,c=p.config.parsers,i={row:[],normalized:[]},k=0;k<e;++k){var j=d(p.tBodies[0].rows[k]),f=[];if(j.hasClass(p.config.cssChildRow))i.row[i.row.length-1]=i.row[i.row.length-1].add(j);else{i.row.push(j);for(var g=0;g<h;++g)f.push(c[g].format(n(p.config,j[0].cells[g]),p,j[0].cells[g]));f.push(i.normalized.length);i.normalized.push(f)}}p.config.debug&&a("Building cache for "+e+" rows:",b);return i}function n(a,
b){var e="";if(!b)return"";a.supportsTextContent||(a.supportsTextContent=b.textContent||!1);return e="simple"==a.textExtraction?a.supportsTextContent?b.textContent:b.childNodes[0]&&b.childNodes[0].hasChildNodes()?b.childNodes[0].innerHTML:b.innerHTML:"function"==typeof a.textExtraction?a.textExtraction(b):d(b).text()}function w(b,e){var v;b.config.debug&&(v=new Date);for(var h=e.row,c=e.normalized,i=c.length,k=c[0].length-1,j=d(b.tBodies[0]),g=[],f=0;f<i;f++){var m=c[f][k];g.push(h[m]);if(!b.config.appender)for(var n=
h[m].length,l=0;l<n;l++)j[0].appendChild(h[m][l])}b.config.appender&&b.config.appender(b,g);g=null;b.config.debug&&a("Rebuilt table:",v);B(b);setTimeout(function(){d(b).trigger("sortEnd")},0)}function u(a,d){return a.config.headers[d]&&a.config.headers[d].lockedOrder?a.config.headers[d].lockedOrder:!1}function B(a){for(var d=a.config.widgets,b=d.length,e=0;e<b;e++)x(d[e]).format(a)}function x(a){for(var d=t.length,b=0;b<d;b++)if(t[b].id.toLowerCase()==a.toLowerCase())return t[b]}function C(a,b,e,
h){b.removeClass(h[0]).removeClass(h[1]);var c=[];b.each(function(){this.sortDisabled||(c[this.column]=d(this))});a=e.length;for(b=0;b<a;b++)c[e[b][0]].addClass(h[e[b][1]])}function y(d,b,e){var h,c;d.config.debug&&(h=new Date);var i="var sortWrapper = function(a,b) {",k=b.length;for(c=0;c<k;c++)var j=b[c][0],g=b[c][1],j="text"==d.config.parsers[j].type?0==g?o("text","asc",j):o("text","desc",j):0==g?o("numeric","asc",j):o("numeric","desc",j),f="e"+c,i=i+("var "+f+" = "+j),i=i+("if("+f+") { return "+
f+"; } "),i=i+"else { ";c=e.normalized[0].length-1;i+="return a["+c+"]-b["+c+"];";for(c=0;c<k;c++)i+="}; ";i+="return 0; }; ";d.config.debug&&a("Evaling expression:"+i,new Date);eval(i);e.normalized.sort(sortWrapper);d.config.debug&&a("Sorting on "+b.toString()+" and dir "+g+" time:",h);return e}function o(a,d,b){var e="a["+b+"]",b="b["+b+"]";if("text"==a&&"asc"==d)return"("+e+" == "+b+" ? 0 : ("+e+" === null ? Number.POSITIVE_INFINITY : ("+b+" === null ? Number.NEGATIVE_INFINITY : ("+e+" < "+b+") ? -1 : 1 )));";
if("text"==a&&"desc"==d)return"("+e+" == "+b+" ? 0 : ("+e+" === null ? Number.POSITIVE_INFINITY : ("+b+" === null ? Number.NEGATIVE_INFINITY : ("+b+" < "+e+") ? -1 : 1 )));";if("numeric"==a&&"asc"==d)return"("+e+" === null && "+b+" === null) ? 0 :("+e+" === null ? Number.POSITIVE_INFINITY : ("+b+" === null ? Number.NEGATIVE_INFINITY : "+e+" - "+b+"));";if("numeric"==a&&"desc"==d)return"("+e+" === null && "+b+" === null) ? 0 :("+e+" === null ? Number.POSITIVE_INFINITY : ("+b+" === null ? Number.NEGATIVE_INFINITY : "+
b+" - "+e+"));"}var l=[],t=[];this.defaults={cssHeader:"header",cssAsc:"headerSortUp",cssDesc:"headerSortDown",cssChildRow:"expand-child",sortInitialOrder:"asc",sortMultiSortKey:"shiftKey",sortForce:null,sortAppend:null,sortLocaleCompare:!0,textExtraction:"simple",parsers:{},widgets:[],widgetZebra:{css:["even","odd"]},headers:{},widthFixed:!1,cancelSelection:!0,sortList:[],headerList:[],dateFormat:"us",decimal:"/.|,/g",onRenderHeader:null,selectorHeaders:"thead th",debug:!1};this.benchmark=a;this.construct=
function(f){return this.each(function(){if(this.tHead&&this.tBodies){var m,l,h;this.config={};h=d.extend(this.config,d.tablesorter.defaults,f);m=d(this);d.data(this,"tablesorter",h);var c=this,i;c.config.debug&&(i=new Date);for(var k=[],j={},o=c.getElementsByTagName("THEAD")[0].getElementsByTagName("TR"),t=0;t<o.length;t++)for(var H=o[t].cells,E=0;E<H.length;E++){var s=H[E],q=s.parentNode.rowIndex,F=q+"-"+s.cellIndex,K=s.rowSpan||1,s=s.colSpan||1,D;"undefined"==typeof k[q]&&(k[q]=[]);var r;for(r=
0;r<k[q].length+1;r++)if("undefined"==typeof k[q][r]){D=r;break}j[F]=D;for(r=q;r<q+K;r++){"undefined"==typeof k[r]&&(k[r]=[]);for(var F=k[r],G=D;G<D+s;G++)F[G]="x"}}var z=d(c.config.selectorHeaders,c).each(function(a){this.column=j[this.parentNode.rowIndex+"-"+this.cellIndex];this.count=this.order="Number"!=typeof c.config.sortInitialOrder?"desc"==c.config.sortInitialOrder.toLowerCase()?1:0:1==c.config.sortInitialOrder?1:0;if(d.metadata&&!1===d(this).metadata().sorter||c.config.headers[a]&&!1===c.config.headers[a].sorter)this.sortDisabled=
!0;u(c,a)&&(this.order=this.lockedOrder=u(c,a));if(!this.sortDisabled){var b=d(this).addClass(c.config.cssHeader);c.config.onRenderHeader&&c.config.onRenderHeader.apply(b)}c.config.headerList[a]=this});c.config.debug&&(a("Built headers:",i),b(z));this.config.parsers=e(this,z);l=g(this);var I=[h.cssDesc,h.cssAsc];if(this.config.widthFixed){var J=d("<colgroup>");d("tr:first td",this.tBodies[0]).each(function(){J.append(d("<col>").css("width",d(this).width()))});d(this).prepend(J)}z.click(function(c){var a=
m[0].tBodies[0]&&m[0].tBodies[0].rows.length||0;if(!this.sortDisabled&&a>0){m.trigger("sortStart");d(this);a=this.column;this.order=this.count++%2;if(this.lockedOrder)this.order=this.lockedOrder;if(c[h.sortMultiSortKey]){a:{for(var c=h.sortList,b=c.length,i=0;i<b;i++)if(c[i][0]==a){c=true;break a}c=false}if(c)for(c=0;c<h.sortList.length;c++){b=h.sortList[c];i=h.headerList[b[0]];if(b[0]==a){i.count=b[1];i.count++;b[1]=i.count%2}}else h.sortList.push([a,this.order])}else{h.sortList=[];if(h.sortForce!=
null){b=h.sortForce;for(c=0;c<b.length;c++)b[c][0]!=a&&h.sortList.push(b[c])}h.sortList.push([a,this.order])}setTimeout(function(){C(m[0],z,h.sortList,I);w(m[0],y(m[0],h.sortList,l))},1);return false}}).mousedown(function(){if(h.cancelSelection){this.onselectstart=function(){return false};return false}});m.bind("update",function(){var c=this;setTimeout(function(){c.config.parsers=e(c,z);l=g(c)},1)}).bind("updateCell",function(c,a){var d=this.config,b=[a.parentNode.rowIndex-1,a.cellIndex];l.normalized[b[0]][b[1]]=
d.parsers[b[1]].format(n(d,a),a)}).bind("sorton",function(c,a){d(this).trigger("sortStart");h.sortList=a;for(var b=h.sortList,i=this.config,e=b.length,k=0;k<e;k++){var j=b[k],f=i.headerList[j[0]];f.count=j[1];f.count++}C(this,z,b,I);w(this,y(this,b,l))}).bind("appendCache",function(){w(this,l)}).bind("applyWidgetId",function(c,a){x(a).format(this)}).bind("applyWidgets",function(){B(this)});d.metadata&&(d(this).metadata()&&d(this).metadata().sortlist)&&(h.sortList=d(this).metadata().sortlist);0<h.sortList.length&&
m.trigger("sorton",[h.sortList]);B(this)}})};this.addParser=function(a){for(var b=l.length,d=!0,e=0;e<b;e++)l[e].id.toLowerCase()==a.id.toLowerCase()&&(d=!1);d&&l.push(a)};this.addWidget=function(a){t.push(a)};this.formatFloat=function(a){a=parseFloat(a);return isNaN(a)?0:a};this.formatInt=function(a){a=parseInt(a);return isNaN(a)?0:a};this.isDigit=function(a){return/^[-+]?\d*$/.test(d.trim(a.replace(/[,.']/g,"")))};this.clearTableBody=function(a){d.browser.msie?function(){for(;this.firstChild;)this.removeChild(this.firstChild)}.apply(a.tBodies[0]):
a.tBodies[0].innerHTML=""}}});d.fn.extend({tablesorter:d.tablesorter.construct});var f=d.tablesorter;f.addParser({id:"text",is:function(){return!0},format:function(a){return d.trim(a.toLocaleLowerCase())},type:"text"});f.addParser({id:"digit",is:function(a,b){return d.tablesorter.isDigit(a,b.config)},format:function(a){return d.tablesorter.formatFloat(a)},type:"numeric"});f.addParser({id:"currency",is:function(a){return/^[\u00a3$\u20ac?.]/.test(a)},format:function(a){return d.tablesorter.formatFloat(a.replace(RegExp(/[\u00a3$\u20ac]/g),
""))},type:"numeric"});f.addParser({id:"ipAddress",is:function(a){return/^\d{2,3}[\.]\d{2,3}[\.]\d{2,3}[\.]\d{2,3}$/.test(a)},format:function(a){for(var a=a.split("."),b="",e=a.length,f=0;f<e;f++)var g=a[f],b=2==g.length?b+("0"+g):b+g;return d.tablesorter.formatFloat(b)},type:"numeric"});f.addParser({id:"url",is:function(a){return/^(https?|ftp|file):\/\/$/.test(a)},format:function(a){return jQuery.trim(a.replace(RegExp(/(https?|ftp|file):\/\//),""))},type:"text"});f.addParser({id:"isoDate",is:function(a){return/^\d{4}[\/-]\d{1,2}[\/-]\d{1,2}$/.test(a)},
format:function(a){return d.tablesorter.formatFloat(""!=a?(new Date(a.replace(RegExp(/-/g),"/"))).getTime():"0")},type:"numeric"});f.addParser({id:"percent",is:function(a){return/\%$/.test(d.trim(a))},format:function(a){return d.tablesorter.formatFloat(a.replace(RegExp(/%/g),""))},type:"numeric"});f.addParser({id:"usLongDate",is:function(a){return a.match(RegExp(/^[A-Za-z]{3,10}\.? [0-9]{1,2}, ([0-9]{4}|'?[0-9]{2}) (([0-2]?[0-9]:[0-5][0-9])|([0-1]?[0-9]:[0-5][0-9]\s(AM|PM)))$/))},format:function(a){return d.tablesorter.formatFloat((new Date(a)).getTime())},
type:"numeric"});f.addParser({id:"shortDate",is:function(a){return/\d{1,2}[\/\-]\d{1,2}[\/\-]\d{2,4}/.test(a)},format:function(a,b){var e=b.config,a=a.replace(/\-/g,"/");if("us"==e.dateFormat)a=a.replace(/(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{4})/,"$3/$1/$2");else if("uk"==e.dateFormat)a=a.replace(/(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{4})/,"$3/$2/$1");else if("dd/mm/yy"==e.dateFormat||"dd-mm-yy"==e.dateFormat)a=a.replace(/(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{2})/,"$1/$2/$3");return d.tablesorter.formatFloat((new Date(a)).getTime())},
type:"numeric"});f.addParser({id:"time",is:function(a){return/^(([0-2]?[0-9]:[0-5][0-9])|([0-1]?[0-9]:[0-5][0-9]\s(am|pm)))$/.test(a)},format:function(a){return d.tablesorter.formatFloat((new Date("2000/01/01 "+a)).getTime())},type:"numeric"});f.addParser({id:"metadata",is:function(){return!1},format:function(a,b,e){a=b.config;a=!a.parserMetadataName?"sortValue":a.parserMetadataName;return d(e).metadata()[a]},type:"numeric"});f.addWidget({id:"zebra",format:function(a){var b;a.config.debug&&(b=new Date);
var e,f=-1,g;d("tr:visible",a.tBodies[0]).each(function(){e=d(this);e.hasClass(a.config.cssChildRow)||f++;g=0==f%2;e.removeClass(a.config.widgetZebra.css[g?0:1]).addClass(a.config.widgetZebra.css[g?1:0])});a.config.debug&&d.tablesorter.benchmark("Applying Zebra widget",b)}})})(jQuery);
(function(d){d(function(){d.tablesorter&&(d("<div>"),d.tablesorter.defaults.cssAsc="column-header-asc",d.tablesorter.defaults.cssDesc="column-header-desc",d.tablesorter.defaults.cssHeader="column-header",d.tablesorter.addParser({id:"datetime",is:function(){return!1},format:function(f,a,b){return d("[datetime]:first",b).attr("datetime")},type:"text"}),d.tablesorter.addParser({id:"ignoreCase",is:function(){return!1},format:function(d){return d.toLowerCase()},type:"text"}),d.tablesorter.addParser({id:"string",
is:function(){return!1},format:function(d){return d},type:"text"}),d.tablesorter.addParser({id:"number",is:function(){return!1},format:function(f,a,b){f=d(".number:first",b).attr("data-value");null==f&&(f=Number.MIN_VALUE);return f},type:"numeric"}),d(".table-sortable").each(function(){d(this).tablesorter()}))})})(jQuery);
(function(d){d.fn.fixedcolumn=function(){return this.each(function(){var f=d(this).find("tr:first").find("> :first-child");if(f.length){var a=f[0].nodeName.toUpperCase();if("TD"===a||"TH"===a)a=f.width(),0<a&&f.width(a)}})}})(jQuery);
(function(d){var f="undefined"!=typeof window.innerWidth?function(){return{w:window.innerWidth,h:window.innerHeight}}:"undefined"!=typeof document.documentElement&&"undefined"!=typeof document.documentElement.clientWidth&&0!=document.documentElement.clientWidth?function(){return{w:document.documentElement.clientWidth,h:document.documentElement.clientHeight}}:function(){return{w:document.getElementsByTagName("body")[0].clientWidth,h:document.getElementsByTagName("body")[0].clientHeight}};window.kbs=
function(a){d(".kbs.current",a).removeClass("current");var b=d(".domain-section:first",a),e=d(".domain-section:last",a),m=this.scroll_to=function(c){var a=d(document).scrollTop();d(document).height();var b=f().h,b=a+b,e=c.offset().top,c=e+c.height();e<a?d(document).scrollTop(e):c>b&&d(document).scrollTop(a+(c-b))},g=this.get_current=function(){return d(".kbs.current:first",a)},n=this.set_next=function(c,a,b){c=c||g();a.length&&(c.removeClass("current"),a.addClass("current"),b||m(a))},w=this.next_domain=
function(c){var a=g(),b=u(a);b&&(b=b.find(".kbs:first"),n(a,b,c))},u=this._next_domain=function(c){if(!c||!c.length)return d(".domain-section:first",a);c=c.closest(".domain-section");return!c.length||c[0]===e[0]?b:c.next(".domain-section")},B=this.prev_domain=function(){var c=g(),a=x(c);a&&(a=a.find(".kbs:first"),n(c,a))},x=this._prev_domain=function(c){if(!c||!c.length)return d(".domain-section:last",a);var i=c.closest(".domain-section");return c.closest(".property-section").length||c.closest(".type-section").length?
i:!i.length||i[0]===b[0]?e:i.prev(".domain-section")},C=this.next_type=function(){var a=g(),b=y(a);b&&(b=b.find(".kbs:first"),n(a,b))},y=this._next_type=function(c){if(!c||!c.length)return d(".type-section:first",a);var b=c.closest(".domain-section"),c=c.closest(".type-section"),c=c.length?c.next(".type-section"):b.find(".type-section:first");if(!c||!c.length){var e=u(b);if(e)for(;e.get(0)!==b.get(0);){c=e.find(".type-section:first");if(c.length)break;e=u(e)}}return c},o=this.prev_type=function(){var a=
g(),b=l(a);b&&(b=b.find(".kbs:first"),n(a,b))},l=this._prev_type=function(c){if(!c||!c.length)return d(".type-section:last",a);var b=c.closest(".domain-section"),e=c.closest(".type-section");if(c.closest(".property-section").length)return e;var f;e.length&&(f=e.prev(".type-section"));if(!f||!f.length)if(c=x(b))for(;c.get(0)!==b.get(0);){f=c.find(".type-section:last");if(f.length)break;c=x(c)}return f},t=this.next_prop=function(){var a=g(),b=p(a);b&&(b=b.find(".kbs:first"),n(a,b))},p=this._next_prop=
function(c){if(!c||!c.length)return d(".property-section:first",a);var b=c.closest(".domain-section"),e=c.closest(".type-section"),f=c.closest(".property-section"),b=f.length?f.next(".property-section"):e.length?e.find(".property-section:first"):b.find(".property-section:first");if(!b||!b.length)if(c=y(c))for(;c.get(0)!==e.get(0);){b=c.find(".property-section:first");if(b.length)break;null==e.get(0)&&(e=c);c=y(c)}return b},A=this.prev_prop=function(){var a=g(),b=v(a);b&&(b=b.find(".kbs:first"),n(a,
b))},v=this._prev_prop=function(c){if(!c||!c.length)return d(".property-section:last",a);var b=c.closest(".domain-section"),e=c.closest(".type-section"),f=c.closest(".property-section");if(c.closest(".data-section").length)return f;var g;f.length&&(g=f.prev(".property-section"));if(!g||!g.length)if(o=e.length?l(e):l(b))for(;o.get(0)!==e.get(0);){g=o.find(".property-section:last");if(g.length)break;null==e.get(0)&&(e=o);o=l(o)}return g};this.next=function(){var a=g(),b=this._next(a);b&&n(a,b)};this._next=
function(c){if(!c||!c.length)return d(".domain-section:first .kbs:first",a);var f=c.closest(".domain-section"),g=c.closest(".type-section"),h=c.closest(".property-section");if(c.closest(".data-section").length){c=c.next(".kbs");if(c.length)return c;c=h.next(".property-section").find(".kbs:first");if(c.length)return c;c=g.next(".type-section").find(".kbs:first")}else if(h.length){c=h.find(".data-section:first .kbs:first");if(c.length)return c;c=h.next(".property-section").find(".kbs:first");if(c.length)return c;
c=g.next(".type-section").find(".kbs:first")}else if(g.length){c=g.find(".property-section:first .kbs:first");if(c.length)return c;c=g.next(".type-section").find(".kbs:first")}else c=f.find(".type-section:first .kbs:first");return c.length?c:f.get(0)===e.get(0)?b.find(".kbs:first"):f.next(".domain-section").find(".kbs:first")};this.prev=function(){var a=g(),b=this._prev(a);b&&n(a,b)};this._prev=function(c){if(!c||!c.length)return c=d(".data-section:last .kbs:last",a),c.length||(c=d(".property-section:last .kbs:first",
a)),c.length||(c=d(".type-section:last .kbs:first",a)),c.length||(c=d(".domain-section:last .kbs:first",a)),c;var f=c.closest(".domain-section"),g=c.closest(".type-section"),h=c.closest(".property-section");return c.closest(".data-section").length?(c=c.prev(".kbs"),c.length?c:h.find(".kbs:first")):h.length?(c=h.prev(".property-section").find(".kbs:last"),c.length?c:g.find(".kbs:first")):g.length?(c=g.prev(".type-section").find(".kbs:last"),c.length?c:f.find(".kbs:first")):f.get(0)===b.get(0)?e.find(".kbs:last"):
f.prev(".domain-section").find(".kbs:last")};this.edit=function(){this.get_current().trigger("edit")};var h=this;d(document).unbind(".kbs").bind("keydown.kbs",function(a){var b=a.target;if(b==document.body||b==document||b==window||b==d("html")[0])b=a.keyCode,68===b?a.shiftKey?B():w():84===b?a.shiftKey?o():C():80===b?a.shiftKey?A():t():74===b?h.next():75===b?h.prev():69===b&&h.edit()})}})(jQuery);
(function(d,f){var a=window.propbox={init:function(b,e){e=d.extend({lang:"/lang/en"},e);if(!e.base_ajax_url)throw Error("base_ajax_url required in propbox options");if(!e.base_static_url)throw Error("base_static_url required in propbox options");if(!e.id)throw Error("topic id required in propbox options");if(!e.lang)throw Error("lang required in propbox options");a.options=e;a.kbs=new f(b);a.kbs.set_next(a.kbs.get_current(),d(".kbs:visible:first",b,!0));d(".kbs",b).live("click",function(){var b=a.kbs.get_current();
a.kbs.set_next(b,d(this),!0)}).live("edit",function(){var a=d(this).find(".headmenu:first").data("submenu");a&&d("li:first a:first",a).click()});a.init_menus(b)},init_menus:function(b,e){b=d(b||document);e&&d(".nicemenu",b).nicemenu();(b&&b.is(".data-row")?b:d(".data-row",b)).hover(a.row_menu_hoverover,a.row_menu_hoverout);d(".nicemenu .headmenu",b).add(d(".nicemenu .default-action",b)).click("click",function(){if(a.kbs){var b=a.kbs.get_current();b&&a.kbs.set_next(b,d(this).parents(".kbs:first"),
!0)}return!1})},row_menu_hoverover:function(){var b=d(this);a.row_menu_hoverover.timeout=setTimeout(function(){b.addClass("row-hover")},300)},row_menu_hoverout:function(){clearTimeout(a.row_menu_hoverover.timeout);d(this).removeClass("row-hover")},get_script:function(b,e){var f=a.get_script.cache;f||(f=a.get_script.cache={});var g=f[b];g?1===g.state?g.callbacks.push(e):4===g.state&&e():(g=f[b]={state:0,callbacks:[e]},d.ajax({url:a.options.base_static_url+b,dataType:"script",beforeSend:function(){g.state=
1},success:function(){g.state=4;d.each(g.callbacks,function(a,b){b()})},error:function(){g.state=-1}}))},prop_edit:function(b,e){var f=d(b).parents(".submenu").data("headmenu").parents(".property-section").find(".data-section .data-row:first:visible .nicemenu:first .headmenu:first a");f.length?f.click():a.prop_add(b,e);return!1},prop_add:function(b,e){var f=d(b).parents(".submenu").data("headmenu").parents(".property-section");a.get_script("/propbox-edit.mf.js",function(){a.edit.prop_add_begin(f,
e)});return!1},value_edit:function(b){var e=d(b).parents(".submenu").data("headmenu").parents(".data-row:first"),f=e.parents(".property-section");a.get_script("/propbox-edit.mf.js",function(){a.edit.value_edit_begin(f,e)});return!1},value_delete:function(b){var e=d(b).parents(".submenu").data("headmenu").parents(".data-row:first"),f=e.parents(".property-section");a.get_script("/propbox-edit.mf.js",function(){a.edit.value_delete_begin(f,e)});return!1},close_message:function(a){d(a).parents(".row-msg:first").remove();
return!1}}})(jQuery,window.kbs);
(function(d,f,a){var b=f.i18n_tab={init:function(){d("#i18n-table").fixedcolumn();a.init_menus()},add_name:function(a,m){var g=d(a).parents(".data-row:first");f.get_script(f.h.static_url("i18n-edit.mf.js"),function(){b.edit.add_name_begin(g,m)});return!1},edit_name:function(a,m,g){var n=d(a).parents(".submenu").data("headmenu").parents(".data-row:first");f.get_script(f.h.static_url("i18n-edit.mf.js"),function(){b.edit.edit_name_begin(n,m,g)});return!1},delete_name:function(a,m,g){var n=d(a).parents(".submenu").data("headmenu").parents(".data-row:first");
f.get_script(f.h.static_url("i18n-edit.mf.js"),function(){b.edit.delete_name_begin(n,m,g)});return!1}};d(b.init)})(jQuery,window.freebase,window.propbox);
