
/*
 * Copyright 2012, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Additional Licenses for Third Party components can be found here:
 * http://wiki.freebase.com/wiki/Freebase_Site_License
 *
 */
/*
 
 jQuery Tools @VERSION / Expose - Dim the lights

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/toolbox/expose.html

 Since: Mar 2010
 Date: @DATE 
 
 jQuery Tools @VERSION Overlay - Overlay base. Extend it.

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/overlay/

 Since: March 2008
 Date: @DATE 
*/
(function(e){function f(){if(e.browser.msie){var i=e(document).height(),k=e(window).height();return[window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth,i-k<20?k:i]}return[e(document).width(),e(document).height()]}function c(i){if(i)return i.call(e.mask)}e.tools=e.tools||{version:"@VERSION"};var b;b=e.tools.expose={conf:{maskId:"exposeMask",loadSpeed:"slow",closeSpeed:"fast",closeOnClick:true,closeOnEsc:true,zIndex:9998,opacity:0.8,startOpacity:0,color:"#fff",onLoad:null,
onClose:null}};var a,d,g,h,j;e.mask={load:function(i,k){if(g)return this;if(typeof i=="string")i={color:i};i=i||h;h=i=e.extend(e.extend({},b.conf),i);a=e("#"+i.maskId);if(!a.length){a=e("<div/>").attr("id",i.maskId);e("body").append(a)}var l=f();a.css({position:"absolute",top:0,left:0,width:l[0],height:l[1],display:"none",opacity:i.startOpacity,zIndex:i.zIndex});i.color&&a.css("backgroundColor",i.color);if(c(i.onBeforeLoad)===false)return this;i.closeOnEsc&&e(document).bind("keydown.mask",function(m){m.keyCode==
27&&e.mask.close(m)});i.closeOnClick&&a.bind("click.mask",function(m){e.mask.close(m)});e(window).bind("resize.mask",function(){e.mask.fit()});if(k&&k.length){j=k.eq(0).css("zIndex");e.each(k,function(){var m=e(this);/relative|absolute|fixed/i.test(m.css("position"))||m.css("position","relative")});d=k.css({zIndex:Math.max(i.zIndex+1,j=="auto"?0:j)})}a.css({display:"block"}).fadeTo(i.loadSpeed,i.opacity,function(){e.mask.fit();c(i.onLoad)});g=true;return this},close:function(){if(g){if(c(h.onBeforeClose)===
false)return this;a.fadeOut(h.closeSpeed,function(){c(h.onClose);d&&d.css({zIndex:j})});e(document).unbind("keydown.mask");a.unbind("click.mask");e(window).unbind("resize.mask");g=false}return this},fit:function(){if(g){var i=f();a.css({width:i[0],height:i[1]})}},getMask:function(){return a},isLoaded:function(){return g},getConf:function(){return h},getExposed:function(){return d}};e.fn.mask=function(i){e.mask.load(i);return this};e.fn.expose=function(i){e.mask.load(i,this);return this}})(jQuery);
(function(e){function f(a,d){var g=this,h=a.add(g),j=e(window),i,k,l,m=e.tools.expose&&(d.mask||d.expose),p=Math.random().toString().slice(10);if(m){if(typeof m=="string")m={color:m};m.closeOnClick=m.closeOnEsc=false}var n=d.target||a.attr("rel");k=n?e(n):a;if(!k.length)throw"Could not find Overlay: "+n;a&&a.index(k)==-1&&a.click(function(o){g.load(o);return o.preventDefault()});e.extend(g,{load:function(o){if(g.isOpened())return g;var q=b[d.effect];if(!q)throw'Overlay: cannot find effect : "'+d.effect+
'"';d.oneInstance&&e.each(c,function(){this.close(o)});o=o||e.Event();o.type="onBeforeLoad";h.trigger(o);if(o.isDefaultPrevented())return g;l=true;m&&e(k).expose(m);var r=d.top,t=d.left,u=k.outerWidth({margin:true}),v=k.outerHeight({margin:true});if(typeof r=="string")r=r=="center"?Math.max((j.height()-v)/2,0):parseInt(r,10)/100*j.height();if(t=="center")t=Math.max((j.width()-u)/2,0);q[0].call(g,{top:r,left:t},function(){if(l){o.type="onLoad";h.trigger(o)}});m&&d.closeOnClick&&e.mask.getMask().one("click",
g.close);d.closeOnClick&&e(document).bind("click."+p,function(s){e(s.target).parents(k).length||g.close(s)});d.closeOnEsc&&e(document).bind("keydown."+p,function(s){s.keyCode==27&&g.close(s)});return g},close:function(o){if(!g.isOpened())return g;o=o||e.Event();o.type="onBeforeClose";h.trigger(o);if(!o.isDefaultPrevented()){l=false;b[d.effect][1].call(g,function(){o.type="onClose";h.trigger(o)});e(document).unbind("click."+p).unbind("keydown."+p);m&&e.mask.close();return g}},getOverlay:function(){return k},
getTrigger:function(){return a},getClosers:function(){return i},isOpened:function(){return l},getConf:function(){return d}});e.each("onBeforeLoad,onStart,onLoad,onBeforeClose,onClose".split(","),function(o,q){e.isFunction(d[q])&&e(g).bind(q,d[q]);g[q]=function(r){e(g).bind(q,r);return g}});i=k.find(d.close||".close");if(!i.length&&!d.close){i=e('<a class="close"></a>');k.prepend(i)}i.click(function(o){g.close(o)});d.load&&g.load()}e.tools=e.tools||{version:"@VERSION"};e.tools.overlay={addEffect:function(a,
d,g){b[a]=[d,g]},conf:{close:null,closeOnClick:true,closeOnEsc:true,closeSpeed:"fast",effect:"default",fixed:!e.browser.msie||e.browser.version>6,left:"center",load:false,mask:null,oneInstance:true,speed:"normal",target:null,top:"10%"}};var c=[],b={};e.tools.overlay.addEffect("default",function(a,d){var g=this.getConf(),h=e(window);if(!g.fixed){a.top+=h.scrollTop();a.left+=h.scrollLeft()}a.position=g.fixed?"fixed":"absolute";this.getOverlay().css(a).fadeIn(g.speed,d)},function(a){this.getOverlay().fadeOut(this.getConf().closeSpeed,
a)});e.fn.overlay=function(a){var d=this.data("overlay");if(d)return d;if(e.isFunction(a))a={onBeforeLoad:a};a=e.extend(true,{},e.tools.overlay.conf,a);this.each(function(){d=new f(e(this),a);c.push(d);e(this).data("overlay",d)});return a.api?d:this}})(jQuery);
(function(e){e.fn.mqlkey=function(c){return this.each(function(){var b=e(this);if(b.is(":text")){var a=b.data("mqlkey");a&&a._destroy();a=new f(this,c);b.data("mqlkey",a)}})};var f=e.mqlkey=function(c,b){this.options=e.extend(true,{},f.defaults,b);this.input=e(c);this.original=this.input.val();this.init()};f.prototype={init:function(){var c=this;this.input.bind("keyup.mqlkey",function(b){c.textchange(b)}).bind(e.browser.msie?"paste.mqlkey":"input.mqlkey",function(b){c.textchange(b)});if(this.options.source){this.source=
e(this.options.source);this.source_generate=true;this.input.bind("change.mqlkey",function(){c.source_generate=false});this.source.bind("change.mqlkey",function(){if(c.source_generate){var b=f.from(c.source.val());c.input.val(b).trigger("keyup")}})}},_destroy:function(){this.input.unbind(".mqlkey");this.source&&this.source.unbind("change.mqlkey")},textchange:function(c){clearTimeout(this.textchange_timeout);var b=this;this.textchange_timeout=setTimeout(function(){b.textchange_delay(c)},200)},textchange_delay:function(){this.input.trigger("textchange");
var c=e.trim(this.input.val());return c===this.original&&c!==""?this.valid(c):f.reserved_word(c)?this.invalid(c,c+" is a reserved word."):f.test(c,this.options.schema)?c.length<this.options.minlen?this.invalid(c):this.options.check_key?this.check_key(c):this.valid(c):this.invalid(c)},check_key:function(c){var b=this;if(this.xhr){this.xhr.abort();this.xhr=null}var a={id:null,key:{namespace:this.options.namespace,value:c}};clearTimeout(this.check_key.timeout);this.check_key.timeout=setTimeout(function(){b.xhr=
b.options.mqlread(a,function(d){return d?b.invalid(c,"Key already exists"):b.valid(c)},function(d){return d?b.invalid(d.responseText()):b.invalid("mqlread error!")})},200)},valid:function(c){this.input.trigger("valid",c)},invalid:function(c,b){if(!b){b=this.options.minlen>1?"Key must be "+this.options.minlen+" or more alphanumeric characters":"Key must be alphanumeric";b+=", lowercase, begin with a letter and not end with a non-alphanumeric character. Underscores are allowed but not consecutively."}this.input.trigger("invalid",
b)}};e.extend(f,{defaults:{minlen:1,check_key:true,namespace:"/",mqlread:function(c,b,a){return f.mqlread(null,c,b,a)},source:null,schema:false},mqlread:function(c,b,a,d){c={url:c||"http://api.freebase.com/api/service/mqlread",data:{query:JSON.stringify({query:b})},dataType:"jsonp",success:function(g){return a(g.result)},error:d};return e.ajax(c)},from:function(c){c=c.toLowerCase();c=c.replace(/[^a-z0-9]/g,"_");c=c.replace(/\_\_+/g,"_");c=c.replace(/[^a-z0-9]+$/,"");c=c.replace(/^[^a-z]+/,"");if(f.reserved_word(c))c=
"x_"+c;return c},reservedwords:"meta typeguid left right datatype scope attribute relationship property link class future update insert delete replace create destroy default sort limit offset optional pagesize cursor index !index for while as in is if else return count function read write select var connect this self super xml sql mql any all macro estimate-count",typeonlywords:"guid id object domain name key type keys value timestamp creator permission namespace unique schema reverse",_reserved_word:null,
reserved_word:function(c){if(!f._reserved_word){f._reserved_word={};e.each([f.reservedwords,f.typeonlywords],function(b,a){e.each(a.split(" "),function(d,g){f._reserved_word[g]=1})})}return f._reserved_word[c]===1},fast:/^[A-Za-z0-9](?:[_-]?[A-Za-z0-9])*$/,slow:/^(?:[A-Za-z0-9]|\$[A-F0-9]{4})(?:[_-]?[A-Za-z0-9]|[_-]?\$[A-F0-9]{4})*$/,schema:/^[a-z](?:_?[a-z0-9])*$/,test:function(c,b){if(b)return f.schema.test(c);return f.fast.test(c)||f.slow.test(c)}})})(jQuery);
(function(e,f){f.require("dojo.date.stamp");f.require("dojo.date.locale");f.require("dojo.number");e.fn.validate_input=function(b){return this.each(function(){var a=e(this);if(a.is(":text")){var d=a.data("$.validate_input");d&&d._destroy();d=new c(this,b);a.data("$.validate_input",d)}})};var c=e.validate_input=function(b,a){var d=this.options=e.extend(true,{},c.defaults,a);if(typeof d.validator!=="function")throw"A validator is required";if(!d.lang)d.lang="/lang/en";d.lang=d.lang==="/lang/en"?["lang/en"]:
[d.lang,"/lang/en"];d.locales=[];e.each(d.lang,function(h,j){d.locales[h]=f.i18n.normalizeLocale(j.split("/").pop())});this.input=e(b);this.init();var g=this;this.input.bind("remove",function(){g._destroy()});return this};c.prototype={init:function(){var b=this;this.input.bind("keyup.validate_input",function(a){b.textchange(a)}).bind(e.browser.msie?"paste.validate_input":"input.validate_input",function(a){b.textchange(a)}).bind("keypress.validate_input",function(a){a.keyCode===13&&b.validate(true)}).bind("blur.validate_input",
function(){b.validate(true)})},_destroy:function(){this.input.unbind(".validate_input")},valid:function(b){this.input.trigger("valid",b)},invalid:function(b,a){this.input.trigger("invalid",a)},empty:function(){this.input.trigger("empty")},textchange:function(){clearTimeout(this.textchange_timeout);var b=this;this.textchange_timeout=setTimeout(function(){b.validate()},200)},validate:function(b){b&&clearTimeout(this.textchange_timeout);b=this.options;var a=e.trim(this.input.val());if(a==="")return this.empty();
try{return this.valid(b.validator(a,b))}catch(d){return this.invalid(a,""+d)}}};e.extend(c,{defaults:{validator:function(b){return{text:b,value:b}}},log:function(){},invalid:function(b,a,d,g){throw new Error("Invalid "+d+(g?": "+g:""));},text:function(b,a){if(b.lengh>4096)return this.invalid(b,a,type,"Text too long");return{text:b,value:b}},topic:function(){return c.defaults.validator},enumerated:function(){return c.defaults.validator},"boolean":function(){return c.defaults.validator},uri:function(b,
a){var d=c.uri.regex;if(!d)d=c.uri.regex=/^(https?|ftp):\/\/(((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:)*@)?(((\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5]))|((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?)(:\d*)?)(\/((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)+(\/(([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)*)*)?)?(\?((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|[\uE000-\uF8FF]|\/|\?)*)?(\#((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|\/|\?)*)?$/i;
if(d.test(b))return{text:b,value:b};return c.invalid(b,a,"uri")},"int":function(b,a){return c.number.parse(b,a,false)},"float":function(b,a){return c.number.parse(b,a,true)},number:function(b,a,d){return c.number.parse(b,a,d)},datetime:function(b,a){return c.datetime.parse(b,a)},mqlkey:function(b,a){var d=c.mqlkey.regex;if(!d)d=c.mqlkey.regex=/^[A-Za-z0-9][A-Za-z0-9_-]*$/;if(d.test(b))return{text:b,value:b};return c.invalid(b,a,"mqlkey")}});e.extend(c.number,{parse:function(b,a,d){var g=a&&a.locales||
["en"],h,j;h=0;for(j=g.length;h<j;h++){var i=g[h];a=f.number.parse(b,{locale:i});if(!isNaN(a)){b={};if(d){b.value=a;b.text=f.number.format(a,{locale:i})}else{b.value=f.number.round(a,0);b.text=f.number.format(b.value,{locale:i})}return b}}throw c.invalid("number",b);}});e.extend(c.datetime,{formats:["yyyy",["dateFormatItem-y"],"yyyy-MM",["dateFormatItem-yM","dateFormatItem-yMMM"],"yyyy-MM-dd",["dateFormat-short","dateFormat-medium","dateFormat-long"]],parse:function(b,a){if(!f.date.stamp._isoRegExp)f.date.stamp._isoRegExp=
/^(?:(-?\d{4})(?:-(\d{2})(?:-(\d{2}))?)?)?(?:T(\d{2}):(\d{2})(?::(\d{2})(.\d+)?)?((?:[+-](\d{2}):(\d{2}))|Z)?)?$/;var d=f.date.stamp.fromISOString(b);if(d)return{text:b,value:b,date:d};var g=a&&a.locales||["en"],h,j,i,k,l,m;h=0;for(j=g.length;h<j;h++){var p=g[h],n=f.date.locale._getGregorianBundle(p);i=0;for(k=c.datetime.formats.length;i<k;i+=2){var o=c.datetime.formats[i],q=c.datetime.formats[i+1];l=0;for(m=q.length;l<m;l++){var r=n[q[l]];if(r){r=i18n.normalize_pattern(r);try{d=f.date.locale.parse(b,
{datePattern:r,selector:"date",locale:p});return{text:b,value:f.date.locale.format(d,{datePattern:o,selector:"date"}),date:d}}catch(t){}}}}}throw c.invalid("datetime",b);}})})(jQuery,dojo);
(function(e){e.fn.data_input=function(f){return this.each(function(){var c=e(this),b=c.data("$.data_input");b&&b._destroy();b=new e.data_input(this,f);c.data("$.data_input",b)})};e.data_input=function(f,c){this.options=e.extend(true,{},c);this.container=e(f);this.metadata=this.container.metadata();this.input=e(":input",this.container);this.init();var b=this;this.input.bind("remove",function(){b._destroy()})};e.data_input.prototype={init:function(){var f=this,c=this.container,b=this.input,a=this.options;
b.bind("focusin.data_input",function(){f.container.addClass("focus")}).bind("focusout.data_input",function(){f.container.removeClass("focus")}).bind("valid.data_input",function(g,h){g.stopPropagation();var j={name:f.input.attr("name")};if(h.id)j.id=h.id;else if(h.create_new){j.create_new=h.create_new;j.lang=f.metadata.lang||a.lang}else{j.value=h.value;if(f.metadata.type==="/type/text")j.lang=f.metadata.lang||a.lang;else if(f.metadata.type==="/type/key")j.namespace=h.namespace}f.container.data("data",
j);f.container.removeClass("error").addClass("valid");f.container.trigger("valid")}).bind("invalid.data_input",function(g){g.stopPropagation();f.container.removeData("data");f.container.removeClass("valid").addClass("error");f.container.trigger("invalid")}).bind("empty.data_input",function(g){g.stopPropagation();g={name:f.input.attr("name")};if(f.metadata&&f.metadata.lang)g.lang=f.metadata.lang;f.container.data("data",g);f.container.removeClass("valid").removeClass("error");f.container.trigger("empty")}).bind("keypress.data_input",
function(g){g.keyCode===13&&!g.isDefaultPrevented()&&f.container.trigger("submit")}).bind("keyup.data_input",function(g){g.keyCode===27&&f.container.trigger("cancel")});if(c.is(".topic")){c=f.metadata.type;var d=null;if(a.suggest_impl)d=a.suggest_impl.instance(c,true,f.metadata&&f.metadata.lang||a.lang);b.validate_topic(e.extend({incompatible_types:f.options.incompatible_types,expected_type:c},d)).bind("valid.data_input",function(g,h){f.fb_select(h)}).bind("invalid.data_input",function(){f.fb_textchange()});
if(this.metadata&&this.metadata.id){b.data("data.suggest",this.metadata);this.validate()}}else if(c.is(".text"))b.validate_input({validator:e.validate_input.text});else if(c.is(".datetime"))b.validate_input({validator:e.validate_input.datetime,lang:a.lang});else if(c.is(".enumerated")){b.validate_enumerated().bind("valid.data_input",function(g,h){f.fb_select(h)}).bind("invalid.data_input",function(){f.fb_textchange()});this.metadata&&this.metadata.id&&this.validate()}else if(c.is(".int"))b.validate_input({validator:e.validate_input["int"],
lang:a.lang});else if(c.is(".float"))b.validate_input({validator:e.validate_input["float"],lang:a.lang});else if(c.is(".uri"))b.validate_input({validator:e.validate_input.uri});else if(c.is(".boolean"))b.validate_boolean();else if(c.is(".enumeration"))b.validate_input({validator:e.validate_input.mqlkey});else if(c.is(".key"))b.validate_key(a,this.metadata);else if(c.is(".rawstring"))b.validate_input({validator:e.validate_input.text});else throw new Error("Invalid data-input: "+c.attr("class"));},
_destroy:function(){this.input.unbind(".data_input")},validate:function(){var f=this.input;e.each(["$.validate_topic","$.validate_input","$.validate_enumerated","$.validate_boolean","$.validate_key"],function(c,b){var a=f.data(b);if(a){a.validate(true);return false}})},reset:function(){this.container.removeData("data");if(this.input.is(":text"))this.input.val("");else if(this.input.is("select"))this.input[0].selectedIndex=0;else this.input.is(":radio")&&this.input.each(function(){this.checked=false})},
fb_textchange:function(){},fb_select:function(){},ajax_beforeSend:function(f){if(!this.xhr_queue)this.xhr_queue=[];this.xhr_queue.push(f);this.container.trigger("loading")},ajax_complete:function(f){if(!this.xhr_queue)this.xhr_queue=[];for(var c=0,b=this.xhr_queue.length;c<b;c++)if(f===this.xhr_queue[c]){this.xhr_queue.splice(c,1);break}this.xhr_queue.length===0&&this.container.trigger("loading_complete")}};e.fn.validate_topic=function(f){return this.each(function(){var c=e(this);if(c.is(":text")){var b=
c.data("$.validate_topic");b&&b._destroy();b=new e.validate_topic(this,f);c.data("$.validate_topic",b)}})};e.validate_topic=function(f,c){this.options=e.extend(true,{},c);this.input=e(f);this.init()};e.validate_topic.prototype={init:function(){var f=this;this.input.suggest(this.options).bind("fb-textchange.validate_topic",function(){f.input.val()===""?f.empty():f.invalid()}).bind("fb-select.validate_topic",function(c,b){f.input.val(b.name!=null?b.name:b.id);f.incompatible_types_check(b)}).bind("fb-select-new.validate_topic",
function(c,b){f.valid(b)})},incompatible_types_check:function(f){var c=this;c.options.incompatible_types&&c.options.expected_type?c.options.incompatible_types.check(f.id,c.options.expected_type,{compatible:function(){c.valid(f)},incompatible:c.options.incompatible_types.inline_suggest_incompatible_callback(c.input,{onConfirm:function(){c.valid(f)}})}):this.valid(f)},invalid:function(){this.input.trigger("invalid")},valid:function(f){if(typeof f==="string")f={create_new:f};this.input.trigger("valid",
f)},empty:function(){this.input.trigger("empty")},_destroy:function(){this.input.unbind(".validate_topic")},validate:function(){if(this.input.val()==="")this.empty();else{var f=this.input.data("data.suggest");f?this.valid(f):this.invalid()}}};e.fn.validate_enumerated=function(f){return this.each(function(){var c=e(this);if(c.is("select")){var b=c.data("$.validate_enumerated");b&&b._destroy();b=new e.validate_enumerated(this,f);c.data("$.validate_enumerated",b)}})};e.validate_enumerated=function(f,
c){this.options=e.extend(true,{},c);this.input=e(f);this.init()};e.validate_enumerated.prototype={init:function(){var f=this;this.input.bind("change.validate_enumerated, keypress.validate_enumerated",function(){this.selectedIndex===0?f.empty():f.valid({text:e(":selected",this).text(),id:this.value})})},invalid:function(){this.input.trigger("invalid")},valid:function(f){this.input.trigger("valid",f);this.input.trigger("fb-select",f)},empty:function(){this.input.trigger("empty")},_destroy:function(){this.input.unbind(".validate_enumerated")},
validate:function(){var f=this.input[0];f.selectedIndex>0?this.valid({text:e(":selected",this.input).text(),id:f.value}):this.empty()}};e.fn.validate_boolean=function(f){var c,b;this.each(function(){var d=e(this);if(d.is(":radio"))if(d.val().toLowerCase()==="true")c=d;else if(d.val().toLowerCase()==="false")b=d});if(c&&b){var a=c.data("$.validate_boolean");a&&a._destroy();a=new e.validate_boolean(c,b,f);c.data("$.validate_boolean",a)}else throw"$.fn.validate_boolean requires two radios: true and false";
return this};e.validate_boolean=function(f,c,b){this.options=e.extend(true,{},b);this.tradio=f;this.fradio=c;this.input=this.tradio;this.init()};e.validate_boolean.prototype={init:function(){var f=this;this.tradio.bind("change.validate_boolean",function(){f.validate()})},_destroy:function(){this.input.unbind(".validate_boolean")},valid:function(f){this.input.trigger("valid",f)},empty:function(){this.input.trigger("empty")},validate:function(){if(this.tradio.is(":checked"))this.valid({text:this.tradio.text(),
value:true});else this.fradio.is(":checked")?this.valid({text:this.fradio.text(),value:false}):this.empty()}};e.fn.validate_key=function(f,c){var b,a;this.each(function(){var g=e(this);if(g.is(":text"))if(g.is(".key-namespace"))b=g;else if(g.is(".key-value"))a=g});if(b&&a){var d=a.data("$.validate_key");d&&d._destroy();d=new e.validate_key(b,a,f);b.data("$.validate_key",d);if(c&&c.namespace&&c.value){b.data("data.suggest",{id:c.namespace});a.val(c.value)}}else throw"$.fn.validate_key requires two inputs: namespace and value";
return this};e.validate_key=function(f,c,b){this.options=e.extend(true,{},b);this.key_namespace_input=f;this.key_value_input=c;this.input=this.key_namespace_input;this.init()};e.validate_key.prototype={init:function(){var f=this,c=null;if(this.options.suggest_impl)c=this.key_value_input.attr("name")!="/type/namespace/keys"?this.options.suggest_impl.instance("/type/namespace"):e.extend({},fb.suggest_options.service_defaults);this.key_namespace_input.suggest(c).bind("fb-textchange.validate_key",function(){f.validate()}).bind("fb-select.validate_key",
function(b,a){f.key_namespace_input.val(a.name||a.id);f.validate()});this.key_value_input.validate_input({validator:e.validate_input.mqlkey}).bind("valid",function(b){b.stopPropagation();f.validate()}).bind("invalid",function(b){b.stopPropagation();f.validate()}).bind("empty",function(b){b.stopPropagation();f.validate()})},_destroy:function(){this.key_namespace_input.unbind(".validate_key");this.key_value_input.unbind()},invalid:function(){this.input.trigger("invalid")},valid:function(f){this.input.trigger("valid",
f)},empty:function(){this.input.trigger("empty")},validate:function(){if(this.is_valid_key_namespace()&&this.is_valid_key_value())this.valid({namespace:this.key_namespace_input.data("data.suggest").id,value:this.key_value_input.val(),text:this.key_value_input.val()});else this.key_namespace_input.val()===""&&this.key_value_input.val()===""?this.empty():this.invalid()},is_valid_key_namespace:function(){return this.key_namespace_input.data("data.suggest")!=null},is_valid_key_value:function(){try{e.validate_input.mqlkey(this.key_value_input.val());
return true}catch(f){return false}}}})(jQuery);
(function(e,f,c){var b=window.formlib={status:c,init:function(a){var d=a.event_prefix||"form.";a.form.bind(d+"submit",function(){b.submit(a)}).bind(d+"cancel",function(){b.cancel(a)}).bind(d+"error",function(g,h){a.form.removeClass("loading");b.disable_submit(a);c.error(h,true)}).bind(d+"success",function(){a.form.removeClass("loading")}).bind(d+"valid",function(){b.enable_submit(a)}).bind(d+"invalid",function(){b.disable_submit(a)});b.init_submit_cancel(a);a.init(a)},submit:function(a){if(!a.form.is(".loading"))if(b.is_submit_enabled(a)){document.activeElement&&
e(document.activeElement).blur();if(a.validate(a)){a.form.addClass("loading");a.submit(a,b.default_submit_ajax_options(a))}}},cancel:function(){},init_inline_add_form:function(a){var d=a.event_prefix||"form.inline_add_form.";a.edit_row.bind(d+"submit",function(){b.submit_inline_add_form(a)}).bind(d+"cancel",function(){b.cancel_inline_add_form(a)}).bind(d+"error",function(g,h){a.edit_row.removeClass("loading");b.disable_submit(a);c.error(h,true)}).bind(d+"success",function(){a.edit_row.removeClass("loading")}).bind(d+
"valid",function(){b.enable_submit(a)}).bind(d+"invalid",function(){b.disable_submit(a)});b.init_submit_cancel(a);a.trigger&&a.trigger.parents(".trigger-row:first").hide();a.body.append(a.edit_row).append(a.submit_row);a.init(a)},submit_inline_add_form:function(a){if(!a.edit_row.is(".loading"))if(b.is_submit_enabled(a)){document.activeElement&&e(document.activeElement).blur();if(a.validate(a)){a.edit_row.addClass("loading");a.submit(a,b.default_submit_ajax_options(a))}}},success_inline_add_form:function(a,
d){a.edit_row.before(d);f.ize(d);a.reset(a);a.edit_row.trigger(a.event_prefix+"success")},cancel_inline_add_form:function(a){a.edit_row.remove();a.submit_row.remove();a.trigger&&a.trigger.parents(".trigger-row:first").show()},init_inline_edit_form:function(a){var d=a.event_prefix||"form.inline_edit_form.";a.edit_row.bind(d+"submit",function(){b.submit_inline_edit_form(a)}).bind(d+"cancel",function(){b.cancel_inline_edit_form(a)}).bind(d+"error",function(g,h){a.edit_row.removeClass("loading");b.disable_submit(a);
c.error(h,true)}).bind(d+"success",function(){a.edit_row.removeClass("loading")}).bind(d+"valid",function(){b.enable_submit(a)}).bind(d+"invalid",function(){b.disable_submit(a)});b.init_submit_cancel(a);a.row.hide();a.row.before(a.edit_row).before(a.submit_row);a.init(a)},submit_inline_edit_form:function(a){if(!a.edit_row.is(".loading"))if(b.is_submit_enabled(a)){document.activeElement&&e(document.activeElement).blur();if(a.validate(a)){a.edit_row.addClass("loading");a.submit(a,b.default_submit_ajax_options(a))}}},
success_inline_edit_form:function(a,d){a.row.replaceWith(d);a.row=d;f.ize(d);a.edit_row.trigger(a.event_prefix+"cancel")},cancel_inline_edit_form:function(a){a.edit_row.remove();a.submit_row.remove();a.row.show()},success_inline_delete:function(a,d,g){a.hide().addClass("old-row");a.after(d);d.append(a);if(g){a=e('<a href="#">Undo</a>');e(".msg-default",d).next().append(a);a.click(function(){g();return false})}},success_inline_delete_undo:function(a){var d=e(".old-row",a);a.before(d);d.show().removeClass("old-row");
a.remove()},init_modal_form:function(a){e(document.body).append(a.form.hide());var d=a.event_prefix||"form.modal_form.";a.form.bind(d+"submit",function(){b.submit_modal_form(a)}).bind(d+"cancel",function(){b.cancel_modal_form(a)}).bind(d+"error",function(g,h){a.form.removeClass("loading");b.disable_submit(a);c.error(h,true)}).bind(d+"success",function(){a.form.removeClass("loading")}).bind(d+"valid",function(){b.enable_submit(a)}).bind(d+"invalid",function(){b.disable_submit(a)});b.init_submit_cancel(a);
a.form.data("overlay")&&a.form.removeData("overlay");a.form.overlay({close:".modal-buttons .cancel",closeOnClick:false,load:true,fixed:false,mask:{color:"#000",loadSpeed:200,opacity:0.5},onLoad:function(){a.overlay=this;a.init(a)}})},submit_modal_form:function(a){if(!a.form.is(".loading"))if(b.is_submit_enabled(a)){document.activeElement&&e(document.activeElement).blur();if(a.validate(a)){a.form.addClass("loading");a.submit(a,b.default_submit_ajax_options(a))}}},cancel_modal_form:function(a){a.form.data("overlay").close();
a.form.next("#exposeMask").hide()},init_submit_cancel:function(a){var d=a.form||a.edit_row,g=a.form||a.submit_row,h=a.event_prefix;a=e(".save",g).click(function(){d.trigger(h+"submit")});b.disable(a);e(".cancel",g).click(function(){d.trigger(h+"cancel")});e(":input",d).keyup(function(j){j.keyCode===27&&d.trigger(h+"cancel")})},disable:function(a){e(a).attr("disabled","disabled").addClass("disabled")},enable:function(a){e(a).removeAttr("disabled").removeClass("disabled")},disable_submit:function(a){b.disable(e(".save",
a.form||a.submit_row))},enable_submit:function(a){b.enable(e(".save",a.form||a.submit_row))},is_submit_enabled:function(a){return!e(".save",a.form||a.submit_row).is(":disabled")},init_mqlkey:function(a,d){return a.next(".key-status").removeClass("valid invalid loading").text("").removeAttr("title").end().mqlkey(d).bind("valid",function(){e(this).next(".key-status").removeClass("invalid loading").addClass("valid").text("valid").attr("title","Key is available")}).bind("invalid",function(g,h){e(this).next(".key-status").removeClass("valid loading").addClass("invalid").text("invalid").attr("title",
h)}).bind("textchange",function(){e(this).next(".key-status").removeClass("valid invalid").text("loading").addClass("loading")})},validate_mqlkey:function(a,d){var g=d.next(".key-status"),h=d.val();if(h===""){d.trigger(a.event_prefix+"error","Key is required");return false}if(h===d.data("mqlkey").original)return true;if(g.is(".invalid")){d.trigger(a.event_prefix+"error",g.attr("title"));return false}else if(g.is(".loading"))return false;return true},default_begin_ajax_options:function(){return e.extend(b._default_ajax_options("GET"),
{beforeSend:function(){c.doing("Loading...")},complete:function(){this.formlib_error||c.clear()}})},default_submit_ajax_options:function(a){a=a||{};var d=e.extend(b._default_ajax_options("POST"),a.ajax,{beforeSend:function(){this.formlib_options=a;c.doing("Saving...");e.isFunction(a.beforeSend)&&a.beforeSend.apply(this,arguments)},complete:function(){this.formlib_error||c.clear();e.isFunction(a.complete)&&a.complete.apply(this,arguments)}}),g=a.submit_row||a.form;g&&e("input[type=hidden]",g).each(function(){d.data[this.name]=
this.value});return d},_default_ajax_options:function(a){return{data:{},dataType:"json",type:a||"GET",success:function(d,g,h){if(!b.check_ajax_success(d,g,h))return this._error(h);e.isFunction(this.onsuccess)&&this.onsuccess(d,g,h)},error:function(d){return this._error(d)},_error:function(d){if(d.status===401){c.info("Authorizing...");e(window).trigger("fb.user.unauthorized")}else{console.error(d.responseText);this.formlib_error=true;var g=b.get_error_message(d.responseText);if(e.isFunction(this.onerror))this.onerror(g,
d);else{d=null;if(this.formlib_options)if(this.formlib_options.form){this.formlib_options.form.trigger(this.formlib_options.event_prefix+"cancel");d=this.formlib_options.form}else d=this.formlib_options.edit_row;d?d.trigger(this.formlib_options.event_prefix+"error",g):c.error(g,true)}}}}},check_ajax_success:function(a,d,g){return b.check_api_response(a,d,g)},check_api_response:function(a,d,g){if(e.isPlainObject(a)){if(a.code!=="/api/status/ok")return false}else if(g.status!==200)return false;return true},
get_error_message:function(a){var d=null;try{var g=JSON.parse(a);if(g&&e.isArray(g.messages)&&g.messages.length)d=g.messages[0].message}catch(h){}d||(d=a);return d}}})(jQuery,window.i18n,window.freebase.status);
(function(e){var f=window.editparams={Empty:function(c,b,a){this.structure=c;this.data=b;this.msg=a;this.toString=function(){return"Empty: "+this.msg}},Invalid:function(c,b,a){this.structure=c;this.data=b;this.msg=a;this.toString=function(){return"Invalid: "+this.msg}},parse:function(c,b){function a(i,k,l,m,p){try{f.validate(k,l);p.push(l)}catch(n){if(n instanceof f.Empty)p.push(l);else throw n;}}var d=(c.values||[]).slice(),g=c.properties||[],h=c.expected_type.mediator;if(h){if(!g.length)throw new f.Invalid(c,
null,"mediator musth have 1 or more properties");if(d.length&&d.length!==1)throw new f.Invalid(c,null,"Can't edit more than one value (row) for a mediator");}var j=[];e(".data-input",b).each(function(){var i=e(this),k=i.data("$.data_input");if(!k)throw new f.Invalid(c,null,"$.data-input not initialized for",this);k.validate(true);if(i.is(".error"))throw new f.Invalid(c,null,"$.data-input is invalid",this);k=i.data("data");if(!k)throw new f.Invalid(c,null,"$.data-input has no data",this);if(h){if(!j.length){j.push({property:{}});
e.each(g,function(p,n){j[0].property[n.id]=e.extend({},n,{values:[]})})}var l=j[0].property[k.name];if(l){var m=[];if(d.length)m=(m=d[0].property[l.id])&&m.values||[];a(i,l,k,m,l.values)}else console.warn("editparams","unknown mediator property data",k)}else a(i,c,k,d,j)});return h?f.parse_mediator(c,d,j):f.parse_simple(c,d,j)},parse_mediator:function(c,b,a){if(a.length!==1)throw new f.Invalid(c,a,"Must specify one (new or updated) value for a mediator");a=a[0];var d;if(b.length)d=b[0];b={};if(d)b.id=
d.id;else{b.id=null;b.create="unconditional";b.connect=c.unique?"replace":"insert";var g=[];c.expected_type.id!=="/type/object"&&g.push({id:c.expected_type.id,connect:"insert"});var h=c.expected_type.included_types;h&&e.each(h,function(p,n){n!=="/type/object"&&g.push({id:n,connect:"insert"})});if(g.length)b.type=g}h=false;c=c.properties;for(var j=0,i=c.length;j<i;j++){var k=c[j],l=d&&d.property&&d.property[k.id],m=a.property&&a.property[k.id];l=f.parse_simple(k,l&&l.values||[],m&&m.values||[]);if(l.length){b[k.id]=
l;h=true}}return h?[b]:[]},parse_simple:function(c,b,a){return f.diff(c,b,a)},diff:function(c,b,a){var d=c.expected_type,g=c.expected_type.id,h=c.unique,j=g==="/type/text",i=g==="/type/key";if(h)if(!j)if(b.length&&b.length!==1)throw new f.Invalid(c,b,"Can't edit more than one value (row) for a unique property.");else if(a.length&&a.length!==1)throw new f.Invalid(c,a,"Can't edit more than one value (row) for a unique property.");var k=[];if(f.LITERAL_TYPE_IDS[g]){k.push("value");if(j)k.push("lang");
else i&&k.push("namespace")}else k.push("id");g=[];var l=[],m,p;m=0;for(p=b.length;m<p;m++){var n=b[m];f.validate(c,n);f.inArray.apply(null,[n,a].concat(k))===-1&&g.push(f.clause(n,"delete"))}m=0;for(p=a.length;m<p;m++){n=a[m];try{f.validate(c,n)}catch(o){continue}if(f.inArray.apply(null,[n,b].concat(k))===-1){if(h)if(j){var q=f.inArray(n,g,"lang");q!==-1&&g.splice(q,1)}else if(!i)return[f.clause(n,"replace",d)];l.push(f.clause(n,h?"replace":"insert",d))}}return g.concat(l)},validate:function(c,b){var a=
c.expected_type.id;if(f.LITERAL_TYPE_IDS[a])if(f.isEmpty(b.value))throw new f.Empty(c,b);else{if(a==="/type/text"&&f.isEmpty(b.lang))throw new f.Invalid(c,b,"Expected data.lang for /type/text");else if(a==="/type/key"&&f.isEmpty(b.namespace))throw new f.Invalid(c,b,"Expected data.namespace for /type/key");if(a==="/type/int"||a==="/type/float"){if(e.type(b.value)!=="number")throw new f.Invalid(c,b,"Expected number data.value for "+a);}else if(a==="/type/boolean"){if(e.type(b.value)!=="boolean")throw new f.Invalid(c,
b,"Expected boolean data.value for /type/boolean");}else if(e.type(b.value)!=="string")throw new f.Invalid(c,b,"Expected string data.value for "+a);}else if(f.isEmpty(b.create_new)){if(f.isEmpty(b.id))throw new f.Empty(c,b);}else if(f.isEmpty(b.lang))throw new f.Invalid(c,b,"Expected lang for creating a new topic");return b},type_clause:function(c){var b=[];if(c){if(c.enumeration)return b;c.id!=="/type/object"&&b.push({id:c.id,connect:"insert"});(c=c.included_types)&&e.each(c,function(a,d){d!=="/type/object"&&
b.push({id:d,connect:"insert"})})}return b},clause:function(c,b,a){var d={connect:b};if(c.id){d.id=c.id;if(b!=="delete"&&a&&!a.enumeration){c=f.type_clause(a);if(c.length)d.type=c}}else if(c.create_new&&c.lang){d.name={value:c.create_new,lang:c.lang};d.id=null;d.create="unconditional";c=f.type_clause(a);if(c.length)d.type=c}else{d.value=c.value;if(c.lang)d.lang=c.lang;else if(c.namespace)d.namespace=c.namespace}return d},inArray:function(c,b){var a=Array.prototype.slice.call(arguments,2);if(!a.length)return e.inArray(c,
b);for(var d=0,g=b.length;d<g;d++){for(var h=b[d],j=true,i=0,k=a.length;i<k;i++){var l=a[i];if(h[l]!=c[l]){j=false;break}}if(j)return d}return-1},isEmpty:function(c){return c==null||c===""},LITERAL_TYPE_IDS:{"/type/int":1,"/type/float":1,"/type/boolean":1,"/type/rawstring":1,"/type/uri":1,"/type/text":1,"/type/datetime":1,"/type/id":1,"/type/key":1,"/type/value":1,"/type/enumeration":1}}})(jQuery);
(function(e,f,c,b){f.edit={text_edit_begin:function(a,d,g,h,j,i){var k={s:g,p:h,lang:j};e.ajax(e.extend(c.default_begin_ajax_options(),{url:d+"/text_edit_begin.ajax",data:k,onsuccess:function(l){l=e(l.result.html);var m={event_prefix:"i18n.edit.text_edit.",init:f.edit.text_edit_init,validate:f.edit.text_edit_validate,submit:f.edit.text_edit_submit,ajax:{url:d+"/text_edit_submit.ajax",data:k},form:l,add_input:e(".data-input:first",l).data_input(),add_lang:e(".lang-select",l),structure:l.metadata(),
base_url:d,trigger:a,reload:i};l.bind("i18n.edit.text_edit.cancel",function(){a.trigger("i18n.edit.text_edit.cancel")}).bind("i18n.edit.text_edit.error",function(p,n){a.trigger("i18n.edit.text_edit.error",n)});c.init_modal_form(m)}}))},text_edit_init:function(a){function d(h){e(".icon-link.delete",h).click(function(){a.form.trigger(g+"delete",h)});e(".data-input",h).data_input().bind("valid",function(){a.form.trigger(g+"valid")}).bind("empty",function(){a.form.trigger(g+"valid")}).bind("invalid",
function(){a.form.trigger(g+"invalid")}).bind("submit",function(){a.form.trigger(g+"submit")}).bind("cancel",function(){a.form.trigger(g+"cancel")}).metadata().lang===a.ajax.data.lang&&h.addClass("preferred")}var g=a.event_prefix;e(".values > tr",a.form).each(function(){d(e(this))});e(".icon-link.add",a.form).unbind().bind("mouseover, focus",function(){e(this).parent().addClass("focused")}).bind("mouseout, blur",function(){e(this).parent().removeClass("focused")}).click(function(){a.form.trigger(g+
"add")}).focusin(function(){e(this).addClass("focused")}).focusout(function(){e(this).removeClass("focused")});a.add_lang.unbind().focus(function(){e(this).parent().addClass("focused")}).blur(function(){e(this).parent().removeClass("focused")}).keypress(function(h){h.keyCode===13&&a.form.trigger(g+"add")});a.add_input.unbind().bind("submit",function(){a.form.trigger(g+"add")});a.form.bind(g+"add",function(){var h=a.add_input.data("data"),j=a.add_lang.val();if(h&&j){h=e.trim(h.value);if(h!==""){var i=
e("option[value="+j.replace(/\//g,"\\/")+"]",a.add_lang),k=i.text();h=f.edit.new_text_edit_row(h,j,k).hide();e("tbody.values",a.form).prepend(h);d(h);h.fadeIn(function(){a.add_input.data("$.data_input").reset();a.add_lang[0].selectedIndex=0;a.structure.unique&&i.attr("disabled","disabled");e(":text",a.add_input).focus()});a.form.trigger(g+"valid");j!==a.ajax.data.lang&&e(".lang-warning").css("visibility","visible").hide().fadeIn("slow")}}else console.error("Text value and language required")}).bind(g+
"delete",function(h,j){j=e(j);var i=e(".data-input:first",j).metadata().lang;j.fadeOut(function(){a.structure.unique&&e("option[value="+i.replace(/\//g,"\\/")+"]",a.add_lang).removeAttr("disabled");e(this).remove();a.form.trigger(g+"valid")})})},text_edit_validate:function(){return true},text_edit_submit:function(a,d){try{var g=b.parse(a.structure,e(".values",a.form))}catch(h){g=e(".data-input.error",a.form);if(g.length){a.form.trigger(a.event_prefix+"error","Please specify a valid value");g.eq(0).find(":input").focus().select()}else a.form.trigger(a.event_prefix+
"error",h.toString());return}d.data.o=JSON.stringify(g);g.length?e.ajax(e.extend(d,{onsuccess:function(){a.reload?window.location.reload(true):a.form.trigger(a.event_prefix+"cancel")}})):a.form.trigger(a.event_prefix+"cancel")},new_text_edit_row:function(a,d,g){var h=e('<tr class="new">  <th class="row-header" scope="row">    <span class="data-input text">      <input class="fb-input" type="text">    </span>  </th>  <td class="lang">    <span></span>  </td>  <td class="delete-row">    <a class="icon-link delete" href="javascript:void(0);"><span class="delete-icon">delete</span></a>  </td></tr>'),
j=e(".data-input",h);j.addClass(JSON.stringify({value:a,lang:d,type:"/type/text"}));e(".fb-input",j).val(a);e(".lang > span",h).text(g);return h}}})(jQuery,window.i18n,window.formlib,window.editparams);
