
/*
 * Copyright 2012, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Additional Licenses for Third Party components can be found here:
 * http://wiki.freebase.com/wiki/Freebase_Site_License
 *
 */
/*
 
 jQuery Tools @VERSION / Expose - Dim the lights

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/toolbox/expose.html

 Since: Mar 2010
 Date: @DATE 
 
 jQuery Tools @VERSION Overlay - Overlay base. Extend it.

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/overlay/

 Since: March 2008
 Date: @DATE 
*/
(function(d){var f=function(){return typeof window.innerWidth!="undefined"?function(){return{w:window.innerWidth,h:window.innerHeight}}:typeof document.documentElement!="undefined"&&typeof document.documentElement.clientWidth!="undefined"&&document.documentElement.clientWidth!=0?function(){return{w:document.documentElement.clientWidth,h:document.documentElement.clientHeight}}:function(){return{w:document.getElementsByTagName("body")[0].clientWidth,h:document.getElementsByTagName("body")[0].clientHeight}}}();
window.kbs=function(b){d(".kbs.current",b).removeClass("current");var a=d(".domain-section:first",b),c=d(".domain-section:last",b),e=this.scroll_to=function(h){var l=d(document).scrollTop();d(document).height();var o=f().h;o=l+o;var s=h.offset().top;h=s+h.height();if(s<l)d(document).scrollTop(s);else h>o&&d(document).scrollTop(l+(h-o))},g=this.get_current=function(){return d(".kbs.current:first",b)},i=this.set_next=function(h,l,o){h=h||g();if(l.length){h.removeClass("current");l.addClass("current");
o||e(l)}},j=this.next_domain=function(h){var l=g(),o=k(l);if(o){o=o.find(".kbs:first");i(l,o,h)}},k=this._next_domain=function(h){if(!(h&&h.length))return d(".domain-section:first",b);h=h.closest(".domain-section");return!h.length||h[0]===c[0]?a:h.next(".domain-section")},m=this.prev_domain=function(){var h=g(),l=p(h);if(l){l=l.find(".kbs:first");i(h,l)}},p=this._prev_domain=function(h){if(!(h&&h.length))return d(".domain-section:last",b);var l=h.closest(".domain-section");if(h.closest(".property-section").length||
h.closest(".type-section").length)return l;return!l.length||l[0]===a[0]?c:l.prev(".domain-section")},n=this.next_type=function(){var h=g(),l=t(h);if(l){l=l.find(".kbs:first");i(h,l)}},t=this._next_type=function(h){if(!(h&&h.length))return d(".type-section:first",b);var l=h.closest(".domain-section");h=h.closest(".type-section");h=h.length?h.next(".type-section"):l.find(".type-section:first");if(!(h&&h.length)){var o=k(l);if(o)for(;o.get(0)!==l.get(0);){h=o.find(".type-section:first");if(h.length)break;
o=k(o)}}return h},q=this.prev_type=function(){var h=g(),l=r(h);if(l){l=l.find(".kbs:first");i(h,l)}},r=this._prev_type=function(h){if(!(h&&h.length))return d(".type-section:last",b);var l=h.closest(".domain-section"),o=h.closest(".type-section");if(h.closest(".property-section").length)return o;var s;if(o.length)s=o.prev(".type-section");if(!(s&&s.length))if(h=p(l))for(;h.get(0)!==l.get(0);){s=h.find(".type-section:last");if(s.length)break;h=p(h)}return s},u=this.next_prop=function(){var h=g(),l=
v(h);if(l){l=l.find(".kbs:first");i(h,l)}},v=this._next_prop=function(h){if(!(h&&h.length))return d(".property-section:first",b);var l=h.closest(".domain-section"),o=h.closest(".type-section"),s=h.closest(".property-section");l=s.length?s.next(".property-section"):o.length?o.find(".property-section:first"):l.find(".property-section:first");if(!(l&&l.length))if(h=t(h))for(;h.get(0)!==o.get(0);){l=h.find(".property-section:first");if(l.length)break;if(o.get(0)==null)o=h;h=t(h)}return l},x=this.prev_prop=
function(){var h=g(),l=z(h);if(l){l=l.find(".kbs:first");i(h,l)}},z=this._prev_prop=function(h){if(!(h&&h.length))return d(".property-section:last",b);var l=h.closest(".domain-section"),o=h.closest(".type-section"),s=h.closest(".property-section");if(h.closest(".data-section").length)return s;var w;if(s.length)w=s.prev(".property-section");if(!(w&&w.length))if(q=o.length?r(o):r(l))for(;q.get(0)!==o.get(0);){w=q.find(".property-section:last");if(w.length)break;if(o.get(0)==null)o=q;q=r(q)}return w};
this.next=function(){var h=g(),l=this._next(h);l&&i(h,l)};this._next=function(h){if(!(h&&h.length))return d(".domain-section:first .kbs:first",b);var l=h.closest(".domain-section"),o=h.closest(".type-section"),s=h.closest(".property-section");if(h.closest(".data-section").length){h=h.next(".kbs");if(h.length)return h;h=s.next(".property-section").find(".kbs:first");if(h.length)return h;h=o.next(".type-section").find(".kbs:first")}else if(s.length){h=s.find(".data-section:first .kbs:first");if(h.length)return h;
h=s.next(".property-section").find(".kbs:first");if(h.length)return h;h=o.next(".type-section").find(".kbs:first")}else if(o.length){h=o.find(".property-section:first .kbs:first");if(h.length)return h;h=o.next(".type-section").find(".kbs:first")}else h=l.find(".type-section:first .kbs:first");if(h.length)return h;return l.get(0)===c.get(0)?a.find(".kbs:first"):l.next(".domain-section").find(".kbs:first")};this.prev=function(){var h=g(),l=this._prev(h);l&&i(h,l)};this._prev=function(h){if(!(h&&h.length)){h=
d(".data-section:last .kbs:last",b);h.length||(h=d(".property-section:last .kbs:first",b));h.length||(h=d(".type-section:last .kbs:first",b));h.length||(h=d(".domain-section:last .kbs:first",b));return h}var l=h.closest(".domain-section"),o=h.closest(".type-section"),s=h.closest(".property-section");if(h.closest(".data-section").length){h=h.prev(".kbs");if(h.length)return h;return s.find(".kbs:first")}else if(s.length){h=s.prev(".property-section").find(".kbs:last");if(h.length)return h;return o.find(".kbs:first")}else if(o.length){h=
o.prev(".type-section").find(".kbs:last");if(h.length)return h;return l.find(".kbs:first")}else return l.get(0)===a.get(0)?c.find(".kbs:last"):l.prev(".domain-section").find(".kbs:last")};this.edit=function(){this.get_current().trigger("edit")};var y=this;d(document).unbind(".kbs").bind("keydown.kbs",function(h){var l=h.target;if(l==document.body||l==document||l==window||l==d("html")[0]){l=h.keyCode;if(l===68)h.shiftKey?m():j();else if(l===84)h.shiftKey?q():n();else if(l===80)h.shiftKey?x():u();else if(l===
74)y.next();else if(l===75)y.prev();else l===69&&y.edit()}})}})(jQuery);
(function(d,f){var b=window.propbox={init:function(a,c){c=d.extend({lang:"/lang/en"},c);if(!c.base_ajax_url)throw new Error("base_ajax_url required in propbox options");if(!c.base_static_url)throw new Error("base_static_url required in propbox options");if(!c.id)throw new Error("topic id required in propbox options");if(!c.lang)throw new Error("lang required in propbox options");b.options=c;b.kbs=new f(a);b.kbs.set_next(b.kbs.get_current(),d(".kbs:visible:first",a,true));d(".kbs",a).live("click",
function(){var e=b.kbs.get_current();b.kbs.set_next(e,d(this),true)}).live("edit",function(){var e=d(this).find(".headmenu:first").data("submenu");e&&d("li:first a:first",e).click()});b.init_menus(a)},init_menus:function(a,c){a=d(a||document);c&&d(".nicemenu",a).nicemenu();(a&&a.is(".data-row")?a:d(".data-row",a)).hover(b.row_menu_hoverover,b.row_menu_hoverout);d(".nicemenu .headmenu",a).add(d(".nicemenu .default-action",a)).click("click",function(){if(b.kbs){var e=b.kbs.get_current();e&&b.kbs.set_next(e,
d(this).parents(".kbs:first"),true)}return false})},row_menu_hoverover:function(){var a=d(this);b.row_menu_hoverover.timeout=setTimeout(function(){a.addClass("row-hover")},300)},row_menu_hoverout:function(){clearTimeout(b.row_menu_hoverover.timeout);d(this).removeClass("row-hover")},get_script:function(a,c){var e=b.get_script.cache;if(!e)e=b.get_script.cache={};var g=e[a];if(g)if(g.state===1)g.callbacks.push(c);else g.state===4&&c();else{g=e[a]={state:0,callbacks:[c]};d.ajax({url:b.options.base_static_url+
a,dataType:"script",beforeSend:function(){g.state=1},success:function(){g.state=4;d.each(g.callbacks,function(i,j){j()})},error:function(){g.state=-1}})}},prop_edit:function(a,c){var e=d(a).parents(".submenu").data("headmenu").parents(".property-section").find(".data-section .data-row:first:visible .nicemenu:first .headmenu:first a");e.length?e.click():b.prop_add(a,c);return false},prop_add:function(a,c){var e=d(a).parents(".submenu").data("headmenu").parents(".property-section");b.get_script("/propbox-edit.mf.js",
function(){b.edit.prop_add_begin(e,c)});return false},value_edit:function(a){var c=d(a).parents(".submenu").data("headmenu").parents(".data-row:first"),e=c.parents(".property-section");b.get_script("/propbox-edit.mf.js",function(){b.edit.value_edit_begin(e,c)});return false},value_delete:function(a){var c=d(a).parents(".submenu").data("headmenu").parents(".data-row:first"),e=c.parents(".property-section");b.get_script("/propbox-edit.mf.js",function(){b.edit.value_delete_begin(e,c)});return false},
close_message:function(a){d(a).parents(".row-msg:first").remove();return false}}})(jQuery,window.kbs);
(function(d){function f(){if(d.browser.msie){var k=d(document).height(),m=d(window).height();return[window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth,k-m<20?m:k]}return[d(document).width(),d(document).height()]}function b(k){if(k)return k.call(d.mask)}d.tools=d.tools||{version:"@VERSION"};var a;a=d.tools.expose={conf:{maskId:"exposeMask",loadSpeed:"slow",closeSpeed:"fast",closeOnClick:true,closeOnEsc:true,zIndex:9998,opacity:0.8,startOpacity:0,color:"#fff",onLoad:null,
onClose:null}};var c,e,g,i,j;d.mask={load:function(k,m){if(g)return this;if(typeof k=="string")k={color:k};k=k||i;i=k=d.extend(d.extend({},a.conf),k);c=d("#"+k.maskId);if(!c.length){c=d("<div/>").attr("id",k.maskId);d("body").append(c)}var p=f();c.css({position:"absolute",top:0,left:0,width:p[0],height:p[1],display:"none",opacity:k.startOpacity,zIndex:k.zIndex});k.color&&c.css("backgroundColor",k.color);if(b(k.onBeforeLoad)===false)return this;k.closeOnEsc&&d(document).bind("keydown.mask",function(n){n.keyCode==
27&&d.mask.close(n)});k.closeOnClick&&c.bind("click.mask",function(n){d.mask.close(n)});d(window).bind("resize.mask",function(){d.mask.fit()});if(m&&m.length){j=m.eq(0).css("zIndex");d.each(m,function(){var n=d(this);/relative|absolute|fixed/i.test(n.css("position"))||n.css("position","relative")});e=m.css({zIndex:Math.max(k.zIndex+1,j=="auto"?0:j)})}c.css({display:"block"}).fadeTo(k.loadSpeed,k.opacity,function(){d.mask.fit();b(k.onLoad)});g=true;return this},close:function(){if(g){if(b(i.onBeforeClose)===
false)return this;c.fadeOut(i.closeSpeed,function(){b(i.onClose);e&&e.css({zIndex:j})});d(document).unbind("keydown.mask");c.unbind("click.mask");d(window).unbind("resize.mask");g=false}return this},fit:function(){if(g){var k=f();c.css({width:k[0],height:k[1]})}},getMask:function(){return c},isLoaded:function(){return g},getConf:function(){return i},getExposed:function(){return e}};d.fn.mask=function(k){d.mask.load(k);return this};d.fn.expose=function(k){d.mask.load(k,this);return this}})(jQuery);
(function(d){function f(c,e){var g=this,i=c.add(g),j=d(window),k,m,p,n=d.tools.expose&&(e.mask||e.expose),t=Math.random().toString().slice(10);if(n){if(typeof n=="string")n={color:n};n.closeOnClick=n.closeOnEsc=false}var q=e.target||c.attr("rel");m=q?d(q):c;if(!m.length)throw"Could not find Overlay: "+q;c&&c.index(m)==-1&&c.click(function(r){g.load(r);return r.preventDefault()});d.extend(g,{load:function(r){if(g.isOpened())return g;var u=a[e.effect];if(!u)throw'Overlay: cannot find effect : "'+e.effect+
'"';e.oneInstance&&d.each(b,function(){this.close(r)});r=r||d.Event();r.type="onBeforeLoad";i.trigger(r);if(r.isDefaultPrevented())return g;p=true;n&&d(m).expose(n);var v=e.top,x=e.left,z=m.outerWidth({margin:true}),y=m.outerHeight({margin:true});if(typeof v=="string")v=v=="center"?Math.max((j.height()-y)/2,0):parseInt(v,10)/100*j.height();if(x=="center")x=Math.max((j.width()-z)/2,0);u[0].call(g,{top:v,left:x},function(){if(p){r.type="onLoad";i.trigger(r)}});n&&e.closeOnClick&&d.mask.getMask().one("click",
g.close);e.closeOnClick&&d(document).bind("click."+t,function(h){d(h.target).parents(m).length||g.close(h)});e.closeOnEsc&&d(document).bind("keydown."+t,function(h){h.keyCode==27&&g.close(h)});return g},close:function(r){if(!g.isOpened())return g;r=r||d.Event();r.type="onBeforeClose";i.trigger(r);if(!r.isDefaultPrevented()){p=false;a[e.effect][1].call(g,function(){r.type="onClose";i.trigger(r)});d(document).unbind("click."+t).unbind("keydown."+t);n&&d.mask.close();return g}},getOverlay:function(){return m},
getTrigger:function(){return c},getClosers:function(){return k},isOpened:function(){return p},getConf:function(){return e}});d.each("onBeforeLoad,onStart,onLoad,onBeforeClose,onClose".split(","),function(r,u){d.isFunction(e[u])&&d(g).bind(u,e[u]);g[u]=function(v){d(g).bind(u,v);return g}});k=m.find(e.close||".close");if(!k.length&&!e.close){k=d('<a class="close"></a>');m.prepend(k)}k.click(function(r){g.close(r)});e.load&&g.load()}d.tools=d.tools||{version:"@VERSION"};d.tools.overlay={addEffect:function(c,
e,g){a[c]=[e,g]},conf:{close:null,closeOnClick:true,closeOnEsc:true,closeSpeed:"fast",effect:"default",fixed:!d.browser.msie||d.browser.version>6,left:"center",load:false,mask:null,oneInstance:true,speed:"normal",target:null,top:"10%"}};var b=[],a={};d.tools.overlay.addEffect("default",function(c,e){var g=this.getConf(),i=d(window);if(!g.fixed){c.top+=i.scrollTop();c.left+=i.scrollLeft()}c.position=g.fixed?"fixed":"absolute";this.getOverlay().css(c).fadeIn(g.speed,e)},function(c){this.getOverlay().fadeOut(this.getConf().closeSpeed,
c)});d.fn.overlay=function(c){var e=this.data("overlay");if(e)return e;if(d.isFunction(c))c={onBeforeLoad:c};c=d.extend(true,{},d.tools.overlay.conf,c);this.each(function(){e=new f(d(this),c);b.push(e);d(this).data("overlay",e)});return c.api?e:this}})(jQuery);
(function(d){d.fn.mqlkey=function(b){return this.each(function(){var a=d(this);if(a.is(":text")){var c=a.data("mqlkey");c&&c._destroy();c=new f(this,b);a.data("mqlkey",c)}})};var f=d.mqlkey=function(b,a){this.options=d.extend(true,{},f.defaults,a);this.input=d(b);this.original=this.input.val();this.init()};f.prototype={init:function(){var b=this;this.input.bind("keyup.mqlkey",function(a){b.textchange(a)}).bind(d.browser.msie?"paste.mqlkey":"input.mqlkey",function(a){b.textchange(a)});if(this.options.source){this.source=
d(this.options.source);this.source_generate=true;this.input.bind("change.mqlkey",function(){b.source_generate=false});this.source.bind("change.mqlkey",function(){if(b.source_generate){var a=f.from(b.source.val());b.input.val(a).trigger("keyup")}})}},_destroy:function(){this.input.unbind(".mqlkey");this.source&&this.source.unbind("change.mqlkey")},textchange:function(b){clearTimeout(this.textchange_timeout);var a=this;this.textchange_timeout=setTimeout(function(){a.textchange_delay(b)},200)},textchange_delay:function(){this.input.trigger("textchange");
var b=d.trim(this.input.val());return b===this.original&&b!==""?this.valid(b):f.reserved_word(b)?this.invalid(b,b+" is a reserved word."):f.test(b,this.options.schema)?b.length<this.options.minlen?this.invalid(b):this.options.check_key?this.check_key(b):this.valid(b):this.invalid(b)},check_key:function(b){var a=this;if(this.xhr)this.xhr=null;var c={id:null,key:{namespace:this.options.namespace,value:b}};clearTimeout(this.check_key.timeout);this.check_key.timeout=setTimeout(function(){a.xhr=a.options.mqlread(c,
function(e){return e?a.invalid(b,"Key already exists"):a.valid(b)},function(e){return e?a.invalid(e.responseText()):a.invalid("mqlread error!")})},200)},valid:function(b){this.input.trigger("valid",b)},invalid:function(b,a){if(!a){a=this.options.minlen>1?"Key must be "+this.options.minlen+" or more alphanumeric characters":"Key must be alphanumeric";a+=", lowercase, begin with a letter and not end with a non-alphanumeric character. Underscores are allowed but not consecutively."}this.input.trigger("invalid",
a)}};d.extend(f,{defaults:{minlen:1,check_key:true,namespace:"/",mqlread:function(b,a,c){return f.mqlread(null,b,a,c)},source:null,schema:false},mqlread:function(b,a,c,e){b={url:b||"http://api.freebase.com/api/service/mqlread",data:{query:JSON.stringify({query:a})},dataType:"jsonp",success:function(g){return c(g.result)},error:e};return d.ajax(b)},from:function(b){b=b.toLowerCase();b=b.replace(/[^a-z0-9]/g,"_");b=b.replace(/\_\_+/g,"_");b=b.replace(/[^a-z0-9]+$/,"");b=b.replace(/^[^a-z]+/,"");if(f.reserved_word(b))b=
"x_"+b;return b},reservedwords:"meta typeguid left right datatype scope attribute relationship property link class future update insert delete replace create destroy default sort limit offset optional pagesize cursor index !index for while as in is if else return count function read write select var connect this self super xml sql mql any all macro estimate-count",typeonlywords:"guid id object domain name key type keys value timestamp creator permission namespace unique schema reverse",_reserved_word:null,
reserved_word:function(b){if(!f._reserved_word){f._reserved_word={};d.each([f.reservedwords,f.typeonlywords],function(a,c){d.each(c.split(" "),function(e,g){f._reserved_word[g]=1})})}return f._reserved_word[b]===1},fast:/^[A-Za-z0-9](?:[_-]?[A-Za-z0-9])*$/,slow:/^(?:[A-Za-z0-9]|\$[A-F0-9]{4})(?:[_-]?[A-Za-z0-9]|[_-]?\$[A-F0-9]{4})*$/,schema:/^[a-z](?:_?[a-z0-9])*$/,test:function(b,a){if(a)return f.schema.test(b);return f.fast.test(b)||f.slow.test(b)}})})(jQuery);
(function(d){d.fn.validate_input=function(b){return this.each(function(){var a=d(this);if(a.is(":text")){var c=a.data("$.validate_input");c&&c._destroy();c=new f(this,b);a.data("$.validate_input",c)}})};var f=d.validate_input=function(b,a){if(typeof(this.options=d.extend(true,{},f.defaults,a)).validator!=="function")throw"A validator is required";this.input=d(b);this.init();var c=this;this.input.bind("remove",function(){c._destroy()});return this};f.prototype={init:function(){var b=this;this.input.bind("keyup.validate_input",
function(a){b.textchange(a)}).bind(d.browser.msie?"paste.validate_input":"input.validate_input",function(a){b.textchange(a)}).bind("keypress.validate_input",function(a){a.keyCode===13&&b.validate(true)}).bind("blur.validate_input",function(){b.validate(true)})},_destroy:function(){this.input.unbind(".validate_input")},valid:function(b){this.input.trigger("valid",b)},invalid:function(b,a){this.input.trigger("invalid",a)},empty:function(){this.input.trigger("empty")},textchange:function(){clearTimeout(this.textchange_timeout);
var b=this;this.textchange_timeout=setTimeout(function(){b.validate()},200)},validate:function(b){b&&clearTimeout(this.textchange_timeout);b=this.options;var a=d.trim(this.input.val());if(a==="")return this.empty();try{return this.valid(b.validator(a,b))}catch(c){return this.invalid(a,""+c)}}};d.extend(f,{defaults:{validator:function(b){return{text:b,value:b}}},log:function(){},invalid:function(b,a,c,e){throw new Error("Invalid "+c+(e?": "+e:""));},text:function(b,a){if(b.lengh>4096)return this.invalid(b,
a,type,"Text too long");return{text:b,value:b}},topic:function(){return f.defaults.validator},enumerated:function(){return f.defaults.validator},"boolean":function(){return f.defaults.validator},uri:function(b,a){var c=f.uri.regex;if(!c)c=f.uri.regex=/^(https?|ftp):\/\/(((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:)*@)?(((\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5]))|((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?)(:\d*)?)(\/((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)+(\/(([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)*)*)?)?(\?((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|[\uE000-\uF8FF]|\/|\?)*)?(\#((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|\/|\?)*)?$/i;
if(c.test(b))return{text:b,value:b};return f.invalid(b,a,"uri")},"int":function(b,a){return f.number.parse(b,a,false)},"float":function(b,a){return f.number.parse(b,a,true)},number:function(b,a,c){return f.number.parse(b,a,c)},datetime:function(b,a){return f.datetime.parse(b,a)},mqlkey:function(b,a){var c=f.mqlkey.regex;if(!c)c=f.mqlkey.regex=/^[A-Za-z0-9][A-Za-z0-9_-]*$/;if(c.test(b))return{text:b,value:b};return f.invalid(b,a,"mqlkey")}});d.extend(f.number,{parse:function(b,a,c){a=null;a=c?Globalize.parseFloat(b):
Globalize.parseInt(b);if(isNaN(a))throw f.invalid("number",b);if(c){b="n";c=""+a;var e=c.indexOf(".");if(e!==-1)b="n"+c.substr(e+1).length;return{value:a,text:Globalize.format(a,b)}}else return{value:a,text:Globalize.format(a,"n0")}}});d.extend(f.datetime,{regexp:{iso:/^(?:(-?\d{4})(?:-(\d{2})(?:-(\d{2}))?)?)?(?:T(\d{2}):(\d{2})(?::(\d{2})(.\d+)?)?((?:[+-](\d{2}):(\d{2}))|Z)?)?$/,time:/^T?([01][0-9]|2[0-3])(:[0-5][0-9]){0,2}$/,bce:[/^(\d+)\s*[Bb]\.*[Cc]\.*[Ee]*/,/^[Bb]\.*[Cc]\.*[Ee]*\s*(\d+)/]},formats:["d",
"yyyy-MM-dd","Y","yyyy-MM","t","HH:mm","T","HH:mm:ss"],padyear:function(b){if(b<10)return"000"+b;else if(b<100)return"00"+b;else if(b<1E3)return"0"+b;return""+b},parse:function(b){var a,c,e;if(f.datetime.regexp.iso.test(b)||f.datetime.regexp.time.test(b)){c=b;if(c.indexOf("T")===0)c=c.substring(1);return{text:b,value:c}}c=0;for(e=f.datetime.regexp.bce.length;c<e;c++)if(a=f.datetime.regexp.bce[c].exec(b)){c=parseInt(a[1],10);c-=1;c=f.datetime.padyear(c);return{text:b,value:"-"+c}}c=0;for(e=f.datetime.formats.length;c<
e;c+=2)if(a=Globalize.parseDate(b,f.datetime.formats[c]))return{text:b,value:Globalize.format(a,f.datetime.formats[c+1])};if(a=Globalize.parseDate(b))return{text:b,value:Globalize.format(a,"S")};throw f.invalid("datetime",b);}})})(jQuery,window.Globalize);
(function(d){d.fn.data_input=function(f){return this.each(function(){var b=d(this),a=b.data("$.data_input");a&&a._destroy();a=new d.data_input(this,f);b.data("$.data_input",a)})};d.data_input=function(f,b){this.options=d.extend(true,{},b);this.container=d(f);this.metadata=this.container.metadata();this.input=d(":input",this.container);this.init();var a=this;this.input.bind("remove",function(){a._destroy()})};d.data_input.prototype={init:function(){var f=this,b=this.container,a=this.input,c=this.options;
a.bind("focusin.data_input",function(){f.container.addClass("focus")}).bind("focusout.data_input",function(){f.container.removeClass("focus")}).bind("valid.data_input",function(g,i){g.stopPropagation();var j={name:f.input.attr("name")};if(i.id)j.id=i.id;else if(i.create_new){j.create_new=i.create_new;j.lang=f.metadata.lang||c.lang}else{j.value=i.value;if(f.metadata.type==="/type/text")j.lang=f.metadata.lang||c.lang;else if(f.metadata.type==="/type/key")j.namespace=i.namespace}if(i.incompatible_types)j.incompatible_types=
i.incompatible_types;f.container.data("data",j);f.container.removeClass("error").addClass("valid");f.container.trigger("valid")}).bind("invalid.data_input",function(g){g.stopPropagation();f.container.removeData("data");f.container.removeClass("valid").addClass("error");f.container.trigger("invalid")}).bind("empty.data_input",function(g){g.stopPropagation();g={name:f.input.attr("name")};if(f.metadata&&f.metadata.lang)g.lang=f.metadata.lang;f.container.data("data",g);f.container.removeClass("valid").removeClass("error");
f.container.trigger("empty")}).bind("keypress.data_input",function(g){g.keyCode===13&&!g.isDefaultPrevented()&&f.container.trigger("submit")}).bind("keyup.data_input",function(g){g.keyCode===27&&f.container.trigger("cancel")});if(b.is(".topic")){b=f.metadata.type;var e=null;if(c.suggest_impl)e=c.suggest_impl.instance(b,true,f.metadata&&f.metadata.lang||c.lang);a.validate_topic(d.extend({incompatible_types:f.options.incompatible_types,expected_type:b},e)).bind("valid.data_input",function(g,i){f.fb_select(i)}).bind("invalid.data_input",
function(){f.fb_textchange()});if(this.metadata&&this.metadata.id){a.data("data.suggest",this.metadata);this.validate()}}else if(b.is(".text"))a.validate_input({validator:d.validate_input.text});else if(b.is(".datetime"))a.validate_input({validator:d.validate_input.datetime,lang:c.lang});else if(b.is(".enumerated")){a.validate_enumerated().bind("valid.data_input",function(g,i){f.fb_select(i)}).bind("invalid.data_input",function(){f.fb_textchange()});this.metadata&&this.metadata.id&&this.validate()}else if(b.is(".int"))a.validate_input({validator:d.validate_input["int"],
lang:c.lang});else if(b.is(".float"))a.validate_input({validator:d.validate_input["float"],lang:c.lang});else if(b.is(".uri"))a.validate_input({validator:d.validate_input.uri});else if(b.is(".boolean"))a.validate_boolean();else if(b.is(".enumeration"))a.validate_input({validator:d.validate_input.mqlkey});else if(b.is(".key"))a.validate_key(c,this.metadata);else if(b.is(".rawstring"))a.validate_input({validator:d.validate_input.text});else throw new Error("Invalid data-input: "+b.attr("class"));},
_destroy:function(){this.input.unbind(".data_input")},validate:function(){var f=this.input;d.each(["$.validate_topic","$.validate_input","$.validate_enumerated","$.validate_boolean","$.validate_key"],function(b,a){var c=f.data(a);if(c){c.validate(true);return false}})},reset:function(){this.container.removeData("data");if(this.input.is(":text"))this.input.val("");else if(this.input.is("select"))this.input[0].selectedIndex=0;else this.input.is(":radio")&&this.input.each(function(){this.checked=false})},
fb_textchange:function(){},fb_select:function(){},ajax_beforeSend:function(f){if(!this.xhr_queue)this.xhr_queue=[];this.xhr_queue.push(f);this.container.trigger("loading")},ajax_complete:function(f){if(!this.xhr_queue)this.xhr_queue=[];for(var b=0,a=this.xhr_queue.length;b<a;b++)if(f===this.xhr_queue[b]){this.xhr_queue.splice(b,1);break}this.xhr_queue.length===0&&this.container.trigger("loading_complete")}};d.fn.validate_topic=function(f){return this.each(function(){var b=d(this);if(b.is(":text")){var a=
b.data("$.validate_topic");a&&a._destroy();a=new d.validate_topic(this,f);b.data("$.validate_topic",a)}})};d.validate_topic=function(f,b){this.options=d.extend(true,{},b);this.input=d(f);this.init()};d.validate_topic.prototype={init:function(){var f=this;this.incompatible_types={};this.input.suggest(this.options).bind("fb-textchange.validate_topic",function(){f.input.val()===""?f.empty():f.invalid()}).bind("fb-select.validate_topic",function(b,a){f.input.val(a.name!=null?a.name:a.id);f.incompatible_types_check(a)}).bind("fb-select-new.validate_topic",
function(b,a){f.valid(a)})},incompatible_types_check:function(f){var b=this;b.options.incompatible_types&&b.options.expected_type?b.options.incompatible_types.check(f.id,b.options.expected_type,{compatible:function(){b.valid(f)},incompatible:b.options.incompatible_types.inline_suggest_incompatible_callback(b.input,{onConfirm:function(a,c,e){b.incompatible_types[a]=e;b.valid(f)}})}):this.valid(f)},invalid:function(){this.input.trigger("invalid")},valid:function(f){if(typeof f==="string")f={create_new:f};
if(f.id&&this.incompatible_types[f.id])f.incompatible_types=this.incompatible_types[f.id];this.input.trigger("valid",f)},empty:function(){this.input.trigger("empty")},_destroy:function(){this.input.unbind(".validate_topic")},validate:function(){if(this.input.val()==="")this.empty();else{var f=this.input.data("data.suggest");f?this.valid(f):this.invalid()}}};d.fn.validate_enumerated=function(f){return this.each(function(){var b=d(this);if(b.is("select")){var a=b.data("$.validate_enumerated");a&&a._destroy();
a=new d.validate_enumerated(this,f);b.data("$.validate_enumerated",a)}})};d.validate_enumerated=function(f,b){this.options=d.extend(true,{},b);this.input=d(f);this.init()};d.validate_enumerated.prototype={init:function(){var f=this;this.input.bind("change.validate_enumerated, keypress.validate_enumerated",function(){this.selectedIndex===0?f.empty():f.valid({text:d(":selected",this).text(),id:this.value})})},invalid:function(){this.input.trigger("invalid")},valid:function(f){this.input.trigger("valid",
f);this.input.trigger("fb-select",f)},empty:function(){this.input.trigger("empty")},_destroy:function(){this.input.unbind(".validate_enumerated")},validate:function(){var f=this.input[0];f.selectedIndex>0?this.valid({text:d(":selected",this.input).text(),id:f.value}):this.empty()}};d.fn.validate_boolean=function(f){var b,a;this.each(function(){var e=d(this);if(e.is(":radio"))if(e.val().toLowerCase()==="true")b=e;else if(e.val().toLowerCase()==="false")a=e});if(b&&a){var c=b.data("$.validate_boolean");
c&&c._destroy();c=new d.validate_boolean(b,a,f);b.data("$.validate_boolean",c)}else throw"$.fn.validate_boolean requires two radios: true and false";return this};d.validate_boolean=function(f,b,a){this.options=d.extend(true,{},a);this.tradio=f;this.fradio=b;this.input=this.tradio;this.init()};d.validate_boolean.prototype={init:function(){var f=this;this.tradio.bind("change.validate_boolean",function(){f.validate()})},_destroy:function(){this.input.unbind(".validate_boolean")},valid:function(f){this.input.trigger("valid",
f)},empty:function(){this.input.trigger("empty")},validate:function(){if(this.tradio.is(":checked"))this.valid({text:this.tradio.text(),value:true});else this.fradio.is(":checked")?this.valid({text:this.fradio.text(),value:false}):this.empty()}};d.fn.validate_key=function(f,b){var a,c;this.each(function(){var g=d(this);if(g.is(":text"))if(g.is(".key-namespace"))a=g;else if(g.is(".key-value"))c=g});if(a&&c){var e=c.data("$.validate_key");e&&e._destroy();e=new d.validate_key(a,c,f);a.data("$.validate_key",
e);if(b&&b.namespace&&b.value){a.data("data.suggest",{id:b.namespace});c.val(b.value)}}else throw"$.fn.validate_key requires two inputs: namespace and value";return this};d.validate_key=function(f,b,a){this.options=d.extend(true,{},a);this.key_namespace_input=f;this.key_value_input=b;this.input=this.key_namespace_input;this.init()};d.validate_key.prototype={init:function(){var f=this,b=null;if(this.options.suggest_impl)b=this.key_value_input.attr("name")!="/type/namespace/keys"?this.options.suggest_impl.instance("/type/namespace"):
d.extend({},this.options.suggest_impl.service_defaults);this.key_namespace_input.suggest(b).bind("fb-textchange.validate_key",function(){f.validate()}).bind("fb-select.validate_key",function(a,c){f.key_namespace_input.val(c.name||c.id);f.validate()});this.key_value_input.validate_input({validator:d.validate_input.mqlkey}).bind("valid",function(a){a.stopPropagation();f.validate()}).bind("invalid",function(a){a.stopPropagation();f.validate()}).bind("empty",function(a){a.stopPropagation();f.validate()})},
_destroy:function(){this.key_namespace_input.unbind(".validate_key");this.key_value_input.unbind()},invalid:function(){this.input.trigger("invalid")},valid:function(f){this.input.trigger("valid",f)},empty:function(){this.input.trigger("empty")},validate:function(){if(this.is_valid_key_namespace()&&this.is_valid_key_value())this.valid({namespace:this.key_namespace_input.data("data.suggest").id,value:this.key_value_input.val(),text:this.key_value_input.val()});else this.key_namespace_input.val()===
""&&this.key_value_input.val()===""?this.empty():this.invalid()},is_valid_key_namespace:function(){return this.key_namespace_input.data("data.suggest")!=null},is_valid_key_value:function(){try{d.validate_input.mqlkey(this.key_value_input.val());return true}catch(f){return false}}}})(jQuery);
(function(d,f){var b=window.formlib={status:f,init:function(a){var c=a.event_prefix||"form.";a.form.bind(c+"submit",function(){b.submit(a)}).bind(c+"cancel",function(){b.cancel(a)}).bind(c+"error",function(e,g){a.form.removeClass("loading");b.disable_submit(a);f.error(g,true)}).bind(c+"success",function(){a.form.removeClass("loading")}).bind(c+"valid",function(){b.enable_submit(a)}).bind(c+"invalid",function(){b.disable_submit(a)});b.init_submit_cancel(a);a.init(a)},submit:function(a){if(!a.form.is(".loading"))if(b.is_submit_enabled(a)){document.activeElement&&
d(document.activeElement).blur();if(a.validate(a)){a.form.addClass("loading");a.submit(a,b.default_submit_ajax_options(a))}}},cancel:function(){},init_inline_add_form:function(a){var c=a.event_prefix||"form.inline_add_form.";a.edit_row.bind(c+"submit",function(){b.submit_inline_add_form(a)}).bind(c+"cancel",function(){b.cancel_inline_add_form(a)}).bind(c+"error",function(e,g){a.edit_row.removeClass("loading");b.disable_submit(a);f.error(g,true)}).bind(c+"success",function(){a.edit_row.removeClass("loading")}).bind(c+
"valid",function(){b.enable_submit(a)}).bind(c+"invalid",function(){b.disable_submit(a)});b.init_submit_cancel(a);a.trigger&&a.trigger.parents(".trigger-row:first").hide();a.body.append(a.edit_row).append(a.submit_row);a.init(a)},submit_inline_add_form:function(a){if(!a.edit_row.is(".loading"))if(b.is_submit_enabled(a)){document.activeElement&&d(document.activeElement).blur();if(a.validate(a)){a.edit_row.addClass("loading");a.submit(a,b.default_submit_ajax_options(a))}}},success_inline_add_form:function(a,
c){a.edit_row.before(c);a.reset(a);a.edit_row.trigger(a.event_prefix+"success")},cancel_inline_add_form:function(a){a.edit_row.remove();a.submit_row.remove();a.trigger&&a.trigger.parents(".trigger-row:first").show()},init_inline_edit_form:function(a){var c=a.event_prefix||"form.inline_edit_form.";a.edit_row.bind(c+"submit",function(){b.submit_inline_edit_form(a)}).bind(c+"cancel",function(){b.cancel_inline_edit_form(a)}).bind(c+"error",function(e,g){a.edit_row.removeClass("loading");b.disable_submit(a);
f.error(g,true)}).bind(c+"success",function(){a.edit_row.removeClass("loading")}).bind(c+"valid",function(){b.enable_submit(a)}).bind(c+"invalid",function(){b.disable_submit(a)});b.init_submit_cancel(a);a.row.hide();a.row.before(a.edit_row).before(a.submit_row);a.init(a)},submit_inline_edit_form:function(a){if(!a.edit_row.is(".loading"))if(b.is_submit_enabled(a)){document.activeElement&&d(document.activeElement).blur();if(a.validate(a)){a.edit_row.addClass("loading");a.submit(a,b.default_submit_ajax_options(a))}}},
success_inline_edit_form:function(a,c){a.row.replaceWith(c);a.row=c;a.edit_row.trigger(a.event_prefix+"cancel")},cancel_inline_edit_form:function(a){a.edit_row.remove();a.submit_row.remove();a.row.show()},success_inline_delete:function(a,c,e){a.hide().addClass("old-row");a.after(c);c.append(a);if(e){a=d('<a href="#">Undo</a>');d(".msg-default",c).next().append(a);a.click(function(){e();return false})}},success_inline_delete_undo:function(a){var c=d(".old-row",a);a.before(c);c.show().removeClass("old-row");
a.remove()},init_modal_form:function(a){d(document.body).append(a.form.hide());var c=a.event_prefix||"form.modal_form.";a.form.bind(c+"submit",function(){b.submit_modal_form(a)}).bind(c+"cancel",function(){b.cancel_modal_form(a)}).bind(c+"error",function(e,g){a.form.removeClass("loading");b.disable_submit(a);f.error(g,true)}).bind(c+"success",function(){a.form.removeClass("loading")}).bind(c+"valid",function(){b.enable_submit(a)}).bind(c+"invalid",function(){b.disable_submit(a)});b.init_submit_cancel(a);
a.form.data("overlay")&&a.form.removeData("overlay");a.form.overlay({close:".modal-buttons .cancel",closeOnClick:false,load:true,fixed:false,mask:{color:"#000",loadSpeed:200,opacity:0.5},onLoad:function(){a.overlay=this;a.init(a)}})},submit_modal_form:function(a){if(!a.form.is(".loading"))if(b.is_submit_enabled(a)){document.activeElement&&d(document.activeElement).blur();if(a.validate(a)){a.form.addClass("loading");a.submit(a,b.default_submit_ajax_options(a))}}},cancel_modal_form:function(a){a.form.data("overlay").close();
a.form.next("#exposeMask").hide()},init_submit_cancel:function(a){var c=a.form||a.edit_row,e=a.form||a.submit_row,g=a.event_prefix;a=d(".save",e).click(function(){c.trigger(g+"submit")});b.disable(a);d(".cancel",e).click(function(){c.trigger(g+"cancel")});d(":input",c).keyup(function(i){i.keyCode===27&&c.trigger(g+"cancel")})},disable:function(a){d(a).attr("disabled","disabled").addClass("disabled")},enable:function(a){d(a).removeAttr("disabled").removeClass("disabled")},disable_submit:function(a){b.disable(d(".save",
a.form||a.submit_row))},enable_submit:function(a){b.enable(d(".save",a.form||a.submit_row))},is_submit_enabled:function(a){return!d(".save",a.form||a.submit_row).is(":disabled")},init_mqlkey:function(a,c){return a.next(".key-status").removeClass("valid invalid loading").text("").removeAttr("title").end().mqlkey(c).bind("valid",function(){d(this).next(".key-status").removeClass("invalid loading").addClass("valid").text("valid").attr("title","Key is available")}).bind("invalid",function(e,g){d(this).next(".key-status").removeClass("valid loading").addClass("invalid").text("invalid").attr("title",
g)}).bind("textchange",function(){d(this).next(".key-status").removeClass("valid invalid").text("loading").addClass("loading")})},validate_mqlkey:function(a,c){var e=c.next(".key-status"),g=c.val();if(g===""){c.trigger(a.event_prefix+"error","Key is required");return false}if(g===c.data("mqlkey").original)return true;if(e.is(".invalid")){c.trigger(a.event_prefix+"error",e.attr("title"));return false}else if(e.is(".loading"))return false;return true},default_begin_ajax_options:function(){return d.extend(b._default_ajax_options("GET"),
{beforeSend:function(){f.doing("Loading...")},complete:function(){this.formlib_error||f.clear()}})},default_submit_ajax_options:function(a){a=a||{};var c=d.extend(b._default_ajax_options("POST"),a.ajax,{beforeSend:function(){this.formlib_options=a;f.doing("Saving...");d.isFunction(a.beforeSend)&&a.beforeSend.apply(this,arguments)},complete:function(){this.formlib_error||f.clear();d.isFunction(a.complete)&&a.complete.apply(this,arguments)}}),e=a.submit_row||a.form;e&&d("input[type=hidden]",e).each(function(){c.data[this.name]=
this.value});return c},_default_ajax_options:function(a){return{data:{},dataType:"json",type:a||"GET",success:function(c,e,g){if(!b.check_ajax_success(c,e,g))return this._error(g);d.isFunction(this.onsuccess)&&this.onsuccess(c,e,g)},error:function(c){return this._error(c)},_error:function(c){if(c.status===401){f.info("Authorizing...");d(window).trigger("fb.user.unauthorized")}else{console.error(c.responseText);this.formlib_error=true;var e=b.get_error_message(c.responseText);if(d.isFunction(this.onerror))this.onerror(e,
c);else{c=null;if(this.formlib_options)if(this.formlib_options.form){this.formlib_options.form.trigger(this.formlib_options.event_prefix+"cancel");c=this.formlib_options.form}else c=this.formlib_options.edit_row;c?c.trigger(this.formlib_options.event_prefix+"error",e):f.error(e,true)}}}}},check_ajax_success:function(a,c,e){return b.check_api_response(a,c,e)},check_api_response:function(a,c,e){if(d.isPlainObject(a)){if(a.code!=="/api/status/ok")return false}else if(e.status!==200)return false;return true},
get_error_message:function(a){var c=null;try{var e=JSON.parse(a);if(e&&d.isArray(e.messages)&&e.messages.length)c=e.messages[0].message}catch(g){}c||(c=a);return c}}})(jQuery,window.freebase.status);
(function(d){var f=window.editparams={Empty:function(b,a,c){this.structure=b;this.data=a;this.msg=c;this.toString=function(){return"Empty: "+this.msg}},Invalid:function(b,a,c){this.structure=b;this.data=a;this.msg=c;this.toString=function(){return"Invalid: "+this.msg}},parse:function(b,a){function c(k,m,p,n,t){try{f.validate(m,p);t.push(p)}catch(q){if(q instanceof f.Empty)t.push(p);else throw q;}}var e=(b.values||[]).slice(),g=b.properties||[],i=b.expected_type.mediator;if(i){if(!g.length)throw new f.Invalid(b,
null,"mediator musth have 1 or more properties");if(e.length&&e.length!==1)throw new f.Invalid(b,null,"Can't edit more than one value (row) for a mediator");}var j=[];d(".data-input",a).each(function(){var k=d(this),m=k.data("$.data_input");if(!m)throw new f.Invalid(b,null,"$.data-input not initialized for",this);m.validate(true);if(k.is(".error"))throw new f.Invalid(b,null,"$.data-input is invalid",this);m=k.data("data");if(!m)throw new f.Invalid(b,null,"$.data-input has no data",this);if(i){if(!j.length){j.push({property:{}});
d.each(g,function(t,q){j[0].property[q.id]=d.extend({},q,{values:[]})})}var p=j[0].property[m.name];if(p){var n=[];if(e.length)n=(n=e[0].property[p.id])&&n.values||[];c(k,p,m,n,p.values)}else console.warn("editparams","unknown mediator property data",m)}else c(k,b,m,e,j)});return i?f.parse_mediator(b,e,j):f.parse_simple(b,e,j)},parse_mediator:function(b,a,c){if(c.length!==1)throw new f.Invalid(b,c,"Must specify one (new or updated) value for a mediator");c=c[0];var e;if(a.length)e=a[0];a={};if(e)a.id=
e.id;else{a.id=null;a.create="unconditional";a.connect=b.unique?"replace":"insert";var g=[];b.expected_type.id!=="/type/object"&&g.push({id:b.expected_type.id,connect:"insert"});var i=b.expected_type.included_types;i&&d.each(i,function(t,q){q!=="/type/object"&&g.push({id:q,connect:"insert"})});if(g.length)a.type=g}i=false;b=b.properties;for(var j=0,k=b.length;j<k;j++){var m=b[j],p=e&&e.property&&e.property[m.id],n=c.property&&c.property[m.id];p=f.parse_simple(m,p&&p.values||[],n&&n.values||[]);if(p.length){a[m.id]=
p;i=true}}return i?[a]:[]},parse_simple:function(b,a,c){return f.diff(b,a,c)},diff:function(b,a,c){var e=b.expected_type,g=b.expected_type.id,i=b.unique,j=g==="/type/text",k=g==="/type/key";if(i)if(!j)if(a.length&&a.length!==1)throw new f.Invalid(b,a,"Can't edit more than one value (row) for a unique property.");else if(c.length&&c.length!==1)throw new f.Invalid(b,c,"Can't edit more than one value (row) for a unique property.");var m=[];if(f.LITERAL_TYPE_IDS[g]){m.push("value");if(j)m.push("lang");
else k&&m.push("namespace")}else m.push("id");g=[];var p=[],n,t;n=0;for(t=a.length;n<t;n++){var q=a[n];f.validate(b,q);f.inArray.apply(null,[q,c].concat(m))===-1&&g.push(f.clause(q,"delete"))}n=0;for(t=c.length;n<t;n++){q=c[n];try{f.validate(b,q)}catch(r){continue}if(f.inArray.apply(null,[q,a].concat(m))===-1){if(i)if(j){var u=f.inArray(q,g,"lang");u!==-1&&g.splice(u,1)}else if(!k)return[f.clause(q,"replace",e)];p.push(f.clause(q,i?"replace":"insert",e))}}return g.concat(p)},validate:function(b,a){var c=
b.expected_type.id;if(f.LITERAL_TYPE_IDS[c])if(f.isEmpty(a.value))throw new f.Empty(b,a);else{if(c==="/type/text"&&f.isEmpty(a.lang))throw new f.Invalid(b,a,"Expected data.lang for /type/text");else if(c==="/type/key"&&f.isEmpty(a.namespace))throw new f.Invalid(b,a,"Expected data.namespace for /type/key");if(c==="/type/int"||c==="/type/float"){if(d.type(a.value)!=="number")throw new f.Invalid(b,a,"Expected number data.value for "+c);}else if(c==="/type/boolean"){if(d.type(a.value)!=="boolean")throw new f.Invalid(b,
a,"Expected boolean data.value for /type/boolean");}else if(d.type(a.value)!=="string")throw new f.Invalid(b,a,"Expected string data.value for "+c);}else if(f.isEmpty(a.create_new)){if(f.isEmpty(a.id))throw new f.Empty(b,a);}else if(f.isEmpty(a.lang))throw new f.Invalid(b,a,"Expected lang for creating a new topic");return a},type_clause:function(b,a){a=a||{};var c=[];if(b){if(b.enumeration)return c;else if(b.never_assert)return c;b.id!=="/type/object"&&c.push({id:b.id,connect:"insert"});var e=b.included_types;
e&&d.each(e,function(g,i){i==="/type/object"||a[i]||c.push({id:i,connect:"insert"})})}return c},clause:function(b,a,c){var e={connect:a};if(b.id){e.id=b.id;if(a!=="delete"&&c&&!c.enumeration){b=f.type_clause(c,b.incompatible_types);if(b.length)e.type=b}}else if(b.create_new&&b.lang){e.name={value:b.create_new,lang:b.lang};e.id=null;e.create="unconditional";b=f.type_clause(c);if(b.length)e.type=b}else{e.value=b.value;if(b.lang)e.lang=b.lang;else if(b.namespace)e.namespace=b.namespace}return e},inArray:function(b,
a){var c=Array.prototype.slice.call(arguments,2);if(!c.length)return d.inArray(b,a);for(var e=0,g=a.length;e<g;e++){for(var i=a[e],j=true,k=0,m=c.length;k<m;k++){var p=c[k];if(i[p]!=b[p]){j=false;break}}if(j)return e}return-1},isEmpty:function(b){return b==null||b===""},LITERAL_TYPE_IDS:{"/type/int":1,"/type/float":1,"/type/boolean":1,"/type/rawstring":1,"/type/uri":1,"/type/text":1,"/type/datetime":1,"/type/id":1,"/type/key":1,"/type/value":1,"/type/enumeration":1}}})(jQuery);
(function(d,f,b,a){var c=f.edit={prop_add_begin:function(e){d.ajax(d.extend(b.default_begin_ajax_options(),{url:f.options.base_ajax_url+"/prop_add_begin.ajax",data:{s:f.options.id,p:e.attr("data-id"),lang:f.options.lang},onsuccess:function(g){g=d(g.result.html);var i=g.metadata(),j=i.expected_type.id;return j==="/common/document"?c.prop_add_document(e,g,i):j==="/common/image"?c.prop_add_image(e,g,i):c.prop_add(e,g,i)}}))},prop_add:function(e,g,i){e=d(">.data-section",e);e=d("> .data-table > tbody, > .data-list",
e);var j=d(".edit-row",g);g=d(".edit-row-submit",g);var k={event_prefix:"propbox.edit.prop_add.",init:c.init_prop_add_form,validate:c.validate_prop_add_form,submit:c.submit_prop_add_form,reset:c.reset_prop_add_form,ajax:{url:f.options.base_ajax_url+"/prop_edit_submit.ajax"},body:e,edit_row:j,submit_row:g,structure:i};j.bind("propbox.edit.prop_add.success",function(){i.unique&&j.trigger(k.event_prefix+"cancel")});b.init_inline_add_form(k)},init_prop_add_form:function(e){c.init_data_inputs(e);d(":input:visible:first",
e.edit_row).focus()},validate_prop_add_form:function(){return true},reset_prop_add_form:function(e){c.reset_data_inputs(e);b.disable_submit(e);d(".cancel",e.submit_row).text("Done");d(":input:visible:first",e.edit_row).focus()},submit_prop_add_form:function(e,g){try{var i=a.parse(e.structure,e.edit_row);g.data.o=JSON.stringify(i)}catch(j){i=d(".data-input.error",e.edit_row);if(i.length){e.edit_row.trigger(e.event_prefix+"error","Please specify a valid value");i.eq(0).find(":input").focus().select()}else e.edit_row.trigger(e.event_prefix+
"error",j.toString());return}i.length?d.ajax(d.extend(g,{onsuccess:function(k){k=d(k.result.html);b.success_inline_add_form(e,k);f.init_menus(k,true);d(".nicemenu-item.edit").show();f.kbs.set_next(null,k,true)}})):e.edit_row.trigger(e.event_prefix+"error","Please specify a valid value")},value_edit_begin:function(e,g){var i=null,j=null;if(g.is("tr"))i=g.attr("data-id");else{j=d(".property-value:first",g);i=j.attr("data-value")||j.attr("data-id")||j.attr("datetime");j=j.attr("data-namespace")}d.ajax(d.extend(b.default_begin_ajax_options(),
{url:f.options.base_ajax_url+"/value_edit_begin.ajax",data:{s:f.options.id,p:e.attr("data-id"),replace:i,namespace:j,lang:f.options.lang},onsuccess:function(k){k=d(k.result.html);var m=k.metadata(),p=m.expected_type.id;return p==="/common/document"?c.value_edit_document(e,g,k,m):p==="/common/image"?c.value_edit_image(e,g,k,m):c.value_edit(e,g,k,m)}}))},value_edit:function(e,g,i,j){var k=d(".edit-row",i);i=d(".edit-row-submit",i);j={event_prefix:"propbox.edit.value_edit.",init:c.init_value_edit_form,
validate:c.validate_value_edit_form,submit:c.submit_value_edit_form,ajax:{url:f.options.base_ajax_url+"/prop_edit_submit.ajax"},row:g,edit_row:k,submit_row:i,structure:j};k.bind("propbox.edit.value_edit.delete",function(){k.trigger("propbox.edit.value_edit.cancel");f.edit.value_delete_begin(e,g)});b.init_inline_edit_form(j)},init_value_edit_form:function(e){c.init_data_inputs(e);d(".delete",e.submit_row).click(function(){e.edit_row.trigger(e.event_prefix+"delete")});d(":input:visible:first",e.edit_row).focus()},
validate_value_edit_form:function(){return true},submit_value_edit_form:function(e,g){try{var i=a.parse(e.structure,e.edit_row);g.data.o=JSON.stringify(i)}catch(j){i=d(".data-input.error",e.edit_row);if(i.length){e.edit_row.trigger(e.event_prefix+"error","Please specify a valid value");i.eq(0).find(":input").focus().select()}else e.edit_row.trigger(e.event_prefix+"error",j.toString());return}d.ajax(d.extend(g,{onsuccess:function(k){k=d(k.result.html);b.success_inline_edit_form(e,k);f.init_menus(k,
true);d(".nicemenu-item.edit").show();f.kbs.set_next(null,k,true)}}))},value_delete_begin:function(e,g){var i=null,j=null;if(g.is("tr"))i=g.attr("data-id");else{j=d(".property-value:first",g);i=j.attr("data-value")||j.attr("data-id")||j.attr("datetime");j=j.attr("data-namespace")}var k={s:f.options.id,p:e.attr("data-id"),o:i,lang:f.options.lang,namespace:j};d.ajax(d.extend(b.default_submit_ajax_options(),{url:f.options.base_ajax_url+"/value_delete_submit.ajax",data:k,onsuccess:function(m){var p=d(m.result.html);
b.success_inline_delete(g,p,function(){d.ajax(d.extend(b.default_submit_ajax_options(),{url:f.options.base_ajax_url+"/value_delete_undo.ajax",data:k,onsuccess:function(){b.success_inline_delete_undo(p)}}))})}}))},prop_add_document:function(e,g,i){b.init_modal_form({event_prefix:"propbox.edit.prop_add_document.",init:c.init_prop_add_document_form,validate:c.validate_prop_add_document_form,submit:c.submit_prop_add_document_form,ajax:{url:f.options.base_ajax_url+"/prop_add_document_submit.ajax"},prop_section:e,
form:g,structure:i})},init_prop_add_document_form:function(e){var g=d("select[name=lang]",e.form);g.change(function(){var i=d(".lang-notice",e.form);if(this.value===f.options.lang)i.hide();else{d("strong",i).text(d("option:selected",g).text());i.show()}});d("textarea",e.form).bind("keypress",function(){e.form.trigger(e.event_prefix+"valid")}).bind("paste",function(){e.form.trigger(e.event_prefix+"valid")}).focus()},validate_prop_add_document_form:function(e){var g=d("textarea",e.form);if(d.trim(g.val())===
""){e.form.trigger(e.event_prefix+"invalid");g.focus();return false}return true},submit_prop_add_document_form:function(e,g){var i=d("textarea",e.form);g.data[i.attr("name")]=d.trim(i.val());g.data.lang=d("select[name=lang]",e.form).val();d.ajax(d.extend(g,{onsuccess:function(j){j=d(j.result.html);if(e.prop_row)e.prop_row.replaceWith(j);else{var k=d(">.data-section",e.prop_section);d("> .data-table > tbody, > .data-list",k).append(j)}f.init_menus(j,true);d(".nicemenu-item.edit").show();f.kbs.set_next(null,
j,true);e.form.trigger(e.event_prefix+"cancel")}}))},value_edit_document:function(e,g,i,j){g={event_prefix:"propbox.edit.value_edit_document.",init:c.init_value_edit_document_form,validate:c.validate_value_edit_document_form,submit:c.submit_value_edit_document_form,ajax:{url:f.options.base_ajax_url+"/prop_add_document_submit.ajax"},prop_section:e,prop_row:g,form:i,structure:j,cant_edit:i.is(".cant-edit-document-form")};g.cant_edit&&i.bind("propbox.edit.value_edit_document.submit",function(){i.trigger("propbox.edit.value_edit_document.cancel");
c.prop_add_begin(e)});b.init_modal_form(g)},init_value_edit_document_form:function(e){e.cant_edit?b.enable_submit(e):c.init_prop_add_document_form(e)},validate_value_edit_document_form:function(e){return e.cant_edit?true:c.validate_prop_add_document_form(e)},submit_value_edit_document_form:function(e,g){e.cant_edit||c.submit_prop_add_document_form(e,g)},prop_add_image:function(){alert("Add image not yet implemented")},value_edit_image:function(){alert("Edit image not yet implemented")},init_data_inputs:function(e){d(".data-input",
e.edit_row||e.form).each(function(){c.init_data_input(d(this),e)})},init_data_input:function(e,g){var i=g.edit_row||g.form;e.data_input({lang:f.options.lang,suggest_impl:f.options.suggest_impl,incompatible_types:f.options.incompatible_types}).bind("valid",function(){i.trigger(g.event_prefix+"valid");var j=e.parent(".form-field"),k=j.next(".magicbox-template");if(k.length){k=d("<div>").html(k.html());k=d(".form-field",k);j.after(k);c.init_data_input(d(".data-input",k),g)}}).bind("empty",function(){i.trigger(g.event_prefix+
"valid")}).bind("invalid",function(){i.trigger(g.event_prefix+"invalid")}).bind("submit",function(){i.trigger(g.event_prefix+"submit")}).bind("cancel",function(){i.trigger(g.event_prefix+"cancel")}).bind("loading",function(){d(this).addClass("loading")}).bind("loading_complete",function(){d(this).removeClass("loading")})},reset_data_inputs:function(e){d(".data-input",e.edit_row).each(function(){d(this).data("$.data_input").reset()})}}})(jQuery,window.propbox,window.formlib,window.editparams);
(function(d,f,b,a,c){function e(j){a.edit.init_data_inputs(j);if(!j.structure.expected_type.mediator){var k=d(".fb-input:first",j.form);if(k.attr("name")==="/type/object/name")j.name_input=k.parent(".data-input");else console.error("Expected /type/object/name as the first input")}d(":input:visible:first",j.form).focus()}function g(j){if(j.name_input)if(!j.name_input.data("data").value){j.form.trigger(j.event_prefix+"error","Name is required");return false}return true}function i(j,k){try{j.structure.expected_type.mediator=
true;var m=c.parse(j.structure,j.form);k.data.o=JSON.stringify(m)}catch(p){m=d(".data-input.error",j.form);if(m.length){j.form.trigger(j.event_prefix+"error","Please specify a valid value");m.eq(0).find(":input").focus().select()}else j.form.trigger(j.event_prefix+"error",p.toString());return}d.ajax(d.extend(k,{onsuccess:function(n){n=d(n.result.html);n=d(".property-value:first",n).attr("data-id");window.location.href=f.h.fb_url(n)}}))}d(function(){var j=d(".edit-form"),k=j.metadata(),m=d(".edit-row-submit",
j),p=d("input[name=s]",m).val();m=f.h.lang_id(d("input[name=lang]",m).val());a.init(j,{id:p,base_ajax_url:f.h.ajax_url("lib/propbox"),base_static_url:f.h.static_url("lib/propbox"),lang:m,suggest_impl:f.suggest_options,incompatible_types:f.incompatible_types});j={event_prefix:"create.type.instance.",init:e,validate:g,submit:i,ajax:{url:f.h.ajax_url("lib/propbox/prop_edit_submit.ajax")},form:j,structure:k};b.init(j)})})(jQuery,window.freebase,window.formlib,window.propbox,window.editparams);
