
/*
 * Copyright 2010, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Additional Licenses for Third Party components can be found here:
 * http://wiki.freebase.com/wiki/Freebase_Site_License
 *
 */
/*
 
 jQuery Tools @VERSION / Expose - Dim the lights

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/toolbox/expose.html

 Since: Mar 2010
 Date: @DATE 
 
 jQuery Tools @VERSION Overlay - Overlay base. Extend it.

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/overlay/

 Since: March 2008
 Date: @DATE 
*/
(function(b){function e(){if(b.browser.msie){var h=b(document).height(),k=b(window).height();return[window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth,h-k<20?k:h]}return[b(document).width(),b(document).height()]}function c(h){if(h)return h.call(b.mask)}b.tools=b.tools||{version:"@VERSION"};var a;a=b.tools.expose={conf:{maskId:"exposeMask",loadSpeed:"slow",closeSpeed:"fast",closeOnClick:true,closeOnEsc:true,zIndex:9998,opacity:0.8,startOpacity:0,color:"#fff",onLoad:null,
onClose:null}};var d,f,g,i,j;b.mask={load:function(h,k){if(g)return this;if(typeof h=="string")h={color:h};h=h||i;i=h=b.extend(b.extend({},a.conf),h);d=b("#"+h.maskId);if(!d.length){d=b("<div/>").attr("id",h.maskId);b("body").append(d)}var l=e();d.css({position:"absolute",top:0,left:0,width:l[0],height:l[1],display:"none",opacity:h.startOpacity,zIndex:h.zIndex});h.color&&d.css("backgroundColor",h.color);if(c(h.onBeforeLoad)===false)return this;h.closeOnEsc&&b(document).bind("keydown.mask",function(m){m.keyCode==
27&&b.mask.close(m)});h.closeOnClick&&d.bind("click.mask",function(m){b.mask.close(m)});b(window).bind("resize.mask",function(){b.mask.fit()});if(k&&k.length){j=k.eq(0).css("zIndex");b.each(k,function(){var m=b(this);/relative|absolute|fixed/i.test(m.css("position"))||m.css("position","relative")});f=k.css({zIndex:Math.max(h.zIndex+1,j=="auto"?0:j)})}d.css({display:"block"}).fadeTo(h.loadSpeed,h.opacity,function(){b.mask.fit();c(h.onLoad)});g=true;return this},close:function(){if(g){if(c(i.onBeforeClose)===
false)return this;d.fadeOut(i.closeSpeed,function(){c(i.onClose);f&&f.css({zIndex:j})});b(document).unbind("keydown.mask");d.unbind("click.mask");b(window).unbind("resize.mask");g=false}return this},fit:function(){if(g){var h=e();d.css({width:h[0],height:h[1]})}},getMask:function(){return d},isLoaded:function(){return g},getConf:function(){return i},getExposed:function(){return f}};b.fn.mask=function(h){b.mask.load(h);return this};b.fn.expose=function(h){b.mask.load(h,this);return this}})(jQuery);
(function(b){function e(d,f){var g=this,i=d.add(g),j=b(window),h,k,l,m=b.tools.expose&&(f.mask||f.expose),o=Math.random().toString().slice(10);if(m){if(typeof m=="string")m={color:m};m.closeOnClick=m.closeOnEsc=false}var p=f.target||d.attr("rel");k=p?b(p):d;if(!k.length)throw"Could not find Overlay: "+p;d&&d.index(k)==-1&&d.click(function(n){g.load(n);return n.preventDefault()});b.extend(g,{load:function(n){if(g.isOpened())return g;var r=a[f.effect];if(!r)throw'Overlay: cannot find effect : "'+f.effect+
'"';f.oneInstance&&b.each(c,function(){this.close(n)});n=n||b.Event();n.type="onBeforeLoad";i.trigger(n);if(n.isDefaultPrevented())return g;l=true;m&&b(k).expose(m);var q=f.top,t=f.left,u=k.outerWidth({margin:true}),v=k.outerHeight({margin:true});if(typeof q=="string")q=q=="center"?Math.max((j.height()-v)/2,0):parseInt(q,10)/100*j.height();if(t=="center")t=Math.max((j.width()-u)/2,0);r[0].call(g,{top:q,left:t},function(){if(l){n.type="onLoad";i.trigger(n)}});m&&f.closeOnClick&&b.mask.getMask().one("click",
g.close);f.closeOnClick&&b(document).bind("click."+o,function(s){b(s.target).parents(k).length||g.close(s)});f.closeOnEsc&&b(document).bind("keydown."+o,function(s){s.keyCode==27&&g.close(s)});return g},close:function(n){if(!g.isOpened())return g;n=n||b.Event();n.type="onBeforeClose";i.trigger(n);if(!n.isDefaultPrevented()){l=false;a[f.effect][1].call(g,function(){n.type="onClose";i.trigger(n)});b(document).unbind("click."+o).unbind("keydown."+o);m&&b.mask.close();return g}},getOverlay:function(){return k},
getTrigger:function(){return d},getClosers:function(){return h},isOpened:function(){return l},getConf:function(){return f}});b.each("onBeforeLoad,onStart,onLoad,onBeforeClose,onClose".split(","),function(n,r){b.isFunction(f[r])&&b(g).bind(r,f[r]);g[r]=function(q){b(g).bind(r,q);return g}});h=k.find(f.close||".close");if(!h.length&&!f.close){h=b('<a class="close"></a>');k.prepend(h)}h.click(function(n){g.close(n)});f.load&&g.load()}b.tools=b.tools||{version:"@VERSION"};b.tools.overlay={addEffect:function(d,
f,g){a[d]=[f,g]},conf:{close:null,closeOnClick:true,closeOnEsc:true,closeSpeed:"fast",effect:"default",fixed:!b.browser.msie||b.browser.version>6,left:"center",load:false,mask:null,oneInstance:true,speed:"normal",target:null,top:"10%"}};var c=[],a={};b.tools.overlay.addEffect("default",function(d,f){var g=this.getConf(),i=b(window);if(!g.fixed){d.top+=i.scrollTop();d.left+=i.scrollLeft()}d.position=g.fixed?"fixed":"absolute";this.getOverlay().css(d).fadeIn(g.speed,f)},function(d){this.getOverlay().fadeOut(this.getConf().closeSpeed,
d)});b.fn.overlay=function(d){var f=this.data("overlay");if(f)return f;if(b.isFunction(d))d={onBeforeLoad:d};d=b.extend(true,{},b.tools.overlay.conf,d);this.each(function(){f=new e(b(this),d);c.push(f);b(this).data("overlay",f)});return d.api?f:this}})(jQuery);
(function(b,e){e.require("dojo.date.stamp");e.require("dojo.date.locale");e.require("dojo.number");b.fn.validate_input=function(a){return this.each(function(){var d=b(this);if(d.is(":text")){var f=d.data("$.validate_input");f&&f._destroy();f=new c(this,a);d.data("$.validate_input",f)}})};var c=b.validate_input=function(a,d){var f=this.options=b.extend(true,{},c.defaults,d);if(typeof f.validator!=="function")throw"A validator is required";if(!f.lang)f.lang="/lang/en";f.lang=f.lang==="/lang/en"?["lang/en"]:
[f.lang,"/lang/en"];f.locales=[];b.each(f.lang,function(i,j){f.locales[i]=e.i18n.normalizeLocale(j.split("/").pop())});this.input=b(a);this.init();var g=this;this.input.bind("remove",function(){g._destroy()});return this};c.prototype={init:function(){var a=this;this.input.bind("keyup.validate_input",function(d){a.textchange(d)}).bind(b.browser.msie?"paste.validate_input":"input.validate_input",function(d){a.textchange(d)}).bind("keypress.validate_input",function(d){d.keyCode===13&&a.validate(true)}).bind("blur.validate_input",
function(){a.validate(true)})},_destroy:function(){this.input.unbind(".validate_input")},valid:function(a){this.input.trigger("valid",a)},invalid:function(a,d){this.input.trigger("invalid",d)},empty:function(){this.input.trigger("empty")},textchange:function(){clearTimeout(this.textchange_timeout);var a=this;this.textchange_timeout=setTimeout(function(){a.validate()},200)},validate:function(a){a&&clearTimeout(this.textchange_timeout);a=this.options;var d=b.trim(this.input.val());if(d==="")return this.empty();
try{return this.valid(a.validator(d,a))}catch(f){return this.invalid(d,""+f)}}};b.extend(c,{defaults:{validator:function(a){return{text:a,value:a}}},log:function(){},invalid:function(a,d,f,g){throw new Error("Invalid "+f+(g?": "+g:""));},text:function(a,d){if(a.lengh>4096)return this.invalid(a,d,type,"Text too long");return{text:a,value:a}},topic:function(){return c.defaults.validator},enumerated:function(){return c.defaults.validator},"boolean":function(){return c.defaults.validator},uri:function(a,
d){var f=c.uri.regex;if(!f)f=c.uri.regex=/^(https?|ftp):\/\/(((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:)*@)?(((\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5]))|((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?)(:\d*)?)(\/((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)+(\/(([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)*)*)?)?(\?((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|[\uE000-\uF8FF]|\/|\?)*)?(\#((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|\/|\?)*)?$/i;
if(f.test(a))return{text:a,value:a};return c.invalid(a,d,"uri")},"int":function(a,d){return c.number.parse(a,d,false)},"float":function(a,d){return c.number.parse(a,d,true)},number:function(a,d,f){return c.number.parse(a,d,f)},datetime:function(a,d){return c.datetime.parse(a,d)},mqlkey:function(a,d){var f=c.mqlkey.regex;if(!f)f=c.mqlkey.regex=/^[A-Za-z0-9][A-Za-z0-9_-]*$/;if(f.test(a))return{text:a,value:a};return c.invalid(a,d,"mqlkey")}});b.extend(c.number,{parse:function(a,d,f){var g=d&&d.locales||
["en"],i,j;i=0;for(j=g.length;i<j;i++){var h=g[i];d=e.number.parse(a,{locale:h});if(!isNaN(d)){a={};if(f){a.value=d;a.text=e.number.format(d,{locale:h})}else{a.value=e.number.round(d,0);a.text=e.number.format(a.value,{locale:h})}return a}}throw c.invalid("number",a);}});b.extend(c.datetime,{formats:["yyyy",["dateFormatItem-y"],"yyyy-MM",["dateFormatItem-yM","dateFormatItem-yMMM"],"yyyy-MM-dd",["dateFormat-short","dateFormat-medium","dateFormat-long"]],parse:function(a,d){if(!e.date.stamp._isoRegExp)e.date.stamp._isoRegExp=
/^(?:(-?\d{4})(?:-(\d{2})(?:-(\d{2}))?)?)?(?:T(\d{2}):(\d{2})(?::(\d{2})(.\d+)?)?((?:[+-](\d{2}):(\d{2}))|Z)?)?$/;var f=e.date.stamp.fromISOString(a);if(f)return{text:a,value:a,date:f};var g=d&&d.locales||["en"],i,j,h,k,l,m;i=0;for(j=g.length;i<j;i++){var o=g[i],p=e.date.locale._getGregorianBundle(o);h=0;for(k=c.datetime.formats.length;h<k;h+=2){var n=c.datetime.formats[h],r=c.datetime.formats[h+1];l=0;for(m=r.length;l<m;l++){var q=p[r[l]];if(q){q=i18n.normalize_pattern(q);try{f=e.date.locale.parse(a,
{datePattern:q,selector:"date",locale:o});return{text:a,value:e.date.locale.format(f,{datePattern:n,selector:"date"}),date:f}}catch(t){}}}}}throw c.invalid("datetime",a);}})})(jQuery,dojo);
(function(b){b.fn.data_input=function(e){return this.each(function(){var c=b(this),a=c.data("$.data_input");a&&a._destroy();a=new b.data_input(this,e);c.data("$.data_input",a)})};b.data_input=function(e,c){this.options=b.extend(true,{},b.data_input.defaults,c);this.container=b(e);this.metadata=this.container.metadata();this.input=b(":input",this.container);this.init();var a=this;this.input.bind("remove",function(){a._destroy()})};b.data_input.prototype={init:function(){var e=this,c=this.container,
a=this.input,d=this.options;a.bind("focusin.data_input",function(){e.container.addClass("focus")}).bind("focusout.data_input",function(){e.container.removeClass("focus")}).bind("valid.data_input",function(g,i){var j={name:e.input.attr("name")};if(i.id)j.id=i.id;else{j.value=i.value;if(e.metadata.type==="/type/text")j.lang=e.metadata.lang||d.lang}e.container.data("data",j);e.container.removeClass("error").addClass("valid");e.container.trigger("valid")}).bind("invalid.data_input",function(){e.container.removeData("data");
e.container.removeClass("valid").addClass("error");e.container.trigger("invalid")}).bind("empty.data_input",function(){var g={name:e.input.attr("name")};if(e.metadata&&e.metadata.lang)g.lang=e.metadata.lang;e.container.data("data",g);e.container.removeClass("valid").removeClass("error");e.container.trigger("empty")}).bind("keypress.data_input",function(g){g.keyCode===13&&!g.isDefaultPrevented()&&e.container.trigger("submit")}).bind("keyup.data_input",function(g){g.keyCode===27&&e.container.trigger("cancel")});
if(c.is(".topic")){c=e.metadata.type;var f=b.extend(true,{},d.suggest);f.type=c;if(c.indexOf("/type/")===0||c.indexOf("/common/")===0&&c!=="/common/topic"||c.indexOf("/freebase/")===0&&c.indexOf("_profile")===c.length-8){f.type_strict="any";f.filter="(any type:"+c+")"}else{f.type_strict="should";f.category="object";f.filter="(any without:fus),(should type:"+c+")"}a.validate_topic(f).bind("valid.data_input",function(g,i){e.fb_select(i)}).bind("invalid.data_input",function(){e.fb_textchange()});if(this.metadata&&
this.metadata.id){a.data("data.suggest",this.metadata);this.validate()}}else if(c.is(".text"))a.validate_input({validator:b.validate_input.text});else if(c.is(".datetime"))a.validate_input({validator:b.validate_input.datetime,lang:d.lang});else if(c.is(".enumerated")){a.validate_enumerated().bind("valid.data_input",function(g,i){e.fb_select(i)}).bind("invalid.data_input",function(){e.fb_textchange()});this.metadata&&this.metadata.id&&this.validate()}else if(c.is(".int"))a.validate_input({validator:b.validate_input["int"],
lang:d.lang});else if(c.is(".float"))a.validate_input({validator:b.validate_input["float"],lang:d.lang});else if(c.is(".uri"))a.validate_input({validator:b.validate_input.uri});else if(c.is(".boolean"))a.validate_boolean();else if(c.is(".enumeration"))a.validate_input({validator:b.validate_input.mqlkey});else if(c.is(".rawstring"))a.validate_input({validator:b.validate_input.text});else throw new Error("Invalid data-input: "+c.attr("class"));},_destroy:function(){this.input.unbind(".data_input")},
validate:function(){var e=this.input;b.each(["$.validate_topic","$.validate_input","$.validate_enumerated","$.validate_boolean"],function(c,a){var d=e.data(a);if(d){d.validate(true);return false}})},reset:function(){this.container.removeData("data");if(this.input.is(":text"))this.input.val("");else if(this.input.is("select"))this.input[0].selectedIndex=0;else this.input.is(":radio")&&this.input.each(function(){this.checked=false})},fb_textchange:function(){},fb_select:function(){},ajax_beforeSend:function(e){if(!this.xhr_queue)this.xhr_queue=
[];this.xhr_queue.push(e);this.container.trigger("loading")},ajax_complete:function(e){if(!this.xhr_queue)this.xhr_queue=[];for(var c=0,a=this.xhr_queue.length;c<a;c++)if(e===this.xhr_queue[c]){this.xhr_queue.splice(c,1);break}this.xhr_queue.length===0&&this.container.trigger("loading_complete")}};b.extend(b.data_input,{defaults:{suggest:{service_url:"http://www.freebase.com",service_path:"/private/suggest",flyout_service_url:"http://www.freebase.com",flyout_service_path:"/private/flyout",mqlread_url:"http://api.freebase.com/api/service/mqlread",
category:"object",type:"/common/topic"}}});b.fn.validate_topic=function(e){return this.each(function(){var c=b(this);if(c.is(":text")){var a=c.data("$.validate_topic");a&&a._destroy();a=new b.validate_topic(this,e);c.data("$.validate_topic",a)}})};b.validate_topic=function(e,c){this.options=b.extend(true,{},c);this.input=b(e);this.init()};b.validate_topic.prototype={init:function(){var e=this;this.input.suggest(this.options).bind("fb-textchange.validate_topic",function(){e.input.val()===""?e.empty():
e.invalid()}).bind("fb-select.validate_topic",function(c,a){e.input.val(a.name!=null?a.name:a.id);e.valid(a)})},invalid:function(){this.input.trigger("invalid")},valid:function(e){this.input.trigger("valid",e)},empty:function(){this.input.trigger("empty")},_destroy:function(){this.input.unbind(".validate_topic")},validate:function(){if(this.input.val()==="")this.empty();else{var e=this.input.data("data.suggest");e?this.valid(e):this.invalid()}}};b.fn.validate_enumerated=function(e){return this.each(function(){var c=
b(this);if(c.is("select")){var a=c.data("$.validate_enumerated");a&&a._destroy();a=new b.validate_enumerated(this,e);c.data("$.validate_enumerated",a)}})};b.validate_enumerated=function(e,c){this.options=b.extend(true,{},c);this.input=b(e);this.init()};b.validate_enumerated.prototype={init:function(){var e=this;this.input.bind("change.validate_enumerated, keypress.validate_enumerated",function(){this.selectedIndex===0?e.empty():e.valid({text:b(":selected",this).text(),id:this.value})})},invalid:function(){this.input.trigger("invalid")},
valid:function(e){this.input.trigger("valid",e);this.input.trigger("fb-select",e)},empty:function(){this.input.trigger("empty")},_destroy:function(){this.input.unbind(".validate_enumerated")},validate:function(){var e=this.input[0];e.selectedIndex>0?this.valid({text:b(":selected",this.input).text(),id:e.value}):this.empty()}};b.fn.validate_boolean=function(e){var c,a;this.each(function(){var f=b(this);if(f.is(":radio"))if(f.val().toLowerCase()==="true")c=f;else if(f.val().toLowerCase()==="false")a=
f});if(c&&a){var d=c.data("$.validate_boolean");d&&d._destroy();d=new b.validate_boolean(c,a,e);c.data("$.validate_boolean",d)}return this};b.validate_boolean=function(e,c,a){this.options=b.extend(true,{},a);this.tradio=e;this.fradio=c;this.input=this.tradio;this.init()};b.validate_boolean.prototype={init:function(){var e=this;this.tradio.bind("change.validate_boolean",function(){e.validate()})},_destroy:function(){this.input.unbind(".validate_boolean")},valid:function(e){this.input.trigger("valid",
e)},empty:function(){this.input.trigger("empty")},validate:function(){if(this.tradio.is(":checked"))this.valid({text:this.tradio.text(),value:true});else this.fradio.is(":checked")?this.valid({text:this.fradio.text(),value:false}):this.empty()}}})(jQuery);
(function(b){var e=window.editparams={Empty:function(c,a,d){this.structure=c;this.data=a;this.msg=d;this.toString=function(){return"Empty: "+this.msg}},Invalid:function(c,a,d){this.structure=c;this.data=a;this.msg=d;this.toString=function(){return"Invalid: "+this.msg}},parse:function(c,a){function d(h,k,l,m,o){try{e.validate(k,l);o.push(l)}catch(p){if(p instanceof e.Empty)o.push(l);else throw p;}}var f=(c.values||[]).slice(),g=c.properties||[],i=c.expected_type.mediator;if(i){if(!g.length)throw new e.Invalid(c,
null,"mediator musth have 1 or more properties");if(f.length&&f.length!==1)throw new e.Invalid(c,null,"Can't edit more than one value (row) for a mediator");}var j=[];b(".data-input",a).each(function(){var h=b(this),k=h.data("$.data_input");if(!k)throw new e.Invalid(c,null,"$.data-input not initialized for",this);k.validate(true);if(h.is(".error"))throw new e.Invalid(c,null,"$.data-input is invalid",this);k=h.data("data");if(!k)throw new e.Invalid(c,null,"$.data-input has no data",this);if(i){if(!j.length){j.push({});
b.each(g,function(o,p){j[0][p.id]=b.extend({},p,{values:[]})})}var l=j[0][k.name];if(l){var m=[];if(f.length)m=(m=f[0][l.id])&&m.values||[];d(h,l,k,m,l.values)}else console.warn("editparams","unknown mediator property data",k)}else d(h,c,k,f,j)});return i?e.parse_mediator(c,f,j):e.parse_simple(c,f,j)},parse_mediator:function(c,a,d){if(d.length!==1)throw new e.Invalid(c,d,"Must specify one (new or updated) value for a mediator");d=d[0];var f;if(a.length)f=a[0];a={};if(f)a.id=f.id;else{a.id=null;a.create=
"unconditional";a.connect=c.unique?"replace":"insert";var g=[];c.expected_type.id!=="/type/object"&&g.push({id:c.expected_type.id,connect:"insert"});var i=c.expected_type.included_types;i&&i.forEach(function(m){m!=="/type/object"&&g.push({id:m,connect:"insert"})});if(g.length)a.type=g}i=false;c=c.properties;for(var j=0,h=c.length;j<h;j++){var k=c[j],l=e.parse_simple(k,f&&f[k.id]&&f[k.id].values||[],d[k.id]&&d[k.id].values||[]);if(l.length){a[k.id]=l;i=true}}return i?[a]:[]},parse_simple:function(c,
a,d){return e.diff(c,a,d)},diff:function(c,a,d){var f=c.expected_type,g=c.expected_type.id,i=c.unique,j=g==="/type/text";if(i)if(!j)if(a.length&&a.length!==1)throw new e.Invalid(c,a,"Can't edit more than one value (row) for a unique property.");else if(d.length&&d.length!==1)throw new e.Invalid(c,d,"Can't edit more than one value (row) for a unique property.");var h=[];if(e.LITERAL_TYPE_IDS[g]){h.push("value");j&&h.push("lang")}else h.push("id");g=[];var k=[],l,m;l=0;for(m=a.length;l<m;l++){var o=
a[l];e.validate(c,o);e.inArray.apply(null,[o,d].concat(h))===-1&&g.push(e.clause(o,"delete"))}l=0;for(m=d.length;l<m;l++){o=d[l];try{e.validate(c,o)}catch(p){continue}if(e.inArray.apply(null,[o,a].concat(h))===-1){if(i)if(j){var n=e.inArray(o,g,"lang");n!==-1&&g.splice(n,1)}else return[e.clause(o,"replace",f)];k.push(e.clause(o,i?"replace":"insert",f))}}return g.concat(k)},validate:function(c,a){var d=c.expected_type.id;if(e.LITERAL_TYPE_IDS[d])if(e.isEmpty(a.value))throw new e.Empty(c,a);else{if(d===
"/type/text"&&e.isEmpty(a.lang))throw new e.Invalid(c,a,"Expected data.lang for /type/text");if(d==="/type/int"||d==="/type/float"){if(b.type(a.value)!=="number")throw new e.Invalid(c,a,"Expected number data.value for "+d);}else if(d==="/type/boolean"){if(b.type(a.value)!=="boolean")throw new e.Invalid(c,a,"Expected boolean data.value for /type/boolean");}else if(b.type(a.value)!=="string")throw new e.Invalid(c,a,"Expected string data.value for "+d);}else if(e.isEmpty(a.id))throw new e.Empty(c,a);
return a},clause:function(c,a,d){var f={connect:a};if(c.id){f.id=c.id;if(a!=="delete"&&d&&!d.enumeration){var g=[];d.id!=="/type/object"&&g.push({id:d.id,connect:"insert"});(c=d.included_types)&&c.forEach(function(i){i!=="/type/object"&&g.push({id:i,connect:"insert"})});if(g.length)f.type=g}}else{f.value=c.value;if(c.lang)f.lang=c.lang}return f},inArray:function(c,a){var d=Array.prototype.slice.call(arguments,2);if(!d.length)return b.inArray(c,a);for(var f=0,g=a.length;f<g;f++){for(var i=a[f],j=true,
h=0,k=d.length;h<k;h++){var l=d[h];if(i[l]!=c[l]){j=false;break}}if(j)return f}return-1},isEmpty:function(c){return c==null||c===""},LITERAL_TYPE_IDS:{"/type/int":1,"/type/float":1,"/type/boolean":1,"/type/rawstring":1,"/type/uri":1,"/type/text":1,"/type/datetime":1,"/type/id":1,"/type/key":1,"/type/value":1,"/type/enumeration":1}}})(jQuery);
(function(b,e,c){e.edit={text_edit_begin:function(a,d,f,g){var i={s:d,p:f,lang:g};b.ajax({url:a+"/text_edit_begin.ajax",data:i,dataType:"json",success:function(j){j=b(j.result.html);j={form:j,ajax:{base_url:a,data:b.extend({},i),url:a+"/text_edit_submit.ajax"},add_input:b(".data-input:first",j).data_input(),add_lang:b(".lang-select",j),structure:j.metadata()};e.edit.text_edit_init(j)},error:function(j){console.error("text_edit_begin",j)}})},text_edit_init:function(a){function d(h){b(".icon-link.delete",
h).click(function(){a.form.trigger(i+"delete",h)});b(".data-input",h).data_input().bind("submit",function(){a.form.trigger(i+"submit")}).bind("valid",function(){j.removeAttr("disabled").removeClass("disabled")}).bind("empty",function(){j.removeAttr("disabled").removeClass("disabled")}).metadata().lang===a.ajax.data.lang&&h.addClass("preferred")}b(document.body).append(a.form.hide());var f=b(".lang-select"),g=b(".lang-select-container");f.focus(function(){g.addClass("focused")}).blur(function(){g.removeClass("focused")});
a.form.overlay({close:".modal-buttons .button-cancel",closeOnClick:false,load:true,mask:{color:"#000",loadSpeed:200,opacity:0.5},onLoad:function(){b(":text:first",a.form).focus()}});var i="i18n.edit.text_edit.",j=b(".button-submit",a.form).click(function(){a.form.trigger(i+"submit")});b(".values > tr",a.form).each(function(){d(b(this))});f=b(".icon-link.add",a.form).bind("mouseover, focus",function(){b(this).parent().addClass("focused")}).bind("mouseout, blur",function(){b(this).parent().removeClass("focused")});
f.click(function(){a.form.trigger(i+"add")});f.focusin(function(){b(this).addClass("focused")}).focusout(function(){});a.add_lang.keypress(function(h){h.keyCode===13&&a.form.trigger(i+"add")});a.add_input.bind("submit",function(){a.form.trigger(i+"add")});a.form.bind(i+"add",function(){var h=a.add_input.data("data"),k=a.add_lang.val();if(h&&k){h=b.trim(h.value);if(h!==""){var l=b("option[value="+k.replace(/\//g,"\\/")+"]",a.add_lang),m=l.text();h=e.edit.new_text_edit_row(h,k,m).hide();b("tbody.values").prepend(h);
d(h);h.fadeIn(function(){a.add_input.data("$.data_input").reset();a.add_lang[0].selectedIndex=0;a.structure.unique&&l.attr("disabled","disabled");b(":text",a.add_input).focus()});j.removeAttr("disabled").removeClass("disabled");k!==a.ajax.data.lang&&b(".lang-warning").css("visibility","visible").hide().fadeIn("slow")}}else console.error("Text value and language required")}).bind(i+"submit",function(){e.edit.text_edit_submit(a)}).bind(i+"delete",function(h,k){k=b(k);var l=b(".data-input:first",k).metadata().lang;
k.fadeOut(function(){a.structure.unique&&b("option[value="+l.replace(/\//g,"\\/")+"]",a.add_lang).removeAttr("disabled");b(this).remove();j.removeAttr("disabled").removeClass("disabled")})})},text_edit_submit:function(a){if(!a.form.is(".loading")){var d=b(".button-submit",a.form);if(!d.is(":disabled")){document.activeElement&&b(document.activeElement).blur();var f=c.parse(a.structure,b(".values",a.form));if(f.length){a.form.addClass("loading");b.ajax({url:a.ajax.url,type:"POST",dataType:"json",data:b.extend(a.ajax.data,
{o:JSON.stringify(f)}),success:function(g,i,j){if(g.code!=="/api/status/ok")return console.error("text_edit_submt",j);window.location.reload(true)},error:function(g){console.error("text_edit_submt",g)}})}else d.attr("disabled","disabled").addClass("disabled")}}},new_text_edit_row:function(a,d,f){var g=b('<tr class="new">  <th class="row-header" scope="row">    <span class="data-input text">      <input class="fb-input" type="text">    </span>  </th>  <td class="lang">    <span></span>  </td>  <td class="delete-row">    <a class="icon-link delete" href="javascript:void(0);"><span class="delete-icon">delete</span></a>  </td></tr>'),
i=b(".data-input",g);i.addClass(JSON.stringify({value:a,lang:d,type:"/type/text"}));b(".fb-input",i).val(a);b(".lang > span",g).text(f);return g}}})(jQuery,window.i18n,window.editparams);
