
/*
 * Copyright 2012, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Additional Licenses for Third Party components can be found here:
 * http://wiki.freebase.com/wiki/Freebase_Site_License
 *
 */
/*
 
 jQuery Tools @VERSION / Expose - Dim the lights

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/toolbox/expose.html

 Since: Mar 2010
 Date: @DATE 
 
 jQuery Tools @VERSION Overlay - Overlay base. Extend it.

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/overlay/

 Since: March 2008
 Date: @DATE 
*/
(function(d){function c(){if(d.browser.msie){var a=d(document).height(),b=d(window).height();return[window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth,20>a-b?b:a]}return[d(document).width(),d(document).height()]}function b(a){if(a)return a.call(d.mask)}d.tools=d.tools||{version:"@VERSION"};var a;a=d.tools.expose={conf:{maskId:"exposeMask",loadSpeed:"slow",closeSpeed:"fast",closeOnClick:!0,closeOnEsc:!0,zIndex:9998,opacity:0.8,startOpacity:0,color:"#fff",onLoad:null,
onClose:null}};var e,f,g,m,o;d.mask={load:function(l,q){if(g)return this;"string"==typeof l&&(l={color:l});l=l||m;m=l=d.extend(d.extend({},a.conf),l);e=d("#"+l.maskId);e.length||(e=d("<div/>").attr("id",l.maskId),d("body").append(e));var r=c();e.css({position:"absolute",top:0,left:0,width:r[0],height:r[1],display:"none",opacity:l.startOpacity,zIndex:l.zIndex});l.color&&e.css("backgroundColor",l.color);if(!1===b(l.onBeforeLoad))return this;l.closeOnEsc&&d(document).bind("keydown.mask",function(a){a.keyCode==
27&&d.mask.close(a)});l.closeOnClick&&e.bind("click.mask",function(a){d.mask.close(a)});d(window).bind("resize.mask",function(){d.mask.fit()});q&&q.length&&(o=q.eq(0).css("zIndex"),d.each(q,function(){var a=d(this);/relative|absolute|fixed/i.test(a.css("position"))||a.css("position","relative")}),f=q.css({zIndex:Math.max(l.zIndex+1,"auto"==o?0:o)}));e.css({display:"block"}).fadeTo(l.loadSpeed,l.opacity,function(){d.mask.fit();b(l.onLoad)});g=!0;return this},close:function(){if(g){if(!1===b(m.onBeforeClose))return this;
e.fadeOut(m.closeSpeed,function(){b(m.onClose);f&&f.css({zIndex:o})});d(document).unbind("keydown.mask");e.unbind("click.mask");d(window).unbind("resize.mask");g=!1}return this},fit:function(){if(g){var a=c();e.css({width:a[0],height:a[1]})}},getMask:function(){return e},isLoaded:function(){return g},getConf:function(){return m},getExposed:function(){return f}};d.fn.mask=function(a){d.mask.load(a);return this};d.fn.expose=function(a){d.mask.load(a,this);return this}})(jQuery);
(function(d){function c(e,c){var g=this,m=e.add(g),o=d(window),l,q,r,i=d.tools.expose&&(c.mask||c.expose),y=Math.random().toString().slice(10);i&&("string"==typeof i&&(i={color:i}),i.closeOnClick=i.closeOnEsc=!1);var s=c.target||e.attr("rel");q=s?d(s):e;if(!q.length)throw"Could not find Overlay: "+s;e&&-1==e.index(q)&&e.click(function(a){g.load(a);return a.preventDefault()});d.extend(g,{load:function(e){if(g.isOpened())return g;var s=a[c.effect];if(!s)throw'Overlay: cannot find effect : "'+c.effect+
'"';c.oneInstance&&d.each(b,function(){this.close(e)});e=e||d.Event();e.type="onBeforeLoad";m.trigger(e);if(e.isDefaultPrevented())return g;r=true;i&&d(q).expose(i);var l=c.top,x=c.left,v=q.outerWidth({margin:true}),n=q.outerHeight({margin:true});typeof l=="string"&&(l=l=="center"?Math.max((o.height()-n)/2,0):parseInt(l,10)/100*o.height());x=="center"&&(x=Math.max((o.width()-v)/2,0));s[0].call(g,{top:l,left:x},function(){if(r){e.type="onLoad";m.trigger(e)}});if(i&&c.closeOnClick)d.mask.getMask().one("click",
g.close);c.closeOnClick&&d(document).bind("click."+y,function(a){d(a.target).parents(q).length||g.close(a)});c.closeOnEsc&&d(document).bind("keydown."+y,function(a){a.keyCode==27&&g.close(a)});return g},close:function(b){if(!g.isOpened())return g;b=b||d.Event();b.type="onBeforeClose";m.trigger(b);if(!b.isDefaultPrevented()){r=false;a[c.effect][1].call(g,function(){b.type="onClose";m.trigger(b)});d(document).unbind("click."+y).unbind("keydown."+y);i&&d.mask.close();return g}},getOverlay:function(){return q},
getTrigger:function(){return e},getClosers:function(){return l},isOpened:function(){return r},getConf:function(){return c}});d.each(["onBeforeLoad","onStart","onLoad","onBeforeClose","onClose"],function(a,i){d.isFunction(c[i])&&d(g).bind(i,c[i]);g[i]=function(a){d(g).bind(i,a);return g}});l=q.find(c.close||".close");!l.length&&!c.close&&(l=d('<a class="close"></a>'),q.prepend(l));l.click(function(a){g.close(a)});c.load&&g.load()}d.tools=d.tools||{version:"@VERSION"};d.tools.overlay={addEffect:function(b,
c,d){a[b]=[c,d]},conf:{close:null,closeOnClick:!0,closeOnEsc:!0,closeSpeed:"fast",effect:"default",fixed:!d.browser.msie||6<d.browser.version,left:"center",load:!1,mask:null,oneInstance:!0,speed:"normal",target:null,top:"10%"}};var b=[],a={};d.tools.overlay.addEffect("default",function(a,b){var c=this.getConf(),m=d(window);c.fixed||(a.top+=m.scrollTop(),a.left+=m.scrollLeft());a.position=c.fixed?"fixed":"absolute";this.getOverlay().css(a).fadeIn(c.speed,b)},function(a){this.getOverlay().fadeOut(this.getConf().closeSpeed,
a)});d.fn.overlay=function(a){var f=this.data("overlay");if(f)return f;d.isFunction(a)&&(a={onBeforeLoad:a});a=d.extend(!0,{},d.tools.overlay.conf,a);this.each(function(){f=new c(d(this),a);b.push(f);d(this).data("overlay",f)});return a.api?f:this}})(jQuery);
jQuery.effects||function(d,c){function b(a){var i;return a&&a.constructor==Array&&3==a.length?a:(i=/rgb\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*\)/.exec(a))?[parseInt(i[1],10),parseInt(i[2],10),parseInt(i[3],10)]:(i=/rgb\(\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*\)/.exec(a))?[2.55*parseFloat(i[1]),2.55*parseFloat(i[2]),2.55*parseFloat(i[3])]:(i=/#([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})/.exec(a))?[parseInt(i[1],16),parseInt(i[2],
16),parseInt(i[3],16)]:(i=/#([a-fA-F0-9])([a-fA-F0-9])([a-fA-F0-9])/.exec(a))?[parseInt(i[1]+i[1],16),parseInt(i[2]+i[2],16),parseInt(i[3]+i[3],16)]:/rgba\(0, 0, 0, 0\)/.exec(a)?o.transparent:o[d.trim(a).toLowerCase()]}function a(){var a=document.defaultView?document.defaultView.getComputedStyle(this,null):this.currentStyle,i={},b,c;if(a&&a.length&&a[0]&&a[a[0]])for(var d=a.length;d--;)b=a[d],"string"==typeof a[b]&&(c=b.replace(/\-(\w)/g,function(a,i){return i.toUpperCase()}),i[c]=a[b]);else for(b in a)"string"===
typeof a[b]&&(i[b]=a[b]);return i}function e(a){var i,b;for(i in a)b=a[i],(null==b||d.isFunction(b)||i in q||/scrollbar/.test(i)||!/color/i.test(i)&&isNaN(parseFloat(b)))&&delete a[i];return a}function f(a,i){var b={_:0},c;for(c in i)a[c]!=i[c]&&(b[c]=i[c]);return b}function g(a,i,b,c){"object"==typeof a&&(c=i,b=null,i=a,a=i.effect);d.isFunction(i)&&(c=i,b=null,i={});if("number"==typeof i||d.fx.speeds[i])c=b,b=i,i={};d.isFunction(b)&&(c=b,b=null);i=i||{};b=b||i.duration;b=d.fx.off?0:"number"==typeof b?
b:b in d.fx.speeds?d.fx.speeds[b]:d.fx.speeds._default;c=c||i.complete;return[a,i,b,c]}function m(a){return!a||("number"===typeof a||d.fx.speeds[a])||"string"===typeof a&&!d.effects[a]?!0:!1}d.effects={};d.each("backgroundColor borderBottomColor borderLeftColor borderRightColor borderTopColor borderColor color outlineColor".split(" "),function(a,i){d.fx.step[i]=function(a){if(!a.colorInit){var c;c=a.elem;var e=i,r;do{r=d.curCSS(c,e);if(r!=""&&r!="transparent"||d.nodeName(c,"body"))break;e="backgroundColor"}while(c=
c.parentNode);c=b(r);a.start=c;a.end=b(a.end);a.colorInit=true}a.elem.style[i]="rgb("+Math.max(Math.min(parseInt(a.pos*(a.end[0]-a.start[0])+a.start[0],10),255),0)+","+Math.max(Math.min(parseInt(a.pos*(a.end[1]-a.start[1])+a.start[1],10),255),0)+","+Math.max(Math.min(parseInt(a.pos*(a.end[2]-a.start[2])+a.start[2],10),255),0)+")"}});var o={aqua:[0,255,255],azure:[240,255,255],beige:[245,245,220],black:[0,0,0],blue:[0,0,255],brown:[165,42,42],cyan:[0,255,255],darkblue:[0,0,139],darkcyan:[0,139,139],
darkgrey:[169,169,169],darkgreen:[0,100,0],darkkhaki:[189,183,107],darkmagenta:[139,0,139],darkolivegreen:[85,107,47],darkorange:[255,140,0],darkorchid:[153,50,204],darkred:[139,0,0],darksalmon:[233,150,122],darkviolet:[148,0,211],fuchsia:[255,0,255],gold:[255,215,0],green:[0,128,0],indigo:[75,0,130],khaki:[240,230,140],lightblue:[173,216,230],lightcyan:[224,255,255],lightgreen:[144,238,144],lightgrey:[211,211,211],lightpink:[255,182,193],lightyellow:[255,255,224],lime:[0,255,0],magenta:[255,0,255],
maroon:[128,0,0],navy:[0,0,128],olive:[128,128,0],orange:[255,165,0],pink:[255,192,203],purple:[128,0,128],violet:[128,0,128],red:[255,0,0],silver:[192,192,192],white:[255,255,255],yellow:[255,255,0],transparent:[255,255,255]},l=["add","remove","toggle"],q={border:1,borderBottom:1,borderColor:1,borderLeft:1,borderRight:1,borderTop:1,borderWidth:1,margin:1,padding:1};d.effects.animateClass=function(b,i,c,s){d.isFunction(c)&&(s=c,c=null);return this.queue("fx",function(){var t=d(this),g=t.attr("style")||
" ",m=e(a.call(this)),o,v=t.attr("className");d.each(l,function(a,i){if(b[i])t[i+"Class"](b[i])});o=e(a.call(this));t.attr("className",v);t.animate(f(m,o),i,c,function(){d.each(l,function(a,i){if(b[i])t[i+"Class"](b[i])});if(typeof t.attr("style")=="object"){t.attr("style").cssText="";t.attr("style").cssText=g}else t.attr("style",g);s&&s.apply(this,arguments)});m=d.queue(this);o=m.splice(m.length-1,1)[0];m.splice(1,0,o);d.dequeue(this)})};d.fn.extend({_addClass:d.fn.addClass,addClass:function(a,i,
b,c){return i?d.effects.animateClass.apply(this,[{add:a},i,b,c]):this._addClass(a)},_removeClass:d.fn.removeClass,removeClass:function(a,i,b,c){return i?d.effects.animateClass.apply(this,[{remove:a},i,b,c]):this._removeClass(a)},_toggleClass:d.fn.toggleClass,toggleClass:function(a,i,b,e,t){return"boolean"==typeof i||i===c?b?d.effects.animateClass.apply(this,[i?{add:a}:{remove:a},b,e,t]):this._toggleClass(a,i):d.effects.animateClass.apply(this,[{toggle:a},i,b,e])},switchClass:function(a,i,b,c,e){return d.effects.animateClass.apply(this,
[{add:i,remove:a},b,c,e])}});d.extend(d.effects,{version:"1.8.10",save:function(a,i){for(var b=0;b<i.length;b++)null!==i[b]&&a.data("ec.storage."+i[b],a[0].style[i[b]])},restore:function(a,b){for(var c=0;c<b.length;c++)null!==b[c]&&a.css(b[c],a.data("ec.storage."+b[c]))},setMode:function(a,b){"toggle"==b&&(b=a.is(":hidden")?"show":"hide");return b},getBaseline:function(a,b){var c,d;switch(a[0]){case "top":c=0;break;case "middle":c=0.5;break;case "bottom":c=1;break;default:c=a[0]/b.height}switch(a[1]){case "left":d=
0;break;case "center":d=0.5;break;case "right":d=1;break;default:d=a[1]/b.width}return{x:d,y:c}},createWrapper:function(a){if(a.parent().is(".ui-effects-wrapper"))return a.parent();var b={width:a.outerWidth(!0),height:a.outerHeight(!0),"float":a.css("float")},c=d("<div></div>").addClass("ui-effects-wrapper").css({fontSize:"100%",background:"transparent",border:"none",margin:0,padding:0});a.wrap(c);c=a.parent();"static"==a.css("position")?(c.css({position:"relative"}),a.css({position:"relative"})):
(d.extend(b,{position:a.css("position"),zIndex:a.css("z-index")}),d.each(["top","left","bottom","right"],function(c,d){b[d]=a.css(d);isNaN(parseInt(b[d],10))&&(b[d]="auto")}),a.css({position:"relative",top:0,left:0,right:"auto",bottom:"auto"}));return c.css(b).show()},removeWrapper:function(a){return a.parent().is(".ui-effects-wrapper")?a.parent().replaceWith(a):a},setTransition:function(a,b,c,e){e=e||{};d.each(b,function(b,i){unit=a.cssUnit(i);0<unit[0]&&(e[i]=unit[0]*c+unit[1])});return e}});d.fn.extend({effect:function(a,
b,c,e){var f=g.apply(this,arguments),m={options:f[1],duration:f[2],callback:f[3]},f=m.options.mode,l=d.effects[a];return d.fx.off||!l?f?this[f](m.duration,m.callback):this.each(function(){m.callback&&m.callback.call(this)}):l.call(this,m)},_show:d.fn.show,show:function(a){if(m(a))return this._show.apply(this,arguments);var b=g.apply(this,arguments);b[1].mode="show";return this.effect.apply(this,b)},_hide:d.fn.hide,hide:function(a){if(m(a))return this._hide.apply(this,arguments);var b=g.apply(this,
arguments);b[1].mode="hide";return this.effect.apply(this,b)},__toggle:d.fn.toggle,toggle:function(a){if(m(a)||"boolean"===typeof a||d.isFunction(a))return this.__toggle.apply(this,arguments);var b=g.apply(this,arguments);b[1].mode="toggle";return this.effect.apply(this,b)},cssUnit:function(a){var b=this.css(a),c=[];d.each(["em","px","%","pt"],function(a,d){0<b.indexOf(d)&&(c=[parseFloat(b),d])});return c}});d.easing.jswing=d.easing.swing;d.extend(d.easing,{def:"easeOutQuad",swing:function(a,b,c,
e,f){return d.easing[d.easing.def](a,b,c,e,f)},easeInQuad:function(a,b,c,d,e){return d*(b/=e)*b+c},easeOutQuad:function(a,b,c,d,e){return-d*(b/=e)*(b-2)+c},easeInOutQuad:function(a,b,c,d,e){return 1>(b/=e/2)?d/2*b*b+c:-d/2*(--b*(b-2)-1)+c},easeInCubic:function(a,b,c,d,e){return d*(b/=e)*b*b+c},easeOutCubic:function(a,b,c,d,e){return d*((b=b/e-1)*b*b+1)+c},easeInOutCubic:function(a,b,c,d,e){return 1>(b/=e/2)?d/2*b*b*b+c:d/2*((b-=2)*b*b+2)+c},easeInQuart:function(a,b,c,d,e){return d*(b/=e)*b*b*b+c},
easeOutQuart:function(a,b,c,d,e){return-d*((b=b/e-1)*b*b*b-1)+c},easeInOutQuart:function(a,b,c,d,e){return 1>(b/=e/2)?d/2*b*b*b*b+c:-d/2*((b-=2)*b*b*b-2)+c},easeInQuint:function(a,b,c,d,e){return d*(b/=e)*b*b*b*b+c},easeOutQuint:function(a,b,c,d,e){return d*((b=b/e-1)*b*b*b*b+1)+c},easeInOutQuint:function(a,b,c,d,e){return 1>(b/=e/2)?d/2*b*b*b*b*b+c:d/2*((b-=2)*b*b*b*b+2)+c},easeInSine:function(a,b,c,d,e){return-d*Math.cos(b/e*(Math.PI/2))+d+c},easeOutSine:function(a,b,c,d,e){return d*Math.sin(b/
e*(Math.PI/2))+c},easeInOutSine:function(a,b,c,d,e){return-d/2*(Math.cos(Math.PI*b/e)-1)+c},easeInExpo:function(a,b,c,d,e){return 0==b?c:d*Math.pow(2,10*(b/e-1))+c},easeOutExpo:function(a,b,c,d,e){return b==e?c+d:d*(-Math.pow(2,-10*b/e)+1)+c},easeInOutExpo:function(a,b,c,d,e){return 0==b?c:b==e?c+d:1>(b/=e/2)?d/2*Math.pow(2,10*(b-1))+c:d/2*(-Math.pow(2,-10*--b)+2)+c},easeInCirc:function(a,b,c,d,e){return-d*(Math.sqrt(1-(b/=e)*b)-1)+c},easeOutCirc:function(a,b,c,d,e){return d*Math.sqrt(1-(b=b/e-1)*
b)+c},easeInOutCirc:function(a,b,c,d,e){return 1>(b/=e/2)?-d/2*(Math.sqrt(1-b*b)-1)+c:d/2*(Math.sqrt(1-(b-=2)*b)+1)+c},easeInElastic:function(a,b,c,d,e){var a=1.70158,f=0,g=d;if(0==b)return c;if(1==(b/=e))return c+d;f||(f=0.3*e);g<Math.abs(d)?(g=d,a=f/4):a=f/(2*Math.PI)*Math.asin(d/g);return-(g*Math.pow(2,10*(b-=1))*Math.sin((b*e-a)*2*Math.PI/f))+c},easeOutElastic:function(a,b,c,d,e){var a=1.70158,f=0,g=d;if(0==b)return c;if(1==(b/=e))return c+d;f||(f=0.3*e);g<Math.abs(d)?(g=d,a=f/4):a=f/(2*Math.PI)*
Math.asin(d/g);return g*Math.pow(2,-10*b)*Math.sin((b*e-a)*2*Math.PI/f)+d+c},easeInOutElastic:function(a,b,c,d,e){var a=1.70158,f=0,g=d;if(0==b)return c;if(2==(b/=e/2))return c+d;f||(f=e*0.3*1.5);g<Math.abs(d)?(g=d,a=f/4):a=f/(2*Math.PI)*Math.asin(d/g);return 1>b?-0.5*g*Math.pow(2,10*(b-=1))*Math.sin((b*e-a)*2*Math.PI/f)+c:0.5*g*Math.pow(2,-10*(b-=1))*Math.sin((b*e-a)*2*Math.PI/f)+d+c},easeInBack:function(a,b,d,e,f,g){g==c&&(g=1.70158);return e*(b/=f)*b*((g+1)*b-g)+d},easeOutBack:function(a,b,d,e,
f,g){g==c&&(g=1.70158);return e*((b=b/f-1)*b*((g+1)*b+g)+1)+d},easeInOutBack:function(a,b,d,e,f,g){g==c&&(g=1.70158);return 1>(b/=f/2)?e/2*b*b*(((g*=1.525)+1)*b-g)+d:e/2*((b-=2)*b*(((g*=1.525)+1)*b+g)+2)+d},easeInBounce:function(a,b,c,e,f){return e-d.easing.easeOutBounce(a,f-b,0,e,f)+c},easeOutBounce:function(a,b,c,d,e){return(b/=e)<1/2.75?d*7.5625*b*b+c:b<2/2.75?d*(7.5625*(b-=1.5/2.75)*b+0.75)+c:b<2.5/2.75?d*(7.5625*(b-=2.25/2.75)*b+0.9375)+c:d*(7.5625*(b-=2.625/2.75)*b+0.984375)+c},easeInOutBounce:function(a,
b,c,e,f){return b<f/2?0.5*d.easing.easeInBounce(a,2*b,0,e,f)+c:0.5*d.easing.easeOutBounce(a,2*b-f,0,e,f)+0.5*e+c}})}(jQuery);
(function(d){function c(a,b){return function(c){return o(a.call(this,c),b)}}function b(a){return function(b){return this.lang().ordinal(a.call(this,b))}}function a(){}function e(a){g(this,a)}function f(a){var b=this._data={},c=a.years||a.year||a.y||0,d=a.months||a.month||a.M||0,e=a.weeks||a.week||a.w||0,f=a.days||a.day||a.d||0,g=a.hours||a.hour||a.h||0,i=a.minutes||a.minute||a.m||0,h=a.seconds||a.second||a.s||0,a=a.milliseconds||a.millisecond||a.ms||0;this._milliseconds=a+1E3*h+6E4*i+36E5*g;this._days=
f+7*e;this._months=d+12*c;b.milliseconds=a%1E3;h+=m(a/1E3);b.seconds=h%60;i+=m(h/60);b.minutes=i%60;g+=m(i/60);b.hours=g%24;f+=m(g/24);f+=7*e;b.days=f%30;d+=m(f/30);b.months=d%12;c+=m(d/12);b.years=c}function g(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c]);return a}function m(a){return 0>a?Math.ceil(a):Math.floor(a)}function o(a,b){for(var c=a+"";c.length<b;)c="0"+c;return c}function l(a,b,c){var d=b._milliseconds,e=b._days,b=b._months;d&&a._d.setTime(+a+d*c);e&&a.date(a.date()+e*c);b&&(d=
a.date(),a.date(1).month(a.month()+b*c).date(Math.min(d,a.daysInMonth())))}function q(a,b){var c=Math.min(a.length,b.length),d=Math.abs(a.length-b.length),e=0,f;for(f=0;f<c;f++)~~a[f]!==~~b[f]&&e++;return e+d}function r(a){if(!a)return j.fn._lang;!p[a]&&u&&require("./lang/"+a);return p[a]}function i(a){switch(a){case "DDDD":return L;case "YYYY":return M;case "YYYYY":return N;case "S":case "SS":case "SSS":case "DDD":return O;case "MMM":case "MMMM":case "dd":case "ddd":case "dddd":case "a":case "A":return P;
case "Z":case "ZZ":return H;case "T":return Q;case "MM":case "DD":case "YY":case "HH":case "hh":case "mm":case "ss":case "M":case "D":case "d":case "H":case "h":case "m":case "s":return R;default:return RegExp(a.replace("\\",""))}}function y(a){var b,c=[];for(b=0;7>b;b++)a._a[b]=c[b]=null==a._a[b]?2===b?1:0:a._a[b];c[3]+=a._tzh||0;c[4]+=a._tzm||0;b=new Date(0);a._useUTC?(b.setUTCFullYear(c[0],c[1],c[2]),b.setUTCHours(c[3],c[4],c[5],c[6])):(b.setFullYear(c[0],c[1],c[2]),b.setHours(c[3],c[4],c[5],c[6]));
a._d=b}function s(a){var b=a._f.match(B),c=a._i,d,e;a._a=[];for(d=0;d<b.length;d++)if((e=(i(b[d]).exec(c)||[])[0])&&(c=c.slice(c.indexOf(e)+e.length)),z[b[d]]){var f=a,g=void 0,h=f._a;switch(b[d]){case "M":case "MM":h[1]=null==e?0:~~e-1;break;case "MMM":case "MMMM":g=r(f._l).monthsParse(e);null!=g?h[1]=g:f._isValid=!1;break;case "D":case "DD":case "DDD":case "DDDD":null!=e&&(h[2]=~~e);break;case "YY":h[0]=~~e+(68<~~e?1900:2E3);break;case "YYYY":case "YYYYY":h[0]=~~e;break;case "a":case "A":f._isPm=
"pm"===(e+"").toLowerCase();break;case "H":case "HH":case "h":case "hh":h[3]=~~e;break;case "m":case "mm":h[4]=~~e;break;case "s":case "ss":h[5]=~~e;break;case "S":case "SS":case "SSS":h[6]=~~(1E3*("0."+e));break;case "Z":case "ZZ":f._useUTC=!0;if((g=(e+"").match(S))&&g[1])f._tzh=~~g[1];g&&g[2]&&(f._tzm=~~g[2]);g&&"+"===g[0]&&(f._tzh=-f._tzh,f._tzm=-f._tzm)}null==e&&(f._isValid=!1)}a._isPm&&12>a._a[3]&&(a._a[3]+=12);!1===a._isPm&&12===a._a[3]&&(a._a[3]=0);y(a)}function t(a,b,c,d,e){return e.relativeTime(b||
1,!!c,a,d)}function D(a,b,c){b=c-b;c-=a.day();c>b&&(c-=7);c<b-7&&(c+=7);return Math.ceil(j(a).add("d",c).dayOfYear()/7)}function A(a){var b=a._i,c=a._f;if(null===b||""===b)return null;"string"===typeof b&&(a._i=b=r().preparse(b));if(j.isMoment(b))a=g({},b),a._d=new Date(+b._d);else if(c)if("[object Array]"===Object.prototype.toString.call(c)){for(var b=a,f,h,i=99;b._f.length;){f=g({},b);f._f=b._f.pop();s(f);c=new e(f);if(c.isValid()){h=c;break}f=q(f._a,c.toArray());f<i&&(i=f,h=c)}g(b,h)}else s(a);
else if(h=a,b=h._i,c=w.exec(b),b===d)h._d=new Date;else if(c)h._d=new Date(+c[1]);else if("string"===typeof b)if(c=h._i,T.exec(c)){h._f="YYYY-MM-DDT";for(b=0;4>b;b++)if(I[b][1].exec(c)){h._f+=I[b][0];break}H.exec(c)&&(h._f+=" Z");s(h)}else h._d=new Date(c);else"[object Array]"===Object.prototype.toString.call(b)?(h._a=b.slice(0),y(h)):h._d=b instanceof Date?new Date(+b):new Date(b);return new e(a)}function x(a,b){j.fn[a]=j.fn[a+"s"]=function(a){var c=this._isUTC?"UTC":"";return null!=a?(this._d["set"+
c+b](a),this):this._d["get"+c+b]()}}function v(a){j.duration.fn[a]=function(){return this._data[a]}}function n(a,b){j.duration.fn["as"+a]=function(){return+this/b}}for(var j,h=Math.round,k,p={},u="undefined"!==typeof module&&module.exports,w=/^\/?Date\((\-?\d+)/i,B=/(\[[^\[]*\])|(\\)?(Mo|MM?M?M?|Do|DDDo|DD?D?D?|ddd?d?|do?|w[o|w]?|W[o|W]?|YYYYY|YYYY|YY|a|A|hh?|HH?|mm?|ss?|SS?S?|zz?|ZZ?|.)/g,C=/(\[[^\[]*\])|(\\)?(LT|LL?L?L?|l{1,4})/g,R=/\d\d?/,O=/\d{1,3}/,L=/\d{3}/,M=/\d{1,4}/,N=/[+\-]?\d{1,6}/,P=/[0-9]*[a-z\u00A0-\u05FF\u0700-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+|[\u0600-\u06FF]+\s*?[\u0600-\u06FF]+/i,
H=/Z|[\+\-]\d\d:?\d\d/i,Q=/T/i,T=/^\s*\d{4}-\d\d-\d\d((T| )(\d\d(:\d\d(:\d\d(\.\d\d?\d?)?)?)?)?([\+\-]\d\d:?\d\d)?)?/,I=[["HH:mm:ss.S",/(T| )\d\d:\d\d:\d\d\.\d{1,3}/],["HH:mm:ss",/(T| )\d\d:\d\d:\d\d/],["HH:mm",/(T| )\d\d:\d\d/],["HH",/(T| )\d\d/]],S=/([\+\-]|\d\d)/gi,E="Month Date Hours Minutes Seconds Milliseconds".split(" "),F={Milliseconds:1,Seconds:1E3,Minutes:6E4,Hours:36E5,Days:864E5,Months:2592E6,Years:31536E6},G={},J="DDD w W M D d".split(" "),K="MDHhmswW".split(""),z={M:function(){return this.month()+
1},MMM:function(a){return this.lang().monthsShort(this,a)},MMMM:function(a){return this.lang().months(this,a)},D:function(){return this.date()},DDD:function(){return this.dayOfYear()},d:function(){return this.day()},dd:function(a){return this.lang().weekdaysMin(this,a)},ddd:function(a){return this.lang().weekdaysShort(this,a)},dddd:function(a){return this.lang().weekdays(this,a)},w:function(){return this.week()},W:function(){return this.isoWeek()},YY:function(){return o(this.year()%100,2)},YYYY:function(){return o(this.year(),
4)},YYYYY:function(){return o(this.year(),5)},a:function(){return this.lang().meridiem(this.hours(),this.minutes(),!0)},A:function(){return this.lang().meridiem(this.hours(),this.minutes(),!1)},H:function(){return this.hours()},h:function(){return this.hours()%12||12},m:function(){return this.minutes()},s:function(){return this.seconds()},S:function(){return~~(this.milliseconds()/100)},SS:function(){return o(~~(this.milliseconds()/10),2)},SSS:function(){return o(this.milliseconds(),3)},Z:function(){var a=
-this.zone(),b="+";0>a&&(a=-a,b="-");return b+o(~~(a/60),2)+":"+o(~~a%60,2)},ZZ:function(){var a=-this.zone(),b="+";0>a&&(a=-a,b="-");return b+o(~~(10*a/6),4)}};J.length;)k=J.pop(),z[k+"o"]=b(z[k]);for(;K.length;)k=K.pop(),z[k+k]=c(z[k],2);z.DDDD=c(z.DDD,3);a.prototype={set:function(a){var b,c;for(c in a)b=a[c],"function"===typeof b?this[c]=b:this["_"+c]=b},_months:"January February March April May June July August September October November December".split(" "),months:function(a){return this._months[a.month()]},
_monthsShort:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),monthsShort:function(a){return this._monthsShort[a.month()]},monthsParse:function(a){var b,c;this._monthsParse||(this._monthsParse=[]);for(b=0;12>b;b++)if(this._monthsParse[b]||(c=j([2E3,b]),c="^"+this.months(c,"")+"|^"+this.monthsShort(c,""),this._monthsParse[b]=RegExp(c.replace(".",""),"i")),this._monthsParse[b].test(a))return b},_weekdays:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),weekdays:function(a){return this._weekdays[a.day()]},
_weekdaysShort:"Sun Mon Tue Wed Thu Fri Sat".split(" "),weekdaysShort:function(a){return this._weekdaysShort[a.day()]},_weekdaysMin:"Su Mo Tu We Th Fr Sa".split(" "),weekdaysMin:function(a){return this._weekdaysMin[a.day()]},_longDateFormat:{LT:"h:mm A",L:"MM/DD/YYYY",LL:"MMMM D YYYY",LLL:"MMMM D YYYY LT",LLLL:"dddd, MMMM D YYYY LT"},longDateFormat:function(a){var b=this._longDateFormat[a];!b&&this._longDateFormat[a.toUpperCase()]&&(b=this._longDateFormat[a.toUpperCase()].replace(/MMMM|MM|DD|dddd/g,
function(a){return a.slice(1)}),this._longDateFormat[a]=b);return b},meridiem:function(a,b,c){return 11<a?c?"pm":"PM":c?"am":"AM"},_calendar:{sameDay:"[Today at] LT",nextDay:"[Tomorrow at] LT",nextWeek:"dddd [at] LT",lastDay:"[Yesterday at] LT",lastWeek:"[last] dddd [at] LT",sameElse:"L"},calendar:function(a,b){var c=this._calendar[a];return"function"===typeof c?c.apply(b):c},_relativeTime:{future:"in %s",past:"%s ago",s:"a few seconds",m:"a minute",mm:"%d minutes",h:"an hour",hh:"%d hours",d:"a day",
dd:"%d days",M:"a month",MM:"%d months",y:"a year",yy:"%d years"},relativeTime:function(a,b,c,d){var e=this._relativeTime[c];return"function"===typeof e?e(a,b,c,d):e.replace(/%d/i,a)},pastFuture:function(a,b){var c=this._relativeTime[0<a?"future":"past"];return"function"===typeof c?c(b):c.replace(/%s/i,b)},ordinal:function(a){return this._ordinal.replace("%d",a)},_ordinal:"%d",preparse:function(a){return a},postformat:function(a){return a},week:function(a){return D(a,this._week.dow,this._week.doy)},
_week:{dow:0,doy:6}};j=function(a,b,c){return A({_i:a,_f:b,_l:c,_isUTC:!1})};j.utc=function(a,b,c){return A({_useUTC:!0,_isUTC:!0,_l:c,_i:a,_f:b})};j.unix=function(a){return j(1E3*a)};j.duration=function(a,b){var c=j.isDuration(a),d="number"===typeof a,e=c?a._data:d?{}:a;d&&(b?e[b]=a:e.milliseconds=a);d=new f(e);c&&a.hasOwnProperty("_lang")&&(d._lang=a._lang);return d};j.humanizeDuration=function(a,b,c){return j.duration(a,!0===b?null:b).humanize(!0===b?!0:c)};j.version="1.7.2";j.defaultFormat="YYYY-MM-DDTHH:mm:ssZ";
j.lang=function(b,c){if(!b)return j.fn._lang._abbr;c?(c.abbr=b,p[b]||(p[b]=new a),p[b].set(c)):p[b]||r(b);j.duration.fn._lang=j.fn._lang=r(b)};j.langData=function(a){a&&(a._lang&&a._lang._abbr)&&(a=a._lang._abbr);return r(a)};j.isMoment=function(a){return a instanceof e};j.isDuration=function(a){return a instanceof f};j.fn=e.prototype={clone:function(){return j(this)},valueOf:function(){return+this._d},unix:function(){return Math.floor(+this._d/1E3)},toString:function(){return this.format("ddd MMM DD YYYY HH:mm:ss [GMT]ZZ")},
toDate:function(){return this._d},toJSON:function(){return j.utc(this).format("YYYY-MM-DD[T]HH:mm:ss.SSS[Z]")},toArray:function(){return[this.year(),this.month(),this.date(),this.hours(),this.minutes(),this.seconds(),this.milliseconds()]},isValid:function(){null==this._isValid&&(this._isValid=this._a?!q(this._a,(this._isUTC?j.utc(this._a):j(this._a)).toArray()):!isNaN(this._d.getTime()));return!!this._isValid},utc:function(){this._isUTC=!0;return this},local:function(){this._isUTC=!1;return this},
format:function(a){for(var b=this,a=a||j.defaultFormat,c=function(a){return b.lang().longDateFormat(a)||a},d=5;d--&&C.test(a);)a=a.replace(C,c);if(!G[a]){var e=c=a,f=e.match(B),g,h;g=0;for(h=f.length;g<h;g++)if(z[f[g]])f[g]=z[f[g]];else{var d=f,i=g,v;v=f[g];v=v.match(/\[.*\]/)?v.replace(/^\[|\]$/g,""):v.replace(/\\/g,"");d[i]=v}G[c]=function(a){var b="";for(g=0;g<h;g++)b+="function"===typeof f[g].call?f[g].call(a,e):f[g];return b}}a=G[a](b);return this.lang().postformat(a)},add:function(a,b){var c;
c="string"===typeof a?j.duration(+b,a):j.duration(a,b);l(this,c,1);return this},subtract:function(a,b){var c;c="string"===typeof a?j.duration(+b,a):j.duration(a,b);l(this,c,-1);return this},diff:function(a,b,c){var a=this._isUTC?j(a).utc():j(a).local(),d=6E4*(this.zone()-a.zone()),e;b&&(b=b.replace(/s$/,""));"year"===b||"month"===b?(d=432E5*(this.daysInMonth()+a.daysInMonth()),e=12*(this.year()-a.year())+(this.month()-a.month()),e+=(this-j(this).startOf("month")-(a-j(a).startOf("month")))/d,"year"===
b&&(e/=12)):(d=this-a-d,e="second"===b?d/1E3:"minute"===b?d/6E4:"hour"===b?d/36E5:"day"===b?d/864E5:"week"===b?d/6048E5:d);return c?e:h(e)},from:function(a,b){return j.duration(this.diff(a)).lang(this.lang()._abbr).humanize(!b)},fromNow:function(a){return this.from(j(),a)},calendar:function(){var a=this.diff(j().sod(),"days",!0);return this.format(this.lang().calendar(-6>a?"sameElse":-1>a?"lastWeek":0>a?"lastDay":1>a?"sameDay":2>a?"nextDay":7>a?"nextWeek":"sameElse",this))},isLeapYear:function(){var a=
this.year();return 0===a%4&&0!==a%100||0===a%400},isDST:function(){return this.zone()<j([this.year()]).zone()||this.zone()<j([this.year(),5]).zone()},day:function(a){var b=this._isUTC?this._d.getUTCDay():this._d.getDay();return null==a?b:this.add({d:a-b})},startOf:function(a){a=a.replace(/s$/,"");switch(a){case "year":this.month(0);case "month":this.date(1);case "week":case "day":this.hours(0);case "hour":this.minutes(0);case "minute":this.seconds(0);case "second":this.milliseconds(0)}"week"===a&&
this.day(0);return this},endOf:function(a){return this.startOf(a).add(a.replace(/s?$/,"s"),1).subtract("ms",1)},isAfter:function(a,b){b="undefined"!==typeof b?b:"millisecond";return+this.clone().startOf(b)>+j(a).startOf(b)},isBefore:function(a,b){b="undefined"!==typeof b?b:"millisecond";return+this.clone().startOf(b)<+j(a).startOf(b)},isSame:function(a,b){b="undefined"!==typeof b?b:"millisecond";return+this.clone().startOf(b)===+j(a).startOf(b)},sod:function(){return this.clone().startOf("day")},
eod:function(){return this.clone().endOf("day")},zone:function(){return this._isUTC?0:this._d.getTimezoneOffset()},daysInMonth:function(){return j.utc([this.year(),this.month()+1,0]).date()},dayOfYear:function(a){var b=h((j(this).startOf("day")-j(this).startOf("year"))/864E5)+1;return null==a?b:this.add("d",a-b)},isoWeek:function(a){var b=D(this,1,4);return null==a?b:this.add("d",7*(a-b))},week:function(a){var b=this.lang().week(this);return null==a?b:this.add("d",7*(a-b))},lang:function(a){if(a===
d)return this._lang;this._lang=r(a);return this}};for(k=0;k<E.length;k++)x(E[k].toLowerCase().replace(/s$/,""),E[k]);x("year","FullYear");j.fn.days=j.fn.day;j.fn.weeks=j.fn.week;j.fn.isoWeeks=j.fn.isoWeek;j.duration.fn=f.prototype={weeks:function(){return m(this.days()/7)},valueOf:function(){return this._milliseconds+864E5*this._days+2592E6*this._months},humanize:function(a){var b=+this,c;c=!a;var d=this.lang(),e=h(Math.abs(b)/1E3),f=h(e/60),g=h(f/60),i=h(g/24),v=h(i/365),e=45>e&&["s",e]||1===f&&
["m"]||45>f&&["mm",f]||1===g&&["h"]||22>g&&["hh",g]||1===i&&["d"]||25>=i&&["dd",i]||45>=i&&["M"]||345>i&&["MM",h(i/30)]||1===v&&["y"]||["yy",v];e[2]=c;e[3]=0<b;e[4]=d;c=t.apply({},e);a&&(c=this.lang().pastFuture(b,c));return this.lang().postformat(c)},lang:j.fn.lang};for(k in F)F.hasOwnProperty(k)&&(n(k,F[k]),v(k.toLowerCase()));n("Weeks",6048E5);j.lang("en",{ordinal:function(a){var b=a%10;return a+(1===~~(a%100/10)?"th":1===b?"st":2===b?"nd":3===b?"rd":"th")}});u&&(module.exports=j);"undefined"===
typeof ender&&(this.moment=j);"function"===typeof define&&define.amd&&define("moment",[],function(){return j})}).call(this);
(function(d,c){function b(a){return 10>a?"000"+a:100>a?"00"+a:1E3>a?"0"+a:""+a}function a(a,b,c){var d=null,e=null;"string"===typeof a?(d=b||a,e=c||a):(d=a.format(b),e=a.format(c));return{name:d,value:e}}function e(a){var b=parseInt(a,10);if("string"===$.type(a)){if(2<a.length)return b;if("00"===a)return 2E3}return 100>b?40>b?2E3+b:1900+b:b}if(d)if(c){var f=/^\d{4}-\d\d-\d\d(T| )\d\d:\d\d:\d\d(\.\d{1,4})?(Z|[\+\-]\d\d:?\d\d)?$/,g=/^\d{4}$/,m=/^\d{4}-\d\d$/,o=/^\d{4}-\d\d-\d\d$/,l=/^\d{4}-\d\d-\d\d(T| )\d\d$/,
q=/^\d{4}-\d\d-\d\d(T| )\d\d:\d\d$/,r=/^\d{4}-\d\d-\d\d(T| )\d\d:\d\d:\d\d$/,i=/^\d{4}-\d\d-\d\d(T| )\d\d:\d\d:\d\d.\d{1,4}$/,y=/^\d\d$/,s=/^\d\d?:\d\d$/,t=/^\d\d?:\d\d:\d\d$/,D=/^\d\d?:\d\d:\d\d\.\d{1,4}$/,A=[/^(\d+)\s?[Bb]\.?[Cc](?:.?[Ee])?$/,/^[Bb]\.?[Cc](?:\.?[Ee])?\s?(\d+)$/],x=/[\/\.\-\s]/;$.suggest("suggest_datetime",{request:function(a){a=$.suggest.suggest_datetime.suggestions(a);this.response(a)},_init:function(){this.lang="en";if(this.options.lang){var a=this.options.lang.split("/").pop().toLowerCase();
"en"!==a&&c.langData(a)&&(this.lang=a)}},check_response:function(){return!0}});$.extend($.suggest.suggest_datetime,{defaults:{status:null,nomatch:{title:"You can enter a datetime in many ways, just be sure to include the year when entering dates!",heading:"Try:",tips:"January 2007;9/30/1986;2001;4/1975;12:30 AM;200 BC;1973-11-05T12:00:00Z".split(";")}},suggestions:function(d){var d=$.trim(d),n=[],j=c.utc(),h=null;if(/^\d\d?$/.test(d)){var k=parseInt(d,10);if(0<k&&(12>=k&&(h=c.utc([j.year(),d-1]),
n.push(a(h,"MMMM YYYY","YYYY-MM"))),24>=k&&(h=c.utc(d,"h A"),n.push(a(h,"LT","HH"))),2===d.length))h=c.utc([e(d)]),n.push(a(h,"YYYY","YYYY"));"00"===d&&(h=c.utc([2E3]),n.push(a(h,"YYYY","YYYY")))}/^\w+$/.test(d)&&(h=c.utc(d,"MMM"),h.isValid()&&(h=c.utc([j.year(),h.month()]),n.push(a(h,"MMMM YYYY","YYYY-MM"))));if(/^\d\d?[\/\.\-\s](\d\d|\d{4})$/.test(d)){var p=d.split(x),u=parseInt(p[0],10),k=parseInt(p[1],10);0<u&&12>=u&&(h=c.utc([e(p[1]),u-1]),n.push(a(h,"MMMM YYYY","YYYY-MM")))}/^\w+[\/\.\-\s](\d\d|\d{4})$/.test(d)&&
(k=e(d.split(x)[1]),h=c.utc(d,"MMM"),h.isValid()&&(h=c.utc([k,h.month()]),n.push(a(h,"MMMM YYYY","YYYY-MM"))));/^(\d\d|\d{4})[\/\.\-\s]\w+$/.test(d)&&(k=e(d.split(x)[0]),h=c.utc(d,"MMM"),h.isValid()&&(h=c.utc([k,h.month()]),n.push(a(h,"MMMM YYYY","YYYY-MM"))));if(/^\d\d?[\/\.\-\s]\d\d?$/.test(d)){var p=d.split(x),u=parseInt(p[0],10),w=parseInt(p[1],10);if(0<u&&0<w&&(12>=u&&(h=c.utc([j.year(),u-1,w]),n.push(a(h,"LL","YYYY-MM-DD"))),12>=w))h=c.utc([j.year(),w-1,u]),n.push(a(h,"LL","YYYY-MM-DD"))}/^\w+[\/\.\-\s]\d\d?$/.test(d)&&
(h=c.utc(d,"MMM/D"),h.isValid()&&(h=c.utc([j.year(),h.month(),h.date()]),n.push(a(h,"LL","YYYY-MM-DD"))));/^\d\d?[\/\.\-\s]\w+$/.test(d)&&(h=c.utc(d,"D/MMM"),h.isValid()&&(h=c.utc([j.year(),h.month(),h.date()]),n.push(a(h,"LL","YYYY-MM-DD"))));if(/^\d\d?[\/\.\-\s]\d\d?[\/\.\-\s](\d\d|\d{4})$/.test(d)&&(p=d.split(x),u=parseInt(p[0],10),w=parseInt(p[1],10),k=e(p[2]),0<u&&0<w&&(12>=u&&(h=c.utc([k,u-1,w]),n.push(a(h,"LL","YYYY-MM-DD"))),12>=w)))h=c.utc([k,w-1,u]),n.push(a(h,"LL","YYYY-MM-DD"));/^\w+[\/\.\-\s]\d\d?[\/\.\-\s\,]+(\d\d|\d{4})$/.test(d)&&
(p=d.split(/[\/\.\-\s\,]/),w=p[1],k=e(p.pop()),h=c.utc(d,"MMM"),h.isValid()&&(h=c.utc([k,h.month(),w]),n.push(a(h,"LL","YYYY-MM-DD"))));/^\d\d?[\/\.\-\s]\w+[\/\.\-\s\,]+(\d\d|\d{4})$/.test(d)&&(p=d.split(/[\/\.\-\s\,]/),w=p[0],k=e(p.pop()),h=c.utc(d,"MMM"),h.isValid()&&(h=c.utc([k,h.month(),w]),n.push(a(h,"LL","YYYY-MM-DD"))));g.test(d)?"0000"===d?n.push(a("1 BCE",null,d)):n.push(a(d)):m.test(d)?(h=c.utc(d,"YYYY-MM"),n.push(a(h,"MMMM YYYY","YYYY-MM"))):o.test(d)?(h=c.utc(d,"YYYY-MM-DD"),n.push(a(h,
"LL","YYYY-MM-DD"))):l.test(d)?(h=c.utc(d,"YYYY-MM-DDTHH"),n.push(a(h,"LLL","YYYY-MM-DDTHH"))):q.test(d)?(h=c.utc(d,"YYYY-MM-DDTHH:mm"),n.push(a(h,"LLL","YYYY-MM-DDTHH:mm"))):r.test(d)?(h=c.utc(d,"YYYY-MM-DDTHH:mm:ss"),n.push(a(h,"YYYY-MM-DD HH:mm:ss","YYYY-MM-DDTHH:mm:ss"))):i.test(d)||f.test(d)?n.push(a(d)):(k=d.split("T").pop(),y.test(k)?(h=c.utc(k,"HH"),h.isValid()&&n.push(a(h,"LT","HH"))):s.test(k)?(h=c.utc(k,"HH:mm"),h.isValid()&&n.push(a(h,"LT","HH:mm"))):t.test(k)?(h=c.utc(k,"HH:mm:ss"),h.isValid()&&
n.push(a(h,"HH:mm:ss","HH:mm:ss"))):D.test(k)&&(p=k.split("."),h=c.utc(p[0],"HH:mm:ss"),k=h.format("HH:mm:ss")+"."+p[1],n.push(a(k))));/^\d\d?\s?[aApP][mM]$/.test(d)?(h=c.utc(d,"h A"),h.isValid()&&n.push(a(h,"LT","HH:mm"))):/^\d\d?:\d\d\s?[aApP][mM]$/.test(d)?(h=c.utc(d,"h:mm A"),h.isValid()&&n.push(a(h,"LT","HH:mm"))):/^\d\d?:\d\d:\d\d\s?[aApP][mM]$/.test(d)&&(h=c.utc(d,"h:mm:ss A"),h.isValid()&&n.push(a(h,"HH:mm:ss","HH:mm:ss")));/^\-\d+$/.test(d)&&(k=parseInt(d.substring(1),10),0===k?n.push(a("1 BCE",
null,"0000")):n.push(a(k+1+" BCE",null,"-"+b(k))));j=0;for(h=A.length;j<h;j++)if(k=A[j].exec(d))k=parseInt(k[1],10),0<k&&(1==k?n.push(a("1 BCE",null,"0000")):n.push(a(k+" BCE",null,"-"+b(k-1))));var B=[],C={};$.each(n,function(a,b){var c=b.name+"$$"+b.value;if(!C[c]){B.push(b);C[c]=1}});return B}})}else console.error("moment.js is required");else console.error("$.suggest is required")})(jQuery.suggest,moment);
(function(d){d.fn.mqlkey=function(b){return this.each(function(){var a=d(this);if(a.is(":text")){var e=a.data("mqlkey");e&&e._destroy();e=new c(this,b);a.data("mqlkey",e)}})};var c=d.mqlkey=function(b,a){this.options=d.extend(!0,{},c.defaults,a);this.input=d(b);this.original=this.input.val();this.init()};c.prototype={init:function(){var b=this;this.input.bind("keyup.mqlkey",function(a){b.textchange(a)}).bind(d.browser.msie?"paste.mqlkey":"input.mqlkey",function(a){b.textchange(a)});this.options.source&&
(this.source=d(this.options.source),this.source_generate=""===this.source.val()?!0:!1,this.input.bind("change.mqlkey",function(){b.source_generate=!1}),this.source.bind("change.mqlkey",function(){if(b.source_generate){var a=c.from(b.source.val());b.input.val(a).trigger("keyup")}}))},_destroy:function(){this.input.unbind(".mqlkey");this.source&&this.source.unbind("change.mqlkey")},textchange:function(b){clearTimeout(this.textchange_timeout);var a=this;this.textchange_timeout=setTimeout(function(){a.textchange_delay(b)},
200)},textchange_delay:function(){this.input.trigger("textchange");var b=d.trim(this.input.val());return b===this.original&&""!==b?this.valid(b):c.reserved_word(b)?this.invalid(b,b+" is a reserved word."):c.test(b,this.options.schema)?b.length<this.options.minlen?this.invalid(b):this.options.check_key?this.check_key(b):this.valid(b):this.invalid(b)},check_key:function(b){var a=this;this.xhr&&(this.xhr=null);var c={id:null,key:{namespace:this.options.namespace,value:b}};clearTimeout(this.check_key.timeout);
this.check_key.timeout=setTimeout(function(){a.xhr=a.options.mqlread(c,function(c){return c?a.invalid(b,"Key already exists"):a.valid(b)},function(b){return b?a.invalid(b.responseText()):a.invalid("mqlread error!")})},200)},valid:function(b){this.input.trigger("valid",b)},invalid:function(b,a){a||(a=1<this.options.minlen?"Key must be "+this.options.minlen+" or more alphanumeric characters":"Key must be alphanumeric",a+=", lowercase, begin with a letter and not end with a non-alphanumeric character. Underscores are allowed but not consecutively.");
this.input.trigger("invalid",a)}};d.extend(c,{defaults:{minlen:1,check_key:!0,namespace:"/",mqlread:function(b,a,d){return c.mqlread(null,b,a,d)},source:null,schema:!1},mqlread:function(b,a,c,f){b={url:b||"http://api.freebase.com/api/service/mqlread",data:{query:JSON.stringify({query:a})},dataType:"jsonp",success:function(a){return c(a.result)},error:f};return d.ajax(b)},from:function(b){b=b.toLowerCase();b=b.replace(/[^a-z0-9]/g,"_");b=b.replace(/\_\_+/g,"_");b=b.replace(/[^a-z0-9]+$/,"");b=b.replace(/^[^a-z]+/,
"");c.reserved_word(b)&&(b="x_"+b);return b},reservedwords:"meta typeguid left right datatype scope attribute relationship property link class future update insert delete replace create destroy default sort limit offset optional pagesize cursor index !index for while as in is if else return count function read write select var connect this self super xml sql mql any all macro estimate-count",typeonlywords:"guid id object domain name key type keys value timestamp creator permission namespace unique schema reverse",
_reserved_word:null,reserved_word:function(b){c._reserved_word||(c._reserved_word={},d.each([c.reservedwords,c.typeonlywords],function(a,b){d.each(b.split(" "),function(a,b){c._reserved_word[b]=1})}));return 1===c._reserved_word[b]},fast:/^[A-Za-z0-9](?:[_-]?[A-Za-z0-9])*$/,slow:/^(?:[A-Za-z0-9]|\$[A-F0-9]{4})(?:[_-]?[A-Za-z0-9]|[_-]?\$[A-F0-9]{4})*$/,schema:/^[a-z](?:_?[a-z0-9])*$/,test:function(b,a){return a?c.schema.test(b):c.fast.test(b)||c.slow.test(b)}})})(jQuery);
(function(d){d.fn.validate_input=function(b){return this.each(function(){var a=d(this);if(a.is(":text")){var e=a.data("$.validate_input");e&&e._destroy();e=new c(this,b);a.data("$.validate_input",e)}})};var c=d.validate_input=function(b,a){if("function"!==typeof(this.options=d.extend(!0,{},c.defaults,a)).validator)throw"A validator is required";this.input=d(b);this.init();var e=this;this.input.bind("remove",function(){e._destroy()});return this};c.prototype={init:function(){var b=this;this.input.bind("keyup.validate_input",
function(a){b.textchange(a)}).bind(d.browser.msie?"paste.validate_input":"input.validate_input",function(a){b.textchange(a)}).bind("keypress.validate_input",function(a){13===a.keyCode&&b.validate(!0)}).bind("blur.validate_input",function(){b.validate(!0)})},_destroy:function(){this.input.unbind(".validate_input")},valid:function(b){this.input.trigger("valid",b)},invalid:function(b,a){this.input.trigger("invalid",a)},empty:function(){this.input.trigger("empty")},textchange:function(){clearTimeout(this.textchange_timeout);
var b=this;this.textchange_timeout=setTimeout(function(){b.validate()},200)},validate:function(b){b&&clearTimeout(this.textchange_timeout);var b=this.options,a=d.trim(this.input.val());if(""===a)return this.empty();try{var c=b.validator(a,b);return this.valid(c)}catch(f){return this.invalid(a,""+f)}}};d.extend(c,{defaults:{validator:function(b){return{text:b,value:b}}},log:function(){},invalid:function(b,a,c,d){throw Error("Invalid "+c+(d?": "+d:""));},text:function(b,a){return 4096<b.lengh?this.invalid(b,
a,type,"Text too long"):{text:b,value:b}},topic:function(){return c.defaults.validator},enumerated:function(){return c.defaults.validator},"boolean":function(){return c.defaults.validator},uri:function(b,a){var d=c.uri.regex;d||(d=c.uri.regex=/^(https?|ftp):\/\/(((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:)*@)?(((\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5]))|((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?)(:\d*)?)(\/((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)+(\/(([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)*)*)?)?(\?((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|[\uE000-\uF8FF]|\/|\?)*)?(\#((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|\/|\?)*)?$/i);
return d.test(b)?{text:b,value:b}:c.invalid(b,a,"uri")},"int":function(b,a){return c.number.parse(b,a,!1)},"float":function(b,a){return c.number.parse(b,a,!0)},number:function(b,a,d){return c.number.parse(b,a,d)},datetime:function(){return c.defaults.validator},mqlkey:function(b,a){var d=c.mqlkey.regex;d||(d=c.mqlkey.regex=/^[A-Za-z0-9][A-Za-z0-9_-]*$/);return d.test(b)?{text:b,value:b}:c.invalid(b,a,"mqlkey")}});d.extend(c.number,{parse:function(b,a,d){a=null;a=d?Globalize.parseFloat(b):Globalize.parseInt(b,
10);if(isNaN(a))throw c.invalid("number",b);if(d){var b="n",d=""+a,f=d.indexOf(".");-1!==f&&(b="n"+d.substr(f+1).length);return{value:a,text:Globalize.format(a,b)}}return{value:a,text:Globalize.format(a,"n0")}}})})(jQuery,window.Globalize);
(function(d){d.fn.data_input=function(c){return this.each(function(){var b=d(this),a=b.data("$.data_input");a&&a._destroy();a=new d.data_input(this,c);b.data("$.data_input",a)})};d.data_input=function(c,b){this.options=d.extend(!0,{},b);this.container=d(c);this.metadata=this.container.metadata();this.input=d(":input",this.container);this.init();var a=this;this.input.bind("remove",function(){a._destroy()})};d.data_input.prototype={init:function(){var c=this,b=this.container,a=this.input,e=this.options;
a.bind("focusin.data_input",function(){c.container.addClass("focus")}).bind("focusout.data_input",function(){c.container.removeClass("focus")}).bind("valid.data_input",function(a,b){a.stopPropagation();var d={name:c.input.attr("name")};b.id?d.id=b.id:b.create_new?(d.create_new=b.create_new,d.lang=c.metadata.lang||e.lang):(d.value=b.value,"/type/text"===c.metadata.type?d.lang=c.metadata.lang||e.lang:"/type/key"===c.metadata.type&&(d.namespace=b.namespace));c.container.data("data",d);c.container.removeClass("error").addClass("valid");
c.container.trigger("valid")}).bind("invalid.data_input",function(a){a.stopPropagation();c.container.removeData("data");c.container.removeClass("valid").addClass("error");c.container.trigger("invalid")}).bind("empty.data_input",function(a){a.stopPropagation();a={name:c.input.attr("name")};c.metadata&&c.metadata.lang&&(a.lang=c.metadata.lang);c.container.data("data",a);c.container.removeClass("valid").removeClass("error");c.container.trigger("empty")}).bind("keypress.data_input",function(a){13===a.keyCode&&
!a.isDefaultPrevented()&&c.container.trigger("submit")}).bind("keyup.data_input",function(a){27===a.keyCode&&c.container.trigger("cancel")});if(b.is(".topic")){var b=c.metadata.type,f=null;e.suggest_impl&&(f=e.suggest_impl.instance(b,!0,c.metadata&&c.metadata.lang||e.lang,e.strict));var g=null;e.structure&&c.options.incompatible_types&&(g=e.structure.expected_type.included_types,f=c.options.incompatible_types.suggest_options(b,g,f));a.validate_topic(d.extend({incompatible_types:c.options.incompatible_types,
expected_type:b,included_types:g},f)).bind("valid.data_input",function(a,b){c.fb_select(b)}).bind("invalid.data_input",function(){c.fb_textchange()});this.metadata&&this.metadata.id&&(a.data("data.suggest",this.metadata),this.validate())}else if(b.is(".text"))a.validate_input({validator:d.validate_input.text});else if(b.is(".datetime"))a.validate_datetime({lang:e.lang}).bind("valid.data_input",function(a,b){c.fb_select(b)}).bind("invalid.data_input",function(){c.fb_textchange()}),this.metadata&&this.metadata.value&&
(a.data("data.suggest",this.metadata),this.validate());else if(b.is(".enumerated"))a.validate_enumerated().bind("valid.data_input",function(a,b){c.fb_select(b)}).bind("invalid.data_input",function(){c.fb_textchange()}),this.metadata&&this.metadata.id&&this.validate();else if(b.is(".int"))a.validate_input({validator:d.validate_input["int"],lang:e.lang});else if(b.is(".float"))a.validate_input({validator:d.validate_input["float"],lang:e.lang});else if(b.is(".uri"))a.validate_input({validator:d.validate_input.uri});
else if(b.is(".boolean"))a.validate_boolean();else if(b.is(".enumeration"))a.validate_input({validator:d.validate_input.mqlkey});else if(b.is(".key"))a.validate_key(e,this.metadata);else if(b.is(".rawstring"))a.validate_input({validator:d.validate_input.text});else throw Error("Invalid data-input: "+b.attr("class"));},_destroy:function(){this.input.unbind(".data_input")},validate:function(){var c=this.input;d.each("$.validate_topic $.validate_datetime $.validate_input $.validate_enumerated $.validate_boolean $.validate_key".split(" "),
function(b,a){var d=c.data(a);if(d){d.validate(true);return false}})},reset:function(){this.container.removeData("data");this.input.is(":text")?this.input.val(""):this.input.is("select")?this.input[0].selectedIndex=0:this.input.is(":radio")&&this.input.each(function(){this.checked=!1})},fb_textchange:function(){},fb_select:function(){},ajax_beforeSend:function(c){this.xhr_queue||(this.xhr_queue=[]);this.xhr_queue.push(c);this.container.trigger("loading")},ajax_complete:function(c){this.xhr_queue||
(this.xhr_queue=[]);for(var b=0,a=this.xhr_queue.length;b<a;b++)if(c===this.xhr_queue[b]){this.xhr_queue.splice(b,1);break}0===this.xhr_queue.length&&this.container.trigger("loading_complete")}};d.fn.validate_topic=function(c){return this.each(function(){var b=d(this);if(b.is(":text")){var a=b.data("$.validate_topic");a&&a._destroy();a=new d.validate_topic(this,c);b.data("$.validate_topic",a)}})};d.validate_topic=function(c,b){this.options=d.extend(!0,{},b);this.input=d(c);this.init()};d.validate_topic.prototype=
{init:function(){var c=this;this.input.suggest(this.options).bind("fb-textchange.validate_topic",function(){""===c.input.val()?c.empty():c.invalid()}).bind("fb-select.validate_topic",function(b,a){c.input.val(null!=a.name?a.name:a.id);c.incompatible_types_check(a)}).bind("fb-select-new.validate_topic",function(b,a){c.valid(a)})},incompatible_types_check:function(c){var b=this;b.options.incompatible_types&&b.options.expected_type?b.options.incompatible_types.check(c,b.options.expected_type,b.options.included_types,
{compatible:function(){b.valid(c)},incompatible:b.options.incompatible_types.inline_incompatible_callback({onConfirm:function(){b.valid(c)}},b.input)}):this.valid(c)},invalid:function(){this.input.trigger("invalid")},valid:function(c){"string"===typeof c&&(c={create_new:c});this.input.trigger("valid",c)},empty:function(){this.input.trigger("empty")},_destroy:function(){this.input.unbind(".validate_topic")},validate:function(){if(""===this.input.val())this.empty();else{var c=this.input.data("data.suggest");
c?this.valid(c):this.invalid()}}};d.fn.validate_datetime=function(c){return this.each(function(){var b=d(this);if(b.is(":text")){var a=b.data("$.validate_datetime");a&&a._destroy();a=new d.validate_datetime(this,c);b.data("$.validate_datetime",a)}})};d.validate_datetime=function(c,b){this.options=d.extend(!0,{},b);this.input=d(c);this.init()};d.validate_datetime.prototype={init:function(){var c=this;this.input.suggest_datetime(this.options).bind("fb-textchange.validate_datetime",function(){""===c.input.val()?
c.empty():c.invalid()}).bind("fb-select.validate_datetime",function(b,a){c.input.val(a.name);c.validate()})},invalid:function(){this.input.trigger("invalid")},valid:function(c){this.input.trigger("valid",c)},empty:function(){this.input.trigger("empty")},_destroy:function(){this.input.unbind(".validate_datetime")},validate:function(){if(""===this.input.val())this.empty();else{var c=this.input.data("data.suggest");c?this.valid(c):this.invalid()}}};d.fn.validate_enumerated=function(c){return this.each(function(){var b=
d(this);if(b.is("select")){var a=b.data("$.validate_enumerated");a&&a._destroy();a=new d.validate_enumerated(this,c);b.data("$.validate_enumerated",a)}})};d.validate_enumerated=function(c,b){this.options=d.extend(!0,{},b);this.input=d(c);this.init()};d.validate_enumerated.prototype={init:function(){var c=this;this.input.bind("change.validate_enumerated, keypress.validate_enumerated",function(){0===this.selectedIndex?c.empty():c.valid({text:d(":selected",this).text(),id:this.value})})},invalid:function(){this.input.trigger("invalid")},
valid:function(c){this.input.trigger("valid",c);this.input.trigger("fb-select",c)},empty:function(){this.input.trigger("empty")},_destroy:function(){this.input.unbind(".validate_enumerated")},validate:function(){var c=this.input[0];0<c.selectedIndex?this.valid({text:d(":selected",this.input).text(),id:c.value}):this.empty()}};d.fn.validate_boolean=function(c){var b,a;this.each(function(){var c=d(this);c.is(":radio")&&("true"===c.val().toLowerCase()?b=c:"false"===c.val().toLowerCase()&&(a=c))});if(b&&
a){var e=b.data("$.validate_boolean");e&&e._destroy();e=new d.validate_boolean(b,a,c);b.data("$.validate_boolean",e)}else throw"$.fn.validate_boolean requires two radios: true and false";return this};d.validate_boolean=function(c,b,a){this.options=d.extend(!0,{},a);this.tradio=c;this.fradio=b;this.input=this.tradio;this.init()};d.validate_boolean.prototype={init:function(){var c=this;this.tradio.bind("change.validate_boolean",function(){c.validate()});this.fradio.bind("change.validate_boolean",function(){c.validate()})},
_destroy:function(){this.input.unbind(".validate_boolean")},valid:function(c){this.input.trigger("valid",c)},empty:function(){this.input.trigger("empty")},validate:function(){this.tradio.is(":checked")?this.valid({text:this.tradio.text(),value:!0}):this.fradio.is(":checked")?this.valid({text:this.fradio.text(),value:!1}):this.empty()}};d.fn.validate_key=function(c,b){var a,e;this.each(function(){var b=d(this);b.is(":text")&&(b.is(".key-namespace")?a=b:b.is(".key-value")&&(e=b))});if(a&&e){var f=e.data("$.validate_key");
f&&f._destroy();f=new d.validate_key(a,e,c);a.data("$.validate_key",f);b&&(b.namespace&&b.value)&&(a.data("data.suggest",{id:b.namespace}),e.val(b.value))}else throw"$.fn.validate_key requires two inputs: namespace and value";return this};d.validate_key=function(c,b,a){this.options=d.extend(!0,{},a);this.key_namespace_input=c;this.key_value_input=b;this.input=this.key_namespace_input;this.init()};d.validate_key.prototype={init:function(){var c=this,b=null;this.options.suggest_impl&&(b="/type/namespace/keys"!=
this.key_value_input.attr("name")?this.options.suggest_impl.instance("/type/namespace"):d.extend({},this.options.suggest_impl.service_defaults));this.key_namespace_input.suggest(b).bind("fb-textchange.validate_key",function(){c.validate()}).bind("fb-select.validate_key",function(a,b){c.key_namespace_input.val(b.name||b.id);c.validate()});this.key_value_input.validate_input({validator:d.validate_input.mqlkey}).bind("valid",function(a){a.stopPropagation();c.validate()}).bind("invalid",function(a){a.stopPropagation();
c.validate()}).bind("empty",function(a){a.stopPropagation();c.validate()})},_destroy:function(){this.key_namespace_input.unbind(".validate_key");this.key_value_input.unbind()},invalid:function(){this.input.trigger("invalid")},valid:function(c){this.input.trigger("valid",c)},empty:function(){this.input.trigger("empty")},validate:function(){this.is_valid_key_namespace()&&this.is_valid_key_value()?this.valid({namespace:this.key_namespace_input.data("data.suggest").id,value:this.key_value_input.val(),
text:this.key_value_input.val()}):""===this.key_namespace_input.val()&&""===this.key_value_input.val()?this.empty():this.invalid()},is_valid_key_namespace:function(){return null!=this.key_namespace_input.data("data.suggest")},is_valid_key_value:function(){try{return d.validate_input.mqlkey(this.key_value_input.val()),!0}catch(c){return!1}}}})(jQuery);
(function(d,c){var b=window.formlib={status:c,init:function(a){var d=a.event_prefix||"form.";a.form.bind(d+"submit",function(){b.submit(a)}).bind(d+"cancel",function(){b.cancel(a)}).bind(d+"error",function(d,e){a.form.removeClass("loading");b.disable_submit(a);c.error(e,!0)}).bind(d+"success",function(){a.form.removeClass("loading")}).bind(d+"valid",function(){b.enable_submit(a)}).bind(d+"invalid",function(){b.disable_submit(a)});b.init_submit_cancel(a);a.init(a)},submit:function(a){!a.form.is(".loading")&&
b.is_submit_enabled(a)&&(document.activeElement&&d(document.activeElement).blur(),a.validate(a)&&(a.form.addClass("loading"),a.submit(a,b.default_submit_ajax_options(a))))},cancel:function(){},init_inline_add_form:function(a){var d=a.event_prefix||"form.inline_add_form.";a.edit_row.bind(d+"submit",function(){b.submit_inline_add_form(a)}).bind(d+"cancel",function(){b.cancel_inline_add_form(a)}).bind(d+"error",function(d,e){a.edit_row.removeClass("loading");b.disable_submit(a);c.error(e,!0)}).bind(d+
"success",function(){a.edit_row.removeClass("loading")}).bind(d+"valid",function(){b.enable_submit(a)}).bind(d+"invalid",function(){b.disable_submit(a)});b.init_submit_cancel(a);a.trigger&&a.trigger.parents(".trigger-row:first").hide();a.body.append(a.edit_row).append(a.submit_row);a.init(a)},submit_inline_add_form:function(a){!a.edit_row.is(".loading")&&b.is_submit_enabled(a)&&(document.activeElement&&d(document.activeElement).blur(),a.validate(a)&&(a.edit_row.addClass("loading"),a.submit(a,b.default_submit_ajax_options(a))))},
submit_and_continue_inline_add_form:function(a,b){var c=b.beforeSend,g=b.complete,m=d.extend({},b,{beforeSend:function(b,e){c&&c.apply(this,arguments);var g=a.edit_row.clone().addClass("edit-row-submitting");fb.disable(d(":input",g));b._cloned_edit_row=g;a.edit_row.before(g);a.reset(a)},complete:function(a){g&&g.apply(this,arguments);delete a._cloned_edit_row}});d.ajax(m)},success_inline_add_form:function(a,c,d){d&&d._cloned_edit_row?d._cloned_edit_row.replaceWith(c):(a.edit_row.before(c),a.reset(a));
b.animate_new_row(c);a.edit_row.trigger(a.event_prefix+"success")},cancel_inline_add_form:function(a){a.edit_row.remove();a.submit_row.remove();a.trigger&&a.trigger.parents(".trigger-row:first").show()},animate_new_row:function(a){a.addClass("new-row",1E3,function(){a.removeClass("new-row",1E3)})},init_inline_edit_form:function(a){var d=a.event_prefix||"form.inline_edit_form.";a.edit_row.bind(d+"submit",function(){b.submit_inline_edit_form(a)}).bind(d+"cancel",function(){b.cancel_inline_edit_form(a)}).bind(d+
"error",function(d,e){a.edit_row.removeClass("loading");b.disable_submit(a);c.error(e,!0)}).bind(d+"success",function(){a.edit_row.removeClass("loading")}).bind(d+"valid",function(){b.enable_submit(a)}).bind(d+"invalid",function(){b.disable_submit(a)});b.init_submit_cancel(a);a.row.hide();a.row.before(a.edit_row).before(a.submit_row);a.init(a)},submit_inline_edit_form:function(a){!a.edit_row.is(".loading")&&b.is_submit_enabled(a)&&(document.activeElement&&d(document.activeElement).blur(),a.validate(a)&&
(a.edit_row.addClass("loading"),a.submit(a,b.default_submit_ajax_options(a))))},success_inline_edit_form:function(a,c){a.row.replaceWith(c);a.row=c;b.animate_new_row(c);a.edit_row.trigger(a.event_prefix+"cancel")},cancel_inline_edit_form:function(a){a.edit_row.remove();a.submit_row.remove();a.row.show()},success_inline_delete:function(a,c,f){a.hide().addClass("old-row");a.after(c);c.append(a);b.animate_new_row(c);f&&(a=d('<a href="#">undo</a><span class="divider">|</span>'),d(".msg-default",c).next().append(a),
a.click(function(){f();return!1}))},success_inline_delete_undo:function(a){var c=d(".old-row",a);a.before(c);c.show().removeClass("old-row");a.remove();b.animate_new_row(c)},init_modal_form:function(a){d(document.body).append(a.form.hide());var e=a.event_prefix||"form.modal_form.";a.form.bind(e+"submit",function(){b.submit_modal_form(a)}).bind(e+"cancel",function(){b.cancel_modal_form(a)}).bind(e+"error",function(d,e){a.form.removeClass("loading");b.disable_submit(a);c.error(e,!0)}).bind(e+"success",
function(){a.form.removeClass("loading")}).bind(e+"valid",function(){b.enable_submit(a)}).bind(e+"invalid",function(){b.disable_submit(a)});b.init_submit_cancel(a);a.form.data("overlay")&&a.form.removeData("overlay");a.form.overlay({close:".modal-buttons .cancel",closeOnClick:!1,load:!0,fixed:!1,mask:{color:"#000",loadSpeed:200,opacity:0.5},onLoad:function(){a.overlay=this;a.init(a)}})},submit_modal_form:function(a){!a.form.is(".loading")&&b.is_submit_enabled(a)&&(document.activeElement&&d(document.activeElement).blur(),
a.validate(a)&&(a.form.addClass("loading"),a.submit(a,b.default_submit_ajax_options(a))))},cancel_modal_form:function(a){a.form.data("overlay").close();a.form.next("#exposeMask").hide()},init_submit_cancel:function(a){var c=a.form||a.edit_row,f=a.form||a.submit_row,g=a.event_prefix,a=d(".save",f).click(function(){c.trigger(g+"submit")});b.disable(a);d(".cancel",f).click(function(){c.trigger(g+"cancel")});d(":input",c).keyup(function(a){27===a.keyCode&&c.trigger(g+"cancel")})},disable:function(a){d(a).attr("disabled",
"disabled").addClass("disabled")},enable:function(a){d(a).removeAttr("disabled").removeClass("disabled")},disable_submit:function(a){b.disable(d(".save",a.form||a.submit_row))},enable_submit:function(a){b.enable(d(".save",a.form||a.submit_row))},is_submit_enabled:function(a){return!d(".save",a.form||a.submit_row).is(":disabled")},init_mqlkey:function(a,b){return a.next(".key-status").removeClass("valid invalid loading").text("").removeAttr("title").end().mqlkey(b).bind("valid",function(){d(this).next(".key-status").removeClass("invalid loading").addClass("valid").text("valid").attr("title",
"Key is available")}).bind("invalid",function(a,b){d(this).next(".key-status").removeClass("valid loading").addClass("invalid").text("invalid").attr("title",b)}).bind("textchange",function(){d(this).next(".key-status").removeClass("valid invalid").text("loading").addClass("loading")})},validate_mqlkey:function(a,b){var c=b.next(".key-status"),d=b.val();return""===d?(b.trigger(a.event_prefix+"error","Key is required"),!1):d===b.data("mqlkey").original?!0:c.is(".invalid")?(b.trigger(a.event_prefix+
"error",c.attr("title")),!1):c.is(".loading")?!1:!0},default_begin_ajax_options:function(){return d.extend(b._default_ajax_options("GET"),{beforeSend:function(){c.doing("Loading...")},complete:function(){this.formlib_error||c.clear()}})},status_doing:function(a,b){setTimeout(function(){c.doing(a,b)})},status_info:function(a,b){setTimeout(function(){c.info(a,b)})},status_warning:function(a,b){setTimeout(function(){c.warning(a,b)})},status_success:function(a,b){setTimeout(function(){c.success(a,b)})},
status_error:function(a,b){setTimeout(function(){c.error(a,b)})},default_submit_ajax_options:function(a){var a=a||{},e=d.extend(b._default_ajax_options("POST"),a.ajax,{beforeSend:function(){this.formlib_options=a;c.doing("Saving...");d.isFunction(a.beforeSend)&&a.beforeSend.apply(this,arguments)},complete:function(){this.formlib_error||c.clear();d.isFunction(a.complete)&&a.complete.apply(this,arguments)}}),f=a.submit_row||a.form;f&&d("input[type=hidden]",f).each(function(){e.data[this.name]=this.value});
return e},_default_ajax_options:function(a){return{data:{},dataType:"json",type:a||"GET",success:function(a,c,g){if(!b.check_ajax_success(a,c,g))return this._error(g);if(d.isFunction(this.onsuccess))this.onsuccess(a,c,g)},error:function(a){return this._error(a)},_error:function(a){if(401===a.status)c.info("Authorizing..."),d(window).trigger("fb.user.unauthorized");else{console.error(a.responseText);this.formlib_error=!0;var f=b.get_error_message(a.responseText);if(d.isFunction(this.onerror))this.onerror(f,
a);else a=null,this.formlib_options&&(this.formlib_options.form?(this.formlib_options.form.trigger(this.formlib_options.event_prefix+"cancel"),a=this.formlib_options.form):a=this.formlib_options.edit_row),a?a.trigger(this.formlib_options.event_prefix+"error",f):c.error(f,!0)}}}},check_ajax_success:function(a,c,d){return b.check_api_response(a,c,d)},check_api_response:function(a,b,f){if(d.isPlainObject(a)){if(a.error&&401===a.error.code)return c.info("Authorizing..."),d(window).trigger("fb.user.unauthorized"),
!1;if("/api/status/ok"!==a.code)return!1}else if(200!==f.status)return!1;return!0},get_error_message:function(a){var b=null;try{var c=JSON.parse(a);c&&(c.error&&c.error.message?b=c.error.message:d.isArray(c.messages)&&c.messages.length&&(b=c.messages[0].message))}catch(g){}b||(b=a);b&&0===b.indexOf("JS exception: Error: ")&&(b=b.substring(21));return b}}})(jQuery,window.freebase.status);
(function(d,c,b){var a=c.flag.edit={merge_begin:function(){d.ajax(d.extend(b.default_begin_ajax_options(),{url:c.h.ajax_url("lib/flag/merge_begin.ajax"),data:{id:c.c.id},onsuccess:function(e){e=d(e.result.html);e={event_prefix:"fb.flag.merge.",init:a.merge_init,validate:a.merge_validate,submit:a.merge_submit,ajax:{url:c.h.ajax_url("lib/flag/merge_submit.ajax")},form:e};b.init_modal_form(e)}}))},merge_init:function(a){var f=d(".data-input:first",a.form);f.data_input({lang:c.lang,suggest_impl:c.suggest_options,
strict:!0}).bind("valid",function(){b.enable_submit(a)}).bind("invalid",function(){b.disable_submit(a)}).bind("empty",function(){b.disable_submit(a)});d(":input",f).focus()},merge_validate:function(a){return(a=d(".data-input:first",a.form).data("data"))&&a.id},merge_submit:function(a,c){var g=d(".data-input:first",a.form).data("data");c.data[g.name]=g.id;d.ajax(d.extend(c,{onsuccess:function(c){c&&c.result?c.result.info?b.status_info(c.result.info):c.result.error&&b.status_error(c.result.error):b.status_error("Oops! Something went wrong. Please try again.");
b.cancel_modal_form(a)}}))},split_begin:function(b){a.flag_submit(b,"split")},delete_begin:function(b){a.flag_submit(b,"delete")},offensive_begin:function(b){a.flag_submit(b,"offensive")},flag_submit:function(a,f){d.ajax(d.extend(b.default_submit_ajax_options(),{url:c.h.ajax_url("lib/flag/flag_submit.ajax"),data:{id:c.c.id,kind:f},onsuccess:function(a){a&&a.result?a.result.info?b.status_info(a.result.info):a.result.error&&b.status_error(a.result.error):b.status_error("Oops! Something went wrong. Please try again.")}}))},
undo_begin:function(a,f){d.ajax(d.extend(b.default_submit_ajax_options(),{url:c.h.ajax_url("lib/flag/undo_submit.ajax"),data:{id:f},onsuccess:function(){a.parents(".page-flag-kind:first").remove()}}))}}})(jQuery,window.freebase,window.formlib);
