
/*
 * Copyright 2010, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Additional Licenses for Third Party components can be found here:
 * http://wiki.freebase.com/wiki/Freebase_Site_License
 *
 */
/*
 
 jQuery Tools @VERSION / Expose - Dim the lights

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/toolbox/expose.html

 Since: Mar 2010
 Date: @DATE 
 
 jQuery Tools @VERSION Overlay - Overlay base. Extend it.

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/overlay/

 Since: March 2008
 Date: @DATE 
*/
(function(d){function e(){if(d.browser.msie){var h=d(document).height(),k=d(window).height();return[window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth,h-k<20?k:h]}return[d(document).width(),d(document).height()]}function c(h){if(h)return h.call(d.mask)}d.tools=d.tools||{version:"@VERSION"};var a;a=d.tools.expose={conf:{maskId:"exposeMask",loadSpeed:"slow",closeSpeed:"fast",closeOnClick:true,closeOnEsc:true,zIndex:9998,opacity:0.8,startOpacity:0,color:"#fff",onLoad:null,
onClose:null}};var b,f,g,i,j;d.mask={load:function(h,k){if(g)return this;if(typeof h=="string")h={color:h};h=h||i;i=h=d.extend(d.extend({},a.conf),h);b=d("#"+h.maskId);if(!b.length){b=d("<div/>").attr("id",h.maskId);d("body").append(b)}var l=e();b.css({position:"absolute",top:0,left:0,width:l[0],height:l[1],display:"none",opacity:h.startOpacity,zIndex:h.zIndex});h.color&&b.css("backgroundColor",h.color);if(c(h.onBeforeLoad)===false)return this;h.closeOnEsc&&d(document).bind("keydown.mask",function(m){m.keyCode==
27&&d.mask.close(m)});h.closeOnClick&&b.bind("click.mask",function(m){d.mask.close(m)});d(window).bind("resize.mask",function(){d.mask.fit()});if(k&&k.length){j=k.eq(0).css("zIndex");d.each(k,function(){var m=d(this);/relative|absolute|fixed/i.test(m.css("position"))||m.css("position","relative")});f=k.css({zIndex:Math.max(h.zIndex+1,j=="auto"?0:j)})}b.css({display:"block"}).fadeTo(h.loadSpeed,h.opacity,function(){d.mask.fit();c(h.onLoad)});g=true;return this},close:function(){if(g){if(c(i.onBeforeClose)===
false)return this;b.fadeOut(i.closeSpeed,function(){c(i.onClose);f&&f.css({zIndex:j})});d(document).unbind("keydown.mask");b.unbind("click.mask");d(window).unbind("resize.mask");g=false}return this},fit:function(){if(g){var h=e();b.css({width:h[0],height:h[1]})}},getMask:function(){return b},isLoaded:function(){return g},getConf:function(){return i},getExposed:function(){return f}};d.fn.mask=function(h){d.mask.load(h);return this};d.fn.expose=function(h){d.mask.load(h,this);return this}})(jQuery);
(function(d){function e(b,f){var g=this,i=b.add(g),j=d(window),h,k,l,m=d.tools.expose&&(f.mask||f.expose),o=Math.random().toString().slice(10);if(m){if(typeof m=="string")m={color:m};m.closeOnClick=m.closeOnEsc=false}var p=f.target||b.attr("rel");k=p?d(p):b;if(!k.length)throw"Could not find Overlay: "+p;b&&b.index(k)==-1&&b.click(function(n){g.load(n);return n.preventDefault()});d.extend(g,{load:function(n){if(g.isOpened())return g;var r=a[f.effect];if(!r)throw'Overlay: cannot find effect : "'+f.effect+
'"';f.oneInstance&&d.each(c,function(){this.close(n)});n=n||d.Event();n.type="onBeforeLoad";i.trigger(n);if(n.isDefaultPrevented())return g;l=true;m&&d(k).expose(m);var q=f.top,t=f.left,u=k.outerWidth({margin:true}),v=k.outerHeight({margin:true});if(typeof q=="string")q=q=="center"?Math.max((j.height()-v)/2,0):parseInt(q,10)/100*j.height();if(t=="center")t=Math.max((j.width()-u)/2,0);r[0].call(g,{top:q,left:t},function(){if(l){n.type="onLoad";i.trigger(n)}});m&&f.closeOnClick&&d.mask.getMask().one("click",
g.close);f.closeOnClick&&d(document).bind("click."+o,function(s){d(s.target).parents(k).length||g.close(s)});f.closeOnEsc&&d(document).bind("keydown."+o,function(s){s.keyCode==27&&g.close(s)});return g},close:function(n){if(!g.isOpened())return g;n=n||d.Event();n.type="onBeforeClose";i.trigger(n);if(!n.isDefaultPrevented()){l=false;a[f.effect][1].call(g,function(){n.type="onClose";i.trigger(n)});d(document).unbind("click."+o).unbind("keydown."+o);m&&d.mask.close();return g}},getOverlay:function(){return k},
getTrigger:function(){return b},getClosers:function(){return h},isOpened:function(){return l},getConf:function(){return f}});d.each("onBeforeLoad,onStart,onLoad,onBeforeClose,onClose".split(","),function(n,r){d.isFunction(f[r])&&d(g).bind(r,f[r]);g[r]=function(q){d(g).bind(r,q);return g}});h=k.find(f.close||".close");if(!h.length&&!f.close){h=d('<a class="close"></a>');k.prepend(h)}h.click(function(n){g.close(n)});f.load&&g.load()}d.tools=d.tools||{version:"@VERSION"};d.tools.overlay={addEffect:function(b,
f,g){a[b]=[f,g]},conf:{close:null,closeOnClick:true,closeOnEsc:true,closeSpeed:"fast",effect:"default",fixed:!d.browser.msie||d.browser.version>6,left:"center",load:false,mask:null,oneInstance:true,speed:"normal",target:null,top:"10%"}};var c=[],a={};d.tools.overlay.addEffect("default",function(b,f){var g=this.getConf(),i=d(window);if(!g.fixed){b.top+=i.scrollTop();b.left+=i.scrollLeft()}b.position=g.fixed?"fixed":"absolute";this.getOverlay().css(b).fadeIn(g.speed,f)},function(b){this.getOverlay().fadeOut(this.getConf().closeSpeed,
b)});d.fn.overlay=function(b){var f=this.data("overlay");if(f)return f;if(d.isFunction(b))b={onBeforeLoad:b};b=d.extend(true,{},d.tools.overlay.conf,b);this.each(function(){f=new e(d(this),b);c.push(f);d(this).data("overlay",f)});return b.api?f:this}})(jQuery);
(function(d){d.fn.mqlkey=function(c){return this.each(function(){var a=d(this);if(a.is(":text")){var b=a.data("mqlkey");b&&b._destroy();b=new e(this,c);a.data("mqlkey",b)}})};var e=d.mqlkey=function(c,a){this.options=d.extend(true,{},e.defaults,a);this.options.jsonp=e.use_jsonp(this.options.mqlread_url);this.input=d(c);this.original=this.input.val();this.init()};e.prototype={init:function(){var c=this;this.input.bind("keyup.mqlkey",function(a){c.textchange(a)}).bind(d.browser.msie?"paste.mqlkey":
"input.mqlkey",function(a){c.textchange(a)});if(this.options.source){this.source=d(this.options.source);this.source_generate=true;this.input.bind("change.mqlkey",function(){c.source_generate=false});this.source.bind("change.mqlkey",function(){if(c.source_generate){var a=e.from(c.source.val());c.input.val(a).trigger("keyup")}})}},_destroy:function(){this.input.unbind(".mqlkey");this.source&&this.source.unbind("change.mqlkey")},textchange:function(c){clearTimeout(this.textchange_timeout);var a=this;
this.textchange_timeout=setTimeout(function(){a.textchange_delay(c)},200)},textchange_delay:function(){this.input.trigger("textchange");var c=d.trim(this.input.val());return c===this.original&&c!==""?this.valid(c):e.reserved_word(c)?this.invalid(c,c+" is a reserved word."):e.test(c,this.options.schema)?c.length<this.options.minlen?this.invalid(c):this.options.check_key?this.check_key(c):this.valid(c):this.invalid(c)},check_key:function(c){var a=this;if(this.xhr){this.xhr.abort();this.xhr=null}var b=
{query:'{"query": {"id": null, "key": {"namespace": "'+this.options.namespace+'", "value": "'+c+'"}}}'};clearTimeout(this.check_key.timeout);var f={url:this.options.mqlread_url,data:b,success:function(g){if(g.code==="/api/status/ok")return g.result?a.invalid(c,"Key already exists"):a.valid(c)},error:function(g){if(g)return a.invalid(g.responseText())},dataType:a.options.jsonp?"jsonp":"json"};this.check_key.timeout=setTimeout(function(){a.ac_xhr=d.ajax(f)},200)},valid:function(c){this.input.trigger("valid",
c)},invalid:function(c,a){if(!a){a=this.options.minlen>1?"Key must be "+this.options.minlen+" or more alphanumeric characters":"Key must be alphanumeric";a+=", lowercase, begin with a letter and not end with a non-alphanumeric character. Underscores are allowed but not consecutively."}this.input.trigger("invalid",a)}};d.extend(e,{defaults:{minlen:1,check_key:true,namespace:"/",mqlread_url:"http://api.freebase.com/api/service/mqlread",source:null,schema:false},use_jsonp:function(c){if(!c)return false;
var a=window.location.href;a=a.substr(0,a.length-window.location.pathname.length);if(a===c)return false;return true},from:function(c){c=c.toLowerCase();c=c.replace(/[^a-z0-9]/g,"_");c=c.replace(/\_\_+/g,"_");c=c.replace(/[^a-z0-9]+$/,"");c=c.replace(/^[^a-z]+/,"");if(e.reserved_word(c))c="x_"+c;return c},reservedwords:"meta typeguid left right datatype scope attribute relationship property link class future update insert delete replace create destroy default sort limit offset optional pagesize cursor index !index for while as in is if else return count function read write select var connect this self super xml sql mql any all macro estimate-count",
typeonlywords:"guid id object domain name key type keys value timestamp creator permission namespace unique schema reverse",_reserved_word:null,reserved_word:function(c){if(!e._reserved_word){e._reserved_word={};d.each([e.reservedwords,e.typeonlywords],function(a,b){d.each(b.split(" "),function(f,g){e._reserved_word[g]=1})})}return e._reserved_word[c]===1},fast:/^[A-Za-z0-9](?:[_-]?[A-Za-z0-9])*$/,slow:/^(?:[A-Za-z0-9]|\$[A-F0-9]{4})(?:[_-]?[A-Za-z0-9]|[_-]?\$[A-F0-9]{4})*$/,schema:/^[a-z](?:_?[a-z0-9])*$/,
test:function(c,a){if(a)return e.schema.test(c);return e.fast.test(c)||e.slow.test(c)}})})(jQuery);
(function(d,e){e.require("dojo.date.stamp");e.require("dojo.date.locale");e.require("dojo.number");d.fn.validate_input=function(a){return this.each(function(){var b=d(this);if(b.is(":text")){var f=b.data("$.validate_input");f&&f._destroy();f=new c(this,a);b.data("$.validate_input",f)}})};var c=d.validate_input=function(a,b){var f=this.options=d.extend(true,{},c.defaults,b);if(typeof f.validator!=="function")throw"A validator is required";if(!f.lang)f.lang="/lang/en";f.lang=f.lang==="/lang/en"?["lang/en"]:
[f.lang,"/lang/en"];f.locales=[];d.each(f.lang,function(i,j){f.locales[i]=e.i18n.normalizeLocale(j.split("/").pop())});this.input=d(a);this.init();var g=this;this.input.bind("remove",function(){g._destroy()});return this};c.prototype={init:function(){var a=this;this.input.bind("keyup.validate_input",function(b){a.textchange(b)}).bind(d.browser.msie?"paste.validate_input":"input.validate_input",function(b){a.textchange(b)}).bind("keypress.validate_input",function(b){b.keyCode===13&&a.validate(true)}).bind("blur.validate_input",
function(){a.validate(true)})},_destroy:function(){this.input.unbind(".validate_input")},valid:function(a){this.input.trigger("valid",a)},invalid:function(a,b){this.input.trigger("invalid",b)},empty:function(){this.input.trigger("empty")},textchange:function(){clearTimeout(this.textchange_timeout);var a=this;this.textchange_timeout=setTimeout(function(){a.validate()},200)},validate:function(a){a&&clearTimeout(this.textchange_timeout);a=this.options;var b=d.trim(this.input.val());if(b==="")return this.empty();
try{return this.valid(a.validator(b,a))}catch(f){return this.invalid(b,""+f)}}};d.extend(c,{defaults:{validator:function(a){return{text:a,value:a}}},log:function(){},invalid:function(a,b,f,g){throw new Error("Invalid "+f+(g?": "+g:""));},text:function(a,b){if(a.lengh>4096)return this.invalid(a,b,type,"Text too long");return{text:a,value:a}},topic:function(){return c.defaults.validator},enumerated:function(){return c.defaults.validator},"boolean":function(){return c.defaults.validator},uri:function(a,
b){var f=c.uri.regex;if(!f)f=c.uri.regex=/^(https?|ftp):\/\/(((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:)*@)?(((\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5]))|((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?)(:\d*)?)(\/((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)+(\/(([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)*)*)?)?(\?((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|[\uE000-\uF8FF]|\/|\?)*)?(\#((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|\/|\?)*)?$/i;
if(f.test(a))return{text:a,value:a};return c.invalid(a,b,"uri")},"int":function(a,b){return c.number.parse(a,b,false)},"float":function(a,b){return c.number.parse(a,b,true)},number:function(a,b,f){return c.number.parse(a,b,f)},datetime:function(a,b){return c.datetime.parse(a,b)},mqlkey:function(a,b){var f=c.mqlkey.regex;if(!f)f=c.mqlkey.regex=/^[A-Za-z0-9][A-Za-z0-9_-]*$/;if(f.test(a))return{text:a,value:a};return c.invalid(a,b,"mqlkey")}});d.extend(c.number,{parse:function(a,b,f){var g=b&&b.locales||
["en"],i,j;i=0;for(j=g.length;i<j;i++){var h=g[i];b=e.number.parse(a,{locale:h});if(!isNaN(b)){a={};if(f){a.value=b;a.text=e.number.format(b,{locale:h})}else{a.value=e.number.round(b,0);a.text=e.number.format(a.value,{locale:h})}return a}}throw c.invalid("number",a);}});d.extend(c.datetime,{formats:["yyyy",["dateFormatItem-y"],"yyyy-MM",["dateFormatItem-yM","dateFormatItem-yMMM"],"yyyy-MM-dd",["dateFormat-short","dateFormat-medium","dateFormat-long"]],parse:function(a,b){if(!e.date.stamp._isoRegExp)e.date.stamp._isoRegExp=
/^(?:(-?\d{4})(?:-(\d{2})(?:-(\d{2}))?)?)?(?:T(\d{2}):(\d{2})(?::(\d{2})(.\d+)?)?((?:[+-](\d{2}):(\d{2}))|Z)?)?$/;var f=e.date.stamp.fromISOString(a);if(f)return{text:a,value:a,date:f};var g=b&&b.locales||["en"],i,j,h,k,l,m;i=0;for(j=g.length;i<j;i++){var o=g[i],p=e.date.locale._getGregorianBundle(o);h=0;for(k=c.datetime.formats.length;h<k;h+=2){var n=c.datetime.formats[h],r=c.datetime.formats[h+1];l=0;for(m=r.length;l<m;l++){var q=p[r[l]];if(q){q=i18n.normalize_pattern(q);try{f=e.date.locale.parse(a,
{datePattern:q,selector:"date",locale:o});return{text:a,value:e.date.locale.format(f,{datePattern:n,selector:"date"}),date:f}}catch(t){}}}}}throw c.invalid("datetime",a);}})})(jQuery,dojo);
(function(d){d.fn.data_input=function(e){return this.each(function(){var c=d(this),a=c.data("$.data_input");a&&a._destroy();a=new d.data_input(this,e);c.data("$.data_input",a)})};d.data_input=function(e,c){this.options=d.extend(true,{},d.data_input.defaults,c);this.container=d(e);this.metadata=this.container.metadata();this.input=d(":input",this.container);this.init();var a=this;this.input.bind("remove",function(){a._destroy()})};d.data_input.prototype={init:function(){var e=this,c=this.container,
a=this.input,b=this.options;a.bind("focusin.data_input",function(){e.container.addClass("focus")}).bind("focusout.data_input",function(){e.container.removeClass("focus")}).bind("valid.data_input",function(f,g){var i={name:e.input.attr("name")};if(g.id)i.id=g.id;else{i.value=g.value;if(e.metadata.type==="/type/text")i.lang=e.metadata.lang||b.lang}e.container.data("data",i);e.container.removeClass("error").addClass("valid");e.container.trigger("valid")}).bind("invalid.data_input",function(){e.container.removeData("data");
e.container.removeClass("valid").addClass("error");e.container.trigger("invalid")}).bind("empty.data_input",function(){var f={name:e.input.attr("name")};if(e.metadata&&e.metadata.lang)f.lang=e.metadata.lang;e.container.data("data",f);e.container.removeClass("valid").removeClass("error");e.container.trigger("empty")}).bind("keypress.data_input",function(f){f.keyCode===13&&!f.isDefaultPrevented()&&e.container.trigger("submit")}).bind("keyup.data_input",function(f){f.keyCode===27&&e.container.trigger("cancel")});
if(c.is(".topic")){c=d.extend(true,{},b.suggest,d.data_input.suggest_options(e.metadata.type));a.validate_topic(c).bind("valid.data_input",function(f,g){e.fb_select(g)}).bind("invalid.data_input",function(){e.fb_textchange()});if(this.metadata&&this.metadata.id){a.data("data.suggest",this.metadata);this.validate()}}else if(c.is(".text"))a.validate_input({validator:d.validate_input.text});else if(c.is(".datetime"))a.validate_input({validator:d.validate_input.datetime,lang:b.lang});else if(c.is(".enumerated")){a.validate_enumerated().bind("valid.data_input",
function(f,g){e.fb_select(g)}).bind("invalid.data_input",function(){e.fb_textchange()});this.metadata&&this.metadata.id&&this.validate()}else if(c.is(".int"))a.validate_input({validator:d.validate_input["int"],lang:b.lang});else if(c.is(".float"))a.validate_input({validator:d.validate_input["float"],lang:b.lang});else if(c.is(".uri"))a.validate_input({validator:d.validate_input.uri});else if(c.is(".boolean"))a.validate_boolean();else if(c.is(".enumeration"))a.validate_input({validator:d.validate_input.mqlkey});
else if(c.is(".rawstring"))a.validate_input({validator:d.validate_input.text});else throw new Error("Invalid data-input: "+c.attr("class"));},_destroy:function(){this.input.unbind(".data_input")},validate:function(){var e=this.input;d.each(["$.validate_topic","$.validate_input","$.validate_enumerated","$.validate_boolean"],function(c,a){var b=e.data(a);if(b){b.validate(true);return false}})},reset:function(){this.container.removeData("data");if(this.input.is(":text"))this.input.val("");else if(this.input.is("select"))this.input[0].selectedIndex=
0;else this.input.is(":radio")&&this.input.each(function(){this.checked=false})},fb_textchange:function(){},fb_select:function(){},ajax_beforeSend:function(e){if(!this.xhr_queue)this.xhr_queue=[];this.xhr_queue.push(e);this.container.trigger("loading")},ajax_complete:function(e){if(!this.xhr_queue)this.xhr_queue=[];for(var c=0,a=this.xhr_queue.length;c<a;c++)if(e===this.xhr_queue[c]){this.xhr_queue.splice(c,1);break}this.xhr_queue.length===0&&this.container.trigger("loading_complete")}};d.extend(d.data_input,
{defaults:{suggest:{service_url:"http://www.freebase.com",service_path:"/private/suggest",flyout_service_url:"http://www.freebase.com",flyout_service_path:"/private/flyout",mqlread_url:"http://api.freebase.com/api/service/mqlread",category:"object",type:"/common/topic"}},is_metaweb_system_type:function(e){return e.indexOf("/type/")===0||e.indexOf("/common/")===0&&e!=="/common/topic"||e.indexOf("/freebase/")===0&&e.indexOf("_profile")===e.length-8},suggest_options:function(e){var c={category:"instance",
type:e,type_strict:d.data_input.is_metaweb_system_type(e)?"any":"should"},a=["any","type:"+e,"without:fus","without:inst"];d.each(["user","domain","type"],function(b,f){if(e==="/freebase/"+f+"_profile"){a.push("type:/type/"+f);return false}});e==="/book/book_subject"&&a.push("type:/base/skosbase/skos_concept");c.filter="("+a.join(" ")+")";return c}});d.fn.validate_topic=function(e){return this.each(function(){var c=d(this);if(c.is(":text")){var a=c.data("$.validate_topic");a&&a._destroy();a=new d.validate_topic(this,
e);c.data("$.validate_topic",a)}})};d.validate_topic=function(e,c){this.options=d.extend(true,{},c);this.input=d(e);this.init()};d.validate_topic.prototype={init:function(){var e=this;this.input.suggest(this.options).bind("fb-textchange.validate_topic",function(){e.input.val()===""?e.empty():e.invalid()}).bind("fb-select.validate_topic",function(c,a){e.input.val(a.name!=null?a.name:a.id);e.valid(a)})},invalid:function(){this.input.trigger("invalid")},valid:function(e){this.input.trigger("valid",e)},
empty:function(){this.input.trigger("empty")},_destroy:function(){this.input.unbind(".validate_topic")},validate:function(){if(this.input.val()==="")this.empty();else{var e=this.input.data("data.suggest");e?this.valid(e):this.invalid()}}};d.fn.validate_enumerated=function(e){return this.each(function(){var c=d(this);if(c.is("select")){var a=c.data("$.validate_enumerated");a&&a._destroy();a=new d.validate_enumerated(this,e);c.data("$.validate_enumerated",a)}})};d.validate_enumerated=function(e,c){this.options=
d.extend(true,{},c);this.input=d(e);this.init()};d.validate_enumerated.prototype={init:function(){var e=this;this.input.bind("change.validate_enumerated, keypress.validate_enumerated",function(){this.selectedIndex===0?e.empty():e.valid({text:d(":selected",this).text(),id:this.value})})},invalid:function(){this.input.trigger("invalid")},valid:function(e){this.input.trigger("valid",e);this.input.trigger("fb-select",e)},empty:function(){this.input.trigger("empty")},_destroy:function(){this.input.unbind(".validate_enumerated")},
validate:function(){var e=this.input[0];e.selectedIndex>0?this.valid({text:d(":selected",this.input).text(),id:e.value}):this.empty()}};d.fn.validate_boolean=function(e){var c,a;this.each(function(){var f=d(this);if(f.is(":radio"))if(f.val().toLowerCase()==="true")c=f;else if(f.val().toLowerCase()==="false")a=f});if(c&&a){var b=c.data("$.validate_boolean");b&&b._destroy();b=new d.validate_boolean(c,a,e);c.data("$.validate_boolean",b)}return this};d.validate_boolean=function(e,c,a){this.options=d.extend(true,
{},a);this.tradio=e;this.fradio=c;this.input=this.tradio;this.init()};d.validate_boolean.prototype={init:function(){var e=this;this.tradio.bind("change.validate_boolean",function(){e.validate()})},_destroy:function(){this.input.unbind(".validate_boolean")},valid:function(e){this.input.trigger("valid",e)},empty:function(){this.input.trigger("empty")},validate:function(){if(this.tradio.is(":checked"))this.valid({text:this.tradio.text(),value:true});else this.fradio.is(":checked")?this.valid({text:this.fradio.text(),
value:false}):this.empty()}}})(jQuery);
(function(d,e){var c=window.formlib={init_inline_add_form:function(a){var b=a.event_prefix||"form.inline_add_form.";a.edit_row.bind(b+"submit",function(){c.submit_inline_add_form(a)}).bind(b+"cancel",function(){c.cancel_inline_add_form(a)}).bind(b+"error",function(f,g){c.error(a,g);a.edit_row.removeClass("loading")}).bind(b+"success",function(){a.edit_row.removeClass("loading")}).bind(b+"valid",function(){c.enable_submit(a)}).bind(b+"invalid",function(){c.disable_submit(a)});c.init_submit_cancel(a);
a.trigger&&a.trigger.parents(".trigger-row:first").hide();a.body.append(a.head_row).append(a.edit_row).append(a.submit_row);a.init(a)},submit_inline_add_form:function(a){if(!a.edit_row.is(".loading"))if(c.is_submit_enabled(a)){document.activeElement&&d(document.activeElement).blur();c.clear_message(a);if(a.validate(a)){a.edit_row.addClass("loading");a.submit(a,c.default_submit_ajax_options(a))}}},success_inline_add_form:function(a,b){a.head_row.before(b);e.ize(b);a.reset(a);a.edit_row.trigger(a.event_prefix+
"success")},cancel_inline_add_form:function(a){a.head_row.remove();a.edit_row.remove();a.submit_row.remove();a.trigger&&a.trigger.parents(".trigger-row:first").show()},init_inline_edit_form:function(a){var b=a.event_prefix||"form.inline_edit_form.";a.edit_row.bind(b+"submit",function(){c.submit_inline_edit_form(a)}).bind(b+"cancel",function(){c.cancel_inline_edit_form(a)}).bind(b+"error",function(f,g){c.error(a,g);a.edit_row.removeClass("loading")}).bind(b+"success",function(){a.edit_row.removeClass("loading")}).bind(b+
"valid",function(){c.enable_submit(a)}).bind(b+"invalid",function(){c.disable_submit(a)});c.init_submit_cancel(a);a.row.hide();a.row.before(a.head_row).before(a.edit_row).before(a.submit_row);a.init(a)},submit_inline_edit_form:function(a){if(!a.edit_row.is(".loading"))if(c.is_submit_enabled(a)){document.activeElement&&d(document.activeElement).blur();c.clear_message(a);if(a.validate(a)){a.edit_row.addClass("loading");a.submit(a,c.default_submit_ajax_options(a))}}},success_inline_edit_form:function(a,
b){a.row.replaceWith(b);a.row=b;e.ize(b);a.edit_row.trigger(a.event_prefix+"cancel")},cancel_inline_edit_form:function(a){a.head_row.remove();a.edit_row.remove();a.submit_row.remove();a.row.show()},success_inline_delete:function(a,b,f){a.hide().addClass("old-row");a.after(b);b.append(a);if(f){a=d('<a href="#">Undo</a>');d(".msg-default",b).next().append(a);a.click(function(){f();return false})}},success_inline_delete_undo:function(a){var b=d(".old-row",a);a.before(b);b.show().removeClass("old-row");
a.remove()},init_modal_form:function(a){d(document.body).append(a.form.hide());var b=a.event_prefix||"form.modal_form.";a.form.bind(b+"submit",function(){c.submit_modal_form(a)}).bind(b+"cancel",function(){c.cancel_modal_form(a)}).bind(b+"error",function(f,g){c.error(a,g);a.form.removeClass("loading")}).bind(b+"success",function(){a.form.removeClass("loading")}).bind(b+"valid",function(){c.enable_submit(a)}).bind(b+"invalid",function(){c.disable_submit(a)});c.init_submit_cancel(a);a.form.overlay({close:".modal-buttons .cancel",
closeOnClick:false,load:true,fixed:false,mask:{color:"#000",loadSpeed:200,opacity:0.5},onLoad:function(){a.init(a)}})},submit_modal_form:function(a){if(!a.form.is(".loading"))if(c.is_submit_enabled(a)){document.activeElement&&d(document.activeElement).blur();c.clear_message(a);if(a.validate(a)){a.form.addClass("loading");a.submit(a,c.default_submit_ajax_options(a))}}},cancel_modal_form:function(a){a.form.data("overlay").close()},init_submit_cancel:function(a){var b=a.form||a.edit_row,f=a.form||a.submit_row,
g=a.event_prefix;a=d(".save",f).click(function(){b.trigger(g+"submit")});c.disable(a);d(".cancel",f).click(function(){b.trigger(g+"cancel")});d(":input",b).keypress(function(i){i.keyCode===13&&!i.isDefaultPrevented()&&b.trigger(g+"submit")}).keyup(function(i){i.keyCode===27&&b.trigger(g+"cancel")})},disable:function(a){d(a).attr("disabled","disabled").addClass("disabled")},enable:function(a){d(a).removeAttr("disabled").removeClass("disabled")},disable_submit:function(a){c.disable(d(".save",a.form||
a.submit_row))},enable_submit:function(a){c.enable(d(".save",a.form||a.submit_row))},is_submit_enabled:function(a){return!d(".save",a.form||a.submit_row).is(":disabled")},init_mqlkey:function(a,b){return a.next(".key-status").removeClass("valid invalid loading").text("").removeAttr("title").end().mqlkey(b).bind("valid",function(){d(this).next(".key-status").removeClass("invalid loading").addClass("valid").text("valid").attr("title","Key is available")}).bind("invalid",function(f,g){d(this).next(".key-status").removeClass("valid loading").addClass("invalid").text("invalid").attr("title",
g)}).bind("textchange",function(){d(this).next(".key-status").removeClass("valid invalid").text("loading").addClass("loading")})},validate_mqlkey:function(a,b){var f=b.next(".key-status"),g=b.val();if(g===""){b.trigger(a.event_prefix+"error","Key is required");return false}if(g===b.data("mqlkey").original)return true;if(f.is(".invalid")){b.trigger(a.event_prefix+"error",f.attr("title"));return false}else if(f.is(".loading"))return false;return true},error:function(a,b){c.disable_submit(a);return c.message(a,
b,"error")},message:function(a,b,f){a=a.head_row;a.find(".close-msg").css("visibility","visible").next().find(".msg-default").hide().next().text(b);a.addClass("row-msg");f&&a.addClass("row-msg-"+f)},clear_message:function(){},default_begin_ajax_options:function(){return c._default_ajax_options("GET")},default_submit_ajax_options:function(a){var b=c._default_ajax_options("POST");if(a){d.extend(b,a.ajax);d("input[type=hidden]",a.submit_row||a.form).each(function(){b.data[this.name]=this.value})}return b},
_default_ajax_options:function(a){return{data:{},dataType:"json",type:a||"GET",success:function(){c.check_ajax_success.apply(null,arguments)&&this.onsuccess&&this.onsuccess.apply(this,arguments)},error:function(){var b=c.check_ajax_error.apply(null,arguments);this.onerror&&this.onerror.apply(this,[b].concat(Array.prototype.slice.call(arguments)))}}},check_ajax_success:function(){return true},check_ajax_error:function(a){a.status===401&&d(window).trigger("fb.user.unauthorized");return a.responseText}}})(jQuery,
window.i18n);
(function(d){var e=window.editparams={Empty:function(c,a,b){this.structure=c;this.data=a;this.msg=b;this.toString=function(){return"Empty: "+this.msg}},Invalid:function(c,a,b){this.structure=c;this.data=a;this.msg=b;this.toString=function(){return"Invalid: "+this.msg}},parse:function(c,a){function b(h,k,l,m,o){try{e.validate(k,l);o.push(l)}catch(p){if(p instanceof e.Empty)o.push(l);else throw p;}}var f=(c.values||[]).slice(),g=c.properties||[],i=c.expected_type.mediator;if(i){if(!g.length)throw new e.Invalid(c,null,
"mediator musth have 1 or more properties");if(f.length&&f.length!==1)throw new e.Invalid(c,null,"Can't edit more than one value (row) for a mediator");}var j=[];d(".data-input",a).each(function(){var h=d(this),k=h.data("$.data_input");if(!k)throw new e.Invalid(c,null,"$.data-input not initialized for",this);k.validate(true);if(h.is(".error"))throw new e.Invalid(c,null,"$.data-input is invalid",this);k=h.data("data");if(!k)throw new e.Invalid(c,null,"$.data-input has no data",this);if(i){if(!j.length){j.push({});
d.each(g,function(o,p){j[0][p.id]=d.extend({},p,{values:[]})})}var l=j[0][k.name];if(l){var m=[];if(f.length)m=(m=f[0][l.id])&&m.values||[];b(h,l,k,m,l.values)}else console.warn("editparams","unknown mediator property data",k)}else b(h,c,k,f,j)});return i?e.parse_mediator(c,f,j):e.parse_simple(c,f,j)},parse_mediator:function(c,a,b){if(b.length!==1)throw new e.Invalid(c,b,"Must specify one (new or updated) value for a mediator");b=b[0];var f;if(a.length)f=a[0];a={};if(f)a.id=f.id;else{a.id=null;a.create=
"unconditional";a.connect=c.unique?"replace":"insert";var g=[];c.expected_type.id!=="/type/object"&&g.push({id:c.expected_type.id,connect:"insert"});var i=c.expected_type.included_types;i&&i.forEach(function(m){m!=="/type/object"&&g.push({id:m,connect:"insert"})});if(g.length)a.type=g}i=false;c=c.properties;for(var j=0,h=c.length;j<h;j++){var k=c[j],l=e.parse_simple(k,f&&f[k.id]&&f[k.id].values||[],b[k.id]&&b[k.id].values||[]);if(l.length){a[k.id]=l;i=true}}return i?[a]:[]},parse_simple:function(c,
a,b){return e.diff(c,a,b)},diff:function(c,a,b){var f=c.expected_type,g=c.expected_type.id,i=c.unique,j=g==="/type/text";if(i)if(!j)if(a.length&&a.length!==1)throw new e.Invalid(c,a,"Can't edit more than one value (row) for a unique property.");else if(b.length&&b.length!==1)throw new e.Invalid(c,b,"Can't edit more than one value (row) for a unique property.");var h=[];if(e.LITERAL_TYPE_IDS[g]){h.push("value");j&&h.push("lang")}else h.push("id");g=[];var k=[],l,m;l=0;for(m=a.length;l<m;l++){var o=
a[l];e.validate(c,o);e.inArray.apply(null,[o,b].concat(h))===-1&&g.push(e.clause(o,"delete"))}l=0;for(m=b.length;l<m;l++){o=b[l];try{e.validate(c,o)}catch(p){continue}if(e.inArray.apply(null,[o,a].concat(h))===-1){if(i)if(j){var n=e.inArray(o,g,"lang");n!==-1&&g.splice(n,1)}else return[e.clause(o,"replace",f)];k.push(e.clause(o,i?"replace":"insert",f))}}return g.concat(k)},validate:function(c,a){var b=c.expected_type.id;if(e.LITERAL_TYPE_IDS[b])if(e.isEmpty(a.value))throw new e.Empty(c,a);else{if(b===
"/type/text"&&e.isEmpty(a.lang))throw new e.Invalid(c,a,"Expected data.lang for /type/text");if(b==="/type/int"||b==="/type/float"){if(d.type(a.value)!=="number")throw new e.Invalid(c,a,"Expected number data.value for "+b);}else if(b==="/type/boolean"){if(d.type(a.value)!=="boolean")throw new e.Invalid(c,a,"Expected boolean data.value for /type/boolean");}else if(d.type(a.value)!=="string")throw new e.Invalid(c,a,"Expected string data.value for "+b);}else if(e.isEmpty(a.id))throw new e.Empty(c,a);
return a},clause:function(c,a,b){var f={connect:a};if(c.id){f.id=c.id;if(a!=="delete"&&b&&!b.enumeration){var g=[];b.id!=="/type/object"&&g.push({id:b.id,connect:"insert"});(c=b.included_types)&&c.forEach(function(i){i!=="/type/object"&&g.push({id:i,connect:"insert"})});if(g.length)f.type=g}}else{f.value=c.value;if(c.lang)f.lang=c.lang}return f},inArray:function(c,a){var b=Array.prototype.slice.call(arguments,2);if(!b.length)return d.inArray(c,a);for(var f=0,g=a.length;f<g;f++){for(var i=a[f],j=true,
h=0,k=b.length;h<k;h++){var l=b[h];if(i[l]!=c[l]){j=false;break}}if(j)return f}return-1},isEmpty:function(c){return c==null||c===""},LITERAL_TYPE_IDS:{"/type/int":1,"/type/float":1,"/type/boolean":1,"/type/rawstring":1,"/type/uri":1,"/type/text":1,"/type/datetime":1,"/type/id":1,"/type/key":1,"/type/value":1,"/type/enumeration":1}}})(jQuery);
(function(d,e,c,a){e.edit={text_edit_begin:function(b,f,g,i){var j={s:f,p:g,lang:i};d.ajax(d.extend(c.default_begin_ajax_options(),{url:b+"/text_edit_begin.ajax",data:j,onsuccess:function(h){h=d(h.result.html);h={event_prefix:"i18n.edit.text_edit.",init:e.edit.text_edit_init,validate:e.edit.text_edit_validate,submit:e.edit.text_edit_submit,ajax:{url:b+"/text_edit_submit.ajax",data:j},form:h,add_input:d(".data-input:first",h).data_input(),add_lang:d(".lang-select",h),structure:h.metadata(),base_url:b};
c.init_modal_form(h)}}))},text_edit_init:function(b){function f(i){d(".icon-link.delete",i).click(function(){b.form.trigger(g+"delete",i)});d(".data-input",i).data_input().bind("valid",function(){b.form.trigger(g+"valid")}).bind("empty",function(){b.form.trigger(g+"valid")}).bind("invalid",function(){b.form.trigger(g+"invalid")}).bind("submit",function(){b.form.trigger(g+"submit")}).bind("cancel",function(){b.form.trigger(g+"cancel")}).metadata().lang===b.ajax.data.lang&&i.addClass("preferred")}var g=
b.event_prefix;d(".values > tr",b.form).each(function(){f(d(this))});d(".icon-link.add",b.form).unbind().bind("mouseover, focus",function(){d(this).parent().addClass("focused")}).bind("mouseout, blur",function(){d(this).parent().removeClass("focused")}).click(function(){b.form.trigger(g+"add")}).focusin(function(){d(this).addClass("focused")}).focusout(function(){d(this).removeClass("focused")});b.add_lang.unbind().focus(function(){d(this).parent().addClass("focused")}).blur(function(){d(this).parent().removeClass("focused")}).keypress(function(i){i.keyCode===
13&&b.form.trigger(g+"add")});b.add_input.unbind().bind("submit",function(){b.form.trigger(g+"add")});b.form.bind(g+"add",function(){var i=b.add_input.data("data"),j=b.add_lang.val();if(i&&j){i=d.trim(i.value);if(i!==""){var h=d("option[value="+j.replace(/\//g,"\\/")+"]",b.add_lang),k=h.text();i=e.edit.new_text_edit_row(i,j,k).hide();d("tbody.values",b.form).prepend(i);f(i);i.fadeIn(function(){b.add_input.data("$.data_input").reset();b.add_lang[0].selectedIndex=0;b.structure.unique&&h.attr("disabled",
"disabled");d(":text",b.add_input).focus()});b.form.trigger(g+"valid");j!==b.ajax.data.lang&&d(".lang-warning").css("visibility","visible").hide().fadeIn("slow")}}else console.error("Text value and language required")}).bind(g+"delete",function(i,j){j=d(j);var h=d(".data-input:first",j).metadata().lang;j.fadeOut(function(){b.structure.unique&&d("option[value="+h.replace(/\//g,"\\/")+"]",b.add_lang).removeAttr("disabled");d(this).remove();b.form.trigger(g+"valid")})})},text_edit_validate:function(){return true},
text_edit_submit:function(b,f){try{var g=a.parse(b.structure,d(".values",b.form))}catch(i){g=d(".data-input.error",b.form);if(g.length){b.form.trigger(b.event_prefix+"error","Please specify a valid value");g.eq(0).find(":input").focus().select()}else b.form.trigger(b.event_prefix+"error",i.toString());return}f.data.o=JSON.stringify(g);g.length?d.ajax(d.extend(f,{onsuccess:function(){window.location.reload(true)},onerror:function(j){b.form.trigger(b.event_prefix+"error",j)}})):b.form.trigger(b.event_prefix+
"cancel")},new_text_edit_row:function(b,f,g){var i=d('<tr class="new">  <th class="row-header" scope="row">    <span class="data-input text">      <input class="fb-input" type="text">    </span>  </th>  <td class="lang">    <span></span>  </td>  <td class="delete-row">    <a class="icon-link delete" href="javascript:void(0);"><span class="delete-icon">delete</span></a>  </td></tr>'),j=d(".data-input",i);j.addClass(JSON.stringify({value:b,lang:f,type:"/type/text"}));d(".fb-input",j).val(b);d(".lang > span",
i).text(g);return i}}})(jQuery,window.i18n,window.formlib,window.editparams);
