
/*
 * Copyright 2010, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Additional Licenses for Third Party components can be found here:
 * http://wiki.freebase.com/wiki/Freebase_Site_License
 *
 */
(function(c){var f=function(){return typeof window.innerWidth!="undefined"?function(){return{w:window.innerWidth,h:window.innerHeight}}:typeof document.documentElement!="undefined"&&typeof document.documentElement.clientWidth!="undefined"&&document.documentElement.clientWidth!=0?function(){return{w:document.documentElement.clientWidth,h:document.documentElement.clientHeight}}:function(){return{w:document.getElementsByTagName("body")[0].clientWidth,h:document.getElementsByTagName("body")[0].clientHeight}}}();
window.kbs=function(d){c(".kbs.current",d).removeClass("current");var b=c(".domain-section:first",d),a=c(".domain-section:last",d),e=this.scroll_to=function(g){var k=c(document).scrollTop();c(document).height();var n=f().h;n=k+n;var p=g.offset().top;g=p+g.height();if(p<k)c(document).scrollTop(p);else g>n&&c(document).scrollTop(k+(g-n))},h=this.get_current=function(){return c(".kbs.current:first",d)},i=this.set_next=function(g,k,n){g=g||h();if(k.length){g.removeClass("current");k.addClass("current");
n||e(k)}},j=this.next_domain=function(g){var k=h(),n=m(k);if(n){n=n.find(".kbs:first");i(k,n,g)}},m=this._next_domain=function(g){if(!(g&&g.length))return c(".domain-section:first",d);g=g.closest(".domain-section");return!g.length||g[0]===a[0]?b:g.next(".domain-section")},l=this.prev_domain=function(){var g=h(),k=o(g);if(k){k=k.find(".kbs:first");i(g,k)}},o=this._prev_domain=function(g){if(!(g&&g.length))return c(".domain-section:last",d);var k=g.closest(".domain-section");if(g.closest(".property-section").length||
g.closest(".type-section").length)return k;return!k.length||k[0]===b[0]?a:k.prev(".domain-section")},r=this.next_type=function(){var g=h(),k=q(g);if(k){k=k.find(".kbs:first");i(g,k)}},q=this._next_type=function(g){if(!(g&&g.length))return c(".type-section:first",d);var k=g.closest(".domain-section");g=g.closest(".type-section");g=g.length?g.next(".type-section"):k.find(".type-section:first");if(!(g&&g.length)){var n=m(k);if(n)for(;n.get(0)!==k.get(0);){g=n.find(".type-section:first");if(g.length)break;
n=m(n)}}return g},s=this.prev_type=function(){var g=h(),k=t(g);if(k){k=k.find(".kbs:first");i(g,k)}},t=this._prev_type=function(g){if(!(g&&g.length))return c(".type-section:last",d);var k=g.closest(".domain-section"),n=g.closest(".type-section");if(g.closest(".property-section").length)return n;var p;if(n.length)p=n.prev(".type-section");if(!(p&&p.length))if(g=o(k))for(;g.get(0)!==k.get(0);){p=g.find(".type-section:last");if(p.length)break;g=o(g)}return p},w=this.next_prop=function(){var g=h(),k=
u(g);if(k){k=k.find(".kbs:first");i(g,k)}},u=this._next_prop=function(g){if(!(g&&g.length))return c(".property-section:first",d);var k=g.closest(".domain-section"),n=g.closest(".type-section"),p=g.closest(".property-section");k=p.length?p.next(".property-section"):n.length?n.find(".property-section:first"):k.find(".property-section:first");if(!(k&&k.length))if(g=q(g))for(;g.get(0)!==n.get(0);){k=g.find(".property-section:first");if(k.length)break;if(n.get(0)==null)n=g;g=q(g)}return k},y=this.prev_prop=
function(){var g=h(),k=z(g);if(k){k=k.find(".kbs:first");i(g,k)}},z=this._prev_prop=function(g){if(!(g&&g.length))return c(".property-section:last",d);var k=g.closest(".domain-section"),n=g.closest(".type-section"),p=g.closest(".property-section");if(g.closest(".data-section").length)return p;var v;if(p.length)v=p.prev(".property-section");if(!(v&&v.length))if(s=n.length?t(n):t(k))for(;s.get(0)!==n.get(0);){v=s.find(".property-section:last");if(v.length)break;if(n.get(0)==null)n=s;s=t(s)}return v};
this.next=function(){var g=h(),k=this._next(g);k&&i(g,k)};this._next=function(g){if(!(g&&g.length))return c(".domain-section:first .kbs:first",d);var k=g.closest(".domain-section"),n=g.closest(".type-section"),p=g.closest(".property-section");if(g.closest(".data-section").length){g=g.next(".kbs");if(g.length)return g;g=p.next(".property-section").find(".kbs:first");if(g.length)return g;g=n.next(".type-section").find(".kbs:first")}else if(p.length){g=p.find(".data-section:first .kbs:first");if(g.length)return g;
g=p.next(".property-section").find(".kbs:first");if(g.length)return g;g=n.next(".type-section").find(".kbs:first")}else if(n.length){g=n.find(".property-section:first .kbs:first");if(g.length)return g;g=n.next(".type-section").find(".kbs:first")}else g=k.find(".type-section:first .kbs:first");if(g.length)return g;return k.get(0)===a.get(0)?b.find(".kbs:first"):k.next(".domain-section").find(".kbs:first")};this.prev=function(){var g=h(),k=this._prev(g);k&&i(g,k)};this._prev=function(g){if(!(g&&g.length)){g=
c(".data-section:last .kbs:last",d);g.length||(g=c(".property-section:last .kbs:first",d));g.length||(g=c(".type-section:last .kbs:first",d));g.length||(g=c(".domain-section:last .kbs:first",d));return g}var k=g.closest(".domain-section"),n=g.closest(".type-section"),p=g.closest(".property-section");if(g.closest(".data-section").length){g=g.prev(".kbs");if(g.length)return g;return p.find(".kbs:first")}else if(p.length){g=p.prev(".property-section").find(".kbs:last");if(g.length)return g;return n.find(".kbs:first")}else if(n.length){g=
n.prev(".type-section").find(".kbs:last");if(g.length)return g;return k.find(".kbs:first")}else return k.get(0)===b.get(0)?a.find(".kbs:last"):k.prev(".domain-section").find(".kbs:last")};this.edit=function(){this.get_current().trigger("edit")};var x=this;c(document).unbind(".kbs").bind("keydown.kbs",function(g){var k=g.target;if(k==document.body||k==document||k==window||k==c("html")[0]){k=g.keyCode;if(k===68)g.shiftKey?l():j();else if(k===84)g.shiftKey?s():r();else if(k===80)g.shiftKey?y():w();else if(k===
74)x.next();else if(k===75)x.prev();else k===69&&x.edit()}})}})(jQuery);
(function(c,f){var d=window.propbox={init:function(b,a){a=c.extend({lang:"/lang/en"},a);if(!a.base_ajax_url)throw new Error("base_ajax_url required in propbox options");if(!a.base_static_url)throw new Error("base_static_url required in propbox options");if(!a.id)throw new Error("topic id required in propbox options");if(!a.lang)throw new Error("lang required in propbox options");d.options=a;d.kbs=new f(b);d.kbs.set_next(d.kbs.get_current(),c(".kbs:visible:first",b,true));c(".kbs",b).live("click",
function(){var e=d.kbs.get_current();d.kbs.set_next(e,c(this),true)}).live("edit",function(){var e=c(this).find(".headmenu:first").data("submenu");e&&c("li:first a:first",e).click()});d.init_menus(b)},init_menus:function(b,a){b=c(b||document);a&&c(".nicemenu",b).nicemenu();(b&&b.is(".data-row")?b:c(".data-row",b)).hover(d.row_menu_hoverover,d.row_menu_hoverout);c(".nicemenu .headmenu",b).add(c(".nicemenu .default-action",b)).click("click",function(){var e=d.kbs.get_current();d.kbs.set_next(e,c(this).parents(".kbs:first"),
true);return false})},row_menu_hoverover:function(){var b=c(this);d.row_menu_hoverover.timeout=setTimeout(function(){b.addClass("row-hover")},300)},row_menu_hoverout:function(){clearTimeout(d.row_menu_hoverover.timeout);c(this).removeClass("row-hover")},get_script:function(b,a){var e=d.get_script.cache;if(!e)e=d.get_script.cache={};var h=e[b];if(h)if(h.state===1)h.callbacks.push(a);else h.state===4&&a();else{h=e[b]={state:0,callbacks:[a]};c.ajax({url:d.options.base_static_url+b,dataType:"script",
beforeSend:function(){h.state=1},success:function(){h.state=4;c.each(h.callbacks,function(i,j){j()})},error:function(){h.state=-1}})}},prop_edit:function(b,a){var e=c(b).parents(".submenu").data("headmenu").parents(".property-section").find(".data-section .data-row:first:visible .nicemenu:first .headmenu:first a");e.length?e.click():d.prop_add(b,a);return false},prop_add:function(b,a){var e=c(b).parents(".submenu").data("headmenu").parents(".property-section");if(e.is(".editing"))return false;e.addClass("editing");
d.get_script("/propbox-edit.mf.js",function(){d.edit.prop_add_begin(e,a)});return false},value_edit:function(b){var a=c(b).parents(".submenu").data("headmenu").parents(".data-row:first"),e=a.parents(".property-section");if(e.is(".editing"))return false;e.addClass("editing");d.get_script("/propbox-edit.mf.js",function(){d.edit.value_edit_begin(e,a)});return false},value_delete:function(b){var a=c(b).parents(".submenu").data("headmenu").parents(".data-row:first"),e=a.parents(".property-section");if(e.is(".editing"))return false;
e.addClass("editing");d.get_script("/propbox-edit.mf.js",function(){d.edit.value_delete_begin(e,a)});return false},close_message:function(b){c(b).parents(".row-msg:first").remove();return false}}})(jQuery,window.kbs);
(function(c,f){f.require("dojo.date.stamp");f.require("dojo.date.locale");f.require("dojo.number");c.fn.validate_input=function(b){return this.each(function(){var a=c(this);if(a.is(":text")){var e=a.data("$.validate_input");e&&e._destroy();e=new d(this,b);a.data("$.validate_input",e)}})};var d=c.validate_input=function(b,a){var e=this.options=c.extend(true,{},d.defaults,a);if(typeof e.validator!=="function")throw"A validator is required";if(!e.lang)e.lang="/lang/en";e.lang=e.lang==="/lang/en"?["lang/en"]:
[e.lang,"/lang/en"];e.locales=[];c.each(e.lang,function(i,j){e.locales[i]=f.i18n.normalizeLocale(j.split("/").pop())});this.input=c(b);this.init();var h=this;this.input.bind("remove",function(){h._destroy()});return this};d.prototype={init:function(){var b=this;this.input.bind("keyup.validate_input",function(a){b.textchange(a)}).bind(c.browser.msie?"paste.validate_input":"input.validate_input",function(a){b.textchange(a)}).bind("keypress.validate_input",function(a){a.keyCode===13&&b.validate(true)}).bind("blur.validate_input",
function(){b.validate(true)})},_destroy:function(){this.input.unbind(".validate_input")},valid:function(b){this.input.trigger("valid",b)},invalid:function(b,a){this.input.trigger("invalid",a)},empty:function(){this.input.trigger("empty")},textchange:function(){clearTimeout(this.textchange_timeout);var b=this;this.textchange_timeout=setTimeout(function(){b.validate()},200)},validate:function(b){b&&clearTimeout(this.textchange_timeout);b=this.options;var a=c.trim(this.input.val());if(a==="")return this.empty();
try{return this.valid(b.validator(a,b))}catch(e){return this.invalid(a,""+e)}}};c.extend(d,{defaults:{validator:function(b){return{text:b,value:b}}},log:function(){},invalid:function(b,a,e,h){throw new Error("Invalid "+e+(h?": "+h:""));},text:function(b,a){if(b.lengh>4096)return this.invalid(b,a,type,"Text too long");return{text:b,value:b}},topic:function(){return d.defaults.validator},enumerated:function(){return d.defaults.validator},"boolean":function(){return d.defaults.validator},uri:function(b,
a){var e=d.uri.regex;if(!e)e=d.uri.regex=/^(https?|ftp):\/\/(((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:)*@)?(((\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5]))|((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?)(:\d*)?)(\/((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)+(\/(([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)*)*)?)?(\?((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|[\uE000-\uF8FF]|\/|\?)*)?(\#((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|\/|\?)*)?$/i;
if(e.test(b))return{text:b,value:b};return d.invalid(b,a,"uri")},"int":function(b,a){return d.number.parse(b,a,false)},"float":function(b,a){return d.number.parse(b,a,true)},number:function(b,a,e){return d.number.parse(b,a,e)},datetime:function(b,a){return d.datetime.parse(b,a)},mqlkey:function(b,a){var e=d.mqlkey.regex;if(!e)e=d.mqlkey.regex=/^[A-Za-z0-9][A-Za-z0-9_-]*$/;if(e.test(b))return{text:b,value:b};return d.invalid(b,a,"mqlkey")}});c.extend(d.number,{parse:function(b,a,e){var h=a&&a.locales||
["en"],i,j;i=0;for(j=h.length;i<j;i++){var m=h[i];a=f.number.parse(b,{locale:m});if(!isNaN(a)){b={};if(e){b.value=a;b.text=f.number.format(a,{locale:m})}else{b.value=f.number.round(a,0);b.text=f.number.format(b.value,{locale:m})}return b}}throw d.invalid("number",b);}});c.extend(d.datetime,{formats:["yyyy",["dateFormatItem-y"],"yyyy-MM",["dateFormatItem-yM","dateFormatItem-yMMM"],"yyyy-MM-dd",["dateFormat-short","dateFormat-medium","dateFormat-long"]],parse:function(b,a){if(!f.date.stamp._isoRegExp)f.date.stamp._isoRegExp=
/^(?:(-?\d{4})(?:-(\d{2})(?:-(\d{2}))?)?)?(?:T(\d{2}):(\d{2})(?::(\d{2})(.\d+)?)?((?:[+-](\d{2}):(\d{2}))|Z)?)?$/;var e=f.date.stamp.fromISOString(b);if(e)return{text:b,value:b,date:e};var h=a&&a.locales||["en"],i,j,m,l,o,r;i=0;for(j=h.length;i<j;i++){var q=h[i],s=f.date.locale._getGregorianBundle(q);m=0;for(l=d.datetime.formats.length;m<l;m+=2){var t=d.datetime.formats[m],w=d.datetime.formats[m+1];o=0;for(r=w.length;o<r;o++){var u=s[w[o]];if(u){u=i18n.normalize_pattern(u);try{e=f.date.locale.parse(b,
{datePattern:u,selector:"date",locale:q});return{text:b,value:f.date.locale.format(e,{datePattern:t,selector:"date"}),date:e}}catch(y){}}}}}throw d.invalid("datetime",b);}})})(jQuery,dojo);
(function(c){c.fn.data_input=function(f){return this.each(function(){var d=c(this),b=d.data("$.data_input");b&&b._destroy();b=new c.data_input(this,f);d.data("$.data_input",b)})};c.data_input=function(f,d){this.options=c.extend(true,{},c.data_input.defaults,d);this.container=c(f);this.metadata=this.container.metadata();this.input=c(":input",this.container);this.init();var b=this;this.input.bind("remove",function(){b._destroy()})};c.data_input.prototype={init:function(){var f=this,d=this.container,
b=this.input,a=this.options;b.bind("focusin.data_input",function(){f.container.addClass("focus")}).bind("focusout.data_input",function(){f.container.removeClass("focus")}).bind("valid.data_input",function(h,i){var j={name:f.input.attr("name")};if(i.id)j.id=i.id;else{j.value=i.value;if(f.metadata.type==="/type/text")j.lang=f.metadata.lang||a.lang}f.container.data("data",j);f.container.removeClass("error").addClass("valid");f.container.trigger("valid")}).bind("invalid.data_input",function(){f.container.removeData("data");
f.container.removeClass("valid").addClass("error");f.container.trigger("invalid")}).bind("empty.data_input",function(){var h={name:f.input.attr("name")};if(f.metadata&&f.metadata.lang)h.lang=f.metadata.lang;f.container.data("data",h);f.container.removeClass("valid").removeClass("error");f.container.trigger("empty")}).bind("keypress.data_input",function(h){h.keyCode===13&&!h.isDefaultPrevented()&&f.container.trigger("submit")}).bind("keyup.data_input",function(h){h.keyCode===27&&f.container.trigger("cancel")});
if(d.is(".topic")){d=f.metadata.type;var e=c.extend(true,{},a.suggest);e.type=d;if(d.indexOf("/type/")===0||d.indexOf("/common/")===0&&d!=="/common/topic"||d.indexOf("/freebase/")===0&&d.indexOf("_profile")===d.length-8){e.type_strict="any";e.filter="(any type:"+d+")"}else{e.type_strict="should";e.category="object";e.filter="(any without:fus),(should type:"+d+")"}b.validate_topic(e).bind("valid.data_input",function(h,i){f.fb_select(i)}).bind("invalid.data_input",function(){f.fb_textchange()});if(this.metadata&&
this.metadata.id){b.data("data.suggest",this.metadata);this.validate()}}else if(d.is(".text"))b.validate_input({validator:c.validate_input.text});else if(d.is(".datetime"))b.validate_input({validator:c.validate_input.datetime,lang:a.lang});else if(d.is(".enumerated")){b.validate_enumerated().bind("valid.data_input",function(h,i){f.fb_select(i)}).bind("invalid.data_input",function(){f.fb_textchange()});this.metadata&&this.metadata.id&&this.validate()}else if(d.is(".int"))b.validate_input({validator:c.validate_input["int"],
lang:a.lang});else if(d.is(".float"))b.validate_input({validator:c.validate_input["float"],lang:a.lang});else if(d.is(".uri"))b.validate_input({validator:c.validate_input.uri});else if(d.is(".boolean"))b.validate_boolean();else if(d.is(".enumeration"))b.validate_input({validator:c.validate_input.mqlkey});else if(d.is(".rawstring"))b.validate_input({validator:c.validate_input.text});else throw new Error("Invalid data-input: "+d.attr("class"));},_destroy:function(){this.input.unbind(".data_input")},
validate:function(){var f=this.input;c.each(["$.validate_topic","$.validate_input","$.validate_enumerated","$.validate_boolean"],function(d,b){var a=f.data(b);if(a){a.validate(true);return false}})},reset:function(){this.container.removeData("data");if(this.input.is(":text"))this.input.val("");else if(this.input.is("select"))this.input[0].selectedIndex=0;else this.input.is(":radio")&&this.input.each(function(){this.checked=false})},fb_textchange:function(){},fb_select:function(){},ajax_beforeSend:function(f){if(!this.xhr_queue)this.xhr_queue=
[];this.xhr_queue.push(f);this.container.trigger("loading")},ajax_complete:function(f){if(!this.xhr_queue)this.xhr_queue=[];for(var d=0,b=this.xhr_queue.length;d<b;d++)if(f===this.xhr_queue[d]){this.xhr_queue.splice(d,1);break}this.xhr_queue.length===0&&this.container.trigger("loading_complete")}};c.extend(c.data_input,{defaults:{suggest:{service_url:"http://www.freebase.com",service_path:"/private/suggest",flyout_service_url:"http://www.freebase.com",flyout_service_path:"/private/flyout",mqlread_url:"http://api.freebase.com/api/service/mqlread",
category:"object",type:"/common/topic"}}});c.fn.validate_topic=function(f){return this.each(function(){var d=c(this);if(d.is(":text")){var b=d.data("$.validate_topic");b&&b._destroy();b=new c.validate_topic(this,f);d.data("$.validate_topic",b)}})};c.validate_topic=function(f,d){this.options=c.extend(true,{},d);this.input=c(f);this.init()};c.validate_topic.prototype={init:function(){var f=this;this.input.suggest(this.options).bind("fb-textchange.validate_topic",function(){f.input.val()===""?f.empty():
f.invalid()}).bind("fb-select.validate_topic",function(d,b){f.input.val(b.name!=null?b.name:b.id);f.valid(b)})},invalid:function(){this.input.trigger("invalid")},valid:function(f){this.input.trigger("valid",f)},empty:function(){this.input.trigger("empty")},_destroy:function(){this.input.unbind(".validate_topic")},validate:function(){if(this.input.val()==="")this.empty();else{var f=this.input.data("data.suggest");f?this.valid(f):this.invalid()}}};c.fn.validate_enumerated=function(f){return this.each(function(){var d=
c(this);if(d.is("select")){var b=d.data("$.validate_enumerated");b&&b._destroy();b=new c.validate_enumerated(this,f);d.data("$.validate_enumerated",b)}})};c.validate_enumerated=function(f,d){this.options=c.extend(true,{},d);this.input=c(f);this.init()};c.validate_enumerated.prototype={init:function(){var f=this;this.input.bind("change.validate_enumerated, keypress.validate_enumerated",function(){this.selectedIndex===0?f.empty():f.valid({text:c(":selected",this).text(),id:this.value})})},invalid:function(){this.input.trigger("invalid")},
valid:function(f){this.input.trigger("valid",f);this.input.trigger("fb-select",f)},empty:function(){this.input.trigger("empty")},_destroy:function(){this.input.unbind(".validate_enumerated")},validate:function(){var f=this.input[0];f.selectedIndex>0?this.valid({text:c(":selected",this.input).text(),id:f.value}):this.empty()}};c.fn.validate_boolean=function(f){var d,b;this.each(function(){var e=c(this);if(e.is(":radio"))if(e.val().toLowerCase()==="true")d=e;else if(e.val().toLowerCase()==="false")b=
e});if(d&&b){var a=d.data("$.validate_boolean");a&&a._destroy();a=new c.validate_boolean(d,b,f);d.data("$.validate_boolean",a)}return this};c.validate_boolean=function(f,d,b){this.options=c.extend(true,{},b);this.tradio=f;this.fradio=d;this.input=this.tradio;this.init()};c.validate_boolean.prototype={init:function(){var f=this;this.tradio.bind("change.validate_boolean",function(){f.validate()})},_destroy:function(){this.input.unbind(".validate_boolean")},valid:function(f){this.input.trigger("valid",
f)},empty:function(){this.input.trigger("empty")},validate:function(){if(this.tradio.is(":checked"))this.valid({text:this.tradio.text(),value:true});else this.fradio.is(":checked")?this.valid({text:this.fradio.text(),value:false}):this.empty()}}})(jQuery);
(function(c){var f=window.editparams={Empty:function(d,b,a){this.structure=d;this.data=b;this.msg=a;this.toString=function(){return"Empty: "+this.msg}},Invalid:function(d,b,a){this.structure=d;this.data=b;this.msg=a;this.toString=function(){return"Invalid: "+this.msg}},parse:function(d,b){function a(m,l,o,r,q){try{f.validate(l,o);q.push(o)}catch(s){if(s instanceof f.Empty)q.push(o);else throw s;}}var e=(d.values||[]).slice(),h=d.properties||[],i=d.expected_type.mediator;if(i){if(!h.length)throw new f.Invalid(d,
null,"mediator musth have 1 or more properties");if(e.length&&e.length!==1)throw new f.Invalid(d,null,"Can't edit more than one value (row) for a mediator");}var j=[];c(".data-input",b).each(function(){var m=c(this),l=m.data("$.data_input");if(!l)throw new f.Invalid(d,null,"$.data-input not initialized for",this);l.validate(true);if(m.is(".error"))throw new f.Invalid(d,null,"$.data-input is invalid",this);l=m.data("data");if(!l)throw new f.Invalid(d,null,"$.data-input has no data",this);if(i){if(!j.length){j.push({});
c.each(h,function(q,s){j[0][s.id]=c.extend({},s,{values:[]})})}var o=j[0][l.name];if(o){var r=[];if(e.length)r=(r=e[0][o.id])&&r.values||[];a(m,o,l,r,o.values)}else console.warn("editparams","unknown mediator property data",l)}else a(m,d,l,e,j)});return i?f.parse_mediator(d,e,j):f.parse_simple(d,e,j)},parse_mediator:function(d,b,a){if(a.length!==1)throw new f.Invalid(d,a,"Must specify one (new or updated) value for a mediator");a=a[0];var e;if(b.length)e=b[0];b={};if(e)b.id=e.id;else{b.id=null;b.create=
"unconditional";b.connect=d.unique?"replace":"insert";var h=[];d.expected_type.id!=="/type/object"&&h.push({id:d.expected_type.id,connect:"insert"});var i=d.expected_type.included_types;i&&i.forEach(function(r){r!=="/type/object"&&h.push({id:r,connect:"insert"})});if(h.length)b.type=h}i=false;d=d.properties;for(var j=0,m=d.length;j<m;j++){var l=d[j],o=f.parse_simple(l,e&&e[l.id]&&e[l.id].values||[],a[l.id]&&a[l.id].values||[]);if(o.length){b[l.id]=o;i=true}}return i?[b]:[]},parse_simple:function(d,
b,a){return f.diff(d,b,a)},diff:function(d,b,a){var e=d.expected_type,h=d.expected_type.id,i=d.unique,j=h==="/type/text";if(i)if(!j)if(b.length&&b.length!==1)throw new f.Invalid(d,b,"Can't edit more than one value (row) for a unique property.");else if(a.length&&a.length!==1)throw new f.Invalid(d,a,"Can't edit more than one value (row) for a unique property.");var m=[];if(f.LITERAL_TYPE_IDS[h]){m.push("value");j&&m.push("lang")}else m.push("id");h=[];var l=[],o,r;o=0;for(r=b.length;o<r;o++){var q=
b[o];f.validate(d,q);f.inArray.apply(null,[q,a].concat(m))===-1&&h.push(f.clause(q,"delete"))}o=0;for(r=a.length;o<r;o++){q=a[o];try{f.validate(d,q)}catch(s){continue}if(f.inArray.apply(null,[q,b].concat(m))===-1){if(i)if(j){var t=f.inArray(q,h,"lang");t!==-1&&h.splice(t,1)}else return[f.clause(q,"replace",e)];l.push(f.clause(q,i?"replace":"insert",e))}}return h.concat(l)},validate:function(d,b){var a=d.expected_type.id;if(f.LITERAL_TYPE_IDS[a])if(f.isEmpty(b.value))throw new f.Empty(d,b);else{if(a===
"/type/text"&&f.isEmpty(b.lang))throw new f.Invalid(d,b,"Expected data.lang for /type/text");if(a==="/type/int"||a==="/type/float"){if(c.type(b.value)!=="number")throw new f.Invalid(d,b,"Expected number data.value for "+a);}else if(a==="/type/boolean"){if(c.type(b.value)!=="boolean")throw new f.Invalid(d,b,"Expected boolean data.value for /type/boolean");}else if(c.type(b.value)!=="string")throw new f.Invalid(d,b,"Expected string data.value for "+a);}else if(f.isEmpty(b.id))throw new f.Empty(d,b);
return b},clause:function(d,b,a){var e={connect:b};if(d.id){e.id=d.id;if(b!=="delete"&&a&&!a.enumeration){var h=[];a.id!=="/type/object"&&h.push({id:a.id,connect:"insert"});(d=a.included_types)&&d.forEach(function(i){i!=="/type/object"&&h.push({id:i,connect:"insert"})});if(h.length)e.type=h}}else{e.value=d.value;if(d.lang)e.lang=d.lang}return e},inArray:function(d,b){var a=Array.prototype.slice.call(arguments,2);if(!a.length)return c.inArray(d,b);for(var e=0,h=b.length;e<h;e++){for(var i=b[e],j=true,
m=0,l=a.length;m<l;m++){var o=a[m];if(i[o]!=d[o]){j=false;break}}if(j)return e}return-1},isEmpty:function(d){return d==null||d===""},LITERAL_TYPE_IDS:{"/type/int":1,"/type/float":1,"/type/boolean":1,"/type/rawstring":1,"/type/uri":1,"/type/text":1,"/type/datetime":1,"/type/id":1,"/type/key":1,"/type/value":1,"/type/enumeration":1}}})(jQuery);
(function(c,f,d){var b=f.edit={prop_add_begin:function(a,e){var h={s:f.options.id,p:a.attr("data-id"),lang:f.options.lang};c.ajax({url:f.options.base_ajax_url+"/prop_add_begin.ajax",data:h,dataType:"json",success:function(i,j,m){if(i.code!=="/api/status/ok")return b.ajax_error(m,null,a);i=c(i.result.html).hide();var l={mode:"add",event_prefix:"propbox.edit.prop_add.",ajax:{data:h,url:f.options.base_ajax_url+"/prop_edit_submit.ajax"},init:b.init_prop_add_form,submit:b.submit_prop_add_form,prop_section:a,
msg_row:c(".row-msg",i),edit_row:c(".edit-row",i),submit_row:c(".edit-row-submit",i),structure:i.metadata()};b.init(l);l.edit_row.bind("propbox.edit.prop_add.success",function(){if(e)l.edit_row.trigger(l.event_prefix+"cancel");else{b.reset_data_inputs(l);c(":input:visible:first",l.edit_row).focus();c(".button-submit",l.submit_row).attr("disabled","disabled").addClass("disabled");c(".button-cancel",l.submit_row).text("Done")}})},error:function(i){b.ajax_error(i,null,a)}})},init_prop_add_form:function(a){b.init_data_inputs(a);
c(":input:visible:first",a.edit_row).focus()},submit_prop_add_form:function(a){var e=c.extend({},a.ajax.data);try{var h=d.parse(a.structure,a.edit_row);e.o=JSON.stringify(h)}catch(i){e=c(".data-input.error",a.edit_row);if(e.length){a.edit_row.trigger(a.event_prefix+"error","Please specify a valid value");e.eq(0).find(":input").focus().select()}else a.edit_row.trigger(a.event_prefix+"error",i.toString());return}c.ajax({url:a.ajax.url,type:"POST",dataType:"json",data:e,success:function(j,m,l){if(j.code!==
"/api/status/ok")return b.ajax_error(l,a);j=c(j.result.html);a.msg_row.before(j);i18n.ize(j);c(".edit",j).show();f.init_menus(j,true);f.kbs.set_next(null,j,true);a.edit_row.trigger(a.event_prefix+"success")},error:function(j){b.ajax_error(j,a)}})},value_edit_begin:function(a,e){var h;if(e.is("tr"))h=e.attr("data-id");else{h=c(".property-value:first",e);h=h.attr("data-id")||h.attr("data-value")||h.attr("datetime")}var i={s:f.options.id,p:a.attr("data-id"),replace:h,lang:f.options.lang};c.ajax({url:f.options.base_ajax_url+
"/value_edit_begin.ajax",data:i,dataType:"json",success:function(j,m,l){if(j.code!=="/api/status/ok")return b.ajax_error(l,null,a,e);j=c(j.result.html).hide();var o={mode:"edit",event_prefix:"propbox.edit.value_edit.",ajax:{data:i,url:f.options.base_ajax_url+"/prop_edit_submit.ajax"},init:b.init_value_edit_form,submit:b.submit_value_edit_form,prop_section:a,prop_row:e,msg_row:c(".row-msg",j),edit_row:c(".edit-row",j),submit_row:c(".edit-row-submit",j),structure:j.metadata()};b.init(o);o.edit_row.bind("propbox.edit.value_edit.success",
function(){o.msg_row.remove();o.edit_row.remove();o.submit_row.remove()}).bind("propbox.edit.value_edit.cancel",function(){o.prop_row.show()}).bind("propbox.edit.value_edit.delete",function(){b.loading_begin(o);f.edit.value_delete_begin(a,e,function(){o.msg_row.remove();o.edit_row.remove();o.submit_row.remove()})})},error:function(j){b.ajax_error(j,null,a,e)}})},init_value_edit_form:function(a){b.init_data_inputs(a);c(":input:visible:first",a.edit_row).focus()},submit_value_edit_form:function(a){var e=
c.extend({},a.ajax.data);try{var h=d.parse(a.structure,a.edit_row);e.o=JSON.stringify(h)}catch(i){e=c(".data-input.error",a.edit_row);if(e.length){a.edit_row.trigger(a.event_prefix+"error","Please specify a valid value");e.eq(0).find(":input").focus().select()}else a.edit_row.trigger(a.event_prefix+"error",i.toString());return}c.ajax({url:a.ajax.url,type:"POST",dataType:"json",data:e,success:function(j,m,l){if(j.code!=="/api/status/ok")return b.ajax_error(l,a);j=c(j.result.html);a.prop_row.after(j);
i18n.ize(j);c(".edit",j).show();f.init_menus(j,true);f.kbs.set_next(null,j,true);a.prop_row.remove();a.edit_row.trigger(a.event_prefix+"success")},error:function(j){b.ajax_error(j,a)}})},value_delete_begin:function(a,e,h){var i;if(e.is("tr"))i=e.attr("data-id");else{i=c(".property-value:first",e);i=i.attr("data-id")||i.attr("data-value")||i.attr("datetime")}i={s:f.options.id,p:a.attr("data-id"),o:i,lang:f.options.lang};c.ajax({url:f.options.base_ajax_url+"/value_delete_submit.ajax",type:"POST",data:i,
dataType:"json",success:function(j,m,l){if(j.code!=="/api/status/ok")return b.ajax_error(l,null,a,e);j=c(j.result.html);e.before(j);e.hide();a.removeClass("editing");h&&h()},error:function(j){b.ajax_error(j,null,a,e)}})},value_delete_undo:function(a){var e=c(a).parents(".row-msg:first"),h=e.next(".data-row:hidden"),i=h.parents(".property-section");if(h.is("tr"))a=h.attr("data-id");else{a=c(".property-value:first",h);a=a.attr("data-id")||a.attr("data-value")||a.attr("datetime")}a={s:f.options.id,p:i.attr("data-id"),
o:a,lang:f.options.lang};c.ajax({url:f.options.base_ajax_url+"/value_delete_undo.ajax",type:"POST",data:a,dataType:"json",success:function(j,m,l){if(j.code!=="/api/status/ok")return b.ajax_error(l,null,i,h);h.show();e.remove()},error:function(j){b.ajax_error(j,null,i,h)}});return false},loading_begin:function(a){c.each([a.edit_row,a.msg_row,a.submit_row],function(e,h){h&&h.addClass("loading")})},loading_complete:function(a){c.each([a.edit_row,a.msg_row,a.submit_row],function(e,h){h&&h.removeClass("loading")})},
init_data_inputs:function(a){c(".data-input",a.edit_row).each(function(){b.init_data_input(c(this),a)})},init_data_input:function(a,e){a.data_input({lang:f.options.lang,suggest:f.options.suggest}).bind("valid",function(){e.edit_row.trigger(e.event_prefix+"valid");var h=a.parent(".form-field"),i=h.next(".magicbox-template");if(i.length){i=c("<div>").html(i.html());i=c(".form-field",i);h.after(i);b.init_data_input(c(".data-input",i),e)}}).bind("empty",function(){e.edit_row.trigger(e.event_prefix+"valid")}).bind("invalid",
function(){e.edit_row.trigger(e.event_prefix+"invalid")}).bind("submit",function(){e.edit_row.trigger(e.event_prefix+"submit")}).bind("cancel",function(){e.edit_row.trigger(e.event_prefix+"cancel")}).bind("loading",function(){c(this).addClass("loading")}).bind("loading_complete",function(){c(this).removeClass("loading")});if(a.is(".datetime"))i18n.ize_datetime_input(c(":text",a));else if(a.is(".int")||a.is(".float"))i18n.ize_number_input(c(":text",a))},reset_data_inputs:function(a){c(".data-input",
a.edit_row).each(function(){c(this).data("$.data_input").reset()})},init:function(a){if(a.mode==="add"){var e=c(">.data-section",a.prop_section);c("> .data-table > tbody > .empty-row, > .data-list > .empty-row",e).hide();c("> .data-table > tbody, > .data-list",e).append(a.msg_row).append(a.edit_row).append(a.submit_row)}else if(a.mode==="edit"){a.prop_row.hide();a.prop_row.after(a.msg_row);a.msg_row.after(a.edit_row);a.edit_row.after(a.submit_row)}c(".data-table > thead",a.prop_section).show();var h=
a.event_prefix||"propbox.edit.";a.edit_row.bind(h+"valid",function(){c(".button-submit",a.submit_row).removeAttr("disabled").removeClass("disabled")}).bind(h+"invalid",function(){c(".button-submit",a.submit_row).attr("disabled","disabled").addClass("disabled")}).bind(h+"submit",function(){b.submit(a)}).bind(h+"cancel",function(){b.cancel(a)}).bind(h+"error",function(i,j){b.error(a,j);b.loading_complete(a);a.prop_section.removeClass("editing")}).bind(h+"success",function(){b.loading_complete(a);a.prop_section.removeClass("editing")});
c(".button-submit",a.submit_row).click(function(){a.edit_row.trigger(h+"submit")});c(".button-cancel",a.submit_row).click(function(){a.edit_row.trigger(h+"cancel")});c(".button-delete",a.submit_row).click(function(){a.edit_row.trigger(h+"delete")});a.edit_row.show();a.submit_row.show();f.kbs.scroll_to(a.prop_section);a.init&&a.init(a)},cancel:function(a){a.msg_row.remove();a.edit_row.remove();a.submit_row.remove();a.prop_section.removeClass("editing");a=c(">.data-section",a.prop_section);c("> .data-table > tbody > tr, > .data-list > li",
a).filter(":not(.empty-row)").length||c("> .data-table > tbody > .empty-row, > .data-list > .empty-row",a).show()},submit:function(a){if(!a.edit_row.is(".loading"))if(!c(".button-submit",a.submit_row).is(":disabled")){document.activeElement&&c(document.activeElement).blur();b.clear_form_message(a);b.loading_begin(a);a.submit&&a.submit(a)}},error:function(a,e){c(".button-submit",a.submit_row).attr("disabled","disabled").addClass("disabled");return b.form_message(a,e,"error")},form_message:function(a,
e,h){a.msg_row.find(".close-msg").css("visibility","visible").next().find(".msg-default").hide().next().text(e);a.msg_row.attr("class","row-msg");h&&a.msg_row.addClass("row-msg-"+h)},clear_form_message:function(a){a.msg_row.find(".close-msg").css("visibility","hidden").next().find(".msg-default").show().next().html("&nbsp;")},ajax_error:function(a,e,h,i){a=a.responseText;if(e)e.edit_row.trigger(e.event_prefix+"error",a);else{e=c(".data-table",h);a=e.length?b.row_msg(a,"error","tr",c(">thead>tr:first>th",
e).length):b.row_msg(a,"error","li");if(i){i.before(a);i.is(".edit-row")?i.removeClass("loading"):h.removeClass("editing")}else{e.length?c(">tbody",e).append(a):c(".data-list",h).append(a);h.removeClass("editing")}}},row_msg:function(a,e,h,i){var j=c('<a class="close-msg" href="#">x</a>').click(function(){c(this).parents(".row-msg:first").remove();return false}),m=c("<span>").text(a);a=c("<"+h+' class="row-msg">');if(h==="tr"){h=c("<td>").append(j).append(m);i&&h.attr("colspan",i);a.append(h)}else a.append(j).append(m);
e&&a.addClass("row-msg-"+e);return a}}})(jQuery,window.propbox,window.editparams);
(function(c,f,d,b){function a(h){d.edit.init_data_inputs(h);c(":input:visible:first",h.edit_row).focus()}function e(h){var i=c.extend({},h.ajax.data),j;try{j=b.parse(h.structure,h.edit_row)}catch(m){i=c(".data-input.error",h.edit_row);if(i.length){h.edit_row.trigger(h.event_prefix+"error","Please specify a valid value");i.eq(0).find(":input").focus().select()}else h.edit_row.trigger(h.event_prefix+"error",m.toString());return}if(j&&j.length){i.o=JSON.stringify(j);c.ajax({url:h.ajax.url,type:"POST",
dataType:"json",data:i,success:function(l){l=c(l.result.html);l=c(".property-value:first",l).attr("data-id");window.location.href=f.h.fb_url(l)}})}else{h.edit_row.trigger(h.event_prefix+"error","Please specify a valid value");c("input:first",h.edit_row).focus()}}c(function(){var h=c(".edit-form"),i=c(".edit-row-submit",h),j=c("input[name=s]",i).val(),m=c("input[name=lang]",i).val();d.init(h,{id:j,base_ajax_url:f.h.ajax_url("lib/propbox"),base_static_url:f.h.static_url("lib/propbox"),lang:m,suggest:{service_url:f.h.legacy_fb_url(),
service_path:"/private/suggest",flyout_service_url:f.h.legacy_fb_url(),flyout_service_path:"/private/flyout",mqlread_url:f.h.fb_api_url("/api/service/mqlread"),category:"object",type:"/common/topic",status:["","Searching...","Select an item from the list:"]}});h={mode:"create.type.instance.",event_prefix:"create.type.instance.",ajax:{data:{s:c("input[name=s]",i).val(),p:c("input[name=p]",i).val(),lang:c("input[name=lang]",i).val()},url:f.h.ajax_url("lib/propbox/prop_edit_submit.ajax")},init:a,submit:e,
prop_section:h,msg_row:c(".row-msg",h),edit_row:h,submit_row:i,structure:h.metadata()};d.edit.init(h)})})(jQuery,window.freebase,window.propbox,window.editparams);
