
/*
 * Copyright 2012, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Additional Licenses for Third Party components can be found here:
 * http://wiki.freebase.com/wiki/Freebase_Site_License
 *
 */
/*
 
 jQuery Tools @VERSION / Expose - Dim the lights

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/toolbox/expose.html

 Since: Mar 2010
 Date: @DATE 
 
 jQuery Tools @VERSION Overlay - Overlay base. Extend it.

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/overlay/

 Since: March 2008
 Date: @DATE 
*/
(function(){var e,h,f,d,a=function(c,b){return function(){return c.apply(b,arguments)}};d=this;e=jQuery;e.fn.extend({chosen:function(c,b){if(e.browser==="msie"&&(e.browser.version==="6.0"||e.browser.version==="7.0"))return this;return e(this).each(function(){if(!e(this).hasClass("chzn-done"))return new h(this,c,b)})}});h=function(){function c(b){this.set_default_values();this.form_field=b;this.form_field_jq=e(this.form_field);this.is_multiple=this.form_field.multiple;this.is_rtl=this.form_field_jq.hasClass("chzn-rtl");
this.default_text_default=this.form_field.multiple?"Select Some Options":"Select an Option";this.set_up_html();this.register_observers();this.form_field_jq.addClass("chzn-done")}c.prototype.set_default_values=function(){this.click_test_action=a(function(b){return this.test_active_click(b)},this);this.results_showing=this.mouse_on_container=this.active_field=false;this.result_single_selected=this.result_highlighted=null;return this.choices=0};c.prototype.set_up_html=function(){var b,g;this.container_id=
this.form_field.id.length?this.form_field.id.replace(/(:|\.)/g,"_"):this.generate_field_id();this.container_id+="_chzn";this.f_width=this.form_field_jq.width();this.default_text=this.form_field_jq.data("placeholder")?this.form_field_jq.data("placeholder"):this.default_text_default;b=e("<div />",{id:this.container_id,"class":"chzn-container "+(this.is_rtl?"chzn-rtl":""),style:"width: "+this.f_width+"px;"});this.is_multiple?b.html('<ul class="chzn-choices"><li class="search-field"><input type="text" value="'+
this.default_text+'" class="default" autocomplete="off" style="width:25px;" /></li></ul><div class="chzn-drop" style="left:-9000px;"><ul class="chzn-results"></ul></div>'):b.html('<a href="javascript:void(0)" class="chzn-single"><span>'+this.default_text+'</span><div><b></b></div></a><div class="chzn-drop" style="left:-9000px;"><div class="chzn-search"><input type="text" autocomplete="off" /></div><ul class="chzn-results"></ul></div>');this.form_field_jq.hide().after(b);this.container=e("#"+this.container_id);
this.container.addClass("chzn-container-"+(this.is_multiple?"multi":"single"));this.dropdown=this.container.find("div.chzn-drop").first();b=this.container.height();g=this.f_width-f(this.dropdown);this.dropdown.css({width:g+"px",top:b+"px"});this.search_field=this.container.find("input").first();this.search_results=this.container.find("ul.chzn-results").first();this.search_field_scale();this.search_no_results=this.container.find("li.no-results").first();if(this.is_multiple){this.search_choices=this.container.find("ul.chzn-choices").first();
this.search_container=this.container.find("li.search-field").first()}else{this.search_container=this.container.find("div.chzn-search").first();this.selected_item=this.container.find(".chzn-single").first();b=g-f(this.search_container)-f(this.search_field);this.search_field.css({width:b+"px"})}this.results_build();return this.set_tab_index()};c.prototype.register_observers=function(){this.container.mousedown(a(function(b){return this.container_mousedown(b)},this));this.container.mouseenter(a(function(b){return this.mouse_enter(b)},
this));this.container.mouseleave(a(function(b){return this.mouse_leave(b)},this));this.search_results.mouseup(a(function(b){return this.search_results_mouseup(b)},this));this.search_results.mouseover(a(function(b){return this.search_results_mouseover(b)},this));this.search_results.mouseout(a(function(b){return this.search_results_mouseout(b)},this));this.form_field_jq.bind("liszt:updated",a(function(b){return this.results_update_field(b)},this));this.search_field.blur(a(function(b){return this.input_blur(b)},
this));this.search_field.keyup(a(function(b){return this.keyup_checker(b)},this));this.search_field.keydown(a(function(b){return this.keydown_checker(b)},this));if(this.is_multiple){this.search_choices.click(a(function(b){return this.choices_click(b)},this));return this.search_field.focus(a(function(b){return this.input_focus(b)},this))}else return this.selected_item.focus(a(function(b){return this.activate_field(b)},this))};c.prototype.container_mousedown=function(b){b&&b.type==="mousedown"&&b.stopPropagation();
if(this.pending_destroy_click)return this.pending_destroy_click=false;else{if(this.active_field){if(!this.is_multiple&&b&&(e(b.target)===this.selected_item||e(b.target).parents("a.chzn-single").length)){b.preventDefault();this.results_toggle()}}else{this.is_multiple&&this.search_field.val("");e(document).click(this.click_test_action);this.results_show()}return this.activate_field()}};c.prototype.mouse_enter=function(){return this.mouse_on_container=true};c.prototype.mouse_leave=function(){return this.mouse_on_container=
false};c.prototype.input_focus=function(){if(!this.active_field)return setTimeout(a(function(){return this.container_mousedown()},this),50)};c.prototype.input_blur=function(){if(!this.mouse_on_container){this.active_field=false;return setTimeout(a(function(){return this.blur_test()},this),100)}};c.prototype.blur_test=function(){if(!this.active_field&&this.container.hasClass("chzn-container-active"))return this.close_field()};c.prototype.close_field=function(){e(document).unbind("click",this.click_test_action);
if(!this.is_multiple){this.selected_item.attr("tabindex",this.search_field.attr("tabindex"));this.search_field.attr("tabindex",-1)}this.active_field=false;this.results_hide();this.container.removeClass("chzn-container-active");this.winnow_results_clear();this.clear_backstroke();this.show_search_field_default();return this.search_field_scale()};c.prototype.activate_field=function(){if(!this.is_multiple&&!this.active_field){this.search_field.attr("tabindex",this.selected_item.attr("tabindex"));this.selected_item.attr("tabindex",
-1)}this.container.addClass("chzn-container-active");this.active_field=true;this.search_field.val(this.search_field.val());return this.search_field.focus()};c.prototype.test_active_click=function(b){return e(b.target).parents("#"+this.container_id).length?(this.active_field=true):this.close_field()};c.prototype.results_build=function(){var b,g,j,i,k;this.parsing=true;this.results_data=d.SelectParser.select_to_array(this.form_field);if(this.is_multiple&&this.choices>0){this.search_choices.find("li.search-choice").remove();
this.choices=0}else this.is_multiple||this.selected_item.find("span").text(this.default_text);b="";k=this.results_data;j=0;for(i=k.length;j<i;j++){g=k[j];if(g.group)b+=this.result_add_group(g);else if(!g.empty){b+=this.result_add_option(g);if(g.selected&&this.is_multiple)this.choice_build(g);else g.selected&&!this.is_multiple&&this.selected_item.find("span").text(g.text)}}this.show_search_field_default();this.search_field_scale();this.search_results.html(b);return this.parsing=false};c.prototype.result_add_group=
function(b){if(b.disabled)return"";else{b.dom_id=this.container_id+"_g_"+b.array_index;return'<li id="'+b.dom_id+'" class="group-result">'+e("<div />").text(b.label).html()+"</li>"}};c.prototype.result_add_option=function(b){var g;if(b.disabled)return"";else{b.dom_id=this.container_id+"_o_"+b.array_index;g=b.selected&&this.is_multiple?[]:["active-result"];b.selected&&g.push("result-selected");b.group_array_index!=null&&g.push("group-option");return'<li id="'+b.dom_id+'" class="'+g.join(" ")+'">'+
b.html+"</li>"}};c.prototype.results_update_field=function(){this.result_clear_highlight();this.result_single_selected=null;return this.results_build()};c.prototype.result_do_highlight=function(b){var g,j,i,k;if(b.length){this.result_clear_highlight();this.result_highlight=b;this.result_highlight.addClass("highlighted");j=parseInt(this.search_results.css("maxHeight"),10);k=this.search_results.scrollTop();i=j+k;g=this.result_highlight.position().top+this.search_results.scrollTop();b=g+this.result_highlight.outerHeight();
if(b>=i)return this.search_results.scrollTop(b-j>0?b-j:0);else if(g<k)return this.search_results.scrollTop(g)}};c.prototype.result_clear_highlight=function(){this.result_highlight&&this.result_highlight.removeClass("highlighted");return this.result_highlight=null};c.prototype.results_toggle=function(){return this.results_showing?this.results_hide():this.results_show()};c.prototype.results_show=function(){if(!this.is_multiple){this.selected_item.addClass("chzn-single-with-drop");this.result_single_selected&&
this.result_do_highlight(this.result_single_selected)}this.dropdown.css({top:(this.is_multiple?this.container.height():this.container.height()-1)+"px",left:0});this.results_showing=true;this.search_field.focus();this.search_field.val(this.search_field.val());return this.winnow_results()};c.prototype.results_hide=function(){this.is_multiple||this.selected_item.removeClass("chzn-single-with-drop");this.result_clear_highlight();this.dropdown.css({left:"-9000px"});return this.results_showing=false};c.prototype.set_tab_index=
function(){var b;if(this.form_field_jq.attr("tabindex")){b=this.form_field_jq.attr("tabindex");this.form_field_jq.attr("tabindex",-1);if(this.is_multiple)return this.search_field.attr("tabindex",b);else{this.selected_item.attr("tabindex",b);return this.search_field.attr("tabindex",-1)}}};c.prototype.show_search_field_default=function(){if(this.is_multiple&&this.choices<1&&!this.active_field){this.search_field.val(this.default_text);return this.search_field.addClass("default")}else{this.search_field.val("");
return this.search_field.removeClass("default")}};c.prototype.search_results_mouseup=function(b){var g;g=e(b.target).hasClass("active-result")?e(b.target):e(b.target).parents(".active-result").first();if(g.length){this.result_highlight=g;return this.result_select(b)}};c.prototype.search_results_mouseover=function(b){if(b=e(b.target).hasClass("active-result")?e(b.target):e(b.target).parents(".active-result").first())return this.result_do_highlight(b)};c.prototype.search_results_mouseout=function(b){if(e(b.target).hasClass("active-result"))return this.result_clear_highlight()};
c.prototype.choices_click=function(b){b.preventDefault();if(this.active_field&&!e(b.target).hasClass("search-choice")&&!this.results_showing)return this.results_show()};c.prototype.choice_build=function(b){var g;g=this.container_id+"_c_"+b.array_index;this.choices+=1;this.search_container.before('<li class="search-choice" id="'+g+'"><span>'+b.html+'</span><a href="javascript:void(0)" class="search-choice-close" rel="'+b.array_index+'"></a></li>');return e("#"+g).find("a").first().click(a(function(j){return this.choice_destroy_link_click(j)},
this))};c.prototype.choice_destroy_link_click=function(b){b.preventDefault();this.pending_destroy_click=true;return this.choice_destroy(e(b.target))};c.prototype.choice_destroy=function(b){this.choices-=1;this.show_search_field_default();this.is_multiple&&this.choices>0&&this.search_field.val().length<1&&this.results_hide();this.result_deselect(b.attr("rel"));return b.parents("li").first().remove()};c.prototype.result_select=function(b){var g,j;if(this.result_highlight){g=this.result_highlight;j=
g.attr("id");this.result_clear_highlight();g.addClass("result-selected");if(this.is_multiple)this.result_deactivate(g);else this.result_single_selected=g;g=j.substr(j.lastIndexOf("_")+1);g=this.results_data[g];g.selected=true;this.form_field.options[g.options_index].selected=true;this.is_multiple?this.choice_build(g):this.selected_item.find("span").first().text(g.text);b.metaKey&&this.is_multiple||this.results_hide();this.search_field.val("");this.form_field_jq.trigger("change");return this.search_field_scale()}};
c.prototype.result_activate=function(b){return b.addClass("active-result").show()};c.prototype.result_deactivate=function(b){return b.removeClass("active-result").hide()};c.prototype.result_deselect=function(b){var g;g=this.results_data[b];g.selected=false;this.form_field.options[g.options_index].selected=false;e("#"+this.container_id+"_o_"+b).removeClass("result-selected").addClass("active-result").show();this.result_clear_highlight();this.winnow_results();this.form_field_jq.trigger("change");return this.search_field_scale()};
c.prototype.results_search=function(){return this.results_showing?this.winnow_results():this.results_show()};c.prototype.winnow_results=function(){var b,g,j,i,k,n,m,o,r,l,p,q,s,t;this.no_results_clear();m=0;o=this.search_field.val()===this.default_text?"":e("<div/>").text(e.trim(this.search_field.val())).html();k=new RegExp("^"+o.replace(/[-[\]{}()*+?.,\\^$|#\s]/g,"\\$&"),"i");r=new RegExp(o.replace(/[-[\]{}()*+?.,\\^$|#\s]/g,"\\$&"),"i");t=this.results_data;l=0;for(q=t.length;l<q;l++){g=t[l];if(!g.disabled&&
!g.empty)if(g.group)e("#"+g.dom_id).hide();else if(!(this.is_multiple&&g.selected)){b=false;n=g.dom_id;if(k.test(g.html)){b=true;m+=1}else if(g.html.indexOf(" ")>=0||g.html.indexOf("[")===0){i=g.html.replace(/\[|\]/g,"").split(" ");if(i.length){p=0;for(s=i.length;p<s;p++){j=i[p];if(k.test(j)){b=true;m+=1}}}}if(b){if(o.length){b=g.html.search(r);j=g.html.substr(0,b+o.length)+"</em>"+g.html.substr(b+o.length);j=j.substr(0,b)+"<em>"+j.substr(b)}else j=g.html;e("#"+n).html!==j&&e("#"+n).html(j);this.result_activate(e("#"+
n));g.group_array_index!=null&&e("#"+this.results_data[g.group_array_index].dom_id).show()}else{this.result_highlight&&n===this.result_highlight.attr("id")&&this.result_clear_highlight();this.result_deactivate(e("#"+n))}}}return m<1&&o.length?this.no_results(o):this.winnow_results_set_highlight()};c.prototype.winnow_results_clear=function(){var b,g,j,i,k;this.search_field.val("");g=this.search_results.find("li");k=[];j=0;for(i=g.length;j<i;j++){b=g[j];b=e(b);k.push(b.hasClass("group-result")?b.show():
!this.is_multiple||!b.hasClass("result-selected")?this.result_activate(b):void 0)}return k};c.prototype.winnow_results_set_highlight=function(){var b;if(!this.result_highlight){b=!this.is_multiple?this.search_results.find(".result-selected"):[];b=b.length?b.first():this.search_results.find(".active-result").first();if(b!=null)return this.result_do_highlight(b)}};c.prototype.no_results=function(b){var g;g=e('<li class="no-results">No results match "<span></span>"</li>');g.find("span").first().html(b);
return this.search_results.append(g)};c.prototype.no_results_clear=function(){return this.search_results.find(".no-results").remove()};c.prototype.keydown_arrow=function(){var b;if(this.result_highlight){if(this.results_showing)(b=this.result_highlight.nextAll("li.active-result").first())&&this.result_do_highlight(b)}else(b=this.search_results.find("li.active-result").first())&&this.result_do_highlight(e(b));if(!this.results_showing)return this.results_show()};c.prototype.keyup_arrow=function(){var b;
if(!this.results_showing&&!this.is_multiple)return this.results_show();else if(this.result_highlight){b=this.result_highlight.prevAll("li.active-result");if(b.length)return this.result_do_highlight(b.first());else{this.choices>0&&this.results_hide();return this.result_clear_highlight()}}};c.prototype.keydown_backstroke=function(){if(this.pending_backstroke){this.choice_destroy(this.pending_backstroke.find("a").first());return this.clear_backstroke()}else{this.pending_backstroke=this.search_container.siblings("li.search-choice").last();
return this.pending_backstroke.addClass("search-choice-focus")}};c.prototype.clear_backstroke=function(){this.pending_backstroke&&this.pending_backstroke.removeClass("search-choice-focus");return this.pending_backstroke=null};c.prototype.keyup_checker=function(b){var g,j;g=(j=b.which)!=null?j:b.keyCode;this.search_field_scale();switch(g){case 8:if(this.is_multiple&&this.backstroke_length<1&&this.choices>0)return this.keydown_backstroke();else if(!this.pending_backstroke){this.result_clear_highlight();
return this.results_search()}break;case 13:b.preventDefault();if(this.results_showing)return this.result_select(b);break;case 27:if(this.results_showing)return this.results_hide();break;case 9:case 38:case 40:case 16:case 91:case 17:break;default:return this.results_search()}};c.prototype.keydown_checker=function(b){var g,j;g=(j=b.which)!=null?j:b.keyCode;this.search_field_scale();g!==8&&this.pending_backstroke&&this.clear_backstroke();switch(g){case 8:this.backstroke_length=this.search_field.val().length;
break;case 9:this.mouse_on_container=false;break;case 13:b.preventDefault();break;case 38:b.preventDefault();this.keyup_arrow();break;case 40:this.keydown_arrow();break}};c.prototype.search_field_scale=function(){var b,g,j,i,k;if(this.is_multiple){g="position:absolute; left: -1000px; top: -1000px; display:none;";j=["font-size","font-style","font-weight","font-family","line-height","text-transform","letter-spacing"];i=0;for(k=j.length;i<k;i++){b=j[i];g+=b+":"+this.search_field.css(b)+";"}b=e("<div />",
{style:g});b.text(this.search_field.val());e("body").append(b);g=b.width()+25;b.remove();if(g>this.f_width-10)g=this.f_width-10;this.search_field.css({width:g+"px"});b=this.container.height();return this.dropdown.css({top:b+"px"})}};c.prototype.generate_field_id=function(){var b;b=this.generate_random_id();return this.form_field.id=b};c.prototype.generate_random_id=function(){var b;for(b="sel"+this.generate_random_char()+this.generate_random_char()+this.generate_random_char();e("#"+b).length>0;)b+=
this.generate_random_char();return b};c.prototype.generate_random_char=function(){var b;b=Math.floor(Math.random()*36);return"0123456789ABCDEFGHIJKLMNOPQRSTUVWXTZ".substring(b,b+1)};return c}();f=function(c){return c.outerWidth()-c.width()};d.get_side_border_padding=f}).call(this);
(function(){var e;e=function(){function h(){this.options_index=0;this.parsed=[]}h.prototype.add_node=function(f){return f.nodeName==="OPTGROUP"?this.add_group(f):this.add_option(f)};h.prototype.add_group=function(f){var d,a,c,b,g,j;d=this.parsed.length;this.parsed.push({array_index:d,group:true,label:f.label,children:0,disabled:f.disabled});g=f.childNodes;j=[];c=0;for(b=g.length;c<b;c++){a=g[c];j.push(this.add_option(a,d,f.disabled))}return j};h.prototype.add_option=function(f,d,a){if(f.nodeName===
"OPTION"){if(f.text!==""){if(d!=null)this.parsed[d].children+=1;this.parsed.push({array_index:this.parsed.length,options_index:this.options_index,value:f.value,text:f.text,html:f.innerHTML,selected:f.selected,disabled:a===true?a:f.disabled,group_array_index:d})}else this.parsed.push({array_index:this.parsed.length,options_index:this.options_index,empty:true});return this.options_index+=1}};return h}();e.select_to_array=function(h){var f,d,a,c;f=new e;c=h.childNodes;d=0;for(a=c.length;d<a;d++){h=c[d];
f.add_node(h)}return f.parsed};this.SelectParser=e}).call(this);
(function(e){function h(){if(e.browser.msie){var i=e(document).height(),k=e(window).height();return[window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth,i-k<20?k:i]}return[e(document).width(),e(document).height()]}function f(i){if(i)return i.call(e.mask)}e.tools=e.tools||{version:"@VERSION"};var d;d=e.tools.expose={conf:{maskId:"exposeMask",loadSpeed:"slow",closeSpeed:"fast",closeOnClick:true,closeOnEsc:true,zIndex:9998,opacity:0.8,startOpacity:0,color:"#fff",onLoad:null,
onClose:null}};var a,c,b,g,j;e.mask={load:function(i,k){if(b)return this;if(typeof i=="string")i={color:i};i=i||g;g=i=e.extend(e.extend({},d.conf),i);a=e("#"+i.maskId);if(!a.length){a=e("<div/>").attr("id",i.maskId);e("body").append(a)}var n=h();a.css({position:"absolute",top:0,left:0,width:n[0],height:n[1],display:"none",opacity:i.startOpacity,zIndex:i.zIndex});i.color&&a.css("backgroundColor",i.color);if(f(i.onBeforeLoad)===false)return this;i.closeOnEsc&&e(document).bind("keydown.mask",function(m){m.keyCode==
27&&e.mask.close(m)});i.closeOnClick&&a.bind("click.mask",function(m){e.mask.close(m)});e(window).bind("resize.mask",function(){e.mask.fit()});if(k&&k.length){j=k.eq(0).css("zIndex");e.each(k,function(){var m=e(this);/relative|absolute|fixed/i.test(m.css("position"))||m.css("position","relative")});c=k.css({zIndex:Math.max(i.zIndex+1,j=="auto"?0:j)})}a.css({display:"block"}).fadeTo(i.loadSpeed,i.opacity,function(){e.mask.fit();f(i.onLoad)});b=true;return this},close:function(){if(b){if(f(g.onBeforeClose)===
false)return this;a.fadeOut(g.closeSpeed,function(){f(g.onClose);c&&c.css({zIndex:j})});e(document).unbind("keydown.mask");a.unbind("click.mask");e(window).unbind("resize.mask");b=false}return this},fit:function(){if(b){var i=h();a.css({width:i[0],height:i[1]})}},getMask:function(){return a},isLoaded:function(){return b},getConf:function(){return g},getExposed:function(){return c}};e.fn.mask=function(i){e.mask.load(i);return this};e.fn.expose=function(i){e.mask.load(i,this);return this}})(jQuery);
(function(e){function h(a,c){var b=this,g=a.add(b),j=e(window),i,k,n,m=e.tools.expose&&(c.mask||c.expose),o=Math.random().toString().slice(10);if(m){if(typeof m=="string")m={color:m};m.closeOnClick=m.closeOnEsc=false}var r=c.target||a.attr("rel");k=r?e(r):a;if(!k.length)throw"Could not find Overlay: "+r;a&&a.index(k)==-1&&a.click(function(l){b.load(l);return l.preventDefault()});e.extend(b,{load:function(l){if(b.isOpened())return b;var p=d[c.effect];if(!p)throw'Overlay: cannot find effect : "'+c.effect+
'"';c.oneInstance&&e.each(f,function(){this.close(l)});l=l||e.Event();l.type="onBeforeLoad";g.trigger(l);if(l.isDefaultPrevented())return b;n=true;m&&e(k).expose(m);var q=c.top,s=c.left,t=k.outerWidth({margin:true}),v=k.outerHeight({margin:true});if(typeof q=="string")q=q=="center"?Math.max((j.height()-v)/2,0):parseInt(q,10)/100*j.height();if(s=="center")s=Math.max((j.width()-t)/2,0);p[0].call(b,{top:q,left:s},function(){if(n){l.type="onLoad";g.trigger(l)}});m&&c.closeOnClick&&e.mask.getMask().one("click",
b.close);c.closeOnClick&&e(document).bind("click."+o,function(u){e(u.target).parents(k).length||b.close(u)});c.closeOnEsc&&e(document).bind("keydown."+o,function(u){u.keyCode==27&&b.close(u)});return b},close:function(l){if(!b.isOpened())return b;l=l||e.Event();l.type="onBeforeClose";g.trigger(l);if(!l.isDefaultPrevented()){n=false;d[c.effect][1].call(b,function(){l.type="onClose";g.trigger(l)});e(document).unbind("click."+o).unbind("keydown."+o);m&&e.mask.close();return b}},getOverlay:function(){return k},
getTrigger:function(){return a},getClosers:function(){return i},isOpened:function(){return n},getConf:function(){return c}});e.each("onBeforeLoad,onStart,onLoad,onBeforeClose,onClose".split(","),function(l,p){e.isFunction(c[p])&&e(b).bind(p,c[p]);b[p]=function(q){e(b).bind(p,q);return b}});i=k.find(c.close||".close");if(!i.length&&!c.close){i=e('<a class="close"></a>');k.prepend(i)}i.click(function(l){b.close(l)});c.load&&b.load()}e.tools=e.tools||{version:"@VERSION"};e.tools.overlay={addEffect:function(a,
c,b){d[a]=[c,b]},conf:{close:null,closeOnClick:true,closeOnEsc:true,closeSpeed:"fast",effect:"default",fixed:!e.browser.msie||e.browser.version>6,left:"center",load:false,mask:null,oneInstance:true,speed:"normal",target:null,top:"10%"}};var f=[],d={};e.tools.overlay.addEffect("default",function(a,c){var b=this.getConf(),g=e(window);if(!b.fixed){a.top+=g.scrollTop();a.left+=g.scrollLeft()}a.position=b.fixed?"fixed":"absolute";this.getOverlay().css(a).fadeIn(b.speed,c)},function(a){this.getOverlay().fadeOut(this.getConf().closeSpeed,
a)});e.fn.overlay=function(a){var c=this.data("overlay");if(c)return c;if(e.isFunction(a))a={onBeforeLoad:a};a=e.extend(true,{},e.tools.overlay.conf,a);this.each(function(){c=new h(e(this),a);f.push(c);e(this).data("overlay",c)});return a.api?c:this}})(jQuery);
(function(e){e.fn.mqlkey=function(f){return this.each(function(){var d=e(this);if(d.is(":text")){var a=d.data("mqlkey");a&&a._destroy();a=new h(this,f);d.data("mqlkey",a)}})};var h=e.mqlkey=function(f,d){this.options=e.extend(true,{},h.defaults,d);this.input=e(f);this.original=this.input.val();this.init()};h.prototype={init:function(){var f=this;this.input.bind("keyup.mqlkey",function(d){f.textchange(d)}).bind(e.browser.msie?"paste.mqlkey":"input.mqlkey",function(d){f.textchange(d)});if(this.options.source){this.source=
e(this.options.source);this.source_generate=true;this.input.bind("change.mqlkey",function(){f.source_generate=false});this.source.bind("change.mqlkey",function(){if(f.source_generate){var d=h.from(f.source.val());f.input.val(d).trigger("keyup")}})}},_destroy:function(){this.input.unbind(".mqlkey");this.source&&this.source.unbind("change.mqlkey")},textchange:function(f){clearTimeout(this.textchange_timeout);var d=this;this.textchange_timeout=setTimeout(function(){d.textchange_delay(f)},200)},textchange_delay:function(){this.input.trigger("textchange");
var f=e.trim(this.input.val());return f===this.original&&f!==""?this.valid(f):h.reserved_word(f)?this.invalid(f,f+" is a reserved word."):h.test(f,this.options.schema)?f.length<this.options.minlen?this.invalid(f):this.options.check_key?this.check_key(f):this.valid(f):this.invalid(f)},check_key:function(f){var d=this;if(this.xhr){this.xhr.abort();this.xhr=null}var a={id:null,key:{namespace:this.options.namespace,value:f}};clearTimeout(this.check_key.timeout);this.check_key.timeout=setTimeout(function(){d.xhr=
d.options.mqlread(a,function(c){return c?d.invalid(f,"Key already exists"):d.valid(f)},function(c){return c?d.invalid(c.responseText()):d.invalid("mqlread error!")})},200)},valid:function(f){this.input.trigger("valid",f)},invalid:function(f,d){if(!d){d=this.options.minlen>1?"Key must be "+this.options.minlen+" or more alphanumeric characters":"Key must be alphanumeric";d+=", lowercase, begin with a letter and not end with a non-alphanumeric character. Underscores are allowed but not consecutively."}this.input.trigger("invalid",
d)}};e.extend(h,{defaults:{minlen:1,check_key:true,namespace:"/",mqlread:function(f,d,a){return h.mqlread(null,f,d,a)},source:null,schema:false},mqlread:function(f,d,a,c){f={url:f||"http://api.freebase.com/api/service/mqlread",data:{query:JSON.stringify({query:d})},dataType:"jsonp",success:function(b){return a(b.result)},error:c};return e.ajax(f)},from:function(f){f=f.toLowerCase();f=f.replace(/[^a-z0-9]/g,"_");f=f.replace(/\_\_+/g,"_");f=f.replace(/[^a-z0-9]+$/,"");f=f.replace(/^[^a-z]+/,"");if(h.reserved_word(f))f=
"x_"+f;return f},reservedwords:"meta typeguid left right datatype scope attribute relationship property link class future update insert delete replace create destroy default sort limit offset optional pagesize cursor index !index for while as in is if else return count function read write select var connect this self super xml sql mql any all macro estimate-count",typeonlywords:"guid id object domain name key type keys value timestamp creator permission namespace unique schema reverse",_reserved_word:null,
reserved_word:function(f){if(!h._reserved_word){h._reserved_word={};e.each([h.reservedwords,h.typeonlywords],function(d,a){e.each(a.split(" "),function(c,b){h._reserved_word[b]=1})})}return h._reserved_word[f]===1},fast:/^[A-Za-z0-9](?:[_-]?[A-Za-z0-9])*$/,slow:/^(?:[A-Za-z0-9]|\$[A-F0-9]{4})(?:[_-]?[A-Za-z0-9]|[_-]?\$[A-F0-9]{4})*$/,schema:/^[a-z](?:_?[a-z0-9])*$/,test:function(f,d){if(d)return h.schema.test(f);return h.fast.test(f)||h.slow.test(f)}})})(jQuery);
(function(e,h){h.require("dojo.date.stamp");h.require("dojo.date.locale");h.require("dojo.number");e.fn.validate_input=function(d){return this.each(function(){var a=e(this);if(a.is(":text")){var c=a.data("$.validate_input");c&&c._destroy();c=new f(this,d);a.data("$.validate_input",c)}})};var f=e.validate_input=function(d,a){var c=this.options=e.extend(true,{},f.defaults,a);if(typeof c.validator!=="function")throw"A validator is required";if(!c.lang)c.lang="/lang/en";c.lang=c.lang==="/lang/en"?["lang/en"]:
[c.lang,"/lang/en"];c.locales=[];e.each(c.lang,function(g,j){c.locales[g]=h.i18n.normalizeLocale(j.split("/").pop())});this.input=e(d);this.init();var b=this;this.input.bind("remove",function(){b._destroy()});return this};f.prototype={init:function(){var d=this;this.input.bind("keyup.validate_input",function(a){d.textchange(a)}).bind(e.browser.msie?"paste.validate_input":"input.validate_input",function(a){d.textchange(a)}).bind("keypress.validate_input",function(a){a.keyCode===13&&d.validate(true)}).bind("blur.validate_input",
function(){d.validate(true)})},_destroy:function(){this.input.unbind(".validate_input")},valid:function(d){this.input.trigger("valid",d)},invalid:function(d,a){this.input.trigger("invalid",a)},empty:function(){this.input.trigger("empty")},textchange:function(){clearTimeout(this.textchange_timeout);var d=this;this.textchange_timeout=setTimeout(function(){d.validate()},200)},validate:function(d){d&&clearTimeout(this.textchange_timeout);d=this.options;var a=e.trim(this.input.val());if(a==="")return this.empty();
try{return this.valid(d.validator(a,d))}catch(c){return this.invalid(a,""+c)}}};e.extend(f,{defaults:{validator:function(d){return{text:d,value:d}}},log:function(){},invalid:function(d,a,c,b){throw new Error("Invalid "+c+(b?": "+b:""));},text:function(d,a){if(d.lengh>4096)return this.invalid(d,a,type,"Text too long");return{text:d,value:d}},topic:function(){return f.defaults.validator},enumerated:function(){return f.defaults.validator},"boolean":function(){return f.defaults.validator},uri:function(d,
a){var c=f.uri.regex;if(!c)c=f.uri.regex=/^(https?|ftp):\/\/(((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:)*@)?(((\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5]))|((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?)(:\d*)?)(\/((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)+(\/(([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)*)*)?)?(\?((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|[\uE000-\uF8FF]|\/|\?)*)?(\#((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|\/|\?)*)?$/i;
if(c.test(d))return{text:d,value:d};return f.invalid(d,a,"uri")},"int":function(d,a){return f.number.parse(d,a,false)},"float":function(d,a){return f.number.parse(d,a,true)},number:function(d,a,c){return f.number.parse(d,a,c)},datetime:function(d,a){return f.datetime.parse(d,a)},mqlkey:function(d,a){var c=f.mqlkey.regex;if(!c)c=f.mqlkey.regex=/^[A-Za-z0-9][A-Za-z0-9_-]*$/;if(c.test(d))return{text:d,value:d};return f.invalid(d,a,"mqlkey")}});e.extend(f.number,{parse:function(d,a,c){var b=a&&a.locales||
["en"],g,j;g=0;for(j=b.length;g<j;g++){var i=b[g];a=h.number.parse(d,{locale:i});if(!isNaN(a)){d={};if(c){d.value=a;d.text=h.number.format(a,{locale:i})}else{d.value=h.number.round(a,0);d.text=h.number.format(d.value,{locale:i})}return d}}throw f.invalid("number",d);}});e.extend(f.datetime,{formats:["yyyy",["dateFormatItem-y"],"yyyy-MM",["dateFormatItem-yM","dateFormatItem-yMMM"],"yyyy-MM-dd",["dateFormat-short","dateFormat-medium","dateFormat-long"]],parse:function(d,a){if(!h.date.stamp._isoRegExp)h.date.stamp._isoRegExp=
/^(?:(-?\d{4})(?:-(\d{2})(?:-(\d{2}))?)?)?(?:T(\d{2}):(\d{2})(?::(\d{2})(.\d+)?)?((?:[+-](\d{2}):(\d{2}))|Z)?)?$/;var c=h.date.stamp.fromISOString(d);if(c)return{text:d,value:d,date:c};var b=a&&a.locales||["en"],g,j,i,k,n,m;g=0;for(j=b.length;g<j;g++){var o=b[g],r=h.date.locale._getGregorianBundle(o);i=0;for(k=f.datetime.formats.length;i<k;i+=2){var l=f.datetime.formats[i],p=f.datetime.formats[i+1];n=0;for(m=p.length;n<m;n++){var q=r[p[n]];if(q){q=i18n.normalize_pattern(q);try{c=h.date.locale.parse(d,
{datePattern:q,selector:"date",locale:o});return{text:d,value:h.date.locale.format(c,{datePattern:l,selector:"date"}),date:c}}catch(s){}}}}}throw f.invalid("datetime",d);}})})(jQuery,dojo);
(function(e){e.fn.data_input=function(h){return this.each(function(){var f=e(this),d=f.data("$.data_input");d&&d._destroy();d=new e.data_input(this,h);f.data("$.data_input",d)})};e.data_input=function(h,f){this.options=e.extend(true,{},f);this.container=e(h);this.metadata=this.container.metadata();this.input=e(":input",this.container);this.init();var d=this;this.input.bind("remove",function(){d._destroy()})};e.data_input.prototype={init:function(){var h=this,f=this.container,d=this.input,a=this.options;
d.bind("focusin.data_input",function(){h.container.addClass("focus")}).bind("focusout.data_input",function(){h.container.removeClass("focus")}).bind("valid.data_input",function(b,g){function j(){h.container.data("data",i);h.container.removeClass("error").addClass("valid");h.container.trigger("valid")}var i={name:h.input.attr("name")};if(g.id)i.id=g.id;else if(g.create_new){i.create_new=g.create_new;i.lang=h.metadata.lang||a.lang}else{i.value=g.value;if(h.metadata.type==="/type/text")i.lang=h.metadata.lang||
a.lang;else if(h.metadata.type==="/type/key")i.namespace=g.namespace}g.id&&h.metadata.type&&h.options.incompatible_types?h.options.incompatible_types.check(g.id,h.metadata.type,{compatible:j,incompatible:h.options.incompatible_types.inline_suggest_incompatible_callback(h.input,{onConfirm:j})}):j()}).bind("invalid.data_input",function(){h.container.removeData("data");h.container.removeClass("valid").addClass("error");h.container.trigger("invalid")}).bind("empty.data_input",function(){var b={name:h.input.attr("name")};
if(h.metadata&&h.metadata.lang)b.lang=h.metadata.lang;h.container.data("data",b);h.container.removeClass("valid").removeClass("error");h.container.trigger("empty")}).bind("keypress.data_input",function(b){b.keyCode===13&&!b.isDefaultPrevented()&&h.container.trigger("submit")}).bind("keyup.data_input",function(b){b.keyCode===27&&h.container.trigger("cancel")});if(f.is(".topic")){f=h.metadata.type;var c=null;if(a.suggest_impl)c=a.suggest_impl.instance(f,true,h.metadata&&h.metadata.lang||a.lang);d.validate_topic(c).bind("valid.data_input",
function(b,g){h.fb_select(g)}).bind("invalid.data_input",function(){h.fb_textchange()});if(this.metadata&&this.metadata.id){d.data("data.suggest",this.metadata);this.validate()}}else if(f.is(".text"))d.validate_input({validator:e.validate_input.text});else if(f.is(".datetime"))d.validate_input({validator:e.validate_input.datetime,lang:a.lang});else if(f.is(".enumerated")){d.validate_enumerated().bind("valid.data_input",function(b,g){h.fb_select(g)}).bind("invalid.data_input",function(){h.fb_textchange()});
this.metadata&&this.metadata.id&&this.validate()}else if(f.is(".int"))d.validate_input({validator:e.validate_input["int"],lang:a.lang});else if(f.is(".float"))d.validate_input({validator:e.validate_input["float"],lang:a.lang});else if(f.is(".uri"))d.validate_input({validator:e.validate_input.uri});else if(f.is(".boolean"))d.validate_boolean();else if(f.is(".enumeration"))d.validate_input({validator:e.validate_input.mqlkey});else if(f.is(".key"))d.validate_key(a,this.metadata);else if(f.is(".rawstring"))d.validate_input({validator:e.validate_input.text});
else throw new Error("Invalid data-input: "+f.attr("class"));},_destroy:function(){this.input.unbind(".data_input")},validate:function(){var h=this.input;e.each(["$.validate_topic","$.validate_input","$.validate_enumerated","$.validate_boolean","$.validate_key"],function(f,d){var a=h.data(d);if(a){a.validate(true);return false}})},reset:function(){this.container.removeData("data");if(this.input.is(":text"))this.input.val("");else if(this.input.is("select"))this.input[0].selectedIndex=0;else this.input.is(":radio")&&
this.input.each(function(){this.checked=false})},fb_textchange:function(){},fb_select:function(){},ajax_beforeSend:function(h){if(!this.xhr_queue)this.xhr_queue=[];this.xhr_queue.push(h);this.container.trigger("loading")},ajax_complete:function(h){if(!this.xhr_queue)this.xhr_queue=[];for(var f=0,d=this.xhr_queue.length;f<d;f++)if(h===this.xhr_queue[f]){this.xhr_queue.splice(f,1);break}this.xhr_queue.length===0&&this.container.trigger("loading_complete")}};e.fn.validate_topic=function(h){return this.each(function(){var f=
e(this);if(f.is(":text")){var d=f.data("$.validate_topic");d&&d._destroy();d=new e.validate_topic(this,h);f.data("$.validate_topic",d)}})};e.validate_topic=function(h,f){this.options=e.extend(true,{},f);this.input=e(h);this.init()};e.validate_topic.prototype={init:function(){var h=this;this.input.suggest(this.options).bind("fb-textchange.validate_topic",function(){h.input.val()===""?h.empty():h.invalid()}).bind("fb-select.validate_topic",function(f,d){h.input.val(d.name!=null?d.name:d.id);h.valid(d)}).bind("fb-select-new.validate_topic",
function(f,d){h.valid(d)})},invalid:function(){this.input.trigger("invalid")},valid:function(h){if(typeof h==="string")h={create_new:h};this.input.trigger("valid",h)},empty:function(){this.input.trigger("empty")},_destroy:function(){this.input.unbind(".validate_topic")},validate:function(){if(this.input.val()==="")this.empty();else{var h=this.input.data("data.suggest");h?this.valid(h):this.invalid()}}};e.fn.validate_enumerated=function(h){return this.each(function(){var f=e(this);if(f.is("select")){var d=
f.data("$.validate_enumerated");d&&d._destroy();d=new e.validate_enumerated(this,h);f.data("$.validate_enumerated",d)}})};e.validate_enumerated=function(h,f){this.options=e.extend(true,{},f);this.input=e(h);this.init()};e.validate_enumerated.prototype={init:function(){var h=this;this.input.bind("change.validate_enumerated, keypress.validate_enumerated",function(){this.selectedIndex===0?h.empty():h.valid({text:e(":selected",this).text(),id:this.value})})},invalid:function(){this.input.trigger("invalid")},
valid:function(h){this.input.trigger("valid",h);this.input.trigger("fb-select",h)},empty:function(){this.input.trigger("empty")},_destroy:function(){this.input.unbind(".validate_enumerated")},validate:function(){var h=this.input[0];h.selectedIndex>0?this.valid({text:e(":selected",this.input).text(),id:h.value}):this.empty()}};e.fn.validate_boolean=function(h){var f,d;this.each(function(){var c=e(this);if(c.is(":radio"))if(c.val().toLowerCase()==="true")f=c;else if(c.val().toLowerCase()==="false")d=
c});if(f&&d){var a=f.data("$.validate_boolean");a&&a._destroy();a=new e.validate_boolean(f,d,h);f.data("$.validate_boolean",a)}else throw"$.fn.validate_boolean requires two radios: true and false";return this};e.validate_boolean=function(h,f,d){this.options=e.extend(true,{},d);this.tradio=h;this.fradio=f;this.input=this.tradio;this.init()};e.validate_boolean.prototype={init:function(){var h=this;this.tradio.bind("change.validate_boolean",function(){h.validate()})},_destroy:function(){this.input.unbind(".validate_boolean")},
valid:function(h){this.input.trigger("valid",h)},empty:function(){this.input.trigger("empty")},validate:function(){if(this.tradio.is(":checked"))this.valid({text:this.tradio.text(),value:true});else this.fradio.is(":checked")?this.valid({text:this.fradio.text(),value:false}):this.empty()}};e.fn.validate_key=function(h,f){var d,a;this.each(function(){var b=e(this);if(b.is(":text"))if(b.is(".key-namespace"))d=b;else if(b.is(".key-value"))a=b});if(d&&a){var c=a.data("$.validate_key");c&&c._destroy();
c=new e.validate_key(d,a,h);d.data("$.validate_key",c);if(f&&f.namespace&&f.value){d.data("data.suggest",{id:f.namespace});a.val(f.value)}}else throw"$.fn.validate_key requires two inputs: namespace and value";return this};e.validate_key=function(h,f,d){this.options=e.extend(true,{},d);this.key_namespace_input=h;this.key_value_input=f;this.input=this.key_namespace_input;this.init()};e.validate_key.prototype={init:function(){var h=this,f=null;if(this.options.suggest_impl)f=this.key_value_input.attr("name")===
"/type/namespace/keys"?this.options.suggest_impl.all("without:fus"):this.options.suggest_impl.instance("/type/namespace");this.key_namespace_input.suggest(f).bind("fb-textchange.validate_key",function(){h.validate()}).bind("fb-select.validate_key",function(d,a){h.key_namespace_input.val(a.name||a.id);h.validate()});this.key_value_input.validate_input({validator:e.validate_input.mqlkey}).bind("valid",function(d){d.stopPropagation();h.validate()}).bind("invalid",function(d){d.stopPropagation();h.validate()}).bind("empty",
function(d){d.stopPropagation();h.validate()})},_destroy:function(){this.key_namespace_input.unbind(".validate_key");this.key_value_input.unbind()},invalid:function(){this.input.trigger("invalid")},valid:function(h){this.input.trigger("valid",h)},empty:function(){this.input.trigger("empty")},validate:function(){if(this.is_valid_key_namespace()&&this.is_valid_key_value())this.valid({namespace:this.key_namespace_input.data("data.suggest").id,value:this.key_value_input.val(),text:this.key_value_input.val()});
else this.key_namespace_input.val()===""&&this.key_value_input.val()===""?this.empty():this.invalid()},is_valid_key_namespace:function(){return this.key_namespace_input.data("data.suggest")!=null},is_valid_key_value:function(){try{e.validate_input.mqlkey(this.key_value_input.val());return true}catch(h){return false}}}})(jQuery);
(function(e,h,f){var d=window.formlib={init:function(a){var c=a.event_prefix||"form.";a.form.bind(c+"submit",function(){d.submit(a)}).bind(c+"cancel",function(){d.cancel(a)}).bind(c+"error",function(b,g){d.error(a,g);a.form.removeClass("loading")}).bind(c+"success",function(){a.form.removeClass("loading")}).bind(c+"valid",function(){d.enable_submit(a)}).bind(c+"invalid",function(){d.disable_submit(a)});d.init_submit_cancel(a);a.init(a)},submit:function(a){if(!a.form.is(".loading"))if(d.is_submit_enabled(a)){document.activeElement&&
e(document.activeElement).blur();d.clear_message(a);if(a.validate(a)){a.form.addClass("loading");a.submit(a,d.default_submit_ajax_options(a))}}},cancel:function(){},init_inline_add_form:function(a){var c=a.event_prefix||"form.inline_add_form.";a.edit_row.bind(c+"submit",function(){d.submit_inline_add_form(a)}).bind(c+"cancel",function(){d.cancel_inline_add_form(a)}).bind(c+"error",function(b,g){d.error(a,g);a.edit_row.removeClass("loading")}).bind(c+"success",function(){a.edit_row.removeClass("loading")}).bind(c+
"valid",function(){d.enable_submit(a)}).bind(c+"invalid",function(){d.disable_submit(a)});d.init_submit_cancel(a);a.trigger&&a.trigger.parents(".trigger-row:first").hide();a.body.append(a.head_row).append(a.edit_row).append(a.submit_row);a.init(a)},submit_inline_add_form:function(a){if(!a.edit_row.is(".loading"))if(d.is_submit_enabled(a)){document.activeElement&&e(document.activeElement).blur();d.clear_message(a);if(a.validate(a)){a.edit_row.addClass("loading");a.submit(a,d.default_submit_ajax_options(a))}}},
success_inline_add_form:function(a,c){a.head_row.before(c);h.ize(c);a.reset(a);a.edit_row.trigger(a.event_prefix+"success")},cancel_inline_add_form:function(a){a.head_row.remove();a.edit_row.remove();a.submit_row.remove();a.trigger&&a.trigger.parents(".trigger-row:first").show()},init_inline_edit_form:function(a){var c=a.event_prefix||"form.inline_edit_form.";a.edit_row.bind(c+"submit",function(){d.submit_inline_edit_form(a)}).bind(c+"cancel",function(){d.cancel_inline_edit_form(a)}).bind(c+"error",
function(b,g){d.error(a,g);a.edit_row.removeClass("loading")}).bind(c+"success",function(){a.edit_row.removeClass("loading")}).bind(c+"valid",function(){d.enable_submit(a)}).bind(c+"invalid",function(){d.disable_submit(a)});d.init_submit_cancel(a);a.row.hide();a.row.before(a.head_row).before(a.edit_row).before(a.submit_row);a.init(a)},submit_inline_edit_form:function(a){if(!a.edit_row.is(".loading"))if(d.is_submit_enabled(a)){document.activeElement&&e(document.activeElement).blur();d.clear_message(a);
if(a.validate(a)){a.edit_row.addClass("loading");a.submit(a,d.default_submit_ajax_options(a))}}},success_inline_edit_form:function(a,c){a.row.replaceWith(c);a.row=c;h.ize(c);a.edit_row.trigger(a.event_prefix+"cancel")},cancel_inline_edit_form:function(a){a.head_row.remove();a.edit_row.remove();a.submit_row.remove();a.row.show()},success_inline_delete:function(a,c,b){a.hide().addClass("old-row");a.after(c);c.append(a);if(b){a=e('<a href="#">Undo</a>');e(".msg-default",c).next().append(a);a.click(function(){b();
return false})}},success_inline_delete_undo:function(a){var c=e(".old-row",a);a.before(c);c.show().removeClass("old-row");a.remove()},init_modal_form:function(a){e(document.body).append(a.form.hide());var c=a.event_prefix||"form.modal_form.";a.form.bind(c+"submit",function(){d.submit_modal_form(a)}).bind(c+"cancel",function(){d.cancel_modal_form(a)}).bind(c+"error",function(b,g){d.error(a,g);a.form.removeClass("loading")}).bind(c+"success",function(){a.form.removeClass("loading")}).bind(c+"valid",
function(){d.enable_submit(a)}).bind(c+"invalid",function(){d.disable_submit(a)});d.init_submit_cancel(a);a.form.overlay({close:".modal-buttons .cancel",closeOnClick:false,load:true,fixed:false,mask:{color:"#000",loadSpeed:200,opacity:0.5},onLoad:function(){a.overlay=this;a.init(a)}})},submit_modal_form:function(a){if(!a.form.is(".loading"))if(d.is_submit_enabled(a)){document.activeElement&&e(document.activeElement).blur();d.clear_message(a);if(a.validate(a)){a.form.addClass("loading");a.submit(a,
d.default_submit_ajax_options(a))}}},cancel_modal_form:function(a){a.form.data("overlay").close()},init_submit_cancel:function(a){var c=a.form||a.edit_row,b=a.form||a.submit_row,g=a.event_prefix;a=e(".save",b).click(function(){c.trigger(g+"submit")});d.disable(a);e(".cancel",b).click(function(){c.trigger(g+"cancel")});e(":input",c).keypress(function(j){j.keyCode===13&&!j.isDefaultPrevented()&&c.trigger(g+"submit")}).keyup(function(j){j.keyCode===27&&c.trigger(g+"cancel")})},disable:function(a){e(a).attr("disabled",
"disabled").addClass("disabled")},enable:function(a){e(a).removeAttr("disabled").removeClass("disabled")},disable_submit:function(a){d.disable(e(".save",a.form||a.submit_row))},enable_submit:function(a){d.enable(e(".save",a.form||a.submit_row))},is_submit_enabled:function(a){return!e(".save",a.form||a.submit_row).is(":disabled")},init_mqlkey:function(a,c){return a.next(".key-status").removeClass("valid invalid loading").text("").removeAttr("title").end().mqlkey(c).bind("valid",function(){e(this).next(".key-status").removeClass("invalid loading").addClass("valid").text("valid").attr("title",
"Key is available")}).bind("invalid",function(b,g){e(this).next(".key-status").removeClass("valid loading").addClass("invalid").text("invalid").attr("title",g)}).bind("textchange",function(){e(this).next(".key-status").removeClass("valid invalid").text("loading").addClass("loading")})},validate_mqlkey:function(a,c){var b=c.next(".key-status"),g=c.val();if(g===""){c.trigger(a.event_prefix+"error","Key is required");return false}if(g===c.data("mqlkey").original)return true;if(b.is(".invalid")){c.trigger(a.event_prefix+
"error",b.attr("title"));return false}else if(b.is(".loading"))return false;return true},error:function(a,c){d.disable_submit(a);return d.message(a,c,"error")},message:function(a,c,b){var g=a.head_row;if(!g&&a.form)g=e(".row-msg",a.form);if(g&&g.length){g.find(".close-msg").css("visibility","visible").next().find(".msg-default").hide().next().text(c);g.addClass("row-msg");b&&g.addClass("row-msg-"+b)}},clear_message:function(){},default_begin_ajax_options:function(){return d._default_ajax_options("GET")},
default_submit_ajax_options:function(a){a=a||{};var c=e.extend(d._default_ajax_options("POST"),a.ajax,{beforeSend:function(){f.doing("Saving...");a.beforeSend&&a.beforeSend.apply(null,arguments)},complete:function(){f.clear();a.complete&&a.complete.apply(null,arguments)}}),b=a.submit_row||a.form;b&&e("input[type=hidden]",b).each(function(){c.data[this.name]=this.value});return c},_default_ajax_options:function(a){return{data:{},dataType:"json",type:a||"GET",success:function(c,b,g){if(!d.check_ajax_success.apply(this,
arguments))return this._error.apply(this,[g]);this.onsuccess&&this.onsuccess.apply(this,arguments)},error:function(){d.check_ajax_error.apply(this,arguments);return this._error.apply(this,arguments)},_error:function(c){if(c.status===401)e(window).trigger("fb.user.unauthorized");else if(this.onerror)this.onerror.apply(this,[c.responseText].concat(Array.prototype.slice.call(arguments)));else{var b={},g=this;e.each(["url","data","dataType","type"],function(j,i){b[i]=g[i]});e.each(["status","statusText",
"responseText"],function(j,i){b[i]=c[i]});b.responseHeaders=c.getAllResponseHeaders()}}}},check_ajax_success:function(){return d.check_api_response.apply(this,arguments)},check_ajax_error:function(a){var c=a.responseText;try{c=JSON.stringify(c)}catch(b){}return d.check_api_response.apply(this,[c,a.statusText,a])},check_api_response:function(a,c,b){if(typeof a==="object"){if(a.code!=="/api/status/ok")return false}else if(b.status!==200)return false;return true}}})(jQuery,window.i18n,window.freebase.status);
(function(e,h,f){var d=h.queryeditor.edit={create_begin:function(){e.ajax(e.extend(f.default_begin_ajax_options(),{url:h.h.ajax_url("create_begin.ajax"),data:{query:h.queryeditor.cuecard.queryEditor._editor.getCode()},onsuccess:function(a){a=e(a.result.html);a={event_prefix:"fb.queryeditor.create.",init:d.create_init,validate:d.create_validate,submit:d.create_submit,ajax:{url:h.h.ajax_url("create_submit.ajax")},form:a};f.init_modal_form(a)}}))},create_init:function(a){var c=function(){if(this.value){f.init_mqlkey(j,
{source:b,namespace:this.value+"/views",mqlread:h.mqlread});h.enable(j)}else h.disable(j);f.disable_submit(a)},b=e("input[name=name]:visible",a.form).focus(),g=e(":input[name=domain]",a.form).chosen().change(c),j=e(":input[name=key]",a.form).bind("valid",function(){f.enable_submit(a)}).bind("invalid",function(){f.disable_submit(a)});c.call(g[0])},create_validate:function(a){var c=e("input[name=name]:visible",a.form).val(),b=e(":input[name=domain]",a.form).val();a=e(":input[name=key]",a.form).val();
return c&&b&&a},create_submit:function(a,c){c.data.name=e("input[name=name]:visible",a.form).val();c.data.domain=e(":input[name=domain]",a.form).val();c.data.key=e(":input[name=key]",a.form).val();var b=e("textarea[name=description]",a.form).val();if(b)c.data.description=b;e.ajax(e.extend(c,{onsuccess:function(g){window.location=g.result.url},onerror:function(g){a.form.trigger(a.event_prefix+"error",g)}}))},save_submit:function(){var a=f.default_submit_ajax_options();e.ajax(e.extend(a,{url:h.h.ajax_url("save_submit.ajax"),
data:{topic:h.c.id,query:h.queryeditor.cuecard.queryEditor._editor.getCode()},onsuccess:function(){h.status.info("Saved");h.queryeditor.is_dirty=false;e("#save-query").addClass("disabled")},onerror:function(c){h.status.error(c);console.log("error")}}))}}})(jQuery,window.freebase,window.formlib);
