
/*
 * Copyright 2012, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Additional Licenses for Third Party components can be found here:
 * http://wiki.freebase.com/wiki/Freebase_Site_License
 *
 */
(function(a,c){var g,i,f,d,b,e,j,t,l,r,h,k,s,m,o,q,p,u,n,w,y,A,C,z;g=function(a){return new g.prototype.init(a)};"undefined"!==typeof require&&"undefined"!==typeof exports&&"undefined"!==typeof module?module.exports=g:a.Globalize=g;g.cultures={};g.prototype={constructor:g,init:function(a){this.cultures=g.cultures;this.cultureSelector=a;return this}};g.prototype.init.prototype=g.prototype;g.cultures["default"]={name:"en",englishName:"English",nativeName:"English",isRTL:!1,language:"en",numberFormat:{pattern:["-n"],
decimals:2,",":",",".":".",groupSizes:[3],"+":"+","-":"-",NaN:"NaN",negativeInfinity:"-Infinity",positiveInfinity:"Infinity",percent:{pattern:["-n %","n %"],decimals:2,groupSizes:[3],",":",",".":".",symbol:"%"},currency:{pattern:["($n)","$n"],decimals:2,groupSizes:[3],",":",",".":".",symbol:"$"}},calendars:{standard:{name:"Gregorian_USEnglish","/":"/",":":":",firstDay:0,days:{names:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),namesAbbr:"Sun Mon Tue Wed Thu Fri Sat".split(" "),
namesShort:"Su Mo Tu We Th Fr Sa".split(" ")},months:{names:"January February March April May June July August September October November December ".split(" "),namesAbbr:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec ".split(" ")},AM:["AM","am","AM"],PM:["PM","pm","PM"],eras:[{name:"A.D.",start:null,offset:0}],twoDigitYearMax:2029,patterns:{d:"M/d/yyyy",D:"dddd, MMMM dd, yyyy",t:"h:mm tt",T:"h:mm:ss tt",f:"dddd, MMMM dd, yyyy h:mm tt",F:"dddd, MMMM dd, yyyy h:mm:ss tt",M:"MMMM dd",Y:"yyyy MMMM",
S:"yyyy'-'MM'-'dd'T'HH':'mm':'ss"}}},messages:{}};g.cultures["default"].calendar=g.cultures["default"].calendars.standard;g.cultures.en=g.cultures["default"];g.cultureSelector="en";i=/^0x[a-f0-9]+$/i;f=/^[+\-]?infinity$/i;d=/^[+\-]?\d*\.?\d*(e[+\-]?\d+)?$/;b=/^\s+|\s+$/g;e=function(a,b){if(a.indexOf)return a.indexOf(b);for(var e=0,d=a.length;e<d;e++)if(a[e]===b)return e;return-1};j=function(a,b){return a.substr(a.length-b.length)===b};t=function(){var a,b,e,d,f,j=arguments[0]||{},i=1,k=arguments.length,
g=!1;"boolean"===typeof j&&(g=j,j=arguments[1]||{},i=2);for("object"!==typeof j&&!r(j)&&(j={});i<k;i++)if(null!=(a=arguments[i]))for(b in a)e=j[b],d=a[b],j!==d&&(g&&d&&(h(d)||(f=l(d)))?(f?(f=!1,e=e&&l(e)?e:[]):e=e&&h(e)?e:{},j[b]=t(g,e,d)):d!==c&&(j[b]=d));return j};l=Array.isArray||function(a){return"[object Array]"===Object.prototype.toString.call(a)};r=function(a){return"[object Function]"===Object.prototype.toString.call(a)};h=function(a){return"[object Object]"===Object.prototype.toString.call(a)};
k=function(a,b){return 0===a.indexOf(b)};s=function(a){return(a+"").replace(b,"")};m=function(a){return isNaN(a)?NaN:Math[0>a?"ceil":"floor"](a)};o=function(a,b,e){var d;for(d=a.length;d<b;d+=1)a=e?"0"+a:a+"0";return a};q=function(a,b){for(var e=0,d=!1,h=0,c=a.length;h<c;h++){var f=a.charAt(h);switch(f){case "'":d?b.push("'"):e++;d=!1;break;case "\\":d&&b.push("\\");d=!d;break;default:b.push(f),d=!1}}return e};p=function(a,b){var b=b||"F",e;e=a.patterns;var d=b.length;if(1===d){e=e[b];if(!e)throw"Invalid date format string '"+
b+"'.";b=e}else 2===d&&"%"===b.charAt(0)&&(b=b.charAt(1));return b};u=function(a,b,e){function d(a,b){var e;e=a+"";return 1<b&&e.length<b?(e=t[b-2]+e,e.substr(e.length-b,b)):e}function h(){if(r||g)return r;r=s.test(b);g=!0;return r}function c(a,b){if(n)return n[b];switch(b){case 0:return a.getFullYear();case 1:return a.getMonth();case 2:return a.getDate();default:throw"Invalid part value "+b;}}var f=e.calendar,j=f.convert;if(!b||!b.length||"i"===b){if(e&&e.name.length)if(j)e=u(a,f.patterns.F,e);else{var e=
new Date(a.getTime()),i=y(a,f.eras);e.setFullYear(A(a,f,i));e=e.toLocaleString()}else e=a.toString();return e}var i=f.eras,l="s"===b,b=p(f,b),e=[],k,t=["0","00","000"],r,g,s=/([^d]|^)(d|dd)([^d]|$)/g,m=0,o=w(),n;for(!l&&j&&(n=j.fromGregorian(a));;){k=o.lastIndex;j=o.exec(b);k=b.slice(k,j?j.index:b.length);m+=q(k,e);if(!j)break;if(m%2)e.push(j[0]);else switch(k=j[0],j=k.length,k){case "ddd":case "dddd":e.push((3===j?f.days.namesAbbr:f.days.names)[a.getDay()]);break;case "d":case "dd":r=!0;e.push(d(c(a,
2),j));break;case "MMM":case "MMMM":k=c(a,1);e.push(f.monthsGenitive&&h()?f.monthsGenitive[3===j?"namesAbbr":"names"][k]:f.months[3===j?"namesAbbr":"names"][k]);break;case "M":case "MM":e.push(d(c(a,1)+1,j));break;case "y":case "yy":case "yyyy":k=n?n[0]:A(a,f,y(a,i),l);4>j&&(k%=100);e.push(d(k,j));break;case "h":case "hh":k=a.getHours()%12;0===k&&(k=12);e.push(d(k,j));break;case "H":case "HH":e.push(d(a.getHours(),j));break;case "m":case "mm":e.push(d(a.getMinutes(),j));break;case "s":case "ss":e.push(d(a.getSeconds(),
j));break;case "t":case "tt":k=12>a.getHours()?f.AM?f.AM[0]:" ":f.PM?f.PM[0]:" ";e.push(1===j?k.charAt(0):k);break;case "f":case "ff":case "fff":e.push(d(a.getMilliseconds(),3).substr(0,j));break;case "z":case "zz":k=a.getTimezoneOffset()/60;e.push((0>=k?"+":"-")+d(Math.floor(Math.abs(k)),j));break;case "zzz":k=a.getTimezoneOffset()/60;e.push((0>=k?"+":"-")+d(Math.floor(Math.abs(k)),2)+":"+d(Math.abs(a.getTimezoneOffset()%60),2));break;case "g":case "gg":f.eras&&e.push(f.eras[y(a,i)].name);break;
case "/":e.push(f["/"]);break;default:throw"Invalid date format pattern '"+k+"'.";}}return e.join("")};var D;D=function(a,b,e){var d=e.groupSizes,j=d[0],f=1,h=Math.pow(10,b),c=Math.round(a*h)/h;isFinite(c)||(c=a);h="";h=(c+"").split(/e/i);c=1<h.length?parseInt(h[1],10):0;a=h[0];h=a.split(".");a=h[0];h=1<h.length?h[1]:"";0<c?(h=o(h,c,!1),a+=h.slice(0,c),h=h.substr(c)):0>c&&(c=-c,a=o(a,c+1,!0),h=a.slice(-c,a.length)+h,a=a.slice(0,-c));h=0<b?e["."]+(h.length>b?h.slice(0,b):o(h,b)):"";b=a.length-1;e=
e[","];for(c="";0<=b;){if(0===j||j>b)return a.slice(0,b+1)+(c.length?e+c+h:h);c=a.slice(b-j+1,b+1)+(c.length?e+c:"");b-=j;f<d.length&&(j=d[f],f++)}return a.slice(0,b+1)+e+c+h};n=function(a,b,e){if(!isFinite(a))return Infinity===a?e.numberFormat.positiveInfinity:-Infinity===a?e.numberFormat.negativeInfinity:e.numberFormat.NaN;if(!b||"i"===b)return e.name.length?a.toLocaleString():a.toString();var b=b||"D",e=e.numberFormat,d=Math.abs(a),h=-1;1<b.length&&(h=parseInt(b.slice(1),10));var c=b.charAt(0).toUpperCase(),
j;switch(c){case "D":b="n";d=m(d);-1!==h&&(d=o(""+d,h,!0));0>a&&(d="-"+d);break;case "N":j=e;case "C":j=j||e.currency;case "P":j=j||e.percent;b=0>a?j.pattern[0]:j.pattern[1]||"n";-1===h&&(h=j.decimals);d=D(d*("P"===c?100:1),h,j);break;default:throw"Bad number format specifier: "+c;}a=/n|\$|-|%/g;for(j="";;){h=a.lastIndex;c=a.exec(b);j+=b.slice(h,c?c.index:b.length);if(!c)break;switch(c[0]){case "n":j+=d;break;case "$":j+=e.currency.symbol;break;case "-":/[1-9]/.test(d)&&(j+=e["-"]);break;case "%":j+=
e.percent.symbol}}return j};w=function(){return/\/|dddd|ddd|dd|d|MMMM|MMM|MM|M|yyyy|yy|y|hh|h|HH|H|mm|m|ss|s|tt|t|fff|ff|f|zzz|zz|z|gg|g/g};y=function(a,b){if(!b)return 0;for(var e,d=a.getTime(),h=0,j=b.length;h<j;h++)if(e=b[h].start,null===e||d>=e)return h;return 0};A=function(a,b,e,d){a=a.getFullYear();!d&&b.eras&&(a-=b.eras[e].offset);return a};var E,F,G,H,v,B,x;E=function(a,b){if(100>b){var e=new Date,d=y(e),e=A(e,a,d),d=a.twoDigitYearMax,d="string"===typeof d?(new Date).getFullYear()%100+parseInt(d,
10):d,b=b+(e-e%100);b>d&&(b-=100)}return b};F=function(a,b,d){var h=a.days,j=a._upperDays;j||(a._upperDays=j=[x(h.names),x(h.namesAbbr),x(h.namesShort)]);b=B(b);d?(a=e(j[1],b),-1===a&&(a=e(j[2],b))):a=e(j[0],b);return a};G=function(a,b,d){var h=a.months,j=a.monthsGenitive||a.months,c=a._upperMonths,f=a._upperMonthsGen;c||(a._upperMonths=c=[x(h.names),x(h.namesAbbr)],a._upperMonthsGen=f=[x(j.names),x(j.namesAbbr)]);b=B(b);a=e(d?c[1]:c[0],b);0>a&&(a=e(d?f[1]:f[0],b));return a};H=function(a,b){var e=
a._parseRegExp;if(e){var d=e[b];if(d)return d}else a._parseRegExp=e={};for(var d=p(a,b).replace(/([\^\$\.\*\+\?\|\[\]\(\)\{\}])/g,"\\\\$1"),h=["^"],j=[],c=0,f=0,i=w(),k;null!==(k=i.exec(d));){var l=d.slice(c,k.index),c=i.lastIndex,f=f+q(l,h);if(f%2)h.push(k[0]);else{var l=k[0],r=l.length;switch(l){case "dddd":case "ddd":case "MMMM":case "MMM":case "gg":case "g":l="(\\D+)";break;case "tt":case "t":l="(\\D*)";break;case "yyyy":case "fff":case "ff":case "f":l="(\\d{"+r+"})";break;case "dd":case "d":case "MM":case "M":case "yy":case "y":case "HH":case "H":case "hh":case "h":case "mm":case "m":case "ss":case "s":l=
"(\\d\\d?)";break;case "zzz":l="([+-]?\\d\\d?:\\d{2})";break;case "zz":case "z":l="([+-]?\\d\\d?)";break;case "/":l="(\\/)";break;default:throw"Invalid date format pattern '"+l+"'.";}l&&h.push(l);j.push(k[0])}}q(d.slice(c),h);h.push("$");d={regExp:h.join("").replace(/\s+/g,"\\s+"),groups:j};return e[b]=d};v=function(a,b,e){return a<b||a>e};B=function(a){return a.split("\u00a0").join(" ").toUpperCase()};x=function(a){for(var b=[],e=0,d=a.length;e<d;e++)b[e]=B(a[e]);return b};C=function(a,b,e){var a=
s(a),e=e.calendar,b=H(e,b),d=RegExp(b.regExp).exec(a);if(null===d)return null;var h=b.groups,j=b=a=null,c=null,f=null,i=0,l,r=0,t=0,g=0;l=null;for(var q=!1,m=0,o=h.length;m<o;m++){var p=d[m+1];if(p){var n=h[m],w=n.length,u=parseInt(p,10);switch(n){case "dd":case "d":c=u;if(v(c,1,31))return null;break;case "MMM":case "MMMM":j=G(e,p,3===w);if(v(j,0,11))return null;break;case "M":case "MM":j=u-1;if(v(j,0,11))return null;break;case "y":case "yy":case "yyyy":b=4>w?E(e,u):u;if(v(b,0,9999))return null;break;
case "h":case "hh":i=u;12===i&&(i=0);if(v(i,0,11))return null;break;case "H":case "HH":i=u;if(v(i,0,23))return null;break;case "m":case "mm":r=u;if(v(r,0,59))return null;break;case "s":case "ss":t=u;if(v(t,0,59))return null;break;case "tt":case "t":q=e.PM&&(p===e.PM[0]||p===e.PM[1]||p===e.PM[2]);if(!q&&(!e.AM||p!==e.AM[0]&&p!==e.AM[1]&&p!==e.AM[2]))return null;break;case "f":case "ff":case "fff":g=u*Math.pow(10,3-w);if(v(g,0,999))return null;break;case "ddd":case "dddd":f=F(e,p,3===w);if(v(f,0,6))return null;
break;case "zzz":n=p.split(/:/);if(2!==n.length)return null;l=parseInt(n[0],10);if(v(l,-12,13))return null;n=parseInt(n[1],10);if(v(n,0,59))return null;l=60*l+(k(p,"-")?-n:n);break;case "z":case "zz":l=u;if(v(l,-12,13))return null;l*=60;break;case "g":case "gg":if(!p||!e.eras)return null;p=s(p.toLowerCase());n=0;for(w=e.eras.length;n<w;n++)if(p===e.eras[n].name.toLowerCase()){a=n;break}if(null===a)return null}}}d=new Date;h=(m=e.convert)?m.fromGregorian(d)[0]:d.getFullYear();null===b?b=h:e.eras&&
(b+=e.eras[a||0].offset);null===j&&(j=0);null===c&&(c=1);if(m){if(d=m.toGregorian(b,j,c),null===d)return null}else if(d.setFullYear(b,j,c),d.getDate()!==c||null!==f&&d.getDay()!==f)return null;q&&12>i&&(i+=12);d.setHours(i,r,t,g);null!==l&&(e=d.getMinutes()-(l+d.getTimezoneOffset()),d.setHours(d.getHours()+parseInt(e/60,10),e%60));return d};z=function(a,b,e){var d=b["-"],b=b["+"],h;switch(e){case "n -":d=" "+d,b=" "+b;case "n-":j(a,d)?h=["-",a.substr(0,a.length-d.length)]:j(a,b)&&(h=["+",a.substr(0,
a.length-b.length)]);break;case "- n":d+=" ",b+=" ";case "-n":k(a,d)?h=["-",a.substr(d.length)]:k(a,b)&&(h=["+",a.substr(b.length)]);break;case "(n)":k(a,"(")&&j(a,")")&&(h=["-",a.substr(1,a.length-2)])}return h||["",a]};g.prototype.findClosestCulture=function(a){return g.findClosestCulture.call(this,a)};g.prototype.format=function(a,b,e){return g.format.call(this,a,b,e)};g.prototype.localize=function(a,b){return g.localize.call(this,a,b)};g.prototype.parseInt=function(a,b,e){return g.parseInt.call(this,
a,b,e)};g.prototype.parseFloat=function(a,b,e){return g.parseFloat.call(this,a,b,e)};g.prototype.culture=function(a){return g.culture.call(this,a)};g.addCultureInfo=function(a,b,e){var d={},h=!1;"string"!==typeof a?(e=a,a=this.culture().name,d=this.cultures[a]):"string"!==typeof b?(e=b,h=null==this.cultures[a],d=this.cultures[a]||this.cultures["default"]):(h=!0,d=this.cultures[b]);this.cultures[a]=t(!0,{},d,e);h&&(this.cultures[a].calendar=this.cultures[a].calendars.standard)};g.findClosestCulture=
function(a){var b;if(!a)return this.findClosestCulture(this.cultureSelector)||this.cultures["default"];"string"===typeof a&&(a=a.split(","));if(l(a)){var e,d=this.cultures,h=a,j,c=h.length,f=[];for(j=0;j<c;j++)a=s(h[j]),a=a.split(";"),e=s(a[0]),1===a.length?a=1:(a=s(a[1]),0===a.indexOf("q=")?(a=a.substr(2),a=parseFloat(a),a=isNaN(a)?0:a):a=1),f.push({lang:e,pri:a});f.sort(function(a,b){return a.pri<b.pri?1:a.pri>b.pri?-1:0});for(j=0;j<c;j++)if(e=f[j].lang,b=d[e])return b;for(j=0;j<c;j++){e=f[j].lang;
do{h=e.lastIndexOf("-");if(-1===h)break;e=e.substr(0,h);if(b=d[e])return b}while(1)}for(j=0;j<c;j++){e=f[j].lang;for(var i in d)if(h=d[i],h.language==e)return h}}else if("object"===typeof a)return a;return b||null};g.format=function(a,b,e){e=this.findClosestCulture(e);a instanceof Date?a=u(a,b,e):"number"===typeof a&&(a=n(a,b,e));return a};g.localize=function(a,b){return this.findClosestCulture(b).messages[a]||this.cultures["default"].messages[a]};g.parseDate=function(a,b,e){var e=this.findClosestCulture(e),
d,h;if(b){if("string"===typeof b&&(b=[b]),b.length){h=0;for(var j=b.length;h<j;h++){var c=b[h];if(c&&(d=C(a,c,e)))break}}}else for(h in b=e.calendar.patterns,b)if(d=C(a,b[h],e))break;return d||null};g.parseInt=function(a,b,e){return m(g.parseFloat(a,b,e))};g.parseFloat=function(a,b,e){"number"!==typeof b&&(e=b,b=10);var h=this.findClosestCulture(e),e=NaN,j=h.numberFormat;-1<a.indexOf(h.numberFormat.currency.symbol)&&(a=a.replace(h.numberFormat.currency.symbol,""),a=a.replace(h.numberFormat.currency["."],
h.numberFormat["."]));a=s(a);if(f.test(a))e=parseFloat(a);else if(!b&&i.test(a))e=parseInt(a,16);else{h=z(a,j,j.pattern[0]);b=h[0];h=h[1];""===b&&"(n)"!==j.pattern[0]&&(h=z(a,j,"(n)"),b=h[0],h=h[1]);""===b&&"-n"!==j.pattern[0]&&(h=z(a,j,"-n"),b=h[0],h=h[1]);var b=b||"+",c,a=h.indexOf("e");0>a&&(a=h.indexOf("E"));0>a?(c=h,a=null):(c=h.substr(0,a),a=h.substr(a+1));var l=j["."],k=c.indexOf(l);0>k?(h=c,c=null):(h=c.substr(0,k),c=c.substr(k+l.length));l=j[","];h=h.split(l).join("");k=l.replace(/\u00A0/g,
" ");l!==k&&(h=h.split(k).join(""));b+=h;null!==c&&(b+="."+c);null!==a&&(j=z(a,j,"-n"),b+="e"+(j[0]||"+")+j[1]);d.test(b)&&(e=parseFloat(b))}return e};g.culture=function(a){"undefined"!==typeof a&&(this.cultureSelector=a);return this.findClosestCulture(a)||this.cultures["default"]}})(this);
"JSON"in window&&window.JSON||(this.JSON||(this.JSON={}),function(){function a(a){return a<10?"0"+a:a}function c(a){f.lastIndex=0;return f.test(a)?'"'+a.replace(f,function(a){var b=e[a];return typeof b==="string"?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function g(a,e){var f,h,i,s,m=d,o,q=e[a];q&&(typeof q==="object"&&typeof q.toJSON==="function")&&(q=q.toJSON(a));typeof j==="function"&&(q=j.call(e,a,q));switch(typeof q){case "string":return c(q);case "number":return isFinite(q)?
String(q):"null";case "boolean":case "null":return String(q);case "object":if(!q)return"null";d=d+b;o=[];if(Object.prototype.toString.apply(q)==="[object Array]"){s=q.length;for(f=0;f<s;f=f+1)o[f]=g(f,q)||"null";i=o.length===0?"[]":d?"[\n"+d+o.join(",\n"+d)+"\n"+m+"]":"["+o.join(",")+"]";d=m;return i}if(j&&typeof j==="object"){s=j.length;for(f=0;f<s;f=f+1){h=j[f];if(typeof h==="string")(i=g(h,q))&&o.push(c(h)+(d?": ":":")+i)}}else for(h in q)if(Object.hasOwnProperty.call(q,h))(i=g(h,q))&&o.push(c(h)+
(d?": ":":")+i);i=o.length===0?"{}":d?"{\n"+d+o.join(",\n"+d)+"\n"+m+"}":"{"+o.join(",")+"}";d=m;return i}}if(typeof Date.prototype.toJSON!=="function"){Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null};String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()}}var i=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
f=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,d,b,e={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},j;if(typeof JSON.stringify!=="function")JSON.stringify=function(a,e,c){var h;b=d="";if(typeof c==="number")for(h=0;h<c;h=h+1)b=b+" ";else typeof c==="string"&&(b=c);if((j=e)&&typeof e!=="function"&&(typeof e!=="object"||typeof e.length!=="number"))throw Error("JSON.stringify");return g("",{"":a})};
if(typeof JSON.parse!=="function")JSON.parse=function(a,b){function e(a,d){var h,j,c=a[d];if(c&&typeof c==="object")for(h in c)if(Object.hasOwnProperty.call(c,h)){j=e(c,h);j!==void 0?c[h]=j:delete c[h]}return b.call(a,d,c)}var d,a=String(a);i.lastIndex=0;i.test(a)&&(a=a.replace(i,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){d=eval("("+a+")");return typeof b==="function"?e({"":d},""):d}throw new SyntaxError("JSON.parse");}}());
(function(a){a.factory=function(c,g){if(a.fn[c])throw"$.fn."+c+" plugin already exists";if(a[c])throw"$."+c+" class already exists";a.fn[c]=function(i){return this.each(function(){var f=a(this),d=f.data("$."+c);d&&d._destroy();d=new a[c](f,i);f.data("$."+c,d)})};a[c]=function(i,f){this.options=a.extend(true,{},a[c].defaults,f);this.element=i;this.init()};a.extend(a[c].prototype,{init:function(){},_destroy:function(){}},g);return a[c]}})(jQuery);
(function(){var a={};$.extend({localstore:function(c,g,i,f){var d=document.location.hostname,b=document.location.protocol;if(typeof g!=="undefined"){var e=JSON.stringify(g);if(!i&&window.globalStorage)g===null?delete window.globalStorage[d][b+c]:window.globalStorage[d][b+c]=e;else if(!i&&window.localStorage&&window.localStorage.setItem)g===null?window.localStorage.removeItem(b+c):window.localStorage.setItem(b+c,e);else if(i!==false){i={};i.domain=fb.get_cookie_domain();g===null?$.cookie(c,null,i):
$.cookie(c,e,$.extend(i,f||{expires:14,path:"/"}))}else g===null?delete a[c]:a[c]=e;return g}if(!i&&window.globalStorage){if(window.globalStorage[d][b+c])g=window.globalStorage[d][b+c].value}else g=!i&&window.localStorage?window.localStorage.getItem(b+c):i!==false?$.cookie(c):a[c];return g!=""&&g!==null&&g!==void 0?JSON.parse(g,null):null}})})();
(function(a){a.extend({metadata:{defaults:{type:"class",name:"metadata",cre:/({.*})/,single:"metadata"},setType:function(a,g){this.defaults.type=a;this.defaults.name=g},get:function(c,g){var i=a.extend({},this.defaults,g);if(!i.single.length)i.single="metadata";var f=a.data(c,i.single);if(f)return f;var f="{}",d=function(a){if(typeof a!="string")return a;return a=eval("("+a+")")};if(i.type=="html5"){var b={};a(c.attributes).each(function(){var a=this.nodeName;if(a.match(/^data-/))a=a.replace(/^data-/,
"");else return true;b[a]=d(this.nodeValue)})}else{if(i.type=="class"){var e=i.cre.exec(c.className);e&&(f=e[1])}else if(i.type=="elem"){if(!c.getElementsByTagName)return;e=c.getElementsByTagName(i.name);e.length&&(f=a.trim(e[0].innerHTML))}else if(c.getAttribute!=void 0)(e=c.getAttribute(i.name))&&(f=e);b=d(f.indexOf("{")<0?"{"+f+"}":f)}a.data(c,i.single,b);return b}}});a.fn.metadata=function(c){return a.metadata.get(this[0],c)}})(jQuery);
(function(a,c){function g(c){return!a(c).parents().andSelf().filter(function(){return a.curCSS(this,"visibility")==="hidden"||a.expr.filters.hidden(this)}).length}a.ui=a.ui||{};if(!a.ui.version){a.extend(a.ui,{version:"1.8.10",keyCode:{ALT:18,BACKSPACE:8,CAPS_LOCK:20,COMMA:188,COMMAND:91,COMMAND_LEFT:91,COMMAND_RIGHT:93,CONTROL:17,DELETE:46,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,INSERT:45,LEFT:37,MENU:93,NUMPAD_ADD:107,NUMPAD_DECIMAL:110,NUMPAD_DIVIDE:111,NUMPAD_ENTER:108,NUMPAD_MULTIPLY:106,NUMPAD_SUBTRACT:109,
PAGE_DOWN:34,PAGE_UP:33,PERIOD:190,RIGHT:39,SHIFT:16,SPACE:32,TAB:9,UP:38,WINDOWS:91}});a.fn.extend({_focus:a.fn.focus,focus:function(c,f){return typeof c==="number"?this.each(function(){var d=this;setTimeout(function(){a(d).focus();f&&f.call(d)},c)}):this._focus.apply(this,arguments)},scrollParent:function(){var c;c=a.browser.msie&&/(static|relative)/.test(this.css("position"))||/absolute/.test(this.css("position"))?this.parents().filter(function(){return/(relative|absolute|fixed)/.test(a.curCSS(this,
"position",1))&&/(auto|scroll)/.test(a.curCSS(this,"overflow",1)+a.curCSS(this,"overflow-y",1)+a.curCSS(this,"overflow-x",1))}).eq(0):this.parents().filter(function(){return/(auto|scroll)/.test(a.curCSS(this,"overflow",1)+a.curCSS(this,"overflow-y",1)+a.curCSS(this,"overflow-x",1))}).eq(0);return/fixed/.test(this.css("position"))||!c.length?a(document):c},zIndex:function(i){if(i!==c)return this.css("zIndex",i);if(this.length)for(var i=a(this[0]),f;i.length&&i[0]!==document;){f=i.css("position");if(f===
"absolute"||f==="relative"||f==="fixed"){f=parseInt(i.css("zIndex"),10);if(!isNaN(f)&&f!==0)return f}i=i.parent()}return 0},disableSelection:function(){return this.bind((a.support.selectstart?"selectstart":"mousedown")+".ui-disableSelection",function(a){a.preventDefault()})},enableSelection:function(){return this.unbind(".ui-disableSelection")}});a.each(["Width","Height"],function(i,f){function d(e,d,c,h){a.each(b,function(){d=d-(parseFloat(a.curCSS(e,"padding"+this,true))||0);c&&(d=d-(parseFloat(a.curCSS(e,
"border"+this+"Width",true))||0));h&&(d=d-(parseFloat(a.curCSS(e,"margin"+this,true))||0))});return d}var b=f==="Width"?["Left","Right"]:["Top","Bottom"],e=f.toLowerCase(),j={innerWidth:a.fn.innerWidth,innerHeight:a.fn.innerHeight,outerWidth:a.fn.outerWidth,outerHeight:a.fn.outerHeight};a.fn["inner"+f]=function(b){return b===c?j["inner"+f].call(this):this.each(function(){a(this).css(e,d(this,b)+"px")})};a.fn["outer"+f]=function(b,c){return typeof b!=="number"?j["outer"+f].call(this,b):this.each(function(){a(this).css(e,
d(this,b,true,c)+"px")})}});a.extend(a.expr[":"],{data:function(c,f,d){return!!a.data(c,d[3])},focusable:function(c){var f=c.nodeName.toLowerCase(),d=a.attr(c,"tabindex");if("area"===f){f=c.parentNode;d=f.name;if(!c.href||!d||f.nodeName.toLowerCase()!=="map")return false;c=a("img[usemap=#"+d+"]")[0];return!!c&&g(c)}return(/input|select|textarea|button|object/.test(f)?!c.disabled:"a"==f?c.href||!isNaN(d):!isNaN(d))&&g(c)},tabbable:function(c){var f=a.attr(c,"tabindex");return(isNaN(f)||f>=0)&&a(c).is(":focusable")}});
a(function(){var c=document.body,f=c.appendChild(f=document.createElement("div"));a.extend(f.style,{minHeight:"100px",height:"auto",padding:0,borderWidth:0});a.support.minHeight=f.offsetHeight===100;a.support.selectstart="onselectstart"in f;c.removeChild(f).style.display="none"});a.extend(a.ui,{plugin:{add:function(c,f,d){var c=a.ui[c].prototype,b;for(b in d){c.plugins[b]=c.plugins[b]||[];c.plugins[b].push([f,d[b]])}},call:function(a,c,d){if((c=a.plugins[c])&&a.element[0].parentNode)for(var b=0;b<
c.length;b++)a.options[c[b][0]]&&c[b][1].apply(a.element,d)}},contains:function(a,c){return document.compareDocumentPosition?a.compareDocumentPosition(c)&16:a!==c&&a.contains(c)},hasScroll:function(c,f){if(a(c).css("overflow")==="hidden")return false;var d=f&&f==="left"?"scrollLeft":"scrollTop",b=false;if(c[d]>0)return true;c[d]=1;b=c[d]>0;c[d]=0;return b},isOverAxis:function(a,c,d){return a>c&&a<c+d},isOver:function(c,f,d,b,e,j){return a.ui.isOverAxis(c,d,e)&&a.ui.isOverAxis(f,b,j)}})}})(jQuery);
(function(a,c){if(a.cleanData){var g=a.cleanData;a.cleanData=function(c){for(var d=0,b;(b=c[d])!=null;d++)a(b).triggerHandler("remove");g(c)}}else{var i=a.fn.remove;a.fn.remove=function(c,d){return this.each(function(){d||(!c||a.filter(c,[this]).length)&&a("*",this).add([this]).each(function(){a(this).triggerHandler("remove")});return i.call(a(this),c,d)})}}a.widget=function(c,d,b){var e=c.split(".")[0],j,c=c.split(".")[1];j=e+"-"+c;if(!b){b=d;d=a.Widget}a.expr[":"][j]=function(b){return!!a.data(b,
c)};a[e]=a[e]||{};a[e][c]=function(a,b){arguments.length&&this._createWidget(a,b)};d=new d;d.options=a.extend(true,{},d.options);a[e][c].prototype=a.extend(true,d,{namespace:e,widgetName:c,widgetEventPrefix:a[e][c].prototype.widgetEventPrefix||c,widgetBaseClass:j},b);a.widget.bridge(c,a[e][c])};a.widget.bridge=function(f,d){a.fn[f]=function(b){var e=typeof b==="string",j=Array.prototype.slice.call(arguments,1),i=this,b=!e&&j.length?a.extend.apply(null,[true,b].concat(j)):b;if(e&&b.charAt(0)==="_")return i;
e?this.each(function(){var e=a.data(this,f),d=e&&a.isFunction(e[b])?e[b].apply(e,j):e;if(d!==e&&d!==c){i=d;return false}}):this.each(function(){var e=a.data(this,f);e?e.option(b||{})._init():a.data(this,f,new d(b,this))});return i}};a.Widget=function(a,d){arguments.length&&this._createWidget(a,d)};a.Widget.prototype={widgetName:"widget",widgetEventPrefix:"",options:{disabled:false},_createWidget:function(c,d){a.data(d,this.widgetName,this);this.element=a(d);this.options=a.extend(true,{},this.options,
this._getCreateOptions(),c);var b=this;this.element.bind("remove."+this.widgetName,function(){b.destroy()});this._create();this._trigger("create");this._init()},_getCreateOptions:function(){return a.metadata&&a.metadata.get(this.element[0])[this.widgetName]},_create:function(){},_init:function(){},destroy:function(){this.element.unbind("."+this.widgetName).removeData(this.widgetName);this.widget().unbind("."+this.widgetName).removeAttr("aria-disabled").removeClass(this.widgetBaseClass+"-disabled ui-state-disabled")},
widget:function(){return this.element},option:function(f,d){var b=f;if(arguments.length===0)return a.extend({},this.options);if(typeof f==="string"){if(d===c)return this.options[f];b={};b[f]=d}this._setOptions(b);return this},_setOptions:function(c){var d=this;a.each(c,function(a,e){d._setOption(a,e)});return this},_setOption:function(a,d){this.options[a]=d;a==="disabled"&&this.widget()[d?"addClass":"removeClass"](this.widgetBaseClass+"-disabled ui-state-disabled").attr("aria-disabled",d);return this},
enable:function(){return this._setOption("disabled",false)},disable:function(){return this._setOption("disabled",true)},_trigger:function(c,d,b){var e=this.options[c],d=a.Event(d);d.type=(c===this.widgetEventPrefix?c:this.widgetEventPrefix+c).toLowerCase();b=b||{};if(d.originalEvent)for(var c=a.event.props.length,j;c;){j=a.event.props[--c];d[j]=d.originalEvent[j]}this.element.trigger(d,b);return!(a.isFunction(e)&&e.call(this.element[0],d,b)===false||d.isDefaultPrevented())}}})(jQuery);
(function(a){a.widget("ui.mouse",{options:{cancel:":input,option",distance:1,delay:0},_mouseInit:function(){var c=this;this.element.bind("mousedown."+this.widgetName,function(a){return c._mouseDown(a)}).bind("click."+this.widgetName,function(g){if(true===a.data(g.target,c.widgetName+".preventClickEvent")){a.removeData(g.target,c.widgetName+".preventClickEvent");g.stopImmediatePropagation();return false}});this.started=false},_mouseDestroy:function(){this.element.unbind("."+this.widgetName)},_mouseDown:function(c){c.originalEvent=
c.originalEvent||{};if(!c.originalEvent.mouseHandled){this._mouseStarted&&this._mouseUp(c);this._mouseDownEvent=c;var g=this,i=c.which==1,f=typeof this.options.cancel=="string"?a(c.target).parents().add(c.target).filter(this.options.cancel).length:false;if(!i||f||!this._mouseCapture(c))return true;this.mouseDelayMet=!this.options.delay;if(!this.mouseDelayMet)this._mouseDelayTimer=setTimeout(function(){g.mouseDelayMet=true},this.options.delay);if(this._mouseDistanceMet(c)&&this._mouseDelayMet(c)){this._mouseStarted=
this._mouseStart(c)!==false;if(!this._mouseStarted){c.preventDefault();return true}}this._mouseMoveDelegate=function(a){return g._mouseMove(a)};this._mouseUpDelegate=function(a){return g._mouseUp(a)};a(document).bind("mousemove."+this.widgetName,this._mouseMoveDelegate).bind("mouseup."+this.widgetName,this._mouseUpDelegate);c.preventDefault();return c.originalEvent.mouseHandled=true}},_mouseMove:function(c){if(a.browser.msie&&!(document.documentMode>=9)&&!c.button)return this._mouseUp(c);if(this._mouseStarted){this._mouseDrag(c);
return c.preventDefault()}if(this._mouseDistanceMet(c)&&this._mouseDelayMet(c))(this._mouseStarted=this._mouseStart(this._mouseDownEvent,c)!==false)?this._mouseDrag(c):this._mouseUp(c);return!this._mouseStarted},_mouseUp:function(c){a(document).unbind("mousemove."+this.widgetName,this._mouseMoveDelegate).unbind("mouseup."+this.widgetName,this._mouseUpDelegate);if(this._mouseStarted){this._mouseStarted=false;c.target==this._mouseDownEvent.target&&a.data(c.target,this.widgetName+".preventClickEvent",
true);this._mouseStop(c)}return false},_mouseDistanceMet:function(a){return Math.max(Math.abs(this._mouseDownEvent.pageX-a.pageX),Math.abs(this._mouseDownEvent.pageY-a.pageY))>=this.options.distance},_mouseDelayMet:function(){return this.mouseDelayMet},_mouseStart:function(){},_mouseDrag:function(){},_mouseStop:function(){},_mouseCapture:function(){return true}})})(jQuery);
(function(a){a.ui=a.ui||{};var c=/left|center|right/,g=/top|center|bottom/,i=a.fn.position,f=a.fn.offset;a.fn.position=function(d){if(!d||!d.of)return i.apply(this,arguments);var d=a.extend({},d),b=a(d.of),e=b[0],j=(d.collision||"flip").split(" "),f=d.offset?d.offset.split(" "):[0,0],l,r,h;if(e.nodeType===9){l=b.width();r=b.height();h={top:0,left:0}}else if(e.setTimeout){l=b.width();r=b.height();h={top:b.scrollTop(),left:b.scrollLeft()}}else if(e.preventDefault){d.at="left top";l=r=0;h={top:d.of.pageY,
left:d.of.pageX}}else{l=b.outerWidth();r=b.outerHeight();h=b.offset()}a.each(["my","at"],function(){var a=(d[this]||"").split(" ");a.length===1&&(a=c.test(a[0])?a.concat(["center"]):g.test(a[0])?["center"].concat(a):["center","center"]);a[0]=c.test(a[0])?a[0]:"center";a[1]=g.test(a[1])?a[1]:"center";d[this]=a});j.length===1&&(j[1]=j[0]);f[0]=parseInt(f[0],10)||0;f.length===1&&(f[1]=f[0]);f[1]=parseInt(f[1],10)||0;if(d.at[0]==="right")h.left=h.left+l;else if(d.at[0]==="center")h.left=h.left+l/2;if(d.at[1]===
"bottom")h.top=h.top+r;else if(d.at[1]==="center")h.top=h.top+r/2;h.left=h.left+f[0];h.top=h.top+f[1];return this.each(function(){var b=a(this),e=b.outerWidth(),c=b.outerHeight(),i=parseInt(a.curCSS(this,"marginLeft",true))||0,g=parseInt(a.curCSS(this,"marginTop",true))||0,p=e+i+(parseInt(a.curCSS(this,"marginRight",true))||0),u=c+g+(parseInt(a.curCSS(this,"marginBottom",true))||0),n=a.extend({},h),w;if(d.my[0]==="right")n.left=n.left-e;else if(d.my[0]==="center")n.left=n.left-e/2;if(d.my[1]==="bottom")n.top=
n.top-c;else if(d.my[1]==="center")n.top=n.top-c/2;n.left=Math.round(n.left);n.top=Math.round(n.top);w={left:n.left-i,top:n.top-g};a.each(["left","top"],function(b,h){if(a.ui.position[j[b]])a.ui.position[j[b]][h](n,{targetWidth:l,targetHeight:r,elemWidth:e,elemHeight:c,collisionPosition:w,collisionWidth:p,collisionHeight:u,offset:f,my:d.my,at:d.at})});a.fn.bgiframe&&b.bgiframe();b.offset(a.extend(n,{using:d.using}))})};a.ui.position={fit:{left:function(d,b){var e=a(window),e=b.collisionPosition.left+
b.collisionWidth-e.width()-e.scrollLeft();d.left=e>0?d.left-e:Math.max(d.left-b.collisionPosition.left,d.left)},top:function(d,b){var e=a(window),e=b.collisionPosition.top+b.collisionHeight-e.height()-e.scrollTop();d.top=e>0?d.top-e:Math.max(d.top-b.collisionPosition.top,d.top)}},flip:{left:function(d,b){if(b.at[0]!=="center"){var e=a(window),e=b.collisionPosition.left+b.collisionWidth-e.width()-e.scrollLeft(),c=b.my[0]==="left"?-b.elemWidth:b.my[0]==="right"?b.elemWidth:0,f=b.at[0]==="left"?b.targetWidth:
-b.targetWidth,i=-2*b.offset[0];d.left=d.left+(b.collisionPosition.left<0?c+f+i:e>0?c+f+i:0)}},top:function(d,b){if(b.at[1]!=="center"){var e=a(window),e=b.collisionPosition.top+b.collisionHeight-e.height()-e.scrollTop(),c=b.my[1]==="top"?-b.elemHeight:b.my[1]==="bottom"?b.elemHeight:0,f=b.at[1]==="top"?b.targetHeight:-b.targetHeight,i=-2*b.offset[1];d.top=d.top+(b.collisionPosition.top<0?c+f+i:e>0?c+f+i:0)}}}};if(!a.offset.setOffset){a.offset.setOffset=function(d,b){if(/static/.test(a.curCSS(d,"position")))d.style.position=
"relative";var e=a(d),c=e.offset(),f=parseInt(a.curCSS(d,"top",true),10)||0,i=parseInt(a.curCSS(d,"left",true),10)||0,c={top:b.top-c.top+f,left:b.left-c.left+i};"using"in b?b.using.call(d,c):e.css(c)};a.fn.offset=function(c){var b=this[0];return!b||!b.ownerDocument?null:c?this.each(function(){a.offset.setOffset(this,c)}):f.call(this)}}})(jQuery);
(function(a,c){if(!("console"in window)){var g=window.console={};g.log=g.warn=g.error=g.debug=function(){}}a(function(){var b=a("<div>");a(document.body).append(b);var e=setTimeout(function(){if(a.cleanData){var b=a.cleanData;a.cleanData=function(e){for(var c=0,d;(d=e[c])!=null;c++)a(d).triggerHandler("remove");b(e)}}else{var e=a.fn.remove;a.fn.remove=function(b,c){return this.each(function(){c||(!b||a.filter(b,[this]).length)&&a("*",this).add([this]).each(function(){a(this).triggerHandler("remove")});
return e.call(a(this),b,c)})}}},1);b.bind("remove",function(){clearTimeout(e)});b.remove()});var i={key:1,filter:1,spell:1,exact:1,lang:1,scoring:1,prefixed:1,stemmed:1,format:1,mql_output:1,output:1};a.suggest=function(b,e){a.fn[b]=function(e){this.length||console.warn("Suggest: invoked on empty element set");return this.each(function(){this.nodeName&&(this.nodeName.toUpperCase()==="INPUT"?this.type&&this.type.toUpperCase()!=="TEXT"&&console.warn("Suggest: unsupported INPUT type: "+this.type):console.warn("Suggest: unsupported DOM element: "+
this.nodeName));var c=a.data(this,b);c&&c._destroy();a.data(this,b,new a.suggest[b](this,e))._init()})};a.suggest[b]=function(e,c){var d=this,f=this.options=a.extend(true,{},a.suggest.defaults,a.suggest[b].defaults,c),h=f.css_prefix=f.css_prefix||"",k=f.css;this.name=b;a.each(k,function(a){k[a]=h+k[a]});f.ac_param={};a.each(i,function(a){var b=f[a];b===null||b===""||(f.ac_param[a]=b)});f.flyout_lang=null;if(f.ac_param.lang){var g=f.ac_param.lang;a.type(g)==="string"&&(g=g.split(","));if(a.isArray(g)&&
g.length)if(g=a.trim(g[0]))f.flyout_lang=g}this._status={START:"",LOADING:"",SELECT:"",ERROR:""};if(f.status&&f.status instanceof Array&&f.status.length>=3){this._status.START=f.status[0]||"";this._status.LOADING=f.status[1]||"";this._status.SELECT=f.status[2]||"";if(f.status.length===4)this._status.ERROR=f.status[3]||""}var g=this.status=a('<div style="display:none;">').addClass(k.status),m=this.list=a("<ul>").addClass(k.list),o=this.pane=a('<div style="display:none;" class="fbs-reset">').addClass(k.pane);
o.append(g).append(m);if(f.parent)a(f.parent).append(o);else{o.css("position","absolute");f.zIndex&&o.css("z-index",f.zIndex);a(document.body).append(o)}o.bind("mousedown",function(a){d.input.data("dont_hide",true);a.stopPropagation()}).bind("mouseup",function(a){d.input.data("dont_hide")&&d.input.focus();d.input.removeData("dont_hide");a.stopPropagation()}).bind("click",function(a){a.stopPropagation();if(a=d.get_selected()){d.onselect(a,true);d.hide_all()}});m.hover(function(a){d.hoverover_list(a)},
function(a){d.hoverout_list(a)});this.input=a(e).attr("autocomplete","off").unbind(".suggest").bind("remove.suggest",function(){d._destroy()}).bind("keydown.suggest",function(a){d.keydown(a)}).bind("keypress.suggest",function(a){d.keypress(a)}).bind("keyup.suggest",function(a){d.keyup(a)}).bind("blur.suggest",function(a){d.blur(a)}).bind("textchange.suggest",function(){d.textchange()}).bind("focus.suggest",function(a){d.focus(a)}).bind(a.browser.msie?"paste.suggest":"input.suggest",function(){clearTimeout(d.paste_timeout);
d.paste_timeout=setTimeout(function(){d.textchange()},0)});this.onresize=function(){d.invalidate_position();if(o.is(":visible")){d.position();if(f.flyout&&d.flyoutpane&&d.flyoutpane.is(":visible")){var a=d.get_selected();a&&d.flyout_position(a)}}};a(window).bind("resize.suggest",this.onresize).bind("scroll.suggest",this.onresize)};a.suggest[b].prototype=a.extend({},a.suggest.prototype,e)};a.suggest.prototype={_init:function(){},_destroy:function(){this.pane.remove();this.list.remove();this.input.unbind(".suggest");
a(window).unbind("resize.suggest",this.onresize).unbind("scroll.suggest",this.onresize);this.input.removeData("data.suggest")},invalidate_position:function(){self._position=null},status_start:function(){this.hide_all();this.status.siblings().hide();if(this._status.START){this.status.text(this._status.START).show();if(!this.pane.is(":visible")){this.position();this.pane_show()}}this._status.LOADING&&this.status.removeClass("loading")},status_loading:function(){this.status.siblings().show();if(this._status.LOADING){this.status.addClass("loading").text(this._status.LOADING).show();
if(!this.pane.is(":visible")){this.position();this.pane_show()}}else this.status.hide()},status_select:function(){this.status.siblings().show();this._status.SELECT?this.status.text(this._status.SELECT).show():this.status.hide();this._status.LOADING&&this.status.removeClass("loading")},status_error:function(){this.status.siblings().show();this._status.ERROR?this.status.text(this._status.ERROR).show():this.status.hide();this._status.LOADING&&this.status.removeClass("loading")},focus:function(a){this.input.val()===
""?this.status_start():this.focus_hook(a)},focus_hook:function(){if(!this.input.data("data.suggest")&&!this.pane.is(":visible")&&a("."+this.options.css.item,this.list).length){this.position();this.pane_show()}},keydown:function(a){var e=a.keyCode;if(e===9)this.tab(a);else if(e===38||e===40)a.shiftKey||a.preventDefault()},keypress:function(a){var e=a.keyCode;e===38||e===40?a.shiftKey||a.preventDefault():e===13&&this.enter(a)},keyup:function(b){var e=b.keyCode;if(e===38){b.preventDefault();this.up(b)}else if(e===
40){b.preventDefault();this.down(b)}else if(b.ctrlKey&&e===77)a(".fbs-more-link",this.pane).click();else if(a.suggest.is_char(b)){clearTimeout(this.keypress.timeout);var d=this;this.keypress.timeout=setTimeout(function(){d.textchange()},0)}else e===27&&this.escape(b);return true},blur:function(){if(!this.input.data("dont_hide")){this.input.data("data.suggest");this.hide_all()}},tab:function(b){if(!b.shiftKey&&!b.metaKey&&!b.ctrlKey){var b=this.options,b=this.pane.is(":visible")&&a("."+b.css.item,
this.list).length,e=this.get_selected();if(b&&e){this.onselect(e);this.hide_all()}}},enter:function(b){var e=this.options;if(this.pane.is(":visible"))if(b.shiftKey){this.shift_enter(b);b.preventDefault()}else if(a("."+e.css.item,this.list).length)if(e=this.get_selected()){this.onselect(e);this.hide_all();b.preventDefault()}else{this.input.data("data.suggest");if(a("."+this.options.css.item+":visible",this.list).length){this.updown(false);b.preventDefault()}}},shift_enter:function(){},escape:function(){this.hide_all()},
up:function(a){this.updown(true,a.ctrlKey||a.shiftKey)},down:function(a){this.updown(false,null,a.ctrlKey||a.shiftKey)},updown:function(b,e,d){var c=this.options.css,f=this.list;if(this.pane.is(":visible")){var i=a("."+c.item+":visible",f);if(i.length){var f=a(i[0]),i=a(i[i.length-1]),h=this.get_selected()||[];clearTimeout(this.ignore_mouseover.timeout);this._ignore_mouseover=false;if(b)if(e)this._goto(f);else if(h.length)if(h[0]==f[0]){f.removeClass(c.selected);this.input.val(this.input.data("original.suggest"));
this.hoverout_list()}else{b=h.prevAll("."+c.item+":visible:first");this._goto(b)}else this._goto(i);else if(d)this._goto(i);else if(h.length)if(h[0]==i[0]){i.removeClass(c.selected);this.input.val(this.input.data("original.suggest"));this.hoverout_list()}else{b=h.nextAll("."+c.item+":visible:first");this._goto(b)}else this._goto(f)}}else b||this.textchange()},_goto:function(a){a.trigger("mouseover.suggest");var e=a.data("data.suggest");this.input.val(e?e.name:this.input.data("original.suggest"));
this.scroll_to(a)},scroll_to:function(a){var e=this.list,d=e.scrollTop(),c=d+e.innerHeight(),f=a.outerHeight(),a=a.prevAll().length*f,f=a+f;if(a<d){this.ignore_mouseover();e.scrollTop(a)}else if(f>c){this.ignore_mouseover();e.scrollTop(d+f-c)}},textchange:function(){this.input.removeData("data.suggest");this.input.trigger("fb-textchange",this);var a=this.input.val();if(a==="")this.status_start();else{this.status_loading();this.request(a)}},request:function(){},response:function(b){if(b){"cost"in b&&
this.trackEvent(this.name,"response","cost",b.cost);if(this.check_response(b)){var e=[];if(a.isArray(b))e=b;else if("result"in b)e=b.result;var d=a.map(arguments,function(a){return a});this.response_hook.apply(this,d);var c=null,f=this,i=this.options;a.each(e,function(a,e){if(!e.id&&e.mid)e.id=e.mid;var d=f.create_item(e,b).bind("mouseover.suggest",function(a){f.mouseover_item(a)});d.data("data.suggest",e);f.list.append(d);a===0&&(c=d)});this.input.data("original.suggest",this.input.val());if(a("."+
i.css.item,this.list).length===0&&i.nomatch){e=a('<li class="fbs-nomatch">');if(typeof i.nomatch==="string")e.text(i.nomatch);else{i.nomatch.title&&e.append(a('<em class="fbs-nomatch-text">').text(i.nomatch.title));i.nomatch.heading&&e.append(a("<h3>").text(i.nomatch.heading));if((i=i.nomatch.tips)&&i.length){var h=a('<ul class="fbs-search-tips">');a.each(i,function(b,e){h.append(a("<li>").text(e))});e.append(h)}}e.bind("click.suggest",function(a){a.stopPropagation()});this.list.append(e)}d.push(c);
this.show_hook.apply(this,d);this.position();this.pane_show()}}},pane_show:function(){var b=false;a("> li",this.list).length&&(b=true);b||this.pane.children(":not(."+this.options.css.list+")").each(function(){if(a(this).css("display")!="none"){b=true;return false}});if(b)if(this.options.animate){var e=this;this.pane.slideDown("fast",function(){e.input.trigger("fb-pane-show",e)})}else{this.pane.show();this.input.trigger("fb-pane-show",this)}else{this.pane.hide();this.input.trigger("fb-pane-hide",this)}},
create_item:function(b){var e=this.options.css,d=a("<li>").addClass(e.item),b=a("<label>").text(b.name);d.append(a("<div>").addClass(e.item_name).append(b));return d},mouseover_item:function(b){if(!this._ignore_mouseover){b=b.target;b.nodeName.toLowerCase()!=="li"&&(b=a(b).parents("li:first"));var e=a(b),d=this.options.css;a("."+d.item,this.list).each(function(){this!==e[0]&&a(this).removeClass(d.selected)});if(!e.hasClass(d.selected)){e.addClass(d.selected);this.mouseover_item_hook(e)}}},mouseover_item_hook:function(){},
hoverover_list:function(){},hoverout_list:function(){},check_response:function(){return true},response_hook:function(){this.list.empty()},show_hook:function(){this.status_select()},position:function(){var b=this.pane,e=this.options;if(!e.parent){if(!self._position){var d=this.input,c=d.offset(),f=d.outerWidth(true),i=d.outerHeight(true);c.top=c.top+i;var h=b.outerWidth(),k=b.outerHeight(),g=c.top+k/2,m=a(window).scrollLeft(),d=a(window).scrollTop(),o=a(window).width(),q=a(window).height()+d,p=true;
"left"==e.align?p=true:"right"==e.align?p=false:c.left>m+o/2&&(p=false);if(!p){p=c.left-(h-f);if(p>m)c.left=p}if(g>q){e=c.top-i-k;if(e>d)c.top=e}this._position=c}b.css({top:this._position.top,left:this._position.left})}},ignore_mouseover:function(){this._ignore_mouseover=true;var a=this;this.ignore_mouseover.timeout=setTimeout(function(){a.ignore_mouseover_reset()},1E3)},ignore_mouseover_reset:function(){this._ignore_mouseover=false},get_selected:function(){var b=null,e=this.options.css.selected;
a("li",this.list).each(function(){var d=a(this);if(d.hasClass(e)&&d.is(":visible")){b=d;return false}});return b},onselect:function(a){var e=a.data("data.suggest");if(e){this.input.val(e.name).data("data.suggest",e).trigger("fb-select",e);this.trackEvent(this.name,"fb-select","index",a.prevAll().length)}},trackEvent:function(a,e,d,c){this.input.trigger("fb-track-event",{category:a,action:e,label:d,value:c})},hide_all:function(){this.pane.hide();this.input.trigger("fb-pane-hide",this)}};a.extend(a.suggest,
{defaults:{status:["Start typing to get suggestions...","Searching...","Select an item from the list:","Sorry, something went wrong. Please try again later"],soft:false,nomatch:"no matches",css:{pane:"fbs-pane",list:"fbs-list",item:"fbs-item",item_name:"fbs-item-name",selected:"fbs-selected",status:"fbs-status"},css_prefix:null,parent:null,animate:false,zIndex:null},strongify:function(b,e){var d,c=b.toLowerCase().indexOf(e.toLowerCase());if(c>=0){var f=e.length;d=document.createTextNode(b.substring(0,
c));var i=a("<strong>").text(b.substring(c,c+f)),c=document.createTextNode(b.substring(c+f));d=a("<div>").append(d).append(i).append(c)}else d=a("<div>").text(b);return d},keyCode:{CAPS_LOCK:20,CONTROL:17,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,INSERT:45,LEFT:37,NUMPAD_ENTER:108,PAGE_DOWN:34,PAGE_UP:33,RIGHT:39,SHIFT:16,SPACE:32,TAB:9,UP:38,OPTION:18,APPLE:224},is_char:function(b){if(b.type==="keypress"){if((b.metaKey||b.ctrlKey)&&b.charCode===118)return true;if("isChar"in b)return b.isChar}else{var e=
a.suggest.keyCode.not_char;if(!e){e={};a.each(a.suggest.keyCode,function(a,b){e[""+b]=1});a.suggest.keyCode.not_char=e}return!(""+b.keyCode in e)}},parse_input:function(b){for(var e=/(\S+)\:(?:\"([^\"]+)\"|(\S+))/g,d=b,c=[],f={},g=e.exec(b);g;){g[1]in i?f[g[1]]=a.isEmptyObject(g[2])?g[3]:g[2]:c.push(g[0]);d=d.replace(g[0],"");g=e.exec(b)}d=a.trim(d.replace(/\s+/g," "));return[d,c,f]},mqlkey_fast:/^[_A-Za-z0-9][A-Za-z0-9_-]*$/,mqlkey_slow:/^(?:[A-Za-z0-9]|\$[A-F0-9]{4})(?:[A-Za-z0-9_-]|\$[A-F0-9]{4})*$/,
check_mql_key:function(b){return a.suggest.mqlkey_fast.test(b)||a.suggest.mqlkey_slow.test(b)?true:false},check_mql_id:function(b){if(b.indexOf("/")===0){b=b.split("/");b.shift();if(!(b.length==1&&b[0]===""))for(var e=0,d=b.length;e<d;e++)if(!a.suggest.check_mql_key(b[e]))return false;return true}return false}});var f=a.suggest.prototype._destroy,d=a.suggest.prototype.show_hook;a.suggest("suggest",{_init:function(){var b=this,e=this.options;if(e.flyout_service_url==null)e.flyout_service_url=e.service_url;
this.flyout_url=e.flyout_service_url;if(e.flyout_service_path)this.flyout_url=this.flyout_url+e.flyout_service_path;this.flyout_url=this.flyout_url.replace(/\$\{key\}/g,e.key);if(e.flyout_image_service_url==null)e.flyout_image_service_url=e.service_url;this.flyout_image_url=e.flyout_image_service_url;if(e.flyout_image_service_path)this.flyout_image_url=this.flyout_image_url+e.flyout_image_service_path;this.flyout_image_url=this.flyout_image_url.replace(/\$\{key\}/g,e.key);if(!a.suggest.cache)a.suggest.cache=
{};if(e.flyout){this.flyoutpane=a('<div style="display:none;" class="fbs-reset">').addClass(e.css.flyoutpane);if(e.flyout_parent)a(e.flyout_parent).append(this.flyoutpane);else{this.flyoutpane.css("position","absolute");e.zIndex&&this.flyoutpane.css("z-index",e.zIndex);a(document.body).append(this.flyoutpane)}this.flyoutpane.hover(function(a){b.hoverover_list(a)},function(a){b.hoverout_list(a)}).bind("mousedown.suggest",function(a){a.stopPropagation();b.pane.click()});if(!a.suggest.flyout)a.suggest.flyout=
{};if(!a.suggest.flyout.cache)a.suggest.flyout.cache={}}},_destroy:function(){f.call(this);this.flyoutpane&&this.flyoutpane.remove();this.input.removeData("request.count.suggest");this.input.removeData("flyout.request.count.suggest")},shift_enter:function(){if(this.options.suggest_new){this.suggest_new();this.hide_all()}},hide_all:function(){this.pane.hide();this.flyoutpane&&this.flyoutpane.hide();this.input.trigger("fb-pane-hide",this);this.input.trigger("fb-flyoutpane-hide",this)},request:function(b,
e){var d=this,c=this.options,f=b,i=c.ac_param.filter||[],h=null;a.type(i)==="string"&&(i=[i]);i=i.slice();if(c.advanced){var g=a.suggest.parse_input(f),f=g[0];g[1].length&&i.push("(all "+g[1].join(" ")+")");h=g[2];if(a.suggest.check_mql_id(f)){i.push('(all mid:"'+f+'")');f=""}}g={};g[c.query_param_name]=f;if(e)g.cursor=e;a.extend(g,c.ac_param,h);if(i.length)g.filter=i;var s=c.service_url+c.service_path+"?"+a.param(g,true);if(f=a.suggest.cache[s])this.response(f,e?e:-1,true);else{clearTimeout(this.request.timeout);
var m={url:c.service_url+c.service_path,data:g,traditional:true,beforeSend:function(){var a=d.input.data("request.count.suggest")||0;a||d.trackEvent(d.name,"start_session");a=a+1;d.trackEvent(d.name,"request","count",a);d.input.data("request.count.suggest",a)},success:function(c){a.suggest.cache[s]=c;c.prefix=b;d.response(c,e?e:-1)},error:function(a){d.status_error();d.trackEvent(d.name,"request","error",{url:this.url,response:a?a.responseText:""});d.input.trigger("fb-error",Array.prototype.slice.call(arguments))},
complete:function(a){a&&d.trackEvent(d.name,"request","tid",a.getResponseHeader("X-Metaweb-TID"))},dataType:"jsonp",cache:true};this.request.timeout=setTimeout(function(){a.ajax(m)},c.xhr_delay)}},create_item:function(b,e){var d=this.options.css,c=a("<li>").addClass(d.item),f=a("<label>").append(a.suggest.strongify(b.name||b.id,e.prefix)),i=a("<div>").addClass(d.item_name).append(f);b.under&&a(":first",f).append(a("<small>").text(" ("+b.under+")"));this.options.scoring!=null&&this.options.scoring.toUpperCase()===
"SCHEMA"&&a(":first",f).append(a("<small>").text(" ("+b.id+")"));c.append(i);f=b.notable;d=a("<div>").addClass(d.item_type);f&&f.name?d.text(f.name):this.options.show_id&&b.id&&d.text(b.id);i.prepend(d);return c},mouseover_item_hook:function(a){a=a.data("data.suggest");this.options.flyout&&a&&this.flyout_request(a)},check_response:function(a){return a.prefix===this.input.val()},response_hook:function(b,e){this.flyoutpane&&this.flyoutpane.hide();e>0?a(".fbs-more",this.pane).remove():this.list.empty()},
show_hook:function(b,e,c){d.apply(this,[b]);var f=this.options,i=this,g=this.pane,h=this.list,k=b.result,s=a(".fbs-more",g),m=a(".fbs-suggestnew",g);a(".fbs-status",g);var o=b.correction;if(o&&o.length){var q=a('<a class="fbs-spell-link" href="#">').append(o[0]).bind("click.suggest",function(a){a.preventDefault();a.stopPropagation();i.input.val(o[0]).trigger("textchange")});i.status.empty().append("Search instead for ").append(q).show()}if(k&&k.length&&"cursor"in b){if(!s.length){k=a('<a class="fbs-more-link" href="#" title="(Ctrl+m)">view more</a>');
s=a('<div class="fbs-more">').append(k);k.bind("click.suggest",function(b){b.preventDefault();b.stopPropagation();b=a(this).parent(".fbs-more");i.more(b.data("cursor.suggest"))});h.after(s)}s.data("cursor.suggest",b.cursor);s.show()}else s.remove();if(f.suggest_new){if(!m.length){b=a('<button class="fbs-suggestnew-button">');b.text(f.suggest_new);m=a('<div class="fbs-suggestnew">').append('<div class="fbs-suggestnew-description">Your item not in the list?</div>').append(b).append('<span class="fbs-suggestnew-shortcut">(Shift+Enter)</span>').bind("click.suggest",
function(a){a.stopPropagation();i.suggest_new(a)});g.append(m)}m.show()}else m.remove();if(c&&c.length&&e>0){e=c.prevAll().length*c.outerHeight();h.scrollTop();h.animate({scrollTop:e},"slow",function(){c.trigger("mouseover.suggest")})}},suggest_new:function(){var a=this.input.val();if(a!==""){this.input.data("data.suggest",a).trigger("fb-select-new",a);this.trackEvent(this.name,"fb-select-new","index","new");this.hide_all()}},more:function(a){if(a){var e=this.input.data("original.suggest");e!==null&&
this.input.val(e);this.request(this.input.val(),a);this.trackEvent(this.name,"more","cursor",a)}return false},flyout_request:function(b){var e=this,d=this.options,c=this.flyoutpane.data("data.suggest");if(c&&b.id===c.id){if(!this.flyoutpane.is(":visible")){b=this.get_selected();this.flyout_position(b);this.flyoutpane.show();this.input.trigger("fb-flyoutpane-show",this)}}else if((c=a.suggest.flyout.cache[b.id])&&c.id&&c.html)this.flyout_response(c);else{var f=b.id,i={url:this.flyout_url.replace(/\$\{id\}/g,
b.id),traditional:true,beforeSend:function(){var a=e.input.data("flyout.request.count.suggest")||0,a=a+1;e.trackEvent(e.name,"flyout.request","count",a);e.input.data("flyout.request.count.suggest",a)},success:function(b){b["req:id"]=f;b.html=a.suggest.suggest.create_flyout(b,e.flyout_image_url);a.suggest.flyout.cache[f]=b;e.flyout_response(b)},error:function(a){e.trackEvent(e.name,"flyout","error",{url:this.url,response:a?a.responseText:""})},complete:function(a){a&&e.trackEvent(e.name,"flyout","tid",
a.getResponseHeader("X-Metaweb-TID"))},dataType:"jsonp",cache:true};if(d.flyout_lang)i.data={lang:d.flyout_lang};clearTimeout(this.flyout_request.timeout);this.flyout_request.timeout=setTimeout(function(){a.ajax(i)},d.xhr_delay);this.input.trigger("fb-request-flyout",i)}},flyout_response:function(a){var d=this.pane,c=this.get_selected()||[];if(d.is(":visible")&&c.length)if((d=c.data("data.suggest"))&&a["req:id"]===d.id&&a.html){this.flyoutpane.html(a.html);this.flyout_position(c);this.flyoutpane.show().data("data.suggest",
d);this.input.trigger("fb-flyoutpane-show",this)}},flyout_position:function(b){if(!this.options.flyout_parent){var d=this.pane,f=this.flyoutpane,i=this.options.css,g=c,r=parseInt(f.css("top"),10),h=parseInt(f.css("left"),10),k=d.offset(),s=d.outerWidth(),m=f.outerHeight(),o=f.outerWidth();if(this.options.flyout==="bottom"){g=k;s=this.input.offset();g.top=k.top<s.top?g.top-m:g.top+d.outerHeight();f.addClass(i.flyoutpane+"-bottom")}else{g=b.offset();b=b.outerHeight();g.left=g.left+s;var q=g.left+o,
d=a(document.body).scrollLeft(),p=a(window).width()+d;g.top=g.top+b-m;if(g.top<k.top)g.top=k.top;if(q>p){k=g.left-(s+o);if(k>d)g.left=k}f.removeClass(i.flyoutpane+"-bottom")}g.top===r&&g.left===h||f.css({top:g.top,left:g.left})}},hoverout_list:function(){this.flyoutpane&&!this.get_selected()&&this.flyoutpane.hide()}});a.extend(a.suggest.suggest,{defaults:{filter:null,spell:"always",exact:false,scoring:null,lang:null,key:null,prefixed:true,stemmed:null,format:null,advanced:true,show_id:true,query_param_name:"query",
service_url:"https://www.googleapis.com/freebase/v1",service_path:"/search",align:null,flyout:true,flyout_service_url:null,flyout_service_path:"/topic${id}?filter=suggest&filter=/common/topic/article&key=${key}",flyout_image_service_url:null,flyout_image_service_path:"/image${id}?maxwidth=75&key=${key}",flyout_parent:null,suggest_new:null,nomatch:{title:"No suggested matches",heading:"Tips on getting better suggestions:",tips:["Enter more or fewer characters","Add words related to your original search",
"Try alternate spellings","Check your spelling"]},css:{item_type:"fbs-item-type",flyoutpane:"fbs-flyout-pane"},xhr_delay:200},get_property:function(a,d){var c=a.property;return c?c[d]:null},get_values:function(b,d){var c=a.suggest.suggest.get_property(b,d);return c&&c.values?c.values:null},get_first_value:function(b,d){var c=a.suggest.suggest.get_values(b,d);return c&&c.length>0?c[0]:null},create_flyout:function(b,d){var c=a.suggest.suggest.get_property,f=a.suggest.suggest.get_values,i=a.suggest.suggest.get_first_value,
g=i(b,"/type/object/name");if(g)g=g.text;var h=i(b,"/common/topic/description")||i(b,"/common/topic/article")||false;if(h)h=h.text;(i=i(b,"/common/topic/image")||false)&&(i=d.replace(/\$\{id\}/g,b.id));var k=[],s=[b.id],m=f(b,"/common/topic/notable_properties");m&&a.each(m,function(d,e){var h=c(b,e.id);if(h&&h.valuetype!=="compound")if((h=f(b,e.id))&&h.length){h=a.map(h,function(a){return a.text}).join(", ");k.push([e.text||e.id,h])}});var m=f(b,"/common/topic/notable_for"),o=f(b,"/common/topic/notable_types");
if(m||o){var q={},s=[];a.each([m,o],function(a,b){b&&b.forEach(function(a){if(a.id&&!q[a.id]){s.push(a.text);q[a.id]=true}})})}var s=s.join(", "),p=a('<div class="fbs-flyout-content">');g&&p.append(a('<h1 id="fbs-flyout-title">').text(g));p.append(a('<h3 class="fbs-topic-properties fbs-flyout-id">').text(b.id));a.each(k,function(b,d){p.append(a('<h3 class="fbs-topic-properties">').append(a("<strong>").text(d[0]+": ")).append(document.createTextNode(d[1])))});h&&p.append(a('<p class="fbs-topic-article">').text(h));
if(i){p.children().addClass("fbs-flyout-image-true");p.prepend(a('<img id="fbs-topic-image" class="fbs-flyout-image-true" src="'+i+'">'))}g=a('<span class="fbs-flyout-types">').text(s);g=a('<div class="fbs-attribution">').append(g);return a("<div>").append(p).append(g).html()}});document.createElement("input")})(jQuery);(function(a){window.freebase=window.fb={mwLWTReloading:false};window.SERVER&&typeof window.SERVER==="object"&&a.extend(window.freebase,window.SERVER);a.cookie=window.freebase.cookie})(jQuery);
(function(a,c){if(!c.datelineReloading){if(!window.console)window.console={log:a.noop,info:a.noop,debug:a.noop,warn:a.noop,error:a.noop};c.dispatch=function(b,d,c,e){if(typeof d!=="function")return false;b=a.event.fix(b||window.event);c||(c=[]);e||(e=this);return d.apply(e,[b].concat(c))};c.get_script=function(b,d){var e=c.get_script.cache,f=e[b];if(f)f.state===1?f.callbacks.push(d):f.state===4&&d();else{f=e[b]={state:0,callbacks:[d]};a.ajax({url:b,dataType:"script",beforeSend:function(){f.state=
1},success:function(){f.state=4;a.each(f.callbacks,function(a,b){b()})},error:function(a,b,d){f.state=-1;console.error("fb.get_script error",arguments)}})}};c.get_script.cache={};a(window).bind("fb.user.signedin",function(b,d){c.user=d;var e=a("#nav-username");if(e.length){a("> a",e).text(d.name);e[0].href=e[0].href+c.user.id.substring(1);var f=c.h.image_url(d.id,{maxwidth:25,maxheight:25,mode:"fillcropmid"}),f=a('<a class="user-thumb" href="'+d.id+'"><img src="'+f+'" /></a>');e.prepend(f)}a("#signedin").show();
a(".signedin").show()}).bind("fb.user.signedout",function(){a("#signedout").show();a(".signedout").show()}).bind("fb.user.unauthorized",function(){window.location.href=c.h.fb_url("/account/signin",{onsignin:window.location.href})}).bind("fb.user.feedback",function(a,b){if(confirm("Uh oh! Something went wrong. Please report this using our feedback tool."))try{userfeedback.api.startFeedback({productId:"68931",disableScrolling:false},b);return false}catch(d){}});var g=a.cookie("fb-account-name");if(g){var i=
{id:"/user/"+g,name:g};setTimeout(function(){a(window).trigger("fb.user.signedin",i);var b=c.h.ajax_url("lib/template/refresh_credentials"),d=a("<iframe name='rc'></iframe>").attr("src",b).hide().appendTo("body").load(function(){var c=parseInt(a("body",window.rc.document).text(),10)-(new Date).getTime();c&&c>0&&setTimeout(function(){a(d).attr("src",b)},c)})},0)}else setTimeout(function(){a(window).trigger("fb.user.signedout")},0);c.window_position=function(){var a={};if(typeof window.innerWidth==
"number"){a.width=window.outerWidth;a.height=window.outerHeight;a.top=window.screenY;a.left=window.screenX}else if(document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)){a.width=document.body.clientWidth;a.height=document.body.clientHeight;a.top=window.screenTop;a.left=window.screenLeft}return a};var f=function(){e&&e.slideUp(300);r=null;return false},d=function(d,c,i,g){if(e===null){e=a("#page-state");j=a(".status-msg",e);t=a(".close-msg",e);t.click(f)}if(r===
"error")console.warn("MessagePanel: Already displaying error. Ignoring: ",d,c);else{e.hide();a.each(b,function(a,b){e.removeClass(b)});e.addClass(d);j.text(c);r=d;window.clearTimeout(l);if(g){t.show();e.slideDown(300)}else{t.hide();e.slideDown(300);l=window.setTimeout(f,i)}}return false},b=["notice","info","warning","success","error"],e=null,j=null,t=null,l=null,r=null;c.status={doing:function(a){return d("notice",a,2E6,false)},info:function(a,b){return d("info",a,4E3,b)},warning:function(a,b){return d("warning",
a,4E3,b)},success:function(a,b){return d("success",a,6E3,b)},error:function(a,b){return d("error",a,6E3,b)},sprintf:function(b,c){var e=Array.prototype.slice.call(arguments).slice(2),f=c.split("%s");if(f.length>1&&e.length>1&&e.length%2==0){for(var i=a("<span>"),g=0,l=f.length;g<l;g++){i.append(document.createTextNode(f[g]));var r=a('<a href="#">');r.text(e.shift());var n=e.shift();a.type(n)==="function"&&r.click(n);i.append(r)}e=d(b,"",null,true);j.empty().append(i);return e}return d(b,c,null,true)},
clear:function(){window.clearTimeout(l);r==="error"?console.warn("MessagePanel: Displaying error. Ignoring clearing status."):f()}};c.popup=function(a,b,d,e){var b=b||300,d=d||300,f=c.window_position(),i=Math.floor((f.width-b)/2)+f.left,f=Math.floor((f.height-d)/2)+f.top;/chrome/.test(navigator.userAgent.toLowerCase())&&(d=d+50);var b={width:b,height:d,top:f,left:i,directories:"no",location:"no",menubar:"no",resizable:"no",scrollbars:"yes",status:"no",toolbar:"no"},d=[],g;for(g in b)d.push(g+"="+
b[g]);return window.open(a,e||"",d.join())};c.login_popup=function(a){a||(a=function(){window.location.reload()});var b=c.popup("/account/signin",900,600,"Freebase");if(b.opener==null)b.opener=self;window.onsignin=a;window.focus&&b.focus();return false};c.logout_popup=function(a){a||(a=function(){window.location.reload()});var b=c.popup("/account/signout",900,600,"Freebase");if(b.opener==null)b.opener=self;window.onsignout=a;window.focus&&b.focus();return false};a(function(){var b=a("#header > #nav-utilities > .language-picker"),
d=a(".current-lang",b);a("select",b).bind("change",function(){var b=a(this).find(":selected").text();d.text(b)})});a(function(){c.suggest_lang={SUPPORTED:{en:1,es:1,fr:1,de:1,it:1,pt:1,zh:1,ja:1,ko:1,ru:1,sv:1,fi:1,da:1,nl:1,el:1,ro:1,tr:1,hu:1},lang:function(a){a=c.h.lang_code(a||c.lang||"/lang/en");return c.suggest_lang.SUPPORTED[a]&&a!=="en"?a+",en":"en"}};c.suggest_options={service_defaults:{status:["","Searching...","Select an item from the list:"],service_url:c.h.fb_googleapis_url(),key:c.acre.freebase.api_key,
lang:c.suggest_lang.lang()},filter:{operator:function(){var a=Array.prototype.slice.call(arguments),b=a.shift();if(!(b==="any"||b==="all"||b==="should"))throw"Invalid search operator: "+b;var d=[b];if(b==="should"&&a.length>1){a=["any"].concat(a);d.push(c.suggest_options.filter.operator.apply(null,a))}else d=d.concat(a);return"("+d.join(" ")+")"},any:function(){var a=Array.prototype.slice.call(arguments);a.unshift("any");return c.suggest_options.filter.operator.apply(null,a)},all:function(){var a=
Array.prototype.slice.call(arguments);a.unshift("all");return c.suggest_options.filter.operator.apply(null,a)},should:function(){var a=Array.prototype.slice.call(arguments);a.unshift("should");return c.suggest_options.filter.operator.apply(null,a)}},any:function(){var b=a.extend({},c.suggest_options.service_defaults);b.filter=c.suggest_options.filter.any.apply(null,arguments);return b},all:function(){var b=a.extend({},c.suggest_options.service_defaults);b.filter=c.suggest_options.filter.all.apply(null,
arguments);return b},should:function(){var b=a.extend({},c.suggest_options.service_defaults);b.filter=c.suggest_options.filter.should.apply(null,arguments);return b},search:function(){return a.extend({},c.suggest_options.service_defaults,{status:null,parent:"#site-search-box",align:"right",filter:"(not type:/common/document)"})},instance:function(b,d,e){var f=["type:"+b];a.each(["user","domain","type"],function(a,d){if(b==="/freebase/"+d+"_profile"){f.push("type:/type/"+d);return false}});b==="/book/book_subject"&&
f.push("type:/base/skosbase/skos_concept");var i=null;if(c.h.is_metaweb_system_type(b))i=c.suggest_options.any.apply(null,f);else{i=c.suggest_options.should.apply(null,f);if(d)i.suggest_new="Create new"}if(e)i.lang=c.suggest_lang.lang(e);return i},cotype:function(){return a.extend({scoring:"schema"},c.suggest_options.all.apply(null,["type:/type/type","(not namespace:/type)","(not namespace:/freebase)","(any (not namespace:/common) (any mid:/m/01c5 mid:/m/02_1_m4 mid:/m/03hc3d_))"]))},included_type:function(){return c.suggest_options.cotype()},
expected_type:function(){return a.extend({scoring:"schema"},c.suggest_options.all.apply(null,["type:/type/type"]))},delegate_property:function(){return a.extend({scoring:"schema"},c.suggest_options.all.apply(null,["type:/type/property","(not namespace:/type/object)"]))}}});a(function(){var b=a("#SearchBox .SearchBox-input,#fb-search-input"),d=a("#fb-search");b.suggest(c.suggest_options.search());var e=a("#site-search-label"),f=a("#site-search-box .fbs-pane");b.bind("fb-select",function(b,d){var e=
{};a(this).siblings("input[type=hidden]").each(function(){e[this.name]=this.value});window.location=c.h.fb_url(d.id,e);return false}).bind("fb-pane-show",function(){e.html("<span>Select an item from the list</span>").removeClass("loading")}).bind("fb-textchange",function(){a.trim(b.val())===""?e.html("<span>Start typing to get some suggestions</span>").removeClass("loading"):e.html("<span>Searching...</span>").addClass("loading")}).bind("fb-error",function(){e.html("<span>Sorry, something went wrong. Please try again later</span>").removeClass("loading")}).focus(function(){if(!e.is(":visible")){a("#site-search-label").slideDown("fast");
d.addClass("active")}}).blur(function(){if(!f.is(":visible")&&e.is(":visible")){a("#site-search-label").slideUp("fast");d.removeClass("active")}});a(".SearchBox-form").submit(function(){return a.trim(a("#fb-search-input").val()).length==0?false:true})});c.disable=function(b){a(b).attr("disabled","disabled").addClass("disabled")};c.enable=function(b){a(b).removeAttr("disabled").removeClass("disabled")};c.lang_select=function(b,d){if(d==="/lang/en"){a(this).removeAttr("name");if(!a(":input[name]",this.form).length){window.location=
a(this.form).attr("action");return}}this.form.submit()};c.devbar={div:a("#devbar"),touch:function(){/\.(freebase|sandbox\-freebase)\.com$/.test(c.acre.request.server_name)?a.ajax({url:c.acre.freebase.googleapis_url?c.h.fb_googleapis_url("/touch"):c.h.fb_api_url("/api/service/touch"),dataType:"jsonp"}):a.ajax({url:"/acre/touch"});return false},txn_ids:[],txn:function(){return c.devbar.view_txn(this.href,c.devbar.txn_ids)},view_txn:function(b,d){if(d&&d.length)window.location=b+"?"+a.param({tid:d},
true);return false},ajaxComplete:function(a){if(a&&a.readyState===4)(a=a.getResponseHeader("x-metaweb-tid"))&&c.devbar.txn_ids.push(a)},init:function(){$nav_user_controls=a(".nav-user-controls");$user_controls=a("#user-controls");a("#signedin .trigger").click(function(){if($user_controls.is(":hidden")){$user_controls.fadeIn();$nav_user_controls.addClass("active")}else{$user_controls.fadeOut();$nav_user_controls.removeClass("active")}return false});a("html").click(function(){if($user_controls.is(":visible")){$user_controls.fadeOut();
$nav_user_controls.removeClass("active")}});$user_controls.click(function(a){a.stopPropagation()});a("#devbar-touch > a").click(c.devbar.touch);c.tid&&c.devbar.txn_ids.push(c.tid);a("#devbar-txn > a").click(c.devbar.txn);a.ajaxSetup({complete:function(){c.devbar.ajaxComplete.apply(null,arguments)},error:function(b){a.each(["url","data","dataType","type"],function(){});a.each(["status","statusText","responseText"],function(){});b.getAllResponseHeaders()}})}};c.devbar.init();c.mqlread=function(b,d,
e){var f;if(c.acre.freebase.googleapis_url){f=c.h.fb_googleapis_url("/mqlread");b={query:JSON.stringify(b),key:c.acre.freebase.api_key}}else{f=c.h.fb_api_url("/api/service/mqlread");b={query:JSON.stringify({query:b})}}return a.ajax({url:f,data:b,dataType:"jsonp",success:function(a){d&&d.apply(this,[a.result])},error:function(){e&&e.apply(this,arguments)}})};a(function(){c.hover={pane:"#fb-topic-hover-pane",current_target:null,cache:{},topic_url:c.h.fb_googleapis_url()+"/topic${id}?filter=suggest&limit=3&key="+
c.acre.freebase.api_key+"&lang="+c.h.lang_code(c.lang),image_url:c.h.fb_googleapis_url()+"/image${id}?maxwidth=75&key="+c.acre.freebase.api_key,show:function(){function b(){if(d===c.hover.current_target){a(c.hover.pane).html(c.hover.cache[e]);var f=a(c.hover.pane).height(),i=a(d).height(),g=a(d).offset(),h=g.left,g=g.top,g=g-a(document).scrollTop()+f<a(window).height()?g+i:g-f-i;a(c.hover.pane).css({top:g,left:h}).show()}}var d=this,e=a(d).attr("data-id");if(e){c.hover.current_target=d;a(d).removeAttr("title");
c.hover.cache[e]?b():a.ajax({url:c.hover.topic_url.replace(/\$\{id\}/g,e),success:function(d){d=a.suggest.suggest.create_flyout(d,c.hover.image_url);c.hover.cache[e]=d;b()},dataType:"jsonp",cache:true})}},hide:function(){c.hover.current_target=null;a(c.hover.pane).hide()}};c.keyboard_shortcut={cache_:{},add:function(a,b){var d=a.charCodeAt(0);d in c.keyboard_shortcut.cache_&&console.warn("Overriding keyboard shortcut",a);c.keyboard_shortcut.cache_[d]=b}};a(document).keypress(function(b){var d=b.charCode,
b=b.target;if(c.keyboard_shortcut.cache_[d]&&(b==document.body||b==document||b==window||b==a("html")[0])){c.keyboard_shortcut.cache_[d]();return false}});a("#page-content").on("mouseover","a.property-value",c.hover.show).on("mouseout","a.property-value",c.hover.hide)})}})(jQuery,window.freebase);
(function(a,c){var g;if(!(g=a.type)){var i={};["Boolean","Number","String","Function","Array","Date","RegExp","Object"].forEach(function(a){i["[object "+a+"]"]=a.toLowerCase()});g=function(a){return a==null?String(a):i[Object.prototype.toString.call(a)]||"object"}}var f=c.h={type:g,parse_params:function(d){if(a.isArray(d)){var b={};a.each(d,function(a,d){b[d[0]]=d[1]});return b}return d},build_url:function(d){if(d&&d.indexOf("//")!==0&&d.indexOf("://")===-1)throw"Host must contain scheme: "+d;var b=
d||"",e,c;if(arguments.length>1){e=Array.prototype.slice.call(arguments);e.shift();for(var i=[],g=0,r=e.length;g<r;g++){var h=e[g];if(f.type(h)==="string")i.push(h);else{for(c={};g<r;g++)c=a.extend(c,f.parse_params(e[g]));break}}e=i.join("")}if(e&&e.indexOf("/")!==0)throw"Path must begin with a '/': "+e;e&&(b=b+e);b===""&&(b="/");a.isEmptyObject(c)||(b=b+("?"+a.param(c,true)));return b},fb_url:function(){var a=Array.prototype.slice.call(arguments);a.unshift(null);c.lang&&c.lang!=="/lang/en"&&a.push({lang:f.lang_code(c.lang)});
return f.build_url.apply(null,a)},ajax_url:function(){var a=Array.prototype.slice.call(arguments);a.unshift("/ajax");return f.reentrant_url.apply(null,a)},static_url:function(){var a=Array.prototype.slice.call(arguments);a.unshift("/static");return f.reentrant_url.apply(null,a)},reentrant_url:function(a,b){var b=f.resolve_reentrant_path(b),b=b.replace(/^\/\//,a+"/"),e=Array.prototype.slice.call(arguments,2);e.unshift(b);e.unshift(null);return f.build_url.apply(null,e)},resolve_reentrant_path:function(a){a=
a||"";if(a.indexOf("//")==0)return a;if(a.indexOf("lib/")===0)return c.acre.current_script.app.path+a.substring(3);a&&a[0]!="/"&&(a="/"+a);return c.acre.request.script.app.path+a},legacy_fb_url:function(){var a=Array.prototype.slice.call(arguments),b=c.acre.freebase.site_host.replace(/^(https?\:\/\/)([^\.]+)\./,"$1www.").replace(":"+c.acre.request.server_port,"");a.unshift(b);return f.build_url.apply(null,a)},fb_api_url:function(){var a=Array.prototype.slice.call(arguments);a.unshift(c.acre.freebase.service_url);
return f.build_url.apply(null,a)},fb_googleapis_url:function(){if(c.acre.freebase.googleapis_url){var a=Array.prototype.slice.call(arguments);a.unshift(c.acre.freebase.googleapis_url);return f.build_url.apply(null,a)}throw"fb.acre.freebase.googleapis_url is not defined";},wiki_url:function(a){var b=Array.prototype.slice.call(arguments);b.unshift("http://wiki.freebase.com","/wiki/");return f.build_url.apply(null,b)},lib_base_url:function(a){a=c.acre.metadata.libs[a];return a.base_url+a.version},image_url:function(a,
b){return c.acre.freebase.imgurl(a,b.maxwidth,b.maxheight,b.mode,b.pad,b.errorid)},is_metaweb_system_type:function(a){return a.indexOf("/type/")===0||a.indexOf("/common/")===0&&a!=="/common/topic"||a.indexOf("/freebase/")===0&&a.indexOf("_profile")===a.length-8},id_key:function(a,b){var e=a.split("/"),c=e.pop();if(b){e=e.join("/");e===""&&(e="/");return[e,c]}return c},lang_code:function(a){return f.id_key(a)},lang_id:function(a){return"/lang/"+f.lang_code(a)}}})(jQuery,window.freebase);
(function(a,c){var g=c.permission={init:function(){if(c.user){var i=c.c;i&&i.id&&a.ajax({url:c.h.ajax_url("lib/permission/has_permission.ajax"),data:{id:i.id,user_id:c.user.id},dataType:"json",success:function(c){g.has_permission=c.result&&c.result[i.id]===true;a(window).trigger("fb.permission.has_permission",g.has_permission)}});check_permissioned_objects(a(".edit-perm"),c.user.id)}else setTimeout(function(){g.has_permission=false;a(window).trigger("fb.permission.has_permission",g.has_permission)})}};
a(window).bind("fb.user.signedin",g.init);a(window).bind("fb.user.signedout",g.init);a(window).bind("fb.permission.has_permission",function(c,f){f?a(".edit").show():a(".no-edit").show()})})(jQuery,window.freebase);
function check_permissioned_objects(a,c){if(a.length&&c){var g={},i=[];$.each(a,function(){var a=$(this).metadata().id;if(a&&!g[a]){i.push(a);g[a]=1}});i.length&&$.ajax({url:fb.h.ajax_url("lib/permission/has_permission.ajax"),data:{id:i,user_id:c},traditional:true,dataType:"json",success:function(c){var d=c.result||{};$.each(a,function(){var a=$(this).metadata().id;a&&d[a]===true?$(this).show():$(this).addClass("edit-perm-lock")})}})}}
(function(a,c){var g=c.incompatible_types={overlay_dialog:null,inline_dialog:null,suggest_options:function(c,f,d){var d=d||{},f=[c].concat(f||[]),b=d.filter;if(!a.isArray(b)){b=[];b!=null&&b.push(d.filter);d.filter=b}b.push("(should (not incompatible:"+c+"))");d.filter=b;if(c=d.output)(b=/^\((.*)\)$/.exec(d.output))&&(c="("+g.search_output_(f)+" "+b[1]+")");c||(c=g.search_output_(f,true));d.output=c;return d},search_output_:function(a,c){var d=a.map(function(a){return"incompatible:"+a}).join(" ");
c&&(d="("+d+")");return d},check:function(c,f,d,b){var b=b||{},e=false,g=c.output;if(g){var t=[f].concat(d||[]);a.each(t,function(a,b){var c="incompatible:"+b;if(g[c]["/type/object/type"][0]==="true"||g[c]["/type/object/type"][0]===true)e=true;return!e})}e?b.incompatible&&b.incompatible(c,f,d):b.compatible&&b.compatible(c,f,d)},search:function(i,f,d,b){var e=[f].concat(d||[]),e={filter:"(all mid:"+i+")",output:g.search_output_(e,true)};a.ajax({url:c.h.fb_googleapis_url("/search",e),dataType:"jsonp",
success:function(e){a.isArray(e.result)&&e.result.length>0?g.check(e.result[0],f,d,b):c.status.error("Incompatible type check search error: "+i)}})},overlay_incompatible_callback:function(c,f){if(!g.overlay_dialog)g.overlay_dialog=a(".incompatible-overlay-dialog");if(g.overlay_dialog.length){c=c||{};return function(d,b,e){g.overlay_dialog.removeData("overlay");a(".modal-content",g.overlay_dialog).empty().append(g.description_html(d,b,e));g.overlay_dialog.overlay({close:"button",closeOnClick:false,
load:true,fixed:false,mask:{color:"#000",loadSpeed:200,opacity:0.5},onClose:function(){f&&f.focus().select();a("button",g.overlay_dialog).unbind();if(c.onClose)c.onClose()},onLoad:function(){a(".cancel",g.overlay_dialog).focus().click(function(){f&&f.focus().select().trigger("textchange");if(c.onCancel)c.onCancel()});a(".save",g.overlay_dialog).click(function(){f&&f.focus().select();if(c.onConfirm)c.onConfirm(d,b,e)});if(c.onLoad)c.onLoad()}})}}return g.native_confirm_incompatible_callback(c,f)},
inline_incompatible_callback:function(c,f){if(!g.inline_dialog)g.inline_dialog=a(".incompatible-inline-dialog");if(g.inline_dialog.length){c=c||{};return function(d,b,e){a(".modal-content",g.inline_dialog).empty().append(g.description_html(d,b,e));a(".save",g.inline_dialog).unbind().click(function(){f.focus().select();if(c.onConfirm)c.onConfirm(d,b,e);g.inline_dialog.hide(c.onClose)});a(".cancel",g.inline_dialog).unbind().click(function(){f.focus().select().trigger("textchange");if(c.onCancel)c.onCancel();
g.inline_dialog.hide(c.onClose)});var j=f.offsetParent(),t=f.position();j.append(g.inline_dialog);g.inline_dialog.css({top:t.top+f.outerHeight(),left:t.left});g.inline_dialog.show(c.onLoad)}}return g.native_confirm_incompatible_callback(c,f)},native_confirm_incompatible_callback:function(a,c){a=a||{};return function(d,b,e){if(confirm(g.description_text(d,b,e))){c&&c.focus().select();if(a.onConfirm)a.onConfirm(d,b,e)}else{c&&c.focus().select().trigger("textchange");if(a.onCancel)a.onCancel()}if(a.onClose)a.onClose();
c&&c.focus().select()}},description_html:function(c,f){var d=a("<div>"),b;b=a('<div><b class="incompatible-topic"></b> is incompatible with <b class="incompatible-type"></b>.</div>');a(".incompatible-topic",b).text(c.name||c.id);a(".incompatible-type",b).text(f);d.append(b);b=a('<div>If you continue, <b class="incompatible-topic"></b> will be typed as <b class="incompatible-type"></b> and its included types (if any).</div>');a(".incompatible-topic",b).text(c.name||c.id);a(".incompatible-type",b).text(f);
d.append(b);d.append("<p>Are you sure you want to continue?<p>");return d},description_text:function(a,c,d){return g.description_html(a,c,d).text()}}})(jQuery,window.freebase);
(function(a,c){var g=c.flag={merge:function(a){return g.flag(a,"merge_begin")},split:function(a){return g.flag(a,"split_begin")},"delete":function(a){return g.flag(a,"delete_begin")},offensive:function(a){return g.flag(a,"offensive_begin")},flag:function(i,f){i=a(i);c.get_script(c.h.static_url("lib/flag/flag-edit.mf.js"),function(){g.edit[f](i)});return false},undo:function(i,f){i=a(i);c.get_script(c.h.static_url("lib/flag/flag-edit.mf.js"),function(){g.edit.undo_begin(i,f)});return false}}})(jQuery,
window.freebase);
