
/*
 * Copyright 2012, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Additional Licenses for Third Party components can be found here:
 * http://wiki.freebase.com/wiki/Freebase_Site_License
 *
 */
(function(d){d.extend({tablesorter:new function(){function a(d,a){b(d+","+((new Date).getTime()-a.getTime())+"ms")}function b(d){"undefined"!=typeof console&&"undefined"!=typeof console.debug?console.log(d):alert(d)}function e(a,z){var n="";if(0!=a.tBodies.length){var h=a.tBodies[0].rows;if(h[0])for(var c=[],i=h[0].cells.length,k=0;k<i;k++){var j=!1;d.metadata&&d(z[k]).metadata()&&d(z[k]).metadata().sorter?j=g(d(z[k]).metadata().sorter):a.config.headers[k]&&a.config.headers[k].sorter&&(j=g(a.config.headers[k].sorter));
if(!j)a:{for(var j=a,e=h,f=-1,m=k,p=l.length,s=!1,q=!1,u=!0;""==q&&u;)f++,e[f]?(s=e[f].cells[m],q=d.trim(o(j.config,s)),j.config.debug&&b("Checking if value was empty on row:"+f)):u=!1;for(e=1;e<p;e++)if(l[e].is(q,j,s)){j=l[e];break a}j=l[0]}a.config.debug&&(n+="column:"+k+" parser:"+j.id+"\n");c.push(j)}a.config.debug&&b(n);return c}}function g(d){for(var a=l.length,b=0;b<a;b++)if(l[b].id.toLowerCase()==d.toLowerCase())return l[b];return!1}function f(b){var e;b.config.debug&&(e=new Date);for(var n=
b.tBodies[0]&&b.tBodies[0].rows.length||0,h=b.tBodies[0].rows[0]&&b.tBodies[0].rows[0].cells.length||0,c=b.config.parsers,i={row:[],normalized:[]},k=0;k<n;++k){var j=d(b.tBodies[0].rows[k]),g=[];if(j.hasClass(b.config.cssChildRow))i.row[i.row.length-1]=i.row[i.row.length-1].add(j);else{i.row.push(j);for(var m=0;m<h;++m)g.push(c[m].format(o(b.config,j[0].cells[m]),b,j[0].cells[m]));g.push(i.normalized.length);i.normalized.push(g)}}b.config.debug&&a("Building cache for "+n+" rows:",e);return i}function o(a,
b){var e="";if(!b)return"";a.supportsTextContent||(a.supportsTextContent=b.textContent||!1);return e="simple"==a.textExtraction?a.supportsTextContent?b.textContent:b.childNodes[0]&&b.childNodes[0].hasChildNodes()?b.childNodes[0].innerHTML:b.innerHTML:"function"==typeof a.textExtraction?a.textExtraction(b):d(b).text()}function u(b,e){var n;b.config.debug&&(n=new Date);for(var h=e.row,c=e.normalized,i=c.length,k=c[0].length-1,j=d(b.tBodies[0]),g=[],f=0;f<i;f++){var m=c[f][k];g.push(h[m]);if(!b.config.appender)for(var o=
h[m].length,l=0;l<o;l++)j[0].appendChild(h[m][l])}b.config.appender&&b.config.appender(b,g);g=null;b.config.debug&&a("Rebuilt table:",n);A(b);setTimeout(function(){d(b).trigger("sortEnd")},0)}function v(a,d){return a.config.headers[d]&&a.config.headers[d].lockedOrder?a.config.headers[d].lockedOrder:!1}function A(a){for(var d=a.config.widgets,b=d.length,e=0;e<b;e++)w(d[e]).format(a)}function w(a){for(var d=t.length,b=0;b<d;b++)if(t[b].id.toLowerCase()==a.toLowerCase())return t[b]}function B(a,b,e,
h){b.removeClass(h[0]).removeClass(h[1]);var c=[];b.each(function(){this.sortDisabled||(c[this.column]=d(this))});a=e.length;for(b=0;b<a;b++)c[e[b][0]].addClass(h[e[b][1]])}function x(d,b,e){var h,c;d.config.debug&&(h=new Date);var i="var sortWrapper = function(a,b) {",k=b.length;for(c=0;c<k;c++)var j=b[c][0],g=b[c][1],j="text"==d.config.parsers[j].type?0==g?p("text","asc",j):p("text","desc",j):0==g?p("numeric","asc",j):p("numeric","desc",j),f="e"+c,i=i+("var "+f+" = "+j),i=i+("if("+f+") { return "+
f+"; } "),i=i+"else { ";c=e.normalized[0].length-1;i+="return a["+c+"]-b["+c+"];";for(c=0;c<k;c++)i+="}; ";i+="return 0; }; ";d.config.debug&&a("Evaling expression:"+i,new Date);eval(i);e.normalized.sort(sortWrapper);d.config.debug&&a("Sorting on "+b.toString()+" and dir "+g+" time:",h);return e}function p(a,d,b){var e="a["+b+"]",b="b["+b+"]";if("text"==a&&"asc"==d)return"("+e+" == "+b+" ? 0 : ("+e+" === null ? Number.POSITIVE_INFINITY : ("+b+" === null ? Number.NEGATIVE_INFINITY : ("+e+" < "+b+") ? -1 : 1 )));";
if("text"==a&&"desc"==d)return"("+e+" == "+b+" ? 0 : ("+e+" === null ? Number.POSITIVE_INFINITY : ("+b+" === null ? Number.NEGATIVE_INFINITY : ("+b+" < "+e+") ? -1 : 1 )));";if("numeric"==a&&"asc"==d)return"("+e+" === null && "+b+" === null) ? 0 :("+e+" === null ? Number.POSITIVE_INFINITY : ("+b+" === null ? Number.NEGATIVE_INFINITY : "+e+" - "+b+"));";if("numeric"==a&&"desc"==d)return"("+e+" === null && "+b+" === null) ? 0 :("+e+" === null ? Number.POSITIVE_INFINITY : ("+b+" === null ? Number.NEGATIVE_INFINITY : "+
b+" - "+e+"));"}var l=[],t=[];this.defaults={cssHeader:"header",cssAsc:"headerSortUp",cssDesc:"headerSortDown",cssChildRow:"expand-child",sortInitialOrder:"asc",sortMultiSortKey:"shiftKey",sortForce:null,sortAppend:null,sortLocaleCompare:!0,textExtraction:"simple",parsers:{},widgets:[],widgetZebra:{css:["even","odd"]},headers:{},widthFixed:!1,cancelSelection:!0,sortList:[],headerList:[],dateFormat:"us",decimal:"/.|,/g",onRenderHeader:null,selectorHeaders:"thead th",debug:!1};this.benchmark=a;this.construct=
function(g){return this.each(function(){if(this.tHead&&this.tBodies){var l,n,h;this.config={};h=d.extend(this.config,d.tablesorter.defaults,g);l=d(this);d.data(this,"tablesorter",h);var c=this,i;c.config.debug&&(i=new Date);for(var k=[],j={},p=c.getElementsByTagName("THEAD")[0].getElementsByTagName("TR"),t=0;t<p.length;t++)for(var G=p[t].cells,D=0;D<G.length;D++){var s=G[D],q=s.parentNode.rowIndex,E=q+"-"+s.cellIndex,K=s.rowSpan||1,s=s.colSpan||1,C;"undefined"==typeof k[q]&&(k[q]=[]);var r;for(r=
0;r<k[q].length+1;r++)if("undefined"==typeof k[q][r]){C=r;break}j[E]=C;for(r=q;r<q+K;r++){"undefined"==typeof k[r]&&(k[r]=[]);for(var E=k[r],F=C;F<C+s;F++)E[F]="x"}}var y=d(c.config.selectorHeaders,c).each(function(a){this.column=j[this.parentNode.rowIndex+"-"+this.cellIndex];this.count=this.order="Number"!=typeof c.config.sortInitialOrder?"desc"==c.config.sortInitialOrder.toLowerCase()?1:0:1==c.config.sortInitialOrder?1:0;if(d.metadata&&!1===d(this).metadata().sorter||c.config.headers[a]&&!1===c.config.headers[a].sorter)this.sortDisabled=
!0;v(c,a)&&(this.order=this.lockedOrder=v(c,a));if(!this.sortDisabled){var b=d(this).addClass(c.config.cssHeader);c.config.onRenderHeader&&c.config.onRenderHeader.apply(b)}c.config.headerList[a]=this});c.config.debug&&(a("Built headers:",i),b(y));this.config.parsers=e(this,y);n=f(this);var H=[h.cssDesc,h.cssAsc];if(this.config.widthFixed){var I=d("<colgroup>");d("tr:first td",this.tBodies[0]).each(function(){I.append(d("<col>").css("width",d(this).width()))});d(this).prepend(I)}y.click(function(c){var a=
l[0].tBodies[0]&&l[0].tBodies[0].rows.length||0;if(!this.sortDisabled&&a>0){l.trigger("sortStart");d(this);a=this.column;this.order=this.count++%2;if(this.lockedOrder)this.order=this.lockedOrder;if(c[h.sortMultiSortKey]){a:{for(var c=h.sortList,b=c.length,i=0;i<b;i++)if(c[i][0]==a){c=true;break a}c=false}if(c)for(c=0;c<h.sortList.length;c++){b=h.sortList[c];i=h.headerList[b[0]];if(b[0]==a){i.count=b[1];i.count++;b[1]=i.count%2}}else h.sortList.push([a,this.order])}else{h.sortList=[];if(h.sortForce!=
null){b=h.sortForce;for(c=0;c<b.length;c++)b[c][0]!=a&&h.sortList.push(b[c])}h.sortList.push([a,this.order])}setTimeout(function(){B(l[0],y,h.sortList,H);u(l[0],x(l[0],h.sortList,n))},1);return false}}).mousedown(function(){if(h.cancelSelection){this.onselectstart=function(){return false};return false}});l.bind("update",function(){var c=this;setTimeout(function(){c.config.parsers=e(c,y);n=f(c)},1)}).bind("updateCell",function(c,a){var b=this.config,d=[a.parentNode.rowIndex-1,a.cellIndex];n.normalized[d[0]][d[1]]=
b.parsers[d[1]].format(o(b,a),a)}).bind("sorton",function(c,a){d(this).trigger("sortStart");h.sortList=a;for(var b=h.sortList,i=this.config,e=b.length,k=0;k<e;k++){var g=b[k],j=i.headerList[g[0]];j.count=g[1];j.count++}B(this,y,b,H);u(this,x(this,b,n))}).bind("appendCache",function(){u(this,n)}).bind("applyWidgetId",function(c,a){w(a).format(this)}).bind("applyWidgets",function(){A(this)});d.metadata&&(d(this).metadata()&&d(this).metadata().sortlist)&&(h.sortList=d(this).metadata().sortlist);0<h.sortList.length&&
l.trigger("sorton",[h.sortList]);A(this)}})};this.addParser=function(a){for(var b=l.length,d=!0,e=0;e<b;e++)l[e].id.toLowerCase()==a.id.toLowerCase()&&(d=!1);d&&l.push(a)};this.addWidget=function(a){t.push(a)};this.formatFloat=function(a){a=parseFloat(a);return isNaN(a)?0:a};this.formatInt=function(a){a=parseInt(a);return isNaN(a)?0:a};this.isDigit=function(a){return/^[-+]?\d*$/.test(d.trim(a.replace(/[,.']/g,"")))};this.clearTableBody=function(a){d.browser.msie?function(){for(;this.firstChild;)this.removeChild(this.firstChild)}.apply(a.tBodies[0]):
a.tBodies[0].innerHTML=""}}});d.fn.extend({tablesorter:d.tablesorter.construct});var f=d.tablesorter;f.addParser({id:"text",is:function(){return!0},format:function(a){return d.trim(a.toLocaleLowerCase())},type:"text"});f.addParser({id:"digit",is:function(a,b){return d.tablesorter.isDigit(a,b.config)},format:function(a){return d.tablesorter.formatFloat(a)},type:"numeric"});f.addParser({id:"currency",is:function(a){return/^[\u00a3$\u20ac?.]/.test(a)},format:function(a){return d.tablesorter.formatFloat(a.replace(RegExp(/[\u00a3$\u20ac]/g),
""))},type:"numeric"});f.addParser({id:"ipAddress",is:function(a){return/^\d{2,3}[\.]\d{2,3}[\.]\d{2,3}[\.]\d{2,3}$/.test(a)},format:function(a){for(var a=a.split("."),b="",e=a.length,g=0;g<e;g++)var f=a[g],b=2==f.length?b+("0"+f):b+f;return d.tablesorter.formatFloat(b)},type:"numeric"});f.addParser({id:"url",is:function(a){return/^(https?|ftp|file):\/\/$/.test(a)},format:function(a){return jQuery.trim(a.replace(RegExp(/(https?|ftp|file):\/\//),""))},type:"text"});f.addParser({id:"isoDate",is:function(a){return/^\d{4}[\/-]\d{1,2}[\/-]\d{1,2}$/.test(a)},
format:function(a){return d.tablesorter.formatFloat(""!=a?(new Date(a.replace(RegExp(/-/g),"/"))).getTime():"0")},type:"numeric"});f.addParser({id:"percent",is:function(a){return/\%$/.test(d.trim(a))},format:function(a){return d.tablesorter.formatFloat(a.replace(RegExp(/%/g),""))},type:"numeric"});f.addParser({id:"usLongDate",is:function(a){return a.match(RegExp(/^[A-Za-z]{3,10}\.? [0-9]{1,2}, ([0-9]{4}|'?[0-9]{2}) (([0-2]?[0-9]:[0-5][0-9])|([0-1]?[0-9]:[0-5][0-9]\s(AM|PM)))$/))},format:function(a){return d.tablesorter.formatFloat((new Date(a)).getTime())},
type:"numeric"});f.addParser({id:"shortDate",is:function(a){return/\d{1,2}[\/\-]\d{1,2}[\/\-]\d{2,4}/.test(a)},format:function(a,b){var e=b.config,a=a.replace(/\-/g,"/");if("us"==e.dateFormat)a=a.replace(/(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{4})/,"$3/$1/$2");else if("uk"==e.dateFormat)a=a.replace(/(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{4})/,"$3/$2/$1");else if("dd/mm/yy"==e.dateFormat||"dd-mm-yy"==e.dateFormat)a=a.replace(/(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{2})/,"$1/$2/$3");return d.tablesorter.formatFloat((new Date(a)).getTime())},
type:"numeric"});f.addParser({id:"time",is:function(a){return/^(([0-2]?[0-9]:[0-5][0-9])|([0-1]?[0-9]:[0-5][0-9]\s(am|pm)))$/.test(a)},format:function(a){return d.tablesorter.formatFloat((new Date("2000/01/01 "+a)).getTime())},type:"numeric"});f.addParser({id:"metadata",is:function(){return!1},format:function(a,b,e){a=b.config;a=!a.parserMetadataName?"sortValue":a.parserMetadataName;return d(e).metadata()[a]},type:"numeric"});f.addWidget({id:"zebra",format:function(a){var b;a.config.debug&&(b=new Date);
var e,g=-1,f;d("tr:visible",a.tBodies[0]).each(function(){e=d(this);e.hasClass(a.config.cssChildRow)||g++;f=0==g%2;e.removeClass(a.config.widgetZebra.css[f?0:1]).addClass(a.config.widgetZebra.css[f?1:0])});a.config.debug&&d.tablesorter.benchmark("Applying Zebra widget",b)}})})(jQuery);
(function(d){d(function(){d.tablesorter&&(d("<div>"),d.tablesorter.defaults.cssAsc="column-header-asc",d.tablesorter.defaults.cssDesc="column-header-desc",d.tablesorter.defaults.cssHeader="column-header",d.tablesorter.addParser({id:"datetime",is:function(){return!1},format:function(f,a,b){return d("[datetime]:first",b).attr("datetime")},type:"text"}),d.tablesorter.addParser({id:"ignoreCase",is:function(){return!1},format:function(d){return d.toLowerCase()},type:"text"}),d.tablesorter.addParser({id:"string",
is:function(){return!1},format:function(d){return d},type:"text"}),d.tablesorter.addParser({id:"number",is:function(){return!1},format:function(f,a,b){f=d(".number:first",b).attr("data-value");null==f&&(f=Number.MIN_VALUE);return f},type:"numeric"}),d(".table-sortable").each(function(){d(this).tablesorter()}))})})(jQuery);
(function(d){d.fn.fixedcolumn=function(f){var a=d.extend(!0,{},f);return this.each(function(){var b=d(this).find("tr:first").children();1<b.length&&(a.all||(b=d(b.get(0))),b.each(function(){var a=d(this),b=a[0].nodeName.toUpperCase();if("TD"===b||"TH"===b)b=a.width(),0<b&&d(":first-child",a).width(b).css("display","inline-block")}))})}})(jQuery);
(function(d){var f="undefined"!=typeof window.innerWidth?function(){return{w:window.innerWidth,h:window.innerHeight}}:"undefined"!=typeof document.documentElement&&"undefined"!=typeof document.documentElement.clientWidth&&0!=document.documentElement.clientWidth?function(){return{w:document.documentElement.clientWidth,h:document.documentElement.clientHeight}}:function(){return{w:document.getElementsByTagName("body")[0].clientWidth,h:document.getElementsByTagName("body")[0].clientHeight}};window.kbs=
function(a){d(".kbs.current",a).removeClass("current");var b=d(".domain-section:first",a),e=d(".domain-section:last",a),g=this.scroll_to=function(c){var a=d(document).scrollTop();d(document).height();var b=f().h,b=a+b,e=c.offset().top,c=e+c.height();e<a?d(document).scrollTop(e):c>b&&d(document).scrollTop(a+(c-b))},m=this.get_current=function(){return d(".kbs.current:first",a)},o=this.set_next=function(c,a,b){c=c||m();a.length&&(c.removeClass("current"),a.addClass("current"),b||g(a))},u=this.next_domain=
function(c){var a=m(),b=v(a);b&&(b=b.find(".kbs:first"),o(a,b,c))},v=this._next_domain=function(c){if(!c||!c.length)return d(".domain-section:first",a);c=c.closest(".domain-section");return!c.length||c[0]===e[0]?b:c.next(".domain-section")},A=this.prev_domain=function(){var c=m(),a=w(c);a&&(a=a.find(".kbs:first"),o(c,a))},w=this._prev_domain=function(c){if(!c||!c.length)return d(".domain-section:last",a);var i=c.closest(".domain-section");return c.closest(".property-section").length||c.closest(".type-section").length?
i:!i.length||i[0]===b[0]?e:i.prev(".domain-section")},B=this.next_type=function(){var c=m(),a=x(c);a&&(a=a.find(".kbs:first"),o(c,a))},x=this._next_type=function(c){if(!c||!c.length)return d(".type-section:first",a);var b=c.closest(".domain-section"),c=c.closest(".type-section"),c=c.length?c.next(".type-section"):b.find(".type-section:first");if(!c||!c.length){var e=v(b);if(e)for(;e.get(0)!==b.get(0);){c=e.find(".type-section:first");if(c.length)break;e=v(e)}}return c},p=this.prev_type=function(){var a=
m(),b=l(a);b&&(b=b.find(".kbs:first"),o(a,b))},l=this._prev_type=function(c){if(!c||!c.length)return d(".type-section:last",a);var b=c.closest(".domain-section"),e=c.closest(".type-section");if(c.closest(".property-section").length)return e;var g;e.length&&(g=e.prev(".type-section"));if(!g||!g.length)if(c=w(b))for(;c.get(0)!==b.get(0);){g=c.find(".type-section:last");if(g.length)break;c=w(c)}return g},t=this.next_prop=function(){var a=m(),b=J(a);b&&(b=b.find(".kbs:first"),o(a,b))},J=this._next_prop=
function(c){if(!c||!c.length)return d(".property-section:first",a);var b=c.closest(".domain-section"),e=c.closest(".type-section"),g=c.closest(".property-section"),b=g.length?g.next(".property-section"):e.length?e.find(".property-section:first"):b.find(".property-section:first");if(!b||!b.length)if(c=x(c))for(;c.get(0)!==e.get(0);){b=c.find(".property-section:first");if(b.length)break;null==e.get(0)&&(e=c);c=x(c)}return b},z=this.prev_prop=function(){var a=m(),b=n(a);b&&(b=b.find(".kbs:first"),o(a,
b))},n=this._prev_prop=function(b){if(!b||!b.length)return d(".property-section:last",a);var e=b.closest(".domain-section"),g=b.closest(".type-section"),f=b.closest(".property-section");if(b.closest(".data-section").length)return f;var h;f.length&&(h=f.prev(".property-section"));if(!h||!h.length)if(p=g.length?l(g):l(e))for(;p.get(0)!==g.get(0);){h=p.find(".property-section:last");if(h.length)break;null==g.get(0)&&(g=p);p=l(p)}return h};this.next=function(){var a=m(),b=this._next(a);b&&o(a,b)};this._next=
function(c){if(!c||!c.length)return d(".domain-section:first .kbs:first",a);var g=c.closest(".domain-section"),f=c.closest(".type-section"),h=c.closest(".property-section");if(c.closest(".data-section").length){c=c.next(".kbs");if(c.length)return c;c=h.next(".property-section").find(".kbs:first");if(c.length)return c;c=f.next(".type-section").find(".kbs:first")}else if(h.length){c=h.find(".data-section:first .kbs:first");if(c.length)return c;c=h.next(".property-section").find(".kbs:first");if(c.length)return c;
c=f.next(".type-section").find(".kbs:first")}else if(f.length){c=f.find(".property-section:first .kbs:first");if(c.length)return c;c=f.next(".type-section").find(".kbs:first")}else c=g.find(".type-section:first .kbs:first");return c.length?c:g.get(0)===e.get(0)?b.find(".kbs:first"):g.next(".domain-section").find(".kbs:first")};this.prev=function(){var a=m(),b=this._prev(a);b&&o(a,b)};this._prev=function(c){if(!c||!c.length)return c=d(".data-section:last .kbs:last",a),c.length||(c=d(".property-section:last .kbs:first",
a)),c.length||(c=d(".type-section:last .kbs:first",a)),c.length||(c=d(".domain-section:last .kbs:first",a)),c;var g=c.closest(".domain-section"),f=c.closest(".type-section"),h=c.closest(".property-section");return c.closest(".data-section").length?(c=c.prev(".kbs"),c.length?c:h.find(".kbs:first")):h.length?(c=h.prev(".property-section").find(".kbs:last"),c.length?c:f.find(".kbs:first")):f.length?(c=f.prev(".type-section").find(".kbs:last"),c.length?c:g.find(".kbs:first")):g.get(0)===b.get(0)?e.find(".kbs:last"):
g.prev(".domain-section").find(".kbs:last")};this.edit=function(){this.get_current().trigger("edit")};var h=this;d(document).unbind(".kbs").bind("keydown.kbs",function(a){var b=a.target;if(b==document.body||b==document||b==window||b==d("html")[0])b=a.keyCode,68===b?a.shiftKey?A():u():84===b?a.shiftKey?p():B():80===b?a.shiftKey?z():t():74===b?h.next():75===b?h.prev():69===b&&h.edit()})}})(jQuery);
(function(d,f){var a=window.propbox={init:function(b,e){e=d.extend({lang:"/lang/en"},e);if(!e.base_ajax_url)throw Error("base_ajax_url required in propbox options");if(!e.base_static_url)throw Error("base_static_url required in propbox options");if(!e.id)throw Error("topic id required in propbox options");if(!e.lang)throw Error("lang required in propbox options");a.options=e;a.kbs=new f(b);a.kbs.set_next(a.kbs.get_current(),d(".kbs:visible:first",b,!0));d(".kbs",b).live("click",function(){var b=a.kbs.get_current();
a.kbs.set_next(b,d(this),!0)}).live("edit",function(){var a=d(this).find(".headmenu:first").data("submenu");a&&d("li:first a:first",a).click()});a.init_menus(b)},init_menus:function(b,e){b=d(b||document);e&&d(".nicemenu",b).nicemenu();(b&&b.is(".data-row")?b:d(".data-row",b)).hover(a.row_menu_hoverover,a.row_menu_hoverout);d(".nicemenu .headmenu",b).add(d(".nicemenu .default-action",b)).click("click",function(){if(a.kbs){var b=a.kbs.get_current();b&&a.kbs.set_next(b,d(this).parents(".kbs:first"),
!0)}return!1})},row_menu_hoverover:function(){var b=d(this);a.row_menu_hoverover.timeout=setTimeout(function(){b.addClass("row-hover")},300)},row_menu_hoverout:function(){clearTimeout(a.row_menu_hoverover.timeout);d(this).removeClass("row-hover")},get_script:function(b,e){var g=a.get_script.cache;g||(g=a.get_script.cache={});var f=g[b];f?1===f.state?f.callbacks.push(e):4===f.state&&e():(f=g[b]={state:0,callbacks:[e]},d.ajax({url:a.options.base_static_url+b,dataType:"script",beforeSend:function(){f.state=
1},success:function(){f.state=4;d.each(f.callbacks,function(a,b){b()})},error:function(){f.state=-1}}))},prop_edit:function(b,e){var f=d(b).parents(".submenu").data("headmenu").parents(".property-section").find(".data-section .data-row:first:visible .nicemenu:first .headmenu:first a");f.length?f.click():a.prop_add(b,e);return!1},prop_add:function(b,e){var f=d(b).parents(".submenu").data("headmenu").parents(".property-section");a.get_script("/propbox-edit.mf.js",function(){a.edit.prop_add_begin(f,
e)});return!1},value_edit:function(b){var e=d(b).parents(".submenu").data("headmenu").parents(".data-row:first"),f=e.parents(".property-section");a.get_script("/propbox-edit.mf.js",function(){a.edit.value_edit_begin(f,e)});return!1},value_delete:function(b){var e=d(b).parents(".submenu").data("headmenu").parents(".data-row:first"),f=e.parents(".property-section");a.get_script("/propbox-edit.mf.js",function(){a.edit.value_delete_begin(f,e)});return!1},close_message:function(a){d(a).parents(".row-msg:first").remove();
return!1}}})(jQuery,window.kbs);
(function(d,f,a){var b=f.i18n_tab={init:function(){d("#i18n-table").fixedcolumn();a.init_menus()},add_name:function(a,g){var m=d(a).parents(".data-row:first");f.get_script(f.h.static_url("i18n-edit.mf.js"),function(){b.edit.add_name_begin(m,g)});return!1},edit_name:function(a,g,m){var o=d(a).parents(".submenu").data("headmenu").parents(".data-row:first");f.get_script(f.h.static_url("i18n-edit.mf.js"),function(){b.edit.edit_name_begin(o,g,m)});return!1},delete_name:function(a,g,m){var o=d(a).parents(".submenu").data("headmenu").parents(".data-row:first");
f.get_script(f.h.static_url("i18n-edit.mf.js"),function(){b.edit.delete_name_begin(o,g,m)});return!1}};d(b.init)})(jQuery,window.freebase,window.propbox);
