
/*
 * Copyright 2012, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Additional Licenses for Third Party components can be found here:
 * http://wiki.freebase.com/wiki/Freebase_Site_License
 *
 */
(function(b,f){if(!("console"in window)){var d=window.console={};d.log=d.warn=d.error=d.debug=function(){}}b(function(){var a=b("<div>");b(document.body).append(a);var c=setTimeout(function(){if(b.cleanData){var g=b.cleanData;b.cleanData=function(h){for(var j=0,l;(l=h[j])!=null;j++)b(l).triggerHandler("remove");g(h)}}else{var k=b.fn.remove;b.fn.remove=function(h,j){return this.each(function(){if(!j)if(!h||b.filter(h,[this]).length)b("*",this).add([this]).each(function(){b(this).triggerHandler("remove")});
return k.call(b(this),h,j)})}}},1);a.bind("remove",function(){clearTimeout(c)});a.remove()});var e={key:1,filter:1,spell:1,exact:1,lang:1,scoring:1,prefixed:1,stemmed:1,format:1,mql_output:1};b.suggest=function(a,c){b.fn[a]=function(g){this.length||console.warn("Suggest: invoked on empty element set");return this.each(function(){if(this.nodeName)if(this.nodeName.toUpperCase()==="INPUT")this.type&&this.type.toUpperCase()!=="TEXT"&&console.warn("Suggest: unsupported INPUT type: "+this.type);else console.warn("Suggest: unsupported DOM element: "+
this.nodeName);var k=b.data(this,a);k&&k._destroy();b.data(this,a,new b.suggest[a](this,g))._init()})};b.suggest[a]=function(g,k){var h=this,j=this.options=b.extend(true,{},b.suggest.defaults,b.suggest[a].defaults,k),l=j.css_prefix=j.css_prefix||"",m=j.css;this.name=a;b.each(m,function(n){m[n]=l+m[n]});j.ac_param={};b.each(e,function(n){var q=j[n];q===null||q===""||(j.ac_param[n]=q)});this._status={START:"",LOADING:"",SELECT:"",ERROR:""};if(j.status&&j.status instanceof Array&&j.status.length>=3){this._status.START=
j.status[0]||"";this._status.LOADING=j.status[1]||"";this._status.SELECT=j.status[2]||"";if(j.status.length===4)this._status.ERROR=j.status[3]||""}var p=this.status=b('<div style="display:none;">').addClass(m.status),r=this.list=b("<ul>").addClass(m.list),o=this.pane=b('<div style="display:none;" class="fbs-reset">').addClass(m.pane);o.append(p).append(r);if(j.parent)b(j.parent).append(o);else{o.css("position","absolute");j.zIndex&&o.css("z-index",j.zIndex);b(document.body).append(o)}o.bind("mousedown",
function(n){h.input.data("dont_hide",true);n.stopPropagation()}).bind("mouseup",function(n){h.input.data("dont_hide")&&h.input.focus();h.input.removeData("dont_hide");n.stopPropagation()}).bind("click",function(n){n.stopPropagation();if(n=h.get_selected()){h.onselect(n,true);h.hide_all()}});r.hover(function(n){h.hoverover_list(n)},function(n){h.hoverout_list(n)});this.input=b(g).attr("autocomplete","off").unbind(".suggest").bind("remove.suggest",function(){h._destroy()}).bind("keydown.suggest",function(n){h.keydown(n)}).bind("keypress.suggest",
function(n){h.keypress(n)}).bind("keyup.suggest",function(n){h.keyup(n)}).bind("blur.suggest",function(n){h.blur(n)}).bind("textchange.suggest",function(){h.textchange()}).bind("focus.suggest",function(n){h.focus(n)}).bind(b.browser.msie?"paste.suggest":"input.suggest",function(){clearTimeout(h.paste_timeout);h.paste_timeout=setTimeout(function(){h.textchange()},0)});this.onresize=function(){h.invalidate_position();if(o.is(":visible")){h.position();if(j.flyout&&h.flyoutpane&&h.flyoutpane.is(":visible")){var n=
h.get_selected();n&&h.flyout_position(n)}}};b(window).bind("resize.suggest",this.onresize).bind("scroll.suggest",this.onresize)};b.suggest[a].prototype=b.extend({},b.suggest.prototype,c)};b.suggest.prototype={_init:function(){},_destroy:function(){this.pane.remove();this.list.remove();this.input.unbind(".suggest");b(window).unbind("resize.suggest",this.onresize).unbind("scroll.suggest",this.onresize);this.input.removeData("data.suggest")},invalidate_position:function(){self._position=null},status_start:function(){this.hide_all();
this.status.siblings().hide();if(this._status.START){this.status.text(this._status.START).show();if(!this.pane.is(":visible")){this.position();this.pane_show()}}this._status.LOADING&&this.status.removeClass("loading")},status_loading:function(){this.status.siblings().show();if(this._status.LOADING){this.status.addClass("loading").text(this._status.LOADING).show();if(!this.pane.is(":visible")){this.position();this.pane_show()}}else this.status.hide()},status_select:function(){this.status.siblings().show();
this._status.SELECT?this.status.text(this._status.SELECT).show():this.status.hide();this._status.LOADING&&this.status.removeClass("loading")},status_error:function(){this.status.siblings().show();this._status.ERROR?this.status.text(this._status.ERROR).show():this.status.hide();this._status.LOADING&&this.status.removeClass("loading")},focus:function(a){this.input.val()===""?this.status_start():this.focus_hook(a)},focus_hook:function(){if(!this.input.data("data.suggest")&&!this.pane.is(":visible")&&
b("."+this.options.css.item,this.list).length){this.position();this.pane_show()}},keydown:function(a){var c=a.keyCode;if(c===9)this.tab(a);else if(c===38||c===40)a.shiftKey||a.preventDefault()},keypress:function(a){var c=a.keyCode;if(c===38||c===40)a.shiftKey||a.preventDefault();else c===13&&this.enter(a)},keyup:function(a){var c=a.keyCode;if(c===38){a.preventDefault();this.up(a)}else if(c===40){a.preventDefault();this.down(a)}else if(a.ctrlKey&&c===77)b(".fbs-more-link",this.pane).click();else if(b.suggest.is_char(a)){clearTimeout(this.keypress.timeout);
var g=this;this.keypress.timeout=setTimeout(function(){g.textchange()},0)}else c===27&&this.escape(a);return true},blur:function(){if(!this.input.data("dont_hide")){this.input.data("data.suggest");this.hide_all()}},tab:function(a){if(!(a.shiftKey||a.metaKey||a.ctrlKey)){a=this.options;a=this.pane.is(":visible")&&b("."+a.css.item,this.list).length;var c=this.get_selected();if(a&&c){this.onselect(c);this.hide_all()}}},enter:function(a){var c=this.options;if(this.pane.is(":visible"))if(a.shiftKey){this.shift_enter(a);
a.preventDefault()}else if(b("."+c.css.item,this.list).length)if(c=this.get_selected()){this.onselect(c);this.hide_all();a.preventDefault()}else{this.input.data("data.suggest");if(b("."+this.options.css.item+":visible",this.list).length){this.updown(false);a.preventDefault()}}},shift_enter:function(){},escape:function(){this.hide_all()},up:function(a){this.updown(true,a.ctrlKey||a.shiftKey)},down:function(a){this.updown(false,null,a.ctrlKey||a.shiftKey)},updown:function(a,c,g){var k=this.options.css,
h=this.list;if(this.pane.is(":visible")){var j=b("."+k.item+":visible",h);if(j.length){h=b(j[0]);j=b(j[j.length-1]);var l=this.get_selected()||[];clearTimeout(this.ignore_mouseover.timeout);this._ignore_mouseover=false;if(a)if(c)this._goto(h);else if(l.length)if(l[0]==h[0]){h.removeClass(k.selected);this.input.val(this.input.data("original.suggest"));this.hoverout_list()}else this._goto(l.prevAll("."+k.item+":visible:first"));else this._goto(j);else if(g)this._goto(j);else if(l.length)if(l[0]==j[0]){j.removeClass(k.selected);
this.input.val(this.input.data("original.suggest"));this.hoverout_list()}else this._goto(l.nextAll("."+k.item+":visible:first"));else this._goto(h)}}else a||this.textchange()},_goto:function(a){a.trigger("mouseover.suggest");var c=a.data("data.suggest");this.input.val(c?c.name:this.input.data("original.suggest"));this.scroll_to(a)},scroll_to:function(a){var c=this.list,g=c.scrollTop(),k=g+c.innerHeight(),h=a.outerHeight();a=a.prevAll().length*h;h=a+h;if(a<g){this.ignore_mouseover();c.scrollTop(a)}else if(h>
k){this.ignore_mouseover();c.scrollTop(g+h-k)}},textchange:function(){this.input.removeData("data.suggest");this.input.trigger("fb-textchange",this);var a=this.input.val();if(a==="")this.status_start();else{this.status_loading();this.request(a)}},request:function(){},response:function(a){if(a){"cost"in a&&this.trackEvent(this.name,"response","cost",a.cost);if(this.check_response(a)){var c=[];if(b.isArray(a))c=a;else if("result"in a)c=a.result;var g=b.map(arguments,function(m){return m});this.response_hook.apply(this,
g);var k=null,h=this,j=this.options;b.each(c,function(m,p){if(!p.id&&p.mid)p.id=p.mid;var r=h.create_item(p,a).bind("mouseover.suggest",function(o){h.mouseover_item(o)});r.data("data.suggest",p);h.list.append(r);if(m===0)k=r});this.input.data("original.suggest",this.input.val());if(b("."+j.css.item,this.list).length===0&&j.nomatch){c=b('<li class="fbs-nomatch">');if(typeof j.nomatch==="string")c.text(j.nomatch);else{j.nomatch.title&&c.append(b('<em class="fbs-nomatch-text">').text(j.nomatch.title));
j.nomatch.heading&&c.append(b("<h3>").text(j.nomatch.heading));if((j=j.nomatch.tips)&&j.length){var l=b('<ul class="fbs-search-tips">');b.each(j,function(m,p){l.append(b("<li>").text(p))});c.append(l)}}c.bind("click.suggest",function(m){m.stopPropagation()});this.list.append(c)}g.push(k);this.show_hook.apply(this,g);this.position();this.pane_show()}}},pane_show:function(){var a=false;if(b("> li",this.list).length)a=true;a||this.pane.children(":not(."+this.options.css.list+")").each(function(){if(b(this).css("display")!=
"none"){a=true;return false}});if(a)if(this.options.animate){var c=this;this.pane.slideDown("fast",function(){c.input.trigger("fb-pane-show",c)})}else{this.pane.show();this.input.trigger("fb-pane-show",this)}else{this.pane.hide();this.input.trigger("fb-pane-hide",this)}},create_item:function(a){var c=this.options.css,g=b("<li>").addClass(c.item);a=b("<label>").text(a.name);g.append(b("<div>").addClass(c.item_name).append(a));return g},mouseover_item:function(a){if(!this._ignore_mouseover){a=a.target;
if(a.nodeName.toLowerCase()!=="li")a=b(a).parents("li:first");var c=b(a),g=this.options.css;b("."+g.item,this.list).each(function(){this!==c[0]&&b(this).removeClass(g.selected)});if(!c.hasClass(g.selected)){c.addClass(g.selected);this.mouseover_item_hook(c)}}},mouseover_item_hook:function(){},hoverover_list:function(){},hoverout_list:function(){},check_response:function(){return true},response_hook:function(){this.list.empty()},show_hook:function(){this.status_select()},position:function(){var a=
this.pane,c=this.options;if(!c.parent){if(!self._position){var g=this.input,k=g.offset(),h=g.outerWidth(true),j=g.outerHeight(true);k.top+=j;var l=a.outerWidth(),m=a.outerHeight(),p=k.top+m/2,r=b(window).scrollLeft();g=b(window).scrollTop();var o=b(window).width(),n=b(window).height()+g,q=true;if("left"==c.align)q=true;else if("right"==c.align)q=false;else if(k.left>r+o/2)q=false;if(!q){q=k.left-(l-h);if(q>r)k.left=q}if(p>n){c=k.top-j-m;if(c>g)k.top=c}this._position=k}a.css({top:this._position.top,
left:this._position.left})}},ignore_mouseover:function(){this._ignore_mouseover=true;var a=this;this.ignore_mouseover.timeout=setTimeout(function(){a.ignore_mouseover_reset()},1E3)},ignore_mouseover_reset:function(){this._ignore_mouseover=false},get_selected:function(){var a=null,c=this.options.css.selected;b("li",this.list).each(function(){var g=b(this);if(g.hasClass(c)&&g.is(":visible")){a=g;return false}});return a},onselect:function(a){var c=a.data("data.suggest");if(c){this.input.val(c.name).data("data.suggest",
c).trigger("fb-select",c);this.trackEvent(this.name,"fb-select","index",a.prevAll().length)}},trackEvent:function(a,c,g,k){this.input.trigger("fb-track-event",{category:a,action:c,label:g,value:k})},hide_all:function(){this.pane.hide();this.input.trigger("fb-pane-hide",this)}};b.extend(b.suggest,{defaults:{status:["Start typing to get suggestions...","Searching...","Select an item from the list:","Sorry, something went wrong. Please try again later"],soft:false,nomatch:"no matches",css:{pane:"fbs-pane",
list:"fbs-list",item:"fbs-item",item_name:"fbs-item-name",selected:"fbs-selected",status:"fbs-status"},css_prefix:null,parent:null,animate:false,zIndex:null},use_jsonp:function(a){if(!a)return false;var c=window.location.href;c=c.substr(0,c.length-window.location.pathname.length);if(c===a)return false;return true},strongify:function(a,c){var g,k=a.toLowerCase().indexOf(c.toLowerCase());if(k>=0){var h=c.length;g=document.createTextNode(a.substring(0,k));var j=b("<strong>").text(a.substring(k,k+h));
k=document.createTextNode(a.substring(k+h));g=b("<div>").append(g).append(j).append(k)}else g=b("<div>").text(a);return g},keyCode:{CAPS_LOCK:20,CONTROL:17,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,INSERT:45,LEFT:37,NUMPAD_ENTER:108,PAGE_DOWN:34,PAGE_UP:33,RIGHT:39,SHIFT:16,SPACE:32,TAB:9,UP:38,OPTION:18,APPLE:224},is_char:function(a){if(a.type==="keypress")if((a.metaKey||a.ctrlKey)&&a.charCode===118)return true;else{if("isChar"in a)return a.isChar}else{var c=b.suggest.keyCode.not_char;if(!c){c={};
b.each(b.suggest.keyCode,function(g,k){c[""+k]=1});b.suggest.keyCode.not_char=c}return!(""+a.keyCode in c)}},parse_input:function(a){for(var c=/(\S+)\:(?:\"([^\"]+)\"|(\S+))/g,g=a,k=[],h={},j=c.exec(a);j;){if(j[1]in e)h[j[1]]=b.isEmptyObject(j[2])?j[3]:j[2];else k.push(j[0]);g=g.replace(j[0],"");j=c.exec(a)}g=b.trim(g.replace(/\s+/g," "));return[g,k,h]},mqlkey_fast:/^[_A-Za-z0-9][A-Za-z0-9_-]*$/,mqlkey_slow:/^(?:[A-Za-z0-9]|\$[A-F0-9]{4})(?:[A-Za-z0-9_-]|\$[A-F0-9]{4})*$/,check_mql_key:function(a){if(b.suggest.mqlkey_fast.test(a))return true;
else if(b.suggest.mqlkey_slow.test(a))return true;return false},check_mql_id:function(a){if(a.indexOf("/")===0){a=a.split("/");a.shift();if(!(a.length==1&&a[0]===""))for(var c=0,g=a.length;c<g;c++)if(!b.suggest.check_mql_key(a[c]))return false;return true}else return false}});var i={_destroy:b.suggest.prototype._destroy,show_hook:b.suggest.prototype.show_hook};b.suggest("suggest",{_init:function(){var a=this,c=this.options;if(c.flyout_service_url==null)c.flyout_service_url=c.service_url;this.flyout_url=
c.flyout_service_url;if(c.flyout_service_path)this.flyout_url+=c.flyout_service_path;this.jsonp=true;this.jsonp_flyout=b.suggest.use_jsonp(c.flyout_service_url);if(!b.suggest.cache)b.suggest.cache={};if(c.flyout){this.flyoutpane=b('<div style="display:none;" class="fbs-reset">').addClass(c.css.flyoutpane);if(c.flyout_parent)b(c.flyout_parent).append(this.flyoutpane);else{this.flyoutpane.css("position","absolute");c.zIndex&&this.flyoutpane.css("z-index",c.zIndex);b(document.body).append(this.flyoutpane)}this.flyoutpane.hover(function(g){a.hoverover_list(g)},
function(g){a.hoverout_list(g)}).bind("mousedown.suggest",function(g){g.stopPropagation();a.pane.click()});if(!b.suggest.flyout)b.suggest.flyout={};if(!b.suggest.flyout.cache)b.suggest.flyout.cache={}}},_destroy:function(){i._destroy.call(this);this.flyoutpane&&this.flyoutpane.remove();this.input.removeData("request.count.suggest");this.input.removeData("flyout.request.count.suggest")},shift_enter:function(){if(this.options.suggest_new){this.suggest_new();this.hide_all()}},hide_all:function(){this.pane.hide();
this.flyoutpane&&this.flyoutpane.hide();this.input.trigger("fb-pane-hide",this);this.input.trigger("fb-flyoutpane-hide",this)},request:function(a,c){var g=this,k=this.options;if(this.ac_xhr){!this.jsonp&&this.ac_xhr.abort&&this.ac_xhr.abort();this.ac_xhr=null}var h=a,j=k.ac_param.filter||[],l=null;if(b.type(j)==="string")j=[j];j=j.slice();if(k.advanced){var m=b.suggest.parse_input(h);h=m[0];m[1].length&&j.push("(all "+m[1].join(" ")+")");l=m[2];if(b.suggest.check_mql_id(h)){j.push('(all mid:"'+h+
'")');h=""}}m={};m[k.query_param_name]=h;if(c)m.cursor=c;b.extend(m,k.ac_param,l);if(j.length)m.filter=j;var p=k.service_url+k.service_path+"?"+b.param(m,true);if(h=b.suggest.cache[p])this.response(h,c?c:-1,true);else{clearTimeout(this.request.timeout);var r={url:k.service_url+k.service_path,data:m,traditional:true,beforeSend:function(){var o=g.input.data("request.count.suggest")||0;o||g.trackEvent(g.name,"start_session");o+=1;g.trackEvent(g.name,"request","count",o);g.input.data("request.count.suggest",
o)},success:function(o){b.suggest.cache[p]=o;o.prefix=a;g.response(o,c?c:-1)},error:function(o){g.status_error();g.trackEvent(g.name,"request","error",{url:this.url,response:o?o.responseText:""});g.input.trigger("fb-error",Array.prototype.slice.call(arguments))},complete:function(o){o&&g.trackEvent(g.name,"request","tid",o.getResponseHeader("X-Metaweb-TID"))},dataType:g.jsonp?"jsonp":"json",cache:true};this.request.timeout=setTimeout(function(){g.ac_xhr=b.ajax(r)},k.xhr_delay)}},create_item:function(a,
c){var g=this.options.css,k=b("<li>").addClass(g.item),h=b("<label>").append(b.suggest.strongify(a.name||a.id,c.prefix)),j=b("<div>").addClass(g.item_name).append(h);a.under&&b(":first",h).append(b("<small>").text(" ("+a.under+")"));k.append(j);h=a.notable;g=b("<div>").addClass(g.item_type);if(h&&h.name)g.text(h.name);else a.id&&g.text(a.id);j.prepend(g);return k},mouseover_item_hook:function(a){a=a.data("data.suggest");this.options.flyout&&a&&this.flyout_request(a)},check_response:function(a){return a.prefix===
this.input.val()},response_hook:function(a,c){this.flyoutpane&&this.flyoutpane.hide();c>0?b(".fbs-more",this.pane).remove():this.list.empty()},show_hook:function(a,c,g){i.show_hook.apply(this,[a]);var k=this.options,h=this,j=this.pane,l=this.list,m=a.result,p=b(".fbs-more",j),r=b(".fbs-suggestnew",j);b(".fbs-status",j);var o=a.correction;if(o&&o.length){var n=b('<a class="fbs-spell-link" href="#">').append(o[0]).bind("click.suggest",function(q){q.preventDefault();q.stopPropagation();h.input.val(o[0]).trigger("textchange")});
h.status.empty().append("Search instead for ").append(n).show()}if(m&&m.length&&"cursor"in a){if(!p.length){m=b('<a class="fbs-more-link" href="#" title="(Ctrl+m)">view more</a>');p=b('<div class="fbs-more">').append(m);m.bind("click.suggest",function(q){q.preventDefault();q.stopPropagation();q=b(this).parent(".fbs-more");h.more(q.data("cursor.suggest"))});l.after(p)}p.data("cursor.suggest",a.cursor);p.show()}else p.remove();if(k.suggest_new){if(!r.length){a=b('<button class="fbs-suggestnew-button">');
a.text(k.suggest_new);r=b('<div class="fbs-suggestnew">').append('<div class="fbs-suggestnew-description">Your item not in the list?</div>').append(a).append('<span class="fbs-suggestnew-shortcut">(Shift+Enter)</span>').bind("click.suggest",function(q){q.stopPropagation();h.suggest_new(q)});j.append(r)}r.show()}else r.remove();if(g&&g.length&&c>0){c=g.prevAll().length*g.outerHeight();l.scrollTop();l.animate({scrollTop:c},"slow",function(){g.trigger("mouseover.suggest")})}},suggest_new:function(){var a=
this.input.val();if(a!==""){this.input.data("data.suggest",a).trigger("fb-select-new",a);this.trackEvent(this.name,"fb-select-new","index","new");this.hide_all()}},more:function(a){if(a){var c=this.input.data("original.suggest");c!==null&&this.input.val(c);this.request(this.input.val(),a);this.trackEvent(this.name,"more","cursor",a)}return false},flyout_request:function(a){var c=this;if(this.flyout_xhr){!this.jsonp_flyout&&this.flyout_xhr.abort&&this.flyout_xhr.abort();this.flyout_xhr=null}var g=
this.options,k=this.flyoutpane.data("data.suggest");if(k&&a.id===k.id){if(!this.flyoutpane.is(":visible")){this.flyout_position(this.get_selected());this.flyoutpane.show();this.input.trigger("fb-flyoutpane-show",this)}}else if((k=b.suggest.flyout.cache[a.id])&&k.id&&k.html)this.flyout_response(k);else{var h=a.id,j={url:this.flyout_url.replace(/\$\{id\}/g,a.id),traditional:true,data:{},beforeSend:function(){var l=c.input.data("flyout.request.count.suggest")||0;l+=1;c.trackEvent(c.name,"flyout.request",
"count",l);c.input.data("flyout.request.count.suggest",l)},success:function(l){l=c.jsonp_flyout?l:{id:h,html:l};b.suggest.flyout.cache[l.id]=l;c.flyout_response(l)},error:function(l){c.trackEvent(c.name,"flyout","error",{url:this.url,response:l?l.responseText:""})},complete:function(l){l&&c.trackEvent(c.name,"flyout","tid",l.getResponseHeader("X-Metaweb-TID"))},dataType:c.jsonp_flyout?"jsonp":"html",cache:true};if(g.ac_param.lang)j.data.lang=g.ac_param.lang;clearTimeout(this.flyout_request.timeout);
this.flyout_request.timeout=setTimeout(function(){c.flyout_xhr=b.ajax(j)},g.xhr_delay);this.input.trigger("fb-request-flyout",j)}},flyout_response:function(a){var c=this.pane,g=this.get_selected()||[];if(c.is(":visible")&&g.length)if((c=g.data("data.suggest"))&&a.id===c.id&&a.html){this.flyoutpane.html(a.html);this.flyout_position(g);this.flyoutpane.show().data("data.suggest",c);this.input.trigger("fb-flyoutpane-show",this)}},flyout_position:function(a){if(!this.options.flyout_parent){var c=this.pane,
g=this.flyoutpane,k=this.options.css,h=f,j={top:parseInt(g.css("top"),10),left:parseInt(g.css("left"),10)},l=c.offset(),m=c.outerWidth(),p=g.outerHeight(),r=g.outerWidth();if(this.options.flyout==="bottom"){h=l;m=this.input.offset();if(l.top<m.top)h.top-=p;else h.top+=c.outerHeight();g.addClass(k.flyoutpane+"-bottom")}else{h=a.offset();a=a.outerHeight();h.left+=m;var o=h.left+r;c=b(document.body).scrollLeft();var n=b(window).width()+c;h.top=h.top+a-p;if(h.top<l.top)h.top=l.top;if(o>n){l=h.left-(m+
r);if(l>c)h.left=l}g.removeClass(k.flyoutpane+"-bottom")}h.top===j.top&&h.left===j.left||g.css({top:h.top,left:h.left})}},hoverout_list:function(){this.flyoutpane&&!this.get_selected()&&this.flyoutpane.hide()}});b.extend(b.suggest.suggest,{defaults:{filter:null,spell:"always",exact:false,scoring:null,lang:null,key:null,prefixed:true,stemmed:null,format:"ac",advanced:true,query_param_name:"query",service_url:"https://www.googleapis.com",service_path:"/freebase/v1/search",align:null,flyout:true,flyout_service_url:"http://dev.freebase.com",
flyout_service_path:"/flyout?id=${id}",flyout_parent:null,suggest_new:null,nomatch:{title:"No suggested matches",heading:"Tips on getting better suggestions:",tips:["Enter more or fewer characters","Add words related to your original search","Try alternate spellings","Check your spelling"]},css:{item_type:"fbs-item-type",flyoutpane:"fbs-flyout-pane"},xhr_delay:200}});document.createElement("input")})(jQuery);
(function(b){b.fn.extend({simulate:function(f,d){return this.each(function(){var e=b.extend({},b.simulate.defaults,d||{});new b.simulate(this,f,e)})}});b.simulate=function(f,d,e){this.target=f;this.options=e;/^drag$/.test(d)?this[d].apply(this,[this.target,e]):this.simulateEvent(f,d,e)};b.extend(b.simulate.prototype,{simulateEvent:function(f,d,e){var i=this.createEvent(d,e);this.dispatchEvent(f,d,i,e);return i},createEvent:function(f,d){if(/^mouse(over|out|down|up|move)|(dbl)?click$/.test(f))return this.mouseEvent(f,
d);else if(/^key(up|down|press)$/.test(f))return this.keyboardEvent(f,d)},mouseEvent:function(f,d){var e,i=b.extend({bubbles:true,cancelable:f!="mousemove",view:window,detail:0,screenX:0,screenY:0,clientX:0,clientY:0,ctrlKey:false,altKey:false,shiftKey:false,metaKey:false,button:0,relatedTarget:undefined},d);b(i.relatedTarget);if(b.isFunction(document.createEvent)){e=document.createEvent("MouseEvents");e.initMouseEvent(f,i.bubbles,i.cancelable,i.view,i.detail,i.screenX,i.screenY,i.clientX,i.clientY,
i.ctrlKey,i.altKey,i.shiftKey,i.metaKey,i.button,i.relatedTarget||document.body.parentNode)}else if(document.createEventObject){e=document.createEventObject();b.extend(e,i);e.button={0:1,1:4,2:2}[e.button]||e.button}return e},keyboardEvent:function(f,d){var e,i=b.extend({bubbles:true,cancelable:true,view:window,ctrlKey:false,altKey:false,shiftKey:false,metaKey:false,keyCode:0,charCode:0},d);if(b.isFunction(document.createEvent))try{e=document.createEvent("KeyEvents");e.initKeyEvent(f,i.bubbles,i.cancelable,
i.view,i.ctrlKey,i.altKey,i.shiftKey,i.metaKey,i.keyCode,i.charCode)}catch(a){e=document.createEvent("Events");e.initEvent(f,i.bubbles,i.cancelable);b.extend(e,{view:i.view,ctrlKey:i.ctrlKey,altKey:i.altKey,shiftKey:i.shiftKey,metaKey:i.metaKey,keyCode:i.keyCode,charCode:i.charCode})}else if(document.createEventObject){e=document.createEventObject();b.extend(e,i)}if(b.browser.msie||b.browser.opera){e.keyCode=i.charCode>0?i.charCode:i.keyCode;e.charCode=undefined}return e},dispatchEvent:function(f,
d,e){if(f.dispatchEvent)f.dispatchEvent(e);else f.fireEvent&&f.fireEvent("on"+d,e);return e},drag:function(){var f=this.findCenter(this.target),d=this.options,e=Math.floor(f.x);f=Math.floor(f.y);var i=d.dx||0;d=d.dy||0;var a=this.target,c={clientX:e,clientY:f};this.simulateEvent(a,"mousedown",c);c={clientX:e+1,clientY:f+1};this.simulateEvent(document,"mousemove",c);c={clientX:e+i,clientY:f+d};this.simulateEvent(document,"mousemove",c);this.simulateEvent(document,"mousemove",c);this.simulateEvent(a,
"mouseup",c)},findCenter:function(f){f=b(this.target);var d=f.offset();return{x:d.left+f.outerWidth()/2,y:d.top+f.outerHeight()/2}}});b.extend(b.simulate,{defaults:{speed:"sync"},VK_TAB:9,VK_ENTER:13,VK_ESC:27,VK_PGUP:33,VK_PGDN:34,VK_END:35,VK_HOME:36,VK_LEFT:37,VK_UP:38,VK_RIGHT:39,VK_DOWN:40})})(jQuery);var test_input1,test_input2,test_input3,test_input4,TIMEOUT_DELAY=5E3;$(function(){test_input1=$("#test1");test_input2=$("#test2");test_input3=$("#test3");test_input4=$("#test4")});
var module_options={setup:function(){},teardown:function(){$.suggest.cache={};if($.suggest.flyout)$.suggest.flyout.cache={};$.each([test_input1,test_input2,test_input3,test_input4],function(b,f){f.unbind();var d=get_instance(f);d&&d._destroy();f.val("")})}},default_options={service_path:"/freebase/v1/search",key:"AIzaSyBij3tRJN2VdWiLQN48-BmPFjNWpHe7MQE",flyout_service_url:"",advanced:true},test_value="bob dyla",bob_dylan_mid="/m/01vrncs",position_threshold=10;
function get_instance(b){b=b||test_input1;return b.data("suggest")}function simulate_keypress(b,f){var d=f;if(typeof d!=="object")d={keyCode:d};b.simulate("keydown",d);b.simulate("keyup",d);b.simulate("keypress",d)}function simulate_mouseclick(b){b.simulate("mousedown").simulate("mouseup").simulate("mouseclick").click()}
$(function(){function b(d){var e=get_instance();ok(e.pane.hasClass(d.pane),"css.pane");ok(e.status.hasClass(d.status),"css.status");ok(e.list.hasClass(d.list),"css.list");ok(e.flyoutpane.hasClass(d.flyoutpane),"css.flyoutpane");stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",function(){if($(">li",e.list).length){$(">li",e.list).each(function(){$(this).hasClass(d.item);var i=$("."+d.item_name,this);equals(i.length,1);i=$("."+d.item_type,i);equals(i.length,1)});start()}}).val("css").trigger("textchange")}
function f(d,e,i,a){d=$.extend({},default_options,d);test_input1.suggest(d);var c=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",function(){var g=false,k;k=typeof i==="function"?function(j){return i(j)}:function(j){return j.mid===i};var h=$(">li",c.list);if(h.length){h.each(function(){var j=$(this).data("data.suggest");if(g=k(j))return false});ok(g);start()}else if(a){ok(a());start()}}).val(e).trigger("textchange")}module("options",module_options);test("css_prefix",function(){var d=
$.extend({},default_options,{css_prefix:"test-"});test_input1.suggest(d);var e={};d=$.extend(true,{},$.suggest.defaults.css,$.suggest.suggest.defaults.css);$.each(d,function(i,a){e[i]="test-"+a});b(e)});test("css",function(){var d={pane:"my-pane",list:"my-list",item:"my-item",item_name:"my-item-name",selected:"my-selected",status:"my-status",item_type:"my-item-type",flyoutpane:"my-flyout-pane"},e=$.extend({},default_options,{css:d});test_input1.suggest(e);b(d)});test("parent",1,function(){var d=$('<div id="parent">');
$(document.body).append(d);var e=$.extend({},default_options,{parent:"#parent"});test_input1.suggest(e);var i=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",function(){if($(">li",i.list).length){equals(i.pane.parent()[0],d[0]);start()}}).val("bob dyl").trigger("textchange")});test("flyout_parent",1,function(){var d=$('<div id="flyout_parent">');$(document.body).append(d);var e=$.extend({},default_options,{flyout_parent:"#flyout_parent"});test_input1.suggest(e);var i=get_instance();
stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",function(){$("li:first",i.list).trigger("mouseover")}).bind("fb-flyoutpane-show",function(){equals(i.flyoutpane.parent()[0],d[0]);start()}).val("stephen colb").trigger("textchange")});test("status[0]",1,function(){var d=$.extend({},default_options,{status:["0","1","2","3"]});test_input1.suggest(d);d=get_instance();test_input1.val("").trigger("textchange");equals(d.status.text(),"0")});test("status[1]",1,function(){var d=$.extend({},default_options,
{status:["0","1","2","3"]});test_input1.suggest(d);d=get_instance();test_input1.val("obama").trigger("textchange");equals(d.status.text(),"1")});test("status[2]",1,function(){var d=$.extend({},default_options,{status:["0","1","2","3"]});test_input1.suggest(d);var e=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",function(){if($(">li",e.list).length){equals(e.status.text(),"2");start()}}).val("hillary cli").trigger("textchange")});test("status[3]",1,function(){var d=$.extend({},
default_options,{status:["0","1","2","3"]});test_input1.suggest(d);d=get_instance();d.status_error();equals(d.status.text(),"3")});test("zIndex",1,function(){var d=$.extend({},default_options,{zIndex:1E3});test_input1.suggest(d);var e=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",function(){equals(e.pane.css("z-index"),1E3);start()}).val("shohoku").trigger("textchange")});test("flyout=false",1,function(){var d=$.extend({},default_options,{flyout:false});test_input1.suggest(d);
var e=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",function(){if($(">li",e.list).length){$("li:first",e.list).trigger("mouseover");if(!e.flyoutpane){ok("flyout not shown");start()}}}).bind("fb-flyoutpane-show",function(){fail("flyout shown when flyout=false");start()}).val("avatar").trigger("textchange")});test("flyout=bottom",1,function(){var d=$.extend({},default_options,{flyout:"bottom"});test_input1.suggest(d);var e=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",
function(){$("li:first",e.list).trigger("mouseover")}).bind("fb-flyoutpane-show",function(){var i=e.pane.offset(),a=e.flyoutpane.offset();ok(Math.abs(a.top-(i.top+e.pane.height()))<position_threshold);start()}).val("avatar").trigger("textchange")});test("align=left",1,function(){var d=$.extend({},default_options,{align:"left"});test_input1.suggest(d);var e=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",function(){if($(">li",e.list).length){ok(Math.abs(e.pane.offset().left-test_input1.offset().left)<
position_threshold);start()}}).val("lady ga").trigger("textchange")});test("align=right",1,function(){var d=$.extend({},default_options,{align:"right"});test_input3.suggest(d);var e=get_instance(test_input3);stop(TIMEOUT_DELAY);test_input3.bind("fb-pane-show",function(){if($(">li",e.list).length){var i=e.pane.offset().left+e.pane.width(),a=test_input3.offset().left+test_input3.width();ok(Math.abs(i-a)<position_threshold);start()}}).val("jessica alb").trigger("textchange")});test("suggest_new",1,function(){var d=
$.extend({},default_options,{suggest_new:"suggest_new"});test_input1.suggest(d);var e=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",function(){if($(">li",e.list).length){equals($("button:first",e.pane).text(),"suggest_new");start()}}).val("aplusk").trigger("textchange")});$.each(["(any type:/music/artist)","(any type:/people/person type:/music/artist)","(all type:/music/artist)","(all type:/people/person type:/music/artist)","(should type:/music/artist)","(should type:/people/person)"],
function(d,e){test("filter="+e,1,function(){f({filter:e},bob_dylan_mid,bob_dylan_mid)})});test("lang [default]",function(){f(null,"/en/seoul",function(d){return d.name==="Seoul"})});test("lang=en",function(){f({lang:"en"},"/en/seoul",function(d){return d.name==="Seoul"})});test("lang=ko",function(){f({lang:"ko"},"/en/seoul",function(d){return d.name.indexOf("\uc11c\uc6b8")!==-1})});test("lang=es,ko",function(){f({lang:"es,ko"},"/en/cheong_wa_dae",function(d){return d.name==="\uccad\uc640\ub300"})});
test("spell=always",function(){var d=$.extend({},default_options,{spell:"always"});test_input1.suggest(d);var e=get_instance(),i=false;stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",function(){var a=$(">li",e.list);if(i&&a.length){ok(true,"Got spell correction results");start()}else if($(".fbs-spell-link",e.pane).length){ok(true,"Found spell/correction");$(".fbs-spell-link",e.pane).click();i=true}}).val("Bob Dylon").trigger("textchange")});test("exact [default]",function(){f(null,"Bob Dylon",
bob_dylan_mid)});test("exact=false",function(){f(null,"Bob Dylon",bob_dylan_mid)});test("exact=true",function(){f(null,"Bob Dylon",function(){return false},function(){return true})})});
$(function(){module("events",module_options);test("fb-pane-show",1,function(){test_input1.suggest(default_options);var b=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",function(){if($(">li",b.list).length){ok(true,"got fb-pane-show");start()}}).focus().val("bob dylan").trigger("textchange")});test("fb-flyoutpane-show",1,function(){test_input1.suggest(default_options);var b=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-flyoutpane-show",function(){ok(true,"got fb-flyoutpane-show");
start()}).bind("fb-pane-show",function(){$(">li",b.list).length&&$("li:first",b.list).simulate("mouseover")}).focus().val("bob dylan").trigger("textchange")});test("fb-select",2,function(){var b=$.extend({},default_options,{filter:"(any type:/music/artist)"});test_input1.suggest(b);var f=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-select",function(d,e){ok(e);equals(e.mid,bob_dylan_mid);start()}).bind("fb-pane-show",function(){if($(">li",f.list).length){$("li:first",f.list).simulate("mouseover");
simulate_keypress(test_input1,$.simulate.VK_ENTER)}}).focus().val(bob_dylan_mid).trigger("textchange")});test("fb-select-new",1,function(){var b=$.extend({},default_options,{suggest_new:"new"});test_input1.suggest(b);var f=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-select-new",function(d,e){equals(e,"bob dylan");start()}).bind("fb-pane-show",function(){$(">li",f.list).length&&$(".fbs-suggestnew",f.pane).click()}).focus().val("bob dylan").trigger("textchange")});test("fb-textchange",1,
function(){test_input1.suggest(default_options);stop(TIMEOUT_DELAY);test_input1.bind("fb-textchange",function(){ok(true,"got fb-textchange");start()}).focus();simulate_keypress(test_input1,68)})});
$(function(){function b(f,d){test("select: "+f,2,function(){var e=$.extend({},default_options,{filter:"(any type:/music/artist)"});test_input1.suggest(e);var i=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-select",function(a,c){ok(c);equals(c.mid,bob_dylan_mid);start()}).bind("fb-pane-show",function(){$(">li",i.list).length&&d()}).focus().val(bob_dylan_mid).trigger("textchange")})}module("ux",module_options);b("MOUSEOVER MOUSECLICK",function(){var f=get_instance();f=$("li:first",f.list).simulate("mouseover");
simulate_mouseclick(f)});b("MOUSEOVER ENTER",function(){var f=get_instance();$("li:first",f.list).simulate("mouseover");simulate_keypress(test_input1,$.simulate.VK_ENTER)});b("ENTER ENTER",function(){simulate_keypress(test_input1,$.simulate.VK_ENTER);simulate_keypress(test_input1,$.simulate.VK_ENTER)});b("DOWN ENTER",function(){simulate_keypress(test_input1,$.simulate.VK_DOWN);simulate_keypress(test_input1,$.simulate.VK_ENTER)});b("UP DOWN DOWN ENTER",function(){simulate_keypress(test_input1,$.simulate.VK_UP);
simulate_keypress(test_input1,$.simulate.VK_DOWN);simulate_keypress(test_input1,$.simulate.VK_DOWN);simulate_keypress(test_input1,$.simulate.VK_ENTER)});b("CTRL+UP ENTER",function(){simulate_keypress(test_input1,{keyCode:$.simulate.VK_UP,ctrlKey:true});simulate_keypress(test_input1,$.simulate.VK_ENTER)});b("CTRL+DOWN DOWN DOWN ENTER",function(){simulate_keypress(test_input1,{keyCode:$.simulate.VK_DOWN,ctrlKey:true});simulate_keypress(test_input1,$.simulate.VK_DOWN);simulate_keypress(test_input1,$.simulate.VK_DOWN);
simulate_keypress(test_input1,$.simulate.VK_ENTER)});test("select: flyout",2,function(){var f=$.extend({},default_options,{filter:"(any type:/music/artist)"});test_input1.suggest(f);var d=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-select",function(e,i){ok(i);equals(i.mid,bob_dylan_mid);start()}).bind("fb-flyoutpane-show",function(){simulate_mouseclick(d.flyoutpane)}).bind("fb-pane-show",function(){$(">li",d.list).length&&simulate_keypress(test_input1,$.simulate.VK_DOWN)}).focus().val(bob_dylan_mid).trigger("textchange")});
test("suggest_new: SHIFT+ENTER",1,function(){var f=$.extend({},default_options,{suggest_new:"new"});test_input1.suggest(f);var d=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-select-new",function(e,i){equals(i,"bob dylan");start()}).bind("fb-pane-show",function(){$(">li",d.list).length&&simulate_keypress(test_input1,{keyCode:$.simulate.VK_ENTER,shiftKey:true})}).focus().val("bob dylan").trigger("textchange")});test("more: CLICK",1,function(){var f=$.extend({},default_options,{filter:"(any type:/music/artist)"});
test_input1.suggest(f);var d=get_instance(),e=false,i=0;stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",function(){if(e){ok($(">li",d.list).length>i,"got more");start()}else if(i=$(">li",d.list).length){$(".fbs-more-link",d.pane).click();e=true}}).focus().val("bob dylan").trigger("textchange")});test("more: CTRL+M",1,function(){var f=$.extend({},default_options,{filter:"(any type:/music/artist)"});test_input1.suggest(f);var d=get_instance(),e=false,i=0;stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",
function(){if(e){ok($(">li",d.list).length>i,"got more");start()}else if(i=$(">li",d.list).length){simulate_keypress(test_input1,{keyCode:77,ctrlKey:true});e=true}}).focus().val("bob dylan").trigger("textchange")});test("cancel: ESC",2,function(){var f=$.extend({},default_options,{filter:"(any type:/music/artist)"});test_input1.suggest(f);var d=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",function(){if($(">li",d.list).length){ok(d.pane.is(":visible"),"pane visible");simulate_keypress(test_input1,
$.simulate.VK_ESC);ok(!d.pane.is(":visible"),"pane NOT visible");start()}}).focus().val("bob dylan").trigger("textchange")})});
$(function(){module("functional",module_options);test("remove",function(){var b=$.extend({},default_options,{type:"/music/artist"});test_input4.suggest(b);b=get_instance(test_input4);var f=b.pane,d=b.flyoutpane;ok(b,"suggest initialized");test_input4.remove();ok(!f.parent().is("body"),"suggest pane not removed");ok(!d.parent().is("body"),"suggest flyoutpane not removed")});test("flyout abort (CLI-10009)",function(){test_input1.suggest(default_options);var b=get_instance();stop(TIMEOUT_DELAY);var f;
test_input1.bind("fb-flyoutpane-show",function(){ok(true,"got fb-flyoutpane-show");ok(b.flyoutpane.html(),"got non-empty flyout pane");start()}).bind("fb-request-flyout",function(){clearTimeout(b.flyout_request.timeout);var d=f.data("data.suggest").id;$.suggest.flyout.cache[d]={id:d};test_input1.unbind("fb-request-flyout").trigger("textchange")}).bind("fb-pane-show",function(){if($(">li",b.list).length){f=$("li:first",b.list);f.simulate("mouseover")}}).focus().val("bob dylan").trigger("textchange")})});
$(function(){var b={teardown:module_options.teardown,response:$.suggest.suggest.prototype.response};module("xss",$.extend({},module_options,{teardown:function(){b.teardown.apply();$.suggest.suggest.prototype.response=b.response}}));test("script_injection",function(){test_input1.suggest(default_options);var f=get_instance();$.suggest.suggest.prototype.response=function(d){var e=d.result;if(e&&e.length)e[0].name="<script>$(document.body).append('<div id=\"xss\">XSS</div>')<\/script>";return b.response.apply(this,
arguments)};stop(TIMEOUT_DELAY);test_input1.bind("fb-select",function(d,e){ok(e);equals(e.name,"<script>$(document.body).append('<div id=\"xss\">XSS</div>')<\/script>");var i=$("#xss");ok(!i.length,"script injection!");start()}).bind("fb-pane-show",function(){if($(">li",f.list).length){$("li:first",f.list).simulate("mouseover");simulate_keypress(test_input1,$.simulate.VK_ENTER)}}).focus().val("bob dylan").trigger("textchange")});test("script_injection strongified",function(){test_input1.suggest(default_options);
var f=get_instance();$.suggest.suggest.prototype.response=function(d){var e=d.result;if(e&&e.length)e[0].name="bob dylan<script>$(document.body).append('<div id=\"xss\">XSS</div>')<\/script>";return b.response.apply(this,arguments)};stop(TIMEOUT_DELAY);test_input1.bind("fb-select",function(d,e){ok(e);equals(e.name,"bob dylan<script>$(document.body).append('<div id=\"xss\">XSS</div>')<\/script>");var i=$("#xss");ok(!i.length,"script injection!");start()}).bind("fb-pane-show",function(){if($(">li",
f.list).length){$("li:first",f.list).simulate("mouseover");simulate_keypress(test_input1,$.simulate.VK_ENTER)}}).focus().val("bob dylan").trigger("textchange")});test("link_injection",function(){test_input1.suggest(default_options);var f=get_instance();$.suggest.suggest.prototype.response=function(d){var e=d.result;if(e&&e.length)e[0].name='<a href="javascript:alert("XSS");">click me</a>';return b.response.apply(this,arguments)};stop(TIMEOUT_DELAY);test_input1.bind("fb-select",function(d,e){ok(e);
equals(e.name,'<a href="javascript:alert("XSS");">click me</a>');var i=$("li:first",f.list);i=$("a",i);ok(!i.length,"link injection!");start()}).bind("fb-pane-show",function(){if($(">li",f.list).length){$("li:first",f.list).simulate("mouseover");simulate_keypress(test_input1,$.simulate.VK_ENTER)}}).focus().val("bob dylan").trigger("textchange")});test("link_injection strongified",function(){test_input1.suggest(default_options);var f=get_instance();$.suggest.suggest.prototype.response=function(d){var e=
d.result;if(e&&e.length)e[0].name='<a href="javascript:alert("XSS");">click me</a>bob dylan';return b.response.apply(this,arguments)};stop(TIMEOUT_DELAY);test_input1.bind("fb-select",function(d,e){ok(e);equals(e.name,'<a href="javascript:alert("XSS");">click me</a>bob dylan');var i=$("li:first",f.list);i=$("a",i);ok(!i.length,"link injection!");start()}).bind("fb-pane-show",function(){if($(">li",f.list).length){$("li:first",f.list).simulate("mouseover");simulate_keypress(test_input1,$.simulate.VK_ENTER)}}).focus().val("bob dylan").trigger("textchange")})});
$(function(){module("advanced",module_options);test("advanced parsing",function(){for(var b=["bob dylan",["bob dylan",[],{}],"bob dylan type",["bob dylan type",[],{}],"bob dylan type:",["bob dylan type:",[],{}],"type:",["type:",[],{}]," type:album",["",["type:album"],{}],'bob dylan type:"music artist"',["bob dylan",['type:"music artist"'],{}],"Dear... name{full}:Dear... type:/film/film",["Dear...",["name{full}:Dear...","type:/film/film"],{}],"Monty Python: Life of Brian",["Monty Python: Life of Brian",
[],{}],"bob dylan a: b  c: d e",["bob dylan a: b c: d e",[],{}],"bob a:b c   d e: f g h:",["bob c d e: f g h:",["a:b"],{}],'bob a:b c : d:e {foo}:"hello world" dylan',["bob c : dylan",["a:b","d:e",'{foo}:"hello world"'],{}]],f=0,d=b.length;f<d;f+=2){var e=b[f],i=b[f+1];same($.suggest.parse_input(e),i)}b=["bob dylan lang:de",["bob dylan",[],{lang:"de"}],'lang:ko dae han min guk format:"ENTITY"',["dae han min guk",[],{lang:"ko",format:"ENTITY"}],'lang:ru Some Russian Name type:"/film/film" Another Name',
["Some Russian Name Another Name",['type:"/film/film"'],{lang:"ru"}]];f=0;for(d=b.length;f<d;f+=2){e=b[f];i=b[f+1];same($.suggest.parse_input(e),i)}});test("check_mql_key",function(){$.each(["A","a","0","a-b","0-A-9_","0-","abc","1023","$30DE$30C4$30BF$30B1","$30DEa-z$30C4_$30BF4$30B1-"],function(b,f){ok($.suggest.check_mql_key(f),f)});$.each(["a$001","0.ca","$30DE$30C4$30BF$30B"],function(b,f){ok(!$.suggest.check_mql_key(f),f)})});test("check_mql_id",function(){$.each(["/","/freebase","/type/type",
"/film/film/property","/0/1/2","/A/b_-","/wikipedia/ja/$30DE$30C4$30BF$30B1","/_"],function(b,f){ok($.suggest.check_mql_id(f),f)});$.each(["/freebase/","#9202a8c04000641f80000000010c393g","#00000000000000000000000000000000","foobar","","!/freebase","/A/-"],function(b,f){ok(!$.suggest.check_mql_id(f),f)})})});
