
/*
 * Copyright 2012, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Additional Licenses for Third Party components can be found here:
 * http://wiki.freebase.com/wiki/Freebase_Site_License
 *
 */
/*
 
 jQuery Tools @VERSION / Expose - Dim the lights

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/toolbox/expose.html

 Since: Mar 2010
 Date: @DATE 
 
 jQuery Tools @VERSION Overlay - Overlay base. Extend it.

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/overlay/

 Since: March 2008
 Date: @DATE 
 
 jQuery Tools @VERSION Tooltip - UI essentials

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/tooltip/

 Since: November 2008
 Date: @DATE 
*/
(function(b){function h(){if(b.browser.msie){var a=b(document).height(),c=b(window).height();return[window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth,20>a-c?c:a]}return[b(document).width(),b(document).height()]}function e(a){if(a)return a.call(b.mask)}b.tools=b.tools||{version:"@VERSION"};var f;f=b.tools.expose={conf:{maskId:"exposeMask",loadSpeed:"slow",closeSpeed:"fast",closeOnClick:!0,closeOnEsc:!0,zIndex:9998,opacity:0.8,startOpacity:0,color:"#fff",onLoad:null,
onClose:null}};var a,c,d,j,i;b.mask={load:function(g,p){if(d)return this;"string"==typeof g&&(g={color:g});g=g||j;j=g=b.extend(b.extend({},f.conf),g);a=b("#"+g.maskId);a.length||(a=b("<div/>").attr("id",g.maskId),b("body").append(a));var k=h();a.css({position:"absolute",top:0,left:0,width:k[0],height:k[1],display:"none",opacity:g.startOpacity,zIndex:g.zIndex});g.color&&a.css("backgroundColor",g.color);if(!1===e(g.onBeforeLoad))return this;g.closeOnEsc&&b(document).bind("keydown.mask",function(a){a.keyCode==
27&&b.mask.close(a)});g.closeOnClick&&a.bind("click.mask",function(a){b.mask.close(a)});b(window).bind("resize.mask",function(){b.mask.fit()});p&&p.length&&(i=p.eq(0).css("zIndex"),b.each(p,function(){var a=b(this);/relative|absolute|fixed/i.test(a.css("position"))||a.css("position","relative")}),c=p.css({zIndex:Math.max(g.zIndex+1,"auto"==i?0:i)}));a.css({display:"block"}).fadeTo(g.loadSpeed,g.opacity,function(){b.mask.fit();e(g.onLoad)});d=!0;return this},close:function(){if(d){if(!1===e(j.onBeforeClose))return this;
a.fadeOut(j.closeSpeed,function(){e(j.onClose);c&&c.css({zIndex:i})});b(document).unbind("keydown.mask");a.unbind("click.mask");b(window).unbind("resize.mask");d=!1}return this},fit:function(){if(d){var b=h();a.css({width:b[0],height:b[1]})}},getMask:function(){return a},isLoaded:function(){return d},getConf:function(){return j},getExposed:function(){return c}};b.fn.mask=function(a){b.mask.load(a);return this};b.fn.expose=function(a){b.mask.load(a,this);return this}})(jQuery);
(function(b){function h(a,c){var d=this,j=a.add(d),i=b(window),g,h,k,m=b.tools.expose&&(c.mask||c.expose),n=Math.random().toString().slice(10);m&&("string"==typeof m&&(m={color:m}),m.closeOnClick=m.closeOnEsc=!1);var l=c.target||a.attr("rel");h=l?b(l):a;if(!h.length)throw"Could not find Overlay: "+l;a&&-1==a.index(h)&&a.click(function(b){d.load(b);return b.preventDefault()});b.extend(d,{load:function(a){if(d.isOpened())return d;var g=f[c.effect];if(!g)throw'Overlay: cannot find effect : "'+c.effect+
'"';c.oneInstance&&b.each(e,function(){this.close(a)});a=a||b.Event();a.type="onBeforeLoad";j.trigger(a);if(a.isDefaultPrevented())return d;k=true;m&&b(h).expose(m);var o=c.top,t=c.left,r=h.outerWidth({margin:true}),l=h.outerHeight({margin:true});typeof o=="string"&&(o=o=="center"?Math.max((i.height()-l)/2,0):parseInt(o,10)/100*i.height());t=="center"&&(t=Math.max((i.width()-r)/2,0));g[0].call(d,{top:o,left:t},function(){if(k){a.type="onLoad";j.trigger(a)}});if(m&&c.closeOnClick)b.mask.getMask().one("click",
d.close);c.closeOnClick&&b(document).bind("click."+n,function(a){b(a.target).parents(h).length||d.close(a)});c.closeOnEsc&&b(document).bind("keydown."+n,function(b){b.keyCode==27&&d.close(b)});return d},close:function(a){if(!d.isOpened())return d;a=a||b.Event();a.type="onBeforeClose";j.trigger(a);if(!a.isDefaultPrevented()){k=false;f[c.effect][1].call(d,function(){a.type="onClose";j.trigger(a)});b(document).unbind("click."+n).unbind("keydown."+n);m&&b.mask.close();return d}},getOverlay:function(){return h},
getTrigger:function(){return a},getClosers:function(){return g},isOpened:function(){return k},getConf:function(){return c}});b.each(["onBeforeLoad","onStart","onLoad","onBeforeClose","onClose"],function(a,e){b.isFunction(c[e])&&b(d).bind(e,c[e]);d[e]=function(a){b(d).bind(e,a);return d}});g=h.find(c.close||".close");!g.length&&!c.close&&(g=b('<a class="close"></a>'),h.prepend(g));g.click(function(b){d.close(b)});c.load&&d.load()}b.tools=b.tools||{version:"@VERSION"};b.tools.overlay={addEffect:function(b,
c,d){f[b]=[c,d]},conf:{close:null,closeOnClick:!0,closeOnEsc:!0,closeSpeed:"fast",effect:"default",fixed:!b.browser.msie||6<b.browser.version,left:"center",load:!1,mask:null,oneInstance:!0,speed:"normal",target:null,top:"10%"}};var e=[],f={};b.tools.overlay.addEffect("default",function(a,c){var d=this.getConf(),e=b(window);d.fixed||(a.top+=e.scrollTop(),a.left+=e.scrollLeft());a.position=d.fixed?"fixed":"absolute";this.getOverlay().css(a).fadeIn(d.speed,c)},function(b){this.getOverlay().fadeOut(this.getConf().closeSpeed,
b)});b.fn.overlay=function(a){var c=this.data("overlay");if(c)return c;b.isFunction(a)&&(a={onBeforeLoad:a});a=b.extend(!0,{},b.tools.overlay.conf,a);this.each(function(){c=new h(b(this),a);e.push(c);b(this).data("overlay",c)});return a.api?c:this}})(jQuery);
(function(b){b.factory("collapse_module",{init:function(){var e=this;this.$column=b(this.options.column);this.modules=b(this.options.modules,this.element);this.first_module=this.modules.get(0);this.trigger=b(".trigger:first",this.first_module);this.first_section=b(".module-section",this.first_module);this.other_modules=this.modules.slice(1);this.column_offset=this.$column.css("margin-left");this.set_collapsed(this.options.collapsed);this.trigger.click(function(b){return e.toggle(b)})},set_collapsed:function(b){(this.toggle_state=
b)?(this.trigger.addClass("collapsed"),this.$column.css("margin-left",0),this.first_section.hide(),this.other_modules.hide()):(this.trigger.removeClass("collapsed"),this.$column.css("margin-left",this.column_offset),this.first_section.show(),this.other_modules.show())},toggle:function(){var e=this;this.toggle_state?(b.localstore("filters_collapsed",0,!1),this.trigger.removeClass("collapsed"),this.$column.animate({marginLeft:this.column_offset},function(){e.first_section.slideDown(function(){e.modules.removeClass("collapsed")});
e.other_modules.fadeIn()})):(b.localstore("filters_collapsed",1,!1),this.trigger.addClass("collapsed"),this.other_modules.fadeOut(),this.first_section.slideUp(function(){e.$column.animate({marginLeft:0});e.modules.addClass("collapsed")}));this.toggle_state=!this.toggle_state;this.options.toggle_callback&&this.options.toggle_callback.call(this.trigger,this.toggle_state);return!1}});var h=b("body").is(".embed")||b.localstore("filters_collapsed");b.extend(!0,b.collapse_module,{defaults:{collapsed:null===
h?!1:!!h,modules:".module",column:"#main-column"}})})(jQuery);
(function(b){function h(b,c,d){var e=d.relative?b.position().top:b.offset().top,f=d.relative?b.position().left:b.offset().left,g=d.position[0],e=e-(c.outerHeight()-d.offset[0]),f=f+(b.outerWidth()+d.offset[1]),h=c.outerHeight()+b.outerHeight();"center"==g&&(e+=h/2);"bottom"==g&&(e+=h);g=d.position[1];b=c.outerWidth()+b.outerWidth();"center"==g&&(f-=b/2);"left"==g&&(f-=b);return{top:e,left:f}}function e(a,c){var d=this,e=a.add(d),i,g=0,p=0,k=a.attr("title"),m=f[c.effect],n,l=a.is(":input"),s=l&&a.is(":checkbox, :radio, select, :button, :submit"),
u=a.attr("type"),o=c.events[u]||c.events[l?s?"widget":"input":"def"];if(!m)throw'Nonexistent effect "'+c.effect+'"';o=o.split(/,\s*/);if(2!=o.length)throw"Tooltip: bad events configuration for "+u;a.bind(o[0],function(b){clearTimeout(g);c.predelay?p=setTimeout(function(){d.show(b)},c.predelay):d.show(b)}).bind(o[1],function(b){clearTimeout(p);c.delay?g=setTimeout(function(){d.hide(b)},c.delay):d.hide(b)});k&&c.cancelDefault&&(a.removeAttr("title"),a.data("title",k));b.extend(d,{show:function(f){if(!i){if(k)i=
b(c.layout).addClass(c.tipClass).appendTo(document.body).hide().append(k);else if(c.tip)i=b(c.tip).eq(0);else{i=a.next();i.length||(i=a.parent().next())}if(!i.length)throw"Cannot find tooltip for "+a;}if(d.isShown())return d;i.stop(true,true);var r=h(a,i,c),f=f||b.Event();f.type="onBeforeShow";e.trigger(f,[r]);if(f.isDefaultPrevented())return d;r=h(a,i,c);i.css({position:"absolute",top:r.top,left:r.left});n=true;m[0].call(d,function(){f.type="onShow";n="full";e.trigger(f)});r=c.events.tooltip.split(/,\s*/);
i.bind(r[0],function(){clearTimeout(g);clearTimeout(p)});r[1]&&!a.is("input:not(:checkbox, :radio), textarea")&&i.bind(r[1],function(b){b.relatedTarget!=a[0]&&a.trigger(o[1].split(" ")[0])});return d},hide:function(a){if(!i||!d.isShown())return d;a=a||b.Event();a.type="onBeforeHide";e.trigger(a);if(!a.isDefaultPrevented()){n=false;f[c.effect][1].call(d,function(){a.type="onHide";n=false;e.trigger(a)});return d}},isShown:function(b){return b?n=="full":n},getConf:function(){return c},getTip:function(){return i},
getTrigger:function(){return a}});b.each(["onHide","onBeforeShow","onShow","onBeforeHide"],function(a,e){b.isFunction(c[e])&&b(d).bind(e,c[e]);d[e]=function(a){b(d).bind(e,a);return d}})}b.tools=b.tools||{version:"@VERSION"};b.tools.tooltip={conf:{effect:"toggle",fadeOutSpeed:"fast",predelay:0,delay:30,opacity:1,tip:0,position:["top","center"],offset:[0,0],relative:!1,cancelDefault:!0,events:{def:"mouseenter,mouseleave",input:"focus,blur",widget:"focus mouseenter,blur mouseleave",tooltip:"mouseenter,mouseleave"},
layout:"<div/>",tipClass:"tooltip"},addEffect:function(b,c,d){f[b]=[c,d]}};var f={toggle:[function(b){var c=this.getConf(),d=this.getTip(),c=c.opacity;1>c&&d.css({opacity:c});d.show();b.call()},function(b){this.getTip().hide();b.call()}],fade:[function(b){var c=this.getConf();this.getTip().fadeTo(c.fadeInSpeed,c.opacity,b)},function(b){this.getTip().fadeOut(this.getConf().fadeOutSpeed,b)}]};b.fn.tooltip=function(a){var c=this.data("tooltip");if(c)return c;a=b.extend(!0,{},b.tools.tooltip.conf,a);
"string"==typeof a.position&&(a.position=a.position.split(/,?\s/));this.each(function(){c=new e(b(this),a);b(this).data("tooltip",c)});return a.api?c:this}})(jQuery);
(function(b,h){h.filters={init_domain_type_property_filter:function(e){b(":text[name=domain], :text[name=type], :text[name=property]",e).suggest(b.extend({scoring:"schema",format:null,mql_output:JSON.stringify([{id:null,name:null,type:{id:null,"id|=":["/type/domain","/type/type","/type/property"],limit:1}}])},h.suggest_options.any("type:/type/domain","type:/type/type","type:/type/property"))).bind("fb-select",function(e,a){var c=b(this);c.val(a.id);var d=a.type.id;"/type/domain"===d?c.attr("name",
"domain"):"/type/type"===d?c.attr("name","type"):"/type/property"===d&&c.attr("name","property");this.form.submit()}).parents(".filter-form").submit(function(){return!1})}};b(function(){b(".filter-form :input").keypress(function(b){13===b.keyCode&&this.form.submit();return!0});b(".filter-help-trigger").tooltip({events:{def:"click,mouseout"},position:"top center",effect:"fade",delay:300,offset:[-8,0]});b(".filter-form-trigger").click(function(){var e=b(this).siblings(".filter-form");e.is(":hidden")?
e.slideDown(function(){b(":text:first",e).focus()}):e.slideUp()})})})(jQuery,window.freebase);
(function(b){var h="undefined"!=typeof window.innerWidth?function(){return{w:window.innerWidth,h:window.innerHeight}}:"undefined"!=typeof document.documentElement&&"undefined"!=typeof document.documentElement.clientWidth&&0!=document.documentElement.clientWidth?function(){return{w:document.documentElement.clientWidth,h:document.documentElement.clientHeight}}:function(){return{w:document.getElementsByTagName("body")[0].clientWidth,h:document.getElementsByTagName("body")[0].clientHeight}};window.kbs=
function(e){b(".kbs.current",e).removeClass("current");var f=b(".domain-section:first",e),a=b(".domain-section:last",e),c=this.scroll_to=function(a){var c=b(document).scrollTop();b(document).height();var d=h().h,d=c+d,e=a.offset().top,a=e+a.height();e<c?b(document).scrollTop(e):a>d&&b(document).scrollTop(c+(a-d))},d=this.get_current=function(){return b(".kbs.current:first",e)},j=this.set_next=function(b,a,e){b=b||d();a.length&&(b.removeClass("current"),a.addClass("current"),e||c(a))},i=this.next_domain=
function(b){var a=d(),c=g(a);c&&(c=c.find(".kbs:first"),j(a,c,b))},g=this._next_domain=function(q){if(!q||!q.length)return b(".domain-section:first",e);q=q.closest(".domain-section");return!q.length||q[0]===a[0]?f:q.next(".domain-section")},p=this.prev_domain=function(){var b=d(),a=k(b);a&&(a=a.find(".kbs:first"),j(b,a))},k=this._prev_domain=function(q){if(!q||!q.length)return b(".domain-section:last",e);var c=q.closest(".domain-section");return q.closest(".property-section").length||q.closest(".type-section").length?
c:!c.length||c[0]===f[0]?a:c.prev(".domain-section")},m=this.next_type=function(){var b=d(),a=n(b);a&&(a=a.find(".kbs:first"),j(b,a))},n=this._next_type=function(a){if(!a||!a.length)return b(".type-section:first",e);var c=a.closest(".domain-section"),a=a.closest(".type-section"),a=a.length?a.next(".type-section"):c.find(".type-section:first");if(!a||!a.length){var d=g(c);if(d)for(;d.get(0)!==c.get(0);){a=d.find(".type-section:first");if(a.length)break;d=g(d)}}return a},l=this.prev_type=function(){var b=
d(),a=s(b);a&&(a=a.find(".kbs:first"),j(b,a))},s=this._prev_type=function(a){if(!a||!a.length)return b(".type-section:last",e);var c=a.closest(".domain-section"),d=a.closest(".type-section");if(a.closest(".property-section").length)return d;var f;d.length&&(f=d.prev(".type-section"));if(!f||!f.length)if(a=k(c))for(;a.get(0)!==c.get(0);){f=a.find(".type-section:last");if(f.length)break;a=k(a)}return f},u=this.next_prop=function(){var b=d(),a=o(b);a&&(a=a.find(".kbs:first"),j(b,a))},o=this._next_prop=
function(a){if(!a||!a.length)return b(".property-section:first",e);var c=a.closest(".domain-section"),d=a.closest(".type-section"),f=a.closest(".property-section"),c=f.length?f.next(".property-section"):d.length?d.find(".property-section:first"):c.find(".property-section:first");if(!c||!c.length)if(a=n(a))for(;a.get(0)!==d.get(0);){c=a.find(".property-section:first");if(c.length)break;null==d.get(0)&&(d=a);a=n(a)}return c},t=this.prev_prop=function(){var b=d(),a=r(b);a&&(a=a.find(".kbs:first"),j(b,
a))},r=this._prev_prop=function(a){if(!a||!a.length)return b(".property-section:last",e);var c=a.closest(".domain-section"),d=a.closest(".type-section"),f=a.closest(".property-section");if(a.closest(".data-section").length)return f;var g;f.length&&(g=f.prev(".property-section"));if(!g||!g.length)if(l=d.length?s(d):s(c))for(;l.get(0)!==d.get(0);){g=l.find(".property-section:last");if(g.length)break;null==d.get(0)&&(d=l);l=s(l)}return g};this.next=function(){var a=d(),b=this._next(a);b&&j(a,b)};this._next=
function(c){if(!c||!c.length)return b(".domain-section:first .kbs:first",e);var d=c.closest(".domain-section"),g=c.closest(".type-section"),h=c.closest(".property-section");if(c.closest(".data-section").length){c=c.next(".kbs");if(c.length)return c;c=h.next(".property-section").find(".kbs:first");if(c.length)return c;c=g.next(".type-section").find(".kbs:first")}else if(h.length){c=h.find(".data-section:first .kbs:first");if(c.length)return c;c=h.next(".property-section").find(".kbs:first");if(c.length)return c;
c=g.next(".type-section").find(".kbs:first")}else if(g.length){c=g.find(".property-section:first .kbs:first");if(c.length)return c;c=g.next(".type-section").find(".kbs:first")}else c=d.find(".type-section:first .kbs:first");return c.length?c:d.get(0)===a.get(0)?f.find(".kbs:first"):d.next(".domain-section").find(".kbs:first")};this.prev=function(){var a=d(),b=this._prev(a);b&&j(a,b)};this._prev=function(c){if(!c||!c.length)return c=b(".data-section:last .kbs:last",e),c.length||(c=b(".property-section:last .kbs:first",
e)),c.length||(c=b(".type-section:last .kbs:first",e)),c.length||(c=b(".domain-section:last .kbs:first",e)),c;var d=c.closest(".domain-section"),g=c.closest(".type-section"),h=c.closest(".property-section");return c.closest(".data-section").length?(c=c.prev(".kbs"),c.length?c:h.find(".kbs:first")):h.length?(c=h.prev(".property-section").find(".kbs:last"),c.length?c:g.find(".kbs:first")):g.length?(c=g.prev(".type-section").find(".kbs:last"),c.length?c:d.find(".kbs:first")):d.get(0)===f.get(0)?a.find(".kbs:last"):
d.prev(".domain-section").find(".kbs:last")};this.edit=function(){this.get_current().trigger("edit")};var v=this;b(document).unbind(".kbs").bind("keydown.kbs",function(a){var c=a.target;if(c==document.body||c==document||c==window||c==b("html")[0])c=a.keyCode,68===c?a.shiftKey?p():i():84===c?a.shiftKey?l():m():80===c?a.shiftKey?t():u():74===c?v.next():75===c?v.prev():69===c&&v.edit()})}})(jQuery);
(function(b,h){var e=window.propbox={init:function(f,a){a=b.extend({lang:"/lang/en"},a);if(!a.base_ajax_url)throw Error("base_ajax_url required in propbox options");if(!a.base_static_url)throw Error("base_static_url required in propbox options");if(!a.id)throw Error("topic id required in propbox options");if(!a.lang)throw Error("lang required in propbox options");e.options=a;e.kbs=new h(f);e.kbs.set_next(e.kbs.get_current(),b(".kbs:visible:first",f,!0));b(".kbs",f).live("click",function(){var a=e.kbs.get_current();
e.kbs.set_next(a,b(this),!0)}).live("edit",function(){var a=b(this).find(".headmenu:first").data("submenu");a&&b("li:first a:first",a).click()});e.init_menus(f)},init_menus:function(f,a){f=b(f||document);a&&b(".nicemenu",f).nicemenu();(f&&f.is(".data-row")?f:b(".data-row",f)).hover(e.row_menu_hoverover,e.row_menu_hoverout);b(".nicemenu .headmenu",f).add(b(".nicemenu .default-action",f)).click("click",function(){if(e.kbs){var a=e.kbs.get_current();a&&e.kbs.set_next(a,b(this).parents(".kbs:first"),
!0)}return!1})},row_menu_hoverover:function(){var f=b(this);e.row_menu_hoverover.timeout=setTimeout(function(){f.addClass("row-hover")},300)},row_menu_hoverout:function(){clearTimeout(e.row_menu_hoverover.timeout);b(this).removeClass("row-hover")},get_script:function(f,a){var c=e.get_script.cache;c||(c=e.get_script.cache={});var d=c[f];d?1===d.state?d.callbacks.push(a):4===d.state&&a():(d=c[f]={state:0,callbacks:[a]},b.ajax({url:e.options.base_static_url+f,dataType:"script",beforeSend:function(){d.state=
1},success:function(){d.state=4;b.each(d.callbacks,function(a,b){b()})},error:function(){d.state=-1}}))},prop_edit:function(f,a){var c=b(f).parents(".submenu").data("headmenu").parents(".property-section").find(".data-section .data-row:first:visible .nicemenu:first .headmenu:first a");c.length?c.click():e.prop_add(f,a);return!1},prop_add:function(f,a){var c=b(f).parents(".submenu").data("headmenu").parents(".property-section");e.get_script("/propbox-edit.mf.js",function(){e.edit.prop_add_begin(c,
a)});return!1},value_edit:function(f){var a=b(f).parents(".submenu").data("headmenu").parents(".data-row:first"),c=a.parents(".property-section");e.get_script("/propbox-edit.mf.js",function(){e.edit.value_edit_begin(c,a)});return!1},value_delete:function(f){var a=b(f).parents(".submenu").data("headmenu").parents(".data-row:first"),c=a.parents(".property-section");e.get_script("/propbox-edit.mf.js",function(){e.edit.value_delete_begin(c,a)});return!1},close_message:function(e){b(e).parents(".row-msg:first").remove();
return!1}}})(jQuery,window.kbs);(function(b){b.fn.fixedcolumn=function(h){var e=b.extend(!0,{},h);return this.each(function(){var f=b(this).find("tr:first").children();1<f.length&&(e.all||(f=b(f.get(0))),f.each(function(){var a=b(this),c=a[0].nodeName.toUpperCase();if("TD"===c||"TH"===c)c=a.width(),0<c&&b(":first-child",a).width(c).css("display","inline-block")}))})}})(jQuery);
(function(b,h,e){var f=h.topic={init:function(){e.init("#topic-data",{id:h.c.id,base_ajax_url:h.h.ajax_url("lib/propbox"),base_static_url:h.h.static_url("lib/propbox"),lang:h.lang||"/lang/en",suggest_impl:h.suggest_options,incompatible_types:h.incompatible_types});b(".column.nav").collapse_module({modules:".module",column:".section"});h.filters.init_domain_type_property_filter(".column.nav");b(".data-table").fixedcolumn({all:!0});b(".toolbar-trigger").click(function(){var a=b(this),c=b(this).closest(".toolbar"),
d=b(".manage-types").first().css("overflow","hidden"),e=d.outerHeight(),h=b(".topic-types",d).first(),g=b(".topic-type-list",d).first(),p=b("ul",g).children("li").length;d.is(":visible")?(c.removeClass("active"),a.removeClass("active"),d.slideUp()):(a.addClass("active"),c.addClass("active"),d.slideDown(function(){a.data("initialized")||(f.init_manage_types(),a.data("initialized",1))}),Modernizr.csscolumns&&7<p&&g.addClass("multicolumn"),c=g.position().top,g.height(e-c+"px"),h.animate({opacity:1}));
return!1});b(".keyboard-shortcuts > a").overlay({close:".modal-buttons .button.cancel",closeOnClick:!1,fixed:!1,mask:{color:"#000",loadSpeed:200,opacity:0.5}});b("#show-all-domains-link").click(function(){b(":checkbox",".filter-form.all-data-toggle").click();return!1})},init_manage_types:function(){b("#add-type-input").suggest(h.suggest_options.cotype()).bind("fb-select",function(a,b){f.add_type(this,b.id)}).focus()},add_type:function(a,c){function d(b,d,e){h.get_script(h.h.static_url("manage-type.mf.js"),
function(){f.manage_type.add_type_begin(a,c,e)})}a=b(a);h.incompatible_types.check(h.c.id,c,{compatible:d,incompatible:h.incompatible_types.overlay_suggest_incompatible_callback(a,{onLoad:function(){b(".incompatible-overlay-dialog .incompatible-topic").text(b(b(".page-title > h1 > span").get(0).firstChild).text())},onCancel:function(){a.focus()},onConfirm:d})});return!1},remove_type:function(a,c){a=b(a);h.get_script(h.h.static_url("manage-type.mf.js"),function(){f.manage_type.remove_type_begin(a,
c)});return!1}};b(f.init)})(jQuery,window.freebase,window.propbox);
