
/*
 * Copyright 2012, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Additional Licenses for Third Party components can be found here:
 * http://wiki.freebase.com/wiki/Freebase_Site_License
 *
 */
(function(a,e){var g,h,f,d,b,c,j,p,l,t,i,k,s,m,o,r,q,u,n,w,y,A,C,z;g=function(a){return new g.prototype.init(a)};"undefined"!==typeof require&&"undefined"!==typeof exports&&"undefined"!==typeof module?module.exports=g:a.Globalize=g;g.cultures={};g.prototype={constructor:g,init:function(a){this.cultures=g.cultures;this.cultureSelector=a;return this}};g.prototype.init.prototype=g.prototype;g.cultures["default"]={name:"en",englishName:"English",nativeName:"English",isRTL:!1,language:"en",numberFormat:{pattern:["-n"],
decimals:2,",":",",".":".",groupSizes:[3],"+":"+","-":"-",NaN:"NaN",negativeInfinity:"-Infinity",positiveInfinity:"Infinity",percent:{pattern:["-n %","n %"],decimals:2,groupSizes:[3],",":",",".":".",symbol:"%"},currency:{pattern:["($n)","$n"],decimals:2,groupSizes:[3],",":",",".":".",symbol:"$"}},calendars:{standard:{name:"Gregorian_USEnglish","/":"/",":":":",firstDay:0,days:{names:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),namesAbbr:"Sun Mon Tue Wed Thu Fri Sat".split(" "),
namesShort:"Su Mo Tu We Th Fr Sa".split(" ")},months:{names:"January February March April May June July August September October November December ".split(" "),namesAbbr:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec ".split(" ")},AM:["AM","am","AM"],PM:["PM","pm","PM"],eras:[{name:"A.D.",start:null,offset:0}],twoDigitYearMax:2029,patterns:{d:"M/d/yyyy",D:"dddd, MMMM dd, yyyy",t:"h:mm tt",T:"h:mm:ss tt",f:"dddd, MMMM dd, yyyy h:mm tt",F:"dddd, MMMM dd, yyyy h:mm:ss tt",M:"MMMM dd",Y:"yyyy MMMM",
S:"yyyy'-'MM'-'dd'T'HH':'mm':'ss"}}},messages:{}};g.cultures["default"].calendar=g.cultures["default"].calendars.standard;g.cultures.en=g.cultures["default"];g.cultureSelector="en";h=/^0x[a-f0-9]+$/i;f=/^[+\-]?infinity$/i;d=/^[+\-]?\d*\.?\d*(e[+\-]?\d+)?$/;b=/^\s+|\s+$/g;c=function(a,b){if(a.indexOf)return a.indexOf(b);for(var c=0,d=a.length;c<d;c++)if(a[c]===b)return c;return-1};j=function(a,b){return a.substr(a.length-b.length)===b};p=function(){var a,b,c,d,f,j=arguments[0]||{},h=1,k=arguments.length,
g=!1;"boolean"===typeof j&&(g=j,j=arguments[1]||{},h=2);for("object"!==typeof j&&!t(j)&&(j={});h<k;h++)if(null!=(a=arguments[h]))for(b in a)c=j[b],d=a[b],j!==d&&(g&&d&&(i(d)||(f=l(d)))?(f?(f=!1,c=c&&l(c)?c:[]):c=c&&i(c)?c:{},j[b]=p(g,c,d)):d!==e&&(j[b]=d));return j};l=Array.isArray||function(a){return"[object Array]"===Object.prototype.toString.call(a)};t=function(a){return"[object Function]"===Object.prototype.toString.call(a)};i=function(a){return"[object Object]"===Object.prototype.toString.call(a)};
k=function(a,b){return 0===a.indexOf(b)};s=function(a){return(a+"").replace(b,"")};m=function(a){return isNaN(a)?NaN:Math[0>a?"ceil":"floor"](a)};o=function(a,b,c){var d;for(d=a.length;d<b;d+=1)a=c?"0"+a:a+"0";return a};r=function(a,b){for(var c=0,d=!1,i=0,e=a.length;i<e;i++){var f=a.charAt(i);switch(f){case "'":d?b.push("'"):c++;d=!1;break;case "\\":d&&b.push("\\");d=!d;break;default:b.push(f),d=!1}}return c};q=function(a,b){var b=b||"F",c;c=a.patterns;var d=b.length;if(1===d){c=c[b];if(!c)throw"Invalid date format string '"+
b+"'.";b=c}else 2===d&&"%"===b.charAt(0)&&(b=b.charAt(1));return b};u=function(a,b,c){function d(a,b){var c;c=a+"";return 1<b&&c.length<b?(c=t[b-2]+c,c.substr(c.length-b,b)):c}function i(){if(p||g)return p;p=s.test(b);g=!0;return p}function e(a,b){if(n)return n[b];switch(b){case 0:return a.getFullYear();case 1:return a.getMonth();case 2:return a.getDate();default:throw"Invalid part value "+b;}}var f=c.calendar,j=f.convert;if(!b||!b.length||"i"===b){if(c&&c.name.length)if(j)c=u(a,f.patterns.F,c);else{var c=
new Date(a.getTime()),l=y(a,f.eras);c.setFullYear(A(a,f,l));c=c.toLocaleString()}else c=a.toString();return c}var l=f.eras,h="s"===b,b=q(f,b),c=[],k,t=["0","00","000"],p,g,s=/([^d]|^)(d|dd)([^d]|$)/g,m=0,o=w(),n;for(!h&&j&&(n=j.fromGregorian(a));;){k=o.lastIndex;j=o.exec(b);k=b.slice(k,j?j.index:b.length);m+=r(k,c);if(!j)break;if(m%2)c.push(j[0]);else switch(k=j[0],j=k.length,k){case "ddd":case "dddd":c.push((3===j?f.days.namesAbbr:f.days.names)[a.getDay()]);break;case "d":case "dd":p=!0;c.push(d(e(a,
2),j));break;case "MMM":case "MMMM":k=e(a,1);c.push(f.monthsGenitive&&i()?f.monthsGenitive[3===j?"namesAbbr":"names"][k]:f.months[3===j?"namesAbbr":"names"][k]);break;case "M":case "MM":c.push(d(e(a,1)+1,j));break;case "y":case "yy":case "yyyy":k=n?n[0]:A(a,f,y(a,l),h);4>j&&(k%=100);c.push(d(k,j));break;case "h":case "hh":k=a.getHours()%12;0===k&&(k=12);c.push(d(k,j));break;case "H":case "HH":c.push(d(a.getHours(),j));break;case "m":case "mm":c.push(d(a.getMinutes(),j));break;case "s":case "ss":c.push(d(a.getSeconds(),
j));break;case "t":case "tt":k=12>a.getHours()?f.AM?f.AM[0]:" ":f.PM?f.PM[0]:" ";c.push(1===j?k.charAt(0):k);break;case "f":case "ff":case "fff":c.push(d(a.getMilliseconds(),3).substr(0,j));break;case "z":case "zz":k=a.getTimezoneOffset()/60;c.push((0>=k?"+":"-")+d(Math.floor(Math.abs(k)),j));break;case "zzz":k=a.getTimezoneOffset()/60;c.push((0>=k?"+":"-")+d(Math.floor(Math.abs(k)),2)+":"+d(Math.abs(a.getTimezoneOffset()%60),2));break;case "g":case "gg":f.eras&&c.push(f.eras[y(a,l)].name);break;
case "/":c.push(f["/"]);break;default:throw"Invalid date format pattern '"+k+"'.";}}return c.join("")};var D;D=function(a,b,c){var d=c.groupSizes,f=d[0],j=1,i=Math.pow(10,b),e=Math.round(a*i)/i;isFinite(e)||(e=a);i="";i=(e+"").split(/e/i);e=1<i.length?parseInt(i[1],10):0;a=i[0];i=a.split(".");a=i[0];i=1<i.length?i[1]:"";0<e?(i=o(i,e,!1),a+=i.slice(0,e),i=i.substr(e)):0>e&&(e=-e,a=o(a,e+1,!0),i=a.slice(-e,a.length)+i,a=a.slice(0,-e));i=0<b?c["."]+(i.length>b?i.slice(0,b):o(i,b)):"";b=a.length-1;c=
c[","];for(e="";0<=b;){if(0===f||f>b)return a.slice(0,b+1)+(e.length?c+e+i:i);e=a.slice(b-f+1,b+1)+(e.length?c+e:"");b-=f;j<d.length&&(f=d[j],j++)}return a.slice(0,b+1)+c+e+i};n=function(a,b,c){if(!isFinite(a))return Infinity===a?c.numberFormat.positiveInfinity:-Infinity===a?c.numberFormat.negativeInfinity:c.numberFormat.NaN;if(!b||"i"===b)return c.name.length?a.toLocaleString():a.toString();var b=b||"D",c=c.numberFormat,d=Math.abs(a),i=-1;1<b.length&&(i=parseInt(b.slice(1),10));var e=b.charAt(0).toUpperCase(),
f;switch(e){case "D":b="n";d=m(d);-1!==i&&(d=o(""+d,i,!0));0>a&&(d="-"+d);break;case "N":f=c;case "C":f=f||c.currency;case "P":f=f||c.percent;b=0>a?f.pattern[0]:f.pattern[1]||"n";-1===i&&(i=f.decimals);d=D(d*("P"===e?100:1),i,f);break;default:throw"Bad number format specifier: "+e;}a=/n|\$|-|%/g;for(f="";;){i=a.lastIndex;e=a.exec(b);f+=b.slice(i,e?e.index:b.length);if(!e)break;switch(e[0]){case "n":f+=d;break;case "$":f+=c.currency.symbol;break;case "-":/[1-9]/.test(d)&&(f+=c["-"]);break;case "%":f+=
c.percent.symbol}}return f};w=function(){return/\/|dddd|ddd|dd|d|MMMM|MMM|MM|M|yyyy|yy|y|hh|h|HH|H|mm|m|ss|s|tt|t|fff|ff|f|zzz|zz|z|gg|g/g};y=function(a,b){if(!b)return 0;for(var c,d=a.getTime(),f=0,i=b.length;f<i;f++)if(c=b[f].start,null===c||d>=c)return f;return 0};A=function(a,b,c,d){a=a.getFullYear();!d&&b.eras&&(a-=b.eras[c].offset);return a};var E,F,G,H,v,B,x;E=function(a,b){if(100>b){var c=new Date,d=y(c),c=A(c,a,d),d=a.twoDigitYearMax,d="string"===typeof d?(new Date).getFullYear()%100+parseInt(d,
10):d,b=b+(c-c%100);b>d&&(b-=100)}return b};F=function(a,b,d){var f=a.days,i=a._upperDays;i||(a._upperDays=i=[x(f.names),x(f.namesAbbr),x(f.namesShort)]);b=B(b);d?(a=c(i[1],b),-1===a&&(a=c(i[2],b))):a=c(i[0],b);return a};G=function(a,b,d){var f=a.months,i=a.monthsGenitive||a.months,e=a._upperMonths,j=a._upperMonthsGen;e||(a._upperMonths=e=[x(f.names),x(f.namesAbbr)],a._upperMonthsGen=j=[x(i.names),x(i.namesAbbr)]);b=B(b);a=c(d?e[1]:e[0],b);0>a&&(a=c(d?j[1]:j[0],b));return a};H=function(a,b){var c=
a._parseRegExp;if(c){var d=c[b];if(d)return d}else a._parseRegExp=c={};for(var d=q(a,b).replace(/([\^\$\.\*\+\?\|\[\]\(\)\{\}])/g,"\\\\$1"),f=["^"],i=[],e=0,j=0,k=w(),l;null!==(l=k.exec(d));){var h=d.slice(e,l.index),e=k.lastIndex,j=j+r(h,f);if(j%2)f.push(l[0]);else{var h=l[0],p=h.length;switch(h){case "dddd":case "ddd":case "MMMM":case "MMM":case "gg":case "g":h="(\\D+)";break;case "tt":case "t":h="(\\D*)";break;case "yyyy":case "fff":case "ff":case "f":h="(\\d{"+p+"})";break;case "dd":case "d":case "MM":case "M":case "yy":case "y":case "HH":case "H":case "hh":case "h":case "mm":case "m":case "ss":case "s":h=
"(\\d\\d?)";break;case "zzz":h="([+-]?\\d\\d?:\\d{2})";break;case "zz":case "z":h="([+-]?\\d\\d?)";break;case "/":h="(\\/)";break;default:throw"Invalid date format pattern '"+h+"'.";}h&&f.push(h);i.push(l[0])}}r(d.slice(e),f);f.push("$");d={regExp:f.join("").replace(/\s+/g,"\\s+"),groups:i};return c[b]=d};v=function(a,b,c){return a<b||a>c};B=function(a){return a.split("\u00a0").join(" ").toUpperCase()};x=function(a){for(var b=[],c=0,d=a.length;c<d;c++)b[c]=B(a[c]);return b};C=function(a,b,c){var a=
s(a),c=c.calendar,b=H(c,b),d=RegExp(b.regExp).exec(a);if(null===d)return null;var f=b.groups,i=b=a=null,e=null,j=null,l=0,h,p=0,t=0,g=0;h=null;for(var r=!1,m=0,o=f.length;m<o;m++){var q=d[m+1];if(q){var n=f[m],w=n.length,u=parseInt(q,10);switch(n){case "dd":case "d":e=u;if(v(e,1,31))return null;break;case "MMM":case "MMMM":i=G(c,q,3===w);if(v(i,0,11))return null;break;case "M":case "MM":i=u-1;if(v(i,0,11))return null;break;case "y":case "yy":case "yyyy":b=4>w?E(c,u):u;if(v(b,0,9999))return null;break;
case "h":case "hh":l=u;12===l&&(l=0);if(v(l,0,11))return null;break;case "H":case "HH":l=u;if(v(l,0,23))return null;break;case "m":case "mm":p=u;if(v(p,0,59))return null;break;case "s":case "ss":t=u;if(v(t,0,59))return null;break;case "tt":case "t":r=c.PM&&(q===c.PM[0]||q===c.PM[1]||q===c.PM[2]);if(!r&&(!c.AM||q!==c.AM[0]&&q!==c.AM[1]&&q!==c.AM[2]))return null;break;case "f":case "ff":case "fff":g=u*Math.pow(10,3-w);if(v(g,0,999))return null;break;case "ddd":case "dddd":j=F(c,q,3===w);if(v(j,0,6))return null;
break;case "zzz":n=q.split(/:/);if(2!==n.length)return null;h=parseInt(n[0],10);if(v(h,-12,13))return null;n=parseInt(n[1],10);if(v(n,0,59))return null;h=60*h+(k(q,"-")?-n:n);break;case "z":case "zz":h=u;if(v(h,-12,13))return null;h*=60;break;case "g":case "gg":if(!q||!c.eras)return null;q=s(q.toLowerCase());n=0;for(w=c.eras.length;n<w;n++)if(q===c.eras[n].name.toLowerCase()){a=n;break}if(null===a)return null}}}d=new Date;f=(m=c.convert)?m.fromGregorian(d)[0]:d.getFullYear();null===b?b=f:c.eras&&
(b+=c.eras[a||0].offset);null===i&&(i=0);null===e&&(e=1);if(m){if(d=m.toGregorian(b,i,e),null===d)return null}else if(d.setFullYear(b,i,e),d.getDate()!==e||null!==j&&d.getDay()!==j)return null;r&&12>l&&(l+=12);d.setHours(l,p,t,g);null!==h&&(c=d.getMinutes()-(h+d.getTimezoneOffset()),d.setHours(d.getHours()+parseInt(c/60,10),c%60));return d};z=function(a,b,c){var d=b["-"],b=b["+"],f;switch(c){case "n -":d=" "+d,b=" "+b;case "n-":j(a,d)?f=["-",a.substr(0,a.length-d.length)]:j(a,b)&&(f=["+",a.substr(0,
a.length-b.length)]);break;case "- n":d+=" ",b+=" ";case "-n":k(a,d)?f=["-",a.substr(d.length)]:k(a,b)&&(f=["+",a.substr(b.length)]);break;case "(n)":k(a,"(")&&j(a,")")&&(f=["-",a.substr(1,a.length-2)])}return f||["",a]};g.prototype.findClosestCulture=function(a){return g.findClosestCulture.call(this,a)};g.prototype.format=function(a,b,c){return g.format.call(this,a,b,c)};g.prototype.localize=function(a,b){return g.localize.call(this,a,b)};g.prototype.parseInt=function(a,b,c){return g.parseInt.call(this,
a,b,c)};g.prototype.parseFloat=function(a,b,c){return g.parseFloat.call(this,a,b,c)};g.prototype.culture=function(a){return g.culture.call(this,a)};g.addCultureInfo=function(a,b,c){var d={},f=!1;"string"!==typeof a?(c=a,a=this.culture().name,d=this.cultures[a]):"string"!==typeof b?(c=b,f=null==this.cultures[a],d=this.cultures[a]||this.cultures["default"]):(f=!0,d=this.cultures[b]);this.cultures[a]=p(!0,{},d,c);f&&(this.cultures[a].calendar=this.cultures[a].calendars.standard)};g.findClosestCulture=
function(a){var b;if(!a)return this.findClosestCulture(this.cultureSelector)||this.cultures["default"];"string"===typeof a&&(a=a.split(","));if(l(a)){var c,d=this.cultures,f=a,i,e=f.length,j=[];for(i=0;i<e;i++)a=s(f[i]),a=a.split(";"),c=s(a[0]),1===a.length?a=1:(a=s(a[1]),0===a.indexOf("q=")?(a=a.substr(2),a=parseFloat(a),a=isNaN(a)?0:a):a=1),j.push({lang:c,pri:a});j.sort(function(a,b){return a.pri<b.pri?1:a.pri>b.pri?-1:0});for(i=0;i<e;i++)if(c=j[i].lang,b=d[c])return b;for(i=0;i<e;i++){c=j[i].lang;
do{f=c.lastIndexOf("-");if(-1===f)break;c=c.substr(0,f);if(b=d[c])return b}while(1)}for(i=0;i<e;i++){c=j[i].lang;for(var h in d)if(f=d[h],f.language==c)return f}}else if("object"===typeof a)return a;return b||null};g.format=function(a,b,c){c=this.findClosestCulture(c);a instanceof Date?a=u(a,b,c):"number"===typeof a&&(a=n(a,b,c));return a};g.localize=function(a,b){return this.findClosestCulture(b).messages[a]||this.cultures["default"].messages[a]};g.parseDate=function(a,b,c){var c=this.findClosestCulture(c),
d,f;if(b){if("string"===typeof b&&(b=[b]),b.length){f=0;for(var i=b.length;f<i;f++){var e=b[f];if(e&&(d=C(a,e,c)))break}}}else for(f in b=c.calendar.patterns,b)if(d=C(a,b[f],c))break;return d||null};g.parseInt=function(a,b,c){return m(g.parseFloat(a,b,c))};g.parseFloat=function(a,b,c){"number"!==typeof b&&(c=b,b=10);var i=this.findClosestCulture(c),c=NaN,e=i.numberFormat;-1<a.indexOf(i.numberFormat.currency.symbol)&&(a=a.replace(i.numberFormat.currency.symbol,""),a=a.replace(i.numberFormat.currency["."],
i.numberFormat["."]));a=s(a);if(f.test(a))c=parseFloat(a);else if(!b&&h.test(a))c=parseInt(a,16);else{i=z(a,e,e.pattern[0]);b=i[0];i=i[1];""===b&&"(n)"!==e.pattern[0]&&(i=z(a,e,"(n)"),b=i[0],i=i[1]);""===b&&"-n"!==e.pattern[0]&&(i=z(a,e,"-n"),b=i[0],i=i[1]);var b=b||"+",j,a=i.indexOf("e");0>a&&(a=i.indexOf("E"));0>a?(j=i,a=null):(j=i.substr(0,a),a=i.substr(a+1));var l=e["."],k=j.indexOf(l);0>k?(i=j,j=null):(i=j.substr(0,k),j=j.substr(k+l.length));l=e[","];i=i.split(l).join("");k=l.replace(/\u00A0/g,
" ");l!==k&&(i=i.split(k).join(""));b+=i;null!==j&&(b+="."+j);null!==a&&(e=z(a,e,"-n"),b+="e"+(e[0]||"+")+e[1]);d.test(b)&&(c=parseFloat(b))}return c};g.culture=function(a){"undefined"!==typeof a&&(this.cultureSelector=a);return this.findClosestCulture(a)||this.cultures["default"]}})(this);
"JSON"in window&&window.JSON||(this.JSON||(this.JSON={}),function(){function a(a){return a<10?"0"+a:a}function e(a){f.lastIndex=0;return f.test(a)?'"'+a.replace(f,function(a){var b=c[a];return typeof b==="string"?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function g(a,c){var f,i,h,s,m=d,o,r=c[a];r&&(typeof r==="object"&&typeof r.toJSON==="function")&&(r=r.toJSON(a));typeof j==="function"&&(r=j.call(c,a,r));switch(typeof r){case "string":return e(r);case "number":return isFinite(r)?
String(r):"null";case "boolean":case "null":return String(r);case "object":if(!r)return"null";d=d+b;o=[];if(Object.prototype.toString.apply(r)==="[object Array]"){s=r.length;for(f=0;f<s;f=f+1)o[f]=g(f,r)||"null";h=o.length===0?"[]":d?"[\n"+d+o.join(",\n"+d)+"\n"+m+"]":"["+o.join(",")+"]";d=m;return h}if(j&&typeof j==="object"){s=j.length;for(f=0;f<s;f=f+1){i=j[f];if(typeof i==="string")(h=g(i,r))&&o.push(e(i)+(d?": ":":")+h)}}else for(i in r)if(Object.hasOwnProperty.call(r,i))(h=g(i,r))&&o.push(e(i)+
(d?": ":":")+h);h=o.length===0?"{}":d?"{\n"+d+o.join(",\n"+d)+"\n"+m+"}":"{"+o.join(",")+"}";d=m;return h}}if(typeof Date.prototype.toJSON!=="function"){Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null};String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()}}var h=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
f=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,d,b,c={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},j;if(typeof JSON.stringify!=="function")JSON.stringify=function(a,c,f){var i;b=d="";if(typeof f==="number")for(i=0;i<f;i=i+1)b=b+" ";else typeof f==="string"&&(b=f);if((j=c)&&typeof c!=="function"&&(typeof c!=="object"||typeof c.length!=="number"))throw Error("JSON.stringify");return g("",{"":a})};
if(typeof JSON.parse!=="function")JSON.parse=function(a,b){function c(a,d){var f,i,e=a[d];if(e&&typeof e==="object")for(f in e)if(Object.hasOwnProperty.call(e,f)){i=c(e,f);i!==void 0?e[f]=i:delete e[f]}return b.call(a,d,e)}var d,a=String(a);h.lastIndex=0;h.test(a)&&(a=a.replace(h,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){d=eval("("+a+")");return typeof b==="function"?c({"":d},""):d}throw new SyntaxError("JSON.parse");}}());
(function(a){a.factory=function(e,g){if(a.fn[e])throw"$.fn."+e+" plugin already exists";if(a[e])throw"$."+e+" class already exists";a.fn[e]=function(h){return this.each(function(){var f=a(this),d=f.data("$."+e);d&&d._destroy();d=new a[e](f,h);f.data("$."+e,d)})};a[e]=function(h,f){this.options=a.extend(true,{},a[e].defaults,f);this.element=h;this.init()};a.extend(a[e].prototype,{init:function(){},_destroy:function(){}},g);return a[e]}})(jQuery);
(function(){var a={};$.extend({localstore:function(e,g,h,f){var d=document.location.hostname,b=document.location.protocol;if(typeof g!=="undefined"){var c=JSON.stringify(g);if(!h&&window.globalStorage)g===null?delete window.globalStorage[d][b+e]:window.globalStorage[d][b+e]=c;else if(!h&&window.localStorage&&window.localStorage.setItem)g===null?window.localStorage.removeItem(b+e):window.localStorage.setItem(b+e,c);else if(h!==false){h={};h.domain=fb.get_cookie_domain();g===null?$.cookie(e,null,h):
$.cookie(e,c,$.extend(h,f||{expires:14,path:"/"}))}else g===null?delete a[e]:a[e]=c;return g}if(!h&&window.globalStorage){if(window.globalStorage[d][b+e])g=window.globalStorage[d][b+e].value}else g=!h&&window.localStorage?window.localStorage.getItem(b+e):h!==false?$.cookie(e):a[e];return g!=""&&g!==null&&g!==void 0?JSON.parse(g,null):null}})})();
(function(a){a.extend({metadata:{defaults:{type:"class",name:"metadata",cre:/({.*})/,single:"metadata"},setType:function(a,g){this.defaults.type=a;this.defaults.name=g},get:function(e,g){var h=a.extend({},this.defaults,g);if(!h.single.length)h.single="metadata";var f=a.data(e,h.single);if(f)return f;var f="{}",d=function(a){if(typeof a!="string")return a;return a=eval("("+a+")")};if(h.type=="html5"){var b={};a(e.attributes).each(function(){var a=this.nodeName;if(a.match(/^data-/))a=a.replace(/^data-/,
"");else return true;b[a]=d(this.nodeValue)})}else{if(h.type=="class"){var c=h.cre.exec(e.className);c&&(f=c[1])}else if(h.type=="elem"){if(!e.getElementsByTagName)return;c=e.getElementsByTagName(h.name);c.length&&(f=a.trim(c[0].innerHTML))}else if(e.getAttribute!=void 0)(c=e.getAttribute(h.name))&&(f=c);b=d(f.indexOf("{")<0?"{"+f+"}":f)}a.data(e,h.single,b);return b}}});a.fn.metadata=function(e){return a.metadata.get(this[0],e)}})(jQuery);
(function(a,e){function g(e){return!a(e).parents().andSelf().filter(function(){return a.curCSS(this,"visibility")==="hidden"||a.expr.filters.hidden(this)}).length}a.ui=a.ui||{};if(!a.ui.version){a.extend(a.ui,{version:"1.8.10",keyCode:{ALT:18,BACKSPACE:8,CAPS_LOCK:20,COMMA:188,COMMAND:91,COMMAND_LEFT:91,COMMAND_RIGHT:93,CONTROL:17,DELETE:46,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,INSERT:45,LEFT:37,MENU:93,NUMPAD_ADD:107,NUMPAD_DECIMAL:110,NUMPAD_DIVIDE:111,NUMPAD_ENTER:108,NUMPAD_MULTIPLY:106,NUMPAD_SUBTRACT:109,
PAGE_DOWN:34,PAGE_UP:33,PERIOD:190,RIGHT:39,SHIFT:16,SPACE:32,TAB:9,UP:38,WINDOWS:91}});a.fn.extend({_focus:a.fn.focus,focus:function(e,f){return typeof e==="number"?this.each(function(){var d=this;setTimeout(function(){a(d).focus();f&&f.call(d)},e)}):this._focus.apply(this,arguments)},scrollParent:function(){var e;e=a.browser.msie&&/(static|relative)/.test(this.css("position"))||/absolute/.test(this.css("position"))?this.parents().filter(function(){return/(relative|absolute|fixed)/.test(a.curCSS(this,
"position",1))&&/(auto|scroll)/.test(a.curCSS(this,"overflow",1)+a.curCSS(this,"overflow-y",1)+a.curCSS(this,"overflow-x",1))}).eq(0):this.parents().filter(function(){return/(auto|scroll)/.test(a.curCSS(this,"overflow",1)+a.curCSS(this,"overflow-y",1)+a.curCSS(this,"overflow-x",1))}).eq(0);return/fixed/.test(this.css("position"))||!e.length?a(document):e},zIndex:function(h){if(h!==e)return this.css("zIndex",h);if(this.length)for(var h=a(this[0]),f;h.length&&h[0]!==document;){f=h.css("position");if(f===
"absolute"||f==="relative"||f==="fixed"){f=parseInt(h.css("zIndex"),10);if(!isNaN(f)&&f!==0)return f}h=h.parent()}return 0},disableSelection:function(){return this.bind((a.support.selectstart?"selectstart":"mousedown")+".ui-disableSelection",function(a){a.preventDefault()})},enableSelection:function(){return this.unbind(".ui-disableSelection")}});a.each(["Width","Height"],function(h,f){function d(c,d,f,i){a.each(b,function(){d=d-(parseFloat(a.curCSS(c,"padding"+this,true))||0);f&&(d=d-(parseFloat(a.curCSS(c,
"border"+this+"Width",true))||0));i&&(d=d-(parseFloat(a.curCSS(c,"margin"+this,true))||0))});return d}var b=f==="Width"?["Left","Right"]:["Top","Bottom"],c=f.toLowerCase(),j={innerWidth:a.fn.innerWidth,innerHeight:a.fn.innerHeight,outerWidth:a.fn.outerWidth,outerHeight:a.fn.outerHeight};a.fn["inner"+f]=function(b){return b===e?j["inner"+f].call(this):this.each(function(){a(this).css(c,d(this,b)+"px")})};a.fn["outer"+f]=function(b,e){return typeof b!=="number"?j["outer"+f].call(this,b):this.each(function(){a(this).css(c,
d(this,b,true,e)+"px")})}});a.extend(a.expr[":"],{data:function(e,f,d){return!!a.data(e,d[3])},focusable:function(e){var f=e.nodeName.toLowerCase(),d=a.attr(e,"tabindex");if("area"===f){f=e.parentNode;d=f.name;if(!e.href||!d||f.nodeName.toLowerCase()!=="map")return false;e=a("img[usemap=#"+d+"]")[0];return!!e&&g(e)}return(/input|select|textarea|button|object/.test(f)?!e.disabled:"a"==f?e.href||!isNaN(d):!isNaN(d))&&g(e)},tabbable:function(e){var f=a.attr(e,"tabindex");return(isNaN(f)||f>=0)&&a(e).is(":focusable")}});
a(function(){var e=document.body,f=e.appendChild(f=document.createElement("div"));a.extend(f.style,{minHeight:"100px",height:"auto",padding:0,borderWidth:0});a.support.minHeight=f.offsetHeight===100;a.support.selectstart="onselectstart"in f;e.removeChild(f).style.display="none"});a.extend(a.ui,{plugin:{add:function(e,f,d){var e=a.ui[e].prototype,b;for(b in d){e.plugins[b]=e.plugins[b]||[];e.plugins[b].push([f,d[b]])}},call:function(a,f,d){if((f=a.plugins[f])&&a.element[0].parentNode)for(var b=0;b<
f.length;b++)a.options[f[b][0]]&&f[b][1].apply(a.element,d)}},contains:function(a,f){return document.compareDocumentPosition?a.compareDocumentPosition(f)&16:a!==f&&a.contains(f)},hasScroll:function(e,f){if(a(e).css("overflow")==="hidden")return false;var d=f&&f==="left"?"scrollLeft":"scrollTop",b=false;if(e[d]>0)return true;e[d]=1;b=e[d]>0;e[d]=0;return b},isOverAxis:function(a,e,d){return a>e&&a<e+d},isOver:function(e,f,d,b,c,j){return a.ui.isOverAxis(e,d,c)&&a.ui.isOverAxis(f,b,j)}})}})(jQuery);
(function(a,e){if(a.cleanData){var g=a.cleanData;a.cleanData=function(e){for(var d=0,b;(b=e[d])!=null;d++)a(b).triggerHandler("remove");g(e)}}else{var h=a.fn.remove;a.fn.remove=function(e,d){return this.each(function(){d||(!e||a.filter(e,[this]).length)&&a("*",this).add([this]).each(function(){a(this).triggerHandler("remove")});return h.call(a(this),e,d)})}}a.widget=function(e,d,b){var c=e.split(".")[0],j,e=e.split(".")[1];j=c+"-"+e;if(!b){b=d;d=a.Widget}a.expr[":"][j]=function(b){return!!a.data(b,
e)};a[c]=a[c]||{};a[c][e]=function(a,b){arguments.length&&this._createWidget(a,b)};d=new d;d.options=a.extend(true,{},d.options);a[c][e].prototype=a.extend(true,d,{namespace:c,widgetName:e,widgetEventPrefix:a[c][e].prototype.widgetEventPrefix||e,widgetBaseClass:j},b);a.widget.bridge(e,a[c][e])};a.widget.bridge=function(f,d){a.fn[f]=function(b){var c=typeof b==="string",j=Array.prototype.slice.call(arguments,1),h=this,b=!c&&j.length?a.extend.apply(null,[true,b].concat(j)):b;if(c&&b.charAt(0)==="_")return h;
c?this.each(function(){var c=a.data(this,f),d=c&&a.isFunction(c[b])?c[b].apply(c,j):c;if(d!==c&&d!==e){h=d;return false}}):this.each(function(){var c=a.data(this,f);c?c.option(b||{})._init():a.data(this,f,new d(b,this))});return h}};a.Widget=function(a,d){arguments.length&&this._createWidget(a,d)};a.Widget.prototype={widgetName:"widget",widgetEventPrefix:"",options:{disabled:false},_createWidget:function(e,d){a.data(d,this.widgetName,this);this.element=a(d);this.options=a.extend(true,{},this.options,
this._getCreateOptions(),e);var b=this;this.element.bind("remove."+this.widgetName,function(){b.destroy()});this._create();this._trigger("create");this._init()},_getCreateOptions:function(){return a.metadata&&a.metadata.get(this.element[0])[this.widgetName]},_create:function(){},_init:function(){},destroy:function(){this.element.unbind("."+this.widgetName).removeData(this.widgetName);this.widget().unbind("."+this.widgetName).removeAttr("aria-disabled").removeClass(this.widgetBaseClass+"-disabled ui-state-disabled")},
widget:function(){return this.element},option:function(f,d){var b=f;if(arguments.length===0)return a.extend({},this.options);if(typeof f==="string"){if(d===e)return this.options[f];b={};b[f]=d}this._setOptions(b);return this},_setOptions:function(e){var d=this;a.each(e,function(a,c){d._setOption(a,c)});return this},_setOption:function(a,d){this.options[a]=d;a==="disabled"&&this.widget()[d?"addClass":"removeClass"](this.widgetBaseClass+"-disabled ui-state-disabled").attr("aria-disabled",d);return this},
enable:function(){return this._setOption("disabled",false)},disable:function(){return this._setOption("disabled",true)},_trigger:function(e,d,b){var c=this.options[e],d=a.Event(d);d.type=(e===this.widgetEventPrefix?e:this.widgetEventPrefix+e).toLowerCase();b=b||{};if(d.originalEvent)for(var e=a.event.props.length,j;e;){j=a.event.props[--e];d[j]=d.originalEvent[j]}this.element.trigger(d,b);return!(a.isFunction(c)&&c.call(this.element[0],d,b)===false||d.isDefaultPrevented())}}})(jQuery);
(function(a){a.widget("ui.mouse",{options:{cancel:":input,option",distance:1,delay:0},_mouseInit:function(){var e=this;this.element.bind("mousedown."+this.widgetName,function(a){return e._mouseDown(a)}).bind("click."+this.widgetName,function(g){if(true===a.data(g.target,e.widgetName+".preventClickEvent")){a.removeData(g.target,e.widgetName+".preventClickEvent");g.stopImmediatePropagation();return false}});this.started=false},_mouseDestroy:function(){this.element.unbind("."+this.widgetName)},_mouseDown:function(e){e.originalEvent=
e.originalEvent||{};if(!e.originalEvent.mouseHandled){this._mouseStarted&&this._mouseUp(e);this._mouseDownEvent=e;var g=this,h=e.which==1,f=typeof this.options.cancel=="string"?a(e.target).parents().add(e.target).filter(this.options.cancel).length:false;if(!h||f||!this._mouseCapture(e))return true;this.mouseDelayMet=!this.options.delay;if(!this.mouseDelayMet)this._mouseDelayTimer=setTimeout(function(){g.mouseDelayMet=true},this.options.delay);if(this._mouseDistanceMet(e)&&this._mouseDelayMet(e)){this._mouseStarted=
this._mouseStart(e)!==false;if(!this._mouseStarted){e.preventDefault();return true}}this._mouseMoveDelegate=function(a){return g._mouseMove(a)};this._mouseUpDelegate=function(a){return g._mouseUp(a)};a(document).bind("mousemove."+this.widgetName,this._mouseMoveDelegate).bind("mouseup."+this.widgetName,this._mouseUpDelegate);e.preventDefault();return e.originalEvent.mouseHandled=true}},_mouseMove:function(e){if(a.browser.msie&&!(document.documentMode>=9)&&!e.button)return this._mouseUp(e);if(this._mouseStarted){this._mouseDrag(e);
return e.preventDefault()}if(this._mouseDistanceMet(e)&&this._mouseDelayMet(e))(this._mouseStarted=this._mouseStart(this._mouseDownEvent,e)!==false)?this._mouseDrag(e):this._mouseUp(e);return!this._mouseStarted},_mouseUp:function(e){a(document).unbind("mousemove."+this.widgetName,this._mouseMoveDelegate).unbind("mouseup."+this.widgetName,this._mouseUpDelegate);if(this._mouseStarted){this._mouseStarted=false;e.target==this._mouseDownEvent.target&&a.data(e.target,this.widgetName+".preventClickEvent",
true);this._mouseStop(e)}return false},_mouseDistanceMet:function(a){return Math.max(Math.abs(this._mouseDownEvent.pageX-a.pageX),Math.abs(this._mouseDownEvent.pageY-a.pageY))>=this.options.distance},_mouseDelayMet:function(){return this.mouseDelayMet},_mouseStart:function(){},_mouseDrag:function(){},_mouseStop:function(){},_mouseCapture:function(){return true}})})(jQuery);
(function(a){a.ui=a.ui||{};var e=/left|center|right/,g=/top|center|bottom/,h=a.fn.position,f=a.fn.offset;a.fn.position=function(d){if(!d||!d.of)return h.apply(this,arguments);var d=a.extend({},d),b=a(d.of),c=b[0],f=(d.collision||"flip").split(" "),p=d.offset?d.offset.split(" "):[0,0],l,t,i;if(c.nodeType===9){l=b.width();t=b.height();i={top:0,left:0}}else if(c.setTimeout){l=b.width();t=b.height();i={top:b.scrollTop(),left:b.scrollLeft()}}else if(c.preventDefault){d.at="left top";l=t=0;i={top:d.of.pageY,
left:d.of.pageX}}else{l=b.outerWidth();t=b.outerHeight();i=b.offset()}a.each(["my","at"],function(){var a=(d[this]||"").split(" ");a.length===1&&(a=e.test(a[0])?a.concat(["center"]):g.test(a[0])?["center"].concat(a):["center","center"]);a[0]=e.test(a[0])?a[0]:"center";a[1]=g.test(a[1])?a[1]:"center";d[this]=a});f.length===1&&(f[1]=f[0]);p[0]=parseInt(p[0],10)||0;p.length===1&&(p[1]=p[0]);p[1]=parseInt(p[1],10)||0;if(d.at[0]==="right")i.left=i.left+l;else if(d.at[0]==="center")i.left=i.left+l/2;if(d.at[1]===
"bottom")i.top=i.top+t;else if(d.at[1]==="center")i.top=i.top+t/2;i.left=i.left+p[0];i.top=i.top+p[1];return this.each(function(){var b=a(this),c=b.outerWidth(),e=b.outerHeight(),h=parseInt(a.curCSS(this,"marginLeft",true))||0,g=parseInt(a.curCSS(this,"marginTop",true))||0,q=c+h+(parseInt(a.curCSS(this,"marginRight",true))||0),u=e+g+(parseInt(a.curCSS(this,"marginBottom",true))||0),n=a.extend({},i),w;if(d.my[0]==="right")n.left=n.left-c;else if(d.my[0]==="center")n.left=n.left-c/2;if(d.my[1]==="bottom")n.top=
n.top-e;else if(d.my[1]==="center")n.top=n.top-e/2;n.left=Math.round(n.left);n.top=Math.round(n.top);w={left:n.left-h,top:n.top-g};a.each(["left","top"],function(b,i){if(a.ui.position[f[b]])a.ui.position[f[b]][i](n,{targetWidth:l,targetHeight:t,elemWidth:c,elemHeight:e,collisionPosition:w,collisionWidth:q,collisionHeight:u,offset:p,my:d.my,at:d.at})});a.fn.bgiframe&&b.bgiframe();b.offset(a.extend(n,{using:d.using}))})};a.ui.position={fit:{left:function(d,b){var c=a(window),c=b.collisionPosition.left+
b.collisionWidth-c.width()-c.scrollLeft();d.left=c>0?d.left-c:Math.max(d.left-b.collisionPosition.left,d.left)},top:function(d,b){var c=a(window),c=b.collisionPosition.top+b.collisionHeight-c.height()-c.scrollTop();d.top=c>0?d.top-c:Math.max(d.top-b.collisionPosition.top,d.top)}},flip:{left:function(d,b){if(b.at[0]!=="center"){var c=a(window),c=b.collisionPosition.left+b.collisionWidth-c.width()-c.scrollLeft(),e=b.my[0]==="left"?-b.elemWidth:b.my[0]==="right"?b.elemWidth:0,f=b.at[0]==="left"?b.targetWidth:
-b.targetWidth,l=-2*b.offset[0];d.left=d.left+(b.collisionPosition.left<0?e+f+l:c>0?e+f+l:0)}},top:function(d,b){if(b.at[1]!=="center"){var c=a(window),c=b.collisionPosition.top+b.collisionHeight-c.height()-c.scrollTop(),e=b.my[1]==="top"?-b.elemHeight:b.my[1]==="bottom"?b.elemHeight:0,f=b.at[1]==="top"?b.targetHeight:-b.targetHeight,l=-2*b.offset[1];d.top=d.top+(b.collisionPosition.top<0?e+f+l:c>0?e+f+l:0)}}}};if(!a.offset.setOffset){a.offset.setOffset=function(d,b){if(/static/.test(a.curCSS(d,"position")))d.style.position=
"relative";var c=a(d),e=c.offset(),f=parseInt(a.curCSS(d,"top",true),10)||0,l=parseInt(a.curCSS(d,"left",true),10)||0,e={top:b.top-e.top+f,left:b.left-e.left+l};"using"in b?b.using.call(d,e):c.css(e)};a.fn.offset=function(e){var b=this[0];return!b||!b.ownerDocument?null:e?this.each(function(){a.offset.setOffset(this,e)}):f.call(this)}}})(jQuery);
(function(a,e){if(!("console"in window)){var g=window.console={};g.log=g.warn=g.error=g.debug=function(){}}a(function(){var b=a("<div>");a(document.body).append(b);var c=setTimeout(function(){if(a.cleanData){var b=a.cleanData;a.cleanData=function(c){for(var e=0,d;(d=c[e])!=null;e++)a(d).triggerHandler("remove");b(c)}}else{var c=a.fn.remove;a.fn.remove=function(b,e){return this.each(function(){e||(!b||a.filter(b,[this]).length)&&a("*",this).add([this]).each(function(){a(this).triggerHandler("remove")});
return c.call(a(this),b,e)})}}},1);b.bind("remove",function(){clearTimeout(c)});b.remove()});var h={key:1,filter:1,spell:1,exact:1,lang:1,scoring:1,prefixed:1,stemmed:1,format:1,mql_output:1};a.suggest=function(b,c){a.fn[b]=function(c){this.length||console.warn("Suggest: invoked on empty element set");return this.each(function(){this.nodeName&&(this.nodeName.toUpperCase()==="INPUT"?this.type&&this.type.toUpperCase()!=="TEXT"&&console.warn("Suggest: unsupported INPUT type: "+this.type):console.warn("Suggest: unsupported DOM element: "+
this.nodeName));var e=a.data(this,b);e&&e._destroy();a.data(this,b,new a.suggest[b](this,c))._init()})};a.suggest[b]=function(c,e){var d=this,f=this.options=a.extend(true,{},a.suggest.defaults,a.suggest[b].defaults,e),i=f.css_prefix=f.css_prefix||"",k=f.css;this.name=b;a.each(k,function(a){k[a]=i+k[a]});f.ac_param={};a.each(h,function(a){var b=f[a];b===null||b===""||(f.ac_param[a]=b)});f.flyout_lang=null;if(f.ac_param.lang){var g=f.ac_param.lang;a.type(g)==="string"&&(g=g.split(","));if(a.isArray(g)&&
g.length)if(g=a.trim(g[0]))f.flyout_lang=g}this._status={START:"",LOADING:"",SELECT:"",ERROR:""};if(f.status&&f.status instanceof Array&&f.status.length>=3){this._status.START=f.status[0]||"";this._status.LOADING=f.status[1]||"";this._status.SELECT=f.status[2]||"";if(f.status.length===4)this._status.ERROR=f.status[3]||""}var g=this.status=a('<div style="display:none;">').addClass(k.status),m=this.list=a("<ul>").addClass(k.list),o=this.pane=a('<div style="display:none;" class="fbs-reset">').addClass(k.pane);
o.append(g).append(m);if(f.parent)a(f.parent).append(o);else{o.css("position","absolute");f.zIndex&&o.css("z-index",f.zIndex);a(document.body).append(o)}o.bind("mousedown",function(a){d.input.data("dont_hide",true);a.stopPropagation()}).bind("mouseup",function(a){d.input.data("dont_hide")&&d.input.focus();d.input.removeData("dont_hide");a.stopPropagation()}).bind("click",function(a){a.stopPropagation();if(a=d.get_selected()){d.onselect(a,true);d.hide_all()}});m.hover(function(a){d.hoverover_list(a)},
function(a){d.hoverout_list(a)});this.input=a(c).attr("autocomplete","off").unbind(".suggest").bind("remove.suggest",function(){d._destroy()}).bind("keydown.suggest",function(a){d.keydown(a)}).bind("keypress.suggest",function(a){d.keypress(a)}).bind("keyup.suggest",function(a){d.keyup(a)}).bind("blur.suggest",function(a){d.blur(a)}).bind("textchange.suggest",function(){d.textchange()}).bind("focus.suggest",function(a){d.focus(a)}).bind(a.browser.msie?"paste.suggest":"input.suggest",function(){clearTimeout(d.paste_timeout);
d.paste_timeout=setTimeout(function(){d.textchange()},0)});this.onresize=function(){d.invalidate_position();if(o.is(":visible")){d.position();if(f.flyout&&d.flyoutpane&&d.flyoutpane.is(":visible")){var a=d.get_selected();a&&d.flyout_position(a)}}};a(window).bind("resize.suggest",this.onresize).bind("scroll.suggest",this.onresize)};a.suggest[b].prototype=a.extend({},a.suggest.prototype,c)};a.suggest.prototype={_init:function(){},_destroy:function(){this.pane.remove();this.list.remove();this.input.unbind(".suggest");
a(window).unbind("resize.suggest",this.onresize).unbind("scroll.suggest",this.onresize);this.input.removeData("data.suggest")},invalidate_position:function(){self._position=null},status_start:function(){this.hide_all();this.status.siblings().hide();if(this._status.START){this.status.text(this._status.START).show();if(!this.pane.is(":visible")){this.position();this.pane_show()}}this._status.LOADING&&this.status.removeClass("loading")},status_loading:function(){this.status.siblings().show();if(this._status.LOADING){this.status.addClass("loading").text(this._status.LOADING).show();
if(!this.pane.is(":visible")){this.position();this.pane_show()}}else this.status.hide()},status_select:function(){this.status.siblings().show();this._status.SELECT?this.status.text(this._status.SELECT).show():this.status.hide();this._status.LOADING&&this.status.removeClass("loading")},status_error:function(){this.status.siblings().show();this._status.ERROR?this.status.text(this._status.ERROR).show():this.status.hide();this._status.LOADING&&this.status.removeClass("loading")},focus:function(a){this.input.val()===
""?this.status_start():this.focus_hook(a)},focus_hook:function(){if(!this.input.data("data.suggest")&&!this.pane.is(":visible")&&a("."+this.options.css.item,this.list).length){this.position();this.pane_show()}},keydown:function(a){var c=a.keyCode;if(c===9)this.tab(a);else if(c===38||c===40)a.shiftKey||a.preventDefault()},keypress:function(a){var c=a.keyCode;c===38||c===40?a.shiftKey||a.preventDefault():c===13&&this.enter(a)},keyup:function(b){var c=b.keyCode;if(c===38){b.preventDefault();this.up(b)}else if(c===
40){b.preventDefault();this.down(b)}else if(b.ctrlKey&&c===77)a(".fbs-more-link",this.pane).click();else if(a.suggest.is_char(b)){clearTimeout(this.keypress.timeout);var d=this;this.keypress.timeout=setTimeout(function(){d.textchange()},0)}else c===27&&this.escape(b);return true},blur:function(){if(!this.input.data("dont_hide")){this.input.data("data.suggest");this.hide_all()}},tab:function(b){if(!b.shiftKey&&!b.metaKey&&!b.ctrlKey){var b=this.options,b=this.pane.is(":visible")&&a("."+b.css.item,
this.list).length,c=this.get_selected();if(b&&c){this.onselect(c);this.hide_all()}}},enter:function(b){var c=this.options;if(this.pane.is(":visible"))if(b.shiftKey){this.shift_enter(b);b.preventDefault()}else if(a("."+c.css.item,this.list).length)if(c=this.get_selected()){this.onselect(c);this.hide_all();b.preventDefault()}else{this.input.data("data.suggest");if(a("."+this.options.css.item+":visible",this.list).length){this.updown(false);b.preventDefault()}}},shift_enter:function(){},escape:function(){this.hide_all()},
up:function(a){this.updown(true,a.ctrlKey||a.shiftKey)},down:function(a){this.updown(false,null,a.ctrlKey||a.shiftKey)},updown:function(b,c,d){var e=this.options.css,f=this.list;if(this.pane.is(":visible")){var h=a("."+e.item+":visible",f);if(h.length){var f=a(h[0]),h=a(h[h.length-1]),i=this.get_selected()||[];clearTimeout(this.ignore_mouseover.timeout);this._ignore_mouseover=false;if(b)if(c)this._goto(f);else if(i.length)if(i[0]==f[0]){f.removeClass(e.selected);this.input.val(this.input.data("original.suggest"));
this.hoverout_list()}else{b=i.prevAll("."+e.item+":visible:first");this._goto(b)}else this._goto(h);else if(d)this._goto(h);else if(i.length)if(i[0]==h[0]){h.removeClass(e.selected);this.input.val(this.input.data("original.suggest"));this.hoverout_list()}else{b=i.nextAll("."+e.item+":visible:first");this._goto(b)}else this._goto(f)}}else b||this.textchange()},_goto:function(a){a.trigger("mouseover.suggest");var c=a.data("data.suggest");this.input.val(c?c.name:this.input.data("original.suggest"));
this.scroll_to(a)},scroll_to:function(a){var c=this.list,d=c.scrollTop(),e=d+c.innerHeight(),f=a.outerHeight(),a=a.prevAll().length*f,f=a+f;if(a<d){this.ignore_mouseover();c.scrollTop(a)}else if(f>e){this.ignore_mouseover();c.scrollTop(d+f-e)}},textchange:function(){this.input.removeData("data.suggest");this.input.trigger("fb-textchange",this);var a=this.input.val();if(a==="")this.status_start();else{this.status_loading();this.request(a)}},request:function(){},response:function(b){if(b){"cost"in b&&
this.trackEvent(this.name,"response","cost",b.cost);if(this.check_response(b)){var c=[];if(a.isArray(b))c=b;else if("result"in b)c=b.result;var d=a.map(arguments,function(a){return a});this.response_hook.apply(this,d);var e=null,f=this,h=this.options;a.each(c,function(a,c){if(!c.id&&c.mid)c.id=c.mid;var d=f.create_item(c,b).bind("mouseover.suggest",function(a){f.mouseover_item(a)});d.data("data.suggest",c);f.list.append(d);a===0&&(e=d)});this.input.data("original.suggest",this.input.val());if(a("."+
h.css.item,this.list).length===0&&h.nomatch){c=a('<li class="fbs-nomatch">');if(typeof h.nomatch==="string")c.text(h.nomatch);else{h.nomatch.title&&c.append(a('<em class="fbs-nomatch-text">').text(h.nomatch.title));h.nomatch.heading&&c.append(a("<h3>").text(h.nomatch.heading));if((h=h.nomatch.tips)&&h.length){var i=a('<ul class="fbs-search-tips">');a.each(h,function(b,c){i.append(a("<li>").text(c))});c.append(i)}}c.bind("click.suggest",function(a){a.stopPropagation()});this.list.append(c)}d.push(e);
this.show_hook.apply(this,d);this.position();this.pane_show()}}},pane_show:function(){var b=false;a("> li",this.list).length&&(b=true);b||this.pane.children(":not(."+this.options.css.list+")").each(function(){if(a(this).css("display")!="none"){b=true;return false}});if(b)if(this.options.animate){var c=this;this.pane.slideDown("fast",function(){c.input.trigger("fb-pane-show",c)})}else{this.pane.show();this.input.trigger("fb-pane-show",this)}else{this.pane.hide();this.input.trigger("fb-pane-hide",this)}},
create_item:function(b){var c=this.options.css,d=a("<li>").addClass(c.item),b=a("<label>").text(b.name);d.append(a("<div>").addClass(c.item_name).append(b));return d},mouseover_item:function(b){if(!this._ignore_mouseover){b=b.target;b.nodeName.toLowerCase()!=="li"&&(b=a(b).parents("li:first"));var c=a(b),d=this.options.css;a("."+d.item,this.list).each(function(){this!==c[0]&&a(this).removeClass(d.selected)});if(!c.hasClass(d.selected)){c.addClass(d.selected);this.mouseover_item_hook(c)}}},mouseover_item_hook:function(){},
hoverover_list:function(){},hoverout_list:function(){},check_response:function(){return true},response_hook:function(){this.list.empty()},show_hook:function(){this.status_select()},position:function(){var b=this.pane,c=this.options;if(!c.parent){if(!self._position){var d=this.input,e=d.offset(),f=d.outerWidth(true),h=d.outerHeight(true);e.top=e.top+h;var i=b.outerWidth(),g=b.outerHeight(),s=e.top+g/2,m=a(window).scrollLeft(),d=a(window).scrollTop(),o=a(window).width(),r=a(window).height()+d,q=true;
"left"==c.align?q=true:"right"==c.align?q=false:e.left>m+o/2&&(q=false);if(!q){q=e.left-(i-f);if(q>m)e.left=q}if(s>r){c=e.top-h-g;if(c>d)e.top=c}this._position=e}b.css({top:this._position.top,left:this._position.left})}},ignore_mouseover:function(){this._ignore_mouseover=true;var a=this;this.ignore_mouseover.timeout=setTimeout(function(){a.ignore_mouseover_reset()},1E3)},ignore_mouseover_reset:function(){this._ignore_mouseover=false},get_selected:function(){var b=null,c=this.options.css.selected;
a("li",this.list).each(function(){var d=a(this);if(d.hasClass(c)&&d.is(":visible")){b=d;return false}});return b},onselect:function(a){var c=a.data("data.suggest");if(c){this.input.val(c.name).data("data.suggest",c).trigger("fb-select",c);this.trackEvent(this.name,"fb-select","index",a.prevAll().length)}},trackEvent:function(a,c,d,e){this.input.trigger("fb-track-event",{category:a,action:c,label:d,value:e})},hide_all:function(){this.pane.hide();this.input.trigger("fb-pane-hide",this)}};a.extend(a.suggest,
{defaults:{status:["Start typing to get suggestions...","Searching...","Select an item from the list:","Sorry, something went wrong. Please try again later"],soft:false,nomatch:"no matches",css:{pane:"fbs-pane",list:"fbs-list",item:"fbs-item",item_name:"fbs-item-name",selected:"fbs-selected",status:"fbs-status"},css_prefix:null,parent:null,animate:false,zIndex:null},strongify:function(b,c){var d,e=b.toLowerCase().indexOf(c.toLowerCase());if(e>=0){var f=c.length;d=document.createTextNode(b.substring(0,
e));var h=a("<strong>").text(b.substring(e,e+f)),e=document.createTextNode(b.substring(e+f));d=a("<div>").append(d).append(h).append(e)}else d=a("<div>").text(b);return d},keyCode:{CAPS_LOCK:20,CONTROL:17,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,INSERT:45,LEFT:37,NUMPAD_ENTER:108,PAGE_DOWN:34,PAGE_UP:33,RIGHT:39,SHIFT:16,SPACE:32,TAB:9,UP:38,OPTION:18,APPLE:224},is_char:function(b){if(b.type==="keypress"){if((b.metaKey||b.ctrlKey)&&b.charCode===118)return true;if("isChar"in b)return b.isChar}else{var c=
a.suggest.keyCode.not_char;if(!c){c={};a.each(a.suggest.keyCode,function(a,b){c[""+b]=1});a.suggest.keyCode.not_char=c}return!(""+b.keyCode in c)}},parse_input:function(b){for(var c=/(\S+)\:(?:\"([^\"]+)\"|(\S+))/g,d=b,e=[],f={},g=c.exec(b);g;){g[1]in h?f[g[1]]=a.isEmptyObject(g[2])?g[3]:g[2]:e.push(g[0]);d=d.replace(g[0],"");g=c.exec(b)}d=a.trim(d.replace(/\s+/g," "));return[d,e,f]},mqlkey_fast:/^[_A-Za-z0-9][A-Za-z0-9_-]*$/,mqlkey_slow:/^(?:[A-Za-z0-9]|\$[A-F0-9]{4})(?:[A-Za-z0-9_-]|\$[A-F0-9]{4})*$/,
check_mql_key:function(b){return a.suggest.mqlkey_fast.test(b)||a.suggest.mqlkey_slow.test(b)?true:false},check_mql_id:function(b){if(b.indexOf("/")===0){b=b.split("/");b.shift();if(!(b.length==1&&b[0]===""))for(var c=0,d=b.length;c<d;c++)if(!a.suggest.check_mql_key(b[c]))return false;return true}return false}});var f=a.suggest.prototype._destroy,d=a.suggest.prototype.show_hook;a.suggest("suggest",{_init:function(){var b=this,c=this.options;if(c.flyout_service_url==null)c.flyout_service_url=c.service_url;
this.flyout_url=c.flyout_service_url;if(c.flyout_service_path)this.flyout_url=this.flyout_url+c.flyout_service_path;this.flyout_url=this.flyout_url.replace(/\$\{key\}/g,c.key);if(c.flyout_image_service_url==null)c.flyout_image_service_url=c.service_url;this.flyout_image_url=c.flyout_image_service_url;if(c.flyout_image_service_path)this.flyout_image_url=this.flyout_image_url+c.flyout_image_service_path;this.flyout_image_url=this.flyout_image_url.replace(/\$\{key\}/g,c.key);if(!a.suggest.cache)a.suggest.cache=
{};if(c.flyout){this.flyoutpane=a('<div style="display:none;" class="fbs-reset">').addClass(c.css.flyoutpane);if(c.flyout_parent)a(c.flyout_parent).append(this.flyoutpane);else{this.flyoutpane.css("position","absolute");c.zIndex&&this.flyoutpane.css("z-index",c.zIndex);a(document.body).append(this.flyoutpane)}this.flyoutpane.hover(function(a){b.hoverover_list(a)},function(a){b.hoverout_list(a)}).bind("mousedown.suggest",function(a){a.stopPropagation();b.pane.click()});if(!a.suggest.flyout)a.suggest.flyout=
{};if(!a.suggest.flyout.cache)a.suggest.flyout.cache={}}},_destroy:function(){f.call(this);this.flyoutpane&&this.flyoutpane.remove();this.input.removeData("request.count.suggest");this.input.removeData("flyout.request.count.suggest")},shift_enter:function(){if(this.options.suggest_new){this.suggest_new();this.hide_all()}},hide_all:function(){this.pane.hide();this.flyoutpane&&this.flyoutpane.hide();this.input.trigger("fb-pane-hide",this);this.input.trigger("fb-flyoutpane-hide",this)},request:function(b,
c){var d=this,e=this.options,f=b,h=e.ac_param.filter||[],i=null;a.type(h)==="string"&&(h=[h]);h=h.slice();if(e.advanced){var g=a.suggest.parse_input(f),f=g[0];g[1].length&&h.push("(all "+g[1].join(" ")+")");i=g[2];if(a.suggest.check_mql_id(f)){h.push('(all mid:"'+f+'")');f=""}}g={};g[e.query_param_name]=f;if(c)g.cursor=c;a.extend(g,e.ac_param,i);if(h.length)g.filter=h;var s=e.service_url+e.service_path+"?"+a.param(g,true);if(f=a.suggest.cache[s])this.response(f,c?c:-1,true);else{clearTimeout(this.request.timeout);
var m={url:e.service_url+e.service_path,data:g,traditional:true,beforeSend:function(){var a=d.input.data("request.count.suggest")||0;a||d.trackEvent(d.name,"start_session");a=a+1;d.trackEvent(d.name,"request","count",a);d.input.data("request.count.suggest",a)},success:function(e){a.suggest.cache[s]=e;e.prefix=b;d.response(e,c?c:-1)},error:function(a){d.status_error();d.trackEvent(d.name,"request","error",{url:this.url,response:a?a.responseText:""});d.input.trigger("fb-error",Array.prototype.slice.call(arguments))},
complete:function(a){a&&d.trackEvent(d.name,"request","tid",a.getResponseHeader("X-Metaweb-TID"))},dataType:"jsonp",cache:true};this.request.timeout=setTimeout(function(){a.ajax(m)},e.xhr_delay)}},create_item:function(b,c){var d=this.options.css,e=a("<li>").addClass(d.item),f=a("<label>").append(a.suggest.strongify(b.name||b.id,c.prefix)),h=a("<div>").addClass(d.item_name).append(f);b.under&&a(":first",f).append(a("<small>").text(" ("+b.under+")"));e.append(h);f=b.notable;d=a("<div>").addClass(d.item_type);
f&&f.name?d.text(f.name):this.options.show_id&&b.id&&d.text(b.id);h.prepend(d);return e},mouseover_item_hook:function(a){a=a.data("data.suggest");this.options.flyout&&a&&this.flyout_request(a)},check_response:function(a){return a.prefix===this.input.val()},response_hook:function(b,c){this.flyoutpane&&this.flyoutpane.hide();c>0?a(".fbs-more",this.pane).remove():this.list.empty()},show_hook:function(b,c,e){d.apply(this,[b]);var f=this.options,h=this,g=this.pane,i=this.list,k=b.result,s=a(".fbs-more",
g),m=a(".fbs-suggestnew",g);a(".fbs-status",g);var o=b.correction;if(o&&o.length){var r=a('<a class="fbs-spell-link" href="#">').append(o[0]).bind("click.suggest",function(a){a.preventDefault();a.stopPropagation();h.input.val(o[0]).trigger("textchange")});h.status.empty().append("Search instead for ").append(r).show()}if(k&&k.length&&"cursor"in b){if(!s.length){k=a('<a class="fbs-more-link" href="#" title="(Ctrl+m)">view more</a>');s=a('<div class="fbs-more">').append(k);k.bind("click.suggest",function(b){b.preventDefault();
b.stopPropagation();b=a(this).parent(".fbs-more");h.more(b.data("cursor.suggest"))});i.after(s)}s.data("cursor.suggest",b.cursor);s.show()}else s.remove();if(f.suggest_new){if(!m.length){b=a('<button class="fbs-suggestnew-button">');b.text(f.suggest_new);m=a('<div class="fbs-suggestnew">').append('<div class="fbs-suggestnew-description">Your item not in the list?</div>').append(b).append('<span class="fbs-suggestnew-shortcut">(Shift+Enter)</span>').bind("click.suggest",function(a){a.stopPropagation();
h.suggest_new(a)});g.append(m)}m.show()}else m.remove();if(e&&e.length&&c>0){c=e.prevAll().length*e.outerHeight();i.scrollTop();i.animate({scrollTop:c},"slow",function(){e.trigger("mouseover.suggest")})}},suggest_new:function(){var a=this.input.val();if(a!==""){this.input.data("data.suggest",a).trigger("fb-select-new",a);this.trackEvent(this.name,"fb-select-new","index","new");this.hide_all()}},more:function(a){if(a){var c=this.input.data("original.suggest");c!==null&&this.input.val(c);this.request(this.input.val(),
a);this.trackEvent(this.name,"more","cursor",a)}return false},flyout_request:function(b){var c=this,d=this.options,e=this.flyoutpane.data("data.suggest");if(e&&b.id===e.id){if(!this.flyoutpane.is(":visible")){b=this.get_selected();this.flyout_position(b);this.flyoutpane.show();this.input.trigger("fb-flyoutpane-show",this)}}else if((e=a.suggest.flyout.cache[b.id])&&e.id&&e.html)this.flyout_response(e);else{var f=b.id,h={url:this.flyout_url.replace(/\$\{id\}/g,b.id),traditional:true,beforeSend:function(){var a=
c.input.data("flyout.request.count.suggest")||0,a=a+1;c.trackEvent(c.name,"flyout.request","count",a);c.input.data("flyout.request.count.suggest",a)},success:function(b){b["req:id"]=f;b.html=a.suggest.suggest.create_flyout(b,c.flyout_image_url);a.suggest.flyout.cache[f]=b;c.flyout_response(b)},error:function(a){c.trackEvent(c.name,"flyout","error",{url:this.url,response:a?a.responseText:""})},complete:function(a){a&&c.trackEvent(c.name,"flyout","tid",a.getResponseHeader("X-Metaweb-TID"))},dataType:"jsonp",
cache:true};if(d.flyout_lang)h.data={lang:d.flyout_lang};clearTimeout(this.flyout_request.timeout);this.flyout_request.timeout=setTimeout(function(){a.ajax(h)},d.xhr_delay);this.input.trigger("fb-request-flyout",h)}},flyout_response:function(a){var c=this.pane,d=this.get_selected()||[];if(c.is(":visible")&&d.length)if((c=d.data("data.suggest"))&&a["req:id"]===c.id&&a.html){this.flyoutpane.html(a.html);this.flyout_position(d);this.flyoutpane.show().data("data.suggest",c);this.input.trigger("fb-flyoutpane-show",
this)}},flyout_position:function(b){if(!this.options.flyout_parent){var c=this.pane,d=this.flyoutpane,f=this.options.css,h=e,g=parseInt(d.css("top"),10),i=parseInt(d.css("left"),10),k=c.offset(),s=c.outerWidth(),m=d.outerHeight(),o=d.outerWidth();if(this.options.flyout==="bottom"){h=k;s=this.input.offset();h.top=k.top<s.top?h.top-m:h.top+c.outerHeight();d.addClass(f.flyoutpane+"-bottom")}else{h=b.offset();b=b.outerHeight();h.left=h.left+s;var r=h.left+o,c=a(document.body).scrollLeft(),q=a(window).width()+
c;h.top=h.top+b-m;if(h.top<k.top)h.top=k.top;if(r>q){k=h.left-(s+o);if(k>c)h.left=k}d.removeClass(f.flyoutpane+"-bottom")}h.top===g&&h.left===i||d.css({top:h.top,left:h.left})}},hoverout_list:function(){this.flyoutpane&&!this.get_selected()&&this.flyoutpane.hide()}});a.extend(a.suggest.suggest,{defaults:{filter:null,spell:"always",exact:false,scoring:null,lang:null,key:null,prefixed:true,stemmed:null,format:null,advanced:true,show_id:true,query_param_name:"query",service_url:"https://www.googleapis.com/freebase/v1",
service_path:"/search",align:null,flyout:true,flyout_service_url:null,flyout_service_path:"/topic${id}?filter=suggest&filter=/common/topic/article&key=${key}",flyout_image_service_url:null,flyout_image_service_path:"/image${id}?maxwidth=75&key=${key}",flyout_parent:null,suggest_new:null,nomatch:{title:"No suggested matches",heading:"Tips on getting better suggestions:",tips:["Enter more or fewer characters","Add words related to your original search","Try alternate spellings","Check your spelling"]},
css:{item_type:"fbs-item-type",flyoutpane:"fbs-flyout-pane"},xhr_delay:200},get_property:function(a,c){var d=a.property;return d?d[c]:null},get_values:function(b,c){var d=a.suggest.suggest.get_property(b,c);return d&&d.values?d.values:null},get_first_value:function(b,c){var d=a.suggest.suggest.get_values(b,c);return d&&d.length>0?d[0]:null},create_flyout:function(b,d){var e=a.suggest.suggest.get_property,f=a.suggest.suggest.get_values,h=a.suggest.suggest.get_first_value,g=h(b,"/type/object/name");
if(g)g=g.text;var i=h(b,"/common/topic/description")||h(b,"/common/topic/article")||false;if(i)i=i.text;(h=h(b,"/common/topic/image")||false)&&(h=d.replace(/\$\{id\}/g,b.id));var k=[],s=[b.id],m=f(b,"/common/topic/notable_properties");m&&a.each(m,function(d,c){var i=e(b,c.id);if(i&&i.valuetype!=="compound")if((i=f(b,c.id))&&i.length){i=a.map(i,function(a){return a.text}).join(", ");k.push([c.text||c.id,i])}});var m=f(b,"/common/topic/notable_for"),o=f(b,"/common/topic/notable_types");if(m||o){var r=
{},s=[];a.each([m,o],function(a,b){b&&b.forEach(function(a){if(a.id&&!r[a.id]){s.push(a.text);r[a.id]=true}})})}var s=s.join(", "),q=a('<div class="fbs-flyout-content">');g&&q.append(a('<h1 id="fbs-flyout-title">').text(g));q.append(a('<h3 class="fbs-topic-properties fbs-flyout-id">').text(b.id));a.each(k,function(b,d){q.append(a('<h3 class="fbs-topic-properties">').append(a("<strong>").text(d[0]+": ")).append(document.createTextNode(d[1])))});i&&q.append(a('<p class="fbs-topic-article">').text(i));
if(h){q.children().addClass("fbs-flyout-image-true");q.prepend(a('<img id="fbs-topic-image" class="fbs-flyout-image-true" src="'+h+'">'))}g=a('<span class="fbs-flyout-types">').append(s);g=a('<div class="fbs-attribution">').append(g);return a("<div>").append(q).append(g).html()}});document.createElement("input")})(jQuery);(function(a){window.freebase=window.fb={mwLWTReloading:false};window.SERVER&&typeof window.SERVER==="object"&&a.extend(window.freebase,window.SERVER);a.cookie=window.freebase.cookie})(jQuery);
(function(a,e){if(!e.datelineReloading){if(!window.console)window.console={log:a.noop,info:a.noop,debug:a.noop,warn:a.noop,error:a.noop};e.dispatch=function(b,d,c,e){if(typeof d!=="function")return false;b=a.event.fix(b||window.event);c||(c=[]);e||(e=this);return d.apply(e,[b].concat(c))};e.get_script=function(b,d){var c=e.get_script.cache,f=c[b];if(f)f.state===1?f.callbacks.push(d):f.state===4&&d();else{f=c[b]={state:0,callbacks:[d]};a.ajax({url:b,dataType:"script",beforeSend:function(){f.state=
1},success:function(){f.state=4;a.each(f.callbacks,function(a,b){b()})},error:function(a,b,d){f.state=-1;console.error("fb.get_script error",arguments)}})}};e.get_script.cache={};a(window).bind("fb.user.signedin",function(b,d){e.user=d;var c=a("#nav-username");if(c.length){a("> a",c).text(d.name);c[0].href=c[0].href+e.user.id.substring(1);var f=e.h.image_url(d.id,{maxwidth:25,maxheight:25,mode:"fillcropmid"}),f=a('<a class="user-thumb" href="'+d.id+'"><img src="'+f+'" /></a>');c.prepend(f)}a("#signedin").show();
a(".signedin").show()}).bind("fb.user.signedout",function(){a("#signedout").show();a(".signedout").show()}).bind("fb.user.unauthorized",function(){window.location.href=e.h.fb_url("/account/signin",{onsignin:window.location.href})}).bind("fb.user.feedback",function(a,b){if(confirm("Uh oh! Something went wrong. Please report this using our feedback tool."))try{userfeedback.api.startFeedback({productId:"68931",disableScrolling:false},b);return false}catch(d){}});var g=a.cookie("fb-account-name");if(g){var h=
{id:"/user/"+g,name:g};setTimeout(function(){a(window).trigger("fb.user.signedin",h);var b=e.h.ajax_url("lib/template/refresh_credentials"),d=a("<iframe name='rc'></iframe>").attr("src",b).hide().appendTo("body").load(function(){var c=parseInt(a("body",window.rc.document).text(),10)-(new Date).getTime();c&&c>0&&setTimeout(function(){a(d).attr("src",b)},c)})},0)}else setTimeout(function(){a(window).trigger("fb.user.signedout")},0);e.window_position=function(){var a={};if(typeof window.innerWidth==
"number"){a.width=window.outerWidth;a.height=window.outerHeight;a.top=window.screenY;a.left=window.screenX}else if(document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)){a.width=document.body.clientWidth;a.height=document.body.clientHeight;a.top=window.screenTop;a.left=window.screenLeft}return a};var f=function(){c&&c.slideUp(300);t=null;return false},d=function(d,e,h,g){if(c===null){c=a("#page-state");j=a(".status-msg",c);p=a(".close-msg",c);p.click(f)}if(t===
"error")console.warn("MessagePanel: Already displaying error. Ignoring: ",d,e);else{c.hide();a.each(b,function(a,b){c.removeClass(b)});c.addClass(d);j.text(e);t=d;window.clearTimeout(l);if(g){p.show();c.slideDown(300)}else{p.hide();c.slideDown(300);l=window.setTimeout(f,h)}}return false},b=["notice","info","warning","success","error"],c=null,j=null,p=null,l=null,t=null;e.status={doing:function(a){return d("notice",a,2E6,false)},info:function(a,b){return d("info",a,4E3,b)},warning:function(a,b){return d("warning",
a,4E3,b)},success:function(a,b){return d("success",a,6E3,b)},error:function(a,b){return d("error",a,6E3,b)},sprintf:function(b,c){var e=Array.prototype.slice.call(arguments).slice(2),f=c.split("%s");if(f.length>1&&e.length>1&&e.length%2==0){for(var h=a("<span>"),g=0,l=f.length;g<l;g++){h.append(document.createTextNode(f[g]));var p=a('<a href="#">');p.text(e.shift());var n=e.shift();a.type(n)==="function"&&p.click(n);h.append(p)}e=d(b,"",null,true);j.empty().append(h);return e}return d(b,c,null,true)},
clear:function(){window.clearTimeout(l);t==="error"?console.warn("MessagePanel: Displaying error. Ignoring clearing status."):f()}};e.popup=function(a,b,d,c){var b=b||300,d=d||300,f=e.window_position(),h=Math.floor((f.width-b)/2)+f.left,f=Math.floor((f.height-d)/2)+f.top;/chrome/.test(navigator.userAgent.toLowerCase())&&(d=d+50);var b={width:b,height:d,top:f,left:h,directories:"no",location:"no",menubar:"no",resizable:"no",scrollbars:"yes",status:"no",toolbar:"no"},d=[],g;for(g in b)d.push(g+"="+
b[g]);return window.open(a,c||"",d.join())};e.login_popup=function(a){a||(a=function(){window.location.reload()});var b=e.popup("/account/signin",900,600,"Freebase");if(b.opener==null)b.opener=self;window.onsignin=a;window.focus&&b.focus();return false};e.logout_popup=function(a){a||(a=function(){window.location.reload()});var b=e.popup("/account/signout",900,600,"Freebase");if(b.opener==null)b.opener=self;window.onsignout=a;window.focus&&b.focus();return false};a(function(){var b=a("#header > #nav-utilities > .language-picker"),
d=a(".current-lang",b);a("select",b).bind("change",function(){var b=a(this).find(":selected").text();d.text(b)})});a(function(){e.suggest_lang={SUPPORTED:{en:1,es:1,fr:1,de:1,it:1,pt:1,zh:1,ja:1,ko:1,ru:1,sv:1,fi:1,da:1,nl:1,el:1,ro:1,tr:1,hu:1},lang:function(a){a=e.h.lang_code(a||e.lang||"/lang/en");return e.suggest_lang.SUPPORTED[a]&&a!=="en"?a+",en":"en"}};e.suggest_options={service_defaults:{status:["","Searching...","Select an item from the list:"],service_url:e.h.fb_googleapis_url(),key:e.acre.freebase.api_key,
lang:e.suggest_lang.lang()},filter:{operator:function(){var a=Array.prototype.slice.call(arguments),b=a.shift();if(!(b==="any"||b==="all"||b==="should"))throw"Invalid search operator: "+b;var d=[b];if(b==="should"&&a.length>1){a=["any"].concat(a);d.push(e.suggest_options.filter.operator.apply(null,a))}else d=d.concat(a);return"("+d.join(" ")+")"},any:function(){var a=Array.prototype.slice.call(arguments);a.unshift("any");return e.suggest_options.filter.operator.apply(null,a)},all:function(){var a=
Array.prototype.slice.call(arguments);a.unshift("all");return e.suggest_options.filter.operator.apply(null,a)},should:function(){var a=Array.prototype.slice.call(arguments);a.unshift("should");return e.suggest_options.filter.operator.apply(null,a)}},any:function(){var b=a.extend({},e.suggest_options.service_defaults);b.filter=e.suggest_options.filter.any.apply(null,arguments);return b},all:function(){var b=a.extend({},e.suggest_options.service_defaults);b.filter=e.suggest_options.filter.all.apply(null,
arguments);return b},should:function(){var b=a.extend({},e.suggest_options.service_defaults);b.filter=e.suggest_options.filter.should.apply(null,arguments);return b},search:function(){return a.extend({},e.suggest_options.service_defaults,{status:null,parent:"#site-search-box",align:"right",filter:"(not type:/common/document)"})},instance:function(b,d,c){var f=["type:"+b];a.each(["user","domain","type"],function(a,d){if(b==="/freebase/"+d+"_profile"){f.push("type:/type/"+d);return false}});b==="/book/book_subject"&&
f.push("type:/base/skosbase/skos_concept");var h=null;if(e.h.is_metaweb_system_type(b))h=e.suggest_options.any.apply(null,f);else{h=e.suggest_options.should.apply(null,f);if(d)h.suggest_new="Create new"}if(c)h.lang=e.suggest_lang.lang(c);return h},cotype:function(){return a.extend({scoring:"schema"},e.suggest_options.all.apply(null,["type:/type/type","(not namespace:/type)","(not namespace:/freebase)","(any (not namespace:/common) (any mid:/m/01c5 mid:/m/02_1_m4 mid:/m/03hc3d_))"]))},included_type:function(){return e.suggest_options.cotype()},
expected_type:function(){return a.extend({scoring:"schema"},e.suggest_options.all.apply(null,["type:/type/type"]))},delegate_property:function(){return a.extend({scoring:"schema"},e.suggest_options.all.apply(null,["type:/type/property","(not namespace:/type/object)"]))}}});a(function(){var b=a("#SearchBox .SearchBox-input,#fb-search-input"),d=a("#fb-search");b.suggest(e.suggest_options.search());var c=a("#site-search-label"),f=a("#site-search-box .fbs-pane");b.bind("fb-select",function(b,d){var c=
{};a(this).siblings("input[type=hidden]").each(function(){c[this.name]=this.value});window.location=e.h.fb_url(d.id,c);return false}).bind("fb-pane-show",function(){c.html("<span>Select an item from the list</span>").removeClass("loading")}).bind("fb-textchange",function(){a.trim(b.val())===""?c.html("<span>Start typing to get some suggestions</span>").removeClass("loading"):c.html("<span>Searching...</span>").addClass("loading")}).bind("fb-error",function(){c.html("<span>Sorry, something went wrong. Please try again later</span>").removeClass("loading")}).focus(function(){if(!c.is(":visible")){a("#site-search-label").slideDown("fast");
d.addClass("active")}}).blur(function(){if(!f.is(":visible")&&c.is(":visible")){a("#site-search-label").slideUp("fast");d.removeClass("active")}});a(".SearchBox-form").submit(function(){return a.trim(a("#fb-search-input").val()).length==0?false:true})});e.disable=function(b){a(b).attr("disabled","disabled").addClass("disabled")};e.enable=function(b){a(b).removeAttr("disabled").removeClass("disabled")};e.lang_select=function(b,d){if(d==="/lang/en"){a(this).removeAttr("name");if(!a(":input[name]",this.form).length){window.location=
a(this.form).attr("action");return}}this.form.submit()};e.devbar={div:a("#devbar"),touch:function(){/\.(freebase|sandbox\-freebase)\.com$/.test(e.acre.request.server_name)?a.ajax({url:e.acre.freebase.googleapis_url?e.h.fb_googleapis_url("/touch"):e.h.fb_api_url("/api/service/touch"),dataType:"jsonp"}):a.ajax({url:"/acre/touch"});return false},txn_ids:[],txn:function(){return e.devbar.view_txn(this.href,e.devbar.txn_ids)},view_txn:function(b,d){if(d&&d.length)window.location=b+"?"+a.param({tid:d},
true);return false},ajaxComplete:function(a){if(a&&a.readyState===4)(a=a.getResponseHeader("x-metaweb-tid"))&&e.devbar.txn_ids.push(a)},init:function(){$nav_user_controls=a(".nav-user-controls");$user_controls=a("#user-controls");a("#signedin .trigger").click(function(){if($user_controls.is(":hidden")){$user_controls.fadeIn();$nav_user_controls.addClass("active")}else{$user_controls.fadeOut();$nav_user_controls.removeClass("active")}return false});a("html").click(function(){if($user_controls.is(":visible")){$user_controls.fadeOut();
$nav_user_controls.removeClass("active")}});$user_controls.click(function(a){a.stopPropagation()});a("#devbar-touch > a").click(e.devbar.touch);e.tid&&e.devbar.txn_ids.push(e.tid);a("#devbar-txn > a").click(e.devbar.txn);a.ajaxSetup({complete:function(){e.devbar.ajaxComplete.apply(null,arguments)},error:function(b){a.each(["url","data","dataType","type"],function(){});a.each(["status","statusText","responseText"],function(){});b.getAllResponseHeaders()}})}};e.devbar.init();e.mqlread=function(b,d,
c){var f;if(e.acre.freebase.googleapis_url){f=e.h.fb_googleapis_url("/mqlread");b={query:JSON.stringify(b),key:e.acre.freebase.api_key}}else{f=e.h.fb_api_url("/api/service/mqlread");b={query:JSON.stringify({query:b})}}return a.ajax({url:f,data:b,dataType:"jsonp",success:function(a){d&&d.apply(this,[a.result])},error:function(){c&&c.apply(this,arguments)}})};a(function(){e.hover={pane:"#fb-topic-hover-pane",current_target:null,cache:{},topic_url:e.h.fb_googleapis_url()+"/topic${id}?filter=suggest&limit=3&key="+
e.acre.freebase.api_key+"&lang="+e.h.lang_code(e.lang),image_url:e.h.fb_googleapis_url()+"/image${id}?maxwidth=75&key="+e.acre.freebase.api_key,show:function(){function b(){if(d===e.hover.current_target){a(e.hover.pane).html(e.hover.cache[c]);var f=a(e.hover.pane).height(),h=a(d).height(),g=a(d).offset(),i=g.left,g=g.top,g=g-a(document).scrollTop()+f<a(window).height()?g+h:g-f-h;a(e.hover.pane).css({top:g,left:i}).show()}}var d=this,c=a(d).attr("data-id");if(c){e.hover.current_target=d;a(d).removeAttr("title");
e.hover.cache[c]?b():a.ajax({url:e.hover.topic_url.replace(/\$\{id\}/g,c),success:function(d){d=a.suggest.suggest.create_flyout(d,e.hover.image_url);e.hover.cache[c]=d;b()},dataType:"jsonp",cache:true})}},hide:function(){e.hover.current_target=null;a(e.hover.pane).hide()}};a("#page-content").on("mouseover","a.property-value",e.hover.show).on("mouseout","a.property-value",e.hover.hide)})}})(jQuery,window.freebase);
(function(a,e){var g;if(!(g=a.type)){var h={};["Boolean","Number","String","Function","Array","Date","RegExp","Object"].forEach(function(a){h["[object "+a+"]"]=a.toLowerCase()});g=function(a){return a==null?String(a):h[Object.prototype.toString.call(a)]||"object"}}var f=e.h={type:g,parse_params:function(d){if(a.isArray(d)){var b={};a.each(d,function(a,d){b[d[0]]=d[1]});return b}return d},build_url:function(d){if(d&&d.indexOf("//")!==0&&d.indexOf("://")===-1)throw"Host must contain scheme: "+d;var b=
d||"",c,e;if(arguments.length>1){c=Array.prototype.slice.call(arguments);c.shift();for(var h=[],g=0,t=c.length;g<t;g++){var i=c[g];if(f.type(i)==="string")h.push(i);else{for(e={};g<t;g++)e=a.extend(e,f.parse_params(c[g]));break}}c=h.join("")}if(c&&c.indexOf("/")!==0)throw"Path must begin with a '/': "+c;c&&(b=b+c);b===""&&(b="/");a.isEmptyObject(e)||(b=b+("?"+a.param(e,true)));return b},fb_url:function(){var a=Array.prototype.slice.call(arguments);a.unshift(null);e.lang&&e.lang!=="/lang/en"&&a.push({lang:f.lang_code(e.lang)});
return f.build_url.apply(null,a)},ajax_url:function(){var a=Array.prototype.slice.call(arguments);a.unshift("/ajax");return f.reentrant_url.apply(null,a)},static_url:function(){var a=Array.prototype.slice.call(arguments);a.unshift("/static");return f.reentrant_url.apply(null,a)},reentrant_url:function(a,b){var b=f.resolve_reentrant_path(b),b=b.replace(/^\/\//,a+"/"),c=Array.prototype.slice.call(arguments,2);c.unshift(b);c.unshift(null);return f.build_url.apply(null,c)},resolve_reentrant_path:function(a){a=
a||"";if(a.indexOf("//")==0)return a;if(a.indexOf("lib/")===0)return e.acre.current_script.app.path+a.substring(3);a&&a[0]!="/"&&(a="/"+a);return e.acre.request.script.app.path+a},legacy_fb_url:function(){var a=Array.prototype.slice.call(arguments),b=e.acre.freebase.site_host.replace(/^(https?\:\/\/)([^\.]+)\./,"$1www.").replace(":"+e.acre.request.server_port,"");a.unshift(b);return f.build_url.apply(null,a)},fb_api_url:function(){var a=Array.prototype.slice.call(arguments);a.unshift(e.acre.freebase.service_url);
return f.build_url.apply(null,a)},fb_googleapis_url:function(){if(e.acre.freebase.googleapis_url){var a=Array.prototype.slice.call(arguments);a.unshift(e.acre.freebase.googleapis_url);return f.build_url.apply(null,a)}throw"fb.acre.freebase.googleapis_url is not defined";},wiki_url:function(a){var b=Array.prototype.slice.call(arguments);b.unshift("http://wiki.freebase.com","/wiki/");return f.build_url.apply(null,b)},lib_base_url:function(a){a=e.acre.metadata.libs[a];return a.base_url+a.version},image_url:function(a,
b){return e.acre.freebase.imgurl(a,b.maxwidth,b.maxheight,b.mode,b.pad,b.errorid)},is_metaweb_system_type:function(a){return a.indexOf("/type/")===0||a.indexOf("/common/")===0&&a!=="/common/topic"||a.indexOf("/freebase/")===0&&a.indexOf("_profile")===a.length-8},id_key:function(a,b){var c=a.split("/"),e=c.pop();if(b){c=c.join("/");c===""&&(c="/");return[c,e]}return e},lang_code:function(a){return f.id_key(a)},lang_id:function(a){return"/lang/"+f.lang_code(a)}}})(jQuery,window.freebase);
(function(a,e){var g=e.permission={init:function(){if(e.user){var h=e.c;h&&h.id&&a.ajax({url:e.h.ajax_url("lib/permission/has_permission.ajax"),data:{id:h.id,user_id:e.user.id},dataType:"json",success:function(e){g.has_permission=e.result&&e.result[h.id]===true;a(window).trigger("fb.permission.has_permission",g.has_permission)}});check_permissioned_objects(a(".edit-perm"),e.user.id)}else setTimeout(function(){g.has_permission=false;a(window).trigger("fb.permission.has_permission",g.has_permission)})}};
a(window).bind("fb.user.signedin",g.init);a(window).bind("fb.user.signedout",g.init);a(window).bind("fb.permission.has_permission",function(e,f){f?a(".edit").show():a(".no-edit").show()})})(jQuery,window.freebase);
function check_permissioned_objects(a,e){if(a.length&&e){var g={},h=[];$.each(a,function(){var a=$(this).metadata().id;if(a&&!g[a]){h.push(a);g[a]=1}});h.length&&$.ajax({url:fb.h.ajax_url("lib/permission/has_permission.ajax"),data:{id:h,user_id:e},traditional:true,dataType:"json",success:function(e){var d=e.result||{};$.each(a,function(){var a=$(this).metadata().id;a&&d[a]===true?$(this).show():$(this).addClass("edit-perm-lock")})}})}}
(function(a,e){var g=e.incompatible_types={overlay_dialog:null,inline_dialog:null,check:function(h,f,d){d=d||{};a.ajax({url:e.h.ajax_url("lib/incompatible_types/incompatible_types.ajax"),data:{id:h,type:f},dataType:"json",beforeSend:function(){e.status.doing("Checking compatibility...")},success:function(b){var b=b.result,c=false;a.isEmptyObject(b)||a.each(b,function(a){if(a!=="included_types"){c=true;return false}});c?d.incompatible&&d.incompatible(h,f,b):d.compatible&&d.compatible(h,f,b)},error:function(a){e.status.error(a.responseText)},
complete:function(){e.status.clear()}})},overlay_suggest_incompatible_callback:function(e,f){if(!g.overlay_dialog)g.overlay_dialog=a(".incompatible-overlay-dialog");if(g.overlay_dialog.length){f=f||{};return function(d,b,c){g.overlay_dialog.removeData("overlay");a(".modal-content",g.overlay_dialog).empty().append(g.description_html(d,b,c));a(".incompatible-topic",g.overlay_dialog).text(e.val());g.overlay_dialog.overlay({close:"button",closeOnClick:false,load:true,fixed:false,mask:{color:"#000",loadSpeed:200,
opacity:0.5},onClose:function(){e.focus().select();a("button",g.overlay_dialog).unbind();if(f.onClose)f.onClose()},onLoad:function(){a(".cancel",g.overlay_dialog).focus().click(function(){e.focus().select().trigger("textchange");if(f.onCancel)f.onCancel()});a(".save",g.overlay_dialog).click(function(){e.focus().select();if(f.onConfirm)f.onConfirm(d,b,c)});if(f.onLoad)f.onLoad()}})}}return g.native_confirm_suggest_incompatible_callback(e,f)},inline_suggest_incompatible_callback:function(e,f){if(!g.inline_dialog)g.inline_dialog=
a(".incompatible-inline-dialog");if(g.inline_dialog.length){f=f||{};return function(d,b,c){a(".modal-content",g.inline_dialog).empty().append(g.description_html(d,b,c));a(".incompatible-topic",g.inline_dialog).text(e.val());a(".save",g.inline_dialog).unbind().click(function(){e.focus().select();if(f.onConfirm)f.onConfirm(d,b,c);g.inline_dialog.hide(f.onClose)});a(".cancel",g.inline_dialog).unbind().click(function(){e.focus().select().trigger("textchange");if(f.onCancel)f.onCancel();g.inline_dialog.hide(f.onClose)});
var j=e.offsetParent(),p=e.position();j.append(g.inline_dialog);g.inline_dialog.css({top:p.top+e.outerHeight(),left:p.left});g.inline_dialog.show(f.onLoad)}}return g.native_confirm_suggest_incompatible_callback(e,f)},native_confirm_suggest_incompatible_callback:function(a,e){e=e||{};return function(d,b,c){if(confirm(g.description_text(d,b,c))){a.focus().select();if(e.onConfirm)e.onConfirm(d,b,c)}else{a.focus().select().trigger("textchange");if(e.onCancel)e.onCancel()}if(e.onClose)e.onClose();a.focus().select()}},
description_html:function(e,f,d){var b=a("<div>"),c;if(d[f]){c=a('<div><span class="incompatible-topic"></span> is already typed as <ul class="incompatible-existing"></ul>It\'s unlikely it should also be typed as <b class="incompatible-type"></b>.</div>');a(".incompatible-topic",c).text(e);var g=a(".incompatible-existing",c);a.each(d[f],function(b,c){g.append(a("<li>").append(a("<b>").text(c)))});a(".incompatible-type",c).text(f);b.append(c)}var p=[f],l=[];d.included_types&&a.each(d.included_types,
function(a,b){d[b]?l.push(b):p.push(b)});c=a('<div>If you continue, <span class="incompatible-topic"></span> will be typed as <ul class="incompatible-to-type"></ul></div>');a(".incompatible-topic",c).text(e);g=a(".incompatible-to-type",c);a.each(p,function(b,c){g.append(a("<li>").append(a("<b>").text(c)))});if(l.length){c.append('&nbsp;It will <b>*not*</b> be typed as <ul class="incompatible-not-to-type"></ul>');g=a(".incompatible-not-to-type",c);a.each(l,function(b,c){g.append(a("<li>").append(a("<b>").text(c)))})}b.append(c);
b.append("<p>Are you sure you want to continue?<p>");return b},description_text:function(a,e,d){return g.description_html(a,e,d).text()}}})(jQuery,window.freebase);
(function(a,e){var g=e.flag={merge:function(a){return g.flag(a,"merge_begin")},split:function(a){return g.flag(a,"split_begin")},"delete":function(a){return g.flag(a,"delete_begin")},offensive:function(a){return g.flag(a,"offensive_begin")},flag:function(h,f){h=a(h);e.get_script(e.h.static_url("lib/flag/flag-edit.mf.js"),function(){g.edit[f](h)});return false},undo:function(h,f){h=a(h);e.get_script(e.h.static_url("lib/flag/flag-edit.mf.js"),function(){g.edit.undo_begin(h,f)});return false}}})(jQuery,
window.freebase);
