
/*
 * Copyright 2012, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Additional Licenses for Third Party components can be found here:
 * http://wiki.freebase.com/wiki/Freebase_Site_License
 *
 */
/*
 
 jQuery Tools @VERSION / Expose - Dim the lights

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/toolbox/expose.html

 Since: Mar 2010
 Date: @DATE 
 
 jQuery Tools @VERSION Overlay - Overlay base. Extend it.

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/overlay/

 Since: March 2008
 Date: @DATE 
*/
(function(f){function e(){if(f.browser.msie){var i=f(document).height(),k=f(window).height();return[window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth,i-k<20?k:i]}return[f(document).width(),f(document).height()]}function b(i){if(i)return i.call(f.mask)}f.tools=f.tools||{version:"@VERSION"};var a;a=f.tools.expose={conf:{maskId:"exposeMask",loadSpeed:"slow",closeSpeed:"fast",closeOnClick:true,closeOnEsc:true,zIndex:9998,opacity:0.8,startOpacity:0,color:"#fff",onLoad:null,
onClose:null}};var c,d,g,h,j;f.mask={load:function(i,k){if(g)return this;if(typeof i=="string")i={color:i};i=i||h;h=i=f.extend(f.extend({},a.conf),i);c=f("#"+i.maskId);if(!c.length){c=f("<div/>").attr("id",i.maskId);f("body").append(c)}var m=e();c.css({position:"absolute",top:0,left:0,width:m[0],height:m[1],display:"none",opacity:i.startOpacity,zIndex:i.zIndex});i.color&&c.css("backgroundColor",i.color);if(b(i.onBeforeLoad)===false)return this;i.closeOnEsc&&f(document).bind("keydown.mask",function(l){l.keyCode==
27&&f.mask.close(l)});i.closeOnClick&&c.bind("click.mask",function(l){f.mask.close(l)});f(window).bind("resize.mask",function(){f.mask.fit()});if(k&&k.length){j=k.eq(0).css("zIndex");f.each(k,function(){var l=f(this);/relative|absolute|fixed/i.test(l.css("position"))||l.css("position","relative")});d=k.css({zIndex:Math.max(i.zIndex+1,j=="auto"?0:j)})}c.css({display:"block"}).fadeTo(i.loadSpeed,i.opacity,function(){f.mask.fit();b(i.onLoad)});g=true;return this},close:function(){if(g){if(b(h.onBeforeClose)===
false)return this;c.fadeOut(h.closeSpeed,function(){b(h.onClose);d&&d.css({zIndex:j})});f(document).unbind("keydown.mask");c.unbind("click.mask");f(window).unbind("resize.mask");g=false}return this},fit:function(){if(g){var i=e();c.css({width:i[0],height:i[1]})}},getMask:function(){return c},isLoaded:function(){return g},getConf:function(){return h},getExposed:function(){return d}};f.fn.mask=function(i){f.mask.load(i);return this};f.fn.expose=function(i){f.mask.load(i,this);return this}})(jQuery);
(function(f){function e(c,d){var g=this,h=c.add(g),j=f(window),i,k,m,l=f.tools.expose&&(d.mask||d.expose),p=Math.random().toString().slice(10);if(l){if(typeof l=="string")l={color:l};l.closeOnClick=l.closeOnEsc=false}var o=d.target||c.attr("rel");k=o?f(o):c;if(!k.length)throw"Could not find Overlay: "+o;c&&c.index(k)==-1&&c.click(function(n){g.load(n);return n.preventDefault()});f.extend(g,{load:function(n){if(g.isOpened())return g;var q=a[d.effect];if(!q)throw'Overlay: cannot find effect : "'+d.effect+
'"';d.oneInstance&&f.each(b,function(){this.close(n)});n=n||f.Event();n.type="onBeforeLoad";h.trigger(n);if(n.isDefaultPrevented())return g;m=true;l&&f(k).expose(l);var r=d.top,t=d.left,u=k.outerWidth({margin:true}),v=k.outerHeight({margin:true});if(typeof r=="string")r=r=="center"?Math.max((j.height()-v)/2,0):parseInt(r,10)/100*j.height();if(t=="center")t=Math.max((j.width()-u)/2,0);q[0].call(g,{top:r,left:t},function(){if(m){n.type="onLoad";h.trigger(n)}});l&&d.closeOnClick&&f.mask.getMask().one("click",
g.close);d.closeOnClick&&f(document).bind("click."+p,function(s){f(s.target).parents(k).length||g.close(s)});d.closeOnEsc&&f(document).bind("keydown."+p,function(s){s.keyCode==27&&g.close(s)});return g},close:function(n){if(!g.isOpened())return g;n=n||f.Event();n.type="onBeforeClose";h.trigger(n);if(!n.isDefaultPrevented()){m=false;a[d.effect][1].call(g,function(){n.type="onClose";h.trigger(n)});f(document).unbind("click."+p).unbind("keydown."+p);l&&f.mask.close();return g}},getOverlay:function(){return k},
getTrigger:function(){return c},getClosers:function(){return i},isOpened:function(){return m},getConf:function(){return d}});f.each("onBeforeLoad,onStart,onLoad,onBeforeClose,onClose".split(","),function(n,q){f.isFunction(d[q])&&f(g).bind(q,d[q]);g[q]=function(r){f(g).bind(q,r);return g}});i=k.find(d.close||".close");if(!i.length&&!d.close){i=f('<a class="close"></a>');k.prepend(i)}i.click(function(n){g.close(n)});d.load&&g.load()}f.tools=f.tools||{version:"@VERSION"};f.tools.overlay={addEffect:function(c,
d,g){a[c]=[d,g]},conf:{close:null,closeOnClick:true,closeOnEsc:true,closeSpeed:"fast",effect:"default",fixed:!f.browser.msie||f.browser.version>6,left:"center",load:false,mask:null,oneInstance:true,speed:"normal",target:null,top:"10%"}};var b=[],a={};f.tools.overlay.addEffect("default",function(c,d){var g=this.getConf(),h=f(window);if(!g.fixed){c.top+=h.scrollTop();c.left+=h.scrollLeft()}c.position=g.fixed?"fixed":"absolute";this.getOverlay().css(c).fadeIn(g.speed,d)},function(c){this.getOverlay().fadeOut(this.getConf().closeSpeed,
c)});f.fn.overlay=function(c){var d=this.data("overlay");if(d)return d;if(f.isFunction(c))c={onBeforeLoad:c};c=f.extend(true,{},f.tools.overlay.conf,c);this.each(function(){d=new e(f(this),c);b.push(d);f(this).data("overlay",d)});return c.api?d:this}})(jQuery);
(function(f){f.fn.mqlkey=function(b){return this.each(function(){var a=f(this);if(a.is(":text")){var c=a.data("mqlkey");c&&c._destroy();c=new e(this,b);a.data("mqlkey",c)}})};var e=f.mqlkey=function(b,a){this.options=f.extend(true,{},e.defaults,a);this.input=f(b);this.original=this.input.val();this.init()};e.prototype={init:function(){var b=this;this.input.bind("keyup.mqlkey",function(a){b.textchange(a)}).bind(f.browser.msie?"paste.mqlkey":"input.mqlkey",function(a){b.textchange(a)});if(this.options.source){this.source=
f(this.options.source);this.source_generate=true;this.input.bind("change.mqlkey",function(){b.source_generate=false});this.source.bind("change.mqlkey",function(){if(b.source_generate){var a=e.from(b.source.val());b.input.val(a).trigger("keyup")}})}},_destroy:function(){this.input.unbind(".mqlkey");this.source&&this.source.unbind("change.mqlkey")},textchange:function(b){clearTimeout(this.textchange_timeout);var a=this;this.textchange_timeout=setTimeout(function(){a.textchange_delay(b)},200)},textchange_delay:function(){this.input.trigger("textchange");
var b=f.trim(this.input.val());return b===this.original&&b!==""?this.valid(b):e.reserved_word(b)?this.invalid(b,b+" is a reserved word."):e.test(b,this.options.schema)?b.length<this.options.minlen?this.invalid(b):this.options.check_key?this.check_key(b):this.valid(b):this.invalid(b)},check_key:function(b){var a=this;if(this.xhr)this.xhr=null;var c={id:null,key:{namespace:this.options.namespace,value:b}};clearTimeout(this.check_key.timeout);this.check_key.timeout=setTimeout(function(){a.xhr=a.options.mqlread(c,
function(d){return d?a.invalid(b,"Key already exists"):a.valid(b)},function(d){return d?a.invalid(d.responseText()):a.invalid("mqlread error!")})},200)},valid:function(b){this.input.trigger("valid",b)},invalid:function(b,a){if(!a){a=this.options.minlen>1?"Key must be "+this.options.minlen+" or more alphanumeric characters":"Key must be alphanumeric";a+=", lowercase, begin with a letter and not end with a non-alphanumeric character. Underscores are allowed but not consecutively."}this.input.trigger("invalid",
a)}};f.extend(e,{defaults:{minlen:1,check_key:true,namespace:"/",mqlread:function(b,a,c){return e.mqlread(null,b,a,c)},source:null,schema:false},mqlread:function(b,a,c,d){b={url:b||"http://api.freebase.com/api/service/mqlread",data:{query:JSON.stringify({query:a})},dataType:"jsonp",success:function(g){return c(g.result)},error:d};return f.ajax(b)},from:function(b){b=b.toLowerCase();b=b.replace(/[^a-z0-9]/g,"_");b=b.replace(/\_\_+/g,"_");b=b.replace(/[^a-z0-9]+$/,"");b=b.replace(/^[^a-z]+/,"");if(e.reserved_word(b))b=
"x_"+b;return b},reservedwords:"meta typeguid left right datatype scope attribute relationship property link class future update insert delete replace create destroy default sort limit offset optional pagesize cursor index !index for while as in is if else return count function read write select var connect this self super xml sql mql any all macro estimate-count",typeonlywords:"guid id object domain name key type keys value timestamp creator permission namespace unique schema reverse",_reserved_word:null,
reserved_word:function(b){if(!e._reserved_word){e._reserved_word={};f.each([e.reservedwords,e.typeonlywords],function(a,c){f.each(c.split(" "),function(d,g){e._reserved_word[g]=1})})}return e._reserved_word[b]===1},fast:/^[A-Za-z0-9](?:[_-]?[A-Za-z0-9])*$/,slow:/^(?:[A-Za-z0-9]|\$[A-F0-9]{4})(?:[_-]?[A-Za-z0-9]|[_-]?\$[A-F0-9]{4})*$/,schema:/^[a-z](?:_?[a-z0-9])*$/,test:function(b,a){if(a)return e.schema.test(b);return e.fast.test(b)||e.slow.test(b)}})})(jQuery);
(function(f){f.fn.validate_input=function(b){return this.each(function(){var a=f(this);if(a.is(":text")){var c=a.data("$.validate_input");c&&c._destroy();c=new e(this,b);a.data("$.validate_input",c)}})};var e=f.validate_input=function(b,a){if(typeof(this.options=f.extend(true,{},e.defaults,a)).validator!=="function")throw"A validator is required";this.input=f(b);this.init();var c=this;this.input.bind("remove",function(){c._destroy()});return this};e.prototype={init:function(){var b=this;this.input.bind("keyup.validate_input",
function(a){b.textchange(a)}).bind(f.browser.msie?"paste.validate_input":"input.validate_input",function(a){b.textchange(a)}).bind("keypress.validate_input",function(a){a.keyCode===13&&b.validate(true)}).bind("blur.validate_input",function(){b.validate(true)})},_destroy:function(){this.input.unbind(".validate_input")},valid:function(b){this.input.trigger("valid",b)},invalid:function(b,a){this.input.trigger("invalid",a)},empty:function(){this.input.trigger("empty")},textchange:function(){clearTimeout(this.textchange_timeout);
var b=this;this.textchange_timeout=setTimeout(function(){b.validate()},200)},validate:function(b){b&&clearTimeout(this.textchange_timeout);b=this.options;var a=f.trim(this.input.val());if(a==="")return this.empty();try{return this.valid(b.validator(a,b))}catch(c){return this.invalid(a,""+c)}}};f.extend(e,{defaults:{validator:function(b){return{text:b,value:b}}},log:function(){},invalid:function(b,a,c,d){throw new Error("Invalid "+c+(d?": "+d:""));},text:function(b,a){if(b.lengh>4096)return this.invalid(b,
a,type,"Text too long");return{text:b,value:b}},topic:function(){return e.defaults.validator},enumerated:function(){return e.defaults.validator},"boolean":function(){return e.defaults.validator},uri:function(b,a){var c=e.uri.regex;if(!c)c=e.uri.regex=/^(https?|ftp):\/\/(((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:)*@)?(((\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5]))|((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?)(:\d*)?)(\/((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)+(\/(([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)*)*)?)?(\?((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|[\uE000-\uF8FF]|\/|\?)*)?(\#((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|\/|\?)*)?$/i;
if(c.test(b))return{text:b,value:b};return e.invalid(b,a,"uri")},"int":function(b,a){return e.number.parse(b,a,false)},"float":function(b,a){return e.number.parse(b,a,true)},number:function(b,a,c){return e.number.parse(b,a,c)},datetime:function(b,a){return e.datetime.parse(b,a)},mqlkey:function(b,a){var c=e.mqlkey.regex;if(!c)c=e.mqlkey.regex=/^[A-Za-z0-9][A-Za-z0-9_-]*$/;if(c.test(b))return{text:b,value:b};return e.invalid(b,a,"mqlkey")}});f.extend(e.number,{parse:function(b,a,c){a=null;a=c?Globalize.parseFloat(b):
Globalize.parseInt(b);if(isNaN(a))throw e.invalid("number",b);if(c){b="n";c=""+a;var d=c.indexOf(".");if(d!==-1)b="n"+c.substr(d+1).length;return{value:a,text:Globalize.format(a,b)}}else return{value:a,text:Globalize.format(a,"n0")}}});f.extend(e.datetime,{regexp:{iso:/^(?:(-?\d{4})(?:-(\d{2})(?:-(\d{2}))?)?)?(?:T(\d{2}):(\d{2})(?::(\d{2})(.\d+)?)?((?:[+-](\d{2}):(\d{2}))|Z)?)?$/,time:/^T?([01][0-9]|2[0-3])(:[0-5][0-9]){0,2}$/,bce:[/^(\d+)\s*[Bb]\.*[Cc]\.*[Ee]*/,/^[Bb]\.*[Cc]\.*[Ee]*\s*(\d+)/]},formats:["d",
"yyyy-MM-dd","Y","yyyy-MM","t","HH:mm","T","HH:mm:ss"],padyear:function(b){if(b<10)return"000"+b;else if(b<100)return"00"+b;else if(b<1E3)return"0"+b;return""+b},parse:function(b){var a,c,d;if(e.datetime.regexp.iso.test(b)||e.datetime.regexp.time.test(b)){c=b;if(c.indexOf("T")===0)c=c.substring(1);return{text:b,value:c}}c=0;for(d=e.datetime.regexp.bce.length;c<d;c++)if(a=e.datetime.regexp.bce[c].exec(b)){c=parseInt(a[1],10);c-=1;c=e.datetime.padyear(c);return{text:b,value:"-"+c}}c=0;for(d=e.datetime.formats.length;c<
d;c+=2)if(a=Globalize.parseDate(b,e.datetime.formats[c]))return{text:b,value:Globalize.format(a,e.datetime.formats[c+1])};if(a=Globalize.parseDate(b))return{text:b,value:Globalize.format(a,"S")};throw e.invalid("datetime",b);}})})(jQuery,window.Globalize);
(function(f){f.fn.data_input=function(e){return this.each(function(){var b=f(this),a=b.data("$.data_input");a&&a._destroy();a=new f.data_input(this,e);b.data("$.data_input",a)})};f.data_input=function(e,b){this.options=f.extend(true,{},b);this.container=f(e);this.metadata=this.container.metadata();this.input=f(":input",this.container);this.init();var a=this;this.input.bind("remove",function(){a._destroy()})};f.data_input.prototype={init:function(){var e=this,b=this.container,a=this.input,c=this.options;
a.bind("focusin.data_input",function(){e.container.addClass("focus")}).bind("focusout.data_input",function(){e.container.removeClass("focus")}).bind("valid.data_input",function(g,h){g.stopPropagation();var j={name:e.input.attr("name")};if(h.id)j.id=h.id;else if(h.create_new){j.create_new=h.create_new;j.lang=e.metadata.lang||c.lang}else{j.value=h.value;if(e.metadata.type==="/type/text")j.lang=e.metadata.lang||c.lang;else if(e.metadata.type==="/type/key")j.namespace=h.namespace}if(h.incompatible_types)j.incompatible_types=
h.incompatible_types;e.container.data("data",j);e.container.removeClass("error").addClass("valid");e.container.trigger("valid")}).bind("invalid.data_input",function(g){g.stopPropagation();e.container.removeData("data");e.container.removeClass("valid").addClass("error");e.container.trigger("invalid")}).bind("empty.data_input",function(g){g.stopPropagation();g={name:e.input.attr("name")};if(e.metadata&&e.metadata.lang)g.lang=e.metadata.lang;e.container.data("data",g);e.container.removeClass("valid").removeClass("error");
e.container.trigger("empty")}).bind("keypress.data_input",function(g){g.keyCode===13&&!g.isDefaultPrevented()&&e.container.trigger("submit")}).bind("keyup.data_input",function(g){g.keyCode===27&&e.container.trigger("cancel")});if(b.is(".topic")){b=e.metadata.type;var d=null;if(c.suggest_impl)d=c.suggest_impl.instance(b,true,e.metadata&&e.metadata.lang||c.lang);a.validate_topic(f.extend({incompatible_types:e.options.incompatible_types,expected_type:b},d)).bind("valid.data_input",function(g,h){e.fb_select(h)}).bind("invalid.data_input",
function(){e.fb_textchange()});if(this.metadata&&this.metadata.id){a.data("data.suggest",this.metadata);this.validate()}}else if(b.is(".text"))a.validate_input({validator:f.validate_input.text});else if(b.is(".datetime"))a.validate_input({validator:f.validate_input.datetime,lang:c.lang});else if(b.is(".enumerated")){a.validate_enumerated().bind("valid.data_input",function(g,h){e.fb_select(h)}).bind("invalid.data_input",function(){e.fb_textchange()});this.metadata&&this.metadata.id&&this.validate()}else if(b.is(".int"))a.validate_input({validator:f.validate_input["int"],
lang:c.lang});else if(b.is(".float"))a.validate_input({validator:f.validate_input["float"],lang:c.lang});else if(b.is(".uri"))a.validate_input({validator:f.validate_input.uri});else if(b.is(".boolean"))a.validate_boolean();else if(b.is(".enumeration"))a.validate_input({validator:f.validate_input.mqlkey});else if(b.is(".key"))a.validate_key(c,this.metadata);else if(b.is(".rawstring"))a.validate_input({validator:f.validate_input.text});else throw new Error("Invalid data-input: "+b.attr("class"));},
_destroy:function(){this.input.unbind(".data_input")},validate:function(){var e=this.input;f.each(["$.validate_topic","$.validate_input","$.validate_enumerated","$.validate_boolean","$.validate_key"],function(b,a){var c=e.data(a);if(c){c.validate(true);return false}})},reset:function(){this.container.removeData("data");if(this.input.is(":text"))this.input.val("");else if(this.input.is("select"))this.input[0].selectedIndex=0;else this.input.is(":radio")&&this.input.each(function(){this.checked=false})},
fb_textchange:function(){},fb_select:function(){},ajax_beforeSend:function(e){if(!this.xhr_queue)this.xhr_queue=[];this.xhr_queue.push(e);this.container.trigger("loading")},ajax_complete:function(e){if(!this.xhr_queue)this.xhr_queue=[];for(var b=0,a=this.xhr_queue.length;b<a;b++)if(e===this.xhr_queue[b]){this.xhr_queue.splice(b,1);break}this.xhr_queue.length===0&&this.container.trigger("loading_complete")}};f.fn.validate_topic=function(e){return this.each(function(){var b=f(this);if(b.is(":text")){var a=
b.data("$.validate_topic");a&&a._destroy();a=new f.validate_topic(this,e);b.data("$.validate_topic",a)}})};f.validate_topic=function(e,b){this.options=f.extend(true,{},b);this.input=f(e);this.init()};f.validate_topic.prototype={init:function(){var e=this;this.incompatible_types={};this.input.suggest(this.options).bind("fb-textchange.validate_topic",function(){e.input.val()===""?e.empty():e.invalid()}).bind("fb-select.validate_topic",function(b,a){e.input.val(a.name!=null?a.name:a.id);e.incompatible_types_check(a)}).bind("fb-select-new.validate_topic",
function(b,a){e.valid(a)})},incompatible_types_check:function(e){var b=this;b.options.incompatible_types&&b.options.expected_type?b.options.incompatible_types.check(e.id,b.options.expected_type,{compatible:function(){b.valid(e)},incompatible:b.options.incompatible_types.inline_suggest_incompatible_callback(b.input,{onConfirm:function(a,c,d){b.incompatible_types[a]=d;b.valid(e)}})}):this.valid(e)},invalid:function(){this.input.trigger("invalid")},valid:function(e){if(typeof e==="string")e={create_new:e};
if(e.id&&this.incompatible_types[e.id])e.incompatible_types=this.incompatible_types[e.id];this.input.trigger("valid",e)},empty:function(){this.input.trigger("empty")},_destroy:function(){this.input.unbind(".validate_topic")},validate:function(){if(this.input.val()==="")this.empty();else{var e=this.input.data("data.suggest");e?this.valid(e):this.invalid()}}};f.fn.validate_enumerated=function(e){return this.each(function(){var b=f(this);if(b.is("select")){var a=b.data("$.validate_enumerated");a&&a._destroy();
a=new f.validate_enumerated(this,e);b.data("$.validate_enumerated",a)}})};f.validate_enumerated=function(e,b){this.options=f.extend(true,{},b);this.input=f(e);this.init()};f.validate_enumerated.prototype={init:function(){var e=this;this.input.bind("change.validate_enumerated, keypress.validate_enumerated",function(){this.selectedIndex===0?e.empty():e.valid({text:f(":selected",this).text(),id:this.value})})},invalid:function(){this.input.trigger("invalid")},valid:function(e){this.input.trigger("valid",
e);this.input.trigger("fb-select",e)},empty:function(){this.input.trigger("empty")},_destroy:function(){this.input.unbind(".validate_enumerated")},validate:function(){var e=this.input[0];e.selectedIndex>0?this.valid({text:f(":selected",this.input).text(),id:e.value}):this.empty()}};f.fn.validate_boolean=function(e){var b,a;this.each(function(){var d=f(this);if(d.is(":radio"))if(d.val().toLowerCase()==="true")b=d;else if(d.val().toLowerCase()==="false")a=d});if(b&&a){var c=b.data("$.validate_boolean");
c&&c._destroy();c=new f.validate_boolean(b,a,e);b.data("$.validate_boolean",c)}else throw"$.fn.validate_boolean requires two radios: true and false";return this};f.validate_boolean=function(e,b,a){this.options=f.extend(true,{},a);this.tradio=e;this.fradio=b;this.input=this.tradio;this.init()};f.validate_boolean.prototype={init:function(){var e=this;this.tradio.bind("change.validate_boolean",function(){e.validate()})},_destroy:function(){this.input.unbind(".validate_boolean")},valid:function(e){this.input.trigger("valid",
e)},empty:function(){this.input.trigger("empty")},validate:function(){if(this.tradio.is(":checked"))this.valid({text:this.tradio.text(),value:true});else this.fradio.is(":checked")?this.valid({text:this.fradio.text(),value:false}):this.empty()}};f.fn.validate_key=function(e,b){var a,c;this.each(function(){var g=f(this);if(g.is(":text"))if(g.is(".key-namespace"))a=g;else if(g.is(".key-value"))c=g});if(a&&c){var d=c.data("$.validate_key");d&&d._destroy();d=new f.validate_key(a,c,e);a.data("$.validate_key",
d);if(b&&b.namespace&&b.value){a.data("data.suggest",{id:b.namespace});c.val(b.value)}}else throw"$.fn.validate_key requires two inputs: namespace and value";return this};f.validate_key=function(e,b,a){this.options=f.extend(true,{},a);this.key_namespace_input=e;this.key_value_input=b;this.input=this.key_namespace_input;this.init()};f.validate_key.prototype={init:function(){var e=this,b=null;if(this.options.suggest_impl)b=this.key_value_input.attr("name")!="/type/namespace/keys"?this.options.suggest_impl.instance("/type/namespace"):
f.extend({},this.options.suggest_impl.service_defaults);this.key_namespace_input.suggest(b).bind("fb-textchange.validate_key",function(){e.validate()}).bind("fb-select.validate_key",function(a,c){e.key_namespace_input.val(c.name||c.id);e.validate()});this.key_value_input.validate_input({validator:f.validate_input.mqlkey}).bind("valid",function(a){a.stopPropagation();e.validate()}).bind("invalid",function(a){a.stopPropagation();e.validate()}).bind("empty",function(a){a.stopPropagation();e.validate()})},
_destroy:function(){this.key_namespace_input.unbind(".validate_key");this.key_value_input.unbind()},invalid:function(){this.input.trigger("invalid")},valid:function(e){this.input.trigger("valid",e)},empty:function(){this.input.trigger("empty")},validate:function(){if(this.is_valid_key_namespace()&&this.is_valid_key_value())this.valid({namespace:this.key_namespace_input.data("data.suggest").id,value:this.key_value_input.val(),text:this.key_value_input.val()});else this.key_namespace_input.val()===
""&&this.key_value_input.val()===""?this.empty():this.invalid()},is_valid_key_namespace:function(){return this.key_namespace_input.data("data.suggest")!=null},is_valid_key_value:function(){try{f.validate_input.mqlkey(this.key_value_input.val());return true}catch(e){return false}}}})(jQuery);
(function(f,e){var b=window.formlib={status:e,init:function(a){var c=a.event_prefix||"form.";a.form.bind(c+"submit",function(){b.submit(a)}).bind(c+"cancel",function(){b.cancel(a)}).bind(c+"error",function(d,g){a.form.removeClass("loading");b.disable_submit(a);e.error(g,true)}).bind(c+"success",function(){a.form.removeClass("loading")}).bind(c+"valid",function(){b.enable_submit(a)}).bind(c+"invalid",function(){b.disable_submit(a)});b.init_submit_cancel(a);a.init(a)},submit:function(a){if(!a.form.is(".loading"))if(b.is_submit_enabled(a)){document.activeElement&&
f(document.activeElement).blur();if(a.validate(a)){a.form.addClass("loading");a.submit(a,b.default_submit_ajax_options(a))}}},cancel:function(){},init_inline_add_form:function(a){var c=a.event_prefix||"form.inline_add_form.";a.edit_row.bind(c+"submit",function(){b.submit_inline_add_form(a)}).bind(c+"cancel",function(){b.cancel_inline_add_form(a)}).bind(c+"error",function(d,g){a.edit_row.removeClass("loading");b.disable_submit(a);e.error(g,true)}).bind(c+"success",function(){a.edit_row.removeClass("loading")}).bind(c+
"valid",function(){b.enable_submit(a)}).bind(c+"invalid",function(){b.disable_submit(a)});b.init_submit_cancel(a);a.trigger&&a.trigger.parents(".trigger-row:first").hide();a.body.append(a.edit_row).append(a.submit_row);a.init(a)},submit_inline_add_form:function(a){if(!a.edit_row.is(".loading"))if(b.is_submit_enabled(a)){document.activeElement&&f(document.activeElement).blur();if(a.validate(a)){a.edit_row.addClass("loading");a.submit(a,b.default_submit_ajax_options(a))}}},success_inline_add_form:function(a,
c){a.edit_row.before(c);a.reset(a);a.edit_row.trigger(a.event_prefix+"success")},cancel_inline_add_form:function(a){a.edit_row.remove();a.submit_row.remove();a.trigger&&a.trigger.parents(".trigger-row:first").show()},init_inline_edit_form:function(a){var c=a.event_prefix||"form.inline_edit_form.";a.edit_row.bind(c+"submit",function(){b.submit_inline_edit_form(a)}).bind(c+"cancel",function(){b.cancel_inline_edit_form(a)}).bind(c+"error",function(d,g){a.edit_row.removeClass("loading");b.disable_submit(a);
e.error(g,true)}).bind(c+"success",function(){a.edit_row.removeClass("loading")}).bind(c+"valid",function(){b.enable_submit(a)}).bind(c+"invalid",function(){b.disable_submit(a)});b.init_submit_cancel(a);a.row.hide();a.row.before(a.edit_row).before(a.submit_row);a.init(a)},submit_inline_edit_form:function(a){if(!a.edit_row.is(".loading"))if(b.is_submit_enabled(a)){document.activeElement&&f(document.activeElement).blur();if(a.validate(a)){a.edit_row.addClass("loading");a.submit(a,b.default_submit_ajax_options(a))}}},
success_inline_edit_form:function(a,c){a.row.replaceWith(c);a.row=c;a.edit_row.trigger(a.event_prefix+"cancel")},cancel_inline_edit_form:function(a){a.edit_row.remove();a.submit_row.remove();a.row.show()},success_inline_delete:function(a,c,d){a.hide().addClass("old-row");a.after(c);c.append(a);if(d){a=f('<a href="#">Undo</a>');f(".msg-default",c).next().append(a);a.click(function(){d();return false})}},success_inline_delete_undo:function(a){var c=f(".old-row",a);a.before(c);c.show().removeClass("old-row");
a.remove()},init_modal_form:function(a){f(document.body).append(a.form.hide());var c=a.event_prefix||"form.modal_form.";a.form.bind(c+"submit",function(){b.submit_modal_form(a)}).bind(c+"cancel",function(){b.cancel_modal_form(a)}).bind(c+"error",function(d,g){a.form.removeClass("loading");b.disable_submit(a);e.error(g,true)}).bind(c+"success",function(){a.form.removeClass("loading")}).bind(c+"valid",function(){b.enable_submit(a)}).bind(c+"invalid",function(){b.disable_submit(a)});b.init_submit_cancel(a);
a.form.data("overlay")&&a.form.removeData("overlay");a.form.overlay({close:".modal-buttons .cancel",closeOnClick:false,load:true,fixed:false,mask:{color:"#000",loadSpeed:200,opacity:0.5},onLoad:function(){a.overlay=this;a.init(a)}})},submit_modal_form:function(a){if(!a.form.is(".loading"))if(b.is_submit_enabled(a)){document.activeElement&&f(document.activeElement).blur();if(a.validate(a)){a.form.addClass("loading");a.submit(a,b.default_submit_ajax_options(a))}}},cancel_modal_form:function(a){a.form.data("overlay").close();
a.form.next("#exposeMask").hide()},init_submit_cancel:function(a){var c=a.form||a.edit_row,d=a.form||a.submit_row,g=a.event_prefix;a=f(".save",d).click(function(){c.trigger(g+"submit")});b.disable(a);f(".cancel",d).click(function(){c.trigger(g+"cancel")});f(":input",c).keyup(function(h){h.keyCode===27&&c.trigger(g+"cancel")})},disable:function(a){f(a).attr("disabled","disabled").addClass("disabled")},enable:function(a){f(a).removeAttr("disabled").removeClass("disabled")},disable_submit:function(a){b.disable(f(".save",
a.form||a.submit_row))},enable_submit:function(a){b.enable(f(".save",a.form||a.submit_row))},is_submit_enabled:function(a){return!f(".save",a.form||a.submit_row).is(":disabled")},init_mqlkey:function(a,c){return a.next(".key-status").removeClass("valid invalid loading").text("").removeAttr("title").end().mqlkey(c).bind("valid",function(){f(this).next(".key-status").removeClass("invalid loading").addClass("valid").text("valid").attr("title","Key is available")}).bind("invalid",function(d,g){f(this).next(".key-status").removeClass("valid loading").addClass("invalid").text("invalid").attr("title",
g)}).bind("textchange",function(){f(this).next(".key-status").removeClass("valid invalid").text("loading").addClass("loading")})},validate_mqlkey:function(a,c){var d=c.next(".key-status"),g=c.val();if(g===""){c.trigger(a.event_prefix+"error","Key is required");return false}if(g===c.data("mqlkey").original)return true;if(d.is(".invalid")){c.trigger(a.event_prefix+"error",d.attr("title"));return false}else if(d.is(".loading"))return false;return true},default_begin_ajax_options:function(){return f.extend(b._default_ajax_options("GET"),
{beforeSend:function(){e.doing("Loading...")},complete:function(){this.formlib_error||e.clear()}})},default_submit_ajax_options:function(a){a=a||{};var c=f.extend(b._default_ajax_options("POST"),a.ajax,{beforeSend:function(){this.formlib_options=a;e.doing("Saving...");f.isFunction(a.beforeSend)&&a.beforeSend.apply(this,arguments)},complete:function(){this.formlib_error||e.clear();f.isFunction(a.complete)&&a.complete.apply(this,arguments)}}),d=a.submit_row||a.form;d&&f("input[type=hidden]",d).each(function(){c.data[this.name]=
this.value});return c},_default_ajax_options:function(a){return{data:{},dataType:"json",type:a||"GET",success:function(c,d,g){if(!b.check_ajax_success(c,d,g))return this._error(g);f.isFunction(this.onsuccess)&&this.onsuccess(c,d,g)},error:function(c){return this._error(c)},_error:function(c){if(c.status===401){e.info("Authorizing...");f(window).trigger("fb.user.unauthorized")}else{console.error(c.responseText);this.formlib_error=true;var d=b.get_error_message(c.responseText);if(f.isFunction(this.onerror))this.onerror(d,
c);else{c=null;if(this.formlib_options)if(this.formlib_options.form){this.formlib_options.form.trigger(this.formlib_options.event_prefix+"cancel");c=this.formlib_options.form}else c=this.formlib_options.edit_row;c?c.trigger(this.formlib_options.event_prefix+"error",d):e.error(d,true)}}}}},check_ajax_success:function(a,c,d){return b.check_api_response(a,c,d)},check_api_response:function(a,c,d){if(f.isPlainObject(a)){if(a.code!=="/api/status/ok")return false}else if(d.status!==200)return false;return true},
get_error_message:function(a){var c=null;try{var d=JSON.parse(a);if(d&&f.isArray(d.messages)&&d.messages.length)c=d.messages[0].message}catch(g){}c||(c=a);return c}}})(jQuery,window.freebase.status);
(function(f){var e=window.editparams={Empty:function(b,a,c){this.structure=b;this.data=a;this.msg=c;this.toString=function(){return"Empty: "+this.msg}},Invalid:function(b,a,c){this.structure=b;this.data=a;this.msg=c;this.toString=function(){return"Invalid: "+this.msg}},parse:function(b,a){function c(i,k,m,l,p){try{e.validate(k,m);p.push(m)}catch(o){if(o instanceof e.Empty)p.push(m);else throw o;}}var d=(b.values||[]).slice(),g=b.properties||[],h=b.expected_type.mediator;if(h){if(!g.length)throw new e.Invalid(b,
null,"mediator musth have 1 or more properties");if(d.length&&d.length!==1)throw new e.Invalid(b,null,"Can't edit more than one value (row) for a mediator");}var j=[];f(".data-input",a).each(function(){var i=f(this),k=i.data("$.data_input");if(!k)throw new e.Invalid(b,null,"$.data-input not initialized for",this);k.validate(true);if(i.is(".error"))throw new e.Invalid(b,null,"$.data-input is invalid",this);k=i.data("data");if(!k)throw new e.Invalid(b,null,"$.data-input has no data",this);if(h){if(!j.length){j.push({property:{}});
f.each(g,function(p,o){j[0].property[o.id]=f.extend({},o,{values:[]})})}var m=j[0].property[k.name];if(m){var l=[];if(d.length)l=(l=d[0].property[m.id])&&l.values||[];c(i,m,k,l,m.values)}else console.warn("editparams","unknown mediator property data",k)}else c(i,b,k,d,j)});return h?e.parse_mediator(b,d,j):e.parse_simple(b,d,j)},parse_mediator:function(b,a,c){if(c.length!==1)throw new e.Invalid(b,c,"Must specify one (new or updated) value for a mediator");c=c[0];var d;if(a.length)d=a[0];a={};if(d)a.id=
d.id;else{a.id=null;a.create="unconditional";a.connect=b.unique?"replace":"insert";var g=[];b.expected_type.id!=="/type/object"&&g.push({id:b.expected_type.id,connect:"insert"});var h=b.expected_type.included_types;h&&f.each(h,function(p,o){o!=="/type/object"&&g.push({id:o,connect:"insert"})});if(g.length)a.type=g}h=false;b=b.properties;for(var j=0,i=b.length;j<i;j++){var k=b[j],m=d&&d.property&&d.property[k.id],l=c.property&&c.property[k.id];m=e.parse_simple(k,m&&m.values||[],l&&l.values||[]);if(m.length){a[k.id]=
m;h=true}}return h?[a]:[]},parse_simple:function(b,a,c){return e.diff(b,a,c)},diff:function(b,a,c){var d=b.expected_type,g=b.expected_type.id,h=b.unique,j=g==="/type/text",i=g==="/type/key";if(h)if(!j)if(a.length&&a.length!==1)throw new e.Invalid(b,a,"Can't edit more than one value (row) for a unique property.");else if(c.length&&c.length!==1)throw new e.Invalid(b,c,"Can't edit more than one value (row) for a unique property.");var k=[];if(e.LITERAL_TYPE_IDS[g]){k.push("value");if(j)k.push("lang");
else i&&k.push("namespace")}else k.push("id");g=[];var m=[],l,p;l=0;for(p=a.length;l<p;l++){var o=a[l];e.validate(b,o);e.inArray.apply(null,[o,c].concat(k))===-1&&g.push(e.clause(o,"delete"))}l=0;for(p=c.length;l<p;l++){o=c[l];try{e.validate(b,o)}catch(n){continue}if(e.inArray.apply(null,[o,a].concat(k))===-1){if(h)if(j){var q=e.inArray(o,g,"lang");q!==-1&&g.splice(q,1)}else if(!i)return[e.clause(o,"replace",d)];m.push(e.clause(o,h?"replace":"insert",d))}}return g.concat(m)},validate:function(b,a){var c=
b.expected_type.id;if(e.LITERAL_TYPE_IDS[c])if(e.isEmpty(a.value))throw new e.Empty(b,a);else{if(c==="/type/text"&&e.isEmpty(a.lang))throw new e.Invalid(b,a,"Expected data.lang for /type/text");else if(c==="/type/key"&&e.isEmpty(a.namespace))throw new e.Invalid(b,a,"Expected data.namespace for /type/key");if(c==="/type/int"||c==="/type/float"){if(f.type(a.value)!=="number")throw new e.Invalid(b,a,"Expected number data.value for "+c);}else if(c==="/type/boolean"){if(f.type(a.value)!=="boolean")throw new e.Invalid(b,
a,"Expected boolean data.value for /type/boolean");}else if(f.type(a.value)!=="string")throw new e.Invalid(b,a,"Expected string data.value for "+c);}else if(e.isEmpty(a.create_new)){if(e.isEmpty(a.id))throw new e.Empty(b,a);}else if(e.isEmpty(a.lang))throw new e.Invalid(b,a,"Expected lang for creating a new topic");return a},type_clause:function(b,a){a=a||{};var c=[];if(b){if(b.enumeration)return c;else if(b.never_assert)return c;b.id!=="/type/object"&&c.push({id:b.id,connect:"insert"});var d=b.included_types;
d&&f.each(d,function(g,h){h==="/type/object"||a[h]||c.push({id:h,connect:"insert"})})}return c},clause:function(b,a,c){var d={connect:a};if(b.id){d.id=b.id;if(a!=="delete"&&c&&!c.enumeration){b=e.type_clause(c,b.incompatible_types);if(b.length)d.type=b}}else if(b.create_new&&b.lang){d.name={value:b.create_new,lang:b.lang};d.id=null;d.create="unconditional";b=e.type_clause(c);if(b.length)d.type=b}else{d.value=b.value;if(b.lang)d.lang=b.lang;else if(b.namespace)d.namespace=b.namespace}return d},inArray:function(b,
a){var c=Array.prototype.slice.call(arguments,2);if(!c.length)return f.inArray(b,a);for(var d=0,g=a.length;d<g;d++){for(var h=a[d],j=true,i=0,k=c.length;i<k;i++){var m=c[i];if(h[m]!=b[m]){j=false;break}}if(j)return d}return-1},isEmpty:function(b){return b==null||b===""},LITERAL_TYPE_IDS:{"/type/int":1,"/type/float":1,"/type/boolean":1,"/type/rawstring":1,"/type/uri":1,"/type/text":1,"/type/datetime":1,"/type/id":1,"/type/key":1,"/type/value":1,"/type/enumeration":1}}})(jQuery);
(function(f,e,b,a){var c=e.edit={prop_add_begin:function(d){f.ajax(f.extend(b.default_begin_ajax_options(),{url:e.options.base_ajax_url+"/prop_add_begin.ajax",data:{s:e.options.id,p:d.attr("data-id"),lang:e.options.lang},onsuccess:function(g){g=f(g.result.html);var h=g.metadata(),j=h.expected_type.id;return j==="/common/document"?c.prop_add_document(d,g,h):j==="/common/image"?c.prop_add_image(d,g,h):c.prop_add(d,g,h)}}))},prop_add:function(d,g,h){d=f(">.data-section",d);d=f("> .data-table > tbody, > .data-list",
d);var j=f(".edit-row",g);g=f(".edit-row-submit",g);var i={event_prefix:"propbox.edit.prop_add.",init:c.init_prop_add_form,validate:c.validate_prop_add_form,submit:c.submit_prop_add_form,reset:c.reset_prop_add_form,ajax:{url:e.options.base_ajax_url+"/prop_edit_submit.ajax"},body:d,edit_row:j,submit_row:g,structure:h};j.bind("propbox.edit.prop_add.success",function(){h.unique&&j.trigger(i.event_prefix+"cancel")});b.init_inline_add_form(i)},init_prop_add_form:function(d){c.init_data_inputs(d);f(":input:visible:first",
d.edit_row).focus()},validate_prop_add_form:function(){return true},reset_prop_add_form:function(d){c.reset_data_inputs(d);b.disable_submit(d);f(".cancel",d.submit_row).text("Done");f(":input:visible:first",d.edit_row).focus()},submit_prop_add_form:function(d,g){try{var h=a.parse(d.structure,d.edit_row);g.data.o=JSON.stringify(h)}catch(j){h=f(".data-input.error",d.edit_row);if(h.length){d.edit_row.trigger(d.event_prefix+"error","Please specify a valid value");h.eq(0).find(":input").focus().select()}else d.edit_row.trigger(d.event_prefix+
"error",j.toString());return}h.length?f.ajax(f.extend(g,{onsuccess:function(i){i=f(i.result.html);b.success_inline_add_form(d,i);e.init_menus(i,true);f(".nicemenu-item.edit").show();e.kbs.set_next(null,i,true)}})):d.edit_row.trigger(d.event_prefix+"error","Please specify a valid value")},value_edit_begin:function(d,g){var h=null,j=null;if(g.is("tr"))h=g.attr("data-id");else{j=f(".property-value:first",g);h=j.attr("data-value")||j.attr("data-id")||j.attr("datetime");j=j.attr("data-namespace")}f.ajax(f.extend(b.default_begin_ajax_options(),
{url:e.options.base_ajax_url+"/value_edit_begin.ajax",data:{s:e.options.id,p:d.attr("data-id"),replace:h,namespace:j,lang:e.options.lang},onsuccess:function(i){i=f(i.result.html);var k=i.metadata(),m=k.expected_type.id;return m==="/common/document"?c.value_edit_document(d,g,i,k):m==="/common/image"?c.value_edit_image(d,g,i,k):c.value_edit(d,g,i,k)}}))},value_edit:function(d,g,h,j){var i=f(".edit-row",h);h=f(".edit-row-submit",h);j={event_prefix:"propbox.edit.value_edit.",init:c.init_value_edit_form,
validate:c.validate_value_edit_form,submit:c.submit_value_edit_form,ajax:{url:e.options.base_ajax_url+"/prop_edit_submit.ajax"},row:g,edit_row:i,submit_row:h,structure:j};i.bind("propbox.edit.value_edit.delete",function(){i.trigger("propbox.edit.value_edit.cancel");e.edit.value_delete_begin(d,g)});b.init_inline_edit_form(j)},init_value_edit_form:function(d){c.init_data_inputs(d);f(".delete",d.submit_row).click(function(){d.edit_row.trigger(d.event_prefix+"delete")});f(":input:visible:first",d.edit_row).focus()},
validate_value_edit_form:function(){return true},submit_value_edit_form:function(d,g){try{var h=a.parse(d.structure,d.edit_row);g.data.o=JSON.stringify(h)}catch(j){h=f(".data-input.error",d.edit_row);if(h.length){d.edit_row.trigger(d.event_prefix+"error","Please specify a valid value");h.eq(0).find(":input").focus().select()}else d.edit_row.trigger(d.event_prefix+"error",j.toString());return}f.ajax(f.extend(g,{onsuccess:function(i){i=f(i.result.html);b.success_inline_edit_form(d,i);e.init_menus(i,
true);f(".nicemenu-item.edit").show();e.kbs.set_next(null,i,true)}}))},value_delete_begin:function(d,g){var h=null,j=null;if(g.is("tr"))h=g.attr("data-id");else{j=f(".property-value:first",g);h=j.attr("data-value")||j.attr("data-id")||j.attr("datetime");j=j.attr("data-namespace")}var i={s:e.options.id,p:d.attr("data-id"),o:h,lang:e.options.lang,namespace:j};f.ajax(f.extend(b.default_submit_ajax_options(),{url:e.options.base_ajax_url+"/value_delete_submit.ajax",data:i,onsuccess:function(k){var m=f(k.result.html);
b.success_inline_delete(g,m,function(){f.ajax(f.extend(b.default_submit_ajax_options(),{url:e.options.base_ajax_url+"/value_delete_undo.ajax",data:i,onsuccess:function(){b.success_inline_delete_undo(m)}}))})}}))},prop_add_document:function(d,g,h){b.init_modal_form({event_prefix:"propbox.edit.prop_add_document.",init:c.init_prop_add_document_form,validate:c.validate_prop_add_document_form,submit:c.submit_prop_add_document_form,ajax:{url:e.options.base_ajax_url+"/prop_add_document_submit.ajax"},prop_section:d,
form:g,structure:h})},init_prop_add_document_form:function(d){var g=f("select[name=lang]",d.form);g.change(function(){var h=f(".lang-notice",d.form);if(this.value===e.options.lang)h.hide();else{f("strong",h).text(f("option:selected",g).text());h.show()}});f("textarea",d.form).bind("keypress",function(){d.form.trigger(d.event_prefix+"valid")}).bind("paste",function(){d.form.trigger(d.event_prefix+"valid")}).focus()},validate_prop_add_document_form:function(d){var g=f("textarea",d.form);if(f.trim(g.val())===
""){d.form.trigger(d.event_prefix+"invalid");g.focus();return false}return true},submit_prop_add_document_form:function(d,g){var h=f("textarea",d.form);g.data[h.attr("name")]=f.trim(h.val());g.data.lang=f("select[name=lang]",d.form).val();f.ajax(f.extend(g,{onsuccess:function(j){j=f(j.result.html);if(d.prop_row)d.prop_row.replaceWith(j);else{var i=f(">.data-section",d.prop_section);f("> .data-table > tbody, > .data-list",i).append(j)}e.init_menus(j,true);f(".nicemenu-item.edit").show();e.kbs.set_next(null,
j,true);d.form.trigger(d.event_prefix+"cancel")}}))},value_edit_document:function(d,g,h,j){g={event_prefix:"propbox.edit.value_edit_document.",init:c.init_value_edit_document_form,validate:c.validate_value_edit_document_form,submit:c.submit_value_edit_document_form,ajax:{url:e.options.base_ajax_url+"/prop_add_document_submit.ajax"},prop_section:d,prop_row:g,form:h,structure:j,cant_edit:h.is(".cant-edit-document-form")};g.cant_edit&&h.bind("propbox.edit.value_edit_document.submit",function(){h.trigger("propbox.edit.value_edit_document.cancel");
c.prop_add_begin(d)});b.init_modal_form(g)},init_value_edit_document_form:function(d){d.cant_edit?b.enable_submit(d):c.init_prop_add_document_form(d)},validate_value_edit_document_form:function(d){return d.cant_edit?true:c.validate_prop_add_document_form(d)},submit_value_edit_document_form:function(d,g){d.cant_edit||c.submit_prop_add_document_form(d,g)},prop_add_image:function(){alert("Add image not yet implemented")},value_edit_image:function(){alert("Edit image not yet implemented")},init_data_inputs:function(d){f(".data-input",
d.edit_row||d.form).each(function(){c.init_data_input(f(this),d)})},init_data_input:function(d,g){var h=g.edit_row||g.form;d.data_input({lang:e.options.lang,suggest_impl:e.options.suggest_impl,incompatible_types:e.options.incompatible_types}).bind("valid",function(){h.trigger(g.event_prefix+"valid");var j=d.parent(".form-field"),i=j.next(".magicbox-template");if(i.length){i=f("<div>").html(i.html());i=f(".form-field",i);j.after(i);c.init_data_input(f(".data-input",i),g)}}).bind("empty",function(){h.trigger(g.event_prefix+
"valid")}).bind("invalid",function(){h.trigger(g.event_prefix+"invalid")}).bind("submit",function(){h.trigger(g.event_prefix+"submit")}).bind("cancel",function(){h.trigger(g.event_prefix+"cancel")}).bind("loading",function(){f(this).addClass("loading")}).bind("loading_complete",function(){f(this).removeClass("loading")})},reset_data_inputs:function(d){f(".data-input",d.edit_row).each(function(){f(this).data("$.data_input").reset()})}}})(jQuery,window.propbox,window.formlib,window.editparams);
