
/*
 * Copyright 2012, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Additional Licenses for Third Party components can be found here:
 * http://wiki.freebase.com/wiki/Freebase_Site_License
 *
 */
/*
 
 jQuery Tools @VERSION / Expose - Dim the lights

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/toolbox/expose.html

 Since: Mar 2010
 Date: @DATE 
 
 jQuery Tools @VERSION Overlay - Overlay base. Extend it.

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/overlay/

 Since: March 2008
 Date: @DATE 
*/
(function(a){function c(){if(a.browser.msie){var b=a(document).height(),c=a(window).height();return[window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth,20>b-c?c:b]}return[a(document).width(),a(document).height()]}function d(b){if(b)return b.call(a.mask)}a.tools=a.tools||{version:"@VERSION"};var e;e=a.tools.expose={conf:{maskId:"exposeMask",loadSpeed:"slow",closeSpeed:"fast",closeOnClick:!0,closeOnEsc:!0,zIndex:9998,opacity:0.8,startOpacity:0,color:"#fff",onLoad:null,
onClose:null}};var b,h,f,g,k;a.mask={load:function(i,j){if(f)return this;"string"==typeof i&&(i={color:i});i=i||g;g=i=a.extend(a.extend({},e.conf),i);b=a("#"+i.maskId);b.length||(b=a("<div/>").attr("id",i.maskId),a("body").append(b));var l=c();b.css({position:"absolute",top:0,left:0,width:l[0],height:l[1],display:"none",opacity:i.startOpacity,zIndex:i.zIndex});i.color&&b.css("backgroundColor",i.color);if(!1===d(i.onBeforeLoad))return this;i.closeOnEsc&&a(document).bind("keydown.mask",function(b){b.keyCode==
27&&a.mask.close(b)});i.closeOnClick&&b.bind("click.mask",function(b){a.mask.close(b)});a(window).bind("resize.mask",function(){a.mask.fit()});j&&j.length&&(k=j.eq(0).css("zIndex"),a.each(j,function(){var b=a(this);/relative|absolute|fixed/i.test(b.css("position"))||b.css("position","relative")}),h=j.css({zIndex:Math.max(i.zIndex+1,"auto"==k?0:k)}));b.css({display:"block"}).fadeTo(i.loadSpeed,i.opacity,function(){a.mask.fit();d(i.onLoad)});f=!0;return this},close:function(){if(f){if(!1===d(g.onBeforeClose))return this;
b.fadeOut(g.closeSpeed,function(){d(g.onClose);h&&h.css({zIndex:k})});a(document).unbind("keydown.mask");b.unbind("click.mask");a(window).unbind("resize.mask");f=!1}return this},fit:function(){if(f){var a=c();b.css({width:a[0],height:a[1]})}},getMask:function(){return b},isLoaded:function(){return f},getConf:function(){return g},getExposed:function(){return h}};a.fn.mask=function(b){a.mask.load(b);return this};a.fn.expose=function(b){a.mask.load(b,this);return this}})(jQuery);
(function(a){function c(b,c){var f=this,g=b.add(f),k=a(window),i,j,l,m=a.tools.expose&&(c.mask||c.expose),o=Math.random().toString().slice(10);m&&("string"==typeof m&&(m={color:m}),m.closeOnClick=m.closeOnEsc=!1);var n=c.target||b.attr("rel");j=n?a(n):b;if(!j.length)throw"Could not find Overlay: "+n;b&&-1==b.index(j)&&b.click(function(a){f.load(a);return a.preventDefault()});a.extend(f,{load:function(b){if(f.isOpened())return f;var i=e[c.effect];if(!i)throw'Overlay: cannot find effect : "'+c.effect+
'"';c.oneInstance&&a.each(d,function(){this.close(b)});b=b||a.Event();b.type="onBeforeLoad";g.trigger(b);if(b.isDefaultPrevented())return f;l=true;m&&a(j).expose(m);var n=c.top,p=c.left,s=j.outerWidth({margin:true}),t=j.outerHeight({margin:true});typeof n=="string"&&(n=n=="center"?Math.max((k.height()-t)/2,0):parseInt(n,10)/100*k.height());p=="center"&&(p=Math.max((k.width()-s)/2,0));i[0].call(f,{top:n,left:p},function(){if(l){b.type="onLoad";g.trigger(b)}});if(m&&c.closeOnClick)a.mask.getMask().one("click",
f.close);c.closeOnClick&&a(document).bind("click."+o,function(b){a(b.target).parents(j).length||f.close(b)});c.closeOnEsc&&a(document).bind("keydown."+o,function(a){a.keyCode==27&&f.close(a)});return f},close:function(b){if(!f.isOpened())return f;b=b||a.Event();b.type="onBeforeClose";g.trigger(b);if(!b.isDefaultPrevented()){l=false;e[c.effect][1].call(f,function(){b.type="onClose";g.trigger(b)});a(document).unbind("click."+o).unbind("keydown."+o);m&&a.mask.close();return f}},getOverlay:function(){return j},
getTrigger:function(){return b},getClosers:function(){return i},isOpened:function(){return l},getConf:function(){return c}});a.each(["onBeforeLoad","onStart","onLoad","onBeforeClose","onClose"],function(b,e){a.isFunction(c[e])&&a(f).bind(e,c[e]);f[e]=function(b){a(f).bind(e,b);return f}});i=j.find(c.close||".close");!i.length&&!c.close&&(i=a('<a class="close"></a>'),j.prepend(i));i.click(function(a){f.close(a)});c.load&&f.load()}a.tools=a.tools||{version:"@VERSION"};a.tools.overlay={addEffect:function(a,
c,d){e[a]=[c,d]},conf:{close:null,closeOnClick:!0,closeOnEsc:!0,closeSpeed:"fast",effect:"default",fixed:!a.browser.msie||6<a.browser.version,left:"center",load:!1,mask:null,oneInstance:!0,speed:"normal",target:null,top:"10%"}};var d=[],e={};a.tools.overlay.addEffect("default",function(b,c){var e=this.getConf(),d=a(window);e.fixed||(b.top+=d.scrollTop(),b.left+=d.scrollLeft());b.position=e.fixed?"fixed":"absolute";this.getOverlay().css(b).fadeIn(e.speed,c)},function(a){this.getOverlay().fadeOut(this.getConf().closeSpeed,
a)});a.fn.overlay=function(b){var e=this.data("overlay");if(e)return e;a.isFunction(b)&&(b={onBeforeLoad:b});b=a.extend(!0,{},a.tools.overlay.conf,b);this.each(function(){e=new c(a(this),b);d.push(e);a(this).data("overlay",e)});return b.api?e:this}})(jQuery);
(function(a){a.fn.mqlkey=function(d){return this.each(function(){var e=a(this);if(e.is(":text")){var b=e.data("mqlkey");b&&b._destroy();b=new c(this,d);e.data("mqlkey",b)}})};var c=a.mqlkey=function(d,e){this.options=a.extend(!0,{},c.defaults,e);this.input=a(d);this.original=this.input.val();this.init()};c.prototype={init:function(){var d=this;this.input.bind("keyup.mqlkey",function(a){d.textchange(a)}).bind(a.browser.msie?"paste.mqlkey":"input.mqlkey",function(a){d.textchange(a)});this.options.source&&
(this.source=a(this.options.source),this.source_generate=""===this.source.val()?!0:!1,this.input.bind("change.mqlkey",function(){d.source_generate=!1}),this.source.bind("change.mqlkey",function(){if(d.source_generate){var a=c.from(d.source.val());d.input.val(a).trigger("keyup")}}))},_destroy:function(){this.input.unbind(".mqlkey");this.source&&this.source.unbind("change.mqlkey")},textchange:function(a){clearTimeout(this.textchange_timeout);var c=this;this.textchange_timeout=setTimeout(function(){c.textchange_delay(a)},
200)},textchange_delay:function(){this.input.trigger("textchange");var d=a.trim(this.input.val());return d===this.original&&""!==d?this.valid(d):c.reserved_word(d)?this.invalid(d,d+" is a reserved word."):c.test(d,this.options.schema)?d.length<this.options.minlen?this.invalid(d):this.options.check_key?this.check_key(d):this.valid(d):this.invalid(d)},check_key:function(a){var c=this;this.xhr&&(this.xhr=null);var b={id:null,key:{namespace:this.options.namespace,value:a}};clearTimeout(this.check_key.timeout);
this.check_key.timeout=setTimeout(function(){c.xhr=c.options.mqlread(b,function(b){return b?c.invalid(a,"Key already exists"):c.valid(a)},function(a){return a?c.invalid(a.responseText()):c.invalid("mqlread error!")})},200)},valid:function(a){this.input.trigger("valid",a)},invalid:function(a,c){c||(c=1<this.options.minlen?"Key must be "+this.options.minlen+" or more alphanumeric characters":"Key must be alphanumeric",c+=", lowercase, begin with a letter and not end with a non-alphanumeric character. Underscores are allowed but not consecutively.");
this.input.trigger("invalid",c)}};a.extend(c,{defaults:{minlen:1,check_key:!0,namespace:"/",mqlread:function(a,e,b){return c.mqlread(null,a,e,b)},source:null,schema:!1},mqlread:function(c,e,b,h){c={url:c||"http://api.freebase.com/api/service/mqlread",data:{query:JSON.stringify({query:e})},dataType:"jsonp",success:function(a){return b(a.result)},error:h};return a.ajax(c)},from:function(a){a=a.toLowerCase();a=a.replace(/[^a-z0-9]/g,"_");a=a.replace(/\_\_+/g,"_");a=a.replace(/[^a-z0-9]+$/,"");a=a.replace(/^[^a-z]+/,
"");c.reserved_word(a)&&(a="x_"+a);return a},reservedwords:"meta typeguid left right datatype scope attribute relationship property link class future update insert delete replace create destroy default sort limit offset optional pagesize cursor index !index for while as in is if else return count function read write select var connect this self super xml sql mql any all macro estimate-count",typeonlywords:"guid id object domain name key type keys value timestamp creator permission namespace unique schema reverse",
_reserved_word:null,reserved_word:function(d){c._reserved_word||(c._reserved_word={},a.each([c.reservedwords,c.typeonlywords],function(e,b){a.each(b.split(" "),function(a,b){c._reserved_word[b]=1})}));return 1===c._reserved_word[d]},fast:/^[A-Za-z0-9](?:[_-]?[A-Za-z0-9])*$/,slow:/^(?:[A-Za-z0-9]|\$[A-F0-9]{4})(?:[_-]?[A-Za-z0-9]|[_-]?\$[A-F0-9]{4})*$/,schema:/^[a-z](?:_?[a-z0-9])*$/,test:function(a,e){return e?c.schema.test(a):c.fast.test(a)||c.slow.test(a)}})})(jQuery);
(function(a,c){a(window).ajaxSend(function(a,b,c){"POST"===c.type&&b.setRequestHeader("x-acre-cache-control","max-age: 3600")});var d=c.schema.edit={init_edit_form:function(c){if("add"===c.mode)a("tbody",c.table).append(c.row);else if("edit"===c.mode)c.trigger_row.before(c.row);else throw"Unknown edit type mode: "+c.mode;c.trigger_row.before(c.submit_row);var b=c.event_prefix||"fb.schema.edit.";c.row.bind(b+"submit",function(){d.submit_edit_form(c)}).bind(b+"cancel",function(){d.cancel_edit_form(c)}).bind(b+
"error",function(a,b,g){d.row_error(b,g);c.row.removeClass("loading")}).bind(b+"success",function(){c.row.removeClass("loading")});a("button.save",c.submit_row).click(function(){c.row.trigger(b+"submit")});a(".button.cancel",c.submit_row).click(function(){c.row.trigger(b+"cancel")});c.row.showRow(function(){"function"===typeof c.init_form&&c.init_form(c)});c.trigger_row.hide();c.submit_row.show()},cancel_edit_form:function(c){c.row.hideRow(function(){a(this).remove()});d.clear_row_message(c.row);
c.submit_row.remove();c.trigger_row.show();c.trigger.removeClass("editing")},submit_edit_form:function(c){c.row.is(".loading")||(document.activeElement&&a(document.activeElement).blur(),d.clear_row_message(c.row),"function"===typeof c.validate_form&&c.validate_form(c),d.has_row_message(c.row,"error")||(c.row.addClass("loading"),"function"===typeof c.submit_form&&c.submit_form(c)))},ajax_error_handler:function(a,b,c){var f;try{f=JSON.parse(a.responseText),f.messages&&f.messages.length&&(f=JSON.stringify(f.messages[0]))}catch(g){}f||
(f=a.responseText);b?(d.row_error(b,f),b.removeClass("loading")):c&&(d.form_error(c,f),c.removeClass("loading"))},row_error:function(a,b){return d.row_message(a,b,"error")},row_message:function(d,b,h){var f=a('<a class="close-msg" href="#">Close</a>').click(function(a){return c.schema.close_message.apply(this,[a,".row-msg:first"])}),b=a("<span>").text(b),f=a('<td colspan="5">').append(f).append(b),f=a('<tr class="row-msg">').append(f);h&&f.addClass("row-msg-"+h);d.before(f);f.hide().showRow();b=d.data("row-msg");
b||(b={},d.data("row-msg",b));b[h]?b[h].push(f):b[h]=[f];return f},clear_row_message:function(c){var b=c.data("row-msg");b&&(a.each(b,function(b,c){a.each(c,function(a,b){b.remove()})}),c.removeData("row-msg"))},has_row_message:function(a,b){var c=a.data("row-msg");return b?c&&c[b]&&c[b].length:null!=c},init_modal_form:function(e){a(document.body).append(e.form.hide());var b=e.event_prefix||"fb.schema.edit.modal.";e.form.bind(b+"submit",function(){d.submit_modal_form(e)}).bind(b+"error",function(a,
b){d.form_error(e.form,b)}).bind(b+"success",function(){e.form.removeClass("loading")});a(".modal-buttons .button.save",e.form).click(function(){e.form.trigger(b+"submit")});e.form.overlay({close:".modal-buttons .button.cancel",closeOnClick:!1,load:!0,fixed:!1,mask:{color:"#000",loadSpeed:200,opacity:0.5},onLoad:function(){"function"===typeof e.init_form&&e.init_form(e)}});c.schema.init_modal_help(e.form)},submit_modal_form:function(c){c.form.is(".loading")||(document.activeElement&&a(document.activeElement).blur(),
d.clear_form_message(c.form),"function"===typeof c.validate_form&&c.validate_form(c),d.has_form_message(c.form,"error")||(c.form.addClass("loading"),"function"===typeof c.submit_form&&c.submit_form(c)))},form_error:function(a,b){return d.form_message(a,b,"error")},form_message:function(c,b,d){b=a("<div class='form-msg'>").text(b).hide();a(".form-group",c).prepend(b);b.slideDown();var f=c.data("form-msg");f||(f={},c.data("form-msg",f));f[d]?f[d].push(b):f[d]=[b];return b},clear_form_message:function(c){var b=
c.data("form-msg");b&&(a.each(b,function(b,c){a.each(c,function(a,b){b.remove()})}),c.removeData("form-msg"))},has_form_message:function(a,b){var c=a.data("form-msg");return b?c&&c[b]&&c[b].length:null!=c},init_mqlkey:function(c,b){c.mqlkey(b).bind("valid",function(){a(this).next(".key-status").removeClass("invalid").removeClass("loading").addClass("valid").text("valid").attr("title","Key is available")}).bind("invalid",function(b,c){a(this).next(".key-status").removeClass("valid").removeClass("loading").addClass("invalid").text("invalid").attr("title",
c)}).bind("textchange",function(){a(this).next(".key-status").removeClass("invalid").removeClass("valid").addClass("loading")})},validate_mqlkey:function(a,b){var c=a.form||a.row,d=b.next(".key-status"),g=b.val();return""===g?(c.trigger(a.event_prefix+"error","Key is required"),!1):g===b.data("mqlkey").original?!0:d.is(".invalid")?(c.trigger(a.event_prefix+"error",d.attr("title")),!1):d.is(".loading")?!1:!0}}})(jQuery,window.freebase);
(function(a){a.widget("ui.sortable",a.ui.mouse,{widgetEventPrefix:"sort",options:{appendTo:"parent",axis:!1,connectWith:!1,containment:!1,cursor:"auto",cursorAt:!1,dropOnEmpty:!0,forcePlaceholderSize:!1,forceHelperSize:!1,grid:!1,handle:!1,helper:"original",items:"> *",opacity:!1,placeholder:!1,revert:!1,scroll:!0,scrollSensitivity:20,scrollSpeed:20,scope:"default",tolerance:"intersect",zIndex:1E3},_create:function(){this.containerCache={};this.element.addClass("ui-sortable");this.refresh();this.floating=
this.items.length?/left|right/.test(this.items[0].item.css("float")):!1;this.offset=this.element.offset();this._mouseInit()},destroy:function(){this.element.removeClass("ui-sortable ui-sortable-disabled").removeData("sortable").unbind(".sortable");this._mouseDestroy();for(var a=this.items.length-1;0<=a;a--)this.items[a].item.removeData("sortable-item");return this},_setOption:function(c,d){"disabled"===c?(this.options[c]=d,this.widget()[d?"addClass":"removeClass"]("ui-sortable-disabled")):a.Widget.prototype._setOption.apply(this,
arguments)},_mouseCapture:function(c,d){if(this.reverting||this.options.disabled||"static"==this.options.type)return!1;this._refreshItems(c);var e=null,b=this;a(c.target).parents().each(function(){if(a.data(this,"sortable-item")==b)return e=a(this),!1});a.data(c.target,"sortable-item")==b&&(e=a(c.target));if(!e)return!1;if(this.options.handle&&!d){var h=!1;a(this.options.handle,e).find("*").andSelf().each(function(){this==c.target&&(h=!0)});if(!h)return!1}this.currentItem=e;this._removeCurrentsFromItems();
return!0},_mouseStart:function(c,d,e){d=this.options;this.currentContainer=this;this.refreshPositions();this.helper=this._createHelper(c);this._cacheHelperProportions();this._cacheMargins();this.scrollParent=this.helper.scrollParent();this.offset=this.currentItem.offset();this.offset={top:this.offset.top-this.margins.top,left:this.offset.left-this.margins.left};this.helper.css("position","absolute");this.cssPosition=this.helper.css("position");a.extend(this.offset,{click:{left:c.pageX-this.offset.left,
top:c.pageY-this.offset.top},parent:this._getParentOffset(),relative:this._getRelativeOffset()});this.originalPosition=this._generatePosition(c);this.originalPageX=c.pageX;this.originalPageY=c.pageY;d.cursorAt&&this._adjustOffsetFromHelper(d.cursorAt);this.domPosition={prev:this.currentItem.prev()[0],parent:this.currentItem.parent()[0]};this.helper[0]!=this.currentItem[0]&&this.currentItem.hide();this._createPlaceholder();d.containment&&this._setContainment();d.cursor&&(a("body").css("cursor")&&(this._storedCursor=
a("body").css("cursor")),a("body").css("cursor",d.cursor));d.opacity&&(this.helper.css("opacity")&&(this._storedOpacity=this.helper.css("opacity")),this.helper.css("opacity",d.opacity));d.zIndex&&(this.helper.css("zIndex")&&(this._storedZIndex=this.helper.css("zIndex")),this.helper.css("zIndex",d.zIndex));this.scrollParent[0]!=document&&"HTML"!=this.scrollParent[0].tagName&&(this.overflowOffset=this.scrollParent.offset());this._trigger("start",c,this._uiHash());this._preserveHelperProportions||this._cacheHelperProportions();
if(!e)for(e=this.containers.length-1;0<=e;e--)this.containers[e]._trigger("activate",c,this._uiHash(this));a.ui.ddmanager&&(a.ui.ddmanager.current=this);a.ui.ddmanager&&!d.dropBehaviour&&a.ui.ddmanager.prepareOffsets(this,c);this.dragging=!0;this.helper.addClass("ui-sortable-helper");this._mouseDrag(c);return!0},_mouseDrag:function(c){this.position=this._generatePosition(c);this.positionAbs=this._convertPositionTo("absolute");this.lastPositionAbs||(this.lastPositionAbs=this.positionAbs);if(this.options.scroll){var d=
this.options,e=!1;this.scrollParent[0]!=document&&"HTML"!=this.scrollParent[0].tagName?(this.overflowOffset.top+this.scrollParent[0].offsetHeight-c.pageY<d.scrollSensitivity?this.scrollParent[0].scrollTop=e=this.scrollParent[0].scrollTop+d.scrollSpeed:c.pageY-this.overflowOffset.top<d.scrollSensitivity&&(this.scrollParent[0].scrollTop=e=this.scrollParent[0].scrollTop-d.scrollSpeed),this.overflowOffset.left+this.scrollParent[0].offsetWidth-c.pageX<d.scrollSensitivity)?this.scrollParent[0].scrollLeft=
e=this.scrollParent[0].scrollLeft+d.scrollSpeed:c.pageX-this.overflowOffset.left<d.scrollSensitivity&&(this.scrollParent[0].scrollLeft=e=this.scrollParent[0].scrollLeft-d.scrollSpeed):(c.pageY-a(document).scrollTop()<d.scrollSensitivity?e=a(document).scrollTop(a(document).scrollTop()-d.scrollSpeed):a(window).height()-(c.pageY-a(document).scrollTop())<d.scrollSensitivity&&(e=a(document).scrollTop(a(document).scrollTop()+d.scrollSpeed)),c.pageX-a(document).scrollLeft()<d.scrollSensitivity?e=a(document).scrollLeft(a(document).scrollLeft()-
d.scrollSpeed):a(window).width()-(c.pageX-a(document).scrollLeft())<d.scrollSensitivity&&(e=a(document).scrollLeft(a(document).scrollLeft()+d.scrollSpeed)));!1!==e&&(a.ui.ddmanager&&!d.dropBehaviour)&&a.ui.ddmanager.prepareOffsets(this,c)}this.positionAbs=this._convertPositionTo("absolute");if(!this.options.axis||"y"!=this.options.axis)this.helper[0].style.left=this.position.left+"px";if(!this.options.axis||"x"!=this.options.axis)this.helper[0].style.top=this.position.top+"px";for(d=this.items.length-
1;0<=d;d--){var e=this.items[d],b=e.item[0],h=this._intersectsWithPointer(e);if(h&&b!=this.currentItem[0]&&this.placeholder[1==h?"next":"prev"]()[0]!=b&&!a.ui.contains(this.placeholder[0],b)&&("semi-dynamic"==this.options.type?!a.ui.contains(this.element[0],b):1)){this.direction=1==h?"down":"up";if("pointer"==this.options.tolerance||this._intersectsWithSides(e))this._rearrange(c,e);else break;this._trigger("change",c,this._uiHash());break}}this._contactContainers(c);a.ui.ddmanager&&a.ui.ddmanager.drag(this,
c);this._trigger("sort",c,this._uiHash());this.lastPositionAbs=this.positionAbs;return!1},_mouseStop:function(c,d){if(c){a.ui.ddmanager&&!this.options.dropBehaviour&&a.ui.ddmanager.drop(this,c);if(this.options.revert){var e=this,b=e.placeholder.offset();e.reverting=!0;a(this.helper).animate({left:b.left-this.offset.parent.left-e.margins.left+(this.offsetParent[0]==document.body?0:this.offsetParent[0].scrollLeft),top:b.top-this.offset.parent.top-e.margins.top+(this.offsetParent[0]==document.body?0:
this.offsetParent[0].scrollTop)},parseInt(this.options.revert,10)||500,function(){e._clear(c)})}else this._clear(c,d);return!1}},cancel:function(){if(this.dragging){this._mouseUp({target:null});"original"==this.options.helper?this.currentItem.css(this._storedCSS).removeClass("ui-sortable-helper"):this.currentItem.show();for(var c=this.containers.length-1;0<=c;c--)this.containers[c]._trigger("deactivate",null,this._uiHash(this)),this.containers[c].containerCache.over&&(this.containers[c]._trigger("out",
null,this._uiHash(this)),this.containers[c].containerCache.over=0)}this.placeholder&&(this.placeholder[0].parentNode&&this.placeholder[0].parentNode.removeChild(this.placeholder[0]),"original"!=this.options.helper&&(this.helper&&this.helper[0].parentNode)&&this.helper.remove(),a.extend(this,{helper:null,dragging:!1,reverting:!1,_noFinalSort:null}),this.domPosition.prev?a(this.domPosition.prev).after(this.currentItem):a(this.domPosition.parent).prepend(this.currentItem));return this},serialize:function(c){var d=
this._getItemsAsjQuery(c&&c.connected),e=[],c=c||{};a(d).each(function(){var b=(a(c.item||this).attr(c.attribute||"id")||"").match(c.expression||/(.+)[-=_](.+)/);b&&e.push((c.key||b[1]+"[]")+"="+(c.key&&c.expression?b[1]:b[2]))});!e.length&&c.key&&e.push(c.key+"=");return e.join("&")},toArray:function(c){var d=this._getItemsAsjQuery(c&&c.connected),e=[],c=c||{};d.each(function(){e.push(a(c.item||this).attr(c.attribute||"id")||"")});return e},_intersectsWith:function(a){var d=this.positionAbs.left,
e=d+this.helperProportions.width,b=this.positionAbs.top,h=b+this.helperProportions.height,f=a.left,g=f+a.width,k=a.top,i=k+a.height,j=this.offset.click.top,l=this.offset.click.left;return"pointer"==this.options.tolerance||this.options.forcePointerForContainers||"pointer"!=this.options.tolerance&&this.helperProportions[this.floating?"width":"height"]>a[this.floating?"width":"height"]?b+j>k&&b+j<i&&d+l>f&&d+l<g:f<d+this.helperProportions.width/2&&e-this.helperProportions.width/2<g&&k<b+this.helperProportions.height/
2&&h-this.helperProportions.height/2<i},_intersectsWithPointer:function(c){var d=a.ui.isOverAxis(this.positionAbs.top+this.offset.click.top,c.top,c.height),c=a.ui.isOverAxis(this.positionAbs.left+this.offset.click.left,c.left,c.width),d=d&&c,c=this._getDragVerticalDirection(),e=this._getDragHorizontalDirection();return!d?!1:this.floating?e&&"right"==e||"down"==c?2:1:c&&("down"==c?2:1)},_intersectsWithSides:function(c){var d=a.ui.isOverAxis(this.positionAbs.top+this.offset.click.top,c.top+c.height/
2,c.height),c=a.ui.isOverAxis(this.positionAbs.left+this.offset.click.left,c.left+c.width/2,c.width),e=this._getDragVerticalDirection(),b=this._getDragHorizontalDirection();return this.floating&&b?"right"==b&&c||"left"==b&&!c:e&&("down"==e&&d||"up"==e&&!d)},_getDragVerticalDirection:function(){var a=this.positionAbs.top-this.lastPositionAbs.top;return 0!=a&&(0<a?"down":"up")},_getDragHorizontalDirection:function(){var a=this.positionAbs.left-this.lastPositionAbs.left;return 0!=a&&(0<a?"right":"left")},
refresh:function(a){this._refreshItems(a);this.refreshPositions();return this},_connectWith:function(){var a=this.options;return a.connectWith.constructor==String?[a.connectWith]:a.connectWith},_getItemsAsjQuery:function(c){var d=[],e=[],b=this._connectWith();if(b&&c)for(c=b.length-1;0<=c;c--)for(var h=a(b[c]),f=h.length-1;0<=f;f--){var g=a.data(h[f],"sortable");g&&(g!=this&&!g.options.disabled)&&e.push([a.isFunction(g.options.items)?g.options.items.call(g.element):a(g.options.items,g.element).not(".ui-sortable-helper").not(".ui-sortable-placeholder"),
g])}e.push([a.isFunction(this.options.items)?this.options.items.call(this.element,null,{options:this.options,item:this.currentItem}):a(this.options.items,this.element).not(".ui-sortable-helper").not(".ui-sortable-placeholder"),this]);for(c=e.length-1;0<=c;c--)e[c][0].each(function(){d.push(this)});return a(d)},_removeCurrentsFromItems:function(){for(var a=this.currentItem.find(":data(sortable-item)"),d=0;d<this.items.length;d++)for(var e=0;e<a.length;e++)a[e]==this.items[d].item[0]&&this.items.splice(d,
1)},_refreshItems:function(c){this.items=[];this.containers=[this];var d=this.items,e=[[a.isFunction(this.options.items)?this.options.items.call(this.element[0],c,{item:this.currentItem}):a(this.options.items,this.element),this]],b=this._connectWith();if(b)for(var h=b.length-1;0<=h;h--)for(var f=a(b[h]),g=f.length-1;0<=g;g--){var k=a.data(f[g],"sortable");k&&(k!=this&&!k.options.disabled)&&(e.push([a.isFunction(k.options.items)?k.options.items.call(k.element[0],c,{item:this.currentItem}):a(k.options.items,
k.element),k]),this.containers.push(k))}for(h=e.length-1;0<=h;h--){c=e[h][1];b=e[h][0];g=0;for(f=b.length;g<f;g++)k=a(b[g]),k.data("sortable-item",c),d.push({item:k,instance:c,width:0,height:0,left:0,top:0})}},refreshPositions:function(c){this.offsetParent&&this.helper&&(this.offset.parent=this._getParentOffset());for(var d=this.items.length-1;0<=d;d--){var e=this.items[d],b=this.options.toleranceElement?a(this.options.toleranceElement,e.item):e.item;c||(e.width=b.outerWidth(),e.height=b.outerHeight());
b=b.offset();e.left=b.left;e.top=b.top}if(this.options.custom&&this.options.custom.refreshContainers)this.options.custom.refreshContainers.call(this);else for(d=this.containers.length-1;0<=d;d--)b=this.containers[d].element.offset(),this.containers[d].containerCache.left=b.left,this.containers[d].containerCache.top=b.top,this.containers[d].containerCache.width=this.containers[d].element.outerWidth(),this.containers[d].containerCache.height=this.containers[d].element.outerHeight();return this},_createPlaceholder:function(c){var d=
c||this,e=d.options;if(!e.placeholder||e.placeholder.constructor==String){var b=e.placeholder;e.placeholder={element:function(){var c=a(document.createElement(d.currentItem[0].nodeName)).addClass(b||d.currentItem[0].className+" ui-sortable-placeholder").removeClass("ui-sortable-helper")[0];b||(c.style.visibility="hidden");return c},update:function(a,c){if(!b||e.forcePlaceholderSize)c.height()||c.height(d.currentItem.innerHeight()-parseInt(d.currentItem.css("paddingTop")||0,10)-parseInt(d.currentItem.css("paddingBottom")||
0,10)),c.width()||c.width(d.currentItem.innerWidth()-parseInt(d.currentItem.css("paddingLeft")||0,10)-parseInt(d.currentItem.css("paddingRight")||0,10))}}}d.placeholder=a(e.placeholder.element.call(d.element,d.currentItem));d.currentItem.after(d.placeholder);e.placeholder.update(d,d.placeholder)},_contactContainers:function(c){for(var d=null,e=null,b=this.containers.length-1;0<=b;b--)if(!a.ui.contains(this.currentItem[0],this.containers[b].element[0]))if(this._intersectsWith(this.containers[b].containerCache)){if(!d||
!a.ui.contains(this.containers[b].element[0],d.element[0]))d=this.containers[b],e=b}else this.containers[b].containerCache.over&&(this.containers[b]._trigger("out",c,this._uiHash(this)),this.containers[b].containerCache.over=0);if(d)if(1===this.containers.length)this.containers[e]._trigger("over",c,this._uiHash(this)),this.containers[e].containerCache.over=1;else if(this.currentContainer!=this.containers[e]){for(var d=1E4,b=null,h=this.positionAbs[this.containers[e].floating?"left":"top"],f=this.items.length-
1;0<=f;f--)if(a.ui.contains(this.containers[e].element[0],this.items[f].item[0])){var g=this.items[f][this.containers[e].floating?"left":"top"];Math.abs(g-h)<d&&(d=Math.abs(g-h),b=this.items[f])}if(b||this.options.dropOnEmpty)this.currentContainer=this.containers[e],b?this._rearrange(c,b,null,!0):this._rearrange(c,null,this.containers[e].element,!0),this._trigger("change",c,this._uiHash()),this.containers[e]._trigger("change",c,this._uiHash(this)),this.options.placeholder.update(this.currentContainer,
this.placeholder),this.containers[e]._trigger("over",c,this._uiHash(this)),this.containers[e].containerCache.over=1}},_createHelper:function(c){var d=this.options,c=a.isFunction(d.helper)?a(d.helper.apply(this.element[0],[c,this.currentItem])):"clone"==d.helper?this.currentItem.clone():this.currentItem;c.parents("body").length||a("parent"!=d.appendTo?d.appendTo:this.currentItem[0].parentNode)[0].appendChild(c[0]);c[0]==this.currentItem[0]&&(this._storedCSS={width:this.currentItem[0].style.width,height:this.currentItem[0].style.height,
position:this.currentItem.css("position"),top:this.currentItem.css("top"),left:this.currentItem.css("left")});(""==c[0].style.width||d.forceHelperSize)&&c.width(this.currentItem.width());(""==c[0].style.height||d.forceHelperSize)&&c.height(this.currentItem.height());return c},_adjustOffsetFromHelper:function(c){"string"==typeof c&&(c=c.split(" "));a.isArray(c)&&(c={left:+c[0],top:+c[1]||0});"left"in c&&(this.offset.click.left=c.left+this.margins.left);"right"in c&&(this.offset.click.left=this.helperProportions.width-
c.right+this.margins.left);"top"in c&&(this.offset.click.top=c.top+this.margins.top);"bottom"in c&&(this.offset.click.top=this.helperProportions.height-c.bottom+this.margins.top)},_getParentOffset:function(){this.offsetParent=this.helper.offsetParent();var c=this.offsetParent.offset();"absolute"==this.cssPosition&&(this.scrollParent[0]!=document&&a.ui.contains(this.scrollParent[0],this.offsetParent[0]))&&(c.left+=this.scrollParent.scrollLeft(),c.top+=this.scrollParent.scrollTop());if(this.offsetParent[0]==
document.body||this.offsetParent[0].tagName&&"html"==this.offsetParent[0].tagName.toLowerCase()&&a.browser.msie)c={top:0,left:0};return{top:c.top+(parseInt(this.offsetParent.css("borderTopWidth"),10)||0),left:c.left+(parseInt(this.offsetParent.css("borderLeftWidth"),10)||0)}},_getRelativeOffset:function(){if("relative"==this.cssPosition){var a=this.currentItem.position();return{top:a.top-(parseInt(this.helper.css("top"),10)||0)+this.scrollParent.scrollTop(),left:a.left-(parseInt(this.helper.css("left"),
10)||0)+this.scrollParent.scrollLeft()}}return{top:0,left:0}},_cacheMargins:function(){this.margins={left:parseInt(this.currentItem.css("marginLeft"),10)||0,top:parseInt(this.currentItem.css("marginTop"),10)||0}},_cacheHelperProportions:function(){this.helperProportions={width:this.helper.outerWidth(),height:this.helper.outerHeight()}},_setContainment:function(){var c=this.options;"parent"==c.containment&&(c.containment=this.helper[0].parentNode);if("document"==c.containment||"window"==c.containment)this.containment=
[0-this.offset.relative.left-this.offset.parent.left,0-this.offset.relative.top-this.offset.parent.top,a("document"==c.containment?document:window).width()-this.helperProportions.width-this.margins.left,(a("document"==c.containment?document:window).height()||document.body.parentNode.scrollHeight)-this.helperProportions.height-this.margins.top];if(!/^(document|window|parent)$/.test(c.containment)){var d=a(c.containment)[0],c=a(c.containment).offset(),e="hidden"!=a(d).css("overflow");this.containment=
[c.left+(parseInt(a(d).css("borderLeftWidth"),10)||0)+(parseInt(a(d).css("paddingLeft"),10)||0)-this.margins.left,c.top+(parseInt(a(d).css("borderTopWidth"),10)||0)+(parseInt(a(d).css("paddingTop"),10)||0)-this.margins.top,c.left+(e?Math.max(d.scrollWidth,d.offsetWidth):d.offsetWidth)-(parseInt(a(d).css("borderLeftWidth"),10)||0)-(parseInt(a(d).css("paddingRight"),10)||0)-this.helperProportions.width-this.margins.left,c.top+(e?Math.max(d.scrollHeight,d.offsetHeight):d.offsetHeight)-(parseInt(a(d).css("borderTopWidth"),
10)||0)-(parseInt(a(d).css("paddingBottom"),10)||0)-this.helperProportions.height-this.margins.top]}},_convertPositionTo:function(c,d){d||(d=this.position);var e="absolute"==c?1:-1,b="absolute"==this.cssPosition&&!(this.scrollParent[0]!=document&&a.ui.contains(this.scrollParent[0],this.offsetParent[0]))?this.offsetParent:this.scrollParent,h=/(html|body)/i.test(b[0].tagName);return{top:d.top+this.offset.relative.top*e+this.offset.parent.top*e-(a.browser.safari&&"fixed"==this.cssPosition?0:("fixed"==
this.cssPosition?-this.scrollParent.scrollTop():h?0:b.scrollTop())*e),left:d.left+this.offset.relative.left*e+this.offset.parent.left*e-(a.browser.safari&&"fixed"==this.cssPosition?0:("fixed"==this.cssPosition?-this.scrollParent.scrollLeft():h?0:b.scrollLeft())*e)}},_generatePosition:function(c){var d=this.options,e="absolute"==this.cssPosition&&!(this.scrollParent[0]!=document&&a.ui.contains(this.scrollParent[0],this.offsetParent[0]))?this.offsetParent:this.scrollParent,b=/(html|body)/i.test(e[0].tagName);
"relative"==this.cssPosition&&!(this.scrollParent[0]!=document&&this.scrollParent[0]!=this.offsetParent[0])&&(this.offset.relative=this._getRelativeOffset());var h=c.pageX,f=c.pageY;if(this.originalPosition&&(this.containment&&(c.pageX-this.offset.click.left<this.containment[0]&&(h=this.containment[0]+this.offset.click.left),c.pageY-this.offset.click.top<this.containment[1]&&(f=this.containment[1]+this.offset.click.top),c.pageX-this.offset.click.left>this.containment[2]&&(h=this.containment[2]+this.offset.click.left),
c.pageY-this.offset.click.top>this.containment[3]&&(f=this.containment[3]+this.offset.click.top)),d.grid))f=this.originalPageY+Math.round((f-this.originalPageY)/d.grid[1])*d.grid[1],f=this.containment?!(f-this.offset.click.top<this.containment[1]||f-this.offset.click.top>this.containment[3])?f:!(f-this.offset.click.top<this.containment[1])?f-d.grid[1]:f+d.grid[1]:f,h=this.originalPageX+Math.round((h-this.originalPageX)/d.grid[0])*d.grid[0],h=this.containment?!(h-this.offset.click.left<this.containment[0]||
h-this.offset.click.left>this.containment[2])?h:!(h-this.offset.click.left<this.containment[0])?h-d.grid[0]:h+d.grid[0]:h;return{top:f-this.offset.click.top-this.offset.relative.top-this.offset.parent.top+(a.browser.safari&&"fixed"==this.cssPosition?0:"fixed"==this.cssPosition?-this.scrollParent.scrollTop():b?0:e.scrollTop()),left:h-this.offset.click.left-this.offset.relative.left-this.offset.parent.left+(a.browser.safari&&"fixed"==this.cssPosition?0:"fixed"==this.cssPosition?-this.scrollParent.scrollLeft():
b?0:e.scrollLeft())}},_rearrange:function(a,d,e,b){e?e[0].appendChild(this.placeholder[0]):d.item[0].parentNode.insertBefore(this.placeholder[0],"down"==this.direction?d.item[0]:d.item[0].nextSibling);this.counter=this.counter?++this.counter:1;var h=this,f=this.counter;window.setTimeout(function(){f==h.counter&&h.refreshPositions(!b)},0)},_clear:function(c,d){this.reverting=!1;var e=[];!this._noFinalSort&&this.currentItem[0].parentNode&&this.placeholder.before(this.currentItem);this._noFinalSort=
null;if(this.helper[0]==this.currentItem[0]){for(var b in this._storedCSS)if("auto"==this._storedCSS[b]||"static"==this._storedCSS[b])this._storedCSS[b]="";this.currentItem.css(this._storedCSS).removeClass("ui-sortable-helper")}else this.currentItem.show();this.fromOutside&&!d&&e.push(function(a){this._trigger("receive",a,this._uiHash(this.fromOutside))});(this.fromOutside||this.domPosition.prev!=this.currentItem.prev().not(".ui-sortable-helper")[0]||this.domPosition.parent!=this.currentItem.parent()[0])&&
!d&&e.push(function(a){this._trigger("update",a,this._uiHash())});if(!a.ui.contains(this.element[0],this.currentItem[0])){d||e.push(function(a){this._trigger("remove",a,this._uiHash())});for(b=this.containers.length-1;0<=b;b--)a.ui.contains(this.containers[b].element[0],this.currentItem[0])&&!d&&(e.push(function(a){return function(b){a._trigger("receive",b,this._uiHash(this))}}.call(this,this.containers[b])),e.push(function(a){return function(b){a._trigger("update",b,this._uiHash(this))}}.call(this,
this.containers[b])))}for(b=this.containers.length-1;0<=b;b--)d||e.push(function(a){return function(b){a._trigger("deactivate",b,this._uiHash(this))}}.call(this,this.containers[b])),this.containers[b].containerCache.over&&(e.push(function(a){return function(b){a._trigger("out",b,this._uiHash(this))}}.call(this,this.containers[b])),this.containers[b].containerCache.over=0);this._storedCursor&&a("body").css("cursor",this._storedCursor);this._storedOpacity&&this.helper.css("opacity",this._storedOpacity);
this._storedZIndex&&this.helper.css("zIndex","auto"==this._storedZIndex?"":this._storedZIndex);this.dragging=!1;if(this.cancelHelperRemoval){if(!d){this._trigger("beforeStop",c,this._uiHash());for(b=0;b<e.length;b++)e[b].call(this,c);this._trigger("stop",c,this._uiHash())}return!1}d||this._trigger("beforeStop",c,this._uiHash());this.placeholder[0].parentNode.removeChild(this.placeholder[0]);this.helper[0]!=this.currentItem[0]&&this.helper.remove();this.helper=null;if(!d){for(b=0;b<e.length;b++)e[b].call(this,
c);this._trigger("stop",c,this._uiHash())}this.fromOutside=!1;return!0},_trigger:function(){!1===a.Widget.prototype._trigger.apply(this,arguments)&&this.cancel()},_uiHash:function(c){var d=c||this;return{helper:d.helper,placeholder:d.placeholder||a([]),position:d.position,originalPosition:d.originalPosition,offset:d.positionAbs,item:d.currentItem,sender:c?c.element:null}}});a.extend(a.ui.sortable,{version:"1.8.10"})})(jQuery);
(function(a,c){if(a.suggest){var d=a.suggest.suggest.prototype._init,e=a.suggest.suggest.prototype.status_start,b=a.suggest.suggest.prototype.status_loading,h=a.suggest.suggest.prototype.status_select,f=a.suggest.suggest.prototype.create_item,g=a.suggest.suggest.prototype.focus;a.suggest("suggest_expected_type",a.extend(!0,{},a.suggest.suggest.prototype,{_init:function(){var b=this;d.call(b);this.input.bind("remove",function(){b._destroy()});this.ect_pane=a('<div class="ect-pane fbs-reset">');this.ect_menu=
a('<div class="ect-menu-dialog"><span class="ect-menu-title">or choose from the data types below</span></div>');this.ect_list=a('<ul class="ect-menu clear">');a.each(["text","numeric","date","boolean","image","weblink","address","enumeration"],function(a,c){b.ect_list.append(b["create_ect_"+c].call(b))});this.init_unit_dialog();this.ect_pane.append(this.ect_menu);this.ect_pane.append(this.ect_unit);this.ect_menu.append(this.ect_list);this.init_enumeration_dialog();this.ect_pane.bind("ect",function(c,
d){a(".trigger",this).each(function(){var b=a(this).data("tooltip");b&&b.hide()});if(d.id==="/type/float"&&d.name==="Measurement"){b.ect_menu.hide();b.ect_enumeration.hide();b.ect_unit.show();b.status.hide()}else if(d.id==="/type/enumeration"){b.ect_menu.hide();b.ect_unit.hide();b.ect_enumeration.show();b.status.hide()}else{b.input.val(d.name).data("data.suggest",d).trigger("fb-select",d);b.hide_all()}}).bind("mouseup",function(a){a.stopPropagation()});this.pane.append(this.ect_pane);a.suggest.suggest_expected_type.load_dimensions()},
init_unit_dialog:function(){var b=this;this.ect_unit=a('<div class="ect-unit-dialog"><h2 class="ect-unit-dialog-title">Select measurement type</h2><div class="ect-unit-field"><label for="dimension">The kind of thing to measure</label><select name="dimension"></select></div><div class="ect-unit-field"><label for="dimension-unit">The unit to measure it in</label><select name="dimension-unit"></select></div><div class="ect-unit-submit"><button class="button primary">OK</button><button class="button cancel">Cancel</button></div></div>').hide();
this.ect_dimension=a("select:first",this.ect_unit);this.ect_dimension_units=a("select:eq(1)",this.ect_unit);this.ect_dimension.change(function(){var c=a(":selected",this).data("units");if(b.ect_dimension_units.data("units")!==c){b.ect_dimension_units.empty();a.each(c,function(c,d){var e=d.name;d["/freebase/unit_profile/abbreviation"]&&(e=e+(" ("+d["/freebase/unit_profile/abbreviation"]+")"));e=a("<option>").text(e).attr("value",d.id).data("data",d);b.ect_dimension_units.append(e);d.id==="/en/meter"&&
e.attr("selected","selected")})}});a(".button.cancel",this.ect_unit).click(function(a){b.ect_menu.show();b.ect_unit.hide();b.status.show();b.input.focus().removeData("dont_hide");a.stopPropagation()});a(".button.primary",this.ect_unit).click(function(c){var d={name:"Measurment",id:"/type/float",unit:a(":selected",b.ect_dimension_units).data("data")};b.input.val(d.name).data("data.suggest",d).trigger("fb-select",d);b.input.focus().removeData("dont_hide");b.ect_menu.show();b.ect_unit.hide();b.hide_all();
c.stopPropagation()})},init_enumeration_dialog:function(){if(this.options.domain){var b=this;this.ect_enumeration=a('<div class="ect-enumeration-dialog"><h2 class="ect-enumeration-dialog-title">Enumerated Namespace</h2><div class="form-group"><div class="ect-enumeration-field" id="new-enumeration-field"><label><input type="radio" name="namespace" class="ect-enumeration-choice" checked="checked">Create new namespace</label><input type="text" class="text-input" id="ect-namespace-new-input" placeholder="key"/><span class="ect-namespace-root">'+
this.options.domain+'/<span class="ect-namespace-key"></span></span></div><div class="ect-enumeration-field" id="existing-enumeration-field" style="display:none"><label><input type="radio" class="ect-enumeration-choice" name="namespace"><span>Enter a namespace to which you have permisson</span></label><input type="text" placeholder="eg. /authority/netflix" class="text-input"/></div><a href="javascript:void(0);" class="namespace-toggle">or choose existing&hellip;</a><div class="ect-enumeration-submit"><button class="button primary">OK</button><button class="button cancel">Cancel</button></div></div></div>').hide();
a(":text",this.ect_enumeration).focus(function(){a(this).prev("label").find(":radio").attr("checked","checked")}).change(function(){c.schema.edit.clear_form_message(b.ect_enumeration)});a("#ect-namespace-new-input",this.ect_enumeration).keydown(function(){var b=a(this),c=a(".ect-namespace-key");setTimeout(function(){c.html(b.val())},500)});a(".namespace-toggle",this.ect_enumeration).click(function(){var b=a(this),c=a("#new-enumeration-field"),d=a("#existing-enumeration-field");if(d.is(":hidden")){c.hide();
d.show();b.html("cancel")}else{d.hide();c.show();b.html("or choose existing...")}});a(".button.cancel",this.ect_enumeration).click(function(a){b.ect_menu.show();b.ect_enumeration.hide();b.status.show();b.input.focus().removeData("dont_hide");a.stopPropagation()});a(".button.primary",this.ect_enumeration).click(function(d){c.schema.edit.clear_form_message(b.ect_enumeration);var e={name:"Enumeration",id:"/type/enumeration"},f;if(a(":radio:first",b.ect_enumeration).is(":checked"))try{var h=a(":text:first",
b.ect_enumeration),g=a.mqlkey.from(h.val());if(a.mqlkey.reserved_word(g))throw g+" is a reserved word.";if(g.length<5)throw"Key must be 5 or more alphanumeric characters";f=b.options.domain+"/"+g}catch(k){c.schema.edit.form_error(b.ect_enumeration,k);return}else{h=a(":text:eq(1)",b.ect_enumeration);f=h.val()}if(f){e.enumeration=f;b.input.val(e.name).data("data.suggest",e).trigger("fb-select",e);b.input.focus().removeData("dont_hide");b.ect_menu.show();b.ect_enumeration.hide();b.hide_all();d.stopPropagation()}else c.schema.edit.form_error(b.ect_enumeration,
"Please select a namespace.")});this.ect_pane.append(this.ect_enumeration)}},status_start:function(){e.apply(this);this.ect_pane.show();(this.ect_unit.is(":visible")||this.ect_enumeration&&this.ect_enumeration.is(":visible"))&&this.status.hide()},status_loading:function(){b.apply(this);this.ect_pane.hide()},status_select:function(){h.apply(this);this.ect_pane.hide()},create_ect_text:function(){var b=this.create_ect_item("Text");a("> a",b).after(this.create_ect_tooltip([{name:"Short Text Input",id:"/type/text"},
{name:"Machine readable string",id:"/type/rawstring"}])).tooltip(this.options.tooltip_options);return b},create_ect_numeric:function(){var b=this.create_ect_item("Numeric");a("> a",b).after(this.create_ect_tooltip([{name:"Integer",id:"/type/int"},{name:"Decimal point number",id:"/type/float"},{name:"Measurement",id:"/type/float"},{name:"Dated Currency",id:"/measurement_unit/dated_money_value"},{name:"Dated Integer",id:"/measurement_unit/dated_integer"},{name:"Dated Decimal Point Number",id:"/measurement_unit/dated_float"},
{name:"Integer Range",id:"/measurement_unit/integer_range"},{name:"Decimal Point Number Range",id:"/measurement_unit/floating_point_range"}])).tooltip(this.options.tooltip_options);return b},create_ect_date:function(){var b=this.create_ect_item("Date/Time","date");a("> a",b).after(this.create_ect_tooltip([{name:"Date/Time",id:"/type/datetime"},{name:"Day of Week",id:"/time/day_of_week"},{name:"Date of Year",id:"/time/day_of_year"},{name:"Time interval",id:"/measurement_unit/time_interval"}])).tooltip(this.options.tooltip_options);
return b},create_ect_boolean:function(){var b=this.create_ect_item("Boolean");a("> a",b).data("ect",{name:"Boolean",id:"/type/boolean"}).click(function(){a(this).trigger("ect",a(this).data("ect"))});return b},create_ect_image:function(){var b=this.create_ect_item("Image");a("> a",b).data("ect",{name:"Image",id:"/common/image"}).click(function(){a(this).trigger("ect",a(this).data("ect"))});return b},create_ect_weblink:function(){var b=this.create_ect_item("Weblink");a("> a",b).data("ect",{name:"Weblink",
id:"/common/webpage"}).click(function(){a(this).trigger("ect",a(this).data("ect"))});return b},create_ect_address:function(){var b=this.create_ect_item("Address");a("> a",b).data("ect",{name:"Address",id:"/location/mailing_address"}).click(function(){a(this).trigger("ect",a(this).data("ect"))});return b},create_ect_enumeration:function(){var b=this.create_ect_item("Namespace");a("> a",b).data("ect",{name:"Enumeration",id:"/type/enumeration"}).click(function(){a(this).trigger("ect",a(this).data("ect"))});
return b},create_ect_item:function(b,c){c||(c=b.toLowerCase());var d=a('<li class="ect-menu-item">'),e=a('<a href="javascript:void(0);" class="ect-icon trigger">&nbsp;</a>');e.addClass("ect-"+c);d.append(e);d.append(document.createTextNode(b));return d},create_ect_tooltip:function(b){var c=a('<ul class="row-menu tooltip">');a.each(b,function(b,d){var e=a('<li class="row-menu-item">'),f=a('<a href="javascript:void(0);">&nbsp;</a>').attr("title",d.id).data("ect",d).click(function(){a(this).trigger("ect",
a(this).data("ect"))});f.text(d.name);e.append(f);c.append(e)});return c},create_item:function(b,c){var d=f.apply(this,[b,c]),e=b.id.split("/");e.pop();e=e.join("/");a("."+this.options.css.item_type,d).text(e);return d},focus:function(a){g.apply(this,[a]);this.input.removeData("dont_hide")}}));var k=a.suggest.suggest_expected_type;a.extend(k,{defaults:a.extend(!0,{},a.suggest.suggest.defaults,{category:"expected_type",filter:"(all type:/type/type without:hidden)",css:{status:"fbs-status fbs-ect-status"},
tooltip_options:{events:{def:"click,mouseout"},position:"bottom right",offset:[-10,-10],effect:"fade",delay:300,relative:!0}}),set_dimensions:function(b){a(".ect-pane select[name=dimension]").each(function(){var c=a(this);if(c.data("dimensions")!==b){var d;a.each(b,function(b,e){var f=a("<option>").text(e.name).attr("value",e.id).data("units",e.units);c.append(f);"/en/length"===e.id&&(d=f)});c.data("dimensions",b);d&&(d.attr("selected","selected"),c.change())}})},load_dimensions:function(){k.dimensions?
k.set_dimensions(k.dimensions):k.load_dimensions.lock||(k.load_dimensions.lock=!0,c.mqlread([{id:null,name:null,type:"/measurement_unit/dimension",units:[{id:null,name:null,type:"/type/unit","/freebase/unit_profile/abbreviation":null,sort:"name"}],sort:"name"}],k.set_dimensions))},load_dimensions_callback:function(b){"/api/status/ok"===b.code&&(k.dimensions=b.result.sort(k.sort_by_name),a.each(k.dimensions,function(a,b){b.units.sort(k.sort_by_name)}),k.set_dimensions(k.dimensions))},sort_by_name:function(a,
b){return b.name-a.name}})}else alert("$.suggest required")})(jQuery,window.freebase);
(function(a){a.suggest||alert("$.suggest required");var c=a.suggest.suggest.prototype.create_item;a.suggest("suggest_property",a.extend(!0,{},a.suggest.suggest.prototype,{create_item:function(d,e){var b=c.apply(this,[d,e]),h=d.id.split("/");h.pop();h=h.join("/");a("."+this.options.css.item_type,b).text(h);return b}}));a.extend(a.suggest.suggest_property,{defaults:a.extend(!0,{},a.suggest.suggest.defaults,{type:"/type/property",type_strict:"any",filter:"(all type:/type/property without:hidden)",css:{status:"fbs-status fbs-ect-status"}})})})(jQuery);
(function(a,c){var d=c.schema.edit,e=c.schema.type.edit={init_delegate_property:function(b){a(".nav-toggle",b.row).click(function(){e.toggle_delegate_property(a(this),b);return!1})},toggle_delegate_property:function(b,d){if(b.is(".current"))return!1;var f=b.parents(".nav:first");a(".nav-toggle",f).removeClass("current");b.addClass("current");var g=a(".fb-property-expected-type",d.row);a("input",g).val("");g=a("input[name=unique]",d.row).removeAttr("checked");a(".form-msg",d.row).remove();b.is(".nav-delegate")?
(a(".nav-delegate-msg",f).show(),a("input[name=expected_type_input]",d.row).hide().prev(".form-label").text("Property to use"),f=a("input[name=delegated]",d.row).show(),a("label[for=master]",d.row).find("span").text("Delegated"),g.attr("disabled","disabled"),f.data("suggest_property")||f.unbind().suggest_property(c.suggest_options.delegate_property()).bind("fb-select",function(b,c){a(this).val(c.id);setTimeout(function(){e.delegate_property_begin(d,c.id)},0)}).keypress(function(a){13===a.keyCode&&
!a.isDefaultPrevented()&&d.row.trigger(d.event_prefix+"submit")}).keyup(function(a){27===a.keyCode&&d.row.trigger(d.event_prefix+"cancel")})):(a(".nav-delegate-msg",f).hide(),a("input[name=delegated]",d.row).hide(),a("input[name=expected_type_input]",d.row).show().prev(".form-label").text("Expected Type"),a("label[for=master]",d.row).find("span").text("Master"),g.removeAttr("disabled"));a("input[name=name]",d.row).focus()},delegate_property_begin:function(b,e){b.row.addClass("loading");a.ajax({url:c.h.ajax_url("delegate_property_begin.ajax"),
data:{id:e,lang:c.lang},dataType:"json",success:function(c,e,h){if("/api/status/error"===c.code)return d.ajax_error_handler(h,b.row);c=c.result;e={id:c.expected_type,unit:c.unit};a("input[name=expected_type_input]",b.row).trigger("fb-select",e);c.unique&&a("input[name=unique]",b.row).attr("checked","checked");a(".form-msg",b.row).remove();e=a(".form-field:first",b.row);c=a(c.message);e.before(c)},error:function(a){d.ajax_error_handler(a,b.row)},complete:function(){b.row.removeClass("loading")}})},
add_property_begin:function(b,h){var f=b.parents("tr:first");a.ajax({url:c.h.ajax_url("add_property_begin.ajax"),data:{id:h,lang:c.lang},dataType:"json",success:function(g,h,i){if("/api/status/error"===g.code)return d.ajax_error_handler(i,f);var g=a(g.result.html),j={mode:"add",event_prefix:"fb.schema.type.add.property.",ajax:{url:c.h.ajax_url("add_property_submit.ajax")},init_form:e.init_property_form,validate_form:e.validate_property_form,submit_form:e.submit_property_form,table:b.parents("table:first"),
trigger:b,trigger_row:f,row:a(".edit-row",g).hide(),submit_row:a(".edit-row-submit",g).hide()};d.init_edit_form(j);e.init_delegate_property(j);j.row.bind("fb.schema.type.add.property.success",function(){var b=a("tbody:first .table-empty-column",j.table);b.length&&b.parents("tr:first").hide().prev("tr").show();e.toggle_reorder_link(j.table);a(".button.cancel",j.submit_row).text("Done");e.init_property_form(j)})},error:function(a){d.ajax_error_handler(a,f)}})},edit_property_begin:function(b,h){var f=
b.parents("tr:first");a.ajax({url:c.h.ajax_url("edit_property_begin.ajax"),data:{id:h,lang:c.lang},dataType:"json",success:function(g,k,i){if("/api/status/error"===g.code)return d.ajax_error_handler(i,f);var g=a(g.result.html),j={mode:"edit",event_prefix:"fb.schema.type.edit.property.",ajax:{url:c.h.ajax_url("edit_property_submit.ajax"),data:{id:h}},init_form:e.init_property_form,validate_form:e.validate_property_form,submit_form:e.submit_property_form,table:b.parents("table:first"),trigger:b,trigger_row:f,
row:a(".edit-row",g).hide(),submit_row:a(".edit-row-submit",g).hide()};d.init_edit_form(j);j.row.bind("fb.schema.type.edit.property.success",function(){j.trigger_row.remove();j.row.remove();j.submit_row.remove()})},error:function(a){d.ajax_error_handler(a,f)}})},init_property_form:function(b){var e=a("input[name=name]",b.row),f=a("input[name=key]",b.row),g=a("input[name=expected_type_input]",b.row),k=a("input[name=expected_type]",b.row),i=a("input[name=expected_type_new]",b.row),j=a("input[name=unit]",
b.row),l=a("input[name=enumeration]",b.row),m=a("textarea[name=description]",b.row),o=a("input[name=disambiguator]",b.row),n=a("input[name=unique]",b.row),r=a("input[name=hidden]",b.row),q=a("input[name=type]",b.row);"add"===b.mode&&(a(".nav-toggle:first",b.row).click(),e.val(""),f.val(""),g.val(""),k.val(""),i.val(""),j.val(""),m.val(""),a.each([o,n,r],function(a,b){b.is(":disabled")||b.removeAttr("checked")}));b.row.data("initialized")||(d.init_mqlkey(f,{source:e,namespace:q.val(),mqlread:c.mqlread,
schema:!0}),f=q.val().split("/"),f.pop(),f=f.join("/"),g.suggest_expected_type(a.extend(c.suggest_options.expected_type(),{status:["Start typing to get suggestions...","Searching...","Select an item from the list:"],domain:f,suggest_new:"Create new type"})).bind("fb-select",function(c,d){if(d.unit){g.val(d.id+" ("+d.unit.name+")");k.val(d.id);i.val("");j.val(d.unit.id)}else if(d.enumeration){g.val(d.id+" ("+d.enumeration+")");k.val(d.id);i.val("");l.val(d.enumeration)}else{g.val(d.id);k.val(d.id);
i.val("");j.val("");d.id==="/type/boolean"&&a("input[name=unique]",b.row).attr("checked","checked")}}).bind("fb-textchange",function(){k.val("");i.val("");j.val("")}).bind("fb-select-new",function(b,c){i.val(a.trim(c));k.val("");j.val("")}),a(":input:not(textarea)",b.row).keypress(function(a){a.keyCode===13&&!a.isDefaultPrevented()&&b.row.trigger(b.event_prefix+"submit")}).keyup(function(a){a.keyCode===27&&b.row.trigger(b.event_prefix+"cancel")}),b.row.data("initialized",!0));e.focus()},submit_property_form:function(b){var e=
a(":input[name=key]",b.row);d.validate_mqlkey(b,e)?(e={type:a(":input[name=type]",b.row).val(),name:a.trim(a("input[name=name]:visible",b.row).val()),key:e.val(),expected_type:a(":input[name=expected_type]",b.row).val(),expected_type_new:a(":input[name=expected_type_new]",b.row).val(),unit:a(":input[name=unit]",b.row).val(),enumeration:a("input[name=enumeration]",b.row).val(),description:a.trim(a("textarea[name=description]:visible",b.row).val()),disambiguator:a(":input[name=disambiguator]",b.row).is(":checked")?
1:0,unique:a(":input[name=unique]",b.row).is(":checked")?1:0,hidden:a(":input[name=hidden]",b.row).is(":checked")?1:0,deprecated:a(":input[name=deprecated]",b.row).is(":checked")?1:0,lang:c.lang},"add"===b.mode&&a(".nav-delegate",b.row).is(".current")&&(e.delegated=a(":input[name=delegated]",b.row).val()),e={url:b.ajax.url,type:"POST",dataType:"json",data:a.extend(e,b.ajax.data)},e.success=b.ajax.success||function(e,g,h){if(e.code==="/api/status/error")return d.ajax_error_handler(h,b.row);var i=a(e.result.html).addClass("new-row");
b.row.before(i);i.hide();i.showRow(function(){c.schema.init_row_menu(i);a(".edit",i).show()},null,"slow");b.row.trigger(b.event_prefix+"success")},e.error=b.ajax.error||function(a){d.ajax_error_handler(a,b.row)},a.ajax(e)):b.row.removeClass("loading")},validate_property_form:function(b){""===a.trim(a("input[name=name]:visible",b.row).val())&&b.row.trigger(b.event_prefix+"error","Name is required");var c=a("input[name=key]",b.row);d.validate_mqlkey(b,c);var c=a(":input[name=expected_type]",b.row).val(),
e=a(":input[name=expected_type_new]",b.row).val();""===c&&""===e&&b.row.trigger(b.event_prefix+"error",[b.row,"Expected Type is required"])},add_included_type_begin:function(b,h){var f=b.parents("tr:first");a.ajax({url:c.h.ajax_url("add_included_type_begin.ajax"),data:{id:h,lang:c.lang},dataType:"json",success:function(g,h,i){if("/api/status/error"===g.code)return d.ajax_error_handler(i,f);var g=a(g.result.html),j={mode:"edit",event_prefix:"fb.schema.type.add.included_type.",ajax:{url:c.h.ajax_url("add_included_type_submit.ajax")},
init_form:e.init_included_type_form,validate_form:e.validate_included_type_form,submit_form:e.submit_included_type_form,table:b.parents("table:first"),trigger:b,trigger_row:f,row:a(".edit-row",g).hide(),submit_row:a(".edit-row-submit",g).hide()};d.init_edit_form(j);j.row.bind("fb.schema.type.add.included_type.success",function(){a(".button.cancel",j.submit_row).text("Done");e.init_included_type_form(j)})},error:function(a){d.ajax_error_handler(a,f)}})},init_included_type_form:function(b){var d=a("input[name=included_type_input]",
b.row).val(""),e=a("input[name=included_type]",b.row).val(""),g=a("input[name=included_type_new]",b.row).val("");b.row.data("initialized")||(d.suggest(a.extend(c.suggest_options.included_type(),{suggest_new:"Create new type"})).bind("fb-select",function(a,b){d.val(b.id);e.val(b.id)}).bind("fb-textchange",function(){e.val("")}).bind("fb-select-new",function(b,c){g.val(a.trim(c));e.val("")}),a(":input:not(textarea)",b.row).keypress(function(a){13===a.keyCode&&!a.isDefaultPrevented()&&b.row.trigger(b.event_prefix+
"submit")}).keyup(function(a){27===a.keyCode&&b.row.trigger(b.event_prefix+"cancel")}),b.row.data("initialized",!0));d.focus()},validate_included_type_form:function(b){var c=a.trim(a(":input[name=included_type]",b.row).val()),d=a(":input[name=included_type_new]",b.row).val();""===c&&""===d&&b.row.trigger(b.event_prefix+"error",[b.row,"Please choose a type to include"])},submit_included_type_form:function(b){var e={id:a(":input[name=id]",b.row).val(),included_type:a.trim(a(":input[name=included_type]",
b.row).val()),included_type_new:a(":input[name=included_type_new]",b.row).val()};a.ajax({url:b.ajax.url,type:"POST",dataType:"json",data:a.extend(e,b.ajax.data),success:function(e,g,h){if("/api/status/error"===e.code)return d.ajax_error_handler(h,b.row);g=a("<table>");g.html(e.result.html);var i=a(">thead",g);b.table.append(i);a("tr:first",i).hide().showRow(function(){a(".tbody-header",i).each(function(){a(this).data("ajax",!0).click(c.schema.type.toggle);a(".edit",this).show()});b.row.trigger(b.event_prefix+
"success")},null,"slow")},error:function(a){d.ajax_error_handler(a,b.row)}})},delete_included_type_begin:function(b,e,f){var g=b.parents("tr:first");g.parents("table:first");a.ajax({url:c.h.ajax_url("delete_included_type_submit.ajax"),data:{id:e,included_type:f,lang:c.lang},type:"POST",dataType:"json",success:function(b,c,e){if("/api/status/error"===b.code)return d.ajax_error_handler(e,g);b=a(b.result.html).addClass("new-row");g.before(b);b.hide();g.parent("thead").next("tbody:first").remove();g.remove();
b.showRow()},error:function(a){d.ajax_error_handler(a,g)}})},undo_delete_included_type_begin:function(b,e,f){var g=b.parents("tr:first");g.parents("table:first");a.ajax({url:c.h.ajax_url("undo_delete_included_type_submit.ajax"),data:{id:e,included_type:f,lang:c.lang},type:"POST",dataType:"json",success:function(b,e,f){if("/api/status/error"===b.code)return d.ajax_error_handler(f,g);var b=a(b.result.html),h=a(">tr",b).addClass("new-row"),e=g.parents("thead:first");e.before(b);h.hide();e.remove();h.showRow(function(){a(".tbody-header",
h).each(function(){a(this).data("ajax",!0).click(c.schema.type.toggle);a(".edit",this).show()})},null,"slow")},error:function(a){d.ajax_error_handler(a,g)}})},reverse_property_begin:function(b,h,f){var g=b.parents("tr:first");a.ajax({url:c.h.ajax_url("reverse_property_begin.ajax"),data:{id:h,master:f,lang:c.lang},dataType:"json",success:function(h,i,j){if("/api/status/error"===h.code)return d.ajax_error_handler(j,g);var h=a(h.result.html),l={mode:"edit",event_prefix:"fb.schema.type.reverse.property.",
ajax:{url:c.h.ajax_url("add_property_submit.ajax"),data:{master_property:f},success:function(a,b,c){if("/api/status/error"===a.code)return d.ajax_error_handler(c,l.row);e.reverse_property_success(l,a)}},init_form:e.init_property_form,validate_form:e.validate_property_form,submit_form:e.submit_property_form,table:b.parents("table:first"),trigger:b,trigger_row:g,row:a(".edit-row",h).hide(),submit_row:a(".edit-row-submit",h).hide()};d.init_edit_form(l)},error:function(a){d.ajax_error_handler(a,g)}})},
reverse_property_success:function(b,d){var f=a(d.result.html).addClass("new-row"),g=a("#type-table table:first"),k=a("> tbody",g);k.append(f);f.hide();f.showRow(function(){c.schema.init_row_menu(f);c.schema.type.init_tooltips(f);a(".edit",f).show()},null,"slow");k=a(".table-empty-column",k);k.length&&k.parents("tr:first").hide().prev("tr").show();b.trigger_row.remove();b.row.remove();b.submit_row.remove();e.toggle_reorder_link(g)},add_instance_begin:function(b,h){var f=b.parents("tr:first");a.ajax({url:c.h.ajax_url("add_instance_begin.ajax"),
data:{id:h,lang:c.lang},dataType:"json",success:function(g,k,i){if("/api/status/error"===g.code)return d.ajax_error_handler(i,f);var g=a(g.result.html),j={mode:"add",event_prefix:"fb.schema.type.add.instance.",ajax:{url:c.h.ajax_url("add_instance_submit.ajax"),data:{type:h}},init_form:e.init_instance_form,validate_form:e.validate_instance_form,submit_form:e.submit_instance_form,table:b.parents("table:first"),trigger:b,trigger_row:f,row:a(".edit-row",g).hide(),submit_row:a(".edit-row-submit",g).hide()};
d.init_edit_form(j);j.row.bind(j.event_prefix+"success",function(){var b=a("tbody:first .table-empty-column",j.table);b.length&&b.parents("tr:first").hide().prev("tr").show();a(".button.cancel",j.submit_row).text("Done");e.init_instance_form(j)})},error:function(a){d.ajax_error_handler(a,f)}})},init_instance_form:function(b){var d=a("input[name=name]",b.row),e=a("input[name=id]",b.row);d.val("");e.val("");d.data("suggest")||(d.suggest(a.extend(c.suggest_options.instance("/common/topic"),{suggest_new:"Create new"})).bind("fb-select",
function(a,b){e.val(b.id)}).bind("fb-select-new",function(){e.val("")}).bind("fb-textchange",function(){e.val("")}),d.keypress(function(a){13===a.keyCode&&!a.isDefaultPrevented()&&b.row.trigger(b.event_prefix+"submit")}).keyup(function(a){27===a.keyCode&&b.row.trigger(b.event_prefix+"cancel")}));d.focus()},validate_instance_form:function(b){var c=a.trim(a(":input[name=name]",b.row).val()),d=a(":input[name=id]",b.row).val();""===c&&""===d&&b.row.trigger(b.event_prefix+"error",[b.row,"Please select or create a new topic"])},
submit_instance_form:function(b){var e=a(":input[name=name]",b.row),f={name:a.trim(e.val()),id:a(":input[name=id]",b.row).val()},f={url:b.ajax.url,type:"POST",dataType:"json",data:a.extend(f,b.ajax.data),success:function(f,k,i){if("/api/status/error"===f.code)return d.ajax_error_handler(i,b.row);var j=a(f.result.html).addClass("new-row");b.row.before(j);j.hide();j.showRow(function(){c.schema.init_row_menu(j);a(".edit",j).show();e.focus()},null,"slow");b.row.trigger(b.event_prefix+"success")},error:function(a){d.ajax_error_handler(a,
b.row)}};a.ajax(f)},delete_instance_begin:function(b,e,f){var g=b.parents("tr:first");g.parents("table:first");a.ajax({url:c.h.ajax_url("delete_instance_submit.ajax"),data:{id:e,type:f},type:"POST",dataType:"json",success:function(b,c,e){if("/api/status/error"===b.code)return d.ajax_error_handler(e,g);b=a(b.result.html).addClass("new-row");g.before(b);b.hide();g.remove();b.showRow()},error:function(a){d.ajax_error_handler(a,g)}})},undo_delete_instance_begin:function(b,e,f){var g=b.parents("tr:first");
g.parents("table:first");a.ajax({url:c.h.ajax_url("undo_delete_instance_submit.ajax"),data:{id:e,type:f},type:"POST",dataType:"json",success:function(b,e,f){if("/api/status/error"===b.code)return d.ajax_error_handler(f,g);var h=a(b.result.html).addClass("new-row");g.before(h);h.hide();g.remove();h.showRow(function(){c.schema.init_row_menu(h);a(".edit",h).show()},null,"slow")},error:function(a){d.ajax_error_handler(a,g)}})},reorder_property_begin:function(b,h){a.ajax({url:c.h.ajax_url("reorder_property_begin.ajax"),
data:{id:h,lang:c.lang},dataType:"json",success:function(b){b=a(b.result.html);b={event_prefix:"fb.schema.type.reorder.property",ajax:{url:c.h.ajax_url("reorder_property_submit.ajax"),data:{id:h}},init_form:e.init_reorder_property_form,submit_form:e.submit_reorder_property_form,form:b};d.init_modal_form(b);b.form.bind(b.event_prefix+"success",function(a,b){window.location=b.location})}})},init_reorder_property_form:function(b){var c=a(".reorderable",b.form).sortable();a(".btn-mv-top",b.form).click(function(){var b=
a(this).parent(".reorderable-item");c.prepend(b)})},submit_reorder_property_form:function(b){var c=[];a("input[name=properties]",b.form).each(function(){c.push(a(this).val())});var e={id:a("input[name=type]",b.form).val(),properties:c};a.ajax({url:b.ajax.url,type:"POST",dataType:"json",data:a.extend(e,b.ajax.data),traditional:!0,success:function(a,c,e){if("/api/status/error"===a.code)return d.ajax_error_handler(e,null,b.form);b.form.trigger(b.event_prefix+"success",a.result)},error:function(a){d.ajax_error_handler(a,
null,b.form)}})},toggle_reorder_link:function(b){var c=a(".reorder-link",b);1<a("> tbody > tr.hoverable",b).length?c.show():c.hide()}}})(jQuery,window.freebase);
