
/*
 * Copyright 2010, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Additional Licenses for Third Party components can be found here:
 * http://wiki.freebase.com/wiki/Freebase_Site_License
 *
 */
/*
 
 jQuery Tools @VERSION / Expose - Dim the lights

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/toolbox/expose.html

 Since: Mar 2010
 Date: @DATE 
 
 jQuery Tools @VERSION Overlay - Overlay base. Extend it.

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/overlay/

 Since: March 2008
 Date: @DATE 
*/
(function(c,g){var b=window.propbox={init:function(a,d){d=c.extend({lang:"/lang/en"},d);if(!d.base_ajax_url)throw new Error("base_ajax_url required in propbox options");if(!d.base_static_url)throw new Error("base_static_url required in propbox options");if(!d.id)throw new Error("topic id required in propbox options");if(!d.lang)throw new Error("lang required in propbox options");b.options=d;b.kbs=new g(a);b.kbs.set_next(b.kbs.get_current(),c(".kbs:visible:first",a,true));c(".kbs",a).live("click",
function(){var f=b.kbs.get_current();b.kbs.set_next(f,c(this),true)}).live("edit",function(){var f=c(this).find(".headmenu:first").data("submenu");f&&c("li:first a:first",f).click()});b.init_menus(a)},init_menus:function(a,d){a=c(a||document);d&&c(".nicemenu",a).nicemenu();(a&&a.is(".data-row")?a:c(".data-row",a)).hover(b.row_menu_hoverover,b.row_menu_hoverout);c(".nicemenu .headmenu",a).add(c(".nicemenu .default-action",a)).click("click",function(){if(b.kbs){var f=b.kbs.get_current();f&&b.kbs.set_next(f,
c(this).parents(".kbs:first"),true)}return false})},row_menu_hoverover:function(){var a=c(this);b.row_menu_hoverover.timeout=setTimeout(function(){a.addClass("row-hover")},300)},row_menu_hoverout:function(){clearTimeout(b.row_menu_hoverover.timeout);c(this).removeClass("row-hover")},get_script:function(a,d){var f=b.get_script.cache;if(!f)f=b.get_script.cache={};var e=f[a];if(e)if(e.state===1)e.callbacks.push(d);else e.state===4&&d();else{e=f[a]={state:0,callbacks:[d]};c.ajax({url:b.options.base_static_url+
a,dataType:"script",beforeSend:function(){e.state=1},success:function(){e.state=4;c.each(e.callbacks,function(h,j){j()})},error:function(){e.state=-1}})}},prop_edit:function(a,d){var f=c(a).parents(".submenu").data("headmenu").parents(".property-section").find(".data-section .data-row:first:visible .nicemenu:first .headmenu:first a");f.length?f.click():b.prop_add(a,d);return false},prop_add:function(a,d){var f=c(a).parents(".submenu").data("headmenu").parents(".property-section");if(f.is(".editing"))return false;
f.addClass("editing");b.get_script("/propbox-edit.mf.js",function(){b.edit.prop_add_begin(f,d)});return false},value_edit:function(a){var d=c(a).parents(".submenu").data("headmenu").parents(".data-row:first"),f=d.parents(".property-section");if(f.is(".editing"))return false;f.addClass("editing");b.get_script("/propbox-edit.mf.js",function(){b.edit.value_edit_begin(f,d)});return false},value_delete:function(a){var d=c(a).parents(".submenu").data("headmenu").parents(".data-row:first"),f=d.parents(".property-section");
if(f.is(".editing"))return false;f.addClass("editing");b.get_script("/propbox-edit.mf.js",function(){b.edit.value_delete_begin(f,d)});return false},close_message:function(a){c(a).parents(".row-msg:first").remove();return false}}})(jQuery,window.kbs);
(function(c){function g(){if(c.browser.msie){var i=c(document).height(),k=c(window).height();return[window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth,i-k<20?k:i]}return[c(document).width(),c(document).height()]}function b(i){if(i)return i.call(c.mask)}c.tools=c.tools||{version:"@VERSION"};var a;a=c.tools.expose={conf:{maskId:"exposeMask",loadSpeed:"slow",closeSpeed:"fast",closeOnClick:true,closeOnEsc:true,zIndex:9998,opacity:0.8,startOpacity:0,color:"#fff",onLoad:null,
onClose:null}};var d,f,e,h,j;c.mask={load:function(i,k){if(e)return this;if(typeof i=="string")i={color:i};i=i||h;h=i=c.extend(c.extend({},a.conf),i);d=c("#"+i.maskId);if(!d.length){d=c("<div/>").attr("id",i.maskId);c("body").append(d)}var l=g();d.css({position:"absolute",top:0,left:0,width:l[0],height:l[1],display:"none",opacity:i.startOpacity,zIndex:i.zIndex});i.color&&d.css("backgroundColor",i.color);if(b(i.onBeforeLoad)===false)return this;i.closeOnEsc&&c(document).bind("keydown.mask",function(m){m.keyCode==
27&&c.mask.close(m)});i.closeOnClick&&d.bind("click.mask",function(m){c.mask.close(m)});c(window).bind("resize.mask",function(){c.mask.fit()});if(k&&k.length){j=k.eq(0).css("zIndex");c.each(k,function(){var m=c(this);/relative|absolute|fixed/i.test(m.css("position"))||m.css("position","relative")});f=k.css({zIndex:Math.max(i.zIndex+1,j=="auto"?0:j)})}d.css({display:"block"}).fadeTo(i.loadSpeed,i.opacity,function(){c.mask.fit();b(i.onLoad)});e=true;return this},close:function(){if(e){if(b(h.onBeforeClose)===
false)return this;d.fadeOut(h.closeSpeed,function(){b(h.onClose);f&&f.css({zIndex:j})});c(document).unbind("keydown.mask");d.unbind("click.mask");c(window).unbind("resize.mask");e=false}return this},fit:function(){if(e){var i=g();d.css({width:i[0],height:i[1]})}},getMask:function(){return d},isLoaded:function(){return e},getConf:function(){return h},getExposed:function(){return f}};c.fn.mask=function(i){c.mask.load(i);return this};c.fn.expose=function(i){c.mask.load(i,this);return this}})(jQuery);
(function(c){function g(d,f){var e=this,h=d.add(e),j=c(window),i,k,l,m=c.tools.expose&&(f.mask||f.expose),o=Math.random().toString().slice(10);if(m){if(typeof m=="string")m={color:m};m.closeOnClick=m.closeOnEsc=false}var p=f.target||d.attr("rel");k=p?c(p):d;if(!k.length)throw"Could not find Overlay: "+p;d&&d.index(k)==-1&&d.click(function(n){e.load(n);return n.preventDefault()});c.extend(e,{load:function(n){if(e.isOpened())return e;var r=a[f.effect];if(!r)throw'Overlay: cannot find effect : "'+f.effect+
'"';f.oneInstance&&c.each(b,function(){this.close(n)});n=n||c.Event();n.type="onBeforeLoad";h.trigger(n);if(n.isDefaultPrevented())return e;l=true;m&&c(k).expose(m);var q=f.top,t=f.left,u=k.outerWidth({margin:true}),v=k.outerHeight({margin:true});if(typeof q=="string")q=q=="center"?Math.max((j.height()-v)/2,0):parseInt(q,10)/100*j.height();if(t=="center")t=Math.max((j.width()-u)/2,0);r[0].call(e,{top:q,left:t},function(){if(l){n.type="onLoad";h.trigger(n)}});m&&f.closeOnClick&&c.mask.getMask().one("click",
e.close);f.closeOnClick&&c(document).bind("click."+o,function(s){c(s.target).parents(k).length||e.close(s)});f.closeOnEsc&&c(document).bind("keydown."+o,function(s){s.keyCode==27&&e.close(s)});return e},close:function(n){if(!e.isOpened())return e;n=n||c.Event();n.type="onBeforeClose";h.trigger(n);if(!n.isDefaultPrevented()){l=false;a[f.effect][1].call(e,function(){n.type="onClose";h.trigger(n)});c(document).unbind("click."+o).unbind("keydown."+o);m&&c.mask.close();return e}},getOverlay:function(){return k},
getTrigger:function(){return d},getClosers:function(){return i},isOpened:function(){return l},getConf:function(){return f}});c.each("onBeforeLoad,onStart,onLoad,onBeforeClose,onClose".split(","),function(n,r){c.isFunction(f[r])&&c(e).bind(r,f[r]);e[r]=function(q){c(e).bind(r,q);return e}});i=k.find(f.close||".close");if(!i.length&&!f.close){i=c('<a class="close"></a>');k.prepend(i)}i.click(function(n){e.close(n)});f.load&&e.load()}c.tools=c.tools||{version:"@VERSION"};c.tools.overlay={addEffect:function(d,
f,e){a[d]=[f,e]},conf:{close:null,closeOnClick:true,closeOnEsc:true,closeSpeed:"fast",effect:"default",fixed:!c.browser.msie||c.browser.version>6,left:"center",load:false,mask:null,oneInstance:true,speed:"normal",target:null,top:"10%"}};var b=[],a={};c.tools.overlay.addEffect("default",function(d,f){var e=this.getConf(),h=c(window);if(!e.fixed){d.top+=h.scrollTop();d.left+=h.scrollLeft()}d.position=e.fixed?"fixed":"absolute";this.getOverlay().css(d).fadeIn(e.speed,f)},function(d){this.getOverlay().fadeOut(this.getConf().closeSpeed,
d)});c.fn.overlay=function(d){var f=this.data("overlay");if(f)return f;if(c.isFunction(d))d={onBeforeLoad:d};d=c.extend(true,{},c.tools.overlay.conf,d);this.each(function(){f=new g(c(this),d);b.push(f);c(this).data("overlay",f)});return d.api?f:this}})(jQuery);
(function(c){c.fn.mqlkey=function(b){return this.each(function(){var a=c(this);if(a.is(":text")){var d=a.data("mqlkey");d&&d._destroy();d=new g(this,b);a.data("mqlkey",d)}})};var g=c.mqlkey=function(b,a){this.options=c.extend(true,{},g.defaults,a);this.input=c(b);this.original=this.input.val();this.init()};g.prototype={init:function(){var b=this;this.input.bind("keyup.mqlkey",function(a){b.textchange(a)}).bind(c.browser.msie?"paste.mqlkey":"input.mqlkey",function(a){b.textchange(a)});if(this.options.source){this.source=
c(this.options.source);this.source_generate=true;this.input.bind("change.mqlkey",function(){b.source_generate=false});this.source.bind("change.mqlkey",function(){if(b.source_generate){var a=g.from(b.source.val());b.input.val(a).trigger("keyup")}})}},_destroy:function(){this.input.unbind(".mqlkey");this.source&&this.source.unbind("change.mqlkey")},textchange:function(b){clearTimeout(this.textchange_timeout);var a=this;this.textchange_timeout=setTimeout(function(){a.textchange_delay(b)},200)},textchange_delay:function(){this.input.trigger("textchange");
var b=c.trim(this.input.val());return b===this.original&&b!==""?this.valid(b):g.reserved_word(b)?this.invalid(b,b+" is a reserved word."):g.test(b,this.options.schema)?b.length<this.options.minlen?this.invalid(b):this.options.check_key?this.check_key(b):this.valid(b):this.invalid(b)},check_key:function(b){var a=this;if(this.xhr){this.xhr.abort();this.xhr=null}var d={id:null,key:{namespace:this.options.namespace,value:b}};clearTimeout(this.check_key.timeout);this.check_key.timeout=setTimeout(function(){a.xhr=
a.options.mqlread(d,function(f){return f?a.invalid(b,"Key already exists"):a.valid(b)},function(f){return f?a.invalid(f.responseText()):a.invalid("mqlread error!")})},200)},valid:function(b){this.input.trigger("valid",b)},invalid:function(b,a){if(!a){a=this.options.minlen>1?"Key must be "+this.options.minlen+" or more alphanumeric characters":"Key must be alphanumeric";a+=", lowercase, begin with a letter and not end with a non-alphanumeric character. Underscores are allowed but not consecutively."}this.input.trigger("invalid",
a)}};c.extend(g,{defaults:{minlen:1,check_key:true,namespace:"/",mqlread:function(b,a,d){return g.mqlread(null,b,a,d)},source:null,schema:false},mqlread:function(b,a,d,f){b={url:b||"http://api.freebase.com/api/service/mqlread",data:{query:JSON.stringify({query:a})},dataType:"jsonp",success:function(e){return d(e.result)},error:f};return c.ajax(b)},from:function(b){b=b.toLowerCase();b=b.replace(/[^a-z0-9]/g,"_");b=b.replace(/\_\_+/g,"_");b=b.replace(/[^a-z0-9]+$/,"");b=b.replace(/^[^a-z]+/,"");if(g.reserved_word(b))b=
"x_"+b;return b},reservedwords:"meta typeguid left right datatype scope attribute relationship property link class future update insert delete replace create destroy default sort limit offset optional pagesize cursor index !index for while as in is if else return count function read write select var connect this self super xml sql mql any all macro estimate-count",typeonlywords:"guid id object domain name key type keys value timestamp creator permission namespace unique schema reverse",_reserved_word:null,
reserved_word:function(b){if(!g._reserved_word){g._reserved_word={};c.each([g.reservedwords,g.typeonlywords],function(a,d){c.each(d.split(" "),function(f,e){g._reserved_word[e]=1})})}return g._reserved_word[b]===1},fast:/^[A-Za-z0-9](?:[_-]?[A-Za-z0-9])*$/,slow:/^(?:[A-Za-z0-9]|\$[A-F0-9]{4})(?:[_-]?[A-Za-z0-9]|[_-]?\$[A-F0-9]{4})*$/,schema:/^[a-z](?:_?[a-z0-9])*$/,test:function(b,a){if(a)return g.schema.test(b);return g.fast.test(b)||g.slow.test(b)}})})(jQuery);
(function(c,g){g.require("dojo.date.stamp");g.require("dojo.date.locale");g.require("dojo.number");c.fn.validate_input=function(a){return this.each(function(){var d=c(this);if(d.is(":text")){var f=d.data("$.validate_input");f&&f._destroy();f=new b(this,a);d.data("$.validate_input",f)}})};var b=c.validate_input=function(a,d){var f=this.options=c.extend(true,{},b.defaults,d);if(typeof f.validator!=="function")throw"A validator is required";if(!f.lang)f.lang="/lang/en";f.lang=f.lang==="/lang/en"?["lang/en"]:
[f.lang,"/lang/en"];f.locales=[];c.each(f.lang,function(h,j){f.locales[h]=g.i18n.normalizeLocale(j.split("/").pop())});this.input=c(a);this.init();var e=this;this.input.bind("remove",function(){e._destroy()});return this};b.prototype={init:function(){var a=this;this.input.bind("keyup.validate_input",function(d){a.textchange(d)}).bind(c.browser.msie?"paste.validate_input":"input.validate_input",function(d){a.textchange(d)}).bind("keypress.validate_input",function(d){d.keyCode===13&&a.validate(true)}).bind("blur.validate_input",
function(){a.validate(true)})},_destroy:function(){this.input.unbind(".validate_input")},valid:function(a){this.input.trigger("valid",a)},invalid:function(a,d){this.input.trigger("invalid",d)},empty:function(){this.input.trigger("empty")},textchange:function(){clearTimeout(this.textchange_timeout);var a=this;this.textchange_timeout=setTimeout(function(){a.validate()},200)},validate:function(a){a&&clearTimeout(this.textchange_timeout);a=this.options;var d=c.trim(this.input.val());if(d==="")return this.empty();
try{return this.valid(a.validator(d,a))}catch(f){return this.invalid(d,""+f)}}};c.extend(b,{defaults:{validator:function(a){return{text:a,value:a}}},log:function(){},invalid:function(a,d,f,e){throw new Error("Invalid "+f+(e?": "+e:""));},text:function(a,d){if(a.lengh>4096)return this.invalid(a,d,type,"Text too long");return{text:a,value:a}},topic:function(){return b.defaults.validator},enumerated:function(){return b.defaults.validator},"boolean":function(){return b.defaults.validator},uri:function(a,
d){var f=b.uri.regex;if(!f)f=b.uri.regex=/^(https?|ftp):\/\/(((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:)*@)?(((\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5]))|((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?)(:\d*)?)(\/((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)+(\/(([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)*)*)?)?(\?((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|[\uE000-\uF8FF]|\/|\?)*)?(\#((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|\/|\?)*)?$/i;
if(f.test(a))return{text:a,value:a};return b.invalid(a,d,"uri")},"int":function(a,d){return b.number.parse(a,d,false)},"float":function(a,d){return b.number.parse(a,d,true)},number:function(a,d,f){return b.number.parse(a,d,f)},datetime:function(a,d){return b.datetime.parse(a,d)},mqlkey:function(a,d){var f=b.mqlkey.regex;if(!f)f=b.mqlkey.regex=/^[A-Za-z0-9][A-Za-z0-9_-]*$/;if(f.test(a))return{text:a,value:a};return b.invalid(a,d,"mqlkey")}});c.extend(b.number,{parse:function(a,d,f){var e=d&&d.locales||
["en"],h,j;h=0;for(j=e.length;h<j;h++){var i=e[h];d=g.number.parse(a,{locale:i});if(!isNaN(d)){a={};if(f){a.value=d;a.text=g.number.format(d,{locale:i})}else{a.value=g.number.round(d,0);a.text=g.number.format(a.value,{locale:i})}return a}}throw b.invalid("number",a);}});c.extend(b.datetime,{formats:["yyyy",["dateFormatItem-y"],"yyyy-MM",["dateFormatItem-yM","dateFormatItem-yMMM"],"yyyy-MM-dd",["dateFormat-short","dateFormat-medium","dateFormat-long"]],parse:function(a,d){if(!g.date.stamp._isoRegExp)g.date.stamp._isoRegExp=
/^(?:(-?\d{4})(?:-(\d{2})(?:-(\d{2}))?)?)?(?:T(\d{2}):(\d{2})(?::(\d{2})(.\d+)?)?((?:[+-](\d{2}):(\d{2}))|Z)?)?$/;var f=g.date.stamp.fromISOString(a);if(f)return{text:a,value:a,date:f};var e=d&&d.locales||["en"],h,j,i,k,l,m;h=0;for(j=e.length;h<j;h++){var o=e[h],p=g.date.locale._getGregorianBundle(o);i=0;for(k=b.datetime.formats.length;i<k;i+=2){var n=b.datetime.formats[i],r=b.datetime.formats[i+1];l=0;for(m=r.length;l<m;l++){var q=p[r[l]];if(q){q=i18n.normalize_pattern(q);try{f=g.date.locale.parse(a,
{datePattern:q,selector:"date",locale:o});return{text:a,value:g.date.locale.format(f,{datePattern:n,selector:"date"}),date:f}}catch(t){}}}}}throw b.invalid("datetime",a);}})})(jQuery,dojo);
(function(c){c.fn.data_input=function(g){return this.each(function(){var b=c(this),a=b.data("$.data_input");a&&a._destroy();a=new c.data_input(this,g);b.data("$.data_input",a)})};c.data_input=function(g,b){this.options=c.extend(true,{},b);this.container=c(g);this.metadata=this.container.metadata();this.input=c(":input",this.container);this.init();var a=this;this.input.bind("remove",function(){a._destroy()})};c.data_input.prototype={init:function(){var g=this,b=this.container,a=this.input,d=this.options;
a.bind("focusin.data_input",function(){g.container.addClass("focus")}).bind("focusout.data_input",function(){g.container.removeClass("focus")}).bind("valid.data_input",function(e,h){function j(){g.container.data("data",i);g.container.removeClass("error").addClass("valid");g.container.trigger("valid")}var i={name:g.input.attr("name")};if(h.id)i.id=h.id;else if(h.create_new){i.create_new=h.create_new;i.lang=g.metadata.lang||d.lang}else{i.value=h.value;if(g.metadata.type==="/type/text")i.lang=g.metadata.lang||
d.lang}h.id&&g.metadata.type&&g.options.incompatible_types?g.options.incompatible_types.check(h.id,g.metadata.type,j,g.options.incompatible_types.inline_suggest_incompatible_callback(g.input,j)):j()}).bind("invalid.data_input",function(){g.container.removeData("data");g.container.removeClass("valid").addClass("error");g.container.trigger("invalid")}).bind("empty.data_input",function(){var e={name:g.input.attr("name")};if(g.metadata&&g.metadata.lang)e.lang=g.metadata.lang;g.container.data("data",e);
g.container.removeClass("valid").removeClass("error");g.container.trigger("empty")}).bind("keypress.data_input",function(e){e.keyCode===13&&!e.isDefaultPrevented()&&g.container.trigger("submit")}).bind("keyup.data_input",function(e){e.keyCode===27&&g.container.trigger("cancel")});if(b.is(".topic")){b=g.metadata.type;var f=null;if(d.suggest_impl)f=d.suggest_impl.instance(b,true,g.metadata&&g.metadata.lang||d.lang);a.validate_topic(f).bind("valid.data_input",function(e,h){g.fb_select(h)}).bind("invalid.data_input",
function(){g.fb_textchange()});if(this.metadata&&this.metadata.id){a.data("data.suggest",this.metadata);this.validate()}}else if(b.is(".text"))a.validate_input({validator:c.validate_input.text});else if(b.is(".datetime"))a.validate_input({validator:c.validate_input.datetime,lang:d.lang});else if(b.is(".enumerated")){a.validate_enumerated().bind("valid.data_input",function(e,h){g.fb_select(h)}).bind("invalid.data_input",function(){g.fb_textchange()});this.metadata&&this.metadata.id&&this.validate()}else if(b.is(".int"))a.validate_input({validator:c.validate_input["int"],
lang:d.lang});else if(b.is(".float"))a.validate_input({validator:c.validate_input["float"],lang:d.lang});else if(b.is(".uri"))a.validate_input({validator:c.validate_input.uri});else if(b.is(".boolean"))a.validate_boolean();else if(b.is(".enumeration"))a.validate_input({validator:c.validate_input.mqlkey});else if(b.is(".rawstring"))a.validate_input({validator:c.validate_input.text});else throw new Error("Invalid data-input: "+b.attr("class"));},_destroy:function(){this.input.unbind(".data_input")},
validate:function(){var g=this.input;c.each(["$.validate_topic","$.validate_input","$.validate_enumerated","$.validate_boolean"],function(b,a){var d=g.data(a);if(d){d.validate(true);return false}})},reset:function(){this.container.removeData("data");if(this.input.is(":text"))this.input.val("");else if(this.input.is("select"))this.input[0].selectedIndex=0;else this.input.is(":radio")&&this.input.each(function(){this.checked=false})},fb_textchange:function(){},fb_select:function(){},ajax_beforeSend:function(g){if(!this.xhr_queue)this.xhr_queue=
[];this.xhr_queue.push(g);this.container.trigger("loading")},ajax_complete:function(g){if(!this.xhr_queue)this.xhr_queue=[];for(var b=0,a=this.xhr_queue.length;b<a;b++)if(g===this.xhr_queue[b]){this.xhr_queue.splice(b,1);break}this.xhr_queue.length===0&&this.container.trigger("loading_complete")}};c.fn.validate_topic=function(g){return this.each(function(){var b=c(this);if(b.is(":text")){var a=b.data("$.validate_topic");a&&a._destroy();a=new c.validate_topic(this,g);b.data("$.validate_topic",a)}})};
c.validate_topic=function(g,b){this.options=c.extend(true,{},b);this.input=c(g);this.init()};c.validate_topic.prototype={init:function(){var g=this;this.input.suggest(this.options).bind("fb-textchange.validate_topic",function(){g.input.val()===""?g.empty():g.invalid()}).bind("fb-select.validate_topic",function(b,a){g.input.val(a.name!=null?a.name:a.id);g.valid(a)}).bind("fb-select-new.validate_topic",function(b,a){g.valid(a)})},invalid:function(){this.input.trigger("invalid")},valid:function(g){if(typeof g===
"string")g={create_new:g};this.input.trigger("valid",g)},empty:function(){this.input.trigger("empty")},_destroy:function(){this.input.unbind(".validate_topic")},validate:function(){if(this.input.val()==="")this.empty();else{var g=this.input.data("data.suggest");g?this.valid(g):this.invalid()}}};c.fn.validate_enumerated=function(g){return this.each(function(){var b=c(this);if(b.is("select")){var a=b.data("$.validate_enumerated");a&&a._destroy();a=new c.validate_enumerated(this,g);b.data("$.validate_enumerated",
a)}})};c.validate_enumerated=function(g,b){this.options=c.extend(true,{},b);this.input=c(g);this.init()};c.validate_enumerated.prototype={init:function(){var g=this;this.input.bind("change.validate_enumerated, keypress.validate_enumerated",function(){this.selectedIndex===0?g.empty():g.valid({text:c(":selected",this).text(),id:this.value})})},invalid:function(){this.input.trigger("invalid")},valid:function(g){this.input.trigger("valid",g);this.input.trigger("fb-select",g)},empty:function(){this.input.trigger("empty")},
_destroy:function(){this.input.unbind(".validate_enumerated")},validate:function(){var g=this.input[0];g.selectedIndex>0?this.valid({text:c(":selected",this.input).text(),id:g.value}):this.empty()}};c.fn.validate_boolean=function(g){var b,a;this.each(function(){var f=c(this);if(f.is(":radio"))if(f.val().toLowerCase()==="true")b=f;else if(f.val().toLowerCase()==="false")a=f});if(b&&a){var d=b.data("$.validate_boolean");d&&d._destroy();d=new c.validate_boolean(b,a,g);b.data("$.validate_boolean",d)}return this};
c.validate_boolean=function(g,b,a){this.options=c.extend(true,{},a);this.tradio=g;this.fradio=b;this.input=this.tradio;this.init()};c.validate_boolean.prototype={init:function(){var g=this;this.tradio.bind("change.validate_boolean",function(){g.validate()})},_destroy:function(){this.input.unbind(".validate_boolean")},valid:function(g){this.input.trigger("valid",g)},empty:function(){this.input.trigger("empty")},validate:function(){if(this.tradio.is(":checked"))this.valid({text:this.tradio.text(),value:true});
else this.fradio.is(":checked")?this.valid({text:this.fradio.text(),value:false}):this.empty()}}})(jQuery);
(function(c,g){var b=window.formlib={init_inline_add_form:function(a){var d=a.event_prefix||"form.inline_add_form.";a.edit_row.bind(d+"submit",function(){b.submit_inline_add_form(a)}).bind(d+"cancel",function(){b.cancel_inline_add_form(a)}).bind(d+"error",function(f,e){b.error(a,e);a.edit_row.removeClass("loading")}).bind(d+"success",function(){a.edit_row.removeClass("loading")}).bind(d+"valid",function(){b.enable_submit(a)}).bind(d+"invalid",function(){b.disable_submit(a)});b.init_submit_cancel(a);
a.trigger&&a.trigger.parents(".trigger-row:first").hide();a.body.append(a.head_row).append(a.edit_row).append(a.submit_row);a.init(a)},submit_inline_add_form:function(a){if(!a.edit_row.is(".loading"))if(b.is_submit_enabled(a)){document.activeElement&&c(document.activeElement).blur();b.clear_message(a);if(a.validate(a)){a.edit_row.addClass("loading");a.submit(a,b.default_submit_ajax_options(a))}}},success_inline_add_form:function(a,d){a.head_row.before(d);g.ize(d);a.reset(a);a.edit_row.trigger(a.event_prefix+
"success")},cancel_inline_add_form:function(a){a.head_row.remove();a.edit_row.remove();a.submit_row.remove();a.trigger&&a.trigger.parents(".trigger-row:first").show()},init_inline_edit_form:function(a){var d=a.event_prefix||"form.inline_edit_form.";a.edit_row.bind(d+"submit",function(){b.submit_inline_edit_form(a)}).bind(d+"cancel",function(){b.cancel_inline_edit_form(a)}).bind(d+"error",function(f,e){b.error(a,e);a.edit_row.removeClass("loading")}).bind(d+"success",function(){a.edit_row.removeClass("loading")}).bind(d+
"valid",function(){b.enable_submit(a)}).bind(d+"invalid",function(){b.disable_submit(a)});b.init_submit_cancel(a);a.row.hide();a.row.before(a.head_row).before(a.edit_row).before(a.submit_row);a.init(a)},submit_inline_edit_form:function(a){if(!a.edit_row.is(".loading"))if(b.is_submit_enabled(a)){document.activeElement&&c(document.activeElement).blur();b.clear_message(a);if(a.validate(a)){a.edit_row.addClass("loading");a.submit(a,b.default_submit_ajax_options(a))}}},success_inline_edit_form:function(a,
d){a.row.replaceWith(d);a.row=d;g.ize(d);a.edit_row.trigger(a.event_prefix+"cancel")},cancel_inline_edit_form:function(a){a.head_row.remove();a.edit_row.remove();a.submit_row.remove();a.row.show()},success_inline_delete:function(a,d,f){a.hide().addClass("old-row");a.after(d);d.append(a);if(f){a=c('<a href="#">Undo</a>');c(".msg-default",d).next().append(a);a.click(function(){f();return false})}},success_inline_delete_undo:function(a){var d=c(".old-row",a);a.before(d);d.show().removeClass("old-row");
a.remove()},init_modal_form:function(a){c(document.body).append(a.form.hide());var d=a.event_prefix||"form.modal_form.";a.form.bind(d+"submit",function(){b.submit_modal_form(a)}).bind(d+"cancel",function(){b.cancel_modal_form(a)}).bind(d+"error",function(f,e){b.error(a,e);a.form.removeClass("loading")}).bind(d+"success",function(){a.form.removeClass("loading")}).bind(d+"valid",function(){b.enable_submit(a)}).bind(d+"invalid",function(){b.disable_submit(a)});b.init_submit_cancel(a);a.form.overlay({close:".modal-buttons .cancel",
closeOnClick:false,load:true,fixed:false,mask:{color:"#000",loadSpeed:200,opacity:0.5},onLoad:function(){a.overlay=this;a.init(a)}})},submit_modal_form:function(a){if(!a.form.is(".loading"))if(b.is_submit_enabled(a)){document.activeElement&&c(document.activeElement).blur();b.clear_message(a);if(a.validate(a)){a.form.addClass("loading");a.submit(a,b.default_submit_ajax_options(a))}}},cancel_modal_form:function(a){a.form.data("overlay").close()},init_submit_cancel:function(a){var d=a.form||a.edit_row,
f=a.form||a.submit_row,e=a.event_prefix;a=c(".save",f).click(function(){d.trigger(e+"submit")});b.disable(a);c(".cancel",f).click(function(){d.trigger(e+"cancel")});c(":input",d).keypress(function(h){h.keyCode===13&&!h.isDefaultPrevented()&&d.trigger(e+"submit")}).keyup(function(h){h.keyCode===27&&d.trigger(e+"cancel")})},disable:function(a){c(a).attr("disabled","disabled").addClass("disabled")},enable:function(a){c(a).removeAttr("disabled").removeClass("disabled")},disable_submit:function(a){b.disable(c(".save",
a.form||a.submit_row))},enable_submit:function(a){b.enable(c(".save",a.form||a.submit_row))},is_submit_enabled:function(a){return!c(".save",a.form||a.submit_row).is(":disabled")},init_mqlkey:function(a,d){return a.next(".key-status").removeClass("valid invalid loading").text("").removeAttr("title").end().mqlkey(d).bind("valid",function(){c(this).next(".key-status").removeClass("invalid loading").addClass("valid").text("valid").attr("title","Key is available")}).bind("invalid",function(f,e){c(this).next(".key-status").removeClass("valid loading").addClass("invalid").text("invalid").attr("title",
e)}).bind("textchange",function(){c(this).next(".key-status").removeClass("valid invalid").text("loading").addClass("loading")})},validate_mqlkey:function(a,d){var f=d.next(".key-status"),e=d.val();if(e===""){d.trigger(a.event_prefix+"error","Key is required");return false}if(e===d.data("mqlkey").original)return true;if(f.is(".invalid")){d.trigger(a.event_prefix+"error",f.attr("title"));return false}else if(f.is(".loading"))return false;return true},error:function(a,d){b.disable_submit(a);return b.message(a,
d,"error")},message:function(a,d,f){a=a.head_row;a.find(".close-msg").css("visibility","visible").next().find(".msg-default").hide().next().text(d);a.addClass("row-msg");f&&a.addClass("row-msg-"+f)},clear_message:function(){},default_begin_ajax_options:function(){return b._default_ajax_options("GET")},default_submit_ajax_options:function(a){var d=b._default_ajax_options("POST");if(a){c.extend(d,a.ajax);c("input[type=hidden]",a.submit_row||a.form).each(function(){d.data[this.name]=this.value})}return d},
_default_ajax_options:function(a){return{data:{},dataType:"json",type:a||"GET",success:function(d,f,e){if(!b.check_ajax_success.apply(this,arguments))return this._error.apply(this,[e]);this.onsuccess&&this.onsuccess.apply(this,arguments)},error:function(){b.check_ajax_error.apply(this,arguments);return this._error.apply(this,arguments)},_error:function(d){if(d.status===401)c(window).trigger("fb.user.unauthorized");else if(this.onerror)this.onerror.apply(this,[d.responseText].concat(Array.prototype.slice.call(arguments)));
else{var f={},e=this;c.each(["url","data","dataType","type"],function(h,j){f[j]=e[j]});c.each(["status","statusText","responseText"],function(h,j){f[j]=d[j]});f.responseHeaders=d.getAllResponseHeaders();c(window).trigger("fb.user.feedback",f)}}}},check_ajax_success:function(){return b.check_api_response.apply(this,arguments)},check_ajax_error:function(a){var d=a.responseText;try{d=JSON.stringify(d)}catch(f){}return b.check_api_response.apply(this,[d,a.statusText,a])},check_api_response:function(a,
d,f){if(typeof a==="object"){if(a.code!=="/api/status/ok")return false}else if(f.status!==200)return false;return true}}})(jQuery,window.i18n);
(function(c){var g=window.editparams={Empty:function(b,a,d){this.structure=b;this.data=a;this.msg=d;this.toString=function(){return"Empty: "+this.msg}},Invalid:function(b,a,d){this.structure=b;this.data=a;this.msg=d;this.toString=function(){return"Invalid: "+this.msg}},parse:function(b,a){function d(i,k,l,m,o){try{g.validate(k,l);o.push(l)}catch(p){if(p instanceof g.Empty)o.push(l);else throw p;}}var f=(b.values||[]).slice(),e=b.properties||[],h=b.expected_type.mediator;if(h){if(!e.length)throw new g.Invalid(b,
null,"mediator musth have 1 or more properties");if(f.length&&f.length!==1)throw new g.Invalid(b,null,"Can't edit more than one value (row) for a mediator");}var j=[];c(".data-input",a).each(function(){var i=c(this),k=i.data("$.data_input");if(!k)throw new g.Invalid(b,null,"$.data-input not initialized for",this);k.validate(true);if(i.is(".error"))throw new g.Invalid(b,null,"$.data-input is invalid",this);k=i.data("data");if(!k)throw new g.Invalid(b,null,"$.data-input has no data",this);if(h){if(!j.length){j.push({property:{}});
c.each(e,function(o,p){j[0].property[p.id]=c.extend({},p,{values:[]})})}var l=j[0].property[k.name];if(l){var m=[];if(f.length)m=(m=f[0].property[l.id])&&m.values||[];d(i,l,k,m,l.values)}else console.warn("editparams","unknown mediator property data",k)}else d(i,b,k,f,j)});return h?g.parse_mediator(b,f,j):g.parse_simple(b,f,j)},parse_mediator:function(b,a,d){if(d.length!==1)throw new g.Invalid(b,d,"Must specify one (new or updated) value for a mediator");d=d[0];var f;if(a.length)f=a[0];a={};if(f)a.id=
f.id;else{a.id=null;a.create="unconditional";a.connect=b.unique?"replace":"insert";var e=[];b.expected_type.id!=="/type/object"&&e.push({id:b.expected_type.id,connect:"insert"});var h=b.expected_type.included_types;h&&h.forEach(function(o){o!=="/type/object"&&e.push({id:o,connect:"insert"})});if(e.length)a.type=e}h=false;b=b.properties;for(var j=0,i=b.length;j<i;j++){var k=b[j],l=f&&f.property&&f.property[k.id],m=d.property&&d.property[k.id];l=g.parse_simple(k,l&&l.values||[],m&&m.values||[]);if(l.length){a[k.id]=
l;h=true}}return h?[a]:[]},parse_simple:function(b,a,d){return g.diff(b,a,d)},diff:function(b,a,d){var f=b.expected_type,e=b.expected_type.id,h=b.unique,j=e==="/type/text";if(h)if(!j)if(a.length&&a.length!==1)throw new g.Invalid(b,a,"Can't edit more than one value (row) for a unique property.");else if(d.length&&d.length!==1)throw new g.Invalid(b,d,"Can't edit more than one value (row) for a unique property.");var i=[];if(g.LITERAL_TYPE_IDS[e]){i.push("value");j&&i.push("lang")}else i.push("id");
e=[];var k=[],l,m;l=0;for(m=a.length;l<m;l++){var o=a[l];g.validate(b,o);g.inArray.apply(null,[o,d].concat(i))===-1&&e.push(g.clause(o,"delete"))}l=0;for(m=d.length;l<m;l++){o=d[l];try{g.validate(b,o)}catch(p){continue}if(g.inArray.apply(null,[o,a].concat(i))===-1){if(h)if(j){var n=g.inArray(o,e,"lang");n!==-1&&e.splice(n,1)}else return[g.clause(o,"replace",f)];k.push(g.clause(o,h?"replace":"insert",f))}}return e.concat(k)},validate:function(b,a){var d=b.expected_type.id;if(g.LITERAL_TYPE_IDS[d])if(g.isEmpty(a.value))throw new g.Empty(b,
a);else{if(d==="/type/text"&&g.isEmpty(a.lang))throw new g.Invalid(b,a,"Expected data.lang for /type/text");if(d==="/type/int"||d==="/type/float"){if(c.type(a.value)!=="number")throw new g.Invalid(b,a,"Expected number data.value for "+d);}else if(d==="/type/boolean"){if(c.type(a.value)!=="boolean")throw new g.Invalid(b,a,"Expected boolean data.value for /type/boolean");}else if(c.type(a.value)!=="string")throw new g.Invalid(b,a,"Expected string data.value for "+d);}else if(g.isEmpty(a.create_new)){if(g.isEmpty(a.id))throw new g.Empty(b,
a);}else if(g.isEmpty(a.lang))throw new g.Invalid(b,a,"Expected lang for creating a new topic");return a},type_clause:function(b){var a=[];if(b){if(b.enumeration)return a;b.id!=="/type/object"&&a.push({id:b.id,connect:"insert"});(b=b.included_types)&&b.forEach(function(d){d!=="/type/object"&&a.push({id:d,connect:"insert"})})}return a},clause:function(b,a,d){var f={connect:a};if(b.id){f.id=b.id;if(a!=="delete"&&d&&!d.enumeration){b=g.type_clause(d);if(b.length)f.type=b}}else if(b.create_new&&b.lang){f.name=
{value:b.create_new,lang:b.lang};f.id=null;f.create="unconditional";b=g.type_clause(d);if(b.length)f.type=b}else{f.value=b.value;if(b.lang)f.lang=b.lang}return f},inArray:function(b,a){var d=Array.prototype.slice.call(arguments,2);if(!d.length)return c.inArray(b,a);for(var f=0,e=a.length;f<e;f++){for(var h=a[f],j=true,i=0,k=d.length;i<k;i++){var l=d[i];if(h[l]!=b[l]){j=false;break}}if(j)return f}return-1},isEmpty:function(b){return b==null||b===""},LITERAL_TYPE_IDS:{"/type/int":1,"/type/float":1,
"/type/boolean":1,"/type/rawstring":1,"/type/uri":1,"/type/text":1,"/type/datetime":1,"/type/id":1,"/type/key":1,"/type/value":1,"/type/enumeration":1}}})(jQuery);
(function(c,g,b,a,d){var f=g.edit={prop_add_begin:function(e){c.ajax(c.extend(b.default_begin_ajax_options(),{url:g.options.base_ajax_url+"/prop_add_begin.ajax",data:{s:g.options.id,p:e.attr("data-id"),lang:g.options.lang},onsuccess:function(h){h=c(h.result.html);var j=h.metadata(),i=j.expected_type.id;return i==="/common/document"?f.prop_add_document(e,h,j):i==="/common/image"?f.prop_add_image(e,h,j):f.prop_add(e,h,j)}}))},prop_add:function(e,h,j){var i=c(">.data-section",e);i=c("> .data-table > tbody, > .data-list",
i);var k=c(".edit-row-head",h),l=c(".edit-row",h);h=c(".edit-row-submit",h);h={event_prefix:"propbox.edit.prop_add.",init:f.init_prop_add_form,validate:f.validate_prop_add_form,submit:f.submit_prop_add_form,reset:f.reset_prop_add_form,ajax:{url:g.options.base_ajax_url+"/prop_edit_submit.ajax"},body:i,head_row:k,edit_row:l,submit_row:h,structure:j};l.bind("propbox.edit.prop_add.cancel",function(){e.removeClass("editing")}).bind("propbox.edit.prop_add.success",function(){j.unique&&l.trigger(form.event_prefix+
"cancel")});b.init_inline_add_form(h)},init_prop_add_form:function(e){f.init_data_inputs(e);c(":input:visible:first",e.edit_row).focus()},validate_prop_add_form:function(){return true},reset_prop_add_form:function(e){f.reset_data_inputs(e);b.disable_submit(e);c(".cancel",e.submit_row).text("Done");c(":input:visible:first",e.edit_row).focus()},submit_prop_add_form:function(e,h){try{var j=a.parse(e.structure,e.edit_row);h.data.o=JSON.stringify(j)}catch(i){j=c(".data-input.error",e.edit_row);if(j.length){e.edit_row.trigger(e.event_prefix+
"error","Please specify a valid value");j.eq(0).find(":input").focus().select()}else e.edit_row.trigger(e.event_prefix+"error",i.toString());return}c.ajax(c.extend(h,{onsuccess:function(k){k=c(k.result.html);b.success_inline_add_form(e,k);g.init_menus(k,true);c(".nicemenu-item.edit").show();g.kbs.set_next(null,k,true)},onerror:function(k){e.edit_row.trigger(e.event_prefix+"error",k)}}))},value_edit_begin:function(e,h){var j;if(h.is("tr"))j=h.attr("data-id");else{j=c(".property-value:first",h);j=j.attr("data-id")||
j.attr("data-value")||j.attr("datetime")}c.ajax(c.extend(b.default_begin_ajax_options(),{url:g.options.base_ajax_url+"/value_edit_begin.ajax",data:{s:g.options.id,p:e.attr("data-id"),replace:j,lang:g.options.lang},onsuccess:function(i){i=c(i.result.html);var k=i.metadata(),l=k.expected_type.id;return l==="/common/document"?f.value_edit_document(e,h,i,k):l==="/common/image"?f.value_edit_image(e,h,i,k):f.value_edit(e,h,i,k)}}))},value_edit:function(e,h,j,i){var k=c(".edit-row-head",j),l=c(".edit-row",
j);j=c(".edit-row-submit",j);i={event_prefix:"propbox.edit.value_edit.",init:f.init_value_edit_form,validate:f.validate_value_edit_form,submit:f.submit_value_edit_form,ajax:{url:g.options.base_ajax_url+"/prop_edit_submit.ajax"},row:h,head_row:k,edit_row:l,submit_row:j,structure:i};l.bind("propbox.edit.value_edit.success",function(){e.removeClass("editing")}).bind("propbox.edit.value_edit.cancel",function(){e.removeClass("editing")}).bind("propbox.edit.value_edit.delete",function(){l.trigger("propbox.edit.value_edit.cancel");
g.edit.value_delete_begin(e,h)});b.init_inline_edit_form(i)},init_value_edit_form:function(e){f.init_data_inputs(e);c(".delete",e.submit_row).click(function(){e.edit_row.trigger(e.event_prefix+"delete")});c(":input:visible:first",e.edit_row).focus()},validate_value_edit_form:function(){return true},submit_value_edit_form:function(e,h){try{var j=a.parse(e.structure,e.edit_row);h.data.o=JSON.stringify(j)}catch(i){j=c(".data-input.error",e.edit_row);if(j.length){e.edit_row.trigger(e.event_prefix+"error",
"Please specify a valid value");j.eq(0).find(":input").focus().select()}else e.edit_row.trigger(e.event_prefix+"error",i.toString());return}c.ajax(c.extend(h,{onsuccess:function(k){k=c(k.result.html);b.success_inline_edit_form(e,k);g.init_menus(k,true);c(".nicemenu-item.edit").show();g.kbs.set_next(null,k,true)},onerror:function(k){e.edit_row.trigger(e.event_prefix+"error",k)}}))},value_delete_begin:function(e,h){var j;if(h.is("tr"))j=h.attr("data-id");else{j=c(".property-value:first",h);j=j.attr("data-id")||
j.attr("data-value")||j.attr("datetime")}var i={s:g.options.id,p:e.attr("data-id"),o:j,lang:g.options.lang};c.ajax(c.extend(b.default_submit_ajax_options(),{url:g.options.base_ajax_url+"/value_delete_submit.ajax",data:i,onsuccess:function(k){var l=c(k.result.html);b.success_inline_delete(h,l,function(){c.ajax(c.extend(b.default_submit_ajax_options(),{url:g.options.base_ajax_url+"/value_delete_undo.ajax",data:i,onsuccess:function(){b.success_inline_delete_undo(l)}}))});e.removeClass("editing")}}))},
prop_add_document:function(e,h,j){j={event_prefix:"propbox.edit.prop_add_document.",init:f.init_prop_add_document_form,validate:f.validate_prop_add_document_form,submit:f.submit_prop_add_document_form,ajax:{url:g.options.base_ajax_url+"/prop_add_document_submit.ajax"},prop_section:e,form:h,structure:j};h.bind("propbox.edit.prop_add_document.cancel",function(){e.removeClass("editing")});b.init_modal_form(j)},init_prop_add_document_form:function(e){var h=c("select[name=lang]",e.form);h.change(function(){var j=
c(".lang-notice",e.form);if(this.value===g.options.lang)j.hide();else{c("strong",j).text(c("option:selected",h).text());j.show()}});c("textarea",e.form).bind("keypress",function(){e.form.trigger(e.event_prefix+"valid")}).bind("paste",function(){e.form.trigger(e.event_prefix+"valid")}).focus()},validate_prop_add_document_form:function(e){var h=c("textarea",e.form);if(c.trim(h.val())===""){e.form.trigger(e.event_prefix+"invalid");h.focus();return false}return true},submit_prop_add_document_form:function(e,
h){var j=c("textarea",e.form);h.data[j.attr("name")]=c.trim(j.val());h.data.lang=c("select[name=lang]",e.form).val();c.ajax(c.extend(h,{onsuccess:function(i){i=c(i.result.html);if(e.prop_row)e.prop_row.replaceWith(i);else{var k=c(">.data-section",e.prop_section);c("> .data-table > tbody, > .data-list",k).append(i)}d.ize(i);g.init_menus(i,true);c(".nicemenu-item.edit").show();g.kbs.set_next(null,i,true);e.form.trigger(e.event_prefix+"cancel")},onerror:function(i){e.form.trigger(e.event_prefix+"error",
i)}}))},value_edit_document:function(e,h,j,i){h={event_prefix:"propbox.edit.value_edit_document.",init:f.init_value_edit_document_form,validate:f.validate_value_edit_document_form,submit:f.submit_value_edit_document_form,ajax:{url:g.options.base_ajax_url+"/prop_add_document_submit.ajax"},prop_section:e,prop_row:h,form:j,structure:i,cant_edit:j.is(".cant-edit-document-form")};j.bind("propbox.edit.value_edit_document.cancel",function(){e.removeClass("editing")});h.cant_edit&&j.bind("propbox.edit.value_edit_document.submit",
function(){j.trigger("propbox.edit.value_edit_document.cancel");f.prop_add_begin(e)});b.init_modal_form(h)},init_value_edit_document_form:function(e){e.cant_edit?b.enable_submit(e):f.init_prop_add_document_form(e)},validate_value_edit_document_form:function(e){return e.cant_edit?true:f.validate_prop_add_document_form(e)},submit_value_edit_document_form:function(e,h){e.cant_edit||f.submit_prop_add_document_form(e,h)},prop_add_image:function(e){alert("Add image not yet implemented");e.removeClass("editing")},
value_edit_image:function(e){alert("Edit image not yet implemented");e.removeClass("editing")},init_data_inputs:function(e){c(".data-input",e.edit_row).each(function(){f.init_data_input(c(this),e)})},init_data_input:function(e,h){e.data_input({lang:g.options.lang,suggest_impl:g.options.suggest_impl,incompatible_types:g.options.incompatible_types}).bind("valid",function(){h.edit_row.trigger(h.event_prefix+"valid");var j=e.parent(".form-field"),i=j.next(".magicbox-template");if(i.length){i=c("<div>").html(i.html());
i=c(".form-field",i);j.after(i);f.init_data_input(c(".data-input",i),h)}}).bind("empty",function(){h.edit_row.trigger(h.event_prefix+"valid")}).bind("invalid",function(){h.edit_row.trigger(h.event_prefix+"invalid")}).bind("submit",function(){h.edit_row.trigger(h.event_prefix+"submit")}).bind("cancel",function(){h.edit_row.trigger(h.event_prefix+"cancel")}).bind("loading",function(){c(this).addClass("loading")}).bind("loading_complete",function(){c(this).removeClass("loading")});if(e.is(".datetime"))d.ize_datetime_input(c(":text",
e));else if(e.is(".int")||e.is(".float"))d.ize_number_input(c(":text",e))},reset_data_inputs:function(e){c(".data-input",e.edit_row).each(function(){c(this).data("$.data_input").reset()})}}})(jQuery,window.propbox,window.formlib,window.editparams,window.i18n);
(function(c,g,b,a,d,f){var e=g.collection.edit={row_edit_begin:function(h){e._row_edit_begin(h)},row_edit_init:function(h){f.ize(h.form);b.init(h.form,{id:h.row.attr("data-id"),base_ajax_url:g.h.ajax_url("lib/propbox"),base_static_url:g.h.static_url("lib/propbox"),lang:g.lang||"/lang/en",suggest_impl:g.suggest_options,incompatible_types:g.incompatible_types});c(".edit",h.form).show();c(".nicemenu",h.form).nicemenu({overlay:h.overlay.getOverlay()});var j=c(".property-value:first",h.row).text();c(".modal-nav-title").text(j).css("visibility",
"visible");j=c(".modal-nav-prev",h.form).unbind();var i=c(".modal-nav-next",h.form).unbind(),k=h.row.prev(".data-row"),l=h.row.next(".data-row");k.length?j.click(function(){e.row_edit_prev(k,h);return false}).css("visibility","visible"):j.css("visibility","hidden");l.length?i.click(function(){e.row_edit_next(l,h);return false}).css("visibility","visible"):i.css("visibility","hidden")},row_edit_prev:function(h,j){e._row_edit_begin(h,j)},row_edit_next:function(h,j){e._row_edit_begin(h,j)},_row_edit_begin:function(h,
j){var i=j!=null,k=h.attr("data-id"),l=h.parent("table").metadata().prop_structures;l=l.map(function(m){return m.id});k={s:k,p:l,lang:g.h.lang_code(g.lang||"/lang/en"),nav:i};c.ajax(c.extend(a.default_begin_ajax_options(),{url:g.h.ajax_url("lib/collection/row_edit_begin.ajax"),data:k,traditional:true,onsuccess:function(m){m=c(m.result.html);if(i){c(".modal-inner",j.form).replaceWith(m);j.row=h;e.row_edit_init(j)}else{j={event_prefix:"collection.edit.row_edit.",init:e.row_edit_init,validate:function(){return true},
submit:function(){},ajax:{},form:m,row:h};c("button[type=submit]",m).hide();m.bind("collection.edit.row_edit.cancel",function(){window.location.reload(true)});a.init_modal_form(j)}}}))}}})(jQuery,window.freebase,window.propbox,window.formlib,window.editparams,window.i18n);
