
/*
 * Copyright 2012, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Additional Licenses for Third Party components can be found here:
 * http://wiki.freebase.com/wiki/Freebase_Site_License
 *
 */
(function(a,f){var h,g,e,d,b,c,i,k,m,t,j,r,n,s,l,p,q,u,o,v,y,A,C,z;h=function(a){return new h.prototype.init(a)};"undefined"!==typeof require&&"undefined"!==typeof exports&&"undefined"!==typeof module?module.exports=h:a.Globalize=h;h.cultures={};h.prototype={constructor:h,init:function(a){this.cultures=h.cultures;this.cultureSelector=a;return this}};h.prototype.init.prototype=h.prototype;h.cultures["default"]={name:"en",englishName:"English",nativeName:"English",isRTL:!1,language:"en",numberFormat:{pattern:["-n"],
decimals:2,",":",",".":".",groupSizes:[3],"+":"+","-":"-",NaN:"NaN",negativeInfinity:"-Infinity",positiveInfinity:"Infinity",percent:{pattern:["-n %","n %"],decimals:2,groupSizes:[3],",":",",".":".",symbol:"%"},currency:{pattern:["($n)","$n"],decimals:2,groupSizes:[3],",":",",".":".",symbol:"$"}},calendars:{standard:{name:"Gregorian_USEnglish","/":"/",":":":",firstDay:0,days:{names:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),namesAbbr:"Sun Mon Tue Wed Thu Fri Sat".split(" "),
namesShort:"Su Mo Tu We Th Fr Sa".split(" ")},months:{names:"January February March April May June July August September October November December ".split(" "),namesAbbr:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec ".split(" ")},AM:["AM","am","AM"],PM:["PM","pm","PM"],eras:[{name:"A.D.",start:null,offset:0}],twoDigitYearMax:2029,patterns:{d:"M/d/yyyy",D:"dddd, MMMM dd, yyyy",t:"h:mm tt",T:"h:mm:ss tt",f:"dddd, MMMM dd, yyyy h:mm tt",F:"dddd, MMMM dd, yyyy h:mm:ss tt",M:"MMMM dd",Y:"yyyy MMMM",
S:"yyyy'-'MM'-'dd'T'HH':'mm':'ss"}}},messages:{}};h.cultures["default"].calendar=h.cultures["default"].calendars.standard;h.cultures.en=h.cultures["default"];h.cultureSelector="en";g=/^0x[a-f0-9]+$/i;e=/^[+\-]?infinity$/i;d=/^[+\-]?\d*\.?\d*(e[+\-]?\d+)?$/;b=/^\s+|\s+$/g;c=function(a,b){if(a.indexOf)return a.indexOf(b);for(var c=0,d=a.length;c<d;c++)if(a[c]===b)return c;return-1};i=function(a,b){return a.substr(a.length-b.length)===b};k=function(){var a,b,c,d,e,i=arguments[0]||{},g=1,h=arguments.length,
r=!1;"boolean"===typeof i&&(r=i,i=arguments[1]||{},g=2);for("object"!==typeof i&&!t(i)&&(i={});g<h;g++)if(null!=(a=arguments[g]))for(b in a)c=i[b],d=a[b],i!==d&&(r&&d&&(j(d)||(e=m(d)))?(e?(e=!1,c=c&&m(c)?c:[]):c=c&&j(c)?c:{},i[b]=k(r,c,d)):d!==f&&(i[b]=d));return i};m=Array.isArray||function(a){return"[object Array]"===Object.prototype.toString.call(a)};t=function(a){return"[object Function]"===Object.prototype.toString.call(a)};j=function(a){return"[object Object]"===Object.prototype.toString.call(a)};
r=function(a,b){return 0===a.indexOf(b)};n=function(a){return(a+"").replace(b,"")};s=function(a){return isNaN(a)?NaN:Math[0>a?"ceil":"floor"](a)};l=function(a,b,c){var d;for(d=a.length;d<b;d+=1)a=c?"0"+a:a+"0";return a};p=function(a,b){for(var c=0,d=!1,f=0,e=a.length;f<e;f++){var i=a.charAt(f);switch(i){case "'":d?b.push("'"):c++;d=!1;break;case "\\":d&&b.push("\\");d=!d;break;default:b.push(i),d=!1}}return c};q=function(a,b){var b=b||"F",c;c=a.patterns;var d=b.length;if(1===d){c=c[b];if(!c)throw"Invalid date format string '"+
b+"'.";b=c}else 2===d&&"%"===b.charAt(0)&&(b=b.charAt(1));return b};u=function(a,b,c){function d(a,b){var c;c=a+"";return 1<b&&c.length<b?(c=r[b-2]+c,c.substr(c.length-b,b)):c}function f(){if(h||t)return h;h=n.test(b);t=!0;return h}function e(a,b){if(o)return o[b];switch(b){case 0:return a.getFullYear();case 1:return a.getMonth();case 2:return a.getDate();default:throw"Invalid part value "+b;}}var i=c.calendar,g=i.convert;if(!b||!b.length||"i"===b){if(c&&c.name.length)if(g)c=u(a,i.patterns.F,c);else{var c=
new Date(a.getTime()),j=y(a,i.eras);c.setFullYear(A(a,i,j));c=c.toLocaleString()}else c=a.toString();return c}var j=i.eras,m="s"===b,b=q(i,b),c=[],k,r=["0","00","000"],h,t,n=/([^d]|^)(d|dd)([^d]|$)/g,l=0,s=v(),o;for(!m&&g&&(o=g.fromGregorian(a));;){k=s.lastIndex;g=s.exec(b);k=b.slice(k,g?g.index:b.length);l+=p(k,c);if(!g)break;if(l%2)c.push(g[0]);else switch(k=g[0],g=k.length,k){case "ddd":case "dddd":c.push((3===g?i.days.namesAbbr:i.days.names)[a.getDay()]);break;case "d":case "dd":h=!0;c.push(d(e(a,
2),g));break;case "MMM":case "MMMM":k=e(a,1);c.push(i.monthsGenitive&&f()?i.monthsGenitive[3===g?"namesAbbr":"names"][k]:i.months[3===g?"namesAbbr":"names"][k]);break;case "M":case "MM":c.push(d(e(a,1)+1,g));break;case "y":case "yy":case "yyyy":k=o?o[0]:A(a,i,y(a,j),m);4>g&&(k%=100);c.push(d(k,g));break;case "h":case "hh":k=a.getHours()%12;0===k&&(k=12);c.push(d(k,g));break;case "H":case "HH":c.push(d(a.getHours(),g));break;case "m":case "mm":c.push(d(a.getMinutes(),g));break;case "s":case "ss":c.push(d(a.getSeconds(),
g));break;case "t":case "tt":k=12>a.getHours()?i.AM?i.AM[0]:" ":i.PM?i.PM[0]:" ";c.push(1===g?k.charAt(0):k);break;case "f":case "ff":case "fff":c.push(d(a.getMilliseconds(),3).substr(0,g));break;case "z":case "zz":k=a.getTimezoneOffset()/60;c.push((0>=k?"+":"-")+d(Math.floor(Math.abs(k)),g));break;case "zzz":k=a.getTimezoneOffset()/60;c.push((0>=k?"+":"-")+d(Math.floor(Math.abs(k)),2)+":"+d(Math.abs(a.getTimezoneOffset()%60),2));break;case "g":case "gg":i.eras&&c.push(i.eras[y(a,j)].name);break;
case "/":c.push(i["/"]);break;default:throw"Invalid date format pattern '"+k+"'.";}}return c.join("")};var D;D=function(a,b,c){var d=c.groupSizes,f=d[0],i=1,g=Math.pow(10,b),e=Math.round(a*g)/g;isFinite(e)||(e=a);g="";g=(e+"").split(/e/i);e=1<g.length?parseInt(g[1],10):0;a=g[0];g=a.split(".");a=g[0];g=1<g.length?g[1]:"";0<e?(g=l(g,e,!1),a+=g.slice(0,e),g=g.substr(e)):0>e&&(e=-e,a=l(a,e+1,!0),g=a.slice(-e,a.length)+g,a=a.slice(0,-e));g=0<b?c["."]+(g.length>b?g.slice(0,b):l(g,b)):"";b=a.length-1;c=
c[","];for(e="";0<=b;){if(0===f||f>b)return a.slice(0,b+1)+(e.length?c+e+g:g);e=a.slice(b-f+1,b+1)+(e.length?c+e:"");b-=f;i<d.length&&(f=d[i],i++)}return a.slice(0,b+1)+c+e+g};o=function(a,b,c){if(!isFinite(a))return Infinity===a?c.numberFormat.positiveInfinity:-Infinity===a?c.numberFormat.negativeInfinity:c.numberFormat.NaN;if(!b||"i"===b)return c.name.length?a.toLocaleString():a.toString();var b=b||"D",c=c.numberFormat,d=Math.abs(a),g=-1;1<b.length&&(g=parseInt(b.slice(1),10));var f=b.charAt(0).toUpperCase(),
e;switch(f){case "D":b="n";d=s(d);-1!==g&&(d=l(""+d,g,!0));0>a&&(d="-"+d);break;case "N":e=c;case "C":e=e||c.currency;case "P":e=e||c.percent;b=0>a?e.pattern[0]:e.pattern[1]||"n";-1===g&&(g=e.decimals);d=D(d*("P"===f?100:1),g,e);break;default:throw"Bad number format specifier: "+f;}a=/n|\$|-|%/g;for(e="";;){g=a.lastIndex;f=a.exec(b);e+=b.slice(g,f?f.index:b.length);if(!f)break;switch(f[0]){case "n":e+=d;break;case "$":e+=c.currency.symbol;break;case "-":/[1-9]/.test(d)&&(e+=c["-"]);break;case "%":e+=
c.percent.symbol}}return e};v=function(){return/\/|dddd|ddd|dd|d|MMMM|MMM|MM|M|yyyy|yy|y|hh|h|HH|H|mm|m|ss|s|tt|t|fff|ff|f|zzz|zz|z|gg|g/g};y=function(a,b){if(!b)return 0;for(var c,d=a.getTime(),e=0,g=b.length;e<g;e++)if(c=b[e].start,null===c||d>=c)return e;return 0};A=function(a,b,c,d){a=a.getFullYear();!d&&b.eras&&(a-=b.eras[c].offset);return a};var E,F,G,H,w,B,x;E=function(a,b){if(100>b){var c=new Date,d=y(c),c=A(c,a,d),d=a.twoDigitYearMax,d="string"===typeof d?(new Date).getFullYear()%100+parseInt(d,
10):d,b=b+(c-c%100);b>d&&(b-=100)}return b};F=function(a,b,d){var e=a.days,g=a._upperDays;g||(a._upperDays=g=[x(e.names),x(e.namesAbbr),x(e.namesShort)]);b=B(b);d?(a=c(g[1],b),-1===a&&(a=c(g[2],b))):a=c(g[0],b);return a};G=function(a,b,d){var e=a.months,g=a.monthsGenitive||a.months,f=a._upperMonths,i=a._upperMonthsGen;f||(a._upperMonths=f=[x(e.names),x(e.namesAbbr)],a._upperMonthsGen=i=[x(g.names),x(g.namesAbbr)]);b=B(b);a=c(d?f[1]:f[0],b);0>a&&(a=c(d?i[1]:i[0],b));return a};H=function(a,b){var c=
a._parseRegExp;if(c){var d=c[b];if(d)return d}else a._parseRegExp=c={};for(var d=q(a,b).replace(/([\^\$\.\*\+\?\|\[\]\(\)\{\}])/g,"\\\\$1"),e=["^"],g=[],f=0,i=0,j=v(),k;null!==(k=j.exec(d));){var m=d.slice(f,k.index),f=j.lastIndex,i=i+p(m,e);if(i%2)e.push(k[0]);else{var m=k[0],h=m.length;switch(m){case "dddd":case "ddd":case "MMMM":case "MMM":case "gg":case "g":m="(\\D+)";break;case "tt":case "t":m="(\\D*)";break;case "yyyy":case "fff":case "ff":case "f":m="(\\d{"+h+"})";break;case "dd":case "d":case "MM":case "M":case "yy":case "y":case "HH":case "H":case "hh":case "h":case "mm":case "m":case "ss":case "s":m=
"(\\d\\d?)";break;case "zzz":m="([+-]?\\d\\d?:\\d{2})";break;case "zz":case "z":m="([+-]?\\d\\d?)";break;case "/":m="(\\/)";break;default:throw"Invalid date format pattern '"+m+"'.";}m&&e.push(m);g.push(k[0])}}p(d.slice(f),e);e.push("$");d={regExp:e.join("").replace(/\s+/g,"\\s+"),groups:g};return c[b]=d};w=function(a,b,c){return a<b||a>c};B=function(a){return a.split("\u00a0").join(" ").toUpperCase()};x=function(a){for(var b=[],c=0,d=a.length;c<d;c++)b[c]=B(a[c]);return b};C=function(a,b,c){var a=
n(a),c=c.calendar,b=H(c,b),d=RegExp(b.regExp).exec(a);if(null===d)return null;var e=b.groups,g=b=a=null,f=null,i=null,j=0,k,m=0,h=0,t=0;k=null;for(var p=!1,l=0,s=e.length;l<s;l++){var q=d[l+1];if(q){var o=e[l],u=o.length,v=parseInt(q,10);switch(o){case "dd":case "d":f=v;if(w(f,1,31))return null;break;case "MMM":case "MMMM":g=G(c,q,3===u);if(w(g,0,11))return null;break;case "M":case "MM":g=v-1;if(w(g,0,11))return null;break;case "y":case "yy":case "yyyy":b=4>u?E(c,v):v;if(w(b,0,9999))return null;break;
case "h":case "hh":j=v;12===j&&(j=0);if(w(j,0,11))return null;break;case "H":case "HH":j=v;if(w(j,0,23))return null;break;case "m":case "mm":m=v;if(w(m,0,59))return null;break;case "s":case "ss":h=v;if(w(h,0,59))return null;break;case "tt":case "t":p=c.PM&&(q===c.PM[0]||q===c.PM[1]||q===c.PM[2]);if(!p&&(!c.AM||q!==c.AM[0]&&q!==c.AM[1]&&q!==c.AM[2]))return null;break;case "f":case "ff":case "fff":t=v*Math.pow(10,3-u);if(w(t,0,999))return null;break;case "ddd":case "dddd":i=F(c,q,3===u);if(w(i,0,6))return null;
break;case "zzz":o=q.split(/:/);if(2!==o.length)return null;k=parseInt(o[0],10);if(w(k,-12,13))return null;o=parseInt(o[1],10);if(w(o,0,59))return null;k=60*k+(r(q,"-")?-o:o);break;case "z":case "zz":k=v;if(w(k,-12,13))return null;k*=60;break;case "g":case "gg":if(!q||!c.eras)return null;q=n(q.toLowerCase());o=0;for(u=c.eras.length;o<u;o++)if(q===c.eras[o].name.toLowerCase()){a=o;break}if(null===a)return null}}}d=new Date;e=(l=c.convert)?l.fromGregorian(d)[0]:d.getFullYear();null===b?b=e:c.eras&&
(b+=c.eras[a||0].offset);null===g&&(g=0);null===f&&(f=1);if(l){if(d=l.toGregorian(b,g,f),null===d)return null}else if(d.setFullYear(b,g,f),d.getDate()!==f||null!==i&&d.getDay()!==i)return null;p&&12>j&&(j+=12);d.setHours(j,m,h,t);null!==k&&(c=d.getMinutes()-(k+d.getTimezoneOffset()),d.setHours(d.getHours()+parseInt(c/60,10),c%60));return d};z=function(a,b,c){var d=b["-"],b=b["+"],e;switch(c){case "n -":d=" "+d,b=" "+b;case "n-":i(a,d)?e=["-",a.substr(0,a.length-d.length)]:i(a,b)&&(e=["+",a.substr(0,
a.length-b.length)]);break;case "- n":d+=" ",b+=" ";case "-n":r(a,d)?e=["-",a.substr(d.length)]:r(a,b)&&(e=["+",a.substr(b.length)]);break;case "(n)":r(a,"(")&&i(a,")")&&(e=["-",a.substr(1,a.length-2)])}return e||["",a]};h.prototype.findClosestCulture=function(a){return h.findClosestCulture.call(this,a)};h.prototype.format=function(a,b,c){return h.format.call(this,a,b,c)};h.prototype.localize=function(a,b){return h.localize.call(this,a,b)};h.prototype.parseInt=function(a,b,c){return h.parseInt.call(this,
a,b,c)};h.prototype.parseFloat=function(a,b,c){return h.parseFloat.call(this,a,b,c)};h.prototype.culture=function(a){return h.culture.call(this,a)};h.addCultureInfo=function(a,b,c){var d={},e=!1;"string"!==typeof a?(c=a,a=this.culture().name,d=this.cultures[a]):"string"!==typeof b?(c=b,e=null==this.cultures[a],d=this.cultures[a]||this.cultures["default"]):(e=!0,d=this.cultures[b]);this.cultures[a]=k(!0,{},d,c);e&&(this.cultures[a].calendar=this.cultures[a].calendars.standard)};h.findClosestCulture=
function(a){var b;if(!a)return this.findClosestCulture(this.cultureSelector)||this.cultures["default"];"string"===typeof a&&(a=a.split(","));if(m(a)){var c,d=this.cultures,e=a,g,f=e.length,i=[];for(g=0;g<f;g++)a=n(e[g]),a=a.split(";"),c=n(a[0]),1===a.length?a=1:(a=n(a[1]),0===a.indexOf("q=")?(a=a.substr(2),a=parseFloat(a),a=isNaN(a)?0:a):a=1),i.push({lang:c,pri:a});i.sort(function(a,b){return a.pri<b.pri?1:a.pri>b.pri?-1:0});for(g=0;g<f;g++)if(c=i[g].lang,b=d[c])return b;for(g=0;g<f;g++){c=i[g].lang;
do{e=c.lastIndexOf("-");if(-1===e)break;c=c.substr(0,e);if(b=d[c])return b}while(1)}for(g=0;g<f;g++){c=i[g].lang;for(var j in d)if(e=d[j],e.language==c)return e}}else if("object"===typeof a)return a;return b||null};h.format=function(a,b,c){c=this.findClosestCulture(c);a instanceof Date?a=u(a,b,c):"number"===typeof a&&(a=o(a,b,c));return a};h.localize=function(a,b){return this.findClosestCulture(b).messages[a]||this.cultures["default"].messages[a]};h.parseDate=function(a,b,c){var c=this.findClosestCulture(c),
d,e;if(b){if("string"===typeof b&&(b=[b]),b.length){e=0;for(var g=b.length;e<g;e++){var f=b[e];if(f&&(d=C(a,f,c)))break}}}else for(e in b=c.calendar.patterns,b)if(d=C(a,b[e],c))break;return d||null};h.parseInt=function(a,b,c){return s(h.parseFloat(a,b,c))};h.parseFloat=function(a,b,c){"number"!==typeof b&&(c=b,b=10);var f=this.findClosestCulture(c),c=NaN,i=f.numberFormat;-1<a.indexOf(f.numberFormat.currency.symbol)&&(a=a.replace(f.numberFormat.currency.symbol,""),a=a.replace(f.numberFormat.currency["."],
f.numberFormat["."]));a=n(a);if(e.test(a))c=parseFloat(a);else if(!b&&g.test(a))c=parseInt(a,16);else{f=z(a,i,i.pattern[0]);b=f[0];f=f[1];""===b&&"(n)"!==i.pattern[0]&&(f=z(a,i,"(n)"),b=f[0],f=f[1]);""===b&&"-n"!==i.pattern[0]&&(f=z(a,i,"-n"),b=f[0],f=f[1]);var b=b||"+",j,a=f.indexOf("e");0>a&&(a=f.indexOf("E"));0>a?(j=f,a=null):(j=f.substr(0,a),a=f.substr(a+1));var k=i["."],m=j.indexOf(k);0>m?(f=j,j=null):(f=j.substr(0,m),j=j.substr(m+k.length));k=i[","];f=f.split(k).join("");m=k.replace(/\u00A0/g,
" ");k!==m&&(f=f.split(m).join(""));b+=f;null!==j&&(b+="."+j);null!==a&&(i=z(a,i,"-n"),b+="e"+(i[0]||"+")+i[1]);d.test(b)&&(c=parseFloat(b))}return c};h.culture=function(a){"undefined"!==typeof a&&(this.cultureSelector=a);return this.findClosestCulture(a)||this.cultures["default"]}})(this);
"JSON"in window&&window.JSON||(this.JSON||(this.JSON={}),function(){function a(a){return a<10?"0"+a:a}function f(a){e.lastIndex=0;return e.test(a)?'"'+a.replace(e,function(a){var b=c[a];return typeof b==="string"?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function h(a,c){var e,g,r,n,s=d,l,p=c[a];p&&(typeof p==="object"&&typeof p.toJSON==="function")&&(p=p.toJSON(a));typeof i==="function"&&(p=i.call(c,a,p));switch(typeof p){case "string":return f(p);case "number":return isFinite(p)?
String(p):"null";case "boolean":case "null":return String(p);case "object":if(!p)return"null";d=d+b;l=[];if(Object.prototype.toString.apply(p)==="[object Array]"){n=p.length;for(e=0;e<n;e=e+1)l[e]=h(e,p)||"null";r=l.length===0?"[]":d?"[\n"+d+l.join(",\n"+d)+"\n"+s+"]":"["+l.join(",")+"]";d=s;return r}if(i&&typeof i==="object"){n=i.length;for(e=0;e<n;e=e+1){g=i[e];if(typeof g==="string")(r=h(g,p))&&l.push(f(g)+(d?": ":":")+r)}}else for(g in p)if(Object.hasOwnProperty.call(p,g))(r=h(g,p))&&l.push(f(g)+
(d?": ":":")+r);r=l.length===0?"{}":d?"{\n"+d+l.join(",\n"+d)+"\n"+s+"}":"{"+l.join(",")+"}";d=s;return r}}if(typeof Date.prototype.toJSON!=="function"){Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null};String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()}}var g=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
e=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,d,b,c={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},i;if(typeof JSON.stringify!=="function")JSON.stringify=function(a,c,e){var g;b=d="";if(typeof e==="number")for(g=0;g<e;g=g+1)b=b+" ";else typeof e==="string"&&(b=e);if((i=c)&&typeof c!=="function"&&(typeof c!=="object"||typeof c.length!=="number"))throw Error("JSON.stringify");return h("",{"":a})};
if(typeof JSON.parse!=="function")JSON.parse=function(a,b){function c(a,d){var e,g,f=a[d];if(f&&typeof f==="object")for(e in f)if(Object.hasOwnProperty.call(f,e)){g=c(f,e);g!==void 0?f[e]=g:delete f[e]}return b.call(a,d,f)}var d,a=String(a);g.lastIndex=0;g.test(a)&&(a=a.replace(g,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){d=eval("("+a+")");return typeof b==="function"?c({"":d},""):d}throw new SyntaxError("JSON.parse");}}());
(function(a){a.factory=function(f,h){if(a.fn[f])throw"$.fn."+f+" plugin already exists";if(a[f])throw"$."+f+" class already exists";a.fn[f]=function(g){var e=null,d=null;if(a.type(g)==="string"){e=g;d=Array.prototype.slice.call(arguments,1)}return this.each(function(){var b=a(this),c=b.data("$."+f);if(e)c&&a.type(c[e])==="function"?c[e].apply(c,d):console.warn(f,"Unable to invoke method",e);else{c&&c._destroy();c=new a[f](b,g);b.data("$."+f,c)}})};a[f]=function(g,e){this.options=a.extend(true,{},
a[f].defaults,e);this.element=g;this.init()};a.extend(a[f].prototype,{init:function(){},_destroy:function(){}},h);return a[f]}})(jQuery);
(function(){var a={};$.extend({localstore:function(f,h,g,e){var d=document.location.hostname,b=document.location.protocol;if(typeof h!=="undefined"){var c=JSON.stringify(h);if(!g&&window.globalStorage)h===null?delete window.globalStorage[d][b+f]:window.globalStorage[d][b+f]=c;else if(!g&&window.localStorage&&window.localStorage.setItem)h===null?window.localStorage.removeItem(b+f):window.localStorage.setItem(b+f,c);else if(g!==false){g={};g.domain=fb.get_cookie_domain();h===null?$.cookie(f,null,g):
$.cookie(f,c,$.extend(g,e||{expires:14,path:"/"}))}else h===null?delete a[f]:a[f]=c;return h}if(!g&&window.globalStorage){if(window.globalStorage[d][b+f])h=window.globalStorage[d][b+f].value}else h=!g&&window.localStorage?window.localStorage.getItem(b+f):g!==false?$.cookie(f):a[f];return h!=""&&h!==null&&h!==void 0?JSON.parse(h,null):null}})})();
(function(a){a.extend({metadata:{defaults:{type:"class",name:"metadata",cre:/({.*})/,single:"metadata"},setType:function(a,h){this.defaults.type=a;this.defaults.name=h},get:function(f,h){var g=a.extend({},this.defaults,h);if(!g.single.length)g.single="metadata";var e=a.data(f,g.single);if(e)return e;var e="{}",d=function(a){if(typeof a!="string")return a;return a=eval("("+a+")")};if(g.type=="html5"){var b={};a(f.attributes).each(function(){var a=this.nodeName;if(a.match(/^data-/))a=a.replace(/^data-/,
"");else return true;b[a]=d(this.nodeValue)})}else{if(g.type=="class"){var c=g.cre.exec(f.className);c&&(e=c[1])}else if(g.type=="elem"){if(!f.getElementsByTagName)return;c=f.getElementsByTagName(g.name);c.length&&(e=a.trim(c[0].innerHTML))}else if(f.getAttribute!=void 0)(c=f.getAttribute(g.name))&&(e=c);b=d(e.indexOf("{")<0?"{"+e+"}":e)}a.data(f,g.single,b);return b}}});a.fn.metadata=function(f){return a.metadata.get(this[0],f)}})(jQuery);
(function(a,f){function h(g){return!a(g).parents().andSelf().filter(function(){return a.curCSS(this,"visibility")==="hidden"||a.expr.filters.hidden(this)}).length}a.ui=a.ui||{};if(!a.ui.version){a.extend(a.ui,{version:"1.8.10",keyCode:{ALT:18,BACKSPACE:8,CAPS_LOCK:20,COMMA:188,COMMAND:91,COMMAND_LEFT:91,COMMAND_RIGHT:93,CONTROL:17,DELETE:46,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,INSERT:45,LEFT:37,MENU:93,NUMPAD_ADD:107,NUMPAD_DECIMAL:110,NUMPAD_DIVIDE:111,NUMPAD_ENTER:108,NUMPAD_MULTIPLY:106,NUMPAD_SUBTRACT:109,
PAGE_DOWN:34,PAGE_UP:33,PERIOD:190,RIGHT:39,SHIFT:16,SPACE:32,TAB:9,UP:38,WINDOWS:91}});a.fn.extend({_focus:a.fn.focus,focus:function(g,e){return typeof g==="number"?this.each(function(){var d=this;setTimeout(function(){a(d).focus();e&&e.call(d)},g)}):this._focus.apply(this,arguments)},scrollParent:function(){var g;g=a.browser.msie&&/(static|relative)/.test(this.css("position"))||/absolute/.test(this.css("position"))?this.parents().filter(function(){return/(relative|absolute|fixed)/.test(a.curCSS(this,
"position",1))&&/(auto|scroll)/.test(a.curCSS(this,"overflow",1)+a.curCSS(this,"overflow-y",1)+a.curCSS(this,"overflow-x",1))}).eq(0):this.parents().filter(function(){return/(auto|scroll)/.test(a.curCSS(this,"overflow",1)+a.curCSS(this,"overflow-y",1)+a.curCSS(this,"overflow-x",1))}).eq(0);return/fixed/.test(this.css("position"))||!g.length?a(document):g},zIndex:function(g){if(g!==f)return this.css("zIndex",g);if(this.length)for(var g=a(this[0]),e;g.length&&g[0]!==document;){e=g.css("position");if(e===
"absolute"||e==="relative"||e==="fixed"){e=parseInt(g.css("zIndex"),10);if(!isNaN(e)&&e!==0)return e}g=g.parent()}return 0},disableSelection:function(){return this.bind((a.support.selectstart?"selectstart":"mousedown")+".ui-disableSelection",function(a){a.preventDefault()})},enableSelection:function(){return this.unbind(".ui-disableSelection")}});a.each(["Width","Height"],function(g,e){function d(c,d,e,g){a.each(b,function(){d=d-(parseFloat(a.curCSS(c,"padding"+this,true))||0);e&&(d=d-(parseFloat(a.curCSS(c,
"border"+this+"Width",true))||0));g&&(d=d-(parseFloat(a.curCSS(c,"margin"+this,true))||0))});return d}var b=e==="Width"?["Left","Right"]:["Top","Bottom"],c=e.toLowerCase(),i={innerWidth:a.fn.innerWidth,innerHeight:a.fn.innerHeight,outerWidth:a.fn.outerWidth,outerHeight:a.fn.outerHeight};a.fn["inner"+e]=function(b){return b===f?i["inner"+e].call(this):this.each(function(){a(this).css(c,d(this,b)+"px")})};a.fn["outer"+e]=function(b,g){return typeof b!=="number"?i["outer"+e].call(this,b):this.each(function(){a(this).css(c,
d(this,b,true,g)+"px")})}});a.extend(a.expr[":"],{data:function(g,e,d){return!!a.data(g,d[3])},focusable:function(g){var e=g.nodeName.toLowerCase(),d=a.attr(g,"tabindex");if("area"===e){e=g.parentNode;d=e.name;if(!g.href||!d||e.nodeName.toLowerCase()!=="map")return false;g=a("img[usemap=#"+d+"]")[0];return!!g&&h(g)}return(/input|select|textarea|button|object/.test(e)?!g.disabled:"a"==e?g.href||!isNaN(d):!isNaN(d))&&h(g)},tabbable:function(g){var e=a.attr(g,"tabindex");return(isNaN(e)||e>=0)&&a(g).is(":focusable")}});
a(function(){var g=document.body,e=g.appendChild(e=document.createElement("div"));a.extend(e.style,{minHeight:"100px",height:"auto",padding:0,borderWidth:0});a.support.minHeight=e.offsetHeight===100;a.support.selectstart="onselectstart"in e;g.removeChild(e).style.display="none"});a.extend(a.ui,{plugin:{add:function(g,e,d){var g=a.ui[g].prototype,b;for(b in d){g.plugins[b]=g.plugins[b]||[];g.plugins[b].push([e,d[b]])}},call:function(a,e,d){if((e=a.plugins[e])&&a.element[0].parentNode)for(var b=0;b<
e.length;b++)a.options[e[b][0]]&&e[b][1].apply(a.element,d)}},contains:function(a,e){return document.compareDocumentPosition?a.compareDocumentPosition(e)&16:a!==e&&a.contains(e)},hasScroll:function(f,e){if(a(f).css("overflow")==="hidden")return false;var d=e&&e==="left"?"scrollLeft":"scrollTop",b=false;if(f[d]>0)return true;f[d]=1;b=f[d]>0;f[d]=0;return b},isOverAxis:function(a,e,d){return a>e&&a<e+d},isOver:function(f,e,d,b,c,i){return a.ui.isOverAxis(f,d,c)&&a.ui.isOverAxis(e,b,i)}})}})(jQuery);
(function(a,f){if(a.cleanData){var h=a.cleanData;a.cleanData=function(e){for(var d=0,b;(b=e[d])!=null;d++)a(b).triggerHandler("remove");h(e)}}else{var g=a.fn.remove;a.fn.remove=function(e,d){return this.each(function(){d||(!e||a.filter(e,[this]).length)&&a("*",this).add([this]).each(function(){a(this).triggerHandler("remove")});return g.call(a(this),e,d)})}}a.widget=function(e,d,b){var c=e.split(".")[0],f,e=e.split(".")[1];f=c+"-"+e;if(!b){b=d;d=a.Widget}a.expr[":"][f]=function(b){return!!a.data(b,
e)};a[c]=a[c]||{};a[c][e]=function(a,b){arguments.length&&this._createWidget(a,b)};d=new d;d.options=a.extend(true,{},d.options);a[c][e].prototype=a.extend(true,d,{namespace:c,widgetName:e,widgetEventPrefix:a[c][e].prototype.widgetEventPrefix||e,widgetBaseClass:f},b);a.widget.bridge(e,a[c][e])};a.widget.bridge=function(e,d){a.fn[e]=function(b){var c=typeof b==="string",g=Array.prototype.slice.call(arguments,1),k=this,b=!c&&g.length?a.extend.apply(null,[true,b].concat(g)):b;if(c&&b.charAt(0)==="_")return k;
c?this.each(function(){var c=a.data(this,e),d=c&&a.isFunction(c[b])?c[b].apply(c,g):c;if(d!==c&&d!==f){k=d;return false}}):this.each(function(){var c=a.data(this,e);c?c.option(b||{})._init():a.data(this,e,new d(b,this))});return k}};a.Widget=function(a,d){arguments.length&&this._createWidget(a,d)};a.Widget.prototype={widgetName:"widget",widgetEventPrefix:"",options:{disabled:false},_createWidget:function(e,d){a.data(d,this.widgetName,this);this.element=a(d);this.options=a.extend(true,{},this.options,
this._getCreateOptions(),e);var b=this;this.element.bind("remove."+this.widgetName,function(){b.destroy()});this._create();this._trigger("create");this._init()},_getCreateOptions:function(){return a.metadata&&a.metadata.get(this.element[0])[this.widgetName]},_create:function(){},_init:function(){},destroy:function(){this.element.unbind("."+this.widgetName).removeData(this.widgetName);this.widget().unbind("."+this.widgetName).removeAttr("aria-disabled").removeClass(this.widgetBaseClass+"-disabled ui-state-disabled")},
widget:function(){return this.element},option:function(e,d){var b=e;if(arguments.length===0)return a.extend({},this.options);if(typeof e==="string"){if(d===f)return this.options[e];b={};b[e]=d}this._setOptions(b);return this},_setOptions:function(e){var d=this;a.each(e,function(a,c){d._setOption(a,c)});return this},_setOption:function(a,d){this.options[a]=d;a==="disabled"&&this.widget()[d?"addClass":"removeClass"](this.widgetBaseClass+"-disabled ui-state-disabled").attr("aria-disabled",d);return this},
enable:function(){return this._setOption("disabled",false)},disable:function(){return this._setOption("disabled",true)},_trigger:function(e,d,b){var c=this.options[e],d=a.Event(d);d.type=(e===this.widgetEventPrefix?e:this.widgetEventPrefix+e).toLowerCase();b=b||{};if(d.originalEvent)for(var e=a.event.props.length,f;e;){f=a.event.props[--e];d[f]=d.originalEvent[f]}this.element.trigger(d,b);return!(a.isFunction(c)&&c.call(this.element[0],d,b)===false||d.isDefaultPrevented())}}})(jQuery);
(function(a){a.widget("ui.mouse",{options:{cancel:":input,option",distance:1,delay:0},_mouseInit:function(){var f=this;this.element.bind("mousedown."+this.widgetName,function(a){return f._mouseDown(a)}).bind("click."+this.widgetName,function(h){if(true===a.data(h.target,f.widgetName+".preventClickEvent")){a.removeData(h.target,f.widgetName+".preventClickEvent");h.stopImmediatePropagation();return false}});this.started=false},_mouseDestroy:function(){this.element.unbind("."+this.widgetName)},_mouseDown:function(f){f.originalEvent=
f.originalEvent||{};if(!f.originalEvent.mouseHandled){this._mouseStarted&&this._mouseUp(f);this._mouseDownEvent=f;var h=this,g=f.which==1,e=typeof this.options.cancel=="string"?a(f.target).parents().add(f.target).filter(this.options.cancel).length:false;if(!g||e||!this._mouseCapture(f))return true;this.mouseDelayMet=!this.options.delay;if(!this.mouseDelayMet)this._mouseDelayTimer=setTimeout(function(){h.mouseDelayMet=true},this.options.delay);if(this._mouseDistanceMet(f)&&this._mouseDelayMet(f)){this._mouseStarted=
this._mouseStart(f)!==false;if(!this._mouseStarted){f.preventDefault();return true}}this._mouseMoveDelegate=function(a){return h._mouseMove(a)};this._mouseUpDelegate=function(a){return h._mouseUp(a)};a(document).bind("mousemove."+this.widgetName,this._mouseMoveDelegate).bind("mouseup."+this.widgetName,this._mouseUpDelegate);f.preventDefault();return f.originalEvent.mouseHandled=true}},_mouseMove:function(f){if(a.browser.msie&&!(document.documentMode>=9)&&!f.button)return this._mouseUp(f);if(this._mouseStarted){this._mouseDrag(f);
return f.preventDefault()}if(this._mouseDistanceMet(f)&&this._mouseDelayMet(f))(this._mouseStarted=this._mouseStart(this._mouseDownEvent,f)!==false)?this._mouseDrag(f):this._mouseUp(f);return!this._mouseStarted},_mouseUp:function(f){a(document).unbind("mousemove."+this.widgetName,this._mouseMoveDelegate).unbind("mouseup."+this.widgetName,this._mouseUpDelegate);if(this._mouseStarted){this._mouseStarted=false;f.target==this._mouseDownEvent.target&&a.data(f.target,this.widgetName+".preventClickEvent",
true);this._mouseStop(f)}return false},_mouseDistanceMet:function(a){return Math.max(Math.abs(this._mouseDownEvent.pageX-a.pageX),Math.abs(this._mouseDownEvent.pageY-a.pageY))>=this.options.distance},_mouseDelayMet:function(){return this.mouseDelayMet},_mouseStart:function(){},_mouseDrag:function(){},_mouseStop:function(){},_mouseCapture:function(){return true}})})(jQuery);
(function(a){a.ui=a.ui||{};var f=/left|center|right/,h=/top|center|bottom/,g=a.fn.position,e=a.fn.offset;a.fn.position=function(d){if(!d||!d.of)return g.apply(this,arguments);var d=a.extend({},d),b=a(d.of),c=b[0],e=(d.collision||"flip").split(" "),k=d.offset?d.offset.split(" "):[0,0],m,t,j;if(c.nodeType===9){m=b.width();t=b.height();j={top:0,left:0}}else if(c.setTimeout){m=b.width();t=b.height();j={top:b.scrollTop(),left:b.scrollLeft()}}else if(c.preventDefault){d.at="left top";m=t=0;j={top:d.of.pageY,
left:d.of.pageX}}else{m=b.outerWidth();t=b.outerHeight();j=b.offset()}a.each(["my","at"],function(){var a=(d[this]||"").split(" ");a.length===1&&(a=f.test(a[0])?a.concat(["center"]):h.test(a[0])?["center"].concat(a):["center","center"]);a[0]=f.test(a[0])?a[0]:"center";a[1]=h.test(a[1])?a[1]:"center";d[this]=a});e.length===1&&(e[1]=e[0]);k[0]=parseInt(k[0],10)||0;k.length===1&&(k[1]=k[0]);k[1]=parseInt(k[1],10)||0;if(d.at[0]==="right")j.left=j.left+m;else if(d.at[0]==="center")j.left=j.left+m/2;if(d.at[1]===
"bottom")j.top=j.top+t;else if(d.at[1]==="center")j.top=j.top+t/2;j.left=j.left+k[0];j.top=j.top+k[1];return this.each(function(){var b=a(this),c=b.outerWidth(),f=b.outerHeight(),g=parseInt(a.curCSS(this,"marginLeft",true))||0,h=parseInt(a.curCSS(this,"marginTop",true))||0,q=c+g+(parseInt(a.curCSS(this,"marginRight",true))||0),u=f+h+(parseInt(a.curCSS(this,"marginBottom",true))||0),o=a.extend({},j),v;if(d.my[0]==="right")o.left=o.left-c;else if(d.my[0]==="center")o.left=o.left-c/2;if(d.my[1]==="bottom")o.top=
o.top-f;else if(d.my[1]==="center")o.top=o.top-f/2;o.left=Math.round(o.left);o.top=Math.round(o.top);v={left:o.left-g,top:o.top-h};a.each(["left","top"],function(b,g){if(a.ui.position[e[b]])a.ui.position[e[b]][g](o,{targetWidth:m,targetHeight:t,elemWidth:c,elemHeight:f,collisionPosition:v,collisionWidth:q,collisionHeight:u,offset:k,my:d.my,at:d.at})});a.fn.bgiframe&&b.bgiframe();b.offset(a.extend(o,{using:d.using}))})};a.ui.position={fit:{left:function(d,b){var c=a(window),c=b.collisionPosition.left+
b.collisionWidth-c.width()-c.scrollLeft();d.left=c>0?d.left-c:Math.max(d.left-b.collisionPosition.left,d.left)},top:function(d,b){var c=a(window),c=b.collisionPosition.top+b.collisionHeight-c.height()-c.scrollTop();d.top=c>0?d.top-c:Math.max(d.top-b.collisionPosition.top,d.top)}},flip:{left:function(d,b){if(b.at[0]!=="center"){var c=a(window),c=b.collisionPosition.left+b.collisionWidth-c.width()-c.scrollLeft(),e=b.my[0]==="left"?-b.elemWidth:b.my[0]==="right"?b.elemWidth:0,f=b.at[0]==="left"?b.targetWidth:
-b.targetWidth,g=-2*b.offset[0];d.left=d.left+(b.collisionPosition.left<0?e+f+g:c>0?e+f+g:0)}},top:function(d,b){if(b.at[1]!=="center"){var c=a(window),c=b.collisionPosition.top+b.collisionHeight-c.height()-c.scrollTop(),e=b.my[1]==="top"?-b.elemHeight:b.my[1]==="bottom"?b.elemHeight:0,f=b.at[1]==="top"?b.targetHeight:-b.targetHeight,g=-2*b.offset[1];d.top=d.top+(b.collisionPosition.top<0?e+f+g:c>0?e+f+g:0)}}}};if(!a.offset.setOffset){a.offset.setOffset=function(d,b){if(/static/.test(a.curCSS(d,"position")))d.style.position=
"relative";var c=a(d),e=c.offset(),f=parseInt(a.curCSS(d,"top",true),10)||0,g=parseInt(a.curCSS(d,"left",true),10)||0,e={top:b.top-e.top+f,left:b.left-e.left+g};"using"in b?b.using.call(d,e):c.css(e)};a.fn.offset=function(d){var b=this[0];return!b||!b.ownerDocument?null:d?this.each(function(){a.offset.setOffset(this,d)}):e.call(this)}}})(jQuery);
(function(a,f){if(!("console"in window)){var h=window.console={};h.log=h.warn=h.error=h.debug=function(){}}a(function(){var b=a("<div>");a(document.body).append(b);var c=setTimeout(function(){if(a.cleanData){var b=a.cleanData;a.cleanData=function(c){for(var d=0,e;(e=c[d])!=null;d++)a(e).triggerHandler("remove");b(c)}}else{var c=a.fn.remove;a.fn.remove=function(b,d){return this.each(function(){d||(!b||a.filter(b,[this]).length)&&a("*",this).add([this]).each(function(){a(this).triggerHandler("remove")});
return c.call(a(this),b,d)})}}},1);b.bind("remove",function(){clearTimeout(c)});b.remove()});var g={key:1,filter:1,spell:1,exact:1,lang:1,scoring:1,prefixed:1,stemmed:1,format:1,mql_output:1,output:1};a.suggest=function(b,c){a.fn[b]=function(c){this.length||console.warn("Suggest: invoked on empty element set");return this.each(function(){this.nodeName&&(this.nodeName.toUpperCase()==="INPUT"?this.type&&this.type.toUpperCase()!=="TEXT"&&console.warn("Suggest: unsupported INPUT type: "+this.type):console.warn("Suggest: unsupported DOM element: "+
this.nodeName));var d=a.data(this,b);d&&d._destroy();a.data(this,b,new a.suggest[b](this,c))._init()})};a.suggest[b]=function(c,d){var e=this,f=this.options=a.extend(true,{},a.suggest.defaults,a.suggest[b].defaults,d),j=f.css_prefix=f.css_prefix||"",h=f.css;this.name=b;a.each(h,function(a){h[a]=j+h[a]});f.ac_param={};a.each(g,function(a){var b=f[a];b===null||b===""||(f.ac_param[a]=b)});f.flyout_lang=null;if(f.ac_param.lang){var n=f.ac_param.lang;a.isArray(n)&&n.length&&(n=n.join(","));if(n)f.flyout_lang=
n}this._status={START:"",LOADING:"",SELECT:"",ERROR:""};if(f.status&&f.status instanceof Array&&f.status.length>=3){this._status.START=f.status[0]||"";this._status.LOADING=f.status[1]||"";this._status.SELECT=f.status[2]||"";if(f.status.length===4)this._status.ERROR=f.status[3]||""}var n=this.status=a('<div style="display:none;">').addClass(h.status),s=this.list=a("<ul>").addClass(h.list),l=this.pane=a('<div style="display:none;" class="fbs-reset">').addClass(h.pane);l.append(n).append(s);if(f.parent)a(f.parent).append(l);
else{l.css("position","absolute");f.zIndex&&l.css("z-index",f.zIndex);a(document.body).append(l)}l.bind("mousedown",function(a){e.input.data("dont_hide",true);a.stopPropagation()}).bind("mouseup",function(a){e.input.data("dont_hide")&&e.input.focus();e.input.removeData("dont_hide");a.stopPropagation()}).bind("click",function(a){a.stopPropagation();if(a=e.get_selected()){e.onselect(a,true);e.hide_all()}});s.hover(function(a){e.hoverover_list(a)},function(a){e.hoverout_list(a)});this.input=a(c).attr("autocomplete",
"off").unbind(".suggest").bind("remove.suggest",function(){e._destroy()}).bind("keydown.suggest",function(a){e.keydown(a)}).bind("keypress.suggest",function(a){e.keypress(a)}).bind("keyup.suggest",function(a){e.keyup(a)}).bind("blur.suggest",function(a){e.blur(a)}).bind("textchange.suggest",function(){e.textchange()}).bind("focus.suggest",function(a){e.focus(a)}).bind(a.browser.msie?"paste.suggest":"input.suggest",function(){clearTimeout(e.paste_timeout);e.paste_timeout=setTimeout(function(){e.textchange()},
0)});this.onresize=function(){e.invalidate_position();if(l.is(":visible")){e.position();if(f.flyout&&e.flyoutpane&&e.flyoutpane.is(":visible")){var a=e.get_selected();a&&e.flyout_position(a)}}};a(window).bind("resize.suggest",this.onresize).bind("scroll.suggest",this.onresize)};a.suggest[b].prototype=a.extend({},a.suggest.prototype,c)};a.suggest.prototype={_init:function(){},_destroy:function(){this.pane.remove();this.list.remove();this.input.unbind(".suggest");a(window).unbind("resize.suggest",this.onresize).unbind("scroll.suggest",
this.onresize);this.input.removeData("data.suggest")},invalidate_position:function(){self._position=null},status_start:function(){this.hide_all();this.status.siblings().hide();if(this._status.START){this.status.text(this._status.START).show();if(!this.pane.is(":visible")){this.position();this.pane_show()}}this._status.LOADING&&this.status.removeClass("loading")},status_loading:function(){this.status.siblings().show();if(this._status.LOADING){this.status.addClass("loading").text(this._status.LOADING).show();
if(!this.pane.is(":visible")){this.position();this.pane_show()}}else this.status.hide()},status_select:function(){this.status.siblings().show();this._status.SELECT?this.status.text(this._status.SELECT).show():this.status.hide();this._status.LOADING&&this.status.removeClass("loading")},status_error:function(){this.status.siblings().show();this._status.ERROR?this.status.text(this._status.ERROR).show():this.status.hide();this._status.LOADING&&this.status.removeClass("loading")},focus:function(a){this.input.val()===
""?this.status_start():this.focus_hook(a)},focus_hook:function(){if(!this.input.data("data.suggest")&&!this.pane.is(":visible")&&a("."+this.options.css.item,this.list).length){this.position();this.pane_show()}},keydown:function(a){var c=a.keyCode;if(c===9)this.tab(a);else if(c===38||c===40)a.shiftKey||a.preventDefault()},keypress:function(a){var c=a.keyCode;c===38||c===40?a.shiftKey||a.preventDefault():c===13&&this.enter(a)},keyup:function(b){var c=b.keyCode;if(c===38){b.preventDefault();this.up(b)}else if(c===
40){b.preventDefault();this.down(b)}else if(b.ctrlKey&&c===77)a(".fbs-more-link",this.pane).click();else if(a.suggest.is_char(b)){clearTimeout(this.keypress.timeout);var d=this;this.keypress.timeout=setTimeout(function(){d.textchange()},0)}else c===27&&this.escape(b);return true},blur:function(){if(!this.input.data("dont_hide")){this.input.data("data.suggest");this.hide_all()}},tab:function(b){if(!b.shiftKey&&!b.metaKey&&!b.ctrlKey){var b=this.options,b=this.pane.is(":visible")&&a("."+b.css.item,
this.list).length,c=this.get_selected();if(b&&c){this.onselect(c);this.hide_all()}}},enter:function(b){var c=this.options;if(this.pane.is(":visible")){if(b.shiftKey){this.shift_enter(b);b.preventDefault();return}if(a("."+c.css.item,this.list).length){var d=this.get_selected();if(d){this.onselect(d);this.hide_all();b.preventDefault();return}if(!c.soft){this.input.data("data.suggest");if(a("."+this.options.css.item+":visible",this.list).length){this.updown(false);b.preventDefault();return}}}}c.soft?
this.soft_enter():b.preventDefault()},soft_enter:function(){},shift_enter:function(){},escape:function(){this.hide_all()},up:function(a){this.updown(true,a.ctrlKey||a.shiftKey)},down:function(a){this.updown(false,null,a.ctrlKey||a.shiftKey)},updown:function(b,c,d){var e=this.options.css,f=this.list;if(this.pane.is(":visible")){var g=a("."+e.item+":visible",f);if(g.length){var f=a(g[0]),g=a(g[g.length-1]),j=this.get_selected()||[];clearTimeout(this.ignore_mouseover.timeout);this._ignore_mouseover=
false;if(b)if(c)this._goto(f);else if(j.length)if(j[0]==f[0]){f.removeClass(e.selected);this.input.val(this.input.data("original.suggest"));this.hoverout_list()}else{b=j.prevAll("."+e.item+":visible:first");this._goto(b)}else this._goto(g);else if(d)this._goto(g);else if(j.length)if(j[0]==g[0]){g.removeClass(e.selected);this.input.val(this.input.data("original.suggest"));this.hoverout_list()}else{b=j.nextAll("."+e.item+":visible:first");this._goto(b)}else this._goto(f)}}else b||this.textchange()},
_goto:function(a){a.trigger("mouseover.suggest");var c=a.data("data.suggest");this.input.val(c?c.name:this.input.data("original.suggest"));this.scroll_to(a)},scroll_to:function(a){var c=this.list,d=c.scrollTop(),e=d+c.innerHeight(),f=a.outerHeight(),a=a.prevAll().length*f,f=a+f;if(a<d){this.ignore_mouseover();c.scrollTop(a)}else if(f>e){this.ignore_mouseover();c.scrollTop(d+f-e)}},textchange:function(){this.input.removeData("data.suggest");this.input.trigger("fb-textchange",this);var a=this.input.val();
if(a==="")this.status_start();else{this.status_loading();this.request(a)}},request:function(){},response:function(b){if(b){"cost"in b&&this.trackEvent(this.name,"response","cost",b.cost);if(this.check_response(b)){var c=[];if(a.isArray(b))c=b;else if("result"in b)c=b.result;var d=a.map(arguments,function(a){return a});this.response_hook.apply(this,d);var e=null,f=this,g=this.options;a.each(c,function(a,c){if(!c.id&&c.mid)c.id=c.mid;var d=f.create_item(c,b).bind("mouseover.suggest",function(a){f.mouseover_item(a)});
d.data("data.suggest",c);f.list.append(d);a===0&&(e=d)});this.input.data("original.suggest",this.input.val());if(a("."+g.css.item,this.list).length===0&&g.nomatch){c=a('<li class="fbs-nomatch">');if(typeof g.nomatch==="string")c.text(g.nomatch);else{g.nomatch.title&&c.append(a('<em class="fbs-nomatch-text">').text(g.nomatch.title));g.nomatch.heading&&c.append(a("<h3>").text(g.nomatch.heading));if((g=g.nomatch.tips)&&g.length){var j=a('<ul class="fbs-search-tips">');a.each(g,function(b,c){j.append(a("<li>").text(c))});
c.append(j)}}c.bind("click.suggest",function(a){a.stopPropagation()});this.list.append(c)}d.push(e);this.show_hook.apply(this,d);this.position();this.pane_show()}}},pane_show:function(){var b=false;a("> li",this.list).length&&(b=true);b||this.pane.children(":not(."+this.options.css.list+")").each(function(){if(a(this).css("display")!="none"){b=true;return false}});if(b)if(this.options.animate){var c=this;this.pane.slideDown("fast",function(){c.input.trigger("fb-pane-show",c)})}else{this.pane.show();
this.input.trigger("fb-pane-show",this)}else{this.pane.hide();this.input.trigger("fb-pane-hide",this)}},create_item:function(b){var c=this.options.css,d=a("<li>").addClass(c.item),b=a("<label>").text(b.name);d.append(a("<div>").addClass(c.item_name).append(b));return d},mouseover_item:function(b){if(!this._ignore_mouseover){b=b.target;b.nodeName.toLowerCase()!=="li"&&(b=a(b).parents("li:first"));var c=a(b),d=this.options.css;a("."+d.item,this.list).each(function(){this!==c[0]&&a(this).removeClass(d.selected)});
if(!c.hasClass(d.selected)){c.addClass(d.selected);this.mouseover_item_hook(c)}}},mouseover_item_hook:function(){},hoverover_list:function(){},hoverout_list:function(){},check_response:function(){return true},response_hook:function(){this.list.empty()},show_hook:function(){this.status_select()},position:function(){var b=this.pane,c=this.options;if(!c.parent){if(!self._position){var d=this.input,e=d.offset(),f=d.outerWidth(true),g=d.outerHeight(true);e.top=e.top+g;var j=b.outerWidth(),h=b.outerHeight(),
n=e.top+h/2,s=a(window).scrollLeft(),d=a(window).scrollTop(),l=a(window).width(),p=a(window).height()+d,q=true;"left"==c.align?q=true:"right"==c.align?q=false:e.left>s+l/2&&(q=false);if(!q){q=e.left-(j-f);if(q>s)e.left=q}if(n>p){c=e.top-g-h;if(c>d)e.top=c}this._position=e}b.css({top:this._position.top,left:this._position.left})}},ignore_mouseover:function(){this._ignore_mouseover=true;var a=this;this.ignore_mouseover.timeout=setTimeout(function(){a.ignore_mouseover_reset()},1E3)},ignore_mouseover_reset:function(){this._ignore_mouseover=
false},get_selected:function(){var b=null,c=this.options.css.selected;a("li",this.list).each(function(){var d=a(this);if(d.hasClass(c)&&d.is(":visible")){b=d;return false}});return b},onselect:function(a){var c=a.data("data.suggest");if(c){this.input.val(c.name).data("data.suggest",c).trigger("fb-select",c);this.trackEvent(this.name,"fb-select","index",a.prevAll().length)}},trackEvent:function(a,c,d,e){this.input.trigger("fb-track-event",{category:a,action:c,label:d,value:e})},hide_all:function(){this.pane.hide();
this.input.trigger("fb-pane-hide",this)}};a.extend(a.suggest,{defaults:{status:["Start typing to get suggestions...","Searching...","Select an item from the list:","Sorry, something went wrong. Please try again later"],soft:false,nomatch:"no matches",css:{pane:"fbs-pane",list:"fbs-list",item:"fbs-item",item_name:"fbs-item-name",selected:"fbs-selected",status:"fbs-status"},css_prefix:null,parent:null,animate:false,zIndex:null},strongify:function(b,c){var d,e=b.toLowerCase().indexOf(c.toLowerCase());
if(e>=0){var f=c.length;d=document.createTextNode(b.substring(0,e));var g=a("<strong>").text(b.substring(e,e+f)),e=document.createTextNode(b.substring(e+f));d=a("<div>").append(d).append(g).append(e)}else d=a("<div>").text(b);return d},keyCode:{CAPS_LOCK:20,CONTROL:17,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,INSERT:45,LEFT:37,NUMPAD_ENTER:108,PAGE_DOWN:34,PAGE_UP:33,RIGHT:39,SHIFT:16,SPACE:32,TAB:9,UP:38,OPTION:18,APPLE:224},is_char:function(b){if(b.type==="keypress"){if((b.metaKey||b.ctrlKey)&&
b.charCode===118)return true;if("isChar"in b)return b.isChar}else{var c=a.suggest.keyCode.not_char;if(!c){c={};a.each(a.suggest.keyCode,function(a,b){c[""+b]=1});a.suggest.keyCode.not_char=c}return!(""+b.keyCode in c)}},parse_input:function(b){for(var c=/(\S+)\:(?:\"([^\"]+)\"|(\S+))/g,d=b,e=[],f={},h=c.exec(b);h;){h[1]in g?f[h[1]]=a.isEmptyObject(h[2])?h[3]:h[2]:e.push(h[0]);d=d.replace(h[0],"");h=c.exec(b)}d=a.trim(d.replace(/\s+/g," "));return[d,e,f]},mqlkey_fast:/^[_A-Za-z0-9][A-Za-z0-9_-]*$/,
mqlkey_slow:/^(?:[A-Za-z0-9]|\$[A-F0-9]{4})(?:[A-Za-z0-9_-]|\$[A-F0-9]{4})*$/,check_mql_key:function(b){return a.suggest.mqlkey_fast.test(b)||a.suggest.mqlkey_slow.test(b)?true:false},check_mql_id:function(b){if(b.indexOf("/")===0){b=b.split("/");b.shift();if(!(b.length==1&&b[0]===""))for(var c=0,d=b.length;c<d;c++)if(!a.suggest.check_mql_key(b[c]))return false;return true}return false},is_system_type:function(a){return a==null?false:a.indexOf("/type/")===0}});var e=a.suggest.prototype._destroy,d=
a.suggest.prototype.show_hook;a.suggest("suggest",{_init:function(){var b=this,c=this.options;if(c.flyout_service_url==null)c.flyout_service_url=c.service_url;this.flyout_url=c.flyout_service_url;if(c.flyout_service_path)this.flyout_url=this.flyout_url+c.flyout_service_path;this.flyout_url=this.flyout_url.replace(/\$\{key\}/g,c.key);if(c.flyout_image_service_url==null)c.flyout_image_service_url=c.service_url;this.flyout_image_url=c.flyout_image_service_url;if(c.flyout_image_service_path)this.flyout_image_url=
this.flyout_image_url+c.flyout_image_service_path;this.flyout_image_url=this.flyout_image_url.replace(/\$\{key\}/g,c.key);if(!a.suggest.cache)a.suggest.cache={};if(c.flyout){this.flyoutpane=a('<div style="display:none;" class="fbs-reset">').addClass(c.css.flyoutpane);if(c.flyout_parent)a(c.flyout_parent).append(this.flyoutpane);else{this.flyoutpane.css("position","absolute");c.zIndex&&this.flyoutpane.css("z-index",c.zIndex);a(document.body).append(this.flyoutpane)}this.flyoutpane.hover(function(a){b.hoverover_list(a)},
function(a){b.hoverout_list(a)}).bind("mousedown.suggest",function(a){a.stopPropagation();b.pane.click()});if(!a.suggest.flyout)a.suggest.flyout={};if(!a.suggest.flyout.cache)a.suggest.flyout.cache={}}},_destroy:function(){e.call(this);this.flyoutpane&&this.flyoutpane.remove();this.input.removeData("request.count.suggest");this.input.removeData("flyout.request.count.suggest")},shift_enter:function(){if(this.options.suggest_new){this.suggest_new();this.hide_all()}},hide_all:function(){this.pane.hide();
this.flyoutpane&&this.flyoutpane.hide();this.input.trigger("fb-pane-hide",this);this.input.trigger("fb-flyoutpane-hide",this)},request:function(b,c){var d=this,e=this.options,f=b,g=e.ac_param.filter||[],j=null;a.type(g)==="string"&&(g=[g]);g=g.slice();if(e.advanced){var h=a.suggest.parse_input(f),f=h[0];h[1].length&&g.push("(all "+h[1].join(" ")+")");j=h[2];if(a.suggest.check_mql_id(f)){g.push('(any alias{start}:"'+f+'" mid:"'+f+'")');j.prefixed=true;f=""}}h={};h[e.query_param_name]=f;if(c)h.cursor=
c;a.extend(h,e.ac_param,j);if(g.length)h.filter=g;var n=e.service_url+e.service_path+"?"+a.param(h,true);if(f=a.suggest.cache[n])this.response(f,c?c:-1,true);else{clearTimeout(this.request.timeout);var s={url:e.service_url+e.service_path,data:h,traditional:true,beforeSend:function(){var a=d.input.data("request.count.suggest")||0;a||d.trackEvent(d.name,"start_session");a=a+1;d.trackEvent(d.name,"request","count",a);d.input.data("request.count.suggest",a)},success:function(e){a.suggest.cache[n]=e;e.prefix=
b;d.response(e,c?c:-1)},error:function(a){d.status_error();d.trackEvent(d.name,"request","error",{url:this.url,response:a?a.responseText:""});d.input.trigger("fb-error",Array.prototype.slice.call(arguments))},complete:function(a){a&&d.trackEvent(d.name,"request","tid",a.getResponseHeader("X-Metaweb-TID"))},dataType:"jsonp",cache:true};this.request.timeout=setTimeout(function(){a.ajax(s)},e.xhr_delay)}},create_item:function(b,c){var d=this.options.css,e=a("<li>").addClass(d.item),f=a("<label>").append(a.suggest.strongify(b.name||
b.id,c.prefix)),g=a("<div>").addClass(d.item_name).append(f),j=b.notable;b.under&&a(":first",f).append(a("<small>").text(" ("+b.under+")"));(j!=null&&a.suggest.is_system_type(j.id)||this.options.scoring!=null&&this.options.scoring.toUpperCase()==="SCHEMA")&&a(":first",f).append(a("<small>").text(" ("+b.id+")"));e.append(g);d=a("<div>").addClass(d.item_type);j&&j.name?d.text(j.name):this.options.show_id&&b.id&&d.text(b.id);g.prepend(d);return e},mouseover_item_hook:function(a){a=a.data("data.suggest");
this.options.flyout&&a&&this.flyout_request(a)},check_response:function(a){return a.prefix===this.input.val()},response_hook:function(b,c){this.flyoutpane&&this.flyoutpane.hide();c>0?a(".fbs-more",this.pane).remove():this.list.empty()},show_hook:function(b,c,e){d.apply(this,[b]);var f=this.options,g=this,h=this.pane,j=this.list,r=b.result,n=a(".fbs-more",h),s=a(".fbs-suggestnew",h);a(".fbs-status",h);var l=b.correction;if(l&&l.length){var p=a('<a class="fbs-spell-link" href="#">').append(l[0]).bind("click.suggest",
function(a){a.preventDefault();a.stopPropagation();g.input.val(l[0]).trigger("textchange")});g.status.empty().append("Search instead for ").append(p).show()}if(r&&r.length&&"cursor"in b){if(!n.length){r=a('<a class="fbs-more-link" href="#" title="(Ctrl+m)">view more</a>');n=a('<div class="fbs-more">').append(r);r.bind("click.suggest",function(b){b.preventDefault();b.stopPropagation();b=a(this).parent(".fbs-more");g.more(b.data("cursor.suggest"))});j.after(n)}n.data("cursor.suggest",b.cursor);n.show()}else n.remove();
if(f.suggest_new){if(!s.length){b=a('<button class="fbs-suggestnew-button">');b.text(f.suggest_new);s=a('<div class="fbs-suggestnew">').append('<div class="fbs-suggestnew-description">Your item not in the list?</div>').append(b).append('<span class="fbs-suggestnew-shortcut">(Shift+Enter)</span>').bind("click.suggest",function(a){a.stopPropagation();g.suggest_new(a)});h.append(s)}s.show()}else s.remove();if(e&&e.length&&c>0){c=e.prevAll().length*e.outerHeight();j.scrollTop();j.animate({scrollTop:c},
"slow",function(){e.trigger("mouseover.suggest")})}},suggest_new:function(){var a=this.input.val();if(a!==""){this.input.data("data.suggest",a).trigger("fb-select-new",a);this.trackEvent(this.name,"fb-select-new","index","new");this.hide_all()}},more:function(a){if(a){var c=this.input.data("original.suggest");c!==null&&this.input.val(c);this.request(this.input.val(),a);this.trackEvent(this.name,"more","cursor",a)}return false},flyout_request:function(b){var c=this,d=this.options,e=this.flyoutpane.data("data.suggest");
if(e&&b.id===e.id){if(!this.flyoutpane.is(":visible")){b=this.get_selected();this.flyout_position(b);this.flyoutpane.show();this.input.trigger("fb-flyoutpane-show",this)}}else if((e=a.suggest.flyout.cache[b.id])&&e.id&&e.html)this.flyout_response(e);else{var f=b.id,g={url:this.flyout_url.replace(/\$\{id\}/g,b.id),traditional:true,beforeSend:function(){var a=c.input.data("flyout.request.count.suggest")||0,a=a+1;c.trackEvent(c.name,"flyout.request","count",a);c.input.data("flyout.request.count.suggest",
a)},success:function(b){b["req:id"]=f;if(b.result&&b.result.length)b.html=a.suggest.suggest.create_flyout(b.result[0],c.flyout_image_url);a.suggest.flyout.cache[f]=b;c.flyout_response(b)},error:function(a){c.trackEvent(c.name,"flyout","error",{url:this.url,response:a?a.responseText:""})},complete:function(a){a&&c.trackEvent(c.name,"flyout","tid",a.getResponseHeader("X-Metaweb-TID"))},dataType:"jsonp",cache:true};if(d.flyout_lang)g.data={lang:d.flyout_lang};clearTimeout(this.flyout_request.timeout);
this.flyout_request.timeout=setTimeout(function(){a.ajax(g)},d.xhr_delay);this.input.trigger("fb-request-flyout",g)}},flyout_response:function(a){var c=this.pane,d=this.get_selected()||[];if(c.is(":visible")&&d.length)if((c=d.data("data.suggest"))&&a["req:id"]===c.id&&a.html){this.flyoutpane.html(a.html);this.flyout_position(d);this.flyoutpane.show().data("data.suggest",c);this.input.trigger("fb-flyoutpane-show",this)}},flyout_position:function(b){if(!this.options.flyout_parent){var c=this.pane,d=
this.flyoutpane,e=this.options.css,g=f,h=parseInt(d.css("top"),10),j=parseInt(d.css("left"),10),r=c.offset(),n=c.outerWidth(),s=d.outerHeight(),l=d.outerWidth();if(this.options.flyout==="bottom"){g=r;n=this.input.offset();g.top=r.top<n.top?g.top-s:g.top+c.outerHeight();d.addClass(e.flyoutpane+"-bottom")}else{g=b.offset();b=b.outerHeight();g.left=g.left+n;var p=g.left+l,c=a(document.body).scrollLeft(),q=a(window).width()+c;g.top=g.top+b-s;if(g.top<r.top)g.top=r.top;if(p>q){r=g.left-(n+l);if(r>c)g.left=
r}d.removeClass(e.flyoutpane+"-bottom")}g.top===h&&g.left===j||d.css({top:g.top,left:g.left})}},hoverout_list:function(){this.flyoutpane&&!this.get_selected()&&this.flyoutpane.hide()}});a.extend(a.suggest.suggest,{defaults:{filter:null,spell:"always",exact:false,scoring:null,lang:null,key:null,prefixed:true,stemmed:null,format:null,advanced:true,show_id:true,query_param_name:"query",service_url:"https://www.googleapis.com/freebase/v1",service_path:"/search",align:null,flyout:true,flyout_service_url:null,
flyout_service_path:"/search?filter=(all mid:${id})&output=(notable:/client/summary description type)&key=${key}",flyout_image_service_url:null,flyout_image_service_path:"/image${id}?maxwidth=75&key=${key}&errorid=/freebase/no_image_png",flyout_parent:null,suggest_new:null,nomatch:{title:"No suggested matches",heading:"Tips on getting better suggestions:",tips:["Enter more or fewer characters","Add words related to your original search","Try alternate spellings","Check your spelling"]},css:{item_type:"fbs-item-type",
flyoutpane:"fbs-flyout-pane"},xhr_delay:200},get_value:function(b,c,d){if(b==null||c==null||c.length==0)return null;a.isArray(c)||(c=[c]);var e=null;a.each(c,function(a,c){e=b[c];if(e==null)return false;b=e;return true});if(d){if(e==null)return[];a.isArray(e)||(e=[e]);var f=[];a.each(e,function(b,c){if(a.type(c)==="object")if(c.name!=null)c=c.name;else if(c.id||c.mid)c=c.id||c.mid;else if(c.value!=null){var d=[];a.each(c,function(a,b){a!=="value"&&d.push(b)});c=c.value;d.length&&(c=c+(" ("+d.join(", ")+
")"))}if(a.isArray(c)&&c.length)c=c[0].value;c!=null&&f.push(c)});return f}return e==null?null:e},is_commons_id:function(a){return/^\/base\//.test(a)||/^\/user\//.test(a)?false:true},create_flyout:function(b,c){var d=a.suggest.suggest.get_value,e=a.suggest.is_system_type,f=b.name,g=null,h=null,r=[],n=[],s={};if((g=d(b,"notable"))&&g.name){n.push(g.name);s[g.name]=true}if(g&&e(g.id))g=b.id;else{g=b.mid;h=c.replace(/\$\{id\}/g,g)}var e="freebase",l=d(b,["output","description","wikipedia"],true);l&&
l.length?e="wikipedia":l=d(b,["output","description","freebase"],true);var l=l&&l.length?l[0]:null,p=d(b,["output","notable:/client/summary"]);if(p){var q=d(p,"/common/topic/notable_paths");q&&q.length&&a.each(q,function(a,b){var c=d(p,b,true);if(c&&c.length){var e=b.split("/").pop();r.push([e,c.join(", ")])}})}(q=d(b,["output","type","/type/object/type"],true))&&q.length&&a.each(q,function(a,b){if(!s[b]){n.push(b);s[b]=true}});var u=a('<div class="fbs-flyout-content">');f&&u.append(a('<h1 id="fbs-flyout-title">').text(f));
u.append(a('<h3 class="fbs-topic-properties fbs-flyout-id">').text(g));a.each(r,function(b,c){u.append(a('<h3 class="fbs-topic-properties">').append(a("<strong>").text(c[0]+": ")).append(document.createTextNode(c[1])))});l&&u.append(a('<p class="fbs-topic-article">').append(a('<em class="fbs-citation">').text("["+e+"] ")).append(document.createTextNode(l)));if(h){u.children().addClass("fbs-flyout-image-true");u.prepend(a('<img id="fbs-topic-image" class="fbs-flyout-image-true" src="'+h+'">'))}f=a('<span class="fbs-flyout-types">').text(n.slice(0,
10).join(", "));f=a('<div class="fbs-attribution">').append(f);return a("<div>").append(u).append(f).html()}});document.createElement("input")})(jQuery);(function(a){window.freebase=window.fb={mwLWTReloading:false};window.SERVER&&typeof window.SERVER==="object"&&a.extend(window.freebase,window.SERVER);a.cookie=window.freebase.cookie})(jQuery);
(function(a,f){a.ajaxSettings.traditional=true;if(!f.datelineReloading){if(!window.console)window.console={log:a.noop,info:a.noop,debug:a.noop,warn:a.noop,error:a.noop};f.dispatch=function(b,c,d,e){if(typeof c!=="function")return false;b=a.event.fix(b||window.event);d||(d=[]);e||(e=this);return c.apply(e,[b].concat(d))};f.get_script=function(b,c){var d=f.get_script.cache,e=d[b];if(e)e.state===1?e.callbacks.push(c):e.state===4&&c();else{e=d[b]={state:0,callbacks:[c]};a.ajax({url:b,dataType:"script",
cache:true,beforeSend:function(){e.state=1},success:function(){e.state=4;a.each(e.callbacks,function(a,b){b()})},error:function(a,b,c){e.state=-1;console.error("fb.get_script error",arguments)}})}};f.get_script.cache={};a(window).bind("fb.user.signedin",function(b,c){f.user=c;var d=a("#nav-username");if(d.length){a("> a",d).text(c.name);d[0].href=d[0].href+f.user.id.substring(1);var e=f.h.image_url(c.id,{maxwidth:40,maxheight:40,mode:"fillcropmid"}),e=a('<a class="user-thumb" href="'+c.id+'"><img src="'+
e+'" /></a>');d.prepend(e)}a("#signedin").show();a(".signedin").show()}).bind("fb.user.signedout",function(){a("#signedin").hide();a("#signedout").show()}).bind("fb.user.unauthorized",function(){setTimeout(function(){a.get(f.h.ajax_url("lib/template/signout.ajax"));a(window).trigger("fb.user.signedout");f.status.clear();f.status.sprintf("info","Please %s to continue.","Sign In",function(){window.location.href=a("#fb-signin-link").attr("href");return false})})}).bind("fb.user.feedback",function(a,
b){if(confirm("Uh oh! Something went wrong. Please report this using our feedback tool."))try{userfeedback.api.startFeedback({productId:"68931",disableScrolling:false},b);return false}catch(c){}});var h=a.cookie("fb-account-name");if(h){var g={id:"/user/"+h,name:h};setTimeout(function(){a(window).trigger("fb.user.signedin",g);var b=f.h.ajax_url("lib/template/refresh_credentials"),c=a("<iframe name='rc'></iframe>").attr("src",b).hide().appendTo("body").load(function(){var d=parseInt(a("body",window.rc.document).text(),
10)-(new Date).getTime();d&&d>0&&setTimeout(function(){a(c).attr("src",b)},d)})},0)}else setTimeout(function(){a(window).trigger("fb.user.signedout")},0);f.window_position=function(){var a={};if(typeof window.innerWidth=="number"){a.width=window.outerWidth;a.height=window.outerHeight;a.top=window.screenY;a.left=window.screenX}else if(document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)){a.width=document.body.clientWidth;a.height=document.body.clientHeight;
a.top=window.screenTop;a.left=window.screenLeft}return a};var e=function(){c&&c.slideUp(300);t=null;return false},d=function(d,f,g,h){if(c===null){c=a("#page-state");i=a(".status-msg",c);k=a(".close-msg",c);k.click(e)}if(t==="error")console.warn("MessagePanel: Already displaying error. Ignoring: ",d,f);else{c.hide();a.each(b,function(a,b){c.removeClass(b)});c.addClass(d);i.text(f);t=d;window.clearTimeout(m);if(h){k.show();c.slideDown(300)}else{k.hide();c.slideDown(300);m=window.setTimeout(e,g)}}return false},
b=["notice","info","warning","success","error"],c=null,i=null,k=null,m=null,t=null;f.status={doing:function(a){return d("notice",a,2E6,false)},info:function(a,b){return d("info",a,4E3,b)},warning:function(a,b){return d("warning",a,4E3,b)},success:function(a,b){return d("success",a,6E3,b)},error:function(a,b){return d("error",a,6E3,b)},sprintf:function(b,c){var e=Array.prototype.slice.call(arguments).slice(2),f=c.split("%s");if(f.length>1&&e.length>1&&e.length%2==0){for(var g=a("<span>"),h=0,k=f.length;h<
k;h++){g.append(document.createTextNode(f[h]));var m=a('<a href="#">');m.text(e.shift());var o=e.shift();a.type(o)==="function"&&m.click(o);g.append(m)}e=d(b,"",null,true);i.empty().append(g);return e}return d(b,c,null,true)},clear:function(){window.clearTimeout(m);t==="error"?console.warn("MessagePanel: Displaying error. Ignoring clearing status."):e()}};f.popup=function(a,b,c,d){var b=b||300,c=c||300,e=f.window_position(),g=Math.floor((e.width-b)/2)+e.left,e=Math.floor((e.height-c)/2)+e.top;/chrome/.test(navigator.userAgent.toLowerCase())&&
(c=c+50);var b={width:b,height:c,top:e,left:g,directories:"no",location:"no",menubar:"no",resizable:"no",scrollbars:"yes",status:"no",toolbar:"no"},c=[],h;for(h in b)c.push(h+"="+b[h]);return window.open(a,d||"",c.join())};f.login_popup=function(a){a||(a=function(){window.location.reload()});var b=f.popup("/account/signin",900,600,"Freebase");if(b.opener==null)b.opener=self;window.onsignin=a;window.focus&&b.focus();return false};f.logout_popup=function(a){a||(a=function(){window.location.reload()});
var b=f.popup("/account/signout",900,600,"Freebase");if(b.opener==null)b.opener=self;window.onsignout=a;window.focus&&b.focus();return false};a(function(){var b=a("#header > #nav-utilities > .language-picker"),c=a(".current-lang",b);a("select",b).bind("change",function(){var b=a(this).find(":selected").text();c.text(b)})});a(function(){f.suggest_lang={SUPPORTED:{en:1,es:1,fr:1,de:1,it:1,pt:1,zh:1,ja:1,ko:1,ru:1,sv:1,fi:1,da:1,nl:1,el:1,ro:1,tr:1,hu:1},lang:function(a){a=f.h.lang_code(a||f.lang||"/lang/en");
return f.suggest_lang.SUPPORTED[a]&&a!=="en"?a+",en":"en"}};var b=f,c=f.h.fb_googleapis_url(),d=f.acre.freebase.api_key,e,g=[];a.each(f.suggest_lang.lang().split(","),function(a,b){g.push("s/"+b+",d/"+b)});g.push("s/all,d/all");e=g.join(",");b.suggest_options={service_defaults:{status:["","Searching...","Select an item from the list:"],service_url:c,key:d,lang:e},filter:{operator:function(){var a=Array.prototype.slice.call(arguments),b=a.shift();if(!(b==="any"||b==="all"||b==="should"))throw"Invalid search operator: "+
b;var c=[b];if(b==="should"&&a.length>1){a=["any"].concat(a);c.push(f.suggest_options.filter.operator.apply(null,a))}else c=c.concat(a);return"("+c.join(" ")+")"},any:function(){var a=Array.prototype.slice.call(arguments);a.unshift("any");return f.suggest_options.filter.operator.apply(null,a)},all:function(){var a=Array.prototype.slice.call(arguments);a.unshift("all");return f.suggest_options.filter.operator.apply(null,a)},should:function(){var a=Array.prototype.slice.call(arguments);a.unshift("should");
return f.suggest_options.filter.operator.apply(null,a)}},any:function(){var b=a.extend({},f.suggest_options.service_defaults);b.filter=f.suggest_options.filter.any.apply(null,arguments);return b},all:function(){var b=a.extend({},f.suggest_options.service_defaults);b.filter=f.suggest_options.filter.all.apply(null,arguments);return b},should:function(){var b=a.extend({},f.suggest_options.service_defaults);b.filter=f.suggest_options.filter.should.apply(null,arguments);return b},search:function(b){var c=
a.extend({},f.suggest_options.service_defaults,{status:null,parent:"#site-search-box",align:"right",filter:["(not type:/common/document)"],soft:true,nomatch:{title:"No suggested matches",heading:"Tips on getting better suggestions:",tips:["Enter more or fewer characters","Add words related to your original search","Try alternate spellings","Check your spelling","Toggle checkbox to include non-topics"]}});b&&c.filter.push("(any type:/common/topic)");return c},instance:function(b,c,d,e,g){var h=["type:"+
b];a.each(["user","domain","type"],function(a,c){if(b==="/freebase/"+c+"_profile"){h.push("type:/type/"+c);return false}});b==="/book/book_subject"&&h.push("type:/base/skosbase/skos_concept");var i=null;if(f.h.is_metaweb_system_type(b)||e)i=f.suggest_options.any.apply(null,h);else{i=f.suggest_options.should.apply(null,h);if(c)i.suggest_new="Create new"}if(d)i.lang=f.suggest_lang.lang(d);i.filter=[i.filter,"(all namespace:/m)"];g&&i.filter.push('(not mid:"'+g+'")');return i},cotype:function(){return a.extend({scoring:"schema"},
f.suggest_options.all.apply(null,["type:/type/type","namespace:/m","(not namespace:/type)","(not namespace:/freebase)","(any (not namespace:/common) (any mid:/m/01c5 mid:/m/02_1_m4 mid:/m/03hc3d_))"]))},included_type:function(){return f.suggest_options.cotype()},expected_type:function(){return a.extend({scoring:"schema"},f.suggest_options.all.apply(null,["type:/type/type","namespace:/m"]))},delegate_property:function(){return a.extend({scoring:"schema"},f.suggest_options.all.apply(null,["type:/type/property",
"(not namespace:/type/object)","namespace:/m"]))}}});a(function(){function b(){var c=a.localstore("fb-search-topic-only")!==false;d.suggest(f.suggest_options.search(c))}function c(){if(!d.data("dont_hide")&&!k.is(":visible")&&g.is(":visible")){h.hide();a("#site-search-label").slideUp("fast");e.removeClass("active")}}var d=a("#fb-search-input"),e=a("#fb-search"),g=a("#site-search-label"),h=a("#site-search-topic-option").mousedown(function(){d.data("dont_hide",true)}).mouseup(function(){d.data("dont_hide",
false)}),i=a(":checkbox",h).change(function(){var c=a(this).is(":checked");a.localstore("fb-search-topic-only",!c);b();d.focus().trigger("textchange")});a.localstore("fb-search-topic-only")===false&&i.attr("checked","checked");b();var k=a("#site-search-box .fbs-pane");d.bind("fb-select",function(b,c){var d={};a(this).siblings("input[type=hidden]").each(function(){d[this.name]=this.value});var e;e=c.id;e=e.indexOf("/en/")==0?c.mid||e:c.notable&&f.h.is_metaweb_system_type(c.notable.id)?e:c.mid||e;window.location.href=
f.h.fb_url(e,d);return false}).bind("fb-pane-show",function(){g.html("<span>Select an item from the list</span>").removeClass("loading");h.show()}).bind("fb-textchange",function(){a.trim(d.val())===""?g.html("<span>Start typing to get some suggestions</span>").removeClass("loading"):g.html("<span>Searching...</span>").addClass("loading");h.hide()}).bind("fb-error",function(){g.html("<span>Sorry, something went wrong. Please try again later</span>").removeClass("loading");h.hide()}).focus(function(){if(!g.is(":visible")){a("#site-search-label").slideDown("fast");
e.addClass("active")}}).blur(function(){setTimeout(c,0)});d.parent("form").submit(function(){i.is(":checked")||a(this).append('<input type="hidden" name="any" value="/common/topic">');return true})});f.disable=function(b){a(b).attr("disabled","disabled").addClass("disabled")};f.enable=function(b){a(b).removeAttr("disabled").removeClass("disabled")};f.lang_select=function(b,c){if(c==="/lang/en"){a(this).removeAttr("name");if(!a(":input[name]",this.form).length){window.location=a(this.form).attr("action");
return}}this.form.submit()};f.devbar={div:a("#devbar"),touch:function(){/\.(freebase|sandbox\-freebase)\.com$/.test(f.acre.request.server_name)?a.ajax({url:f.acre.freebase.googleapis_url?f.h.fb_googleapis_url("/touch"):f.h.fb_api_url("/api/service/touch"),dataType:"jsonp"}):a.ajax({url:"/acre/touch"});return false},txn_ids:[],txn:function(){return f.devbar.view_txn(this.href,f.devbar.txn_ids)},view_txn:function(b,c){if(c&&c.length)window.location=b+"?"+a.param({tid:c},true);return false},ajaxComplete:function(a){if(a&&
a.readyState===4)(a=a.getResponseHeader("x-metaweb-tid"))&&f.devbar.txn_ids.push(a)},init:function(){$nav_user_controls=a(".nav-user-controls");$user_controls=a("#user-controls");a("#signedin .trigger").click(function(){if($user_controls.is(":hidden")){$user_controls.fadeIn();$nav_user_controls.addClass("active")}else{$user_controls.fadeOut();$nav_user_controls.removeClass("active")}return false});a("html").click(function(){if($user_controls.is(":visible")){$user_controls.fadeOut();$nav_user_controls.removeClass("active")}});
$user_controls.click(function(a){a.stopPropagation()});a("#devbar-touch > a").click(f.devbar.touch);f.tid&&f.devbar.txn_ids.push(f.tid);a("#devbar-txn > a").click(f.devbar.txn);a.ajaxSetup({complete:function(){f.devbar.ajaxComplete.apply(null,arguments)},error:function(b){a.each(["url","data","dataType","type"],function(){});a.each(["status","statusText","responseText"],function(){});b.getAllResponseHeaders()}})}};f.devbar.init();f.mqlread=function(b,c,d){var e;if(f.acre.freebase.googleapis_url){e=
f.h.fb_googleapis_url("/mqlread");b={query:JSON.stringify(b),key:f.acre.freebase.api_key}}else{e=f.h.fb_api_url("/api/service/mqlread");b={query:JSON.stringify({query:b})}}return a.ajax({url:e,data:b,dataType:"jsonp",success:function(a){c&&c.apply(this,[a.result])},error:function(){d&&d.apply(this,arguments)}})};a(function(){var b=f,c=a("#fb-topic-hover-pane").hover(function(){clearTimeout(f.hover.hide_timer_)},function(){f.hover.hide_now_()});b.hover={pane:c,current_target:null,cache:{},search_url:f.h.fb_googleapis_url()+
"/search?filter=(all mid:${id})&output=(notable:/client/summary description type)&key="+f.acre.freebase.api_key+"&lang="+f.suggest_lang.lang(),image_url:f.h.fb_googleapis_url()+"/image${id}?maxwidth=75&errorid=/freebase/no_image_png&key="+f.acre.freebase.api_key,show:function(b){clearTimeout(f.hover.hide_timer_);var c=b.target,d=a(c).attr("data-id");if(d){f.hover.current_target=c;a(c).removeAttr("title");f.hover.cache[d]?f.hover.show_now_(c,f.hover.cache[d]):a.ajax({url:f.hover.search_url.replace(/\$\{id\}/g,
d),success:function(b){if(b.result&&b.result.length){b=a.suggest.suggest.create_flyout(b.result[0],f.hover.image_url);f.hover.cache[d]=b;f.hover.show_now_(c,b)}},dataType:"jsonp",cache:true})}},show_now_:function(b,c){if(b===f.hover.current_target){f.hover.pane.html(c);var d=f.hover.pane.height(),e=a(b).height(),g=a(b).offset(),h=g.left,g=g.top,g=g-a(document).scrollTop()+d<a(window).height()?g+e:g-d-e;f.hover.pane.css({top:g,left:h}).show()}},hide:function(){f.hover.hide_timer_=setTimeout(f.hover.hide_now_,
100)},hide_now_:function(){f.hover.current_target=null;f.hover.pane.hide()}};f.keyboard_shortcut={cache_:{},add:function(a,b,c){var d=a.charCodeAt(0);!c&&d in f.keyboard_shortcut.cache_&&console.warn("Overriding keyboard shortcut",a);f.keyboard_shortcut.cache_[d]=b}};f.on_mid_dblclick=function(a){a=a.target;if(document.body.createTextRange){var b=document.body.createTextRange();b.moveToElementText(a);b.select()}else if(window.getSelection){var c=window.getSelection(),b=document.createRange();b.selectNodeContents(a);
c.removeAllRanges();c.addRange(b)}};a(document).keypress(function(b){if(b.altKey||b.ctrlKey||b.metaKey||b.shiftKey)return true;var c=b.charCode,b=b.target;if(f.keyboard_shortcut.cache_[c]&&(b==document.body||b==document||b==window||b==a("html")[0])){f.keyboard_shortcut.cache_[c]();return false}return true});a("#page-content").on("mouseenter","a.property-value",f.hover.show).on("mouseleave","a.property-value",f.hover.hide);a(document.body).on("dblclick",".mid",f.on_mid_dblclick).on("click",".mid",
f.on_mid_dblclick)})}})(jQuery,window.freebase);
(function(a,f){var h;if(!(h=a.type)){var g={};["Boolean","Number","String","Function","Array","Date","RegExp","Object"].forEach(function(a){g["[object "+a+"]"]=a.toLowerCase()});h=function(a){return a==null?String(a):g[Object.prototype.toString.call(a)]||"object"}}var e=f.h={type:h,parse_params:function(d){if(a.isArray(d)){var b={};a.each(d,function(a,d){b[d[0]]=d[1]});return b}return d},build_url:function(d){if(d&&d.indexOf("//")!==0&&d.indexOf("://")===-1)throw"Host must contain scheme: "+d;var b=
d||"",c,g;if(arguments.length>1){c=Array.prototype.slice.call(arguments);c.shift();for(var f=[],h=0,t=c.length;h<t;h++){var j=c[h];if(e.type(j)==="string")f.push(j);else{for(g={};h<t;h++)g=a.extend(g,e.parse_params(c[h]));break}}c=f.join("")}if(c&&c.indexOf("/")!==0)throw"Path must begin with a '/': "+c;c&&(b=b+c);b===""&&(b="/");a.isEmptyObject(g)||(b=b+("?"+a.param(g,true)));return b},fb_url:function(){var a=Array.prototype.slice.call(arguments);a.unshift(null);f.lang&&f.lang!=="/lang/en"&&a.push({lang:e.lang_code(f.lang)});
return e.build_url.apply(null,a)},ajax_url:function(){var a=Array.prototype.slice.call(arguments);a.unshift("/ajax");return e.reentrant_url.apply(null,a)},static_url:function(){var a=Array.prototype.slice.call(arguments);a.unshift("/static");return e.reentrant_url.apply(null,a)},reentrant_url:function(a,b){var b=e.resolve_reentrant_path(b),b=b.replace(/^\/\//,a+"/"),c=Array.prototype.slice.call(arguments,2);c.unshift(b);c.unshift(null);return e.build_url.apply(null,c)},resolve_reentrant_path:function(a){a=
a||"";if(a.indexOf("//")==0)return a;if(a.indexOf("lib/")===0)return f.acre.current_script.app.path+a.substring(3);a&&a[0]!="/"&&(a="/"+a);return f.acre.request.script.app.path+a},legacy_fb_url:function(){var a=Array.prototype.slice.call(arguments),b=f.acre.freebase.site_host.replace(/^(https?\:\/\/)([^\.]+)\./,"$1www.").replace(":"+f.acre.request.server_port,"");a.unshift(b);return e.build_url.apply(null,a)},fb_api_url:function(){var a=Array.prototype.slice.call(arguments);a.unshift(f.acre.freebase.service_url);
return e.build_url.apply(null,a)},fb_googleapis_url:function(){if(f.acre.freebase.googleapis_url){var a=Array.prototype.slice.call(arguments);a.unshift(f.acre.freebase.googleapis_url);return e.build_url.apply(null,a)}throw"fb.acre.freebase.googleapis_url is not defined";},wiki_url:function(a){var b=Array.prototype.slice.call(arguments);b.unshift("http://wiki.freebase.com","/wiki/");return e.build_url.apply(null,b)},lib_base_url:function(a){a=f.acre.metadata.libs[a];return a.base_url+a.version},image_url:function(a,
b){return f.acre.freebase.imgurl(a,b.maxwidth,b.maxheight,b.mode,b.pad,b.errorid)},is_metaweb_system_type:function(a){return a.indexOf("/type/")===0||a.indexOf("/common/")===0&&a!=="/common/topic"||a.indexOf("/freebase/")===0&&a.indexOf("_profile")===a.length-8},id_key:function(a,b){var c=a.split("/"),e=c.pop();if(b){c=c.join("/");c===""&&(c="/");return[c,e]}return e},lang_code:function(a){return e.id_key(a)},lang_id:function(a){return"/lang/"+e.lang_code(a)}}})(jQuery,window.freebase);
(function(a,f){var h=f.permission={init:function(){if(f.access=="readonly"){a(".edit").hide();a(".no-edit").show()}else if(f.user){var g=f.c;g&&g.id&&a.ajax({url:f.h.ajax_url("lib/permission/has_permission.ajax"),data:{id:g.id,user_id:f.user.id},dataType:"json",success:function(e){h.has_permission=e.result&&e.result[g.id]===true;a(window).trigger("fb.permission.has_permission",h.has_permission)}});check_permissioned_objects(a(".edit-perm"),f.user.id)}else setTimeout(function(){h.has_permission=false;
a(window).trigger("fb.permission.has_permission",h.has_permission)})}};a(window).bind("fb.user.signedin",h.init);a(window).bind("fb.user.signedout",h.init);a(window).bind("fb.permission.has_permission",function(g,e){e?a(".edit").show():a(".no-edit").show()})})(jQuery,window.freebase);
function check_permissioned_objects(a,f){if(a.length&&f){var h={},g=[];$.each(a,function(){var a=$(this).metadata().id;if(a&&!h[a]){g.push(a);h[a]=1}});g.length&&$.ajax({url:fb.h.ajax_url("lib/permission/has_permission.ajax"),data:{id:g,user_id:f},traditional:true,dataType:"json",success:function(e){var d=e.result||{};$.each(a,function(){var a=$(this).metadata().id;a&&d[a]===true?$(this).show():$(this).addClass("edit-perm-lock")})}})}}
(function(a,f){var h=f.incompatible_types={overlay_dialog:null,inline_dialog:null,suggest_options:function(g,e,d){var d=d||{},e=[g].concat(e||[]),b=d.filter;if(!a.isArray(b)){b=[];b!=null&&b.push(d.filter);d.filter=b}b.push("(should (not incompatible:"+g+"))");d.filter=b;if(g=d.output)(b=/^\((.*)\)$/.exec(d.output))&&(g="("+h.search_output_(e)+" "+b[1]+")");g||(g=h.search_output_(e,true));d.output=g;return d},search_output_:function(a,e){var d=a.map(function(a){return"incompatible:"+a}).join(" ");
e&&(d="("+d+")");return d},check:function(g,e,d,b){var b=b||{},c=false,f=g.output;if(f){var h=[e].concat(d||[]);a.each(h,function(a,b){var d="incompatible:"+b;if(f[d]["/type/object/type"][0]==="true"||f[d]["/type/object/type"][0]===true)c=true;return!c})}c?b.incompatible&&b.incompatible(g,e,d):b.compatible&&b.compatible(g,e,d)},search:function(g,e,d,b){var c=[e].concat(d||[]),c={filter:"(all mid:"+g+")",output:h.search_output_(c,true),key:f.acre.freebase.api_key};a.ajax({url:f.h.fb_googleapis_url("/search",
c),dataType:"jsonp",success:function(c){a.isArray(c.result)&&c.result.length>0?h.check(c.result[0],e,d,b):b.compatible&&b.compatible({id:g},e,d)}})},overlay_incompatible_callback:function(g,e){if(!h.overlay_dialog)h.overlay_dialog=a(".incompatible-overlay-dialog");if(h.overlay_dialog.length){g=g||{};return function(d,b,c){h.overlay_dialog.removeData("overlay");a(".modal-content",h.overlay_dialog).empty().append(h.description_html(d,b,c));h.overlay_dialog.overlay({close:"button",closeOnClick:false,
load:true,fixed:false,mask:{color:"#000",loadSpeed:200,opacity:0.5},onClose:function(){e&&e.focus().select();a("button",h.overlay_dialog).unbind();if(g.onClose)g.onClose()},onLoad:function(){a(".cancel",h.overlay_dialog).focus().click(function(){e&&e.focus().select().trigger("textchange");if(g.onCancel)g.onCancel()});a(".save",h.overlay_dialog).click(function(){e&&e.focus().select();if(g.onConfirm)g.onConfirm(d,b,c)});if(g.onLoad)g.onLoad()}})}}return h.native_confirm_incompatible_callback(g,e)},
inline_incompatible_callback:function(g,e){if(!h.inline_dialog)h.inline_dialog=a(".incompatible-inline-dialog");if(h.inline_dialog.length){g=g||{};return function(d,b,c){a(".modal-content",h.inline_dialog).empty().append(h.description_html(d,b,c));a(".save",h.inline_dialog).unbind().click(function(){e.focus().select();if(g.onConfirm)g.onConfirm(d,b,c);h.inline_dialog.hide(g.onClose)});a(".cancel",h.inline_dialog).unbind().click(function(){e.focus().select().trigger("textchange");if(g.onCancel)g.onCancel();
h.inline_dialog.hide(g.onClose)});var f=e.offsetParent(),k=e.position();f.append(h.inline_dialog);h.inline_dialog.css({top:k.top+e.outerHeight(),left:k.left});h.inline_dialog.show(g.onLoad)}}return h.native_confirm_incompatible_callback(g,e)},native_confirm_incompatible_callback:function(a,e){a=a||{};return function(d,b,c){if(confirm(h.description_text(d,b,c))){e&&e.focus().select();if(a.onConfirm)a.onConfirm(d,b,c)}else{e&&e.focus().select().trigger("textchange");if(a.onCancel)a.onCancel()}if(a.onClose)a.onClose();
e&&e.focus().select()}},description_html:function(f,e){var d=a("<p>"),b;b=a('<div><b class="incompatible-topic"></b> is incompatible with <b class="incompatible-type"></b>.</div>');a(".incompatible-topic",b).text(f.name||f.id);a(".incompatible-type",b).text(e);d.append(b);b=a('<div>If you continue, <b class="incompatible-topic"></b> will be typed as <b class="incompatible-type"></b> and its included types (if any).</div>');a(".incompatible-topic",b).text(f.name||f.id);a(".incompatible-type",b).text(e);
d.append(b);d.append("<p>Are you sure you want to continue?<p>");return d},description_text:function(a,e,d){return h.description_html(a,e,d).text()}}})(jQuery,window.freebase);
(function(a,f){var h=f.flag={merge:function(a){return h.flag(a,"merge_begin")},split:function(a){return h.flag(a,"split_begin")},"delete":function(a){return h.flag(a,"delete_begin")},offensive:function(a){return h.flag(a,"offensive_begin")},flag:function(g,e){g=a(g);f.get_script(f.h.static_url("lib/flag/flag-edit.mf.js"),function(){h.edit[e](g)});return false},undo:function(g,e){g=a(g);f.get_script(f.h.static_url("lib/flag/flag-edit.mf.js"),function(){h.edit.undo_begin(g,e)});return false}}})(jQuery,
window.freebase);
(function(a){function f(){g();a(this).parents(".headmenu").data("submenu").find("a:first").click();return false}function h(e,d){var b=a(this),c=b.data("menu"),f=b.data("submenu");c.addClass("active");if(!f.is(".submenu-valid")){var c=b.offset(),h=b.outerHeight(),h=c.top+h;if(f.is(".center")){b=b.outerWidth();b=c.left+b/2-f.outerWidth()/2}else if(f.is(".right")){b=b.outerWidth();b=c.left+b-f.outerWidth()}else b=c.left;b={display:"none",position:"absolute",top:h,left:b};d.overlay&&(b.zIndex=d.overlay.css("zIndex"));
f.css(b);a(document.body).append(f);f.addClass(".submenu-valid")}if(f.is(":visible"))g(f);else{g();f.fadeIn()}return false}function g(e){e=e||a(".submenu:visible");e.data("menu")&&e.data("menu").removeClass("active");e.hide()}a.factory("nicemenu",{init:function(){var e=this.options;a(".headmenu",this.element).each(function(){var d=a(this),b=d.next(".submenu"),c=d.parents(".nicemenu");d.data("submenu",b);d.data("menu",c);b.data("headmenu",d);b.data("menu",c);a(".default-action",d).click(f);d.click(function(a){return h.apply(this,
[a,e])})});a(".submenu",this.element).click(function(){g(a(this));a(this).fadeOut()})}});a(document).click(function(){g()})})(jQuery);
(function(a,f){a(function(){a(".nicemenu").nicemenu();a("#description").css("height","auto");var h=a("#page-header .creation-timestamp").width();a("#page-header h1").css("margin-right",h);f.init_search();var g=function(){var a=null,c=null;if(e.is(":visible")){c=e;a=d}else{c=d;a=e}c.fadeOut();a.fadeIn(function(){setTimeout(g,6E3)})},e=a("#page-header .topics-count").first(),d=a("#page-header .topics-count").last();d.hide();setTimeout(g,6E3)});f.nav_ajax=function(h){a.getScript(h.href,function(){f.nav_ajax.begin(h)});
return false};f.init_search=function(){var f=a("#header #fb-search-input");a(document).keydown(function(a){if(f.is(":focus"))a.keyCode===27&&f.blur();else if(!(this!==event.target&&(/textarea|select/i.test(event.target.nodeName)||event.target.type==="text"))&&a.keyCode===191){f.focus();return false}})}})(jQuery,window.freebase);
