
/*
 * Copyright 2012, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Additional Licenses for Third Party components can be found here:
 * http://wiki.freebase.com/wiki/Freebase_Site_License
 *
 */
(function(e){var j="undefined"!=typeof window.innerWidth?function(){return{w:window.innerWidth,h:window.innerHeight}}:"undefined"!=typeof document.documentElement&&"undefined"!=typeof document.documentElement.clientWidth&&0!=document.documentElement.clientWidth?function(){return{w:document.documentElement.clientWidth,h:document.documentElement.clientHeight}}:function(){return{w:document.getElementsByTagName("body")[0].clientWidth,h:document.getElementsByTagName("body")[0].clientHeight}};window.kbs=
function(d){e(".kbs.current",d).removeClass("current");var b=e(".domain-section:first",d),c=e(".domain-section:last",d),f=this.scroll_to=function(a){var h=e(document).scrollTop();e(document).height();var b=j().h,b=h+b,d=a.offset().top,a=d+a.height();d<h?e(document).scrollTop(d):a>b&&e(document).scrollTop(h+(a-b))},g=this.get_current=function(){return e(".kbs.current:first",d)},i=this.set_next=function(a,h,b){a=a||g();h.length&&(a.removeClass("current"),h.addClass("current"),b||f(h))},q=this.next_domain=
function(a){var h=g(),b=m(h);b&&(b=b.find(".kbs:first"),i(h,b,a))},m=this._next_domain=function(a){if(!a||!a.length)return e(".domain-section:first",d);a=a.closest(".domain-section");return!a.length||a[0]===c[0]?b:a.next(".domain-section")},r=this.prev_domain=function(){var a=g(),h=n(a);h&&(h=h.find(".kbs:first"),i(a,h))},n=this._prev_domain=function(a){if(!a||!a.length)return e(".domain-section:last",d);var h=a.closest(".domain-section");return a.closest(".property-section").length||a.closest(".type-section").length?
h:!h.length||h[0]===b[0]?c:h.prev(".domain-section")},s=this.next_type=function(){var a=g(),h=o(a);h&&(h=h.find(".kbs:first"),i(a,h))},o=this._next_type=function(a){if(!a||!a.length)return e(".type-section:first",d);var h=a.closest(".domain-section"),a=a.closest(".type-section"),a=a.length?a.next(".type-section"):h.find(".type-section:first");if(!a||!a.length){var b=m(h);if(b)for(;b.get(0)!==h.get(0);){a=b.find(".type-section:first");if(a.length)break;b=m(b)}}return a},k=this.prev_type=function(){var a=
g(),b=l(a);b&&(b=b.find(".kbs:first"),i(a,b))},l=this._prev_type=function(a){if(!a||!a.length)return e(".type-section:last",d);var b=a.closest(".domain-section"),c=a.closest(".type-section");if(a.closest(".property-section").length)return c;var f;c.length&&(f=c.prev(".type-section"));if(!f||!f.length)if(a=n(b))for(;a.get(0)!==b.get(0);){f=a.find(".type-section:last");if(f.length)break;a=n(a)}return f},u=this.next_prop=function(){var a=g(),b=t(a);b&&(b=b.find(".kbs:first"),i(a,b))},t=this._next_prop=
function(a){if(!a||!a.length)return e(".property-section:first",d);var b=a.closest(".domain-section"),c=a.closest(".type-section"),f=a.closest(".property-section"),b=f.length?f.next(".property-section"):c.length?c.find(".property-section:first"):b.find(".property-section:first");if(!b||!b.length)if(a=o(a))for(;a.get(0)!==c.get(0);){b=a.find(".property-section:first");if(b.length)break;null==c.get(0)&&(c=a);a=o(a)}return b},w=this.prev_prop=function(){var a=g(),b=v(a);b&&(b=b.find(".kbs:first"),i(a,
b))},v=this._prev_prop=function(a){if(!a||!a.length)return e(".property-section:last",d);var b=a.closest(".domain-section"),c=a.closest(".type-section"),f=a.closest(".property-section");if(a.closest(".data-section").length)return f;var g;f.length&&(g=f.prev(".property-section"));if(!g||!g.length)if(k=c.length?l(c):l(b))for(;k.get(0)!==c.get(0);){g=k.find(".property-section:last");if(g.length)break;null==c.get(0)&&(c=k);k=l(k)}return g};this.next=function(){var a=g();if(a&&a.length){var b=this._next(a);
if(b){i(a,b);return}}a=e(".kbs:visible:first",d);i(a,a)};this._next=function(a){if(!a||!a.length)return e(".domain-section:first .kbs:first",d);var f=a.closest(".domain-section"),g=a.closest(".type-section"),i=a.closest(".property-section");if(a.closest(".data-section").length){a=a.next(".kbs");if(a.length)return a;a=i.next(".property-section").find(".kbs:first");if(a.length)return a;a=g.next(".type-section").find(".kbs:first")}else if(i.length){a=i.find(".data-section:first .kbs:first");if(a.length)return a;
a=i.next(".property-section").find(".kbs:first");if(a.length)return a;a=g.next(".type-section").find(".kbs:first")}else if(g.length){a=g.find(".property-section:first .kbs:first");if(a.length)return a;a=g.next(".type-section").find(".kbs:first")}else a=f.find(".type-section:first .kbs:first");return a.length?a:f.get(0)===c.get(0)?b.find(".kbs:first"):f.next(".domain-section").find(".kbs:first")};this.prev=function(){var a=g(),b=this._prev(a);b&&i(a,b)};this._prev=function(a){if(!a||!a.length)return a=
e(".data-section:last .kbs:last",d),a.length||(a=e(".property-section:last .kbs:first",d)),a.length||(a=e(".type-section:last .kbs:first",d)),a.length||(a=e(".domain-section:last .kbs:first",d)),a;var f=a.closest(".domain-section"),g=a.closest(".type-section"),i=a.closest(".property-section");return a.closest(".data-section").length?(a=a.prev(".kbs"),a.length?a:i.find(".kbs:first")):i.length?(a=i.prev(".property-section").find(".kbs:last"),a.length?a:g.find(".kbs:first")):g.length?(a=g.prev(".type-section").find(".kbs:last"),
a.length?a:f.find(".kbs:first")):f.get(0)===b.get(0)?c.find(".kbs:last"):f.prev(".domain-section").find(".kbs:last")};this.edit=function(){this.get_current().trigger("edit")};var p=this;e(document).unbind(".kbs").bind("keydown.kbs",function(a){var b=a.target;if(b==document.body||b==document||b==window||b==e("html")[0])b=a.keyCode,68===b?a.shiftKey?r():q():84===b?a.shiftKey?k():s():80===b?a.shiftKey?w():u():74===b?p.next():75===b?p.prev():69===b&&p.edit()})}})(jQuery);
(function(e,j){var d=window.propbox={init:function(b,c){c=e.extend({lang:"/lang/en"},c);if(!c.base_ajax_url)throw Error("base_ajax_url required in propbox options");if(!c.base_static_url)throw Error("base_static_url required in propbox options");if(!c.id)throw Error("topic id required in propbox options");if(!c.lang)throw Error("lang required in propbox options");d.options=c;d.kbs=new j(b);e(".kbs",b).live("click",function(){var b=d.kbs.get_current();d.kbs.set_next(b,e(this),!0)}).live("edit",function(){var b=
e(this).find(".headmenu:first").data("submenu");b&&e("li:first a:first",b).click()});d.init_menus(b)},init_menus:function(b,c){b=e(b||document);c&&e(".nicemenu",b).nicemenu();var f;f=b&&b.is(".hover-row")?b:e(".hover-row",b);f.hover(d.row_menu_hoverover,d.row_menu_hoverout);f.dblclick(function(){var b=e(".nicemenu .default-action",this);b.length||(b=e(".nicemenu:first .submenu:first a:first",this));var c=b.attr("href");c&&("#"==c||0==c.indexOf("javascript:void(0)"))&&e(b).click()});e(".nicemenu .headmenu",
b).add(e(".nicemenu .default-action",b)).click("click",function(){if(d.kbs){var b=d.kbs.get_current();b&&d.kbs.set_next(b,e(this).parents(".kbs:first"),!0)}return!1})},row_menu_hoverover:function(){e(this).addClass("row-hover")},row_menu_hoverout:function(){e(this).removeClass("row-hover")},get_script:function(b,c){var f=d.get_script.cache;f||(f=d.get_script.cache={});var g=f[b];g?1===g.state?g.callbacks.push(c):4===g.state&&c():(g=f[b]={state:0,callbacks:[c]},e.ajax({url:d.options.base_static_url+
b,dataType:"script",cache:!0,beforeSend:function(){g.state=1},success:function(){g.state=4;e.each(g.callbacks,function(b,c){c()})},error:function(){g.state=-1}}))},prop_edit:function(b,c){var f=e(b).parents(".property-section");f.length||(f=e(b).parents(".submenu").data("headmenu").parents(".property-section"));f=f.find(".data-section .data-row:first:visible .nicemenu:first .headmenu");f.length?f.data("submenu").find("a:first").click():d.prop_add(b,c);return!1},prop_add:function(b,c){var f=e(b).parents(".property-section");
f.length||(f=e(b).parents(".submenu").data("headmenu").parents(".property-section"));d.get_script("/propbox-edit.mf.js",function(){d.edit.prop_add_begin(f,c)});return!1},value_edit:function(b){var c=e(b).parents(".submenu").data("headmenu").parents(".data-row:first"),f=c.parents(".property-section");d.get_script("/propbox-edit.mf.js",function(){d.edit.value_edit_begin(f,c)});return!1},value_delete:function(b){var c=e(b).parents(".submenu").data("headmenu").parents(".data-row:first"),f=c.parents(".property-section");
d.get_script("/propbox-edit.mf.js",function(){d.edit.value_delete_begin(f,c)});return!1},remove_type:function(b){var b=e(b),c=b.parents(".type-section");d.get_script("/propbox-edit.mf.js",function(){d.edit.remove_type_begin(b,c)});return!1},add_type:function(b,c,f){var b=e(b),g=b.parents(".type-section"),i=d.options.incompatible_types;i?i.search(d.options.id,c,f,{compatible:function(){d.add_type_submit(b,g)},incompatible:i.overlay_incompatible_callback({onConfirm:function(){d.add_type_submit(b,g)}})}):
d.add_type_submit(b,g);return!1},add_type_submit:function(b,c){d.get_script("/propbox-edit.mf.js",function(){d.edit.add_type_submit(b,c)})},add_has_no_value:function(b){var c=e(b).parents(".submenu").data("headmenu").parents(".property-section");d.get_script("/propbox-edit.mf.js",function(){d.edit.add_has_no_value(c)});return!1},add_has_value:function(b){var c=e(b).parents(".submenu").data("headmenu").parents(".property-section");d.get_script("/propbox-edit.mf.js",function(){d.edit.add_has_value(c)});
return!1},remove_has_no_value:function(b){var c=e(b).parents(".property-section");d.get_script("/propbox-edit.mf.js",function(){d.edit.remove_has_no_value(c)});return!1},remove_has_value:function(b){var c=e(b).parents(".property-section");d.get_script("/propbox-edit.mf.js",function(){d.edit.remove_has_value(c)});return!1},more:function(b,c,f){var g=e(b).parents(".property-section");d.get_script("/propbox-edit.mf.js",function(){d.edit.more(g,c,f)})}}})(jQuery,window.kbs);
(function(e,j,d){j.schema={init_modal_help:function(b){e(".modal-help-toggle",b).click(function(){var b=e(this),d=b.parents().find(".modal-help"),g=b.parents().find(".modal-content");d.is(":hidden")?(d.height(g.height()-5).slideDown(),b.html("[ - ] Hide Help")):(d.slideUp(),b.html("[ + ] Show Help"))})}};e(function(){d.init_menus()})})(jQuery,window.freebase,window.propbox);
(function(e,j){var d=j.schema.domain={init:function(){d.init_toggle_help_messages()},init_toggle_help_messages:function(){e(".table-empty-trigger").click(function(){var b=e(this).parents(".table-empty-msg"),c=b.find(".table-empty-text");c.is(":hidden")?(b.addClass("active"),c.slideDown()):(b.removeClass("active"),c.slideUp())})},init_edit:function(){var b=e("table.table");b.first().find(".table-empty-msg").addClass("active").find(".table-empty-text").slideDown();0===b.find("tbody > tr").length?e(".table-title > .help-link").hide():
e(".table-empty-msg").hide()},add_type:function(b,c,f){var g=e(this).parents("table:first");j.get_script(j.h.static_url("domain-edit.mf.js"),function(){d.edit.add_type_begin(g,c,f)});return!1},edit_type:function(b,c){var f=e(this).parents(".submenu").data("headmenu").parents(".data-row:first");j.get_script(j.h.static_url("domain-edit.mf.js"),function(){d.edit.edit_type_begin(f,c)});return!1}};e(d.init)})(jQuery,window.freebase);
