
/*
 * Copyright 2012, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Additional Licenses for Third Party components can be found here:
 * http://wiki.freebase.com/wiki/Freebase_Site_License
 *
 */
(function(a,f){var h,d,g,e,b,c,i,t,n,j,k,p,o,r,q,s,m,v,l,w,z,u,y,B;h=function(a){return new h.prototype.init(a)};"undefined"!==typeof require&&"undefined"!==typeof exports&&"undefined"!==typeof module?module.exports=h:a.Globalize=h;h.cultures={};h.prototype={constructor:h,init:function(a){this.cultures=h.cultures;this.cultureSelector=a;return this}};h.prototype.init.prototype=h.prototype;h.cultures["default"]={name:"en",englishName:"English",nativeName:"English",isRTL:!1,language:"en",numberFormat:{pattern:["-n"],
decimals:2,",":",",".":".",groupSizes:[3],"+":"+","-":"-",NaN:"NaN",negativeInfinity:"-Infinity",positiveInfinity:"Infinity",percent:{pattern:["-n %","n %"],decimals:2,groupSizes:[3],",":",",".":".",symbol:"%"},currency:{pattern:["($n)","$n"],decimals:2,groupSizes:[3],",":",",".":".",symbol:"$"}},calendars:{standard:{name:"Gregorian_USEnglish","/":"/",":":":",firstDay:0,days:{names:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),namesAbbr:"Sun Mon Tue Wed Thu Fri Sat".split(" "),
namesShort:"Su Mo Tu We Th Fr Sa".split(" ")},months:{names:"January February March April May June July August September October November December ".split(" "),namesAbbr:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec ".split(" ")},AM:["AM","am","AM"],PM:["PM","pm","PM"],eras:[{name:"A.D.",start:null,offset:0}],twoDigitYearMax:2029,patterns:{d:"M/d/yyyy",D:"dddd, MMMM dd, yyyy",t:"h:mm tt",T:"h:mm:ss tt",f:"dddd, MMMM dd, yyyy h:mm tt",F:"dddd, MMMM dd, yyyy h:mm:ss tt",M:"MMMM dd",Y:"yyyy MMMM",
S:"yyyy'-'MM'-'dd'T'HH':'mm':'ss"}}},messages:{}};h.cultures["default"].calendar=h.cultures["default"].calendars.standard;h.cultures.en=h.cultures["default"];h.cultureSelector="en";d=/^0x[a-f0-9]+$/i;g=/^[+\-]?infinity$/i;e=/^[+\-]?\d*\.?\d*(e[+\-]?\d+)?$/;b=/^\s+|\s+$/g;c=function(a,b){if(a.indexOf)return a.indexOf(b);for(var c=0,e=a.length;c<e;c++)if(a[c]===b)return c;return-1};i=function(a,b){return a.substr(a.length-b.length)===b};t=function(){var a,b,c,e,i,g=arguments[0]||{},d=1,p=arguments.length,
h=!1;"boolean"===typeof g&&(h=g,g=arguments[1]||{},d=2);for("object"!==typeof g&&!j(g)&&(g={});d<p;d++)if(null!=(a=arguments[d]))for(b in a)c=g[b],e=a[b],g!==e&&(h&&e&&(k(e)||(i=n(e)))?(i?(i=!1,c=c&&n(c)?c:[]):c=c&&k(c)?c:{},g[b]=t(h,c,e)):e!==f&&(g[b]=e));return g};n=Array.isArray||function(a){return"[object Array]"===Object.prototype.toString.call(a)};j=function(a){return"[object Function]"===Object.prototype.toString.call(a)};k=function(a){return"[object Object]"===Object.prototype.toString.call(a)};
p=function(a,b){return 0===a.indexOf(b)};o=function(a){return(a+"").replace(b,"")};r=function(a){return isNaN(a)?NaN:Math[0>a?"ceil":"floor"](a)};q=function(a,b,c){var e;for(e=a.length;e<b;e+=1)a=c?"0"+a:a+"0";return a};s=function(a,b){for(var c=0,e=!1,f=0,g=a.length;f<g;f++){var i=a.charAt(f);switch(i){case "'":e?b.push("'"):c++;e=!1;break;case "\\":e&&b.push("\\");e=!e;break;default:b.push(i),e=!1}}return c};m=function(a,b){var b=b||"F",c;c=a.patterns;var e=b.length;if(1===e){c=c[b];if(!c)throw"Invalid date format string '"+
b+"'.";b=c}else 2===e&&"%"===b.charAt(0)&&(b=b.charAt(1));return b};v=function(a,b,c){function e(a,b){var c;c=a+"";return 1<b&&c.length<b?(c=t[b-2]+c,c.substr(c.length-b,b)):c}function f(){if(p||h)return p;p=o.test(b);h=!0;return p}function g(a,b){if(l)return l[b];switch(b){case 0:return a.getFullYear();case 1:return a.getMonth();case 2:return a.getDate();default:throw"Invalid part value "+b;}}var i=c.calendar,d=i.convert;if(!b||!b.length||"i"===b){if(c&&c.name.length)if(d)c=v(a,i.patterns.F,c);else{var c=
new Date(a.getTime()),k=z(a,i.eras);c.setFullYear(u(a,i,k));c=c.toLocaleString()}else c=a.toString();return c}var k=i.eras,n="s"===b,b=m(i,b),c=[],j,t=["0","00","000"],p,h,o=/([^d]|^)(d|dd)([^d]|$)/g,r=0,q=w(),l;for(!n&&d&&(l=d.fromGregorian(a));;){j=q.lastIndex;d=q.exec(b);j=b.slice(j,d?d.index:b.length);r+=s(j,c);if(!d)break;if(r%2)c.push(d[0]);else switch(j=d[0],d=j.length,j){case "ddd":case "dddd":c.push((3===d?i.days.namesAbbr:i.days.names)[a.getDay()]);break;case "d":case "dd":p=!0;c.push(e(g(a,
2),d));break;case "MMM":case "MMMM":j=g(a,1);c.push(i.monthsGenitive&&f()?i.monthsGenitive[3===d?"namesAbbr":"names"][j]:i.months[3===d?"namesAbbr":"names"][j]);break;case "M":case "MM":c.push(e(g(a,1)+1,d));break;case "y":case "yy":case "yyyy":j=l?l[0]:u(a,i,z(a,k),n);4>d&&(j%=100);c.push(e(j,d));break;case "h":case "hh":j=a.getHours()%12;0===j&&(j=12);c.push(e(j,d));break;case "H":case "HH":c.push(e(a.getHours(),d));break;case "m":case "mm":c.push(e(a.getMinutes(),d));break;case "s":case "ss":c.push(e(a.getSeconds(),
d));break;case "t":case "tt":j=12>a.getHours()?i.AM?i.AM[0]:" ":i.PM?i.PM[0]:" ";c.push(1===d?j.charAt(0):j);break;case "f":case "ff":case "fff":c.push(e(a.getMilliseconds(),3).substr(0,d));break;case "z":case "zz":j=a.getTimezoneOffset()/60;c.push((0>=j?"+":"-")+e(Math.floor(Math.abs(j)),d));break;case "zzz":j=a.getTimezoneOffset()/60;c.push((0>=j?"+":"-")+e(Math.floor(Math.abs(j)),2)+":"+e(Math.abs(a.getTimezoneOffset()%60),2));break;case "g":case "gg":i.eras&&c.push(i.eras[z(a,k)].name);break;
case "/":c.push(i["/"]);break;default:throw"Invalid date format pattern '"+j+"'.";}}return c.join("")};var D;D=function(a,b,c){var e=c.groupSizes,f=e[0],i=1,g=Math.pow(10,b),d=Math.round(a*g)/g;isFinite(d)||(d=a);g="";g=(d+"").split(/e/i);d=1<g.length?parseInt(g[1],10):0;a=g[0];g=a.split(".");a=g[0];g=1<g.length?g[1]:"";0<d?(g=q(g,d,!1),a+=g.slice(0,d),g=g.substr(d)):0>d&&(d=-d,a=q(a,d+1,!0),g=a.slice(-d,a.length)+g,a=a.slice(0,-d));g=0<b?c["."]+(g.length>b?g.slice(0,b):q(g,b)):"";b=a.length-1;c=
c[","];for(d="";0<=b;){if(0===f||f>b)return a.slice(0,b+1)+(d.length?c+d+g:g);d=a.slice(b-f+1,b+1)+(d.length?c+d:"");b-=f;i<e.length&&(f=e[i],i++)}return a.slice(0,b+1)+c+d+g};l=function(a,b,c){if(!isFinite(a))return Infinity===a?c.numberFormat.positiveInfinity:-Infinity===a?c.numberFormat.negativeInfinity:c.numberFormat.NaN;if(!b||"i"===b)return c.name.length?a.toLocaleString():a.toString();var b=b||"D",c=c.numberFormat,e=Math.abs(a),g=-1;1<b.length&&(g=parseInt(b.slice(1),10));var f=b.charAt(0).toUpperCase(),
d;switch(f){case "D":b="n";e=r(e);-1!==g&&(e=q(""+e,g,!0));0>a&&(e="-"+e);break;case "N":d=c;case "C":d=d||c.currency;case "P":d=d||c.percent;b=0>a?d.pattern[0]:d.pattern[1]||"n";-1===g&&(g=d.decimals);e=D(e*("P"===f?100:1),g,d);break;default:throw"Bad number format specifier: "+f;}a=/n|\$|-|%/g;for(d="";;){g=a.lastIndex;f=a.exec(b);d+=b.slice(g,f?f.index:b.length);if(!f)break;switch(f[0]){case "n":d+=e;break;case "$":d+=c.currency.symbol;break;case "-":/[1-9]/.test(e)&&(d+=c["-"]);break;case "%":d+=
c.percent.symbol}}return d};w=function(){return/\/|dddd|ddd|dd|d|MMMM|MMM|MM|M|yyyy|yy|y|hh|h|HH|H|mm|m|ss|s|tt|t|fff|ff|f|zzz|zz|z|gg|g/g};z=function(a,b){if(!b)return 0;for(var c,e=a.getTime(),d=0,g=b.length;d<g;d++)if(c=b[d].start,null===c||e>=c)return d;return 0};u=function(a,b,c,e){a=a.getFullYear();!e&&b.eras&&(a-=b.eras[c].offset);return a};var E,F,G,H,x,C,A;E=function(a,b){if(100>b){var c=new Date,e=z(c),c=u(c,a,e),e=a.twoDigitYearMax,e="string"===typeof e?(new Date).getFullYear()%100+parseInt(e,
10):e,b=b+(c-c%100);b>e&&(b-=100)}return b};F=function(a,b,e){var d=a.days,g=a._upperDays;g||(a._upperDays=g=[A(d.names),A(d.namesAbbr),A(d.namesShort)]);b=C(b);e?(a=c(g[1],b),-1===a&&(a=c(g[2],b))):a=c(g[0],b);return a};G=function(a,b,e){var d=a.months,g=a.monthsGenitive||a.months,f=a._upperMonths,i=a._upperMonthsGen;f||(a._upperMonths=f=[A(d.names),A(d.namesAbbr)],a._upperMonthsGen=i=[A(g.names),A(g.namesAbbr)]);b=C(b);a=c(e?f[1]:f[0],b);0>a&&(a=c(e?i[1]:i[0],b));return a};H=function(a,b){var c=
a._parseRegExp;if(c){var e=c[b];if(e)return e}else a._parseRegExp=c={};for(var e=m(a,b).replace(/([\^\$\.\*\+\?\|\[\]\(\)\{\}])/g,"\\\\$1"),d=["^"],g=[],f=0,i=0,k=w(),j;null!==(j=k.exec(e));){var n=e.slice(f,j.index),f=k.lastIndex,i=i+s(n,d);if(i%2)d.push(j[0]);else{var n=j[0],t=n.length;switch(n){case "dddd":case "ddd":case "MMMM":case "MMM":case "gg":case "g":n="(\\D+)";break;case "tt":case "t":n="(\\D*)";break;case "yyyy":case "fff":case "ff":case "f":n="(\\d{"+t+"})";break;case "dd":case "d":case "MM":case "M":case "yy":case "y":case "HH":case "H":case "hh":case "h":case "mm":case "m":case "ss":case "s":n=
"(\\d\\d?)";break;case "zzz":n="([+-]?\\d\\d?:\\d{2})";break;case "zz":case "z":n="([+-]?\\d\\d?)";break;case "/":n="(\\/)";break;default:throw"Invalid date format pattern '"+n+"'.";}n&&d.push(n);g.push(j[0])}}s(e.slice(f),d);d.push("$");e={regExp:d.join("").replace(/\s+/g,"\\s+"),groups:g};return c[b]=e};x=function(a,b,c){return a<b||a>c};C=function(a){return a.split("\u00a0").join(" ").toUpperCase()};A=function(a){for(var b=[],c=0,e=a.length;c<e;c++)b[c]=C(a[c]);return b};y=function(a,b,c){var a=
o(a),c=c.calendar,b=H(c,b),e=RegExp(b.regExp).exec(a);if(null===e)return null;var d=b.groups,g=b=a=null,f=null,i=null,j=0,k,n=0,t=0,h=0;k=null;for(var s=!1,r=0,q=d.length;r<q;r++){var m=e[r+1];if(m){var l=d[r],v=l.length,u=parseInt(m,10);switch(l){case "dd":case "d":f=u;if(x(f,1,31))return null;break;case "MMM":case "MMMM":g=G(c,m,3===v);if(x(g,0,11))return null;break;case "M":case "MM":g=u-1;if(x(g,0,11))return null;break;case "y":case "yy":case "yyyy":b=4>v?E(c,u):u;if(x(b,0,9999))return null;break;
case "h":case "hh":j=u;12===j&&(j=0);if(x(j,0,11))return null;break;case "H":case "HH":j=u;if(x(j,0,23))return null;break;case "m":case "mm":n=u;if(x(n,0,59))return null;break;case "s":case "ss":t=u;if(x(t,0,59))return null;break;case "tt":case "t":s=c.PM&&(m===c.PM[0]||m===c.PM[1]||m===c.PM[2]);if(!s&&(!c.AM||m!==c.AM[0]&&m!==c.AM[1]&&m!==c.AM[2]))return null;break;case "f":case "ff":case "fff":h=u*Math.pow(10,3-v);if(x(h,0,999))return null;break;case "ddd":case "dddd":i=F(c,m,3===v);if(x(i,0,6))return null;
break;case "zzz":l=m.split(/:/);if(2!==l.length)return null;k=parseInt(l[0],10);if(x(k,-12,13))return null;l=parseInt(l[1],10);if(x(l,0,59))return null;k=60*k+(p(m,"-")?-l:l);break;case "z":case "zz":k=u;if(x(k,-12,13))return null;k*=60;break;case "g":case "gg":if(!m||!c.eras)return null;m=o(m.toLowerCase());l=0;for(v=c.eras.length;l<v;l++)if(m===c.eras[l].name.toLowerCase()){a=l;break}if(null===a)return null}}}e=new Date;d=(r=c.convert)?r.fromGregorian(e)[0]:e.getFullYear();null===b?b=d:c.eras&&
(b+=c.eras[a||0].offset);null===g&&(g=0);null===f&&(f=1);if(r){if(e=r.toGregorian(b,g,f),null===e)return null}else if(e.setFullYear(b,g,f),e.getDate()!==f||null!==i&&e.getDay()!==i)return null;s&&12>j&&(j+=12);e.setHours(j,n,t,h);null!==k&&(c=e.getMinutes()-(k+e.getTimezoneOffset()),e.setHours(e.getHours()+parseInt(c/60,10),c%60));return e};B=function(a,b,c){var e=b["-"],b=b["+"],d;switch(c){case "n -":e=" "+e,b=" "+b;case "n-":i(a,e)?d=["-",a.substr(0,a.length-e.length)]:i(a,b)&&(d=["+",a.substr(0,
a.length-b.length)]);break;case "- n":e+=" ",b+=" ";case "-n":p(a,e)?d=["-",a.substr(e.length)]:p(a,b)&&(d=["+",a.substr(b.length)]);break;case "(n)":p(a,"(")&&i(a,")")&&(d=["-",a.substr(1,a.length-2)])}return d||["",a]};h.prototype.findClosestCulture=function(a){return h.findClosestCulture.call(this,a)};h.prototype.format=function(a,b,c){return h.format.call(this,a,b,c)};h.prototype.localize=function(a,b){return h.localize.call(this,a,b)};h.prototype.parseInt=function(a,b,c){return h.parseInt.call(this,
a,b,c)};h.prototype.parseFloat=function(a,b,c){return h.parseFloat.call(this,a,b,c)};h.prototype.culture=function(a){return h.culture.call(this,a)};h.addCultureInfo=function(a,b,c){var e={},d=!1;"string"!==typeof a?(c=a,a=this.culture().name,e=this.cultures[a]):"string"!==typeof b?(c=b,d=null==this.cultures[a],e=this.cultures[a]||this.cultures["default"]):(d=!0,e=this.cultures[b]);this.cultures[a]=t(!0,{},e,c);d&&(this.cultures[a].calendar=this.cultures[a].calendars.standard)};h.findClosestCulture=
function(a){var b;if(!a)return this.findClosestCulture(this.cultureSelector)||this.cultures["default"];"string"===typeof a&&(a=a.split(","));if(n(a)){var c,e=this.cultures,d=a,g,f=d.length,i=[];for(g=0;g<f;g++)a=o(d[g]),a=a.split(";"),c=o(a[0]),1===a.length?a=1:(a=o(a[1]),0===a.indexOf("q=")?(a=a.substr(2),a=parseFloat(a),a=isNaN(a)?0:a):a=1),i.push({lang:c,pri:a});i.sort(function(a,b){return a.pri<b.pri?1:a.pri>b.pri?-1:0});for(g=0;g<f;g++)if(c=i[g].lang,b=e[c])return b;for(g=0;g<f;g++){c=i[g].lang;
do{d=c.lastIndexOf("-");if(-1===d)break;c=c.substr(0,d);if(b=e[c])return b}while(1)}for(g=0;g<f;g++){c=i[g].lang;for(var j in e)if(d=e[j],d.language==c)return d}}else if("object"===typeof a)return a;return b||null};h.format=function(a,b,c){c=this.findClosestCulture(c);a instanceof Date?a=v(a,b,c):"number"===typeof a&&(a=l(a,b,c));return a};h.localize=function(a,b){return this.findClosestCulture(b).messages[a]||this.cultures["default"].messages[a]};h.parseDate=function(a,b,c){var c=this.findClosestCulture(c),
e,d;if(b){if("string"===typeof b&&(b=[b]),b.length){d=0;for(var g=b.length;d<g;d++){var f=b[d];if(f&&(e=y(a,f,c)))break}}}else for(d in b=c.calendar.patterns,b)if(e=y(a,b[d],c))break;return e||null};h.parseInt=function(a,b,c){return r(h.parseFloat(a,b,c))};h.parseFloat=function(a,b,c){"number"!==typeof b&&(c=b,b=10);var f=this.findClosestCulture(c),c=NaN,i=f.numberFormat;-1<a.indexOf(f.numberFormat.currency.symbol)&&(a=a.replace(f.numberFormat.currency.symbol,""),a=a.replace(f.numberFormat.currency["."],
f.numberFormat["."]));a=o(a);if(g.test(a))c=parseFloat(a);else if(!b&&d.test(a))c=parseInt(a,16);else{f=B(a,i,i.pattern[0]);b=f[0];f=f[1];""===b&&"(n)"!==i.pattern[0]&&(f=B(a,i,"(n)"),b=f[0],f=f[1]);""===b&&"-n"!==i.pattern[0]&&(f=B(a,i,"-n"),b=f[0],f=f[1]);var b=b||"+",j,a=f.indexOf("e");0>a&&(a=f.indexOf("E"));0>a?(j=f,a=null):(j=f.substr(0,a),a=f.substr(a+1));var k=i["."],n=j.indexOf(k);0>n?(f=j,j=null):(f=j.substr(0,n),j=j.substr(n+k.length));k=i[","];f=f.split(k).join("");n=k.replace(/\u00A0/g,
" ");k!==n&&(f=f.split(n).join(""));b+=f;null!==j&&(b+="."+j);null!==a&&(i=B(a,i,"-n"),b+="e"+(i[0]||"+")+i[1]);e.test(b)&&(c=parseFloat(b))}return c};h.culture=function(a){"undefined"!==typeof a&&(this.cultureSelector=a);return this.findClosestCulture(a)||this.cultures["default"]}})(this);
"JSON"in window&&window.JSON||(this.JSON||(this.JSON={}),function(){function a(a){return a<10?"0"+a:a}function f(a){g.lastIndex=0;return g.test(a)?'"'+a.replace(g,function(a){var b=c[a];return typeof b==="string"?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function h(a,c){var d,g,p,o,r=e,q,s=c[a];s&&(typeof s==="object"&&typeof s.toJSON==="function")&&(s=s.toJSON(a));typeof i==="function"&&(s=i.call(c,a,s));switch(typeof s){case "string":return f(s);case "number":return isFinite(s)?
String(s):"null";case "boolean":case "null":return String(s);case "object":if(!s)return"null";e=e+b;q=[];if(Object.prototype.toString.apply(s)==="[object Array]"){o=s.length;for(d=0;d<o;d=d+1)q[d]=h(d,s)||"null";p=q.length===0?"[]":e?"[\n"+e+q.join(",\n"+e)+"\n"+r+"]":"["+q.join(",")+"]";e=r;return p}if(i&&typeof i==="object"){o=i.length;for(d=0;d<o;d=d+1){g=i[d];if(typeof g==="string")(p=h(g,s))&&q.push(f(g)+(e?": ":":")+p)}}else for(g in s)if(Object.hasOwnProperty.call(s,g))(p=h(g,s))&&q.push(f(g)+
(e?": ":":")+p);p=q.length===0?"{}":e?"{\n"+e+q.join(",\n"+e)+"\n"+r+"}":"{"+q.join(",")+"}";e=r;return p}}if(typeof Date.prototype.toJSON!=="function"){Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null};String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()}}var d=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
g=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,e,b,c={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},i;if(typeof JSON.stringify!=="function")JSON.stringify=function(a,c,d){var g;b=e="";if(typeof d==="number")for(g=0;g<d;g=g+1)b=b+" ";else typeof d==="string"&&(b=d);if((i=c)&&typeof c!=="function"&&(typeof c!=="object"||typeof c.length!=="number"))throw Error("JSON.stringify");return h("",{"":a})};
if(typeof JSON.parse!=="function")JSON.parse=function(a,b){function c(a,e){var d,g,f=a[e];if(f&&typeof f==="object")for(d in f)if(Object.hasOwnProperty.call(f,d)){g=c(f,d);g!==void 0?f[d]=g:delete f[d]}return b.call(a,e,f)}var e,a=String(a);d.lastIndex=0;d.test(a)&&(a=a.replace(d,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){e=eval("("+a+")");return typeof b==="function"?c({"":e},""):e}throw new SyntaxError("JSON.parse");}}());
(function(a){a.factory=function(f,h){if(a.fn[f])throw"$.fn."+f+" plugin already exists";if(a[f])throw"$."+f+" class already exists";a.fn[f]=function(d){var g=null,e=null;if(a.type(d)==="string"){g=d;e=Array.prototype.slice.call(arguments,1)}return this.each(function(){var b=a(this),c=b.data("$."+f);if(g)c&&a.type(c[g])==="function"?c[g].apply(c,e):console.warn(f,"Unable to invoke method",g);else{c&&c._destroy();c=new a[f](b,d);b.data("$."+f,c)}})};a[f]=function(d,g){this.options=a.extend(true,{},
a[f].defaults,g);this.element=d;this.init()};a.extend(a[f].prototype,{init:function(){},_destroy:function(){}},h);return a[f]}})(jQuery);
(function(){var a={};$.extend({localstore:function(f,h,d,g){var e=document.location.hostname,b=document.location.protocol;if(typeof h!=="undefined"){var c=JSON.stringify(h);if(!d&&window.globalStorage)h===null?delete window.globalStorage[e][b+f]:window.globalStorage[e][b+f]=c;else if(!d&&window.localStorage&&window.localStorage.setItem)h===null?window.localStorage.removeItem(b+f):window.localStorage.setItem(b+f,c);else if(d!==false){d={};d.domain=fb.get_cookie_domain();h===null?$.cookie(f,null,d):
$.cookie(f,c,$.extend(d,g||{expires:14,path:"/"}))}else h===null?delete a[f]:a[f]=c;return h}if(!d&&window.globalStorage){if(window.globalStorage[e][b+f])h=window.globalStorage[e][b+f].value}else h=!d&&window.localStorage?window.localStorage.getItem(b+f):d!==false?$.cookie(f):a[f];return h!=""&&h!==null&&h!==void 0?JSON.parse(h,null):null}})})();
(function(a){a.extend({metadata:{defaults:{type:"class",name:"metadata",cre:/({.*})/,single:"metadata"},setType:function(a,h){this.defaults.type=a;this.defaults.name=h},get:function(f,h){var d=a.extend({},this.defaults,h);if(!d.single.length)d.single="metadata";var g=a.data(f,d.single);if(g)return g;var g="{}",e=function(a){if(typeof a!="string")return a;return a=eval("("+a+")")};if(d.type=="html5"){var b={};a(f.attributes).each(function(){var a=this.nodeName;if(a.match(/^data-/))a=a.replace(/^data-/,
"");else return true;b[a]=e(this.nodeValue)})}else{if(d.type=="class"){var c=d.cre.exec(f.className);c&&(g=c[1])}else if(d.type=="elem"){if(!f.getElementsByTagName)return;c=f.getElementsByTagName(d.name);c.length&&(g=a.trim(c[0].innerHTML))}else if(f.getAttribute!=void 0)(c=f.getAttribute(d.name))&&(g=c);b=e(g.indexOf("{")<0?"{"+g+"}":g)}a.data(f,d.single,b);return b}}});a.fn.metadata=function(f){return a.metadata.get(this[0],f)}})(jQuery);
(function(a,f){function h(d){return!a(d).parents().andSelf().filter(function(){return a.curCSS(this,"visibility")==="hidden"||a.expr.filters.hidden(this)}).length}a.ui=a.ui||{};if(!a.ui.version){a.extend(a.ui,{version:"1.8.10",keyCode:{ALT:18,BACKSPACE:8,CAPS_LOCK:20,COMMA:188,COMMAND:91,COMMAND_LEFT:91,COMMAND_RIGHT:93,CONTROL:17,DELETE:46,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,INSERT:45,LEFT:37,MENU:93,NUMPAD_ADD:107,NUMPAD_DECIMAL:110,NUMPAD_DIVIDE:111,NUMPAD_ENTER:108,NUMPAD_MULTIPLY:106,NUMPAD_SUBTRACT:109,
PAGE_DOWN:34,PAGE_UP:33,PERIOD:190,RIGHT:39,SHIFT:16,SPACE:32,TAB:9,UP:38,WINDOWS:91}});a.fn.extend({_focus:a.fn.focus,focus:function(d,g){return typeof d==="number"?this.each(function(){var e=this;setTimeout(function(){a(e).focus();g&&g.call(e)},d)}):this._focus.apply(this,arguments)},scrollParent:function(){var d;d=a.browser.msie&&/(static|relative)/.test(this.css("position"))||/absolute/.test(this.css("position"))?this.parents().filter(function(){return/(relative|absolute|fixed)/.test(a.curCSS(this,
"position",1))&&/(auto|scroll)/.test(a.curCSS(this,"overflow",1)+a.curCSS(this,"overflow-y",1)+a.curCSS(this,"overflow-x",1))}).eq(0):this.parents().filter(function(){return/(auto|scroll)/.test(a.curCSS(this,"overflow",1)+a.curCSS(this,"overflow-y",1)+a.curCSS(this,"overflow-x",1))}).eq(0);return/fixed/.test(this.css("position"))||!d.length?a(document):d},zIndex:function(d){if(d!==f)return this.css("zIndex",d);if(this.length)for(var d=a(this[0]),g;d.length&&d[0]!==document;){g=d.css("position");if(g===
"absolute"||g==="relative"||g==="fixed"){g=parseInt(d.css("zIndex"),10);if(!isNaN(g)&&g!==0)return g}d=d.parent()}return 0},disableSelection:function(){return this.bind((a.support.selectstart?"selectstart":"mousedown")+".ui-disableSelection",function(a){a.preventDefault()})},enableSelection:function(){return this.unbind(".ui-disableSelection")}});a.each(["Width","Height"],function(d,g){function e(c,e,d,g){a.each(b,function(){e=e-(parseFloat(a.curCSS(c,"padding"+this,true))||0);d&&(e=e-(parseFloat(a.curCSS(c,
"border"+this+"Width",true))||0));g&&(e=e-(parseFloat(a.curCSS(c,"margin"+this,true))||0))});return e}var b=g==="Width"?["Left","Right"]:["Top","Bottom"],c=g.toLowerCase(),i={innerWidth:a.fn.innerWidth,innerHeight:a.fn.innerHeight,outerWidth:a.fn.outerWidth,outerHeight:a.fn.outerHeight};a.fn["inner"+g]=function(b){return b===f?i["inner"+g].call(this):this.each(function(){a(this).css(c,e(this,b)+"px")})};a.fn["outer"+g]=function(b,d){return typeof b!=="number"?i["outer"+g].call(this,b):this.each(function(){a(this).css(c,
e(this,b,true,d)+"px")})}});a.extend(a.expr[":"],{data:function(d,g,e){return!!a.data(d,e[3])},focusable:function(d){var g=d.nodeName.toLowerCase(),e=a.attr(d,"tabindex");if("area"===g){g=d.parentNode;e=g.name;if(!d.href||!e||g.nodeName.toLowerCase()!=="map")return false;d=a("img[usemap=#"+e+"]")[0];return!!d&&h(d)}return(/input|select|textarea|button|object/.test(g)?!d.disabled:"a"==g?d.href||!isNaN(e):!isNaN(e))&&h(d)},tabbable:function(d){var g=a.attr(d,"tabindex");return(isNaN(g)||g>=0)&&a(d).is(":focusable")}});
a(function(){var d=document.body,g=d.appendChild(g=document.createElement("div"));a.extend(g.style,{minHeight:"100px",height:"auto",padding:0,borderWidth:0});a.support.minHeight=g.offsetHeight===100;a.support.selectstart="onselectstart"in g;d.removeChild(g).style.display="none"});a.extend(a.ui,{plugin:{add:function(d,g,e){var d=a.ui[d].prototype,b;for(b in e){d.plugins[b]=d.plugins[b]||[];d.plugins[b].push([g,e[b]])}},call:function(a,g,e){if((g=a.plugins[g])&&a.element[0].parentNode)for(var b=0;b<
g.length;b++)a.options[g[b][0]]&&g[b][1].apply(a.element,e)}},contains:function(a,g){return document.compareDocumentPosition?a.compareDocumentPosition(g)&16:a!==g&&a.contains(g)},hasScroll:function(d,g){if(a(d).css("overflow")==="hidden")return false;var e=g&&g==="left"?"scrollLeft":"scrollTop",b=false;if(d[e]>0)return true;d[e]=1;b=d[e]>0;d[e]=0;return b},isOverAxis:function(a,g,e){return a>g&&a<g+e},isOver:function(d,g,e,b,c,f){return a.ui.isOverAxis(d,e,c)&&a.ui.isOverAxis(g,b,f)}})}})(jQuery);
(function(a,f){if(a.cleanData){var h=a.cleanData;a.cleanData=function(d){for(var e=0,b;(b=d[e])!=null;e++)a(b).triggerHandler("remove");h(d)}}else{var d=a.fn.remove;a.fn.remove=function(g,e){return this.each(function(){e||(!g||a.filter(g,[this]).length)&&a("*",this).add([this]).each(function(){a(this).triggerHandler("remove")});return d.call(a(this),g,e)})}}a.widget=function(d,e,b){var c=d.split(".")[0],f,d=d.split(".")[1];f=c+"-"+d;if(!b){b=e;e=a.Widget}a.expr[":"][f]=function(b){return!!a.data(b,
d)};a[c]=a[c]||{};a[c][d]=function(a,b){arguments.length&&this._createWidget(a,b)};e=new e;e.options=a.extend(true,{},e.options);a[c][d].prototype=a.extend(true,e,{namespace:c,widgetName:d,widgetEventPrefix:a[c][d].prototype.widgetEventPrefix||d,widgetBaseClass:f},b);a.widget.bridge(d,a[c][d])};a.widget.bridge=function(d,e){a.fn[d]=function(b){var c=typeof b==="string",i=Array.prototype.slice.call(arguments,1),h=this,b=!c&&i.length?a.extend.apply(null,[true,b].concat(i)):b;if(c&&b.charAt(0)==="_")return h;
c?this.each(function(){var c=a.data(this,d),e=c&&a.isFunction(c[b])?c[b].apply(c,i):c;if(e!==c&&e!==f){h=e;return false}}):this.each(function(){var c=a.data(this,d);c?c.option(b||{})._init():a.data(this,d,new e(b,this))});return h}};a.Widget=function(a,e){arguments.length&&this._createWidget(a,e)};a.Widget.prototype={widgetName:"widget",widgetEventPrefix:"",options:{disabled:false},_createWidget:function(d,e){a.data(e,this.widgetName,this);this.element=a(e);this.options=a.extend(true,{},this.options,
this._getCreateOptions(),d);var b=this;this.element.bind("remove."+this.widgetName,function(){b.destroy()});this._create();this._trigger("create");this._init()},_getCreateOptions:function(){return a.metadata&&a.metadata.get(this.element[0])[this.widgetName]},_create:function(){},_init:function(){},destroy:function(){this.element.unbind("."+this.widgetName).removeData(this.widgetName);this.widget().unbind("."+this.widgetName).removeAttr("aria-disabled").removeClass(this.widgetBaseClass+"-disabled ui-state-disabled")},
widget:function(){return this.element},option:function(d,e){var b=d;if(arguments.length===0)return a.extend({},this.options);if(typeof d==="string"){if(e===f)return this.options[d];b={};b[d]=e}this._setOptions(b);return this},_setOptions:function(d){var e=this;a.each(d,function(a,c){e._setOption(a,c)});return this},_setOption:function(a,e){this.options[a]=e;a==="disabled"&&this.widget()[e?"addClass":"removeClass"](this.widgetBaseClass+"-disabled ui-state-disabled").attr("aria-disabled",e);return this},
enable:function(){return this._setOption("disabled",false)},disable:function(){return this._setOption("disabled",true)},_trigger:function(d,e,b){var c=this.options[d],e=a.Event(e);e.type=(d===this.widgetEventPrefix?d:this.widgetEventPrefix+d).toLowerCase();b=b||{};if(e.originalEvent)for(var d=a.event.props.length,f;d;){f=a.event.props[--d];e[f]=e.originalEvent[f]}this.element.trigger(e,b);return!(a.isFunction(c)&&c.call(this.element[0],e,b)===false||e.isDefaultPrevented())}}})(jQuery);
(function(a){a.widget("ui.mouse",{options:{cancel:":input,option",distance:1,delay:0},_mouseInit:function(){var f=this;this.element.bind("mousedown."+this.widgetName,function(a){return f._mouseDown(a)}).bind("click."+this.widgetName,function(h){if(true===a.data(h.target,f.widgetName+".preventClickEvent")){a.removeData(h.target,f.widgetName+".preventClickEvent");h.stopImmediatePropagation();return false}});this.started=false},_mouseDestroy:function(){this.element.unbind("."+this.widgetName)},_mouseDown:function(f){f.originalEvent=
f.originalEvent||{};if(!f.originalEvent.mouseHandled){this._mouseStarted&&this._mouseUp(f);this._mouseDownEvent=f;var h=this,d=f.which==1,g=typeof this.options.cancel=="string"?a(f.target).parents().add(f.target).filter(this.options.cancel).length:false;if(!d||g||!this._mouseCapture(f))return true;this.mouseDelayMet=!this.options.delay;if(!this.mouseDelayMet)this._mouseDelayTimer=setTimeout(function(){h.mouseDelayMet=true},this.options.delay);if(this._mouseDistanceMet(f)&&this._mouseDelayMet(f)){this._mouseStarted=
this._mouseStart(f)!==false;if(!this._mouseStarted){f.preventDefault();return true}}this._mouseMoveDelegate=function(a){return h._mouseMove(a)};this._mouseUpDelegate=function(a){return h._mouseUp(a)};a(document).bind("mousemove."+this.widgetName,this._mouseMoveDelegate).bind("mouseup."+this.widgetName,this._mouseUpDelegate);f.preventDefault();return f.originalEvent.mouseHandled=true}},_mouseMove:function(f){if(a.browser.msie&&!(document.documentMode>=9)&&!f.button)return this._mouseUp(f);if(this._mouseStarted){this._mouseDrag(f);
return f.preventDefault()}if(this._mouseDistanceMet(f)&&this._mouseDelayMet(f))(this._mouseStarted=this._mouseStart(this._mouseDownEvent,f)!==false)?this._mouseDrag(f):this._mouseUp(f);return!this._mouseStarted},_mouseUp:function(f){a(document).unbind("mousemove."+this.widgetName,this._mouseMoveDelegate).unbind("mouseup."+this.widgetName,this._mouseUpDelegate);if(this._mouseStarted){this._mouseStarted=false;f.target==this._mouseDownEvent.target&&a.data(f.target,this.widgetName+".preventClickEvent",
true);this._mouseStop(f)}return false},_mouseDistanceMet:function(a){return Math.max(Math.abs(this._mouseDownEvent.pageX-a.pageX),Math.abs(this._mouseDownEvent.pageY-a.pageY))>=this.options.distance},_mouseDelayMet:function(){return this.mouseDelayMet},_mouseStart:function(){},_mouseDrag:function(){},_mouseStop:function(){},_mouseCapture:function(){return true}})})(jQuery);
(function(a){a.ui=a.ui||{};var f=/left|center|right/,h=/top|center|bottom/,d=a.fn.position,g=a.fn.offset;a.fn.position=function(e){if(!e||!e.of)return d.apply(this,arguments);var e=a.extend({},e),b=a(e.of),c=b[0],g=(e.collision||"flip").split(" "),t=e.offset?e.offset.split(" "):[0,0],n,j,k;if(c.nodeType===9){n=b.width();j=b.height();k={top:0,left:0}}else if(c.setTimeout){n=b.width();j=b.height();k={top:b.scrollTop(),left:b.scrollLeft()}}else if(c.preventDefault){e.at="left top";n=j=0;k={top:e.of.pageY,
left:e.of.pageX}}else{n=b.outerWidth();j=b.outerHeight();k=b.offset()}a.each(["my","at"],function(){var a=(e[this]||"").split(" ");a.length===1&&(a=f.test(a[0])?a.concat(["center"]):h.test(a[0])?["center"].concat(a):["center","center"]);a[0]=f.test(a[0])?a[0]:"center";a[1]=h.test(a[1])?a[1]:"center";e[this]=a});g.length===1&&(g[1]=g[0]);t[0]=parseInt(t[0],10)||0;t.length===1&&(t[1]=t[0]);t[1]=parseInt(t[1],10)||0;if(e.at[0]==="right")k.left=k.left+n;else if(e.at[0]==="center")k.left=k.left+n/2;if(e.at[1]===
"bottom")k.top=k.top+j;else if(e.at[1]==="center")k.top=k.top+j/2;k.left=k.left+t[0];k.top=k.top+t[1];return this.each(function(){var b=a(this),c=b.outerWidth(),d=b.outerHeight(),f=parseInt(a.curCSS(this,"marginLeft",true))||0,h=parseInt(a.curCSS(this,"marginTop",true))||0,m=c+f+(parseInt(a.curCSS(this,"marginRight",true))||0),v=d+h+(parseInt(a.curCSS(this,"marginBottom",true))||0),l=a.extend({},k),w;if(e.my[0]==="right")l.left=l.left-c;else if(e.my[0]==="center")l.left=l.left-c/2;if(e.my[1]==="bottom")l.top=
l.top-d;else if(e.my[1]==="center")l.top=l.top-d/2;l.left=Math.round(l.left);l.top=Math.round(l.top);w={left:l.left-f,top:l.top-h};a.each(["left","top"],function(b,f){if(a.ui.position[g[b]])a.ui.position[g[b]][f](l,{targetWidth:n,targetHeight:j,elemWidth:c,elemHeight:d,collisionPosition:w,collisionWidth:m,collisionHeight:v,offset:t,my:e.my,at:e.at})});a.fn.bgiframe&&b.bgiframe();b.offset(a.extend(l,{using:e.using}))})};a.ui.position={fit:{left:function(e,b){var c=a(window),c=b.collisionPosition.left+
b.collisionWidth-c.width()-c.scrollLeft();e.left=c>0?e.left-c:Math.max(e.left-b.collisionPosition.left,e.left)},top:function(e,b){var c=a(window),c=b.collisionPosition.top+b.collisionHeight-c.height()-c.scrollTop();e.top=c>0?e.top-c:Math.max(e.top-b.collisionPosition.top,e.top)}},flip:{left:function(e,b){if(b.at[0]!=="center"){var c=a(window),c=b.collisionPosition.left+b.collisionWidth-c.width()-c.scrollLeft(),d=b.my[0]==="left"?-b.elemWidth:b.my[0]==="right"?b.elemWidth:0,f=b.at[0]==="left"?b.targetWidth:
-b.targetWidth,g=-2*b.offset[0];e.left=e.left+(b.collisionPosition.left<0?d+f+g:c>0?d+f+g:0)}},top:function(e,b){if(b.at[1]!=="center"){var c=a(window),c=b.collisionPosition.top+b.collisionHeight-c.height()-c.scrollTop(),d=b.my[1]==="top"?-b.elemHeight:b.my[1]==="bottom"?b.elemHeight:0,f=b.at[1]==="top"?b.targetHeight:-b.targetHeight,g=-2*b.offset[1];e.top=e.top+(b.collisionPosition.top<0?d+f+g:c>0?d+f+g:0)}}}};if(!a.offset.setOffset){a.offset.setOffset=function(e,b){if(/static/.test(a.curCSS(e,"position")))e.style.position=
"relative";var c=a(e),d=c.offset(),f=parseInt(a.curCSS(e,"top",true),10)||0,g=parseInt(a.curCSS(e,"left",true),10)||0,d={top:b.top-d.top+f,left:b.left-d.left+g};"using"in b?b.using.call(e,d):c.css(d)};a.fn.offset=function(e){var b=this[0];return!b||!b.ownerDocument?null:e?this.each(function(){a.offset.setOffset(this,e)}):g.call(this)}}})(jQuery);
(function(a,f){if(!("console"in window)){var h=window.console={};h.log=h.warn=h.error=h.debug=function(){}}a(function(){var b=a("<div>");a(document.body).append(b);var c=setTimeout(function(){if(a.cleanData){var b=a.cleanData;a.cleanData=function(c){for(var e=0,d;(d=c[e])!=null;e++)a(d).triggerHandler("remove");b(c)}}else{var c=a.fn.remove;a.fn.remove=function(b,e){return this.each(function(){e||(!b||a.filter(b,[this]).length)&&a("*",this).add([this]).each(function(){a(this).triggerHandler("remove")});
return c.call(a(this),b,e)})}}},1);b.bind("remove",function(){clearTimeout(c)});b.remove()});var d={key:1,filter:1,spell:1,exact:1,lang:1,scoring:1,prefixed:1,stemmed:1,format:1,mql_output:1,output:1};a.suggest=function(b,c){a.fn[b]=function(c){this.length||console.warn("Suggest: invoked on empty element set");return this.each(function(){this.nodeName&&(this.nodeName.toUpperCase()==="INPUT"?this.type&&this.type.toUpperCase()!=="TEXT"&&console.warn("Suggest: unsupported INPUT type: "+this.type):console.warn("Suggest: unsupported DOM element: "+
this.nodeName));var e=a.data(this,b);e&&e._destroy();a.data(this,b,new a.suggest[b](this,c))._init()})};a.suggest[b]=function(c,e){var f=this,g=this.options=a.extend(true,{},a.suggest.defaults,a.suggest[b].defaults,e),k=g.css_prefix=g.css_prefix||"",h=g.css;this.name=b;a.each(h,function(a){h[a]=k+h[a]});g.ac_param={};a.each(d,function(a){var b=g[a];b===null||b===""||(g.ac_param[a]=b)});g.flyout_lang=null;if(g.ac_param.lang){var o=g.ac_param.lang;a.isArray(o)&&o.length&&(o=o.join(","));if(o)g.flyout_lang=
o}this._status={START:"",LOADING:"",SELECT:"",ERROR:""};if(g.status&&g.status instanceof Array&&g.status.length>=3){this._status.START=g.status[0]||"";this._status.LOADING=g.status[1]||"";this._status.SELECT=g.status[2]||"";if(g.status.length===4)this._status.ERROR=g.status[3]||""}var o=this.status=a('<div style="display:none;">').addClass(h.status),r=this.list=a("<ul>").addClass(h.list),q=this.pane=a('<div style="display:none;" class="fbs-reset">').addClass(h.pane);q.append(o).append(r);if(g.parent)a(g.parent).append(q);
else{q.css("position","absolute");g.zIndex&&q.css("z-index",g.zIndex);a(document.body).append(q)}q.bind("mousedown",function(a){f.input.data("dont_hide",true);a.stopPropagation()}).bind("mouseup",function(a){f.input.data("dont_hide")&&f.input.focus();f.input.removeData("dont_hide");a.stopPropagation()}).bind("click",function(a){a.stopPropagation();if(a=f.get_selected()){f.onselect(a,true);f.hide_all()}});r.hover(function(a){f.hoverover_list(a)},function(a){f.hoverout_list(a)});this.input=a(c).attr("autocomplete",
"off").unbind(".suggest").bind("remove.suggest",function(){f._destroy()}).bind("keydown.suggest",function(a){f.keydown(a)}).bind("keypress.suggest",function(a){f.keypress(a)}).bind("keyup.suggest",function(a){f.keyup(a)}).bind("blur.suggest",function(a){f.blur(a)}).bind("textchange.suggest",function(){f.textchange()}).bind("focus.suggest",function(a){f.focus(a)}).bind(a.browser.msie?"paste.suggest":"input.suggest",function(){clearTimeout(f.paste_timeout);f.paste_timeout=setTimeout(function(){f.textchange()},
0)});this.onresize=function(){f.invalidate_position();if(q.is(":visible")){f.position();if(g.flyout&&f.flyoutpane&&f.flyoutpane.is(":visible")){var a=f.get_selected();a&&f.flyout_position(a)}}};a(window).bind("resize.suggest",this.onresize).bind("scroll.suggest",this.onresize)};a.suggest[b].prototype=a.extend({},a.suggest.prototype,c)};a.suggest.prototype={_init:function(){},_destroy:function(){this.pane.remove();this.list.remove();this.input.unbind(".suggest");a(window).unbind("resize.suggest",this.onresize).unbind("scroll.suggest",
this.onresize);this.input.removeData("data.suggest")},invalidate_position:function(){self._position=null},status_start:function(){this.hide_all();this.status.siblings().hide();if(this._status.START){this.status.text(this._status.START).show();if(!this.pane.is(":visible")){this.position();this.pane_show()}}this._status.LOADING&&this.status.removeClass("loading")},status_loading:function(){this.status.siblings().show();if(this._status.LOADING){this.status.addClass("loading").text(this._status.LOADING).show();
if(!this.pane.is(":visible")){this.position();this.pane_show()}}else this.status.hide()},status_select:function(){this.status.siblings().show();this._status.SELECT?this.status.text(this._status.SELECT).show():this.status.hide();this._status.LOADING&&this.status.removeClass("loading")},status_error:function(){this.status.siblings().show();this._status.ERROR?this.status.text(this._status.ERROR).show():this.status.hide();this._status.LOADING&&this.status.removeClass("loading")},focus:function(a){this.input.val()===
""?this.status_start():this.focus_hook(a)},focus_hook:function(){if(!this.input.data("data.suggest")&&!this.pane.is(":visible")&&a("."+this.options.css.item,this.list).length){this.position();this.pane_show()}},keydown:function(a){var c=a.keyCode;if(c===9)this.tab(a);else if(c===38||c===40)a.shiftKey||a.preventDefault()},keypress:function(a){var c=a.keyCode;c===38||c===40?a.shiftKey||a.preventDefault():c===13&&this.enter(a)},keyup:function(b){var c=b.keyCode;if(c===38){b.preventDefault();this.up(b)}else if(c===
40){b.preventDefault();this.down(b)}else if(b.ctrlKey&&c===77)a(".fbs-more-link",this.pane).click();else if(a.suggest.is_char(b)){clearTimeout(this.keypress.timeout);var e=this;this.keypress.timeout=setTimeout(function(){e.textchange()},0)}else c===27&&this.escape(b);return true},blur:function(){if(!this.input.data("dont_hide")){this.input.data("data.suggest");this.hide_all()}},tab:function(b){if(!b.shiftKey&&!b.metaKey&&!b.ctrlKey){var b=this.options,b=this.pane.is(":visible")&&a("."+b.css.item,
this.list).length,c=this.get_selected();if(b&&c){this.onselect(c);this.hide_all()}}},enter:function(b){var c=this.options;if(this.pane.is(":visible")){if(b.shiftKey){this.shift_enter(b);b.preventDefault();return}if(a("."+c.css.item,this.list).length){var e=this.get_selected();if(e){this.onselect(e);this.hide_all();b.preventDefault();return}if(!c.soft){this.input.data("data.suggest");if(a("."+this.options.css.item+":visible",this.list).length){this.updown(false);b.preventDefault();return}}}}c.soft?
this.soft_enter():b.preventDefault()},soft_enter:function(){},shift_enter:function(){},escape:function(){this.hide_all()},up:function(a){this.updown(true,a.ctrlKey||a.shiftKey)},down:function(a){this.updown(false,null,a.ctrlKey||a.shiftKey)},updown:function(b,c,e){var d=this.options.css,f=this.list;if(this.pane.is(":visible")){var g=a("."+d.item+":visible",f);if(g.length){var f=a(g[0]),g=a(g[g.length-1]),k=this.get_selected()||[];clearTimeout(this.ignore_mouseover.timeout);this._ignore_mouseover=
false;if(b)if(c)this._goto(f);else if(k.length)if(k[0]==f[0]){f.removeClass(d.selected);this.input.val(this.input.data("original.suggest"));this.hoverout_list()}else{b=k.prevAll("."+d.item+":visible:first");this._goto(b)}else this._goto(g);else if(e)this._goto(g);else if(k.length)if(k[0]==g[0]){g.removeClass(d.selected);this.input.val(this.input.data("original.suggest"));this.hoverout_list()}else{b=k.nextAll("."+d.item+":visible:first");this._goto(b)}else this._goto(f)}}else b||this.textchange()},
_goto:function(a){a.trigger("mouseover.suggest");var c=a.data("data.suggest");this.input.val(c?c.name:this.input.data("original.suggest"));this.scroll_to(a)},scroll_to:function(a){var c=this.list,e=c.scrollTop(),d=e+c.innerHeight(),f=a.outerHeight(),a=a.prevAll().length*f,f=a+f;if(a<e){this.ignore_mouseover();c.scrollTop(a)}else if(f>d){this.ignore_mouseover();c.scrollTop(e+f-d)}},textchange:function(){this.input.removeData("data.suggest");this.input.trigger("fb-textchange",this);var a=this.input.val();
if(a==="")this.status_start();else{this.status_loading();this.request(a)}},request:function(){},response:function(b){if(b){"cost"in b&&this.trackEvent(this.name,"response","cost",b.cost);if(this.check_response(b)){var c=[];if(a.isArray(b))c=b;else if("result"in b)c=b.result;var e=a.map(arguments,function(a){return a});this.response_hook.apply(this,e);var d=null,f=this,g=this.options;a.each(c,function(a,c){if(!c.id&&c.mid)c.id=c.mid;var e=f.create_item(c,b).bind("mouseover.suggest",function(a){f.mouseover_item(a)});
e.data("data.suggest",c);f.list.append(e);a===0&&(d=e)});this.input.data("original.suggest",this.input.val());if(a("."+g.css.item,this.list).length===0&&g.nomatch){c=a('<li class="fbs-nomatch">');if(typeof g.nomatch==="string")c.text(g.nomatch);else{g.nomatch.title&&c.append(a('<em class="fbs-nomatch-text">').text(g.nomatch.title));g.nomatch.heading&&c.append(a("<h3>").text(g.nomatch.heading));if((g=g.nomatch.tips)&&g.length){var k=a('<ul class="fbs-search-tips">');a.each(g,function(b,c){k.append(a("<li>").text(c))});
c.append(k)}}c.bind("click.suggest",function(a){a.stopPropagation()});this.list.append(c)}e.push(d);this.show_hook.apply(this,e);this.position();this.pane_show()}}},pane_show:function(){var b=false;a("> li",this.list).length&&(b=true);b||this.pane.children(":not(."+this.options.css.list+")").each(function(){if(a(this).css("display")!="none"){b=true;return false}});if(b)if(this.options.animate){var c=this;this.pane.slideDown("fast",function(){c.input.trigger("fb-pane-show",c)})}else{this.pane.show();
this.input.trigger("fb-pane-show",this)}else{this.pane.hide();this.input.trigger("fb-pane-hide",this)}},create_item:function(b){var c=this.options.css,e=a("<li>").addClass(c.item),b=a("<label>").text(b.name);e.append(a("<div>").addClass(c.item_name).append(b));return e},mouseover_item:function(b){if(!this._ignore_mouseover){b=b.target;b.nodeName.toLowerCase()!=="li"&&(b=a(b).parents("li:first"));var c=a(b),e=this.options.css;a("."+e.item,this.list).each(function(){this!==c[0]&&a(this).removeClass(e.selected)});
if(!c.hasClass(e.selected)){c.addClass(e.selected);this.mouseover_item_hook(c)}}},mouseover_item_hook:function(){},hoverover_list:function(){},hoverout_list:function(){},check_response:function(){return true},response_hook:function(){this.list.empty()},show_hook:function(){this.status_select()},position:function(){var b=this.pane,c=this.options;if(!c.parent){if(!self._position){var e=this.input,d=e.offset(),f=e.outerWidth(true),g=e.outerHeight(true);d.top=d.top+g;var k=b.outerWidth(),h=b.outerHeight(),
o=d.top+h/2,r=a(window).scrollLeft(),e=a(window).scrollTop(),q=a(window).width(),s=a(window).height()+e,m=true;"left"==c.align?m=true:"right"==c.align?m=false:d.left>r+q/2&&(m=false);if(!m){m=d.left-(k-f);if(m>r)d.left=m}if(o>s){c=d.top-g-h;if(c>e)d.top=c}this._position=d}b.css({top:this._position.top,left:this._position.left})}},ignore_mouseover:function(){this._ignore_mouseover=true;var a=this;this.ignore_mouseover.timeout=setTimeout(function(){a.ignore_mouseover_reset()},1E3)},ignore_mouseover_reset:function(){this._ignore_mouseover=
false},get_selected:function(){var b=null,c=this.options.css.selected;a("li",this.list).each(function(){var e=a(this);if(e.hasClass(c)&&e.is(":visible")){b=e;return false}});return b},onselect:function(a){var c=a.data("data.suggest");if(c){this.input.val(c.name).data("data.suggest",c).trigger("fb-select",c);this.trackEvent(this.name,"fb-select","index",a.prevAll().length)}},trackEvent:function(a,c,e,d){this.input.trigger("fb-track-event",{category:a,action:c,label:e,value:d})},hide_all:function(){this.pane.hide();
this.input.trigger("fb-pane-hide",this)}};a.extend(a.suggest,{defaults:{status:["Start typing to get suggestions...","Searching...","Select an item from the list:","Sorry, something went wrong. Please try again later"],soft:false,nomatch:"no matches",css:{pane:"fbs-pane",list:"fbs-list",item:"fbs-item",item_name:"fbs-item-name",selected:"fbs-selected",status:"fbs-status"},css_prefix:null,parent:null,animate:false,zIndex:null},strongify:function(b,c){var e,d=b.toLowerCase().indexOf(c.toLowerCase());
if(d>=0){var f=c.length;e=document.createTextNode(b.substring(0,d));var g=a("<strong>").text(b.substring(d,d+f)),d=document.createTextNode(b.substring(d+f));e=a("<div>").append(e).append(g).append(d)}else e=a("<div>").text(b);return e},keyCode:{CAPS_LOCK:20,CONTROL:17,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,INSERT:45,LEFT:37,NUMPAD_ENTER:108,PAGE_DOWN:34,PAGE_UP:33,RIGHT:39,SHIFT:16,SPACE:32,TAB:9,UP:38,OPTION:18,APPLE:224},is_char:function(b){if(b.type==="keypress"){if((b.metaKey||b.ctrlKey)&&
b.charCode===118)return true;if("isChar"in b)return b.isChar}else{var c=a.suggest.keyCode.not_char;if(!c){c={};a.each(a.suggest.keyCode,function(a,b){c[""+b]=1});a.suggest.keyCode.not_char=c}return!(""+b.keyCode in c)}},parse_input:function(b){for(var c=/(\S+)\:(?:\"([^\"]+)\"|(\S+))/g,e=b,f=[],g={},h=c.exec(b);h;){h[1]in d?g[h[1]]=a.isEmptyObject(h[2])?h[3]:h[2]:f.push(h[0]);e=e.replace(h[0],"");h=c.exec(b)}e=a.trim(e.replace(/\s+/g," "));return[e,f,g]},mqlkey_fast:/^[_A-Za-z0-9][A-Za-z0-9_-]*$/,
mqlkey_slow:/^(?:[A-Za-z0-9]|\$[A-F0-9]{4})(?:[A-Za-z0-9_-]|\$[A-F0-9]{4})*$/,check_mql_key:function(b){return a.suggest.mqlkey_fast.test(b)||a.suggest.mqlkey_slow.test(b)?true:false},check_mql_id:function(b){if(b.indexOf("/")===0){b=b.split("/");b.shift();if(!(b.length==1&&b[0]===""))for(var c=0,e=b.length;c<e;c++)if(!a.suggest.check_mql_key(b[c]))return false;return true}return false},is_system_type:function(a){return a==null?false:a.indexOf("/type/")===0}});var g=a.suggest.prototype._destroy,e=
a.suggest.prototype.show_hook;a.suggest("suggest",{_init:function(){var b=this,c=this.options;if(c.flyout_service_url==null)c.flyout_service_url=c.service_url;this.flyout_url=c.flyout_service_url;if(c.flyout_service_path)this.flyout_url=this.flyout_url+c.flyout_service_path;this.flyout_url=this.flyout_url.replace(/\$\{key\}/g,c.key);if(c.flyout_image_service_url==null)c.flyout_image_service_url=c.service_url;this.flyout_image_url=c.flyout_image_service_url;if(c.flyout_image_service_path)this.flyout_image_url=
this.flyout_image_url+c.flyout_image_service_path;this.flyout_image_url=this.flyout_image_url.replace(/\$\{key\}/g,c.key);if(!a.suggest.cache)a.suggest.cache={};if(c.flyout){this.flyoutpane=a('<div style="display:none;" class="fbs-reset">').addClass(c.css.flyoutpane);if(c.flyout_parent)a(c.flyout_parent).append(this.flyoutpane);else{this.flyoutpane.css("position","absolute");c.zIndex&&this.flyoutpane.css("z-index",c.zIndex);a(document.body).append(this.flyoutpane)}this.flyoutpane.hover(function(a){b.hoverover_list(a)},
function(a){b.hoverout_list(a)}).bind("mousedown.suggest",function(a){a.stopPropagation();b.pane.click()});if(!a.suggest.flyout)a.suggest.flyout={};if(!a.suggest.flyout.cache)a.suggest.flyout.cache={}}},_destroy:function(){g.call(this);this.flyoutpane&&this.flyoutpane.remove();this.input.removeData("request.count.suggest");this.input.removeData("flyout.request.count.suggest")},shift_enter:function(){if(this.options.suggest_new){this.suggest_new();this.hide_all()}},hide_all:function(){this.pane.hide();
this.flyoutpane&&this.flyoutpane.hide();this.input.trigger("fb-pane-hide",this);this.input.trigger("fb-flyoutpane-hide",this)},request:function(b,c){var e=this,d=this.options,f=b,g=d.ac_param.filter||[],k=null;a.type(g)==="string"&&(g=[g]);g=g.slice();if(d.advanced){var h=a.suggest.parse_input(f),f=h[0];h[1].length&&g.push("(all "+h[1].join(" ")+")");k=h[2];if(a.suggest.check_mql_id(f)){g.push('(any alias{start}:"'+f+'" mid:"'+f+'")');k.prefixed=true;f=""}}h={};h[d.query_param_name]=f;if(c)h.cursor=
c;a.extend(h,d.ac_param,k);if(g.length)h.filter=g;var o=d.service_url+d.service_path+"?"+a.param(h,true);if(f=a.suggest.cache[o])this.response(f,c?c:-1,true);else{clearTimeout(this.request.timeout);var r={url:d.service_url+d.service_path,data:h,traditional:true,beforeSend:function(){var a=e.input.data("request.count.suggest")||0;a||e.trackEvent(e.name,"start_session");a=a+1;e.trackEvent(e.name,"request","count",a);e.input.data("request.count.suggest",a)},success:function(d){a.suggest.cache[o]=d;d.prefix=
b;e.response(d,c?c:-1)},error:function(a){e.status_error();e.trackEvent(e.name,"request","error",{url:this.url,response:a?a.responseText:""});e.input.trigger("fb-error",Array.prototype.slice.call(arguments))},complete:function(a){a&&e.trackEvent(e.name,"request","tid",a.getResponseHeader("X-Metaweb-TID"))},dataType:"jsonp",cache:true};this.request.timeout=setTimeout(function(){a.ajax(r)},d.xhr_delay)}},create_item:function(b,c){var e=this.options.css,d=a("<li>").addClass(e.item),f=a("<label>").append(a.suggest.strongify(b.name||
b.id,c.prefix)),g=a("<div>").addClass(e.item_name).append(f),k=b.notable;b.under&&a(":first",f).append(a("<small>").text(" ("+b.under+")"));(k!=null&&a.suggest.is_system_type(k.id)||this.options.scoring!=null&&this.options.scoring.toUpperCase()==="SCHEMA")&&a(":first",f).append(a("<small>").text(" ("+b.id+")"));d.append(g);e=a("<div>").addClass(e.item_type);k&&k.name?e.text(k.name):this.options.show_id&&b.id&&e.text(b.id);g.prepend(e);return d},mouseover_item_hook:function(a){a=a.data("data.suggest");
this.options.flyout&&a&&this.flyout_request(a)},check_response:function(a){return a.prefix===this.input.val()},response_hook:function(b,c){this.flyoutpane&&this.flyoutpane.hide();c>0?a(".fbs-more",this.pane).remove():this.list.empty()},show_hook:function(b,c,d){e.apply(this,[b]);var f=this.options,g=this,h=this.pane,k=this.list,p=b.result,o=a(".fbs-more",h),r=a(".fbs-suggestnew",h);a(".fbs-status",h);var q=b.correction;if(q&&q.length){var s=a('<a class="fbs-spell-link" href="#">').append(q[0]).bind("click.suggest",
function(a){a.preventDefault();a.stopPropagation();g.input.val(q[0]).trigger("textchange")});g.status.empty().append("Search instead for ").append(s).show()}if(p&&p.length&&"cursor"in b){if(!o.length){p=a('<a class="fbs-more-link" href="#" title="(Ctrl+m)">view more</a>');o=a('<div class="fbs-more">').append(p);p.bind("click.suggest",function(b){b.preventDefault();b.stopPropagation();b=a(this).parent(".fbs-more");g.more(b.data("cursor.suggest"))});k.after(o)}o.data("cursor.suggest",b.cursor);o.show()}else o.remove();
if(f.suggest_new){if(!r.length){b=a('<button class="fbs-suggestnew-button">');b.text(f.suggest_new);r=a('<div class="fbs-suggestnew">').append('<div class="fbs-suggestnew-description">Your item not in the list?</div>').append(b).append('<span class="fbs-suggestnew-shortcut">(Shift+Enter)</span>').bind("click.suggest",function(a){a.stopPropagation();g.suggest_new(a)});h.append(r)}r.show()}else r.remove();if(d&&d.length&&c>0){c=d.prevAll().length*d.outerHeight();k.scrollTop();k.animate({scrollTop:c},
"slow",function(){d.trigger("mouseover.suggest")})}},suggest_new:function(){var a=this.input.val();if(a!==""){this.input.data("data.suggest",a).trigger("fb-select-new",a);this.trackEvent(this.name,"fb-select-new","index","new");this.hide_all()}},more:function(a){if(a){var c=this.input.data("original.suggest");c!==null&&this.input.val(c);this.request(this.input.val(),a);this.trackEvent(this.name,"more","cursor",a)}return false},flyout_request:function(b){var c=this,e=this.options,d=this.flyoutpane.data("data.suggest");
if(d&&b.id===d.id){if(!this.flyoutpane.is(":visible")){b=this.get_selected();this.flyout_position(b);this.flyoutpane.show();this.input.trigger("fb-flyoutpane-show",this)}}else if((d=a.suggest.flyout.cache[b.id])&&d.id&&d.html)this.flyout_response(d);else{var f=b.id,g={url:this.flyout_url.replace(/\$\{id\}/g,b.id),traditional:true,beforeSend:function(){var a=c.input.data("flyout.request.count.suggest")||0,a=a+1;c.trackEvent(c.name,"flyout.request","count",a);c.input.data("flyout.request.count.suggest",
a)},success:function(b){b["req:id"]=f;if(b.result&&b.result.length)b.html=a.suggest.suggest.create_flyout(b.result[0],c.flyout_image_url);a.suggest.flyout.cache[f]=b;c.flyout_response(b)},error:function(a){c.trackEvent(c.name,"flyout","error",{url:this.url,response:a?a.responseText:""})},complete:function(a){a&&c.trackEvent(c.name,"flyout","tid",a.getResponseHeader("X-Metaweb-TID"))},dataType:"jsonp",cache:true};if(e.flyout_lang)g.data={lang:e.flyout_lang};clearTimeout(this.flyout_request.timeout);
this.flyout_request.timeout=setTimeout(function(){a.ajax(g)},e.xhr_delay);this.input.trigger("fb-request-flyout",g)}},flyout_response:function(a){var c=this.pane,e=this.get_selected()||[];if(c.is(":visible")&&e.length)if((c=e.data("data.suggest"))&&a["req:id"]===c.id&&a.html){this.flyoutpane.html(a.html);this.flyout_position(e);this.flyoutpane.show().data("data.suggest",c);this.input.trigger("fb-flyoutpane-show",this)}},flyout_position:function(b){if(!this.options.flyout_parent){var c=this.pane,e=
this.flyoutpane,d=this.options.css,g=f,h=parseInt(e.css("top"),10),k=parseInt(e.css("left"),10),p=c.offset(),o=c.outerWidth(),r=e.outerHeight(),q=e.outerWidth();if(this.options.flyout==="bottom"){g=p;o=this.input.offset();g.top=p.top<o.top?g.top-r:g.top+c.outerHeight();e.addClass(d.flyoutpane+"-bottom")}else{g=b.offset();b=b.outerHeight();g.left=g.left+o;var s=g.left+q,c=a(document.body).scrollLeft(),m=a(window).width()+c;g.top=g.top+b-r;if(g.top<p.top)g.top=p.top;if(s>m){p=g.left-(o+q);if(p>c)g.left=
p}e.removeClass(d.flyoutpane+"-bottom")}g.top===h&&g.left===k||e.css({top:g.top,left:g.left})}},hoverout_list:function(){this.flyoutpane&&!this.get_selected()&&this.flyoutpane.hide()}});a.extend(a.suggest.suggest,{defaults:{filter:null,spell:"always",exact:false,scoring:null,lang:null,key:null,prefixed:true,stemmed:null,format:null,advanced:true,show_id:true,query_param_name:"query",service_url:"https://www.googleapis.com/freebase/v1",service_path:"/search",align:null,flyout:true,flyout_service_url:null,
flyout_service_path:"/search?filter=(all mid:${id})&output=(notable:/client/summary (description citation provenance) type)&key=${key}",flyout_image_service_url:null,flyout_image_service_path:"/image${id}?maxwidth=75&key=${key}&errorid=/freebase/no_image_png",flyout_parent:null,suggest_new:null,nomatch:{title:"No suggested matches",heading:"Tips on getting better suggestions:",tips:["Enter more or fewer characters","Add words related to your original search","Try alternate spellings","Check your spelling"]},
css:{item_type:"fbs-item-type",flyoutpane:"fbs-flyout-pane"},xhr_delay:200},get_value_by_keys:function(b,c){for(var e=a.isArray(c)?c:Array.prototype.slice.call(arguments,1),d=0;d<e.length;d++){b=b[e[d]];if(b==null)break}return b},get_value:function(b,c,e){if(b==null||c==null||c.length==0)return null;a.isArray(c)||(c=[c]);b=a.suggest.suggest.get_value_by_keys(b,c);if(e){if(b==null)return[];a.isArray(b)||(b=[b]);var d=[];a.each(b,function(b,c){if(a.type(c)==="object")if(c.name!=null)c=c.name;else if(c.id||
c.mid)c=c.id||c.mid;else if(c.value!=null){var e=[];a.each(c,function(a,b){a!=="value"&&e.push(b)});c=c.value;e.length&&(c=c+(" ("+e.join(", ")+")"))}if(a.isArray(c)&&c.length)c=c[0].value;c!=null&&d.push(c)});return d}return b==null?null:b},is_commons_id:function(a){return/^\/base\//.test(a)||/^\/user\//.test(a)?false:true},create_flyout:function(b,c){var e=a.suggest.suggest.get_value_by_keys,d=a.suggest.suggest.get_value,f=a.suggest.is_system_type,g=b.name,h=null,p=null,o=[],r=[],q={};if((h=d(b,
"notable"))&&h.name){r.push(h.name);q[h.name]=true}if(h&&f(h.id))h=b.id;else{h=b.mid;p=c.replace(/\$\{id\}/g,h)}var s=null,m=f=null,v=null,l=e(b,"output","description","/common/topic/description")||[];if(l.length){var w=l[0];a.each(l,function(a,b){if(e(b,"citation",0,"mid")=="/m/0d07ph"){w=b;return false}return true});s=a.isArray(w.value)&&w.value.length?w.value[0].value:w.value;if(e(w,"provenance",0,"restrictions",0)=="REQUIRES_CITATION"){f=e(w,"provenance",0,"source",0);if((m=e(w,"citation","provider",
0,"name"))&&a.isArray(m)&&m.length)m=m[0].value;if((v=e(w,"citation","statement",0))&&v.value)v=v.value}}else a.each(["wikipedia","freebase"],function(a,c){if((l=d(b,["output","description",c],true))&&l.length){s=l[0];m=c;return false}return true});var z=d(b,["output","notable:/client/summary"]);if(z){var u=d(z,"/common/topic/notable_paths");u&&u.length&&a.each(u,function(a,b){var c=d(z,b,true);if(c&&c.length){var c=c.slice(0,3),e=b.split("/").pop();o.push([e,c.join(", ")])}})}(u=d(b,["output","type",
"/type/object/type"],true))&&u.length&&a.each(u,function(a,b){if(!q[b]){r.push(b);q[b]=true}});var y=a('<div class="fbs-flyout-content">');g&&y.append(a('<h1 id="fbs-flyout-title">').text(g));y.append(a('<h3 class="fbs-topic-properties fbs-flyout-id">').text(h));o=o.slice(0,3);a.each(o,function(b,c){y.append(a('<h3 class="fbs-topic-properties">').append(a("<strong>").text(c[0]+": ")).append(document.createTextNode(c[1])))});if(s){g=a('<p class="fbs-topic-article">');m&&(f?g.append(a('<a class="fbs-citation">').attr("href",
f).attr("title",v||m).text("["+m+"]")):g.append(a('<em class="fbs-citation">').attr("title",v||m).text("["+m+"] ")));g.append(document.createTextNode(" "+s));y.append(g)}if(p){y.children().addClass("fbs-flyout-image-true");y.prepend(a('<img id="fbs-topic-image" class="fbs-flyout-image-true" src="'+p+'">'))}p=a('<span class="fbs-flyout-types">').text(r.slice(0,3).join(", "));p=a('<div class="fbs-attribution">').append(p);return a("<div>").append(y).append(p).html()}});document.createElement("input")})(jQuery);
(function(a){window.freebase=window.fb={mwLWTReloading:false};window.SERVER&&typeof window.SERVER==="object"&&a.extend(window.freebase,window.SERVER);a.cookie=window.freebase.cookie})(jQuery);
(function(a,f){a.ajaxSettings.traditional=true;if(!f.datelineReloading){if(!window.console)window.console={log:a.noop,info:a.noop,debug:a.noop,warn:a.noop,error:a.noop};f.dispatch=function(b,c,e,d){if(typeof c!=="function")return false;b=a.event.fix(b||window.event);e||(e=[]);d||(d=this);return c.apply(d,[b].concat(e))};f.get_script=function(b,c){var e=f.get_script.cache,d=e[b];if(d)d.state===1?d.callbacks.push(c):d.state===4&&c();else{d=e[b]={state:0,callbacks:[c]};a.ajax({url:b,dataType:"script",
cache:true,beforeSend:function(){d.state=1},success:function(){d.state=4;a.each(d.callbacks,function(a,b){b()})},error:function(a,b,c){d.state=-1;console.error("fb.get_script error",arguments)}})}};f.get_script.cache={};a(window).bind("fb.user.signedin",function(b,c){f.user=c;var e=a("#nav-username");if(e.length){a("> a",e).text(c.name);e[0].href=e[0].href+f.user.id.substring(1);var d=f.h.image_url(c.id,{maxwidth:40,maxheight:40,mode:"fillcropmid"}),d=a('<a class="user-thumb" href="'+c.id+'"><img src="'+
d+'" /></a>');e.prepend(d)}a("#signedin").show();a(".signedin").show()}).bind("fb.user.signedout",function(){a("#signedin").hide();a("#signedout").show()}).bind("fb.user.unauthorized",function(){setTimeout(function(){a.get(f.h.ajax_url("lib/template/signout.ajax"));a(window).trigger("fb.user.signedout");f.status.clear();f.status.sprintf("info","Please %s to continue.","Sign In",function(){window.location.href=a("#fb-signin-link").attr("href");return false})})}).bind("fb.user.feedback",function(a,
b){if(confirm("Uh oh! Something went wrong. Please report this using our feedback tool."))try{userfeedback.api.startFeedback({productId:"68931",disableScrolling:false},b);return false}catch(c){}});var h=a.cookie("fb-account-name");if(h){var d={id:"/user/"+h,name:h};setTimeout(function(){a(window).trigger("fb.user.signedin",d);var b=f.h.ajax_url("lib/template/refresh_credentials"),c=a("<iframe name='rc'></iframe>").attr("src",b).hide().appendTo("body").load(function(){var e=parseInt(a("body",window.rc.document).text(),
10)-(new Date).getTime();e&&e>0&&setTimeout(function(){a(c).attr("src",b)},e)})},0)}else setTimeout(function(){a(window).trigger("fb.user.signedout")},0);f.window_position=function(){var a={};if(typeof window.innerWidth=="number"){a.width=window.outerWidth;a.height=window.outerHeight;a.top=window.screenY;a.left=window.screenX}else if(document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)){a.width=document.body.clientWidth;a.height=document.body.clientHeight;
a.top=window.screenTop;a.left=window.screenLeft}return a};var g=function(){c&&c.slideUp(300);j=null;return false},e=function(e,d,f,h){if(c===null){c=a("#page-state");i=a(".status-msg",c);t=a(".close-msg",c);t.click(g)}if(j==="error")console.warn("MessagePanel: Already displaying error. Ignoring: ",e,d);else{c.hide();a.each(b,function(a,b){c.removeClass(b)});c.addClass(e);i.text(d);j=e;window.clearTimeout(n);if(h){t.show();c.slideDown(300)}else{t.hide();c.slideDown(300);n=window.setTimeout(g,f)}}return false},
b=["notice","info","warning","success","error"],c=null,i=null,t=null,n=null,j=null;f.status={doing:function(a){return e("notice",a,2E6,false)},info:function(a,b){return e("info",a,4E3,b)},warning:function(a,b){return e("warning",a,4E3,b)},success:function(a,b){return e("success",a,6E3,b)},error:function(a,b){return e("error",a,6E3,b)},sprintf:function(b,c){var d=Array.prototype.slice.call(arguments).slice(2),f=c.split("%s");if(f.length>1&&d.length>1&&d.length%2==0){for(var g=a("<span>"),h=0,m=f.length;h<
m;h++){g.append(document.createTextNode(f[h]));var j=a('<a href="#">');j.text(d.shift());var l=d.shift();a.type(l)==="function"&&j.click(l);g.append(j)}d=e(b,"",null,true);i.empty().append(g);return d}return e(b,c,null,true)},clear:function(){window.clearTimeout(n);j==="error"?console.warn("MessagePanel: Displaying error. Ignoring clearing status."):g()}};f.popup=function(a,b,c,e){var b=b||300,c=c||300,d=f.window_position(),g=Math.floor((d.width-b)/2)+d.left,d=Math.floor((d.height-c)/2)+d.top;/chrome/.test(navigator.userAgent.toLowerCase())&&
(c=c+50);var b={width:b,height:c,top:d,left:g,directories:"no",location:"no",menubar:"no",resizable:"no",scrollbars:"yes",status:"no",toolbar:"no"},c=[],h;for(h in b)c.push(h+"="+b[h]);return window.open(a,e||"",c.join())};f.login_popup=function(a){a||(a=function(){window.location.reload()});var b=f.popup("/account/signin",900,600,"Freebase");if(b.opener==null)b.opener=self;window.onsignin=a;window.focus&&b.focus();return false};f.logout_popup=function(a){a||(a=function(){window.location.reload()});
var b=f.popup("/account/signout",900,600,"Freebase");if(b.opener==null)b.opener=self;window.onsignout=a;window.focus&&b.focus();return false};a(function(){var b=a("#header > #nav-utilities > .language-picker"),c=a(".current-lang",b);a("select",b).bind("change",function(){var b=a(this).find(":selected").text();c.text(b)})});a(function(){var b=f,c=f.SEARCH_LANGS,e={};a.each((c||"en,es,fr,de,it,pt,zh,ja,ko,ru,sv,fi,da,nl,el,ro,tr,hu,th").split(","),function(b,c){e[a.trim(c)]=1});b.suggest_lang={SUPPORTED:e,
lang:function(a){a=f.h.lang_code(a||f.lang||"/lang/en");return f.suggest_lang.SUPPORTED[a]&&a!=="en"?a+",en":"en"}};var b=f,c=f.h.fb_googleapis_url(),d=f.acre.freebase.api_key,g,h=[];a.each(f.suggest_lang.lang().split(","),function(a,b){h.push("s/"+b+",d/"+b)});h.push("s/all,d/all");g=h.join(",");b.suggest_options={service_defaults:{status:["","Searching...","Select an item from the list:"],service_url:c,key:d,lang:g},filter:{operator:function(){var a=Array.prototype.slice.call(arguments),b=a.shift();
if(!(b==="any"||b==="all"||b==="should"))throw"Invalid search operator: "+b;var c=[b];if(b==="should"&&a.length>1){a=["any"].concat(a);c.push(f.suggest_options.filter.operator.apply(null,a))}else c=c.concat(a);return"("+c.join(" ")+")"},any:function(){var a=Array.prototype.slice.call(arguments);a.unshift("any");return f.suggest_options.filter.operator.apply(null,a)},all:function(){var a=Array.prototype.slice.call(arguments);a.unshift("all");return f.suggest_options.filter.operator.apply(null,a)},
should:function(){var a=Array.prototype.slice.call(arguments);a.unshift("should");return f.suggest_options.filter.operator.apply(null,a)}},any:function(){var b=a.extend({},f.suggest_options.service_defaults);b.filter=f.suggest_options.filter.any.apply(null,arguments);return b},all:function(){var b=a.extend({},f.suggest_options.service_defaults);b.filter=f.suggest_options.filter.all.apply(null,arguments);return b},should:function(){var b=a.extend({},f.suggest_options.service_defaults);b.filter=f.suggest_options.filter.should.apply(null,
arguments);return b},search:function(b){var c=a.extend({},f.suggest_options.service_defaults,{status:null,parent:"#site-search-box",align:"right",filter:["(not type:/common/document)"],soft:true,nomatch:{title:"No suggested matches",heading:"Tips on getting better suggestions:",tips:["Enter more or fewer characters","Add words related to your original search","Try alternate spellings","Check your spelling","Toggle checkbox to include non-topics"]}});b&&c.filter.push("(any type:/common/topic)");return c},
instance:function(b,c,e,d,g){var h=["type:"+b];a.each(["user","domain","type"],function(a,c){if(b==="/freebase/"+c+"_profile"){h.push("type:/type/"+c);return false}});b==="/book/book_subject"&&h.push("type:/base/skosbase/skos_concept");var i=null;if(f.h.is_metaweb_system_type(b)||d)i=f.suggest_options.any.apply(null,h);else{i=f.suggest_options.should.apply(null,h);if(c)i.suggest_new="Create new"}if(e)i.lang=f.suggest_lang.lang(e);i.filter=[i.filter,"(all namespace:/m)"];g&&i.filter.push('(not mid:"'+
g+'")');return i},cotype:function(){return a.extend({scoring:"schema"},f.suggest_options.all.apply(null,["type:/type/type","namespace:/m","(not namespace:/type)","(not namespace:/freebase)","(any (not namespace:/common) (any mid:/m/01c5 mid:/m/02_1_m4 mid:/m/03hc3d_))"]))},included_type:function(){return f.suggest_options.cotype()},expected_type:function(){return a.extend({scoring:"schema"},f.suggest_options.all.apply(null,["type:/type/type","namespace:/m"]))},delegate_property:function(){return a.extend({scoring:"schema"},
f.suggest_options.all.apply(null,["type:/type/property","(not namespace:/type/object)","namespace:/m"]))}}});a(function(){function b(){var c=a.localstore("fb-search-topic-only")!==false;e.suggest(f.suggest_options.search(c))}function c(){if(!e.data("dont_hide")&&!j.is(":visible")&&g.is(":visible")){h.hide();a("#site-search-label").slideUp("fast");d.removeClass("active")}}var e=a("#fb-search-input"),d=a("#fb-search"),g=a("#site-search-label"),h=a("#site-search-topic-option").mousedown(function(){e.data("dont_hide",
true)}).mouseup(function(){e.data("dont_hide",false)}),i=a(":checkbox",h).change(function(){var c=a(this).is(":checked");a.localstore("fb-search-topic-only",!c);b();e.focus().trigger("textchange")});a.localstore("fb-search-topic-only")===false&&i.attr("checked","checked");b();var j=a("#site-search-box .fbs-pane");e.bind("fb-select",function(b,c){var e={};a(this).siblings("input[type=hidden]").each(function(){e[this.name]=this.value});var d;d=c.id;d=d.indexOf("/en/")==0?c.mid||d:c.notable&&f.h.is_metaweb_system_type(c.notable.id)?
d:c.mid||d;window.location.href=f.h.fb_url(d,e);return false}).bind("fb-pane-show",function(){g.html("<span>Select an item from the list</span>").removeClass("loading");h.show()}).bind("fb-textchange",function(){a.trim(e.val())===""?g.html("<span>Start typing to get some suggestions</span>").removeClass("loading"):g.html("<span>Searching...</span>").addClass("loading");h.hide()}).bind("fb-error",function(){g.html("<span>Sorry, something went wrong. Please try again later</span>").removeClass("loading");
h.hide()}).focus(function(){if(!g.is(":visible")){a("#site-search-label").slideDown("fast");d.addClass("active")}}).blur(function(){setTimeout(c,0)});e.parent("form").submit(function(){i.is(":checked")||a(this).append('<input type="hidden" name="any" value="/common/topic">');return true})});f.disable=function(b){a(b).attr("disabled","disabled").addClass("disabled")};f.enable=function(b){a(b).removeAttr("disabled").removeClass("disabled")};f.lang_select=function(b,c){if(c==="/lang/en"){a(this).removeAttr("name");
if(!a(":input[name]",this.form).length){window.location=a(this.form).attr("action");return}}this.form.submit()};f.devbar={div:a("#devbar"),touch:function(){/\.(freebase|sandbox\-freebase)\.com$/.test(f.acre.request.server_name)?a.ajax({url:f.acre.freebase.googleapis_url?f.h.fb_googleapis_url("/touch"):f.h.fb_api_url("/api/service/touch"),dataType:"jsonp"}):a.ajax({url:"/acre/touch"});return false},txn_ids:[],txn:function(){return f.devbar.view_txn(this.href,f.devbar.txn_ids)},view_txn:function(b,
c){if(c&&c.length)window.location=b+"?"+a.param({tid:c},true);return false},ajaxComplete:function(a){if(a&&a.readyState===4)(a=a.getResponseHeader("x-metaweb-tid"))&&f.devbar.txn_ids.push(a)},init:function(){$nav_user_controls=a(".nav-user-controls");$user_controls=a("#user-controls");a("#signedin .trigger").click(function(){if($user_controls.is(":hidden")){$user_controls.fadeIn();$nav_user_controls.addClass("active")}else{$user_controls.fadeOut();$nav_user_controls.removeClass("active")}return false});
a("html").click(function(){if($user_controls.is(":visible")){$user_controls.fadeOut();$nav_user_controls.removeClass("active")}});$user_controls.click(function(a){a.stopPropagation()});a("#devbar-touch > a").click(f.devbar.touch);f.tid&&f.devbar.txn_ids.push(f.tid);a("#devbar-txn > a").click(f.devbar.txn);a(document).ajaxComplete(function(){f.devbar.ajaxComplete.apply(null,arguments)});a(document).ajaxError(function(b,c,e){var d={};a.each(["url","data","dataType","type"],function(a,b){d[b]=e[b]});
a.each(["status","statusText","responseText"],function(a,b){d[b]=c[b]});d.responseHeaders=c.getAllResponseHeaders();if(d.status!==200){var b=d.url.match(/^.*[^\/]\/([a-z_]*)\.ajax.*$/)[1],f=d.status===401?"User Error":"Site Error";(window._gaq||[]).push(["_trackEvent",f,"AJAX Error "+(b||""),"path:"+d.url+";status:"+d.status+";status-text:"+d.statusText,1])}})}};f.devbar.init();f.mqlread=function(b,c,e){var d;if(f.acre.freebase.googleapis_url){d=f.h.fb_googleapis_url("/mqlread");b={query:JSON.stringify(b),
key:f.acre.freebase.api_key}}else{d=f.h.fb_api_url("/api/service/mqlread");b={query:JSON.stringify({query:b})}}return a.ajax({url:d,data:b,dataType:"jsonp",success:function(a){c&&c.apply(this,[a.result])},error:function(){e&&e.apply(this,arguments)}})};f.touch_and_reload=function(){a.ajax({url:"/acre/touch"}).done(function(){window.location.reload(true)});return false};a(function(){var b=f,c=a("#fb-topic-hover-pane").hover(function(){clearTimeout(f.hover.hide_timer_)},function(){f.hover.hide_now_()});
b.hover={pane:c,current_target:null,cache:{},search_url:f.h.fb_googleapis_url()+"/search?filter=(all mid:${id})&output=(notable:/client/summary (description citation provenance) type)&key="+f.acre.freebase.api_key+"&lang="+f.suggest_lang.lang(),image_url:f.h.fb_googleapis_url()+"/image${id}?maxwidth=75&errorid=/freebase/no_image_png&key="+f.acre.freebase.api_key,show:function(b){clearTimeout(f.hover.hide_timer_);var c=b.target,e=a(c).attr("data-id");if(e){f.hover.current_target=c;a(c).removeAttr("title");
f.hover.cache[e]?f.hover.show_now_(c,f.hover.cache[e]):a.ajax({url:f.hover.search_url.replace(/\$\{id\}/g,e),success:function(b){if(b.result&&b.result.length){b=a.suggest.suggest.create_flyout(b.result[0],f.hover.image_url);f.hover.cache[e]=b;f.hover.show_now_(c,b)}},dataType:"jsonp",cache:true})}},show_now_:function(b,c){if(b===f.hover.current_target){f.hover.pane.html(c);var e=f.hover.pane.height(),d=a(b).height(),g=a(b).offset(),h=g.left,g=g.top,g=g-a(document).scrollTop()+e<a(window).height()?
g+d:g-e-d;f.hover.pane.css({top:g,left:h}).show()}},hide:function(){f.hover.hide_timer_=setTimeout(f.hover.hide_now_,100)},hide_now_:function(){f.hover.current_target=null;f.hover.pane.hide()}};f.keyboard_shortcut={cache_:{},add:function(a,b,c){var e=a.charCodeAt(0);!c&&e in f.keyboard_shortcut.cache_&&console.warn("Overriding keyboard shortcut",a);f.keyboard_shortcut.cache_[e]=b}};f.on_mid_dblclick=function(a){a=a.target;if(document.body.createTextRange){var b=document.body.createTextRange();b.moveToElementText(a);
b.select()}else if(window.getSelection){var c=window.getSelection(),b=document.createRange();b.selectNodeContents(a);c.removeAllRanges();c.addRange(b)}};a(document).keypress(function(b){if(b.altKey||b.ctrlKey||b.metaKey||b.shiftKey)return true;var c=b.charCode,b=b.target;if(f.keyboard_shortcut.cache_[c]&&(b==document.body||b==document||b==window||b==a("html")[0])){f.keyboard_shortcut.cache_[c]();return false}return true});a("#page-content").on("mouseenter","a.property-value",f.hover.show).on("mouseleave",
"a.property-value",f.hover.hide);a(document.body).on("dblclick",".mid",f.on_mid_dblclick).on("click",".mid",f.on_mid_dblclick)})}})(jQuery,window.freebase);
(function(a,f){var h;if(!(h=a.type)){var d={};["Boolean","Number","String","Function","Array","Date","RegExp","Object"].forEach(function(a){d["[object "+a+"]"]=a.toLowerCase()});h=function(a){return a==null?String(a):d[Object.prototype.toString.call(a)]||"object"}}var g=f.h={type:h,parse_params:function(e){if(a.isArray(e)){var b={};a.each(e,function(a,e){b[e[0]]=e[1]});return b}return e},build_url:function(e){if(e&&e.indexOf("//")!==0&&e.indexOf("://")===-1)throw"Host must contain scheme: "+e;var b=
e||"",c,d;if(arguments.length>1){c=Array.prototype.slice.call(arguments);c.shift();for(var f=[],h=0,j=c.length;h<j;h++){var k=c[h];if(g.type(k)==="string")f.push(k);else{for(d={};h<j;h++)d=a.extend(d,g.parse_params(c[h]));break}}c=f.join("")}if(c&&c.indexOf("/")!==0)throw"Path must begin with a '/': "+c;c&&(b=b+c);b===""&&(b="/");a.isEmptyObject(d)||(b=b+("?"+a.param(d,true)));return b},fb_url:function(){var a=Array.prototype.slice.call(arguments);a.unshift(null);f.lang&&f.lang!=="/lang/en"&&a.push({lang:g.lang_code(f.lang)});
return g.build_url.apply(null,a)},ajax_url:function(){var a=Array.prototype.slice.call(arguments);a.unshift("/ajax");return g.reentrant_url.apply(null,a)},static_url:function(){var a=Array.prototype.slice.call(arguments);a.unshift("/static");return g.reentrant_url.apply(null,a)},reentrant_url:function(a,b){var b=g.resolve_reentrant_path(b),b=b.replace(/^\/\//,a+"/"),c=Array.prototype.slice.call(arguments,2);c.unshift(b);c.unshift(null);return g.build_url.apply(null,c)},resolve_reentrant_path:function(a){a=
a||"";if(a.indexOf("//")==0)return a;if(a.indexOf("lib/")===0)return f.acre.current_script.app.path+a.substring(3);a&&a[0]!="/"&&(a="/"+a);return f.acre.request.script.app.path+a},legacy_fb_url:function(){var a=Array.prototype.slice.call(arguments),b=f.acre.freebase.site_host.replace(/^(https?\:\/\/)([^\.]+)\./,"$1www.").replace(":"+f.acre.request.server_port,"");a.unshift(b);return g.build_url.apply(null,a)},fb_api_url:function(){var a=Array.prototype.slice.call(arguments);a.unshift(f.acre.freebase.service_url);
return g.build_url.apply(null,a)},fb_googleapis_url:function(){if(f.acre.freebase.googleapis_url){var a=Array.prototype.slice.call(arguments);a.unshift(f.acre.freebase.googleapis_url);return g.build_url.apply(null,a)}throw"fb.acre.freebase.googleapis_url is not defined";},wiki_url:function(a){var b=Array.prototype.slice.call(arguments);b.unshift("http://wiki.freebase.com","/wiki/");return g.build_url.apply(null,b)},lib_base_url:function(a){a=f.acre.metadata.libs[a];return a.base_url+a.version},image_url:function(a,
b){return f.acre.freebase.imgurl(a,b.maxwidth,b.maxheight,b.mode,b.pad,b.errorid)},is_metaweb_system_type:function(a){return a.indexOf("/type/")===0||a.indexOf("/common/")===0&&a!=="/common/topic"||a.indexOf("/freebase/")===0&&a.indexOf("_profile")===a.length-8},id_key:function(a,b){var c=a.split("/"),d=c.pop();if(b){c=c.join("/");c===""&&(c="/");return[c,d]}return d},get_value_by_keys:function(d,b){for(var c=a.isArray(b),g=c?b:arguments,c=c?0:1;c<g.length;c++){d=d[g[c]];if(d===void 0)break}return d},
lang_code:function(a){return g.id_key(a)},lang_id:function(a){return"/lang/"+g.lang_code(a)}}})(jQuery,window.freebase);
(function(a,f){var h=f.permission={init:function(){if(f.access=="readonly"){a(".edit").hide();a(".no-edit").show()}else if(f.user){var d=f.c;d&&d.id&&a.ajax({url:f.h.ajax_url("lib/permission/has_permission.ajax"),data:{id:d.id,user_id:f.user.id},dataType:"json",success:function(g){h.has_permission=g.result&&g.result[d.id]===true;a(window).trigger("fb.permission.has_permission",h.has_permission)}});check_permissioned_objects(a(".edit-perm"),f.user.id)}else setTimeout(function(){h.has_permission=false;
a(window).trigger("fb.permission.has_permission",h.has_permission)})}};a(window).bind("fb.user.signedin",h.init);a(window).bind("fb.user.signedout",h.init);a(window).bind("fb.permission.has_permission",function(d,g){g?a(".edit").show():a(".no-edit").show()})})(jQuery,window.freebase);
function check_permissioned_objects(a,f){if(a.length&&f){var h={},d=[];$.each(a,function(){var a=$(this).metadata().id;if(a&&!h[a]){d.push(a);h[a]=1}});d.length&&$.ajax({url:fb.h.ajax_url("lib/permission/has_permission.ajax"),data:{id:d,user_id:f},traditional:true,dataType:"json",success:function(d){var e=d.result||{};$.each(a,function(){var a=$(this).metadata().id;a&&e[a]===true?$(this).show():$(this).addClass("edit-perm-lock")})}})}}
(function(a,f){var h=f.incompatible_types={overlay_dialog:null,inline_dialog:null,suggest_options:function(d,f,e){var e=e||{},f=[d].concat(f||[]),b=e.filter;if(!a.isArray(b)){b=[];b!=null&&b.push(e.filter);e.filter=b}b.push("(should (not incompatible:"+d+"))");e.filter=b;if(d=e.output)(b=/^\((.*)\)$/.exec(e.output))&&(d="("+h.search_output_(f)+" "+b[1]+")");d||(d=h.search_output_(f,true));e.output=d;return e},search_output_:function(a,f){var e=a.map(function(a){return"incompatible:"+a}).join(" ");
f&&(e="("+e+")");return e},check:function(d,f,e,b){var b=b||{},c=false,h=d.output;if(h){var t=[f].concat(e||[]);a.each(t,function(a,b){var d="incompatible:"+b;if(h[d]["/type/object/type"][0]==="true"||h[d]["/type/object/type"][0]===true)c=true;return!c})}c?b.incompatible&&b.incompatible(d,f,e):b.compatible&&b.compatible(d,f,e)},search:function(d,g,e,b){var c=[g].concat(e||[]),c={filter:"(all mid:"+d+")",output:h.search_output_(c,true),key:f.acre.freebase.api_key};a.ajax({url:f.h.fb_googleapis_url("/search",
c),dataType:"jsonp",success:function(c){a.isArray(c.result)&&c.result.length>0?h.check(c.result[0],g,e,b):b.compatible&&b.compatible({id:d},g,e)}})},overlay_incompatible_callback:function(d,f){if(!h.overlay_dialog)h.overlay_dialog=a(".incompatible-overlay-dialog");if(h.overlay_dialog.length){d=d||{};return function(e,b,c){h.overlay_dialog.removeData("overlay");a(".modal-content",h.overlay_dialog).empty().append(h.description_html(e,b,c));h.overlay_dialog.overlay({close:"button",closeOnClick:false,
load:true,fixed:false,mask:{color:"#000",loadSpeed:200,opacity:0.5},onClose:function(){f&&f.focus().select();a("button",h.overlay_dialog).unbind();if(d.onClose)d.onClose()},onLoad:function(){a(".cancel",h.overlay_dialog).focus().click(function(){f&&f.focus().select().trigger("textchange");if(d.onCancel)d.onCancel()});a(".save",h.overlay_dialog).click(function(){f&&f.focus().select();if(d.onConfirm)d.onConfirm(e,b,c)});if(d.onLoad)d.onLoad()}})}}return h.native_confirm_incompatible_callback(d,f)},
inline_incompatible_callback:function(d,f){if(!h.inline_dialog)h.inline_dialog=a(".incompatible-inline-dialog");if(h.inline_dialog.length){d=d||{};return function(e,b,c){a(".modal-content",h.inline_dialog).empty().append(h.description_html(e,b,c));a(".save",h.inline_dialog).unbind().click(function(){f.focus().select();if(d.onConfirm)d.onConfirm(e,b,c);h.inline_dialog.hide(d.onClose)});a(".cancel",h.inline_dialog).unbind().click(function(){f.focus().select().trigger("textchange");if(d.onCancel)d.onCancel();
h.inline_dialog.hide(d.onClose)});var i=f.offsetParent(),t=f.position();i.append(h.inline_dialog);h.inline_dialog.css({top:t.top+f.outerHeight(),left:t.left});h.inline_dialog.show(d.onLoad)}}return h.native_confirm_incompatible_callback(d,f)},native_confirm_incompatible_callback:function(a,f){a=a||{};return function(e,b,c){if(confirm(h.description_text(e,b,c))){f&&f.focus().select();if(a.onConfirm)a.onConfirm(e,b,c)}else{f&&f.focus().select().trigger("textchange");if(a.onCancel)a.onCancel()}if(a.onClose)a.onClose();
f&&f.focus().select()}},description_html:function(d,f){var e=a("<p>"),b;b=a('<div><b class="incompatible-topic"></b> is incompatible with <b class="incompatible-type"></b>.</div>');a(".incompatible-topic",b).text(d.name||d.id);a(".incompatible-type",b).text(f);e.append(b);b=a('<div>If you continue, <b class="incompatible-topic"></b> will be typed as <b class="incompatible-type"></b> and its included types (if any).</div>');a(".incompatible-topic",b).text(d.name||d.id);a(".incompatible-type",b).text(f);
e.append(b);e.append("<p>Are you sure you want to continue?<p>");return e},description_text:function(a,f,e){return h.description_html(a,f,e).text()}}})(jQuery,window.freebase);
(function(a,f){var h=f.flag={merge:function(a){return h.flag(a,"merge_begin")},split:function(a){return h.flag(a,"split_begin")},"delete":function(a){return h.flag(a,"delete_begin")},offensive:function(a){return h.flag(a,"offensive_begin")},flag:function(d,g){d=a(d);f.get_script(f.h.static_url("lib/flag/flag-edit.mf.js"),function(){h.edit[g](d)});return false},undo:function(d,g){d=a(d);f.get_script(f.h.static_url("lib/flag/flag-edit.mf.js"),function(){h.edit.undo_begin(d,g)});return false}}})(jQuery,
window.freebase);
(function(a){function f(){d();a(this).parents(".headmenu").data("submenu").find("a:first").click();return false}function h(f,e){var b=a(this),c=b.data("menu"),h=b.data("submenu");c.addClass("active");if(!h.is(".submenu-valid")){var c=b.offset(),t=b.outerHeight(),t=c.top+t;if(h.is(".center")){b=b.outerWidth();b=c.left+b/2-h.outerWidth()/2}else if(h.is(".right")){b=b.outerWidth();b=c.left+b-h.outerWidth()}else b=c.left;b={display:"none",position:"absolute",top:t,left:b};e.overlay&&(b.zIndex=e.overlay.css("zIndex"));
h.css(b);a(document.body).append(h);h.addClass(".submenu-valid")}if(h.is(":visible"))d(h);else{d();h.fadeIn()}return false}function d(d){d=d||a(".submenu:visible");d.data("menu")&&d.data("menu").removeClass("active");d.hide()}a.factory("nicemenu",{init:function(){var g=this.options;a(".headmenu",this.element).each(function(){var d=a(this),b=d.next(".submenu"),c=d.parents(".nicemenu");d.data("submenu",b);d.data("menu",c);b.data("headmenu",d);b.data("menu",c);a(".default-action",d).click(f);d.click(function(a){return h.apply(this,
[a,g])})});a(".submenu",this.element).click(function(){d(a(this));a(this).fadeOut()})}});a(document).click(function(){d()})})(jQuery);
(function(a,f){function h(c){if(!e.is(":visible")){b.hide();e.show()}c&&a(window).unbind("scroll resize",g);return false}function d(c){if(!b.is(":visible")){e.hide();b.show()}c&&a(window).unbind("scroll resize",g);return false}function g(){a(document.body).scrollTop()<40?d():h()}a(function(){a(".nicemenu").nicemenu();a(window).bind("fb.permission.has_permission",function(b,c){var d=".nav-utilities > li > .submenu > li:not(.no-settings)";c||(d=d+":not(.edit)");a(d).length||a("li.no-settings").show()});
a("#description").css("height","auto");var b=a("#page-header .creation-timestamp").width();a("#page-header h1").css("margin-right",b);b=a("#less-blurb");if(b.length){b.click(h);a("#more-blurb").click(d)}f.init_search()});f.nav_get_script=function(b,d,e){a.ajax({url:b.href,dataType:"script",beforeSend:function(){f.status.doing("Loading...")},success:function(){f.status.clear();if(d){var b=d.split(".");if(b.length){var c=f;b.every(function(a){if(c[a]){c=c[a];return true}c=null;return false});a.isFunction(c)&&
a.isArray(e)&&c.apply(null,e)}}},error:function(){f.status.error("Error retrieving script")}});return false};f.init_search=function(){var b=a("#header #fb-search-input");f.keyboard_shortcut.add("/",function(){b.focus()});b.keydown(function(a){a.keyCode===27&&b.blur()})};var e=null,b=null;a(function(){e=a("#min-blurb");b=a("#max-blurb")})})(jQuery,window.freebase);
