
/*
 * Copyright 2012, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Additional Licenses for Third Party components can be found here:
 * http://wiki.freebase.com/wiki/Freebase_Site_License
 *
 */
(function(a,b){var h,f,g,d,c,e,i,k,l,n,j,o,p,t,m,r,s,u,q,v,y,A,C,z;h=function(a){return new h.prototype.init(a)};"undefined"!==typeof require&&"undefined"!==typeof exports&&"undefined"!==typeof module?module.exports=h:a.Globalize=h;h.cultures={};h.prototype={constructor:h,init:function(a){this.cultures=h.cultures;this.cultureSelector=a;return this}};h.prototype.init.prototype=h.prototype;h.cultures["default"]={name:"en",englishName:"English",nativeName:"English",isRTL:!1,language:"en",numberFormat:{pattern:["-n"],
decimals:2,",":",",".":".",groupSizes:[3],"+":"+","-":"-",NaN:"NaN",negativeInfinity:"-Infinity",positiveInfinity:"Infinity",percent:{pattern:["-n %","n %"],decimals:2,groupSizes:[3],",":",",".":".",symbol:"%"},currency:{pattern:["($n)","$n"],decimals:2,groupSizes:[3],",":",",".":".",symbol:"$"}},calendars:{standard:{name:"Gregorian_USEnglish","/":"/",":":":",firstDay:0,days:{names:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),namesAbbr:"Sun Mon Tue Wed Thu Fri Sat".split(" "),
namesShort:"Su Mo Tu We Th Fr Sa".split(" ")},months:{names:"January February March April May June July August September October November December ".split(" "),namesAbbr:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec ".split(" ")},AM:["AM","am","AM"],PM:["PM","pm","PM"],eras:[{name:"A.D.",start:null,offset:0}],twoDigitYearMax:2029,patterns:{d:"M/d/yyyy",D:"dddd, MMMM dd, yyyy",t:"h:mm tt",T:"h:mm:ss tt",f:"dddd, MMMM dd, yyyy h:mm tt",F:"dddd, MMMM dd, yyyy h:mm:ss tt",M:"MMMM dd",Y:"yyyy MMMM",
S:"yyyy'-'MM'-'dd'T'HH':'mm':'ss"}}},messages:{}};h.cultures["default"].calendar=h.cultures["default"].calendars.standard;h.cultures.en=h.cultures["default"];h.cultureSelector="en";f=/^0x[a-f0-9]+$/i;g=/^[+\-]?infinity$/i;d=/^[+\-]?\d*\.?\d*(e[+\-]?\d+)?$/;c=/^\s+|\s+$/g;e=function(a,c){if(a.indexOf)return a.indexOf(c);for(var e=0,d=a.length;e<d;e++)if(a[e]===c)return e;return-1};i=function(a,c){return a.substr(a.length-c.length)===c};k=function(){var a,c,e,d,g,i=arguments[0]||{},f=1,h=arguments.length,
o=!1;"boolean"===typeof i&&(o=i,i=arguments[1]||{},f=2);for("object"!==typeof i&&!n(i)&&(i={});f<h;f++)if(null!=(a=arguments[f]))for(c in a)e=i[c],d=a[c],i!==d&&(o&&d&&(j(d)||(g=l(d)))?(g?(g=!1,e=e&&l(e)?e:[]):e=e&&j(e)?e:{},i[c]=k(o,e,d)):d!==b&&(i[c]=d));return i};l=Array.isArray||function(a){return"[object Array]"===Object.prototype.toString.call(a)};n=function(a){return"[object Function]"===Object.prototype.toString.call(a)};j=function(a){return"[object Object]"===Object.prototype.toString.call(a)};
o=function(a,c){return 0===a.indexOf(c)};p=function(a){return(a+"").replace(c,"")};t=function(a){return isNaN(a)?NaN:Math[0>a?"ceil":"floor"](a)};m=function(a,c,e){var d;for(d=a.length;d<c;d+=1)a=e?"0"+a:a+"0";return a};r=function(a,c){for(var e=0,d=!1,b=0,g=a.length;b<g;b++){var i=a.charAt(b);switch(i){case "'":d?c.push("'"):e++;d=!1;break;case "\\":d&&c.push("\\");d=!d;break;default:c.push(i),d=!1}}return e};s=function(a,c){var c=c||"F",e;e=a.patterns;var d=c.length;if(1===d){e=e[c];if(!e)throw"Invalid date format string '"+
c+"'.";c=e}else 2===d&&"%"===c.charAt(0)&&(c=c.charAt(1));return c};u=function(a,c,e){function d(a,c){var e;e=a+"";return 1<c&&e.length<c?(e=o[c-2]+e,e.substr(e.length-c,c)):e}function b(){if(h||n)return h;h=p.test(c);n=!0;return h}function g(a,c){if(q)return q[c];switch(c){case 0:return a.getFullYear();case 1:return a.getMonth();case 2:return a.getDate();default:throw"Invalid part value "+c;}}var i=e.calendar,f=i.convert;if(!c||!c.length||"i"===c){if(e&&e.name.length)if(f)e=u(a,i.patterns.F,e);else{var e=
new Date(a.getTime()),j=y(a,i.eras);e.setFullYear(A(a,i,j));e=e.toLocaleString()}else e=a.toString();return e}var j=i.eras,l="s"===c,c=s(i,c),e=[],k,o=["0","00","000"],h,n,p=/([^d]|^)(d|dd)([^d]|$)/g,m=0,t=v(),q;for(!l&&f&&(q=f.fromGregorian(a));;){k=t.lastIndex;f=t.exec(c);k=c.slice(k,f?f.index:c.length);m+=r(k,e);if(!f)break;if(m%2)e.push(f[0]);else switch(k=f[0],f=k.length,k){case "ddd":case "dddd":e.push((3===f?i.days.namesAbbr:i.days.names)[a.getDay()]);break;case "d":case "dd":h=!0;e.push(d(g(a,
2),f));break;case "MMM":case "MMMM":k=g(a,1);e.push(i.monthsGenitive&&b()?i.monthsGenitive[3===f?"namesAbbr":"names"][k]:i.months[3===f?"namesAbbr":"names"][k]);break;case "M":case "MM":e.push(d(g(a,1)+1,f));break;case "y":case "yy":case "yyyy":k=q?q[0]:A(a,i,y(a,j),l);4>f&&(k%=100);e.push(d(k,f));break;case "h":case "hh":k=a.getHours()%12;0===k&&(k=12);e.push(d(k,f));break;case "H":case "HH":e.push(d(a.getHours(),f));break;case "m":case "mm":e.push(d(a.getMinutes(),f));break;case "s":case "ss":e.push(d(a.getSeconds(),
f));break;case "t":case "tt":k=12>a.getHours()?i.AM?i.AM[0]:" ":i.PM?i.PM[0]:" ";e.push(1===f?k.charAt(0):k);break;case "f":case "ff":case "fff":e.push(d(a.getMilliseconds(),3).substr(0,f));break;case "z":case "zz":k=a.getTimezoneOffset()/60;e.push((0>=k?"+":"-")+d(Math.floor(Math.abs(k)),f));break;case "zzz":k=a.getTimezoneOffset()/60;e.push((0>=k?"+":"-")+d(Math.floor(Math.abs(k)),2)+":"+d(Math.abs(a.getTimezoneOffset()%60),2));break;case "g":case "gg":i.eras&&e.push(i.eras[y(a,j)].name);break;
case "/":e.push(i["/"]);break;default:throw"Invalid date format pattern '"+k+"'.";}}return e.join("")};var D;D=function(a,c,e){var d=e.groupSizes,b=d[0],i=1,f=Math.pow(10,c),g=Math.round(a*f)/f;isFinite(g)||(g=a);f="";f=(g+"").split(/e/i);g=1<f.length?parseInt(f[1],10):0;a=f[0];f=a.split(".");a=f[0];f=1<f.length?f[1]:"";0<g?(f=m(f,g,!1),a+=f.slice(0,g),f=f.substr(g)):0>g&&(g=-g,a=m(a,g+1,!0),f=a.slice(-g,a.length)+f,a=a.slice(0,-g));f=0<c?e["."]+(f.length>c?f.slice(0,c):m(f,c)):"";c=a.length-1;e=
e[","];for(g="";0<=c;){if(0===b||b>c)return a.slice(0,c+1)+(g.length?e+g+f:f);g=a.slice(c-b+1,c+1)+(g.length?e+g:"");c-=b;i<d.length&&(b=d[i],i++)}return a.slice(0,c+1)+e+g+f};q=function(a,c,e){if(!isFinite(a))return Infinity===a?e.numberFormat.positiveInfinity:-Infinity===a?e.numberFormat.negativeInfinity:e.numberFormat.NaN;if(!c||"i"===c)return e.name.length?a.toLocaleString():a.toString();var c=c||"D",e=e.numberFormat,d=Math.abs(a),f=-1;1<c.length&&(f=parseInt(c.slice(1),10));var g=c.charAt(0).toUpperCase(),
b;switch(g){case "D":c="n";d=t(d);-1!==f&&(d=m(""+d,f,!0));0>a&&(d="-"+d);break;case "N":b=e;case "C":b=b||e.currency;case "P":b=b||e.percent;c=0>a?b.pattern[0]:b.pattern[1]||"n";-1===f&&(f=b.decimals);d=D(d*("P"===g?100:1),f,b);break;default:throw"Bad number format specifier: "+g;}a=/n|\$|-|%/g;for(b="";;){f=a.lastIndex;g=a.exec(c);b+=c.slice(f,g?g.index:c.length);if(!g)break;switch(g[0]){case "n":b+=d;break;case "$":b+=e.currency.symbol;break;case "-":/[1-9]/.test(d)&&(b+=e["-"]);break;case "%":b+=
e.percent.symbol}}return b};v=function(){return/\/|dddd|ddd|dd|d|MMMM|MMM|MM|M|yyyy|yy|y|hh|h|HH|H|mm|m|ss|s|tt|t|fff|ff|f|zzz|zz|z|gg|g/g};y=function(a,c){if(!c)return 0;for(var e,d=a.getTime(),b=0,f=c.length;b<f;b++)if(e=c[b].start,null===e||d>=e)return b;return 0};A=function(a,c,e,d){a=a.getFullYear();!d&&c.eras&&(a-=c.eras[e].offset);return a};var E,F,G,H,w,B,x;E=function(a,c){if(100>c){var e=new Date,d=y(e),e=A(e,a,d),d=a.twoDigitYearMax,d="string"===typeof d?(new Date).getFullYear()%100+parseInt(d,
10):d,c=c+(e-e%100);c>d&&(c-=100)}return c};F=function(a,c,d){var b=a.days,f=a._upperDays;f||(a._upperDays=f=[x(b.names),x(b.namesAbbr),x(b.namesShort)]);c=B(c);d?(a=e(f[1],c),-1===a&&(a=e(f[2],c))):a=e(f[0],c);return a};G=function(a,c,d){var b=a.months,f=a.monthsGenitive||a.months,g=a._upperMonths,i=a._upperMonthsGen;g||(a._upperMonths=g=[x(b.names),x(b.namesAbbr)],a._upperMonthsGen=i=[x(f.names),x(f.namesAbbr)]);c=B(c);a=e(d?g[1]:g[0],c);0>a&&(a=e(d?i[1]:i[0],c));return a};H=function(a,c){var e=
a._parseRegExp;if(e){var d=e[c];if(d)return d}else a._parseRegExp=e={};for(var d=s(a,c).replace(/([\^\$\.\*\+\?\|\[\]\(\)\{\}])/g,"\\\\$1"),b=["^"],f=[],g=0,i=0,j=v(),k;null!==(k=j.exec(d));){var l=d.slice(g,k.index),g=j.lastIndex,i=i+r(l,b);if(i%2)b.push(k[0]);else{var l=k[0],h=l.length;switch(l){case "dddd":case "ddd":case "MMMM":case "MMM":case "gg":case "g":l="(\\D+)";break;case "tt":case "t":l="(\\D*)";break;case "yyyy":case "fff":case "ff":case "f":l="(\\d{"+h+"})";break;case "dd":case "d":case "MM":case "M":case "yy":case "y":case "HH":case "H":case "hh":case "h":case "mm":case "m":case "ss":case "s":l=
"(\\d\\d?)";break;case "zzz":l="([+-]?\\d\\d?:\\d{2})";break;case "zz":case "z":l="([+-]?\\d\\d?)";break;case "/":l="(\\/)";break;default:throw"Invalid date format pattern '"+l+"'.";}l&&b.push(l);f.push(k[0])}}r(d.slice(g),b);b.push("$");d={regExp:b.join("").replace(/\s+/g,"\\s+"),groups:f};return e[c]=d};w=function(a,c,e){return a<c||a>e};B=function(a){return a.split("\u00a0").join(" ").toUpperCase()};x=function(a){for(var c=[],e=0,d=a.length;e<d;e++)c[e]=B(a[e]);return c};C=function(a,c,e){var a=
p(a),e=e.calendar,c=H(e,c),d=RegExp(c.regExp).exec(a);if(null===d)return null;var b=c.groups,f=c=a=null,g=null,i=null,j=0,k,l=0,h=0,n=0;k=null;for(var r=!1,m=0,t=b.length;m<t;m++){var s=d[m+1];if(s){var q=b[m],u=q.length,v=parseInt(s,10);switch(q){case "dd":case "d":g=v;if(w(g,1,31))return null;break;case "MMM":case "MMMM":f=G(e,s,3===u);if(w(f,0,11))return null;break;case "M":case "MM":f=v-1;if(w(f,0,11))return null;break;case "y":case "yy":case "yyyy":c=4>u?E(e,v):v;if(w(c,0,9999))return null;break;
case "h":case "hh":j=v;12===j&&(j=0);if(w(j,0,11))return null;break;case "H":case "HH":j=v;if(w(j,0,23))return null;break;case "m":case "mm":l=v;if(w(l,0,59))return null;break;case "s":case "ss":h=v;if(w(h,0,59))return null;break;case "tt":case "t":r=e.PM&&(s===e.PM[0]||s===e.PM[1]||s===e.PM[2]);if(!r&&(!e.AM||s!==e.AM[0]&&s!==e.AM[1]&&s!==e.AM[2]))return null;break;case "f":case "ff":case "fff":n=v*Math.pow(10,3-u);if(w(n,0,999))return null;break;case "ddd":case "dddd":i=F(e,s,3===u);if(w(i,0,6))return null;
break;case "zzz":q=s.split(/:/);if(2!==q.length)return null;k=parseInt(q[0],10);if(w(k,-12,13))return null;q=parseInt(q[1],10);if(w(q,0,59))return null;k=60*k+(o(s,"-")?-q:q);break;case "z":case "zz":k=v;if(w(k,-12,13))return null;k*=60;break;case "g":case "gg":if(!s||!e.eras)return null;s=p(s.toLowerCase());q=0;for(u=e.eras.length;q<u;q++)if(s===e.eras[q].name.toLowerCase()){a=q;break}if(null===a)return null}}}d=new Date;b=(m=e.convert)?m.fromGregorian(d)[0]:d.getFullYear();null===c?c=b:e.eras&&
(c+=e.eras[a||0].offset);null===f&&(f=0);null===g&&(g=1);if(m){if(d=m.toGregorian(c,f,g),null===d)return null}else if(d.setFullYear(c,f,g),d.getDate()!==g||null!==i&&d.getDay()!==i)return null;r&&12>j&&(j+=12);d.setHours(j,l,h,n);null!==k&&(e=d.getMinutes()-(k+d.getTimezoneOffset()),d.setHours(d.getHours()+parseInt(e/60,10),e%60));return d};z=function(a,c,e){var d=c["-"],c=c["+"],b;switch(e){case "n -":d=" "+d,c=" "+c;case "n-":i(a,d)?b=["-",a.substr(0,a.length-d.length)]:i(a,c)&&(b=["+",a.substr(0,
a.length-c.length)]);break;case "- n":d+=" ",c+=" ";case "-n":o(a,d)?b=["-",a.substr(d.length)]:o(a,c)&&(b=["+",a.substr(c.length)]);break;case "(n)":o(a,"(")&&i(a,")")&&(b=["-",a.substr(1,a.length-2)])}return b||["",a]};h.prototype.findClosestCulture=function(a){return h.findClosestCulture.call(this,a)};h.prototype.format=function(a,c,e){return h.format.call(this,a,c,e)};h.prototype.localize=function(a,c){return h.localize.call(this,a,c)};h.prototype.parseInt=function(a,c,e){return h.parseInt.call(this,
a,c,e)};h.prototype.parseFloat=function(a,c,e){return h.parseFloat.call(this,a,c,e)};h.prototype.culture=function(a){return h.culture.call(this,a)};h.addCultureInfo=function(a,c,e){var d={},b=!1;"string"!==typeof a?(e=a,a=this.culture().name,d=this.cultures[a]):"string"!==typeof c?(e=c,b=null==this.cultures[a],d=this.cultures[a]||this.cultures["default"]):(b=!0,d=this.cultures[c]);this.cultures[a]=k(!0,{},d,e);b&&(this.cultures[a].calendar=this.cultures[a].calendars.standard)};h.findClosestCulture=
function(a){var c;if(!a)return this.findClosestCulture(this.cultureSelector)||this.cultures["default"];"string"===typeof a&&(a=a.split(","));if(l(a)){var e,d=this.cultures,b=a,f,g=b.length,i=[];for(f=0;f<g;f++)a=p(b[f]),a=a.split(";"),e=p(a[0]),1===a.length?a=1:(a=p(a[1]),0===a.indexOf("q=")?(a=a.substr(2),a=parseFloat(a),a=isNaN(a)?0:a):a=1),i.push({lang:e,pri:a});i.sort(function(a,c){return a.pri<c.pri?1:a.pri>c.pri?-1:0});for(f=0;f<g;f++)if(e=i[f].lang,c=d[e])return c;for(f=0;f<g;f++){e=i[f].lang;
do{b=e.lastIndexOf("-");if(-1===b)break;e=e.substr(0,b);if(c=d[e])return c}while(1)}for(f=0;f<g;f++){e=i[f].lang;for(var j in d)if(b=d[j],b.language==e)return b}}else if("object"===typeof a)return a;return c||null};h.format=function(a,c,e){e=this.findClosestCulture(e);a instanceof Date?a=u(a,c,e):"number"===typeof a&&(a=q(a,c,e));return a};h.localize=function(a,c){return this.findClosestCulture(c).messages[a]||this.cultures["default"].messages[a]};h.parseDate=function(a,c,e){var e=this.findClosestCulture(e),
d,b;if(c){if("string"===typeof c&&(c=[c]),c.length){b=0;for(var f=c.length;b<f;b++){var g=c[b];if(g&&(d=C(a,g,e)))break}}}else for(b in c=e.calendar.patterns,c)if(d=C(a,c[b],e))break;return d||null};h.parseInt=function(a,c,e){return t(h.parseFloat(a,c,e))};h.parseFloat=function(a,c,e){"number"!==typeof c&&(e=c,c=10);var b=this.findClosestCulture(e),e=NaN,i=b.numberFormat;-1<a.indexOf(b.numberFormat.currency.symbol)&&(a=a.replace(b.numberFormat.currency.symbol,""),a=a.replace(b.numberFormat.currency["."],
b.numberFormat["."]));a=p(a);if(g.test(a))e=parseFloat(a);else if(!c&&f.test(a))e=parseInt(a,16);else{b=z(a,i,i.pattern[0]);c=b[0];b=b[1];""===c&&"(n)"!==i.pattern[0]&&(b=z(a,i,"(n)"),c=b[0],b=b[1]);""===c&&"-n"!==i.pattern[0]&&(b=z(a,i,"-n"),c=b[0],b=b[1]);var c=c||"+",j,a=b.indexOf("e");0>a&&(a=b.indexOf("E"));0>a?(j=b,a=null):(j=b.substr(0,a),a=b.substr(a+1));var k=i["."],l=j.indexOf(k);0>l?(b=j,j=null):(b=j.substr(0,l),j=j.substr(l+k.length));k=i[","];b=b.split(k).join("");l=k.replace(/\u00A0/g,
" ");k!==l&&(b=b.split(l).join(""));c+=b;null!==j&&(c+="."+j);null!==a&&(i=z(a,i,"-n"),c+="e"+(i[0]||"+")+i[1]);d.test(c)&&(e=parseFloat(c))}return e};h.culture=function(a){"undefined"!==typeof a&&(this.cultureSelector=a);return this.findClosestCulture(a)||this.cultures["default"]}})(this);
"JSON"in window&&window.JSON||(this.JSON||(this.JSON={}),function(){function a(a){return a<10?"0"+a:a}function b(a){g.lastIndex=0;return g.test(a)?'"'+a.replace(g,function(a){var c=e[a];return typeof c==="string"?c:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function h(a,e){var f,g,o,p,t=d,m,r=e[a];r&&(typeof r==="object"&&typeof r.toJSON==="function")&&(r=r.toJSON(a));typeof i==="function"&&(r=i.call(e,a,r));switch(typeof r){case "string":return b(r);case "number":return isFinite(r)?
String(r):"null";case "boolean":case "null":return String(r);case "object":if(!r)return"null";d=d+c;m=[];if(Object.prototype.toString.apply(r)==="[object Array]"){p=r.length;for(f=0;f<p;f=f+1)m[f]=h(f,r)||"null";o=m.length===0?"[]":d?"[\n"+d+m.join(",\n"+d)+"\n"+t+"]":"["+m.join(",")+"]";d=t;return o}if(i&&typeof i==="object"){p=i.length;for(f=0;f<p;f=f+1){g=i[f];if(typeof g==="string")(o=h(g,r))&&m.push(b(g)+(d?": ":":")+o)}}else for(g in r)if(Object.hasOwnProperty.call(r,g))(o=h(g,r))&&m.push(b(g)+
(d?": ":":")+o);o=m.length===0?"{}":d?"{\n"+d+m.join(",\n"+d)+"\n"+t+"}":"{"+m.join(",")+"}";d=t;return o}}if(typeof Date.prototype.toJSON!=="function"){Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null};String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()}}var f=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
g=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,d,c,e={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},i;if(typeof JSON.stringify!=="function")JSON.stringify=function(a,e,b){var f;c=d="";if(typeof b==="number")for(f=0;f<b;f=f+1)c=c+" ";else typeof b==="string"&&(c=b);if((i=e)&&typeof e!=="function"&&(typeof e!=="object"||typeof e.length!=="number"))throw Error("JSON.stringify");return h("",{"":a})};
if(typeof JSON.parse!=="function")JSON.parse=function(a,c){function e(a,d){var b,f,g=a[d];if(g&&typeof g==="object")for(b in g)if(Object.hasOwnProperty.call(g,b)){f=e(g,b);f!==void 0?g[b]=f:delete g[b]}return c.call(a,d,g)}var d,a=String(a);f.lastIndex=0;f.test(a)&&(a=a.replace(f,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){d=eval("("+a+")");return typeof c==="function"?e({"":d},""):d}throw new SyntaxError("JSON.parse");}}());
(function(a){a.factory=function(b,h){if(a.fn[b])throw"$.fn."+b+" plugin already exists";if(a[b])throw"$."+b+" class already exists";a.fn[b]=function(f){var g=null,d=null;if(a.type(f)==="string"){g=f;d=Array.prototype.slice.call(arguments,1)}return this.each(function(){var c=a(this),e=c.data("$."+b);if(g)e&&a.type(e[g])==="function"?e[g].apply(e,d):console.warn(b,"Unable to invoke method",g);else{e&&e._destroy();e=new a[b](c,f);c.data("$."+b,e)}})};a[b]=function(f,g){this.options=a.extend(true,{},
a[b].defaults,g);this.element=f;this.init()};a.extend(a[b].prototype,{init:function(){},_destroy:function(){}},h);return a[b]}})(jQuery);
(function(){var a={};$.extend({localstore:function(b,h,f,g){var d=document.location.hostname,c=document.location.protocol;if(typeof h!=="undefined"){var e=JSON.stringify(h);if(!f&&window.globalStorage)h===null?delete window.globalStorage[d][c+b]:window.globalStorage[d][c+b]=e;else if(!f&&window.localStorage&&window.localStorage.setItem)h===null?window.localStorage.removeItem(c+b):window.localStorage.setItem(c+b,e);else if(f!==false){f={};f.domain=fb.get_cookie_domain();h===null?$.cookie(b,null,f):
$.cookie(b,e,$.extend(f,g||{expires:14,path:"/"}))}else h===null?delete a[b]:a[b]=e;return h}if(!f&&window.globalStorage){if(window.globalStorage[d][c+b])h=window.globalStorage[d][c+b].value}else h=!f&&window.localStorage?window.localStorage.getItem(c+b):f!==false?$.cookie(b):a[b];return h!=""&&h!==null&&h!==void 0?JSON.parse(h,null):null}})})();
(function(a){a.extend({metadata:{defaults:{type:"class",name:"metadata",cre:/({.*})/,single:"metadata"},setType:function(a,h){this.defaults.type=a;this.defaults.name=h},get:function(b,h){var f=a.extend({},this.defaults,h);if(!f.single.length)f.single="metadata";var g=a.data(b,f.single);if(g)return g;var g="{}",d=function(a){if(typeof a!="string")return a;return a=eval("("+a+")")};if(f.type=="html5"){var c={};a(b.attributes).each(function(){var a=this.nodeName;if(a.match(/^data-/))a=a.replace(/^data-/,
"");else return true;c[a]=d(this.nodeValue)})}else{if(f.type=="class"){var e=f.cre.exec(b.className);e&&(g=e[1])}else if(f.type=="elem"){if(!b.getElementsByTagName)return;e=b.getElementsByTagName(f.name);e.length&&(g=a.trim(e[0].innerHTML))}else if(b.getAttribute!=void 0)(e=b.getAttribute(f.name))&&(g=e);c=d(g.indexOf("{")<0?"{"+g+"}":g)}a.data(b,f.single,c);return c}}});a.fn.metadata=function(b){return a.metadata.get(this[0],b)}})(jQuery);
(function(a,b){function h(b){return!a(b).parents().andSelf().filter(function(){return a.curCSS(this,"visibility")==="hidden"||a.expr.filters.hidden(this)}).length}a.ui=a.ui||{};if(!a.ui.version){a.extend(a.ui,{version:"1.8.10",keyCode:{ALT:18,BACKSPACE:8,CAPS_LOCK:20,COMMA:188,COMMAND:91,COMMAND_LEFT:91,COMMAND_RIGHT:93,CONTROL:17,DELETE:46,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,INSERT:45,LEFT:37,MENU:93,NUMPAD_ADD:107,NUMPAD_DECIMAL:110,NUMPAD_DIVIDE:111,NUMPAD_ENTER:108,NUMPAD_MULTIPLY:106,NUMPAD_SUBTRACT:109,
PAGE_DOWN:34,PAGE_UP:33,PERIOD:190,RIGHT:39,SHIFT:16,SPACE:32,TAB:9,UP:38,WINDOWS:91}});a.fn.extend({_focus:a.fn.focus,focus:function(b,g){return typeof b==="number"?this.each(function(){var d=this;setTimeout(function(){a(d).focus();g&&g.call(d)},b)}):this._focus.apply(this,arguments)},scrollParent:function(){var b;b=a.browser.msie&&/(static|relative)/.test(this.css("position"))||/absolute/.test(this.css("position"))?this.parents().filter(function(){return/(relative|absolute|fixed)/.test(a.curCSS(this,
"position",1))&&/(auto|scroll)/.test(a.curCSS(this,"overflow",1)+a.curCSS(this,"overflow-y",1)+a.curCSS(this,"overflow-x",1))}).eq(0):this.parents().filter(function(){return/(auto|scroll)/.test(a.curCSS(this,"overflow",1)+a.curCSS(this,"overflow-y",1)+a.curCSS(this,"overflow-x",1))}).eq(0);return/fixed/.test(this.css("position"))||!b.length?a(document):b},zIndex:function(f){if(f!==b)return this.css("zIndex",f);if(this.length)for(var f=a(this[0]),g;f.length&&f[0]!==document;){g=f.css("position");if(g===
"absolute"||g==="relative"||g==="fixed"){g=parseInt(f.css("zIndex"),10);if(!isNaN(g)&&g!==0)return g}f=f.parent()}return 0},disableSelection:function(){return this.bind((a.support.selectstart?"selectstart":"mousedown")+".ui-disableSelection",function(a){a.preventDefault()})},enableSelection:function(){return this.unbind(".ui-disableSelection")}});a.each(["Width","Height"],function(f,g){function d(e,d,b,f){a.each(c,function(){d=d-(parseFloat(a.curCSS(e,"padding"+this,true))||0);b&&(d=d-(parseFloat(a.curCSS(e,
"border"+this+"Width",true))||0));f&&(d=d-(parseFloat(a.curCSS(e,"margin"+this,true))||0))});return d}var c=g==="Width"?["Left","Right"]:["Top","Bottom"],e=g.toLowerCase(),i={innerWidth:a.fn.innerWidth,innerHeight:a.fn.innerHeight,outerWidth:a.fn.outerWidth,outerHeight:a.fn.outerHeight};a.fn["inner"+g]=function(c){return c===b?i["inner"+g].call(this):this.each(function(){a(this).css(e,d(this,c)+"px")})};a.fn["outer"+g]=function(c,b){return typeof c!=="number"?i["outer"+g].call(this,c):this.each(function(){a(this).css(e,
d(this,c,true,b)+"px")})}});a.extend(a.expr[":"],{data:function(b,g,d){return!!a.data(b,d[3])},focusable:function(b){var g=b.nodeName.toLowerCase(),d=a.attr(b,"tabindex");if("area"===g){g=b.parentNode;d=g.name;if(!b.href||!d||g.nodeName.toLowerCase()!=="map")return false;b=a("img[usemap=#"+d+"]")[0];return!!b&&h(b)}return(/input|select|textarea|button|object/.test(g)?!b.disabled:"a"==g?b.href||!isNaN(d):!isNaN(d))&&h(b)},tabbable:function(b){var g=a.attr(b,"tabindex");return(isNaN(g)||g>=0)&&a(b).is(":focusable")}});
a(function(){var b=document.body,g=b.appendChild(g=document.createElement("div"));a.extend(g.style,{minHeight:"100px",height:"auto",padding:0,borderWidth:0});a.support.minHeight=g.offsetHeight===100;a.support.selectstart="onselectstart"in g;b.removeChild(g).style.display="none"});a.extend(a.ui,{plugin:{add:function(b,g,d){var b=a.ui[b].prototype,c;for(c in d){b.plugins[c]=b.plugins[c]||[];b.plugins[c].push([g,d[c]])}},call:function(a,b,d){if((b=a.plugins[b])&&a.element[0].parentNode)for(var c=0;c<
b.length;c++)a.options[b[c][0]]&&b[c][1].apply(a.element,d)}},contains:function(a,b){return document.compareDocumentPosition?a.compareDocumentPosition(b)&16:a!==b&&a.contains(b)},hasScroll:function(b,g){if(a(b).css("overflow")==="hidden")return false;var d=g&&g==="left"?"scrollLeft":"scrollTop",c=false;if(b[d]>0)return true;b[d]=1;c=b[d]>0;b[d]=0;return c},isOverAxis:function(a,b,d){return a>b&&a<b+d},isOver:function(b,g,d,c,e,i){return a.ui.isOverAxis(b,d,e)&&a.ui.isOverAxis(g,c,i)}})}})(jQuery);
(function(a,b){if(a.cleanData){var h=a.cleanData;a.cleanData=function(b){for(var d=0,c;(c=b[d])!=null;d++)a(c).triggerHandler("remove");h(b)}}else{var f=a.fn.remove;a.fn.remove=function(b,d){return this.each(function(){d||(!b||a.filter(b,[this]).length)&&a("*",this).add([this]).each(function(){a(this).triggerHandler("remove")});return f.call(a(this),b,d)})}}a.widget=function(b,d,c){var e=b.split(".")[0],f,b=b.split(".")[1];f=e+"-"+b;if(!c){c=d;d=a.Widget}a.expr[":"][f]=function(c){return!!a.data(c,
b)};a[e]=a[e]||{};a[e][b]=function(a,c){arguments.length&&this._createWidget(a,c)};d=new d;d.options=a.extend(true,{},d.options);a[e][b].prototype=a.extend(true,d,{namespace:e,widgetName:b,widgetEventPrefix:a[e][b].prototype.widgetEventPrefix||b,widgetBaseClass:f},c);a.widget.bridge(b,a[e][b])};a.widget.bridge=function(f,d){a.fn[f]=function(c){var e=typeof c==="string",i=Array.prototype.slice.call(arguments,1),k=this,c=!e&&i.length?a.extend.apply(null,[true,c].concat(i)):c;if(e&&c.charAt(0)==="_")return k;
e?this.each(function(){var e=a.data(this,f),d=e&&a.isFunction(e[c])?e[c].apply(e,i):e;if(d!==e&&d!==b){k=d;return false}}):this.each(function(){var e=a.data(this,f);e?e.option(c||{})._init():a.data(this,f,new d(c,this))});return k}};a.Widget=function(a,b){arguments.length&&this._createWidget(a,b)};a.Widget.prototype={widgetName:"widget",widgetEventPrefix:"",options:{disabled:false},_createWidget:function(b,d){a.data(d,this.widgetName,this);this.element=a(d);this.options=a.extend(true,{},this.options,
this._getCreateOptions(),b);var c=this;this.element.bind("remove."+this.widgetName,function(){c.destroy()});this._create();this._trigger("create");this._init()},_getCreateOptions:function(){return a.metadata&&a.metadata.get(this.element[0])[this.widgetName]},_create:function(){},_init:function(){},destroy:function(){this.element.unbind("."+this.widgetName).removeData(this.widgetName);this.widget().unbind("."+this.widgetName).removeAttr("aria-disabled").removeClass(this.widgetBaseClass+"-disabled ui-state-disabled")},
widget:function(){return this.element},option:function(f,d){var c=f;if(arguments.length===0)return a.extend({},this.options);if(typeof f==="string"){if(d===b)return this.options[f];c={};c[f]=d}this._setOptions(c);return this},_setOptions:function(b){var d=this;a.each(b,function(a,e){d._setOption(a,e)});return this},_setOption:function(a,b){this.options[a]=b;a==="disabled"&&this.widget()[b?"addClass":"removeClass"](this.widgetBaseClass+"-disabled ui-state-disabled").attr("aria-disabled",b);return this},
enable:function(){return this._setOption("disabled",false)},disable:function(){return this._setOption("disabled",true)},_trigger:function(b,d,c){var e=this.options[b],d=a.Event(d);d.type=(b===this.widgetEventPrefix?b:this.widgetEventPrefix+b).toLowerCase();c=c||{};if(d.originalEvent)for(var b=a.event.props.length,f;b;){f=a.event.props[--b];d[f]=d.originalEvent[f]}this.element.trigger(d,c);return!(a.isFunction(e)&&e.call(this.element[0],d,c)===false||d.isDefaultPrevented())}}})(jQuery);
(function(a){a.widget("ui.mouse",{options:{cancel:":input,option",distance:1,delay:0},_mouseInit:function(){var b=this;this.element.bind("mousedown."+this.widgetName,function(a){return b._mouseDown(a)}).bind("click."+this.widgetName,function(h){if(true===a.data(h.target,b.widgetName+".preventClickEvent")){a.removeData(h.target,b.widgetName+".preventClickEvent");h.stopImmediatePropagation();return false}});this.started=false},_mouseDestroy:function(){this.element.unbind("."+this.widgetName)},_mouseDown:function(b){b.originalEvent=
b.originalEvent||{};if(!b.originalEvent.mouseHandled){this._mouseStarted&&this._mouseUp(b);this._mouseDownEvent=b;var h=this,f=b.which==1,g=typeof this.options.cancel=="string"?a(b.target).parents().add(b.target).filter(this.options.cancel).length:false;if(!f||g||!this._mouseCapture(b))return true;this.mouseDelayMet=!this.options.delay;if(!this.mouseDelayMet)this._mouseDelayTimer=setTimeout(function(){h.mouseDelayMet=true},this.options.delay);if(this._mouseDistanceMet(b)&&this._mouseDelayMet(b)){this._mouseStarted=
this._mouseStart(b)!==false;if(!this._mouseStarted){b.preventDefault();return true}}this._mouseMoveDelegate=function(a){return h._mouseMove(a)};this._mouseUpDelegate=function(a){return h._mouseUp(a)};a(document).bind("mousemove."+this.widgetName,this._mouseMoveDelegate).bind("mouseup."+this.widgetName,this._mouseUpDelegate);b.preventDefault();return b.originalEvent.mouseHandled=true}},_mouseMove:function(b){if(a.browser.msie&&!(document.documentMode>=9)&&!b.button)return this._mouseUp(b);if(this._mouseStarted){this._mouseDrag(b);
return b.preventDefault()}if(this._mouseDistanceMet(b)&&this._mouseDelayMet(b))(this._mouseStarted=this._mouseStart(this._mouseDownEvent,b)!==false)?this._mouseDrag(b):this._mouseUp(b);return!this._mouseStarted},_mouseUp:function(b){a(document).unbind("mousemove."+this.widgetName,this._mouseMoveDelegate).unbind("mouseup."+this.widgetName,this._mouseUpDelegate);if(this._mouseStarted){this._mouseStarted=false;b.target==this._mouseDownEvent.target&&a.data(b.target,this.widgetName+".preventClickEvent",
true);this._mouseStop(b)}return false},_mouseDistanceMet:function(a){return Math.max(Math.abs(this._mouseDownEvent.pageX-a.pageX),Math.abs(this._mouseDownEvent.pageY-a.pageY))>=this.options.distance},_mouseDelayMet:function(){return this.mouseDelayMet},_mouseStart:function(){},_mouseDrag:function(){},_mouseStop:function(){},_mouseCapture:function(){return true}})})(jQuery);
(function(a){a.ui=a.ui||{};var b=/left|center|right/,h=/top|center|bottom/,f=a.fn.position,g=a.fn.offset;a.fn.position=function(d){if(!d||!d.of)return f.apply(this,arguments);var d=a.extend({},d),c=a(d.of),e=c[0],i=(d.collision||"flip").split(" "),g=d.offset?d.offset.split(" "):[0,0],l,n,j;if(e.nodeType===9){l=c.width();n=c.height();j={top:0,left:0}}else if(e.setTimeout){l=c.width();n=c.height();j={top:c.scrollTop(),left:c.scrollLeft()}}else if(e.preventDefault){d.at="left top";l=n=0;j={top:d.of.pageY,
left:d.of.pageX}}else{l=c.outerWidth();n=c.outerHeight();j=c.offset()}a.each(["my","at"],function(){var a=(d[this]||"").split(" ");a.length===1&&(a=b.test(a[0])?a.concat(["center"]):h.test(a[0])?["center"].concat(a):["center","center"]);a[0]=b.test(a[0])?a[0]:"center";a[1]=h.test(a[1])?a[1]:"center";d[this]=a});i.length===1&&(i[1]=i[0]);g[0]=parseInt(g[0],10)||0;g.length===1&&(g[1]=g[0]);g[1]=parseInt(g[1],10)||0;if(d.at[0]==="right")j.left=j.left+l;else if(d.at[0]==="center")j.left=j.left+l/2;if(d.at[1]===
"bottom")j.top=j.top+n;else if(d.at[1]==="center")j.top=j.top+n/2;j.left=j.left+g[0];j.top=j.top+g[1];return this.each(function(){var c=a(this),e=c.outerWidth(),b=c.outerHeight(),f=parseInt(a.curCSS(this,"marginLeft",true))||0,h=parseInt(a.curCSS(this,"marginTop",true))||0,s=e+f+(parseInt(a.curCSS(this,"marginRight",true))||0),u=b+h+(parseInt(a.curCSS(this,"marginBottom",true))||0),q=a.extend({},j),v;if(d.my[0]==="right")q.left=q.left-e;else if(d.my[0]==="center")q.left=q.left-e/2;if(d.my[1]==="bottom")q.top=
q.top-b;else if(d.my[1]==="center")q.top=q.top-b/2;q.left=Math.round(q.left);q.top=Math.round(q.top);v={left:q.left-f,top:q.top-h};a.each(["left","top"],function(c,f){if(a.ui.position[i[c]])a.ui.position[i[c]][f](q,{targetWidth:l,targetHeight:n,elemWidth:e,elemHeight:b,collisionPosition:v,collisionWidth:s,collisionHeight:u,offset:g,my:d.my,at:d.at})});a.fn.bgiframe&&c.bgiframe();c.offset(a.extend(q,{using:d.using}))})};a.ui.position={fit:{left:function(b,c){var e=a(window),e=c.collisionPosition.left+
c.collisionWidth-e.width()-e.scrollLeft();b.left=e>0?b.left-e:Math.max(b.left-c.collisionPosition.left,b.left)},top:function(b,c){var e=a(window),e=c.collisionPosition.top+c.collisionHeight-e.height()-e.scrollTop();b.top=e>0?b.top-e:Math.max(b.top-c.collisionPosition.top,b.top)}},flip:{left:function(b,c){if(c.at[0]!=="center"){var e=a(window),e=c.collisionPosition.left+c.collisionWidth-e.width()-e.scrollLeft(),f=c.my[0]==="left"?-c.elemWidth:c.my[0]==="right"?c.elemWidth:0,g=c.at[0]==="left"?c.targetWidth:
-c.targetWidth,l=-2*c.offset[0];b.left=b.left+(c.collisionPosition.left<0?f+g+l:e>0?f+g+l:0)}},top:function(b,c){if(c.at[1]!=="center"){var e=a(window),e=c.collisionPosition.top+c.collisionHeight-e.height()-e.scrollTop(),f=c.my[1]==="top"?-c.elemHeight:c.my[1]==="bottom"?c.elemHeight:0,g=c.at[1]==="top"?c.targetHeight:-c.targetHeight,l=-2*c.offset[1];b.top=b.top+(c.collisionPosition.top<0?f+g+l:e>0?f+g+l:0)}}}};if(!a.offset.setOffset){a.offset.setOffset=function(b,c){if(/static/.test(a.curCSS(b,"position")))b.style.position=
"relative";var e=a(b),f=e.offset(),g=parseInt(a.curCSS(b,"top",true),10)||0,l=parseInt(a.curCSS(b,"left",true),10)||0,f={top:c.top-f.top+g,left:c.left-f.left+l};"using"in c?c.using.call(b,f):e.css(f)};a.fn.offset=function(b){var c=this[0];return!c||!c.ownerDocument?null:b?this.each(function(){a.offset.setOffset(this,b)}):g.call(this)}}})(jQuery);
(function(a,b){if(!("console"in window)){var h=window.console={};h.log=h.warn=h.error=h.debug=function(){}}a(function(){var c=a("<div>");a(document.body).append(c);var e=setTimeout(function(){if(a.cleanData){var c=a.cleanData;a.cleanData=function(e){for(var b=0,d;(d=e[b])!=null;b++)a(d).triggerHandler("remove");c(e)}}else{var e=a.fn.remove;a.fn.remove=function(c,b){return this.each(function(){b||(!c||a.filter(c,[this]).length)&&a("*",this).add([this]).each(function(){a(this).triggerHandler("remove")});
return e.call(a(this),c,b)})}}},1);c.bind("remove",function(){clearTimeout(e)});c.remove()});var f={key:1,filter:1,spell:1,exact:1,lang:1,scoring:1,prefixed:1,stemmed:1,format:1,mql_output:1,output:1};a.suggest=function(c,e){a.fn[c]=function(e){this.length||console.warn("Suggest: invoked on empty element set");return this.each(function(){this.nodeName&&(this.nodeName.toUpperCase()==="INPUT"?this.type&&this.type.toUpperCase()!=="TEXT"&&console.warn("Suggest: unsupported INPUT type: "+this.type):console.warn("Suggest: unsupported DOM element: "+
this.nodeName));var b=a.data(this,c);b&&b._destroy();a.data(this,c,new a.suggest[c](this,e))._init()})};a.suggest[c]=function(e,b){var d=this,g=this.options=a.extend(true,{},a.suggest.defaults,a.suggest[c].defaults,b),j=g.css_prefix=g.css_prefix||"",h=g.css;this.name=c;a.each(h,function(a){h[a]=j+h[a]});g.ac_param={};a.each(f,function(a){var c=g[a];c===null||c===""||(g.ac_param[a]=c)});g.flyout_lang=null;if(g.ac_param.lang){var p=g.ac_param.lang;a.isArray(p)&&p.length&&(p=p.join(","));if(p)g.flyout_lang=
p}this._status={START:"",LOADING:"",SELECT:"",ERROR:""};if(g.status&&g.status instanceof Array&&g.status.length>=3){this._status.START=g.status[0]||"";this._status.LOADING=g.status[1]||"";this._status.SELECT=g.status[2]||"";if(g.status.length===4)this._status.ERROR=g.status[3]||""}var p=this.status=a('<div style="display:none;">').addClass(h.status),t=this.list=a("<ul>").addClass(h.list),m=this.pane=a('<div style="display:none;" class="fbs-reset">').addClass(h.pane);m.append(p).append(t);if(g.parent)a(g.parent).append(m);
else{m.css("position","absolute");g.zIndex&&m.css("z-index",g.zIndex);a(document.body).append(m)}m.bind("mousedown",function(a){d.input.data("dont_hide",true);a.stopPropagation()}).bind("mouseup",function(a){d.input.data("dont_hide")&&d.input.focus();d.input.removeData("dont_hide");a.stopPropagation()}).bind("click",function(a){a.stopPropagation();if(a=d.get_selected()){d.onselect(a,true);d.hide_all()}});t.hover(function(a){d.hoverover_list(a)},function(a){d.hoverout_list(a)});this.input=a(e).attr("autocomplete",
"off").unbind(".suggest").bind("remove.suggest",function(){d._destroy()}).bind("keydown.suggest",function(a){d.keydown(a)}).bind("keypress.suggest",function(a){d.keypress(a)}).bind("keyup.suggest",function(a){d.keyup(a)}).bind("blur.suggest",function(a){d.blur(a)}).bind("textchange.suggest",function(){d.textchange()}).bind("focus.suggest",function(a){d.focus(a)}).bind(a.browser.msie?"paste.suggest":"input.suggest",function(){clearTimeout(d.paste_timeout);d.paste_timeout=setTimeout(function(){d.textchange()},
0)});this.onresize=function(){d.invalidate_position();if(m.is(":visible")){d.position();if(g.flyout&&d.flyoutpane&&d.flyoutpane.is(":visible")){var a=d.get_selected();a&&d.flyout_position(a)}}};a(window).bind("resize.suggest",this.onresize).bind("scroll.suggest",this.onresize)};a.suggest[c].prototype=a.extend({},a.suggest.prototype,e)};a.suggest.prototype={_init:function(){},_destroy:function(){this.pane.remove();this.list.remove();this.input.unbind(".suggest");a(window).unbind("resize.suggest",this.onresize).unbind("scroll.suggest",
this.onresize);this.input.removeData("data.suggest")},invalidate_position:function(){self._position=null},status_start:function(){this.hide_all();this.status.siblings().hide();if(this._status.START){this.status.text(this._status.START).show();if(!this.pane.is(":visible")){this.position();this.pane_show()}}this._status.LOADING&&this.status.removeClass("loading")},status_loading:function(){this.status.siblings().show();if(this._status.LOADING){this.status.addClass("loading").text(this._status.LOADING).show();
if(!this.pane.is(":visible")){this.position();this.pane_show()}}else this.status.hide()},status_select:function(){this.status.siblings().show();this._status.SELECT?this.status.text(this._status.SELECT).show():this.status.hide();this._status.LOADING&&this.status.removeClass("loading")},status_error:function(){this.status.siblings().show();this._status.ERROR?this.status.text(this._status.ERROR).show():this.status.hide();this._status.LOADING&&this.status.removeClass("loading")},focus:function(a){this.input.val()===
""?this.status_start():this.focus_hook(a)},focus_hook:function(){if(!this.input.data("data.suggest")&&!this.pane.is(":visible")&&a("."+this.options.css.item,this.list).length){this.position();this.pane_show()}},keydown:function(a){var e=a.keyCode;if(e===9)this.tab(a);else if(e===38||e===40)a.shiftKey||a.preventDefault()},keypress:function(a){var e=a.keyCode;e===38||e===40?a.shiftKey||a.preventDefault():e===13&&this.enter(a)},keyup:function(c){var e=c.keyCode;if(e===38){c.preventDefault();this.up(c)}else if(e===
40){c.preventDefault();this.down(c)}else if(c.ctrlKey&&e===77)a(".fbs-more-link",this.pane).click();else if(a.suggest.is_char(c)){clearTimeout(this.keypress.timeout);var b=this;this.keypress.timeout=setTimeout(function(){b.textchange()},0)}else e===27&&this.escape(c);return true},blur:function(){if(!this.input.data("dont_hide")){this.input.data("data.suggest");this.hide_all()}},tab:function(c){if(!c.shiftKey&&!c.metaKey&&!c.ctrlKey){var c=this.options,c=this.pane.is(":visible")&&a("."+c.css.item,
this.list).length,e=this.get_selected();if(c&&e){this.onselect(e);this.hide_all()}}},enter:function(c){var e=this.options;if(this.pane.is(":visible")){if(c.shiftKey){this.shift_enter(c);c.preventDefault();return}if(a("."+e.css.item,this.list).length){var b=this.get_selected();if(b){this.onselect(b);this.hide_all();c.preventDefault();return}if(!e.soft){this.input.data("data.suggest");if(a("."+this.options.css.item+":visible",this.list).length){this.updown(false);c.preventDefault();return}}}}e.soft?
this.soft_enter():c.preventDefault()},soft_enter:function(){},shift_enter:function(){},escape:function(){this.hide_all()},up:function(a){this.updown(true,a.ctrlKey||a.shiftKey)},down:function(a){this.updown(false,null,a.ctrlKey||a.shiftKey)},updown:function(c,e,b){var d=this.options.css,f=this.list;if(this.pane.is(":visible")){var g=a("."+d.item+":visible",f);if(g.length){var f=a(g[0]),g=a(g[g.length-1]),j=this.get_selected()||[];clearTimeout(this.ignore_mouseover.timeout);this._ignore_mouseover=
false;if(c)if(e)this._goto(f);else if(j.length)if(j[0]==f[0]){f.removeClass(d.selected);this.input.val(this.input.data("original.suggest"));this.hoverout_list()}else{c=j.prevAll("."+d.item+":visible:first");this._goto(c)}else this._goto(g);else if(b)this._goto(g);else if(j.length)if(j[0]==g[0]){g.removeClass(d.selected);this.input.val(this.input.data("original.suggest"));this.hoverout_list()}else{c=j.nextAll("."+d.item+":visible:first");this._goto(c)}else this._goto(f)}}else c||this.textchange()},
_goto:function(a){a.trigger("mouseover.suggest");var e=a.data("data.suggest");this.input.val(e?e.name:this.input.data("original.suggest"));this.scroll_to(a)},scroll_to:function(a){var e=this.list,b=e.scrollTop(),d=b+e.innerHeight(),f=a.outerHeight(),a=a.prevAll().length*f,f=a+f;if(a<b){this.ignore_mouseover();e.scrollTop(a)}else if(f>d){this.ignore_mouseover();e.scrollTop(b+f-d)}},textchange:function(){this.input.removeData("data.suggest");this.input.trigger("fb-textchange",this);var a=this.input.val();
if(a==="")this.status_start();else{this.status_loading();this.request(a)}},request:function(){},response:function(c){if(c){"cost"in c&&this.trackEvent(this.name,"response","cost",c.cost);if(this.check_response(c)){var e=[];if(a.isArray(c))e=c;else if("result"in c)e=c.result;var b=a.map(arguments,function(a){return a});this.response_hook.apply(this,b);var d=null,f=this,g=this.options;a.each(e,function(a,e){if(!e.id&&e.mid)e.id=e.mid;var b=f.create_item(e,c).bind("mouseover.suggest",function(a){f.mouseover_item(a)});
b.data("data.suggest",e);f.list.append(b);a===0&&(d=b)});this.input.data("original.suggest",this.input.val());if(a("."+g.css.item,this.list).length===0&&g.nomatch){e=a('<li class="fbs-nomatch">');if(typeof g.nomatch==="string")e.text(g.nomatch);else{g.nomatch.title&&e.append(a('<em class="fbs-nomatch-text">').text(g.nomatch.title));g.nomatch.heading&&e.append(a("<h3>").text(g.nomatch.heading));if((g=g.nomatch.tips)&&g.length){var j=a('<ul class="fbs-search-tips">');a.each(g,function(c,e){j.append(a("<li>").text(e))});
e.append(j)}}e.bind("click.suggest",function(a){a.stopPropagation()});this.list.append(e)}b.push(d);this.show_hook.apply(this,b);this.position();this.pane_show()}}},pane_show:function(){var c=false;a("> li",this.list).length&&(c=true);c||this.pane.children(":not(."+this.options.css.list+")").each(function(){if(a(this).css("display")!="none"){c=true;return false}});if(c)if(this.options.animate){var e=this;this.pane.slideDown("fast",function(){e.input.trigger("fb-pane-show",e)})}else{this.pane.show();
this.input.trigger("fb-pane-show",this)}else{this.pane.hide();this.input.trigger("fb-pane-hide",this)}},create_item:function(c){var e=this.options.css,b=a("<li>").addClass(e.item),c=a("<label>").text(c.name);b.append(a("<div>").addClass(e.item_name).append(c));return b},mouseover_item:function(c){if(!this._ignore_mouseover){c=c.target;c.nodeName.toLowerCase()!=="li"&&(c=a(c).parents("li:first"));var e=a(c),b=this.options.css;a("."+b.item,this.list).each(function(){this!==e[0]&&a(this).removeClass(b.selected)});
if(!e.hasClass(b.selected)){e.addClass(b.selected);this.mouseover_item_hook(e)}}},mouseover_item_hook:function(){},hoverover_list:function(){},hoverout_list:function(){},check_response:function(){return true},response_hook:function(){this.list.empty()},show_hook:function(){this.status_select()},position:function(){var c=this.pane,e=this.options;if(!e.parent){if(!self._position){var b=this.input,d=b.offset(),f=b.outerWidth(true),g=b.outerHeight(true);d.top=d.top+g;var j=c.outerWidth(),h=c.outerHeight(),
p=d.top+h/2,t=a(window).scrollLeft(),b=a(window).scrollTop(),m=a(window).width(),r=a(window).height()+b,s=true;"left"==e.align?s=true:"right"==e.align?s=false:d.left>t+m/2&&(s=false);if(!s){s=d.left-(j-f);if(s>t)d.left=s}if(p>r){e=d.top-g-h;if(e>b)d.top=e}this._position=d}c.css({top:this._position.top,left:this._position.left})}},ignore_mouseover:function(){this._ignore_mouseover=true;var a=this;this.ignore_mouseover.timeout=setTimeout(function(){a.ignore_mouseover_reset()},1E3)},ignore_mouseover_reset:function(){this._ignore_mouseover=
false},get_selected:function(){var c=null,b=this.options.css.selected;a("li",this.list).each(function(){var d=a(this);if(d.hasClass(b)&&d.is(":visible")){c=d;return false}});return c},onselect:function(a){var b=a.data("data.suggest");if(b){this.input.val(b.name).data("data.suggest",b).trigger("fb-select",b);this.trackEvent(this.name,"fb-select","index",a.prevAll().length)}},trackEvent:function(a,b,d,f){this.input.trigger("fb-track-event",{category:a,action:b,label:d,value:f})},hide_all:function(){this.pane.hide();
this.input.trigger("fb-pane-hide",this)}};a.extend(a.suggest,{defaults:{status:["Start typing to get suggestions...","Searching...","Select an item from the list:","Sorry, something went wrong. Please try again later"],soft:false,nomatch:"no matches",css:{pane:"fbs-pane",list:"fbs-list",item:"fbs-item",item_name:"fbs-item-name",selected:"fbs-selected",status:"fbs-status"},css_prefix:null,parent:null,animate:false,zIndex:null},strongify:function(c,b){var d,f=c.toLowerCase().indexOf(b.toLowerCase());
if(f>=0){var g=b.length;d=document.createTextNode(c.substring(0,f));var h=a("<strong>").text(c.substring(f,f+g)),f=document.createTextNode(c.substring(f+g));d=a("<div>").append(d).append(h).append(f)}else d=a("<div>").text(c);return d},keyCode:{CAPS_LOCK:20,CONTROL:17,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,INSERT:45,LEFT:37,NUMPAD_ENTER:108,PAGE_DOWN:34,PAGE_UP:33,RIGHT:39,SHIFT:16,SPACE:32,TAB:9,UP:38,OPTION:18,APPLE:224},is_char:function(c){if(c.type==="keypress"){if((c.metaKey||c.ctrlKey)&&
c.charCode===118)return true;if("isChar"in c)return c.isChar}else{var b=a.suggest.keyCode.not_char;if(!b){b={};a.each(a.suggest.keyCode,function(a,c){b[""+c]=1});a.suggest.keyCode.not_char=b}return!(""+c.keyCode in b)}},parse_input:function(c){for(var b=/(\S+)\:(?:\"([^\"]+)\"|(\S+))/g,d=c,g=[],h={},n=b.exec(c);n;){n[1]in f?h[n[1]]=a.isEmptyObject(n[2])?n[3]:n[2]:g.push(n[0]);d=d.replace(n[0],"");n=b.exec(c)}d=a.trim(d.replace(/\s+/g," "));return[d,g,h]},mqlkey_fast:/^[_A-Za-z0-9][A-Za-z0-9_-]*$/,
mqlkey_slow:/^(?:[A-Za-z0-9]|\$[A-F0-9]{4})(?:[A-Za-z0-9_-]|\$[A-F0-9]{4})*$/,check_mql_key:function(c){return a.suggest.mqlkey_fast.test(c)||a.suggest.mqlkey_slow.test(c)?true:false},check_mql_id:function(c){if(c.indexOf("/")===0){c=c.split("/");c.shift();if(!(c.length==1&&c[0]===""))for(var b=0,d=c.length;b<d;b++)if(!a.suggest.check_mql_key(c[b]))return false;return true}return false},is_system_type:function(a){return a==null?false:a.indexOf("/type/")===0}});var g=a.suggest.prototype._destroy,d=
a.suggest.prototype.show_hook;a.suggest("suggest",{_init:function(){var c=this,b=this.options;if(b.flyout_service_url==null)b.flyout_service_url=b.service_url;this.flyout_url=b.flyout_service_url;if(b.flyout_service_path)this.flyout_url=this.flyout_url+b.flyout_service_path;this.flyout_url=this.flyout_url.replace(/\$\{key\}/g,b.key);if(b.flyout_image_service_url==null)b.flyout_image_service_url=b.service_url;this.flyout_image_url=b.flyout_image_service_url;if(b.flyout_image_service_path)this.flyout_image_url=
this.flyout_image_url+b.flyout_image_service_path;this.flyout_image_url=this.flyout_image_url.replace(/\$\{key\}/g,b.key);if(!a.suggest.cache)a.suggest.cache={};if(b.flyout){this.flyoutpane=a('<div style="display:none;" class="fbs-reset">').addClass(b.css.flyoutpane);if(b.flyout_parent)a(b.flyout_parent).append(this.flyoutpane);else{this.flyoutpane.css("position","absolute");b.zIndex&&this.flyoutpane.css("z-index",b.zIndex);a(document.body).append(this.flyoutpane)}this.flyoutpane.hover(function(a){c.hoverover_list(a)},
function(a){c.hoverout_list(a)}).bind("mousedown.suggest",function(a){a.stopPropagation();c.pane.click()});if(!a.suggest.flyout)a.suggest.flyout={};if(!a.suggest.flyout.cache)a.suggest.flyout.cache={}}},_destroy:function(){g.call(this);this.flyoutpane&&this.flyoutpane.remove();this.input.removeData("request.count.suggest");this.input.removeData("flyout.request.count.suggest")},shift_enter:function(){if(this.options.suggest_new){this.suggest_new();this.hide_all()}},hide_all:function(){this.pane.hide();
this.flyoutpane&&this.flyoutpane.hide();this.input.trigger("fb-pane-hide",this);this.input.trigger("fb-flyoutpane-hide",this)},request:function(c,b){var d=this,f=this.options,g=c,h=f.ac_param.filter||[],j=null;a.type(h)==="string"&&(h=[h]);h=h.slice();if(f.advanced){var o=a.suggest.parse_input(g),g=o[0];o[1].length&&h.push("(all "+o[1].join(" ")+")");j=o[2];if(a.suggest.check_mql_id(g)){h.push('(any alias{start}:"'+g+'" mid:"'+g+'")');j.prefixed=true;g=""}}o={};o[f.query_param_name]=g;if(b)o.cursor=
b;a.extend(o,f.ac_param,j);if(h.length)o.filter=h;var p=f.service_url+f.service_path+"?"+a.param(o,true);if(g=a.suggest.cache[p])this.response(g,b?b:-1,true);else{clearTimeout(this.request.timeout);var t={url:f.service_url+f.service_path,data:o,traditional:true,beforeSend:function(){var a=d.input.data("request.count.suggest")||0;a||d.trackEvent(d.name,"start_session");a=a+1;d.trackEvent(d.name,"request","count",a);d.input.data("request.count.suggest",a)},success:function(f){a.suggest.cache[p]=f;f.prefix=
c;d.response(f,b?b:-1)},error:function(a){d.status_error();d.trackEvent(d.name,"request","error",{url:this.url,response:a?a.responseText:""});d.input.trigger("fb-error",Array.prototype.slice.call(arguments))},complete:function(a){a&&d.trackEvent(d.name,"request","tid",a.getResponseHeader("X-Metaweb-TID"))},dataType:"jsonp",cache:true};this.request.timeout=setTimeout(function(){a.ajax(t)},f.xhr_delay)}},create_item:function(c,b){var d=this.options.css,f=a("<li>").addClass(d.item),g=a("<label>").append(a.suggest.strongify(c.name||
c.id,b.prefix)),h=a("<div>").addClass(d.item_name).append(g),j=c.notable;c.under&&a(":first",g).append(a("<small>").text(" ("+c.under+")"));(j!=null&&a.suggest.is_system_type(j.id)||this.options.scoring!=null&&this.options.scoring.toUpperCase()==="SCHEMA")&&a(":first",g).append(a("<small>").text(" ("+c.id+")"));f.append(h);d=a("<div>").addClass(d.item_type);j&&j.name?d.text(j.name):this.options.show_id&&c.id&&d.text(c.id);h.prepend(d);return f},mouseover_item_hook:function(a){a=a.data("data.suggest");
this.options.flyout&&a&&this.flyout_request(a)},check_response:function(a){return a.prefix===this.input.val()},response_hook:function(c,b){this.flyoutpane&&this.flyoutpane.hide();b>0?a(".fbs-more",this.pane).remove():this.list.empty()},show_hook:function(c,b,f){d.apply(this,[c]);var g=this.options,h=this,n=this.pane,j=this.list,o=c.result,p=a(".fbs-more",n),t=a(".fbs-suggestnew",n);a(".fbs-status",n);var m=c.correction;if(m&&m.length){var r=a('<a class="fbs-spell-link" href="#">').append(m[0]).bind("click.suggest",
function(a){a.preventDefault();a.stopPropagation();h.input.val(m[0]).trigger("textchange")});h.status.empty().append("Search instead for ").append(r).show()}if(o&&o.length&&"cursor"in c){if(!p.length){o=a('<a class="fbs-more-link" href="#" title="(Ctrl+m)">view more</a>');p=a('<div class="fbs-more">').append(o);o.bind("click.suggest",function(c){c.preventDefault();c.stopPropagation();c=a(this).parent(".fbs-more");h.more(c.data("cursor.suggest"))});j.after(p)}p.data("cursor.suggest",c.cursor);p.show()}else p.remove();
if(g.suggest_new){if(!t.length){c=a('<button class="fbs-suggestnew-button">');c.text(g.suggest_new);t=a('<div class="fbs-suggestnew">').append('<div class="fbs-suggestnew-description">Your item not in the list?</div>').append(c).append('<span class="fbs-suggestnew-shortcut">(Shift+Enter)</span>').bind("click.suggest",function(a){a.stopPropagation();h.suggest_new(a)});n.append(t)}t.show()}else t.remove();if(f&&f.length&&b>0){b=f.prevAll().length*f.outerHeight();j.scrollTop();j.animate({scrollTop:b},
"slow",function(){f.trigger("mouseover.suggest")})}},suggest_new:function(){var a=this.input.val();if(a!==""){this.input.data("data.suggest",a).trigger("fb-select-new",a);this.trackEvent(this.name,"fb-select-new","index","new");this.hide_all()}},more:function(a){if(a){var b=this.input.data("original.suggest");b!==null&&this.input.val(b);this.request(this.input.val(),a);this.trackEvent(this.name,"more","cursor",a)}return false},flyout_request:function(c){var b=this,d=this.options,f=this.flyoutpane.data("data.suggest");
if(f&&c.id===f.id){if(!this.flyoutpane.is(":visible")){c=this.get_selected();this.flyout_position(c);this.flyoutpane.show();this.input.trigger("fb-flyoutpane-show",this)}}else if((f=a.suggest.flyout.cache[c.id])&&f.id&&f.html)this.flyout_response(f);else{var g=c.id,h={url:this.flyout_url.replace(/\$\{id\}/g,c.id),traditional:true,beforeSend:function(){var a=b.input.data("flyout.request.count.suggest")||0,a=a+1;b.trackEvent(b.name,"flyout.request","count",a);b.input.data("flyout.request.count.suggest",
a)},success:function(c){c["req:id"]=g;if(c.result&&c.result.length)c.html=a.suggest.suggest.create_flyout(c.result[0],b.flyout_image_url);a.suggest.flyout.cache[g]=c;b.flyout_response(c)},error:function(a){b.trackEvent(b.name,"flyout","error",{url:this.url,response:a?a.responseText:""})},complete:function(a){a&&b.trackEvent(b.name,"flyout","tid",a.getResponseHeader("X-Metaweb-TID"))},dataType:"jsonp",cache:true};if(d.flyout_lang)h.data={lang:d.flyout_lang};clearTimeout(this.flyout_request.timeout);
this.flyout_request.timeout=setTimeout(function(){a.ajax(h)},d.xhr_delay);this.input.trigger("fb-request-flyout",h)}},flyout_response:function(a){var b=this.pane,d=this.get_selected()||[];if(b.is(":visible")&&d.length)if((b=d.data("data.suggest"))&&a["req:id"]===b.id&&a.html){this.flyoutpane.html(a.html);this.flyout_position(d);this.flyoutpane.show().data("data.suggest",b);this.input.trigger("fb-flyoutpane-show",this)}},flyout_position:function(c){if(!this.options.flyout_parent){var d=this.pane,f=
this.flyoutpane,g=this.options.css,h=b,n=parseInt(f.css("top"),10),j=parseInt(f.css("left"),10),o=d.offset(),p=d.outerWidth(),t=f.outerHeight(),m=f.outerWidth();if(this.options.flyout==="bottom"){h=o;p=this.input.offset();h.top=o.top<p.top?h.top-t:h.top+d.outerHeight();f.addClass(g.flyoutpane+"-bottom")}else{h=c.offset();c=c.outerHeight();h.left=h.left+p;var r=h.left+m,d=a(document.body).scrollLeft(),s=a(window).width()+d;h.top=h.top+c-t;if(h.top<o.top)h.top=o.top;if(r>s){o=h.left-(p+m);if(o>d)h.left=
o}f.removeClass(g.flyoutpane+"-bottom")}h.top===n&&h.left===j||f.css({top:h.top,left:h.left})}},hoverout_list:function(){this.flyoutpane&&!this.get_selected()&&this.flyoutpane.hide()}});a.extend(a.suggest.suggest,{defaults:{filter:null,spell:"always",exact:false,scoring:null,lang:null,key:null,prefixed:true,stemmed:null,format:null,advanced:true,show_id:true,query_param_name:"query",service_url:"https://www.googleapis.com/freebase/v1",service_path:"/search",align:null,flyout:true,flyout_service_url:null,
flyout_service_path:"/search?filter=(all mid:${id})&output=(notable:/client/summary description type)&key=${key}",flyout_image_service_url:null,flyout_image_service_path:"/image${id}?maxwidth=75&key=${key}&errorid=/freebase/no_image_png",flyout_parent:null,suggest_new:null,nomatch:{title:"No suggested matches",heading:"Tips on getting better suggestions:",tips:["Enter more or fewer characters","Add words related to your original search","Try alternate spellings","Check your spelling"]},css:{item_type:"fbs-item-type",
flyoutpane:"fbs-flyout-pane"},xhr_delay:200},get_value:function(c,b,d){if(c==null||b==null||b.length==0)return null;a.isArray(b)||(b=[b]);var f=null;a.each(b,function(a,b){f=c[b];if(f==null)return false;c=f;return true});if(d){if(f==null)return[];a.isArray(f)||(f=[f]);var g=[];a.each(f,function(c,b){if(a.type(b)==="object")if(b.name!=null)b=b.name;else if(b.id||b.mid)b=b.id||b.mid;else if(b.value!=null){var d=[];a.each(b,function(a,b){a!=="value"&&d.push(b)});b=b.value;d.length&&(b=b+(" ("+d.join(", ")+
")"))}if(a.isArray(b)&&b.length)b=b[0].value;b!=null&&g.push(b)});return g}return f==null?null:f},is_commons_id:function(a){return/^\/base\//.test(a)||/^\/user\//.test(a)?false:true},create_flyout:function(b,d){var f=a.suggest.suggest.get_value,g=a.suggest.is_system_type,h=b.name,n=null,j=null,o=[],p=[],t={};if((n=f(b,"notable"))&&n.name){p.push(n.name);t[n.name]=true}if(n&&g(n.id))n=b.id;else{n=b.mid;j=d.replace(/\$\{id\}/g,n)}var g="freebase",m=f(b,["output","description","wikipedia"],true);m&&
m.length?g="wikipedia":m=f(b,["output","description","freebase"],true);var m=m&&m.length?m[0]:null,r=f(b,["output","notable:/client/summary"]);if(r){var s=f(r,"/common/topic/notable_paths");s&&s.length&&a.each(s,function(a,b){var c=f(r,b,true);if(c&&c.length){var d=b.split("/").pop();o.push([d,c.join(", ")])}})}(s=f(b,["output","type","/type/object/type"],true))&&s.length&&a.each(s,function(a,b){if(!t[b]){p.push(b);t[b]=true}});var u=a('<div class="fbs-flyout-content">');h&&u.append(a('<h1 id="fbs-flyout-title">').text(h));
u.append(a('<h3 class="fbs-topic-properties fbs-flyout-id">').text(n));a.each(o,function(b,c){u.append(a('<h3 class="fbs-topic-properties">').append(a("<strong>").text(c[0]+": ")).append(document.createTextNode(c[1])))});m&&u.append(a('<p class="fbs-topic-article">').append(a('<em class="fbs-citation">').text("["+g+"] ")).append(document.createTextNode(m)));if(j){u.children().addClass("fbs-flyout-image-true");u.prepend(a('<img id="fbs-topic-image" class="fbs-flyout-image-true" src="'+j+'">'))}h=a('<span class="fbs-flyout-types">').text(p.slice(0,
10).join(", "));h=a('<div class="fbs-attribution">').append(h);return a("<div>").append(u).append(h).html()}});document.createElement("input")})(jQuery);(function(a){window.freebase=window.fb={mwLWTReloading:false};window.SERVER&&typeof window.SERVER==="object"&&a.extend(window.freebase,window.SERVER);a.cookie=window.freebase.cookie})(jQuery);
(function(a,b){a.ajaxSettings.traditional=true;if(!b.datelineReloading){if(!window.console)window.console={log:a.noop,info:a.noop,debug:a.noop,warn:a.noop,error:a.noop};b.dispatch=function(b,c,d,e){if(typeof c!=="function")return false;b=a.event.fix(b||window.event);d||(d=[]);e||(e=this);return c.apply(e,[b].concat(d))};b.get_script=function(c,d){var e=b.get_script.cache,f=e[c];if(f)f.state===1?f.callbacks.push(d):f.state===4&&d();else{f=e[c]={state:0,callbacks:[d]};a.ajax({url:c,dataType:"script",
cache:true,beforeSend:function(){f.state=1},success:function(){f.state=4;a.each(f.callbacks,function(a,b){b()})},error:function(a,b,c){f.state=-1;console.error("fb.get_script error",arguments)}})}};b.get_script.cache={};a(window).bind("fb.user.signedin",function(c,d){b.user=d;var e=a("#nav-username");if(e.length){a("> a",e).text(d.name);e[0].href=e[0].href+b.user.id.substring(1);var f=b.h.image_url(d.id,{maxwidth:40,maxheight:40,mode:"fillcropmid"}),f=a('<a class="user-thumb" href="'+d.id+'"><img src="'+
f+'" /></a>');e.prepend(f)}a("#signedin").show();a(".signedin").show()}).bind("fb.user.signedout",function(){a("#signedout").show();a(".signedout").show()}).bind("fb.user.unauthorized",function(){window.location.href=b.h.fb_url("/account/signin",{onsignin:window.location.href})}).bind("fb.user.feedback",function(a,b){if(confirm("Uh oh! Something went wrong. Please report this using our feedback tool."))try{userfeedback.api.startFeedback({productId:"68931",disableScrolling:false},b);return false}catch(c){}});
var h=a.cookie("fb-account-name");if(h){var f={id:"/user/"+h,name:h};setTimeout(function(){a(window).trigger("fb.user.signedin",f);var c=b.h.ajax_url("lib/template/refresh_credentials"),d=a("<iframe name='rc'></iframe>").attr("src",c).hide().appendTo("body").load(function(){var b=parseInt(a("body",window.rc.document).text(),10)-(new Date).getTime();b&&b>0&&setTimeout(function(){a(d).attr("src",c)},b)})},0)}else setTimeout(function(){a(window).trigger("fb.user.signedout")},0);b.window_position=function(){var a=
{};if(typeof window.innerWidth=="number"){a.width=window.outerWidth;a.height=window.outerHeight;a.top=window.screenY;a.left=window.screenX}else if(document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)){a.width=document.body.clientWidth;a.height=document.body.clientHeight;a.top=window.screenTop;a.left=window.screenLeft}return a};var g=function(){e&&e.slideUp(300);n=null;return false},d=function(b,d,f,h){if(e===null){e=a("#page-state");i=a(".status-msg",
e);k=a(".close-msg",e);k.click(g)}if(n==="error")console.warn("MessagePanel: Already displaying error. Ignoring: ",b,d);else{e.hide();a.each(c,function(a,b){e.removeClass(b)});e.addClass(b);i.text(d);n=b;window.clearTimeout(l);if(h){k.show();e.slideDown(300)}else{k.hide();e.slideDown(300);l=window.setTimeout(g,f)}}return false},c=["notice","info","warning","success","error"],e=null,i=null,k=null,l=null,n=null;b.status={doing:function(a){return d("notice",a,2E6,false)},info:function(a,b){return d("info",
a,4E3,b)},warning:function(a,b){return d("warning",a,4E3,b)},success:function(a,b){return d("success",a,6E3,b)},error:function(a,b){return d("error",a,6E3,b)},sprintf:function(b,c){var e=Array.prototype.slice.call(arguments).slice(2),f=c.split("%s");if(f.length>1&&e.length>1&&e.length%2==0){for(var g=a("<span>"),h=0,k=f.length;h<k;h++){g.append(document.createTextNode(f[h]));var l=a('<a href="#">');l.text(e.shift());var n=e.shift();a.type(n)==="function"&&l.click(n);g.append(l)}e=d(b,"",null,true);
i.empty().append(g);return e}return d(b,c,null,true)},clear:function(){window.clearTimeout(l);n==="error"?console.warn("MessagePanel: Displaying error. Ignoring clearing status."):g()}};b.popup=function(a,c,d,e){var c=c||300,d=d||300,f=b.window_position(),g=Math.floor((f.width-c)/2)+f.left,f=Math.floor((f.height-d)/2)+f.top;/chrome/.test(navigator.userAgent.toLowerCase())&&(d=d+50);var c={width:c,height:d,top:f,left:g,directories:"no",location:"no",menubar:"no",resizable:"no",scrollbars:"yes",status:"no",
toolbar:"no"},d=[],h;for(h in c)d.push(h+"="+c[h]);return window.open(a,e||"",d.join())};b.login_popup=function(a){a||(a=function(){window.location.reload()});var c=b.popup("/account/signin",900,600,"Freebase");if(c.opener==null)c.opener=self;window.onsignin=a;window.focus&&c.focus();return false};b.logout_popup=function(a){a||(a=function(){window.location.reload()});var c=b.popup("/account/signout",900,600,"Freebase");if(c.opener==null)c.opener=self;window.onsignout=a;window.focus&&c.focus();return false};
a(function(){var b=a("#header > #nav-utilities > .language-picker"),c=a(".current-lang",b);a("select",b).bind("change",function(){var b=a(this).find(":selected").text();c.text(b)})});a(function(){b.suggest_lang={SUPPORTED:{en:1,es:1,fr:1,de:1,it:1,pt:1,zh:1,ja:1,ko:1,ru:1,sv:1,fi:1,da:1,nl:1,el:1,ro:1,tr:1,hu:1},lang:function(a){a=b.h.lang_code(a||b.lang||"/lang/en");return b.suggest_lang.SUPPORTED[a]&&a!=="en"?a+",en":"en"}};var c=b,d=b.h.fb_googleapis_url(),e=b.acre.freebase.api_key,f,g=[];a.each(b.suggest_lang.lang().split(","),
function(a,b){g.push("s/"+b+",d/"+b)});g.push("s/all,d/all");f=g.join(",");c.suggest_options={service_defaults:{status:["","Searching...","Select an item from the list:"],service_url:d,key:e,lang:f},filter:{operator:function(){var a=Array.prototype.slice.call(arguments),c=a.shift();if(!(c==="any"||c==="all"||c==="should"))throw"Invalid search operator: "+c;var d=[c];if(c==="should"&&a.length>1){a=["any"].concat(a);d.push(b.suggest_options.filter.operator.apply(null,a))}else d=d.concat(a);return"("+
d.join(" ")+")"},any:function(){var a=Array.prototype.slice.call(arguments);a.unshift("any");return b.suggest_options.filter.operator.apply(null,a)},all:function(){var a=Array.prototype.slice.call(arguments);a.unshift("all");return b.suggest_options.filter.operator.apply(null,a)},should:function(){var a=Array.prototype.slice.call(arguments);a.unshift("should");return b.suggest_options.filter.operator.apply(null,a)}},any:function(){var c=a.extend({},b.suggest_options.service_defaults);c.filter=b.suggest_options.filter.any.apply(null,
arguments);return c},all:function(){var c=a.extend({},b.suggest_options.service_defaults);c.filter=b.suggest_options.filter.all.apply(null,arguments);return c},should:function(){var c=a.extend({},b.suggest_options.service_defaults);c.filter=b.suggest_options.filter.should.apply(null,arguments);return c},search:function(c){var d=a.extend({},b.suggest_options.service_defaults,{status:null,parent:"#site-search-box",align:"right",filter:["(not type:/common/document)"],soft:true,nomatch:{title:"No suggested matches",
heading:"Tips on getting better suggestions:",tips:["Enter more or fewer characters","Add words related to your original search","Try alternate spellings","Check your spelling","Toggle checkbox to include non-topics"]}});c&&d.filter.push("(any type:/common/topic)");return d},instance:function(c,d,e,f,g){var h=["type:"+c];a.each(["user","domain","type"],function(a,b){if(c==="/freebase/"+b+"_profile"){h.push("type:/type/"+b);return false}});c==="/book/book_subject"&&h.push("type:/base/skosbase/skos_concept");
var i=null;if(b.h.is_metaweb_system_type(c)||f)i=b.suggest_options.any.apply(null,h);else{i=b.suggest_options.should.apply(null,h);if(d)i.suggest_new="Create new"}if(e)i.lang=b.suggest_lang.lang(e);i.filter=[i.filter,"(all namespace:/m)"];g&&i.filter.push('(not mid:"'+g+'")');return i},cotype:function(){return a.extend({scoring:"schema"},b.suggest_options.all.apply(null,["type:/type/type","namespace:/m","(not namespace:/type)","(not namespace:/freebase)","(any (not namespace:/common) (any mid:/m/01c5 mid:/m/02_1_m4 mid:/m/03hc3d_))"]))},
included_type:function(){return b.suggest_options.cotype()},expected_type:function(){return a.extend({scoring:"schema"},b.suggest_options.all.apply(null,["type:/type/type","namespace:/m"]))},delegate_property:function(){return a.extend({scoring:"schema"},b.suggest_options.all.apply(null,["type:/type/property","(not namespace:/type/object)","namespace:/m"]))}}});a(function(){function c(){var d=a.localstore("fb-search-topic-only")!==false;e.suggest(b.suggest_options.search(d))}function d(){if(!e.data("dont_hide")&&
!k.is(":visible")&&g.is(":visible")){h.hide();a("#site-search-label").slideUp("fast");f.removeClass("active")}}var e=a("#fb-search-input"),f=a("#fb-search"),g=a("#site-search-label"),h=a("#site-search-topic-option").mousedown(function(){e.data("dont_hide",true)}).mouseup(function(){e.data("dont_hide",false)}),i=a(":checkbox",h).change(function(){var b=a(this).is(":checked");a.localstore("fb-search-topic-only",!b);c();e.focus().trigger("textchange")});a.localstore("fb-search-topic-only")===false&&
i.attr("checked","checked");c();var k=a("#site-search-box .fbs-pane");e.bind("fb-select",function(c,d){var e={};a(this).siblings("input[type=hidden]").each(function(){e[this.name]=this.value});var f;f=d.id;f=f.indexOf("/en/")==0?d.mid||f:d.notable&&b.h.is_metaweb_system_type(d.notable.id)?f:d.mid||f;window.location.href=b.h.fb_url(f,e);return false}).bind("fb-pane-show",function(){g.html("<span>Select an item from the list</span>").removeClass("loading");h.show()}).bind("fb-textchange",function(){a.trim(e.val())===
""?g.html("<span>Start typing to get some suggestions</span>").removeClass("loading"):g.html("<span>Searching...</span>").addClass("loading");h.hide()}).bind("fb-error",function(){g.html("<span>Sorry, something went wrong. Please try again later</span>").removeClass("loading");h.hide()}).focus(function(){if(!g.is(":visible")){a("#site-search-label").slideDown("fast");f.addClass("active")}}).blur(function(){setTimeout(d,0)});e.parent("form").submit(function(){i.is(":checked")||a(this).append('<input type="hidden" name="any" value="/common/topic">');
return true})});b.disable=function(b){a(b).attr("disabled","disabled").addClass("disabled")};b.enable=function(b){a(b).removeAttr("disabled").removeClass("disabled")};b.lang_select=function(b,c){if(c==="/lang/en"){a(this).removeAttr("name");if(!a(":input[name]",this.form).length){window.location=a(this.form).attr("action");return}}this.form.submit()};b.devbar={div:a("#devbar"),touch:function(){/\.(freebase|sandbox\-freebase)\.com$/.test(b.acre.request.server_name)?a.ajax({url:b.acre.freebase.googleapis_url?
b.h.fb_googleapis_url("/touch"):b.h.fb_api_url("/api/service/touch"),dataType:"jsonp"}):a.ajax({url:"/acre/touch"});return false},txn_ids:[],txn:function(){return b.devbar.view_txn(this.href,b.devbar.txn_ids)},view_txn:function(b,c){if(c&&c.length)window.location=b+"?"+a.param({tid:c},true);return false},ajaxComplete:function(a){if(a&&a.readyState===4)(a=a.getResponseHeader("x-metaweb-tid"))&&b.devbar.txn_ids.push(a)},init:function(){$nav_user_controls=a(".nav-user-controls");$user_controls=a("#user-controls");
a("#signedin .trigger").click(function(){if($user_controls.is(":hidden")){$user_controls.fadeIn();$nav_user_controls.addClass("active")}else{$user_controls.fadeOut();$nav_user_controls.removeClass("active")}return false});a("html").click(function(){if($user_controls.is(":visible")){$user_controls.fadeOut();$nav_user_controls.removeClass("active")}});$user_controls.click(function(a){a.stopPropagation()});a("#devbar-touch > a").click(b.devbar.touch);b.tid&&b.devbar.txn_ids.push(b.tid);a("#devbar-txn > a").click(b.devbar.txn);
a.ajaxSetup({complete:function(){b.devbar.ajaxComplete.apply(null,arguments)},error:function(b){a.each(["url","data","dataType","type"],function(){});a.each(["status","statusText","responseText"],function(){});b.getAllResponseHeaders()}})}};b.devbar.init();b.mqlread=function(c,d,e){var f;if(b.acre.freebase.googleapis_url){f=b.h.fb_googleapis_url("/mqlread");c={query:JSON.stringify(c),key:b.acre.freebase.api_key}}else{f=b.h.fb_api_url("/api/service/mqlread");c={query:JSON.stringify({query:c})}}return a.ajax({url:f,
data:c,dataType:"jsonp",success:function(a){d&&d.apply(this,[a.result])},error:function(){e&&e.apply(this,arguments)}})};a(function(){var c=b,d=a("#fb-topic-hover-pane").hover(function(){clearTimeout(b.hover.hide_timer_)},function(){b.hover.hide_now_()});c.hover={pane:d,current_target:null,cache:{},search_url:b.h.fb_googleapis_url()+"/search?filter=(all mid:${id})&output=(notable:/client/summary description type)&key="+b.acre.freebase.api_key+"&lang="+b.suggest_lang.lang(),image_url:b.h.fb_googleapis_url()+
"/image${id}?maxwidth=75&errorid=/freebase/no_image_png&key="+b.acre.freebase.api_key,show:function(c){clearTimeout(b.hover.hide_timer_);var d=c.target,e=a(d).attr("data-id");if(e){b.hover.current_target=d;a(d).removeAttr("title");b.hover.cache[e]?b.hover.show_now_(d,b.hover.cache[e]):a.ajax({url:b.hover.search_url.replace(/\$\{id\}/g,e),success:function(c){if(c.result&&c.result.length){c=a.suggest.suggest.create_flyout(c.result[0],b.hover.image_url);b.hover.cache[e]=c;b.hover.show_now_(d,c)}},dataType:"jsonp",
cache:true})}},show_now_:function(c,d){if(c===b.hover.current_target){b.hover.pane.html(d);var e=b.hover.pane.height(),f=a(c).height(),g=a(c).offset(),h=g.left,g=g.top,g=g-a(document).scrollTop()+e<a(window).height()?g+f:g-e-f;b.hover.pane.css({top:g,left:h}).show()}},hide:function(){b.hover.hide_timer_=setTimeout(b.hover.hide_now_,100)},hide_now_:function(){b.hover.current_target=null;b.hover.pane.hide()}};b.keyboard_shortcut={cache_:{},add:function(a,c,d){var e=a.charCodeAt(0);!d&&e in b.keyboard_shortcut.cache_&&
console.warn("Overriding keyboard shortcut",a);b.keyboard_shortcut.cache_[e]=c}};b.on_mid_dblclick=function(a){a=a.target;if(document.body.createTextRange){var c=document.body.createTextRange();c.moveToElementText(a);c.select()}else if(window.getSelection){var b=window.getSelection(),c=document.createRange();c.selectNodeContents(a);b.removeAllRanges();b.addRange(c)}};a(document).keypress(function(c){if(c.altKey||c.ctrlKey||c.metaKey||c.shiftKey)return true;var d=c.charCode,c=c.target;if(b.keyboard_shortcut.cache_[d]&&
(c==document.body||c==document||c==window||c==a("html")[0])){b.keyboard_shortcut.cache_[d]();return false}return true});a("#page-content").on("mouseenter","a.property-value",b.hover.show).on("mouseleave","a.property-value",b.hover.hide);a(document.body).on("dblclick",".mid",b.on_mid_dblclick).on("click",".mid",b.on_mid_dblclick)})}})(jQuery,window.freebase);
(function(a,b){var h;if(!(h=a.type)){var f={};["Boolean","Number","String","Function","Array","Date","RegExp","Object"].forEach(function(a){f["[object "+a+"]"]=a.toLowerCase()});h=function(a){return a==null?String(a):f[Object.prototype.toString.call(a)]||"object"}}var g=b.h={type:h,parse_params:function(b){if(a.isArray(b)){var c={};a.each(b,function(a,b){c[b[0]]=b[1]});return c}return b},build_url:function(b){if(b&&b.indexOf("//")!==0&&b.indexOf("://")===-1)throw"Host must contain scheme: "+b;var c=
b||"",e,f;if(arguments.length>1){e=Array.prototype.slice.call(arguments);e.shift();for(var h=[],l=0,n=e.length;l<n;l++){var j=e[l];if(g.type(j)==="string")h.push(j);else{for(f={};l<n;l++)f=a.extend(f,g.parse_params(e[l]));break}}e=h.join("")}if(e&&e.indexOf("/")!==0)throw"Path must begin with a '/': "+e;e&&(c=c+e);c===""&&(c="/");a.isEmptyObject(f)||(c=c+("?"+a.param(f,true)));return c},fb_url:function(){var a=Array.prototype.slice.call(arguments);a.unshift(null);b.lang&&b.lang!=="/lang/en"&&a.push({lang:g.lang_code(b.lang)});
return g.build_url.apply(null,a)},ajax_url:function(){var a=Array.prototype.slice.call(arguments);a.unshift("/ajax");return g.reentrant_url.apply(null,a)},static_url:function(){var a=Array.prototype.slice.call(arguments);a.unshift("/static");return g.reentrant_url.apply(null,a)},reentrant_url:function(a,c){var c=g.resolve_reentrant_path(c),c=c.replace(/^\/\//,a+"/"),b=Array.prototype.slice.call(arguments,2);b.unshift(c);b.unshift(null);return g.build_url.apply(null,b)},resolve_reentrant_path:function(a){a=
a||"";if(a.indexOf("//")==0)return a;if(a.indexOf("lib/")===0)return b.acre.current_script.app.path+a.substring(3);a&&a[0]!="/"&&(a="/"+a);return b.acre.request.script.app.path+a},legacy_fb_url:function(){var a=Array.prototype.slice.call(arguments),c=b.acre.freebase.site_host.replace(/^(https?\:\/\/)([^\.]+)\./,"$1www.").replace(":"+b.acre.request.server_port,"");a.unshift(c);return g.build_url.apply(null,a)},fb_api_url:function(){var a=Array.prototype.slice.call(arguments);a.unshift(b.acre.freebase.service_url);
return g.build_url.apply(null,a)},fb_googleapis_url:function(){if(b.acre.freebase.googleapis_url){var a=Array.prototype.slice.call(arguments);a.unshift(b.acre.freebase.googleapis_url);return g.build_url.apply(null,a)}throw"fb.acre.freebase.googleapis_url is not defined";},wiki_url:function(a){var c=Array.prototype.slice.call(arguments);c.unshift("http://wiki.freebase.com","/wiki/");return g.build_url.apply(null,c)},lib_base_url:function(a){a=b.acre.metadata.libs[a];return a.base_url+a.version},image_url:function(a,
c){return b.acre.freebase.imgurl(a,c.maxwidth,c.maxheight,c.mode,c.pad,c.errorid)},is_metaweb_system_type:function(a){return a.indexOf("/type/")===0||a.indexOf("/common/")===0&&a!=="/common/topic"||a.indexOf("/freebase/")===0&&a.indexOf("_profile")===a.length-8},id_key:function(a,c){var b=a.split("/"),f=b.pop();if(c){b=b.join("/");b===""&&(b="/");return[b,f]}return f},lang_code:function(a){return g.id_key(a)},lang_id:function(a){return"/lang/"+g.lang_code(a)}}})(jQuery,window.freebase);
(function(a,b){var h=b.permission={init:function(){if(b.access=="readonly"){a(".edit").hide();a(".no-edit").show()}else if(b.user){var f=b.c;f&&f.id&&a.ajax({url:b.h.ajax_url("lib/permission/has_permission.ajax"),data:{id:f.id,user_id:b.user.id},dataType:"json",success:function(b){h.has_permission=b.result&&b.result[f.id]===true;a(window).trigger("fb.permission.has_permission",h.has_permission)}});check_permissioned_objects(a(".edit-perm"),b.user.id)}else setTimeout(function(){h.has_permission=false;
a(window).trigger("fb.permission.has_permission",h.has_permission)})}};a(window).bind("fb.user.signedin",h.init);a(window).bind("fb.user.signedout",h.init);a(window).bind("fb.permission.has_permission",function(b,g){g?a(".edit").show():a(".no-edit").show()})})(jQuery,window.freebase);
function check_permissioned_objects(a,b){if(a.length&&b){var h={},f=[];$.each(a,function(){var a=$(this).metadata().id;if(a&&!h[a]){f.push(a);h[a]=1}});f.length&&$.ajax({url:fb.h.ajax_url("lib/permission/has_permission.ajax"),data:{id:f,user_id:b},traditional:true,dataType:"json",success:function(b){var d=b.result||{};$.each(a,function(){var a=$(this).metadata().id;a&&d[a]===true?$(this).show():$(this).addClass("edit-perm-lock")})}})}}
(function(a,b){var h=b.incompatible_types={overlay_dialog:null,inline_dialog:null,suggest_options:function(b,g,d){var d=d||{},g=[b].concat(g||[]),c=d.filter;if(!a.isArray(c)){c=[];c!=null&&c.push(d.filter);d.filter=c}c.push("(should (not incompatible:"+b+"))");d.filter=c;if(b=d.output)(c=/^\((.*)\)$/.exec(d.output))&&(b="("+h.search_output_(g)+" "+c[1]+")");b||(b=h.search_output_(g,true));d.output=b;return d},search_output_:function(a,b){var d=a.map(function(a){return"incompatible:"+a}).join(" ");
b&&(d="("+d+")");return d},check:function(b,g,d,c){var c=c||{},e=false,h=b.output;if(h){var k=[g].concat(d||[]);a.each(k,function(a,b){var c="incompatible:"+b;if(h[c]["/type/object/type"][0]==="true"||h[c]["/type/object/type"][0]===true)e=true;return!e})}e?c.incompatible&&c.incompatible(b,g,d):c.compatible&&c.compatible(b,g,d)},search:function(f,g,d,c){var e=[g].concat(d||[]),e={filter:"(all mid:"+f+")",output:h.search_output_(e,true),key:b.acre.freebase.api_key};a.ajax({url:b.h.fb_googleapis_url("/search",
e),dataType:"jsonp",success:function(b){a.isArray(b.result)&&b.result.length>0?h.check(b.result[0],g,d,c):c.compatible&&c.compatible({id:f},g,d)}})},overlay_incompatible_callback:function(b,g){if(!h.overlay_dialog)h.overlay_dialog=a(".incompatible-overlay-dialog");if(h.overlay_dialog.length){b=b||{};return function(d,c,e){h.overlay_dialog.removeData("overlay");a(".modal-content",h.overlay_dialog).empty().append(h.description_html(d,c,e));h.overlay_dialog.overlay({close:"button",closeOnClick:false,
load:true,fixed:false,mask:{color:"#000",loadSpeed:200,opacity:0.5},onClose:function(){g&&g.focus().select();a("button",h.overlay_dialog).unbind();if(b.onClose)b.onClose()},onLoad:function(){a(".cancel",h.overlay_dialog).focus().click(function(){g&&g.focus().select().trigger("textchange");if(b.onCancel)b.onCancel()});a(".save",h.overlay_dialog).click(function(){g&&g.focus().select();if(b.onConfirm)b.onConfirm(d,c,e)});if(b.onLoad)b.onLoad()}})}}return h.native_confirm_incompatible_callback(b,g)},
inline_incompatible_callback:function(b,g){if(!h.inline_dialog)h.inline_dialog=a(".incompatible-inline-dialog");if(h.inline_dialog.length){b=b||{};return function(d,c,e){a(".modal-content",h.inline_dialog).empty().append(h.description_html(d,c,e));a(".save",h.inline_dialog).unbind().click(function(){g.focus().select();if(b.onConfirm)b.onConfirm(d,c,e);h.inline_dialog.hide(b.onClose)});a(".cancel",h.inline_dialog).unbind().click(function(){g.focus().select().trigger("textchange");if(b.onCancel)b.onCancel();
h.inline_dialog.hide(b.onClose)});var i=g.offsetParent(),k=g.position();i.append(h.inline_dialog);h.inline_dialog.css({top:k.top+g.outerHeight(),left:k.left});h.inline_dialog.show(b.onLoad)}}return h.native_confirm_incompatible_callback(b,g)},native_confirm_incompatible_callback:function(a,b){a=a||{};return function(d,c,e){if(confirm(h.description_text(d,c,e))){b&&b.focus().select();if(a.onConfirm)a.onConfirm(d,c,e)}else{b&&b.focus().select().trigger("textchange");if(a.onCancel)a.onCancel()}if(a.onClose)a.onClose();
b&&b.focus().select()}},description_html:function(b,g){var d=a("<p>"),c;c=a('<div><b class="incompatible-topic"></b> is incompatible with <b class="incompatible-type"></b>.</div>');a(".incompatible-topic",c).text(b.name||b.id);a(".incompatible-type",c).text(g);d.append(c);c=a('<div>If you continue, <b class="incompatible-topic"></b> will be typed as <b class="incompatible-type"></b> and its included types (if any).</div>');a(".incompatible-topic",c).text(b.name||b.id);a(".incompatible-type",c).text(g);
d.append(c);d.append("<p>Are you sure you want to continue?<p>");return d},description_text:function(a,b,d){return h.description_html(a,b,d).text()}}})(jQuery,window.freebase);
(function(a,b){var h=b.flag={merge:function(a){return h.flag(a,"merge_begin")},split:function(a){return h.flag(a,"split_begin")},"delete":function(a){return h.flag(a,"delete_begin")},offensive:function(a){return h.flag(a,"offensive_begin")},flag:function(f,g){f=a(f);b.get_script(b.h.static_url("lib/flag/flag-edit.mf.js"),function(){h.edit[g](f)});return false},undo:function(f,g){f=a(f);b.get_script(b.h.static_url("lib/flag/flag-edit.mf.js"),function(){h.edit.undo_begin(f,g)});return false}}})(jQuery,
window.freebase);
(function(a){function b(){f();a(this).parents(".headmenu").data("submenu").find("a:first").click();return false}function h(b,d){var c=a(this),e=c.data("menu"),h=c.data("submenu");e.addClass("active");if(!h.is(".submenu-valid")){var e=c.offset(),k=c.outerHeight(),k=e.top+k;if(h.is(".center")){c=c.outerWidth();c=e.left+c/2-h.outerWidth()/2}else if(h.is(".right")){c=c.outerWidth();c=e.left+c-h.outerWidth()}else c=e.left;c={display:"none",position:"absolute",top:k,left:c};d.overlay&&(c.zIndex=d.overlay.css("zIndex"));
h.css(c);a(document.body).append(h);h.addClass(".submenu-valid")}if(h.is(":visible"))f(h);else{f();h.fadeIn()}return false}function f(b){b=b||a(".submenu:visible");b.data("menu")&&b.data("menu").removeClass("active");b.hide()}a.factory("nicemenu",{init:function(){var g=this.options;a(".headmenu",this.element).each(function(){var d=a(this),c=d.next(".submenu"),e=d.parents(".nicemenu");d.data("submenu",c);d.data("menu",e);c.data("headmenu",d);c.data("menu",e);a(".default-action",d).click(b);d.click(function(a){return h.apply(this,
[a,g])})});a(".submenu",this.element).click(function(){f(a(this));a(this).fadeOut()})}});a(document).click(function(){f()})})(jQuery);
(function(a,b){a(function(){a(".nicemenu").nicemenu();a("#description").css("height","auto");var h=a("#page-header .creation-timestamp").width();a("#page-header h1").css("margin-right",h);b.init_search();var f=function(){var a=null,b=null;if(g.is(":visible")){b=g;a=d}else{b=d;a=g}b.fadeOut();a.fadeIn(function(){setTimeout(f,6E3)})},g=a("#page-header .topics-count").first(),d=a("#page-header .topics-count").last();d.hide();setTimeout(f,6E3)});b.nav_ajax=function(h){a.getScript(h.href,function(){b.nav_ajax.begin(h)});
return false};b.init_search=function(){var b=a("#header #fb-search-input");a(document).keydown(function(a){if(b.is(":focus"))a.keyCode===27&&b.blur();else if(!(this!==event.target&&(/textarea|select/i.test(event.target.nodeName)||event.target.type==="text"))&&a.keyCode===191){b.focus();return false}})}})(jQuery,window.freebase);
