[
  "flot/flot.core.mf.js",
  "flot/js/jquery.flot.fillbetween.js",
  "flot/js/jquery.flot.navigate.js",
  "flot/js/jquery.flot.stack.js",
  "flot/js/jquery.flot.image.js",
  "flot/js/jquery.flot.pie.js",
  "flot/js/jquery.flot.threshold.js",
  "flot/js/jquery.flot.crosshair.js",
  "flot/js/jquery.flot.selection.js"
]
