
/*
 * Copyright 2012, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Additional Licenses for Third Party components can be found here:
 * http://wiki.freebase.com/wiki/Freebase_Site_License
 *
 */
/*
 
 jQuery Tools @VERSION Tooltip - UI essentials

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/tooltip/

 Since: November 2008
 Date: @DATE 
*/
(function(c){c.extend({tablesorter:new function(){function b(a,c){d(a+","+((new Date).getTime()-c.getTime())+"ms")}function d(a){"undefined"!=typeof console&&"undefined"!=typeof console.debug?console.log(a):alert(a)}function g(b,e){var g="";if(0!=b.tBodies.length){var l=b.tBodies[0].rows;if(l[0])for(var i=[],J=l[0].cells.length,k=0;k<J;k++){var o=!1;c.metadata&&c(e[k]).metadata()&&c(e[k]).metadata().sorter?o=a(c(e[k]).metadata().sorter):b.config.headers[k]&&b.config.headers[k].sorter&&(o=a(b.config.headers[k].sorter));
if(!o)a:{for(var o=b,u=l,w=-1,p=k,m=q.length,s=!1,n=!1,j=!0;""==n&&j;)w++,u[w]?(s=u[w].cells[p],n=c.trim(f(o.config,s)),o.config.debug&&d("Checking if value was empty on row:"+w)):j=!1;for(u=1;u<m;u++)if(q[u].is(n,o,s)){o=q[u];break a}o=q[0]}b.config.debug&&(g+="column:"+k+" parser:"+o.id+"\n");i.push(o)}b.config.debug&&d(g);return i}}function a(a){for(var c=q.length,b=0;b<c;b++)if(q[b].id.toLowerCase()==a.toLowerCase())return q[b];return!1}function e(a){var e;a.config.debug&&(e=new Date);for(var d=
a.tBodies[0]&&a.tBodies[0].rows.length||0,g=a.tBodies[0].rows[0]&&a.tBodies[0].rows[0].cells.length||0,h=a.config.parsers,i={row:[],normalized:[]},k=0;k<d;++k){var o=c(a.tBodies[0].rows[k]),p=[];if(o.hasClass(a.config.cssChildRow))i.row[i.row.length-1]=i.row[i.row.length-1].add(o);else{i.row.push(o);for(var m=0;m<g;++m)p.push(h[m].format(f(a.config,o[0].cells[m]),a,o[0].cells[m]));p.push(i.normalized.length);i.normalized.push(p)}}a.config.debug&&b("Building cache for "+d+" rows:",e);return i}function f(a,
b){var e="";if(!b)return"";a.supportsTextContent||(a.supportsTextContent=b.textContent||!1);return e="simple"==a.textExtraction?a.supportsTextContent?b.textContent:b.childNodes[0]&&b.childNodes[0].hasChildNodes()?b.childNodes[0].innerHTML:b.innerHTML:"function"==typeof a.textExtraction?a.textExtraction(b):c(b).text()}function i(a,e){var d;a.config.debug&&(d=new Date);for(var g=e.row,f=e.normalized,i=f.length,h=f[0].length-1,k=c(a.tBodies[0]),m=[],n=0;n<i;n++){var j=f[n][h];m.push(g[j]);if(!a.config.appender)for(var q=
g[j].length,s=0;s<q;s++)k[0].appendChild(g[j][s])}a.config.appender&&a.config.appender(a,m);m=null;a.config.debug&&b("Rebuilt table:",d);p(a);setTimeout(function(){c(a).trigger("sortEnd")},0)}function k(a,b){return a.config.headers[b]&&a.config.headers[b].lockedOrder?a.config.headers[b].lockedOrder:!1}function p(a){for(var b=a.config.widgets,c=b.length,e=0;e<c;e++)n(b[e]).format(a)}function n(a){for(var b=r.length,c=0;c<b;c++)if(r[c].id.toLowerCase()==a.toLowerCase())return r[c]}function y(a,b,e,
d){b.removeClass(d[0]).removeClass(d[1]);var g=[];b.each(function(){this.sortDisabled||(g[this.column]=c(this))});a=e.length;for(b=0;b<a;b++)g[e[b][0]].addClass(d[e[b][1]])}function m(a,c,e){var d,g;a.config.debug&&(d=new Date);var f="var sortWrapper = function(a,b) {",i=c.length;for(g=0;g<i;g++)var h=c[g][0],k=c[g][1],h="text"==a.config.parsers[h].type?0==k?j("text","asc",h):j("text","desc",h):0==k?j("numeric","asc",h):j("numeric","desc",h),m="e"+g,f=f+("var "+m+" = "+h),f=f+("if("+m+") { return "+
m+"; } "),f=f+"else { ";g=e.normalized[0].length-1;f+="return a["+g+"]-b["+g+"];";for(g=0;g<i;g++)f+="}; ";f+="return 0; }; ";a.config.debug&&b("Evaling expression:"+f,new Date);eval(f);e.normalized.sort(sortWrapper);a.config.debug&&b("Sorting on "+c.toString()+" and dir "+k+" time:",d);return e}function j(a,b,c){var e="a["+c+"]",c="b["+c+"]";if("text"==a&&"asc"==b)return"("+e+" == "+c+" ? 0 : ("+e+" === null ? Number.POSITIVE_INFINITY : ("+c+" === null ? Number.NEGATIVE_INFINITY : ("+e+" < "+c+") ? -1 : 1 )));";
if("text"==a&&"desc"==b)return"("+e+" == "+c+" ? 0 : ("+e+" === null ? Number.POSITIVE_INFINITY : ("+c+" === null ? Number.NEGATIVE_INFINITY : ("+c+" < "+e+") ? -1 : 1 )));";if("numeric"==a&&"asc"==b)return"("+e+" === null && "+c+" === null) ? 0 :("+e+" === null ? Number.POSITIVE_INFINITY : ("+c+" === null ? Number.NEGATIVE_INFINITY : "+e+" - "+c+"));";if("numeric"==a&&"desc"==b)return"("+e+" === null && "+c+" === null) ? 0 :("+e+" === null ? Number.POSITIVE_INFINITY : ("+c+" === null ? Number.NEGATIVE_INFINITY : "+
c+" - "+e+"));"}var q=[],r=[];this.defaults={cssHeader:"header",cssAsc:"headerSortUp",cssDesc:"headerSortDown",cssChildRow:"expand-child",sortInitialOrder:"asc",sortMultiSortKey:"shiftKey",sortForce:null,sortAppend:null,sortLocaleCompare:!0,textExtraction:"simple",parsers:{},widgets:[],widgetZebra:{css:["even","odd"]},headers:{},widthFixed:!1,cancelSelection:!0,sortList:[],headerList:[],dateFormat:"us",decimal:"/.|,/g",onRenderHeader:null,selectorHeaders:"thead th",debug:!1};this.benchmark=b;this.construct=
function(a){return this.each(function(){if(this.tHead&&this.tBodies){var v,A,l;this.config={};l=c.extend(this.config,c.tablesorter.defaults,a);v=c(this);c.data(this,"tablesorter",l);var j=this,q;j.config.debug&&(q=new Date);for(var r=[],o={},u=j.getElementsByTagName("THEAD")[0].getElementsByTagName("TR"),w=0;w<u.length;w++)for(var G=u[w].cells,D=0;D<G.length;D++){var s=G[D],x=s.parentNode.rowIndex,E=x+"-"+s.cellIndex,K=s.rowSpan||1,s=s.colSpan||1,C;"undefined"==typeof r[x]&&(r[x]=[]);var t;for(t=
0;t<r[x].length+1;t++)if("undefined"==typeof r[x][t]){C=t;break}o[E]=C;for(t=x;t<x+K;t++){"undefined"==typeof r[t]&&(r[t]=[]);for(var E=r[t],F=C;F<C+s;F++)E[F]="x"}}var B=c(j.config.selectorHeaders,j).each(function(a){this.column=o[this.parentNode.rowIndex+"-"+this.cellIndex];this.count=this.order="Number"!=typeof j.config.sortInitialOrder?"desc"==j.config.sortInitialOrder.toLowerCase()?1:0:1==j.config.sortInitialOrder?1:0;if(c.metadata&&!1===c(this).metadata().sorter||j.config.headers[a]&&!1===j.config.headers[a].sorter)this.sortDisabled=
!0;k(j,a)&&(this.order=this.lockedOrder=k(j,a));if(!this.sortDisabled){var b=c(this).addClass(j.config.cssHeader);j.config.onRenderHeader&&j.config.onRenderHeader.apply(b)}j.config.headerList[a]=this});j.config.debug&&(b("Built headers:",q),d(B));this.config.parsers=g(this,B);A=e(this);var H=[l.cssDesc,l.cssAsc];if(this.config.widthFixed){var I=c("<colgroup>");c("tr:first td",this.tBodies[0]).each(function(){I.append(c("<col>").css("width",c(this).width()))});c(this).prepend(I)}B.click(function(a){var b=
v[0].tBodies[0]&&v[0].tBodies[0].rows.length||0;if(!this.sortDisabled&&b>0){v.trigger("sortStart");c(this);b=this.column;this.order=this.count++%2;if(this.lockedOrder)this.order=this.lockedOrder;if(a[l.sortMultiSortKey]){a:{for(var a=l.sortList,e=a.length,g=0;g<e;g++)if(a[g][0]==b){a=true;break a}a=false}if(a)for(a=0;a<l.sortList.length;a++){e=l.sortList[a];g=l.headerList[e[0]];if(e[0]==b){g.count=e[1];g.count++;e[1]=g.count%2}}else l.sortList.push([b,this.order])}else{l.sortList=[];if(l.sortForce!=
null){e=l.sortForce;for(a=0;a<e.length;a++)e[a][0]!=b&&l.sortList.push(e[a])}l.sortList.push([b,this.order])}setTimeout(function(){y(v[0],B,l.sortList,H);i(v[0],m(v[0],l.sortList,A))},1);return false}}).mousedown(function(){if(l.cancelSelection){this.onselectstart=function(){return false};return false}});v.bind("update",function(){var a=this;setTimeout(function(){a.config.parsers=g(a,B);A=e(a)},1)}).bind("updateCell",function(a,b){var e=this.config,c=[b.parentNode.rowIndex-1,b.cellIndex];A.normalized[c[0]][c[1]]=
e.parsers[c[1]].format(f(e,b),b)}).bind("sorton",function(a,b){c(this).trigger("sortStart");l.sortList=b;for(var e=l.sortList,g=this.config,f=e.length,d=0;d<f;d++){var h=e[d],k=g.headerList[h[0]];k.count=h[1];k.count++}y(this,B,e,H);i(this,m(this,e,A))}).bind("appendCache",function(){i(this,A)}).bind("applyWidgetId",function(a,b){n(b).format(this)}).bind("applyWidgets",function(){p(this)});c.metadata&&(c(this).metadata()&&c(this).metadata().sortlist)&&(l.sortList=c(this).metadata().sortlist);0<l.sortList.length&&
v.trigger("sorton",[l.sortList]);p(this)}})};this.addParser=function(a){for(var b=q.length,e=!0,c=0;c<b;c++)q[c].id.toLowerCase()==a.id.toLowerCase()&&(e=!1);e&&q.push(a)};this.addWidget=function(a){r.push(a)};this.formatFloat=function(a){a=parseFloat(a);return isNaN(a)?0:a};this.formatInt=function(a){a=parseInt(a);return isNaN(a)?0:a};this.isDigit=function(a){return/^[-+]?\d*$/.test(c.trim(a.replace(/[,.']/g,"")))};this.clearTableBody=function(a){c.browser.msie?function(){for(;this.firstChild;)this.removeChild(this.firstChild)}.apply(a.tBodies[0]):
a.tBodies[0].innerHTML=""}}});c.fn.extend({tablesorter:c.tablesorter.construct});var d=c.tablesorter;d.addParser({id:"text",is:function(){return!0},format:function(b){return c.trim(b.toLocaleLowerCase())},type:"text"});d.addParser({id:"digit",is:function(b,d){return c.tablesorter.isDigit(b,d.config)},format:function(b){return c.tablesorter.formatFloat(b)},type:"numeric"});d.addParser({id:"currency",is:function(b){return/^[\u00a3$\u20ac?.]/.test(b)},format:function(b){return c.tablesorter.formatFloat(b.replace(RegExp(/[\u00a3$\u20ac]/g),
""))},type:"numeric"});d.addParser({id:"ipAddress",is:function(b){return/^\d{2,3}[\.]\d{2,3}[\.]\d{2,3}[\.]\d{2,3}$/.test(b)},format:function(b){for(var b=b.split("."),d="",g=b.length,a=0;a<g;a++)var e=b[a],d=2==e.length?d+("0"+e):d+e;return c.tablesorter.formatFloat(d)},type:"numeric"});d.addParser({id:"url",is:function(b){return/^(https?|ftp|file):\/\/$/.test(b)},format:function(b){return jQuery.trim(b.replace(RegExp(/(https?|ftp|file):\/\//),""))},type:"text"});d.addParser({id:"isoDate",is:function(b){return/^\d{4}[\/-]\d{1,2}[\/-]\d{1,2}$/.test(b)},
format:function(b){return c.tablesorter.formatFloat(""!=b?(new Date(b.replace(RegExp(/-/g),"/"))).getTime():"0")},type:"numeric"});d.addParser({id:"percent",is:function(b){return/\%$/.test(c.trim(b))},format:function(b){return c.tablesorter.formatFloat(b.replace(RegExp(/%/g),""))},type:"numeric"});d.addParser({id:"usLongDate",is:function(b){return b.match(RegExp(/^[A-Za-z]{3,10}\.? [0-9]{1,2}, ([0-9]{4}|'?[0-9]{2}) (([0-2]?[0-9]:[0-5][0-9])|([0-1]?[0-9]:[0-5][0-9]\s(AM|PM)))$/))},format:function(b){return c.tablesorter.formatFloat((new Date(b)).getTime())},
type:"numeric"});d.addParser({id:"shortDate",is:function(b){return/\d{1,2}[\/\-]\d{1,2}[\/\-]\d{2,4}/.test(b)},format:function(b,d){var g=d.config,b=b.replace(/\-/g,"/");if("us"==g.dateFormat)b=b.replace(/(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{4})/,"$3/$1/$2");else if("uk"==g.dateFormat)b=b.replace(/(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{4})/,"$3/$2/$1");else if("dd/mm/yy"==g.dateFormat||"dd-mm-yy"==g.dateFormat)b=b.replace(/(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{2})/,"$1/$2/$3");return c.tablesorter.formatFloat((new Date(b)).getTime())},
type:"numeric"});d.addParser({id:"time",is:function(b){return/^(([0-2]?[0-9]:[0-5][0-9])|([0-1]?[0-9]:[0-5][0-9]\s(am|pm)))$/.test(b)},format:function(b){return c.tablesorter.formatFloat((new Date("2000/01/01 "+b)).getTime())},type:"numeric"});d.addParser({id:"metadata",is:function(){return!1},format:function(b,d,g){b=d.config;b=!b.parserMetadataName?"sortValue":b.parserMetadataName;return c(g).metadata()[b]},type:"numeric"});d.addWidget({id:"zebra",format:function(b){var d;b.config.debug&&(d=new Date);
var g,a=-1,e;c("tr:visible",b.tBodies[0]).each(function(){g=c(this);g.hasClass(b.config.cssChildRow)||a++;e=0==a%2;g.removeClass(b.config.widgetZebra.css[e?0:1]).addClass(b.config.widgetZebra.css[e?1:0])});b.config.debug&&c.tablesorter.benchmark("Applying Zebra widget",d)}})})(jQuery);
(function(c){c(function(){c.tablesorter&&(c("<div>"),c.tablesorter.defaults.cssAsc="column-header-asc",c.tablesorter.defaults.cssDesc="column-header-desc",c.tablesorter.defaults.cssHeader="column-header",c.tablesorter.addParser({id:"datetime",is:function(){return!1},format:function(d,b,h){return c("[datetime]:first",h).attr("datetime")},type:"text"}),c.tablesorter.addParser({id:"ignoreCase",is:function(){return!1},format:function(c){return c.toLowerCase()},type:"text"}),c.tablesorter.addParser({id:"string",
is:function(){return!1},format:function(c){return c},type:"text"}),c.tablesorter.addParser({id:"number",is:function(){return!1},format:function(d,b,h){d=c(".number:first",h).attr("data-value");null==d&&(d=Number.MIN_VALUE);return d},type:"numeric"}),c(".table-sortable").each(function(){c(this).tablesorter()}))})})(jQuery);
(function(c){c.factory("collapse_module",{init:function(){var b=this;this.$column=c(this.options.column);this.modules=c(this.options.modules,this.element);this.first_module=this.modules.get(0);this.trigger=c(".trigger:first",this.first_module);this.first_section=c(".module-section",this.first_module);this.other_modules=this.modules.slice(1);this.column_offset=this.$column.css("margin-left");this.set_collapsed(this.options.collapsed);this.trigger.click(function(c){return b.toggle(c)})},set_collapsed:function(b){(this.toggle_state=
b)?(this.trigger.addClass("collapsed"),this.$column.css("margin-left",0),this.first_section.hide(),this.other_modules.hide()):(this.trigger.removeClass("collapsed"),this.$column.css("margin-left",this.column_offset),this.first_section.show(),this.other_modules.show())},toggle:function(){var b=this;this.toggle_state?(c.localstore("filters_collapsed",0,!1),this.trigger.removeClass("collapsed"),this.$column.animate({marginLeft:this.column_offset},function(){b.first_section.slideDown(function(){b.modules.removeClass("collapsed")});
b.other_modules.fadeIn()})):(c.localstore("filters_collapsed",1,!1),this.trigger.addClass("collapsed"),this.other_modules.fadeOut(),this.first_section.slideUp(function(){b.$column.animate({marginLeft:0});b.modules.addClass("collapsed")}));this.toggle_state=!this.toggle_state;this.options.toggle_callback&&this.options.toggle_callback.call(this.trigger,this.toggle_state);return!1}});var d=c("body").is(".embed")||c.localstore("filters_collapsed");c.extend(!0,c.collapse_module,{defaults:{collapsed:null===
d?!1:!!d,modules:".module",column:"#main-column"}})})(jQuery);
(function(c){function d(b,a,c){var d=c.relative?b.position().top:b.offset().top,i=c.relative?b.position().left:b.offset().left,k=c.position[0],d=d-(a.outerHeight()-c.offset[0]),i=i+(b.outerWidth()+c.offset[1]),h=a.outerHeight()+b.outerHeight();"center"==k&&(d+=h/2);"bottom"==k&&(d+=h);k=c.position[1];b=a.outerWidth()+b.outerWidth();"center"==k&&(i-=b/2);"left"==k&&(i-=b);return{top:d,left:i}}function b(b,a){var e=this,f=b.add(e),i,k=0,p=0,n=b.attr("title"),y=h[a.effect],m,j=b.is(":input"),q=j&&b.is(":checkbox, :radio, select, :button, :submit"),
r=b.attr("type"),z=a.events[r]||a.events[j?q?"widget":"input":"def"];if(!y)throw'Nonexistent effect "'+a.effect+'"';z=z.split(/,\s*/);if(2!=z.length)throw"Tooltip: bad events configuration for "+r;b.bind(z[0],function(b){clearTimeout(k);a.predelay?p=setTimeout(function(){e.show(b)},a.predelay):e.show(b)}).bind(z[1],function(b){clearTimeout(p);a.delay?k=setTimeout(function(){e.hide(b)},a.delay):e.hide(b)});n&&a.cancelDefault&&(b.removeAttr("title"),b.data("title",n));c.extend(e,{show:function(h){if(!i){if(n)i=
c(a.layout).addClass(a.tipClass).appendTo(document.body).hide().append(n);else if(a.tip)i=c(a.tip).eq(0);else{i=b.next();i.length||(i=b.parent().next())}if(!i.length)throw"Cannot find tooltip for "+b;}if(e.isShown())return e;i.stop(true,true);var j=d(b,i,a),h=h||c.Event();h.type="onBeforeShow";f.trigger(h,[j]);if(h.isDefaultPrevented())return e;j=d(b,i,a);i.css({position:"absolute",top:j.top,left:j.left});m=true;y[0].call(e,function(){h.type="onShow";m="full";f.trigger(h)});j=a.events.tooltip.split(/,\s*/);
i.bind(j[0],function(){clearTimeout(k);clearTimeout(p)});j[1]&&!b.is("input:not(:checkbox, :radio), textarea")&&i.bind(j[1],function(a){a.relatedTarget!=b[0]&&b.trigger(z[1].split(" ")[0])});return e},hide:function(b){if(!i||!e.isShown())return e;b=b||c.Event();b.type="onBeforeHide";f.trigger(b);if(!b.isDefaultPrevented()){m=false;h[a.effect][1].call(e,function(){b.type="onHide";m=false;f.trigger(b)});return e}},isShown:function(a){return a?m=="full":m},getConf:function(){return a},getTip:function(){return i},
getTrigger:function(){return b}});c.each(["onHide","onBeforeShow","onShow","onBeforeHide"],function(b,d){c.isFunction(a[d])&&c(e).bind(d,a[d]);e[d]=function(a){c(e).bind(d,a);return e}})}c.tools=c.tools||{version:"@VERSION"};c.tools.tooltip={conf:{effect:"toggle",fadeOutSpeed:"fast",predelay:0,delay:30,opacity:1,tip:0,position:["top","center"],offset:[0,0],relative:!1,cancelDefault:!0,events:{def:"mouseenter,mouseleave",input:"focus,blur",widget:"focus mouseenter,blur mouseleave",tooltip:"mouseenter,mouseleave"},
layout:"<div/>",tipClass:"tooltip"},addEffect:function(b,a,c){h[b]=[a,c]}};var h={toggle:[function(b){var a=this.getConf(),c=this.getTip(),a=a.opacity;1>a&&c.css({opacity:a});c.show();b.call()},function(b){this.getTip().hide();b.call()}],fade:[function(b){var a=this.getConf();this.getTip().fadeTo(a.fadeInSpeed,a.opacity,b)},function(b){this.getTip().fadeOut(this.getConf().fadeOutSpeed,b)}]};c.fn.tooltip=function(d){var a=this.data("tooltip");if(a)return a;d=c.extend(!0,{},c.tools.tooltip.conf,d);
"string"==typeof d.position&&(d.position=d.position.split(/,?\s/));this.each(function(){a=new b(c(this),d);c(this).data("tooltip",a)});return d.api?a:this}})(jQuery);
(function(c,d){d.filters={init_domain_type_property_filter:function(b){c(":text[name=domain], :text[name=type], :text[name=property]",b).suggest(c.extend({scoring:"schema",format:null,mql_output:JSON.stringify([{id:null,name:null,type:{id:null,"id|=":["/type/domain","/type/type","/type/property"],limit:1}}])},d.suggest_options.any("type:/type/domain","type:/type/type","type:/type/property"))).bind("fb-select",function(b,d){var a=c(this);a.val(d.id);var e=d.type.id;"/type/domain"===e?a.attr("name",
"domain"):"/type/type"===e?a.attr("name","type"):"/type/property"===e&&a.attr("name","property");this.form.submit()}).parents(".filter-form").submit(function(){return!1})}};c(function(){c(".filter-form :input").keypress(function(b){13===b.keyCode&&this.form.submit();return!0});c(".filter-help-trigger").tooltip({events:{def:"click,mouseout"},position:"top center",effect:"fade",delay:300,offset:[-8,0]});c(".filter-form-trigger").click(function(){var b=c(this).siblings(".filter-form");b.is(":hidden")?
b.slideDown(function(){c(":text:first",b).focus()}):b.slideUp()})})})(jQuery,window.freebase);
(function(c,d,b){d.infinitescroll=function(a,b,c){this.element=d(c);this._create(a,b)};d.infinitescroll.defaults={loading:{finished:b,finishedMsg:"<em>Congratulations, you've reached the end of the internet.</em>",img:"http://www.infinite-scroll.com/loading.gif",msg:null,msgText:"<em>Loading the next set of posts...</em>",selector:null,speed:"fast",start:b},state:{isDuringAjax:!1,isInvalidPage:!1,isDestroyed:!1,isDone:!1,isPaused:!1,currPage:1},callback:b,debug:!1,behavior:b,binder:d(c),nextSelector:"div.navigation a:first",
navSelector:"div.navigation",contentSelector:null,extraScrollPx:150,itemSelector:"div.post",animate:!1,pathParse:b,dataType:"html",appendCallback:!0,bufferPx:40,errorCallback:function(){},infid:0,pixelsFromNavToBottom:b,path:b};d.infinitescroll.prototype={_binding:function(a){var c=this,d=c.options;if(d.behavior&&this["_binding_"+d.behavior]!==b)this["_binding_"+d.behavior].call(this);else{if("bind"!==a&&"unbind"!==a)return this._debug("Binding value  "+a+" not valid"),!1;if("unbind"==a)this.options.binder.unbind("smartscroll.infscr."+
c.options.infid);else this.options.binder[a]("smartscroll.infscr."+c.options.infid,function(){c.scroll()});this._debug("Binding",a)}},_create:function(a,c){if(!this._validate(a))return!1;var f=this.options=d.extend(!0,{},d.infinitescroll.defaults,a),g=d(f.nextSelector).attr("href");f.contentSelector=f.contentSelector||this.element;f.loading.selector=f.loading.selector||f.contentSelector;g?(f.path=this._determinepath(g),f.loading.msg=d('<div id="infscr-loading"><img alt="Loading..." src="'+f.loading.img+
'" /><div>'+f.loading.msgText+"</div></div>"),(new Image).src=f.loading.img,f.pixelsFromNavToBottom=d(document).height()-d(f.navSelector).offset().top,f.loading.start=f.loading.start||function(){d(f.navSelector).hide();f.loading.msg.appendTo(f.loading.selector).show(f.loading.speed,function(){beginAjax(f)})},f.loading.finished=f.loading.finished||function(){f.loading.msg.fadeOut("normal")},f.callback=function(a,g){f.behavior&&a["_callback_"+f.behavior]!==b&&a["_callback_"+f.behavior].call(d(f.contentSelector)[0],
g);c&&c.call(d(f.contentSelector)[0],g)},this._setup()):this._debug("Navigation selector not found")},_debug:function(){if(this.options.debug)return c.console&&console.log.call(console,arguments)},_determinepath:function(a){var c=this.options;if(c.behavior&&this["_determinepath_"+c.behavior]!==b)this["_determinepath_"+c.behavior].call(this,a);else{if(c.pathParse)return this._debug("pathParse manual"),"function"===typeof c.pathParse?c.pathParse():c.pathParse;if(a.match(/^(.*?)\b2\b(.*?$)/))a=a.match(/^(.*?)\b2\b(.*?$)/).slice(1);
else if(a.match(/^(.*?)2(.*?$)/)){if(a.match(/^(.*?page=)2(\/.*|$)/))return a=a.match(/^(.*?page=)2(\/.*|$)/).slice(1);a=a.match(/^(.*?)2(.*?$)/).slice(1)}else{if(a.match(/^(.*?page=)1(\/.*|$)/))return a=a.match(/^(.*?page=)1(\/.*|$)/).slice(1);this._debug("Sorry, we couldn't parse your Next (Previous Posts) URL. Verify your the css selector points to the correct A tag. If you still get this error: yell, scream, and kindly ask for help at infinite-scroll.com.");c.state.isInvalidPage=!0}this._debug("determinePath",
a);return a}},_error:function(a){var c=this.options;c.behavior&&this["_error_"+c.behavior]!==b?this["_error_"+c.behavior].call(this,a):("destroy"!==a&&"end"!==a&&(a="unknown"),this._debug("Error",a),"end"==a&&this._showdonemsg(),c.state.isDone=!0,c.state.currPage=1,c.state.isPaused=!1,this._binding("unbind"))},_loadcallback:function(a,e){var f=this.options,g=this.options.callback,h=f.state.isDone?"done":!f.appendCallback?"no-append":"append";if(f.behavior&&this["_loadcallback_"+f.behavior]!==b)this["_loadcallback_"+
f.behavior].call(this,a,e);else{switch(h){case "done":return this._showdonemsg(),!1;case "no-append":"html"==f.dataType&&(e=d("<div>"+e+"</div>").find(f.itemSelector));break;case "append":var p=a.children();if(0==p.length)return this._error("end");for(h=document.createDocumentFragment();a[0].firstChild;)h.appendChild(a[0].firstChild);this._debug("contentSelector",d(f.contentSelector)[0]);d(f.contentSelector)[0].appendChild(h);e=p.get()}f.loading.finished.call(d(f.contentSelector)[0],f);f.animate&&
(h=d(c).scrollTop()+d("#infscr-loading").height()+f.extraScrollPx+"px",d("html,body").animate({scrollTop:h},800,function(){f.state.isDuringAjax=!1}));f.animate||(f.state.isDuringAjax=!1);g(this,e)}},_nearbottom:function(){var a=this.options,e=0+d(document).height()-a.binder.scrollTop()-d(c).height();if(a.behavior&&this["_nearbottom_"+a.behavior]!==b)this["_nearbottom_"+a.behavior].call(this);else return this._debug("math:",e,a.pixelsFromNavToBottom),e-a.bufferPx<a.pixelsFromNavToBottom},_pausing:function(a){var c=
this.options;if(c.behavior&&this["_pausing_"+c.behavior]!==b)this["_pausing_"+c.behavior].call(this,a);else{"pause"!==a&&("resume"!==a&&null!==a)&&this._debug("Invalid argument. Toggling pause value instead");switch(a&&("pause"==a||"resume"==a)?a:"toggle"){case "pause":c.state.isPaused=!0;break;case "resume":c.state.isPaused=!1;break;case "toggle":c.state.isPaused=!c.state.isPaused}this._debug("Paused",c.state.isPaused);return!1}},_setup:function(){var a=this.options;if(a.behavior&&this["_setup_"+
a.behavior]!==b)this["_setup_"+a.behavior].call(this);else return this._binding("bind"),!1},_showdonemsg:function(){var a=this.options;a.behavior&&this["_showdonemsg_"+a.behavior]!==b?this["_showdonemsg_"+a.behavior].call(this):(a.loading.msg.find("img").hide().parent().find("div").html(a.loading.finishedMsg).animate({opacity:1},2E3,function(){d(this).parent().fadeOut("normal")}),a.errorCallback.call(d(a.contentSelector)[0],"done"))},_validate:function(a){for(var b in a)return b.indexOf&&-1<b.indexOf("Selector")&&
0===d(a[b]).length?(this._debug("Your "+b+" found no elements."),!1):!0},bind:function(){this._binding("bind")},destroy:function(){this.options.state.isDestroyed=!0;return this._error("destroy")},pause:function(){this._pausing("pause")},resume:function(){this._pausing("resume")},retrieve:function(a){var c=this,f=c.options,g=this._determinepath(g),h,p,n,y,a=a||null;beginAjax=function(a){a.state.currPage++;c._debug("heading into ajax",g);h=d(a.contentSelector).is("table")?d("<tbody/>"):d("<div/>");
p=g.join(a.state.currPage);n="html"==a.dataType||"json"==a.dataType?a.dataType:"html+callback";a.appendCallback&&"html"==a.dataType&&(n+="+callback");switch(n){case "html+callback":c._debug("Using HTML via .load() method");h.load(p+" "+a.itemSelector,null,function(a){c._loadcallback(h,a)});break;case "html":case "json":c._debug("Using "+n.toUpperCase()+" via $.ajax() method"),d.ajax({url:p,dataType:a.dataType,complete:function(a,b){(y="undefined"!==typeof a.isResolved?a.isResolved():"success"===b||
"notmodified"===b)?c._loadcallback(h,a.responseText):c._error("end")}})}};if(f.behavior&&this["retrieve_"+f.behavior]!==b)this["retrieve_"+f.behavior].call(this,a);else{if(f.state.isDestroyed)return this._debug("Instance is destroyed"),!1;f.state.isDuringAjax=!0;f.loading.start.call(d(f.contentSelector)[0],f)}},scroll:function(){var a=this.options,c=a.state;a.behavior&&this["scroll_"+a.behavior]!==b?this["scroll_"+a.behavior].call(this):!c.isDuringAjax&&!c.isInvalidPage&&!c.isDone&&!c.isDestroyed&&
!c.isPaused&&this._nearbottom()&&this.retrieve()},toggle:function(){this._pausing()},unbind:function(){this._binding("unbind")},update:function(a){d.isPlainObject(a)&&(this.options=d.extend(!0,this.options,a))}};d.fn.infinitescroll=function(a,b){switch(typeof a){case "string":var c=Array.prototype.slice.call(arguments,1);this.each(function(){var b=d.data(this,"infinitescroll");if(!b||!d.isFunction(b[a])||"_"===a.charAt(0))return!1;b[a].apply(b,c)});break;case "object":this.each(function(){var c=d.data(this,
"infinitescroll");c?c.update(a):d.data(this,"infinitescroll",new d.infinitescroll(a,b,this))})}return this};var h=d.event,g;h.special.smartscroll={setup:function(){d(this).bind("scroll",h.special.smartscroll.handler)},teardown:function(){d(this).unbind("scroll",h.special.smartscroll.handler)},handler:function(a,b){var c=this,h=arguments;a.type="smartscroll";g&&clearTimeout(g);g=setTimeout(function(){d.event.handle.apply(c,h)},"execAsap"===b?0:100)}};d.fn.smartscroll=function(a){return a?this.bind("smartscroll",
a):this.trigger("smartscroll",["execAsap"])}})(window,jQuery);(function(c){c.fn.fixedcolumn=function(d){var b=c.extend(!0,{},d);return this.each(function(){var d=c(this).find("tr:first").children();1<d.length&&(b.all||(d=c(d.get(0))),d.each(function(){var b=c(this),a=b[0].nodeName.toUpperCase();if("TD"===a||"TH"===a)a=b.width(),0<a&&c(":first-child",b).width(a).css("display","inline-block")}))})}})(jQuery);
(function(c,d){var b=d.triples={row_hoverover:function(){var d=c(this);b.row_hoverover.timeout=setTimeout(function(){d.addClass("row-hover")},300)},row_hoverout:function(){clearTimeout(b.row_hoverover.timeout);c(this).removeClass("row-hover")},init_menus:function(d,g){g&&c(".nicemenu",d).nicemenu();c(">tr",d).hover(b.row_hoverover,b.row_hoverout)},init_linkcount:function(b,d){var a=c(">tr",b).length,e=c("[name=infinitescroll-count]");c(".number",e).attr("data-value",a).text(a);c(".more",e).toggle(!!d)},
init_infinitescroll:function(){var h=c("#infinitescroll > tbody"),g=h.attr("data-next");b.init_menus(h);b.init_linkcount(h,g);if(g){var a=c("#infinitescroll-next");h.infinitescroll({loading:{msgText:"Fetching more links",img:d.h.static_url("lib/template/img/horizontal-loader.gif")},nextSelector:"#infinitescroll-next",navSelector:"#infinitescroll-next",dataType:"json",pathParse:function(){return[a[0].href+"&"+c.param({next:h.attr("data-next")})+"&page=",""]},appendCallback:!1},function(a){a=JSON.parse(a);
a=c(a.result.html);b.init_menus(a,!0);var d=a.attr("data-next");h.append(c(">tr",a));h.attr("data-next",d);b.init_linkcount(h,d);h.parent("table").trigger("update");d||c(window).unbind(".infscr")});c(window).trigger("scroll")}},init:function(){b.init_menus();c(".column.nav").collapse_module({modules:".module",column:".section"});d.filters.init_domain_type_property_filter(".column.nav");c(":text[name=creator]").suggest(d.suggest_options.any("type:/type/user")).bind("fb-select",function(b,d){c(this).val(d.id).parents("form:first").submit()});
b.init_infinitescroll();c("#infinitescroll").fixedcolumn()}};c(b.init)})(jQuery,window.freebase);
