
/*
 * Copyright 2012, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Additional Licenses for Third Party components can be found here:
 * http://wiki.freebase.com/wiki/Freebase_Site_License
 *
 */
/*
 
 jQuery Tools @VERSION / Expose - Dim the lights

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/toolbox/expose.html

 Since: Mar 2010
 Date: @DATE 
 
 jQuery Tools @VERSION Overlay - Overlay base. Extend it.

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/overlay/

 Since: March 2008
 Date: @DATE 
*/
(function(c,d){var a=window.propbox={init:function(b,e){e=c.extend({lang:"/lang/en"},e);if(!e.base_ajax_url)throw Error("base_ajax_url required in propbox options");if(!e.base_static_url)throw Error("base_static_url required in propbox options");if(!e.id)throw Error("topic id required in propbox options");if(!e.lang)throw Error("lang required in propbox options");a.options=e;a.kbs=new d(b);a.kbs.set_next(a.kbs.get_current(),c(".kbs:visible:first",b,!0));c(".kbs",b).live("click",function(){var b=a.kbs.get_current();
a.kbs.set_next(b,c(this),!0)}).live("edit",function(){var b=c(this).find(".headmenu:first").data("submenu");b&&c("li:first a:first",b).click()});a.init_menus(b)},init_menus:function(b,e){b=c(b||document);e&&c(".nicemenu",b).nicemenu();var d;d=b&&b.is(".hover-row")?b:c(".hover-row",b);d.hover(a.row_menu_hoverover,a.row_menu_hoverout);d.dblclick(function(){var b=c(".nicemenu .default-action",this);b.length||(b=c(".nicemenu:first .submenu:first a:first",this));var a=b.attr("href");("#"==a||0==a.indexOf("javascript:void(0)"))&&
c(b).click()});c(".nicemenu .headmenu",b).add(c(".nicemenu .default-action",b)).click("click",function(){if(a.kbs){var b=a.kbs.get_current();b&&a.kbs.set_next(b,c(this).parents(".kbs:first"),!0)}return!1})},row_menu_hoverover:function(){c(this).addClass("row-hover")},row_menu_hoverout:function(){c(this).removeClass("row-hover")},get_script:function(b,e){var d=a.get_script.cache;d||(d=a.get_script.cache={});var g=d[b];g?1===g.state?g.callbacks.push(e):4===g.state&&e():(g=d[b]={state:0,callbacks:[e]},
c.ajax({url:a.options.base_static_url+b,dataType:"script",beforeSend:function(){g.state=1},success:function(){g.state=4;c.each(g.callbacks,function(b,a){a()})},error:function(){g.state=-1}}))},prop_edit:function(b,e){var d=c(b).parents(".property-section");d.length||(d=c(b).parents(".submenu").data("headmenu").parents(".property-section"));d=d.find(".data-section .data-row:first:visible .nicemenu:first .headmenu:first a");d.length?d.click():a.prop_add(b,e);return!1},prop_add:function(b,e){var d=c(b).parents(".property-section");
d.length||(d=c(b).parents(".submenu").data("headmenu").parents(".property-section"));a.get_script("/propbox-edit.mf.js",function(){a.edit.prop_add_begin(d,e)});return!1},value_edit:function(b){var e=c(b).parents(".submenu").data("headmenu").parents(".data-row:first"),d=e.parents(".property-section");a.get_script("/propbox-edit.mf.js",function(){a.edit.value_edit_begin(d,e)});return!1},value_delete:function(b){var e=c(b).parents(".submenu").data("headmenu").parents(".data-row:first"),d=e.parents(".property-section");
a.get_script("/propbox-edit.mf.js",function(){a.edit.value_delete_begin(d,e)});return!1},remove_type:function(b){var b=c(b),e=b.parents(".type-section");a.get_script("/propbox-edit.mf.js",function(){a.edit.remove_type_begin(b,e)});return!1},add_type:function(b,e,d){var b=c(b),g=b.parents(".type-section"),i=a.options.incompatible_types;i?i.search(a.options.id,e,d,{compatible:function(){a.add_type_submit(b,g)},incompatible:i.overlay_incompatible_callback({onConfirm:function(){a.add_type_submit(b,g)}})}):
a.add_type_submit(b,g);return!1},add_type_submit:function(b,c){a.get_script("/propbox-edit.mf.js",function(){a.edit.add_type_submit(b,c)})},add_has_no_value:function(b){var e=c(b).parents(".submenu").data("headmenu").parents(".property-section");a.get_script("/propbox-edit.mf.js",function(){a.edit.add_has_no_value(e)});return!1},add_has_value:function(b){var e=c(b).parents(".submenu").data("headmenu").parents(".property-section");a.get_script("/propbox-edit.mf.js",function(){a.edit.add_has_value(e)});
return!1},remove_has_no_value:function(b){var e=c(b).parents(".property-section");a.get_script("/propbox-edit.mf.js",function(){a.edit.remove_has_no_value(e)});return!1},remove_has_value:function(b){var e=c(b).parents(".property-section");a.get_script("/propbox-edit.mf.js",function(){a.edit.remove_has_value(e)});return!1},more:function(b,e,d){var g=c(b).parents(".property-section");a.get_script("/propbox-edit.mf.js",function(){a.edit.more(g,e,d)})}}})(jQuery,window.kbs);
(function(c){function d(){if(c.browser.msie){var b=c(document).height(),a=c(window).height();return[window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth,20>b-a?a:b]}return[c(document).width(),c(document).height()]}function a(b){if(b)return b.call(c.mask)}c.tools=c.tools||{version:"@VERSION"};var b;b=c.tools.expose={conf:{maskId:"exposeMask",loadSpeed:"slow",closeSpeed:"fast",closeOnClick:!0,closeOnEsc:!0,zIndex:9998,opacity:0.8,startOpacity:0,color:"#fff",onLoad:null,
onClose:null}};var e,f,g,i,j;c.mask={load:function(h,k){if(g)return this;"string"==typeof h&&(h={color:h});h=h||i;i=h=c.extend(c.extend({},b.conf),h);e=c("#"+h.maskId);e.length||(e=c("<div/>").attr("id",h.maskId),c("body").append(e));var m=d();e.css({position:"absolute",top:0,left:0,width:m[0],height:m[1],display:"none",opacity:h.startOpacity,zIndex:h.zIndex});h.color&&e.css("backgroundColor",h.color);if(!1===a(h.onBeforeLoad))return this;h.closeOnEsc&&c(document).bind("keydown.mask",function(b){b.keyCode==
27&&c.mask.close(b)});h.closeOnClick&&e.bind("click.mask",function(b){c.mask.close(b)});c(window).bind("resize.mask",function(){c.mask.fit()});k&&k.length&&(j=k.eq(0).css("zIndex"),c.each(k,function(){var b=c(this);/relative|absolute|fixed/i.test(b.css("position"))||b.css("position","relative")}),f=k.css({zIndex:Math.max(h.zIndex+1,"auto"==j?0:j)}));e.css({display:"block"}).fadeTo(h.loadSpeed,h.opacity,function(){c.mask.fit();a(h.onLoad)});g=!0;return this},close:function(){if(g){if(!1===a(i.onBeforeClose))return this;
e.fadeOut(i.closeSpeed,function(){a(i.onClose);f&&f.css({zIndex:j})});c(document).unbind("keydown.mask");e.unbind("click.mask");c(window).unbind("resize.mask");g=!1}return this},fit:function(){if(g){var b=d();e.css({width:b[0],height:b[1]})}},getMask:function(){return e},isLoaded:function(){return g},getConf:function(){return i},getExposed:function(){return f}};c.fn.mask=function(b){c.mask.load(b);return this};c.fn.expose=function(b){c.mask.load(b,this);return this}})(jQuery);
(function(c){function d(e,d){var g=this,i=e.add(g),j=c(window),h,k,m,l=c.tools.expose&&(d.mask||d.expose),o=Math.random().toString().slice(10);l&&("string"==typeof l&&(l={color:l}),l.closeOnClick=l.closeOnEsc=!1);var n=d.target||e.attr("rel");k=n?c(n):e;if(!k.length)throw"Could not find Overlay: "+n;e&&-1==e.index(k)&&e.click(function(b){g.load(b);return b.preventDefault()});c.extend(g,{load:function(e){if(g.isOpened())return g;var n=b[d.effect];if(!n)throw'Overlay: cannot find effect : "'+d.effect+
'"';d.oneInstance&&c.each(a,function(){this.close(e)});e=e||c.Event();e.type="onBeforeLoad";i.trigger(e);if(e.isDefaultPrevented())return g;m=true;l&&c(k).expose(l);var h=d.top,p=d.left,q=k.outerWidth({margin:true}),s=k.outerHeight({margin:true});typeof h=="string"&&(h=h=="center"?Math.max((j.height()-s)/2,0):parseInt(h,10)/100*j.height());p=="center"&&(p=Math.max((j.width()-q)/2,0));n[0].call(g,{top:h,left:p},function(){if(m){e.type="onLoad";i.trigger(e)}});if(l&&d.closeOnClick)c.mask.getMask().one("click",
g.close);d.closeOnClick&&c(document).bind("click."+o,function(b){c(b.target).parents(k).length||g.close(b)});d.closeOnEsc&&c(document).bind("keydown."+o,function(b){b.keyCode==27&&g.close(b)});return g},close:function(a){if(!g.isOpened())return g;a=a||c.Event();a.type="onBeforeClose";i.trigger(a);if(!a.isDefaultPrevented()){m=false;b[d.effect][1].call(g,function(){a.type="onClose";i.trigger(a)});c(document).unbind("click."+o).unbind("keydown."+o);l&&c.mask.close();return g}},getOverlay:function(){return k},
getTrigger:function(){return e},getClosers:function(){return h},isOpened:function(){return m},getConf:function(){return d}});c.each(["onBeforeLoad","onStart","onLoad","onBeforeClose","onClose"],function(b,a){c.isFunction(d[a])&&c(g).bind(a,d[a]);g[a]=function(b){c(g).bind(a,b);return g}});h=k.find(d.close||".close");!h.length&&!d.close&&(h=c('<a class="close"></a>'),k.prepend(h));h.click(function(b){g.close(b)});d.load&&g.load()}c.tools=c.tools||{version:"@VERSION"};c.tools.overlay={addEffect:function(a,
c,d){b[a]=[c,d]},conf:{close:null,closeOnClick:!0,closeOnEsc:!0,closeSpeed:"fast",effect:"default",fixed:!c.browser.msie||6<c.browser.version,left:"center",load:!1,mask:null,oneInstance:!0,speed:"normal",target:null,top:"10%"}};var a=[],b={};c.tools.overlay.addEffect("default",function(b,a){var d=this.getConf(),i=c(window);d.fixed||(b.top+=i.scrollTop(),b.left+=i.scrollLeft());b.position=d.fixed?"fixed":"absolute";this.getOverlay().css(b).fadeIn(d.speed,a)},function(b){this.getOverlay().fadeOut(this.getConf().closeSpeed,
b)});c.fn.overlay=function(b){var f=this.data("overlay");if(f)return f;c.isFunction(b)&&(b={onBeforeLoad:b});b=c.extend(!0,{},c.tools.overlay.conf,b);this.each(function(){f=new d(c(this),b);a.push(f);c(this).data("overlay",f)});return b.api?f:this}})(jQuery);
jQuery.effects||function(c,d){function a(b){var a;return b&&b.constructor==Array&&3==b.length?b:(a=/rgb\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*\)/.exec(b))?[parseInt(a[1],10),parseInt(a[2],10),parseInt(a[3],10)]:(a=/rgb\(\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*\)/.exec(b))?[2.55*parseFloat(a[1]),2.55*parseFloat(a[2]),2.55*parseFloat(a[3])]:(a=/#([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})/.exec(b))?[parseInt(a[1],16),parseInt(a[2],
16),parseInt(a[3],16)]:(a=/#([a-fA-F0-9])([a-fA-F0-9])([a-fA-F0-9])/.exec(b))?[parseInt(a[1]+a[1],16),parseInt(a[2]+a[2],16),parseInt(a[3]+a[3],16)]:/rgba\(0, 0, 0, 0\)/.exec(b)?j.transparent:j[c.trim(b).toLowerCase()]}function b(){var b=document.defaultView?document.defaultView.getComputedStyle(this,null):this.currentStyle,a={},c,d;if(b&&b.length&&b[0]&&b[b[0]])for(var e=b.length;e--;)c=b[e],"string"==typeof b[c]&&(d=c.replace(/\-(\w)/g,function(b,a){return a.toUpperCase()}),a[d]=b[c]);else for(c in b)"string"===
typeof b[c]&&(a[c]=b[c]);return a}function e(b){var a,d;for(a in b)d=b[a],(null==d||c.isFunction(d)||a in k||/scrollbar/.test(a)||!/color/i.test(a)&&isNaN(parseFloat(d)))&&delete b[a];return b}function f(b,a){var c={_:0},d;for(d in a)b[d]!=a[d]&&(c[d]=a[d]);return c}function g(b,a,d,e){"object"==typeof b&&(e=a,d=null,a=b,b=a.effect);c.isFunction(a)&&(e=a,d=null,a={});if("number"==typeof a||c.fx.speeds[a])e=d,d=a,a={};c.isFunction(d)&&(e=d,d=null);a=a||{};d=d||a.duration;d=c.fx.off?0:"number"==typeof d?
d:d in c.fx.speeds?c.fx.speeds[d]:c.fx.speeds._default;e=e||a.complete;return[b,a,d,e]}function i(b){return!b||("number"===typeof b||c.fx.speeds[b])||"string"===typeof b&&!c.effects[b]?!0:!1}c.effects={};c.each("backgroundColor borderBottomColor borderLeftColor borderRightColor borderTopColor borderColor color outlineColor".split(" "),function(b,d){c.fx.step[d]=function(b){if(!b.colorInit){var e;e=b.elem;var g=d,f;do{f=c.curCSS(e,g);if(f!=""&&f!="transparent"||c.nodeName(e,"body"))break;g="backgroundColor"}while(e=
e.parentNode);e=a(f);b.start=e;b.end=a(b.end);b.colorInit=true}b.elem.style[d]="rgb("+Math.max(Math.min(parseInt(b.pos*(b.end[0]-b.start[0])+b.start[0],10),255),0)+","+Math.max(Math.min(parseInt(b.pos*(b.end[1]-b.start[1])+b.start[1],10),255),0)+","+Math.max(Math.min(parseInt(b.pos*(b.end[2]-b.start[2])+b.start[2],10),255),0)+")"}});var j={aqua:[0,255,255],azure:[240,255,255],beige:[245,245,220],black:[0,0,0],blue:[0,0,255],brown:[165,42,42],cyan:[0,255,255],darkblue:[0,0,139],darkcyan:[0,139,139],
darkgrey:[169,169,169],darkgreen:[0,100,0],darkkhaki:[189,183,107],darkmagenta:[139,0,139],darkolivegreen:[85,107,47],darkorange:[255,140,0],darkorchid:[153,50,204],darkred:[139,0,0],darksalmon:[233,150,122],darkviolet:[148,0,211],fuchsia:[255,0,255],gold:[255,215,0],green:[0,128,0],indigo:[75,0,130],khaki:[240,230,140],lightblue:[173,216,230],lightcyan:[224,255,255],lightgreen:[144,238,144],lightgrey:[211,211,211],lightpink:[255,182,193],lightyellow:[255,255,224],lime:[0,255,0],magenta:[255,0,255],
maroon:[128,0,0],navy:[0,0,128],olive:[128,128,0],orange:[255,165,0],pink:[255,192,203],purple:[128,0,128],violet:[128,0,128],red:[255,0,0],silver:[192,192,192],white:[255,255,255],yellow:[255,255,0],transparent:[255,255,255]},h=["add","remove","toggle"],k={border:1,borderBottom:1,borderColor:1,borderLeft:1,borderRight:1,borderTop:1,borderWidth:1,margin:1,padding:1};c.effects.animateClass=function(a,d,g,n){c.isFunction(g)&&(n=g,g=null);return this.queue("fx",function(){var i=c(this),j=i.attr("style")||
" ",k=e(b.call(this)),p,q=i.attr("className");c.each(h,function(b,c){if(a[c])i[c+"Class"](a[c])});p=e(b.call(this));i.attr("className",q);i.animate(f(k,p),d,g,function(){c.each(h,function(b,c){if(a[c])i[c+"Class"](a[c])});if(typeof i.attr("style")=="object"){i.attr("style").cssText="";i.attr("style").cssText=j}else i.attr("style",j);n&&n.apply(this,arguments)});k=c.queue(this);p=k.splice(k.length-1,1)[0];k.splice(1,0,p);c.dequeue(this)})};c.fn.extend({_addClass:c.fn.addClass,addClass:function(b,a,
d,e){return a?c.effects.animateClass.apply(this,[{add:b},a,d,e]):this._addClass(b)},_removeClass:c.fn.removeClass,removeClass:function(b,a,d,e){return a?c.effects.animateClass.apply(this,[{remove:b},a,d,e]):this._removeClass(b)},_toggleClass:c.fn.toggleClass,toggleClass:function(b,a,e,g,f){return"boolean"==typeof a||a===d?e?c.effects.animateClass.apply(this,[a?{add:b}:{remove:b},e,g,f]):this._toggleClass(b,a):c.effects.animateClass.apply(this,[{toggle:b},a,e,g])},switchClass:function(b,a,d,e,g){return c.effects.animateClass.apply(this,
[{add:a,remove:b},d,e,g])}});c.extend(c.effects,{version:"1.8.10",save:function(b,a){for(var c=0;c<a.length;c++)null!==a[c]&&b.data("ec.storage."+a[c],b[0].style[a[c]])},restore:function(b,a){for(var c=0;c<a.length;c++)null!==a[c]&&b.css(a[c],b.data("ec.storage."+a[c]))},setMode:function(b,a){"toggle"==a&&(a=b.is(":hidden")?"show":"hide");return a},getBaseline:function(b,a){var c,d;switch(b[0]){case "top":c=0;break;case "middle":c=0.5;break;case "bottom":c=1;break;default:c=b[0]/a.height}switch(b[1]){case "left":d=
0;break;case "center":d=0.5;break;case "right":d=1;break;default:d=b[1]/a.width}return{x:d,y:c}},createWrapper:function(b){if(b.parent().is(".ui-effects-wrapper"))return b.parent();var a={width:b.outerWidth(!0),height:b.outerHeight(!0),"float":b.css("float")},d=c("<div></div>").addClass("ui-effects-wrapper").css({fontSize:"100%",background:"transparent",border:"none",margin:0,padding:0});b.wrap(d);d=b.parent();"static"==b.css("position")?(d.css({position:"relative"}),b.css({position:"relative"})):
(c.extend(a,{position:b.css("position"),zIndex:b.css("z-index")}),c.each(["top","left","bottom","right"],function(c,d){a[d]=b.css(d);isNaN(parseInt(a[d],10))&&(a[d]="auto")}),b.css({position:"relative",top:0,left:0,right:"auto",bottom:"auto"}));return d.css(a).show()},removeWrapper:function(b){return b.parent().is(".ui-effects-wrapper")?b.parent().replaceWith(b):b},setTransition:function(b,a,d,e){e=e||{};c.each(a,function(a,c){unit=b.cssUnit(c);0<unit[0]&&(e[c]=unit[0]*d+unit[1])});return e}});c.fn.extend({effect:function(b,
a,d,e){var f=g.apply(this,arguments),i={options:f[1],duration:f[2],callback:f[3]},f=i.options.mode,h=c.effects[b];return c.fx.off||!h?f?this[f](i.duration,i.callback):this.each(function(){i.callback&&i.callback.call(this)}):h.call(this,i)},_show:c.fn.show,show:function(b){if(i(b))return this._show.apply(this,arguments);var a=g.apply(this,arguments);a[1].mode="show";return this.effect.apply(this,a)},_hide:c.fn.hide,hide:function(b){if(i(b))return this._hide.apply(this,arguments);var a=g.apply(this,
arguments);a[1].mode="hide";return this.effect.apply(this,a)},__toggle:c.fn.toggle,toggle:function(b){if(i(b)||"boolean"===typeof b||c.isFunction(b))return this.__toggle.apply(this,arguments);var a=g.apply(this,arguments);a[1].mode="toggle";return this.effect.apply(this,a)},cssUnit:function(b){var a=this.css(b),d=[];c.each(["em","px","%","pt"],function(b,c){0<a.indexOf(c)&&(d=[parseFloat(a),c])});return d}});c.easing.jswing=c.easing.swing;c.extend(c.easing,{def:"easeOutQuad",swing:function(b,a,d,
e,g){return c.easing[c.easing.def](b,a,d,e,g)},easeInQuad:function(b,a,c,d,e){return d*(a/=e)*a+c},easeOutQuad:function(b,a,c,d,e){return-d*(a/=e)*(a-2)+c},easeInOutQuad:function(b,a,c,d,e){return 1>(a/=e/2)?d/2*a*a+c:-d/2*(--a*(a-2)-1)+c},easeInCubic:function(b,a,c,d,e){return d*(a/=e)*a*a+c},easeOutCubic:function(b,a,c,d,e){return d*((a=a/e-1)*a*a+1)+c},easeInOutCubic:function(b,a,c,d,e){return 1>(a/=e/2)?d/2*a*a*a+c:d/2*((a-=2)*a*a+2)+c},easeInQuart:function(b,a,c,d,e){return d*(a/=e)*a*a*a+c},
easeOutQuart:function(b,a,c,d,e){return-d*((a=a/e-1)*a*a*a-1)+c},easeInOutQuart:function(b,a,c,d,e){return 1>(a/=e/2)?d/2*a*a*a*a+c:-d/2*((a-=2)*a*a*a-2)+c},easeInQuint:function(b,a,c,d,e){return d*(a/=e)*a*a*a*a+c},easeOutQuint:function(b,a,c,d,e){return d*((a=a/e-1)*a*a*a*a+1)+c},easeInOutQuint:function(b,a,c,d,e){return 1>(a/=e/2)?d/2*a*a*a*a*a+c:d/2*((a-=2)*a*a*a*a+2)+c},easeInSine:function(b,a,c,d,e){return-d*Math.cos(a/e*(Math.PI/2))+d+c},easeOutSine:function(b,a,c,d,e){return d*Math.sin(a/
e*(Math.PI/2))+c},easeInOutSine:function(b,a,c,d,e){return-d/2*(Math.cos(Math.PI*a/e)-1)+c},easeInExpo:function(b,a,c,d,e){return 0==a?c:d*Math.pow(2,10*(a/e-1))+c},easeOutExpo:function(b,a,c,d,e){return a==e?c+d:d*(-Math.pow(2,-10*a/e)+1)+c},easeInOutExpo:function(b,a,c,d,e){return 0==a?c:a==e?c+d:1>(a/=e/2)?d/2*Math.pow(2,10*(a-1))+c:d/2*(-Math.pow(2,-10*--a)+2)+c},easeInCirc:function(b,a,c,d,e){return-d*(Math.sqrt(1-(a/=e)*a)-1)+c},easeOutCirc:function(b,a,c,d,e){return d*Math.sqrt(1-(a=a/e-1)*
a)+c},easeInOutCirc:function(b,a,c,d,e){return 1>(a/=e/2)?-d/2*(Math.sqrt(1-a*a)-1)+c:d/2*(Math.sqrt(1-(a-=2)*a)+1)+c},easeInElastic:function(b,a,c,d,e){var b=1.70158,g=0,f=d;if(0==a)return c;if(1==(a/=e))return c+d;g||(g=0.3*e);f<Math.abs(d)?(f=d,b=g/4):b=g/(2*Math.PI)*Math.asin(d/f);return-(f*Math.pow(2,10*(a-=1))*Math.sin((a*e-b)*2*Math.PI/g))+c},easeOutElastic:function(b,a,c,d,e){var b=1.70158,g=0,f=d;if(0==a)return c;if(1==(a/=e))return c+d;g||(g=0.3*e);f<Math.abs(d)?(f=d,b=g/4):b=g/(2*Math.PI)*
Math.asin(d/f);return f*Math.pow(2,-10*a)*Math.sin((a*e-b)*2*Math.PI/g)+d+c},easeInOutElastic:function(b,a,c,d,e){var b=1.70158,g=0,f=d;if(0==a)return c;if(2==(a/=e/2))return c+d;g||(g=e*0.3*1.5);f<Math.abs(d)?(f=d,b=g/4):b=g/(2*Math.PI)*Math.asin(d/f);return 1>a?-0.5*f*Math.pow(2,10*(a-=1))*Math.sin((a*e-b)*2*Math.PI/g)+c:0.5*f*Math.pow(2,-10*(a-=1))*Math.sin((a*e-b)*2*Math.PI/g)+d+c},easeInBack:function(b,a,c,e,g,f){f==d&&(f=1.70158);return e*(a/=g)*a*((f+1)*a-f)+c},easeOutBack:function(b,a,c,e,
g,f){f==d&&(f=1.70158);return e*((a=a/g-1)*a*((f+1)*a+f)+1)+c},easeInOutBack:function(a,b,c,e,g,f){f==d&&(f=1.70158);return 1>(b/=g/2)?e/2*b*b*(((f*=1.525)+1)*b-f)+c:e/2*((b-=2)*b*(((f*=1.525)+1)*b+f)+2)+c},easeInBounce:function(b,a,d,e,g){return e-c.easing.easeOutBounce(b,g-a,0,e,g)+d},easeOutBounce:function(b,a,c,d,e){return(a/=e)<1/2.75?d*7.5625*a*a+c:a<2/2.75?d*(7.5625*(a-=1.5/2.75)*a+0.75)+c:a<2.5/2.75?d*(7.5625*(a-=2.25/2.75)*a+0.9375)+c:d*(7.5625*(a-=2.625/2.75)*a+0.984375)+c},easeInOutBounce:function(a,
b,d,e,g){return b<g/2?0.5*c.easing.easeInBounce(a,2*b,0,e,g)+d:0.5*c.easing.easeOutBounce(a,2*b-g,0,e,g)+0.5*e+d}})}(jQuery);
(function(c){c.fn.mqlkey=function(a){return this.each(function(){var b=c(this);if(b.is(":text")){var e=b.data("mqlkey");e&&e._destroy();e=new d(this,a);b.data("mqlkey",e)}})};var d=c.mqlkey=function(a,b){this.options=c.extend(!0,{},d.defaults,b);this.input=c(a);this.original=this.input.val();this.init()};d.prototype={init:function(){var a=this;this.input.bind("keyup.mqlkey",function(b){a.textchange(b)}).bind(c.browser.msie?"paste.mqlkey":"input.mqlkey",function(b){a.textchange(b)});this.options.source&&
(this.source=c(this.options.source),this.source_generate=""===this.source.val()?!0:!1,this.input.bind("change.mqlkey",function(){a.source_generate=!1}),this.source.bind("change.mqlkey",function(){if(a.source_generate){var b=d.from(a.source.val());a.input.val(b).trigger("keyup")}}))},_destroy:function(){this.input.unbind(".mqlkey");this.source&&this.source.unbind("change.mqlkey")},textchange:function(a){clearTimeout(this.textchange_timeout);var b=this;this.textchange_timeout=setTimeout(function(){b.textchange_delay(a)},
200)},textchange_delay:function(){this.input.trigger("textchange");var a=c.trim(this.input.val());return a===this.original&&""!==a?this.valid(a):d.reserved_word(a)?this.invalid(a,a+" is a reserved word."):d.test(a,this.options.schema)?a.length<this.options.minlen?this.invalid(a):this.options.check_key?this.check_key(a):this.valid(a):this.invalid(a)},check_key:function(a){var b=this;this.xhr&&(this.xhr=null);var c={id:null,key:{namespace:this.options.namespace,value:a}};clearTimeout(this.check_key.timeout);
this.check_key.timeout=setTimeout(function(){b.xhr=b.options.mqlread(c,function(c){return c?b.invalid(a,"Key already exists"):b.valid(a)},function(a){return a?b.invalid(a.responseText()):b.invalid("mqlread error!")})},200)},valid:function(a){this.input.trigger("valid",a)},invalid:function(a,b){b||(b=1<this.options.minlen?"Key must be "+this.options.minlen+" or more alphanumeric characters":"Key must be alphanumeric",b+=", lowercase, begin with a letter and not end with a non-alphanumeric character. Underscores are allowed but not consecutively.");
this.input.trigger("invalid",b)}};c.extend(d,{defaults:{minlen:1,check_key:!0,namespace:"/",mqlread:function(a,b,c){return d.mqlread(null,a,b,c)},source:null,schema:!1},mqlread:function(a,b,d,f){a={url:a||"http://api.freebase.com/api/service/mqlread",data:{query:JSON.stringify({query:b})},dataType:"jsonp",success:function(a){return d(a.result)},error:f};return c.ajax(a)},from:function(a){a=a.toLowerCase();a=a.replace(/[^a-z0-9]/g,"_");a=a.replace(/\_\_+/g,"_");a=a.replace(/[^a-z0-9]+$/,"");a=a.replace(/^[^a-z]+/,
"");d.reserved_word(a)&&(a="x_"+a);return a},reservedwords:"meta typeguid left right datatype scope attribute relationship property link class future update insert delete replace create destroy default sort limit offset optional pagesize cursor index !index for while as in is if else return count function read write select var connect this self super xml sql mql any all macro estimate-count",typeonlywords:"guid id object domain name key type keys value timestamp creator permission namespace unique schema reverse",
_reserved_word:null,reserved_word:function(a){d._reserved_word||(d._reserved_word={},c.each([d.reservedwords,d.typeonlywords],function(a,e){c.each(e.split(" "),function(a,b){d._reserved_word[b]=1})}));return 1===d._reserved_word[a]},fast:/^[A-Za-z0-9](?:[_-]?[A-Za-z0-9])*$/,slow:/^(?:[A-Za-z0-9]|\$[A-F0-9]{4})(?:[_-]?[A-Za-z0-9]|[_-]?\$[A-F0-9]{4})*$/,schema:/^[a-z](?:_?[a-z0-9])*$/,test:function(a,b){return b?d.schema.test(a):d.fast.test(a)||d.slow.test(a)}})})(jQuery);
(function(c){c.fn.validate_input=function(a){return this.each(function(){var b=c(this);if(b.is(":text")){var e=b.data("$.validate_input");e&&e._destroy();e=new d(this,a);b.data("$.validate_input",e)}})};var d=c.validate_input=function(a,b){if("function"!==typeof(this.options=c.extend(!0,{},d.defaults,b)).validator)throw"A validator is required";this.input=c(a);this.init();var e=this;this.input.bind("remove",function(){e._destroy()});return this};d.prototype={init:function(){var a=this;this.input.bind("keyup.validate_input",
function(b){a.textchange(b)}).bind(c.browser.msie?"paste.validate_input":"input.validate_input",function(b){a.textchange(b)}).bind("keypress.validate_input",function(b){13===b.keyCode&&a.validate(!0)}).bind("blur.validate_input",function(){a.validate(!0)})},_destroy:function(){this.input.unbind(".validate_input")},valid:function(a){this.input.trigger("valid",a)},invalid:function(a,b){this.input.trigger("invalid",b)},empty:function(){this.input.trigger("empty")},textchange:function(){clearTimeout(this.textchange_timeout);
var a=this;this.textchange_timeout=setTimeout(function(){a.validate()},200)},validate:function(a){a&&clearTimeout(this.textchange_timeout);var a=this.options,b=c.trim(this.input.val());if(""===b)return this.empty();try{var d=a.validator(b,a);return this.valid(d)}catch(f){return this.invalid(b,""+f)}}};c.extend(d,{defaults:{validator:function(a){return{text:a,value:a}}},log:function(){},invalid:function(a,b,c,d){throw Error("Invalid "+c+(d?": "+d:""));},text:function(a,b){return 4096<a.lengh?this.invalid(a,
b,type,"Text too long"):{text:a,value:a}},topic:function(){return d.defaults.validator},enumerated:function(){return d.defaults.validator},"boolean":function(){return d.defaults.validator},uri:function(a,b){var c=d.uri.regex;c||(c=d.uri.regex=/^(https?|ftp):\/\/(((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:)*@)?(((\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5]))|((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?)(:\d*)?)(\/((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)+(\/(([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)*)*)?)?(\?((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|[\uE000-\uF8FF]|\/|\?)*)?(\#((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|\/|\?)*)?$/i);
return c.test(a)?{text:a,value:a}:d.invalid(a,b,"uri")},"int":function(a,b){return d.number.parse(a,b,!1)},"float":function(a,b){return d.number.parse(a,b,!0)},number:function(a,b,c){return d.number.parse(a,b,c)},datetime:function(a,b){return d.datetime.parse(a,b)},mqlkey:function(a,b){var c=d.mqlkey.regex;c||(c=d.mqlkey.regex=/^[A-Za-z0-9][A-Za-z0-9_-]*$/);return c.test(a)?{text:a,value:a}:d.invalid(a,b,"mqlkey")}});c.extend(d.number,{parse:function(a,b,c){b=null;b=c?Globalize.parseFloat(a):Globalize.parseInt(a,
10);if(isNaN(b))throw d.invalid("number",a);if(c){var a="n",c=""+b,f=c.indexOf(".");-1!==f&&(a="n"+c.substr(f+1).length);return{value:b,text:Globalize.format(b,a)}}return{value:b,text:Globalize.format(b,"n0")}}});c.extend(d.datetime,{regexp:{iso:/^(?:(-?\d{4})(?:-(\d{2})(?:-(\d{2}))?)?)?(?:T(\d{2}):(\d{2})(?::(\d{2})(.\d+)?)?((?:[+-](\d{2}):(\d{2}))|Z)?)?$/,time:/^T?([01][0-9]|2[0-3])(:[0-5][0-9]){0,2}$/,bce:[/^(\d+)\s*[Bb]\.*[Cc]\.*[Ee]*/,/^[Bb]\.*[Cc]\.*[Ee]*\s*(\d+)/]},formats:"d yyyy-MM-dd Y yyyy-MM t HH:mm T HH:mm:ss".split(" "),
padyear:function(a){return 10>a?"000"+a:100>a?"00"+a:1E3>a?"0"+a:""+a},parse:function(a){var b,c,f;if(d.datetime.regexp.iso.test(a)||d.datetime.regexp.time.test(a))return c=a,0===c.indexOf("T")&&(c=c.substring(1)),{text:a,value:c};c=0;for(f=d.datetime.regexp.bce.length;c<f;c++)if(b=d.datetime.regexp.bce[c].exec(a))return c=parseInt(b[1],10),c-=1,c=d.datetime.padyear(c),{text:a,value:"-"+c};c=0;for(f=d.datetime.formats.length;c<f;c+=2)if(b=Globalize.parseDate(a,d.datetime.formats[c]))return{text:a,
value:Globalize.format(b,d.datetime.formats[c+1])};if(b=Globalize.parseDate(a))return{text:a,value:Globalize.format(b,"S")};throw d.invalid("datetime",a);}})})(jQuery,window.Globalize);
(function(c){c.fn.data_input=function(d){return this.each(function(){var a=c(this),b=a.data("$.data_input");b&&b._destroy();b=new c.data_input(this,d);a.data("$.data_input",b)})};c.data_input=function(d,a){this.options=c.extend(!0,{},a);this.container=c(d);this.metadata=this.container.metadata();this.input=c(":input",this.container);this.init();var b=this;this.input.bind("remove",function(){b._destroy()})};c.data_input.prototype={init:function(){var d=this,a=this.container,b=this.input,e=this.options;
b.bind("focusin.data_input",function(){d.container.addClass("focus")}).bind("focusout.data_input",function(){d.container.removeClass("focus")}).bind("valid.data_input",function(a,b){a.stopPropagation();var c={name:d.input.attr("name")};b.id?c.id=b.id:b.create_new?(c.create_new=b.create_new,c.lang=d.metadata.lang||e.lang):(c.value=b.value,"/type/text"===d.metadata.type?c.lang=d.metadata.lang||e.lang:"/type/key"===d.metadata.type&&(c.namespace=b.namespace));d.container.data("data",c);d.container.removeClass("error").addClass("valid");
d.container.trigger("valid")}).bind("invalid.data_input",function(a){a.stopPropagation();d.container.removeData("data");d.container.removeClass("valid").addClass("error");d.container.trigger("invalid")}).bind("empty.data_input",function(a){a.stopPropagation();a={name:d.input.attr("name")};d.metadata&&d.metadata.lang&&(a.lang=d.metadata.lang);d.container.data("data",a);d.container.removeClass("valid").removeClass("error");d.container.trigger("empty")}).bind("keypress.data_input",function(a){13===a.keyCode&&
!a.isDefaultPrevented()&&d.container.trigger("submit")}).bind("keyup.data_input",function(a){27===a.keyCode&&d.container.trigger("cancel")});if(a.is(".topic")){var a=d.metadata.type,f=null;e.suggest_impl&&(f=e.suggest_impl.instance(a,!0,d.metadata&&d.metadata.lang||e.lang));var g=null;e.structure&&d.options.incompatible_types&&(g=e.structure.expected_type.included_types,f=d.options.incompatible_types.suggest_options(a,g,f));b.validate_topic(c.extend({incompatible_types:d.options.incompatible_types,
expected_type:a,included_types:g},f)).bind("valid.data_input",function(a,b){d.fb_select(b)}).bind("invalid.data_input",function(){d.fb_textchange()});this.metadata&&this.metadata.id&&(b.data("data.suggest",this.metadata),this.validate())}else if(a.is(".text"))b.validate_input({validator:c.validate_input.text});else if(a.is(".datetime"))b.validate_input({validator:c.validate_input.datetime,lang:e.lang});else if(a.is(".enumerated"))b.validate_enumerated().bind("valid.data_input",function(a,b){d.fb_select(b)}).bind("invalid.data_input",
function(){d.fb_textchange()}),this.metadata&&this.metadata.id&&this.validate();else if(a.is(".int"))b.validate_input({validator:c.validate_input["int"],lang:e.lang});else if(a.is(".float"))b.validate_input({validator:c.validate_input["float"],lang:e.lang});else if(a.is(".uri"))b.validate_input({validator:c.validate_input.uri});else if(a.is(".boolean"))b.validate_boolean();else if(a.is(".enumeration"))b.validate_input({validator:c.validate_input.mqlkey});else if(a.is(".key"))b.validate_key(e,this.metadata);
else if(a.is(".rawstring"))b.validate_input({validator:c.validate_input.text});else throw Error("Invalid data-input: "+a.attr("class"));},_destroy:function(){this.input.unbind(".data_input")},validate:function(){var d=this.input;c.each(["$.validate_topic","$.validate_input","$.validate_enumerated","$.validate_boolean","$.validate_key"],function(a,b){var c=d.data(b);if(c)return c.validate(!0),!1})},reset:function(){this.container.removeData("data");this.input.is(":text")?this.input.val(""):this.input.is("select")?
this.input[0].selectedIndex=0:this.input.is(":radio")&&this.input.each(function(){this.checked=!1})},fb_textchange:function(){},fb_select:function(){},ajax_beforeSend:function(c){this.xhr_queue||(this.xhr_queue=[]);this.xhr_queue.push(c);this.container.trigger("loading")},ajax_complete:function(c){this.xhr_queue||(this.xhr_queue=[]);for(var a=0,b=this.xhr_queue.length;a<b;a++)if(c===this.xhr_queue[a]){this.xhr_queue.splice(a,1);break}0===this.xhr_queue.length&&this.container.trigger("loading_complete")}};
c.fn.validate_topic=function(d){return this.each(function(){var a=c(this);if(a.is(":text")){var b=a.data("$.validate_topic");b&&b._destroy();b=new c.validate_topic(this,d);a.data("$.validate_topic",b)}})};c.validate_topic=function(d,a){this.options=c.extend(!0,{},a);this.input=c(d);this.init()};c.validate_topic.prototype={init:function(){var c=this;this.input.suggest(this.options).bind("fb-textchange.validate_topic",function(){""===c.input.val()?c.empty():c.invalid()}).bind("fb-select.validate_topic",
function(a,b){c.input.val(null!=b.name?b.name:b.id);c.incompatible_types_check(b)}).bind("fb-select-new.validate_topic",function(a,b){c.valid(b)})},incompatible_types_check:function(c){var a=this;a.options.incompatible_types&&a.options.expected_type?a.options.incompatible_types.check(c,a.options.expected_type,a.options.included_types,{compatible:function(){a.valid(c)},incompatible:a.options.incompatible_types.inline_incompatible_callback({onConfirm:function(){a.valid(c)}},a.input)}):this.valid(c)},
invalid:function(){this.input.trigger("invalid")},valid:function(c){"string"===typeof c&&(c={create_new:c});this.input.trigger("valid",c)},empty:function(){this.input.trigger("empty")},_destroy:function(){this.input.unbind(".validate_topic")},validate:function(){if(""===this.input.val())this.empty();else{var c=this.input.data("data.suggest");c?this.valid(c):this.invalid()}}};c.fn.validate_enumerated=function(d){return this.each(function(){var a=c(this);if(a.is("select")){var b=a.data("$.validate_enumerated");
b&&b._destroy();b=new c.validate_enumerated(this,d);a.data("$.validate_enumerated",b)}})};c.validate_enumerated=function(d,a){this.options=c.extend(!0,{},a);this.input=c(d);this.init()};c.validate_enumerated.prototype={init:function(){var d=this;this.input.bind("change.validate_enumerated, keypress.validate_enumerated",function(){0===this.selectedIndex?d.empty():d.valid({text:c(":selected",this).text(),id:this.value})})},invalid:function(){this.input.trigger("invalid")},valid:function(c){this.input.trigger("valid",
c);this.input.trigger("fb-select",c)},empty:function(){this.input.trigger("empty")},_destroy:function(){this.input.unbind(".validate_enumerated")},validate:function(){var d=this.input[0];0<d.selectedIndex?this.valid({text:c(":selected",this.input).text(),id:d.value}):this.empty()}};c.fn.validate_boolean=function(d){var a,b;this.each(function(){var d=c(this);d.is(":radio")&&("true"===d.val().toLowerCase()?a=d:"false"===d.val().toLowerCase()&&(b=d))});if(a&&b){var e=a.data("$.validate_boolean");e&&
e._destroy();e=new c.validate_boolean(a,b,d);a.data("$.validate_boolean",e)}else throw"$.fn.validate_boolean requires two radios: true and false";return this};c.validate_boolean=function(d,a,b){this.options=c.extend(!0,{},b);this.tradio=d;this.fradio=a;this.input=this.tradio;this.init()};c.validate_boolean.prototype={init:function(){var c=this;this.tradio.bind("change.validate_boolean",function(){c.validate()})},_destroy:function(){this.input.unbind(".validate_boolean")},valid:function(c){this.input.trigger("valid",
c)},empty:function(){this.input.trigger("empty")},validate:function(){this.tradio.is(":checked")?this.valid({text:this.tradio.text(),value:!0}):this.fradio.is(":checked")?this.valid({text:this.fradio.text(),value:!1}):this.empty()}};c.fn.validate_key=function(d,a){var b,e;this.each(function(){var a=c(this);a.is(":text")&&(a.is(".key-namespace")?b=a:a.is(".key-value")&&(e=a))});if(b&&e){var f=e.data("$.validate_key");f&&f._destroy();f=new c.validate_key(b,e,d);b.data("$.validate_key",f);a&&(a.namespace&&
a.value)&&(b.data("data.suggest",{id:a.namespace}),e.val(a.value))}else throw"$.fn.validate_key requires two inputs: namespace and value";return this};c.validate_key=function(d,a,b){this.options=c.extend(!0,{},b);this.key_namespace_input=d;this.key_value_input=a;this.input=this.key_namespace_input;this.init()};c.validate_key.prototype={init:function(){var d=this,a=null;this.options.suggest_impl&&(a="/type/namespace/keys"!=this.key_value_input.attr("name")?this.options.suggest_impl.instance("/type/namespace"):
c.extend({},this.options.suggest_impl.service_defaults));this.key_namespace_input.suggest(a).bind("fb-textchange.validate_key",function(){d.validate()}).bind("fb-select.validate_key",function(a,c){d.key_namespace_input.val(c.name||c.id);d.validate()});this.key_value_input.validate_input({validator:c.validate_input.mqlkey}).bind("valid",function(a){a.stopPropagation();d.validate()}).bind("invalid",function(a){a.stopPropagation();d.validate()}).bind("empty",function(a){a.stopPropagation();d.validate()})},
_destroy:function(){this.key_namespace_input.unbind(".validate_key");this.key_value_input.unbind()},invalid:function(){this.input.trigger("invalid")},valid:function(c){this.input.trigger("valid",c)},empty:function(){this.input.trigger("empty")},validate:function(){this.is_valid_key_namespace()&&this.is_valid_key_value()?this.valid({namespace:this.key_namespace_input.data("data.suggest").id,value:this.key_value_input.val(),text:this.key_value_input.val()}):""===this.key_namespace_input.val()&&""===
this.key_value_input.val()?this.empty():this.invalid()},is_valid_key_namespace:function(){return null!=this.key_namespace_input.data("data.suggest")},is_valid_key_value:function(){try{return c.validate_input.mqlkey(this.key_value_input.val()),!0}catch(d){return!1}}}})(jQuery);
(function(c,d){var a=window.formlib={status:d,init:function(b){var c=b.event_prefix||"form.";b.form.bind(c+"submit",function(){a.submit(b)}).bind(c+"cancel",function(){a.cancel(b)}).bind(c+"error",function(c,e){b.form.removeClass("loading");a.disable_submit(b);d.error(e,!0)}).bind(c+"success",function(){b.form.removeClass("loading")}).bind(c+"valid",function(){a.enable_submit(b)}).bind(c+"invalid",function(){a.disable_submit(b)});a.init_submit_cancel(b);b.init(b)},submit:function(b){!b.form.is(".loading")&&
a.is_submit_enabled(b)&&(document.activeElement&&c(document.activeElement).blur(),b.validate(b)&&(b.form.addClass("loading"),b.submit(b,a.default_submit_ajax_options(b))))},cancel:function(){},init_inline_add_form:function(b){var c=b.event_prefix||"form.inline_add_form.";b.edit_row.bind(c+"submit",function(){a.submit_inline_add_form(b)}).bind(c+"cancel",function(){a.cancel_inline_add_form(b)}).bind(c+"error",function(c,e){b.edit_row.removeClass("loading");a.disable_submit(b);d.error(e,!0)}).bind(c+
"success",function(){b.edit_row.removeClass("loading")}).bind(c+"valid",function(){a.enable_submit(b)}).bind(c+"invalid",function(){a.disable_submit(b)});a.init_submit_cancel(b);b.trigger&&b.trigger.parents(".trigger-row:first").hide();b.body.append(b.edit_row).append(b.submit_row);b.init(b)},submit_inline_add_form:function(b){!b.edit_row.is(".loading")&&a.is_submit_enabled(b)&&(document.activeElement&&c(document.activeElement).blur(),b.validate(b)&&(b.edit_row.addClass("loading"),b.submit(b,a.default_submit_ajax_options(b))))},
submit_and_continue_inline_add_form:function(a,d){var f=d.beforeSend,g=d.complete,i=c.extend({},d,{beforeSend:function(d,e){f&&f.apply(this,arguments);var g=a.edit_row.clone().addClass("edit-row-submitting");fb.disable(c(":input",g));d._cloned_edit_row=g;a.edit_row.before(g);a.reset(a)},complete:function(a){g&&g.apply(this,arguments);delete a._cloned_edit_row}});c.ajax(i)},success_inline_add_form:function(b,c,d){d&&d._cloned_edit_row?d._cloned_edit_row.replaceWith(c):(b.edit_row.before(c),b.reset(b));
a.animate_new_row(c);b.edit_row.trigger(b.event_prefix+"success")},cancel_inline_add_form:function(a){a.edit_row.remove();a.submit_row.remove();a.trigger&&a.trigger.parents(".trigger-row:first").show()},animate_new_row:function(a){a.addClass("new-row",1E3,function(){a.removeClass("new-row",1E3)})},init_inline_edit_form:function(b){var c=b.event_prefix||"form.inline_edit_form.";b.edit_row.bind(c+"submit",function(){a.submit_inline_edit_form(b)}).bind(c+"cancel",function(){a.cancel_inline_edit_form(b)}).bind(c+
"error",function(c,e){b.edit_row.removeClass("loading");a.disable_submit(b);d.error(e,!0)}).bind(c+"success",function(){b.edit_row.removeClass("loading")}).bind(c+"valid",function(){a.enable_submit(b)}).bind(c+"invalid",function(){a.disable_submit(b)});a.init_submit_cancel(b);b.row.hide();b.row.before(b.edit_row).before(b.submit_row);b.init(b)},submit_inline_edit_form:function(b){!b.edit_row.is(".loading")&&a.is_submit_enabled(b)&&(document.activeElement&&c(document.activeElement).blur(),b.validate(b)&&
(b.edit_row.addClass("loading"),b.submit(b,a.default_submit_ajax_options(b))))},success_inline_edit_form:function(b,c){b.row.replaceWith(c);b.row=c;a.animate_new_row(c);b.edit_row.trigger(b.event_prefix+"cancel")},cancel_inline_edit_form:function(a){a.edit_row.remove();a.submit_row.remove();a.row.show()},success_inline_delete:function(b,d,f){b.hide().addClass("old-row");b.after(d);d.append(b);a.animate_new_row(d);f&&(b=c('<a href="#">undo</a><span class="divider">|</span>'),c(".msg-default",d).next().append(b),
b.click(function(){f();return!1}))},success_inline_delete_undo:function(b){var d=c(".old-row",b);b.before(d);d.show().removeClass("old-row");b.remove();a.animate_new_row(d)},init_modal_form:function(b){c(document.body).append(b.form.hide());var e=b.event_prefix||"form.modal_form.";b.form.bind(e+"submit",function(){a.submit_modal_form(b)}).bind(e+"cancel",function(){a.cancel_modal_form(b)}).bind(e+"error",function(c,e){b.form.removeClass("loading");a.disable_submit(b);d.error(e,!0)}).bind(e+"success",
function(){b.form.removeClass("loading")}).bind(e+"valid",function(){a.enable_submit(b)}).bind(e+"invalid",function(){a.disable_submit(b)});a.init_submit_cancel(b);b.form.data("overlay")&&b.form.removeData("overlay");b.form.overlay({close:".modal-buttons .cancel",closeOnClick:!1,load:!0,fixed:!1,mask:{color:"#000",loadSpeed:200,opacity:0.5},onLoad:function(){b.overlay=this;b.init(b)}})},submit_modal_form:function(b){!b.form.is(".loading")&&a.is_submit_enabled(b)&&(document.activeElement&&c(document.activeElement).blur(),
b.validate(b)&&(b.form.addClass("loading"),b.submit(b,a.default_submit_ajax_options(b))))},cancel_modal_form:function(a){a.form.data("overlay").close();a.form.next("#exposeMask").hide()},init_submit_cancel:function(b){var d=b.form||b.edit_row,f=b.form||b.submit_row,g=b.event_prefix,b=c(".save",f).click(function(){d.trigger(g+"submit")});a.disable(b);c(".cancel",f).click(function(){d.trigger(g+"cancel")});c(":input",d).keyup(function(a){27===a.keyCode&&d.trigger(g+"cancel")})},disable:function(a){c(a).attr("disabled",
"disabled").addClass("disabled")},enable:function(a){c(a).removeAttr("disabled").removeClass("disabled")},disable_submit:function(b){a.disable(c(".save",b.form||b.submit_row))},enable_submit:function(b){a.enable(c(".save",b.form||b.submit_row))},is_submit_enabled:function(a){return!c(".save",a.form||a.submit_row).is(":disabled")},init_mqlkey:function(a,d){return a.next(".key-status").removeClass("valid invalid loading").text("").removeAttr("title").end().mqlkey(d).bind("valid",function(){c(this).next(".key-status").removeClass("invalid loading").addClass("valid").text("valid").attr("title",
"Key is available")}).bind("invalid",function(a,b){c(this).next(".key-status").removeClass("valid loading").addClass("invalid").text("invalid").attr("title",b)}).bind("textchange",function(){c(this).next(".key-status").removeClass("valid invalid").text("loading").addClass("loading")})},validate_mqlkey:function(a,c){var d=c.next(".key-status"),g=c.val();return""===g?(c.trigger(a.event_prefix+"error","Key is required"),!1):g===c.data("mqlkey").original?!0:d.is(".invalid")?(c.trigger(a.event_prefix+
"error",d.attr("title")),!1):d.is(".loading")?!1:!0},default_begin_ajax_options:function(){return c.extend(a._default_ajax_options("GET"),{beforeSend:function(){d.doing("Loading...")},complete:function(){this.formlib_error||d.clear()}})},default_submit_ajax_options:function(b){var b=b||{},e=c.extend(a._default_ajax_options("POST"),b.ajax,{beforeSend:function(){this.formlib_options=b;d.doing("Saving...");c.isFunction(b.beforeSend)&&b.beforeSend.apply(this,arguments)},complete:function(){this.formlib_error||
d.clear();c.isFunction(b.complete)&&b.complete.apply(this,arguments)}}),f=b.submit_row||b.form;f&&c("input[type=hidden]",f).each(function(){e.data[this.name]=this.value});return e},_default_ajax_options:function(b){return{data:{},dataType:"json",type:b||"GET",success:function(b,d,g){if(!a.check_ajax_success(b,d,g))return this._error(g);if(c.isFunction(this.onsuccess))this.onsuccess(b,d,g)},error:function(a){return this._error(a)},_error:function(b){if(401===b.status)d.info("Authorizing..."),c(window).trigger("fb.user.unauthorized");
else{console.error(b.responseText);this.formlib_error=!0;var f=a.get_error_message(b.responseText);if(c.isFunction(this.onerror))this.onerror(f,b);else b=null,this.formlib_options&&(this.formlib_options.form?(this.formlib_options.form.trigger(this.formlib_options.event_prefix+"cancel"),b=this.formlib_options.form):b=this.formlib_options.edit_row),b?b.trigger(this.formlib_options.event_prefix+"error",f):d.error(f,!0)}}}},check_ajax_success:function(b,c,d){return a.check_api_response(b,c,d)},check_api_response:function(a,
e,f){if(c.isPlainObject(a)){if(a.error&&401===a.error.code)return d.info("Authorizing..."),c(window).trigger("fb.user.unauthorized"),!1;if("/api/status/ok"!==a.code)return!1}else if(200!==f.status)return!1;return!0},get_error_message:function(a){var d=null;try{var f=JSON.parse(a);f&&(f.error&&f.error.message?d=f.error.message:c.isArray(f.messages)&&f.messages.length&&(d=f.messages[0].message))}catch(g){}d||(d=a);return d}}})(jQuery,window.freebase.status);
(function(c){var d=window.editparams={Empty:function(a,b,c){this.structure=a;this.data=b;this.msg=c;this.toString=function(){return"Empty: "+this.msg}},Invalid:function(a,b,c){this.structure=a;this.data=b;this.msg=c;this.toString=function(){return"Invalid: "+this.msg}},parse:function(a,b){function e(a,b,c,e,g){try{d.validate(b,c),g.push(c)}catch(f){if(f instanceof d.Empty)g.push(c);else throw f;}}var f=(a.values||[]).slice(),g=a.properties||[],i=a.expected_type.mediator;if(i){if(!g.length)throw new d.Invalid(a,
null,"mediator musth have 1 or more properties");if(f.length&&1!==f.length)throw new d.Invalid(a,null,"Can't edit more than one value (row) for a mediator");}var j=[];c(".data-input",b).each(function(){var b=c(this),k=b.data("$.data_input");if(!k)throw new d.Invalid(a,null,"$.data-input not initialized for",this);k.validate(!0);if(b.is(".error"))throw new d.Invalid(a,null,"$.data-input is invalid",this);k=b.data("data");if(!k)throw new d.Invalid(a,null,"$.data-input has no data",this);if(i){j.length||
(j.push({property:{}}),c.each(g,function(a,b){j[0].property[b.id]=c.extend({},b,{values:[]})}));var m=j[0].property[k.name];if(m){var l=[];f.length&&(l=(l=f[0].property[m.id])&&l.values||[]);e(b,m,k,l,m.values)}else console.warn("editparams","unknown mediator property data",k)}else e(b,a,k,f,j)});return i?d.parse_mediator(a,f,j):d.parse_simple(a,f,j)},parse_mediator:function(a,b,e){if(1!==e.length)throw new d.Invalid(a,e,"Must specify one (new or updated) value for a mediator");var e=e[0],f;b.length&&
(f=b[0]);b={};if(f)b.id=f.id;else{b.id=null;b.create="unconditional";b.connect=a.unique?"replace":"insert";var g=[];"/type/object"!==a.expected_type.id&&g.push({id:a.expected_type.id,connect:"insert"});var i=a.expected_type.included_types;i&&c.each(i,function(a,b){"/type/object"!==b&&g.push({id:b,connect:"insert"})});g.length&&(b.type=g)}for(var i=!1,a=a.properties,j=0,h=a.length;j<h;j++){var k=a[j],m=f&&f.property&&f.property[k.id],l=e.property&&e.property[k.id],m=d.parse_simple(k,m&&m.values||[],
l&&l.values||[]);m.length&&(b[k.id]=m,i=!0)}return i?[b]:[]},parse_simple:function(a,b,c){return d.diff(a,b,c)},diff:function(a,b,c){var f=a.expected_type,g=a.expected_type.id,i=a.unique,j="/type/text"===g,h="/type/key"===g;if(i&&!j){if(b.length&&1!==b.length)throw new d.Invalid(a,b,"Can't edit more than one value (row) for a unique property.");if(c.length&&1!==c.length)throw new d.Invalid(a,c,"Can't edit more than one value (row) for a unique property.");}var k=[];d.LITERAL_TYPE_IDS[g]?(k.push("value"),
j?k.push("lang"):h&&k.push("namespace")):k.push("id");var g=[],m=[],l,o;l=0;for(o=b.length;l<o;l++){var n=b[l];d.validate(a,n);-1===d.inArray.apply(null,[n,c].concat(k))&&g.push(d.clause(n,"delete"))}l=0;for(o=c.length;l<o;l++){n=c[l];try{d.validate(a,n)}catch(t){continue}if(-1===d.inArray.apply(null,[n,b].concat(k))){if(i)if(j){var r=d.inArray(n,g,"lang");-1!==r&&g.splice(r,1)}else if(!h)return[d.clause(n,"replace",f)];m.push(d.clause(n,i?"replace":"insert",f))}}return g.concat(m)},validate:function(a,
b){var e=a.expected_type.id;if(d.LITERAL_TYPE_IDS[e]){if(d.isEmpty(b.value))throw new d.Empty(a,b);if("/type/text"===e&&d.isEmpty(b.lang))throw new d.Invalid(a,b,"Expected data.lang for /type/text");if("/type/key"===e&&d.isEmpty(b.namespace))throw new d.Invalid(a,b,"Expected data.namespace for /type/key");if("/type/int"===e||"/type/float"===e){if("number"!==c.type(b.value))throw new d.Invalid(a,b,"Expected number data.value for "+e);}else if("/type/boolean"===e){if("boolean"!==c.type(b.value))throw new d.Invalid(a,
b,"Expected boolean data.value for /type/boolean");}else if("string"!==c.type(b.value))throw new d.Invalid(a,b,"Expected string data.value for "+e);}else if(d.isEmpty(b.create_new)){if(d.isEmpty(b.id))throw new d.Empty(a,b);}else if(d.isEmpty(b.lang))throw new d.Invalid(a,b,"Expected lang for creating a new topic");return b},type_clause:function(a){var b=[];if(a){if(a.enumeration||a.never_assert)return b;"/type/object"!==a.id&&b.push({id:a.id,connect:"insert"});(a=a.included_types)&&c.each(a,function(a,
c){"/type/object"!==c&&b.push({id:c,connect:"insert"})})}return b},clause:function(a,b,c){var f={connect:b};a.id?(f.id=a.id,"delete"!==b&&(c&&!c.enumeration)&&(a=d.type_clause(c),a.length&&(f.type=a))):a.create_new&&a.lang?(f.name={value:a.create_new,lang:a.lang},f.id=null,f.create="unconditional",a=d.type_clause(c),a.length&&(f.type=a)):(f.value=a.value,a.lang?f.lang=a.lang:a.namespace&&(f.namespace=a.namespace));return f},inArray:function(a,b){var d=Array.prototype.slice.call(arguments,2);if(!d.length)return c.inArray(a,
b);for(var f=0,g=b.length;f<g;f++){for(var i=b[f],j=!0,h=0,k=d.length;h<k;h++){var m=d[h];if(i[m]!=a[m]){j=!1;break}}if(j)return f}return-1},isEmpty:function(a){return null==a||""===a},LITERAL_TYPE_IDS:{"/type/int":1,"/type/float":1,"/type/boolean":1,"/type/rawstring":1,"/type/uri":1,"/type/text":1,"/type/datetime":1,"/type/id":1,"/type/key":1,"/type/value":1,"/type/enumeration":1}}})(jQuery);
(function(c,d,a,b,e){var f=d.edit={prop_add_begin:function(b){c.ajax(c.extend(a.default_begin_ajax_options(),{url:d.options.base_ajax_url+"/prop_add_begin.ajax",data:{s:d.options.id,p:b.attr("data-id"),lang:d.options.lang},onsuccess:function(a){var a=c(a.result.html),d=a.metadata(),e=d.expected_type.id;return"/common/document"===e?f.prop_add_document(b,a,d):"/common/image"===e?f.prop_add_image(b,a,d):f.prop_add(b,a,d)}}))},prop_add:function(b,e,j){var b=c(">.data-section",b),b=c("> .data-table > tbody, > .data-list",
b),h=c(".edit-row",e),e=c(".edit-row-submit",e),k={event_prefix:"propbox.edit.prop_add.",init:f.init_prop_add_form,validate:f.validate_prop_add_form,submit:f.submit_prop_add_form,reset:f.reset_prop_add_form,ajax:{url:d.options.base_ajax_url+"/prop_edit_submit.ajax"},body:b,edit_row:h,submit_row:e,structure:j};h.bind("propbox.edit.prop_add.success",function(){j.unique&&h.trigger(k.event_prefix+"cancel")});a.init_inline_add_form(k)},init_prop_add_form:function(a){f.init_data_inputs(a);c(":input:visible:first",
a.edit_row).focus()},validate_prop_add_form:function(){return!0},reset_prop_add_form:function(b){f.reset_data_inputs(b);a.disable_submit(b);c(".cancel",b.submit_row).text("Done");c(":input:visible:first",b.edit_row).focus()},submit_prop_add_form:function(e,f){try{var j=b.parse(e.structure,e.edit_row);f.data.o=JSON.stringify(j)}catch(h){j=c(".data-input.error",e.edit_row);j.length?(e.edit_row.trigger(e.event_prefix+"error","Please specify a valid value"),j.eq(0).find(":input").focus().select()):e.edit_row.trigger(e.event_prefix+
"error",h.toString());return}j.length?a.submit_and_continue_inline_add_form(e,c.extend(f,{onsuccess:function(b,f,i){b=c(b.result.html);a.success_inline_add_form(e,b,i);d.init_menus(b,!0);c(".nicemenu-item.edit").show();d.kbs.set_next(null,b,!0)}})):e.edit_row.trigger(e.event_prefix+"error","Please specify a valid value")},value_edit_begin:function(b,i){var j=null,h=null;i.is("tr")?j=i.attr("data-id"):(h=c(".property-value:first",i),j=h.attr("data-value")||h.attr("data-id")||h.attr("datetime"),h=h.attr("data-namespace"));
c.ajax(c.extend(a.default_begin_ajax_options(),{url:d.options.base_ajax_url+"/value_edit_begin.ajax",data:{s:d.options.id,p:b.attr("data-id"),replace:j,namespace:h,lang:d.options.lang},onsuccess:function(a){if(a.result.invalid){e.clear();setTimeout(function(){e.sprintf("warning","The value you are trying edit is no longer valid. Please %s to continue editing.","reload",function(){window.location.reload(true);return false})})}else{var a=c(a.result.html),d=a.metadata(),h=d.expected_type.id;return h===
"/common/document"?f.value_edit_document(b,i,a,d):h==="/common/image"?f.value_edit_image(b,i,a,d):f.value_edit(b,i,a,d)}}}))},value_edit:function(b,e,j,h){var k=c(".edit-row",j),j=c(".edit-row-submit",j),h={event_prefix:"propbox.edit.value_edit.",init:f.init_value_edit_form,validate:f.validate_value_edit_form,submit:f.submit_value_edit_form,ajax:{url:d.options.base_ajax_url+"/prop_edit_submit.ajax"},row:e,edit_row:k,submit_row:j,structure:h};k.bind("propbox.edit.value_edit.delete",function(){k.trigger("propbox.edit.value_edit.cancel");
d.edit.value_delete_begin(b,e)});a.init_inline_edit_form(h)},init_value_edit_form:function(a){f.init_data_inputs(a);c(".delete",a.submit_row).click(function(){a.edit_row.trigger(a.event_prefix+"delete")});c(":input:visible:first",a.edit_row).focus()},validate_value_edit_form:function(){return!0},submit_value_edit_form:function(e,f){try{var j=b.parse(e.structure,e.edit_row);f.data.o=JSON.stringify(j)}catch(h){j=c(".data-input.error",e.edit_row);j.length?(e.edit_row.trigger(e.event_prefix+"error","Please specify a valid value"),
j.eq(0).find(":input").focus().select()):e.edit_row.trigger(e.event_prefix+"error",h.toString());return}c.ajax(c.extend(f,{onsuccess:function(b){b=c(b.result.html);a.success_inline_edit_form(e,b);d.init_menus(b,!0);c(".nicemenu-item.edit").show();d.kbs.set_next(null,b,!0)}}))},value_delete_begin:function(b,f){var j=null,h=null;f.is("tr")?j=f.attr("data-id"):(h=c(".property-value:first",f),j=h.attr("data-value")||h.attr("data-id")||h.attr("datetime"),h=h.attr("data-namespace"));var k={s:d.options.id,
p:b.attr("data-id"),o:j,lang:d.options.lang,namespace:h};c.ajax(c.extend(a.default_submit_ajax_options(),{url:d.options.base_ajax_url+"/value_delete_submit.ajax",data:k,onsuccess:function(b){if(b.result.invalid){e.clear();setTimeout(function(){e.sprintf("warning","The value you are trying remove is no longer valid. Please %s to continue editing.","reload",function(){window.location.reload(true);return false})})}else{var g=c(b.result.html);a.success_inline_delete(f,g,function(){c.ajax(c.extend(a.default_submit_ajax_options(),
{url:d.options.base_ajax_url+"/value_delete_undo.ajax",data:k,onsuccess:function(){a.success_inline_delete_undo(g)}}))})}}}))},prop_add_document:function(b,c,e){a.init_modal_form({event_prefix:"propbox.edit.prop_add_document.",init:f.init_prop_add_document_form,validate:f.validate_prop_add_document_form,submit:f.submit_prop_add_document_form,ajax:{url:d.options.base_ajax_url+"/prop_add_document_submit.ajax"},prop_section:b,form:c,structure:e})},init_prop_add_document_form:function(a){var b=c("select[name=lang]",
a.form);b.change(function(){var e=c(".lang-notice",a.form);this.value===d.options.lang?e.hide():(c("strong",e).text(c("option:selected",b).text()),e.show())});c("textarea",a.form).bind("keypress",function(){a.form.trigger(a.event_prefix+"valid")}).bind("paste",function(){a.form.trigger(a.event_prefix+"valid")}).focus()},validate_prop_add_document_form:function(a){var b=c("textarea",a.form);return""===c.trim(b.val())?(a.form.trigger(a.event_prefix+"invalid"),b.focus(),!1):!0},submit_prop_add_document_form:function(a,
b){var e=c("textarea",a.form);b.data[e.attr("name")]=c.trim(e.val());b.data.lang=c("select[name=lang]",a.form).val();c.ajax(c.extend(b,{onsuccess:function(b){b=c(b.result.html);if(a.prop_row)a.prop_row.replaceWith(b);else{var e=c(">.data-section",a.prop_section);c("> .data-table > tbody, > .data-list",e).append(b)}d.init_menus(b,!0);c(".nicemenu-item.edit").show();d.kbs.set_next(null,b,!0);a.form.trigger(a.event_prefix+"cancel")}}))},value_edit_document:function(b,c,e,h){c={event_prefix:"propbox.edit.value_edit_document.",
init:f.init_value_edit_document_form,validate:f.validate_value_edit_document_form,submit:f.submit_value_edit_document_form,ajax:{url:d.options.base_ajax_url+"/prop_add_document_submit.ajax"},prop_section:b,prop_row:c,form:e,structure:h,cant_edit:e.is(".cant-edit-document-form")};c.cant_edit&&e.bind("propbox.edit.value_edit_document.submit",function(){e.trigger("propbox.edit.value_edit_document.cancel");f.prop_add_begin(b)});a.init_modal_form(c)},init_value_edit_document_form:function(b){b.cant_edit?
a.enable_submit(b):f.init_prop_add_document_form(b)},validate_value_edit_document_form:function(a){return a.cant_edit?!0:f.validate_prop_add_document_form(a)},submit_value_edit_document_form:function(a,b){a.cant_edit||f.submit_prop_add_document_form(a,b)},prop_add_image:function(){alert("Add image not yet implemented")},value_edit_image:function(){alert("Edit image not yet implemented")},add_type_submit:function(b,e){var f=e.attr("data-id"),f={id:d.options.id,type:f,lang:d.options.lang};c.ajax(c.extend(a.default_submit_ajax_options(),
{url:d.options.base_ajax_url+"/add_type_submit.ajax",data:f,onsuccess:function(a){a=c(a.result.html);b.parents(".inline-message:first").replaceWith(a)}}))},remove_type_begin:function(b,e){var j=e.attr("data-id"),j={id:d.options.id,type:j,lang:d.options.lang};c.ajax(c.extend(a.default_begin_ajax_options(),{url:d.options.base_ajax_url+"/remove_type_begin.ajax",data:j,onsuccess:function(h){h=c(h.result.html);a.init_modal_form({event_prefix:"propbox.edit.remove_type.",init:f.remove_type_init,validate:f.remove_type_validate,
submit:f.remove_type_submit,ajax:{url:d.options.base_ajax_url+"/remove_type_submit.ajax"},type_section:e,form:h,trigger:b})}}))},remove_type_init:function(b){c("button.cancel",b.form).focus();a.enable_submit(b)},remove_type_validate:function(){return!0},remove_type_submit:function(a,b){c.ajax(c.extend(b,{onsuccess:function(b){b=c(b.result.html);a.type_section.find("> .header").after(b);a.trigger.hide();a.form.trigger(a.event_prefix+"cancel")}}))},add_has_no_value:function(a){f.valuenotation_submit(a,
"/freebase/valuenotation/has_no_value","insert")},add_has_value:function(a){f.valuenotation_submit(a,"/freebase/valuenotation/has_value","insert")},remove_has_no_value:function(a){f.valuenotation_submit(a,"/freebase/valuenotation/has_no_value","delete")},remove_has_value:function(a){f.valuenotation_submit(a,"/freebase/valuenotation/has_value","delete")},valuenotation_submit:function(b,e,f){e={s:d.options.id,p:e,o:b.attr("data-id"),connect:f,lang:d.options.lang};c.ajax(c.extend(a.default_submit_ajax_options(),
{url:d.options.base_ajax_url+"/valuenotation_submit.ajax",data:e,onsuccess:function(a){a=c(a.result.html);b.replaceWith(a);d.init_menus(a,!0);c(".nicemenu-item.edit",a).show()}}))},more:function(b,e,f){c.ajax(c.extend(a.default_begin_ajax_options(),{url:d.options.base_ajax_url+"/more.ajax",data:{s:e,p:f,lang:d.options.lang},onsuccess:function(a){a=c(a.result.html).children();b.children().remove();b.append(a);d.init_menus(b,!0);c(".nicemenu-item.edit",b).show()}}))},init_data_inputs:function(a){c(".data-input",
a.edit_row||a.form).each(function(){f.init_data_input(c(this),a)})},init_data_input:function(a,b){var e=b.edit_row||b.form;a.data_input({lang:d.options.lang,suggest_impl:d.options.suggest_impl,incompatible_types:d.options.incompatible_types,structure:b.structure}).bind("valid",function(){e.trigger(b.event_prefix+"valid");var d=a.parent(".form-field"),k=d.next(".magicbox-template");k.length&&(k=c("<div>").html(k.html()),k=c(".form-field",k),d.after(k),f.init_data_input(c(".data-input",k),b))}).bind("empty",
function(){e.trigger(b.event_prefix+"valid")}).bind("invalid",function(){e.trigger(b.event_prefix+"invalid")}).bind("submit",function(){e.trigger(b.event_prefix+"submit")}).bind("cancel",function(){e.trigger(b.event_prefix+"cancel")}).bind("loading",function(){c(this).addClass("loading")}).bind("loading_complete",function(){c(this).removeClass("loading")})},reset_data_inputs:function(a){c(".data-input",a.edit_row).each(function(){c(this).data("$.data_input").reset()})}}})(jQuery,window.propbox,window.formlib,
window.editparams,window.freebase.status);
(function(c,d,a,b){var e=d.collection.edit={row_edit_begin:function(a){e._row_edit_begin(a)},row_edit_init:function(b){a.init(b.form,{id:b.row.attr("data-id"),base_ajax_url:d.h.ajax_url("lib/propbox"),base_static_url:d.h.static_url("lib/propbox"),lang:d.lang||"/lang/en",suggest_impl:d.suggest_options,incompatible_types:d.incompatible_types});c(".edit",b.form).show();c(".nicemenu",b.form).nicemenu({overlay:b.overlay.getOverlay()});if(c(".modal-inner.mediator",b.form).length){var g=c(".property-value:first",
b.row).text();c(".modal-nav-title",b.form).text(g)}var g=c(".modal-nav-prev",b.form).unbind(),i=c(".modal-nav-next",b.form).unbind(),j=b.row.prev(".data-row"),h=b.row.next(".data-row");j.length?g.click(function(){e.row_edit_prev(j,b);return!1}).css("visibility","visible"):g.css("visibility","hidden");h.length?i.click(function(){e.row_edit_next(h,b);return!1}).css("visibility","visible"):i.css("visibility","hidden")},row_edit_prev:function(a,b){e._row_edit_begin(a,b)},row_edit_next:function(a,b){e._row_edit_begin(a,
b)},_row_edit_begin:function(a,g){var i=null!=g,j=a.attr("data-id"),h=a.parent("table").metadata().prop_structures,h=h.map(function(a){return a.id}),j={s:j,p:h,lang:d.h.lang_code(d.lang||"/lang/en"),nav:i};c.ajax(c.extend(b.default_begin_ajax_options(),{url:d.h.ajax_url("lib/collection/row_edit_begin.ajax"),data:j,traditional:!0,onsuccess:function(h){h=c(h.result.html);i?(c(".modal-inner",g.form).replaceWith(h),g.row=a,e.row_edit_init(g)):(g={event_prefix:"collection.edit.row_edit.",init:e.row_edit_init,
validate:function(){return!0},submit:function(){},ajax:{},form:h,row:a},c("button[type=submit]",h).hide(),h.ajaxSuccess(function(a,b,d){"POST"===d.type&&c(window).data("reload.collection",!0)}).bind("collection.edit.row_edit.cancel",function(){c(window).data("reload.collection")&&d.status.success("Please reload to see your changes.")}),b.init_modal_form(g))}}))}}})(jQuery,window.freebase,window.propbox,window.formlib,window.editparams);
