
/*
 * Copyright 2010, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Additional Licenses for Third Party components can be found here:
 * http://wiki.freebase.com/wiki/Freebase_Site_License
 *
 */
["flot/excanvas.js","flot/jquery.flot.js","flot/jquery.colorhelpers.js"](function(z){z.plot.plugins.push({init:function(c){function f(a,l){var g;for(g=0;g<l.length;++g)if(l[g].id==a.fillBetween)return l[g];if(typeof a.fillBetween=="number"){g=a.fillBetween;if(g<0||g>=l.length)return null;return l[g]}return null}c.hooks.processDatapoints.push(function(a,l,g){if(l.fillBetween!=null){var j=f(l,a.getData());if(j){a=g.pointsize;var o=g.points,b=j.datapoints.pointsize;j=j.datapoints.points;for(var d=[],
k,n,e,t,h=l.lines.show,r=a>2&&g.format[2].y,q=h&&l.lines.steps,B=true,u=0,v=0,A;;){if(u>=o.length)break;A=d.length;if(o[u]==null){for(m=0;m<a;++m)d.push(o[u+m]);u+=a}else if(v>=j.length){if(!h)for(m=0;m<a;++m)d.push(o[u+m]);u+=a}else if(j[v]==null){for(m=0;m<a;++m)d.push(null);B=true;v+=b}else{k=o[u];n=o[u+1];l=j[v];e=j[v+1];t=0;if(k==l){for(m=0;m<a;++m)d.push(o[u+m]);t=e;u+=a;v+=b}else if(k>l){if(h&&u>0&&o[u-a]!=null){k=n+(o[u-a+1]-n)*(l-k)/(o[u-a]-k);d.push(l);d.push(k);for(m=2;m<a;++m)d.push(o[u+
m]);t=e}v+=b}else{if(B&&h){u+=a;continue}for(m=0;m<a;++m)d.push(o[u+m]);if(h&&v>0&&j[v-b]!=null)t=e+(j[v-b+1]-e)*(k-l)/(j[v-b]-l);u+=a}B=false;if(A!=d.length&&r)d[A+2]=t}if(q&&A!=d.length&&A>0&&d[A]!=null&&d[A]!=d[A-a]&&d[A+1]!=d[A-a+1]){for(m=0;m<a;++m)d[A+a+m]=d[A+m];d[A+1]=d[A-a+1]}}g.points=d}}})},options:{series:{fillBetween:null}},name:"fillbetween",version:"1.0"})})(jQuery);
(function(z){function c(b){var d=this,k,n=b.data||{};if(n.elem){d=b.dragTarget=n.elem;b.dragProxy=o.proxy||d;b.cursorOffsetX=n.pageX-n.left;b.cursorOffsetY=n.pageY-n.top;b.offsetX=b.pageX-b.cursorOffsetX;b.offsetY=b.pageY-b.cursorOffsetY}else if(o.dragging||n.which>0&&b.which!=n.which||z(b.target).is(n.not))return;switch(b.type){case "mousedown":z.extend(n,z(d).offset(),{elem:d,target:b.target,pageX:b.pageX,pageY:b.pageY});g.add(document,"mousemove mouseup",c,n);l(d,false);o.dragging=null;return false;
case !o.dragging&&"mousemove":if(Math.pow(b.pageX-n.pageX,2)+Math.pow(b.pageY-n.pageY,2)<n.distance)break;b.target=n.target;k=f(b,"dragstart",d);if(k!==false){o.dragging=d;o.proxy=b.dragProxy=z(k||d)[0]}case "mousemove":if(o.dragging){k=f(b,"drag",d);if(j.drop){j.drop.allowed=k!==false;j.drop.handler(b)}if(k!==false)break;b.type="mouseup"}case "mouseup":g.remove(document,"mousemove mouseup",c);if(o.dragging){j.drop&&j.drop.handler(b);f(b,"dragend",d)}l(d,true);o.dragging=o.proxy=n.elem=false;break}return true}
function f(b,d,k){b.type=d;d=z.event.handle.call(k,b);return d===false?false:d||b.result}function a(){return o.dragging===false}function l(b,d){if(b){b.unselectable=d?"off":"on";b.onselectstart=function(){return d};if(b.style)b.style.MozUserSelect=d?"":"none"}}z.fn.drag=function(b,d,k){d&&this.bind("dragstart",b);k&&this.bind("dragend",k);return!b?this.trigger("drag"):this.bind("drag",d?d:b)};var g=z.event,j=g.special,o=j.drag={not:":input",distance:0,which:1,dragging:false,setup:function(b){b=z.extend({distance:o.distance,
which:o.which,not:o.not},b||{});b.distance=Math.pow(b.distance,2);g.add(this,"mousedown",c,b);this.attachEvent&&this.attachEvent("ondragstart",a)},teardown:function(){g.remove(this,"mousedown",c);if(this===o.dragging)o.dragging=o.proxy=false;l(this,true);this.detachEvent&&this.detachEvent("ondragstart",a)}};j.dragstart=j.dragend={setup:function(){},teardown:function(){}}})(jQuery);
(function(z){function c(a){var l=[].slice.call(arguments,1),g=0;a=z.event.fix(a||window.event);a.type="mousewheel";if(a.wheelDelta)g=a.wheelDelta/120;if(a.detail)g=-a.detail/3;l.unshift(a,g);return z.event.handle.apply(this,l)}var f=["DOMMouseScroll","mousewheel"];z.event.special.mousewheel={setup:function(){if(this.addEventListener)for(var a=f.length;a;)this.addEventListener(f[--a],c,false);else this.onmousewheel=c},teardown:function(){if(this.removeEventListener)for(var a=f.length;a;)this.removeEventListener(f[--a],
c,false);else this.onmousewheel=null}};z.fn.extend({mousewheel:function(a){return a?this.bind("mousewheel",a):this.trigger("mousewheel")},unmousewheel:function(a){return this.unbind("mousewheel",a)}})})(jQuery);
(function(z){z.plot.plugins.push({init:function(c){c.zoomOut=function(f){f||(f={});if(!f.amount)f.amount=c.getOptions().zoom.amount;f.amount=1/f.amount;c.zoom(f)};c.zoom=function(f){f||(f={});var a=f.center,l=f.amount||c.getOptions().zoom.amount,g=c.width(),j=c.height();a||(a={left:g/2,top:j/2});var o=a.left/g,b=a.top/j,d={x:{min:a.left-o*g/l,max:a.left+(1-o)*g/l},y:{min:a.top-b*j/l,max:a.top+(1-b)*j/l}};z.each(c.getUsedAxes(),function(k,n){var e=n.options,t=d[n.direction].min,h=d[n.direction].max;
t=n.c2p(t);h=n.c2p(h);if(t>h){var r=t;t=h;h=r}r=h-t;var q=e.zoomRange;if(!(q&&(q[0]!=null&&r<q[0]||q[1]!=null&&r>q[1]))){e.min=t;e.max=h}});c.setupGrid();c.draw();f.preventEvent||c.getPlaceholder().trigger("plotzoom",[c])};c.pan=function(f){var a={x:+f.left,y:+f.top};if(isNaN(a.x))a.x=0;if(isNaN(a.y))a.y=0;z.each(c.getUsedAxes(),function(l,g){var j=g.options,o,b,d=a[g.direction];o=g.c2p(g.p2c(g.min)+d);b=g.c2p(g.p2c(g.max)+d);var k=j.panRange;if(k){if(k[0]!=null&&k[0]>o){d=k[0]-o;o+=d;b+=d}if(k[1]!=
null&&k[1]<b){d=k[1]-b;o+=d;b+=d}}j.min=o;j.max=b});c.setupGrid();c.draw();f.preventEvent||c.getPlaceholder().trigger("plotpan",[c])};c.hooks.bindEvents.push(function(f,a){var l=f.getOptions();if(l.zoom.interactive){var g=function(d,k){var n=f.offset();n.left=d.pageX-n.left;n.top=d.pageY-n.top;k?f.zoomOut({center:n}):f.zoom({center:n})};a[l.zoom.trigger](g);a.mousewheel(function(d,k){g(d,k<0);return false})}if(l.pan.interactive){var j=0,o=0,b=null;a.bind("dragstart",{distance:10},function(d){if(d.which!=
1)return false;eventHolderCursor=a.css("cursor");a.css("cursor","move");j=d.pageX;o=d.pageY});a.bind("drag",function(d){b||!l.pan.frameRate||(b=setTimeout(function(){f.pan({left:j-d.pageX,top:o-d.pageY});j=d.pageX;o=d.pageY;b=null},1/l.pan.frameRate*1E3))});a.bind("dragend",function(d){if(b){clearTimeout(b);b=null}a.css("cursor","default");f.pan({left:j-d.pageX,top:o-d.pageY})})}})},options:{xaxis:{zoomRange:null,panRange:null},zoom:{interactive:false,trigger:"dblclick",amount:1.5},pan:{interactive:false,
frameRate:20}},name:"navigate",version:"1.2"})})(jQuery);
(function(z){z.plot.plugins.push({init:function(c){c.hooks.processDatapoints.push(function(f,a,l){if(a.stack!=null){var g;f=f.getData();for(var j=null,o=0;o<f.length;++o){if(a==f[o])break;if(f[o].stack==a.stack)j=f[o]}if(g=j){f=l.pointsize;j=l.points;o=g.datapoints.pointsize;g=g.datapoints.points;var b=[],d,k,n,e,t,h,r=a.lines.show;e=a.bars.horizontal;var q=f>2&&(e?l.format[2].x:l.format[2].y);a=r&&a.lines.steps;n=true;for(var B=e?1:0,u=e?0:1,v=0,A=0,G;;){if(v>=j.length)break;G=b.length;if(j[v]==
null){for(m=0;m<f;++m)b.push(j[v+m]);v+=f}else if(A>=g.length){if(!r)for(m=0;m<f;++m)b.push(j[v+m]);v+=f}else if(g[A]==null){for(m=0;m<f;++m)b.push(null);n=true;A+=o}else{d=j[v+B];k=j[v+u];e=g[A+B];t=g[A+u];h=0;if(d==e){for(m=0;m<f;++m)b.push(j[v+m]);b[G+u]+=t;h=t;v+=f;A+=o}else if(d>e){if(r&&v>0&&j[v-f]!=null){n=k+(j[v-f+u]-k)*(e-d)/(j[v-f+B]-d);b.push(e);b.push(n+t);for(m=2;m<f;++m)b.push(j[v+m]);h=t}A+=o}else{if(n&&r){v+=f;continue}for(m=0;m<f;++m)b.push(j[v+m]);if(r&&A>0&&g[A-o]!=null)h=t+(g[A-
o+u]-t)*(d-e)/(g[A-o+B]-e);b[G+u]+=h;v+=f}n=false;if(G!=b.length&&q)b[G+2]+=h}if(a&&G!=b.length&&G>0&&b[G]!=null&&b[G]!=b[G-f]&&b[G+1]!=b[G-f+1]){for(m=0;m<f;++m)b[G+f+m]=b[G+m];b[G+1]=b[G-f+1]}}l.points=b}}})},options:{series:{stack:null}},name:"stack",version:"1.2"})})(jQuery);
(function(z){function c(a,l,g){a=a.getPlotOffset();if(g.images&&g.images.show)for(var j=g.datapoints.points,o=g.datapoints.pointsize,b=0;b<j.length;b+=o){var d=j[b],k=j[b+1],n=j[b+2],e=j[b+3],t=j[b+4],h=g.xaxis,r=g.yaxis,q;if(!(!d||d.width<=0||d.height<=0)){if(k>e){q=e;e=k;k=q}if(n>t){q=t;t=n;n=q}if(g.images.anchor=="center"){q=0.5*(e-k)/(d.width-1);k-=q;e+=q;q=0.5*(t-n)/(d.height-1);n-=q;t+=q}if(!(k==e||n==t||k>=h.max||e<=h.min||n>=r.max||t<=r.min)){var B=0,u=0,v=d.width,A=d.height;if(k<h.min){B+=
(v-B)*(h.min-k)/(e-k);k=h.min}if(e>h.max){v+=(v-B)*(h.max-e)/(e-k);e=h.max}if(n<r.min){A+=(u-A)*(r.min-n)/(t-n);n=r.min}if(t>r.max){u+=(u-A)*(r.max-t)/(t-n);t=r.max}k=h.p2c(k);e=h.p2c(e);n=r.p2c(n);t=r.p2c(t);if(k>e){q=e;e=k;k=q}if(n>t){q=t;t=n;n=q}q=l.globalAlpha;l.globalAlpha*=g.images.alpha;l.drawImage(d,B,u,v-B,A-u,k+a.left,n+a.top,e-k,t-n);l.globalAlpha=q}}}}function f(a,l,g,j){if(l.images.show)j.format=[{required:true},{x:true,number:true,required:true},{y:true,number:true,required:true},{x:true,
number:true,required:true},{y:true,number:true,required:true}]}z.plot.image={};z.plot.image.loadDataImages=function(a,l,g){var j=[],o=[],b=l.series.images.show;z.each(a,function(d,k){if(b||k.images.show){if(k.data)k=k.data;z.each(k,function(n,e){if(typeof e[0]=="string"){j.push(e[0]);o.push(e)}})}});z.plot.image.load(j,function(d){z.each(o,function(k,n){var e=n[0];if(d[e])n[0]=d[e]});g()})};z.plot.image.load=function(a,l){var g=a.length,j={};g==0&&l({});z.each(a,function(o,b){var d=function(){--g;
j[b]=this;g==0&&l(j)};z("<img />").load(d).error(d).attr("src",b)})};z.plot.plugins.push({init:function(a){a.hooks.processRawData.push(f);a.hooks.drawSeries.push(c)},options:{series:{images:{show:false,alpha:1,anchor:"corner"}}},name:"image",version:"1.1"})})(jQuery);
(function(z){var c={series:{pie:{show:false,radius:"auto",innerRadius:0,startAngle:1.5,tilt:1,offset:{top:0,left:"auto"},stroke:{color:"#FFF",width:1},label:{show:"auto",formatter:function(f,a){return'<div style="font-size:x-small;text-align:center;padding:2px;color:'+a.color+';">'+f+"<br/>"+Math.round(a.percent)+"%</div>"},radius:1,background:{color:null,opacity:0},threshold:0},combine:{threshold:-1,color:null,label:"Other"},highlight:{opacity:0.5}}}};z.plot.plugins.push({init:function(f){function a(p){if(!W){W=
true;e=p.getCanvas();t=z(e).parent();c=p.getOptions();p.setData(l(p.getData()))}}function l(p){p=p;for(var s=0;s<p.length;++s)if(typeof p[s].data=="number")p[s].data=[[1,p[s].data]];else if(typeof p[s].data=="undefined"||typeof p[s].data[0]=="undefined"){if(typeof p[s].data!="undefined"&&typeof p[s].data.label!="undefined")p[s].label=p[s].data.label;p[s].data=[[1,0]]}s=p=p;for(var D=0;D<s.length;++D){var F=parseFloat(s[D].data[0][1]);if(F)B+=F}D=s=0;F=c.series.pie.combine.color;for(var E=[],w=0;w<
p.length;++w){p[w].data[0][1]=parseFloat(p[w].data[0][1]);p[w].data[0][1]||(p[w].data[0][1]=0);if(p[w].data[0][1]/B<=c.series.pie.combine.threshold){s+=p[w].data[0][1];D++;if(!F)F=p[w].color}else E.push({data:[[1,p[w].data[0][1]]],color:p[w].color,label:p[w].label,angle:p[w].data[0][1]*Math.PI*2/B,percent:p[w].data[0][1]/B*100})}D>0&&E.push({data:[[1,s]],color:F,label:c.series.pie.combine.label,angle:s*Math.PI*2/B,percent:s/B*100});return E}function g(p,s){function D(){ctx.clearRect(0,0,e.width,e.height);
t.children().filter(".pieLabel, .pieLabelBackground").remove()}function F(){var C=c.series.pie.radius>1?c.series.pie.radius:h*c.series.pie.radius;if(!(C>=e.width/2-5||C*c.series.pie.tilt>=e.height/2-15||C<=10)){ctx.save();ctx.translate(5,15);ctx.globalAlpha=0.02;ctx.fillStyle="#000";ctx.translate(r,q);ctx.scale(1,c.series.pie.tilt);for(var P=1;P<=10;P++){ctx.beginPath();ctx.arc(0,0,C,0,Math.PI*2,false);ctx.fill();C-=P}ctx.restore()}}function E(){function C(R,U,V){if(!(R<=0)){if(V)ctx.fillStyle=U;
else{ctx.strokeStyle=U;ctx.lineJoin="round"}ctx.beginPath();if(R!=Math.PI*2)ctx.moveTo(0,0);else if(z.browser.msie)R-=1.0E-4;ctx.arc(0,0,L,Q,Q+R,false);ctx.closePath();Q+=R;V?ctx.fill():ctx.stroke()}}function P(){function R(S,M,I){if(S.data[0][1]!=0){var K=c.legend.labelFormatter,J=c.series.pie.label.formatter;K=K?K(S.label,S):S.label;if(J)K=J(K,S);J=(M+S.angle+M)/2;M=r+Math.round(Math.cos(J)*V);J=q+Math.round(Math.sin(J)*V)*c.series.pie.tilt;t.append('<span class="pieLabel" id="pieLabel'+I+'" style="position:absolute;top:'+
J+"px;left:"+M+'px;">'+K+"</span>");I=t.children("#pieLabel"+I);K=J-I.height()/2;M=M-I.width()/2;I.css("top",K);I.css("left",M);if(0-K>0||0-M>0||e.height-(K+I.height())<0||e.width-(M+I.width())<0)u=true;if(c.series.pie.label.background.opacity!=0){J=c.series.pie.label.background.color;if(J==null)J=S.color;z('<div class="pieLabelBackground" style="position:absolute;width:'+I.width()+"px;height:"+I.height()+"px;"+("top:"+K+"px;left:"+M+"px;")+"background-color:"+J+';"> </div>').insertBefore(I).css("opacity",
c.series.pie.label.background.opacity)}}}for(var U=startAngle,V=c.series.pie.label.radius>1?c.series.pie.label.radius:h*c.series.pie.label.radius,T=0;T<w.length;++T){w[T].percent>=c.series.pie.label.threshold*100&&R(w[T],U,T);U+=w[T].angle}}startAngle=Math.PI*c.series.pie.startAngle;var L=c.series.pie.radius>1?c.series.pie.radius:h*c.series.pie.radius;ctx.save();ctx.translate(r,q);ctx.scale(1,c.series.pie.tilt);ctx.save();for(var Q=startAngle,H=0;H<w.length;++H){w[H].startAngle=Q;C(w[H].angle,w[H].color,
true)}ctx.restore();ctx.save();ctx.lineWidth=c.series.pie.stroke.width;Q=startAngle;for(H=0;H<w.length;++H)C(w[H].angle,c.series.pie.stroke.color,false);ctx.restore();j(ctx);c.series.pie.label.show&&P();ctx.restore()}if(t){ctx=s;G=t.children().filter(".legend").children().width();h=Math.min(e.width,e.height/c.series.pie.tilt)/2;q=e.height/2+c.series.pie.offset.top;r=e.width/2;if(c.series.pie.offset.left=="auto")if(c.legend.position.match("w"))r+=G/2;else r-=G/2;else r+=c.series.pie.offset.left;if(r<
h)r=h;else if(r>e.width-h)r=e.width-h;for(var w=p.getData(),N=0;u&&N<v;){u=false;if(N>0)h*=A;N+=1;D();c.series.pie.tilt<=0.8&&F();E()}if(N>=v){D();t.prepend('<div class="error">Could not draw pie with labels contained inside canvas</div>')}if(p.setSeries&&p.insertLegend){p.setSeries(w);p.insertLegend()}}}function j(p){if(c.series.pie.innerRadius>0){p.save();innerRadius=c.series.pie.innerRadius>1?c.series.pie.innerRadius:h*c.series.pie.innerRadius;p.globalCompositeOperation="destination-out";p.beginPath();
p.fillStyle=c.series.pie.stroke.color;p.arc(0,0,innerRadius,0,Math.PI*2,false);p.fill();p.closePath();p.restore();p.save();p.beginPath();p.strokeStyle=c.series.pie.stroke.color;p.arc(0,0,innerRadius,0,Math.PI*2,false);p.stroke();p.closePath();p.restore()}}function o(p){d("plothover",p)}function b(p){d("plotclick",p)}function d(p,s){var D=f.offset(),F=parseInt(s.pageX-D.left);a:{D=parseInt(s.pageY-D.top);var E=f.getData(),w=f.getOptions();w=w.series.pie.radius>1?w.series.pie.radius:h*w.series.pie.radius;
for(var N=0;N<E.length;++N){var C=E[N];if(C.pie.show){ctx.save();ctx.beginPath();ctx.moveTo(0,0);ctx.arc(0,0,w,C.startAngle,C.startAngle+C.angle,false);ctx.closePath();x=F-r;y=D-q;if(ctx.isPointInPath){if(ctx.isPointInPath(F-r,D-q)){ctx.restore();F={datapoint:[C.percent,C.data],dataIndex:0,series:C,seriesIndex:N};break a}}else{p1X=w*Math.cos(C.startAngle);p1Y=w*Math.sin(C.startAngle);p2X=w*Math.cos(C.startAngle+C.angle/4);p2Y=w*Math.sin(C.startAngle+C.angle/4);p3X=w*Math.cos(C.startAngle+C.angle/
2);p3Y=w*Math.sin(C.startAngle+C.angle/2);p4X=w*Math.cos(C.startAngle+C.angle/1.5);p4Y=w*Math.sin(C.startAngle+C.angle/1.5);p5X=w*Math.cos(C.startAngle+C.angle);p5Y=w*Math.sin(C.startAngle+C.angle);arrPoly=[[0,0],[p1X,p1Y],[p2X,p2Y],[p3X,p3Y],[p4X,p4Y],[p5X,p5Y]];arrPoint=[x,y];for(var P=false,L=-1,Q=arrPoly.length,H=Q-1;++L<Q;H=L)(arrPoly[L][1]<=arrPoint[1]&&arrPoint[1]<arrPoly[H][1]||arrPoly[H][1]<=arrPoint[1]&&arrPoint[1]<arrPoly[L][1])&&arrPoint[0]<(arrPoly[H][0]-arrPoly[L][0])*(arrPoint[1]-arrPoly[L][1])/
(arrPoly[H][1]-arrPoly[L][1])+arrPoly[L][0]&&(P=!P);if(P){ctx.restore();F={datapoint:[C.percent,C.data],dataIndex:0,series:C,seriesIndex:N};break a}}ctx.restore()}}F=null}if(c.grid.autoHighlight)for(D=0;D<O.length;++D){E=O[D];if(E.auto==p&&!(F&&E.series==F.series)){E=E.series;if(E==null){O=[];f.triggerRedrawOverlay()}if(typeof E=="number")E=series[E];E=k(E);if(E!=-1){O.splice(E,1);f.triggerRedrawOverlay()}}}if(F){D=F.series;if(typeof D=="number")D=series[D];E=k(D);if(E==-1){O.push({series:D,auto:p});
f.triggerRedrawOverlay()}else if(!p)O[E].auto=false;t.trigger(p,[{pageX:s.pageX,pageY:s.pageY},F])}}function k(p){for(var s=0;s<O.length;++s)if(O[s].series==p)return s;return-1}function n(p,s){function D(w){if(!(w.angle<0)){s.fillStyle="rgba(255, 255, 255, "+F.series.pie.highlight.opacity+")";s.beginPath();w.angle!=Math.PI*2&&s.moveTo(0,0);s.arc(0,0,E,w.startAngle,w.startAngle+w.angle,false);s.closePath();s.fill()}}var F=p.getOptions(),E=F.series.pie.radius>1?F.series.pie.radius:h*F.series.pie.radius;
s.save();s.translate(r,q);s.scale(1,F.series.pie.tilt);for(i=0;i<O.length;++i)D(O[i].series);j(s);s.restore()}var e=null,t=null,h=null,r=null,q=null,B=0,u=true,v=10,A=0.95,G=0,W=false,O=[];f.hooks.processOptions.push(function(p,s){if(s.series.pie.show){s.grid.show=false;if(s.series.pie.label.show=="auto")s.series.pie.label.show=s.legend.show?false:true;if(s.series.pie.radius=="auto")s.series.pie.radius=s.series.pie.label.show?0.75:1;if(s.series.pie.tilt>1)s.series.pie.tilt=1;if(s.series.pie.tilt<
0)s.series.pie.tilt=0;p.hooks.processDatapoints.push(a);p.hooks.drawOverlay.push(n);p.hooks.draw.push(g)}});f.hooks.bindEvents.push(function(p,s){var D=p.getOptions();D.series.pie.show&&D.grid.hoverable&&s.unbind("mousemove").mousemove(o);D.series.pie.show&&D.grid.clickable&&s.unbind("click").click(b)})},options:c,name:"pie",version:"1.0"})})(jQuery);
(function(z){z.plot.plugins.push({init:function(c){c.hooks.processDatapoints.push(function(f,a,l){if(a.threshold){var g=l.pointsize,j,o,b,d,k=z.extend({},a);k.datapoints={points:[],pointsize:g};k.label=null;k.color=a.threshold.color;k.threshold=null;k.originSeries=a;k.data=[];var n=a.threshold.below,e=l.points,t=a.lines.show;threspoints=[];newpoints=[];for(a=0;a<e.length;a+=g){j=e[a];o=e[a+1];d=b;b=o<n?threspoints:newpoints;if(t&&d!=b&&j!=null&&a>0&&e[a-g]!=null){var h=(j-e[a-g])/(o-e[a-g+1])*(n-
o)+j;d.push(h);d.push(n);for(m=2;m<g;++m)d.push(e[a+m]);b.push(null);b.push(null);for(m=2;m<g;++m)b.push(e[a+m]);b.push(h);b.push(n);for(m=2;m<g;++m)b.push(e[a+m])}b.push(j);b.push(o)}l.points=newpoints;k.datapoints.points=threspoints;k.datapoints.points.length>0&&f.getData().push(k)}})},options:{series:{threshold:null}},name:"threshold",version:"1.0"})})(jQuery);
(function(z){z.plot.plugins.push({init:function(c){var f={x:-1,y:-1,locked:false};c.setCrosshair=function(a){if(a){a=c.p2c(a);f.x=Math.max(0,Math.min(a.left,c.width()));f.y=Math.max(0,Math.min(a.top,c.height()))}else f.x=-1;c.triggerRedrawOverlay()};c.clearCrosshair=c.setCrosshair;c.lockCrosshair=function(a){a&&c.setCrosshair(a);f.locked=true};c.unlockCrosshair=function(){f.locked=false};c.hooks.bindEvents.push(function(a,l){if(a.getOptions().crosshair.mode){l.mouseout(function(){if(!f.locked)if(f.x!=
-1){f.x=-1;a.triggerRedrawOverlay()}});l.mousemove(function(g){if(!f.locked)if(a.getSelection&&a.getSelection())f.x=-1;else{var j=a.offset();f.x=Math.max(0,Math.min(g.pageX-j.left,a.width()));f.y=Math.max(0,Math.min(g.pageY-j.top,a.height()));a.triggerRedrawOverlay()}})}});c.hooks.drawOverlay.push(function(a,l){var g=a.getOptions().crosshair;if(g.mode){var j=a.getPlotOffset();l.save();l.translate(j.left,j.top);if(f.x!=-1){l.strokeStyle=g.color;l.lineWidth=g.lineWidth;l.lineJoin="round";l.beginPath();
if(g.mode.indexOf("x")!=-1){l.moveTo(f.x,0);l.lineTo(f.x,a.height())}if(g.mode.indexOf("y")!=-1){l.moveTo(0,f.y);l.lineTo(a.width(),f.y)}l.stroke()}l.restore()}})},options:{crosshair:{mode:null,color:"rgba(170, 0, 0, 0.80)",lineWidth:1}},name:"crosshair",version:"1.0"})})(jQuery);
(function(z){z.plot.plugins.push({init:function(c){function f(h){if(e.active){c.getPlaceholder().trigger("plotselecting",[g()]);b(h)}}function a(h){if(h.which==1){document.body.focus();if(document.onselectstart!==undefined&&t.onselectstart==null){t.onselectstart=document.onselectstart;document.onselectstart=function(){return false}}if(document.ondrag!==undefined&&t.ondrag==null){t.ondrag=document.ondrag;document.ondrag=function(){return false}}o(e.first,h);e.active=true;z(document).one("mouseup",
l)}}function l(h){if(document.onselectstart!==undefined)document.onselectstart=t.onselectstart;if(document.ondrag!==undefined)document.ondrag=t.ondrag;e.active=false;b(h);if(n())j();else{c.getPlaceholder().trigger("plotunselected",[]);c.getPlaceholder().trigger("plotselecting",[null])}return false}function g(){if(!n())return null;var h={},r=e.first,q=e.second;z.each(c.getAxes(),function(B,u){if(u.used){var v=u.c2p(r[u.direction]),A=u.c2p(q[u.direction]);h[B]={from:Math.min(v,A),to:Math.max(v,A)}}});
return h}function j(){var h=g();c.getPlaceholder().trigger("plotselected",[h]);h.xaxis&&h.yaxis&&c.getPlaceholder().trigger("selected",[{x1:h.xaxis.from,y1:h.yaxis.from,x2:h.xaxis.to,y2:h.yaxis.to}])}function o(h,r){var q=c.getOptions(),B=c.getPlaceholder().offset(),u=c.getPlotOffset(),v=r.pageX-B.left-u.left,A=c.width();h.x=v<0?0:v>A?A:v;B=r.pageY-B.top-u.top;u=c.height();h.y=B<0?0:B>u?u:B;if(q.selection.mode=="y")h.x=h==e.first?0:c.width();if(q.selection.mode=="x")h.y=h==e.first?0:c.height()}function b(h){if(h.pageX!=
null){o(e.second,h);if(n()){e.show=true;c.triggerRedrawOverlay()}else d(true)}}function d(h){if(e.show){e.show=false;c.triggerRedrawOverlay();h||c.getPlaceholder().trigger("plotunselected",[])}}function k(h,r){var q,B,u,v,A;v=c.getUsedAxes();for(i=0;i<v.length;++i){q=v[i];if(q.direction==r){A=r+q.n+"axis";if(!h[A]&&q.n==1)A=r+"axis";if(h[A]){B=h[A].from;u=h[A].to;break}}}if(!h[A]){q=r=="x"?c.getXAxes()[0]:c.getYAxes()[0];B=h[r+"1"];u=h[r+"2"]}if(B!=null&&u!=null&&B>u){v=B;B=u;u=v}return{from:B,to:u,
axis:q}}function n(){return Math.abs(e.second.x-e.first.x)>=5&&Math.abs(e.second.y-e.first.y)>=5}var e={first:{x:-1,y:-1},second:{x:-1,y:-1},show:false,active:false},t={};c.clearSelection=d;c.setSelection=function(h,r){var q,B=c.getOptions();if(B.selection.mode=="y"){e.first.x=0;e.second.x=c.width()}else{q=k(h,"x");e.first.x=q.axis.p2c(q.from);e.second.x=q.axis.p2c(q.to)}if(B.selection.mode=="x"){e.first.y=0;e.second.y=c.height()}else{q=k(h,"y");e.first.y=q.axis.p2c(q.from);e.second.y=q.axis.p2c(q.to)}e.show=
true;c.triggerRedrawOverlay();!r&&n()&&j()};c.getSelection=g;c.hooks.bindEvents.push(function(h,r){var q=h.getOptions();q.selection.mode!=null&&r.mousemove(f);q.selection.mode!=null&&r.mousedown(a)});c.hooks.drawOverlay.push(function(h,r){if(e.show&&n()){var q=h.getPlotOffset(),B=h.getOptions();r.save();r.translate(q.left,q.top);q=z.color.parse(B.selection.color);r.strokeStyle=q.scale("a",0.8).toString();r.lineWidth=1;r.lineJoin="round";r.fillStyle=q.scale("a",0.4).toString();q=Math.min(e.first.x,
e.second.x);B=Math.min(e.first.y,e.second.y);var u=Math.abs(e.second.x-e.first.x),v=Math.abs(e.second.y-e.first.y);r.fillRect(q,B,u,v);r.strokeRect(q,B,u,v);r.restore()}})},options:{selection:{mode:null,color:"#e8cfac"}},name:"selection",version:"1.0"})})(jQuery);
