
/*
 * Copyright 2010, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Additional Licenses for Third Party components can be found here:
 * http://wiki.freebase.com/wiki/Freebase_Site_License
 *
 */
/*
 
 jQuery Tools @VERSION Tabs- The basics of UI design.

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/tabs/

 Since: November 2008
 Date: @DATE 
*/
(function(a){function j(c,b,d){var e=this,i=c.add(this),g=c.find(d.tabs),h=b.jquery?b:c.children(b),n;g.length||(g=c.children());h.length||(h=c.parent().find(b));h.length||(h=a(b));a.extend(this,{click:function(m,l){var o=g.eq(m);if(typeof m=="string"&&m.replace("#","")){m=m.replace(/([\"\#\$\%\&\'\(\)\*\+\,\.\/\:\;\<\=\>\?\@\[\\\]\^\`\{\|\}\~])/g,"\\$1");o=g.filter("[href*="+m.replace("#","")+"]");m=Math.max(g.index(o),0)}if(d.rotate){var q=g.length-1;if(m<0)return e.click(q,l);if(m>q)return e.click(0,
l)}if(!o.length){if(n>=0)return e;m=d.initialIndex;o=g.eq(m)}if(m===n)return e;l=l||a.Event();l.type="onBeforeClick";i.trigger(l,[m]);if(!l.isDefaultPrevented()){k[d.effect].call(e,m,function(){l.type="onClick";i.trigger(l,[m])});n=m;g.removeClass(d.current);o.addClass(d.current);return e}},getConf:function(){return d},getTabs:function(){return g},getPanes:function(){return h},getCurrentPane:function(){return h.eq(n)},getCurrentTab:function(){return g.eq(n)},getIndex:function(){return n},next:function(){return e.click(n+
1)},prev:function(){return e.click(n-1)},destroy:function(){g.unbind(d.event).removeClass(d.current);h.find("a[href^=#]").unbind("click.T");return e}});a.each("onBeforeClick,onClick".split(","),function(m,l){a.isFunction(d[l])&&a(e).bind(l,d[l]);e[l]=function(o){a(e).bind(l,o);return e}});if(d.history&&a.fn.history){a.tools.history.init(g);d.event="history"}g.each(function(m){a(this).bind(d.event,function(l){e.click(m,l);return l.preventDefault()})});h.find("a[href^=#]").bind("click.T",function(m){e.click(a(this).attr("href"),
m)});if(location.hash)e.click(location.hash);else if(d.initialIndex===0||d.initialIndex>0)e.click(d.initialIndex)}a.tools=a.tools||{version:"@VERSION"};a.tools.tabs={conf:{tabs:"a",current:"current",onBeforeClick:null,onClick:null,effect:"default",initialIndex:0,event:"click",rotate:false,history:false},addEffect:function(c,b){k[c]=b}};var k={"default":function(c,b){this.getPanes().hide().eq(c).show();b.call()},fade:function(c,b){var d=this.getConf(),e=d.fadeOutSpeed,i=this.getPanes();e?i.fadeOut(e):
i.hide();i.eq(c).fadeIn(d.fadeInSpeed,b)},slide:function(c,b){this.getPanes().slideUp(200);this.getPanes().eq(c).slideDown(400,b)},ajax:function(c,b){this.getPanes().eq(0).load(this.getTabs().eq(c).attr("href"),b)}},f;a.tools.tabs.addEffect("horizontal",function(c,b){f||(f=this.getPanes().eq(0).width());this.getCurrentPane().animate({width:0},function(){a(this).hide()});this.getPanes().eq(c).animate({width:f},function(){a(this).show();b.call()})});a.fn.tabs=function(c,b){var d=this.data("tabs");if(d){d.destroy();
this.removeData("tabs")}if(a.isFunction(b))b={onBeforeClick:b};b=a.extend({},a.tools.tabs.conf,b);this.each(function(){d=new j(a(this),c,b);a(this).data("tabs",d)});return b.api?d:this}})(jQuery);
(function(a,j){function k(f){return!a(f).parents().andSelf().filter(function(){return a.curCSS(this,"visibility")==="hidden"||a.expr.filters.hidden(this)}).length}a.ui=a.ui||{};if(!a.ui.version){a.extend(a.ui,{version:"1.8.10",keyCode:{ALT:18,BACKSPACE:8,CAPS_LOCK:20,COMMA:188,COMMAND:91,COMMAND_LEFT:91,COMMAND_RIGHT:93,CONTROL:17,DELETE:46,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,INSERT:45,LEFT:37,MENU:93,NUMPAD_ADD:107,NUMPAD_DECIMAL:110,NUMPAD_DIVIDE:111,NUMPAD_ENTER:108,NUMPAD_MULTIPLY:106,NUMPAD_SUBTRACT:109,
PAGE_DOWN:34,PAGE_UP:33,PERIOD:190,RIGHT:39,SHIFT:16,SPACE:32,TAB:9,UP:38,WINDOWS:91}});a.fn.extend({_focus:a.fn.focus,focus:function(f,c){return typeof f==="number"?this.each(function(){var b=this;setTimeout(function(){a(b).focus();c&&c.call(b)},f)}):this._focus.apply(this,arguments)},scrollParent:function(){var f;f=a.browser.msie&&/(static|relative)/.test(this.css("position"))||/absolute/.test(this.css("position"))?this.parents().filter(function(){return/(relative|absolute|fixed)/.test(a.curCSS(this,
"position",1))&&/(auto|scroll)/.test(a.curCSS(this,"overflow",1)+a.curCSS(this,"overflow-y",1)+a.curCSS(this,"overflow-x",1))}).eq(0):this.parents().filter(function(){return/(auto|scroll)/.test(a.curCSS(this,"overflow",1)+a.curCSS(this,"overflow-y",1)+a.curCSS(this,"overflow-x",1))}).eq(0);return/fixed/.test(this.css("position"))||!f.length?a(document):f},zIndex:function(f){if(f!==j)return this.css("zIndex",f);if(this.length){f=a(this[0]);for(var c;f.length&&f[0]!==document;){c=f.css("position");
if(c==="absolute"||c==="relative"||c==="fixed"){c=parseInt(f.css("zIndex"),10);if(!isNaN(c)&&c!==0)return c}f=f.parent()}}return 0},disableSelection:function(){return this.bind((a.support.selectstart?"selectstart":"mousedown")+".ui-disableSelection",function(f){f.preventDefault()})},enableSelection:function(){return this.unbind(".ui-disableSelection")}});a.each(["Width","Height"],function(f,c){function b(g,h,n,m){a.each(d,function(){h-=parseFloat(a.curCSS(g,"padding"+this,true))||0;if(n)h-=parseFloat(a.curCSS(g,
"border"+this+"Width",true))||0;if(m)h-=parseFloat(a.curCSS(g,"margin"+this,true))||0});return h}var d=c==="Width"?["Left","Right"]:["Top","Bottom"],e=c.toLowerCase(),i={innerWidth:a.fn.innerWidth,innerHeight:a.fn.innerHeight,outerWidth:a.fn.outerWidth,outerHeight:a.fn.outerHeight};a.fn["inner"+c]=function(g){if(g===j)return i["inner"+c].call(this);return this.each(function(){a(this).css(e,b(this,g)+"px")})};a.fn["outer"+c]=function(g,h){if(typeof g!=="number")return i["outer"+c].call(this,g);return this.each(function(){a(this).css(e,
b(this,g,true,h)+"px")})}});a.extend(a.expr[":"],{data:function(f,c,b){return!!a.data(f,b[3])},focusable:function(f){var c=f.nodeName.toLowerCase(),b=a.attr(f,"tabindex");if("area"===c){c=f.parentNode;b=c.name;if(!f.href||!b||c.nodeName.toLowerCase()!=="map")return false;f=a("img[usemap=#"+b+"]")[0];return!!f&&k(f)}return(/input|select|textarea|button|object/.test(c)?!f.disabled:"a"==c?f.href||!isNaN(b):!isNaN(b))&&k(f)},tabbable:function(f){var c=a.attr(f,"tabindex");return(isNaN(c)||c>=0)&&a(f).is(":focusable")}});
a(function(){var f=document.body,c=f.appendChild(c=document.createElement("div"));a.extend(c.style,{minHeight:"100px",height:"auto",padding:0,borderWidth:0});a.support.minHeight=c.offsetHeight===100;a.support.selectstart="onselectstart"in c;f.removeChild(c).style.display="none"});a.extend(a.ui,{plugin:{add:function(f,c,b){f=a.ui[f].prototype;for(var d in b){f.plugins[d]=f.plugins[d]||[];f.plugins[d].push([c,b[d]])}},call:function(f,c,b){if((c=f.plugins[c])&&f.element[0].parentNode)for(var d=0;d<c.length;d++)f.options[c[d][0]]&&
c[d][1].apply(f.element,b)}},contains:function(f,c){return document.compareDocumentPosition?f.compareDocumentPosition(c)&16:f!==c&&f.contains(c)},hasScroll:function(f,c){if(a(f).css("overflow")==="hidden")return false;var b=c&&c==="left"?"scrollLeft":"scrollTop",d=false;if(f[b]>0)return true;f[b]=1;d=f[b]>0;f[b]=0;return d},isOverAxis:function(f,c,b){return f>c&&f<c+b},isOver:function(f,c,b,d,e,i){return a.ui.isOverAxis(f,b,e)&&a.ui.isOverAxis(c,d,i)}})}})(jQuery);
(function(a,j){if(a.cleanData){var k=a.cleanData;a.cleanData=function(c){for(var b=0,d;(d=c[b])!=null;b++)a(d).triggerHandler("remove");k(c)}}else{var f=a.fn.remove;a.fn.remove=function(c,b){return this.each(function(){if(!b)if(!c||a.filter(c,[this]).length)a("*",this).add([this]).each(function(){a(this).triggerHandler("remove")});return f.call(a(this),c,b)})}}a.widget=function(c,b,d){var e=c.split(".")[0],i;c=c.split(".")[1];i=e+"-"+c;if(!d){d=b;b=a.Widget}a.expr[":"][i]=function(g){return!!a.data(g,
c)};a[e]=a[e]||{};a[e][c]=function(g,h){arguments.length&&this._createWidget(g,h)};b=new b;b.options=a.extend(true,{},b.options);a[e][c].prototype=a.extend(true,b,{namespace:e,widgetName:c,widgetEventPrefix:a[e][c].prototype.widgetEventPrefix||c,widgetBaseClass:i},d);a.widget.bridge(c,a[e][c])};a.widget.bridge=function(c,b){a.fn[c]=function(d){var e=typeof d==="string",i=Array.prototype.slice.call(arguments,1),g=this;d=!e&&i.length?a.extend.apply(null,[true,d].concat(i)):d;if(e&&d.charAt(0)==="_")return g;
e?this.each(function(){var h=a.data(this,c),n=h&&a.isFunction(h[d])?h[d].apply(h,i):h;if(n!==h&&n!==j){g=n;return false}}):this.each(function(){var h=a.data(this,c);h?h.option(d||{})._init():a.data(this,c,new b(d,this))});return g}};a.Widget=function(c,b){arguments.length&&this._createWidget(c,b)};a.Widget.prototype={widgetName:"widget",widgetEventPrefix:"",options:{disabled:false},_createWidget:function(c,b){a.data(b,this.widgetName,this);this.element=a(b);this.options=a.extend(true,{},this.options,
this._getCreateOptions(),c);var d=this;this.element.bind("remove."+this.widgetName,function(){d.destroy()});this._create();this._trigger("create");this._init()},_getCreateOptions:function(){return a.metadata&&a.metadata.get(this.element[0])[this.widgetName]},_create:function(){},_init:function(){},destroy:function(){this.element.unbind("."+this.widgetName).removeData(this.widgetName);this.widget().unbind("."+this.widgetName).removeAttr("aria-disabled").removeClass(this.widgetBaseClass+"-disabled ui-state-disabled")},
widget:function(){return this.element},option:function(c,b){var d=c;if(arguments.length===0)return a.extend({},this.options);if(typeof c==="string"){if(b===j)return this.options[c];d={};d[c]=b}this._setOptions(d);return this},_setOptions:function(c){var b=this;a.each(c,function(d,e){b._setOption(d,e)});return this},_setOption:function(c,b){this.options[c]=b;if(c==="disabled")this.widget()[b?"addClass":"removeClass"](this.widgetBaseClass+"-disabled ui-state-disabled").attr("aria-disabled",b);return this},
enable:function(){return this._setOption("disabled",false)},disable:function(){return this._setOption("disabled",true)},_trigger:function(c,b,d){var e=this.options[c];b=a.Event(b);b.type=(c===this.widgetEventPrefix?c:this.widgetEventPrefix+c).toLowerCase();d=d||{};if(b.originalEvent){c=a.event.props.length;for(var i;c;){i=a.event.props[--c];b[i]=b.originalEvent[i]}}this.element.trigger(b,d);return!(a.isFunction(e)&&e.call(this.element[0],b,d)===false||b.isDefaultPrevented())}}})(jQuery);
(function(a){a.widget("ui.mouse",{options:{cancel:":input,option",distance:1,delay:0},_mouseInit:function(){var j=this;this.element.bind("mousedown."+this.widgetName,function(k){return j._mouseDown(k)}).bind("click."+this.widgetName,function(k){if(true===a.data(k.target,j.widgetName+".preventClickEvent")){a.removeData(k.target,j.widgetName+".preventClickEvent");k.stopImmediatePropagation();return false}});this.started=false},_mouseDestroy:function(){this.element.unbind("."+this.widgetName)},_mouseDown:function(j){j.originalEvent=
j.originalEvent||{};if(!j.originalEvent.mouseHandled){this._mouseStarted&&this._mouseUp(j);this._mouseDownEvent=j;var k=this,f=j.which==1,c=typeof this.options.cancel=="string"?a(j.target).parents().add(j.target).filter(this.options.cancel).length:false;if(!f||c||!this._mouseCapture(j))return true;this.mouseDelayMet=!this.options.delay;if(!this.mouseDelayMet)this._mouseDelayTimer=setTimeout(function(){k.mouseDelayMet=true},this.options.delay);if(this._mouseDistanceMet(j)&&this._mouseDelayMet(j)){this._mouseStarted=
this._mouseStart(j)!==false;if(!this._mouseStarted){j.preventDefault();return true}}this._mouseMoveDelegate=function(b){return k._mouseMove(b)};this._mouseUpDelegate=function(b){return k._mouseUp(b)};a(document).bind("mousemove."+this.widgetName,this._mouseMoveDelegate).bind("mouseup."+this.widgetName,this._mouseUpDelegate);j.preventDefault();return j.originalEvent.mouseHandled=true}},_mouseMove:function(j){if(a.browser.msie&&!(document.documentMode>=9)&&!j.button)return this._mouseUp(j);if(this._mouseStarted){this._mouseDrag(j);
return j.preventDefault()}if(this._mouseDistanceMet(j)&&this._mouseDelayMet(j))(this._mouseStarted=this._mouseStart(this._mouseDownEvent,j)!==false)?this._mouseDrag(j):this._mouseUp(j);return!this._mouseStarted},_mouseUp:function(j){a(document).unbind("mousemove."+this.widgetName,this._mouseMoveDelegate).unbind("mouseup."+this.widgetName,this._mouseUpDelegate);if(this._mouseStarted){this._mouseStarted=false;j.target==this._mouseDownEvent.target&&a.data(j.target,this.widgetName+".preventClickEvent",
true);this._mouseStop(j)}return false},_mouseDistanceMet:function(j){return Math.max(Math.abs(this._mouseDownEvent.pageX-j.pageX),Math.abs(this._mouseDownEvent.pageY-j.pageY))>=this.options.distance},_mouseDelayMet:function(){return this.mouseDelayMet},_mouseStart:function(){},_mouseDrag:function(){},_mouseStop:function(){},_mouseCapture:function(){return true}})})(jQuery);
(function(a){a.ui=a.ui||{};var j=/left|center|right/,k=/top|center|bottom/,f=a.fn.position,c=a.fn.offset;a.fn.position=function(b){if(!b||!b.of)return f.apply(this,arguments);b=a.extend({},b);var d=a(b.of),e=d[0],i=(b.collision||"flip").split(" "),g=b.offset?b.offset.split(" "):[0,0],h,n,m;if(e.nodeType===9){h=d.width();n=d.height();m={top:0,left:0}}else if(e.setTimeout){h=d.width();n=d.height();m={top:d.scrollTop(),left:d.scrollLeft()}}else if(e.preventDefault){b.at="left top";h=n=0;m={top:b.of.pageY,
left:b.of.pageX}}else{h=d.outerWidth();n=d.outerHeight();m=d.offset()}a.each(["my","at"],function(){var l=(b[this]||"").split(" ");if(l.length===1)l=j.test(l[0])?l.concat(["center"]):k.test(l[0])?["center"].concat(l):["center","center"];l[0]=j.test(l[0])?l[0]:"center";l[1]=k.test(l[1])?l[1]:"center";b[this]=l});if(i.length===1)i[1]=i[0];g[0]=parseInt(g[0],10)||0;if(g.length===1)g[1]=g[0];g[1]=parseInt(g[1],10)||0;if(b.at[0]==="right")m.left+=h;else if(b.at[0]==="center")m.left+=h/2;if(b.at[1]==="bottom")m.top+=
n;else if(b.at[1]==="center")m.top+=n/2;m.left+=g[0];m.top+=g[1];return this.each(function(){var l=a(this),o=l.outerWidth(),q=l.outerHeight(),r=parseInt(a.curCSS(this,"marginLeft",true))||0,s=parseInt(a.curCSS(this,"marginTop",true))||0,v=o+r+(parseInt(a.curCSS(this,"marginRight",true))||0),w=q+s+(parseInt(a.curCSS(this,"marginBottom",true))||0),p=a.extend({},m),t;if(b.my[0]==="right")p.left-=o;else if(b.my[0]==="center")p.left-=o/2;if(b.my[1]==="bottom")p.top-=q;else if(b.my[1]==="center")p.top-=
q/2;p.left=Math.round(p.left);p.top=Math.round(p.top);t={left:p.left-r,top:p.top-s};a.each(["left","top"],function(u,x){a.ui.position[i[u]]&&a.ui.position[i[u]][x](p,{targetWidth:h,targetHeight:n,elemWidth:o,elemHeight:q,collisionPosition:t,collisionWidth:v,collisionHeight:w,offset:g,my:b.my,at:b.at})});a.fn.bgiframe&&l.bgiframe();l.offset(a.extend(p,{using:b.using}))})};a.ui.position={fit:{left:function(b,d){var e=a(window);e=d.collisionPosition.left+d.collisionWidth-e.width()-e.scrollLeft();b.left=
e>0?b.left-e:Math.max(b.left-d.collisionPosition.left,b.left)},top:function(b,d){var e=a(window);e=d.collisionPosition.top+d.collisionHeight-e.height()-e.scrollTop();b.top=e>0?b.top-e:Math.max(b.top-d.collisionPosition.top,b.top)}},flip:{left:function(b,d){if(d.at[0]!=="center"){var e=a(window);e=d.collisionPosition.left+d.collisionWidth-e.width()-e.scrollLeft();var i=d.my[0]==="left"?-d.elemWidth:d.my[0]==="right"?d.elemWidth:0,g=d.at[0]==="left"?d.targetWidth:-d.targetWidth,h=-2*d.offset[0];b.left+=
d.collisionPosition.left<0?i+g+h:e>0?i+g+h:0}},top:function(b,d){if(d.at[1]!=="center"){var e=a(window);e=d.collisionPosition.top+d.collisionHeight-e.height()-e.scrollTop();var i=d.my[1]==="top"?-d.elemHeight:d.my[1]==="bottom"?d.elemHeight:0,g=d.at[1]==="top"?d.targetHeight:-d.targetHeight,h=-2*d.offset[1];b.top+=d.collisionPosition.top<0?i+g+h:e>0?i+g+h:0}}}};if(!a.offset.setOffset){a.offset.setOffset=function(b,d){if(/static/.test(a.curCSS(b,"position")))b.style.position="relative";var e=a(b),
i=e.offset(),g=parseInt(a.curCSS(b,"top",true),10)||0,h=parseInt(a.curCSS(b,"left",true),10)||0;i={top:d.top-i.top+g,left:d.left-i.left+h};"using"in d?d.using.call(b,i):e.css(i)};a.fn.offset=function(b){var d=this[0];if(!d||!d.ownerDocument)return null;if(b)return this.each(function(){a.offset.setOffset(this,b)});return c.call(this)}}})(jQuery);
(function(a,j){var k={buttons:true,height:true,maxHeight:true,maxWidth:true,minHeight:true,minWidth:true,width:true},f={maxHeight:true,maxWidth:true,minHeight:true,minWidth:true};a.widget("ui.dialog",{options:{autoOpen:true,buttons:{},closeOnEscape:true,closeText:"close",dialogClass:"",draggable:true,hide:null,height:"auto",maxHeight:false,maxWidth:false,minHeight:150,minWidth:150,modal:false,position:{my:"center",at:"center",collision:"fit",using:function(c){var b=a(this).css(c).offset().top;b<0&&
a(this).css("top",c.top-b)}},resizable:true,show:null,stack:true,title:"",width:300,zIndex:1E3},_create:function(){this.originalTitle=this.element.attr("title");if(typeof this.originalTitle!=="string")this.originalTitle="";this.options.title=this.options.title||this.originalTitle;var c=this,b=c.options,d=b.title||"&#160;",e=a.ui.dialog.getTitleId(c.element),i=(c.uiDialog=a("<div></div>")).appendTo(document.body).hide().addClass("ui-dialog ui-widget ui-widget-content ui-corner-all "+b.dialogClass).css({zIndex:b.zIndex}).attr("tabIndex",
-1).css("outline",0).keydown(function(n){if(b.closeOnEscape&&n.keyCode&&n.keyCode===a.ui.keyCode.ESCAPE){c.close(n);n.preventDefault()}}).attr({role:"dialog","aria-labelledby":e}).mousedown(function(n){c.moveToTop(false,n)});c.element.show().removeAttr("title").addClass("ui-dialog-content ui-widget-content").appendTo(i);var g=(c.uiDialogTitlebar=a("<div></div>")).addClass("ui-dialog-titlebar ui-widget-header ui-corner-all ui-helper-clearfix").prependTo(i),h=a('<a href="#"></a>').addClass("ui-dialog-titlebar-close ui-corner-all").attr("role",
"button").hover(function(){h.addClass("ui-state-hover")},function(){h.removeClass("ui-state-hover")}).focus(function(){h.addClass("ui-state-focus")}).blur(function(){h.removeClass("ui-state-focus")}).click(function(n){c.close(n);return false}).appendTo(g);(c.uiDialogTitlebarCloseText=a("<span></span>")).addClass("ui-icon ui-icon-closethick").text(b.closeText).appendTo(h);a("<span></span>").addClass("ui-dialog-title").attr("id",e).html(d).prependTo(g);if(a.isFunction(b.beforeclose)&&!a.isFunction(b.beforeClose))b.beforeClose=
b.beforeclose;g.find("*").add(g).disableSelection();b.draggable&&a.fn.draggable&&c._makeDraggable();b.resizable&&a.fn.resizable&&c._makeResizable();c._createButtons(b.buttons);c._isOpen=false;a.fn.bgiframe&&i.bgiframe()},_init:function(){this.options.autoOpen&&this.open()},destroy:function(){this.overlay&&this.overlay.destroy();this.uiDialog.hide();this.element.unbind(".dialog").removeData("dialog").removeClass("ui-dialog-content ui-widget-content").hide().appendTo("body");this.uiDialog.remove();
this.originalTitle&&this.element.attr("title",this.originalTitle);return this},widget:function(){return this.uiDialog},close:function(c){var b=this,d,e;if(false!==b._trigger("beforeClose",c)){b.overlay&&b.overlay.destroy();b.uiDialog.unbind("keypress.ui-dialog");b._isOpen=false;if(b.options.hide)b.uiDialog.hide(b.options.hide,function(){b._trigger("close",c)});else{b.uiDialog.hide();b._trigger("close",c)}a.ui.dialog.overlay.resize();if(b.options.modal){d=0;a(".ui-dialog").each(function(){if(this!==
b.uiDialog[0]){e=a(this).css("z-index");isNaN(e)||(d=Math.max(d,e))}});a.ui.dialog.maxZ=d}return b}},isOpen:function(){return this._isOpen},moveToTop:function(c,b){var d=this.options;if(d.modal&&!c||!d.stack&&!d.modal)return this._trigger("focus",b);if(d.zIndex>a.ui.dialog.maxZ)a.ui.dialog.maxZ=d.zIndex;if(this.overlay){a.ui.dialog.maxZ+=1;this.overlay.$el.css("z-index",a.ui.dialog.overlay.maxZ=a.ui.dialog.maxZ)}d={scrollTop:this.element.attr("scrollTop"),scrollLeft:this.element.attr("scrollLeft")};
a.ui.dialog.maxZ+=1;this.uiDialog.css("z-index",a.ui.dialog.maxZ);this.element.attr(d);this._trigger("focus",b);return this},open:function(){if(!this._isOpen){var c=this.options,b=this.uiDialog;this.overlay=c.modal?new a.ui.dialog.overlay(this):null;this._size();this._position(c.position);b.show(c.show);this.moveToTop(true);c.modal&&b.bind("keypress.ui-dialog",function(d){if(d.keyCode===a.ui.keyCode.TAB){var e=a(":tabbable",this),i=e.filter(":first");e=e.filter(":last");if(d.target===e[0]&&!d.shiftKey){i.focus(1);
return false}else if(d.target===i[0]&&d.shiftKey){e.focus(1);return false}}});a(this.element.find(":tabbable").get().concat(b.find(".ui-dialog-buttonpane :tabbable").get().concat(b.get()))).eq(0).focus();this._isOpen=true;this._trigger("open");return this}},_createButtons:function(c){var b=this,d=false,e=a("<div></div>").addClass("ui-dialog-buttonpane ui-widget-content ui-helper-clearfix"),i=a("<div></div>").addClass("ui-dialog-buttonset").appendTo(e);b.uiDialog.find(".ui-dialog-buttonpane").remove();
typeof c==="object"&&c!==null&&a.each(c,function(){return!(d=true)});if(d){a.each(c,function(g,h){h=a.isFunction(h)?{click:h,text:g}:h;var n=a('<button type="button"></button>').attr(h,true).unbind("click").click(function(){h.click.apply(b.element[0],arguments)}).appendTo(i);a.fn.button&&n.button()});e.appendTo(b.uiDialog)}},_makeDraggable:function(){function c(g){return{position:g.position,offset:g.offset}}var b=this,d=b.options,e=a(document),i;b.uiDialog.draggable({cancel:".ui-dialog-content, .ui-dialog-titlebar-close",
handle:".ui-dialog-titlebar",containment:"document",start:function(g,h){i=d.height==="auto"?"auto":a(this).height();a(this).height(a(this).height()).addClass("ui-dialog-dragging");b._trigger("dragStart",g,c(h))},drag:function(g,h){b._trigger("drag",g,c(h))},stop:function(g,h){d.position=[h.position.left-e.scrollLeft(),h.position.top-e.scrollTop()];a(this).removeClass("ui-dialog-dragging").height(i);b._trigger("dragStop",g,c(h));a.ui.dialog.overlay.resize()}})},_makeResizable:function(c){function b(g){return{originalPosition:g.originalPosition,
originalSize:g.originalSize,position:g.position,size:g.size}}c=c===j?this.options.resizable:c;var d=this,e=d.options,i=d.uiDialog.css("position");d.uiDialog.resizable({cancel:".ui-dialog-content",containment:"document",alsoResize:d.element,maxWidth:e.maxWidth,maxHeight:e.maxHeight,minWidth:e.minWidth,minHeight:d._minHeight(),handles:typeof c==="string"?c:"n,e,s,w,se,sw,ne,nw",start:function(g,h){a(this).addClass("ui-dialog-resizing");d._trigger("resizeStart",g,b(h))},resize:function(g,h){d._trigger("resize",
g,b(h))},stop:function(g,h){a(this).removeClass("ui-dialog-resizing");e.height=a(this).height();e.width=a(this).width();d._trigger("resizeStop",g,b(h));a.ui.dialog.overlay.resize()}}).css("position",i).find(".ui-resizable-se").addClass("ui-icon ui-icon-grip-diagonal-se")},_minHeight:function(){var c=this.options;return c.height==="auto"?c.minHeight:Math.min(c.minHeight,c.height)},_position:function(c){var b=[],d=[0,0],e;if(c){if(typeof c==="string"||typeof c==="object"&&"0"in c){b=c.split?c.split(" "):
[c[0],c[1]];if(b.length===1)b[1]=b[0];a.each(["left","top"],function(i,g){if(+b[i]===b[i]){d[i]=b[i];b[i]=g}});c={my:b.join(" "),at:b.join(" "),offset:d.join(" ")}}c=a.extend({},a.ui.dialog.prototype.options.position,c)}else c=a.ui.dialog.prototype.options.position;(e=this.uiDialog.is(":visible"))||this.uiDialog.show();this.uiDialog.css({top:0,left:0}).position(a.extend({of:window},c));e||this.uiDialog.hide()},_setOptions:function(c){var b=this,d={},e=false;a.each(c,function(i,g){b._setOption(i,g);
if(i in k)e=true;if(i in f)d[i]=g});e&&this._size();this.uiDialog.is(":data(resizable)")&&this.uiDialog.resizable("option",d)},_setOption:function(c,b){var d=this.uiDialog;switch(c){case "beforeclose":c="beforeClose";break;case "buttons":this._createButtons(b);break;case "closeText":this.uiDialogTitlebarCloseText.text(""+b);break;case "dialogClass":d.removeClass(this.options.dialogClass).addClass("ui-dialog ui-widget ui-widget-content ui-corner-all "+b);break;case "disabled":b?d.addClass("ui-dialog-disabled"):
d.removeClass("ui-dialog-disabled");break;case "draggable":var e=d.is(":data(draggable)");e&&!b&&d.draggable("destroy");!e&&b&&this._makeDraggable();break;case "position":this._position(b);break;case "resizable":(e=d.is(":data(resizable)"))&&!b&&d.resizable("destroy");e&&typeof b==="string"&&d.resizable("option","handles",b);!e&&b!==false&&this._makeResizable(b);break;case "title":a(".ui-dialog-title",this.uiDialogTitlebar).html(""+(b||"&#160;"));break}a.Widget.prototype._setOption.apply(this,arguments)},
_size:function(){var c=this.options,b,d,e=this.uiDialog.is(":visible");this.element.show().css({width:"auto",minHeight:0,height:0});if(c.minWidth>c.width)c.width=c.minWidth;b=this.uiDialog.css({height:"auto",width:c.width}).height();d=Math.max(0,c.minHeight-b);if(c.height==="auto")if(a.support.minHeight)this.element.css({minHeight:d,height:"auto"});else{this.uiDialog.show();c=this.element.css("height","auto").height();e||this.uiDialog.hide();this.element.height(Math.max(c,d))}else this.element.height(Math.max(c.height-
b,0));this.uiDialog.is(":data(resizable)")&&this.uiDialog.resizable("option","minHeight",this._minHeight())}});a.extend(a.ui.dialog,{version:"1.8.10",uuid:0,maxZ:0,getTitleId:function(c){c=c.attr("id");if(!c){this.uuid+=1;c=this.uuid}return"ui-dialog-title-"+c},overlay:function(c){this.$el=a.ui.dialog.overlay.create(c)}});a.extend(a.ui.dialog.overlay,{instances:[],oldInstances:[],maxZ:0,events:a.map("focus,mousedown,mouseup,keydown,keypress,click".split(","),function(c){return c+".dialog-overlay"}).join(" "),
create:function(c){if(this.instances.length===0){setTimeout(function(){a.ui.dialog.overlay.instances.length&&a(document).bind(a.ui.dialog.overlay.events,function(d){if(a(d.target).zIndex()<a.ui.dialog.overlay.maxZ)return false})},1);a(document).bind("keydown.dialog-overlay",function(d){if(c.options.closeOnEscape&&d.keyCode&&d.keyCode===a.ui.keyCode.ESCAPE){c.close(d);d.preventDefault()}});a(window).bind("resize.dialog-overlay",a.ui.dialog.overlay.resize)}var b=(this.oldInstances.pop()||a("<div></div>").addClass("ui-widget-overlay")).appendTo(document.body).css({width:this.width(),
height:this.height()});a.fn.bgiframe&&b.bgiframe();this.instances.push(b);return b},destroy:function(c){var b=a.inArray(c,this.instances);b!=-1&&this.oldInstances.push(this.instances.splice(b,1)[0]);this.instances.length===0&&a([document,window]).unbind(".dialog-overlay");c.remove();var d=0;a.each(this.instances,function(){d=Math.max(d,this.css("z-index"))});this.maxZ=d},height:function(){var c,b;if(a.browser.msie&&a.browser.version<7){c=Math.max(document.documentElement.scrollHeight,document.body.scrollHeight);
b=Math.max(document.documentElement.offsetHeight,document.body.offsetHeight);return c<b?a(window).height()+"px":c+"px"}else return a(document).height()+"px"},width:function(){var c,b;if(a.browser.msie&&a.browser.version<7){c=Math.max(document.documentElement.scrollWidth,document.body.scrollWidth);b=Math.max(document.documentElement.offsetWidth,document.body.offsetWidth);return c<b?a(window).width()+"px":c+"px"}else return a(document).width()+"px"},resize:function(){var c=a([]);a.each(a.ui.dialog.overlay.instances,
function(){c=c.add(this)});c.css({width:0,height:0}).css({width:a.ui.dialog.overlay.width(),height:a.ui.dialog.overlay.height()})}});a.extend(a.ui.dialog.overlay.prototype,{destroy:function(){a.ui.dialog.overlay.destroy(this.$el)}})})(jQuery);
(function(a,j){var k=j.queryeditor={init:function(){CueCard.helper=j.h.ajax_url("lib/cuecard/");CueCard.freebaseServiceUrl=j.acre.freebase.service_url+"/";CueCard.urlPrefix=CueCard.apiProxy.base=j.h.ajax_url("lib/cuecard/");var f={initial_tab:"json"},c={focusOnReady:true,codeMirror:{parserfile:[a("#codemirror-js").attr("href")],stylesheet:[a("#codemirror-css").attr("href")]}};if(!j.permission.has_permission){c.readOnly=true;c.hideControls=true}if(j.c&&j.c.query){c.content=JSON.stringify(j.c.query);
autorun=c.cleanUp=true;f.queryLoaded=true}c.onChange=function(){k.is_dirty=true;a("#save-query").addClass("disabled")};c.onRun=function(b){b.code==="/api/status/ok"&&k.is_dirty&&a("#save-query").removeClass("disabled")};c.onReady=function(){k.resize();a(window).resize(k.resize);k.is_dirty=false;autorun&&k.cuecard.queryEditor.run(false);setTimeout(function(){a("#qe-module, #the-output-pane").css("visibility","visible")},1)};k.cuecard=CueCard.createComposition({queryEditorElement:a("#the-query-editor")[0],
queryEditorOptions:c,outputPaneElement:a("#the-output-pane")[0],outputPaneOptions:f});k.page_chrome_height=a("#header").outerHeight()+a("#page-header").outerHeight()+a("#footer").outerHeight()+(a("#page-content").outerHeight(true)-a("#page-content").height())+a("#page-title").outerHeight(true);a(window).bind("beforeunload",function(){})},resize:function(){var f=a("body").outerHeight()-k.page_chrome_height;if(f){a("#qe-module").height(f);k.cuecard.outputPane&&k.cuecard.outputPane.layout(f);k.cuecard.queryEditor&&
k.cuecard.queryEditor.layout(f)}},save:function(){var f=a(this);if(f.is(".editing"))return false;f.addClass("editing");j.get_script(j.h.static_url("query-edit.mf.js"),function(){k.edit.save_submit(this)});return false},clone:function(){window.location=j.h.fb_url("/query",{q:j.queryeditor.cuecard.queryEditor._editor.getCode(),autorun:1})}};a(k.init())})(jQuery,window.freebase);
