
/*
 * Copyright 2012, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Additional Licenses for Third Party components can be found here:
 * http://wiki.freebase.com/wiki/Freebase_Site_License
 *
 */
(function(a,g){if(!("console"in window)){var d=window.console={};d.log=d.warn=d.error=d.debug=function(){}}a(function(){var b=a("<div>");a(document.body).append(b);var c=setTimeout(function(){if(a.cleanData){var f=a.cleanData;a.cleanData=function(h){for(var i=0,l;(l=h[i])!=null;i++)a(l).triggerHandler("remove");f(h)}}else{var k=a.fn.remove;a.fn.remove=function(h,i){return this.each(function(){if(!i)if(!h||a.filter(h,[this]).length)a("*",this).add([this]).each(function(){a(this).triggerHandler("remove")});
return k.call(a(this),h,i)})}}},1);b.bind("remove",function(){clearTimeout(c)});b.remove()});var e={key:1,filter:1,spell:1,exact:1,lang:1,scoring:1,prefixed:1,stemmed:1,format:1,mql_output:1};a.suggest=function(b,c){a.fn[b]=function(f){this.length||console.warn("Suggest: invoked on empty element set");return this.each(function(){if(this.nodeName)if(this.nodeName.toUpperCase()==="INPUT")this.type&&this.type.toUpperCase()!=="TEXT"&&console.warn("Suggest: unsupported INPUT type: "+this.type);else console.warn("Suggest: unsupported DOM element: "+
this.nodeName);var k=a.data(this,b);k&&k._destroy();a.data(this,b,new a.suggest[b](this,f))._init()})};a.suggest[b]=function(f,k){var h=this,i=this.options=a.extend(true,{},a.suggest.defaults,a.suggest[b].defaults,k),l=i.css_prefix=i.css_prefix||"",m=i.css;this.name=b;a.each(m,function(n){m[n]=l+m[n]});i.ac_param={};a.each(e,function(n){var q=i[n];q===null||q===""||(i.ac_param[n]=q)});i.flyout_lang=null;if(i.ac_param.lang){var o=i.ac_param.lang;if(a.type(o)==="string")o=o.split(",");if(a.isArray(o)&&
o.length)if(o=a.trim(o[0]))i.flyout_lang=o}this._status={START:"",LOADING:"",SELECT:"",ERROR:""};if(i.status&&i.status instanceof Array&&i.status.length>=3){this._status.START=i.status[0]||"";this._status.LOADING=i.status[1]||"";this._status.SELECT=i.status[2]||"";if(i.status.length===4)this._status.ERROR=i.status[3]||""}o=this.status=a('<div style="display:none;">').addClass(m.status);var r=this.list=a("<ul>").addClass(m.list),p=this.pane=a('<div style="display:none;" class="fbs-reset">').addClass(m.pane);
p.append(o).append(r);if(i.parent)a(i.parent).append(p);else{p.css("position","absolute");i.zIndex&&p.css("z-index",i.zIndex);a(document.body).append(p)}p.bind("mousedown",function(n){h.input.data("dont_hide",true);n.stopPropagation()}).bind("mouseup",function(n){h.input.data("dont_hide")&&h.input.focus();h.input.removeData("dont_hide");n.stopPropagation()}).bind("click",function(n){n.stopPropagation();if(n=h.get_selected()){h.onselect(n,true);h.hide_all()}});r.hover(function(n){h.hoverover_list(n)},
function(n){h.hoverout_list(n)});this.input=a(f).attr("autocomplete","off").unbind(".suggest").bind("remove.suggest",function(){h._destroy()}).bind("keydown.suggest",function(n){h.keydown(n)}).bind("keypress.suggest",function(n){h.keypress(n)}).bind("keyup.suggest",function(n){h.keyup(n)}).bind("blur.suggest",function(n){h.blur(n)}).bind("textchange.suggest",function(){h.textchange()}).bind("focus.suggest",function(n){h.focus(n)}).bind(a.browser.msie?"paste.suggest":"input.suggest",function(){clearTimeout(h.paste_timeout);
h.paste_timeout=setTimeout(function(){h.textchange()},0)});this.onresize=function(){h.invalidate_position();if(p.is(":visible")){h.position();if(i.flyout&&h.flyoutpane&&h.flyoutpane.is(":visible")){var n=h.get_selected();n&&h.flyout_position(n)}}};a(window).bind("resize.suggest",this.onresize).bind("scroll.suggest",this.onresize)};a.suggest[b].prototype=a.extend({},a.suggest.prototype,c)};a.suggest.prototype={_init:function(){},_destroy:function(){this.pane.remove();this.list.remove();this.input.unbind(".suggest");
a(window).unbind("resize.suggest",this.onresize).unbind("scroll.suggest",this.onresize);this.input.removeData("data.suggest")},invalidate_position:function(){self._position=null},status_start:function(){this.hide_all();this.status.siblings().hide();if(this._status.START){this.status.text(this._status.START).show();if(!this.pane.is(":visible")){this.position();this.pane_show()}}this._status.LOADING&&this.status.removeClass("loading")},status_loading:function(){this.status.siblings().show();if(this._status.LOADING){this.status.addClass("loading").text(this._status.LOADING).show();
if(!this.pane.is(":visible")){this.position();this.pane_show()}}else this.status.hide()},status_select:function(){this.status.siblings().show();this._status.SELECT?this.status.text(this._status.SELECT).show():this.status.hide();this._status.LOADING&&this.status.removeClass("loading")},status_error:function(){this.status.siblings().show();this._status.ERROR?this.status.text(this._status.ERROR).show():this.status.hide();this._status.LOADING&&this.status.removeClass("loading")},focus:function(b){this.input.val()===
""?this.status_start():this.focus_hook(b)},focus_hook:function(){if(!this.input.data("data.suggest")&&!this.pane.is(":visible")&&a("."+this.options.css.item,this.list).length){this.position();this.pane_show()}},keydown:function(b){var c=b.keyCode;if(c===9)this.tab(b);else if(c===38||c===40)b.shiftKey||b.preventDefault()},keypress:function(b){var c=b.keyCode;if(c===38||c===40)b.shiftKey||b.preventDefault();else c===13&&this.enter(b)},keyup:function(b){var c=b.keyCode;if(c===38){b.preventDefault();
this.up(b)}else if(c===40){b.preventDefault();this.down(b)}else if(b.ctrlKey&&c===77)a(".fbs-more-link",this.pane).click();else if(a.suggest.is_char(b)){clearTimeout(this.keypress.timeout);var f=this;this.keypress.timeout=setTimeout(function(){f.textchange()},0)}else c===27&&this.escape(b);return true},blur:function(){if(!this.input.data("dont_hide")){this.input.data("data.suggest");this.hide_all()}},tab:function(b){if(!(b.shiftKey||b.metaKey||b.ctrlKey)){b=this.options;b=this.pane.is(":visible")&&
a("."+b.css.item,this.list).length;var c=this.get_selected();if(b&&c){this.onselect(c);this.hide_all()}}},enter:function(b){var c=this.options;if(this.pane.is(":visible"))if(b.shiftKey){this.shift_enter(b);b.preventDefault()}else if(a("."+c.css.item,this.list).length)if(c=this.get_selected()){this.onselect(c);this.hide_all();b.preventDefault()}else{this.input.data("data.suggest");if(a("."+this.options.css.item+":visible",this.list).length){this.updown(false);b.preventDefault()}}},shift_enter:function(){},
escape:function(){this.hide_all()},up:function(b){this.updown(true,b.ctrlKey||b.shiftKey)},down:function(b){this.updown(false,null,b.ctrlKey||b.shiftKey)},updown:function(b,c,f){var k=this.options.css,h=this.list;if(this.pane.is(":visible")){var i=a("."+k.item+":visible",h);if(i.length){h=a(i[0]);i=a(i[i.length-1]);var l=this.get_selected()||[];clearTimeout(this.ignore_mouseover.timeout);this._ignore_mouseover=false;if(b)if(c)this._goto(h);else if(l.length)if(l[0]==h[0]){h.removeClass(k.selected);
this.input.val(this.input.data("original.suggest"));this.hoverout_list()}else this._goto(l.prevAll("."+k.item+":visible:first"));else this._goto(i);else if(f)this._goto(i);else if(l.length)if(l[0]==i[0]){i.removeClass(k.selected);this.input.val(this.input.data("original.suggest"));this.hoverout_list()}else this._goto(l.nextAll("."+k.item+":visible:first"));else this._goto(h)}}else b||this.textchange()},_goto:function(b){b.trigger("mouseover.suggest");var c=b.data("data.suggest");this.input.val(c?
c.name:this.input.data("original.suggest"));this.scroll_to(b)},scroll_to:function(b){var c=this.list,f=c.scrollTop(),k=f+c.innerHeight(),h=b.outerHeight();b=b.prevAll().length*h;h=b+h;if(b<f){this.ignore_mouseover();c.scrollTop(b)}else if(h>k){this.ignore_mouseover();c.scrollTop(f+h-k)}},textchange:function(){this.input.removeData("data.suggest");this.input.trigger("fb-textchange",this);var b=this.input.val();if(b==="")this.status_start();else{this.status_loading();this.request(b)}},request:function(){},
response:function(b){if(b){"cost"in b&&this.trackEvent(this.name,"response","cost",b.cost);if(this.check_response(b)){var c=[];if(a.isArray(b))c=b;else if("result"in b)c=b.result;var f=a.map(arguments,function(m){return m});this.response_hook.apply(this,f);var k=null,h=this,i=this.options;a.each(c,function(m,o){if(!o.id&&o.mid)o.id=o.mid;var r=h.create_item(o,b).bind("mouseover.suggest",function(p){h.mouseover_item(p)});r.data("data.suggest",o);h.list.append(r);if(m===0)k=r});this.input.data("original.suggest",
this.input.val());if(a("."+i.css.item,this.list).length===0&&i.nomatch){c=a('<li class="fbs-nomatch">');if(typeof i.nomatch==="string")c.text(i.nomatch);else{i.nomatch.title&&c.append(a('<em class="fbs-nomatch-text">').text(i.nomatch.title));i.nomatch.heading&&c.append(a("<h3>").text(i.nomatch.heading));if((i=i.nomatch.tips)&&i.length){var l=a('<ul class="fbs-search-tips">');a.each(i,function(m,o){l.append(a("<li>").text(o))});c.append(l)}}c.bind("click.suggest",function(m){m.stopPropagation()});
this.list.append(c)}f.push(k);this.show_hook.apply(this,f);this.position();this.pane_show()}}},pane_show:function(){var b=false;if(a("> li",this.list).length)b=true;b||this.pane.children(":not(."+this.options.css.list+")").each(function(){if(a(this).css("display")!="none"){b=true;return false}});if(b)if(this.options.animate){var c=this;this.pane.slideDown("fast",function(){c.input.trigger("fb-pane-show",c)})}else{this.pane.show();this.input.trigger("fb-pane-show",this)}else{this.pane.hide();this.input.trigger("fb-pane-hide",
this)}},create_item:function(b){var c=this.options.css,f=a("<li>").addClass(c.item);b=a("<label>").text(b.name);f.append(a("<div>").addClass(c.item_name).append(b));return f},mouseover_item:function(b){if(!this._ignore_mouseover){b=b.target;if(b.nodeName.toLowerCase()!=="li")b=a(b).parents("li:first");var c=a(b),f=this.options.css;a("."+f.item,this.list).each(function(){this!==c[0]&&a(this).removeClass(f.selected)});if(!c.hasClass(f.selected)){c.addClass(f.selected);this.mouseover_item_hook(c)}}},
mouseover_item_hook:function(){},hoverover_list:function(){},hoverout_list:function(){},check_response:function(){return true},response_hook:function(){this.list.empty()},show_hook:function(){this.status_select()},position:function(){var b=this.pane,c=this.options;if(!c.parent){if(!self._position){var f=this.input,k=f.offset(),h=f.outerWidth(true),i=f.outerHeight(true);k.top+=i;var l=b.outerWidth(),m=b.outerHeight(),o=k.top+m/2,r=a(window).scrollLeft();f=a(window).scrollTop();var p=a(window).width(),
n=a(window).height()+f,q=true;if("left"==c.align)q=true;else if("right"==c.align)q=false;else if(k.left>r+p/2)q=false;if(!q){q=k.left-(l-h);if(q>r)k.left=q}if(o>n){c=k.top-i-m;if(c>f)k.top=c}this._position=k}b.css({top:this._position.top,left:this._position.left})}},ignore_mouseover:function(){this._ignore_mouseover=true;var b=this;this.ignore_mouseover.timeout=setTimeout(function(){b.ignore_mouseover_reset()},1E3)},ignore_mouseover_reset:function(){this._ignore_mouseover=false},get_selected:function(){var b=
null,c=this.options.css.selected;a("li",this.list).each(function(){var f=a(this);if(f.hasClass(c)&&f.is(":visible")){b=f;return false}});return b},onselect:function(b){var c=b.data("data.suggest");if(c){this.input.val(c.name).data("data.suggest",c).trigger("fb-select",c);this.trackEvent(this.name,"fb-select","index",b.prevAll().length)}},trackEvent:function(b,c,f,k){this.input.trigger("fb-track-event",{category:b,action:c,label:f,value:k})},hide_all:function(){this.pane.hide();this.input.trigger("fb-pane-hide",
this)}};a.extend(a.suggest,{defaults:{status:["Start typing to get suggestions...","Searching...","Select an item from the list:","Sorry, something went wrong. Please try again later"],soft:false,nomatch:"no matches",css:{pane:"fbs-pane",list:"fbs-list",item:"fbs-item",item_name:"fbs-item-name",selected:"fbs-selected",status:"fbs-status"},css_prefix:null,parent:null,animate:false,zIndex:null},strongify:function(b,c){var f,k=b.toLowerCase().indexOf(c.toLowerCase());if(k>=0){var h=c.length;f=document.createTextNode(b.substring(0,
k));var i=a("<strong>").text(b.substring(k,k+h));k=document.createTextNode(b.substring(k+h));f=a("<div>").append(f).append(i).append(k)}else f=a("<div>").text(b);return f},keyCode:{CAPS_LOCK:20,CONTROL:17,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,INSERT:45,LEFT:37,NUMPAD_ENTER:108,PAGE_DOWN:34,PAGE_UP:33,RIGHT:39,SHIFT:16,SPACE:32,TAB:9,UP:38,OPTION:18,APPLE:224},is_char:function(b){if(b.type==="keypress")if((b.metaKey||b.ctrlKey)&&b.charCode===118)return true;else{if("isChar"in b)return b.isChar}else{var c=
a.suggest.keyCode.not_char;if(!c){c={};a.each(a.suggest.keyCode,function(f,k){c[""+k]=1});a.suggest.keyCode.not_char=c}return!(""+b.keyCode in c)}},parse_input:function(b){for(var c=/(\S+)\:(?:\"([^\"]+)\"|(\S+))/g,f=b,k=[],h={},i=c.exec(b);i;){if(i[1]in e)h[i[1]]=a.isEmptyObject(i[2])?i[3]:i[2];else k.push(i[0]);f=f.replace(i[0],"");i=c.exec(b)}f=a.trim(f.replace(/\s+/g," "));return[f,k,h]},mqlkey_fast:/^[_A-Za-z0-9][A-Za-z0-9_-]*$/,mqlkey_slow:/^(?:[A-Za-z0-9]|\$[A-F0-9]{4})(?:[A-Za-z0-9_-]|\$[A-F0-9]{4})*$/,
check_mql_key:function(b){if(a.suggest.mqlkey_fast.test(b))return true;else if(a.suggest.mqlkey_slow.test(b))return true;return false},check_mql_id:function(b){if(b.indexOf("/")===0){b=b.split("/");b.shift();if(!(b.length==1&&b[0]===""))for(var c=0,f=b.length;c<f;c++)if(!a.suggest.check_mql_key(b[c]))return false;return true}else return false}});var j={_destroy:a.suggest.prototype._destroy,show_hook:a.suggest.prototype.show_hook};a.suggest("suggest",{_init:function(){var b=this,c=this.options;if(c.flyout_service_url==
null)c.flyout_service_url=c.service_url;this.flyout_url=c.flyout_service_url;if(c.flyout_service_path)this.flyout_url+=c.flyout_service_path;this.flyout_url=this.flyout_url.replace(/\$\{key\}/g,c.key);if(c.flyout_image_service_url==null)c.flyout_image_service_url=c.service_url;this.flyout_image_url=c.flyout_image_service_url;if(c.flyout_image_service_path)this.flyout_image_url+=c.flyout_image_service_path;this.flyout_image_url=this.flyout_image_url.replace(/\$\{key\}/g,c.key);if(!a.suggest.cache)a.suggest.cache=
{};if(c.flyout){this.flyoutpane=a('<div style="display:none;" class="fbs-reset">').addClass(c.css.flyoutpane);if(c.flyout_parent)a(c.flyout_parent).append(this.flyoutpane);else{this.flyoutpane.css("position","absolute");c.zIndex&&this.flyoutpane.css("z-index",c.zIndex);a(document.body).append(this.flyoutpane)}this.flyoutpane.hover(function(f){b.hoverover_list(f)},function(f){b.hoverout_list(f)}).bind("mousedown.suggest",function(f){f.stopPropagation();b.pane.click()});if(!a.suggest.flyout)a.suggest.flyout=
{};if(!a.suggest.flyout.cache)a.suggest.flyout.cache={}}},_destroy:function(){j._destroy.call(this);this.flyoutpane&&this.flyoutpane.remove();this.input.removeData("request.count.suggest");this.input.removeData("flyout.request.count.suggest")},shift_enter:function(){if(this.options.suggest_new){this.suggest_new();this.hide_all()}},hide_all:function(){this.pane.hide();this.flyoutpane&&this.flyoutpane.hide();this.input.trigger("fb-pane-hide",this);this.input.trigger("fb-flyoutpane-hide",this)},request:function(b,
c){var f=this,k=this.options,h=b,i=k.ac_param.filter||[],l=null;if(a.type(i)==="string")i=[i];i=i.slice();if(k.advanced){var m=a.suggest.parse_input(h);h=m[0];m[1].length&&i.push("(all "+m[1].join(" ")+")");l=m[2];if(a.suggest.check_mql_id(h)){i.push('(all mid:"'+h+'")');h=""}}m={};m[k.query_param_name]=h;if(c)m.cursor=c;a.extend(m,k.ac_param,l);if(i.length)m.filter=i;var o=k.service_url+k.service_path+"?"+a.param(m,true);if(h=a.suggest.cache[o])this.response(h,c?c:-1,true);else{clearTimeout(this.request.timeout);
var r={url:k.service_url+k.service_path,data:m,traditional:true,beforeSend:function(){var p=f.input.data("request.count.suggest")||0;p||f.trackEvent(f.name,"start_session");p+=1;f.trackEvent(f.name,"request","count",p);f.input.data("request.count.suggest",p)},success:function(p){a.suggest.cache[o]=p;p.prefix=b;f.response(p,c?c:-1)},error:function(p){f.status_error();f.trackEvent(f.name,"request","error",{url:this.url,response:p?p.responseText:""});f.input.trigger("fb-error",Array.prototype.slice.call(arguments))},
complete:function(p){p&&f.trackEvent(f.name,"request","tid",p.getResponseHeader("X-Metaweb-TID"))},dataType:"jsonp",cache:true};this.request.timeout=setTimeout(function(){a.ajax(r)},k.xhr_delay)}},create_item:function(b,c){var f=this.options.css,k=a("<li>").addClass(f.item),h=a("<label>").append(a.suggest.strongify(b.name||b.id,c.prefix)),i=a("<div>").addClass(f.item_name).append(h);b.under&&a(":first",h).append(a("<small>").text(" ("+b.under+")"));k.append(i);h=b.notable;f=a("<div>").addClass(f.item_type);
if(h&&h.name)f.text(h.name);else this.options.show_id&&b.id&&f.text(b.id);i.prepend(f);return k},mouseover_item_hook:function(b){b=b.data("data.suggest");this.options.flyout&&b&&this.flyout_request(b)},check_response:function(b){return b.prefix===this.input.val()},response_hook:function(b,c){this.flyoutpane&&this.flyoutpane.hide();c>0?a(".fbs-more",this.pane).remove():this.list.empty()},show_hook:function(b,c,f){j.show_hook.apply(this,[b]);var k=this.options,h=this,i=this.pane,l=this.list,m=b.result,
o=a(".fbs-more",i),r=a(".fbs-suggestnew",i);a(".fbs-status",i);var p=b.correction;if(p&&p.length){var n=a('<a class="fbs-spell-link" href="#">').append(p[0]).bind("click.suggest",function(q){q.preventDefault();q.stopPropagation();h.input.val(p[0]).trigger("textchange")});h.status.empty().append("Search instead for ").append(n).show()}if(m&&m.length&&"cursor"in b){if(!o.length){m=a('<a class="fbs-more-link" href="#" title="(Ctrl+m)">view more</a>');o=a('<div class="fbs-more">').append(m);m.bind("click.suggest",
function(q){q.preventDefault();q.stopPropagation();q=a(this).parent(".fbs-more");h.more(q.data("cursor.suggest"))});l.after(o)}o.data("cursor.suggest",b.cursor);o.show()}else o.remove();if(k.suggest_new){if(!r.length){b=a('<button class="fbs-suggestnew-button">');b.text(k.suggest_new);r=a('<div class="fbs-suggestnew">').append('<div class="fbs-suggestnew-description">Your item not in the list?</div>').append(b).append('<span class="fbs-suggestnew-shortcut">(Shift+Enter)</span>').bind("click.suggest",
function(q){q.stopPropagation();h.suggest_new(q)});i.append(r)}r.show()}else r.remove();if(f&&f.length&&c>0){c=f.prevAll().length*f.outerHeight();l.scrollTop();l.animate({scrollTop:c},"slow",function(){f.trigger("mouseover.suggest")})}},suggest_new:function(){var b=this.input.val();if(b!==""){this.input.data("data.suggest",b).trigger("fb-select-new",b);this.trackEvent(this.name,"fb-select-new","index","new");this.hide_all()}},more:function(b){if(b){var c=this.input.data("original.suggest");c!==null&&
this.input.val(c);this.request(this.input.val(),b);this.trackEvent(this.name,"more","cursor",b)}return false},flyout_request:function(b){var c=this,f=this.options,k=this.flyoutpane.data("data.suggest");if(k&&b.id===k.id){if(!this.flyoutpane.is(":visible")){this.flyout_position(this.get_selected());this.flyoutpane.show();this.input.trigger("fb-flyoutpane-show",this)}}else if((k=a.suggest.flyout.cache[b.id])&&k.id&&k.html)this.flyout_response(k);else{var h=b.id,i={url:this.flyout_url.replace(/\$\{id\}/g,
b.id),traditional:true,beforeSend:function(){var l=c.input.data("flyout.request.count.suggest")||0;l+=1;c.trackEvent(c.name,"flyout.request","count",l);c.input.data("flyout.request.count.suggest",l)},success:function(l){l["req:id"]=h;l.html=a.suggest.suggest.create_flyout(l,c.flyout_image_url);a.suggest.flyout.cache[h]=l;c.flyout_response(l)},error:function(l){c.trackEvent(c.name,"flyout","error",{url:this.url,response:l?l.responseText:""})},complete:function(l){l&&c.trackEvent(c.name,"flyout","tid",
l.getResponseHeader("X-Metaweb-TID"))},dataType:"jsonp",cache:true};if(f.flyout_lang)i.data={lang:f.flyout_lang};clearTimeout(this.flyout_request.timeout);this.flyout_request.timeout=setTimeout(function(){a.ajax(i)},f.xhr_delay);this.input.trigger("fb-request-flyout",i)}},flyout_response:function(b){var c=this.pane,f=this.get_selected()||[];if(c.is(":visible")&&f.length)if((c=f.data("data.suggest"))&&b["req:id"]===c.id&&b.html){this.flyoutpane.html(b.html);this.flyout_position(f);this.flyoutpane.show().data("data.suggest",
c);this.input.trigger("fb-flyoutpane-show",this)}},flyout_position:function(b){if(!this.options.flyout_parent){var c=this.pane,f=this.flyoutpane,k=this.options.css,h=g,i={top:parseInt(f.css("top"),10),left:parseInt(f.css("left"),10)},l=c.offset(),m=c.outerWidth(),o=f.outerHeight(),r=f.outerWidth();if(this.options.flyout==="bottom"){h=l;m=this.input.offset();if(l.top<m.top)h.top-=o;else h.top+=c.outerHeight();f.addClass(k.flyoutpane+"-bottom")}else{h=b.offset();b=b.outerHeight();h.left+=m;var p=h.left+
r;c=a(document.body).scrollLeft();var n=a(window).width()+c;h.top=h.top+b-o;if(h.top<l.top)h.top=l.top;if(p>n){l=h.left-(m+r);if(l>c)h.left=l}f.removeClass(k.flyoutpane+"-bottom")}h.top===i.top&&h.left===i.left||f.css({top:h.top,left:h.left})}},hoverout_list:function(){this.flyoutpane&&!this.get_selected()&&this.flyoutpane.hide()}});a.extend(a.suggest.suggest,{defaults:{filter:null,spell:"always",exact:false,scoring:null,lang:null,key:null,prefixed:true,stemmed:null,format:null,advanced:true,show_id:true,
query_param_name:"query",service_url:"https://www.googleapis.com/freebase/v1",service_path:"/search",align:null,flyout:true,flyout_service_url:null,flyout_service_path:"/topic${id}?filter=suggest&limit=3&key=${key}",flyout_image_service_url:null,flyout_image_service_path:"/image${id}?maxwidth=75&key=${key}",flyout_parent:null,suggest_new:null,nomatch:{title:"No suggested matches",heading:"Tips on getting better suggestions:",tips:["Enter more or fewer characters","Add words related to your original search",
"Try alternate spellings","Check your spelling"]},css:{item_type:"fbs-item-type",flyoutpane:"fbs-flyout-pane"},xhr_delay:200},get_values:function(b,c){var f=b.property;return f&&f[c]&&f[c].values?f[c].values:null},get_first_value:function(b,c){var f=a.suggest.suggest.get_values(b,c);if(f&&f.length>0)return f[0];return null},create_flyout:function(b,c){var f=a.suggest.suggest.get_values,k=a.suggest.suggest.get_first_value,h=k(b,"/type/object/name");h=h?h.text:b.id;var i=k(b,"/common/topic/description")||
k(b,"/common/topic/article")||false;if(i)i=i.text;if(k=k(b,"/common/topic/image")||false)k=c.replace(/\$\{id\}/g,b.id);var l=[],m=[b.id],o=f(b,"/common/topic/notable_properties");o&&a.each(o,function(q,t){var s=f(b,t.id);if(s&&s.length){s=a.map(s,function(u){return u.text}).join(", ");l.push([t.text||t.id,s])}});o=f(b,"/common/topic/notable_for");var r=f(b,"/common/topic/notable_types");if(o||r){var p={};m=[];a.each([o,r],function(q,t){t&&t.forEach(function(s){if(s.id&&!p[s.id]){m.push(s.text);p[s.id]=
true}})})}m=m.join(", ");var n=a('<div class="fbs-flyout-content">');n.append(a('<h1 id="fbs-flyout-title">').text(h));a.each(l,function(q,t){n.append(a('<h3 class="fbs-topic-properties">').append(a("<strong>").text(t[0]+": ")).append(document.createTextNode(t[1])))});i&&n.append(a('<p class="fbs-topic-article">').text(i));if(k){n.children().addClass("fbs-flyout-image-true");n.prepend(a('<img id="fbs-topic-image" class="fbs-flyout-image-true" src="'+k+'">'))}h=a('<span class="fbs-flyout-types">').append(m);
h=a('<div class="fbs-attribution">').append(h);return a("<div>").append(n).append(h).html()}});document.createElement("input")})(jQuery);
(function(a){a.fn.extend({simulate:function(g,d){return this.each(function(){var e=a.extend({},a.simulate.defaults,d||{});new a.simulate(this,g,e)})}});a.simulate=function(g,d,e){this.target=g;this.options=e;/^drag$/.test(d)?this[d].apply(this,[this.target,e]):this.simulateEvent(g,d,e)};a.extend(a.simulate.prototype,{simulateEvent:function(g,d,e){var j=this.createEvent(d,e);this.dispatchEvent(g,d,j,e);return j},createEvent:function(g,d){if(/^mouse(over|out|down|up|move)|(dbl)?click$/.test(g))return this.mouseEvent(g,
d);else if(/^key(up|down|press)$/.test(g))return this.keyboardEvent(g,d)},mouseEvent:function(g,d){var e,j=a.extend({bubbles:true,cancelable:g!="mousemove",view:window,detail:0,screenX:0,screenY:0,clientX:0,clientY:0,ctrlKey:false,altKey:false,shiftKey:false,metaKey:false,button:0,relatedTarget:undefined},d);a(j.relatedTarget);if(a.isFunction(document.createEvent)){e=document.createEvent("MouseEvents");e.initMouseEvent(g,j.bubbles,j.cancelable,j.view,j.detail,j.screenX,j.screenY,j.clientX,j.clientY,
j.ctrlKey,j.altKey,j.shiftKey,j.metaKey,j.button,j.relatedTarget||document.body.parentNode)}else if(document.createEventObject){e=document.createEventObject();a.extend(e,j);e.button={0:1,1:4,2:2}[e.button]||e.button}return e},keyboardEvent:function(g,d){var e,j=a.extend({bubbles:true,cancelable:true,view:window,ctrlKey:false,altKey:false,shiftKey:false,metaKey:false,keyCode:0,charCode:0},d);if(a.isFunction(document.createEvent))try{e=document.createEvent("KeyEvents");e.initKeyEvent(g,j.bubbles,j.cancelable,
j.view,j.ctrlKey,j.altKey,j.shiftKey,j.metaKey,j.keyCode,j.charCode)}catch(b){e=document.createEvent("Events");e.initEvent(g,j.bubbles,j.cancelable);a.extend(e,{view:j.view,ctrlKey:j.ctrlKey,altKey:j.altKey,shiftKey:j.shiftKey,metaKey:j.metaKey,keyCode:j.keyCode,charCode:j.charCode})}else if(document.createEventObject){e=document.createEventObject();a.extend(e,j)}if(a.browser.msie||a.browser.opera){e.keyCode=j.charCode>0?j.charCode:j.keyCode;e.charCode=undefined}return e},dispatchEvent:function(g,
d,e){if(g.dispatchEvent)g.dispatchEvent(e);else g.fireEvent&&g.fireEvent("on"+d,e);return e},drag:function(){var g=this.findCenter(this.target),d=this.options,e=Math.floor(g.x);g=Math.floor(g.y);var j=d.dx||0;d=d.dy||0;var b=this.target,c={clientX:e,clientY:g};this.simulateEvent(b,"mousedown",c);c={clientX:e+1,clientY:g+1};this.simulateEvent(document,"mousemove",c);c={clientX:e+j,clientY:g+d};this.simulateEvent(document,"mousemove",c);this.simulateEvent(document,"mousemove",c);this.simulateEvent(b,
"mouseup",c)},findCenter:function(g){g=a(this.target);var d=g.offset();return{x:d.left+g.outerWidth()/2,y:d.top+g.outerHeight()/2}}});a.extend(a.simulate,{defaults:{speed:"sync"},VK_TAB:9,VK_ENTER:13,VK_ESC:27,VK_PGUP:33,VK_PGDN:34,VK_END:35,VK_HOME:36,VK_LEFT:37,VK_UP:38,VK_RIGHT:39,VK_DOWN:40})})(jQuery);var test_input1,test_input2,test_input3,test_input4,TIMEOUT_DELAY=5E3;$(function(){test_input1=$("#test1");test_input2=$("#test2");test_input3=$("#test3");test_input4=$("#test4")});
var module_options={setup:function(){},teardown:function(){$.suggest.cache={};if($.suggest.flyout)$.suggest.flyout.cache={};$.each([test_input1,test_input2,test_input3,test_input4],function(a,g){g.unbind();var d=get_instance(g);d&&d._destroy();g.val("")})}},default_options={key:"AIzaSyBij3tRJN2VdWiLQN48-BmPFjNWpHe7MQE",advanced:true},test_value="bob dyla",bob_dylan_mid="/m/01vrncs",position_threshold=10;function get_instance(a){a=a||test_input1;return a.data("suggest")}
function simulate_keypress(a,g){var d=g;if(typeof d!=="object")d={keyCode:d};a.simulate("keydown",d);a.simulate("keyup",d);a.simulate("keypress",d)}function simulate_mouseclick(a){a.simulate("mousedown").simulate("mouseup").simulate("mouseclick").click()}
$(function(){function a(d){var e=get_instance();ok(e.pane.hasClass(d.pane),"css.pane");ok(e.status.hasClass(d.status),"css.status");ok(e.list.hasClass(d.list),"css.list");ok(e.flyoutpane.hasClass(d.flyoutpane),"css.flyoutpane");stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",function(){if($(">li",e.list).length){$(">li",e.list).each(function(){$(this).hasClass(d.item);var j=$("."+d.item_name,this);equals(j.length,1);j=$("."+d.item_type,j);equals(j.length,1)});start()}}).val("css").trigger("textchange")}
function g(d,e,j,b){d=$.extend({},default_options,d);test_input1.suggest(d);var c=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",function(){var f=false,k;k=typeof j==="function"?function(i){return j(i)}:function(i){return i.mid===j};var h=$(">li",c.list);if(h.length){h.each(function(){var i=$(this).data("data.suggest");if(f=k(i))return false});ok(f);start()}else if(b){ok(b());start()}}).val(e).trigger("textchange")}module("options",module_options);test("css_prefix",function(){var d=
$.extend({},default_options,{css_prefix:"test-"});test_input1.suggest(d);var e={};d=$.extend(true,{},$.suggest.defaults.css,$.suggest.suggest.defaults.css);$.each(d,function(j,b){e[j]="test-"+b});a(e)});test("css",function(){var d={pane:"my-pane",list:"my-list",item:"my-item",item_name:"my-item-name",selected:"my-selected",status:"my-status",item_type:"my-item-type",flyoutpane:"my-flyout-pane"},e=$.extend({},default_options,{css:d});test_input1.suggest(e);a(d)});test("parent",1,function(){var d=$('<div id="parent">');
$(document.body).append(d);var e=$.extend({},default_options,{parent:"#parent"});test_input1.suggest(e);var j=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",function(){if($(">li",j.list).length){equals(j.pane.parent()[0],d[0]);start()}}).val("bob dyl").trigger("textchange")});test("flyout_parent",1,function(){var d=$('<div id="flyout_parent">');$(document.body).append(d);var e=$.extend({},default_options,{flyout_parent:"#flyout_parent"});test_input1.suggest(e);var j=get_instance();
stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",function(){$("li:first",j.list).trigger("mouseover")}).bind("fb-flyoutpane-show",function(){equals(j.flyoutpane.parent()[0],d[0]);start()}).val("stephen colb").trigger("textchange")});test("status[0]",1,function(){var d=$.extend({},default_options,{status:["0","1","2","3"]});test_input1.suggest(d);d=get_instance();test_input1.val("").trigger("textchange");equals(d.status.text(),"0")});test("status[1]",1,function(){var d=$.extend({},default_options,
{status:["0","1","2","3"]});test_input1.suggest(d);d=get_instance();test_input1.val("obama").trigger("textchange");equals(d.status.text(),"1")});test("status[2]",1,function(){var d=$.extend({},default_options,{status:["0","1","2","3"]});test_input1.suggest(d);var e=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",function(){if($(">li",e.list).length){equals(e.status.text(),"2");start()}}).val("hillary cli").trigger("textchange")});test("status[3]",1,function(){var d=$.extend({},
default_options,{status:["0","1","2","3"]});test_input1.suggest(d);d=get_instance();d.status_error();equals(d.status.text(),"3")});test("zIndex",1,function(){var d=$.extend({},default_options,{zIndex:1E3});test_input1.suggest(d);var e=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",function(){equals(e.pane.css("z-index"),1E3);start()}).val("shohoku").trigger("textchange")});test("flyout=false",1,function(){var d=$.extend({},default_options,{flyout:false});test_input1.suggest(d);
var e=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",function(){if($(">li",e.list).length){$("li:first",e.list).trigger("mouseover");if(!e.flyoutpane){ok("flyout not shown");start()}}}).bind("fb-flyoutpane-show",function(){fail("flyout shown when flyout=false");start()}).val("avatar").trigger("textchange")});test("flyout=bottom",1,function(){var d=$.extend({},default_options,{flyout:"bottom"});test_input1.suggest(d);var e=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",
function(){$("li:first",e.list).trigger("mouseover")}).bind("fb-flyoutpane-show",function(){var j=e.pane.offset(),b=e.flyoutpane.offset();ok(Math.abs(b.top-(j.top+e.pane.height()))<position_threshold);start()}).val("avatar").trigger("textchange")});test("align=left",1,function(){var d=$.extend({},default_options,{align:"left"});test_input1.suggest(d);var e=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",function(){if($(">li",e.list).length){ok(Math.abs(e.pane.offset().left-test_input1.offset().left)<
position_threshold);start()}}).val("lady ga").trigger("textchange")});test("align=right",1,function(){var d=$.extend({},default_options,{align:"right"});test_input3.suggest(d);var e=get_instance(test_input3);stop(TIMEOUT_DELAY);test_input3.bind("fb-pane-show",function(){if($(">li",e.list).length){var j=e.pane.offset().left+e.pane.width(),b=test_input3.offset().left+test_input3.width();ok(Math.abs(j-b)<position_threshold);start()}}).val("jessica alb").trigger("textchange")});test("suggest_new",1,function(){var d=
$.extend({},default_options,{suggest_new:"suggest_new"});test_input1.suggest(d);var e=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",function(){if($(">li",e.list).length){equals($("button:first",e.pane).text(),"suggest_new");start()}}).val("aplusk").trigger("textchange")});$.each(["(any type:/music/artist)","(any type:/people/person type:/music/artist)","(all type:/music/artist)","(all type:/people/person type:/music/artist)","(should type:/music/artist)","(should type:/people/person)"],
function(d,e){test("filter="+e,1,function(){g({filter:e},bob_dylan_mid,bob_dylan_mid)})});test("lang [default]",function(){g(null,"/en/seoul",function(d){return d.name==="Seoul"})});test("lang=en",function(){g({lang:"en"},"/en/seoul",function(d){return d.name==="Seoul"})});test("lang=ko",function(){g({lang:"ko"},"/en/seoul",function(d){return d.name.indexOf("\uc11c\uc6b8")!==-1})});test("lang=es,ko",function(){g({lang:"es,ko"},"/en/cheong_wa_dae",function(d){return d.name==="\uccad\uc640\ub300"})});
test("spell=always",function(){var d=$.extend({},default_options,{spell:"always"});test_input1.suggest(d);var e=get_instance(),j=false;stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",function(){var b=$(">li",e.list);if(j&&b.length){ok(true,"Got spell correction results");start()}else if($(".fbs-spell-link",e.pane).length){ok(true,"Found spell/correction");$(".fbs-spell-link",e.pane).click();j=true}}).val("Bob Dylon").trigger("textchange")});test("exact [default]",function(){g(null,"Bob Dylon",
bob_dylan_mid)});test("exact=false",function(){g(null,"Bob Dylon",bob_dylan_mid)});test("exact=true",function(){g(null,"Bob Dylon",function(){return false},function(){return true})})});
$(function(){module("events",module_options);test("fb-pane-show",1,function(){test_input1.suggest(default_options);var a=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",function(){if($(">li",a.list).length){ok(true,"got fb-pane-show");start()}}).focus().val("bob dylan").trigger("textchange")});test("fb-flyoutpane-show",1,function(){test_input1.suggest(default_options);var a=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-flyoutpane-show",function(){ok(true,"got fb-flyoutpane-show");
start()}).bind("fb-pane-show",function(){$(">li",a.list).length&&$("li:first",a.list).simulate("mouseover")}).focus().val("bob dylan").trigger("textchange")});test("fb-select",2,function(){var a=$.extend({},default_options,{filter:"(any type:/music/artist)"});test_input1.suggest(a);var g=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-select",function(d,e){ok(e);equals(e.mid,bob_dylan_mid);start()}).bind("fb-pane-show",function(){if($(">li",g.list).length){$("li:first",g.list).simulate("mouseover");
simulate_keypress(test_input1,$.simulate.VK_ENTER)}}).focus().val(bob_dylan_mid).trigger("textchange")});test("fb-select-new",1,function(){var a=$.extend({},default_options,{suggest_new:"new"});test_input1.suggest(a);var g=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-select-new",function(d,e){equals(e,"bob dylan");start()}).bind("fb-pane-show",function(){$(">li",g.list).length&&$(".fbs-suggestnew",g.pane).click()}).focus().val("bob dylan").trigger("textchange")});test("fb-textchange",1,
function(){test_input1.suggest(default_options);stop(TIMEOUT_DELAY);test_input1.bind("fb-textchange",function(){ok(true,"got fb-textchange");start()}).focus();simulate_keypress(test_input1,68)})});
$(function(){function a(g,d){test("select: "+g,2,function(){var e=$.extend({},default_options,{filter:"(any type:/music/artist)"});test_input1.suggest(e);var j=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-select",function(b,c){ok(c);equals(c.mid,bob_dylan_mid);start()}).bind("fb-pane-show",function(){$(">li",j.list).length&&d()}).focus().val(bob_dylan_mid).trigger("textchange")})}module("ux",module_options);a("MOUSEOVER MOUSECLICK",function(){var g=get_instance();g=$("li:first",g.list).simulate("mouseover");
simulate_mouseclick(g)});a("MOUSEOVER ENTER",function(){var g=get_instance();$("li:first",g.list).simulate("mouseover");simulate_keypress(test_input1,$.simulate.VK_ENTER)});a("ENTER ENTER",function(){simulate_keypress(test_input1,$.simulate.VK_ENTER);simulate_keypress(test_input1,$.simulate.VK_ENTER)});a("DOWN ENTER",function(){simulate_keypress(test_input1,$.simulate.VK_DOWN);simulate_keypress(test_input1,$.simulate.VK_ENTER)});a("UP DOWN DOWN ENTER",function(){simulate_keypress(test_input1,$.simulate.VK_UP);
simulate_keypress(test_input1,$.simulate.VK_DOWN);simulate_keypress(test_input1,$.simulate.VK_DOWN);simulate_keypress(test_input1,$.simulate.VK_ENTER)});a("CTRL+UP ENTER",function(){simulate_keypress(test_input1,{keyCode:$.simulate.VK_UP,ctrlKey:true});simulate_keypress(test_input1,$.simulate.VK_ENTER)});a("CTRL+DOWN DOWN DOWN ENTER",function(){simulate_keypress(test_input1,{keyCode:$.simulate.VK_DOWN,ctrlKey:true});simulate_keypress(test_input1,$.simulate.VK_DOWN);simulate_keypress(test_input1,$.simulate.VK_DOWN);
simulate_keypress(test_input1,$.simulate.VK_ENTER)});test("select: flyout",2,function(){var g=$.extend({},default_options,{filter:"(any type:/music/artist)"});test_input1.suggest(g);var d=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-select",function(e,j){ok(j);equals(j.mid,bob_dylan_mid);start()}).bind("fb-flyoutpane-show",function(){simulate_mouseclick(d.flyoutpane)}).bind("fb-pane-show",function(){$(">li",d.list).length&&simulate_keypress(test_input1,$.simulate.VK_DOWN)}).focus().val(bob_dylan_mid).trigger("textchange")});
test("suggest_new: SHIFT+ENTER",1,function(){var g=$.extend({},default_options,{suggest_new:"new"});test_input1.suggest(g);var d=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-select-new",function(e,j){equals(j,"bob dylan");start()}).bind("fb-pane-show",function(){$(">li",d.list).length&&simulate_keypress(test_input1,{keyCode:$.simulate.VK_ENTER,shiftKey:true})}).focus().val("bob dylan").trigger("textchange")});test("more: CLICK",1,function(){var g=$.extend({},default_options,{filter:"(any type:/music/artist)"});
test_input1.suggest(g);var d=get_instance(),e=false,j=0;stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",function(){if(e){ok($(">li",d.list).length>j,"got more");start()}else if(j=$(">li",d.list).length){$(".fbs-more-link",d.pane).click();e=true}}).focus().val("bob dylan").trigger("textchange")});test("more: CTRL+M",1,function(){var g=$.extend({},default_options,{filter:"(any type:/music/artist)"});test_input1.suggest(g);var d=get_instance(),e=false,j=0;stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",
function(){if(e){ok($(">li",d.list).length>j,"got more");start()}else if(j=$(">li",d.list).length){simulate_keypress(test_input1,{keyCode:77,ctrlKey:true});e=true}}).focus().val("bob dylan").trigger("textchange")});test("cancel: ESC",2,function(){var g=$.extend({},default_options,{filter:"(any type:/music/artist)"});test_input1.suggest(g);var d=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",function(){if($(">li",d.list).length){ok(d.pane.is(":visible"),"pane visible");simulate_keypress(test_input1,
$.simulate.VK_ESC);ok(!d.pane.is(":visible"),"pane NOT visible");start()}}).focus().val("bob dylan").trigger("textchange")})});
$(function(){module("functional",module_options);test("remove",function(){var a=$.extend({},default_options,{type:"/music/artist"});test_input4.suggest(a);a=get_instance(test_input4);var g=a.pane,d=a.flyoutpane;ok(a,"suggest initialized");test_input4.remove();ok(!g.parent().is("body"),"suggest pane not removed");ok(!d.parent().is("body"),"suggest flyoutpane not removed")});test("flyout abort (CLI-10009)",function(){test_input1.suggest(default_options);var a=get_instance();stop(TIMEOUT_DELAY);var g;
test_input1.bind("fb-flyoutpane-show",function(){ok(true,"got fb-flyoutpane-show");ok(a.flyoutpane.html(),"got non-empty flyout pane");start()}).bind("fb-request-flyout",function(){clearTimeout(a.flyout_request.timeout);var d=g.data("data.suggest").id;$.suggest.flyout.cache[d]={id:d};test_input1.unbind("fb-request-flyout").trigger("textchange")}).bind("fb-pane-show",function(){if($(">li",a.list).length){g=$("li:first",a.list);g.simulate("mouseover")}}).focus().val("bob dylan").trigger("textchange")})});
$(function(){var a={teardown:module_options.teardown,response:$.suggest.suggest.prototype.response};module("xss",$.extend({},module_options,{teardown:function(){a.teardown.apply();$.suggest.suggest.prototype.response=a.response}}));test("script_injection",function(){test_input1.suggest(default_options);var g=get_instance();$.suggest.suggest.prototype.response=function(d){var e=d.result;if(e&&e.length)e[0].name="<script>$(document.body).append('<div id=\"xss\">XSS</div>')<\/script>";return a.response.apply(this,
arguments)};stop(TIMEOUT_DELAY);test_input1.bind("fb-select",function(d,e){ok(e);equals(e.name,"<script>$(document.body).append('<div id=\"xss\">XSS</div>')<\/script>");var j=$("#xss");ok(!j.length,"script injection!");start()}).bind("fb-pane-show",function(){if($(">li",g.list).length){$("li:first",g.list).simulate("mouseover");simulate_keypress(test_input1,$.simulate.VK_ENTER)}}).focus().val("bob dylan").trigger("textchange")});test("script_injection strongified",function(){test_input1.suggest(default_options);
var g=get_instance();$.suggest.suggest.prototype.response=function(d){var e=d.result;if(e&&e.length)e[0].name="bob dylan<script>$(document.body).append('<div id=\"xss\">XSS</div>')<\/script>";return a.response.apply(this,arguments)};stop(TIMEOUT_DELAY);test_input1.bind("fb-select",function(d,e){ok(e);equals(e.name,"bob dylan<script>$(document.body).append('<div id=\"xss\">XSS</div>')<\/script>");var j=$("#xss");ok(!j.length,"script injection!");start()}).bind("fb-pane-show",function(){if($(">li",
g.list).length){$("li:first",g.list).simulate("mouseover");simulate_keypress(test_input1,$.simulate.VK_ENTER)}}).focus().val("bob dylan").trigger("textchange")});test("link_injection",function(){test_input1.suggest(default_options);var g=get_instance();$.suggest.suggest.prototype.response=function(d){var e=d.result;if(e&&e.length)e[0].name='<a href="javascript:alert("XSS");">click me</a>';return a.response.apply(this,arguments)};stop(TIMEOUT_DELAY);test_input1.bind("fb-select",function(d,e){ok(e);
equals(e.name,'<a href="javascript:alert("XSS");">click me</a>');var j=$("li:first",g.list);j=$("a",j);ok(!j.length,"link injection!");start()}).bind("fb-pane-show",function(){if($(">li",g.list).length){$("li:first",g.list).simulate("mouseover");simulate_keypress(test_input1,$.simulate.VK_ENTER)}}).focus().val("bob dylan").trigger("textchange")});test("link_injection strongified",function(){test_input1.suggest(default_options);var g=get_instance();$.suggest.suggest.prototype.response=function(d){var e=
d.result;if(e&&e.length)e[0].name='<a href="javascript:alert("XSS");">click me</a>bob dylan';return a.response.apply(this,arguments)};stop(TIMEOUT_DELAY);test_input1.bind("fb-select",function(d,e){ok(e);equals(e.name,'<a href="javascript:alert("XSS");">click me</a>bob dylan');var j=$("li:first",g.list);j=$("a",j);ok(!j.length,"link injection!");start()}).bind("fb-pane-show",function(){if($(">li",g.list).length){$("li:first",g.list).simulate("mouseover");simulate_keypress(test_input1,$.simulate.VK_ENTER)}}).focus().val("bob dylan").trigger("textchange")})});
$(function(){module("advanced",module_options);test("advanced parsing",function(){for(var a=["bob dylan",["bob dylan",[],{}],"bob dylan type",["bob dylan type",[],{}],"bob dylan type:",["bob dylan type:",[],{}],"type:",["type:",[],{}]," type:album",["",["type:album"],{}],'bob dylan type:"music artist"',["bob dylan",['type:"music artist"'],{}],"Dear... name{full}:Dear... type:/film/film",["Dear...",["name{full}:Dear...","type:/film/film"],{}],"Monty Python: Life of Brian",["Monty Python: Life of Brian",
[],{}],"bob dylan a: b  c: d e",["bob dylan a: b c: d e",[],{}],"bob a:b c   d e: f g h:",["bob c d e: f g h:",["a:b"],{}],'bob a:b c : d:e {foo}:"hello world" dylan',["bob c : dylan",["a:b","d:e",'{foo}:"hello world"'],{}]],g=0,d=a.length;g<d;g+=2){var e=a[g],j=a[g+1];same($.suggest.parse_input(e),j)}a=["bob dylan lang:de",["bob dylan",[],{lang:"de"}],'lang:ko dae han min guk format:"ENTITY"',["dae han min guk",[],{lang:"ko",format:"ENTITY"}],'lang:ru Some Russian Name type:"/film/film" Another Name',
["Some Russian Name Another Name",['type:"/film/film"'],{lang:"ru"}]];g=0;for(d=a.length;g<d;g+=2){e=a[g];j=a[g+1];same($.suggest.parse_input(e),j)}});test("check_mql_key",function(){$.each(["A","a","0","a-b","0-A-9_","0-","abc","1023","$30DE$30C4$30BF$30B1","$30DEa-z$30C4_$30BF4$30B1-"],function(a,g){ok($.suggest.check_mql_key(g),g)});$.each(["a$001","0.ca","$30DE$30C4$30BF$30B"],function(a,g){ok(!$.suggest.check_mql_key(g),g)})});test("check_mql_id",function(){$.each(["/","/freebase","/type/type",
"/film/film/property","/0/1/2","/A/b_-","/wikipedia/ja/$30DE$30C4$30BF$30B1","/_"],function(a,g){ok($.suggest.check_mql_id(g),g)});$.each(["/freebase/","#9202a8c04000641f80000000010c393g","#00000000000000000000000000000000","foobar","","!/freebase","/A/-"],function(a,g){ok(!$.suggest.check_mql_id(g),g)})})});
