
/*
 * Copyright 2012, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Additional Licenses for Third Party components can be found here:
 * http://wiki.freebase.com/wiki/Freebase_Site_License
 *
 */
/*
 
 jQuery Tools @VERSION Tooltip - UI essentials

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/tooltip/

 Since: November 2008
 Date: @DATE 
*/
(function(c){c.extend({tablesorter:new function(){function b(a,c){d(a+","+((new Date).getTime()-c.getTime())+"ms")}function d(a){"undefined"!=typeof console&&"undefined"!=typeof console.debug?console.log(a):alert(a)}function g(b,e){var g="";if(0!=b.tBodies.length){var f=b.tBodies[0].rows;if(f[0])for(var i=[],m=f[0].cells.length,t=0;t<m;t++){var r=!1;c.metadata&&c(e[t]).metadata()&&c(e[t]).metadata().sorter?r=a(c(e[t]).metadata().sorter):b.config.headers[t]&&b.config.headers[t].sorter&&(r=a(b.config.headers[t].sorter));
if(!r)a:{for(var r=b,l=f,k=-1,s=t,q=o.length,j=!1,p=!1,u=!0;""==p&&u;)k++,l[k]?(j=l[k].cells[s],p=c.trim(h(r.config,j)),r.config.debug&&d("Checking if value was empty on row:"+k)):u=!1;for(l=1;l<q;l++)if(o[l].is(p,r,j)){r=o[l];break a}r=o[0]}b.config.debug&&(g+="column:"+t+" parser:"+r.id+"\n");i.push(r)}b.config.debug&&d(g);return i}}function a(a){for(var c=o.length,b=0;b<c;b++)if(o[b].id.toLowerCase()==a.toLowerCase())return o[b];return!1}function e(a){var e;a.config.debug&&(e=new Date);for(var g=
a.tBodies[0]&&a.tBodies[0].rows.length||0,d=a.tBodies[0].rows[0]&&a.tBodies[0].rows[0].cells.length||0,i=a.config.parsers,m={row:[],normalized:[]},f=0;f<g;++f){var r=c(a.tBodies[0].rows[f]),l=[];if(r.hasClass(a.config.cssChildRow))m.row[m.row.length-1]=m.row[m.row.length-1].add(r);else{m.row.push(r);for(var k=0;k<d;++k)l.push(i[k].format(h(a.config,r[0].cells[k]),a,r[0].cells[k]));l.push(m.normalized.length);m.normalized.push(l)}}a.config.debug&&b("Building cache for "+g+" rows:",e);return m}function h(a,
b){var e="";if(!b)return"";a.supportsTextContent||(a.supportsTextContent=b.textContent||!1);return e="simple"==a.textExtraction?a.supportsTextContent?b.textContent:b.childNodes[0]&&b.childNodes[0].hasChildNodes()?b.childNodes[0].innerHTML:b.innerHTML:"function"==typeof a.textExtraction?a.textExtraction(b):c(b).text()}function f(a,e){var g;a.config.debug&&(g=new Date);for(var h=e.row,i=e.normalized,m=i.length,d=i[0].length-1,l=c(a.tBodies[0]),k=[],s=0;s<m;s++){var j=i[s][d];k.push(h[j]);if(!a.config.appender)for(var p=
h[j].length,o=0;o<p;o++)l[0].appendChild(h[j][o])}a.config.appender&&a.config.appender(a,k);k=null;a.config.debug&&b("Rebuilt table:",g);q(a);setTimeout(function(){c(a).trigger("sortEnd")},0)}function k(a,b){return a.config.headers[b]&&a.config.headers[b].lockedOrder?a.config.headers[b].lockedOrder:!1}function q(a){for(var b=a.config.widgets,c=b.length,e=0;e<c;e++)p(b[e]).format(a)}function p(a){for(var b=u.length,c=0;c<b;c++)if(u[c].id.toLowerCase()==a.toLowerCase())return u[c]}function x(a,b,e,
g){b.removeClass(g[0]).removeClass(g[1]);var i=[];b.each(function(){this.sortDisabled||(i[this.column]=c(this))});a=e.length;for(b=0;b<a;b++)i[e[b][0]].addClass(g[e[b][1]])}function s(a,c,e){var g,i;a.config.debug&&(g=new Date);var m="var sortWrapper = function(a,b) {",h=c.length;for(i=0;i<h;i++)var d=c[i][0],f=c[i][1],d="text"==a.config.parsers[d].type?0==f?j("text","asc",d):j("text","desc",d):0==f?j("numeric","asc",d):j("numeric","desc",d),l="e"+i,m=m+("var "+l+" = "+d),m=m+("if("+l+") { return "+
l+"; } "),m=m+"else { ";i=e.normalized[0].length-1;m+="return a["+i+"]-b["+i+"];";for(i=0;i<h;i++)m+="}; ";m+="return 0; }; ";a.config.debug&&b("Evaling expression:"+m,new Date);eval(m);e.normalized.sort(sortWrapper);a.config.debug&&b("Sorting on "+c.toString()+" and dir "+f+" time:",g);return e}function j(a,b,c){var e="a["+c+"]",c="b["+c+"]";if("text"==a&&"asc"==b)return"("+e+" == "+c+" ? 0 : ("+e+" === null ? Number.POSITIVE_INFINITY : ("+c+" === null ? Number.NEGATIVE_INFINITY : ("+e+" < "+c+") ? -1 : 1 )));";
if("text"==a&&"desc"==b)return"("+e+" == "+c+" ? 0 : ("+e+" === null ? Number.POSITIVE_INFINITY : ("+c+" === null ? Number.NEGATIVE_INFINITY : ("+c+" < "+e+") ? -1 : 1 )));";if("numeric"==a&&"asc"==b)return"("+e+" === null && "+c+" === null) ? 0 :("+e+" === null ? Number.POSITIVE_INFINITY : ("+c+" === null ? Number.NEGATIVE_INFINITY : "+e+" - "+c+"));";if("numeric"==a&&"desc"==b)return"("+e+" === null && "+c+" === null) ? 0 :("+e+" === null ? Number.POSITIVE_INFINITY : ("+c+" === null ? Number.NEGATIVE_INFINITY : "+
c+" - "+e+"));"}var o=[],u=[];this.defaults={cssHeader:"header",cssAsc:"headerSortUp",cssDesc:"headerSortDown",cssChildRow:"expand-child",sortInitialOrder:"asc",sortMultiSortKey:"shiftKey",sortForce:null,sortAppend:null,sortLocaleCompare:!0,textExtraction:"simple",parsers:{},widgets:[],widgetZebra:{css:["even","odd"]},headers:{},widthFixed:!1,cancelSelection:!0,sortList:[],headerList:[],dateFormat:"us",decimal:"/.|,/g",onRenderHeader:null,selectorHeaders:"thead th",debug:!1};this.benchmark=b;this.construct=
function(a){return this.each(function(){if(this.tHead&&this.tBodies){var v,j,n;this.config={};n=c.extend(this.config,c.tablesorter.defaults,a);v=c(this);c.data(this,"tablesorter",n);var i=this,m;i.config.debug&&(m=new Date);for(var t=[],r={},o=i.getElementsByTagName("THEAD")[0].getElementsByTagName("TR"),u=0;u<o.length;u++)for(var G=o[u].cells,D=0;D<G.length;D++){var A=G[D],z=A.parentNode.rowIndex,E=z+"-"+A.cellIndex,K=A.rowSpan||1,A=A.colSpan||1,C;"undefined"==typeof t[z]&&(t[z]=[]);var w;for(w=
0;w<t[z].length+1;w++)if("undefined"==typeof t[z][w]){C=w;break}r[E]=C;for(w=z;w<z+K;w++){"undefined"==typeof t[w]&&(t[w]=[]);for(var E=t[w],F=C;F<C+A;F++)E[F]="x"}}var B=c(i.config.selectorHeaders,i).each(function(a){this.column=r[this.parentNode.rowIndex+"-"+this.cellIndex];this.count=this.order="Number"!=typeof i.config.sortInitialOrder?"desc"==i.config.sortInitialOrder.toLowerCase()?1:0:1==i.config.sortInitialOrder?1:0;if(c.metadata&&!1===c(this).metadata().sorter||i.config.headers[a]&&!1===i.config.headers[a].sorter)this.sortDisabled=
!0;k(i,a)&&(this.order=this.lockedOrder=k(i,a));if(!this.sortDisabled){var b=c(this).addClass(i.config.cssHeader);i.config.onRenderHeader&&i.config.onRenderHeader.apply(b)}i.config.headerList[a]=this});i.config.debug&&(b("Built headers:",m),d(B));this.config.parsers=g(this,B);j=e(this);var H=[n.cssDesc,n.cssAsc];if(this.config.widthFixed){var I=c("<colgroup>");c("tr:first td",this.tBodies[0]).each(function(){I.append(c("<col>").css("width",c(this).width()))});c(this).prepend(I)}B.click(function(a){var b=
v[0].tBodies[0]&&v[0].tBodies[0].rows.length||0;if(!this.sortDisabled&&b>0){v.trigger("sortStart");c(this);b=this.column;this.order=this.count++%2;if(this.lockedOrder)this.order=this.lockedOrder;if(a[n.sortMultiSortKey]){a:{for(var a=n.sortList,e=a.length,i=0;i<e;i++)if(a[i][0]==b){a=true;break a}a=false}if(a)for(a=0;a<n.sortList.length;a++){e=n.sortList[a];i=n.headerList[e[0]];if(e[0]==b){i.count=e[1];i.count++;e[1]=i.count%2}}else n.sortList.push([b,this.order])}else{n.sortList=[];if(n.sortForce!=
null){e=n.sortForce;for(a=0;a<e.length;a++)e[a][0]!=b&&n.sortList.push(e[a])}n.sortList.push([b,this.order])}setTimeout(function(){x(v[0],B,n.sortList,H);f(v[0],s(v[0],n.sortList,j))},1);return false}}).mousedown(function(){if(n.cancelSelection){this.onselectstart=function(){return false};return false}});v.bind("update",function(){var a=this;setTimeout(function(){a.config.parsers=g(a,B);j=e(a)},1)}).bind("updateCell",function(a,b){var c=this.config,e=[b.parentNode.rowIndex-1,b.cellIndex];j.normalized[e[0]][e[1]]=
c.parsers[e[1]].format(h(c,b),b)}).bind("sorton",function(a,b){c(this).trigger("sortStart");n.sortList=b;for(var e=n.sortList,i=this.config,g=e.length,d=0;d<g;d++){var h=e[d],m=i.headerList[h[0]];m.count=h[1];m.count++}x(this,B,e,H);f(this,s(this,e,j))}).bind("appendCache",function(){f(this,j)}).bind("applyWidgetId",function(a,b){p(b).format(this)}).bind("applyWidgets",function(){q(this)});c.metadata&&(c(this).metadata()&&c(this).metadata().sortlist)&&(n.sortList=c(this).metadata().sortlist);0<n.sortList.length&&
v.trigger("sorton",[n.sortList]);q(this)}})};this.addParser=function(a){for(var b=o.length,c=!0,e=0;e<b;e++)o[e].id.toLowerCase()==a.id.toLowerCase()&&(c=!1);c&&o.push(a)};this.addWidget=function(a){u.push(a)};this.formatFloat=function(a){a=parseFloat(a);return isNaN(a)?0:a};this.formatInt=function(a){a=parseInt(a);return isNaN(a)?0:a};this.isDigit=function(a){return/^[-+]?\d*$/.test(c.trim(a.replace(/[,.']/g,"")))};this.clearTableBody=function(a){c.browser.msie?function(){for(;this.firstChild;)this.removeChild(this.firstChild)}.apply(a.tBodies[0]):
a.tBodies[0].innerHTML=""}}});c.fn.extend({tablesorter:c.tablesorter.construct});var f=c.tablesorter;f.addParser({id:"text",is:function(){return!0},format:function(b){return c.trim(b.toLocaleLowerCase())},type:"text"});f.addParser({id:"digit",is:function(b,d){return c.tablesorter.isDigit(b,d.config)},format:function(b){return c.tablesorter.formatFloat(b)},type:"numeric"});f.addParser({id:"currency",is:function(b){return/^[\u00a3$\u20ac?.]/.test(b)},format:function(b){return c.tablesorter.formatFloat(b.replace(RegExp(/[\u00a3$\u20ac]/g),
""))},type:"numeric"});f.addParser({id:"ipAddress",is:function(b){return/^\d{2,3}[\.]\d{2,3}[\.]\d{2,3}[\.]\d{2,3}$/.test(b)},format:function(b){for(var b=b.split("."),d="",g=b.length,a=0;a<g;a++)var e=b[a],d=2==e.length?d+("0"+e):d+e;return c.tablesorter.formatFloat(d)},type:"numeric"});f.addParser({id:"url",is:function(b){return/^(https?|ftp|file):\/\/$/.test(b)},format:function(b){return jQuery.trim(b.replace(RegExp(/(https?|ftp|file):\/\//),""))},type:"text"});f.addParser({id:"isoDate",is:function(b){return/^\d{4}[\/-]\d{1,2}[\/-]\d{1,2}$/.test(b)},
format:function(b){return c.tablesorter.formatFloat(""!=b?(new Date(b.replace(RegExp(/-/g),"/"))).getTime():"0")},type:"numeric"});f.addParser({id:"percent",is:function(b){return/\%$/.test(c.trim(b))},format:function(b){return c.tablesorter.formatFloat(b.replace(RegExp(/%/g),""))},type:"numeric"});f.addParser({id:"usLongDate",is:function(b){return b.match(RegExp(/^[A-Za-z]{3,10}\.? [0-9]{1,2}, ([0-9]{4}|'?[0-9]{2}) (([0-2]?[0-9]:[0-5][0-9])|([0-1]?[0-9]:[0-5][0-9]\s(AM|PM)))$/))},format:function(b){return c.tablesorter.formatFloat((new Date(b)).getTime())},
type:"numeric"});f.addParser({id:"shortDate",is:function(b){return/\d{1,2}[\/\-]\d{1,2}[\/\-]\d{2,4}/.test(b)},format:function(b,d){var g=d.config,b=b.replace(/\-/g,"/");if("us"==g.dateFormat)b=b.replace(/(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{4})/,"$3/$1/$2");else if("uk"==g.dateFormat)b=b.replace(/(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{4})/,"$3/$2/$1");else if("dd/mm/yy"==g.dateFormat||"dd-mm-yy"==g.dateFormat)b=b.replace(/(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{2})/,"$1/$2/$3");return c.tablesorter.formatFloat((new Date(b)).getTime())},
type:"numeric"});f.addParser({id:"time",is:function(b){return/^(([0-2]?[0-9]:[0-5][0-9])|([0-1]?[0-9]:[0-5][0-9]\s(am|pm)))$/.test(b)},format:function(b){return c.tablesorter.formatFloat((new Date("2000/01/01 "+b)).getTime())},type:"numeric"});f.addParser({id:"metadata",is:function(){return!1},format:function(b,d,g){b=d.config;b=!b.parserMetadataName?"sortValue":b.parserMetadataName;return c(g).metadata()[b]},type:"numeric"});f.addWidget({id:"zebra",format:function(b){var d;b.config.debug&&(d=new Date);
var g,a=-1,e;c("tr:visible",b.tBodies[0]).each(function(){g=c(this);g.hasClass(b.config.cssChildRow)||a++;e=0==a%2;g.removeClass(b.config.widgetZebra.css[e?0:1]).addClass(b.config.widgetZebra.css[e?1:0])});b.config.debug&&c.tablesorter.benchmark("Applying Zebra widget",d)}})})(jQuery);
(function(c){c(function(){c.tablesorter&&(c("<div>"),c.tablesorter.defaults.cssAsc="column-header-asc",c.tablesorter.defaults.cssDesc="column-header-desc",c.tablesorter.defaults.cssHeader="column-header",c.tablesorter.addParser({id:"datetime",is:function(){return!1},format:function(f,b,d){return c("[datetime]:first",d).attr("datetime")},type:"text"}),c.tablesorter.addParser({id:"ignoreCase",is:function(){return!1},format:function(c){return c.toLowerCase()},type:"text"}),c.tablesorter.addParser({id:"string",
is:function(){return!1},format:function(c){return c},type:"text"}),c.tablesorter.addParser({id:"number",is:function(){return!1},format:function(f,b,d){f=c(".number:first",d).attr("data-value");null==f&&(f=Number.MIN_VALUE);return f},type:"numeric"}),c(".table-sortable").each(function(){c(this).tablesorter()}))})})(jQuery);
(function(c){c.factory("collapse_module",{init:function(){var b=this;this.$column=c(this.options.column);this.modules=c(this.options.modules,this.element);this.first_module=this.modules.get(0);this.trigger=c(".trigger:first",this.first_module);this.first_section=c(".module-section",this.first_module);this.other_modules=this.modules.slice(1);this.column_offset=this.$column.css("margin-left");this.set_collapsed(this.options.collapsed);this.trigger.click(function(c){return b.toggle(c)})},set_collapsed:function(b){(this.toggle_state=
b)?(this.trigger.addClass("collapsed"),this.$column.css("margin-left",0),this.first_section.hide(),this.other_modules.hide()):(this.trigger.removeClass("collapsed"),this.$column.css("margin-left",this.column_offset),this.first_section.show(),this.other_modules.show())},toggle:function(){var b=this;this.toggle_state?(c.localstore("filters_collapsed",0,!1),this.trigger.removeClass("collapsed"),this.$column.animate({marginLeft:this.column_offset},function(){b.first_section.slideDown(function(){b.modules.removeClass("collapsed")});
b.other_modules.fadeIn()})):(c.localstore("filters_collapsed",1,!1),this.trigger.addClass("collapsed"),this.other_modules.fadeOut(),this.first_section.slideUp(function(){b.$column.animate({marginLeft:0});b.modules.addClass("collapsed")}));this.toggle_state=!this.toggle_state;this.options.toggle_callback&&this.options.toggle_callback.call(this.trigger,this.toggle_state);return!1}});var f=c("body").is(".embed")||c.localstore("filters_collapsed");c.extend(!0,c.collapse_module,{defaults:{collapsed:null===
f?!1:!!f,modules:".module",column:"#main-column"}})})(jQuery);
(function(c){function f(b,a,c){var h=c.relative?b.position().top:b.offset().top,d=c.relative?b.position().left:b.offset().left,f=c.position[0],h=h-(a.outerHeight()-c.offset[0]),d=d+(b.outerWidth()+c.offset[1]),q=a.outerHeight()+b.outerHeight();"center"==f&&(h+=q/2);"bottom"==f&&(h+=q);f=c.position[1];b=a.outerWidth()+b.outerWidth();"center"==f&&(d-=b/2);"left"==f&&(d-=b);return{top:h,left:d}}function b(b,a){var e=this,h=b.add(e),l,k=0,q=0,p=b.attr("title"),x=d[a.effect],s,j=b.is(":input"),o=j&&b.is(":checkbox, :radio, select, :button, :submit"),
u=b.attr("type"),y=a.events[u]||a.events[j?o?"widget":"input":"def"];if(!x)throw'Nonexistent effect "'+a.effect+'"';y=y.split(/,\s*/);if(2!=y.length)throw"Tooltip: bad events configuration for "+u;b.bind(y[0],function(b){clearTimeout(k);a.predelay?q=setTimeout(function(){e.show(b)},a.predelay):e.show(b)}).bind(y[1],function(b){clearTimeout(q);a.delay?k=setTimeout(function(){e.hide(b)},a.delay):e.hide(b)});p&&a.cancelDefault&&(b.removeAttr("title"),b.data("title",p));c.extend(e,{show:function(d){if(!l){if(p)l=
c(a.layout).addClass(a.tipClass).appendTo(document.body).hide().append(p);else if(a.tip)l=c(a.tip).eq(0);else{l=b.next();l.length||(l=b.parent().next())}if(!l.length)throw"Cannot find tooltip for "+b;}if(e.isShown())return e;l.stop(true,true);var j=f(b,l,a),d=d||c.Event();d.type="onBeforeShow";h.trigger(d,[j]);if(d.isDefaultPrevented())return e;j=f(b,l,a);l.css({position:"absolute",top:j.top,left:j.left});s=true;x[0].call(e,function(){d.type="onShow";s="full";h.trigger(d)});j=a.events.tooltip.split(/,\s*/);
l.bind(j[0],function(){clearTimeout(k);clearTimeout(q)});j[1]&&!b.is("input:not(:checkbox, :radio), textarea")&&l.bind(j[1],function(a){a.relatedTarget!=b[0]&&b.trigger(y[1].split(" ")[0])});return e},hide:function(b){if(!l||!e.isShown())return e;b=b||c.Event();b.type="onBeforeHide";h.trigger(b);if(!b.isDefaultPrevented()){s=false;d[a.effect][1].call(e,function(){b.type="onHide";s=false;h.trigger(b)});return e}},isShown:function(a){return a?s=="full":s},getConf:function(){return a},getTip:function(){return l},
getTrigger:function(){return b}});c.each(["onHide","onBeforeShow","onShow","onBeforeHide"],function(b,d){c.isFunction(a[d])&&c(e).bind(d,a[d]);e[d]=function(a){c(e).bind(d,a);return e}})}c.tools=c.tools||{version:"@VERSION"};c.tools.tooltip={conf:{effect:"toggle",fadeOutSpeed:"fast",predelay:0,delay:30,opacity:1,tip:0,position:["top","center"],offset:[0,0],relative:!1,cancelDefault:!0,events:{def:"mouseenter,mouseleave",input:"focus,blur",widget:"focus mouseenter,blur mouseleave",tooltip:"mouseenter,mouseleave"},
layout:"<div/>",tipClass:"tooltip"},addEffect:function(b,a,c){d[b]=[a,c]}};var d={toggle:[function(b){var a=this.getConf(),c=this.getTip(),a=a.opacity;1>a&&c.css({opacity:a});c.show();b.call()},function(b){this.getTip().hide();b.call()}],fade:[function(b){var a=this.getConf();this.getTip().fadeTo(a.fadeInSpeed,a.opacity,b)},function(b){this.getTip().fadeOut(this.getConf().fadeOutSpeed,b)}]};c.fn.tooltip=function(d){var a=this.data("tooltip");if(a)return a;d=c.extend(!0,{},c.tools.tooltip.conf,d);
"string"==typeof d.position&&(d.position=d.position.split(/,?\s/));this.each(function(){a=new b(c(this),d);c(this).data("tooltip",a)});return d.api?a:this}})(jQuery);
(function(c,f){f.filters={init_domain_type_property_filter:function(b){c(":text[name=domain], :text[name=type], :text[name=property]",b).suggest(c.extend({scoring:"schema",format:null,mql_output:JSON.stringify([{id:null,name:null,type:{id:null,"id|=":["/type/domain","/type/type","/type/property"],limit:1}}])},f.suggest_options.any("type:/type/domain","type:/type/type","type:/type/property"))).bind("fb-select",function(b,f){var a=c(this);a.val(f.id);var e=f.type.id;"/type/domain"===e?a.attr("name",
"domain"):"/type/type"===e?a.attr("name","type"):"/type/property"===e&&a.attr("name","property");this.form.submit()}).parents(".filter-form").submit(function(){return!1})}};c(function(){c(".filter-form :input").keypress(function(b){13===b.keyCode&&this.form.submit();return!0});c(".filter-help-trigger").tooltip({events:{def:"click,mouseout"},position:"top center",effect:"fade",delay:300,offset:[-8,0]});c(".filter-form-trigger").click(function(){var b=c(this).siblings(".filter-form");b.is(":hidden")?
b.slideDown(function(){c(":text:first",b).focus()}):b.slideUp()})})})(jQuery,window.freebase);
(function(c){var f="undefined"!=typeof window.innerWidth?function(){return{w:window.innerWidth,h:window.innerHeight}}:"undefined"!=typeof document.documentElement&&"undefined"!=typeof document.documentElement.clientWidth&&0!=document.documentElement.clientWidth?function(){return{w:document.documentElement.clientWidth,h:document.documentElement.clientHeight}}:function(){return{w:document.getElementsByTagName("body")[0].clientWidth,h:document.getElementsByTagName("body")[0].clientHeight}};window.kbs=
function(b){c(".kbs.current",b).removeClass("current");var d=c(".domain-section:first",b),g=c(".domain-section:last",b),a=this.scroll_to=function(a){var b=c(document).scrollTop();c(document).height();var e=f().h,e=b+e,d=a.offset().top,a=d+a.height();d<b?c(document).scrollTop(d):a>e&&c(document).scrollTop(b+(a-e))},e=this.get_current=function(){return c(".kbs.current:first",b)},h=this.set_next=function(b,c,d){b=b||e();c.length&&(b.removeClass("current"),c.addClass("current"),d||a(c))},l=this.next_domain=
function(a){var b=e(),c=k(b);c&&(c=c.find(".kbs:first"),h(b,c,a))},k=this._next_domain=function(a){if(!a||!a.length)return c(".domain-section:first",b);a=a.closest(".domain-section");return!a.length||a[0]===g[0]?d:a.next(".domain-section")},q=this.prev_domain=function(){var a=e(),b=p(a);b&&(b=b.find(".kbs:first"),h(a,b))},p=this._prev_domain=function(a){if(!a||!a.length)return c(".domain-section:last",b);var e=a.closest(".domain-section");return a.closest(".property-section").length||a.closest(".type-section").length?
e:!e.length||e[0]===d[0]?g:e.prev(".domain-section")},x=this.next_type=function(){var a=e(),b=s(a);b&&(b=b.find(".kbs:first"),h(a,b))},s=this._next_type=function(a){if(!a||!a.length)return c(".type-section:first",b);var e=a.closest(".domain-section"),a=a.closest(".type-section"),a=a.length?a.next(".type-section"):e.find(".type-section:first");if(!a||!a.length){var d=k(e);if(d)for(;d.get(0)!==e.get(0);){a=d.find(".type-section:first");if(a.length)break;d=k(d)}}return a},j=this.prev_type=function(){var a=
e(),b=o(a);b&&(b=b.find(".kbs:first"),h(a,b))},o=this._prev_type=function(a){if(!a||!a.length)return c(".type-section:last",b);var e=a.closest(".domain-section"),d=a.closest(".type-section");if(a.closest(".property-section").length)return d;var h;d.length&&(h=d.prev(".type-section"));if(!h||!h.length)if(a=p(e))for(;a.get(0)!==e.get(0);){h=a.find(".type-section:last");if(h.length)break;a=p(a)}return h},u=this.next_prop=function(){var a=e(),b=y(a);b&&(b=b.find(".kbs:first"),h(a,b))},y=this._next_prop=
function(a){if(!a||!a.length)return c(".property-section:first",b);var e=a.closest(".domain-section"),d=a.closest(".type-section"),h=a.closest(".property-section"),e=h.length?h.next(".property-section"):d.length?d.find(".property-section:first"):e.find(".property-section:first");if(!e||!e.length)if(a=s(a))for(;a.get(0)!==d.get(0);){e=a.find(".property-section:first");if(e.length)break;null==d.get(0)&&(d=a);a=s(a)}return e},v=this.prev_prop=function(){var a=e(),b=J(a);b&&(b=b.find(".kbs:first"),h(a,
b))},J=this._prev_prop=function(a){if(!a||!a.length)return c(".property-section:last",b);var e=a.closest(".domain-section"),d=a.closest(".type-section"),h=a.closest(".property-section");if(a.closest(".data-section").length)return h;var f;h.length&&(f=h.prev(".property-section"));if(!f||!f.length)if(j=d.length?o(d):o(e))for(;j.get(0)!==d.get(0);){f=j.find(".property-section:last");if(f.length)break;null==d.get(0)&&(d=j);j=o(j)}return f};this.next=function(){var a=e(),b=this._next(a);b&&h(a,b)};this._next=
function(a){if(!a||!a.length)return c(".domain-section:first .kbs:first",b);var e=a.closest(".domain-section"),h=a.closest(".type-section"),f=a.closest(".property-section");if(a.closest(".data-section").length){a=a.next(".kbs");if(a.length)return a;a=f.next(".property-section").find(".kbs:first");if(a.length)return a;a=h.next(".type-section").find(".kbs:first")}else if(f.length){a=f.find(".data-section:first .kbs:first");if(a.length)return a;a=f.next(".property-section").find(".kbs:first");if(a.length)return a;
a=h.next(".type-section").find(".kbs:first")}else if(h.length){a=h.find(".property-section:first .kbs:first");if(a.length)return a;a=h.next(".type-section").find(".kbs:first")}else a=e.find(".type-section:first .kbs:first");return a.length?a:e.get(0)===g.get(0)?d.find(".kbs:first"):e.next(".domain-section").find(".kbs:first")};this.prev=function(){var a=e(),b=this._prev(a);b&&h(a,b)};this._prev=function(a){if(!a||!a.length)return a=c(".data-section:last .kbs:last",b),a.length||(a=c(".property-section:last .kbs:first",
b)),a.length||(a=c(".type-section:last .kbs:first",b)),a.length||(a=c(".domain-section:last .kbs:first",b)),a;var e=a.closest(".domain-section"),h=a.closest(".type-section"),f=a.closest(".property-section");return a.closest(".data-section").length?(a=a.prev(".kbs"),a.length?a:f.find(".kbs:first")):f.length?(a=f.prev(".property-section").find(".kbs:last"),a.length?a:h.find(".kbs:first")):h.length?(a=h.prev(".type-section").find(".kbs:last"),a.length?a:e.find(".kbs:first")):e.get(0)===d.get(0)?g.find(".kbs:last"):
e.prev(".domain-section").find(".kbs:last")};this.edit=function(){this.get_current().trigger("edit")};var n=this;c(document).unbind(".kbs").bind("keydown.kbs",function(a){var b=a.target;if(b==document.body||b==document||b==window||b==c("html")[0])b=a.keyCode,68===b?a.shiftKey?q():l():84===b?a.shiftKey?j():x():80===b?a.shiftKey?v():u():74===b?n.next():75===b?n.prev():69===b&&n.edit()})}})(jQuery);
(function(c,f){var b=window.propbox={init:function(d,g){g=c.extend({lang:"/lang/en"},g);if(!g.base_ajax_url)throw Error("base_ajax_url required in propbox options");if(!g.base_static_url)throw Error("base_static_url required in propbox options");if(!g.id)throw Error("topic id required in propbox options");if(!g.lang)throw Error("lang required in propbox options");b.options=g;b.kbs=new f(d);b.kbs.set_next(b.kbs.get_current(),c(".kbs:visible:first",d,!0));c(".kbs",d).live("click",function(){var a=b.kbs.get_current();
b.kbs.set_next(a,c(this),!0)}).live("edit",function(){var a=c(this).find(".headmenu:first").data("submenu");a&&c("li:first a:first",a).click()});b.init_menus(d)},init_menus:function(d,f){d=c(d||document);f&&c(".nicemenu",d).nicemenu();var a;a=d&&d.is(".hover-row")?d:c(".hover-row",d);a.hover(b.row_menu_hoverover,b.row_menu_hoverout);a.dblclick(function(){var a=c(".nicemenu .default-action",this);a.length||(a=c(".nicemenu:first .submenu:first a:first",this));var b=a.attr("href");("#"==b||0==b.indexOf("javascript:void(0)"))&&
c(a).click()});c(".nicemenu .headmenu",d).add(c(".nicemenu .default-action",d)).click("click",function(){if(b.kbs){var a=b.kbs.get_current();a&&b.kbs.set_next(a,c(this).parents(".kbs:first"),!0)}return!1})},row_menu_hoverover:function(){c(this).addClass("row-hover")},row_menu_hoverout:function(){c(this).removeClass("row-hover")},get_script:function(d,f){var a=b.get_script.cache;a||(a=b.get_script.cache={});var e=a[d];e?1===e.state?e.callbacks.push(f):4===e.state&&f():(e=a[d]={state:0,callbacks:[f]},
c.ajax({url:b.options.base_static_url+d,dataType:"script",beforeSend:function(){e.state=1},success:function(){e.state=4;c.each(e.callbacks,function(a,b){b()})},error:function(){e.state=-1}}))},prop_edit:function(d,f){var a=c(d).parents(".property-section");a.length||(a=c(d).parents(".submenu").data("headmenu").parents(".property-section"));a=a.find(".data-section .data-row:first:visible .nicemenu:first .headmenu:first a");a.length?a.click():b.prop_add(d,f);return!1},prop_add:function(d,f){var a=c(d).parents(".property-section");
a.length||(a=c(d).parents(".submenu").data("headmenu").parents(".property-section"));b.get_script("/propbox-edit.mf.js",function(){b.edit.prop_add_begin(a,f)});return!1},value_edit:function(d){var f=c(d).parents(".submenu").data("headmenu").parents(".data-row:first"),a=f.parents(".property-section");b.get_script("/propbox-edit.mf.js",function(){b.edit.value_edit_begin(a,f)});return!1},value_delete:function(d){var f=c(d).parents(".submenu").data("headmenu").parents(".data-row:first"),a=f.parents(".property-section");
b.get_script("/propbox-edit.mf.js",function(){b.edit.value_delete_begin(a,f)});return!1},remove_type:function(d){var d=c(d),f=d.parents(".type-section");b.get_script("/propbox-edit.mf.js",function(){b.edit.remove_type_begin(d,f)});return!1},add_type:function(d,f,a){var d=c(d),e=d.parents(".type-section"),h=b.options.incompatible_types;h?h.search(b.options.id,f,a,{compatible:function(){b.add_type_submit(d,e)},incompatible:h.overlay_incompatible_callback({onConfirm:function(){b.add_type_submit(d,e)}})}):
b.add_type_submit(d,e);return!1},add_type_submit:function(c,f){b.get_script("/propbox-edit.mf.js",function(){b.edit.add_type_submit(c,f)})},add_has_no_value:function(d){var f=c(d).parents(".submenu").data("headmenu").parents(".property-section");b.get_script("/propbox-edit.mf.js",function(){b.edit.add_has_no_value(f)});return!1},add_has_value:function(d){var f=c(d).parents(".submenu").data("headmenu").parents(".property-section");b.get_script("/propbox-edit.mf.js",function(){b.edit.add_has_value(f)});
return!1},remove_has_no_value:function(d){var f=c(d).parents(".property-section");b.get_script("/propbox-edit.mf.js",function(){b.edit.remove_has_no_value(f)});return!1},remove_has_value:function(d){var f=c(d).parents(".property-section");b.get_script("/propbox-edit.mf.js",function(){b.edit.remove_has_value(f)});return!1},more:function(d,f,a){var e=c(d).parents(".property-section");b.get_script("/propbox-edit.mf.js",function(){b.edit.more(e,f,a)})}}})(jQuery,window.kbs);
(function(c,f,b){f.infinitescroll=function(a,b,c){this.element=f(c);this._create(a,b)};f.infinitescroll.defaults={loading:{finished:b,finishedMsg:"<em>Congratulations, you've reached the end of the internet.</em>",img:"http://www.infinite-scroll.com/loading.gif",msg:null,msgText:"<em>Loading the next set of posts...</em>",selector:null,speed:"fast",start:b},state:{isDuringAjax:!1,isInvalidPage:!1,isDestroyed:!1,isDone:!1,isPaused:!1,currPage:1},callback:b,debug:!1,behavior:b,binder:f(c),nextSelector:"div.navigation a:first",
navSelector:"div.navigation",contentSelector:null,extraScrollPx:150,itemSelector:"div.post",animate:!1,pathParse:b,dataType:"html",appendCallback:!0,bufferPx:40,errorCallback:function(){},infid:0,pixelsFromNavToBottom:b,path:b};f.infinitescroll.prototype={_binding:function(a){var c=this,d=c.options;if(d.behavior&&this["_binding_"+d.behavior]!==b)this["_binding_"+d.behavior].call(this);else{if("bind"!==a&&"unbind"!==a)return this._debug("Binding value  "+a+" not valid"),!1;if("unbind"==a)this.options.binder.unbind("smartscroll.infscr."+
c.options.infid);else this.options.binder[a]("smartscroll.infscr."+c.options.infid,function(){c.scroll()});this._debug("Binding",a)}},_create:function(a,c){if(!this._validate(a))return!1;var d=this.options=f.extend(!0,{},f.infinitescroll.defaults,a),g=f(d.nextSelector).attr("href");d.contentSelector=d.contentSelector||this.element;d.loading.selector=d.loading.selector||d.contentSelector;g?(d.path=this._determinepath(g),d.loading.msg=f('<div id="infscr-loading"><img alt="Loading..." src="'+d.loading.img+
'" /><div>'+d.loading.msgText+"</div></div>"),(new Image).src=d.loading.img,d.pixelsFromNavToBottom=f(document).height()-f(d.navSelector).offset().top,d.loading.start=d.loading.start||function(){f(d.navSelector).hide();d.loading.msg.appendTo(d.loading.selector).show(d.loading.speed,function(){beginAjax(d)})},d.loading.finished=d.loading.finished||function(){d.loading.msg.fadeOut("normal")},d.callback=function(a,g){d.behavior&&a["_callback_"+d.behavior]!==b&&a["_callback_"+d.behavior].call(f(d.contentSelector)[0],
g);c&&c.call(f(d.contentSelector)[0],g)},this._setup()):this._debug("Navigation selector not found")},_debug:function(){if(this.options.debug)return c.console&&console.log.call(console,arguments)},_determinepath:function(a){var c=this.options;if(c.behavior&&this["_determinepath_"+c.behavior]!==b)this["_determinepath_"+c.behavior].call(this,a);else{if(c.pathParse)return this._debug("pathParse manual"),"function"===typeof c.pathParse?c.pathParse():c.pathParse;if(a.match(/^(.*?)\b2\b(.*?$)/))a=a.match(/^(.*?)\b2\b(.*?$)/).slice(1);
else if(a.match(/^(.*?)2(.*?$)/)){if(a.match(/^(.*?page=)2(\/.*|$)/))return a=a.match(/^(.*?page=)2(\/.*|$)/).slice(1);a=a.match(/^(.*?)2(.*?$)/).slice(1)}else{if(a.match(/^(.*?page=)1(\/.*|$)/))return a=a.match(/^(.*?page=)1(\/.*|$)/).slice(1);this._debug("Sorry, we couldn't parse your Next (Previous Posts) URL. Verify your the css selector points to the correct A tag. If you still get this error: yell, scream, and kindly ask for help at infinite-scroll.com.");c.state.isInvalidPage=!0}this._debug("determinePath",
a);return a}},_error:function(a){var c=this.options;c.behavior&&this["_error_"+c.behavior]!==b?this["_error_"+c.behavior].call(this,a):("destroy"!==a&&"end"!==a&&(a="unknown"),this._debug("Error",a),"end"==a&&this._showdonemsg(),c.state.isDone=!0,c.state.currPage=1,c.state.isPaused=!1,this._binding("unbind"))},_loadcallback:function(a,e){var d=this.options,g=this.options.callback,k=d.state.isDone?"done":!d.appendCallback?"no-append":"append";if(d.behavior&&this["_loadcallback_"+d.behavior]!==b)this["_loadcallback_"+
d.behavior].call(this,a,e);else{switch(k){case "done":return this._showdonemsg(),!1;case "no-append":"html"==d.dataType&&(e=f("<div>"+e+"</div>").find(d.itemSelector));break;case "append":var q=a.children();if(0==q.length)return this._error("end");for(k=document.createDocumentFragment();a[0].firstChild;)k.appendChild(a[0].firstChild);this._debug("contentSelector",f(d.contentSelector)[0]);f(d.contentSelector)[0].appendChild(k);e=q.get()}d.loading.finished.call(f(d.contentSelector)[0],d);d.animate&&
(k=f(c).scrollTop()+f("#infscr-loading").height()+d.extraScrollPx+"px",f("html,body").animate({scrollTop:k},800,function(){d.state.isDuringAjax=!1}));d.animate||(d.state.isDuringAjax=!1);g(this,e)}},_nearbottom:function(){var a=this.options,d=0+f(document).height()-a.binder.scrollTop()-f(c).height();if(a.behavior&&this["_nearbottom_"+a.behavior]!==b)this["_nearbottom_"+a.behavior].call(this);else return this._debug("math:",d,a.pixelsFromNavToBottom),d-a.bufferPx<a.pixelsFromNavToBottom},_pausing:function(a){var c=
this.options;if(c.behavior&&this["_pausing_"+c.behavior]!==b)this["_pausing_"+c.behavior].call(this,a);else{"pause"!==a&&("resume"!==a&&null!==a)&&this._debug("Invalid argument. Toggling pause value instead");switch(a&&("pause"==a||"resume"==a)?a:"toggle"){case "pause":c.state.isPaused=!0;break;case "resume":c.state.isPaused=!1;break;case "toggle":c.state.isPaused=!c.state.isPaused}this._debug("Paused",c.state.isPaused);return!1}},_setup:function(){var a=this.options;if(a.behavior&&this["_setup_"+
a.behavior]!==b)this["_setup_"+a.behavior].call(this);else return this._binding("bind"),!1},_showdonemsg:function(){var a=this.options;a.behavior&&this["_showdonemsg_"+a.behavior]!==b?this["_showdonemsg_"+a.behavior].call(this):(a.loading.msg.find("img").hide().parent().find("div").html(a.loading.finishedMsg).animate({opacity:1},2E3,function(){f(this).parent().fadeOut("normal")}),a.errorCallback.call(f(a.contentSelector)[0],"done"))},_validate:function(a){for(var b in a)return b.indexOf&&-1<b.indexOf("Selector")&&
0===f(a[b]).length?(this._debug("Your "+b+" found no elements."),!1):!0},bind:function(){this._binding("bind")},destroy:function(){this.options.state.isDestroyed=!0;return this._error("destroy")},pause:function(){this._pausing("pause")},resume:function(){this._pausing("resume")},retrieve:function(a){var c=this,d=c.options,g=this._determinepath(g),k,q,p,x,a=a||null;beginAjax=function(a){a.state.currPage++;c._debug("heading into ajax",g);k=f(a.contentSelector).is("table")?f("<tbody/>"):f("<div/>");
q=g.join(a.state.currPage);p="html"==a.dataType||"json"==a.dataType?a.dataType:"html+callback";a.appendCallback&&"html"==a.dataType&&(p+="+callback");switch(p){case "html+callback":c._debug("Using HTML via .load() method");k.load(q+" "+a.itemSelector,null,function(a){c._loadcallback(k,a)});break;case "html":case "json":c._debug("Using "+p.toUpperCase()+" via $.ajax() method"),f.ajax({url:q,dataType:a.dataType,complete:function(a,b){(x="undefined"!==typeof a.isResolved?a.isResolved():"success"===b||
"notmodified"===b)?c._loadcallback(k,a.responseText):c._error("end")}})}};if(d.behavior&&this["retrieve_"+d.behavior]!==b)this["retrieve_"+d.behavior].call(this,a);else{if(d.state.isDestroyed)return this._debug("Instance is destroyed"),!1;d.state.isDuringAjax=!0;d.loading.start.call(f(d.contentSelector)[0],d)}},scroll:function(){var a=this.options,c=a.state;a.behavior&&this["scroll_"+a.behavior]!==b?this["scroll_"+a.behavior].call(this):!c.isDuringAjax&&!c.isInvalidPage&&!c.isDone&&!c.isDestroyed&&
!c.isPaused&&this._nearbottom()&&this.retrieve()},toggle:function(){this._pausing()},unbind:function(){this._binding("unbind")},update:function(a){f.isPlainObject(a)&&(this.options=f.extend(!0,this.options,a))}};f.fn.infinitescroll=function(a,b){switch(typeof a){case "string":var c=Array.prototype.slice.call(arguments,1);this.each(function(){var b=f.data(this,"infinitescroll");if(!b||!f.isFunction(b[a])||"_"===a.charAt(0))return!1;b[a].apply(b,c)});break;case "object":this.each(function(){var c=f.data(this,
"infinitescroll");c?c.update(a):f.data(this,"infinitescroll",new f.infinitescroll(a,b,this))})}return this};var d=f.event,g;d.special.smartscroll={setup:function(){f(this).bind("scroll",d.special.smartscroll.handler)},teardown:function(){f(this).unbind("scroll",d.special.smartscroll.handler)},handler:function(a,b){var c=this,d=arguments;a.type="smartscroll";g&&clearTimeout(g);g=setTimeout(function(){f.event.handle.apply(c,d)},"execAsap"===b?0:100)}};f.fn.smartscroll=function(a){return a?this.bind("smartscroll",
a):this.trigger("smartscroll",["execAsap"])}})(window,jQuery);(function(c){c.fn.fixedcolumn=function(f){var b=c.extend(!0,{},f);return this.each(function(){var d=c(this).find("tr:first").children();1<d.length&&(b.all||(d=c(d.get(0))),d.each(function(){var b=c(this),a=b[0].nodeName.toUpperCase();if("TD"===a||"TH"===a)a=b.width(),0<a&&c(":first-child",b).width(a).css("display","inline-block")}))})}})(jQuery);
(function(c,f,b){var d=f.sameas={init:function(){c(".column.nav").collapse_module({modules:".module",column:".section"});c(":text[name=creator]").suggest(f.suggest_options.any("type:/type/user")).bind("fb-select",function(b,a){c(this).val(a.id).parents("form:first").submit()});b.init_menus();c(".infinitescroll > tbody").each(function(){d.init_infinitescroll(c(this))});c(".infinitescroll").fixedcolumn()},infid:0,init_infinitescroll:function(g){if(g.attr("data-next")){var a=g.next("tfoot").find(".infinitescroll-next");
g.infinitescroll({loading:{msgText:"Fetching more links",img:f.h.static_url("lib/template/img/horizontal-loader.gif")},nextSelector:a,navSelector:a,dataType:"json",pathParse:function(){return[a[0].href+"&"+c.param({next:g.attr("data-next")})+"&page=",""]},appendCallback:!1,infid:d.infid++},function(a){var a=JSON.parse(a),d=c(a.result.html);if(a=d.attr("data-next")){d=c(">tr",d);g.append(d);d.each(function(){b.init_menus(this,!0)});g.attr("data-next",a);var a=c(">tr",g).length,d=g.parent("table"),
f=d.prev(".table-title").find("[name=infinitescroll-count]");c(".number",f).attr("data-value",a).text(a);d.trigger("update")}else(a=g.data("infinitescroll"))&&a.unbind()});c(window).trigger("scroll")}else g.next("tfoot").remove()},add_key:function(b,a){var e=c(this);f.get_script(f.h.static_url("sameas-edit.mf.js"),function(){d.edit.add_key_begin(e,a)});return!1},edit_key:function(b,a){var e=c(b).parents(".submenu").data("headmenu").parents(".data-row:first");f.get_script(f.h.static_url("sameas-edit.mf.js"),
function(){d.edit.edit_key_begin(e,a)});return!1},delete_key:function(b,a){var e=c(b).parents(".submenu").data("headmenu").parents(".data-row:first");f.get_script(f.h.static_url("sameas-edit.mf.js"),function(){d.edit.delete_key_begin(e,a)});return!1}};c(d.init)})(jQuery,window.freebase,window.propbox);
