
/*
 * Copyright 2012, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Additional Licenses for Third Party components can be found here:
 * http://wiki.freebase.com/wiki/Freebase_Site_License
 *
 */
(function(a,d){var h,f,g,e,b,c,i,t,o,k,j,m,p,r,q,s,n,v,l,w,z,u,y,B;h=function(a){return new h.prototype.init(a)};"undefined"!==typeof require&&"undefined"!==typeof exports&&"undefined"!==typeof module?module.exports=h:a.Globalize=h;h.cultures={};h.prototype={constructor:h,init:function(a){this.cultures=h.cultures;this.cultureSelector=a;return this}};h.prototype.init.prototype=h.prototype;h.cultures["default"]={name:"en",englishName:"English",nativeName:"English",isRTL:!1,language:"en",numberFormat:{pattern:["-n"],
decimals:2,",":",",".":".",groupSizes:[3],"+":"+","-":"-",NaN:"NaN",negativeInfinity:"-Infinity",positiveInfinity:"Infinity",percent:{pattern:["-n %","n %"],decimals:2,groupSizes:[3],",":",",".":".",symbol:"%"},currency:{pattern:["($n)","$n"],decimals:2,groupSizes:[3],",":",",".":".",symbol:"$"}},calendars:{standard:{name:"Gregorian_USEnglish","/":"/",":":":",firstDay:0,days:{names:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),namesAbbr:"Sun Mon Tue Wed Thu Fri Sat".split(" "),
namesShort:"Su Mo Tu We Th Fr Sa".split(" ")},months:{names:"January February March April May June July August September October November December ".split(" "),namesAbbr:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec ".split(" ")},AM:["AM","am","AM"],PM:["PM","pm","PM"],eras:[{name:"A.D.",start:null,offset:0}],twoDigitYearMax:2029,patterns:{d:"M/d/yyyy",D:"dddd, MMMM dd, yyyy",t:"h:mm tt",T:"h:mm:ss tt",f:"dddd, MMMM dd, yyyy h:mm tt",F:"dddd, MMMM dd, yyyy h:mm:ss tt",M:"MMMM dd",Y:"yyyy MMMM",
S:"yyyy'-'MM'-'dd'T'HH':'mm':'ss"}}},messages:{}};h.cultures["default"].calendar=h.cultures["default"].calendars.standard;h.cultures.en=h.cultures["default"];h.cultureSelector="en";f=/^0x[a-f0-9]+$/i;g=/^[+\-]?infinity$/i;e=/^[+\-]?\d*\.?\d*(e[+\-]?\d+)?$/;b=/^\s+|\s+$/g;c=function(a,b){if(a.indexOf)return a.indexOf(b);for(var c=0,e=a.length;c<e;c++)if(a[c]===b)return c;return-1};i=function(a,b){return a.substr(a.length-b.length)===b};t=function(){var a,b,c,e,g,i=arguments[0]||{},f=1,m=arguments.length,
h=!1;"boolean"===typeof i&&(h=i,i=arguments[1]||{},f=2);for("object"!==typeof i&&!k(i)&&(i={});f<m;f++)if(null!=(a=arguments[f]))for(b in a)c=i[b],e=a[b],i!==e&&(h&&e&&(j(e)||(g=o(e)))?(g?(g=!1,c=c&&o(c)?c:[]):c=c&&j(c)?c:{},i[b]=t(h,c,e)):e!==d&&(i[b]=e));return i};o=Array.isArray||function(a){return"[object Array]"===Object.prototype.toString.call(a)};k=function(a){return"[object Function]"===Object.prototype.toString.call(a)};j=function(a){return"[object Object]"===Object.prototype.toString.call(a)};
m=function(a,b){return 0===a.indexOf(b)};p=function(a){return(a+"").replace(b,"")};r=function(a){return isNaN(a)?NaN:Math[0>a?"ceil":"floor"](a)};q=function(a,b,c){var e;for(e=a.length;e<b;e+=1)a=c?"0"+a:a+"0";return a};s=function(a,b){for(var c=0,e=!1,d=0,i=a.length;d<i;d++){var g=a.charAt(d);switch(g){case "'":e?b.push("'"):c++;e=!1;break;case "\\":e&&b.push("\\");e=!e;break;default:b.push(g),e=!1}}return c};n=function(a,b){var b=b||"F",c;c=a.patterns;var e=b.length;if(1===e){c=c[b];if(!c)throw"Invalid date format string '"+
b+"'.";b=c}else 2===e&&"%"===b.charAt(0)&&(b=b.charAt(1));return b};v=function(a,b,c){function e(a,b){var c;c=a+"";return 1<b&&c.length<b?(c=t[b-2]+c,c.substr(c.length-b,b)):c}function d(){if(m||h)return m;m=p.test(b);h=!0;return m}function i(a,b){if(l)return l[b];switch(b){case 0:return a.getFullYear();case 1:return a.getMonth();case 2:return a.getDate();default:throw"Invalid part value "+b;}}var g=c.calendar,f=g.convert;if(!b||!b.length||"i"===b){if(c&&c.name.length)if(f)c=v(a,g.patterns.F,c);else{var c=
new Date(a.getTime()),j=z(a,g.eras);c.setFullYear(u(a,g,j));c=c.toLocaleString()}else c=a.toString();return c}var j=g.eras,o="s"===b,b=n(g,b),c=[],k,t=["0","00","000"],m,h,p=/([^d]|^)(d|dd)([^d]|$)/g,r=0,q=w(),l;for(!o&&f&&(l=f.fromGregorian(a));;){k=q.lastIndex;f=q.exec(b);k=b.slice(k,f?f.index:b.length);r+=s(k,c);if(!f)break;if(r%2)c.push(f[0]);else switch(k=f[0],f=k.length,k){case "ddd":case "dddd":c.push((3===f?g.days.namesAbbr:g.days.names)[a.getDay()]);break;case "d":case "dd":m=!0;c.push(e(i(a,
2),f));break;case "MMM":case "MMMM":k=i(a,1);c.push(g.monthsGenitive&&d()?g.monthsGenitive[3===f?"namesAbbr":"names"][k]:g.months[3===f?"namesAbbr":"names"][k]);break;case "M":case "MM":c.push(e(i(a,1)+1,f));break;case "y":case "yy":case "yyyy":k=l?l[0]:u(a,g,z(a,j),o);4>f&&(k%=100);c.push(e(k,f));break;case "h":case "hh":k=a.getHours()%12;0===k&&(k=12);c.push(e(k,f));break;case "H":case "HH":c.push(e(a.getHours(),f));break;case "m":case "mm":c.push(e(a.getMinutes(),f));break;case "s":case "ss":c.push(e(a.getSeconds(),
f));break;case "t":case "tt":k=12>a.getHours()?g.AM?g.AM[0]:" ":g.PM?g.PM[0]:" ";c.push(1===f?k.charAt(0):k);break;case "f":case "ff":case "fff":c.push(e(a.getMilliseconds(),3).substr(0,f));break;case "z":case "zz":k=a.getTimezoneOffset()/60;c.push((0>=k?"+":"-")+e(Math.floor(Math.abs(k)),f));break;case "zzz":k=a.getTimezoneOffset()/60;c.push((0>=k?"+":"-")+e(Math.floor(Math.abs(k)),2)+":"+e(Math.abs(a.getTimezoneOffset()%60),2));break;case "g":case "gg":g.eras&&c.push(g.eras[z(a,j)].name);break;
case "/":c.push(g["/"]);break;default:throw"Invalid date format pattern '"+k+"'.";}}return c.join("")};var D;D=function(a,b,c){var e=c.groupSizes,d=e[0],g=1,f=Math.pow(10,b),i=Math.round(a*f)/f;isFinite(i)||(i=a);f="";f=(i+"").split(/e/i);i=1<f.length?parseInt(f[1],10):0;a=f[0];f=a.split(".");a=f[0];f=1<f.length?f[1]:"";0<i?(f=q(f,i,!1),a+=f.slice(0,i),f=f.substr(i)):0>i&&(i=-i,a=q(a,i+1,!0),f=a.slice(-i,a.length)+f,a=a.slice(0,-i));f=0<b?c["."]+(f.length>b?f.slice(0,b):q(f,b)):"";b=a.length-1;c=
c[","];for(i="";0<=b;){if(0===d||d>b)return a.slice(0,b+1)+(i.length?c+i+f:f);i=a.slice(b-d+1,b+1)+(i.length?c+i:"");b-=d;g<e.length&&(d=e[g],g++)}return a.slice(0,b+1)+c+i+f};l=function(a,b,c){if(!isFinite(a))return Infinity===a?c.numberFormat.positiveInfinity:-Infinity===a?c.numberFormat.negativeInfinity:c.numberFormat.NaN;if(!b||"i"===b)return c.name.length?a.toLocaleString():a.toString();var b=b||"D",c=c.numberFormat,e=Math.abs(a),f=-1;1<b.length&&(f=parseInt(b.slice(1),10));var d=b.charAt(0).toUpperCase(),
i;switch(d){case "D":b="n";e=r(e);-1!==f&&(e=q(""+e,f,!0));0>a&&(e="-"+e);break;case "N":i=c;case "C":i=i||c.currency;case "P":i=i||c.percent;b=0>a?i.pattern[0]:i.pattern[1]||"n";-1===f&&(f=i.decimals);e=D(e*("P"===d?100:1),f,i);break;default:throw"Bad number format specifier: "+d;}a=/n|\$|-|%/g;for(i="";;){f=a.lastIndex;d=a.exec(b);i+=b.slice(f,d?d.index:b.length);if(!d)break;switch(d[0]){case "n":i+=e;break;case "$":i+=c.currency.symbol;break;case "-":/[1-9]/.test(e)&&(i+=c["-"]);break;case "%":i+=
c.percent.symbol}}return i};w=function(){return/\/|dddd|ddd|dd|d|MMMM|MMM|MM|M|yyyy|yy|y|hh|h|HH|H|mm|m|ss|s|tt|t|fff|ff|f|zzz|zz|z|gg|g/g};z=function(a,b){if(!b)return 0;for(var c,e=a.getTime(),i=0,f=b.length;i<f;i++)if(c=b[i].start,null===c||e>=c)return i;return 0};u=function(a,b,c,e){a=a.getFullYear();!e&&b.eras&&(a-=b.eras[c].offset);return a};var E,F,G,H,x,C,A;E=function(a,b){if(100>b){var c=new Date,e=z(c),c=u(c,a,e),e=a.twoDigitYearMax,e="string"===typeof e?(new Date).getFullYear()%100+parseInt(e,
10):e,b=b+(c-c%100);b>e&&(b-=100)}return b};F=function(a,b,e){var i=a.days,f=a._upperDays;f||(a._upperDays=f=[A(i.names),A(i.namesAbbr),A(i.namesShort)]);b=C(b);e?(a=c(f[1],b),-1===a&&(a=c(f[2],b))):a=c(f[0],b);return a};G=function(a,b,e){var i=a.months,f=a.monthsGenitive||a.months,d=a._upperMonths,g=a._upperMonthsGen;d||(a._upperMonths=d=[A(i.names),A(i.namesAbbr)],a._upperMonthsGen=g=[A(f.names),A(f.namesAbbr)]);b=C(b);a=c(e?d[1]:d[0],b);0>a&&(a=c(e?g[1]:g[0],b));return a};H=function(a,b){var c=
a._parseRegExp;if(c){var e=c[b];if(e)return e}else a._parseRegExp=c={};for(var e=n(a,b).replace(/([\^\$\.\*\+\?\|\[\]\(\)\{\}])/g,"\\\\$1"),i=["^"],f=[],d=0,g=0,j=w(),k;null!==(k=j.exec(e));){var o=e.slice(d,k.index),d=j.lastIndex,g=g+s(o,i);if(g%2)i.push(k[0]);else{var o=k[0],m=o.length;switch(o){case "dddd":case "ddd":case "MMMM":case "MMM":case "gg":case "g":o="(\\D+)";break;case "tt":case "t":o="(\\D*)";break;case "yyyy":case "fff":case "ff":case "f":o="(\\d{"+m+"})";break;case "dd":case "d":case "MM":case "M":case "yy":case "y":case "HH":case "H":case "hh":case "h":case "mm":case "m":case "ss":case "s":o=
"(\\d\\d?)";break;case "zzz":o="([+-]?\\d\\d?:\\d{2})";break;case "zz":case "z":o="([+-]?\\d\\d?)";break;case "/":o="(\\/)";break;default:throw"Invalid date format pattern '"+o+"'.";}o&&i.push(o);f.push(k[0])}}s(e.slice(d),i);i.push("$");e={regExp:i.join("").replace(/\s+/g,"\\s+"),groups:f};return c[b]=e};x=function(a,b,c){return a<b||a>c};C=function(a){return a.split("\u00a0").join(" ").toUpperCase()};A=function(a){for(var b=[],c=0,e=a.length;c<e;c++)b[c]=C(a[c]);return b};y=function(a,b,c){var a=
p(a),c=c.calendar,b=H(c,b),e=RegExp(b.regExp).exec(a);if(null===e)return null;var i=b.groups,f=b=a=null,d=null,g=null,j=0,k,o=0,t=0,h=0;k=null;for(var s=!1,r=0,q=i.length;r<q;r++){var n=e[r+1];if(n){var l=i[r],v=l.length,u=parseInt(n,10);switch(l){case "dd":case "d":d=u;if(x(d,1,31))return null;break;case "MMM":case "MMMM":f=G(c,n,3===v);if(x(f,0,11))return null;break;case "M":case "MM":f=u-1;if(x(f,0,11))return null;break;case "y":case "yy":case "yyyy":b=4>v?E(c,u):u;if(x(b,0,9999))return null;break;
case "h":case "hh":j=u;12===j&&(j=0);if(x(j,0,11))return null;break;case "H":case "HH":j=u;if(x(j,0,23))return null;break;case "m":case "mm":o=u;if(x(o,0,59))return null;break;case "s":case "ss":t=u;if(x(t,0,59))return null;break;case "tt":case "t":s=c.PM&&(n===c.PM[0]||n===c.PM[1]||n===c.PM[2]);if(!s&&(!c.AM||n!==c.AM[0]&&n!==c.AM[1]&&n!==c.AM[2]))return null;break;case "f":case "ff":case "fff":h=u*Math.pow(10,3-v);if(x(h,0,999))return null;break;case "ddd":case "dddd":g=F(c,n,3===v);if(x(g,0,6))return null;
break;case "zzz":l=n.split(/:/);if(2!==l.length)return null;k=parseInt(l[0],10);if(x(k,-12,13))return null;l=parseInt(l[1],10);if(x(l,0,59))return null;k=60*k+(m(n,"-")?-l:l);break;case "z":case "zz":k=u;if(x(k,-12,13))return null;k*=60;break;case "g":case "gg":if(!n||!c.eras)return null;n=p(n.toLowerCase());l=0;for(v=c.eras.length;l<v;l++)if(n===c.eras[l].name.toLowerCase()){a=l;break}if(null===a)return null}}}e=new Date;i=(r=c.convert)?r.fromGregorian(e)[0]:e.getFullYear();null===b?b=i:c.eras&&
(b+=c.eras[a||0].offset);null===f&&(f=0);null===d&&(d=1);if(r){if(e=r.toGregorian(b,f,d),null===e)return null}else if(e.setFullYear(b,f,d),e.getDate()!==d||null!==g&&e.getDay()!==g)return null;s&&12>j&&(j+=12);e.setHours(j,o,t,h);null!==k&&(c=e.getMinutes()-(k+e.getTimezoneOffset()),e.setHours(e.getHours()+parseInt(c/60,10),c%60));return e};B=function(a,b,c){var e=b["-"],b=b["+"],f;switch(c){case "n -":e=" "+e,b=" "+b;case "n-":i(a,e)?f=["-",a.substr(0,a.length-e.length)]:i(a,b)&&(f=["+",a.substr(0,
a.length-b.length)]);break;case "- n":e+=" ",b+=" ";case "-n":m(a,e)?f=["-",a.substr(e.length)]:m(a,b)&&(f=["+",a.substr(b.length)]);break;case "(n)":m(a,"(")&&i(a,")")&&(f=["-",a.substr(1,a.length-2)])}return f||["",a]};h.prototype.findClosestCulture=function(a){return h.findClosestCulture.call(this,a)};h.prototype.format=function(a,b,c){return h.format.call(this,a,b,c)};h.prototype.localize=function(a,b){return h.localize.call(this,a,b)};h.prototype.parseInt=function(a,b,c){return h.parseInt.call(this,
a,b,c)};h.prototype.parseFloat=function(a,b,c){return h.parseFloat.call(this,a,b,c)};h.prototype.culture=function(a){return h.culture.call(this,a)};h.addCultureInfo=function(a,b,c){var e={},f=!1;"string"!==typeof a?(c=a,a=this.culture().name,e=this.cultures[a]):"string"!==typeof b?(c=b,f=null==this.cultures[a],e=this.cultures[a]||this.cultures["default"]):(f=!0,e=this.cultures[b]);this.cultures[a]=t(!0,{},e,c);f&&(this.cultures[a].calendar=this.cultures[a].calendars.standard)};h.findClosestCulture=
function(a){var b;if(!a)return this.findClosestCulture(this.cultureSelector)||this.cultures["default"];"string"===typeof a&&(a=a.split(","));if(o(a)){var c,e=this.cultures,f=a,i,d=f.length,g=[];for(i=0;i<d;i++)a=p(f[i]),a=a.split(";"),c=p(a[0]),1===a.length?a=1:(a=p(a[1]),0===a.indexOf("q=")?(a=a.substr(2),a=parseFloat(a),a=isNaN(a)?0:a):a=1),g.push({lang:c,pri:a});g.sort(function(a,b){return a.pri<b.pri?1:a.pri>b.pri?-1:0});for(i=0;i<d;i++)if(c=g[i].lang,b=e[c])return b;for(i=0;i<d;i++){c=g[i].lang;
do{f=c.lastIndexOf("-");if(-1===f)break;c=c.substr(0,f);if(b=e[c])return b}while(1)}for(i=0;i<d;i++){c=g[i].lang;for(var j in e)if(f=e[j],f.language==c)return f}}else if("object"===typeof a)return a;return b||null};h.format=function(a,b,c){c=this.findClosestCulture(c);a instanceof Date?a=v(a,b,c):"number"===typeof a&&(a=l(a,b,c));return a};h.localize=function(a,b){return this.findClosestCulture(b).messages[a]||this.cultures["default"].messages[a]};h.parseDate=function(a,b,c){var c=this.findClosestCulture(c),
e,i;if(b){if("string"===typeof b&&(b=[b]),b.length){i=0;for(var f=b.length;i<f;i++){var d=b[i];if(d&&(e=y(a,d,c)))break}}}else for(i in b=c.calendar.patterns,b)if(e=y(a,b[i],c))break;return e||null};h.parseInt=function(a,b,c){return r(h.parseFloat(a,b,c))};h.parseFloat=function(a,b,c){"number"!==typeof b&&(c=b,b=10);var i=this.findClosestCulture(c),c=NaN,d=i.numberFormat;-1<a.indexOf(i.numberFormat.currency.symbol)&&(a=a.replace(i.numberFormat.currency.symbol,""),a=a.replace(i.numberFormat.currency["."],
i.numberFormat["."]));a=p(a);if(g.test(a))c=parseFloat(a);else if(!b&&f.test(a))c=parseInt(a,16);else{i=B(a,d,d.pattern[0]);b=i[0];i=i[1];""===b&&"(n)"!==d.pattern[0]&&(i=B(a,d,"(n)"),b=i[0],i=i[1]);""===b&&"-n"!==d.pattern[0]&&(i=B(a,d,"-n"),b=i[0],i=i[1]);var b=b||"+",j,a=i.indexOf("e");0>a&&(a=i.indexOf("E"));0>a?(j=i,a=null):(j=i.substr(0,a),a=i.substr(a+1));var k=d["."],o=j.indexOf(k);0>o?(i=j,j=null):(i=j.substr(0,o),j=j.substr(o+k.length));k=d[","];i=i.split(k).join("");o=k.replace(/\u00A0/g,
" ");k!==o&&(i=i.split(o).join(""));b+=i;null!==j&&(b+="."+j);null!==a&&(d=B(a,d,"-n"),b+="e"+(d[0]||"+")+d[1]);e.test(b)&&(c=parseFloat(b))}return c};h.culture=function(a){"undefined"!==typeof a&&(this.cultureSelector=a);return this.findClosestCulture(a)||this.cultures["default"]}})(this);
"JSON"in window&&window.JSON||(this.JSON||(this.JSON={}),function(){function a(a){return a<10?"0"+a:a}function d(a){g.lastIndex=0;return g.test(a)?'"'+a.replace(g,function(a){var b=c[a];return typeof b==="string"?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function h(a,c){var f,g,m,p,r=e,q,s=c[a];s&&(typeof s==="object"&&typeof s.toJSON==="function")&&(s=s.toJSON(a));typeof i==="function"&&(s=i.call(c,a,s));switch(typeof s){case "string":return d(s);case "number":return isFinite(s)?
String(s):"null";case "boolean":case "null":return String(s);case "object":if(!s)return"null";e=e+b;q=[];if(Object.prototype.toString.apply(s)==="[object Array]"){p=s.length;for(f=0;f<p;f=f+1)q[f]=h(f,s)||"null";m=q.length===0?"[]":e?"[\n"+e+q.join(",\n"+e)+"\n"+r+"]":"["+q.join(",")+"]";e=r;return m}if(i&&typeof i==="object"){p=i.length;for(f=0;f<p;f=f+1){g=i[f];if(typeof g==="string")(m=h(g,s))&&q.push(d(g)+(e?": ":":")+m)}}else for(g in s)if(Object.hasOwnProperty.call(s,g))(m=h(g,s))&&q.push(d(g)+
(e?": ":":")+m);m=q.length===0?"{}":e?"{\n"+e+q.join(",\n"+e)+"\n"+r+"}":"{"+q.join(",")+"}";e=r;return m}}if(typeof Date.prototype.toJSON!=="function"){Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null};String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()}}var f=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
g=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,e,b,c={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},i;if(typeof JSON.stringify!=="function")JSON.stringify=function(a,c,f){var d;b=e="";if(typeof f==="number")for(d=0;d<f;d=d+1)b=b+" ";else typeof f==="string"&&(b=f);if((i=c)&&typeof c!=="function"&&(typeof c!=="object"||typeof c.length!=="number"))throw Error("JSON.stringify");return h("",{"":a})};
if(typeof JSON.parse!=="function")JSON.parse=function(a,b){function c(a,e){var i,f,d=a[e];if(d&&typeof d==="object")for(i in d)if(Object.hasOwnProperty.call(d,i)){f=c(d,i);f!==void 0?d[i]=f:delete d[i]}return b.call(a,e,d)}var e,a=String(a);f.lastIndex=0;f.test(a)&&(a=a.replace(f,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){e=eval("("+a+")");return typeof b==="function"?c({"":e},""):e}throw new SyntaxError("JSON.parse");}}());
(function(a){a.factory=function(d,h){if(a.fn[d])throw"$.fn."+d+" plugin already exists";if(a[d])throw"$."+d+" class already exists";a.fn[d]=function(f){var g=null,e=null;if(a.type(f)==="string"){g=f;e=Array.prototype.slice.call(arguments,1)}return this.each(function(){var b=a(this),c=b.data("$."+d);if(g)c&&a.type(c[g])==="function"?c[g].apply(c,e):console.warn(d,"Unable to invoke method",g);else{c&&c._destroy();c=new a[d](b,f);b.data("$."+d,c)}})};a[d]=function(f,g){this.options=a.extend(true,{},
a[d].defaults,g);this.element=f;this.init()};a.extend(a[d].prototype,{init:function(){},_destroy:function(){}},h);return a[d]}})(jQuery);
(function(){var a={};$.extend({localstore:function(d,h,f,g){var e=document.location.hostname,b=document.location.protocol;if(typeof h!=="undefined"){var c=JSON.stringify(h);if(!f&&window.globalStorage)h===null?delete window.globalStorage[e][b+d]:window.globalStorage[e][b+d]=c;else if(!f&&window.localStorage&&window.localStorage.setItem)h===null?window.localStorage.removeItem(b+d):window.localStorage.setItem(b+d,c);else if(f!==false){f={};f.domain=fb.get_cookie_domain();h===null?$.cookie(d,null,f):
$.cookie(d,c,$.extend(f,g||{expires:14,path:"/"}))}else h===null?delete a[d]:a[d]=c;return h}if(!f&&window.globalStorage){if(window.globalStorage[e][b+d])h=window.globalStorage[e][b+d].value}else h=!f&&window.localStorage?window.localStorage.getItem(b+d):f!==false?$.cookie(d):a[d];return h!=""&&h!==null&&h!==void 0?JSON.parse(h,null):null}})})();
(function(a){a.extend({metadata:{defaults:{type:"class",name:"metadata",cre:/({.*})/,single:"metadata"},setType:function(a,h){this.defaults.type=a;this.defaults.name=h},get:function(d,h){var f=a.extend({},this.defaults,h);if(!f.single.length)f.single="metadata";var g=a.data(d,f.single);if(g)return g;var g="{}",e=function(a){if(typeof a!="string")return a;return a=eval("("+a+")")};if(f.type=="html5"){var b={};a(d.attributes).each(function(){var a=this.nodeName;if(a.match(/^data-/))a=a.replace(/^data-/,
"");else return true;b[a]=e(this.nodeValue)})}else{if(f.type=="class"){var c=f.cre.exec(d.className);c&&(g=c[1])}else if(f.type=="elem"){if(!d.getElementsByTagName)return;c=d.getElementsByTagName(f.name);c.length&&(g=a.trim(c[0].innerHTML))}else if(d.getAttribute!=void 0)(c=d.getAttribute(f.name))&&(g=c);b=e(g.indexOf("{")<0?"{"+g+"}":g)}a.data(d,f.single,b);return b}}});a.fn.metadata=function(d){return a.metadata.get(this[0],d)}})(jQuery);
(function(a,d){function h(f){return!a(f).parents().andSelf().filter(function(){return a.curCSS(this,"visibility")==="hidden"||a.expr.filters.hidden(this)}).length}a.ui=a.ui||{};if(!a.ui.version){a.extend(a.ui,{version:"1.8.10",keyCode:{ALT:18,BACKSPACE:8,CAPS_LOCK:20,COMMA:188,COMMAND:91,COMMAND_LEFT:91,COMMAND_RIGHT:93,CONTROL:17,DELETE:46,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,INSERT:45,LEFT:37,MENU:93,NUMPAD_ADD:107,NUMPAD_DECIMAL:110,NUMPAD_DIVIDE:111,NUMPAD_ENTER:108,NUMPAD_MULTIPLY:106,NUMPAD_SUBTRACT:109,
PAGE_DOWN:34,PAGE_UP:33,PERIOD:190,RIGHT:39,SHIFT:16,SPACE:32,TAB:9,UP:38,WINDOWS:91}});a.fn.extend({_focus:a.fn.focus,focus:function(f,d){return typeof f==="number"?this.each(function(){var e=this;setTimeout(function(){a(e).focus();d&&d.call(e)},f)}):this._focus.apply(this,arguments)},scrollParent:function(){var f;f=a.browser.msie&&/(static|relative)/.test(this.css("position"))||/absolute/.test(this.css("position"))?this.parents().filter(function(){return/(relative|absolute|fixed)/.test(a.curCSS(this,
"position",1))&&/(auto|scroll)/.test(a.curCSS(this,"overflow",1)+a.curCSS(this,"overflow-y",1)+a.curCSS(this,"overflow-x",1))}).eq(0):this.parents().filter(function(){return/(auto|scroll)/.test(a.curCSS(this,"overflow",1)+a.curCSS(this,"overflow-y",1)+a.curCSS(this,"overflow-x",1))}).eq(0);return/fixed/.test(this.css("position"))||!f.length?a(document):f},zIndex:function(f){if(f!==d)return this.css("zIndex",f);if(this.length)for(var f=a(this[0]),g;f.length&&f[0]!==document;){g=f.css("position");if(g===
"absolute"||g==="relative"||g==="fixed"){g=parseInt(f.css("zIndex"),10);if(!isNaN(g)&&g!==0)return g}f=f.parent()}return 0},disableSelection:function(){return this.bind((a.support.selectstart?"selectstart":"mousedown")+".ui-disableSelection",function(a){a.preventDefault()})},enableSelection:function(){return this.unbind(".ui-disableSelection")}});a.each(["Width","Height"],function(f,g){function e(c,e,i,f){a.each(b,function(){e=e-(parseFloat(a.curCSS(c,"padding"+this,true))||0);i&&(e=e-(parseFloat(a.curCSS(c,
"border"+this+"Width",true))||0));f&&(e=e-(parseFloat(a.curCSS(c,"margin"+this,true))||0))});return e}var b=g==="Width"?["Left","Right"]:["Top","Bottom"],c=g.toLowerCase(),i={innerWidth:a.fn.innerWidth,innerHeight:a.fn.innerHeight,outerWidth:a.fn.outerWidth,outerHeight:a.fn.outerHeight};a.fn["inner"+g]=function(b){return b===d?i["inner"+g].call(this):this.each(function(){a(this).css(c,e(this,b)+"px")})};a.fn["outer"+g]=function(b,f){return typeof b!=="number"?i["outer"+g].call(this,b):this.each(function(){a(this).css(c,
e(this,b,true,f)+"px")})}});a.extend(a.expr[":"],{data:function(f,d,e){return!!a.data(f,e[3])},focusable:function(f){var d=f.nodeName.toLowerCase(),e=a.attr(f,"tabindex");if("area"===d){d=f.parentNode;e=d.name;if(!f.href||!e||d.nodeName.toLowerCase()!=="map")return false;f=a("img[usemap=#"+e+"]")[0];return!!f&&h(f)}return(/input|select|textarea|button|object/.test(d)?!f.disabled:"a"==d?f.href||!isNaN(e):!isNaN(e))&&h(f)},tabbable:function(f){var d=a.attr(f,"tabindex");return(isNaN(d)||d>=0)&&a(f).is(":focusable")}});
a(function(){var f=document.body,d=f.appendChild(d=document.createElement("div"));a.extend(d.style,{minHeight:"100px",height:"auto",padding:0,borderWidth:0});a.support.minHeight=d.offsetHeight===100;a.support.selectstart="onselectstart"in d;f.removeChild(d).style.display="none"});a.extend(a.ui,{plugin:{add:function(f,d,e){var f=a.ui[f].prototype,b;for(b in e){f.plugins[b]=f.plugins[b]||[];f.plugins[b].push([d,e[b]])}},call:function(a,d,e){if((d=a.plugins[d])&&a.element[0].parentNode)for(var b=0;b<
d.length;b++)a.options[d[b][0]]&&d[b][1].apply(a.element,e)}},contains:function(a,d){return document.compareDocumentPosition?a.compareDocumentPosition(d)&16:a!==d&&a.contains(d)},hasScroll:function(d,g){if(a(d).css("overflow")==="hidden")return false;var e=g&&g==="left"?"scrollLeft":"scrollTop",b=false;if(d[e]>0)return true;d[e]=1;b=d[e]>0;d[e]=0;return b},isOverAxis:function(a,d,e){return a>d&&a<d+e},isOver:function(d,g,e,b,c,i){return a.ui.isOverAxis(d,e,c)&&a.ui.isOverAxis(g,b,i)}})}})(jQuery);
(function(a,d){if(a.cleanData){var h=a.cleanData;a.cleanData=function(d){for(var e=0,b;(b=d[e])!=null;e++)a(b).triggerHandler("remove");h(d)}}else{var f=a.fn.remove;a.fn.remove=function(d,e){return this.each(function(){e||(!d||a.filter(d,[this]).length)&&a("*",this).add([this]).each(function(){a(this).triggerHandler("remove")});return f.call(a(this),d,e)})}}a.widget=function(d,e,b){var c=d.split(".")[0],i,d=d.split(".")[1];i=c+"-"+d;if(!b){b=e;e=a.Widget}a.expr[":"][i]=function(b){return!!a.data(b,
d)};a[c]=a[c]||{};a[c][d]=function(a,b){arguments.length&&this._createWidget(a,b)};e=new e;e.options=a.extend(true,{},e.options);a[c][d].prototype=a.extend(true,e,{namespace:c,widgetName:d,widgetEventPrefix:a[c][d].prototype.widgetEventPrefix||d,widgetBaseClass:i},b);a.widget.bridge(d,a[c][d])};a.widget.bridge=function(f,e){a.fn[f]=function(b){var c=typeof b==="string",i=Array.prototype.slice.call(arguments,1),h=this,b=!c&&i.length?a.extend.apply(null,[true,b].concat(i)):b;if(c&&b.charAt(0)==="_")return h;
c?this.each(function(){var c=a.data(this,f),e=c&&a.isFunction(c[b])?c[b].apply(c,i):c;if(e!==c&&e!==d){h=e;return false}}):this.each(function(){var c=a.data(this,f);c?c.option(b||{})._init():a.data(this,f,new e(b,this))});return h}};a.Widget=function(a,e){arguments.length&&this._createWidget(a,e)};a.Widget.prototype={widgetName:"widget",widgetEventPrefix:"",options:{disabled:false},_createWidget:function(d,e){a.data(e,this.widgetName,this);this.element=a(e);this.options=a.extend(true,{},this.options,
this._getCreateOptions(),d);var b=this;this.element.bind("remove."+this.widgetName,function(){b.destroy()});this._create();this._trigger("create");this._init()},_getCreateOptions:function(){return a.metadata&&a.metadata.get(this.element[0])[this.widgetName]},_create:function(){},_init:function(){},destroy:function(){this.element.unbind("."+this.widgetName).removeData(this.widgetName);this.widget().unbind("."+this.widgetName).removeAttr("aria-disabled").removeClass(this.widgetBaseClass+"-disabled ui-state-disabled")},
widget:function(){return this.element},option:function(f,e){var b=f;if(arguments.length===0)return a.extend({},this.options);if(typeof f==="string"){if(e===d)return this.options[f];b={};b[f]=e}this._setOptions(b);return this},_setOptions:function(d){var e=this;a.each(d,function(a,c){e._setOption(a,c)});return this},_setOption:function(a,e){this.options[a]=e;a==="disabled"&&this.widget()[e?"addClass":"removeClass"](this.widgetBaseClass+"-disabled ui-state-disabled").attr("aria-disabled",e);return this},
enable:function(){return this._setOption("disabled",false)},disable:function(){return this._setOption("disabled",true)},_trigger:function(d,e,b){var c=this.options[d],e=a.Event(e);e.type=(d===this.widgetEventPrefix?d:this.widgetEventPrefix+d).toLowerCase();b=b||{};if(e.originalEvent)for(var d=a.event.props.length,i;d;){i=a.event.props[--d];e[i]=e.originalEvent[i]}this.element.trigger(e,b);return!(a.isFunction(c)&&c.call(this.element[0],e,b)===false||e.isDefaultPrevented())}}})(jQuery);
(function(a){a.widget("ui.mouse",{options:{cancel:":input,option",distance:1,delay:0},_mouseInit:function(){var d=this;this.element.bind("mousedown."+this.widgetName,function(a){return d._mouseDown(a)}).bind("click."+this.widgetName,function(h){if(true===a.data(h.target,d.widgetName+".preventClickEvent")){a.removeData(h.target,d.widgetName+".preventClickEvent");h.stopImmediatePropagation();return false}});this.started=false},_mouseDestroy:function(){this.element.unbind("."+this.widgetName)},_mouseDown:function(d){d.originalEvent=
d.originalEvent||{};if(!d.originalEvent.mouseHandled){this._mouseStarted&&this._mouseUp(d);this._mouseDownEvent=d;var h=this,f=d.which==1,g=typeof this.options.cancel=="string"?a(d.target).parents().add(d.target).filter(this.options.cancel).length:false;if(!f||g||!this._mouseCapture(d))return true;this.mouseDelayMet=!this.options.delay;if(!this.mouseDelayMet)this._mouseDelayTimer=setTimeout(function(){h.mouseDelayMet=true},this.options.delay);if(this._mouseDistanceMet(d)&&this._mouseDelayMet(d)){this._mouseStarted=
this._mouseStart(d)!==false;if(!this._mouseStarted){d.preventDefault();return true}}this._mouseMoveDelegate=function(a){return h._mouseMove(a)};this._mouseUpDelegate=function(a){return h._mouseUp(a)};a(document).bind("mousemove."+this.widgetName,this._mouseMoveDelegate).bind("mouseup."+this.widgetName,this._mouseUpDelegate);d.preventDefault();return d.originalEvent.mouseHandled=true}},_mouseMove:function(d){if(a.browser.msie&&!(document.documentMode>=9)&&!d.button)return this._mouseUp(d);if(this._mouseStarted){this._mouseDrag(d);
return d.preventDefault()}if(this._mouseDistanceMet(d)&&this._mouseDelayMet(d))(this._mouseStarted=this._mouseStart(this._mouseDownEvent,d)!==false)?this._mouseDrag(d):this._mouseUp(d);return!this._mouseStarted},_mouseUp:function(d){a(document).unbind("mousemove."+this.widgetName,this._mouseMoveDelegate).unbind("mouseup."+this.widgetName,this._mouseUpDelegate);if(this._mouseStarted){this._mouseStarted=false;d.target==this._mouseDownEvent.target&&a.data(d.target,this.widgetName+".preventClickEvent",
true);this._mouseStop(d)}return false},_mouseDistanceMet:function(a){return Math.max(Math.abs(this._mouseDownEvent.pageX-a.pageX),Math.abs(this._mouseDownEvent.pageY-a.pageY))>=this.options.distance},_mouseDelayMet:function(){return this.mouseDelayMet},_mouseStart:function(){},_mouseDrag:function(){},_mouseStop:function(){},_mouseCapture:function(){return true}})})(jQuery);
(function(a){a.ui=a.ui||{};var d=/left|center|right/,h=/top|center|bottom/,f=a.fn.position,g=a.fn.offset;a.fn.position=function(e){if(!e||!e.of)return f.apply(this,arguments);var e=a.extend({},e),b=a(e.of),c=b[0],i=(e.collision||"flip").split(" "),g=e.offset?e.offset.split(" "):[0,0],o,k,j;if(c.nodeType===9){o=b.width();k=b.height();j={top:0,left:0}}else if(c.setTimeout){o=b.width();k=b.height();j={top:b.scrollTop(),left:b.scrollLeft()}}else if(c.preventDefault){e.at="left top";o=k=0;j={top:e.of.pageY,
left:e.of.pageX}}else{o=b.outerWidth();k=b.outerHeight();j=b.offset()}a.each(["my","at"],function(){var a=(e[this]||"").split(" ");a.length===1&&(a=d.test(a[0])?a.concat(["center"]):h.test(a[0])?["center"].concat(a):["center","center"]);a[0]=d.test(a[0])?a[0]:"center";a[1]=h.test(a[1])?a[1]:"center";e[this]=a});i.length===1&&(i[1]=i[0]);g[0]=parseInt(g[0],10)||0;g.length===1&&(g[1]=g[0]);g[1]=parseInt(g[1],10)||0;if(e.at[0]==="right")j.left=j.left+o;else if(e.at[0]==="center")j.left=j.left+o/2;if(e.at[1]===
"bottom")j.top=j.top+k;else if(e.at[1]==="center")j.top=j.top+k/2;j.left=j.left+g[0];j.top=j.top+g[1];return this.each(function(){var b=a(this),c=b.outerWidth(),d=b.outerHeight(),f=parseInt(a.curCSS(this,"marginLeft",true))||0,h=parseInt(a.curCSS(this,"marginTop",true))||0,n=c+f+(parseInt(a.curCSS(this,"marginRight",true))||0),v=d+h+(parseInt(a.curCSS(this,"marginBottom",true))||0),l=a.extend({},j),w;if(e.my[0]==="right")l.left=l.left-c;else if(e.my[0]==="center")l.left=l.left-c/2;if(e.my[1]==="bottom")l.top=
l.top-d;else if(e.my[1]==="center")l.top=l.top-d/2;l.left=Math.round(l.left);l.top=Math.round(l.top);w={left:l.left-f,top:l.top-h};a.each(["left","top"],function(b,f){if(a.ui.position[i[b]])a.ui.position[i[b]][f](l,{targetWidth:o,targetHeight:k,elemWidth:c,elemHeight:d,collisionPosition:w,collisionWidth:n,collisionHeight:v,offset:g,my:e.my,at:e.at})});a.fn.bgiframe&&b.bgiframe();b.offset(a.extend(l,{using:e.using}))})};a.ui.position={fit:{left:function(e,b){var c=a(window),c=b.collisionPosition.left+
b.collisionWidth-c.width()-c.scrollLeft();e.left=c>0?e.left-c:Math.max(e.left-b.collisionPosition.left,e.left)},top:function(e,b){var c=a(window),c=b.collisionPosition.top+b.collisionHeight-c.height()-c.scrollTop();e.top=c>0?e.top-c:Math.max(e.top-b.collisionPosition.top,e.top)}},flip:{left:function(e,b){if(b.at[0]!=="center"){var c=a(window),c=b.collisionPosition.left+b.collisionWidth-c.width()-c.scrollLeft(),d=b.my[0]==="left"?-b.elemWidth:b.my[0]==="right"?b.elemWidth:0,f=b.at[0]==="left"?b.targetWidth:
-b.targetWidth,g=-2*b.offset[0];e.left=e.left+(b.collisionPosition.left<0?d+f+g:c>0?d+f+g:0)}},top:function(e,b){if(b.at[1]!=="center"){var c=a(window),c=b.collisionPosition.top+b.collisionHeight-c.height()-c.scrollTop(),d=b.my[1]==="top"?-b.elemHeight:b.my[1]==="bottom"?b.elemHeight:0,f=b.at[1]==="top"?b.targetHeight:-b.targetHeight,g=-2*b.offset[1];e.top=e.top+(b.collisionPosition.top<0?d+f+g:c>0?d+f+g:0)}}}};if(!a.offset.setOffset){a.offset.setOffset=function(e,b){if(/static/.test(a.curCSS(e,"position")))e.style.position=
"relative";var c=a(e),d=c.offset(),f=parseInt(a.curCSS(e,"top",true),10)||0,g=parseInt(a.curCSS(e,"left",true),10)||0,d={top:b.top-d.top+f,left:b.left-d.left+g};"using"in b?b.using.call(e,d):c.css(d)};a.fn.offset=function(e){var b=this[0];return!b||!b.ownerDocument?null:e?this.each(function(){a.offset.setOffset(this,e)}):g.call(this)}}})(jQuery);
(function(a,d){if(!("console"in window)){var h=window.console={};h.log=h.warn=h.error=h.debug=function(){}}a(function(){var b=a("<div>");a(document.body).append(b);var c=setTimeout(function(){if(a.cleanData){var b=a.cleanData;a.cleanData=function(c){for(var e=0,d;(d=c[e])!=null;e++)a(d).triggerHandler("remove");b(c)}}else{var c=a.fn.remove;a.fn.remove=function(b,e){return this.each(function(){e||(!b||a.filter(b,[this]).length)&&a("*",this).add([this]).each(function(){a(this).triggerHandler("remove")});
return c.call(a(this),b,e)})}}},1);b.bind("remove",function(){clearTimeout(c)});b.remove()});var f={key:1,filter:1,spell:1,exact:1,lang:1,scoring:1,prefixed:1,stemmed:1,format:1,mql_output:1,output:1};a.suggest=function(b,c){a.fn[b]=function(c){this.length||console.warn("Suggest: invoked on empty element set");return this.each(function(){this.nodeName&&(this.nodeName.toUpperCase()==="INPUT"?this.type&&this.type.toUpperCase()!=="TEXT"&&console.warn("Suggest: unsupported INPUT type: "+this.type):console.warn("Suggest: unsupported DOM element: "+
this.nodeName));var e=a.data(this,b);e&&e._destroy();a.data(this,b,new a.suggest[b](this,c))._init()})};a.suggest[b]=function(c,e){var d=this,g=this.options=a.extend(true,{},a.suggest.defaults,a.suggest[b].defaults,e),j=g.css_prefix=g.css_prefix||"",h=g.css;this.name=b;a.each(h,function(a){h[a]=j+h[a]});g.ac_param={};a.each(f,function(a){var b=g[a];b===null||b===""||(g.ac_param[a]=b)});g.flyout_lang=null;if(g.ac_param.lang){var p=g.ac_param.lang;a.isArray(p)&&p.length&&(p=p.join(","));if(p)g.flyout_lang=
p}this._status={START:"",LOADING:"",SELECT:"",ERROR:""};if(g.status&&g.status instanceof Array&&g.status.length>=3){this._status.START=g.status[0]||"";this._status.LOADING=g.status[1]||"";this._status.SELECT=g.status[2]||"";if(g.status.length===4)this._status.ERROR=g.status[3]||""}var p=this.status=a('<div style="display:none;">').addClass(h.status),r=this.list=a("<ul>").addClass(h.list),q=this.pane=a('<div style="display:none;" class="fbs-reset">').addClass(h.pane);q.append(p).append(r);if(g.parent)a(g.parent).append(q);
else{q.css("position","absolute");g.zIndex&&q.css("z-index",g.zIndex);a(document.body).append(q)}q.bind("mousedown",function(a){d.input.data("dont_hide",true);a.stopPropagation()}).bind("mouseup",function(a){d.input.data("dont_hide")&&d.input.focus();d.input.removeData("dont_hide");a.stopPropagation()}).bind("click",function(a){a.stopPropagation();if(a=d.get_selected()){d.onselect(a,true);d.hide_all()}});r.hover(function(a){d.hoverover_list(a)},function(a){d.hoverout_list(a)});this.input=a(c).attr("autocomplete",
"off").unbind(".suggest").bind("remove.suggest",function(){d._destroy()}).bind("keydown.suggest",function(a){d.keydown(a)}).bind("keypress.suggest",function(a){d.keypress(a)}).bind("keyup.suggest",function(a){d.keyup(a)}).bind("blur.suggest",function(a){d.blur(a)}).bind("textchange.suggest",function(){d.textchange()}).bind("focus.suggest",function(a){d.focus(a)}).bind("paste.suggest input.suggest",function(){clearTimeout(d.paste_timeout);d.paste_timeout=setTimeout(function(){d.textchange()},0)});
this.onresize=function(){d.invalidate_position();if(q.is(":visible")){d.position();if(g.flyout&&d.flyoutpane&&d.flyoutpane.is(":visible")){var a=d.get_selected();a&&d.flyout_position(a)}}};a(window).bind("resize.suggest",this.onresize).bind("scroll.suggest",this.onresize)};a.suggest[b].prototype=a.extend({},a.suggest.prototype,c)};a.suggest.prototype={_init:function(){},_destroy:function(){this.pane.remove();this.list.remove();this.input.unbind(".suggest");a(window).unbind("resize.suggest",this.onresize).unbind("scroll.suggest",
this.onresize);this.input.removeData("data.suggest")},invalidate_position:function(){self._position=null},status_start:function(){this.hide_all();this.status.siblings().hide();if(this._status.START){this.status.text(this._status.START).show();if(!this.pane.is(":visible")){this.position();this.pane_show()}}this._status.LOADING&&this.status.removeClass("loading")},status_loading:function(){this.status.siblings().show();if(this._status.LOADING){this.status.addClass("loading").text(this._status.LOADING).show();
if(!this.pane.is(":visible")){this.position();this.pane_show()}}else this.status.hide()},status_select:function(){this.status.siblings().show();this._status.SELECT?this.status.text(this._status.SELECT).show():this.status.hide();this._status.LOADING&&this.status.removeClass("loading")},status_error:function(){this.status.siblings().show();this._status.ERROR?this.status.text(this._status.ERROR).show():this.status.hide();this._status.LOADING&&this.status.removeClass("loading")},focus:function(a){this.input.val()===
""?this.status_start():this.focus_hook(a)},focus_hook:function(){if(!this.input.data("data.suggest")&&!this.pane.is(":visible")&&a("."+this.options.css.item,this.list).length){this.position();this.pane_show()}},keydown:function(a){var c=a.keyCode;if(c===9)this.tab(a);else if(c===38||c===40)a.shiftKey||a.preventDefault()},keypress:function(a){var c=a.keyCode;c===38||c===40?a.shiftKey||a.preventDefault():c===13&&this.enter(a)},keyup:function(b){var c=b.keyCode;if(c===38){b.preventDefault();this.up(b)}else if(c===
40){b.preventDefault();this.down(b)}else if(b.ctrlKey&&c===77)a(".fbs-more-link",this.pane).click();else if(a.suggest.is_char(b)){clearTimeout(this.keypress.timeout);var e=this;this.keypress.timeout=setTimeout(function(){e.textchange()},0)}else c===27&&this.escape(b);return true},blur:function(){if(!this.input.data("dont_hide")){this.input.data("data.suggest");this.hide_all()}},tab:function(b){if(!b.shiftKey&&!b.metaKey&&!b.ctrlKey){var b=this.options,b=this.pane.is(":visible")&&a("."+b.css.item,
this.list).length,c=this.get_selected();if(b&&c){this.onselect(c);this.hide_all()}}},enter:function(b){var c=this.options;if(this.pane.is(":visible")){if(b.shiftKey){this.shift_enter(b);b.preventDefault();return}if(a("."+c.css.item,this.list).length){var e=this.get_selected();if(e){this.onselect(e);this.hide_all();b.preventDefault();return}if(!c.soft){this.input.data("data.suggest");if(a("."+this.options.css.item+":visible",this.list).length){this.updown(false);b.preventDefault();return}}}}c.soft?
this.soft_enter():b.preventDefault()},soft_enter:function(){},shift_enter:function(){},escape:function(){this.hide_all()},up:function(a){this.updown(true,a.ctrlKey||a.shiftKey)},down:function(a){this.updown(false,null,a.ctrlKey||a.shiftKey)},updown:function(b,c,e){var d=this.options.css,f=this.list;if(this.pane.is(":visible")){var g=a("."+d.item+":visible",f);if(g.length){var f=a(g[0]),g=a(g[g.length-1]),j=this.get_selected()||[];clearTimeout(this.ignore_mouseover.timeout);this._ignore_mouseover=
false;if(b)if(c)this._goto(f);else if(j.length)if(j[0]==f[0]){f.removeClass(d.selected);this.input.val(this.input.data("original.suggest"));this.hoverout_list()}else{b=j.prevAll("."+d.item+":visible:first");this._goto(b)}else this._goto(g);else if(e)this._goto(g);else if(j.length)if(j[0]==g[0]){g.removeClass(d.selected);this.input.val(this.input.data("original.suggest"));this.hoverout_list()}else{b=j.nextAll("."+d.item+":visible:first");this._goto(b)}else this._goto(f)}}else b||this.textchange()},
_goto:function(a){a.trigger("mouseover.suggest");var c=a.data("data.suggest");this.input.val(c?c.name:this.input.data("original.suggest"));this.scroll_to(a)},scroll_to:function(a){var c=this.list,e=c.scrollTop(),d=e+c.innerHeight(),f=a.outerHeight(),a=a.prevAll().length*f,f=a+f;if(a<e){this.ignore_mouseover();c.scrollTop(a)}else if(f>d){this.ignore_mouseover();c.scrollTop(e+f-d)}},textchange:function(){this.input.removeData("data.suggest");this.input.trigger("fb-textchange",this);var a=this.input.val();
if(a==="")this.status_start();else{this.status_loading();this.request(a)}},request:function(){},response:function(b){if(b){"cost"in b&&this.trackEvent(this.name,"response","cost",b.cost);if(this.check_response(b)){var c=[];if(a.isArray(b))c=b;else if("result"in b)c=b.result;var e=a.map(arguments,function(a){return a});this.response_hook.apply(this,e);var d=null,f=this,g=this.options;a.each(c,function(a,c){if(!c.id&&c.mid)c.id=c.mid;var e=f.create_item(c,b).bind("mouseover.suggest",function(a){f.mouseover_item(a)});
e.data("data.suggest",c);f.list.append(e);a===0&&(d=e)});this.input.data("original.suggest",this.input.val());if(a("."+g.css.item,this.list).length===0&&g.nomatch){c=a('<li class="fbs-nomatch">');if(typeof g.nomatch==="string")c.text(g.nomatch);else{g.nomatch.title&&c.append(a('<em class="fbs-nomatch-text">').text(g.nomatch.title));g.nomatch.heading&&c.append(a("<h3>").text(g.nomatch.heading));if((g=g.nomatch.tips)&&g.length){var j=a('<ul class="fbs-search-tips">');a.each(g,function(b,c){j.append(a("<li>").text(c))});
c.append(j)}}c.bind("click.suggest",function(a){a.stopPropagation()});this.list.append(c)}e.push(d);this.show_hook.apply(this,e);this.position();this.pane_show()}}},pane_show:function(){var b=false;a("> li",this.list).length&&(b=true);b||this.pane.children(":not(."+this.options.css.list+")").each(function(){if(a(this).css("display")!="none"){b=true;return false}});if(b)if(this.options.animate){var c=this;this.pane.slideDown("fast",function(){c.input.trigger("fb-pane-show",c)})}else{this.pane.show();
this.input.trigger("fb-pane-show",this)}else{this.pane.hide();this.input.trigger("fb-pane-hide",this)}},create_item:function(b){var c=this.options.css,e=a("<li>").addClass(c.item),b=a("<label>").text(b.name);e.append(a("<div>").addClass(c.item_name).append(b));return e},mouseover_item:function(b){if(!this._ignore_mouseover){b=b.target;b.nodeName.toLowerCase()!=="li"&&(b=a(b).parents("li:first"));var c=a(b),e=this.options.css;a("."+e.item,this.list).each(function(){this!==c[0]&&a(this).removeClass(e.selected)});
if(!c.hasClass(e.selected)){c.addClass(e.selected);this.mouseover_item_hook(c)}}},mouseover_item_hook:function(){},hoverover_list:function(){},hoverout_list:function(){},check_response:function(){return true},response_hook:function(){this.list.empty()},show_hook:function(){this.status_select()},position:function(){var b=this.pane,c=this.options;if(!c.parent){if(!self._position){var e=this.input,d=e.offset(),f=e.outerWidth(true),g=e.outerHeight(true);d.top=d.top+g;var j=b.outerWidth(),h=b.outerHeight(),
p=d.top+h/2,r=a(window).scrollLeft(),e=a(window).scrollTop(),q=a(window).width(),s=a(window).height()+e,n=true;"left"==c.align?n=true:"right"==c.align?n=false:d.left>r+q/2&&(n=false);if(!n){n=d.left-(j-f);if(n>r)d.left=n}if(p>s){c=d.top-g-h;if(c>e)d.top=c}this._position=d}b.css({top:this._position.top,left:this._position.left})}},ignore_mouseover:function(){this._ignore_mouseover=true;var a=this;this.ignore_mouseover.timeout=setTimeout(function(){a.ignore_mouseover_reset()},1E3)},ignore_mouseover_reset:function(){this._ignore_mouseover=
false},get_selected:function(){var b=null,c=this.options.css.selected;a("li",this.list).each(function(){var e=a(this);if(e.hasClass(c)&&e.is(":visible")){b=e;return false}});return b},onselect:function(a){var c=a.data("data.suggest");if(c){this.input.val(c.name).data("data.suggest",c).trigger("fb-select",c);this.trackEvent(this.name,"fb-select","index",a.prevAll().length)}},trackEvent:function(a,c,e,d){this.input.trigger("fb-track-event",{category:a,action:c,label:e,value:d})},hide_all:function(){this.pane.hide();
this.input.trigger("fb-pane-hide",this)}};a.extend(a.suggest,{defaults:{status:["Start typing to get suggestions...","Searching...","Select an item from the list:","Sorry, something went wrong. Please try again later"],soft:false,nomatch:"no matches",css:{pane:"fbs-pane",list:"fbs-list",item:"fbs-item",item_name:"fbs-item-name",selected:"fbs-selected",status:"fbs-status"},css_prefix:null,parent:null,animate:false,zIndex:null},strongify:function(b,c){var e,d=b.toLowerCase().indexOf(c.toLowerCase());
if(d>=0){var f=c.length;e=document.createTextNode(b.substring(0,d));var g=a("<strong>").text(b.substring(d,d+f)),d=document.createTextNode(b.substring(d+f));e=a("<div>").append(e).append(g).append(d)}else e=a("<div>").text(b);return e},keyCode:{CAPS_LOCK:20,CONTROL:17,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,INSERT:45,LEFT:37,NUMPAD_ENTER:108,PAGE_DOWN:34,PAGE_UP:33,RIGHT:39,SHIFT:16,SPACE:32,TAB:9,UP:38,OPTION:18,APPLE:224},is_char:function(b){if(b.type==="keypress"){if((b.metaKey||b.ctrlKey)&&
b.charCode===118)return true;if("isChar"in b)return b.isChar}else{var c=a.suggest.keyCode.not_char;if(!c){c={};a.each(a.suggest.keyCode,function(a,b){c[""+b]=1});a.suggest.keyCode.not_char=c}return!(""+b.keyCode in c)}},parse_input:function(b){for(var c=/(\S+)\:(?:\"([^\"]+)\"|(\S+))/g,e=b,d=[],g={},h=c.exec(b);h;){h[1]in f?g[h[1]]=a.isEmptyObject(h[2])?h[3]:h[2]:d.push(h[0]);e=e.replace(h[0],"");h=c.exec(b)}e=a.trim(e.replace(/\s+/g," "));return[e,d,g]},mqlkey_fast:/^[_A-Za-z0-9][A-Za-z0-9_-]*$/,
mqlkey_slow:/^(?:[A-Za-z0-9]|\$[A-F0-9]{4})(?:[A-Za-z0-9_-]|\$[A-F0-9]{4})*$/,check_mql_key:function(b){return a.suggest.mqlkey_fast.test(b)||a.suggest.mqlkey_slow.test(b)?true:false},check_mql_id:function(b){if(b.indexOf("/")===0){b=b.split("/");b.shift();if(!(b.length==1&&b[0]===""))for(var c=0,e=b.length;c<e;c++)if(!a.suggest.check_mql_key(b[c]))return false;return true}return false},is_system_type:function(a){return a==null?false:a.indexOf("/type/")===0}});var g=a.suggest.prototype._destroy,e=
a.suggest.prototype.show_hook;a.suggest("suggest",{_init:function(){var b=this,c=this.options;if(c.flyout_service_url==null)c.flyout_service_url=c.service_url;this.flyout_url=c.flyout_service_url;if(c.flyout_service_path)this.flyout_url=this.flyout_url+c.flyout_service_path;this.flyout_url=this.flyout_url.replace(/\$\{key\}/g,c.key);if(c.flyout_image_service_url==null)c.flyout_image_service_url=c.service_url;this.flyout_image_url=c.flyout_image_service_url;if(c.flyout_image_service_path)this.flyout_image_url=
this.flyout_image_url+c.flyout_image_service_path;this.flyout_image_url=this.flyout_image_url.replace(/\$\{key\}/g,c.key);if(!a.suggest.cache)a.suggest.cache={};if(c.flyout){this.flyoutpane=a('<div style="display:none;" class="fbs-reset">').addClass(c.css.flyoutpane);if(c.flyout_parent)a(c.flyout_parent).append(this.flyoutpane);else{this.flyoutpane.css("position","absolute");c.zIndex&&this.flyoutpane.css("z-index",c.zIndex);a(document.body).append(this.flyoutpane)}this.flyoutpane.hover(function(a){b.hoverover_list(a)},
function(a){b.hoverout_list(a)}).bind("mousedown.suggest",function(a){a.stopPropagation();b.pane.click()});if(!a.suggest.flyout)a.suggest.flyout={};if(!a.suggest.flyout.cache)a.suggest.flyout.cache={}}},_destroy:function(){g.call(this);this.flyoutpane&&this.flyoutpane.remove();this.input.removeData("request.count.suggest");this.input.removeData("flyout.request.count.suggest")},shift_enter:function(){if(this.options.suggest_new){this.suggest_new();this.hide_all()}},hide_all:function(){this.pane.hide();
this.flyoutpane&&this.flyoutpane.hide();this.input.trigger("fb-pane-hide",this);this.input.trigger("fb-flyoutpane-hide",this)},request:function(b,c){var e=this,d=this.options,f=b,g=d.ac_param.filter||[],j=null;a.type(g)==="string"&&(g=[g]);g=g.slice();if(d.advanced){var h=a.suggest.parse_input(f),f=h[0];h[1].length&&g.push("(all "+h[1].join(" ")+")");j=h[2];if(a.suggest.check_mql_id(f)){g.push('(any alias{start}:"'+f+'" mid:"'+f+'")');j.prefixed=true;f=""}}h={};h[d.query_param_name]=f;if(c)h.cursor=
c;a.extend(h,d.ac_param,j);if(g.length)h.filter=g;var p=d.service_url+d.service_path+"?"+a.param(h,true);if(f=a.suggest.cache[p])this.response(f,c?c:-1,true);else{clearTimeout(this.request.timeout);var r={url:d.service_url+d.service_path,data:h,traditional:true,beforeSend:function(){var a=e.input.data("request.count.suggest")||0;a||e.trackEvent(e.name,"start_session");a=a+1;e.trackEvent(e.name,"request","count",a);e.input.data("request.count.suggest",a)},success:function(d){a.suggest.cache[p]=d;d.prefix=
b;e.response(d,c?c:-1)},error:function(a){e.status_error();e.trackEvent(e.name,"request","error",{url:this.url,response:a?a.responseText:""});e.input.trigger("fb-error",Array.prototype.slice.call(arguments))},complete:function(a){a&&e.trackEvent(e.name,"request","tid",a.getResponseHeader("X-Metaweb-TID"))},dataType:"jsonp",cache:true};this.request.timeout=setTimeout(function(){a.ajax(r)},d.xhr_delay)}},create_item:function(b,c){var e=this.options.css,d=a("<li>").addClass(e.item),f=a("<label>").append(a.suggest.strongify(b.name||
b.id,c.prefix)),g=a("<div>").addClass(e.item_name).append(f),j=b.notable;b.under&&a(":first",f).append(a("<small>").text(" ("+b.under+")"));(j!=null&&a.suggest.is_system_type(j.id)||this.options.scoring!=null&&this.options.scoring.toUpperCase()==="SCHEMA")&&a(":first",f).append(a("<small>").text(" ("+b.id+")"));d.append(g);e=a("<div>").addClass(e.item_type);j&&j.name?e.text(j.name):this.options.show_id&&b.id&&e.text(b.id);g.prepend(e);return d},mouseover_item_hook:function(a){a=a.data("data.suggest");
this.options.flyout&&a&&this.flyout_request(a)},check_response:function(a){return a.prefix===this.input.val()},response_hook:function(b,c){this.flyoutpane&&this.flyoutpane.hide();c>0?a(".fbs-more",this.pane).remove():this.list.empty()},show_hook:function(b,c,d){e.apply(this,[b]);var f=this.options,g=this,h=this.pane,j=this.list,m=b.result,p=a(".fbs-more",h),r=a(".fbs-suggestnew",h);a(".fbs-status",h);var q=b.correction;if(q&&q.length){var s=a('<a class="fbs-spell-link" href="#">').text(q[0]).bind("click.suggest",
function(a){a.preventDefault();a.stopPropagation();g.input.val(q[0]).trigger("textchange")});g.status.empty().append("Search instead for ").append(s).show()}if(m&&m.length&&"cursor"in b){if(!p.length){m=a('<a class="fbs-more-link" href="#" title="(Ctrl+m)">view more</a>');p=a('<div class="fbs-more">').append(m);m.bind("click.suggest",function(b){b.preventDefault();b.stopPropagation();b=a(this).parent(".fbs-more");g.more(b.data("cursor.suggest"))});j.after(p)}p.data("cursor.suggest",b.cursor);p.show()}else p.remove();
if(f.suggest_new){if(!r.length){b=a('<button class="fbs-suggestnew-button">');b.text(f.suggest_new);r=a('<div class="fbs-suggestnew">').append('<div class="fbs-suggestnew-description">Your item not in the list?</div>').append(b).append('<span class="fbs-suggestnew-shortcut">(Shift+Enter)</span>').bind("click.suggest",function(a){a.stopPropagation();g.suggest_new(a)});h.append(r)}r.show()}else r.remove();if(d&&d.length&&c>0){c=d.prevAll().length*d.outerHeight();j.scrollTop();j.animate({scrollTop:c},
"slow",function(){d.trigger("mouseover.suggest")})}},suggest_new:function(){var a=this.input.val();if(a!==""){this.input.data("data.suggest",a).trigger("fb-select-new",a);this.trackEvent(this.name,"fb-select-new","index","new");this.hide_all()}},more:function(a){if(a){var c=this.input.data("original.suggest");c!==null&&this.input.val(c);this.request(this.input.val(),a);this.trackEvent(this.name,"more","cursor",a)}return false},flyout_request:function(b){var c=this,e=this.options,d=this.flyoutpane.data("data.suggest");
if(d&&b.id===d.id){if(!this.flyoutpane.is(":visible")){b=this.get_selected();this.flyout_position(b);this.flyoutpane.show();this.input.trigger("fb-flyoutpane-show",this)}}else if((d=a.suggest.flyout.cache[b.id])&&d.id&&d.html)this.flyout_response(d);else{var f=b.id,g={url:this.flyout_url.replace(/\$\{id\}/g,b.id),traditional:true,beforeSend:function(){var a=c.input.data("flyout.request.count.suggest")||0,a=a+1;c.trackEvent(c.name,"flyout.request","count",a);c.input.data("flyout.request.count.suggest",
a)},success:function(b){b["req:id"]=f;if(b.result&&b.result.length)b.html=a.suggest.suggest.create_flyout(b.result[0],c.flyout_image_url);a.suggest.flyout.cache[f]=b;c.flyout_response(b)},error:function(a){c.trackEvent(c.name,"flyout","error",{url:this.url,response:a?a.responseText:""})},complete:function(a){a&&c.trackEvent(c.name,"flyout","tid",a.getResponseHeader("X-Metaweb-TID"))},dataType:"jsonp",cache:true};if(e.flyout_lang)g.data={lang:e.flyout_lang};clearTimeout(this.flyout_request.timeout);
this.flyout_request.timeout=setTimeout(function(){a.ajax(g)},e.xhr_delay);this.input.trigger("fb-request-flyout",g)}},flyout_response:function(a){var c=this.pane,e=this.get_selected()||[];if(c.is(":visible")&&e.length)if((c=e.data("data.suggest"))&&a["req:id"]===c.id&&a.html){this.flyoutpane.html(a.html);this.flyout_position(e);this.flyoutpane.show().data("data.suggest",c);this.input.trigger("fb-flyoutpane-show",this)}},flyout_position:function(b){if(!this.options.flyout_parent){var c=this.pane,e=
this.flyoutpane,f=this.options.css,g=d,h=parseInt(e.css("top"),10),j=parseInt(e.css("left"),10),m=c.offset(),p=c.outerWidth(),r=e.outerHeight(),q=e.outerWidth();if(this.options.flyout==="bottom"){g=m;p=this.input.offset();g.top=m.top<p.top?g.top-r:g.top+c.outerHeight();e.addClass(f.flyoutpane+"-bottom")}else{g=b.offset();b=b.outerHeight();g.left=g.left+p;var s=g.left+q,c=a(document.body).scrollLeft(),n=a(window).width()+c;g.top=g.top+b-r;if(g.top<m.top)g.top=m.top;if(s>n){m=g.left-(p+q);if(m>c)g.left=
m}e.removeClass(f.flyoutpane+"-bottom")}g.top===h&&g.left===j||e.css({top:g.top,left:g.left})}},hoverout_list:function(){this.flyoutpane&&!this.get_selected()&&this.flyoutpane.hide()}});a.extend(a.suggest.suggest,{defaults:{filter:null,spell:"always",exact:false,scoring:null,lang:null,key:null,prefixed:true,stemmed:null,format:null,advanced:true,show_id:true,query_param_name:"query",service_url:"https://www.googleapis.com/freebase/v1",service_path:"/search",align:null,flyout:true,flyout_service_url:null,
flyout_service_path:"/search?filter=(all mid:${id})&output=(notable:/client/summary (description citation provenance) type)&key=${key}",flyout_image_service_url:null,flyout_image_service_path:"/image${id}?maxwidth=75&key=${key}&errorid=/freebase/no_image_png",flyout_parent:null,suggest_new:null,nomatch:{title:"No suggested matches",heading:"Tips on getting better suggestions:",tips:["Enter more or fewer characters","Add words related to your original search","Try alternate spellings","Check your spelling"]},
css:{item_type:"fbs-item-type",flyoutpane:"fbs-flyout-pane"},xhr_delay:200},get_value_by_keys:function(b,c){for(var e=a.isArray(c)?c:Array.prototype.slice.call(arguments,1),d=0;d<e.length;d++){b=b[e[d]];if(b==null)break}return b},get_value:function(b,c,e){if(b==null||c==null||c.length==0)return null;a.isArray(c)||(c=[c]);b=a.suggest.suggest.get_value_by_keys(b,c);if(e){if(b==null)return[];a.isArray(b)||(b=[b]);var d=[];a.each(b,function(b,c){if(a.type(c)==="object")if(c.name!=null)c=c.name;else if(c.id||
c.mid)c=c.id||c.mid;else if(c.value!=null){var e=[];a.each(c,function(a,b){a!=="value"&&e.push(b)});c=c.value;e.length&&(c=c+(" ("+e.join(", ")+")"))}if(a.isArray(c)&&c.length)c=c[0].value;c!=null&&d.push(c)});return d}return b==null?null:b},is_commons_id:function(a){return/^\/base\//.test(a)||/^\/user\//.test(a)?false:true},create_flyout:function(b,c){var e=a.suggest.suggest.get_value_by_keys,d=a.suggest.suggest.get_value,f=a.suggest.is_system_type,g=b.name,h=null,m=null,p=[],r=[],q={};if((h=d(b,
"notable"))&&h.name){r.push(h.name);q[h.name]=true}if(h&&f(h.id))h=b.id;else{h=b.mid;m=c.replace(/\$\{id\}/g,h)}var s=null,n=f=null,v=null,l=e(b,"output","description","/common/topic/description")||[];if(l.length){var w=l[0];a.each(l,function(a,b){if(e(b,"citation",0,"mid")=="/m/0d07ph"){w=b;return false}return true});s=a.isArray(w.value)&&w.value.length?w.value[0].value:w.value;if(e(w,"provenance",0,"restrictions",0)=="REQUIRES_CITATION"){f=e(w,"provenance",0,"source",0);if((n=e(w,"citation","provider",
0,"name"))&&a.isArray(n)&&n.length)n=n[0].value;if((v=e(w,"citation","statement",0))&&v.value)v=v.value}}else a.each(["wikipedia","freebase"],function(a,c){if((l=d(b,["output","description",c],true))&&l.length){s=l[0];n=c;return false}return true});var z=d(b,["output","notable:/client/summary"]);if(z){var u=d(z,"/common/topic/notable_paths");u&&u.length&&a.each(u,function(a,b){var c=d(z,b,true);if(c&&c.length){var c=c.slice(0,3),e=b.split("/").pop();p.push([e,c.join(", ")])}})}(u=d(b,["output","type",
"/type/object/type"],true))&&u.length&&a.each(u,function(a,b){if(!q[b]){r.push(b);q[b]=true}});var y=a('<div class="fbs-flyout-content">');g&&y.append(a('<h1 id="fbs-flyout-title">').text(g));y.append(a('<h3 class="fbs-topic-properties fbs-flyout-id">').text(h));p=p.slice(0,3);a.each(p,function(b,c){y.append(a('<h3 class="fbs-topic-properties">').append(a("<strong>").text(c[0]+": ")).append(document.createTextNode(c[1])))});if(s){g=a('<p class="fbs-topic-article">');n&&(f?g.append(a('<a class="fbs-citation">').attr("href",
f).attr("title",v||n).text("["+n+"]")):g.append(a('<em class="fbs-citation">').attr("title",v||n).text("["+n+"] ")));g.append(document.createTextNode(" "+s));y.append(g)}if(m){y.children().addClass("fbs-flyout-image-true");y.prepend(a('<img id="fbs-topic-image" class="fbs-flyout-image-true" src="'+m+'">'))}m=a('<span class="fbs-flyout-types">').text(r.slice(0,3).join(", "));m=a('<div class="fbs-attribution">').append(m);return a("<div>").append(y).append(m).html()}});document.createElement("input")})(jQuery);
(function(a){window.freebase=window.fb={mwLWTReloading:false};window.SERVER&&typeof window.SERVER==="object"&&a.extend(window.freebase,window.SERVER);a.cookie=window.freebase.cookie})(jQuery);
(function(a,d){a.ajaxSettings.traditional=true;if(!d.datelineReloading){if(!window.console)window.console={log:a.noop,info:a.noop,debug:a.noop,warn:a.noop,error:a.noop};d.dispatch=function(b,c,e,d){if(typeof c!=="function")return false;b=a.event.fix(b||window.event);e||(e=[]);d||(d=this);return c.apply(d,[b].concat(e))};d.get_script=function(b,c){var e=d.get_script.cache,f=e[b];if(f)f.state===1?f.callbacks.push(c):f.state===4&&c();else{f=e[b]={state:0,callbacks:[c]};a.ajax({url:b,dataType:"script",
cache:true,beforeSend:function(){f.state=1},success:function(){f.state=4;a.each(f.callbacks,function(a,b){b()})},error:function(a,b,c){f.state=-1;console.error("fb.get_script error",arguments)}})}};d.get_script.cache={};a(window).bind("fb.user.signedin",function(b,c){d.user=c;var e=a("#nav-username");if(e.length){a("> a",e).text(c.name);e[0].href=e[0].href+d.user.id.substring(1);var f=d.h.image_url(c.id,{maxwidth:40,maxheight:40,mode:"fillcropmid"}),f=a('<a class="user-thumb" href="'+c.id+'"><img src="'+
f+'" /></a>');e.prepend(f)}a("#signedin").show();a(".signedin").show()}).bind("fb.user.signedout",function(){a("#signedin").hide();a("#signedout").show()}).bind("fb.user.unauthorized",function(){setTimeout(function(){a.get(d.h.ajax_url("lib/template/signout.ajax"));a(window).trigger("fb.user.signedout");d.status.clear();d.status.sprintf("info","Please %s to continue.","Sign In",function(){window.location.href=a("#fb-signin-link").attr("href");return false})})}).bind("fb.user.feedback",function(a,
b){if(confirm("Uh oh! Something went wrong. Please report this using our feedback tool."))try{userfeedback.api.startFeedback({productId:"68931",disableScrolling:false},b);return false}catch(c){}});var h=a.cookie("fb-account-name");if(h){var f={id:"/user/"+h,name:h};setTimeout(function(){a(window).trigger("fb.user.signedin",f);var b=d.h.ajax_url("lib/template/refresh_credentials"),c=a("<iframe name='rc'></iframe>").attr("src",b).hide().appendTo("body").load(function(){var e=parseInt(a("body",window.rc.document).text(),
10)-(new Date).getTime();e&&e>0&&setTimeout(function(){a(c).attr("src",b)},e)})},0)}else setTimeout(function(){a(window).trigger("fb.user.signedout")},0);d.window_position=function(){var a={};if(typeof window.innerWidth=="number"){a.width=window.outerWidth;a.height=window.outerHeight;a.top=window.screenY;a.left=window.screenX}else if(document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)){a.width=document.body.clientWidth;a.height=document.body.clientHeight;
a.top=window.screenTop;a.left=window.screenLeft}return a};var g=function(){c&&c.slideUp(300);k=null;return false},e=function(e,d,f,h){if(c===null){c=a("#page-state");i=a(".status-msg",c);t=a(".close-msg",c);t.click(g)}if(k==="error")console.warn("MessagePanel: Already displaying error. Ignoring: ",e,d);else{c.hide();a.each(b,function(a,b){c.removeClass(b)});c.addClass(e);i.text(d);k=e;window.clearTimeout(o);if(h){t.show();c.slideDown(300)}else{t.hide();c.slideDown(300);o=window.setTimeout(g,f)}}return false},
b=["notice","info","warning","success","error"],c=null,i=null,t=null,o=null,k=null;d.status={doing:function(a){return e("notice",a,2E6,false)},info:function(a,b){return e("info",a,4E3,b)},warning:function(a,b){return e("warning",a,4E3,b)},success:function(a,b){return e("success",a,6E3,b)},error:function(a,b){return e("error",a,6E3,b)},sprintf:function(b,c){var d=Array.prototype.slice.call(arguments).slice(2),f=c.split("%s");if(f.length>1&&d.length>1&&d.length%2==0){for(var g=a("<span>"),h=0,n=f.length;h<
n;h++){g.append(document.createTextNode(f[h]));var k=a('<a href="#">');k.text(d.shift());var l=d.shift();a.type(l)==="function"&&k.click(l);g.append(k)}d=e(b,"",null,true);i.empty().append(g);return d}return e(b,c,null,true)},clear:function(){window.clearTimeout(o);k==="error"?console.warn("MessagePanel: Displaying error. Ignoring clearing status."):g()}};d.popup=function(a,b,c,e){var b=b||300,c=c||300,f=d.window_position(),g=Math.floor((f.width-b)/2)+f.left,f=Math.floor((f.height-c)/2)+f.top;/chrome/.test(navigator.userAgent.toLowerCase())&&
(c=c+50);var b={width:b,height:c,top:f,left:g,directories:"no",location:"no",menubar:"no",resizable:"no",scrollbars:"yes",status:"no",toolbar:"no"},c=[],i;for(i in b)c.push(i+"="+b[i]);return window.open(a,e||"",c.join())};d.login_popup=function(a){a||(a=function(){window.location.reload()});var b=d.popup("/account/signin",900,600,"Freebase");if(b.opener==null)b.opener=self;window.onsignin=a;window.focus&&b.focus();return false};d.logout_popup=function(a){a||(a=function(){window.location.reload()});
var b=d.popup("/account/signout",900,600,"Freebase");if(b.opener==null)b.opener=self;window.onsignout=a;window.focus&&b.focus();return false};a(function(){var b=a("#header > #nav-utilities > .language-picker"),c=a(".current-lang",b);a("select",b).bind("change",function(){var b=a(this).find(":selected").text();c.text(b)})});a(function(){var b=d,c=d.SEARCH_LANGS,e={};a.each((c||"en,es,fr,de,it,pt,zh,ja,ko,ru,sv,fi,da,nl,el,ro,tr,hu,th").split(","),function(b,c){e[a.trim(c)]=1});b.suggest_lang={SUPPORTED:e,
lang:function(a){a=d.h.lang_code(a||d.lang||"/lang/en");return d.suggest_lang.SUPPORTED[a]&&a!=="en"?a+",en":"en"}};var b=d,c=d.h.fb_googleapis_url(),f=d.acre.freebase.api_key,g,i=[];a.each(d.suggest_lang.lang().split(","),function(a,b){i.push("s/"+b+",d/"+b)});i.push("s/all,d/all");g=i.join(",");b.suggest_options={service_defaults:{status:["","Searching...","Select an item from the list:"],service_url:c,key:f,lang:g},filter:{operator:function(){var a=Array.prototype.slice.call(arguments),b=a.shift();
if(!(b==="any"||b==="all"||b==="should"))throw"Invalid search operator: "+b;var c=[b];if(b==="should"&&a.length>1){a=["any"].concat(a);c.push(d.suggest_options.filter.operator.apply(null,a))}else c=c.concat(a);return"("+c.join(" ")+")"},any:function(){var a=Array.prototype.slice.call(arguments);a.unshift("any");return d.suggest_options.filter.operator.apply(null,a)},all:function(){var a=Array.prototype.slice.call(arguments);a.unshift("all");return d.suggest_options.filter.operator.apply(null,a)},
should:function(){var a=Array.prototype.slice.call(arguments);a.unshift("should");return d.suggest_options.filter.operator.apply(null,a)}},any:function(){var b=a.extend({},d.suggest_options.service_defaults);b.filter=d.suggest_options.filter.any.apply(null,arguments);return b},all:function(){var b=a.extend({},d.suggest_options.service_defaults);b.filter=d.suggest_options.filter.all.apply(null,arguments);return b},should:function(){var b=a.extend({},d.suggest_options.service_defaults);b.filter=d.suggest_options.filter.should.apply(null,
arguments);return b},search:function(b){var c=a.extend({},d.suggest_options.service_defaults,{status:null,parent:"#site-search-box",align:"right",filter:["(not type:/common/document)"],soft:true,nomatch:{title:"No suggested matches",heading:"Tips on getting better suggestions:",tips:["Enter more or fewer characters","Add words related to your original search","Try alternate spellings","Check your spelling","Toggle checkbox to include non-topics"]}});b&&c.filter.push("(any type:/common/topic)");return c},
instance:function(b,c,e,f,g){var i=["type:"+b];a.each(["user","domain","type"],function(a,c){if(b==="/freebase/"+c+"_profile"){i.push("type:/type/"+c);return false}});b==="/book/book_subject"&&i.push("type:/base/skosbase/skos_concept");var h=null;if(d.h.is_metaweb_system_type(b)||f)h=d.suggest_options.any.apply(null,i);else{h=d.suggest_options.should.apply(null,i);if(c)h.suggest_new="Create new"}if(e)h.lang=d.suggest_lang.lang(e);h.filter=[h.filter,"(all namespace:/m)"];g&&h.filter.push('(not mid:"'+
g+'")');return h},cotype:function(){return a.extend({scoring:"schema"},d.suggest_options.all.apply(null,["type:/type/type","namespace:/m","(not namespace:/type)","(not namespace:/freebase)","(any (not namespace:/common) (any mid:/m/01c5 mid:/m/02_1_m4 mid:/m/03hc3d_))"]))},included_type:function(){return d.suggest_options.cotype()},expected_type:function(){return a.extend({scoring:"schema"},d.suggest_options.all.apply(null,["type:/type/type","namespace:/m"]))},delegate_property:function(){return a.extend({scoring:"schema"},
d.suggest_options.all.apply(null,["type:/type/property","(not namespace:/type/object)","namespace:/m"]))}}});a(function(){function b(){var c=a.localstore("fb-search-topic-only")!==false;e.suggest(d.suggest_options.search(c))}function c(){if(!e.data("dont_hide")&&!k.is(":visible")&&g.is(":visible")){i.hide();a("#site-search-label").slideUp("fast");f.removeClass("active")}}var e=a("#fb-search-input"),f=a("#fb-search"),g=a("#site-search-label"),i=a("#site-search-topic-option").mousedown(function(){e.data("dont_hide",
true)}).mouseup(function(){e.data("dont_hide",false)}),h=a(":checkbox",i).change(function(){var c=a(this).is(":checked");a.localstore("fb-search-topic-only",!c);b();e.focus().trigger("textchange")});a.localstore("fb-search-topic-only")===false&&h.attr("checked","checked");b();var k=a("#site-search-box .fbs-pane");e.bind("fb-select",function(b,c){var e={};a(this).siblings("input[type=hidden]").each(function(){e[this.name]=this.value});var f;f=c.id;f=f.indexOf("/en/")==0?c.mid||f:c.notable&&d.h.is_metaweb_system_type(c.notable.id)?
f:c.mid||f;window.location.href=d.h.fb_url(f,e);return false}).bind("fb-pane-show",function(){g.html("<span>Select an item from the list</span>").removeClass("loading");i.show()}).bind("fb-textchange",function(){a.trim(e.val())===""?g.html("<span>Start typing to get some suggestions</span>").removeClass("loading"):g.html("<span>Searching...</span>").addClass("loading");i.hide()}).bind("fb-error",function(){g.html("<span>Sorry, something went wrong. Please try again later</span>").removeClass("loading");
i.hide()}).focus(function(){if(!g.is(":visible")){a("#site-search-label").slideDown("fast");f.addClass("active")}}).blur(function(){setTimeout(c,0)});e.parent("form").submit(function(){h.is(":checked")||a(this).append('<input type="hidden" name="any" value="/common/topic">');return true})});d.disable=function(b){a(b).attr("disabled","disabled").addClass("disabled")};d.enable=function(b){a(b).removeAttr("disabled").removeClass("disabled")};d.lang_select=function(b,c){if(c==="/lang/en"){a(this).removeAttr("name");
if(!a(":input[name]",this.form).length){window.location=a(this.form).attr("action");return}}this.form.submit()};d.devbar={div:a("#devbar"),touch:function(){/\.(freebase|sandbox\-freebase)\.com$/.test(d.acre.request.server_name)?a.ajax({url:d.acre.freebase.googleapis_url?d.h.fb_googleapis_url("/touch"):d.h.fb_api_url("/api/service/touch"),dataType:"jsonp"}):a.ajax({url:"/acre/touch"});return false},txn_ids:[],txn:function(){return d.devbar.view_txn(this.href,d.devbar.txn_ids)},view_txn:function(b,
c){if(c&&c.length)window.location=b+"?"+a.param({tid:c},true);return false},ajaxComplete:function(a){if(a&&a.readyState===4)(a=a.getResponseHeader("x-metaweb-tid"))&&d.devbar.txn_ids.push(a)},init:function(){$nav_user_controls=a(".nav-user-controls");$user_controls=a("#user-controls");a("#signedin .trigger").click(function(){if($user_controls.is(":hidden")){$user_controls.fadeIn();$nav_user_controls.addClass("active")}else{$user_controls.fadeOut();$nav_user_controls.removeClass("active")}return false});
a("html").click(function(){if($user_controls.is(":visible")){$user_controls.fadeOut();$nav_user_controls.removeClass("active")}});$user_controls.click(function(a){a.stopPropagation()});a("#devbar-touch > a").click(d.devbar.touch);d.tid&&d.devbar.txn_ids.push(d.tid);a("#devbar-txn > a").click(d.devbar.txn);a(document).ajaxComplete(function(){d.devbar.ajaxComplete.apply(null,arguments)});a(document).ajaxError(function(b,c,e){var d={};a.each(["url","data","dataType","type"],function(a,b){d[b]=e[b]});
a.each(["status","statusText","responseText"],function(a,b){d[b]=c[b]});d.responseHeaders=c.getAllResponseHeaders();if(d.status!==200){var b=d.url.match(/^.*[^\/]\/([a-z_]*)\.ajax.*$/)[1],f=d.status===401?"User Error":"Site Error";(window._gaq||[]).push(["_trackEvent",f,"AJAX Error "+(b||""),"path:"+d.url+";status:"+d.status+";status-text:"+d.statusText,1])}})}};d.devbar.init();d.mqlread=function(b,c,e){var f;if(d.acre.freebase.googleapis_url){f=d.h.fb_googleapis_url("/mqlread");b={query:JSON.stringify(b),
key:d.acre.freebase.api_key}}else{f=d.h.fb_api_url("/api/service/mqlread");b={query:JSON.stringify({query:b})}}return a.ajax({url:f,data:b,dataType:"jsonp",success:function(a){c&&c.apply(this,[a.result])},error:function(){e&&e.apply(this,arguments)}})};d.touch_and_reload=function(){a.ajax({url:"/acre/touch"}).done(function(){window.location.reload(true)});return false};a(function(){var b=d,c=a("#fb-topic-hover-pane").hover(function(){clearTimeout(d.hover.hide_timer_)},function(){d.hover.hide_now_()});
b.hover={pane:c,current_target:null,cache:{},search_url:d.h.fb_googleapis_url()+"/search?filter=(all mid:${id})&output=(notable:/client/summary (description citation provenance) type)&key="+d.acre.freebase.api_key+"&lang="+d.suggest_lang.lang(),image_url:d.h.fb_googleapis_url()+"/image${id}?maxwidth=75&errorid=/freebase/no_image_png&key="+d.acre.freebase.api_key,show:function(b){clearTimeout(d.hover.hide_timer_);var c=b.target,e=a(c).attr("data-id");if(e){d.hover.current_target=c;a(c).removeAttr("title");
d.hover.cache[e]?d.hover.show_now_(c,d.hover.cache[e]):a.ajax({url:d.hover.search_url.replace(/\$\{id\}/g,e),success:function(b){if(b.result&&b.result.length){b=a.suggest.suggest.create_flyout(b.result[0],d.hover.image_url);d.hover.cache[e]=b;d.hover.show_now_(c,b)}},dataType:"jsonp",cache:true})}},show_now_:function(b,c){if(b===d.hover.current_target){d.hover.pane.html(c);var e=d.hover.pane.height(),f=a(b).height(),g=a(b).offset(),i=g.left,g=g.top,g=g-a(document).scrollTop()+e<a(window).height()?
g+f:g-e-f;d.hover.pane.css({top:g,left:i}).show()}},hide:function(){d.hover.hide_timer_=setTimeout(d.hover.hide_now_,100)},hide_now_:function(){d.hover.current_target=null;d.hover.pane.hide()}};d.keyboard_shortcut={cache_:{},add:function(a,b,c){var e=a.charCodeAt(0);!c&&e in d.keyboard_shortcut.cache_&&console.warn("Overriding keyboard shortcut",a);d.keyboard_shortcut.cache_[e]=b}};d.on_mid_dblclick=function(a){a=a.target;if(document.body.createTextRange){var b=document.body.createTextRange();b.moveToElementText(a);
b.select()}else if(window.getSelection){var c=window.getSelection(),b=document.createRange();b.selectNodeContents(a);c.removeAllRanges();c.addRange(b)}};a(document).keypress(function(b){if(b.altKey||b.ctrlKey||b.metaKey||b.shiftKey)return true;var c=b.charCode,b=b.target;if(d.keyboard_shortcut.cache_[c]&&(b==document.body||b==document||b==window||b==a("html")[0])){d.keyboard_shortcut.cache_[c]();return false}return true});a("#page-content").on("mouseenter","a.property-value",d.hover.show).on("mouseleave",
"a.property-value",d.hover.hide);a(document.body).on("dblclick",".mid",d.on_mid_dblclick).on("click",".mid",d.on_mid_dblclick)})}})(jQuery,window.freebase);
(function(a,d){var h;if(!(h=a.type)){var f={};["Boolean","Number","String","Function","Array","Date","RegExp","Object"].forEach(function(a){f["[object "+a+"]"]=a.toLowerCase()});h=function(a){return a==null?String(a):f[Object.prototype.toString.call(a)]||"object"}}var g=d.h={type:h,parse_params:function(e){if(a.isArray(e)){var b={};a.each(e,function(a,e){b[e[0]]=e[1]});return b}return e},build_url:function(e){if(e&&e.indexOf("//")!==0&&e.indexOf("://")===-1)throw"Host must contain scheme: "+e;var b=
e||"",c,d;if(arguments.length>1){c=Array.prototype.slice.call(arguments);c.shift();for(var f=[],h=0,k=c.length;h<k;h++){var j=c[h];if(g.type(j)==="string")f.push(j);else{for(d={};h<k;h++)d=a.extend(d,g.parse_params(c[h]));break}}c=f.join("")}if(c&&c.indexOf("/")!==0)throw"Path must begin with a '/': "+c;c&&(b=b+c);b===""&&(b="/");a.isEmptyObject(d)||(b=b+("?"+a.param(d,true)));return b},fb_url:function(){var a=Array.prototype.slice.call(arguments);a.unshift(null);d.lang&&d.lang!=="/lang/en"&&a.push({lang:g.lang_code(d.lang)});
return g.build_url.apply(null,a)},ajax_url:function(){var a=Array.prototype.slice.call(arguments);a.unshift("/ajax");return g.reentrant_url.apply(null,a)},static_url:function(){var a=Array.prototype.slice.call(arguments);a.unshift("/static");return g.reentrant_url.apply(null,a)},reentrant_url:function(a,b){var b=g.resolve_reentrant_path(b),b=b.replace(/^\/\//,a+"/"),c=Array.prototype.slice.call(arguments,2);c.unshift(b);c.unshift(null);return g.build_url.apply(null,c)},resolve_reentrant_path:function(a){a=
a||"";if(a.indexOf("//")==0)return a;if(a.indexOf("lib/")===0)return d.acre.current_script.app.path+a.substring(3);a&&a[0]!="/"&&(a="/"+a);return d.acre.request.script.app.path+a},legacy_fb_url:function(){var a=Array.prototype.slice.call(arguments),b=d.acre.freebase.site_host.replace(/^(https?\:\/\/)([^\.]+)\./,"$1www.").replace(":"+d.acre.request.server_port,"");a.unshift(b);return g.build_url.apply(null,a)},fb_api_url:function(){var a=Array.prototype.slice.call(arguments);a.unshift(d.acre.freebase.service_url);
return g.build_url.apply(null,a)},fb_googleapis_url:function(){if(d.acre.freebase.googleapis_url){var a=Array.prototype.slice.call(arguments);a.unshift(d.acre.freebase.googleapis_url);return g.build_url.apply(null,a)}throw"fb.acre.freebase.googleapis_url is not defined";},wiki_url:function(a){var b=Array.prototype.slice.call(arguments);b.unshift("http://wiki.freebase.com","/wiki/");return g.build_url.apply(null,b)},lib_base_url:function(a){a=d.acre.metadata.libs[a];return a.base_url+a.version},image_url:function(a,
b){return d.acre.freebase.imgurl(a,b.maxwidth,b.maxheight,b.mode,b.pad,b.errorid)},is_metaweb_system_type:function(a){return a.indexOf("/type/")===0||a.indexOf("/common/")===0&&a!=="/common/topic"||a.indexOf("/freebase/")===0&&a.indexOf("_profile")===a.length-8},id_key:function(a,b){var c=a.split("/"),d=c.pop();if(b){c=c.join("/");c===""&&(c="/");return[c,d]}return d},get_value_by_keys:function(e,b){for(var c=a.isArray(b),d=c?b:arguments,c=c?0:1;c<d.length;c++){e=e[d[c]];if(e===void 0)break}return e},
lang_code:function(a){return g.id_key(a)},lang_id:function(a){return"/lang/"+g.lang_code(a)}}})(jQuery,window.freebase);
(function(a,d){var h=d.permission={init:function(){if(d.access=="readonly"){a(".edit").hide();a(".no-edit").show()}else if(d.user){var f=d.c;f&&f.id&&a.ajax({url:d.h.ajax_url("lib/permission/has_permission.ajax"),data:{id:f.id,user_id:d.user.id},dataType:"json",success:function(d){h.has_permission=d.result&&d.result[f.id]===true;a(window).trigger("fb.permission.has_permission",h.has_permission)}});check_permissioned_objects(a(".edit-perm"),d.user.id)}else setTimeout(function(){h.has_permission=false;
a(window).trigger("fb.permission.has_permission",h.has_permission)})}};a(window).bind("fb.user.signedin",h.init);a(window).bind("fb.user.signedout",h.init);a(window).bind("fb.permission.has_permission",function(d,g){g?a(".edit").show():a(".no-edit").show()})})(jQuery,window.freebase);
function check_permissioned_objects(a,d){if(a.length&&d){var h={},f=[];$.each(a,function(){var a=$(this).metadata().id;if(a&&!h[a]){f.push(a);h[a]=1}});f.length&&$.ajax({url:fb.h.ajax_url("lib/permission/has_permission.ajax"),data:{id:f,user_id:d},traditional:true,dataType:"json",success:function(d){var e=d.result||{};$.each(a,function(){var a=$(this).metadata().id;a&&e[a]===true?$(this).show():$(this).addClass("edit-perm-lock")})}})}}
(function(a,d){var h=d.incompatible_types={overlay_dialog:null,inline_dialog:null,suggest_options:function(d,g,e){var e=e||{},g=[d].concat(g||[]),b=e.filter;if(!a.isArray(b)){b=[];b!=null&&b.push(e.filter);e.filter=b}b.push("(should (not incompatible:"+d+"))");e.filter=b;if(d=e.output)(b=/^\((.*)\)$/.exec(e.output))&&(d="("+h.search_output_(g)+" "+b[1]+")");d||(d=h.search_output_(g,true));e.output=d;return e},search_output_:function(a,d){var e=a.map(function(a){return"incompatible:"+a}).join(" ");
d&&(e="("+e+")");return e},check:function(d,g,e,b){var b=b||{},c=false,h=d.output;if(h){var t=[g].concat(e||[]);a.each(t,function(a,b){var d="incompatible:"+b;if(h[d]["/type/object/type"][0]==="true"||h[d]["/type/object/type"][0]===true)c=true;return!c})}c?b.incompatible&&b.incompatible(d,g,e):b.compatible&&b.compatible(d,g,e)},search:function(f,g,e,b){var c=[g].concat(e||[]),c={filter:"(all mid:"+f+")",output:h.search_output_(c,true),key:d.acre.freebase.api_key};a.ajax({url:d.h.fb_googleapis_url("/search",
c),dataType:"jsonp",success:function(c){a.isArray(c.result)&&c.result.length>0?h.check(c.result[0],g,e,b):b.compatible&&b.compatible({id:f},g,e)}})},overlay_incompatible_callback:function(d,g){if(!h.overlay_dialog)h.overlay_dialog=a(".incompatible-overlay-dialog");if(h.overlay_dialog.length){d=d||{};return function(e,b,c){h.overlay_dialog.removeData("overlay");a(".modal-content",h.overlay_dialog).empty().append(h.description_html(e,b,c));h.overlay_dialog.overlay({close:"button",closeOnClick:false,
load:true,fixed:false,mask:{color:"#000",loadSpeed:200,opacity:0.5},onClose:function(){g&&g.focus().select();a("button",h.overlay_dialog).unbind();if(d.onClose)d.onClose()},onLoad:function(){a(".cancel",h.overlay_dialog).focus().click(function(){g&&g.focus().select().trigger("textchange");if(d.onCancel)d.onCancel()});a(".save",h.overlay_dialog).click(function(){g&&g.focus().select();if(d.onConfirm)d.onConfirm(e,b,c)});if(d.onLoad)d.onLoad()}})}}return h.native_confirm_incompatible_callback(d,g)},
inline_incompatible_callback:function(d,g){if(!h.inline_dialog)h.inline_dialog=a(".incompatible-inline-dialog");if(h.inline_dialog.length){d=d||{};return function(e,b,c){a(".modal-content",h.inline_dialog).empty().append(h.description_html(e,b,c));a(".save",h.inline_dialog).unbind().click(function(){g.focus().select();if(d.onConfirm)d.onConfirm(e,b,c);h.inline_dialog.hide(d.onClose)});a(".cancel",h.inline_dialog).unbind().click(function(){g.focus().select().trigger("textchange");if(d.onCancel)d.onCancel();
h.inline_dialog.hide(d.onClose)});var i=g.offsetParent(),t=g.position();i.append(h.inline_dialog);h.inline_dialog.css({top:t.top+g.outerHeight(),left:t.left});h.inline_dialog.show(d.onLoad)}}return h.native_confirm_incompatible_callback(d,g)},native_confirm_incompatible_callback:function(a,d){a=a||{};return function(e,b,c){if(confirm(h.description_text(e,b,c))){d&&d.focus().select();if(a.onConfirm)a.onConfirm(e,b,c)}else{d&&d.focus().select().trigger("textchange");if(a.onCancel)a.onCancel()}if(a.onClose)a.onClose();
d&&d.focus().select()}},description_html:function(d,g){var e=a("<p>"),b;b=a('<div><b class="incompatible-topic"></b> is incompatible with <b class="incompatible-type"></b>.</div>');a(".incompatible-topic",b).text(d.name||d.id);a(".incompatible-type",b).text(g);e.append(b);b=a('<div>If you continue, <b class="incompatible-topic"></b> will be typed as <b class="incompatible-type"></b> and its included types (if any).</div>');a(".incompatible-topic",b).text(d.name||d.id);a(".incompatible-type",b).text(g);
e.append(b);e.append("<p>Are you sure you want to continue?<p>");return e},description_text:function(a,d,e){return h.description_html(a,d,e).text()}}})(jQuery,window.freebase);
(function(a,d){var h=d.flag={merge:function(a){return h.flag(a,"merge_begin")},split:function(a){return h.flag(a,"split_begin")},"delete":function(a){return h.flag(a,"delete_begin")},offensive:function(a){return h.flag(a,"offensive_begin")},flag:function(f,g){f=a(f);d.get_script(d.h.static_url("lib/flag/flag-edit.mf.js"),function(){h.edit[g](f)});return false},undo:function(f,g){f=a(f);d.get_script(d.h.static_url("lib/flag/flag-edit.mf.js"),function(){h.edit.undo_begin(f,g)});return false}}})(jQuery,
window.freebase);
(function(a){function d(){f();a(this).parents(".headmenu").data("submenu").find("a:first").click();return false}function h(d,e){var b=a(this),c=b.data("menu"),h=b.data("submenu");c.addClass("active");if(!h.is(".submenu-valid")){var c=b.offset(),t=b.outerHeight(),t=c.top+t;if(h.is(".center")){b=b.outerWidth();b=c.left+b/2-h.outerWidth()/2}else if(h.is(".right")){b=b.outerWidth();b=c.left+b-h.outerWidth()}else b=c.left;b={display:"none",position:"absolute",top:t,left:b};e.overlay&&(b.zIndex=e.overlay.css("zIndex"));
h.css(b);a(document.body).append(h);h.addClass(".submenu-valid")}if(h.is(":visible"))f(h);else{f();h.fadeIn()}return false}function f(d){d=d||a(".submenu:visible");d.data("menu")&&d.data("menu").removeClass("active");d.hide()}a.factory("nicemenu",{init:function(){var g=this.options;a(".headmenu",this.element).each(function(){var e=a(this),b=e.next(".submenu"),c=e.parents(".nicemenu");e.data("submenu",b);e.data("menu",c);b.data("headmenu",e);b.data("menu",c);a(".default-action",e).click(d);e.click(function(a){return h.apply(this,
[a,g])})});a(".submenu",this.element).click(function(){f(a(this));a(this).fadeOut()})}});a(document).click(function(){f()})})(jQuery);
(function(a,d){a(function(){a(".nicemenu").nicemenu();a("#description").css("height","auto");var h=a("#page-header .creation-timestamp").width();a("#page-header h1").css("margin-right",h);d.init_search();var f=function(){var a=null,c=null;if(g.is(":visible")){c=g;a=e}else{c=e;a=g}c.fadeOut();a.fadeIn(function(){setTimeout(f,6E3)})},g=a("#page-header .topics-count").first(),e=a("#page-header .topics-count").last();e.hide();setTimeout(f,6E3)});d.nav_ajax=function(h){a.getScript(h.href,function(){d.nav_ajax.begin(h)});
return false};d.init_search=function(){var d=a("#header #fb-search-input");a(document).keydown(function(a){if(d.is(":focus"))a.keyCode===27&&d.blur();else if(!(this!==event.target&&(/textarea|select/i.test(event.target.nodeName)||event.target.type==="text"))&&a.keyCode===191){d.focus();return false}})}})(jQuery,window.freebase);
