
/*
 * Copyright 2010, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Additional Licenses for Third Party components can be found here:
 * http://wiki.freebase.com/wiki/Freebase_Site_License
 *
 */
if(!("JSON"in window&&window.JSON)){if(!this.JSON)this.JSON={};(function(){function b(i){return i<10?"0"+i:i}function g(i){a.lastIndex=0;return a.test(i)?'"'+i.replace(a,function(k){var m=j[k];return typeof m==="string"?m:"\\u"+("0000"+k.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+i+'"'}function d(i,k){var m,l,q,r,n=c,o,p=k[i];if(p&&typeof p==="object"&&typeof p.toJSON==="function")p=p.toJSON(i);if(typeof h==="function")p=h.call(k,i,p);switch(typeof p){case "string":return g(p);case "number":return isFinite(p)?
String(p):"null";case "boolean":case "null":return String(p);case "object":if(!p)return"null";c+=f;o=[];if(Object.prototype.toString.apply(p)==="[object Array]"){r=p.length;for(m=0;m<r;m+=1)o[m]=d(m,p)||"null";q=o.length===0?"[]":c?"[\n"+c+o.join(",\n"+c)+"\n"+n+"]":"["+o.join(",")+"]";c=n;return q}if(h&&typeof h==="object"){r=h.length;for(m=0;m<r;m+=1){l=h[m];if(typeof l==="string")if(q=d(l,p))o.push(g(l)+(c?": ":":")+q)}}else for(l in p)if(Object.hasOwnProperty.call(p,l))if(q=d(l,p))o.push(g(l)+
(c?": ":":")+q);q=o.length===0?"{}":c?"{\n"+c+o.join(",\n"+c)+"\n"+n+"}":"{"+o.join(",")+"}";c=n;return q}}if(typeof Date.prototype.toJSON!=="function"){Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+b(this.getUTCMonth()+1)+"-"+b(this.getUTCDate())+"T"+b(this.getUTCHours())+":"+b(this.getUTCMinutes())+":"+b(this.getUTCSeconds())+"Z":null};String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()}}var e=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
a=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,c,f,j={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},h;if(typeof JSON.stringify!=="function")JSON.stringify=function(i,k,m){var l;f=c="";if(typeof m==="number")for(l=0;l<m;l+=1)f+=" ";else if(typeof m==="string")f=m;if((h=k)&&typeof k!=="function"&&(typeof k!=="object"||typeof k.length!=="number"))throw new Error("JSON.stringify");return d("",
{"":i})};if(typeof JSON.parse!=="function")JSON.parse=function(i,k){function m(q,r){var n,o,p=q[r];if(p&&typeof p==="object")for(n in p)if(Object.hasOwnProperty.call(p,n)){o=m(p,n);if(o!==undefined)p[n]=o;else delete p[n]}return k.call(q,r,p)}var l;i=String(i);e.lastIndex=0;if(e.test(i))i=i.replace(e,function(q){return"\\u"+("0000"+q.charCodeAt(0).toString(16)).slice(-4)});if(/^[\],:{}\s]*$/.test(i.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){l=eval("("+i+")");return typeof k==="function"?m({"":l},""):l}throw new SyntaxError("JSON.parse");}})()}
(function(b,g){if(!("console"in window)){var d=window.console={};d.log=d.warn=d.error=d.debug=function(){}}b(function(){var a=b("<div>");b(document.body).append(a);var c=setTimeout(function(){if(b.cleanData){var f=b.cleanData;b.cleanData=function(h){for(var i=0,k;(k=h[i])!=null;i++)b(k).triggerHandler("remove");f(h)}}else{var j=b.fn.remove;b.fn.remove=function(h,i){return this.each(function(){if(!i)if(!h||b.filter(h,[this]).length)b("*",this).add([this]).each(function(){b(this).triggerHandler("remove")});
return j.call(b(this),h,i)})}}},1);a.bind("remove",function(){clearTimeout(c)});a.remove()});b.suggest=function(a,c){b.fn[a]=function(f){this.length||console.warn("Suggest: invoked on empty element set");return this.each(function(){if(this.nodeName)if(this.nodeName.toUpperCase()==="INPUT")this.type&&this.type.toUpperCase()!=="TEXT"&&console.warn("Suggest: unsupported INPUT type: "+this.type);else console.warn("Suggest: unsupported DOM element: "+this.nodeName);var j=b.data(this,a);j&&j._destroy();
b.data(this,a,new b.suggest[a](this,f))._init()})};b.suggest[a]=function(f,j){var h=this,i=this.options=b.extend(true,{},b.suggest.defaults,b.suggest[a].defaults,j),k=i.css_prefix=i.css_prefix||"",m=i.css;this.name=a;b.each(m,function(n){m[n]=k+m[n]});i.ac_param={};b.each(["key","filter","spell","exact","lang"],function(n,o){var p=i[o];p===null||p===""||(i.ac_param[o]=p)});this._status={START:"",LOADING:"",SELECT:"",ERROR:""};if(i.status&&i.status instanceof Array&&i.status.length>=3){this._status.START=
i.status[0]||"";this._status.LOADING=i.status[1]||"";this._status.SELECT=i.status[2]||"";if(i.status.length===4)this._status.ERROR=i.status[3]||""}var l=this.status=b('<div style="display:none;">').addClass(m.status),q=this.list=b("<ul>").addClass(m.list),r=this.pane=b('<div style="display:none;" class="fbs-reset">').addClass(m.pane);r.append(l).append(q);if(i.parent)b(i.parent).append(r);else{r.css("position","absolute");i.zIndex&&r.css("z-index",i.zIndex);b(document.body).append(r)}r.bind("mousedown",
function(n){h.input.data("dont_hide",true);n.stopPropagation()}).bind("mouseup",function(n){h.input.data("dont_hide")&&h.input.focus();h.input.removeData("dont_hide");n.stopPropagation()}).bind("click",function(n){n.stopPropagation();if(n=h.get_selected()){h.onselect(n,true);h.hide_all()}});q.hover(function(n){h.hoverover_list(n)},function(n){h.hoverout_list(n)});this.input=b(f).attr("autocomplete","off").unbind(".suggest").bind("remove.suggest",function(){h._destroy()}).bind("keydown.suggest",function(n){h.keydown(n)}).bind("keypress.suggest",
function(n){h.keypress(n)}).bind("keyup.suggest",function(n){h.keyup(n)}).bind("blur.suggest",function(n){h.blur(n)}).bind("textchange.suggest",function(){h.textchange()}).bind("focus.suggest",function(n){h.focus(n)}).bind(b.browser.msie?"paste.suggest":"input.suggest",function(){clearTimeout(h.paste_timeout);h.paste_timeout=setTimeout(function(){h.textchange()},0)});this.onresize=function(){h.invalidate_position();if(r.is(":visible")){h.position();if(i.flyout&&h.flyoutpane&&h.flyoutpane.is(":visible")){var n=
h.get_selected();n&&h.flyout_position(n)}}};b(window).bind("resize.suggest",this.onresize).bind("scroll.suggest",this.onresize)};b.suggest[a].prototype=b.extend({},b.suggest.prototype,c)};b.suggest.prototype={_init:function(){},_destroy:function(){this.pane.remove();this.list.remove();this.input.unbind(".suggest");b(window).unbind("resize.suggest",this.onresize).unbind("scroll.suggest",this.onresize);this.input.removeData("data.suggest")},invalidate_position:function(){self._position=null},status_start:function(){this.hide_all();
this.status.siblings().hide();if(this._status.START){this.status.text(this._status.START).show();if(!this.pane.is(":visible")){this.position();this.pane_show()}}this._status.LOADING&&this.status.removeClass("loading")},status_loading:function(){this.status.siblings().show();if(this._status.LOADING){this.status.addClass("loading").text(this._status.LOADING).show();if(!this.pane.is(":visible")){this.position();this.pane_show()}}else this.status.hide()},status_select:function(){this.status.siblings().show();
this._status.SELECT?this.status.text(this._status.SELECT).show():this.status.hide();this._status.LOADING&&this.status.removeClass("loading")},status_error:function(){this.status.siblings().show();this._status.ERROR?this.status.text(this._status.ERROR).show():this.status.hide();this._status.LOADING&&this.status.removeClass("loading")},focus:function(a){this.input.val()===""?this.status_start():this.focus_hook(a)},focus_hook:function(){if(!this.input.data("data.suggest")&&!this.pane.is(":visible")&&
b("."+this.options.css.item,this.list).length){this.position();this.pane_show()}},keydown:function(a){var c=a.keyCode;if(c===9)this.tab(a);else if(c===38||c===40)a.shiftKey||a.preventDefault()},keypress:function(a){var c=a.keyCode;if(c===38||c===40)a.shiftKey||a.preventDefault();else c===13&&this.enter(a)},keyup:function(a){var c=a.keyCode;if(c===38){a.preventDefault();this.up(a)}else if(c===40){a.preventDefault();this.down(a)}else if(a.ctrlKey&&c===77)b(".fbs-more-link",this.pane).click();else if(b.suggest.is_char(a)){clearTimeout(this.keypress.timeout);
var f=this;this.keypress.timeout=setTimeout(function(){f.textchange()},0)}else c===27&&this.escape(a);return true},blur:function(a){if(!this.input.data("dont_hide")){this.input.data("data.suggest")||this.check_required(a);this.hide_all()}},tab:function(a){if(!(a.shiftKey||a.metaKey||a.ctrlKey)){a=this.options;a=this.pane.is(":visible")&&b("."+a.css.item,this.list).length;var c=this.get_selected();if(a&&c){this.onselect(c);this.hide_all()}}},enter:function(a){var c=this.options;if(this.pane.is(":visible"))if(a.shiftKey){this.shift_enter(a);
a.preventDefault()}else if(b("."+c.css.item,this.list).length){var f=this.get_selected();if(f){this.onselect(f);this.hide_all();a.preventDefault()}else{f=this.input.data("data.suggest");if(c.soft)f||this.check_required(a);else if(b("."+this.options.css.item+":visible",this.list).length){this.updown(false);a.preventDefault()}else f||this.check_required(a)}}},shift_enter:function(){},escape:function(){this.hide_all()},up:function(a){this.updown(true,a.ctrlKey||a.shiftKey)},down:function(a){this.updown(false,
null,a.ctrlKey||a.shiftKey)},updown:function(a,c,f){var j=this.options.css,h=this.list;if(this.pane.is(":visible")){var i=b("."+j.item+":visible",h);if(i.length){h=b(i[0]);i=b(i[i.length-1]);var k=this.get_selected()||[];clearTimeout(this.ignore_mouseover.timeout);this._ignore_mouseover=false;if(a)if(c)this._goto(h);else if(k.length)if(k[0]==h[0]){h.removeClass(j.selected);this.input.val(this.input.data("original.suggest"));this.hoverout_list()}else this._goto(k.prevAll("."+j.item+":visible:first"));
else this._goto(i);else if(f)this._goto(i);else if(k.length)if(k[0]==i[0]){i.removeClass(j.selected);this.input.val(this.input.data("original.suggest"));this.hoverout_list()}else this._goto(k.nextAll("."+j.item+":visible:first"));else this._goto(h)}}else a||this.textchange()},_goto:function(a){a.trigger("mouseover.suggest");var c=a.data("data.suggest");this.input.val(c?c.name:this.input.data("original.suggest"));this.scroll_to(a)},scroll_to:function(a){var c=this.list,f=c.scrollTop(),j=f+c.innerHeight(),
h=a.outerHeight();a=a.prevAll().length*h;h=a+h;if(a<f){this.ignore_mouseover();c.scrollTop(a)}else if(h>j){this.ignore_mouseover();c.scrollTop(f+h-j)}},textchange:function(){this.input.removeData("data.suggest");this.input.trigger("fb-textchange",this);var a=this.input.val();if(a==="")this.status_start();else{this.status_loading();this.request(a)}},request:function(){},response:function(a){if(a){"cost"in a&&this.trackEvent(this.name,"response","cost",a.cost);if(this.check_response(a)){var c=[];if(b.isArray(a))c=
a;else if("result"in a)c=a.result;var f=b.map(arguments,function(m){return m});this.response_hook.apply(this,f);var j=null,h=this,i=this.options;b.each(c,function(m,l){if(!l.id&&l.mid)l.id=l.mid;var q=h.create_item(l,a).bind("mouseover.suggest",function(r){h.mouseover_item(r)}).data("data.suggest",l);h.list.append(q);if(m===0)j=q});this.input.data("original.suggest",this.input.val());if(b("."+i.css.item,this.list).length===0&&i.nomatch){c=b('<li class="fbs-nomatch">');if(typeof i.nomatch==="string")c.text(i.nomatch);
else{i.nomatch.title&&c.append(b('<em class="fbs-nomatch-text">').text(i.nomatch.title));i.nomatch.heading&&c.append(b("<h3>").text(i.nomatch.heading));if((i=i.nomatch.tips)&&i.length){var k=b('<ul class="fbs-search-tips">');b.each(i,function(m,l){k.append(b("<li>").text(l))});c.append(k)}}c.bind("click.suggest",function(m){m.stopPropagation()});this.list.append(c)}f.push(j);this.show_hook.apply(this,f);this.position();this.pane_show()}}},pane_show:function(){var a=false;if(b("> li",this.list).length)a=
true;a||this.pane.children(":not(."+this.options.css.list+")").each(function(){if(b(this).css("display")!="none"){a=true;return false}});if(a)if(this.options.animate){var c=this;this.pane.slideDown("fast",function(){c.input.trigger("fb-pane-show",c)})}else{this.pane.show();this.input.trigger("fb-pane-show",this)}else{this.pane.hide();this.input.trigger("fb-pane-hide",this)}},create_item:function(a){var c=this.options.css,f=b("<li>").addClass(c.item);a=b("<label>").text(a.name);f.append(b("<div>").addClass(c.item_name).append(a));
return f},mouseover_item:function(a){if(!this._ignore_mouseover){a=a.target;if(a.nodeName.toLowerCase()!=="li")a=b(a).parents("li:first");var c=b(a),f=this.options.css;b("."+f.item,this.list).each(function(){this!==c[0]&&b(this).removeClass(f.selected)});if(!c.hasClass(f.selected)){c.addClass(f.selected);this.mouseover_item_hook(c)}}},mouseover_item_hook:function(){},hoverover_list:function(){},hoverout_list:function(){},check_response:function(){return true},response_hook:function(){this.list.empty()},
show_hook:function(){this.status_select()},position:function(){var a=this.pane,c=this.options;if(!c.parent){if(!self._position){var f=this.input,j=f.offset(),h=f.outerWidth(true),i=f.outerHeight(true);j.top+=i;var k=a.outerWidth(),m=a.outerHeight(),l=j.top+m/2,q=b(window).scrollLeft();f=b(window).scrollTop();var r=b(window).width(),n=b(window).height()+f,o=true;if("left"==c.align)o=true;else if("right"==c.align)o=false;else if(j.left>q+r/2)o=false;if(!o){o=j.left-(k-h);if(o>q)j.left=o}if(l>n){c=j.top-
i-m;if(c>f)j.top=c}this._position=j}a.css({top:this._position.top,left:this._position.left})}},ignore_mouseover:function(){this._ignore_mouseover=true;var a=this;this.ignore_mouseover.timeout=setTimeout(function(){a.ignore_mouseover_reset()},1E3)},ignore_mouseover_reset:function(){this._ignore_mouseover=false},get_selected:function(){var a=null,c=this.options.css.selected;b("li",this.list).each(function(){var f=b(this);if(f.hasClass(c)&&f.is(":visible")){a=f;return false}});return a},onselect:function(a){var c=
a.data("data.suggest");if(c){this.input.val(c.name).data("data.suggest",c).trigger("fb-select",c);this.trackEvent(this.name,"fb-select","index",a.prevAll().length)}},trackEvent:function(a,c,f,j){this.input.trigger("fb-track-event",{category:a,action:c,label:f,value:j})},check_required:function(a){var c=this.options.required;if(c===true){if(this.input.val()!==""){this.input.trigger("fb-required",{domEvent:a});return false}}else if(c==="always"){this.input.trigger("fb-required",{domEvent:a});return false}return true},
hide_all:function(){this.pane.hide();this.input.trigger("fb-pane-hide",this)}};b.extend(b.suggest,{defaults:{status:["Start typing to get suggestions...","Searching...","Select an item from the list:","Sorry, something went wrong. Please try again later"],required:false,soft:false,nomatch:"no matches",css:{pane:"fbs-pane",list:"fbs-list",item:"fbs-item",item_name:"fbs-item-name",selected:"fbs-selected",status:"fbs-status"},css_prefix:null,parent:null,animate:false,zIndex:null},$$:function(a,c){return b("."+
a,c)},use_jsonp:function(a){if(!a)return false;var c=window.location.href;c=c.substr(0,c.length-window.location.pathname.length);if(c===a)return false;return true},strongify:function(a,c){var f,j=a.toLowerCase().indexOf(c.toLowerCase());if(j>=0){var h=c.length;f=document.createTextNode(a.substring(0,j));var i=b("<strong>").text(a.substring(j,j+h));j=document.createTextNode(a.substring(j+h));f=b("<div>").append(f).append(i).append(j)}else f=b("<div>").text(a);return f},keyCode:{CAPS_LOCK:20,CONTROL:17,
DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,INSERT:45,LEFT:37,NUMPAD_ENTER:108,PAGE_DOWN:34,PAGE_UP:33,RIGHT:39,SHIFT:16,SPACE:32,TAB:9,UP:38,OPTION:18,APPLE:224},is_char:function(a){if(a.type==="keypress")if((a.metaKey||a.ctrlKey)&&a.charCode===118)return true;else{if("isChar"in a)return a.isChar}else{var c=b.suggest.keyCode.not_char;if(!c){c={};b.each(b.suggest.keyCode,function(f,j){c[""+j]=1});b.suggest.keyCode.not_char=c}return!(""+a.keyCode in c)}}});var e={_destroy:b.suggest.prototype._destroy,
show_hook:b.suggest.prototype.show_hook};b.suggest("suggest",{_init:function(){var a=this,c=this.options;if(c.flyout_service_url==null)c.flyout_service_url=c.service_url;this.flyout_url=c.flyout_service_url;if(c.flyout_service_path)if(/^\$\{id\}$/.test(c.flyout_service_path))this.flyout_object_url=true;else this.flyout_url+=c.flyout_service_path;this.jsonp=true;this.jsonp_flyout=b.suggest.use_jsonp(c.flyout_url);if(!b.suggest.cache)b.suggest.cache={};if(c.flyout){this.flyoutpane=b('<div style="display:none;" class="fbs-reset">').addClass(c.css.flyoutpane);
if(c.flyout_parent)b(c.flyout_parent).append(this.flyoutpane);else{this.flyoutpane.css("position","absolute");c.zIndex&&this.flyoutpane.css("z-index",c.zIndex);b(document.body).append(this.flyoutpane)}this.flyoutpane.hover(function(f){a.hoverover_list(f)},function(f){a.hoverout_list(f)}).bind("mousedown.suggest",function(f){f.stopPropagation();a.pane.click()});if(!b.suggest.flyout)b.suggest.flyout={};if(!b.suggest.flyout.cache)b.suggest.flyout.cache={}}},_destroy:function(){e._destroy.call(this);
this.flyoutpane&&this.flyoutpane.remove();this.input.removeData("request.count.suggest");this.input.removeData("flyout.request.count.suggest")},shift_enter:function(a){if(this.options.suggest_new){this.suggest_new();this.hide_all()}else this.check_required(a)},hide_all:function(){this.pane.hide();this.flyoutpane&&this.flyoutpane.hide();this.input.trigger("fb-pane-hide",this);this.input.trigger("fb-flyoutpane-hide",this)},request:function(a,c){var f=this,j=this.options;if(this.ac_xhr){this.ac_xhr.abort();
this.ac_xhr=null}var h={query:a,prefixed:true,format:"ac"};if(c)h.cursor=c;b.extend(h,j.ac_param);var i=j.service_url+j.service_path+"?"+b.param(h),k=b.suggest.cache[i];if(k)this.response(k,c?c:-1,true);else{clearTimeout(this.request.timeout);var m={url:j.service_url+j.service_path,data:h,traditional:true,beforeSend:function(){var l=f.input.data("request.count.suggest")||0;l||f.trackEvent(f.name,"start_session");l+=1;f.trackEvent(f.name,"request","count",l);f.input.data("request.count.suggest",l)},
success:function(l){b.suggest.cache[i]=l;l.prefix=a;f.response(l,c?c:-1)},error:function(l){f.status_error();f.trackEvent(f.name,"request","error",{url:this.url,response:l?l.responseText:""});f.input.trigger("fb-error",Array.prototype.slice.call(arguments))},complete:function(l){l&&f.trackEvent(f.name,"request","tid",l.getResponseHeader("X-Metaweb-TID"))},dataType:f.jsonp?"jsonp":"json",cache:true};this.request.timeout=setTimeout(function(){f.ac_xhr=b.ajax(m)},j.xhr_delay)}},create_item:function(a,
c){var f=this.options.css,j=b("<li>").addClass(f.item),h=b("<div>").addClass(f.item_name).append(b("<label>").append(b.suggest.strongify(a.name||a.id,c.prefix)));j.append(h);var i=a.notable;f=b("<div>").addClass(f.item_type);i&&i.name&&f.text(i.name);h.prepend(f);return j},mouseover_item_hook:function(a){a=a.data("data.suggest");this.options.flyout&&a&&this.flyout_request(a)},check_response:function(a){return a.prefix===this.input.val()},response_hook:function(a,c){this.flyoutpane&&this.flyoutpane.hide();
c>0?b(".fbs-more",this.pane).remove():this.list.empty()},show_hook:function(a,c,f){e.show_hook.apply(this,[a]);var j=this.options,h=this,i=this.pane,k=this.list,m=a.result,l=b(".fbs-more",i),q=b(".fbs-suggestnew",i);b(".fbs-status",i);var r=a.correction;if(r&&r.length){var n=b('<a class="fbs-spell-link" href="#">').append(r[0]).bind("click.suggest",function(o){o.preventDefault();o.stopPropagation();h.input.val(r[0]).trigger("textchange")});h.status.empty().append("Search instead for ").append(n).show()}if(m&&
m.length&&"cursor"in a){if(!l.length){m=b('<a class="fbs-more-link" href="#" title="(Ctrl+m)">view more</a>');l=b('<div class="fbs-more">').append(m);m.bind("click.suggest",function(o){o.preventDefault();o.stopPropagation();o=b(this).parent(".fbs-more");h.more(o.data("cursor.suggest"))});k.after(l)}l.data("cursor.suggest",a.cursor);l.show()}else l.remove();if(j.suggest_new){if(!q.length){a=b('<button class="fbs-suggestnew-button">');a.text(j.suggest_new);q=b('<div class="fbs-suggestnew">').append('<div class="fbs-suggestnew-description">Your item not in the list?</div>').append(a).append('<span class="fbs-suggestnew-shortcut">(Shift+Enter)</span>').bind("click.suggest",
function(o){o.stopPropagation();h.suggest_new(o)});i.append(q)}q.show()}else q.remove();if(f&&f.length&&c>0){c=f.prevAll().length*f.outerHeight();k.scrollTop();k.animate({scrollTop:c},"slow",function(){f.trigger("mouseover.suggest")})}},suggest_new:function(){var a=this.input.val();if(a!==""){this.input.data("data.suggest",a).trigger("fb-select-new",a);this.trackEvent(this.name,"fb-select-new","index","new");this.hide_all()}},more:function(a){if(a){var c=this.input.data("original.suggest");c!==null&&
this.input.val(c);this.request(this.input.val(),a);this.trackEvent(this.name,"more","cursor",a)}return false},flyout_request:function(a){var c=this;if(this.flyout_xhr){this.flyout_xhr.abort();this.flyout_xhr=null}var f=this.options,j=this.flyoutpane.data("data.suggest");if(j&&a.id===j.id){if(!this.flyoutpane.is(":visible")){this.flyout_position(this.get_selected());this.flyoutpane.show();this.input.trigger("fb-flyoutpane-show",this)}}else if((j=b.suggest.flyout.cache[a.id])&&j.id&&j.html)this.flyout_response(j);
else{j=this.flyout_url;var h=a.id;a=null;if(this.flyout_object_url)j+=h+"?flyout";else a={id:h};var i={url:j,data:a,traditional:true,beforeSend:function(){var k=c.input.data("flyout.request.count.suggest")||0;k+=1;c.trackEvent(c.name,"flyout.request","count",k);c.input.data("flyout.request.count.suggest",k)},success:function(k){k=c.jsonp_flyout?k:{id:h,html:k};b.suggest.flyout.cache[k.id]=k;c.flyout_response(k)},error:function(k){c.trackEvent(c.name,"flyout","error",{url:this.url,response:k?k.responseText:
""})},complete:function(k){k&&c.trackEvent(c.name,"flyout","tid",k.getResponseHeader("X-Metaweb-TID"))},dataType:c.jsonp_flyout?"jsonp":"html",cache:true};clearTimeout(this.flyout_request.timeout);this.flyout_request.timeout=setTimeout(function(){c.flyout_xhr=b.ajax(i)},f.xhr_delay);this.input.trigger("fb-request-flyout",i)}},flyout_response:function(a){var c=this.pane,f=this.get_selected()||[];if(c.is(":visible")&&f.length)if((c=f.data("data.suggest"))&&a.id===c.id&&a.html){this.flyoutpane.html(a.html);
this.flyout_position(f);this.flyoutpane.show().data("data.suggest",c);this.input.trigger("fb-flyoutpane-show",this)}},flyout_position:function(a){if(!this.options.flyout_parent){var c=this.pane,f=this.flyoutpane,j=this.options.css,h=g,i={top:parseInt(f.css("top"),10),left:parseInt(f.css("left"),10)},k=c.offset(),m=c.outerWidth(),l=f.outerHeight(),q=f.outerWidth();if(this.options.flyout==="bottom"){h=k;m=this.input.offset();if(k.top<m.top)h.top-=l;else h.top+=c.outerHeight();f.addClass(j.flyoutpane+
"-bottom")}else{h=a.offset();a=a.outerHeight();h.left+=m;var r=h.left+q;c=b(document.body).scrollLeft();var n=b(window).width()+c;h.top=h.top+a-l;if(h.top<k.top)h.top=k.top;if(r>n){k=h.left-(m+q);if(k>c)h.left=k}f.removeClass(j.flyoutpane+"-bottom")}h.top===i.top&&h.left===i.left||f.css({top:h.top,left:h.left})}},hoverout_list:function(){this.flyoutpane&&!this.get_selected()&&this.flyoutpane.hide()}});b.extend(b.suggest.suggest,{defaults:{filter:null,spell:"always",exact:false,lang:null,key:null,
service_url:"https://www.googleapis.com",service_path:"/freebase/v1/search",align:null,flyout:true,flyout_service_url:"http://www.freebase.com",flyout_service_path:"/private/flyout",flyout_parent:null,suggest_new:null,nomatch:{title:"No suggested matches",heading:"Tips on getting better suggestions:",tips:["Enter more or fewer characters","Add words related to your original search","Try alternate spellings","Check your spelling"]},css:{item_type:"fbs-item-type",flyoutpane:"fbs-flyout-pane"},xhr_delay:200}});
document.createElement("input")})(jQuery);
(function(b){b.fn.extend({simulate:function(g,d){return this.each(function(){var e=b.extend({},b.simulate.defaults,d||{});new b.simulate(this,g,e)})}});b.simulate=function(g,d,e){this.target=g;this.options=e;/^drag$/.test(d)?this[d].apply(this,[this.target,e]):this.simulateEvent(g,d,e)};b.extend(b.simulate.prototype,{simulateEvent:function(g,d,e){var a=this.createEvent(d,e);this.dispatchEvent(g,d,a,e);return a},createEvent:function(g,d){if(/^mouse(over|out|down|up|move)|(dbl)?click$/.test(g))return this.mouseEvent(g,d);
else if(/^key(up|down|press)$/.test(g))return this.keyboardEvent(g,d)},mouseEvent:function(g,d){var e,a=b.extend({bubbles:true,cancelable:g!="mousemove",view:window,detail:0,screenX:0,screenY:0,clientX:0,clientY:0,ctrlKey:false,altKey:false,shiftKey:false,metaKey:false,button:0,relatedTarget:undefined},d);b(a.relatedTarget);if(b.isFunction(document.createEvent)){e=document.createEvent("MouseEvents");e.initMouseEvent(g,a.bubbles,a.cancelable,a.view,a.detail,a.screenX,a.screenY,a.clientX,a.clientY,
a.ctrlKey,a.altKey,a.shiftKey,a.metaKey,a.button,a.relatedTarget||document.body.parentNode)}else if(document.createEventObject){e=document.createEventObject();b.extend(e,a);e.button={0:1,1:4,2:2}[e.button]||e.button}return e},keyboardEvent:function(g,d){var e,a=b.extend({bubbles:true,cancelable:true,view:window,ctrlKey:false,altKey:false,shiftKey:false,metaKey:false,keyCode:0,charCode:0},d);if(b.isFunction(document.createEvent))try{e=document.createEvent("KeyEvents");e.initKeyEvent(g,a.bubbles,a.cancelable,
a.view,a.ctrlKey,a.altKey,a.shiftKey,a.metaKey,a.keyCode,a.charCode)}catch(c){e=document.createEvent("Events");e.initEvent(g,a.bubbles,a.cancelable);b.extend(e,{view:a.view,ctrlKey:a.ctrlKey,altKey:a.altKey,shiftKey:a.shiftKey,metaKey:a.metaKey,keyCode:a.keyCode,charCode:a.charCode})}else if(document.createEventObject){e=document.createEventObject();b.extend(e,a)}if(b.browser.msie||b.browser.opera){e.keyCode=a.charCode>0?a.charCode:a.keyCode;e.charCode=undefined}return e},dispatchEvent:function(g,
d,e){if(g.dispatchEvent)g.dispatchEvent(e);else g.fireEvent&&g.fireEvent("on"+d,e);return e},drag:function(){var g=this.findCenter(this.target),d=this.options,e=Math.floor(g.x);g=Math.floor(g.y);var a=d.dx||0;d=d.dy||0;var c=this.target,f={clientX:e,clientY:g};this.simulateEvent(c,"mousedown",f);f={clientX:e+1,clientY:g+1};this.simulateEvent(document,"mousemove",f);f={clientX:e+a,clientY:g+d};this.simulateEvent(document,"mousemove",f);this.simulateEvent(document,"mousemove",f);this.simulateEvent(c,
"mouseup",f)},findCenter:function(g){g=b(this.target);var d=g.offset();return{x:d.left+g.outerWidth()/2,y:d.top+g.outerHeight()/2}}});b.extend(b.simulate,{defaults:{speed:"sync"},VK_TAB:9,VK_ENTER:13,VK_ESC:27,VK_PGUP:33,VK_PGDN:34,VK_END:35,VK_HOME:36,VK_LEFT:37,VK_UP:38,VK_RIGHT:39,VK_DOWN:40})})(jQuery);var test_input1,test_input2,test_input3,test_input4,TIMEOUT_DELAY=5E3;$(function(){test_input1=$("#test1");test_input2=$("#test2");test_input3=$("#test3");test_input4=$("#test4")});
var module_options={setup:function(){},teardown:function(){$.suggest.cache={};if($.suggest.flyout)$.suggest.flyout.cache={};$.each([test_input1,test_input2,test_input3,test_input4],function(b,g){g.unbind();var d=get_instance(g);d&&d._destroy();g.val("")})}},default_options={service_path:"/freebase/v1/search",key:"AIzaSyBij3tRJN2VdWiLQN48-BmPFjNWpHe7MQE",flyout_service_url:"",flyout_service_path:"${id}"},test_value="bob dyla",bob_dylan_id="/m/01vrncs",position_threshold=10;
function get_instance(b){b=b||test_input1;return b.data("suggest")}function simulate_keypress(b,g){var d=g;if(typeof d!=="object")d={keyCode:d};b.simulate("keydown",d);b.simulate("keyup",d);b.simulate("keypress",d)}function simulate_mouseclick(b){b.simulate("mousedown").simulate("mouseup").simulate("mouseclick").click()}
$(function(){function b(d){var e=get_instance();ok(e.pane.hasClass(d.pane),"css.pane");ok(e.status.hasClass(d.status),"css.status");ok(e.list.hasClass(d.list),"css.list");ok(e.flyoutpane.hasClass(d.flyoutpane),"css.flyoutpane");stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",function(){if($(">li",e.list).length){$(">li",e.list).each(function(){$(this).hasClass(d.item);var a=$("."+d.item_name,this);equals(a.length,1);a=$("."+d.item_type,a);equals(a.length,1)});start()}}).val("css").trigger("textchange")}
function g(d,e,a,c){d=$.extend({},default_options,d);test_input1.suggest(d);var f=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",function(){var j=false,h;h=typeof a==="function"?function(k){return a(k)}:function(k){return k.id===a};var i=$(">li",f.list);if(i.length){i.each(function(){var k=$(this).data("data.suggest");if(j=h(k))return false});ok(j);start()}else if(c){ok(c());start()}}).val(e).trigger("textchange")}module("options",module_options);test("css_prefix",function(){var d=
$.extend({},default_options,{css_prefix:"test-"});test_input1.suggest(d);var e={};d=$.extend(true,{},$.suggest.defaults.css,$.suggest.suggest.defaults.css);$.each(d,function(a,c){e[a]="test-"+c});b(e)});test("css",function(){var d={pane:"my-pane",list:"my-list",item:"my-item",item_name:"my-item-name",selected:"my-selected",status:"my-status",item_type:"my-item-type",flyoutpane:"my-flyout-pane"},e=$.extend({},default_options,{css:d});test_input1.suggest(e);b(d)});test("parent",1,function(){var d=$('<div id="parent">');
$(document.body).append(d);var e=$.extend({},default_options,{parent:"#parent"});test_input1.suggest(e);var a=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",function(){if($(">li",a.list).length){equals(a.pane.parent()[0],d[0]);start()}}).val("bob dyl").trigger("textchange")});test("flyout_parent",1,function(){var d=$('<div id="flyout_parent">');$(document.body).append(d);var e=$.extend({},default_options,{flyout_parent:"#flyout_parent"});test_input1.suggest(e);var a=get_instance();
stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",function(){$("li:first",a.list).trigger("mouseover")}).bind("fb-flyoutpane-show",function(){equals(a.flyoutpane.parent()[0],d[0]);start()}).val("stephen colb").trigger("textchange")});test("status[0]",1,function(){var d=$.extend({},default_options,{status:["0","1","2","3"]});test_input1.suggest(d);d=get_instance();test_input1.val("").trigger("textchange");equals(d.status.text(),"0")});test("status[1]",1,function(){var d=$.extend({},default_options,
{status:["0","1","2","3"]});test_input1.suggest(d);d=get_instance();test_input1.val("obama").trigger("textchange");equals(d.status.text(),"1")});test("status[2]",1,function(){var d=$.extend({},default_options,{status:["0","1","2","3"]});test_input1.suggest(d);var e=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",function(){if($(">li",e.list).length){equals(e.status.text(),"2");start()}}).val("hillary cli").trigger("textchange")});test("status[3]",1,function(){var d=$.extend({},
default_options,{status:["0","1","2","3"]});test_input1.suggest(d);d=get_instance();d.status_error();equals(d.status.text(),"3")});test("required=true",1,function(){var d=$.extend({},default_options,{required:true});test_input1.suggest(d);d=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-required",function(){ok(true);start()}).val("sakuragi hana").trigger("textchange");d.blur()});test("required=always",1,function(){var d=$.extend({},default_options,{required:"always"});test_input1.suggest(d);
d=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-required",function(){ok(true);start()}).val("").trigger("textchange");d.blur()});test("zIndex",1,function(){var d=$.extend({},default_options,{zIndex:1E3});test_input1.suggest(d);var e=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",function(){equals(e.pane.css("z-index"),1E3);start()}).val("shohoku").trigger("textchange")});test("flyout=false",1,function(){var d=$.extend({},default_options,{flyout:false});test_input1.suggest(d);
var e=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",function(){if($(">li",e.list).length){$("li:first",e.list).trigger("mouseover");if(!e.flyoutpane){ok("flyout not shown");start()}}}).bind("fb-flyoutpane-show",function(){fail("flyout shown when flyout=false");start()}).val("avatar").trigger("textchange")});test("flyout=bottom",1,function(){var d=$.extend({},default_options,{flyout:"bottom"});test_input1.suggest(d);var e=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",
function(){$("li:first",e.list).trigger("mouseover")}).bind("fb-flyoutpane-show",function(){var a=e.pane.offset(),c=e.flyoutpane.offset();ok(Math.abs(c.top-(a.top+e.pane.height()))<position_threshold);start()}).val("avatar").trigger("textchange")});test("align=left",1,function(){var d=$.extend({},default_options,{align:"left"});test_input1.suggest(d);var e=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",function(){if($(">li",e.list).length){ok(Math.abs(e.pane.offset().left-test_input1.offset().left)<
position_threshold);start()}}).val("lady ga").trigger("textchange")});test("align=right",1,function(){var d=$.extend({},default_options,{align:"right"});test_input3.suggest(d);var e=get_instance(test_input3);stop(TIMEOUT_DELAY);test_input3.bind("fb-pane-show",function(){if($(">li",e.list).length){var a=e.pane.offset().left+e.pane.width(),c=test_input3.offset().left+test_input3.width();ok(Math.abs(a-c)<position_threshold);start()}}).val("jessica alb").trigger("textchange")});test("suggest_new",1,function(){var d=
$.extend({},default_options,{suggest_new:"suggest_new"});test_input1.suggest(d);var e=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",function(){if($(">li",e.list).length){equals($("button:first",e.pane).text(),"suggest_new");start()}}).val("aplusk").trigger("textchange")});$.each(["(any type:/music/artist)","(any type:/people/person type:/music/artist)","(all type:/music/artist)","(all type:/people/person type:/music/artist)","(should type:/music/artist)","(should type:/people/person)"],
function(d,e){test("filter="+e,1,function(){g({filter:e},"bob dylan",bob_dylan_id)})});test("lang [default]",function(){g(null,"/en/seoul",function(d){return d.name==="Seoul"})});test("lang=en",function(){g({lang:"en"},"/en/seoul",function(d){return d.name==="Seoul"})});test("lang=ko",function(){g({lang:"ko"},"/en/seoul",function(d){return d.name.indexOf("\uc11c\uc6b8")!==-1})});test("lang=es,ko",function(){g({lang:"es,ko"},"/en/cheong_wa_dae",function(d){return d.name==="\uccad\uc640\ub300"})});
test("spell=always",function(){var d=$.extend({},default_options,{spell:"always"});test_input1.suggest(d);var e=get_instance(),a=false;stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",function(){var c=$(">li",e.list);if(a&&c.length){ok(true,"Got spell correction results");start()}else if($(".fbs-spell-link",e.pane).length){ok(true,"Found spell/correction");$(".fbs-spell-link",e.pane).click();a=true}}).val("Bob Dylon").trigger("textchange")});test("exact [default]",function(){g(null,"Bob Dylon",
bob_dylan_id)});test("exact=false",function(){g(null,"Bob Dylon",bob_dylan_id)});test("exact=true",function(){g(null,"Bob Dylon",function(){return false},function(){return true})})});
$(function(){module("events",module_options);test("fb-pane-show",1,function(){test_input1.suggest(default_options);var b=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",function(){if($(">li",b.list).length){ok(true,"got fb-pane-show");start()}}).focus().val("bob dylan").trigger("textchange")});test("fb-flyoutpane-show",1,function(){test_input1.suggest(default_options);var b=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-flyoutpane-show",function(){ok(true,"got fb-flyoutpane-show");
start()}).bind("fb-pane-show",function(){$(">li",b.list).length&&$("li:first",b.list).simulate("mouseover")}).focus().val("bob dylan").trigger("textchange")});test("fb-select",2,function(){var b=$.extend({},default_options,{filter:"(any type:/music/artist)"});test_input1.suggest(b);var g=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-select",function(d,e){ok(e);equals(e.id,bob_dylan_id);start()}).bind("fb-pane-show",function(){if($(">li",g.list).length){$("li:first",g.list).simulate("mouseover");
simulate_keypress(test_input1,$.simulate.VK_ENTER)}}).focus().val(bob_dylan_id).trigger("textchange")});test("fb-select-new",1,function(){var b=$.extend({},default_options,{suggest_new:"new"});test_input1.suggest(b);var g=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-select-new",function(d,e){equals(e,"bob dylan");start()}).bind("fb-pane-show",function(){$(">li",g.list).length&&$(".fbs-suggestnew",g.pane).click()}).focus().val("bob dylan").trigger("textchange")});test("fb-textchange",1,
function(){test_input1.suggest(default_options);stop(TIMEOUT_DELAY);test_input1.bind("fb-textchange",function(){ok(true,"got fb-textchange");start()}).focus();simulate_keypress(test_input1,68)})});
$(function(){function b(g,d){test("select: "+g,2,function(){var e=$.extend({},default_options,{filter:"(any type:/music/artist)"});test_input1.suggest(e);var a=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-select",function(c,f){ok(f);equals(f.id,bob_dylan_id);start()}).bind("fb-pane-show",function(){$(">li",a.list).length&&d()}).focus().val(bob_dylan_id).trigger("textchange")})}module("ux",module_options);b("MOUSEOVER MOUSECLICK",function(){var g=get_instance();g=$("li:first",g.list).simulate("mouseover");
simulate_mouseclick(g)});b("MOUSEOVER ENTER",function(){var g=get_instance();$("li:first",g.list).simulate("mouseover");simulate_keypress(test_input1,$.simulate.VK_ENTER)});b("ENTER ENTER",function(){simulate_keypress(test_input1,$.simulate.VK_ENTER);simulate_keypress(test_input1,$.simulate.VK_ENTER)});b("DOWN ENTER",function(){simulate_keypress(test_input1,$.simulate.VK_DOWN);simulate_keypress(test_input1,$.simulate.VK_ENTER)});b("UP DOWN DOWN ENTER",function(){simulate_keypress(test_input1,$.simulate.VK_UP);
simulate_keypress(test_input1,$.simulate.VK_DOWN);simulate_keypress(test_input1,$.simulate.VK_DOWN);simulate_keypress(test_input1,$.simulate.VK_ENTER)});b("CTRL+UP ENTER",function(){simulate_keypress(test_input1,{keyCode:$.simulate.VK_UP,ctrlKey:true});simulate_keypress(test_input1,$.simulate.VK_ENTER)});b("CTRL+DOWN DOWN DOWN ENTER",function(){simulate_keypress(test_input1,{keyCode:$.simulate.VK_DOWN,ctrlKey:true});simulate_keypress(test_input1,$.simulate.VK_DOWN);simulate_keypress(test_input1,$.simulate.VK_DOWN);
simulate_keypress(test_input1,$.simulate.VK_ENTER)});test("select: flyout",2,function(){var g=$.extend({},default_options,{filter:"(any type:/music/artist)"});test_input1.suggest(g);var d=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-select",function(e,a){ok(a);equals(a.id,bob_dylan_id);start()}).bind("fb-flyoutpane-show",function(){simulate_mouseclick(d.flyoutpane)}).bind("fb-pane-show",function(){$(">li",d.list).length&&simulate_keypress(test_input1,$.simulate.VK_DOWN)}).focus().val(bob_dylan_id).trigger("textchange")});
test("suggest_new: SHIFT+ENTER",1,function(){var g=$.extend({},default_options,{suggest_new:"new"});test_input1.suggest(g);var d=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-select-new",function(e,a){equals(a,"bob dylan");start()}).bind("fb-pane-show",function(){$(">li",d.list).length&&simulate_keypress(test_input1,{keyCode:$.simulate.VK_ENTER,shiftKey:true})}).focus().val("bob dylan").trigger("textchange")});test("more: CLICK",1,function(){var g=$.extend({},default_options,{filter:"(any type:/music/artist)"});
test_input1.suggest(g);var d=get_instance(),e=false,a=0;stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",function(){if(e){ok($(">li",d.list).length>a,"got more");start()}else if(a=$(">li",d.list).length){$(".fbs-more-link",d.pane).click();e=true}}).focus().val("bob dylan").trigger("textchange")});test("more: CTRL+M",1,function(){var g=$.extend({},default_options,{filter:"(any type:/music/artist)"});test_input1.suggest(g);var d=get_instance(),e=false,a=0;stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",
function(){if(e){ok($(">li",d.list).length>a,"got more");start()}else if(a=$(">li",d.list).length){simulate_keypress(test_input1,{keyCode:77,ctrlKey:true});e=true}}).focus().val("bob dylan").trigger("textchange")});test("cancel: ESC",2,function(){var g=$.extend({},default_options,{filter:"(any type:/music/artist)"});test_input1.suggest(g);var d=get_instance();stop(TIMEOUT_DELAY);test_input1.bind("fb-pane-show",function(){if($(">li",d.list).length){ok(d.pane.is(":visible"),"pane visible");simulate_keypress(test_input1,
$.simulate.VK_ESC);ok(!d.pane.is(":visible"),"pane NOT visible");start()}}).focus().val("bob dylan").trigger("textchange")})});
$(function(){module("functional",module_options);test("remove",function(){var b=$.extend({},default_options,{type:"/music/artist"});test_input4.suggest(b);b=get_instance(test_input4);var g=b.pane,d=b.flyoutpane;ok(b,"suggest initialized");test_input4.remove();ok(!g.parent().is("body"),"suggest pane not removed");ok(!d.parent().is("body"),"suggest flyoutpane not removed")});test("flyout abort (CLI-10009)",function(){test_input1.suggest(default_options);var b=get_instance();stop(TIMEOUT_DELAY);var g;
test_input1.bind("fb-flyoutpane-show",function(){ok(true,"got fb-flyoutpane-show");ok(b.flyoutpane.html(),"got non-empty flyout pane");start()}).bind("fb-request-flyout",function(){clearTimeout(b.flyout_request.timeout);var d=g.data("data.suggest").id;$.suggest.flyout.cache[d]={id:d};test_input1.unbind("fb-request-flyout").trigger("textchange")}).bind("fb-pane-show",function(){if($(">li",b.list).length){g=$("li:first",b.list);g.simulate("mouseover")}}).focus().val("bob dylan").trigger("textchange")})});
$(function(){var b={teardown:module_options.teardown,response:$.suggest.suggest.prototype.response};module("xss",$.extend({},module_options,{teardown:function(){b.teardown.apply();$.suggest.suggest.prototype.response=b.response}}));test("script_injection",function(){test_input1.suggest(default_options);var g=get_instance();$.suggest.suggest.prototype.response=function(d){var e=d.result;if(e&&e.length)e[0].name="<script>$(document.body).append('<div id=\"xss\">XSS</div>')<\/script>";return b.response.apply(this,
arguments)};stop(TIMEOUT_DELAY);test_input1.bind("fb-select",function(d,e){ok(e);equals(e.name,"<script>$(document.body).append('<div id=\"xss\">XSS</div>')<\/script>");var a=$("#xss");ok(!a.length,"script injection!");start()}).bind("fb-pane-show",function(){if($(">li",g.list).length){$("li:first",g.list).simulate("mouseover");simulate_keypress(test_input1,$.simulate.VK_ENTER)}}).focus().val("bob dylan").trigger("textchange")});test("script_injection strongified",function(){test_input1.suggest(default_options);
var g=get_instance();$.suggest.suggest.prototype.response=function(d){var e=d.result;if(e&&e.length)e[0].name="bob dylan<script>$(document.body).append('<div id=\"xss\">XSS</div>')<\/script>";return b.response.apply(this,arguments)};stop(TIMEOUT_DELAY);test_input1.bind("fb-select",function(d,e){ok(e);equals(e.name,"bob dylan<script>$(document.body).append('<div id=\"xss\">XSS</div>')<\/script>");var a=$("#xss");ok(!a.length,"script injection!");start()}).bind("fb-pane-show",function(){if($(">li",
g.list).length){$("li:first",g.list).simulate("mouseover");simulate_keypress(test_input1,$.simulate.VK_ENTER)}}).focus().val("bob dylan").trigger("textchange")});test("link_injection",function(){test_input1.suggest(default_options);var g=get_instance();$.suggest.suggest.prototype.response=function(d){var e=d.result;if(e&&e.length)e[0].name='<a href="javascript:alert("XSS");">click me</a>';return b.response.apply(this,arguments)};stop(TIMEOUT_DELAY);test_input1.bind("fb-select",function(d,e){ok(e);
equals(e.name,'<a href="javascript:alert("XSS");">click me</a>');var a=$("li:first",g.list);a=$("a",a);ok(!a.length,"link injection!");start()}).bind("fb-pane-show",function(){if($(">li",g.list).length){$("li:first",g.list).simulate("mouseover");simulate_keypress(test_input1,$.simulate.VK_ENTER)}}).focus().val("bob dylan").trigger("textchange")});test("link_injection strongified",function(){test_input1.suggest(default_options);var g=get_instance();$.suggest.suggest.prototype.response=function(d){var e=
d.result;if(e&&e.length)e[0].name='<a href="javascript:alert("XSS");">click me</a>bob dylan';return b.response.apply(this,arguments)};stop(TIMEOUT_DELAY);test_input1.bind("fb-select",function(d,e){ok(e);equals(e.name,'<a href="javascript:alert("XSS");">click me</a>bob dylan');var a=$("li:first",g.list);a=$("a",a);ok(!a.length,"link injection!");start()}).bind("fb-pane-show",function(){if($(">li",g.list).length){$("li:first",g.list).simulate("mouseover");simulate_keypress(test_input1,$.simulate.VK_ENTER)}}).focus().val("bob dylan").trigger("textchange")})});
