
/*
 * Copyright 2012, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Additional Licenses for Third Party components can be found here:
 * http://wiki.freebase.com/wiki/Freebase_Site_License
 *
 */
function CodeAssist(a,e,b){this._container=a;this._editor=e;this._options=b;this._assistKeyComboDetected=!1;this._autoAssistTimerID=null;var d=this;try{$(e.win.document).keyup(function(a){return d._onEditorKeyUp(a)}).keydown(function(a){return d._onEditorKeyDown(a)}).keypress(function(a){return d._onEditorKeyPress(a)}).mousedown(function(a){return d._onEditorMouseDown(a)})}catch(c){alert("Unable to install keyup handler on codemirror window")}}CodeAssist.helperUrl=fb.acre.appeditor.service_path;
CodeAssist.prototype.dispose=function(){this._cancelPopup();this._cancelAutoAssist()};CodeAssist.prototype.getSetting=function(a){switch(a){case "dotTrigger":return this._options.dotTrigger}return null};CodeAssist.prototype.putSetting=function(a,e){switch(a){case "dotTrigger":this._options.dotTrigger=e}};CodeAssist.prototype._onEditorMouseDown=function(){};
CodeAssist.prototype._onEditorKeyDown=function(a){if(32==a.keyCode&&(a.ctrlKey||a.metaKey||a.altKey))return this._assistKeyComboDetected=!0,a.preventDefault(),!1;8==a.keyCode&&this._cancelPopup()};CodeAssist.prototype._onEditorKeyUp=function(a){if(this._assistKeyComboDetected)return this._assistKeyComboDetected=!1,this.startAssistAtCursor(""),a.preventDefault(),!1};
CodeAssist.prototype._onEditorKeyPress=function(a){!a.shiftKey&&32==a.keyCode||32==a.charCode||(this._cancelAutoAssist(),!a.ctrlKey&&(!a.metaKey&&!a.altKey)&&(this._options.dotTrigger&&(!a.shiftKey&&46==a.keyCode||46==a.charCode)?this._scheduleAutoAssist("."):!a.shiftKey&&188==a.keyCode||44==a.charCode?this._scheduleAutoAssist(","):a.shiftKey&&57==a.keyCode||40==a.charCode?this._scheduleAutoAssist("("):a.shiftKey&&48==a.keyCode||41==a.charCode?this._cancelPopup():(38==a.keyCode||40==a.keyCode||33==
a.keyCode||34==a.keyCode||35==a.keyCode||36==a.keyCode)&&this._cancelPopup()))};CodeAssist.prototype._cancelAutoAssist=function(){null!=this._autoAssistTimerID&&(window.clearTimeout(this._autoAssistTimerID),this._autoAssistTimerID=null)};CodeAssist.prototype._scheduleAutoAssist=function(a){var e=this;this._autoAssistTimerID=window.setTimeout(function(){e._autoAssistTimerID=null;e.startAssistAtCursor(a)},"."==a?1E3:200)};
CodeAssist.prototype._findCurrentNode=function(a,e,b){e=this._editor.win.document.body.firstChild;a=a.line||e;for(e=a.nextSibling;0<b&&null!=e&&(1!=e.nodeType||"br"!=e.tagName.toLowerCase())&&null!=e.firstChild&&e.firstChild.nodeValue.length<b;)b-=e.firstChild.nodeValue.length,a=e,e=e.nextSibling;var d,c,g;null==e||"br"==e.tagName.toLowerCase()?(null!=e?(c=$(e).offset(),$.browser.msie&&null!=a&&"br"!=a.tagName.toLowerCase()?(d=a.offsetWidth,g=a.offsetHeight):(d=c.left,g=e.offsetHeight)):(c=$(a).offset(),
d=a.firstChild?a.firstChild.nodeValue.length:0,d=c.left+(0==d?0:b*a.offsetWidth/d),g=a.offsetHeight),c=c.top):(c=$(e).offset(),d=e.firstChild?e.firstChild.nodeValue.length:0,d=c.left+(0==d?0:b*e.offsetWidth/d),c=c.top,g=e.offsetHeight);return null!=e?{left:d,top:c,height:g,currentNode:e,currentNodeOffset:b}:{left:d,top:c,height:g,currentNode:a,currentNodeOffset:null!=a&&null!=a.firstChild?a.firstChild.nodeValue.length:0}};
CodeAssist.prototype.startAssistAtCursor=function(a){this._cancelPopup();this._cancelAutoAssist();var e=this._editor.cursorPosition(!1),b=this._editor.lineNumber(e.line)-1,d=e.character,c=this._editor.lineContent(e.line),e=this._findCurrentNode(e,b,d,c),c=e.currentNode,g=e.currentNodeOffset;if(null!=g){if(0==c.className.indexOf("xml-")){var f=!1;if("xml-attribute"==c.className){for(var h="",f=c.previousSibling;null!=f&&"xml-tagname"!=f.className&&"xml-tagname-acre"!=f.className;)"xml-attname"==f.className&&
(h=f.firstChild.nodeValue),f=f.previousSibling;c=c.firstChild.nodeValue.replace(/^["']/,"").replace(/["']$/,"");g-=1;f=0>h.indexOf("acre:")&&(null==f||"xml-tagname-acre"!=f.className)}else if("xml-text"==c.className)c=c.firstChild.nodeValue,f=!0;else return;h=0;if(f){var h=c.substr(0,g),i=h.lastIndexOf("{"),f=h.lastIndexOf("}");if(0<i&&"$"==h.charAt(i-1)&&f<i)h=i+1;else if(h=h.lastIndexOf("$"),0<=h&&f<h)h+=1;else return}c=c.substr(h);g-=h}else if("br"==c.tagName.toLowerCase()||"whitespace"==c.className||
0==c.className.indexOf("js-")&&"js-comment"!=c.className){if(("br"==c.tagName.toLowerCase()||"whitespace"==c.className)&&this._options.isMjt){for(f=c.previousSibling;null!=f&&0>f.className.indexOf("xml-")&&0!=f.className.indexOf("js-");)f=f.previousSibling;if(null==f)return;if("xml-punctuation"==f.className&&">"==f.firstChild.nodeValue){if(f=f.previousSibling,null==f||"xml-tagname-acre"!=f.className||"acre:script"!=f.firstChild.nodeValue)return}else if(0==f.className.indexOf("xml-"))return}h=[];for(f=
c.previousSibling;null!=f&&0>f.className.indexOf("xml-");)"br"==f.tagName.toLowerCase()?h.unshift("\n"):h.unshift(f.firstChild.nodeValue),f=f.previousSibling;h=h.join("");c=h+(null!=c.firstChild?c.firstChild.nodeValue.substr(0,g):"");g=h.length+g}else return;"("==a||","==a?this._internalStartFunctionArgumentAssist({left:e.left,top:e.top,height:e.height},b,d,c,g):this._internalStartApiAssist({left:e.left,top:e.top,height:e.height},b,d,c,g)}};
CodeAssist.prototype._cancelPopup=function(){"_popup"in this&&null!=this._popup&&(this._popup.cancel(),this._popup=null)};
CodeAssist.prototype._internalStartApiAssist=function(a,e,b,d,c){for(var d=new CodeAssist.QueryTokenizer(d,0,c),c=[],g;null!=(g=d.token());)c.push(g),d.next();if(!(0<c.length&&c[c.length-1].type==CodeAssist.Token.Types.numberLiteral)){for(var d=[],f=c.length-1;0<=f;f--)if(g=c[f],g.type==CodeAssist.Token.Types.identifier)d.unshift(g.content);else if(g.type==CodeAssist.Token.Types.operator&&"."==g.content)d.unshift(".");else if(g.type==CodeAssist.Token.Types.error){if(0==d.length)return;break}else if(g.type!=
CodeAssist.Token.Types.whitespace)break;for(d=d.join("");;)if(c=d.replace(/\.\./g,"."),d!=c)d=c;else break;var h=this,i=$(this._container).offset();i.left-=this._editor.win.document.body.scrollLeft+document.body.scrollLeft;i.top-=this._editor.win.document.body.scrollTop+document.body.scrollTop;c=d.lastIndexOf(".");if(0<=c)var k=d.substr(c+1),d=d.substr(0,c);else k=d,d="";var j=function(a,c,d,f){try{var g=h._editor.nthLine(e+1),i=b-k.length;h._editor.selectLines(g,i,g,b);h._editor.editor.replaceSelection(a)}catch(j){}d=
d||a.length;f=f||a.length;window.setTimeout(function(){h._editor.selectLines(g,i+d,g,i+f);h._editor.editor.highlightAtCursor();h._editor.focus();c&&c(i+f)},100)},l=function(a){h._cancelPopup();"string"==typeof a?j(a):"module"==a.type?j(a.label+".",function(){h.startAssistAtCursor()}):"hash"==a.type?j(a.label+"["):"function"==a.type?0<("paramInfo"in a?a.paramInfo.length:a.params.length)?j(a.label+"(",function(){var b=h._editor.cursorPosition(!1),c=h._editor.lineNumber(b.line)-1,d=b.character,e=h._editor.lineContent(b.line),
b=h._findCurrentNode(b,c,d,e);h._showFunctionArgumentAssistance(a,0,b)}):j(a.label+"()"):j(a.label)},m=function(a,c){if(0<b&&8==a.keyCode&&0==c.length){h._cancelPopup();h._editor.focus();var d=h._editor.nthLine(e+1);h._editor.selectLines(d,b-1,d,b);h._editor.editor.replaceSelection("")}else if(190==a.keyCode||46==a.charCode)j(c+".",function(){h.startAssistAtCursor()});else if(57==a.keyCode||40==a.charCode)j(c+"(",function(){h._scheduleAutoAssist("(")});else return;a.returnValue=!1;a.cancelBubble=
!0;"preventDefault"in a&&a.preventDefault();return!1},n=function(){h._popup=new CueCard.Popup(Math.round(i.left+a.left),Math.round(i.top+a.top),Math.round(a.height),[window,h._editor.win],{onCancel:function(a){"key"==a&&h._editor.focus()}});h._popup.elmt.html("<div></div>")};0==d.length?(n(),new CueCard.SuggestionController(h._popup,h._popup.elmt[0].firstChild,new CodeAssist.SearchSuggestor(this._getLocalVariables(),l,m),k)):(d=CodeAssist.helperUrl+"assist?segments="+encodeURIComponent(d),$.ajax(d,
{dataType:"json",success:function(a){a=a.result;0<a.length&&(n(),new CueCard.SuggestionController(h._popup,h._popup.elmt[0].firstChild,new CodeAssist.ScopedSuggestor(a,l,m),k))},error:function(){}}))}};
CodeAssist.prototype._getLocalVariables=function(){for(var a=[],e=function(a){return a.replace(/^\s+/,"").replace(/\s+$/,"")},b=this._editor.win.document.getElementsByTagName("span"),d=0;d<b.length;d++){var c=b[d];if("js-variable"==c.className){for(var g=c.previousSibling,f=!1,h=!1;null!=g;){if("js-keyword"==g.className){g=e(g.firstChild.nodeValue);"var"==g?f=!0:"function"==g&&(h=f=!0);break}else if("whitespace"!=g.className)break;g=g.previousSibling}f&&(c=e(c.firstChild.nodeValue),a.push({label:c,
type:"var",description:h?"local function":"local variable"}))}else"js-variabledef"==c.className&&(c=e(c.firstChild.nodeValue),a.push({label:c,type:"var",description:"local variable or function argument"}))}return a};
CodeAssist.prototype._internalStartFunctionArgumentAssist=function(a,e,b,d,c){d=new CodeAssist.QueryTokenizer(d,0,c);for(e=[];null!=(b=d.token())&&1E3>e.length;)e.push(b),d.next();if(0!=e.length){for(var g=c=0,d=e.length-1;0<=d;d--)if(b=e[d],b.type==CodeAssist.Token.Types.delimiter)if("("==b.content||"["==b.content||"{"==b.content)if(0==c){d--;break}else c--;else")"==b.content||"]"==b.content||"}"==b.content?c++:","==b.content&&0==c&&g++;if(!(null==b||0<c)){for(c=[];0<=d;d--)if(b=e[d],b.type==CodeAssist.Token.Types.identifier)c.unshift(b.content);
else if(b.type==CodeAssist.Token.Types.operator&&"."==b.content)c.unshift(".");else if(b.type!=CodeAssist.Token.Types.whitespace)break;for(c=c.join("");;)if(e=c.replace(/\.\./g,"."),c!=e)c=e;else break;if(0!=c.length){var f=this,e=CodeAssist.helperUrl+"assist_args?segments="+encodeURIComponent(c);$.ajax(e,{dataType:"json",success:function(b){if(b=b.result){var c=$(f._container).offset();c.left-=f._editor.win.document.body.scrollLeft+document.body.scrollLeft;c.top-=f._editor.win.document.body.scrollTop+
document.body.scrollTop;f._popup=new CueCard.Popup(Math.round(c.left+a.left),Math.round(c.top+a.top),Math.round(a.height),[window,f._editor.win],{});f._showFunctionArgumentAssistance(b,g,a)}},error:function(){}})}}}};
CodeAssist.prototype._showFunctionArgumentAssistance=function(a,e,b){var d=this,c=$(this._container).offset();c.left-=this._editor.win.document.body.scrollLeft+document.body.scrollLeft;c.top-=this._editor.win.document.body.scrollTop+document.body.scrollTop;null==this._popup?this._popup=new CueCard.Popup(Math.round(c.left+b.left),Math.round(c.top+b.top),Math.round(b.height),[window,this._editor.win],{onCancel:function(a){"key"==a&&d._editor.focus()}}):this._popup.elmt.empty();b=$('<div class="codeAssist-argumentAssist-singleLine"></div>').appendTo(this._popup.elmt);
if("paramInfo"in a)for(c=0;c<a.paramInfo.length;c++){var g=a.paramInfo[c];0<c&&$("<span>, </span>").appendTo(b);if(c==e){$("<b>"+g.name+"</b>").appendTo(b);var f=$('<div class="codeAssist-argumentAssist-details"><span class="codeAssist-argumentAssist-type">'+g.type+'</span>, <span class="codeAssist-argumentAssist-optional">'+(g.optional?"optional":"required")+'</span>: <span class="codeAssist-argumentAssist-description">'+g.description+"</span></div>").appendTo(this._popup.elmt);if("structure"in g)for(var f=
$('<div class="codeAssist-argumentAssist-structure">Keys:</div>').appendTo(f),f=$("<ul></ul>").appendTo(f),h=0;h<g.structure.length;h++){var i=g.structure[h];$("<li>"+i.name+" ("+i.type+"): "+i.description+"</li>").appendTo(f)}}else $("<span>"+g.name+"</span>").appendTo(b)}else for(c=0;c<a.params.length;c++)0<c&&$("<span>, </span>").appendTo(b),c==e?$("<b>"+a.params[c]+"</b>").appendTo(b):$("<span>"+a.params[c]+"</span>").appendTo(b);this._popup.reposition()};
CodeAssist.renderApiSuggestion=function(a,e){if("type"in a&&"function"==a.type)if("paramInfo"in a){var b=[];$.each(a.paramInfo,function(){b.push(this.name)});a.hint="("+b.join(", ")+"): "+a.description}else a.hint="("+a.params.join(", ")+"): "+a.description;else"description"in a&&(a.hint=a.description);var d=a.label;if(0<e.length)var c=d.toLowerCase().indexOf(e),d=d.substr(0,c)+"<b>"+d.substr(c,e.length)+"</b>"+d.substr(c+e.length);var c="cuecard-suggestion-entry codeAssist-entry",g="";"deprecated"in
a&&a.deprecated&&(c+=" codeAssist-deprecated",g='<div class="codeAssist-deprecation">Deprecated',"see"in a&&(g+=" - see "+("string"==typeof a.see?a.see:a.see.join(", "))),g+="</div>");a.elmt=$('<a class="'+c+'" href="javascript:{}"><span class="codeAssist-entry-title">'+d+"</span>"+g+("hint"in a?' <span class="cuecard-suggestion-hint">'+a.hint+"</span>":"")+"</a>")};
CodeAssist.ScopedSuggestor=function(a,e,b){this._suggestions=a;this._onCommit=e;this.onKeyDown=b;for(a=0;a<this._suggestions.length;a++)CodeAssist.renderApiSuggestion(this._suggestions[a],"")};CodeAssist.ScopedSuggestor.prototype.getSuggestions=function(a,e){for(var b=[],d=0;d<this._suggestions.length;d++){var c=this._suggestions[d];(0==a.length||0<=c.label.indexOf(a))&&b.push(c)}e(b)};CodeAssist.ScopedSuggestor.prototype.commit=function(a){this._onCommit(a)};
CodeAssist.SearchSuggestor=function(a,e,b){this._localVariables=a;this._onCommit=e;this.onKeyDown=b;for(e=0;e<a.length;e++)CodeAssist.renderApiSuggestion(a[e],"")};
CodeAssist.SearchSuggestor.prototype.getSuggestions=function(a,e){for(var b=CodeAssist.helperUrl+(0==a.length?"assist?segments=":"search?q="+encodeURIComponent(a)),d=[],c=0;c<this._localVariables.length;c++){var g=this._localVariables[c];(0==a.length||0<=g.label.toLowerCase().indexOf(a))&&d.push(g)}CueCard.JsonpQueue.call(b,function(b){for(var c=0;c<b.length;c++){var g=b[c];CodeAssist.renderApiSuggestion(g,a);d.push(g)}e(d)},function(){e(d)})};CodeAssist.SearchSuggestor.prototype.commit=function(a){this._onCommit(a)};
CodeAssist.QueryTokenizer=function(a,e,b){this._text=a+" ";this._maxIndex=b;this._index=e;this._col=this._line=0;this.next()};CodeAssist.QueryTokenizer.prototype.token=function(){return this._token};CodeAssist.QueryTokenizer.prototype.index=function(){return this._index};CodeAssist.QueryTokenizer._whitespaces=" \t\r\n";
CodeAssist.QueryTokenizer.prototype.next=function(){this._token=null;if(this._index<this._maxIndex){var a=this._text.charAt(this._index),e=this._text.charAt(this._index+1),b=this,d=function(){b._index++;b._col++},c=function(){return new CodeAssist.TokenPos(b._index,b._line,b._col)},g=function(){var a=c();d();return a},f=function(a,d,e){var f=c();b._pos=f;b._token=new CodeAssist.Token(a,e||b._text.substring(d.offset,f.offset),d,f)},h={"function":!0,"return":!0,"if":!0,"else":!0,"for":!0,"while":!0,
"do":!0,"break":!0,"break":!0,"switch":!0,"case":!0,"default":!0,"with":!0,"try":!0,"catch":!0,"finally":!0,"throw":!0,"instanceof":!0,"typeof":!0,"in":!0};if(0<=CodeAssist.QueryTokenizer._whitespaces.indexOf(a)){for(a=c();b._index<b._maxIndex;){h=b._text.charAt(b._index);if(0>CodeAssist.QueryTokenizer._whitespaces.indexOf(h))break;"\n"==h?(b._line++,b._col=0):b._col++;b._index++}f(CodeAssist.Token.Types.whitespace,a)}else if("/"==a)if("/"==e){a=c();d();for(d();b._index<b._maxIndex&&"\n"!=b._text.charAt(b._index);)d();
f=c();h=b._text.substring(a.offset,f.offset);b._pos=f;b._token=new CodeAssist.Token(CodeAssist.Token.Types.endOfLineComment,h,a,f)}else if("*"==e){f=c();d();d();for(h=!1;b._index<b._maxIndex;)if(a=b._text.charAt(b._index),e=b._text.charAt(b._index+1),"*"==a&&"/"==e){d();d();h=!0;break}else d();a=c();e=b._text.substring(f.offset,a.offset);b._pos=a;b._token=new CodeAssist.Token(CodeAssist.Token.Types[h?"comment":"error"],e,f,a)}else if(0<=CodeAssist.QueryTokenizer._whitespaces.indexOf(e))f(CodeAssist.Token.Types.operator,
g());else{f=c();d();for(h=!1;b._index<b._maxIndex;)if(a=b._text.charAt(b._index),d(),"/"==a){h=!0;break}else"\\"==a&&b._index<b._maxIndex&&d();b._index<b._maxIndex&&0<="gi".indexOf(b._text.charAt(b._index))&&d();a=c();e=b._text.substring(f.offset,a.offset);b._pos=a;b._token=new CodeAssist.Token(CodeAssist.Token.Types[h?"regexLiteral":"error"],e,f,a)}else if(0<="[{()}],:;".indexOf(a))f(CodeAssist.Token.Types.delimiter,g());else if('"'==a||"'"==a){h=a;e=c();d();for(var g="",i=!1;b._index<b._maxIndex;){a=
b._text.charAt(b._index);if(a==h){d();i=!0;break}else if("\r"==a||"\n"==a)break;"\\"==a?(d(),g+=b._text.charAt(b._index)):g+=a;d()}f(CodeAssist.Token.Types[i?"stringLiteral":"error"],e,g)}else if("-"==a||"+"==a||CodeAssist.QueryTokenizer._isDigit(a)){h=c();for("+"==a?d():"-"==a&&d();b._index<b._maxIndex&&CodeAssist.QueryTokenizer._isDigit(b._text.charAt(b._index));)d();if(b._index<b._maxIndex&&"."==b._text.charAt(b._index))for(d();b._index<b._maxIndex&&CodeAssist.QueryTokenizer._isDigit(b._text.charAt(b._index));)d();
f(CodeAssist.Token.Types.numberLiteral,h)}else if(0<="<>=!+-*/?&.".indexOf(a))f(CodeAssist.Token.Types.operator,g());else if(0<=CodeAssist.QueryTokenizer._identifierPrefix.indexOf(a)){for(a=c();b._index<b._maxIndex;)if(f=b._text.charAt(b._index),0<=CodeAssist.QueryTokenizer._identifierCharacters.indexOf(f)||0<=CodeAssist.QueryTokenizer._identifierPrefix.indexOf(f))d();else break;f=c();e=b._text.substring(a.offset,f.offset);b._pos=f;b._token=e in h?new CodeAssist.Token(CodeAssist.Token.Types.keyword,
e,a,f):new CodeAssist.Token(CodeAssist.Token.Types.identifier,e,a,f)}else f(CodeAssist.Token.Types.error,g())}return this._token};CodeAssist.QueryTokenizer._isDigit=function(a){return 0<="0123456789".indexOf(a)};CodeAssist.QueryTokenizer._identifierPrefix="_abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ$";CodeAssist.QueryTokenizer._identifierCharacters="0123456789";CodeAssist.TokenPos=function(a,e,b){this.offset=a;this.line=e;this.col=b};
CodeAssist.Token=function(a,e,b,d){this.type=a;this.content=e;this.start=b;this.end=d};CodeAssist.Token.Types={error:-1,whitespace:0,operator:1,delimiter:2,numberLiteral:3,stringLiteral:4,booleanLiteral:5,regexLiteral:6,keyword:7,identifier:8,comment:9,endOfLineComment:10};
