
/*
 * Copyright 2010, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Additional Licenses for Third Party components can be found here:
 * http://wiki.freebase.com/wiki/Freebase_Site_License
 *
 */
/*
 
 jQuery Tools @VERSION / Expose - Dim the lights

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/toolbox/expose.html

 Since: Mar 2010
 Date: @DATE 
 
 jQuery Tools @VERSION Overlay - Overlay base. Extend it.

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/overlay/

 Since: March 2008
 Date: @DATE 
*/
(function(d){function e(){if(d.browser.msie){var h=d(document).height(),j=d(window).height();return[window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth,h-j<20?j:h]}return[d(document).width(),d(document).height()]}function b(h){if(h)return h.call(d.mask)}d.tools=d.tools||{version:"@VERSION"};var a;a=d.tools.expose={conf:{maskId:"exposeMask",loadSpeed:"slow",closeSpeed:"fast",closeOnClick:true,closeOnEsc:true,zIndex:9998,opacity:0.8,startOpacity:0,color:"#fff",onLoad:null,
onClose:null}};var c,g,f,i,k;d.mask={load:function(h,j){if(f)return this;if(typeof h=="string")h={color:h};h=h||i;i=h=d.extend(d.extend({},a.conf),h);c=d("#"+h.maskId);if(!c.length){c=d("<div/>").attr("id",h.maskId);d("body").append(c)}var l=e();c.css({position:"absolute",top:0,left:0,width:l[0],height:l[1],display:"none",opacity:h.startOpacity,zIndex:h.zIndex});h.color&&c.css("backgroundColor",h.color);if(b(h.onBeforeLoad)===false)return this;h.closeOnEsc&&d(document).bind("keydown.mask",function(m){m.keyCode==
27&&d.mask.close(m)});h.closeOnClick&&c.bind("click.mask",function(m){d.mask.close(m)});d(window).bind("resize.mask",function(){d.mask.fit()});if(j&&j.length){k=j.eq(0).css("zIndex");d.each(j,function(){var m=d(this);/relative|absolute|fixed/i.test(m.css("position"))||m.css("position","relative")});g=j.css({zIndex:Math.max(h.zIndex+1,k=="auto"?0:k)})}c.css({display:"block"}).fadeTo(h.loadSpeed,h.opacity,function(){d.mask.fit();b(h.onLoad)});f=true;return this},close:function(){if(f){if(b(i.onBeforeClose)===
false)return this;c.fadeOut(i.closeSpeed,function(){b(i.onClose);g&&g.css({zIndex:k})});d(document).unbind("keydown.mask");c.unbind("click.mask");d(window).unbind("resize.mask");f=false}return this},fit:function(){if(f){var h=e();c.css({width:h[0],height:h[1]})}},getMask:function(){return c},isLoaded:function(){return f},getConf:function(){return i},getExposed:function(){return g}};d.fn.mask=function(h){d.mask.load(h);return this};d.fn.expose=function(h){d.mask.load(h,this);return this}})(jQuery);
(function(d){function e(c,g){var f=this,i=c.add(f),k=d(window),h,j,l,m=d.tools.expose&&(g.mask||g.expose),n=Math.random().toString().slice(10);if(m){if(typeof m=="string")m={color:m};m.closeOnClick=m.closeOnEsc=false}var p=g.target||c.attr("rel");j=p?d(p):c;if(!j.length)throw"Could not find Overlay: "+p;c&&c.index(j)==-1&&c.click(function(o){f.load(o);return o.preventDefault()});d.extend(f,{load:function(o){if(f.isOpened())return f;var r=a[g.effect];if(!r)throw'Overlay: cannot find effect : "'+g.effect+
'"';g.oneInstance&&d.each(b,function(){this.close(o)});o=o||d.Event();o.type="onBeforeLoad";i.trigger(o);if(o.isDefaultPrevented())return f;l=true;m&&d(j).expose(m);var q=g.top,t=g.left,u=j.outerWidth({margin:true}),v=j.outerHeight({margin:true});if(typeof q=="string")q=q=="center"?Math.max((k.height()-v)/2,0):parseInt(q,10)/100*k.height();if(t=="center")t=Math.max((k.width()-u)/2,0);r[0].call(f,{top:q,left:t},function(){if(l){o.type="onLoad";i.trigger(o)}});m&&g.closeOnClick&&d.mask.getMask().one("click",
f.close);g.closeOnClick&&d(document).bind("click."+n,function(s){d(s.target).parents(j).length||f.close(s)});g.closeOnEsc&&d(document).bind("keydown."+n,function(s){s.keyCode==27&&f.close(s)});return f},close:function(o){if(!f.isOpened())return f;o=o||d.Event();o.type="onBeforeClose";i.trigger(o);if(!o.isDefaultPrevented()){l=false;a[g.effect][1].call(f,function(){o.type="onClose";i.trigger(o)});d(document).unbind("click."+n).unbind("keydown."+n);m&&d.mask.close();return f}},getOverlay:function(){return j},
getTrigger:function(){return c},getClosers:function(){return h},isOpened:function(){return l},getConf:function(){return g}});d.each("onBeforeLoad,onStart,onLoad,onBeforeClose,onClose".split(","),function(o,r){d.isFunction(g[r])&&d(f).bind(r,g[r]);f[r]=function(q){d(f).bind(r,q);return f}});h=j.find(g.close||".close");if(!h.length&&!g.close){h=d('<a class="close"></a>');j.prepend(h)}h.click(function(o){f.close(o)});g.load&&f.load()}d.tools=d.tools||{version:"@VERSION"};d.tools.overlay={addEffect:function(c,
g,f){a[c]=[g,f]},conf:{close:null,closeOnClick:true,closeOnEsc:true,closeSpeed:"fast",effect:"default",fixed:!d.browser.msie||d.browser.version>6,left:"center",load:false,mask:null,oneInstance:true,speed:"normal",target:null,top:"10%"}};var b=[],a={};d.tools.overlay.addEffect("default",function(c,g){var f=this.getConf(),i=d(window);if(!f.fixed){c.top+=i.scrollTop();c.left+=i.scrollLeft()}c.position=f.fixed?"fixed":"absolute";this.getOverlay().css(c).fadeIn(f.speed,g)},function(c){this.getOverlay().fadeOut(this.getConf().closeSpeed,
c)});d.fn.overlay=function(c){var g=this.data("overlay");if(g)return g;if(d.isFunction(c))c={onBeforeLoad:c};c=d.extend(true,{},d.tools.overlay.conf,c);this.each(function(){g=new e(d(this),c);b.push(g);d(this).data("overlay",g)});return c.api?g:this}})(jQuery);
(function(d){d.fn.mqlkey=function(b){return this.each(function(){var a=d(this);if(a.is(":text")){var c=a.data("mqlkey");c&&c._destroy();c=new e(this,b);a.data("mqlkey",c)}})};var e=d.mqlkey=function(b,a){this.options=d.extend(true,{},e.defaults,a);this.options.jsonp=e.use_jsonp(this.options.mqlread_url);this.input=d(b);this.original=this.input.val();this.init()};e.prototype={init:function(){var b=this;this.input.bind("keyup.mqlkey",function(a){b.textchange(a)}).bind(d.browser.msie?"paste.mqlkey":
"input.mqlkey",function(a){b.textchange(a)});if(this.options.source){this.source=d(this.options.source);this.source_generate=true;this.input.bind("change.mqlkey",function(){b.source_generate=false});this.source.bind("change.mqlkey",function(){if(b.source_generate){var a=e.from(b.source.val());b.input.val(a).trigger("keyup")}})}},_destroy:function(){this.input.unbind(".mqlkey");this.source&&this.source.unbind("change.mqlkey")},textchange:function(b){clearTimeout(this.textchange_timeout);var a=this;
this.textchange_timeout=setTimeout(function(){a.textchange_delay(b)},200)},textchange_delay:function(){this.input.trigger("textchange");var b=d.trim(this.input.val());return b===this.original&&b!==""?this.valid(b):e.reserved_word(b)?this.invalid(b,b+" is a reserved word."):e.test(b,this.options.schema)?b.length<this.options.minlen?this.invalid(b):this.options.check_key?this.check_key(b):this.valid(b):this.invalid(b)},check_key:function(b){var a=this;if(this.xhr){this.xhr.abort();this.xhr=null}var c=
{query:'{"query": {"id": null, "key": {"namespace": "'+this.options.namespace+'", "value": "'+b+'"}}}'};clearTimeout(this.check_key.timeout);var g={url:this.options.mqlread_url,data:c,success:function(f){if(f.code==="/api/status/ok")return f.result?a.invalid(b,"Key already exists"):a.valid(b)},error:function(f){if(f)return a.invalid(f.responseText())},dataType:a.options.jsonp?"jsonp":"json"};this.check_key.timeout=setTimeout(function(){a.ac_xhr=d.ajax(g)},200)},valid:function(b){this.input.trigger("valid",
b)},invalid:function(b,a){if(!a){a=this.options.minlen>1?"Key must be "+this.options.minlen+" or more alphanumeric characters":"Key must be alphanumeric";a+=", lowercase, begin with a letter and not end with a non-alphanumeric character. Underscores are allowed but not consecutively."}this.input.trigger("invalid",a)}};d.extend(e,{defaults:{minlen:1,check_key:true,namespace:"/",mqlread_url:"http://api.freebase.com/api/service/mqlread",source:null,schema:false},use_jsonp:function(b){if(!b)return false;
var a=window.location.href;a=a.substr(0,a.length-window.location.pathname.length);if(a===b)return false;return true},from:function(b){b=b.toLowerCase();b=b.replace(/[^a-z0-9]/g,"_");b=b.replace(/\_\_+/g,"_");b=b.replace(/[^a-z0-9]+$/,"");b=b.replace(/^[^a-z]+/,"");if(e.reserved_word(b))b="x_"+b;return b},reservedwords:"meta typeguid left right datatype scope attribute relationship property link class future update insert delete replace create destroy default sort limit offset optional pagesize cursor index !index for while as in is if else return count function read write select var connect this self super xml sql mql any all macro estimate-count",
typeonlywords:"guid id object domain name key type keys value timestamp creator permission namespace unique schema reverse",_reserved_word:null,reserved_word:function(b){if(!e._reserved_word){e._reserved_word={};d.each([e.reservedwords,e.typeonlywords],function(a,c){d.each(c.split(" "),function(g,f){e._reserved_word[f]=1})})}return e._reserved_word[b]===1},fast:/^[A-Za-z0-9](?:[_-]?[A-Za-z0-9])*$/,slow:/^(?:[A-Za-z0-9]|\$[A-F0-9]{4})(?:[_-]?[A-Za-z0-9]|[_-]?\$[A-F0-9]{4})*$/,schema:/^[a-z](?:_?[a-z0-9])*$/,
test:function(b,a){if(a)return e.schema.test(b);return e.fast.test(b)||e.slow.test(b)}})})(jQuery);
(function(d,e){e.require("dojo.date.stamp");e.require("dojo.date.locale");e.require("dojo.number");d.fn.validate_input=function(a){return this.each(function(){var c=d(this);if(c.is(":text")){var g=c.data("$.validate_input");g&&g._destroy();g=new b(this,a);c.data("$.validate_input",g)}})};var b=d.validate_input=function(a,c){var g=this.options=d.extend(true,{},b.defaults,c);if(typeof g.validator!=="function")throw"A validator is required";if(!g.lang)g.lang="/lang/en";g.lang=g.lang==="/lang/en"?["lang/en"]:
[g.lang,"/lang/en"];g.locales=[];d.each(g.lang,function(i,k){g.locales[i]=e.i18n.normalizeLocale(k.split("/").pop())});this.input=d(a);this.init();var f=this;this.input.bind("remove",function(){f._destroy()});return this};b.prototype={init:function(){var a=this;this.input.bind("keyup.validate_input",function(c){a.textchange(c)}).bind(d.browser.msie?"paste.validate_input":"input.validate_input",function(c){a.textchange(c)}).bind("keypress.validate_input",function(c){c.keyCode===13&&a.validate(true)}).bind("blur.validate_input",
function(){a.validate(true)})},_destroy:function(){this.input.unbind(".validate_input")},valid:function(a){this.input.trigger("valid",a)},invalid:function(a,c){this.input.trigger("invalid",c)},empty:function(){this.input.trigger("empty")},textchange:function(){clearTimeout(this.textchange_timeout);var a=this;this.textchange_timeout=setTimeout(function(){a.validate()},200)},validate:function(a){a&&clearTimeout(this.textchange_timeout);a=this.options;var c=d.trim(this.input.val());if(c==="")return this.empty();
try{return this.valid(a.validator(c,a))}catch(g){return this.invalid(c,""+g)}}};d.extend(b,{defaults:{validator:function(a){return{text:a,value:a}}},log:function(){},invalid:function(a,c,g,f){throw new Error("Invalid "+g+(f?": "+f:""));},text:function(a,c){if(a.lengh>4096)return this.invalid(a,c,type,"Text too long");return{text:a,value:a}},topic:function(){return b.defaults.validator},enumerated:function(){return b.defaults.validator},"boolean":function(){return b.defaults.validator},uri:function(a,
c){var g=b.uri.regex;if(!g)g=b.uri.regex=/^(https?|ftp):\/\/(((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:)*@)?(((\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5]))|((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?)(:\d*)?)(\/((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)+(\/(([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)*)*)?)?(\?((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|[\uE000-\uF8FF]|\/|\?)*)?(\#((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|\/|\?)*)?$/i;
if(g.test(a))return{text:a,value:a};return b.invalid(a,c,"uri")},"int":function(a,c){return b.number.parse(a,c,false)},"float":function(a,c){return b.number.parse(a,c,true)},number:function(a,c,g){return b.number.parse(a,c,g)},datetime:function(a,c){return b.datetime.parse(a,c)},mqlkey:function(a,c){var g=b.mqlkey.regex;if(!g)g=b.mqlkey.regex=/^[A-Za-z0-9][A-Za-z0-9_-]*$/;if(g.test(a))return{text:a,value:a};return b.invalid(a,c,"mqlkey")}});d.extend(b.number,{parse:function(a,c,g){var f=c&&c.locales||
["en"],i,k;i=0;for(k=f.length;i<k;i++){var h=f[i];c=e.number.parse(a,{locale:h});if(!isNaN(c)){a={};if(g){a.value=c;a.text=e.number.format(c,{locale:h})}else{a.value=e.number.round(c,0);a.text=e.number.format(a.value,{locale:h})}return a}}throw b.invalid("number",a);}});d.extend(b.datetime,{formats:["yyyy",["dateFormatItem-y"],"yyyy-MM",["dateFormatItem-yM","dateFormatItem-yMMM"],"yyyy-MM-dd",["dateFormat-short","dateFormat-medium","dateFormat-long"]],parse:function(a,c){if(!e.date.stamp._isoRegExp)e.date.stamp._isoRegExp=
/^(?:(-?\d{4})(?:-(\d{2})(?:-(\d{2}))?)?)?(?:T(\d{2}):(\d{2})(?::(\d{2})(.\d+)?)?((?:[+-](\d{2}):(\d{2}))|Z)?)?$/;var g=e.date.stamp.fromISOString(a);if(g)return{text:a,value:a,date:g};var f=c&&c.locales||["en"],i,k,h,j,l,m;i=0;for(k=f.length;i<k;i++){var n=f[i],p=e.date.locale._getGregorianBundle(n);h=0;for(j=b.datetime.formats.length;h<j;h+=2){var o=b.datetime.formats[h],r=b.datetime.formats[h+1];l=0;for(m=r.length;l<m;l++){var q=p[r[l]];if(q){q=i18n.normalize_pattern(q);try{g=e.date.locale.parse(a,
{datePattern:q,selector:"date",locale:n});return{text:a,value:e.date.locale.format(g,{datePattern:o,selector:"date"}),date:g}}catch(t){}}}}}throw b.invalid("datetime",a);}})})(jQuery,dojo);
(function(d){d.fn.data_input=function(e){return this.each(function(){var b=d(this),a=b.data("$.data_input");a&&a._destroy();a=new d.data_input(this,e);b.data("$.data_input",a)})};d.data_input=function(e,b){this.options=d.extend(true,{},d.data_input.defaults,b);this.container=d(e);this.metadata=this.container.metadata();this.input=d(":input",this.container);this.init();var a=this;this.input.bind("remove",function(){a._destroy()})};d.data_input.prototype={init:function(){var e=this,b=this.container,
a=this.input,c=this.options;a.bind("focusin.data_input",function(){e.container.addClass("focus")}).bind("focusout.data_input",function(){e.container.removeClass("focus")}).bind("valid.data_input",function(g,f){var i={name:e.input.attr("name")};if(f.id)i.id=f.id;else{i.value=f.value;if(e.metadata.type==="/type/text")i.lang=e.metadata.lang||c.lang}e.container.data("data",i);e.container.removeClass("error").addClass("valid");e.container.trigger("valid")}).bind("invalid.data_input",function(){e.container.removeData("data");
e.container.removeClass("valid").addClass("error");e.container.trigger("invalid")}).bind("empty.data_input",function(){var g={name:e.input.attr("name")};if(e.metadata&&e.metadata.lang)g.lang=e.metadata.lang;e.container.data("data",g);e.container.removeClass("valid").removeClass("error");e.container.trigger("empty")}).bind("keypress.data_input",function(g){g.keyCode===13&&!g.isDefaultPrevented()&&e.container.trigger("submit")}).bind("keyup.data_input",function(g){g.keyCode===27&&e.container.trigger("cancel")});
if(b.is(".topic")){b=d.extend(true,{},c.suggest,d.data_input.suggest_options(e.metadata.type));a.validate_topic(b).bind("valid.data_input",function(g,f){e.fb_select(f)}).bind("invalid.data_input",function(){e.fb_textchange()});if(this.metadata&&this.metadata.id){a.data("data.suggest",this.metadata);this.validate()}}else if(b.is(".text"))a.validate_input({validator:d.validate_input.text});else if(b.is(".datetime"))a.validate_input({validator:d.validate_input.datetime,lang:c.lang});else if(b.is(".enumerated")){a.validate_enumerated().bind("valid.data_input",
function(g,f){e.fb_select(f)}).bind("invalid.data_input",function(){e.fb_textchange()});this.metadata&&this.metadata.id&&this.validate()}else if(b.is(".int"))a.validate_input({validator:d.validate_input["int"],lang:c.lang});else if(b.is(".float"))a.validate_input({validator:d.validate_input["float"],lang:c.lang});else if(b.is(".uri"))a.validate_input({validator:d.validate_input.uri});else if(b.is(".boolean"))a.validate_boolean();else if(b.is(".enumeration"))a.validate_input({validator:d.validate_input.mqlkey});
else if(b.is(".rawstring"))a.validate_input({validator:d.validate_input.text});else throw new Error("Invalid data-input: "+b.attr("class"));},_destroy:function(){this.input.unbind(".data_input")},validate:function(){var e=this.input;d.each(["$.validate_topic","$.validate_input","$.validate_enumerated","$.validate_boolean"],function(b,a){var c=e.data(a);if(c){c.validate(true);return false}})},reset:function(){this.container.removeData("data");if(this.input.is(":text"))this.input.val("");else if(this.input.is("select"))this.input[0].selectedIndex=
0;else this.input.is(":radio")&&this.input.each(function(){this.checked=false})},fb_textchange:function(){},fb_select:function(){},ajax_beforeSend:function(e){if(!this.xhr_queue)this.xhr_queue=[];this.xhr_queue.push(e);this.container.trigger("loading")},ajax_complete:function(e){if(!this.xhr_queue)this.xhr_queue=[];for(var b=0,a=this.xhr_queue.length;b<a;b++)if(e===this.xhr_queue[b]){this.xhr_queue.splice(b,1);break}this.xhr_queue.length===0&&this.container.trigger("loading_complete")}};d.extend(d.data_input,
{defaults:{suggest:{service_url:"http://www.freebase.com",service_path:"/private/suggest",flyout_service_url:"http://www.freebase.com",flyout_service_path:"/private/flyout",mqlread_url:"http://api.freebase.com/api/service/mqlread",category:"object",type:"/common/topic"}},is_metaweb_system_type:function(e){return e.indexOf("/type/")===0||e.indexOf("/common/")===0&&e!=="/common/topic"||e.indexOf("/freebase/")===0&&e.indexOf("_profile")===e.length-8},suggest_options:function(e){var b={category:"instance",
type:e,type_strict:d.data_input.is_metaweb_system_type(e)?"any":"should"},a=["any","type:"+e,"without:fus","without:inst"];d.each(["user","domain","type"],function(c,g){if(e==="/freebase/"+g+"_profile"){a.push("type:/type/"+g);return false}});e==="/book/book_subject"&&a.push("type:/base/skosbase/skos_concept");b.filter="("+a.join(" ")+")";return b}});d.fn.validate_topic=function(e){return this.each(function(){var b=d(this);if(b.is(":text")){var a=b.data("$.validate_topic");a&&a._destroy();a=new d.validate_topic(this,
e);b.data("$.validate_topic",a)}})};d.validate_topic=function(e,b){this.options=d.extend(true,{},b);this.input=d(e);this.init()};d.validate_topic.prototype={init:function(){var e=this;this.input.suggest(this.options).bind("fb-textchange.validate_topic",function(){e.input.val()===""?e.empty():e.invalid()}).bind("fb-select.validate_topic",function(b,a){e.input.val(a.name!=null?a.name:a.id);e.valid(a)})},invalid:function(){this.input.trigger("invalid")},valid:function(e){this.input.trigger("valid",e)},
empty:function(){this.input.trigger("empty")},_destroy:function(){this.input.unbind(".validate_topic")},validate:function(){if(this.input.val()==="")this.empty();else{var e=this.input.data("data.suggest");e?this.valid(e):this.invalid()}}};d.fn.validate_enumerated=function(e){return this.each(function(){var b=d(this);if(b.is("select")){var a=b.data("$.validate_enumerated");a&&a._destroy();a=new d.validate_enumerated(this,e);b.data("$.validate_enumerated",a)}})};d.validate_enumerated=function(e,b){this.options=
d.extend(true,{},b);this.input=d(e);this.init()};d.validate_enumerated.prototype={init:function(){var e=this;this.input.bind("change.validate_enumerated, keypress.validate_enumerated",function(){this.selectedIndex===0?e.empty():e.valid({text:d(":selected",this).text(),id:this.value})})},invalid:function(){this.input.trigger("invalid")},valid:function(e){this.input.trigger("valid",e);this.input.trigger("fb-select",e)},empty:function(){this.input.trigger("empty")},_destroy:function(){this.input.unbind(".validate_enumerated")},
validate:function(){var e=this.input[0];e.selectedIndex>0?this.valid({text:d(":selected",this.input).text(),id:e.value}):this.empty()}};d.fn.validate_boolean=function(e){var b,a;this.each(function(){var g=d(this);if(g.is(":radio"))if(g.val().toLowerCase()==="true")b=g;else if(g.val().toLowerCase()==="false")a=g});if(b&&a){var c=b.data("$.validate_boolean");c&&c._destroy();c=new d.validate_boolean(b,a,e);b.data("$.validate_boolean",c)}return this};d.validate_boolean=function(e,b,a){this.options=d.extend(true,
{},a);this.tradio=e;this.fradio=b;this.input=this.tradio;this.init()};d.validate_boolean.prototype={init:function(){var e=this;this.tradio.bind("change.validate_boolean",function(){e.validate()})},_destroy:function(){this.input.unbind(".validate_boolean")},valid:function(e){this.input.trigger("valid",e)},empty:function(){this.input.trigger("empty")},validate:function(){if(this.tradio.is(":checked"))this.valid({text:this.tradio.text(),value:true});else this.fradio.is(":checked")?this.valid({text:this.fradio.text(),
value:false}):this.empty()}}})(jQuery);
(function(d,e){var b=window.formlib={init_inline_add_form:function(a){var c=a.event_prefix||"form.inline_add_form.";a.edit_row.bind(c+"submit",function(){b.submit_inline_add_form(a)}).bind(c+"cancel",function(){b.cancel_inline_add_form(a)}).bind(c+"error",function(g,f){b.error(a,f);a.edit_row.removeClass("loading")}).bind(c+"success",function(){a.edit_row.removeClass("loading")}).bind(c+"valid",function(){b.enable_submit(a)}).bind(c+"invalid",function(){b.disable_submit(a)});b.init_submit_cancel(a);
a.trigger&&a.trigger.parents(".trigger-row:first").hide();a.body.append(a.head_row).append(a.edit_row).append(a.submit_row);a.init(a)},submit_inline_add_form:function(a){if(!a.edit_row.is(".loading"))if(b.is_submit_enabled(a)){document.activeElement&&d(document.activeElement).blur();b.clear_message(a);if(a.validate(a)){a.edit_row.addClass("loading");a.submit(a,b.default_submit_ajax_options(a))}}},success_inline_add_form:function(a,c){a.head_row.before(c);e.ize(c);a.reset(a);a.edit_row.trigger(a.event_prefix+
"success")},cancel_inline_add_form:function(a){a.head_row.remove();a.edit_row.remove();a.submit_row.remove();a.trigger&&a.trigger.parents(".trigger-row:first").show()},init_inline_edit_form:function(a){var c=a.event_prefix||"form.inline_edit_form.";a.edit_row.bind(c+"submit",function(){b.submit_inline_edit_form(a)}).bind(c+"cancel",function(){b.cancel_inline_edit_form(a)}).bind(c+"error",function(g,f){b.error(a,f);a.edit_row.removeClass("loading")}).bind(c+"success",function(){a.edit_row.removeClass("loading")}).bind(c+
"valid",function(){b.enable_submit(a)}).bind(c+"invalid",function(){b.disable_submit(a)});b.init_submit_cancel(a);a.row.hide();a.row.before(a.head_row).before(a.edit_row).before(a.submit_row);a.init(a)},submit_inline_edit_form:function(a){if(!a.edit_row.is(".loading"))if(b.is_submit_enabled(a)){document.activeElement&&d(document.activeElement).blur();b.clear_message(a);if(a.validate(a)){a.edit_row.addClass("loading");a.submit(a,b.default_submit_ajax_options(a))}}},success_inline_edit_form:function(a,
c){a.row.replaceWith(c);a.row=c;e.ize(c);a.edit_row.trigger(a.event_prefix+"cancel")},cancel_inline_edit_form:function(a){a.head_row.remove();a.edit_row.remove();a.submit_row.remove();a.row.show()},success_inline_delete:function(a,c,g){a.hide().addClass("old-row");a.after(c);c.append(a);if(g){a=d('<a href="#">Undo</a>');d(".msg-default",c).next().append(a);a.click(function(){g();return false})}},success_inline_delete_undo:function(a){var c=d(".old-row",a);a.before(c);c.show().removeClass("old-row");
a.remove()},init_modal_form:function(a){d(document.body).append(a.form.hide());var c=a.event_prefix||"form.modal_form.";a.form.bind(c+"submit",function(){b.submit_modal_form(a)}).bind(c+"cancel",function(){b.cancel_modal_form(a)}).bind(c+"error",function(g,f){b.error(a,f);a.form.removeClass("loading")}).bind(c+"success",function(){a.form.removeClass("loading")}).bind(c+"valid",function(){b.enable_submit(a)}).bind(c+"invalid",function(){b.disable_submit(a)});b.init_submit_cancel(a);a.form.overlay({close:".modal-buttons .cancel",
closeOnClick:false,load:true,fixed:false,mask:{color:"#000",loadSpeed:200,opacity:0.5},onLoad:function(){a.overlay=this;a.init(a)}})},submit_modal_form:function(a){if(!a.form.is(".loading"))if(b.is_submit_enabled(a)){document.activeElement&&d(document.activeElement).blur();b.clear_message(a);if(a.validate(a)){a.form.addClass("loading");a.submit(a,b.default_submit_ajax_options(a))}}},cancel_modal_form:function(a){a.form.data("overlay").close()},init_submit_cancel:function(a){var c=a.form||a.edit_row,
g=a.form||a.submit_row,f=a.event_prefix;a=d(".save",g).click(function(){c.trigger(f+"submit")});b.disable(a);d(".cancel",g).click(function(){c.trigger(f+"cancel")});d(":input",c).keypress(function(i){i.keyCode===13&&!i.isDefaultPrevented()&&c.trigger(f+"submit")}).keyup(function(i){i.keyCode===27&&c.trigger(f+"cancel")})},disable:function(a){d(a).attr("disabled","disabled").addClass("disabled")},enable:function(a){d(a).removeAttr("disabled").removeClass("disabled")},disable_submit:function(a){b.disable(d(".save",
a.form||a.submit_row))},enable_submit:function(a){b.enable(d(".save",a.form||a.submit_row))},is_submit_enabled:function(a){return!d(".save",a.form||a.submit_row).is(":disabled")},init_mqlkey:function(a,c){return a.next(".key-status").removeClass("valid invalid loading").text("").removeAttr("title").end().mqlkey(c).bind("valid",function(){d(this).next(".key-status").removeClass("invalid loading").addClass("valid").text("valid").attr("title","Key is available")}).bind("invalid",function(g,f){d(this).next(".key-status").removeClass("valid loading").addClass("invalid").text("invalid").attr("title",
f)}).bind("textchange",function(){d(this).next(".key-status").removeClass("valid invalid").text("loading").addClass("loading")})},validate_mqlkey:function(a,c){var g=c.next(".key-status"),f=c.val();if(f===""){c.trigger(a.event_prefix+"error","Key is required");return false}if(f===c.data("mqlkey").original)return true;if(g.is(".invalid")){c.trigger(a.event_prefix+"error",g.attr("title"));return false}else if(g.is(".loading"))return false;return true},error:function(a,c){b.disable_submit(a);return b.message(a,
c,"error")},message:function(a,c,g){a=a.head_row;a.find(".close-msg").css("visibility","visible").next().find(".msg-default").hide().next().text(c);a.addClass("row-msg");g&&a.addClass("row-msg-"+g)},clear_message:function(){},default_begin_ajax_options:function(){return b._default_ajax_options("GET")},default_submit_ajax_options:function(a){var c=b._default_ajax_options("POST");if(a){d.extend(c,a.ajax);d("input[type=hidden]",a.submit_row||a.form).each(function(){c.data[this.name]=this.value})}return c},
_default_ajax_options:function(a){return{data:{},dataType:"json",type:a||"GET",success:function(c,g,f){if(!b.check_ajax_success.apply(this,arguments))return this._error.apply(this,[f]);this.onsuccess&&this.onsuccess.apply(this,arguments)},error:function(){b.check_ajax_error.apply(this,arguments);return this._error.apply(this,arguments)},_error:function(c){if(c.status===401)d(window).trigger("fb.user.unauthorized");else if(this.onerror)this.onerror.apply(this,[c.responseText].concat(Array.prototype.slice.call(arguments)));
else{var g={},f=this;d.each(["url","data","dataType","type"],function(i,k){g[k]=f[k]});d.each(["status","statusText","responseText"],function(i,k){g[k]=c[k]});g.responseHeaders=c.getAllResponseHeaders();d(window).trigger("fb.user.feedback",g)}}}},check_ajax_success:function(){return b.check_api_response.apply(this,arguments)},check_ajax_error:function(a){var c=a.responseText;try{c=JSON.stringify(c)}catch(g){}return b.check_api_response.apply(this,[c,a.statusText,a])},check_api_response:function(a,
c,g){if(typeof a==="object"){if(a.code!=="/api/status/ok")return false}else if(g.status!==200)return false;return true}}})(jQuery,window.i18n);
(function(d){var e=window.editparams={Empty:function(b,a,c){this.structure=b;this.data=a;this.msg=c;this.toString=function(){return"Empty: "+this.msg}},Invalid:function(b,a,c){this.structure=b;this.data=a;this.msg=c;this.toString=function(){return"Invalid: "+this.msg}},parse:function(b,a){function c(h,j,l,m,n){try{e.validate(j,l);n.push(l)}catch(p){if(p instanceof e.Empty)n.push(l);else throw p;}}var g=(b.values||[]).slice(),f=b.properties||[],i=b.expected_type.mediator;if(i){if(!f.length)throw new e.Invalid(b,
null,"mediator musth have 1 or more properties");if(g.length&&g.length!==1)throw new e.Invalid(b,null,"Can't edit more than one value (row) for a mediator");}var k=[];d(".data-input",a).each(function(){var h=d(this),j=h.data("$.data_input");if(!j)throw new e.Invalid(b,null,"$.data-input not initialized for",this);j.validate(true);if(h.is(".error"))throw new e.Invalid(b,null,"$.data-input is invalid",this);j=h.data("data");if(!j)throw new e.Invalid(b,null,"$.data-input has no data",this);if(i){if(!k.length){k.push({});
d.each(f,function(n,p){k[0][p.id]=d.extend({},p,{values:[]})})}var l=k[0][j.name];if(l){var m=[];if(g.length)m=(m=g[0][l.id])&&m.values||[];c(h,l,j,m,l.values)}else console.warn("editparams","unknown mediator property data",j)}else c(h,b,j,g,k)});return i?e.parse_mediator(b,g,k):e.parse_simple(b,g,k)},parse_mediator:function(b,a,c){if(c.length!==1)throw new e.Invalid(b,c,"Must specify one (new or updated) value for a mediator");c=c[0];var g;if(a.length)g=a[0];a={};if(g)a.id=g.id;else{a.id=null;a.create=
"unconditional";a.connect=b.unique?"replace":"insert";var f=[];b.expected_type.id!=="/type/object"&&f.push({id:b.expected_type.id,connect:"insert"});var i=b.expected_type.included_types;i&&i.forEach(function(m){m!=="/type/object"&&f.push({id:m,connect:"insert"})});if(f.length)a.type=f}i=false;b=b.properties;for(var k=0,h=b.length;k<h;k++){var j=b[k],l=e.parse_simple(j,g&&g[j.id]&&g[j.id].values||[],c[j.id]&&c[j.id].values||[]);if(l.length){a[j.id]=l;i=true}}return i?[a]:[]},parse_simple:function(b,
a,c){return e.diff(b,a,c)},diff:function(b,a,c){var g=b.expected_type,f=b.expected_type.id,i=b.unique,k=f==="/type/text";if(i)if(!k)if(a.length&&a.length!==1)throw new e.Invalid(b,a,"Can't edit more than one value (row) for a unique property.");else if(c.length&&c.length!==1)throw new e.Invalid(b,c,"Can't edit more than one value (row) for a unique property.");var h=[];if(e.LITERAL_TYPE_IDS[f]){h.push("value");k&&h.push("lang")}else h.push("id");f=[];var j=[],l,m;l=0;for(m=a.length;l<m;l++){var n=
a[l];e.validate(b,n);e.inArray.apply(null,[n,c].concat(h))===-1&&f.push(e.clause(n,"delete"))}l=0;for(m=c.length;l<m;l++){n=c[l];try{e.validate(b,n)}catch(p){continue}if(e.inArray.apply(null,[n,a].concat(h))===-1){if(i)if(k){var o=e.inArray(n,f,"lang");o!==-1&&f.splice(o,1)}else return[e.clause(n,"replace",g)];j.push(e.clause(n,i?"replace":"insert",g))}}return f.concat(j)},validate:function(b,a){var c=b.expected_type.id;if(e.LITERAL_TYPE_IDS[c])if(e.isEmpty(a.value))throw new e.Empty(b,a);else{if(c===
"/type/text"&&e.isEmpty(a.lang))throw new e.Invalid(b,a,"Expected data.lang for /type/text");if(c==="/type/int"||c==="/type/float"){if(d.type(a.value)!=="number")throw new e.Invalid(b,a,"Expected number data.value for "+c);}else if(c==="/type/boolean"){if(d.type(a.value)!=="boolean")throw new e.Invalid(b,a,"Expected boolean data.value for /type/boolean");}else if(d.type(a.value)!=="string")throw new e.Invalid(b,a,"Expected string data.value for "+c);}else if(e.isEmpty(a.id))throw new e.Empty(b,a);
return a},clause:function(b,a,c){var g={connect:a};if(b.id){g.id=b.id;if(a!=="delete"&&c&&!c.enumeration){var f=[];c.id!=="/type/object"&&f.push({id:c.id,connect:"insert"});(b=c.included_types)&&b.forEach(function(i){i!=="/type/object"&&f.push({id:i,connect:"insert"})});if(f.length)g.type=f}}else{g.value=b.value;if(b.lang)g.lang=b.lang}return g},inArray:function(b,a){var c=Array.prototype.slice.call(arguments,2);if(!c.length)return d.inArray(b,a);for(var g=0,f=a.length;g<f;g++){for(var i=a[g],k=true,
h=0,j=c.length;h<j;h++){var l=c[h];if(i[l]!=b[l]){k=false;break}}if(k)return g}return-1},isEmpty:function(b){return b==null||b===""},LITERAL_TYPE_IDS:{"/type/int":1,"/type/float":1,"/type/boolean":1,"/type/rawstring":1,"/type/uri":1,"/type/text":1,"/type/datetime":1,"/type/id":1,"/type/key":1,"/type/value":1,"/type/enumeration":1}}})(jQuery);
(function(d,e,b,a,c){var g=e.edit={prop_add_begin:function(f,i){var k={s:e.options.id,p:f.attr("data-id"),lang:e.options.lang},h=d(">.data-section",f),j=d("> .data-table > tbody, > .data-list",h);d.ajax(d.extend(b.default_begin_ajax_options(),{url:e.options.base_ajax_url+"/prop_add_begin.ajax",data:k,onsuccess:function(l){l=d(l.result.html);var m=d(".edit-row-head",l),n=d(".edit-row",l),p=d(".edit-row-submit",l);l={event_prefix:"propbox.edit.prop_add.",init:g.init_prop_add_form,validate:g.validate_prop_add_form,
submit:g.submit_prop_add_form,reset:g.reset_prop_add_form,ajax:{url:e.options.base_ajax_url+"/prop_edit_submit.ajax",data:k},body:j,head_row:m,edit_row:n,submit_row:p,structure:l.metadata()};n.bind("propbox.edit.prop_add.cancel",function(){f.removeClass("editing")}).bind("propbox.edit.prop_add.success",function(){i&&n.trigger(form.event_prefix+"cancel")});b.init_inline_add_form(l)}}))},init_prop_add_form:function(f){g.init_data_inputs(f);d(":input:visible:first",f.edit_row).focus()},validate_prop_add_form:function(){return true},
reset_prop_add_form:function(f){g.reset_data_inputs(f);b.disable_submit(f);d(".cancel",f.submit_row).text("Done");d(":input:visible:first",f.edit_row).focus()},submit_prop_add_form:function(f,i){try{var k=a.parse(f.structure,f.edit_row);i.data.o=JSON.stringify(k)}catch(h){k=d(".data-input.error",f.edit_row);if(k.length){f.edit_row.trigger(f.event_prefix+"error","Please specify a valid value");k.eq(0).find(":input").focus().select()}else f.edit_row.trigger(f.event_prefix+"error",h.toString());return}d.ajax(d.extend(i,
{onsuccess:function(j){j=d(j.result.html);b.success_inline_add_form(f,j);e.init_menus(j,true);d(".nicemenu-item.edit").show();e.kbs.set_next(null,j,true)},onerror:function(j){f.edit_row.trigger(f.event_prefix+"error",j)}}))},value_edit_begin:function(f,i){var k;if(i.is("tr"))k=i.attr("data-id");else{k=d(".property-value:first",i);k=k.attr("data-id")||k.attr("data-value")||k.attr("datetime")}var h={s:e.options.id,p:f.attr("data-id"),replace:k,lang:e.options.lang};d.ajax(d.extend(b.default_begin_ajax_options(),
{url:e.options.base_ajax_url+"/value_edit_begin.ajax",data:h,onsuccess:function(j){j=d(j.result.html);var l=d(".edit-row-head",j),m=d(".edit-row",j),n=d(".edit-row-submit",j);j={event_prefix:"propbox.edit.value_edit.",init:g.init_value_edit_form,validate:g.validate_value_edit_form,submit:g.submit_value_edit_form,ajax:{url:e.options.base_ajax_url+"/prop_edit_submit.ajax",data:h},row:i,head_row:l,edit_row:m,submit_row:n,structure:j.metadata()};m.bind("propbox.edit.value_edit.success",function(){f.removeClass("editing")}).bind("propbox.edit.value_edit.cancel",
function(){f.removeClass("editing")}).bind("propbox.edit.value_edit.delete",function(){m.trigger("propbox.edit.value_edit.cancel");e.edit.value_delete_begin(f,i)});b.init_inline_edit_form(j)}}))},init_value_edit_form:function(f){g.init_data_inputs(f);d(".delete",f.submit_row).click(function(){f.edit_row.trigger(f.event_prefix+"delete")});d(":input:visible:first",f.edit_row).focus()},validate_value_edit_form:function(){return true},submit_value_edit_form:function(f,i){try{var k=a.parse(f.structure,
f.edit_row);i.data.o=JSON.stringify(k)}catch(h){k=d(".data-input.error",f.edit_row);if(k.length){f.edit_row.trigger(f.event_prefix+"error","Please specify a valid value");k.eq(0).find(":input").focus().select()}else f.edit_row.trigger(f.event_prefix+"error",h.toString());return}d.ajax(d.extend(i,{onsuccess:function(j){j=d(j.result.html);b.success_inline_edit_form(f,j);e.init_menus(j,true);d(".nicemenu-item.edit").show();e.kbs.set_next(null,j,true)},onerror:function(j){f.edit_row.trigger(f.event_prefix+
"error",j)}}))},value_delete_begin:function(f,i){var k;if(i.is("tr"))k=i.attr("data-id");else{k=d(".property-value:first",i);k=k.attr("data-id")||k.attr("data-value")||k.attr("datetime")}var h={s:e.options.id,p:f.attr("data-id"),o:k,lang:e.options.lang};d.ajax(d.extend(b.default_submit_ajax_options(),{url:e.options.base_ajax_url+"/value_delete_submit.ajax",data:h,onsuccess:function(j){var l=d(j.result.html);b.success_inline_delete(i,l,function(){d.ajax(d.extend(b.default_submit_ajax_options(),{url:e.options.base_ajax_url+
"/value_delete_undo.ajax",data:h,onsuccess:function(){b.success_inline_delete_undo(l)}}))});f.removeClass("editing")}}))},init_data_inputs:function(f){d(".data-input",f.edit_row).each(function(){g.init_data_input(d(this),f)})},init_data_input:function(f,i){f.data_input({lang:e.options.lang,suggest:e.options.suggest}).bind("valid",function(){i.edit_row.trigger(i.event_prefix+"valid");var k=f.parent(".form-field"),h=k.next(".magicbox-template");if(h.length){h=d("<div>").html(h.html());h=d(".form-field",
h);k.after(h);g.init_data_input(d(".data-input",h),i)}}).bind("empty",function(){i.edit_row.trigger(i.event_prefix+"valid")}).bind("invalid",function(){i.edit_row.trigger(i.event_prefix+"invalid")}).bind("submit",function(){i.edit_row.trigger(i.event_prefix+"submit")}).bind("cancel",function(){i.edit_row.trigger(i.event_prefix+"cancel")}).bind("loading",function(){d(this).addClass("loading")}).bind("loading_complete",function(){d(this).removeClass("loading")});if(f.is(".datetime"))c.ize_datetime_input(d(":text",
f));else if(f.is(".int")||f.is(".float"))c.ize_number_input(d(":text",f))},reset_data_inputs:function(f){d(".data-input",f.edit_row).each(function(){d(this).data("$.data_input").reset()})}}})(jQuery,window.propbox,window.formlib,window.editparams,window.i18n);
