
/*
 * Copyright 2012, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Additional Licenses for Third Party components can be found here:
 * http://wiki.freebase.com/wiki/Freebase_Site_License
 *
 */
/*
 
 jQuery Tools @VERSION / Expose - Dim the lights

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/toolbox/expose.html

 Since: Mar 2010
 Date: @DATE 
 
 jQuery Tools @VERSION Overlay - Overlay base. Extend it.

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/overlay/

 Since: March 2008
 Date: @DATE 
*/
(function(b){function e(){if(b.browser.msie){var j=b(document).height(),k=b(window).height();return[window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth,j-k<20?k:j]}return[b(document).width(),b(document).height()]}function d(j){if(j)return j.call(b.mask)}b.tools=b.tools||{version:"@VERSION"};var c;c=b.tools.expose={conf:{maskId:"exposeMask",loadSpeed:"slow",closeSpeed:"fast",closeOnClick:true,closeOnEsc:true,zIndex:9998,opacity:0.8,startOpacity:0,color:"#fff",onLoad:null,
onClose:null}};var a,f,g,h,i;b.mask={load:function(j,k){if(g)return this;if(typeof j=="string")j={color:j};j=j||h;h=j=b.extend(b.extend({},c.conf),j);a=b("#"+j.maskId);if(!a.length){a=b("<div/>").attr("id",j.maskId);b("body").append(a)}var l=e();a.css({position:"absolute",top:0,left:0,width:l[0],height:l[1],display:"none",opacity:j.startOpacity,zIndex:j.zIndex});j.color&&a.css("backgroundColor",j.color);if(d(j.onBeforeLoad)===false)return this;j.closeOnEsc&&b(document).bind("keydown.mask",function(n){n.keyCode==
27&&b.mask.close(n)});j.closeOnClick&&a.bind("click.mask",function(n){b.mask.close(n)});b(window).bind("resize.mask",function(){b.mask.fit()});if(k&&k.length){i=k.eq(0).css("zIndex");b.each(k,function(){var n=b(this);/relative|absolute|fixed/i.test(n.css("position"))||n.css("position","relative")});f=k.css({zIndex:Math.max(j.zIndex+1,i=="auto"?0:i)})}a.css({display:"block"}).fadeTo(j.loadSpeed,j.opacity,function(){b.mask.fit();d(j.onLoad)});g=true;return this},close:function(){if(g){if(d(h.onBeforeClose)===
false)return this;a.fadeOut(h.closeSpeed,function(){d(h.onClose);f&&f.css({zIndex:i})});b(document).unbind("keydown.mask");a.unbind("click.mask");b(window).unbind("resize.mask");g=false}return this},fit:function(){if(g){var j=e();a.css({width:j[0],height:j[1]})}},getMask:function(){return a},isLoaded:function(){return g},getConf:function(){return h},getExposed:function(){return f}};b.fn.mask=function(j){b.mask.load(j);return this};b.fn.expose=function(j){b.mask.load(j,this);return this}})(jQuery);
(function(b){function e(a,f){var g=this,h=a.add(g),i=b(window),j,k,l,n=b.tools.expose&&(f.mask||f.expose),r=Math.random().toString().slice(10);if(n){if(typeof n=="string")n={color:n};n.closeOnClick=n.closeOnEsc=false}var s=f.target||a.attr("rel");k=s?b(s):a;if(!k.length)throw"Could not find Overlay: "+s;a&&a.index(k)==-1&&a.click(function(m){g.load(m);return m.preventDefault()});b.extend(g,{load:function(m){if(g.isOpened())return g;var q=c[f.effect];if(!q)throw'Overlay: cannot find effect : "'+f.effect+
'"';f.oneInstance&&b.each(d,function(){this.close(m)});m=m||b.Event();m.type="onBeforeLoad";h.trigger(m);if(m.isDefaultPrevented())return g;l=true;n&&b(k).expose(n);var p=f.top,o=f.left,u=k.outerWidth({margin:true}),v=k.outerHeight({margin:true});if(typeof p=="string")p=p=="center"?Math.max((i.height()-v)/2,0):parseInt(p,10)/100*i.height();if(o=="center")o=Math.max((i.width()-u)/2,0);q[0].call(g,{top:p,left:o},function(){if(l){m.type="onLoad";h.trigger(m)}});n&&f.closeOnClick&&b.mask.getMask().one("click",
g.close);f.closeOnClick&&b(document).bind("click."+r,function(t){b(t.target).parents(k).length||g.close(t)});f.closeOnEsc&&b(document).bind("keydown."+r,function(t){t.keyCode==27&&g.close(t)});return g},close:function(m){if(!g.isOpened())return g;m=m||b.Event();m.type="onBeforeClose";h.trigger(m);if(!m.isDefaultPrevented()){l=false;c[f.effect][1].call(g,function(){m.type="onClose";h.trigger(m)});b(document).unbind("click."+r).unbind("keydown."+r);n&&b.mask.close();return g}},getOverlay:function(){return k},
getTrigger:function(){return a},getClosers:function(){return j},isOpened:function(){return l},getConf:function(){return f}});b.each("onBeforeLoad,onStart,onLoad,onBeforeClose,onClose".split(","),function(m,q){b.isFunction(f[q])&&b(g).bind(q,f[q]);g[q]=function(p){b(g).bind(q,p);return g}});j=k.find(f.close||".close");if(!j.length&&!f.close){j=b('<a class="close"></a>');k.prepend(j)}j.click(function(m){g.close(m)});f.load&&g.load()}b.tools=b.tools||{version:"@VERSION"};b.tools.overlay={addEffect:function(a,
f,g){c[a]=[f,g]},conf:{close:null,closeOnClick:true,closeOnEsc:true,closeSpeed:"fast",effect:"default",fixed:!b.browser.msie||b.browser.version>6,left:"center",load:false,mask:null,oneInstance:true,speed:"normal",target:null,top:"10%"}};var d=[],c={};b.tools.overlay.addEffect("default",function(a,f){var g=this.getConf(),h=b(window);if(!g.fixed){a.top+=h.scrollTop();a.left+=h.scrollLeft()}a.position=g.fixed?"fixed":"absolute";this.getOverlay().css(a).fadeIn(g.speed,f)},function(a){this.getOverlay().fadeOut(this.getConf().closeSpeed,
a)});b.fn.overlay=function(a){var f=this.data("overlay");if(f)return f;if(b.isFunction(a))a={onBeforeLoad:a};a=b.extend(true,{},b.tools.overlay.conf,a);this.each(function(){f=new e(b(this),a);d.push(f);b(this).data("overlay",f)});return a.api?f:this}})(jQuery);
(function(b){b.fn.mqlkey=function(d){return this.each(function(){var c=b(this);if(c.is(":text")){var a=c.data("mqlkey");a&&a._destroy();a=new e(this,d);c.data("mqlkey",a)}})};var e=b.mqlkey=function(d,c){this.options=b.extend(true,{},e.defaults,c);this.input=b(d);this.original=this.input.val();this.init()};e.prototype={init:function(){var d=this;this.input.bind("keyup.mqlkey",function(c){d.textchange(c)}).bind(b.browser.msie?"paste.mqlkey":"input.mqlkey",function(c){d.textchange(c)});if(this.options.source){this.source=
b(this.options.source);this.source_generate=true;this.input.bind("change.mqlkey",function(){d.source_generate=false});this.source.bind("change.mqlkey",function(){if(d.source_generate){var c=e.from(d.source.val());d.input.val(c).trigger("keyup")}})}},_destroy:function(){this.input.unbind(".mqlkey");this.source&&this.source.unbind("change.mqlkey")},textchange:function(d){clearTimeout(this.textchange_timeout);var c=this;this.textchange_timeout=setTimeout(function(){c.textchange_delay(d)},200)},textchange_delay:function(){this.input.trigger("textchange");
var d=b.trim(this.input.val());return d===this.original&&d!==""?this.valid(d):e.reserved_word(d)?this.invalid(d,d+" is a reserved word."):e.test(d,this.options.schema)?d.length<this.options.minlen?this.invalid(d):this.options.check_key?this.check_key(d):this.valid(d):this.invalid(d)},check_key:function(d){var c=this;if(this.xhr){this.xhr.abort();this.xhr=null}var a={id:null,key:{namespace:this.options.namespace,value:d}};clearTimeout(this.check_key.timeout);this.check_key.timeout=setTimeout(function(){c.xhr=
c.options.mqlread(a,function(f){return f?c.invalid(d,"Key already exists"):c.valid(d)},function(f){return f?c.invalid(f.responseText()):c.invalid("mqlread error!")})},200)},valid:function(d){this.input.trigger("valid",d)},invalid:function(d,c){if(!c){c=this.options.minlen>1?"Key must be "+this.options.minlen+" or more alphanumeric characters":"Key must be alphanumeric";c+=", lowercase, begin with a letter and not end with a non-alphanumeric character. Underscores are allowed but not consecutively."}this.input.trigger("invalid",
c)}};b.extend(e,{defaults:{minlen:1,check_key:true,namespace:"/",mqlread:function(d,c,a){return e.mqlread(null,d,c,a)},source:null,schema:false},mqlread:function(d,c,a,f){d={url:d||"http://api.freebase.com/api/service/mqlread",data:{query:JSON.stringify({query:c})},dataType:"jsonp",success:function(g){return a(g.result)},error:f};return b.ajax(d)},from:function(d){d=d.toLowerCase();d=d.replace(/[^a-z0-9]/g,"_");d=d.replace(/\_\_+/g,"_");d=d.replace(/[^a-z0-9]+$/,"");d=d.replace(/^[^a-z]+/,"");if(e.reserved_word(d))d=
"x_"+d;return d},reservedwords:"meta typeguid left right datatype scope attribute relationship property link class future update insert delete replace create destroy default sort limit offset optional pagesize cursor index !index for while as in is if else return count function read write select var connect this self super xml sql mql any all macro estimate-count",typeonlywords:"guid id object domain name key type keys value timestamp creator permission namespace unique schema reverse",_reserved_word:null,
reserved_word:function(d){if(!e._reserved_word){e._reserved_word={};b.each([e.reservedwords,e.typeonlywords],function(c,a){b.each(a.split(" "),function(f,g){e._reserved_word[g]=1})})}return e._reserved_word[d]===1},fast:/^[A-Za-z0-9](?:[_-]?[A-Za-z0-9])*$/,slow:/^(?:[A-Za-z0-9]|\$[A-F0-9]{4})(?:[_-]?[A-Za-z0-9]|[_-]?\$[A-F0-9]{4})*$/,schema:/^[a-z](?:_?[a-z0-9])*$/,test:function(d,c){if(c)return e.schema.test(d);return e.fast.test(d)||e.slow.test(d)}})})(jQuery);
(function(b,e){b(window).ajaxSend(function(c,a,f){f.type==="POST"&&a.setRequestHeader("x-acre-cache-control","max-age: 3600")});var d=e.schema.edit={init_edit_form:function(c){if(c.mode==="add")b("tbody",c.table).append(c.row);else if(c.mode==="edit")c.trigger_row.before(c.row);else throw"Unknown edit type mode: "+c.mode;c.trigger_row.before(c.submit_row);var a=c.event_prefix||"fb.schema.edit.";c.row.bind(a+"submit",function(){d.submit_edit_form(c)}).bind(a+"cancel",function(){d.cancel_edit_form(c)}).bind(a+
"error",function(f,g,h){d.row_error(g,h);c.row.removeClass("loading")}).bind(a+"success",function(){c.row.removeClass("loading")});b("button.save",c.submit_row).click(function(){c.row.trigger(a+"submit")});b(".button.cancel",c.submit_row).click(function(){c.row.trigger(a+"cancel")});c.row.showRow(function(){typeof c.init_form==="function"&&c.init_form(c)});c.trigger_row.hide();c.submit_row.show()},cancel_edit_form:function(c){c.row.hideRow(function(){b(this).remove()});d.clear_row_message(c.row);
c.submit_row.remove();c.trigger_row.show();c.trigger.removeClass("editing")},submit_edit_form:function(c){if(!c.row.is(".loading")){document.activeElement&&b(document.activeElement).blur();d.clear_row_message(c.row);typeof c.validate_form==="function"&&c.validate_form(c);if(!d.has_row_message(c.row,"error")){c.row.addClass("loading");typeof c.submit_form==="function"&&c.submit_form(c)}}},ajax_error_handler:function(c,a,f){var g;try{g=JSON.parse(c.responseText);if(g.messages&&g.messages.length)g=JSON.stringify(g.messages[0])}catch(h){}if(!g)g=
c.responseText;if(a){d.row_error(a,g);a.removeClass("loading")}else if(f){d.form_error(f,g);f.removeClass("loading")}},row_error:function(c,a){return d.row_message(c,a,"error")},row_message:function(c,a,f){var g=b('<a class="close-msg" href="#">Close</a>').click(function(h){return e.schema.close_message.apply(this,[h,".row-msg:first"])});a=b("<span>").text(a);g=b('<td colspan="5">').append(g).append(a);g=b('<tr class="row-msg">').append(g);f&&g.addClass("row-msg-"+f);c.before(g);g.hide().showRow();
a=c.data("row-msg");if(!a){a={};c.data("row-msg",a)}if(a[f])a[f].push(g);else a[f]=[g];return g},clear_row_message:function(c){var a=c.data("row-msg");if(a){b.each(a,function(f,g){b.each(g,function(h,i){i.remove()})});c.removeData("row-msg")}},has_row_message:function(c,a){var f=c.data("row-msg");if(a)return f&&f[a]&&f[a].length;return f!=null},init_modal_form:function(c){b(document.body).append(c.form.hide());var a=c.event_prefix||"fb.schema.edit.modal.";c.form.bind(a+"submit",function(){d.submit_modal_form(c)}).bind(a+
"error",function(f,g){d.form_error(c.form,g)}).bind(a+"success",function(){c.form.removeClass("loading")});b(".modal-buttons .button.save",c.form).click(function(){c.form.trigger(a+"submit")});c.form.overlay({close:".modal-buttons .button.cancel",closeOnClick:false,load:true,fixed:false,mask:{color:"#000",loadSpeed:200,opacity:0.5},onLoad:function(){typeof c.init_form==="function"&&c.init_form(c)}});e.schema.init_modal_help(c.form)},submit_modal_form:function(c){if(!c.form.is(".loading")){document.activeElement&&
b(document.activeElement).blur();d.clear_form_message(c.form);typeof c.validate_form==="function"&&c.validate_form(c);if(!d.has_form_message(c.form,"error")){c.form.addClass("loading");typeof c.submit_form==="function"&&c.submit_form(c)}}},form_error:function(c,a){return d.form_message(c,a,"error")},form_message:function(c,a,f){a=b("<div class='form-msg'>").text(a).hide();b(".form-group",c).prepend(a);a.slideDown();var g=c.data("form-msg");if(!g){g={};c.data("form-msg",g)}if(g[f])g[f].push(a);else g[f]=
[a];return a},clear_form_message:function(c){var a=c.data("form-msg");if(a){b.each(a,function(f,g){b.each(g,function(h,i){i.remove()})});c.removeData("form-msg")}},has_form_message:function(c,a){var f=c.data("form-msg");if(a)return f&&f[a]&&f[a].length;return f!=null},init_mqlkey:function(c,a){c.mqlkey(a).bind("valid",function(){b(this).next(".key-status").removeClass("invalid").removeClass("loading").addClass("valid").text("valid").attr("title","Key is available")}).bind("invalid",function(f,g){b(this).next(".key-status").removeClass("valid").removeClass("loading").addClass("invalid").text("invalid").attr("title",
g)}).bind("textchange",function(){b(this).next(".key-status").removeClass("invalid").removeClass("valid").addClass("loading")})},validate_mqlkey:function(c,a){var f=c.form||c.row,g=a.next(".key-status"),h=a.val();if(h===""){f.trigger(c.event_prefix+"error","Key is required");return false}if(h===a.data("mqlkey").original)return true;if(g.is(".invalid")){f.trigger(c.event_prefix+"error",g.attr("title"));return false}else if(g.is(".loading"))return false;return true}}})(jQuery,window.freebase);
(function(b){b.widget("ui.sortable",b.ui.mouse,{widgetEventPrefix:"sort",options:{appendTo:"parent",axis:false,connectWith:false,containment:false,cursor:"auto",cursorAt:false,dropOnEmpty:true,forcePlaceholderSize:false,forceHelperSize:false,grid:false,handle:false,helper:"original",items:"> *",opacity:false,placeholder:false,revert:false,scroll:true,scrollSensitivity:20,scrollSpeed:20,scope:"default",tolerance:"intersect",zIndex:1E3},_create:function(){this.containerCache={};this.element.addClass("ui-sortable");
this.refresh();this.floating=this.items.length?/left|right/.test(this.items[0].item.css("float")):false;this.offset=this.element.offset();this._mouseInit()},destroy:function(){this.element.removeClass("ui-sortable ui-sortable-disabled").removeData("sortable").unbind(".sortable");this._mouseDestroy();for(var e=this.items.length-1;e>=0;e--)this.items[e].item.removeData("sortable-item");return this},_setOption:function(e,d){if(e==="disabled"){this.options[e]=d;this.widget()[d?"addClass":"removeClass"]("ui-sortable-disabled")}else b.Widget.prototype._setOption.apply(this,
arguments)},_mouseCapture:function(e,d){if(this.reverting)return false;if(this.options.disabled||this.options.type=="static")return false;this._refreshItems(e);var c=null,a=this;b(e.target).parents().each(function(){if(b.data(this,"sortable-item")==a){c=b(this);return false}});if(b.data(e.target,"sortable-item")==a)c=b(e.target);if(!c)return false;if(this.options.handle&&!d){var f=false;b(this.options.handle,c).find("*").andSelf().each(function(){if(this==e.target)f=true});if(!f)return false}this.currentItem=
c;this._removeCurrentsFromItems();return true},_mouseStart:function(e,d,c){d=this.options;this.currentContainer=this;this.refreshPositions();this.helper=this._createHelper(e);this._cacheHelperProportions();this._cacheMargins();this.scrollParent=this.helper.scrollParent();this.offset=this.currentItem.offset();this.offset={top:this.offset.top-this.margins.top,left:this.offset.left-this.margins.left};this.helper.css("position","absolute");this.cssPosition=this.helper.css("position");b.extend(this.offset,
{click:{left:e.pageX-this.offset.left,top:e.pageY-this.offset.top},parent:this._getParentOffset(),relative:this._getRelativeOffset()});this.originalPosition=this._generatePosition(e);this.originalPageX=e.pageX;this.originalPageY=e.pageY;d.cursorAt&&this._adjustOffsetFromHelper(d.cursorAt);this.domPosition={prev:this.currentItem.prev()[0],parent:this.currentItem.parent()[0]};this.helper[0]!=this.currentItem[0]&&this.currentItem.hide();this._createPlaceholder();d.containment&&this._setContainment();
if(d.cursor){if(b("body").css("cursor"))this._storedCursor=b("body").css("cursor");b("body").css("cursor",d.cursor)}if(d.opacity){if(this.helper.css("opacity"))this._storedOpacity=this.helper.css("opacity");this.helper.css("opacity",d.opacity)}if(d.zIndex){if(this.helper.css("zIndex"))this._storedZIndex=this.helper.css("zIndex");this.helper.css("zIndex",d.zIndex)}if(this.scrollParent[0]!=document&&this.scrollParent[0].tagName!="HTML")this.overflowOffset=this.scrollParent.offset();this._trigger("start",
e,this._uiHash());this._preserveHelperProportions||this._cacheHelperProportions();if(!c)for(c=this.containers.length-1;c>=0;c--)this.containers[c]._trigger("activate",e,this._uiHash(this));if(b.ui.ddmanager)b.ui.ddmanager.current=this;b.ui.ddmanager&&!d.dropBehaviour&&b.ui.ddmanager.prepareOffsets(this,e);this.dragging=true;this.helper.addClass("ui-sortable-helper");this._mouseDrag(e);return true},_mouseDrag:function(e){this.position=this._generatePosition(e);this.positionAbs=this._convertPositionTo("absolute");
if(!this.lastPositionAbs)this.lastPositionAbs=this.positionAbs;if(this.options.scroll){var d=this.options,c=false;if(this.scrollParent[0]!=document&&this.scrollParent[0].tagName!="HTML"){if(this.overflowOffset.top+this.scrollParent[0].offsetHeight-e.pageY<d.scrollSensitivity)this.scrollParent[0].scrollTop=c=this.scrollParent[0].scrollTop+d.scrollSpeed;else if(e.pageY-this.overflowOffset.top<d.scrollSensitivity)this.scrollParent[0].scrollTop=c=this.scrollParent[0].scrollTop-d.scrollSpeed;if(this.overflowOffset.left+
this.scrollParent[0].offsetWidth-e.pageX<d.scrollSensitivity)this.scrollParent[0].scrollLeft=c=this.scrollParent[0].scrollLeft+d.scrollSpeed;else if(e.pageX-this.overflowOffset.left<d.scrollSensitivity)this.scrollParent[0].scrollLeft=c=this.scrollParent[0].scrollLeft-d.scrollSpeed}else{if(e.pageY-b(document).scrollTop()<d.scrollSensitivity)c=b(document).scrollTop(b(document).scrollTop()-d.scrollSpeed);else if(b(window).height()-(e.pageY-b(document).scrollTop())<d.scrollSensitivity)c=b(document).scrollTop(b(document).scrollTop()+
d.scrollSpeed);if(e.pageX-b(document).scrollLeft()<d.scrollSensitivity)c=b(document).scrollLeft(b(document).scrollLeft()-d.scrollSpeed);else if(b(window).width()-(e.pageX-b(document).scrollLeft())<d.scrollSensitivity)c=b(document).scrollLeft(b(document).scrollLeft()+d.scrollSpeed)}c!==false&&b.ui.ddmanager&&!d.dropBehaviour&&b.ui.ddmanager.prepareOffsets(this,e)}this.positionAbs=this._convertPositionTo("absolute");if(!this.options.axis||this.options.axis!="y")this.helper[0].style.left=this.position.left+
"px";if(!this.options.axis||this.options.axis!="x")this.helper[0].style.top=this.position.top+"px";for(d=this.items.length-1;d>=0;d--){c=this.items[d];var a=c.item[0],f=this._intersectsWithPointer(c);if(f)if(a!=this.currentItem[0]&&this.placeholder[f==1?"next":"prev"]()[0]!=a&&!b.ui.contains(this.placeholder[0],a)&&(this.options.type=="semi-dynamic"?!b.ui.contains(this.element[0],a):true)){this.direction=f==1?"down":"up";if(this.options.tolerance=="pointer"||this._intersectsWithSides(c))this._rearrange(e,
c);else break;this._trigger("change",e,this._uiHash());break}}this._contactContainers(e);b.ui.ddmanager&&b.ui.ddmanager.drag(this,e);this._trigger("sort",e,this._uiHash());this.lastPositionAbs=this.positionAbs;return false},_mouseStop:function(e,d){if(e){b.ui.ddmanager&&!this.options.dropBehaviour&&b.ui.ddmanager.drop(this,e);if(this.options.revert){var c=this,a=c.placeholder.offset();c.reverting=true;b(this.helper).animate({left:a.left-this.offset.parent.left-c.margins.left+(this.offsetParent[0]==
document.body?0:this.offsetParent[0].scrollLeft),top:a.top-this.offset.parent.top-c.margins.top+(this.offsetParent[0]==document.body?0:this.offsetParent[0].scrollTop)},parseInt(this.options.revert,10)||500,function(){c._clear(e)})}else this._clear(e,d);return false}},cancel:function(){if(this.dragging){this._mouseUp({target:null});this.options.helper=="original"?this.currentItem.css(this._storedCSS).removeClass("ui-sortable-helper"):this.currentItem.show();for(var e=this.containers.length-1;e>=0;e--){this.containers[e]._trigger("deactivate",
null,this._uiHash(this));if(this.containers[e].containerCache.over){this.containers[e]._trigger("out",null,this._uiHash(this));this.containers[e].containerCache.over=0}}}if(this.placeholder){this.placeholder[0].parentNode&&this.placeholder[0].parentNode.removeChild(this.placeholder[0]);this.options.helper!="original"&&this.helper&&this.helper[0].parentNode&&this.helper.remove();b.extend(this,{helper:null,dragging:false,reverting:false,_noFinalSort:null});this.domPosition.prev?b(this.domPosition.prev).after(this.currentItem):
b(this.domPosition.parent).prepend(this.currentItem)}return this},serialize:function(e){var d=this._getItemsAsjQuery(e&&e.connected),c=[];e=e||{};b(d).each(function(){var a=(b(e.item||this).attr(e.attribute||"id")||"").match(e.expression||/(.+)[-=_](.+)/);if(a)c.push((e.key||a[1]+"[]")+"="+(e.key&&e.expression?a[1]:a[2]))});!c.length&&e.key&&c.push(e.key+"=");return c.join("&")},toArray:function(e){var d=this._getItemsAsjQuery(e&&e.connected),c=[];e=e||{};d.each(function(){c.push(b(e.item||this).attr(e.attribute||
"id")||"")});return c},_intersectsWith:function(e){var d=this.positionAbs.left,c=d+this.helperProportions.width,a=this.positionAbs.top,f=a+this.helperProportions.height,g=e.left,h=g+e.width,i=e.top,j=i+e.height,k=this.offset.click.top,l=this.offset.click.left;return this.options.tolerance=="pointer"||this.options.forcePointerForContainers||this.options.tolerance!="pointer"&&this.helperProportions[this.floating?"width":"height"]>e[this.floating?"width":"height"]?a+k>i&&a+k<j&&d+l>g&&d+l<h:g<d+this.helperProportions.width/
2&&c-this.helperProportions.width/2<h&&i<a+this.helperProportions.height/2&&f-this.helperProportions.height/2<j},_intersectsWithPointer:function(e){var d=b.ui.isOverAxis(this.positionAbs.top+this.offset.click.top,e.top,e.height);e=b.ui.isOverAxis(this.positionAbs.left+this.offset.click.left,e.left,e.width);d=d&&e;e=this._getDragVerticalDirection();var c=this._getDragHorizontalDirection();if(!d)return false;return this.floating?c&&c=="right"||e=="down"?2:1:e&&(e=="down"?2:1)},_intersectsWithSides:function(e){var d=
b.ui.isOverAxis(this.positionAbs.top+this.offset.click.top,e.top+e.height/2,e.height);e=b.ui.isOverAxis(this.positionAbs.left+this.offset.click.left,e.left+e.width/2,e.width);var c=this._getDragVerticalDirection(),a=this._getDragHorizontalDirection();return this.floating&&a?a=="right"&&e||a=="left"&&!e:c&&(c=="down"&&d||c=="up"&&!d)},_getDragVerticalDirection:function(){var e=this.positionAbs.top-this.lastPositionAbs.top;return e!=0&&(e>0?"down":"up")},_getDragHorizontalDirection:function(){var e=
this.positionAbs.left-this.lastPositionAbs.left;return e!=0&&(e>0?"right":"left")},refresh:function(e){this._refreshItems(e);this.refreshPositions();return this},_connectWith:function(){var e=this.options;return e.connectWith.constructor==String?[e.connectWith]:e.connectWith},_getItemsAsjQuery:function(e){var d=[],c=[],a=this._connectWith();if(a&&e)for(e=a.length-1;e>=0;e--)for(var f=b(a[e]),g=f.length-1;g>=0;g--){var h=b.data(f[g],"sortable");if(h&&h!=this&&!h.options.disabled)c.push([b.isFunction(h.options.items)?
h.options.items.call(h.element):b(h.options.items,h.element).not(".ui-sortable-helper").not(".ui-sortable-placeholder"),h])}c.push([b.isFunction(this.options.items)?this.options.items.call(this.element,null,{options:this.options,item:this.currentItem}):b(this.options.items,this.element).not(".ui-sortable-helper").not(".ui-sortable-placeholder"),this]);for(e=c.length-1;e>=0;e--)c[e][0].each(function(){d.push(this)});return b(d)},_removeCurrentsFromItems:function(){for(var e=this.currentItem.find(":data(sortable-item)"),
d=0;d<this.items.length;d++)for(var c=0;c<e.length;c++)e[c]==this.items[d].item[0]&&this.items.splice(d,1)},_refreshItems:function(e){this.items=[];this.containers=[this];var d=this.items,c=[[b.isFunction(this.options.items)?this.options.items.call(this.element[0],e,{item:this.currentItem}):b(this.options.items,this.element),this]],a=this._connectWith();if(a)for(var f=a.length-1;f>=0;f--)for(var g=b(a[f]),h=g.length-1;h>=0;h--){var i=b.data(g[h],"sortable");if(i&&i!=this&&!i.options.disabled){c.push([b.isFunction(i.options.items)?
i.options.items.call(i.element[0],e,{item:this.currentItem}):b(i.options.items,i.element),i]);this.containers.push(i)}}for(f=c.length-1;f>=0;f--){e=c[f][1];a=c[f][0];h=0;for(g=a.length;h<g;h++){i=b(a[h]);i.data("sortable-item",e);d.push({item:i,instance:e,width:0,height:0,left:0,top:0})}}},refreshPositions:function(e){if(this.offsetParent&&this.helper)this.offset.parent=this._getParentOffset();for(var d=this.items.length-1;d>=0;d--){var c=this.items[d],a=this.options.toleranceElement?b(this.options.toleranceElement,
c.item):c.item;if(!e){c.width=a.outerWidth();c.height=a.outerHeight()}a=a.offset();c.left=a.left;c.top=a.top}if(this.options.custom&&this.options.custom.refreshContainers)this.options.custom.refreshContainers.call(this);else for(d=this.containers.length-1;d>=0;d--){a=this.containers[d].element.offset();this.containers[d].containerCache.left=a.left;this.containers[d].containerCache.top=a.top;this.containers[d].containerCache.width=this.containers[d].element.outerWidth();this.containers[d].containerCache.height=
this.containers[d].element.outerHeight()}return this},_createPlaceholder:function(e){var d=e||this,c=d.options;if(!c.placeholder||c.placeholder.constructor==String){var a=c.placeholder;c.placeholder={element:function(){var f=b(document.createElement(d.currentItem[0].nodeName)).addClass(a||d.currentItem[0].className+" ui-sortable-placeholder").removeClass("ui-sortable-helper")[0];if(!a)f.style.visibility="hidden";return f},update:function(f,g){if(!(a&&!c.forcePlaceholderSize)){g.height()||g.height(d.currentItem.innerHeight()-
parseInt(d.currentItem.css("paddingTop")||0,10)-parseInt(d.currentItem.css("paddingBottom")||0,10));g.width()||g.width(d.currentItem.innerWidth()-parseInt(d.currentItem.css("paddingLeft")||0,10)-parseInt(d.currentItem.css("paddingRight")||0,10))}}}}d.placeholder=b(c.placeholder.element.call(d.element,d.currentItem));d.currentItem.after(d.placeholder);c.placeholder.update(d,d.placeholder)},_contactContainers:function(e){for(var d=null,c=null,a=this.containers.length-1;a>=0;a--)if(!b.ui.contains(this.currentItem[0],
this.containers[a].element[0]))if(this._intersectsWith(this.containers[a].containerCache)){if(!(d&&b.ui.contains(this.containers[a].element[0],d.element[0]))){d=this.containers[a];c=a}}else if(this.containers[a].containerCache.over){this.containers[a]._trigger("out",e,this._uiHash(this));this.containers[a].containerCache.over=0}if(d)if(this.containers.length===1){this.containers[c]._trigger("over",e,this._uiHash(this));this.containers[c].containerCache.over=1}else if(this.currentContainer!=this.containers[c]){d=
1E4;a=null;for(var f=this.positionAbs[this.containers[c].floating?"left":"top"],g=this.items.length-1;g>=0;g--)if(b.ui.contains(this.containers[c].element[0],this.items[g].item[0])){var h=this.items[g][this.containers[c].floating?"left":"top"];if(Math.abs(h-f)<d){d=Math.abs(h-f);a=this.items[g]}}if(a||this.options.dropOnEmpty){this.currentContainer=this.containers[c];a?this._rearrange(e,a,null,true):this._rearrange(e,null,this.containers[c].element,true);this._trigger("change",e,this._uiHash());this.containers[c]._trigger("change",
e,this._uiHash(this));this.options.placeholder.update(this.currentContainer,this.placeholder);this.containers[c]._trigger("over",e,this._uiHash(this));this.containers[c].containerCache.over=1}}},_createHelper:function(e){var d=this.options;e=b.isFunction(d.helper)?b(d.helper.apply(this.element[0],[e,this.currentItem])):d.helper=="clone"?this.currentItem.clone():this.currentItem;e.parents("body").length||b(d.appendTo!="parent"?d.appendTo:this.currentItem[0].parentNode)[0].appendChild(e[0]);if(e[0]==
this.currentItem[0])this._storedCSS={width:this.currentItem[0].style.width,height:this.currentItem[0].style.height,position:this.currentItem.css("position"),top:this.currentItem.css("top"),left:this.currentItem.css("left")};if(e[0].style.width==""||d.forceHelperSize)e.width(this.currentItem.width());if(e[0].style.height==""||d.forceHelperSize)e.height(this.currentItem.height());return e},_adjustOffsetFromHelper:function(e){if(typeof e=="string")e=e.split(" ");if(b.isArray(e))e={left:+e[0],top:+e[1]||
0};if("left"in e)this.offset.click.left=e.left+this.margins.left;if("right"in e)this.offset.click.left=this.helperProportions.width-e.right+this.margins.left;if("top"in e)this.offset.click.top=e.top+this.margins.top;if("bottom"in e)this.offset.click.top=this.helperProportions.height-e.bottom+this.margins.top},_getParentOffset:function(){this.offsetParent=this.helper.offsetParent();var e=this.offsetParent.offset();if(this.cssPosition=="absolute"&&this.scrollParent[0]!=document&&b.ui.contains(this.scrollParent[0],
this.offsetParent[0])){e.left+=this.scrollParent.scrollLeft();e.top+=this.scrollParent.scrollTop()}if(this.offsetParent[0]==document.body||this.offsetParent[0].tagName&&this.offsetParent[0].tagName.toLowerCase()=="html"&&b.browser.msie)e={top:0,left:0};return{top:e.top+(parseInt(this.offsetParent.css("borderTopWidth"),10)||0),left:e.left+(parseInt(this.offsetParent.css("borderLeftWidth"),10)||0)}},_getRelativeOffset:function(){if(this.cssPosition=="relative"){var e=this.currentItem.position();return{top:e.top-
(parseInt(this.helper.css("top"),10)||0)+this.scrollParent.scrollTop(),left:e.left-(parseInt(this.helper.css("left"),10)||0)+this.scrollParent.scrollLeft()}}else return{top:0,left:0}},_cacheMargins:function(){this.margins={left:parseInt(this.currentItem.css("marginLeft"),10)||0,top:parseInt(this.currentItem.css("marginTop"),10)||0}},_cacheHelperProportions:function(){this.helperProportions={width:this.helper.outerWidth(),height:this.helper.outerHeight()}},_setContainment:function(){var e=this.options;
if(e.containment=="parent")e.containment=this.helper[0].parentNode;if(e.containment=="document"||e.containment=="window")this.containment=[0-this.offset.relative.left-this.offset.parent.left,0-this.offset.relative.top-this.offset.parent.top,b(e.containment=="document"?document:window).width()-this.helperProportions.width-this.margins.left,(b(e.containment=="document"?document:window).height()||document.body.parentNode.scrollHeight)-this.helperProportions.height-this.margins.top];if(!/^(document|window|parent)$/.test(e.containment)){var d=
b(e.containment)[0];e=b(e.containment).offset();var c=b(d).css("overflow")!="hidden";this.containment=[e.left+(parseInt(b(d).css("borderLeftWidth"),10)||0)+(parseInt(b(d).css("paddingLeft"),10)||0)-this.margins.left,e.top+(parseInt(b(d).css("borderTopWidth"),10)||0)+(parseInt(b(d).css("paddingTop"),10)||0)-this.margins.top,e.left+(c?Math.max(d.scrollWidth,d.offsetWidth):d.offsetWidth)-(parseInt(b(d).css("borderLeftWidth"),10)||0)-(parseInt(b(d).css("paddingRight"),10)||0)-this.helperProportions.width-
this.margins.left,e.top+(c?Math.max(d.scrollHeight,d.offsetHeight):d.offsetHeight)-(parseInt(b(d).css("borderTopWidth"),10)||0)-(parseInt(b(d).css("paddingBottom"),10)||0)-this.helperProportions.height-this.margins.top]}},_convertPositionTo:function(e,d){if(!d)d=this.position;var c=e=="absolute"?1:-1,a=this.cssPosition=="absolute"&&!(this.scrollParent[0]!=document&&b.ui.contains(this.scrollParent[0],this.offsetParent[0]))?this.offsetParent:this.scrollParent,f=/(html|body)/i.test(a[0].tagName);return{top:d.top+
this.offset.relative.top*c+this.offset.parent.top*c-(b.browser.safari&&this.cssPosition=="fixed"?0:(this.cssPosition=="fixed"?-this.scrollParent.scrollTop():f?0:a.scrollTop())*c),left:d.left+this.offset.relative.left*c+this.offset.parent.left*c-(b.browser.safari&&this.cssPosition=="fixed"?0:(this.cssPosition=="fixed"?-this.scrollParent.scrollLeft():f?0:a.scrollLeft())*c)}},_generatePosition:function(e){var d=this.options,c=this.cssPosition=="absolute"&&!(this.scrollParent[0]!=document&&b.ui.contains(this.scrollParent[0],
this.offsetParent[0]))?this.offsetParent:this.scrollParent,a=/(html|body)/i.test(c[0].tagName);if(this.cssPosition=="relative"&&!(this.scrollParent[0]!=document&&this.scrollParent[0]!=this.offsetParent[0]))this.offset.relative=this._getRelativeOffset();var f=e.pageX,g=e.pageY;if(this.originalPosition){if(this.containment){if(e.pageX-this.offset.click.left<this.containment[0])f=this.containment[0]+this.offset.click.left;if(e.pageY-this.offset.click.top<this.containment[1])g=this.containment[1]+this.offset.click.top;
if(e.pageX-this.offset.click.left>this.containment[2])f=this.containment[2]+this.offset.click.left;if(e.pageY-this.offset.click.top>this.containment[3])g=this.containment[3]+this.offset.click.top}if(d.grid){g=this.originalPageY+Math.round((g-this.originalPageY)/d.grid[1])*d.grid[1];g=this.containment?!(g-this.offset.click.top<this.containment[1]||g-this.offset.click.top>this.containment[3])?g:!(g-this.offset.click.top<this.containment[1])?g-d.grid[1]:g+d.grid[1]:g;f=this.originalPageX+Math.round((f-
this.originalPageX)/d.grid[0])*d.grid[0];f=this.containment?!(f-this.offset.click.left<this.containment[0]||f-this.offset.click.left>this.containment[2])?f:!(f-this.offset.click.left<this.containment[0])?f-d.grid[0]:f+d.grid[0]:f}}return{top:g-this.offset.click.top-this.offset.relative.top-this.offset.parent.top+(b.browser.safari&&this.cssPosition=="fixed"?0:this.cssPosition=="fixed"?-this.scrollParent.scrollTop():a?0:c.scrollTop()),left:f-this.offset.click.left-this.offset.relative.left-this.offset.parent.left+
(b.browser.safari&&this.cssPosition=="fixed"?0:this.cssPosition=="fixed"?-this.scrollParent.scrollLeft():a?0:c.scrollLeft())}},_rearrange:function(e,d,c,a){c?c[0].appendChild(this.placeholder[0]):d.item[0].parentNode.insertBefore(this.placeholder[0],this.direction=="down"?d.item[0]:d.item[0].nextSibling);this.counter=this.counter?++this.counter:1;var f=this,g=this.counter;window.setTimeout(function(){g==f.counter&&f.refreshPositions(!a)},0)},_clear:function(e,d){this.reverting=false;var c=[];!this._noFinalSort&&
this.currentItem[0].parentNode&&this.placeholder.before(this.currentItem);this._noFinalSort=null;if(this.helper[0]==this.currentItem[0]){for(var a in this._storedCSS)if(this._storedCSS[a]=="auto"||this._storedCSS[a]=="static")this._storedCSS[a]="";this.currentItem.css(this._storedCSS).removeClass("ui-sortable-helper")}else this.currentItem.show();this.fromOutside&&!d&&c.push(function(f){this._trigger("receive",f,this._uiHash(this.fromOutside))});if((this.fromOutside||this.domPosition.prev!=this.currentItem.prev().not(".ui-sortable-helper")[0]||
this.domPosition.parent!=this.currentItem.parent()[0])&&!d)c.push(function(f){this._trigger("update",f,this._uiHash())});if(!b.ui.contains(this.element[0],this.currentItem[0])){d||c.push(function(f){this._trigger("remove",f,this._uiHash())});for(a=this.containers.length-1;a>=0;a--)if(b.ui.contains(this.containers[a].element[0],this.currentItem[0])&&!d){c.push(function(f){return function(g){f._trigger("receive",g,this._uiHash(this))}}.call(this,this.containers[a]));c.push(function(f){return function(g){f._trigger("update",
g,this._uiHash(this))}}.call(this,this.containers[a]))}}for(a=this.containers.length-1;a>=0;a--){d||c.push(function(f){return function(g){f._trigger("deactivate",g,this._uiHash(this))}}.call(this,this.containers[a]));if(this.containers[a].containerCache.over){c.push(function(f){return function(g){f._trigger("out",g,this._uiHash(this))}}.call(this,this.containers[a]));this.containers[a].containerCache.over=0}}this._storedCursor&&b("body").css("cursor",this._storedCursor);this._storedOpacity&&this.helper.css("opacity",
this._storedOpacity);if(this._storedZIndex)this.helper.css("zIndex",this._storedZIndex=="auto"?"":this._storedZIndex);this.dragging=false;if(this.cancelHelperRemoval){if(!d){this._trigger("beforeStop",e,this._uiHash());for(a=0;a<c.length;a++)c[a].call(this,e);this._trigger("stop",e,this._uiHash())}return false}d||this._trigger("beforeStop",e,this._uiHash());this.placeholder[0].parentNode.removeChild(this.placeholder[0]);this.helper[0]!=this.currentItem[0]&&this.helper.remove();this.helper=null;if(!d){for(a=
0;a<c.length;a++)c[a].call(this,e);this._trigger("stop",e,this._uiHash())}this.fromOutside=false;return true},_trigger:function(){b.Widget.prototype._trigger.apply(this,arguments)===false&&this.cancel()},_uiHash:function(e){var d=e||this;return{helper:d.helper,placeholder:d.placeholder||b([]),position:d.position,originalPosition:d.originalPosition,offset:d.positionAbs,item:d.currentItem,sender:e?e.element:null}}});b.extend(b.ui.sortable,{version:"1.8.10"})})(jQuery);
(function(b,e){if(b.suggest){var d={_init:b.suggest.suggest.prototype._init,status_start:b.suggest.suggest.prototype.status_start,status_loading:b.suggest.suggest.prototype.status_loading,status_select:b.suggest.suggest.prototype.status_select,create_item:b.suggest.suggest.prototype.create_item,focus:b.suggest.suggest.prototype.focus};b.suggest("suggest_expected_type",b.extend(true,{},b.suggest.suggest.prototype,{_init:function(){var a=this;d._init.call(a);this.input.bind("remove",function(){a._destroy()});
this.ect_pane=b('<div class="ect-pane fbs-reset">');this.ect_menu=b('<div class="ect-menu-dialog"><span class="ect-menu-title">or choose from the data types below</span></div>');this.ect_list=b('<ul class="ect-menu clear">');b.each(["text","numeric","date","boolean","image","weblink","address","enumeration"],function(f,g){a.ect_list.append(a["create_ect_"+g].call(a))});this.init_unit_dialog();this.ect_pane.append(this.ect_menu);this.ect_pane.append(this.ect_unit);this.ect_menu.append(this.ect_list);
this.init_enumeration_dialog();this.ect_pane.bind("ect",function(f,g){b(".trigger",this).each(function(){var h=b(this).data("tooltip");h&&h.hide()});if(g.id==="/type/float"&&g.name==="Measurement"){a.ect_menu.hide();a.ect_enumeration.hide();a.ect_unit.show();a.status.hide()}else if(g.id==="/type/enumeration"){a.ect_menu.hide();a.ect_unit.hide();a.ect_enumeration.show();a.status.hide()}else{a.input.val(g.name).data("data.suggest",g).trigger("fb-select",g);a.hide_all()}}).bind("mouseup",function(f){f.stopPropagation()});
this.pane.append(this.ect_pane);b.suggest.suggest_expected_type.load_dimensions()},init_unit_dialog:function(){var a=this;this.ect_unit=b('<div class="ect-unit-dialog"><h2 class="ect-unit-dialog-title">Select measurement type</h2><div class="ect-unit-field"><label for="dimension">The kind of thing to measure</label><select name="dimension"></select></div><div class="ect-unit-field"><label for="dimension-unit">The unit to measure it in</label><select name="dimension-unit"></select></div><div class="ect-unit-submit"><button class="button primary">OK</button><button class="button cancel">Cancel</button></div></div>').hide();
this.ect_dimension=b("select:first",this.ect_unit);this.ect_dimension_units=b("select:eq(1)",this.ect_unit);console.log("this.ect_dimension",this.ect_dimension,"this.ect_dimension_units",this.ect_dimension_units);this.ect_dimension.change(function(){var f=b(":selected",this).data("units");if(a.ect_dimension_units.data("units")!==f){a.ect_dimension_units.empty();b.each(f,function(g,h){var i=h.name;if(h["/freebase/unit_profile/abbreviation"])i+=" ("+h["/freebase/unit_profile/abbreviation"]+")";i=b("<option>").text(i).attr("value",
h.id).data("data",h);a.ect_dimension_units.append(i);h.id==="/en/meter"&&i.attr("selected","selected")})}});b(".button.cancel",this.ect_unit).click(function(f){a.ect_menu.show();a.ect_unit.hide();a.status.show();a.input.focus().removeData("dont_hide");f.stopPropagation()});b(".button.primary",this.ect_unit).click(function(f){var g={name:"Measurment",id:"/type/float",unit:b(":selected",a.ect_dimension_units).data("data")};a.input.val(g.name).data("data.suggest",g).trigger("fb-select",g);a.input.focus().removeData("dont_hide");
a.ect_menu.show();a.ect_unit.hide();a.hide_all();f.stopPropagation()})},init_enumeration_dialog:function(){if(this.options.domain){var a=this;this.ect_enumeration=b('<div class="ect-enumeration-dialog"><h2 class="ect-enumeration-dialog-title">Enumerated Namespace</h2><div class="form-group"><div class="ect-enumeration-field" id="new-enumeration-field"><label><input type="radio" name="namespace" class="ect-enumeration-choice" checked="checked">Create new namespace</label><input type="text" class="text-input" id="ect-namespace-new-input" placeholder="key"/><span class="ect-namespace-root">'+
this.options.domain+'/<span class="ect-namespace-key"></span></span></div><div class="ect-enumeration-field" id="existing-enumeration-field" style="display:none"><label><input type="radio" class="ect-enumeration-choice" name="namespace"><span>Enter a namespace to which you have permisson</span></label><input type="text" placeholder="eg. /authority/netflix" class="text-input"/></div><a href="javascript:void(0);" class="namespace-toggle">or choose existing&hellip;</a><div class="ect-enumeration-submit"><button class="button primary">OK</button><button class="button cancel">Cancel</button></div></div></div>').hide();
b(":text",this.ect_enumeration).focus(function(){b(this).prev("label").find(":radio").attr("checked","checked")}).change(function(){e.schema.edit.clear_form_message(a.ect_enumeration)});b("#ect-namespace-new-input",this.ect_enumeration).keydown(function(){var f=null,g=b(this),h=b(".ect-namespace-key");f=setTimeout(function(){h.html(g.val())},500)});b(".namespace-toggle",this.ect_enumeration).click(function(){var f=b(this),g=b("#new-enumeration-field"),h=b("#existing-enumeration-field");if(h.is(":hidden")){g.hide();
h.show();f.html("cancel")}else{h.hide();g.show();f.html("or choose existing...")}});b(".button.cancel",this.ect_enumeration).click(function(f){a.ect_menu.show();a.ect_enumeration.hide();a.status.show();a.input.focus().removeData("dont_hide");f.stopPropagation()});b(".button.primary",this.ect_enumeration).click(function(f){e.schema.edit.clear_form_message(a.ect_enumeration);var g={name:"Enumeration",id:"/type/enumeration"},h;if(b(":radio:first",a.ect_enumeration).is(":checked"))try{var i=b(":text:first",
a.ect_enumeration),j=b.mqlkey.from(i.val());if(b.mqlkey.reserved_word(j))throw j+" is a reserved word.";else if(j.length<5)throw"Key must be 5 or more alphanumeric characters";h=a.options.domain+"/"+j}catch(k){e.schema.edit.form_error(a.ect_enumeration,k);return}else{i=b(":text:eq(1)",a.ect_enumeration);h=i.val()}if(h){console.log(h);g.enumeration=h;a.input.val(g.name).data("data.suggest",g).trigger("fb-select",g);a.input.focus().removeData("dont_hide");a.ect_menu.show();a.ect_enumeration.hide();
a.hide_all();f.stopPropagation()}else e.schema.edit.form_error(a.ect_enumeration,"Please select a namespace.")});this.ect_pane.append(this.ect_enumeration)}},status_start:function(){d.status_start.apply(this);this.ect_pane.show();if(this.ect_unit.is(":visible")||this.ect_enumeration&&this.ect_enumeration.is(":visible"))this.status.hide()},status_loading:function(){d.status_loading.apply(this);this.ect_pane.hide()},status_select:function(){d.status_select.apply(this);this.ect_pane.hide()},create_ect_text:function(){var a=
this.create_ect_item("Text");b("> a",a).after(this.create_ect_tooltip([{name:"Short Text Input",id:"/type/text"},{name:"Machine readable string",id:"/type/rawstring"}])).tooltip(this.options.tooltip_options);return a},create_ect_numeric:function(){var a=this.create_ect_item("Numeric");b("> a",a).after(this.create_ect_tooltip([{name:"Integer",id:"/type/int"},{name:"Decimal point number",id:"/type/float"},{name:"Measurement",id:"/type/float"},{name:"Dated Currency",id:"/measurement_unit/dated_money_value"},
{name:"Dated Integer",id:"/measurement_unit/dated_integer"},{name:"Dated Decimal Point Number",id:"/measurement_unit/dated_float"},{name:"Integer Range",id:"/measurement_unit/integer_range"},{name:"Decimal Point Number Range",id:"/measurement_unit/floating_point_range"}])).tooltip(this.options.tooltip_options);return a},create_ect_date:function(){var a=this.create_ect_item("Date/Time","date");b("> a",a).after(this.create_ect_tooltip([{name:"Date/Time",id:"/type/datetime"},{name:"Day of Week",id:"/time/day_of_week"},
{name:"Date of Year",id:"/time/day_of_year"},{name:"Time interval",id:"/measurement_unit/time_interval"}])).tooltip(this.options.tooltip_options);return a},create_ect_boolean:function(){var a=this.create_ect_item("Boolean");b("> a",a).data("ect",{name:"Boolean",id:"/type/boolean"}).click(function(){b(this).trigger("ect",b(this).data("ect"))});return a},create_ect_image:function(){var a=this.create_ect_item("Image");b("> a",a).data("ect",{name:"Image",id:"/common/image"}).click(function(){b(this).trigger("ect",
b(this).data("ect"))});return a},create_ect_weblink:function(){var a=this.create_ect_item("Weblink");b("> a",a).data("ect",{name:"Weblink",id:"/common/webpage"}).click(function(){b(this).trigger("ect",b(this).data("ect"))});return a},create_ect_address:function(){var a=this.create_ect_item("Address");b("> a",a).data("ect",{name:"Address",id:"/location/mailing_address"}).click(function(){b(this).trigger("ect",b(this).data("ect"))});return a},create_ect_enumeration:function(){var a=this.create_ect_item("Namespace");
b("> a",a).data("ect",{name:"Enumeration",id:"/type/enumeration"}).click(function(){b(this).trigger("ect",b(this).data("ect"))});return a},create_ect_item:function(a,f){f||(f=a.toLowerCase());var g=b('<li class="ect-menu-item">'),h=b('<a href="javascript:void(0);" class="ect-icon trigger">&nbsp;</a>');h.addClass("ect-"+f);g.append(h);g.append(document.createTextNode(a));return g},create_ect_tooltip:function(a){var f=b('<ul class="row-menu tooltip">');b.each(a,function(g,h){var i=b('<li class="row-menu-item">'),
j=b('<a href="javascript:void(0);">&nbsp;</a>').attr("title",h.id).data("ect",h).click(function(){b(this).trigger("ect",b(this).data("ect"))});j.text(h.name);i.append(j);f.append(i)});return f},create_item:function(a,f){var g=d.create_item.apply(this,[a,f]),h=a.id.split("/");h.pop();h=h.join("/");b("."+this.options.css.item_type,g).text(h);return g},focus:function(a){d.focus.apply(this,[a]);this.input.removeData("dont_hide")}}));var c=b.suggest.suggest_expected_type;b.extend(c,{defaults:b.extend(true,
{},b.suggest.suggest.defaults,{category:"expected_type",filter:"(all type:/type/type without:hidden)",css:{status:"fbs-status fbs-ect-status"},tooltip_options:{events:{def:"click,mouseout"},position:"bottom right",offset:[-10,-10],effect:"fade",delay:300,relative:true}}),set_dimensions:function(a){b(".ect-pane select[name=dimension]").each(function(){var f=b(this);if(f.data("dimensions")!==a){var g;b.each(a,function(h,i){var j=b("<option>").text(i.name).attr("value",i.id).data("units",i.units);f.append(j);
if(i.id==="/en/length")g=j});f.data("dimensions",a);if(g){g.attr("selected","selected");f.change()}}})},load_dimensions:function(){if(c.dimensions)c.set_dimensions(c.dimensions);else if(!c.load_dimensions.lock){c.load_dimensions.lock=true;e.mqlread([{id:null,name:null,type:"/measurement_unit/dimension",units:[{id:null,name:null,type:"/type/unit","/freebase/unit_profile/abbreviation":null,sort:"name"}],sort:"name"}],c.set_dimensions)}},load_dimensions_callback:function(a){if(a.code==="/api/status/ok"){c.dimensions=
a.result.sort(c.sort_by_name);b.each(c.dimensions,function(f,g){g.units.sort(c.sort_by_name)});c.set_dimensions(c.dimensions)}},sort_by_name:function(a,f){return f.name-a.name}})}else alert("$.suggest required")})(jQuery,window.freebase);
(function(b){b.suggest||alert("$.suggest required");var e={create_item:b.suggest.suggest.prototype.create_item};b.suggest("suggest_property",b.extend(true,{},b.suggest.suggest.prototype,{create_item:function(d,c){var a=e.create_item.apply(this,[d,c]),f=d.id.split("/");f.pop();f=f.join("/");b("."+this.options.css.item_type,a).text(f);return a}}));b.extend(b.suggest.suggest_property,{defaults:b.extend(true,{},b.suggest.suggest.defaults,{type:"/type/property",type_strict:"any",filter:"(all type:/type/property without:hidden)",
css:{status:"fbs-status fbs-ect-status"}})})})(jQuery);
(function(b,e){var d=e.schema.edit,c=e.schema.type.edit={init_delegate_property:function(a){b(".nav-toggle",a.row).click(function(){c.toggle_delegate_property(b(this),a);return false})},toggle_delegate_property:function(a,f){if(a.is(".current"))return false;var g=a.parents(".nav:first");b(".nav-toggle",g).removeClass("current");a.addClass("current");var h=b(".fb-property-expected-type",f.row);b("input",h).val("");h=b("input[name=unique]",f.row).removeAttr("checked");b(".form-msg",f.row).remove();
if(a.is(".nav-delegate")){b(".nav-delegate-msg",g).show();b("input[name=expected_type_input]",f.row).hide().prev(".form-label").text("Property to use");g=b("input[name=delegated]",f.row).show();b("label[for=master]",f.row).find("span").text("Delegated");h.attr("disabled","disabled");g.data("suggest_property")||g.unbind().suggest_property(e.suggest_options.delegate_property()).bind("fb-select",function(i,j){b(this).val(j.id);setTimeout(function(){c.delegate_property_begin(f,j.id)},0)}).keypress(function(i){i.keyCode===
13&&!i.isDefaultPrevented()&&f.row.trigger(f.event_prefix+"submit")}).keyup(function(i){i.keyCode===27&&f.row.trigger(f.event_prefix+"cancel")})}else{b(".nav-delegate-msg",g).hide();b("input[name=delegated]",f.row).hide();b("input[name=expected_type_input]",f.row).show().prev(".form-label").text("Expected Type");b("label[for=master]",f.row).find("span").text("Master");h.removeAttr("disabled")}b("input[name=name]",f.row).focus()},delegate_property_begin:function(a,f){a.row.addClass("loading");b.ajax({url:e.h.ajax_url("delegate_property_begin.ajax"),
data:{id:f,lang:e.lang},dataType:"json",success:function(g,h,i){if(g.code==="/api/status/error")return d.ajax_error_handler(i,a.row);g=g.result;h={id:g.expected_type,unit:g.unit};b("input[name=expected_type_input]",a.row).trigger("fb-select",h);g.unique&&b("input[name=unique]",a.row).attr("checked","checked");b(".form-msg",a.row).remove();h=b(".form-field:first",a.row);g=b(g.message);h.before(g)},error:function(g){d.ajax_error_handler(g,a.row)},complete:function(){a.row.removeClass("loading")}})},
add_property_begin:function(a,f){var g=a.parents("tr:first");b.ajax({url:e.h.ajax_url("add_property_begin.ajax"),data:{id:f,lang:e.lang},dataType:"json",success:function(h,i,j){if(h.code==="/api/status/error")return d.ajax_error_handler(j,g);h=b(h.result.html);var k={mode:"add",event_prefix:"fb.schema.type.add.property.",ajax:{url:e.h.ajax_url("add_property_submit.ajax")},init_form:c.init_property_form,validate_form:c.validate_property_form,submit_form:c.submit_property_form,table:a.parents("table:first"),
trigger:a,trigger_row:g,row:b(".edit-row",h).hide(),submit_row:b(".edit-row-submit",h).hide()};d.init_edit_form(k);c.init_delegate_property(k);k.row.bind("fb.schema.type.add.property.success",function(){var l=b("tbody:first .table-empty-column",k.table);l.length&&l.parents("tr:first").hide().prev("tr").show();c.toggle_reorder_link(k.table);b(".button.cancel",k.submit_row).text("Done");c.init_property_form(k)})},error:function(h){d.ajax_error_handler(h,g)}})},edit_property_begin:function(a,f){var g=
a.parents("tr:first");b.ajax({url:e.h.ajax_url("edit_property_begin.ajax"),data:{id:f,lang:e.lang},dataType:"json",success:function(h,i,j){if(h.code==="/api/status/error")return d.ajax_error_handler(j,g);h=b(h.result.html);var k={mode:"edit",event_prefix:"fb.schema.type.edit.property.",ajax:{url:e.h.ajax_url("edit_property_submit.ajax"),data:{id:f}},init_form:c.init_property_form,validate_form:c.validate_property_form,submit_form:c.submit_property_form,table:a.parents("table:first"),trigger:a,trigger_row:g,
row:b(".edit-row",h).hide(),submit_row:b(".edit-row-submit",h).hide()};d.init_edit_form(k);k.row.bind("fb.schema.type.edit.property.success",function(){k.trigger_row.remove();k.row.remove();k.submit_row.remove()})},error:function(h){d.ajax_error_handler(h,g)}})},init_property_form:function(a){var f=b("input[name=name]",a.row),g=b("input[name=key]",a.row),h=b("input[name=expected_type_input]",a.row),i=b("input[name=expected_type]",a.row),j=b("input[name=expected_type_new]",a.row),k=b("input[name=unit]",
a.row),l=b("input[name=enumeration]",a.row),n=b("textarea[name=description]",a.row),r=b("input[name=disambiguator]",a.row),s=b("input[name=unique]",a.row),m=b("input[name=hidden]",a.row),q=b("input[name=type]",a.row);if(a.mode==="add"){b(".nav-toggle:first",a.row).click();f.val("");g.val("");h.val("");i.val("");j.val("");k.val("");n.val("");b.each([r,s,m],function(p,o){o.is(":disabled")||o.removeAttr("checked")})}if(!a.row.data("initialized")){d.init_mqlkey(g,{source:f,namespace:q.val(),mqlread:e.mqlread,
schema:true});g=q.val().split("/");g.pop();g=g.join("/");h.suggest_expected_type(b.extend(e.suggest_options.expected_type(),{status:["Start typing to get suggestions...","Searching...","Select an item from the list:"],domain:g,suggest_new:"Create new type"})).bind("fb-select",function(p,o){if(o.unit){h.val(o.id+" ("+o.unit.name+")");i.val(o.id);j.val("");k.val(o.unit.id)}else if(o.enumeration){h.val(o.id+" ("+o.enumeration+")");i.val(o.id);j.val("");l.val(o.enumeration)}else{h.val(o.id);i.val(o.id);
j.val("");k.val("");o.id==="/type/boolean"&&b("input[name=unique]",a.row).attr("checked","checked")}}).bind("fb-textchange",function(){i.val("");j.val("");k.val("")}).bind("fb-select-new",function(p,o){j.val(b.trim(o));i.val("");k.val("")});b(":input:not(textarea)",a.row).keypress(function(p){p.keyCode===13&&!p.isDefaultPrevented()&&a.row.trigger(a.event_prefix+"submit")}).keyup(function(p){p.keyCode===27&&a.row.trigger(a.event_prefix+"cancel")});a.row.data("initialized",true)}f.focus()},submit_property_form:function(a){var f=
b(":input[name=key]",a.row);if(d.validate_mqlkey(a,f)){f={type:b(":input[name=type]",a.row).val(),name:b.trim(b("input[name=name]:visible",a.row).val()),key:f.val(),expected_type:b(":input[name=expected_type]",a.row).val(),expected_type_new:b(":input[name=expected_type_new]",a.row).val(),unit:b(":input[name=unit]",a.row).val(),enumeration:b("input[name=enumeration]",a.row).val(),description:b.trim(b("textarea[name=description]:visible",a.row).val()),disambiguator:b(":input[name=disambiguator]",a.row).is(":checked")?
1:0,unique:b(":input[name=unique]",a.row).is(":checked")?1:0,hidden:b(":input[name=hidden]",a.row).is(":checked")?1:0,deprecated:b(":input[name=deprecated]",a.row).is(":checked")?1:0,lang:e.lang};if(a.mode==="add")if(b(".nav-delegate",a.row).is(".current"))f.delegated=b(":input[name=delegated]",a.row).val();f={url:a.ajax.url,type:"POST",dataType:"json",data:b.extend(f,a.ajax.data)};f.success=a.ajax.success||function(g,h,i){if(g.code==="/api/status/error")return d.ajax_error_handler(i,a.row);var j=
b(g.result.html).addClass("new-row");a.row.before(j);j.hide();j.showRow(function(){e.schema.init_row_menu(j);b(".edit",j).show()},null,"slow");a.row.trigger(a.event_prefix+"success")};f.error=a.ajax.error||function(g){d.ajax_error_handler(g,a.row)};b.ajax(f)}else a.row.removeClass("loading")},validate_property_form:function(a){b.trim(b("input[name=name]:visible",a.row).val())===""&&a.row.trigger(a.event_prefix+"error","Name is required");var f=b("input[name=key]",a.row);d.validate_mqlkey(a,f);f=b(":input[name=expected_type]",
a.row).val();var g=b(":input[name=expected_type_new]",a.row).val();f===""&&g===""&&a.row.trigger(a.event_prefix+"error",[a.row,"Expected Type is required"])},add_included_type_begin:function(a,f){var g=a.parents("tr:first");b.ajax({url:e.h.ajax_url("add_included_type_begin.ajax"),data:{id:f,lang:e.lang},dataType:"json",success:function(h,i,j){if(h.code==="/api/status/error")return d.ajax_error_handler(j,g);h=b(h.result.html);var k={mode:"edit",event_prefix:"fb.schema.type.add.included_type.",ajax:{url:e.h.ajax_url("add_included_type_submit.ajax")},
init_form:c.init_included_type_form,validate_form:c.validate_included_type_form,submit_form:c.submit_included_type_form,table:a.parents("table:first"),trigger:a,trigger_row:g,row:b(".edit-row",h).hide(),submit_row:b(".edit-row-submit",h).hide()};d.init_edit_form(k);k.row.bind("fb.schema.type.add.included_type.success",function(){b(".button.cancel",k.submit_row).text("Done");c.init_included_type_form(k)})},error:function(h){d.ajax_error_handler(h,g)}})},init_included_type_form:function(a){var f=b("input[name=included_type_input]",
a.row).val(""),g=b("input[name=included_type]",a.row).val(""),h=b("input[name=included_type_new]",a.row).val("");if(!a.row.data("initialized")){f.suggest(b.extend(e.suggest_options.included_type(),{suggest_new:"Create new type"})).bind("fb-select",function(i,j){f.val(j.id);g.val(j.id)}).bind("fb-textchange",function(){g.val("")}).bind("fb-select-new",function(i,j){h.val(b.trim(j));g.val("")});b(":input:not(textarea)",a.row).keypress(function(i){i.keyCode===13&&!i.isDefaultPrevented()&&a.row.trigger(a.event_prefix+
"submit")}).keyup(function(i){i.keyCode===27&&a.row.trigger(a.event_prefix+"cancel")});a.row.data("initialized",true)}f.focus()},validate_included_type_form:function(a){var f=b.trim(b(":input[name=included_type]",a.row).val()),g=b(":input[name=included_type_new]",a.row).val();f===""&&g===""&&a.row.trigger(a.event_prefix+"error",[a.row,"Please choose a type to include"])},submit_included_type_form:function(a){var f={id:b(":input[name=id]",a.row).val(),included_type:b.trim(b(":input[name=included_type]",
a.row).val()),included_type_new:b(":input[name=included_type_new]",a.row).val()};b.ajax({url:a.ajax.url,type:"POST",dataType:"json",data:b.extend(f,a.ajax.data),success:function(g,h,i){if(g.code==="/api/status/error")return d.ajax_error_handler(i,a.row);h=b("<table>");h.html(g.result.html);var j=b(">thead",h);a.table.append(j);b("tr:first",j).hide().showRow(function(){b(".tbody-header",j).each(function(){b(this).data("ajax",true).click(e.schema.type.toggle);b(".edit",this).show()});a.row.trigger(a.event_prefix+
"success")},null,"slow")},error:function(g){d.ajax_error_handler(g,a.row)}})},delete_included_type_begin:function(a,f,g){var h=a.parents("tr:first");h.parents("table:first");b.ajax({url:e.h.ajax_url("delete_included_type_submit.ajax"),data:{id:f,included_type:g,lang:e.lang},type:"POST",dataType:"json",success:function(i,j,k){if(i.code==="/api/status/error")return d.ajax_error_handler(k,h);i=b(i.result.html).addClass("new-row");h.before(i);i.hide();h.parent("thead").next("tbody:first").remove();h.remove();
i.showRow()},error:function(i){d.ajax_error_handler(i,h)}})},undo_delete_included_type_begin:function(a,f,g){var h=a.parents("tr:first");h.parents("table:first");b.ajax({url:e.h.ajax_url("undo_delete_included_type_submit.ajax"),data:{id:f,included_type:g,lang:e.lang},type:"POST",dataType:"json",success:function(i,j,k){if(i.code==="/api/status/error")return d.ajax_error_handler(k,h);i=b(i.result.html);var l=b(">tr",i).addClass("new-row");j=h.parents("thead:first");j.before(i);l.hide();j.remove();l.showRow(function(){b(".tbody-header",
l).each(function(){b(this).data("ajax",true).click(e.schema.type.toggle);b(".edit",this).show()})},null,"slow")},error:function(i){d.ajax_error_handler(i,h)}})},reverse_property_begin:function(a,f,g){var h=a.parents("tr:first");b.ajax({url:e.h.ajax_url("reverse_property_begin.ajax"),data:{id:f,master:g,lang:e.lang},dataType:"json",success:function(i,j,k){if(i.code==="/api/status/error")return d.ajax_error_handler(k,h);i=b(i.result.html);var l={mode:"edit",event_prefix:"fb.schema.type.reverse.property.",
ajax:{url:e.h.ajax_url("add_property_submit.ajax"),data:{master_property:g},success:function(n,r,s){if(n.code==="/api/status/error")return d.ajax_error_handler(s,l.row);c.reverse_property_success(l,n)}},init_form:c.init_property_form,validate_form:c.validate_property_form,submit_form:c.submit_property_form,table:a.parents("table:first"),trigger:a,trigger_row:h,row:b(".edit-row",i).hide(),submit_row:b(".edit-row-submit",i).hide()};d.init_edit_form(l)},error:function(i){d.ajax_error_handler(i,h)}})},
reverse_property_success:function(a,f){var g=b(f.result.html).addClass("new-row"),h=b("#type-table table:first"),i=b("> tbody",h);i.append(g);g.hide();g.showRow(function(){e.schema.init_row_menu(g);e.schema.type.init_tooltips(g);b(".edit",g).show()},null,"slow");i=b(".table-empty-column",i);i.length&&i.parents("tr:first").hide().prev("tr").show();a.trigger_row.remove();a.row.remove();a.submit_row.remove();c.toggle_reorder_link(h)},add_instance_begin:function(a,f){var g=a.parents("tr:first");b.ajax({url:e.h.ajax_url("add_instance_begin.ajax"),
data:{id:f,lang:e.lang},dataType:"json",success:function(h,i,j){if(h.code==="/api/status/error")return d.ajax_error_handler(j,g);h=b(h.result.html);var k={mode:"add",event_prefix:"fb.schema.type.add.instance.",ajax:{url:e.h.ajax_url("add_instance_submit.ajax"),data:{type:f}},init_form:c.init_instance_form,validate_form:c.validate_instance_form,submit_form:c.submit_instance_form,table:a.parents("table:first"),trigger:a,trigger_row:g,row:b(".edit-row",h).hide(),submit_row:b(".edit-row-submit",h).hide()};
d.init_edit_form(k);k.row.bind(k.event_prefix+"success",function(){var l=b("tbody:first .table-empty-column",k.table);l.length&&l.parents("tr:first").hide().prev("tr").show();b(".button.cancel",k.submit_row).text("Done");c.init_instance_form(k)})},error:function(h){d.ajax_error_handler(h,g)}})},init_instance_form:function(a){var f=b("input[name=name]",a.row),g=b("input[name=id]",a.row);f.val("");g.val("");if(!f.data("suggest")){f.suggest(b.extend(e.suggest_options.instance("/common/topic"),{suggest_new:"Create new"})).bind("fb-select",
function(h,i){g.val(i.id)}).bind("fb-select-new",function(){g.val("")}).bind("fb-textchange",function(){g.val("")});f.keypress(function(h){h.keyCode===13&&!h.isDefaultPrevented()&&a.row.trigger(a.event_prefix+"submit")}).keyup(function(h){h.keyCode===27&&a.row.trigger(a.event_prefix+"cancel")})}f.focus()},validate_instance_form:function(a){var f=b.trim(b(":input[name=name]",a.row).val()),g=b(":input[name=id]",a.row).val();f===""&&g===""&&a.row.trigger(a.event_prefix+"error",[a.row,"Please select or create a new topic"])},
submit_instance_form:function(a){var f=b(":input[name=name]",a.row),g={name:b.trim(f.val()),id:b(":input[name=id]",a.row).val()};g={url:a.ajax.url,type:"POST",dataType:"json",data:b.extend(g,a.ajax.data),success:function(h,i,j){if(h.code==="/api/status/error")return d.ajax_error_handler(j,a.row);var k=b(h.result.html).addClass("new-row");a.row.before(k);k.hide();k.showRow(function(){e.schema.init_row_menu(k);b(".edit",k).show();f.focus()},null,"slow");a.row.trigger(a.event_prefix+"success")},error:function(h){d.ajax_error_handler(h,
a.row)}};b.ajax(g)},delete_instance_begin:function(a,f,g){var h=a.parents("tr:first");h.parents("table:first");b.ajax({url:e.h.ajax_url("delete_instance_submit.ajax"),data:{id:f,type:g},type:"POST",dataType:"json",success:function(i,j,k){if(i.code==="/api/status/error")return d.ajax_error_handler(k,h);i=b(i.result.html).addClass("new-row");h.before(i);i.hide();h.remove();i.showRow()},error:function(i){d.ajax_error_handler(i,h)}})},undo_delete_instance_begin:function(a,f,g){var h=a.parents("tr:first");
h.parents("table:first");b.ajax({url:e.h.ajax_url("undo_delete_instance_submit.ajax"),data:{id:f,type:g},type:"POST",dataType:"json",success:function(i,j,k){if(i.code==="/api/status/error")return d.ajax_error_handler(k,h);var l=b(i.result.html).addClass("new-row");h.before(l);l.hide();h.remove();l.showRow(function(){e.schema.init_row_menu(l);b(".edit",l).show()},null,"slow")},error:function(i){d.ajax_error_handler(i,h)}})},reorder_property_begin:function(a,f){b.ajax({url:e.h.ajax_url("reorder_property_begin.ajax"),
data:{id:f,lang:e.lang},dataType:"json",success:function(g){g=b(g.result.html);g={event_prefix:"fb.schema.type.reorder.property",ajax:{url:e.h.ajax_url("reorder_property_submit.ajax"),data:{id:f}},init_form:c.init_reorder_property_form,submit_form:c.submit_reorder_property_form,form:g};d.init_modal_form(g);g.form.bind(g.event_prefix+"success",function(h,i){window.location=i.location})}})},init_reorder_property_form:function(a){var f=b(".reorderable",a.form).sortable();b(".btn-mv-top",a.form).click(function(){var g=
b(this).parent(".reorderable-item");f.prepend(g)})},submit_reorder_property_form:function(a){var f=[];b("input[name=properties]",a.form).each(function(){f.push(b(this).val())});var g={id:b("input[name=type]",a.form).val(),properties:f};b.ajax({url:a.ajax.url,type:"POST",dataType:"json",data:b.extend(g,a.ajax.data),traditional:true,success:function(h,i,j){if(h.code==="/api/status/error")return d.ajax_error_handler(j,null,a.form);a.form.trigger(a.event_prefix+"success",h.result)},error:function(h){d.ajax_error_handler(h,
null,a.form)}})},toggle_reorder_link:function(a){var f=b(".reorder-link",a);b("> tbody > tr.hoverable",a).length>1?f.show():f.hide()}}})(jQuery,window.freebase);
