
/*
 * Copyright 2012, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * Additional Licenses for Third Party components can be found here:
 * http://wiki.freebase.com/wiki/Freebase_Site_License
 *
 */
/*
 
 jQuery Tools @VERSION Tooltip - UI essentials

 NO COPYRIGHTS OR LICENSES. DO WHAT YOU LIKE.

 http://flowplayer.org/tools/tooltip/

 Since: November 2008
 Date: @DATE 
*/
(function(c){c.extend({tablesorter:new (function(){function b(e,h){m(e+","+((new Date).getTime()-h.getTime())+"ms")}function m(e){typeof console!="undefined"&&typeof console.debug!="undefined"?console.log(e):alert(e)}function j(e,h){if(e.config.debug)var k="";var p=e.tBodies[0].rows;if(e.tBodies[0].rows[0]){var l=[];p=p[0].cells;for(var u=p.length,n=0;n<u;n++){var q=false;if(c.metadata&&c(h[n]).metadata()&&c(h[n]).metadata().sorter)q=a(c(h[n]).metadata().sorter);else if(e.config.headers[n]&&e.config.headers[n].sorter)q=
a(e.config.headers[n].sorter);if(!q)a:{q=p[n];for(var r=x.length,t=1;t<r;t++)if(x[t].is(c.trim(f(e.config,q)),e,q)){q=x[t];break a}q=x[0]}if(e.config.debug)k+="column:"+n+" parser:"+q.id+"\n";l.push(q)}}e.config.debug&&m(k);return l}function a(e){for(var h=x.length,k=0;k<h;k++)if(x[k].id.toLowerCase()==e.toLowerCase())return x[k];return false}function d(e){if(e.config.debug)var h=new Date;for(var k=e.tBodies[0]&&e.tBodies[0].rows.length||0,p=e.tBodies[0].rows[0]&&e.tBodies[0].rows[0].cells.length||
0,l=e.config.parsers,u={row:[],normalized:[]},n=0;n<k;++n){var q=e.tBodies[0].rows[n],r=[];u.row.push(c(q));for(var t=0;t<p;++t)r.push(l[t].format(f(e.config,q.cells[t]),e,q.cells[t]));r.push(n);u.normalized.push(r)}e.config.debug&&b("Building cache for "+k+" rows:",h);return u}function f(e,h){if(!h)return"";var k="";return k=e.textExtraction=="simple"?h.childNodes[0]&&h.childNodes[0].hasChildNodes()?h.childNodes[0].innerHTML:h.innerHTML:typeof e.textExtraction=="function"?e.textExtraction(h):c(h).text()}
function o(e,h){if(e.config.debug)var k=new Date;for(var p=h.row,l=h.normalized,u=l.length,n=l[0].length-1,q=c(e.tBodies[0]),r=[],t=0;t<u;t++){r.push(p[l[t][n]]);if(!e.config.appender)for(var F=p[l[t][n]],E=F.length,C=0;C<E;C++)q[0].appendChild(F[C])}e.config.appender&&e.config.appender(e,r);r=null;e.config.debug&&b("Rebuilt table:",k);v(e);setTimeout(function(){c(e).trigger("sortEnd")},0)}function s(e){if(e.config.debug)var h=new Date;for(var k=[],p=0;p<e.tHead.rows.length;p++)k[p]=0;$tableHeaders=
c("thead th",e);$tableHeaders.each(function(l){this.count=0;this.column=l;var u=e.config.sortInitialOrder;this.order=i=typeof u!="Number"?u.toLowerCase()=="desc"?1:0:u==1?u:0;if(!(u=c.metadata&&c(this).metadata().sorter===false?true:false))u=e.config.headers[l]&&e.config.headers[l].sorter===false?true:false;if(u)this.sortDisabled=true;this.sortDisabled||c(this).addClass(e.config.cssHeader);e.config.headerList[l]=this});if(e.config.debug){b("Built headers:",h);m($tableHeaders)}return $tableHeaders}
function v(e){for(var h=e.config.widgets,k=h.length,p=0;p<k;p++)y(h[p]).format(e)}function y(e){for(var h=z.length,k=0;k<h;k++)if(z[k].id.toLowerCase()==e.toLowerCase())return z[k]}function D(e,h){for(var k=h.length,p=0;p<k;p++)if(h[p][0]==e)return true;return false}function w(e,h,k,p){h.removeClass(p[0]).removeClass(p[1]);var l=[];h.each(function(){this.sortDisabled||(l[this.column]=c(this))});e=k.length;for(h=0;h<e;h++)l[k[h][0]].addClass(p[k[h][1]])}function A(e){if(e.config.widthFixed){var h=
c("<colgroup>");c("tr:first td",e.tBodies[0]).each(function(){h.append(c("<col>").css("width",c(this).width()))});c(e).prepend(h)}}function B(e,h,k){if(e.config.debug)var p=new Date;for(var l="var sortWrapper = function(a,b) {",u=h.length,n=0;n<u;n++){var q=h[n][0],r=h[n][1],t="e"+n;l+="var "+t+" = "+(e.config.parsers[q].type=="text"?r==0?"sortText":"sortTextDesc":r==0?"sortNumeric":"sortNumericDesc")+"(a["+q+"],b["+q+"]); ";l+="if("+t+") { return "+t+"; } ";l+="else { "}n=k.normalized[0].length-
1;l+="return a["+n+"]-b["+n+"];";for(n=0;n<u;n++)l+="}; ";l+="return 0; ";l+="}; ";eval(l);k.normalized.sort(sortWrapper);e.config.debug&&b("Sorting on "+h.toString()+" and dir "+r+" time:",p);return k}var x=[],z=[];this.defaults={cssHeader:"header",cssAsc:"headerSortUp",cssDesc:"headerSortDown",sortInitialOrder:"asc",sortMultiSortKey:"shiftKey",sortForce:null,sortAppend:null,textExtraction:"simple",parsers:{},widgets:[],widgetZebra:{css:["even","odd"]},headers:{},widthFixed:false,cancelSelection:true,
sortList:[],headerList:[],dateFormat:"us",decimal:".",debug:false};this.benchmark=b;this.construct=function(e){return this.each(function(){if(this.tHead&&this.tBodies){var h,k,p,l;this.config={};l=c.extend(this.config,c.tablesorter.defaults,e);h=c(this);k=s(this);this.config.parsers=j(this,k);p=d(this);var u=[l.cssDesc,l.cssAsc];A(this);k.click(function(n){h.trigger("sortStart");var q=h[0].tBodies[0]&&h[0].tBodies[0].rows.length||0;if(!this.sortDisabled&&q>0){c(this);q=this.column;this.order=this.count++%
2;if(n[l.sortMultiSortKey])if(D(q,l.sortList))for(n=0;n<l.sortList.length;n++){var r=l.sortList[n],t=l.headerList[r[0]];if(r[0]==q){t.count=r[1];t.count++;r[1]=t.count%2}}else l.sortList.push([q,this.order]);else{l.sortList=[];if(l.sortForce!=null){r=l.sortForce;for(n=0;n<r.length;n++)r[n][0]!=q&&l.sortList.push(r[n])}l.sortList.push([q,this.order])}setTimeout(function(){w(h[0],k,l.sortList,u);o(h[0],B(h[0],l.sortList,p))},1);return false}}).mousedown(function(){if(l.cancelSelection){this.onselectstart=
function(){return false};return false}});h.bind("update",function(){this.config.parsers=j(this,k);p=d(this)}).bind("sorton",function(n,q){c(this).trigger("sortStart");l.sortList=q;for(var r=l.sortList,t=this.config,F=r.length,E=0;E<F;E++){var C=r[E],G=t.headerList[C[0]];G.count=C[1];G.count++}w(this,k,r,u);o(this,B(this,r,p))}).bind("appendCache",function(){o(this,p)}).bind("applyWidgetId",function(n,q){y(q).format(this)}).bind("applyWidgets",function(){v(this)});if(c.metadata&&c(this).metadata()&&
c(this).metadata().sortlist)l.sortList=c(this).metadata().sortlist;l.sortList.length>0&&h.trigger("sorton",[l.sortList]);v(this)}})};this.addParser=function(e){for(var h=x.length,k=true,p=0;p<h;p++)if(x[p].id.toLowerCase()==e.id.toLowerCase())k=false;k&&x.push(e)};this.addWidget=function(e){z.push(e)};this.formatFloat=function(e){e=parseFloat(e);return isNaN(e)?0:e};this.formatInt=function(e){e=parseInt(e);return isNaN(e)?0:e};this.isDigit=function(e,h){var k="\\"+h.decimal;return RegExp("/(^[+]?0("+
k+"0+)?$)|(^([-+]?[1-9][0-9]*)$)|(^([-+]?((0?|[1-9][0-9]*)"+k+"(0*[1-9][0-9]*)))$)|(^[-+]?[1-9]+[0-9]*"+k+"0+$)/").test(c.trim(e))};this.clearTableBody=function(e){if(c.browser.msie)(function(){for(;this.firstChild;)this.removeChild(this.firstChild)}).apply(e.tBodies[0]);else e.tBodies[0].innerHTML=""}})});c.fn.extend({tablesorter:c.tablesorter.construct});var g=c.tablesorter;g.addParser({id:"text",is:function(){return true},format:function(b){return c.trim(b.toLowerCase())},type:"text"});g.addParser({id:"digit",
is:function(b,m){return c.tablesorter.isDigit(b,m.config)},format:function(b){return c.tablesorter.formatFloat(b)},type:"numeric"});g.addParser({id:"currency",is:function(b){return/^[\u00c3\u201a\u00c2\u00a3$\u00c3\u00a2\u00e2\u20ac\u0161\u00c2\u00ac?.]/.test(b)},format:function(b){return c.tablesorter.formatFloat(b.replace(new RegExp(/[^0-9.]/g),""))},type:"numeric"});g.addParser({id:"ipAddress",is:function(b){return/^\d{2,3}[\.]\d{2,3}[\.]\d{2,3}[\.]\d{2,3}$/.test(b)},format:function(b){b=b.split(".");
for(var m="",j=b.length,a=0;a<j;a++){var d=b[a];m+=d.length==2?"0"+d:d}return c.tablesorter.formatFloat(m)},type:"numeric"});g.addParser({id:"url",is:function(b){return/^(https?|ftp|file):\/\/$/.test(b)},format:function(b){return jQuery.trim(b.replace(new RegExp(/(https?|ftp|file):\/\//),""))},type:"text"});g.addParser({id:"isoDate",is:function(b){return/^\d{4}[\/-]\d{1,2}[\/-]\d{1,2}$/.test(b)},format:function(b){return c.tablesorter.formatFloat(b!=""?(new Date(b.replace(new RegExp(/-/g),"/"))).getTime():
"0")},type:"numeric"});g.addParser({id:"percent",is:function(b){return/\%$/.test(c.trim(b))},format:function(b){return c.tablesorter.formatFloat(b.replace(new RegExp(/%/g),""))},type:"numeric"});g.addParser({id:"usLongDate",is:function(b){return b.match(new RegExp(/^[A-Za-z]{3,10}\.? [0-9]{1,2}, ([0-9]{4}|'?[0-9]{2}) (([0-2]?[0-9]:[0-5][0-9])|([0-1]?[0-9]:[0-5][0-9]\s(AM|PM)))$/))},format:function(b){return c.tablesorter.formatFloat((new Date(b)).getTime())},type:"numeric"});g.addParser({id:"shortDate",
is:function(b){return/\d{1,2}[\/\-]\d{1,2}[\/\-]\d{2,4}/.test(b)},format:function(b,m){var j=m.config;b=b.replace(/\-/g,"/");if(j.dateFormat=="us")b=b.replace(/(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{4})/,"$3/$1/$2");else if(j.dateFormat=="uk")b=b.replace(/(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{4})/,"$3/$2/$1");else if(j.dateFormat=="dd/mm/yy"||j.dateFormat=="dd-mm-yy")b=b.replace(/(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{2})/,"$1/$2/$3");return c.tablesorter.formatFloat((new Date(b)).getTime())},type:"numeric"});
g.addParser({id:"time",is:function(b){return/^(([0-2]?[0-9]:[0-5][0-9])|([0-1]?[0-9]:[0-5][0-9]\s(am|pm)))$/.test(b)},format:function(b){return c.tablesorter.formatFloat((new Date("2000/01/01 "+b)).getTime())},type:"numeric"});g.addParser({id:"metadata",is:function(){return false},format:function(b,m,j){b=m.config;b=!b.parserMetadataName?"sortValue":b.parserMetadataName;return c(j).metadata()[b]},type:"numeric"});g.addWidget({id:"zebra",format:function(b){if(b.config.debug)var m=new Date;c("tr:visible",
b.tBodies[0]).filter(":even").removeClass(b.config.widgetZebra.css[1]).addClass(b.config.widgetZebra.css[0]).end().filter(":odd").removeClass(b.config.widgetZebra.css[0]).addClass(b.config.widgetZebra.css[1]);b.config.debug&&c.tablesorter.benchmark("Applying Zebra widget",m)}})})(jQuery);
(function(c){c(function(){if(c.tablesorter){var g=c("<div>");c.tablesorter.defaults.cssAsc="column-header-asc";c.tablesorter.defaults.cssDesc="column-header-desc";c.tablesorter.defaults.cssHeader="column-header";c.tablesorter.addParser({id:"datetime",is:function(){return false},format:function(b){g.html(b);return g.find("time:first").attr("datetime")},type:"text"});c.tablesorter.addParser({id:"ignoreCase",is:function(){return false},format:function(b){g.html(b);return g.text().toLowerCase()},type:"text"});
c.tablesorter.addParser({id:"string",is:function(){return false},format:function(b){g.html(b);return g.text()},type:"text"});c.tablesorter.addParser({id:"number",is:function(){return false},format:function(b){g.html(b);b=g.find(".number:first").attr("data-value");if(b==null)return Number.MAX_VALUE;return b},type:"numeric"});c(".table-sortable").each(function(){c(this).tablesorter()})}})})(jQuery);
(function(c){c.factory("collapse_module",{init:function(){var b=this;this.$column=c(this.options.column);this.modules=c(this.options.modules,this.element);this.first_module=this.modules.get(0);this.trigger=c(".trigger:first",this.first_module);this.first_section=c(".module-section",this.first_module);this.other_modules=this.modules.slice(1);this.column_offset=this.$column.css("margin-left");this.set_collapsed(this.options.collapsed);this.trigger.click(function(m){return b.toggle(m)})},set_collapsed:function(b){if(this.toggle_state=
b){this.trigger.addClass("collapsed");this.$column.css("margin-left",0);this.first_section.hide();this.other_modules.hide()}else{this.trigger.removeClass("collapsed");this.$column.css("margin-left",this.column_offset);this.first_section.show();this.other_modules.show()}},toggle:function(){var b=this;if(this.toggle_state){c.localstore("filters_collapsed",0,false);this.trigger.removeClass("collapsed");this.$column.animate({marginLeft:this.column_offset},function(){b.first_section.slideDown(function(){b.modules.removeClass("collapsed")});
b.other_modules.fadeIn()})}else{c.localstore("filters_collapsed",1,false);this.trigger.addClass("collapsed");this.other_modules.fadeOut();this.first_section.slideUp(function(){b.$column.animate({marginLeft:0});b.modules.addClass("collapsed")})}this.toggle_state=!this.toggle_state;this.options.toggle_callback&&this.options.toggle_callback.call(this.trigger,this.toggle_state);return false}});var g=c("body").is(".embed")||c.localstore("filters_collapsed");c.extend(true,c.collapse_module,{defaults:{collapsed:g===
null?false:!!g,modules:".module",column:"#main-column"}})})(jQuery);
(function(c){function g(j,a,d){var f=d.relative?j.position().top:j.offset().top,o=d.relative?j.position().left:j.offset().left,s=d.position[0];f-=a.outerHeight()-d.offset[0];o+=j.outerWidth()+d.offset[1];var v=a.outerHeight()+j.outerHeight();if(s=="center")f+=v/2;if(s=="bottom")f+=v;s=d.position[1];j=a.outerWidth()+j.outerWidth();if(s=="center")o-=j/2;if(s=="left")o-=j;return{top:f,left:o}}function b(j,a){var d=this,f=j.add(d),o,s=0,v=0,y=j.attr("title"),D=m[a.effect],w,A=j.is(":input"),B=A&&j.is(":checkbox, :radio, select, :button, :submit"),
x=j.attr("type"),z=a.events[x]||a.events[A?B?"widget":"input":"def"];if(!D)throw'Nonexistent effect "'+a.effect+'"';z=z.split(/,\s*/);if(z.length!=2)throw"Tooltip: bad events configuration for "+x;j.bind(z[0],function(e){clearTimeout(s);if(a.predelay)v=setTimeout(function(){d.show(e)},a.predelay);else d.show(e)}).bind(z[1],function(e){clearTimeout(v);if(a.delay)s=setTimeout(function(){d.hide(e)},a.delay);else d.hide(e)});if(y&&a.cancelDefault){j.removeAttr("title");j.data("title",y)}c.extend(d,{show:function(e){if(!o){if(y)o=
c(a.layout).addClass(a.tipClass).appendTo(document.body).hide().append(y);else if(a.tip)o=c(a.tip).eq(0);else{o=j.next();o.length||(o=j.parent().next())}if(!o.length)throw"Cannot find tooltip for "+j;}if(d.isShown())return d;o.stop(true,true);var h=g(j,o,a);e=e||c.Event();e.type="onBeforeShow";f.trigger(e,[h]);if(e.isDefaultPrevented())return d;h=g(j,o,a);o.css({position:"absolute",top:h.top,left:h.left});w=true;D[0].call(d,function(){e.type="onShow";w="full";f.trigger(e)});h=a.events.tooltip.split(/,\s*/);
o.bind(h[0],function(){clearTimeout(s);clearTimeout(v)});h[1]&&!j.is("input:not(:checkbox, :radio), textarea")&&o.bind(h[1],function(k){k.relatedTarget!=j[0]&&j.trigger(z[1].split(" ")[0])});return d},hide:function(e){if(!o||!d.isShown())return d;e=e||c.Event();e.type="onBeforeHide";f.trigger(e);if(!e.isDefaultPrevented()){w=false;m[a.effect][1].call(d,function(){e.type="onHide";w=false;f.trigger(e)});return d}},isShown:function(e){return e?w=="full":w},getConf:function(){return a},getTip:function(){return o},
getTrigger:function(){return j}});c.each("onHide,onBeforeShow,onShow,onBeforeHide".split(","),function(e,h){c.isFunction(a[h])&&c(d).bind(h,a[h]);d[h]=function(k){c(d).bind(h,k);return d}})}c.tools=c.tools||{version:"@VERSION"};c.tools.tooltip={conf:{effect:"toggle",fadeOutSpeed:"fast",predelay:0,delay:30,opacity:1,tip:0,position:["top","center"],offset:[0,0],relative:false,cancelDefault:true,events:{def:"mouseenter,mouseleave",input:"focus,blur",widget:"focus mouseenter,blur mouseleave",tooltip:"mouseenter,mouseleave"},
layout:"<div/>",tipClass:"tooltip"},addEffect:function(j,a,d){m[j]=[a,d]}};var m={toggle:[function(j){var a=this.getConf(),d=this.getTip();a=a.opacity;a<1&&d.css({opacity:a});d.show();j.call()},function(j){this.getTip().hide();j.call()}],fade:[function(j){var a=this.getConf();this.getTip().fadeTo(a.fadeInSpeed,a.opacity,j)},function(j){this.getTip().fadeOut(this.getConf().fadeOutSpeed,j)}]};c.fn.tooltip=function(j){var a=this.data("tooltip");if(a)return a;j=c.extend(true,{},c.tools.tooltip.conf,j);
if(typeof j.position=="string")j.position=j.position.split(/,?\s/);this.each(function(){a=new b(c(this),j);c(this).data("tooltip",a)});return j.api?a:this}})(jQuery);
(function(c,g){g.filters={init_domain_type_property_filter:function(b){c(":text[name=domain], :text[name=type], :text[name=property]",b).suggest(c.extend({scoring:"schema",format:null,mql_output:JSON.stringify([{id:null,name:null,type:{id:null,"id|=":["/type/domain","/type/type","/type/property"],limit:1}}])},g.suggest_options.any("type:/type/domain","type:/type/type","type:/type/property"))).bind("fb-select",function(m,j){var a=c(this);a.val(j.id);var d=j.type.id;if(d==="/type/domain")a.attr("name",
"domain");else if(d==="/type/type")a.attr("name","type");else d==="/type/property"&&a.attr("name","property");this.form.submit()}).parents(".filter-form").submit(function(){return false})}};c(function(){c(".filter-form :input").keypress(function(b){b.keyCode===13&&this.form.submit();return true});c(".filter-help-trigger").tooltip({events:{def:"click,mouseout"},position:"top center",effect:"fade",delay:300,offset:[-8,0]});c(".filter-form-trigger").click(function(){var b=c(this).siblings(".filter-form");
b.is(":hidden")?b.slideDown(function(){c(":text:first",b).focus()}):b.slideUp()})})})(jQuery,window.freebase);
(function(c,g,b){g.infinitescroll=function(a,d,f){this.element=g(f);this._create(a,d)};g.infinitescroll.defaults={loading:{finished:b,finishedMsg:"<em>Congratulations, you've reached the end of the internet.</em>",img:"http://www.infinite-scroll.com/loading.gif",msg:null,msgText:"<em>Loading the next set of posts...</em>",selector:null,speed:"fast",start:b},state:{isDuringAjax:false,isInvalidPage:false,isDestroyed:false,isDone:false,isPaused:false,currPage:1},callback:b,debug:false,behavior:b,binder:g(c),
nextSelector:"div.navigation a:first",navSelector:"div.navigation",contentSelector:null,extraScrollPx:150,itemSelector:"div.post",animate:false,pathParse:b,dataType:"html",appendCallback:true,bufferPx:40,errorCallback:function(){},infid:0,pixelsFromNavToBottom:b,path:b};g.infinitescroll.prototype={_binding:function(a){var d=this,f=d.options;if(f.behavior&&this["_binding_"+f.behavior]!==b)this["_binding_"+f.behavior].call(this);else{if(a!=="bind"&&a!=="unbind"){this._debug("Binding value  "+a+" not valid");
return false}a=="unbind"?this.options.binder.unbind("smartscroll.infscr."+d.options.infid):this.options.binder[a]("smartscroll.infscr."+d.options.infid,function(){d.scroll()});this._debug("Binding",a)}},_create:function(a,d){if(!this._validate(a))return false;var f=this.options=g.extend(true,{},g.infinitescroll.defaults,a),o=g(f.nextSelector).attr("href");f.contentSelector=f.contentSelector||this.element;f.loading.selector=f.loading.selector||f.contentSelector;if(o){f.path=this._determinepath(o);
f.loading.msg=g('<div id="infscr-loading"><img alt="Loading..." src="'+f.loading.img+'" /><div>'+f.loading.msgText+"</div></div>");(new Image).src=f.loading.img;f.pixelsFromNavToBottom=g(document).height()-g(f.navSelector).offset().top;f.loading.start=f.loading.start||function(){g(f.navSelector).hide();f.loading.msg.appendTo(f.loading.selector).show(f.loading.speed,function(){beginAjax(f)})};f.loading.finished=f.loading.finished||function(){f.loading.msg.fadeOut("normal")};f.callback=function(s,v){f.behavior&&
s["_callback_"+f.behavior]!==b&&s["_callback_"+f.behavior].call(g(f.contentSelector)[0],v);d&&d.call(g(f.contentSelector)[0],v)};this._setup()}else this._debug("Navigation selector not found")},_debug:function(){if(this.options.debug)return c.console&&console.log.call(console,arguments)},_determinepath:function(a){var d=this.options;if(d.behavior&&this["_determinepath_"+d.behavior]!==b)this["_determinepath_"+d.behavior].call(this,a);else{if(d.pathParse){this._debug("pathParse manual");if(typeof d.pathParse===
"function")return d.pathParse();return d.pathParse}else if(a.match(/^(.*?)\b2\b(.*?$)/))a=a.match(/^(.*?)\b2\b(.*?$)/).slice(1);else if(a.match(/^(.*?)2(.*?$)/)){if(a.match(/^(.*?page=)2(\/.*|$)/))return a=a.match(/^(.*?page=)2(\/.*|$)/).slice(1);a=a.match(/^(.*?)2(.*?$)/).slice(1)}else if(a.match(/^(.*?page=)1(\/.*|$)/))return a=a.match(/^(.*?page=)1(\/.*|$)/).slice(1);else{this._debug("Sorry, we couldn't parse your Next (Previous Posts) URL. Verify your the css selector points to the correct A tag. If you still get this error: yell, scream, and kindly ask for help at infinite-scroll.com.");
d.state.isInvalidPage=true}this._debug("determinePath",a);return a}},_error:function(a){var d=this.options;if(d.behavior&&this["_error_"+d.behavior]!==b)this["_error_"+d.behavior].call(this,a);else{if(a!=="destroy"&&a!=="end")a="unknown";this._debug("Error",a);a=="end"&&this._showdonemsg();d.state.isDone=true;d.state.currPage=1;d.state.isPaused=false;this._binding("unbind")}},_loadcallback:function(a,d){var f=this.options,o=this.options.callback,s=f.state.isDone?"done":!f.appendCallback?"no-append":
"append";if(f.behavior&&this["_loadcallback_"+f.behavior]!==b)this["_loadcallback_"+f.behavior].call(this,a,d);else{switch(s){case "done":this._showdonemsg();return false;case "no-append":if(f.dataType=="html"){d="<div>"+d+"</div>";d=g(d).find(f.itemSelector)}break;case "append":var v=a.children();if(v.length==0)return this._error("end");for(s=document.createDocumentFragment();a[0].firstChild;)s.appendChild(a[0].firstChild);this._debug("contentSelector",g(f.contentSelector)[0]);g(f.contentSelector)[0].appendChild(s);
d=v.get();break}f.loading.finished.call(g(f.contentSelector)[0],f);if(f.animate){s=g(c).scrollTop()+g("#infscr-loading").height()+f.extraScrollPx+"px";g("html,body").animate({scrollTop:s},800,function(){f.state.isDuringAjax=false})}if(!f.animate)f.state.isDuringAjax=false;o(this,d)}},_nearbottom:function(){var a=this.options,d=0+g(document).height()-a.binder.scrollTop()-g(c).height();if(a.behavior&&this["_nearbottom_"+a.behavior]!==b)this["_nearbottom_"+a.behavior].call(this);else{this._debug("math:",
d,a.pixelsFromNavToBottom);return d-a.bufferPx<a.pixelsFromNavToBottom}},_pausing:function(a){var d=this.options;if(d.behavior&&this["_pausing_"+d.behavior]!==b)this["_pausing_"+d.behavior].call(this,a);else{a!=="pause"&&a!=="resume"&&a!==null&&this._debug("Invalid argument. Toggling pause value instead");switch(a&&(a=="pause"||a=="resume")?a:"toggle"){case "pause":d.state.isPaused=true;break;case "resume":d.state.isPaused=false;break;case "toggle":d.state.isPaused=!d.state.isPaused;break}this._debug("Paused",
d.state.isPaused);return false}},_setup:function(){var a=this.options;if(a.behavior&&this["_setup_"+a.behavior]!==b)this["_setup_"+a.behavior].call(this);else{this._binding("bind");return false}},_showdonemsg:function(){var a=this.options;if(a.behavior&&this["_showdonemsg_"+a.behavior]!==b)this["_showdonemsg_"+a.behavior].call(this);else{a.loading.msg.find("img").hide().parent().find("div").html(a.loading.finishedMsg).animate({opacity:1},2E3,function(){g(this).parent().fadeOut("normal")});a.errorCallback.call(g(a.contentSelector)[0],
"done")}},_validate:function(a){for(var d in a){if(d.indexOf&&d.indexOf("Selector")>-1&&g(a[d]).length===0){this._debug("Your "+d+" found no elements.");return false}return true}},bind:function(){this._binding("bind")},destroy:function(){this.options.state.isDestroyed=true;return this._error("destroy")},pause:function(){this._pausing("pause")},resume:function(){this._pausing("resume")},retrieve:function(a){var d=this,f=d.options,o=this._determinepath(o),s,v,y,D;a=a||null;beginAjax=function(w){w.state.currPage++;
d._debug("heading into ajax",o);s=g(w.contentSelector).is("table")?g("<tbody/>"):g("<div/>");v=o.join(w.state.currPage);y=w.dataType=="html"||w.dataType=="json"?w.dataType:"html+callback";if(w.appendCallback&&w.dataType=="html")y+="+callback";switch(y){case "html+callback":d._debug("Using HTML via .load() method");s.load(v+" "+w.itemSelector,null,function(A){d._loadcallback(s,A)});break;case "html":case "json":d._debug("Using "+y.toUpperCase()+" via $.ajax() method");g.ajax({url:v,dataType:w.dataType,
complete:function(A,B){(D=typeof A.isResolved!=="undefined"?A.isResolved():B==="success"||B==="notmodified")?d._loadcallback(s,A.responseText):d._error("end")}});break}};if(f.behavior&&this["retrieve_"+f.behavior]!==b)this["retrieve_"+f.behavior].call(this,a);else{if(f.state.isDestroyed){this._debug("Instance is destroyed");return false}f.state.isDuringAjax=true;f.loading.start.call(g(f.contentSelector)[0],f)}},scroll:function(){var a=this.options,d=a.state;if(a.behavior&&this["scroll_"+a.behavior]!==
b)this["scroll_"+a.behavior].call(this);else d.isDuringAjax||d.isInvalidPage||d.isDone||d.isDestroyed||d.isPaused||this._nearbottom()&&this.retrieve()},toggle:function(){this._pausing()},unbind:function(){this._binding("unbind")},update:function(a){if(g.isPlainObject(a))this.options=g.extend(true,this.options,a)}};g.fn.infinitescroll=function(a,d){switch(typeof a){case "string":var f=Array.prototype.slice.call(arguments,1);this.each(function(){var o=g.data(this,"infinitescroll");if(!o)return false;
if(!g.isFunction(o[a])||a.charAt(0)==="_")return false;o[a].apply(o,f)});break;case "object":this.each(function(){var o=g.data(this,"infinitescroll");o?o.update(a):g.data(this,"infinitescroll",new g.infinitescroll(a,d,this))});break}return this};var m=g.event,j;m.special.smartscroll={setup:function(){g(this).bind("scroll",m.special.smartscroll.handler)},teardown:function(){g(this).unbind("scroll",m.special.smartscroll.handler)},handler:function(a,d){var f=this,o=arguments;a.type="smartscroll";j&&
clearTimeout(j);j=setTimeout(function(){g.event.handle.apply(f,o)},d==="execAsap"?0:100)}};g.fn.smartscroll=function(a){return a?this.bind("smartscroll",a):this.trigger("smartscroll",["execAsap"])}})(window,jQuery);
(function(c,g){var b=g.triples={row_hoverover:function(){var m=c(this);b.row_hoverover.timeout=setTimeout(function(){m.addClass("row-hover")},300)},row_hoverout:function(){clearTimeout(b.row_hoverover.timeout);c(this).removeClass("row-hover")},init_menus:function(m,j){j&&c(".nicemenu",m).nicemenu();c(">tr",m).hover(b.row_hoverover,b.row_hoverout)},init_linkcount:function(m,j){var a=c(">tr",m).length,d=c("[name=infinitescroll-count]");c(".number",d).attr("data-value",a).text(a);c(".more",d).toggle(!!j)},
init_infinitescroll:function(){var m=c("#infinitescroll > tbody"),j=m.attr("data-next");b.init_menus(m);b.init_linkcount(m,j);if(j){var a=c("#infinitescroll-next");m.infinitescroll({loading:{msgText:"Fetching more links",img:g.h.static_url("lib/template/img/horizontal-loader.gif")},nextSelector:"#infinitescroll-next",navSelector:"#infinitescroll-next",dataType:"json",pathParse:function(){return[a[0].href+"&"+c.param({next:m.attr("data-next")})+"&page=",""]},appendCallback:false},function(d){d=JSON.parse(d);
d=c(d.result.html);b.init_menus(d,true);var f=d.attr("data-next");m.append(c(">tr",d));m.attr("data-next",f);b.init_linkcount(m,f);m.parent("table").trigger("update");f||c(window).unbind(".infscr")});c(window).trigger("scroll")}},init:function(){b.init_menus();c(".column.nav").collapse_module({modules:".module",column:".section"});g.filters.init_domain_type_property_filter(".column.nav");c(":text[name=creator]").suggest(g.suggest_options.any("type:/type/user")).bind("fb-select",function(m,j){c(this).val(j.id).parents("form:first").submit()});
b.init_infinitescroll()}};c(b.init)})(jQuery,window.freebase);
